### ISSUE TITLE
Argument of type 'AsyncThunkAction<number, number, {}>' is not assignable to parameter of type 'AnyAction'.   Property 'type' is missing in type 'AsyncThunkAction<number, number, {}>' but required in type 'AnyAction'.  TS2345

### ISSUE THREAD

**Issue by nrayann** [reduxjs/redux-toolkit#1004]
I have a fresh install of `yarn create react-app my-app --template redux-typescript` 

The app stop working after install `aws-appsync` with `yarn add aws-appsync`

`incrementAsync` and `incrementIfOdd` could not be dispatched with the custom typed hooks

How to make these methods work with `aws-appsync` installed?

**Comment by markerikson** [comment]
First, please don't cross-post issues across repos.

It looks like `aws-appsync` still depends on `redux@^3.7.2`. This is out of date, unfortunately, and the Redux TS types changed noticeably in 4.0.  So, you're probably ending up with more than one Redux version in your application, and there's type mismatches from Redux 3.x and Redux 4.x being in the app at the same time.

Not sure what the exact solution is here, but most likely `aws-appsync` needs to depend on a newer version of Redux.  It's really an issue with that package.

**Comment by nrayann** [comment]
Thank you @markerikson
