### ISSUE TITLE
Typed try/catch axios for createAsyncThunk return response | error

### ISSUE THREAD

**Issue by kevinmamaqi** [reduxjs/redux-toolkit#1009]
I think I'm missing something from the docs. I have the following asyncThunk:

```
export const getSliderCount = createAsyncThunk("er/getSliderCount", async () => {
	try {
		const response: {data: number} = await axios({
			method: "get",
			url: "/data/v1/er/get-steps",
		});
		return response.data;
	} catch (error) {
		const err = error as AxiosError;
		return err;
	}
});
```

And the following createSlice extraReducers:

```
extraReducers: (builder) => {
    builder.addCase(getSliderCount.fulfilled, (state, action) => {
        state.sliderCount = action.payload;
    });
},
```

While doing the fulfilled action I would expect that my payload would be just number, but I get an error with the following message: **_Type 'number | AxiosError<any>' is not assignable to type 'number'.
  Type 'AxiosError<any>' is not assignable to type 'number'.ts(2322)_**

Am I missing something?

**Comment by phryneas** [comment]
When you `return` something, it becomes the `payload` of a `fulfilled` action - as we are just calling your function, we cannot know if you internally return from a catch block or something like that (and even if we could see that, we could not know your intention. You could also be returning a valid fallback value or something like that).

If you want to return an error that results in a `rejected` action, you'll have to use `return rejectWithValue(err)` like [shown here in the documentation](https://redux-toolkit.js.org/api/createAsyncThunk#handling-thunk-errors)
