### ISSUE TITLE
Redux Toolkit v1.5.1 uses immer v8 instead of v9

### ISSUE THREAD

**Issue by ReasonX7** [reduxjs/redux-toolkit#1010]
Hello. We decided to use `@reduxjs/toolkit` and `immer` in our project, but noticed that `@reduxjs/toolkit` uses `immer@8`, while the latest version is 9.0.1, which leads to the problem of two versions `immer` being installed.

I can see that `master` branch already uses `immer@9`, so maybe you could publish it, please?

**Comment by markerikson** [comment]
That's slated for release in the upcoming RTK 1.6 version:

https://github.com/reduxjs/redux-toolkit/milestone/3

We're working on pulling together the last pieces for RTK 1.6 right now. No concrete release date, but "as soon as we possibly can".

Until then, I'd suggest just consolidating on a single version of Immer in your app.
