### ISSUE TITLE
Question: Redux-persist

### ISSUE THREAD

**Issue by rwanito** [reduxjs/redux-toolkit#1021]
Hi !

You know problably redux-persist. 
A tool that allows you to persist the state in a storage.

This tool is unmaintened and I want to know if this tool is stable with redux 4.1 + and more ?
Or, is it easy to create a simple state saver like that ?
Or it it plan to import it onto redux-toolkit ?

I've triied to fork but it's a little bit heavy :| !

Thanks !

**Comment by phryneas** [comment]
I don't see any reason why there why it shouldn't work after a minor update of a peer dependency.

Also, we have [documentation on how to use it with redux-toolkit](https://redux-toolkit.js.org/usage/usage-guide#use-with-redux-persist) and don't plan to integrate it so far.
