### ISSUE TITLE
Final RTKQ alpha feedback, fixes, and tweaks

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#1023]
Gotta resolve any issues that get reported during the alpha, and apply any final changes left over from the old repo.

**Comment by mgcrea** [comment]
Can't wait to test RTK-Query in my new projects!

Minor note, in the changelog the import path is `import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/react'` when it looks like it should be `import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'`.

**Comment by phryneas** [comment]
@mgcrea  Thanks, updated it.

**Comment by markerikson** [comment]
Yeah, we need to go through and add visibility attributes to all types so we stop getting extraction warnings.

**Comment by markerikson** [comment]
Running list of merged PRs since `alpha.2` for reference:

- #1026: add export for `copyWithStructuralSharing`
- #1029: fix/default serialize query args
- #1022: export Result Definition types
- #1035: simplify `selectFromResult` usage
- #1038: fix MiddlewareArray for new build
- #1039: remove last traces of TSDX
- #1042: Docs - RTKQ - Convert codeblocks to TS & enable codeblock transpilation
- #1036: Docs - add 'Cached data' concept page
- #1034: split up middleware, add OptionalPromise, add cache entry lifecycle
- #1041: prevent badly typed `Middleware<any>` from casting `dispatch` to `any`
- #1049: Docs - add Streaming Updates page
- #1053: add a per-endpoint keepUnusedDataFor option
- #1051: remove alpha.2 deprecation fallbacks

**Comment by phryneas** [comment]
*just some minor tweaks* :laughing: 

Still missing on that list: 
* #1056 allow using skipSymbol as arg in hooks
* add a `merge` (or `mergeWithLastResult` option to endpoints)
* add a docs page w/ an example for infinite scrolling (actually, without using `merge`, that's only gonna be useful in a "streaming" context)

**Comment by bravew** [comment]
First of all, excellent functionalities for RTK query, start refactoring our codes by adopting alpha.2, can't wait the official release. 
A quick question ,Is there any way to change baseUrl after calling createApi?
In our app we allow user to change the server address which is stored in the redux state, and will be used in following REST API call. It seems that baseUrl for RTKQ can't be modified after initialization.   
Thanks!

**Comment by StefanBRas** [comment]
@bravew : phryneas mentioned on Discord that this could be done by wrapping baseQuery, as that have access to `getState`. I had a similiar usecase, where i wanted to add a projectId to the url. Here is an (untested, but hopefully working) example:

```typescript
import { fetchBaseQuery } from '@rtk-incubator/rtk-query';
import { createApi } from '@rtk-incubator/rtk-query/react';

const baseQuery = fetchBaseQuery({
  baseUrl: 'http://localhost:8000/'
});

const wrappedBaseQuery = (
  ...[args, api, extraOptions]: Parameters<typeof baseQuery>
) => {
  const partialUrl = typeof (args) === 'string' ? args : args.url
  const projectId = (api.getState() as any).auth.projectId // circular reference if as RootState 
  const url = `project/${projectId}/${partialUrl}`
  const newArgs = typeof (args) === 'string' ? url : { ...args, url }
  return baseQuery(newArgs, api, extraOptions)
}

export const api = createApi({
  baseQuery: wrappedBaseQuery,
...
```

(Note that I haven't updated to next RTK, so i'm using the old imports)

**Comment by bravew** [comment]
@StefanBRas , Thanks a lot , your code provides the last piece of our puzzle.

**Comment by markerikson** [comment]
@Shrugsy that snippet seems worth adding to "Customizing Queries"

**Comment by markerikson** [comment]
:rocket:
