### ISSUE TITLE
Typescript: createAsyncThunk only sometimes infers correct type

### ISSUE THREAD

**Issue by flexwie** [reduxjs/redux-toolkit#1025]
`createAsyncThunk` only sometimes infers a type. Take this for example:
```typescript
const updateTemplate = createAsyncThunk<
  ODataResponse<Template>,
  RawCreateRequest,
  { state: State; rejectWithValue: Error }
>("templates/updateTemplate", async (rec, { getState, rejectWithValue }) => {
  const { updateTemplate } = useTemplateService(getState);
  return handleServiceCall(updateTemplate, rejectWithValue, rec);
});

const deleteTemplate = createAsyncThunk<
  any,
  string,
  { state: State; rejectWithValue: Error }
>(
  "templates/deleteTemplateStatus",
  async (id, { getState, rejectWithValue }) => {
    const { deleteId } = useTemplateService(getState);
    return handleServiceCall(deleteId, rejectWithValue, id);
  }
);
```

The second function `deleteTemplate` works fine and has the correct type interfered, but the first one `updateTemplate` has not. Instead I get an error saying:

`'updateTemplate' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.`

Why is that? Both functions seem similar enough that I can't figure it out on my own.

**Comment by markerikson** [comment]
Sorry for the belated response. Can you post an example that shows the issue, preferably as a CodeSandbox?

**Comment by flexwie** [comment]
I can't reproduce the issue sadly so I'm assuming it has something to do with our Typescript configuration. I'm closing this issue for now and might reopen it, when I figureded out what we had wrong to let others know. Thanks for your help!
