### ISSUE TITLE
How to effectively type app actions and middleware (TS)

### ISSUE THREAD

**Issue by mtodberg** [reduxjs/redux-toolkit#1037]
I'm using redux-toolkit, but don't know how to effectively type everything.

1) Firstly, how can you extract a type for all application actions? Both those defined by `createActions` and elsewhere like the thunks from `createApi` from redux-toolkit-query, which will soon become a part of this repository. According to the documentation, the types for the app state and dispatch gets inferred from the store. This is all good. However, once in a while you need a type for all application actions, for example when typing middleware.

```ts
// In the store
export type AppState = ReturnType<typeof store.getState>
export type AppDispatch = typeof store.dispatch;
export type AppAction = ??? <-- How to obtain this?
```

```ts
// Some custom middleware
export const customMiddleware: () => Middleware<unknown, AppState, AppDispatch> = () => (
  store,
) => {
   return (next) => (action: AppAction) => { <-- This needs to be typed like this.
     next(action);
   };
```

2) Secondly, how can the `AppState` and `AppDispatch` in the above `Middleware` generics be typed when they are inferred from the state, which in turn references `customMiddleware`? This causes a circular reference.

**Comment by phryneas** [comment]
Our recommendation is that you should not have an AppAction type like this.

For `put`, use the `AppDispatch` type. 

For `take` & co, just write `take(actionCreator, (action) => { /* action is correctly typed here */ })`.
For `yield take`, use `typed-redux-saga` as, let's face it, `redux-saga`'s types are just horribly outdated.

We also recommend using type guards in our documentation, refer to
https://redux-toolkit.js.org/api/createAction#as-a-typescript-type-guard
and https://redux-toolkit.js.org/api/matching-utilities

Generally, I consider union action types as an antipattern as they are a lie to the compiler (the type is *never* complete) and can hide bugs (mimicking exhaustiveness where types are in fact not exhausted) in reducers.

For more info, https://phryneas.de/redux-typescript-no-discriminating-union
