### ISSUE TITLE
What about code splitting..?

### ISSUE THREAD

**Issue by ztaff** [reduxjs/redux-toolkit#1040]
Hi, 
first I want to express my gratitude for this project. It really made Redux easy to implement.

We are working on a React web app.
Now we see that we must do code splitting and lazy load components that are used by a minority of users.

And regarding this, is there a "Redux Toolkit way" to add slices on the fly as code get loaded ?
Or if you could point out any other way still using Redux toolkit for setting the store on app start, it would be appreciated.

**Comment by phryneas** [comment]
Since Redux Toolkit is just a small wrapper around Redux, all the "classical" ways of code splitting should still work for you. At the moment we have nothing special planned out for that.

**Comment by ztaff** [comment]
Thanks - I'll give it a try

**Comment by ztaff** [comment]
I just want to add if someone else is looking for an answer here.
I added the **injectReducer** to store as described at https://redux.js.org/recipes/code-splitting

Then when a component gets loaded and a new reducer is required, I use the following :

`const store = useStore();

    useEffect(()=>{
        if(  !store.asyncReducers["keyForNewReducer"] ){
            store.injectReducer( "testcomments", newReducer);
        }
      // from here I can now dispatch actions using the new reducer ...
    })`

Work like a charm. And soooo much less complex than plain vanilla Redux.
Many Thanks to the team, once again.
