### ISSUE TITLE
[RTK-Q] Invalidation doesn't work in injectEndpoints

### ISSUE THREAD

**Issue by tevariou** [reduxjs/redux-toolkit#1043]
## Version
`@reduxjs/toolkit": "^1.6.0-alpha.2"`

## Description
It seems there is a bug in injectEndpoints with invalidation. To illustrate this, I can provide two examples.

**Scenario 1**: invalidation is working. When `oidcLogout` is called, `apiUserRetrieve` is correctly invalidated. `invalidatesTags` is set in `enhanceEndpoints`.
```typescript
export const api = generatedApi
  .injectEndpoints({
    endpoints: (build) => ({
      oidcLogout: build.mutation({
        query: () => ({
          url: `/oidc/logout/`,
          method: "POST",
        }),
      }),
    }),
  })
  .enhanceEndpoints({
    addTagTypes: tagTypes,
    endpoints: {
      oidcLogout: {
        invalidatesTags: ["Users"],
      },
      /**
       * User
       */
      apiUserRetrieve: {
        providesTags: ["Users"],
      },
    },
  });
```

**Scenario 2**: Here `invalidatesTags` is set directly in the endpoint `oidcLogout` in `injectEndpoints`. When `oidcLogout` is called, it doesn't invalidate `apiUserRetrieve`. 
```typescript
export const api = generatedApi
  .injectEndpoints({
    endpoints: (build) => ({
      oidcLogout: build.mutation({
        query: () => ({
          url: `/oidc/logout/`,
          method: "POST",
          invalidatesTags: ["Users"],
        }),
      }),
    }),
  })
  .enhanceEndpoints({
    addTagTypes: tagTypes,
    endpoints: {
      /**
       * User
       */
      apiUserRetrieve: {
        providesTags: ["Users"],
      },
    },
  });
```

Also type checking does not perform correctly when puting `providesTags` in `injectEndpoints`

**Comment by bradharms** [comment]
What was the resolution for this? I might be having the same issue.

**Comment by bradharms** [comment]
Nevermind, the issue above was due to incorrect nesting. Whatever I'm experiencing is unrelated.
