### ISSUE TITLE
Naming discussion: cache lifecycle & request lifecycle 🚲🏚️

### ISSUE THREAD

**Issue by phryneas** [reduxjs/redux-toolkit#1050]
So I just merged #1034 and #1049 which means that RTK now supports [streaming updates](https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/usage/rtk-query/streaming-updates).

One point is still open though: Do we want those apis to have those names?

Let's go over them quickly:

| current name | description | alternatives |
| ------------- | ------------- | ------------- |
| onQuery(arg, api) | `function` that is called when the thunk for the associated endpoint (**query or mutation**) is invoked  | onInvoke, onInitiate, **onQueryStarted** |
| resultPromise | `Promise` that resolves (with data) when the thunk dispatches the `fulfilled` or rejects (with the error) on the `rejected` action  | **queryFulfilled** |
| onCacheEntryAdded(arg, api) |  `function` that is called when a new cache entry for the associated endpoint has been generated  |  |
| cleanup | `Promise` that resolves once the cache entry has been removed from the cache  | cleanupPromise, removedFromCache, removedFromCachePromise, **cacheEntryRemoved**  |
| firstValueResolved | `Promise` that resolves (with data) the first time a thunk for the current endpoint/arg dispatches a `fulfilled` action (the cache entry has now data). will reject if `cleanup` resolves first  | firstValueResolvedPromise, firstValuePromise, firstDataPromise, receivedFirstData, receivedFirstDataPromise, **cacheDataLoaded** |
| *available in both:* | |  |
| getCacheEntry | pre-bound `selector` for current store, endpoint and arg |  |
| *available in both, but only on query endpoints* | |  |
| updateCacheEntry |  pre-bound version of  `api.util.updateQueryResult` for current store, endpoint and arg | **updateCachedData** |
| api.util.updateQueryResult |  | **api.util.updateQueryData** |
| api.util.patchQueryResult |  | **api.util.patchQueryData** |
| skipSymbol |  | **skipToken** |

**Comment by markerikson** [comment]
Hmm. My thoughts:

- We've got `resultPromise`, `cleanup`, and `firstValueResolved`, which are mismatched names - one has `Promise`, one is past tense. One way or the other we should be consistent. I'd lean towards dropping `Promise` from the name, and perhaps giving them all past tense names.  Maybe something like `resultReceived`, `firstValueResolved`, and `cacheEntryRemoved` ?  `cleanup` is short and descriptive, but I think consistency here would help.
- I suppose we could put all three promises into a `.promises` field or something if we _realllly_ wanted to be clear what they are (and group them), but I'd be fine with tweaking the names and leaving them in the parent object.
- Should we change `getCacheEntry` to `selectCacheEntry` given our suggested naming scheme for selectors?

**Comment by phryneas** [comment]
I love the past tense and I certainly agree that we have to get those "in line".

Can we go a little more consistent between `resultReceived` and `firstValueResolved` as they do pretty much the same thing (apart from the "first")?
Also, not sure with the naming here. 
* `result` is what we use in `transformResult`, this would essentially be the *return value* of `transformResult`
* `data` is what we use in the cache and the return value from the selectors - but if we add a `merge(newX, oldX)` function to be part of the reducer later, this would only be the `newX` part without merging.

So, `value` has never really been used until now while `result` and `data` both have usages, but are not 1000% there. From my gut feeling though, I would go with `result` I think.


It might help to have some example usages here:

```js
const result = await resultPromise
```

```js
const result = await firstValueResolved
```

```js
try {
  await resultPromise
} catch {
  undo()
}
```


```js
resultPromise.catch(undo)
```

```js
try {
  await firstValueResolved
  // websocket init stuff here
} catch {}
await cleanup
// websocket cleanup here
```
---

I'm not so sure about the `promises` object. I first had them in a third argument, and that feld very weird as oftentimes they are the only or one of two things you want to use, so deep destructuring might be a little over the top there

---

Hmm, I like `selectCacheEntry`, but at that point it's not a selector anymore in the sense as you don't have to call it with store.getState any more, but you just call it without an argument to get the current cache entry. So calling it a "selector" might be kinda off?

---

Also, any ideas on `onQuery`?
I mean, we have `query` and `queryFn` there, so it's not sooo off, even in a mutation endpoint, but I would still maybe want to change it?
I was thinking `onInvoke` as (apart from the hooks) you start both queries and mutations by doing `dispatch(endpoint.invoke(arg))`

**Comment by markerikson** [comment]
Lenz and I hashed out the ideas and settled on the updated names highlighted in bold in the original message.
