### ISSUE TITLE
Navigate from extraReducer

### ISSUE THREAD

**Issue by Sir-hennihau** [reduxjs/redux-toolkit#1054]
Hi!

I'm trying to find out how to navigate from an `extraReducer`. Here are some code snippets and the error message. If needed, I can provide a repository that you can check out to reproduce the bug, just let me know.

Anyways:

```
// package.json
    "@react-navigation/native": "~5.8.10",
    "@react-navigation/stack": "~5.12.8",
    "react-redux": "^7.2.4",



// This is used to navigate from outside a functional component
export function navigate(name: string, params: {}) {
  navigationRef.current?.navigate(name, params);
}

// example thunk
export const fetchUsers = createAsyncThunk("users/fetchUsers", async () => {
  const response = await fetch("https://jsonplaceholder.typicode.com/todos/1");

  return response.json();
});

// example slice
export const userSlice = createSlice({
  name: "user",
  initialState: {
    value: 0,
  },
  reducers: {
    navigateFromReducer: () => {
      // navigating from this reducer works without any problem!
      navigate("NotFound", {});
    },
  },
  extraReducers: (builder) => {
    builder.addCase(fetchUsers.fulfilled, () => {
      // navigating from this thunk throws an error!
      navigate("NotFound", {});
    });
  },
  
});

const store = configureStore({
  reducer: { user: userSlice.reducer },
});

export const { navigateFromReducer } = userSlice.actions;

export default function App() {
    return (
      <Provider store={store}>
          <Navigation />
      </Provider>
    );
  }
}
```

Navigating from within the thunk throws the following error:

```
Error: You may not unsubscribe from a store listener while the reducer is executing. See https://redux.js.org/api/store#subscribelistener for more details.
```

What is the best way to invoke a navigation action after my thunk is completed?

The error message is suggesting to use a subscriber, but right now I'm still trying to figure out what the best way to navigate from a subscriber is.

Also I didn't understand why navigating from the reducer works, but not from the thunk?

**Comment by phryneas** [comment]
This would break [the third redux principle](https://redux.js.org/understanding/thinking-in-redux/three-principles#changes-are-made-with-pure-functions) - reducers have to be pure functions and are not allowed to have side effects.

In your case, the navigation leads to unmounting of the component and then to an unsubscribe in a moment that is not allowed.
It's honestly puzzling that it works from the reducer, you should never do it though.

To invoke side effects, you need to use a middleware. In your case, the easiest way to do so is probably a thunk wrapping your asyncThunk.


```js
const wrappedThunk = () => async (dispatch) => {
  await dispatch(fetchUsers())
  navigate("NotFound", {});
}
```

Also, as a general thing: please ask stuff like this on StackOverflow or in the #redux channel on Reactiflux - this issue tracker is for bugs & feature requests.
