### ISSUE TITLE
TypeScript extra reducer createAsyncThunk "No overload matches this call"

### ISSUE THREAD

**Issue by polaroidkidd** [reduxjs/redux-toolkit#1061]
I'm fairly sure I've missed something along the way but I've been tearing my hair out over this and am hoping to get some guidance on my challenge here. The relevant code is [here](http://github.com/polaroidkidd/wichtel/blob/feat/scaffolding/frontend/src/store/app/app-slice.ts#L25-L25). 

The application runs, but I'm getting a TS error and, for the life of me, I can't get to the bottom of it.

I have an async thunk, which does not accept an argument as a parameter.

```TypeScript
const initializeApplication = createAsyncThunk<
  IApiUser,
  never, // this async thunk never accepts an argument
  { state: RootState; rejectValue: IAuthErrorResponse }
>("app/initializeApplication", async (_, thunkAPI) => {
  try {
    const {
      data,
    }: { data: IApiUser } = await authApi.fetchCurrentUserDetails();
    const mappedUser = mapUserAuthResponseToUserState(data);
    thunkAPI.dispatch(userActions.setUser(mappedUser));

    return data;
  } catch (error) {
    const responseData: IAuthErrorResponse = {
      statusCode: error.status,
      error: error.statusText,
      message: "Invalid Token",
    };

    return thunkAPI.rejectWithValue(responseData);
  }
});
```
I create the application slice using the `createSlice` function like this

```TypeScript
const { reducer: appReducer, actions: appActions } = createSlice({
  name: "app",
  initialState,
  reducers: {
    initializationError: (
      state,
      action: PayloadAction<IAuthErrorResponse>
    ) => ({
      loading: false,
      initialized: true,
      error: action.payload,
    }),
  },
  extraReducers: (builder) =>
    builder
      .addCase(initializeApplication.fulfilled, () => ({
        loading: false,
        initialized: true,
        error: null as never,
      }))
      .addCase(initializeApplication.pending, () => ({
        loading: true,
        error: null as never,
        initialized: false,
      }))
      .addCase(initializeApplication.rejected, (_, action) => ({
        loading: false,
        initialized: true,
        error: action.payload,
      })),
});
```
On every `addCase` line I am getting the error

```
TS2769: No overload matches this call.   Overload 1 of 2, '(actionCreator: TypedActionCreator<string>, reducer: CaseReducer<IApplicationState, Action<string>>): ActionReducerMapBuilder<IApplicationState>', gave the following error.     Argument of type 'AsyncThunkFulfilledActionCreator<IApiUser, never>' is not assignable to parameter of type 'TypedActionCreator<string>'.       Types of parameters 'args_2' and 'args' are incompatible.         Type 'any' is not assignable to type 'never'.   Overload 2 of 2, '(type: string, reducer: CaseReducer<IApplicationState, Action<string>>): ActionReducerMapBuilder<IApplicationState>', gave the following error.     Argument of type 'AsyncThunkFulfilledActionCreator<IApiUser, never>' is not assignable to parameter of type 'string'. 
```

I'm confused as to why `initializeApplication.rejected` gives me this error, but when I use `initializeApplication.rejected.type` the error disapears.

What are the differences between using `initializeApplication.rejected`, `initializeApplication.rejected.type` and `initializeApplication.rejected.name` ?

**Comment by phryneas** [comment]
Does this resolve when you change
`never, // this async thunk never accepts an argument`
to
`void, // this async thunk never accepts an argument`
?

**Comment by polaroidkidd** [comment]
in that case it makes the entire `.addCase` block as faulty (before it was just the `initializeApplication.fulfulled` part)

The TS error is

```
TS2769: No overload matches this call.   Overload 1 of 2, '(actionCreator: AsyncThunkRejectedActionCreator<void, { state: EmptyObject & IRootState; rejectValue: IAuthErrorResponse; }>, reducer: CaseReducer<...>): ActionReducerMapBuilder<...>', gave the following error.     Argument of type '(_: WritableDraft<{ error: IAuthErrorResponse; initialized: true; loading: false; }> | WritableDraft<{ error: never; initialized: boolean; loading: boolean; }>, action: { ...; }) => { ...; }' is not assignable to parameter of type 'CaseReducer<IApplicationState, PayloadAction<IAuthErrorResponse | undefined, string, { arg: void; requestId: string; rejectedWithValue: boolean; requestStatus: "rejected"; aborted: boolean; condition: boolean; }, SerializedError>>'.       Types of parameters 'action' and 'action' are incompatible.         Type 'PayloadAction<IAuthErrorResponse | undefined, string, { arg: void; requestId: string; rejectedWithValue: boolean; requestStatus: "rejected"; aborted: boolean; condition: boolean; }, SerializedError>' is not assignable to type '{ payload: IAuthErrorResponse; type: string; }'.           Types of property 'payload' are incompatible.             Type 'IAuthErrorResponse | undefined' is not assignable to type 'IAuthErrorResponse'.               Type 'undefined' is not assignable to type 'IAuthErrorResponse'.   Overload 2 of 2, '(type: string, reducer: CaseReducer<IApplicationState, { payload: IAuthErrorResponse; type: string; }>): ActionReducerMapBuilder<IApplicationState>', gave the following error.     Argument of type 'AsyncThunkRejectedActionCreator<void, { state: EmptyObject & IRootState; rejectValue: IAuthErrorResponse; }>' is not assignable to parameter of type 'string'.
```

**Comment by polaroidkidd** [comment]
If I use your example  combined with replacing `never` with `null` in the asyncThunk I get the same TS error as in my previous comment before. If I use `never` in the async thunk, I get the same error as in the issue description. 

The error disappears when I use `initializeApplication.fulfilled.type`, but I am no sure why.

**Comment by phryneas** [comment]
Because when using `.type`, all type information is lost and your action becomes `any`, which is definitely wrong.
I would say that payload has a type there that can not go into your `error` field.
Which makes sense, because `action.payload` here is `IAuthErrorResponse | undefined` and the `undefined` is probably not allowed.

**Comment by polaroidkidd** [comment]
you were right, it was an error in my application state.

The state was defined as 

```typescript
export type IApplicationState =
  | { error: IAuthErrorResponse; initialized: true; loading: false }
  | { error: never; initialized: boolean; loading: boolean };
  ```
  
  I thought that the `thunkAPI.rejectWIthValue` would automatically assume I'd be in the state
  
  ```typescript
  ....
  | { error: IAuthErrorResponse; initialized: true; loading: false }
  ....
  ```
  because I used it in the `createAsyncThunk` options declaration, but I still had to double check that the `action.payload` wasn't undefined (or never) for typescript to accept it.
  
Is that even possible?

**Comment by phryneas** [comment]
Yes, it for some reason something in your code throws an exception, `action.payload` would be `undefined` and `action.error` would be set. Since we cannot look into your code to see if you are catching everything correctly, we have to assume that some code could somewhere throw and have to include that case as a possibility.

**Comment by polaroidkidd** [comment]
I see. Am I correct in understanding that the `action.payload` is `undefined` within the `initializeApplication.rejected` case when the asyncThunk returns early (due to missing object access for example), i.e. the thunk doesn't even reach the `thunkAPI.rejectWithValue` call (and, additionally the `action.error` would be set)?.

**Comment by polaroidkidd** [comment]
I just found https://github.com/reduxjs/redux-toolkit/issues/766#issuecomment-711415387

This makes sense. Thanks for taking the time to get to the root of it with me. Closing the issue
