### ISSUE TITLE
use creatSlice with creatApi data

### ISSUE THREAD

**Issue by vaqif14** [reduxjs/redux-toolkit#1063]
I fetched data with creatApi and want to create createSlice actions to filter fetched data. How I can make actions from data of queryState

**Comment by phryneas** [comment]
Please don't post twice in two repositories. You will get an answer when someone has time to answer.

In this case though, usage questions should not be posted in the **issue tracker**, but on the appropriate communication channes, meaning either Stackoverflow or the #redux channel of StackOverflow.
