### ISSUE TITLE
RTK-Query: The module `reactHooksModule` is not exported

### ISSUE THREAD

**Issue by mtodberg** [reduxjs/redux-toolkit#1069]
According to the documentation you can import `reactHooksModule` and customize create your own customized `createApi`. However, this module is not exported from the library.

https://rtk-query-docs.netlify.app/concepts/customizing-create-api

```ts
import {
  buildCreateApi,
  coreModule,
  reactHooksModule, <-- error (not publicly exported)
} from '@rtk-incubator/rtk-query';

export const createApi = buildCreateApi(coreModule());
```

**Comment by phryneas** [comment]
It's already up-to-date in the current integration branch, (the import is different) check these docs:

https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/usage/rtk-query/customizing-create-api

**Comment by chandlervdw** [comment]
that link is broken: usage «-» rtk-query

**Comment by phryneas** [comment]
Yeah, those links update every ten minutes while we shuffle the docs around :)
