### ISSUE TITLE
export { pending, fullfilled, reject }  from createAsyncThunk

### ISSUE THREAD

**Issue by muz3** [reduxjs/redux-toolkit#1075]
Hi the createAsyncThunk is a handy function. But I wonder if RTK will extract and export { pending, fullfilled, reject } the logic into a standalone function, then have createAsyncThunk call the fn internally rather than a closure style. 

I am using redux-saga and thunk both in a project, and would like to keep the actions using the same format. Currently I am hard copying it out into my own code.

**Comment by markerikson** [comment]
Afraid I'm not quite sure what you're asking here. Can you give more details?

**Comment by muz3** [comment]
I mean moving the code blocks into one function ( like export createAsyncAction). so my saga and thunk can use the same action format.

https://github.com/reduxjs/redux-toolkit/blob/ed125f56dd18b3dd02ea7fa709fb7a498610c947/src/createAsyncThunk.ts#L323
```
  const fulfilled = createAction(    typePrefix + '/fulfilled',    (result: Returned, requestId: string, arg: ThunkArg) =&gt; {      return {        payload: result,        meta: {          arg,          requestId,          requestStatus: 'fulfilled' as const,        },      }    }  )
  const pending = createAction(    typePrefix + '/pending',    (requestId: string, arg: ThunkArg) =&gt; {      return {        payload: undefined,        meta: {          arg,          requestId,          requestStatus: 'pending' as const,        },      }    }  )
  const rejected = createAction(    typePrefix + '/rejected',    (error: Error | null, requestId: string, arg: ThunkArg) =&gt; {      const rejectedWithValue = error instanceof RejectWithValue      const aborted = !!error &amp;&amp; error.name === 'AbortError'      const condition = !!error &amp;&amp; error.name === 'ConditionError'
      return {        payload: error instanceof RejectWithValue ? error.payload : undefined,        error: ((options &amp;&amp; options.serializeError) || miniSerializeError)(          error || 'Rejected'        ) as GetSerializedErrorType&lt;ThunkApiConfig&gt;,        meta: {          arg,          requestId,          rejectedWithValue,          requestStatus: 'rejected' as const,          aborted,          condition,        },      }    }  )

```

**Comment by markerikson** [comment]
I don't think that's possible, because those action creators are unique for every created thunk due to the prefix that's been passed in.

**Comment by phryneas** [comment]
But when you already create a thunk, you can just *use* these?

```
const myThunk = createAsyncThunk(...)


// in a saga:
yield take(myThunk.fulfilled, () => {...})
```

**Comment by muz3** [comment]
Yeah, but it also creates the actual thunk. performance wise, it is not used.


> But when you already create a thunk, you can just _use_ these?
> 
> ```
> const myThunk = createAsyncThunk(...)
> 
> 
> // in a saga:
> yield take(myThunk.fulfilled, () => {...})
> ```

**Comment by phryneas** [comment]
Performance wise it does not play any role at all.

**Comment by muz3** [comment]
@phryneas thanks for your explanation. I am going to use a wrapper to filter out the only the actions.

```
function createAsyncAction (prefix) {

  let myThunk = createAsyncThunk (..)
  return {
   fulfilled: myThunk.fulfilled
   ....
  }

}

```
