### ISSUE TITLE
defaultSerializeQueryArgs doesn't work with nested objects

### ISSUE THREAD

**Issue by mgmarlow** [reduxjs/redux-toolkit#1076]
## Issue:

When passing a deeply-nested object as the argument to an endpoint `query`, the serialized cache key doesn't retain nested keys/values.

e.g.

```js
const body = {
  filters: { color: 'blue' },
  page: { size: 12 }
}
useGetDataQuery(body)
```

Results in the following cache key:

```js
'getData({\"filter\":{},\"page\":{}})'
```

## Repro:

I have an POST endpoint configured with `createApi` that queries data (does not perform a mutation). It takes an argument, `body`, that passes a deeply-nested object into the request body.

```js
getData: builder.query({
  query: body => ({
    url: `my_data`,
    method: 'POST',
    body,
  }),
})
```

Here's a simplified example using `{ a: { b: 2 } }` as the query arguments to the endpoint. Observe that `b: 2` is lost in the serialized output:

```js
const queryArgs = { a: { b: 2 } }
JSON.stringify(queryArgs, Object.keys(queryArgs).sort())
// outputs: "{\"a\":{}}"
```

## Cause

The issue is caused by the second argument to `JSON.stringify`, `Object.keys(queryArgs).sort()`.

I can totally understand not supporting this case w/ the default serialized query, but I did find it rather difficult to troubleshoot and solve the issue by browsing the documentation. Perhaps the [serializeQueryArgs](https://rtk-query-docs.netlify.app/api/createApi#serializequeryargs) option docs can explain that nested objects aren't supported, or the [default serialization](https://github.com/reduxjs/redux-toolkit/blob/v1.6.0-alpha.2/src/query/defaultSerializeQueryArgs.ts#L11) is updated to support deeply nested queries.

I'm happy to help solve depending on which direction ya'll would like the issue to go.

**Comment by phryneas** [comment]
This is already fixed over in the integration branch #1016, you can try if the codesandbox build there works for you :)

**Comment by phryneas** [comment]
I believe this was the fixing commit: [`1fa89a5` (#1016)](https://github.com/reduxjs/redux-toolkit/pull/1016/commits/1fa89a56a22a58fafe3d7ab040c6c4a69860427f)

**Comment by mgmarlow** [comment]
Oh dang! Yep, tried that code and it worked. Thanks for the quick response!
