### ISSUE TITLE
Type bug: Query's `createApi` throws annotation error when `declaration: true` 

### ISSUE THREAD

**Issue by colemars** [reduxjs/redux-toolkit#1090]
Error:
```
The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.
```

Reproduced:

RTK example repo with tsconfig updated to set `declaration: true`
https://codesandbox.io/s/heuristic-ellis-49zgc?file=/src/services/api.ts

**Comment by colemars** [comment]
https://github.com/microsoft/TypeScript/issues/43817

may be useful

**Comment by kasparkallas** [comment]
I was going to create a new issue but it's too related:
`fakeBaseQuery` with tsconfig's `"declaration": true` causes `TS2527: The inferred type of '***' references an inaccessible 'unique symbol' type. A type annotation is necessary.` 

To reproduce, just use the `fakeBaseQuery` example from: https://redux-toolkit.js.org/rtk-query/usage-with-typescript

**Comment by phryneas** [comment]
Unless the TypeScript team finally gives a *good* explanation when & why *exactly* those errors occur and how to prevent them (apart from exporting *every single type*, which is not a valid solution) I'm sorry there is not much we can do about that.

**Comment by kasparkallas** [comment]
> Unless the TypeScript team finally gives a _good_ explanation when & why _exactly_ those errors occur and how to prevent them (apart from exporting _every single type_, which is not a valid solution) I'm sorry there is not much we can do about that.

FYI, I copy-pasted `fakeBaseQuery` implementation into my own codebase, the error(s) went away and everything compiled, including React hooks. I'll update if anything comes up.
