### ISSUE TITLE
RTK Query - Pausing Streaming Updates

### ISSUE THREAD

**Issue by GabrielViau** [reduxjs/redux-toolkit#1091]
Hi,

Thank you for the great work, I've been using `rtk-query` since the alpha-2! Is there a way to pause a streaming connection that is started from `onCacheEntryAdded`? I'm looking to be able to pause updates from a component & to be able to resume the socket connection. Looking at the documentation I can't think of another way to do this than to unmount the component and re-render it so the websocket gets re-initialized once the query is performed.

**Comment by phryneas** [comment]
Not with RTK-Query means, but nothing stops you from just having for example an event emitter on the side that you could trigger, or starting the websocket outside or RTK-querie's lifecycle and pausing & restarting in as you go, while only subscribing it from your cache lifecycle.

**Comment by GabrielViau** [comment]
Thanks for the quick response!
