### ISSUE TITLE
Using a custom Context for `useDispatch` within `reactHooksModule`

### ISSUE THREAD

**Issue by chandlervdw** [reduxjs/redux-toolkit#1096]
I'm not sure if it’s my implementation but when trying to use `buildCreateApi()`:
```
import {
  createDispatchHook
} from "react-redux";
import {
  fetchBaseQuery,
  buildCreateApi,
  coreModule,
  reactHooksModule,
  CreateApi
} from "@reduxjs/toolkit/query/react";

/* const apiBase excluded for this post */

export const ttApi = customCreateApi({
  reducerPath: "ttApi",
  baseQuery: fetchBaseQuery({baseUrl: `${apiBase}/`}),
  endpoints: ({query, mutation}) => ({
    proxyListIssues: query<ProxyListIssues, string | undefined>({
      query: () => "v2/proxy/listissues"
    })
  })
});

const storeState = {
  [ttApi.reducerPath]: ttApi.reducer
};

const store = configureStore({
  reducer: storeState,
  // Adding the api middleware enables caching, invalidation, polling,
  // and other useful features of `rtk-query`.
  middleware: getDefaultMiddleware =>
    getDefaultMiddleware().concat(ttApi.middleware)
});

export const V2ReduxContext = createContext<ReactReduxContextValue>({
  store,
  storeState
});

const useDispatch = createDispatchHook(V2ReduxContext);

const customCreateApi: CreateApi<any> = buildCreateApi(
  coreModule(),
  reactHooksModule({useDispatch})
);
```

I get a `Cannot access 'useDispatch' before initialization` error

**Comment by chandlervdw** [comment]
@phryneas thank you. We are actually successfully using two different `Provider`s as we necessarily have two separate redux stores: one that follows the default pattern and one that uses a custom context (`V2ReduxContext`). Based on the [docs for customizing the react-redux hooks](https://rtk-query-docs.netlify.app/concepts/customizing-create-api/#customizing-the-react-redux-hooks), it seems that utilizing `buildCreateApi` should be possible, utilizing this custom context.

Am I missing something with the implementation of the custom "V2" `Provider` that gives rtk-query the ability to hook into that context?

**Comment by chandlervdw** [comment]
@phryneas actually, if I remove the `buildCreateApi` and utilize just `createApi` for `ttApi`, that error goes away.

But now, within the component (see `IssuesView` at the bottom of the screenie below) that is trying to import the auto-generated `useProxyListIssuesQuery` hook, I get a new error: `could not find react-redux context value; please ensure the component is wrapped in a <Provider>`.

strangely, though, I can get at that context just fine:
```
  const context = useContext(V2ReduxContext);
  console.log(context?.store?.getState?.());
  const {data, error, isLoading} = useProxyListIssuesQuery(undefined);
  ...
```

that console.log provides the correct store state, including the `ttApi` slice, right before the error happens:
![image](https://user-images.githubusercontent.com/332278/120024986-fc723780-bfbd-11eb-9510-d8823c6676bc.png)

**Comment by phryneas** [comment]
You should initialize that context as 
````diff
-export const V2ReduxContext = createContext<ReactReduxContextValue>({
+export const V2ReduxContext = createContext<ReactReduxContextValue>(null
-  store,
-  storeState
});
`

Honestly I do not know why you are trying to put state in there at all (other to try to circumvent having to use a `Provider` which is highly problematic on it's own). Putting state in there forces a circular depencency.

Oh, and then: order your code up-down in execution order. Don't execute variables above their declaration.

**Comment by chandlervdw** [comment]
sorry, the code was a bit of a copy-and-paste from several different files. Thank you for taking the time to read through it and understand it.

We may have figured it out by removing the `context` param from our V2 `Provider`... I'm not sure about the implications at this point but I'm going to close this for now.

Thanks for your help @phryneas
