### ISSUE TITLE
[docs] Provide createAsyncThunk cancellation example for ignoring/cancelling previous fetch requests

### ISSUE THREAD

**Issue by jnachtigall** [reduxjs/redux-toolkit#1117]
Thanks for this very useful library, makes working with redux fun. Just some feedback: I had the use case that all but the latest fetch network requests should be aborted (or at least their results ignored). Could not really find a solution in https://redux-toolkit.js.org/api/createAsyncThunk#cancellation

Finally, I found one at https://stackoverflow.com/a/64697111/1129950 However, still pretty complicated (maybe more than it has to be). Although while the fetch results are now ignored (state not updated) the network request is still not cancelled as far as I noticed in the DevTools network tab (no AbortSignal).

Would be great if there was a proper go-to example for this use case at https://redux-toolkit.js.org/api/createAsyncThunk#cancellation since I think it is a common one. I think this would be a good point where the documentation could be improved.

**Comment by phryneas** [comment]
Sorry for coming around this only now.

Honestly, the value of this is pretty low. The request has been made, the server has been started processing, unless you expect a payload that is very large (significantly bigger than an image, so in the megabytes), there is just no value in cancelling an ongoing fetch.
Ignoring the result if another request is made on the other hand, much easier to achieve and has pretty much the same result. 
And for that, the pattern of keeping track of the `requestId` you are interested (be it the first or the newest request) is documented as [the first example in this paragraph](https://redux-toolkit.js.org/api/createAsyncThunk#examples)

**Comment by markerikson** [comment]
Sounds like we don't intend to add this ourselves, but if someone else really wants to file a PR, go ahead.

**Comment by jnachtigall** [comment]
@phryneas I read the first example you linked to (actually, several times even). The first example just does an early `return` instead of doing another fetch. I got stuck, because I could not find out how to cancel a previous fetch request with Redux Toolkit. I thought there would be some special way doing it with Redux Toolkit - considering that Redux Toolkit exposes AbortSignal. Then googling let me to the linked (complicated) stackoverflow answer.

Now, what you are saying is: Do not cancel (in 99%), but simply ignore the previous request(s)' response(s). That's how I do it, following the complicated approach from the stackoverflow answer. 

Anyway, maybe someone can pick this up and provide some docs for an RKT typical approach with
a) an example where previous response(s) get ignored
b) an example where previous request(s) get aborted

Thanks for RTK, very great tool!

**Comment by phryneas** [comment]
@jnachtigall it essentially boils down to this (one of thousands of ways to do it):

* you want to prevent later requests overwriting the first one: 
  * on `pending`, if `state !== "pending"`, write current `requestId` to the slice
  * on `fulfilled` exit the reducer early if `action.meta.requestId !== state.requestId`

* you want to prevent old requests overwriting the current one:
  * on `pending`,write current `requestId` to the slice
  * on `fulfilled` exit the reducer early if `action.meta.requestId !== state.requestId`


But generally, for normal requests I would recommend you to look into [RTK Query](https://redux-toolkit.js.org/rtk-query/overview) which we just released as a part of Redux Toolkit 1.6 and that will take care of all that stuff for you (by the way, it will just prevent other requests from being made if one is currently already running - except if you mark it as "mutation" in which case the return values of all those requests are handled separately from each other)

**Comment by primedev22** [comment]
This is very useful discussion. I did research for hours to find similar solution to takeLatest in saga using toolkit, and finally, I could find that this is what I am looking for.

**Comment by roycedot** [comment]
> But generally, for normal requests I would recommend you to look into [RTK Query](https://redux-toolkit.js.org/rtk-query/overview) which we just released as a part of Redux Toolkit 1.6 and that will take care of all that stuff for you (by the way, it will just prevent other requests from being made if one is currently already running

I just started using RTK Query and was curious about this - does RTK Query discard newer requests? or queue them? when a request is already running.

Likewise - is there a way to configure RTK Query to be like Saga with takeLatest() where the newest request becomes the only request whose response matters.

**Comment by markerikson** [comment]
@roycedot : if there are requests for multiple different cache keys, they'll all run.

If a request for a specific cache entry is still in progress, then it won't be re-run until the client does something that would actually force that later _after_ this request is completed (invalidating the related tag, calling `refetch()`, etc).

Do you have a specific example of something you're trying to do that RTKQ doesn't handle?

**Comment by roycedot** [comment]
> if there are requests for multiple different cache keys, they'll all run.

Thanks - that helps.

> Do you have a specific example of something you're trying to do that RTKQ doesn't handle?

My use case is making requests to a remote back-end API as a user zooms/pans on a map. The bounding box of the current map view is the changing query parameter. I only want to take the latest request (if multiple requests are made with different parameters near simultaneously) and want to use only the response from this latest request. Everything seems to be ok as implemented and initially tested with RTKQ but I wanted to double-check that the latest request's response is what ends up in the 'data' field of the query result (I'm using a API slice endpoint hook in my component).

Do I need to save and check requestId as is mentioned 2 replies above (answer in relation to using createAsyncThunk) to ensure the latest response's data is what the hook is returning?

I don't think, in practice, the user can move the map fast enough to trigger near simultaneous results (I trigger the request when the pan/zoom is complete - not as it's happening), so the more important thing, for me, is if the server responds to a request slower than a subsequent request (out-of-order response) where these two requests have different parameters.

**Comment by markerikson** [comment]
@roycedot I think you're kind of asking two different questions there.

If you keep changing the cache key for the hook, it _will_ keep triggering separate requests for each separate cache key.

But, yes, the `.data` field always reflects the value for the _current_ cache key's response.

In other words, it's not about ordering of response times.  It's about the cache key you're passing in, which is mapped to a single corresponding cache entry, always.

**Comment by roycedot** [comment]
Excellent - thanks for the clarification! Makes sense.

I suppose I was asking two questions, so instead of .data, I'm wondering about the cache in one of the questions:

```
const [myParams, setMyParams] = useState('blah1')
const { data, error, isLoading, isUninitialized } = useMyBlahQuery(myParams)

setMyParams('blah2')
```
if the server response for 'blah1' returns after the response for 'blah2', RTKQ will still place the response for 'blah1' into the cache for query 'blah1' ?

I understand I can use 'keepUnusedDataFor' to clear it out relatively quickly, but I'd rather just ignore the response of the older request ('blah1') if possible i.e. don't even add it to cache.

**Comment by markerikson** [comment]
@roycedot : 

> if the server response for 'blah1' returns after the response for 'blah2', RTKQ will still place the response for 'blah1' into the cache for query 'blah1' ?

Yes, because that's the _purpose_ of RTKQ: to cache _many_ responses, one for each requested cache key.  That's why I said it's not about "response times".  It's about "you requested data for endpoint `getPokemon`, cache key `"pikachu"` - save _that_ entry, separate from the entry for cache key `"bulbasaur"`".  Those are two separate requests, and two separate cache entries.

**Comment by roycedot** [comment]
I understand and I appreciate the background info. I wanted to take the opportunity while we were fresh on the subject to inquire if it was possible. It's not crucial, but would be a nice optimization if I was able to tap into it.

Basically, (maybe?) I'd prefer if I could make the cache key just be the endpoint instead of endpoint+parameter.

> Having that entry in the cache isn't meaningfully costing anything.

Probably, but I don't know.

1) My responses are not necessarily small - I'm getting possibly hundreds of polygons to draw. I don't want to even continue pulling the data from the server when a new request is triggered, for example. This app may be used in remote areas with slow connections. Then, I don't know what else happens when saving JSON data to cache.
2) I'd rather not have my code doing anything it doesn't need to do, as a matter of principle

Anyways, thanks for your help!

**Comment by markerikson** [comment]
@roycedot : 

> I'd prefer if I could make the cache key just be the endpoint instead of endpoint+parameter.

You can do that using the `serializeQueryArgs` option:

- https://redux-toolkit.js.org/rtk-query/api/createApi#serializequeryargs-1

That said, yeah, RTKQ doesn't offer a way to actually cancel a request.

**Comment by phryneas** [comment]
You can manually call `.initiate` and `.abort` the response, but that is usually a very weird dance. 

And if you don't do that, but merge everything together into "one cache entry" using `serializeQueryArgs`, you will get into a situation where there is already an old request for that cache entry running, so no parallel one will be started. 
I wouldn't recommend that.

My suggestion here would be to use `getRunningQueryThunk` to get the running promise of the last request and call `.abort` on it manually - but at the same time keep the cache entries separated in case something is wrong.

All that said, you might have a "too specific" use case here and writing some of your own code might be more useful than bending a generic tool to your will. So far it could even be the case that you don't need a global cache, so in this one case just querying from the component and keeping things in local component state might be enough?

**Comment by naritai** [comment]
@phryneas 

>you want to prevent old requests overwriting the current one:
>on pending,write current requestId to the slice
>on fulfilled exit the reducer early if action.meta.requestId !== state.requestId

I tried this approach and find out that it's work, but a little bit slow. 
I decided to maintain a queue and shift all the old promises with abort call on them, works much faster!

`
const [promiseQueue] = useState<CharactersPromise[]>([]);
const [promiseCount, setPromiseCount] = useState<number>(0);

  // first render fetch
  useEffect(() => {
    if (status === FetchStatus.IDLE) {
      const promise = dispatch(fetchCharacters());
      promiseQueue.push(promise as CharactersPromise);
      setPromiseCount(promiseQueue.length);
    }
  }, [status, promiseQueue, dispatch]);

  // track new requests and abort prev requests, except the last (newest)
  useEffect(() => {
    return () => {
      while (promiseQueue.length > 1) {
        const promise = promiseQueue.shift();
        if (promise) {
          promise?.abort();
        }
      }
    };
  }, [promiseCount, promiseQueue, dispatch]);

  const handleFetchCharacters = useCallback(() => {
    const promise = dispatch(fetchCharacters());
    promiseQueue.push(promise as CharactersPromise);
    setPromiseCount(promiseQueue.length);
  }, [promiseQueue, dispatch]);
`

function `handleFetchCharacters` we pass down to several components that can call them anytime.
In the end we'll resolve only the latest (newest) Promise.
