### ISSUE TITLE
Sligthly confussing `skipToken` imports

### ISSUE THREAD

**Issue by StefanBRas** [reduxjs/redux-toolkit#1121]
A minor issue with RTK query that was annoyingly hard to debug:

`skipToken` can be imported from two places:
```typescript
import { skipToken } from '@reduxjs/toolkit/dist/query'
import { skipToken } from '@reduxjs/toolkit/query/react'
```
Both of them have the exact same signature so TypeScript will say that everything is good, but if you import from `dist/query` it will not work at all.

I'm using a fairly standard VS Code setup and when i do auto-import it will only suggest the wrong one, which is how I ended up in this situation.

I will just rename it and reexport it from my api.ts file for now, but i imagine other people could end up in the same situation.

I'm using  `"@reduxjs/toolkit": "1.6.0-beta.0"` (straight from package.json so you know it's true)

**Comment by phryneas** [comment]
This should be already fixed in the next release as the new `/query/react` build will just re-export everything from `/query`.

Could you please validate that with the current CodeSandbox build available at 
https://ci.codesandbox.io/status/reduxjs/redux-toolkit/pr/1016/ ?
```
yarn add https://pkg.csb.dev/reduxjs/redux-toolkit/commit/b1e44380/@reduxjs/toolkit
npm i https://pkg.csb.dev/reduxjs/redux-toolkit/commit/b1e44380/@reduxjs/toolkit
```

**Comment by StefanBRas** [comment]
It still autocompletes to `import { skipToken } from '@reduxjs/toolkit/dist/query'` which now works.

I don't know the implications of importing from `dist` or not, so i can't say if this is as expected

**Comment by phryneas** [comment]
We don't really have any influence where this imports from, but at least it now works, so I'm gonna close this one :tada:
