### ISSUE TITLE
Type bug: RTK Query - package build fails when exporting destructured hooks

### ISSUE THREAD

**Issue by colemars** [reduxjs/redux-toolkit#1122]
Accompanying issue for https://github.com/reduxjs/redux-toolkit/pull/1116#issuecomment-853272194

Build error:
> semantic error TS2339: Property 'useGetPokemonByNameQuery' does not exist on type 'Api<BaseQuer
yFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, { getPokemonByName: QueryDefinition<string, BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, never, any, string>; }, "api", never, unique symbol | unique symbol>'.

Failing repo: https://stackblitz.com/edit/node-tgjkay?file=src%2Fapi.ts

Should be able to* build it there as well to check out the error. 

Can be avoided by just not destructuring the created api, but destructured hook exports are currently in the codegen's schema when specifying `--hooks`.

**Comment by phryneas** [comment]
On first look, that looks as if something there is invoking TypeScript < 4.1 which does not know about those hooks.

**Comment by phryneas** [comment]
I switched over to yarn and added
```json
  "resolutions": {
    "typescript": "4.3.2"
  }
```
to the package.json which ensures that there is *really only* TS 4.3.2 installed.

Makes the problem go away.

=> TSDX brings some old TypeScript version in here. Nothing we can do.

**Comment by phryneas** [comment]
Also, excerpt from the `package-lock.json`:

```json
{
    "node_modules/tsdx/node_modules/typescript": {
      "version": "3.9.9",
      "resolved": "https://registry.npmjs.org/typescript/-/typescript-3.9.9.tgz",
      "integrity": "sha512-kdMjTiekY+z/ubJCATUPlRDl39vXYiMV9iyeMuEuXZh2we6zz80uovNN2WlAxmmdE/Z/YQe+EbOEXB5RHEED3w==",
      "dev": true,
      "bin": {
        "tsc": "bin/tsc",
        "tsserver": "bin/tsserver"
      },
      "engines": {
        "node": ">=4.2.0"
      }
    },
}
```
