### ISSUE TITLE
Cannot resolve type circular dependency

### ISSUE THREAD

**Issue by alextewpin** [reduxjs/redux-toolkit#1126]
I'm quite new to `redux-toolkit` and have no idea how to solve this kind of circular dependency (code is heavily cut):

```js
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";

interface Organization {
  name: string;
}

const fetchSingleOrganization = createAsyncThunk<Organization, string, { state: RootState }>(
  "organizations/fetch-single",
  async (id, { getState }) => {
    // fetch code
  },
);

const organizationsSlice = createSlice({
  name: "organizations",
  initialState: null,
  reducers: {},
  extraReducers: (builder) =>
    builder.addCase(fetchSingleOrganization.fulfilled, () => {
      // upsert code
    }),
});

const store = configureStore({
  reducer: {
    organizations: organizationsSlice.reducer,
  },
});

type RootState = ReturnType<typeof store.getState>;
```

This results in a `Type alias 'RootState' circularly references itself.ts (2456)` error. I need a full state in a `fetchSingleOrganization` function, not just this slice. I can see the problem, but don't know how to fix it. It would probably resolved fine, if there was an option to add `extraReducers` afterwards, but I can't see one. What is a correct approach here?

**Comment by phryneas** [comment]
Assuming that slice and store creation will end up in different files in the end, the best approach to breaking the circle is to explicitly type the reducer.

```diff
- export default slice.reducer
+ export default slice.reducer as Reducer<typeof initialState>
```

**Comment by alextewpin** [comment]
Oh, that did worked out, thank you.

**Comment by markerikson** [comment]
Yeah, we really need to add this to the RTK and core TS usage guides.

**Comment by DevTGhosh** [comment]
For people who are converting their existing slice from js to ts in addition to typing the reducer export also remember to change the `extraReducers`  syntax from 
```js
extraReducers: {
  [apiThunkCall.fetching]: (state, action) {
    //Your api call
  }
}
```

to 

```js
extraReducers: builders => {
  builders.addCase(apiThunkCall.fetching, (state, action) {
     //Your api call
    }
  )
}
```

as mentioned  [here](https://redux-toolkit.js.org/usage/usage-with-typescript#type-safety-with-extrareducers) . Spent way too long trying to figure this out.

**Comment by IuriKintschev** [comment]
Sorry I know it's closed but I really don't understand how to make it work

My organization goes like this

```
store package
    |
    │   ├── slice1 file
    │   ├── slice2 file
    ├── store file
```

In my store I am exporting the type of my slices

```ts
export type RootState = ReturnType<typeof store.getState>;
```

And in my slice it is exporting as suggested, but even so I don't get the types of my state in `getState()` and when I pass the typing directly I end up importing from the store file and it accuses me of the circle error

```ts
export const getSites = createAsyncThunk<SitesResponseProps, void, { state: RootState }>(
  "sites/getSitesFromApi",
  async (_, { getState }) => {
    const { authentication } = getState();
  }
);

> OR

export const getSites = createAsyncThunk<SitesResponseProps, void>(
  "sites/getSitesFromApi",
  async (_, { getState }) => {
    const { authentication } = getState() as RootState;
  }
);

// ...


export default siteSlice.reducer as Reducer<typeof initialState>;
```
> erro:  Type alias 'RootState' circularly references itself.

**Comment by phryneas** [comment]
@IuriKintschev this is a closed thread - pretty much everything that can be said has been said. If this does not solve it for you please create a new thread and provide a full reproduction. From just reading your code without a full application context I can't see any problems here.
