### ISSUE TITLE
Custom graphql base query gives error

### ISSUE THREAD

**Issue by nenadfilipovic** [reduxjs/redux-toolkit#1129]
Hi, when using custom basequery typescript is complaining, here is the code:

This is basequery: 
```js
const graphqlBaseQuery =
  (
    { baseUrl }: { baseUrl: string } = { baseUrl: '' },
  ): BaseQueryFn<any, unknown, any> =>
  async ({ body, variables }) => {
    const result = await request(baseUrl, body, variables);
    return { data: result };
  };
```

This is whole service:

```js
export const deviceApi = createApi({
  baseQuery: graphqlBaseQuery({ baseUrl: '/api/graphql' }),
  endpoints: (builder) => ({
    devices: builder.query<DevicesQuery, DevicesQueryVariables>({
      query: nodeQuery(DevicesDocument),
    }),
  }),
});
```

And this is error: 
```
Types of property 'queryFn' are incompatible.
          Type 'undefined' is not assignable to type '(arg: any, api: BaseQueryApi, extraOptions: unknown, baseQuery: (arg: unknown) => any) => MaybePromise<QueryReturnValue<any, any, unknown>>'.ts(2322)
```

Problem is with this part: BaseQueryFn<any, unknown, any>, if I remove it everything is fine.

I am using 1.6.0-rc.1 version.

**Comment by phryneas** [comment]
I assume the error is somewhere in your `nodeQuery` function - how does that look?

**Comment by nenadfilipovic** [comment]
It copy paste from example, even if I copy paste whole code from example I get same error.

`function nodeQuery<Result, Variables>(
  document: TypedDocumentNode<Result, Variables>,
) {
  return (variables: Variables) => ({ body: document, variables });
}`

Problem is I cant find now that pull request where I find this code :(

**Comment by phryneas** [comment]
Yeah, I'm having a bit of a doozy with that one myself right now. Not 100% sure what is going on there yet.

**Comment by nenadfilipovic** [comment]
Even if I use something like this, error is still there so it is not problem with nodeQuery.

`devices: builder.query<DevicesQuery, QueryDevicesArgs>({
      query: ({ input }) => ({
        body: gql`
          query devices($id: ID!) {
            devices(input: { id: $id }) {
              name
              public
              latitude
              metadata
              longitude
              elevation
              createdAt
              updatedAt
              description
            }
          }
        `,
        variables: {
          id: input.id,
        },
      }),
    }),`

**Comment by phryneas** [comment]
Seems to be the `any` for the error generic argument.

Does this work for you?
```
import { request } from 'graphql-request';

const graphqlBaseQuery = (
  { baseUrl }: { baseUrl: string } = { baseUrl: '' }
): BaseQueryFn<{ document: string | DocumentNode; variables: any }, unknown, unknown> => async ({
  document,
  variables,
}) => {
  const result = await request(baseUrl, document, variables);
  return { data: result };
};
```

**Comment by nenadfilipovic** [comment]
It works in this case:

```
 devices: builder.query<DevicesQuery, DevicesQueryVariables>({
      query: ({ id }) => ({ document: DevicesDocument, variables: { id } }),
    }),
```

What would be your preferred way of writing mutations and queries: write them inside endpoints using gql string or write separate .graphql file?

Thanks for help.

**Comment by phryneas** [comment]
That depends entirely of you. I'm just working on the graphql-codegen, so if you now put them into `.graphql` files you'll be able to switch over easily.

**Comment by nenadfilipovic** [comment]
Im also using graphql-codegen and it can pull queries and mutations from this as it is in separate .graphql file

```
export const deviceApi = createApi({
  baseQuery: graphqlBaseQuery({ baseUrl: '/api/graphql' }),
  endpoints: (builder) => ({
    devices: builder.query<DevicesQuery, DevicesQueryVariables>({
      query: ({ id }) => ({
        document: gql`
          query devices($id: ID!) {
            devices(input: { id: $id }) {
              name
              public
              latitude
              metadata
              longitude
              elevation
              createdAt
              updatedAt
              description
            }
          }
        `,
        variables: { id },
      }),
    }),
  }),
});

```

So I dont think is really needed to write them in separate file, you just need documents define in codegen config:
`"documents": "src/**/*.{ts,tsx,graphql}",`

**Comment by phryneas** [comment]
Of course, but if your endpoint are gonna be generated by graphql-codegen you'd have to move them out at that point in time ;)

https://github.com/phryneas/graphql-code-generator/blob/5f9a2eefd81538782b791e0cc5df633935164a89/dev-test/githunt/types.rtk-query.ts#L406-L427

**Comment by phryneas** [comment]
You maybe wanna swipe https://github.com/phryneas/graphql-code-generator/blob/rtk-query/packages/plugins/typescript/rtk-query/src/graphqlRequestBaseQuery.ts

**Comment by nenadfilipovic** [comment]
Didnt know there will be plugin for rtk query, very nice. Good job.
