### ISSUE TITLE
@typescript-eslint/unbound-method error while implementing Redux-Observable Epic

### ISSUE THREAD

**Issue by jonparkdev** [reduxjs/redux-toolkit#1130]
https://redux-toolkit.js.org/api/createAction#with-redux-observable

At my company we are building a strictly typed web application using react+redux+observables.  Following the documentation linked above we ran into a small bug where the ```actionCreator.match``` within the ```filter()``` was highlighting a tslinting error described by the rule ```@typescript-eslint/unbound-method```

Investigating the typed interface:  

```
declare interface BaseActionCreator<P, T extends string, M = never, E = never> {
    type: T;
    match(action: Action<unknown>): action is PayloadAction<P, T, M, E>;
}
```

```match``` is typed as a "class member function" which I believe is causing the error. 

If the issue is approved, I can send a PR with the solution of typing  ```match``` as a function valued property instead:

```
 match: (action: Action<unknown>) => action is PayloadAction<P, T, M, E>;
```

**Comment by phryneas** [comment]
Uhh, while we would probably accept that, honestly, I'd take that up to eslint. 

That is the [method definition](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions) syntax and has nothing to do with classes in the slightest - and making any assumptions on how something is implemented based on that is, honestly, pretty problematic, as TypeScript itself does not make this distinction.

Like, TypeScript as underlying language does not make this distinction - this is all just the - honestly, weird - interpretation of the author of an eslint rule.

All of these are 100% interchangeable from TypeScript's perspective:

```ts
class X {
  foo(){ return "x" }
}

const classInstance = new X()

const methodDefinitions = {
  foo() {
    return "x"
  }
}

const arrowFn = {
  foo: () => "x"
}


{
  let x: X;
  x = classInstance
  x = methodDefinitions
  x = arrowFn
}

{
  let x: typeof methodDefinitions;
  x = classInstance
  x = methodDefinitions
  x = arrowFn
}

{
  let x: typeof arrowFn;
  x = classInstance
  x = methodDefinitions
  x = arrowFn
}
```

**Comment by markerikson** [comment]
Going to go ahead and close this because I don't think it's specifically actionable on our end, but if you feel the types can be improved in some way, please go ahead and submit a PR.

**Comment by jonparkdev** [comment]
@phryneas  That makes sense, thank you for clarifying.
