### ISSUE TITLE
RTK Query - Code splitting and invalidations

### ISSUE THREAD

**Issue by Aloysb** [reduxjs/redux-toolkit#1131]
Hi !

We've been using RTK Query since the Alpha and it works very well! Thank you 🙏 

We've split our API into several files for maintainability reasons.
However, how can you invalidate tags across the multiple createApi instances?

For example, in the case:

```
const A = createApi({...})
const B = createApi({...})
```

Is it possible for endpoints in A to invalidates tags provided by endpoints in B?

Please let me know if this is unclear.

**Comment by phryneas** [comment]
You should not split one api into many, as that will make invalidation over "api borders" impossible.

Instead, create one "empty" API without endpoints, import that into multiple other files and use `injectEndpoints` for code splitting. This is shown in the ["Code Splitting" section in the docs](https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/rtk-query/usage/code-splitting)

**Comment by Aloysb** [comment]
Thank you for your response 😊
