### ISSUE TITLE
RTKQ feature proposal: Add transformError property to the endpoints

### ISSUE THREAD

**Issue by donatoaguirre24** [reduxjs/redux-toolkit#1139]
It would be great to have a `transformResponse` equivalent for errors. The `transformError` property would allow manipulation of the error returned by a query or mutation before it hits the cache.

This new property would help to decouple error parsing logic from the view. The service will encapsulate the logic, and the views will act just as a presenter of the data/error the query or mutation returns.

**Comment by dreyks** [comment]
I'd love to have this feature! any opinions on this from the team? I can try to come up with a PR if this is something we want to have

**Comment by markerikson** [comment]
Yeah, if someone would like to take a stab at this and file a PR, we can look at it.

**Comment by phryneas** [comment]
But note that this will probably be touching a lot of types, so it might get very complicated.

**Comment by dreyks** [comment]
created #1841 as a first pass. let me know if going the correct direction

**Comment by markerikson** [comment]
Merged this - it'll be in the #2401 PR preview builds momentarily, and I'm hoping to put out `1.9.0-alpha.0` in a bit
