### ISSUE TITLE
RTK query arg should be optional

### ISSUE THREAD

**Issue by Faithfinder** [reduxjs/redux-toolkit#1153]
The api endpoint often enough isn't parametrized, in this cases the `useQuery` arg should probably be optional.

**Comment by markerikson** [comment]
I'm afraid I'm not clear on what you're trying to say here.  Can you give some specific examples?  Is this about the JS runtime behavior, or the TS typings?

**Comment by Faithfinder** [comment]
Well, I'm not sure what's going on in implementation, but it fails at the typings level. Here's the modified basic example to demonstrate:
https://codesandbox.io/s/naughty-gareth-pd3zt

**Comment by markerikson** [comment]
If you're going to write this in TS, you need to supply the `builder.query<QueryResult, QueryArg>` generic parameters, to tell TS what is returned and what can be passed in:

https://redux-toolkit.js.org/rtk-query/usage-with-typescript#typing-query-and-mutation-endpoints

**Comment by Faithfinder** [comment]
I can't specify an optional generic, can I? What do you propose as the argtype in this case?

**Comment by markerikson** [comment]
Use `void` as the `QueryArg` type parameter.

**Comment by Faithfinder** [comment]
This works, thanks. I would say worth updating the docs with an example?
