### ISSUE TITLE
RTKQ: add `previousData` to query return

### ISSUE THREAD

**Issue by Faithfinder** [reduxjs/redux-toolkit#1157]
For polling queries, sometimes we want to know if the data has changed. For that we would need a way to compare the current return to the previous ones. The easiest way for this is to have a `previousData` on the hook return.

Surprisingly, out of [inspirations](https://redux-toolkit.js.org/rtk-query/comparison) for RTKQ I've only found a similar approach on [Apollo](https://www.apollographql.com/docs/react/api/react/hooks/#previousdata)

Our specific use case is polling a "Current version" endpoint, and showing a request to refresh the page to the user if the version is different from what the user has, but I imagine there are other cases.

**Comment by markerikson** [comment]
I'm pretty sure this was later resolved by adding a `currentData` field.
