### ISSUE TITLE
RTKQ: easier access to `transformResponse` typing

### ISSUE THREAD

**Issue by Faithfinder** [reduxjs/redux-toolkit#1158]
I don't want to define `transformResponse` inline, but getting the correct typings for it seems like a pain. Could you provide a public type like `TransformResponseFn<QueryReturnValue,  Result>`?

Also, typings tell me that `meta` on it could be undefined, but I'm not sure in which cases?

**Comment by phryneas** [comment]
The types on `TransformResponse` rely on your `BaseQuery`, so it would end up as `TransformResponseFn<ReturnType<typeof fetchBaseQuery>, Result>`, which would not be very ergonomic.

`fetchBaseQuery` is a 
```ts
BaseQueryFn<
  string | FetchArgs,
  unknown,
  FetchBaseQueryError,
  {},
  FetchBaseQueryMeta
>
```

So, for `fetchBaseQuery`, you should be able to type it as
```ts
function transform(result: unknown, meta?: FetchBaseQueryMeta): Result {}
// or
function transform(result: unknown, meta?: FetchBaseQueryMeta): Promise<Result> {}
```

In which cases `meta` is set or not also depends on the `baseQuery` you are using. In the case of `fetchBaseQuery`, `meta` should always be there.
With other `baseQueries`, it could only be there in the error case (in which case it would be missing in `transformResponse`), always or in random situations. That would really depend on your implementation.
