### ISSUE TITLE
RTKQ: Reducers

### ISSUE THREAD

**Issue by buchanaf** [reduxjs/redux-toolkit#1164]
Hi guys,

First great job on this! Just got through reading all the docs and can't wait to use this.

I basically had a clarifying question. While 95% of the logic in my slice is API based, there are often times global variables that I want stored in the slice that are tied to the API entity but not directly from the API. Although `createApi` returns  a "slice-like structure", is there no ability to add reducers/actions that fall under that namespace? Or basically, what's the suggested approach for adding something like an "activeTodoId" to the "todos" slice that's generated by `createApi`.

**Comment by buchanaf** [comment]
> Definitely the latter approach. That would be a good example of "app state", vs "server state", and helps illustrate the difference in use cases.
> 
> RTKQ is for "server state" - data that was fetched via the server and cached.
> 
> The notion of "active/selected item" is going to be purely a client-side thing.
> 
> But, you can totally use data from both areas in a given component. So, your component can call `useFetchTodosQuery()`, and `const selectedTodoId = useSelector(state => state.todos.selectedId)`, and then use that to indicate which one is selected.

Gotcha, so just to be super clear. You'd have a `apiTodos` slice and an `todos` (aka app state) slice?

**Comment by markerikson** [comment]
Yep, and that's if "the current selected todo" even _needs_ to be in Redux.  Totally fine if it is, but it also could easily be local state in a `<TodosList>` component.

**Comment by buchanaf** [comment]
> We recommend having a single "API slice" for the _entire_ application, not just a single data type:

Ahh, interesting. That's definitely not the way I was thinking about it since my API is very REST-ful so all of my data entities are colocated. Glad I re-read that.

**Comment by markerikson** [comment]
To be clear, having a single "API slice" does _not_ mean you have to have every endpoint in the same file :)  It just means that there's ultimately one slice of state that has the combined cache, and one middleware that's responsible for managing updates to that cache.

The actual definitions of those endpoints can be spread across multiple files if you want to, using the same techniques we have available for code splitting:

https://redux-toolkit.js.org/rtk-query/usage/code-splitting
