### ISSUE TITLE
TS: createAsyncThunk arguments are typed but not really?

### ISSUE THREAD

**Issue by josias-r** [reduxjs/redux-toolkit#1178]
We have an asyncThunkAction which is typed [according to your documentation](https://redux-toolkit.js.org/usage/usage-with-typescript#createasyncthunk).
![image](https://user-images.githubusercontent.com/11424820/121917519-7d0e9300-cd35-11eb-9a9d-f78c5dad20ce.png)
 ![image](https://user-images.githubusercontent.com/11424820/121917079-083b5900-cd35-11eb-8e09-11eb1c3930a1.png)

As you can see on the second screenshot I'm providing a completely false value to a value that expects to be a string. But there's no TS error whatsoever.

When I hover over the username argument it actually shows me it should be a string, but still, no error.

This completely removes the point of TS.

**Comment by phryneas** [comment]
Can you create a reproduction of this in the [TypeScript playground](https://www.typescriptlang.org/play/)?

Also, can you verify that in your `tsconfig.json`, `strict` is set to `true`?

**Comment by josias-r** [comment]
@phryneas Created a reproduction sandbox just to prove the bug does not exist. https://codesandbox.io/s/dry-bush-htbot?file=/src/App.tsx

It turns out some dev in our company added a `// @ts-nocheck` comment to the top of the file, which I did not see :rofl: 

Sorry for the inconvienence

**Comment by phryneas** [comment]
Always happe when bugs solve themselves :) Have a good day!
