### ISSUE TITLE
Update packaged and now I get this on my slice

### ISSUE THREAD

**Issue by elira1** [reduxjs/redux-toolkit#1181]
TS2742: The inferred type of 'usersSlice' cannot be named without a reference to '@reduxjs/toolkit/node_modules/immer/dist/internal'. This is likely not portable. A type annotation is necessary.

**Comment by markerikson** [comment]
We'd need to see an example that reproduces this issue.  Might be worth deleting `node_modules` and reinstalling.

**Comment by thibaultboursier** [comment]
On my side, I had this error message because my local version of `immer` was not the same than `@reduxjs/toolkit` one.
After upgrading it to `9.0.14`, it went well.

**Comment by NickBolles** [comment]
@thibaultboursier +1 looking at `yarn why immer` I had a few versions installed (one was from redux toolkit, others were from other dependencies). After adding a yarn resolution for the RTK one it fixed the type error. Thanks for the idea!

**Comment by kelvin-at-nova** [comment]
Try this, next project or mono repo project, delete your `node_module`, `package-lock.json` then reinstall everything with `npm i`. That fixed my issue. Adding `immer` didn't fix my issue, and I didn't need `immer` to resolve it at the end.
