### ISSUE TITLE
RTK 1.6 Error at project build time

### ISSUE THREAD

**Issue by CyrilQuandalle** [reduxjs/redux-toolkit#1185]
Hello,

I was using the 1.5.1 version and decided to migrate to the latest, but when I tried to build my project with the latest version of RTK (1.6.0) I've got the following error  :

`ERROR in ../../node_modules/@reduxjs/toolkit/node_modules/@babel/runtime/helpers/esm/objectSpread2.js 1:0-46
Module not found: Error: Can't resolve './defineProperty' in '/home/personalpath/node_modules/@reduxjs/toolkit/node_modules/@babel/runtime/helpers/esm'
Did you mean 'defineProperty.js'?
BREAKING CHANGE: The request './defineProperty' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.`

I'm using webpack 5.20.2, babel 7.12.13 and I have enabled sideEffects option for tree-shaking in my package.json

Is there something specific that I need to do ?
Thank you in advance for your answer.

**Comment by msutkowski** [comment]
@CyrilQuandalle Are you able to provide a minimal reproduction where this occurs? This is most likely a configuration issue that would be rather hard for us to recreate.

**Comment by CyrilQuandalle** [comment]
Hello @msutkowski,
Thank you for your answer. I'm not sure I can create a minimal reproduction since I use it on a big project, but I'll continue to investigate to see if I can fix it by tweaking my configuration like you suggested and keep you posted.

**Comment by phryneas** [comment]
Could you please also post here the exact version of the package `../../node_modules/@reduxjs/toolkit/node_modules/@babel/runtime` you have currently installed there and then try to update that one to another version?

**Comment by CyrilQuandalle** [comment]
Hello @phryneas ,
My current version of @babel/runtime there is 7.9.2. I updated the version in that package.json to another one and ran yarn like you suggested but the problem is still there.

**Comment by apizzini** [comment]
What worked for me was installing `npm install --save @babel/runtime`. Of course this package was already installed as a sub-dep but not the last version. This will force having the last version installed and fixes the redux-toolkit runtime error.

**Comment by CyrilQuandalle** [comment]
I just tried your suggestion @apizzini  but unfortunately it didn't work for me.

**Comment by phryneas** [comment]
Try to get babel runtime up to the current (7.14.6) and also make sure it is only installed once, not in multiple versions throughout your project.
`npm list @babel/runtime` or `yarn ls @babel/runtime` will help you find multiple installations.

**Comment by markerikson** [comment]
Given the lack of reproduction and that this appears to be project-specific, I'm going to go ahead and close this.
