### ISSUE TITLE
RTKQ: Access result immediately after a query

### ISSUE THREAD

**Issue by zoubingwu** [reduxjs/redux-toolkit#1195]
Is there a way to access http result immediately after a query like mutation does for some simple, one-time data fetching?

The background is I'm writing a form and when user submit it, it'll need to query some data to map some fields user filled to another kind of data then sumbit the whole form data to server. 

Initially I was thinking about handle this with `useQuery`, like the example code below:
```js
// with useQuery
const { data: user } = useGetUserIdByEmailQuery(email)
const onSubmit = useCallback((formData) => {
	const { id } = user
	const { email, ...rest } = formData
	submitFormDataToServer({
		...rest,
		targetUserId: id,
	})
}, [])
```

But firstly there should have a `user` state, when input of email changes, it should fire a http call then update that user state, secondly, user could hit submit button before the http call returned and that user state updated, so the state might be staled which brings another complexity to maintain.

I'm currently declare it as a mutation to workaround it but that's way so confusing considering the semantics behind `query` and `mutation`.

```js
// current
const [getUserIdByEmail] = useGetUserIdByEmailMutation()
const onSubmit = useCallback((formData) => {
	const { email, ...rest } = formData
	getUserIdByEmail(email).unwrap().then(result => {
		const { id: userId } = result
		submitFormDataToServer({
			...rest,
			targetUserId: userId,
		})
	})
}, [])
```

So is there another ideal way to handle this?

**Comment by phryneas** [comment]
Not at the moment. Might be added in the future in some way though. Right now, you are using the best way to achieve your result.

**Comment by phryneas** [comment]
Looking at your case you might also just want to have both those actions take place in the same endpoint:

https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#performing-multiple-requests-with-a-single-query

**Comment by zoubingwu** [comment]
> Looking at your case you might also just want to have both those actions take place in the same endpoint:
> 
> 
> 
> https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#performing-multiple-requests-with-a-single-query

This looks like a good to do it , I'll look into it, Thanks!

**Comment by zoubingwu** [comment]
My question is answered so I'm closing this issue.
