### ISSUE TITLE
RTKQ: Can I include session cookies on every request (aka `credentials: include` of fetch function)

### ISSUE THREAD

**Issue by alumpe** [reduxjs/redux-toolkit#1196]
Is there a simple way of enabling the inclusion of session cookies on every request? With basic fetch you can set `credentials: include` as an option, is there a way to enable such an option on the `fetchBaseQuery`?

I guess overwriting the fetchFn would be easy enough.
```
baseQuery: fetchBaseQuery({
    baseUrl: "xxx",
    fetchFn: (input: RequestInfo, init?: RequestInit | undefined) =>
      fetch(input, { ...init, credentials: "include" }),
  }),
```

**Comment by msutkowski** [comment]
https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery#fetchbasequery

You can just do this if you wanted to on every request:

```ts
fetchBaseQuery({ baseUrl: "", credentials: "include" });
```

The more common usage might be to use `prepareHeaders` and only do that on requests that require any type of auth headers.
