### ISSUE TITLE
RTKQ: refetchOnFocus not working as expected

### ISSUE THREAD

**Issue by dpyzo0o** [reduxjs/redux-toolkit#1199]
https://codesandbox.io/s/brave-monad-idvei?file=/src/Pokemon.tsx

Here is the basic example from official docs, added with `refetchOnFocus: true`. It turns out the query does not refetch when window regains focus.

**Comment by dpyzo0o** [comment]
Sorry I just found out that I missed this sentence `Note: requires setupListeners to have been called.`

**Comment by ImamAlfariziSyahputra** [comment]
its fix my problem, thank you for this info!
