### ISSUE TITLE
Optimistic updates not working

### ISSUE THREAD

**Issue by adi518** [reduxjs/redux-toolkit#1207]
I was trying to use this API today and it came up short. The single example in the docs is just not enough and I wasn't able to patch my query with an optimistic update. In fact, the `draft` callback doesn't run at all and I can't figure out why. I'm trying to patch a query from a mutation, i.e., `createComment` should update the state of `listComments` query and undo it in case of rejection.

Edit: Made some progress with debugging. Apparently, the query I want to patch is `"uninitialized"`, despite clearly seeing it in my store, with the exact same query args as its key. It leads me to believe it then gets halt by this, which means it skips `updateRecipe`: https://github.com/reduxjs/redux-toolkit/blob/583823474d041773229a8e78b2ceba37f7616851/src/query/core/buildThunks.ts#L236

I went through the rtk-query source code with debugger and still can't figure it out.

A snippet of my wip code:
```ts
export const segmentsApi = createApi({
  baseQuery: graphqlBaseQuery(),
  tagTypes: ["Segments"],
  reducerPath: "segmentsApi",
  serializeQueryArgs,
  endpoints: (builder) => ({
    listSegments: builder.query({
      query: (variables: API.ListSegmentsQueryVariables) => ({
        body: queries.listSegments,
        variables: applyNoLimits(variables),
      }),
      providesTags: listOf("Segments"),
      transformResponse: (response: API.ListSegmentsQuery) =>
        response.listSegments?.items?.filter(nonNullable)!,
    }),
    createSegment: builder.mutation({
      query: (variables: API.CreateSegmentMutationVariables) => ({
        body: mutations.createSegment,
        variables: variables,
      }),
      invalidatesTags: listOf("Segments")(),
      transformResponse: (response: API.CreateSegmentMutation) =>
        response.createSegment,
        async onQueryStarted(payload, { dispatch, queryFulfilled }) {
        // @ts-ignore
        const { type, episodeId, localizedEpisodeId } =
          payload.input as API.CreateSegmentInput;
        const patchResult = dispatch(
          segmentsApi.util.updateQueryData(
            "listSegments",
            {
              filter: {
                type: { eq: type },
                episodeId: { eq: episodeId },
                localizedEpisodeId: { eq: localizedEpisodeId },
              },
            },
            (draft) => {
              console.log({ draft });
              Object.assign(draft, payload);
            }
          )
        );
        try {
          await queryFulfilled;
        } catch {
          patchResult.undo();
        }
      },
    }),
  }),
});
```

**Comment by adi518** [comment]
Upon further investigation, it appears like a bug in serializing objects as cache keys: https://github.com/reduxjs/redux-toolkit/blob/b718e01d323d3ab4b913e5d88c9b90aa790bb975/src/query/defaultSerializeQueryArgs.ts#L5

This following snippets produce different results:

```ts
useListSegmentsQuery({
  filter: {
    type: { eq: SegmentType.GENERATION_QC },
    episodeId: { eq: episodeId },
    localizedEpisodeId: { eq: localizedEpisodeId },
  },
});
```

```ts
useListSegmentsQuery({
  filter: {
    episodeId: { eq: episodeId },
    type: { eq: SegmentType.GENERATION_QC },
    localizedEpisodeId: { eq: localizedEpisodeId },
  },
});
```

**Comment by phryneas** [comment]
Chat later showed that @adi518 was using a custom `SerializeQueryArgs` function that was causing issues.

**Comment by adi518** [comment]
Thanks for chiming in @phryneas. 👍
