### ISSUE TITLE
Support for nested reducerPaths for Redux-Toolkit-Query

### ISSUE THREAD

**Issue by mtodberg** [reduxjs/redux-toolkit#1210]
I have an application with lots of apis. As every api takes up a top-level property key in the store it will eventually create lots of clutter. As a short-term solution, I've temporarily prefixed the `reducerPath` so that they are presented next to one another when inspecting the store in DevTools (e.g. `apis/pokemon`), but this is not ideal. For example:
```ts
{
  apis/one: ...
  apis/two: ...
  apis/three: ...
  ...
  foo: ... (application stuff)
  bar: ... (application stuff)
}
```

Have you thought about this problem, and maybe the possibility to keep everything under a single key? For example `apis`? So you'd store the definitions like this:
```ts
{
  apis: {
    one: ...
    two: ... 
    ...
  } 
  foo: ... (application stuff)
  bar: ... (application stuff)
}
```

**Comment by phryneas** [comment]
Your application should generally only have **one** api. Are you really connecting to many different external services with different datasets at different domains/hosters?

**Comment by mtodberg** [comment]
It's different REST apis that the application communicates with. For example we have `/users` and `/companies`. These are then created as two redux-toolkit apis. For example:

```ts
export const usersApi = createApi({
  reducerPath: 'apis/users',
  baseQuery: fetchBaseQuery({ name: 'users' }),
  endpoints: (builder) => ({
    getUsers: ...
    getUser: ...
    ....
  })
})
```
And:

```ts
export const companiesApi = createApi({
  reducerPath: 'apis/companies',
  baseQuery: fetchBaseQuery({ name: 'companies' }),
  endpoints: (builder) => ({
    getCompanies: ...
    getCompany: ...
    ....
  })
})
```

**Comment by phryneas** [comment]
Those are different REST endpoints on the same API. They definitely should be part of the same `createApi`.
If you want to split that up, you can do so using [Code Splitting](https://redux-toolkit.js.org/rtk-query/usage/code-splitting), but you should have only one `createApi` call and only one `api` slice.

**Comment by mtodberg** [comment]
Thanks for the direction. Will have to change this accordingly then.

**Comment by mtodberg** [comment]
@phryneas By following this approach for code-splitting, is it possible to prefix all endpoints for a particular set of endpoints like `/users/*` or `/companies/*`. So every endpoint `url` in `injectEndpoints` is automatically prefixed with `users` or `companies`. Otherwise this identical information has to be repeated for every endpoint definition `url`. https://redux-toolkit.js.org/rtk-query/usage/code-splitting

**Comment by phryneas** [comment]
No. Of course you can always try to write a wrapper around it, but honestly I would not care if I were you. That repeated word will gzip just fine to probably 1 or 2 bytes, so it won't create any significant extra bundle size.
