### ISSUE TITLE
How to use RTK-Q in a Redux-Thunk?

### ISSUE THREAD

**Issue by mtodberg** [reduxjs/redux-toolkit#1213]
How do I use a Redux-Toolkit-Query api inside a redux-thunk action?

```ts
import { pokemonApi } from '...'; 

const getPokemons = createAsyncThunk<Pokemon[], void>('GET_POKEMONS', async () => {
  // How to use pokemonApi here?
});
```

**Comment by mtodberg** [comment]
Never mind figured it out 👍🏻

**Comment by hhsl** [comment]
For anyone else looking for a solution for this question, it should be found here:
https://redux-toolkit.js.org/rtk-query/usage/usage-without-react-hooks
