### ISSUE TITLE
Undefined data in intermediate RTKQ mutation loading step

### ISSUE THREAD

**Issue by nickbabcock** [reduxjs/redux-toolkit#1215]
[The docs state](https://redux-toolkit.js.org/rtk-query/usage/mutations#frequently-used-mutation-hook-return-values):

> The "mutation result" is an object containing properties such as the latest `data` for the mutation request

What I'm observing is that after the initial mutation, subsequent mutations substitute in `undefined` for the latest data and I wanted to confirm that this is working as designed.

To give an example, I have a button that returns a new API key. It's possible for the user to click the button more than once to generate more than one API key.

```tsx
export const AccountContent: React.FC<{}> = () => {
  const [trigger, { data }] = myApi.endpoints.newApiKey.useMutation();
  console.log(data);
  return (
    <>
      { data?.api_key ? <p>{data?.api_key}</p> : null }
      <button onClick={() => trigger()}>Generate</button>
    </>
  )
}
```

The following is the output from logging the data after three buttons clicks.

```
undefined
"api_key"
undefined
"api_key"
undefined
"api_key"
```

And the element for holding the API key will flicker with every undefined result.

I had anticipated that if `isLoading` is true that the previous defined result would be returned if available, but it appears I am mistaken.

It kinda seems unintended as the docs don't seem to indicate that data, isLoading, and isUninitialized are mutually exclusive to each other (ie: if one is truthy then the others must be falsey). This issue does not seem to apply to queries, interestingly enough.

**Comment by phryneas** [comment]
It's pretty much to the different nature of queries and mutations.

Queries are just the latest data for a specific request to the server. Multiple queries are pooled together if they have the same arguments and you will get a result from the cache as soon as possible, even if it might get updated with more up-to-date data half a second later.

Mutations on the other hand are things where we consider that they invoke a change on the server. We don't pool those, every mutation is unique and will never share a cache key with any other mutation - even if it is to the same endpoint, with the same arguments.

So for the hook, once you trigger it, it jumps over to the "newest triggered mutation" and tracks that. And if that does not have an answer yet, it will just be loading without data. As with cache values, we will also never mix those responses on component/hook level.

**Comment by nickbabcock** [comment]
Ok, it's not a problem for me to cache data pre-trigger. Sounds like there may be a docs improvement lurking around as both queries and mutations use the phrase:

> The query hook returns an object containing properties such as the latest data for the query request

So digesting this: a mutation's data is mutually exclusive with isLoading while a query is not, so the mutation data is discarded on trigger and the latest data assumed to be undefined until proven otherwise, which does makes sense from an alternative angle -- my intuition was just different (that the "latest data" phrase represented data from server so two well defined responses wouldn't have an intermediate undefined state).

**Comment by phryneas** [comment]
> Sounds like there may be a docs improvement lurking 

Yeah, definitely, go for it :)

Important stuff that needs to be in there somehow:

* The mutation hook returns a trigger function and a result object using a tuple, in the form `[trigger, result]`
* `result` contains information about the last mutation that was triggered using the `trigger` function returned *from this hook instance* (data will not be shared with multiple usages of the hook in the same component or other components).
