### ISSUE TITLE
[docs][rtkq] ApiProvider link on Getting Started has an unhelpful cycle

### ISSUE THREAD

**Issue by taylorkline** [reduxjs/redux-toolkit#1217]
Under RTK Query's [What's Included section](https://redux-toolkit.js.org/introduction/getting-started#whats-included-1), it lists the `<ApiProvider />` that "Can be used as a Provider if you do not already have a Redux store."

After following the link to find out more, [the `ApiProvider` documentation](https://redux-toolkit.js.org/rtk-query/api/ApiProvider) says "Using this together with an existing Redux store will cause them to conflict with each other. If you are already using Redux, please follow the instructions as shown in the Getting Started guide." which links right back to the Getting Started documentation we came from, which does not include any enlightening information about when to use the `ApiProvider` versus the `Provider`.

**Comment by phryneas** [comment]
Well, both of these have all the information..?

Are you using Redux? Do not use ApiProvider.

Do you not use Redux? You can use ApiProvider.

**Comment by taylorkline** [comment]
@phryneas to elaborate, one would expect the link included within the "If you are already using Redux, please follow the instructions as shown in the Getting Started guide" to mention something about a `Provider`, and how to set up a `Provider` in a way that perhaps also functions as an `ApiProvider`. But it currently links back to the Getting Started guide that only mentions that you can use the `ApiProvider` under the condition you don't already have a Redux store - and we're back at square one.

**Comment by phryneas** [comment]
If you already are using Redux you already have a Provider and know what a Provider is because otherwise you could not be using Redux.

**Comment by phryneas** [comment]
So you could not care less about the provider in that case.
It's either "integrate RTK-Q into your store" or "use RTK-Q without a store".
That should pretty much imply that you should just follow the normal setup for a store (which at some point includes a Provider) if you want to use RTK-Q with a store, no?

**Comment by taylorkline** [comment]
I think the concern that's not addressed is "What should I do in the case where I am setting up a new project and deciding on an initial structure?"

So, for example, 

> "Can be used as a Provider if you do not already have a Redux store."

could be more helpful to someone with this question along the lines of:

> "Can be used as a Provider if you do not already have a Redux store. If you're integrating Redux Toolkit into your project for the first time or starting a new project, use..." (whether that be use `ApiProvider` until you have a need for a `Provider`, or if there are some situations where you'd want to start with a `Provider` regardless, etc.)

Similarly,

> "Using this together with an existing Redux store will cause them to conflict with each other. If you are already using Redux, please follow the instructions as shown in the Getting Started guide."

to

> "Using this together with an existing Redux store will cause them to conflict with each other. If you are already using Redux, please follow the instructions as shown in the Getting Started guide. If you're integrating Redux Toolkit into your project for the first time or starting a new project, do..."

**Comment by taylorkline** [comment]
I, specifically, am starting a project that I know will eventually use a Redux store, but I don't have one yet. I could start with the `ApiProvider`, right? But is that the best decision since I know I will be adding a Redux store eventually, or is it better to start with the `Provider`?

**Comment by phryneas** [comment]
It pretty much doesn't matter. You can start with the ApiProvider now and later replace one line, or directly set up a Redux store (which is also just 5 or 6 lines).

Going from one to the other is a matter of minutes, if even that - honestly, I think you are just really really overthinking this.
