### ISSUE TITLE
How to handle multiple entities from a single query using RKT-Query?

### ISSUE THREAD

**Issue by vidhu** [reduxjs/redux-toolkit#1220]
Lets say I have an API which returns me a `user` and a list of `posts`

```json
GET /user/123
 
{
   "user":{
      "id": 1,
      "name":"Bob",
      "age":23
   },
   "posts":[
      {
         "id":1,
         "name":"A sample post 1"
      },
      {
         "id":2,
         "name":"A sample post 2"
      }
   ]
}
```

```js
const postEntityAdapter = createEntityAdapter({...});
const userEntityAdapter = createEntityAdapter({...});

const api = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: "https://server.com/api/" }),
  endpoints: (builder) => ({

    getUserAndPost: builder.query({
      query: (userId: string) => `user/${userId}`,
      transformResponse: (response) => {
        return postEntityAdapter.addMany(
          postAdapter.getInitialState(),
          response.post
        );
        // What do I do with response.user ??
      },
    }),

    refreshPost: builder.query({
      query: (postId: string) => `post/${uspostIderId}`,
      transformResponse: (response) => {
        return postEntityAdapter.updateOne(
          postAdapter.getInitialState(),
          response.postData
        );
      },
    }),
  })
});
```

Here I want to initially fetch the entire state of the application (user + post)
Later on I want to refresh a post. 

I don't really see a pattern of doing this cleanly. 

I was thinking of using an `EntityAdapter` to keep track of the list of posts and user. That way, when I called refreshPost, I could simply call `.updateOne`.

Any suggestions on how to go about dealing with multiple nested data/entities?

**Comment by phryneas** [comment]
RTK-Query is not a normalized cache. Each query has their own cache entry (requests with the same arguments are combined into one) and no data is shared between them. If you use EntityAdapter in each of them, those will still be completely separate datasets.

If you have a query that returns multiple types of data, the usual procedure would be to re-run that request to get up-to-date data for it.
You can also use the lifecycle actions of an endpoint to always update an external cache entry of another entry point, but at that part you'll have to pretty much do that on your own.

An example of something similar would be under [optimistic updates](https://redux-toolkit.js.org/rtk-query/usage/optimistic-updates).

But generally, if you have one endpoint with all data, I'd probably just refresh that one. Or use only single-purpose endpoints from the beginning.

**Comment by vidhu** [comment]
Thanks @phryneas. That definitely tracks from what I could tell. Sounds like this is better suited for RESTfull APIs
