### ISSUE TITLE
RTKQ: endpoints generated store data path has `(undefined)` in it

### ISSUE THREAD

**Issue by shotaK** [reduxjs/redux-toolkit#1221]
So I've created my first API using the Query API but seems like can't get rid of auto-generated `(undefined)` in the store.

My createApi:

```typescript
import first from "lodash.first";
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

import apiUrls from "Config/api-urls";

import { Test } from "./Types";

export const testsApi = createApi({
  reducerPath: "testApi",
  baseQuery: fetchBaseQuery({
    baseUrl: apiUrls.api.host,
  }),
  endpoints: (builder) => ({
    getTestsAll: builder.query<Test, void>({
      query: () => ({ url: apiUrls.api.tests.base }),
      transformResponse: (rawResult: Test[]) => {
        return first(rawResult) as Test;
      },
    }),
  }),
});

export const { useGetTestsAllQuery } = testsApi;

```

This is how Redux store looks like:

![image](https://user-images.githubusercontent.com/3370367/123503748-e790ce80-d665-11eb-8762-0674725632c6.png)

So to get the data in the selector I have to do something like this:

```typescript
export const testApiSelector = (state: RootState) =>
  state.testApi.queries["getTestsAll(undefined)"]?.data as Test;
```

Question 1: how to get rid of the `(undefined)`
Question 2: What would be the best way to get the Query API data in a generic selector(for example avoiding go through all of the Query API properties)

**Comment by phryneas** [comment]
Question 1: That is an implementation detail of RTK Query and you really don't need to worry about that one :wink: You are not expected to access the store by hand.

Question 2: You would get a selector for that data by doing
```
const selector = api.endpoints.getTestAll.selector()
```
See [the documentation on select](https://redux-toolkit.js.org/rtk-query/api/created-api/endpoints#select)

If you are using the hooks, you can also use [useQueryState](https://redux-toolkit.js.org/rtk-query/api/created-api/hooks#usequerystate) or just the normal query hook (which will not trigger another request if data is already in the cache), both with [`selectFromResult`](https://redux-toolkit.js.org/rtk-query/usage/queries#selecting-data-from-a-query-result) if needed.
