### ISSUE TITLE
RTKQ: Multiple Query Clarification

### ISSUE THREAD

**Issue by buchanaf** [reduxjs/redux-toolkit#1227]
Hi, 

I just wanted to clarify a couple of things that I couldn't find a clear answer for in the docs.

1. For multiple queries that may be trigged on a page load (GET /authors, /blogs, /comments -- not a great example) is there any guidance on how to compose those requests, or should it simply be 3 useGet[w/e]Queries and it's on our side to handle the 3 loading states. I came across https://github.com/reduxjs/redux-toolkit/issues/1159 and the `useQueries` idea but was curious.

2. For dependent requests, think a promise chain where the next request params rely on the previous async request, is that simply some combination of `useLazy` and then `useEffect` to trigger the dependent request?

**Comment by phryneas** [comment]
1. writing multiple queries is probably the best option at this point
2. you would use the `skip` option or `skipToken` for that. Here with skipToken:
```js
const firstResult = useFirstQuery()
const secondResult = useSecondQuery(firstResult.isSuccess ? firstResult.data.x : skipToken)
```

**Comment by buchanaf** [comment]
Ahh thank you so much!
