### ISSUE TITLE
[RTK Query] Passing nested object to query causes query to continuously retry if the request fails

### ISSUE THREAD

**Issue by knguyen0125** [reduxjs/redux-toolkit#1228]
Hi,

I'm trying to build an api that perform searching via request query. The resulting URL should be like `/user?_where[_and][0][id]=123456&_where[_and][1][role]=admin&_limit=1&_offset=0`

In order to do this, I want to pass a parameter to `useQuery` that have the following:
```
{
   where: {
     _and: [
       { id: 12345 },
       {role: 'admin'}
    ]
  },
  pagination: {
    limit: 1,
    offset: 0
  }
}
```

However, under current RTK implementation, my application will continuously retry and calls the API, even if I use the provided `retry` utility. I think it's because `useQuery` hooks is shallow comparing the properties in arguments, because if I modify the params to primitive values, it works fine. 

Apart from re-creating React module, I don't think it's possible for me to do what I wanted to do. Is there plans to deep compare these values?

**Comment by phryneas** [comment]
Essentially you have to handle everything you put into a query hook the same way as if you were to pass it into a `useEffect` dependency array.

The easiest way to work with this is to use something like `useMemo` in your component when creating that object to keep it referentially stable:

```js
useQuery(useMemo(() => ({
   where: {
     _and: [
       { id: id },
       { role: role }
    ]
  },
  pagination: {
    limit: limit,
    offset: offset
  }
}), [id, role, limit, offset])
```

**Comment by knguyen0125** [comment]
@phryneas It works. Thanks a lot. I just found it in the docs
