### ISSUE TITLE
How can I get RTK Query autogenerated action type access to some other Slice ?

### ISSUE THREAD

**Issue by bankimAtCapgemini** [reduxjs/redux-toolkit#1233]
Hi,

I am using RTK Query to call my API but now I want to listen to that fulfilled event on my other existing slice. Is there any way I can access that action type instead of putting that hardcoded string as an action type in my existing slice?

Please help me ASAP.

Thanks,
Bankim

**Comment by markerikson** [comment]
Yep, see https://redux-toolkit.js.org/rtk-query/api/created-api/endpoints#matchers .

Example:

```js
import { pokemonApi } from "../pokemon/pokemonSlice";

const otherSlice = createSlice({
  name: "somethingElse",
  initialState,
  reducers: {},
  extraReducers: (builder) => {
    builder.addMatcher(pokemonApi.endpoints.getPokemon.matchFulfilled, (state, action) => {
      // reducer logic here
    })
  }
})
```

**Comment by bankimAtCapgemini** [comment]
Thank You :)
