### ISSUE TITLE
Add Additional Information for Redux-Persist

### ISSUE THREAD

**Issue by grumpyTofu** [reduxjs/redux-toolkit#1237]
I was working on a project where I implemented RTK with redux-persist following the docs for RTK but I wanted to 'flush' storage on user logout which seems to be a fairly common action and it wasn't immediately apparent how to accomplish this with RTK based on current documentation. Here was the final solution:

```
import { PURGE } from "redux-persist";

...
extraReducers: (builder) => {
    builder.addCase(PURGE, (state) => {
        customEntityAdapter.removeAll(state);
    });
}
```

Can I open a PR for this addition to the docs?

**Comment by grumpyTofu** [comment]
One additional question:

When working with RTK Query and createApi, it doesn't seem like there is an easy way to do something similar to the previous post, where you listen for a specific type. I was able to implement a solution using a custom middleware and the resetApiState util, but it seems kind of like a 'hacky' solution. Would there be a better way to implement this, or is something like this on the roadmap where we could provide specific action types or reducers to the createApi function?

```
import type { Middleware, Action, Dispatch } from "@reduxjs/toolkit";
import { PURGE } from "redux-persist";
import { pokemonApi } from "./pokemon";

export const utilityMiddleware: Middleware<any, any, Dispatch<Action>> = (store) => (next) => (action) => {
  if (action.type === PURGE) {
    store.dispatch(pokemonApi.util.resetApiState());
    // Repeat for every apiSlice?
  }
  next(action);
};
```

**Comment by phryneas** [comment]
Generally: your application should probably just have one api, not multiple. (one API per server-dataset, 95% of apps probably never need more than that)

Another point: you should not persist your api cache. (Really, if you need to cache things there set according browser headers and let your browser do the work it was designed for. Restoring persisted API caches will leave you with phantom subscriptions from components that do not exist any more.) So you should probably also not bind resetting to your api cache to your persist being flushed.

Assuming you do both of that, one api, no persisting -> one single reset call on logout. I'd just call that on logout then ;)

**Comment by grumpyTofu** [comment]
That seems like really good advice and would simplify a lot of things. I will refactor my code so that the api cache is not persisted. Should something be added to the docs to mention that if you are using redux-persist, you should blacklist apis so that you avoid this problem? 

something like this:
```
const persistConfig = {
  key: "root",
  version: 1,
  storage,
  blacklist: [pokemonApi.reducerPath]
};
```

My understanding is if you don't blacklist it, its going to be persisted so then everyone using redux-persist and createApi is persisting their api state

**Comment by phryneas** [comment]
Yeah, we should probably add that. 

We're still having a lot of learnings on how people are using it and what all could go wrong now that usage is increasing more in the hundreds-thousands of users. Lots of new usecases :sweat_smile:

**Comment by grumpyTofu** [comment]
Well at least one thing is certain, RTK is an awesome product!

I would be more than happy to add it to the docs if you would like?

**Comment by phryneas** [comment]
Always :)

**Comment by thoughtworks-tcaceres** [comment]
> Generally: your application should probably just have one api, not multiple. (one API per server-dataset, 95% of apps probably never need more than that)
> 
> Another point: you should not persist your api cache. (Really, if you need to cache things there set according browser headers and let your browser do the work it was designed for. Restoring persisted API caches will leave you with phantom subscriptions from components that do not exist any more.) So you should probably also not bind resetting to your api cache to your persist being flushed.
> 
> Assuming you do both of that, one api, no persisting -> one single reset call on logout. I'd just call that on logout then ;)

Sorry for bumping this.
Was this ever a way to resolve these 'phantom' subscriptions.
Currently running into this issue now w/ redux-persist. I was trying to get it to 'remove' subscriptions if a certain amount of time occured - but I'm assuming since they are 'phantom subscriptions' - the normal logic of `keepUnusedDataFor`, etc are not running against those cached values.

**Comment by phryneas** [comment]
Yes, you follow https://redux-toolkit.js.org/rtk-query/usage/persistence-and-rehydration#redux-persist to implement `extractRehydrationInfo` and then you dispatch an action with the data you want to rehydrate, for it to be caught in `extractRehydrationInfo`.

This is not a redux-persist only approach

**Comment by thoughtworks-tcaceres** [comment]
> Yes, you follow https://redux-toolkit.js.org/rtk-query/usage/persistence-and-rehydration#redux-persist to implement `extractRehydrationInfo` and then you dispatch an action with the data you want to rehydrate, for it to be caught in `extractRehydrationInfo`.
> 
> This is not a redux-persist only approach

Thanks @phryneas  - we were able to get it to work!
