### ISSUE TITLE
Evaluate the need for `originalArgs` in mutations.

### ISSUE THREAD

**Issue by phryneas** [reduxjs/redux-toolkit#1239]
Triggered by https://stackoverflow.com/questions/68221678/how-to-send-a-file-with-rtk-query-from-redux-toolkit

Generally I think we need `originalArgs` only in queries for re-requesting those and from the back of my mind I don't see why we would need those in mutations. 

So we should analyze if we really need those for mutations and in the case that we don't, not store them in the store.

**Comment by craigfarrer-fc** [comment]
Came here from the stackoverflow post. 

I'm trying to add the ignoredPath option but the error i'm getting for a non-serializable value is stating that the path changes every time. The value between mutations and originalArgs is constantly changing.

A non-serializable value was detected in the state, in the path: `splitApi.mutations.VHhzMuT20khUgBIU7Q26-.originalArgs.

**Comment by phryneas** [comment]
Yeah, as it stands right now you problably will have to ignore the full `splitApi.mutations`

**Comment by Saoirse-Derry** [comment]
@phryneas so RTK Query only really works with queries and NOT mutations? Seriously?

**Comment by markerikson** [comment]
@Saoirse-Derry I'm... really not sure what you're trying to say there.  I think you're misunderstanding the discussion and jumping to a wrong conclusion.

The original question was about trying to pass a non-serializable value as an argument to a mutation.

In our current implementation, we include that value as a param named `originalArg` in the action. But, we also warn about non-serializable values.  So, the question here is whether we even need to pass that param through.

**Comment by asif-mahmud** [comment]
Any suggestion about how to pass `File` as mutation argument ?

**Comment by phryneas** [comment]
Just do it and ignore the warning for now, or ignore the warnings for now.

**Comment by markerikson** [comment]
Should be fixed in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.6.1

**Comment by Lester-Nafwa** [comment]
how do i dispatch an image on redux store. i am creating a mutistep form that allow the user to send the image to an existing campaign id below is my api endpoint that keeps returning empty payload  ;
addCampaignImage: builder.mutation<void, Campaign>({
      query: (campaign) => {
 
     let imagepayload=campaign
     console.log('campaign',imagepayload)
     return { 
        //adding the end point of our api which is the same as the one we used when getting a single campaign
        url: `campaigns/file/1`,
        // adding the method, that is the PUT method
        headers: { myHeader: 'test-header','Content-Type':'image/png'},
        method: "POST",
        
        body:imagepayload,
      }},
      invalidatesTags: ["Campaign"],
    }),

**Comment by phryneas** [comment]
@Lester-Nafwa I'm honestly not really sure what that has to do with this issue at all.
