### ISSUE TITLE
RTKQ: Nextjs getServerSideProps

### ISSUE THREAD

**Issue by romseguy** [reduxjs/redux-toolkit#1240]
Hello,

As mentioned by @gfortaine [here](https://github.com/rtk-incubator/rtk-query/issues/88#issuecomment-763840622) we can avoid the error `Expected signal to be an instanceof AbortSignal` by using Node 15.

The problem being that [Vercel's Node version is 14.x](https://vercel.com/docs/runtimes#official-runtimes/node-js/node-js-version)

Is there any workaround until Vercel offers more recent Node versions?

**Comment by phryneas** [comment]
You might want to follow https://github.com/reduxjs/redux-toolkit/pull/1277 where I'm building SSR support.

For me, I solved this specific problem by doing 

```js
const { default: AbortController } = require("abort-controller");
const { default: fetch, Headers, Request, Response } = require("node-fetch");

Object.assign(globalThis, {
  fetch,
  Headers,
  Request,
  Response,
  AbortController,
});
```

in `_app.js`

**Comment by markerikson** [comment]
Available in the 1.7 betas.

**Comment by agusterodin** [comment]
Wait does 1.7 beta-1 fix this? I am deploying on Vercel running Node 14.x and still get this issue despite being on 1.7 beta-1.

I also tried adding 

```
const { default: AbortController } = require("abort-controller");
const { default: fetch, Headers, Request, Response } = require("node-fetch");

Object.assign(globalThis, {
  fetch,
  Headers,
  Request,
  Response,
  AbortController,
});
```
to my _app.tsx file but when testing locally on my M1 MacBook running Node 16.x I get this error

```
error - node:fs
Module build failed: UnhandledSchemeError: Reading from "node:fs" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
(node:85648) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
wait  - compiling /_error...
error - node:fs
Module build failed: UnhandledSchemeError: Reading from "node:fs" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
```

**Comment by agusterodin** [comment]
^ It also won't compile on vercel either when I try to do the _app trick

**Comment by phryneas** [comment]
@agusterodin that is not something we have any control over unfortunately. You'll have to dig into your environment, the fetch polyfills you use and when they are loaded (the sooner the better).

**Comment by agusterodin** [comment]
Gotcha, thanks! For anybody else encountering this I will leave this link here:

https://github.com/vercel/vercel/discussions/7003

Node 16 on Vercel seems like it is around the corner.

**Comment by srosato** [comment]
I only had this problem when using jest, I ended up doing this under node 14.x within my `jest.setup.ts`:

```
import 'isomorphic-fetch'
import { default as AbortController } from "abort-controller"
Object.assign(globalThis, {
    AbortController,
});
```
