### ISSUE TITLE
RTKQ: Redux store with queries. Discussion.

### ISSUE THREAD

**Issue by fellz** [reduxjs/redux-toolkit#1244]
Hi
I am new to RTKQ and i see that we store in redux store not only data but all other stuff - queries, mutations and so on. So if i need that data elsewhere in components i have to write selector like this:

```useAppSelector((state) => state.kkc.queries["fetchKKCData(undefined)"]?.data```

Do we need this ? can it be optimized ? maybe use redux store only for data ? something like {api: data{...}}

**Comment by phryneas** [comment]
The idea is to have one single api slice for all the data you have and cache each single query per endpoint and argument and *not* mix up data. Also, stuff like the information if a query is currently running *is* data and is stored in a Redux state in most implementation - we have many examples for that in the Redux docs.

You should not be writing those selectors by hand and not directly access that slice like this though - it's an implementation detail you should not care about and for what you know, it could change at any moment.

You can use either 
```js
const {data, isLoading, ...etc} = api.endpoints.fetchKKCData.useQueryState()
```
if you want the loading states or
```js
const data = api.endpoints.fetchKKCData.useQueryState(undefined, { selectFromResult: result => result.data })
```
or just use the selector by hand

```js
const selector = useMemo(() => api.endpoints.fetchKKCData.select())
const data = useSelector(state => selector(state).data))
```

**Comment by phryneas** [comment]
Adding to that: it is also perfectly valid to just do
```
const result = useFetchKKCDataQuery()
```
in *all* your components where you would otherwise select that data.

It will only cause a request if the data is not there yet - which you generally want to happen anyways.

**Comment by Dron007** [comment]
What can I use if I want to create a new selector which uses cached data? For example, there is a list of users and it needs to have selector returning only active users. I don't want to repeat the code in multiple components. I cannot use hooks in the module where selectors are being created.

**Comment by phryneas** [comment]
You could either just export a selector to be used with `selectFromResult` or write a custom hook to import into your component and use there.

**Comment by vlad-audiri** [comment]
I am using `useLazyFetchQuery` which has arguments

When i am using `useFetchQuery(skipToken)` in another Component, it returns result with `status: 'uninitialized'` and the data is `undefined`

Should i provide exact same args? I don't want to do it, i just want to get the latest data, because a lot of components rely on this lazy query.

**Comment by EskiMojo14** [comment]
you need the same arguments to be able to access the same cache entry.

**Comment by vlad-audiri** [comment]
> you need the same arguments to be able to access the same cache entry.

Parent with LazyQuery(args)
-- Child with Query(args)
-- Child with Query(args)
-- Child with Query(args)

So this is either passing `args` to child components or the `data` which is already fetched in the parent one. The answer is obvious.

Thank you for the quick reply @EskiMojo14
