### ISSUE TITLE
Website crashes on pressing up button on blank search bar

### ISSUE THREAD

**Issue by KylixMedusa** [reduxjs/redux-toolkit#1247]
https://user-images.githubusercontent.com/56185721/124359499-f74e7b00-dc42-11eb-9388-95553b21e334.mp4

**Comment by markerikson** [comment]
Hmm. Trying this myself right now, and nothing happens - no errors, no crashing.

The search bar is from Algolia integration, and strictly speaking not anything we have control over.

What version of Chrome are you using?

**Comment by KylixMedusa** [comment]
> Hmm. Trying this myself right now, and nothing happens - no errors, no crashing.
> 
> The search bar is from Algolia integration, and strictly speaking not anything we have control over.
> 
> What version of Chrome are you using?

Chrome 91

**Comment by markerikson** [comment]
I'm on Chrome 91 myself as well.

I definitely see the crash in that video, but I can't reproduce this myself, and I don't think there's anything we can do about that from our end. Sorry :(  My only suggestion is to not press the `up` arrow there.

**Comment by BurnedOx** [comment]
https://user-images.githubusercontent.com/31913130/124360502-d5a3c280-dc47-11eb-8d0f-dd122225d850.mov

Facing the same issue

**Comment by KylixMedusa** [comment]
`Up` arrow must be pressed when the search query is empty

**Comment by markerikson** [comment]
Okay, yeah, I see that now - when the search box _and_ the recent results are empty.

Like I said, we don't have any control over this ourselves, but I'll try pinging the Algolia folks.

**Comment by markerikson** [comment]
Per Algolia folks, this is being fixed:

- https://github.com/algolia/autocomplete/pull/599
- https://twitter.com/FrancoisChlfr/status/1411366471616237568

**Comment by markerikson** [comment]
pretty sure this is resolved now.
