### ISSUE TITLE
[RTK-Query] Accessing data and statuses from other components the redux way

### ISSUE THREAD

**Issue by shubhamdeodia** [reduxjs/redux-toolkit#1254]
From the documentation, it is not clear how I can access data the which was fetched from the RTK query.

I have a like below
```
export const apiSlice= createApi({
    reducerPath: 'api',
    baseQuery: fetchBaseQuery({
        baseUrl: 'url'
    }),
    endpoints: (builder) => ({
        fetchData: builder.query({
            query: () => ({
                url: `/api/`,
                method: 'GET',
            })
        })
    })
});

export const { useFetchDataQuery} = apiSlice;
```

Now this API slice fetch the data and show the different states like isLoading, isFeteching when I use it like this in some component

```
const { data, isLoading, isFetching } = useFetchDataQuery();
```

What I really want to ask is, How can I access the same data (which is fetched in the above query) using selectors in any other component, rather than passing the data as props?

Since the data is getting stored in redux only. I was hoping to access it in a simple way like using `useSelectors`

Also, do we have anything like `useIsFetching()` like there is in react-query?

**Comment by phryneas** [comment]
You can just use the same `useFetchDataQuery` in any number of components - this will not start another request if one has already been made.

Also, theree is `api.endpoints.fetchData.useQueryState` [docs](https://redux-toolkit.js.org/rtk-query/api/created-api/hooks#usequerystate) and `api.endpoints.fetchData.select` [docs](https://redux-toolkit.js.org/rtk-query/api/created-api/endpoints#select)

Both `useQuery` and `useQueryState` have the `selectFromResult` [docs](https://redux-toolkit.js.org/rtk-query/api/created-api/hooks#usequerystate) option which you can use to only select a part of the result, so `selectFromResult: result => ({ loading: result.isFetching })` would be a valid way of building your own `useIsFetching` hook.

**Comment by akursat** [comment]
Your ComponentB subscribes to the *same* data as ComponentA, as it has the [same query parameters](https://redux-toolkit.js.org/rtk-query/usage/cache-behavior#cache-lifetime--subscription-example).

**Comment by shubhamdeodia** [comment]
Thank you for the clarification. This is exactly what I was looking for.

**Comment by ODB-Gideon** [comment]
Hi thank you guys for clearing this up. Is it possible to also share the statuses of a mutation in an easy way?

**Comment by phryneas** [comment]
It will when #1477 lands.

**Comment by ODB-Gideon** [comment]
Wow! Thank you for the swift response @phryneas, I truly appreciate it!

**Comment by magrega** [comment]
Hi! I wanted to ask how I can access the same query data in another component if the query parameters are different?
I have a query in my main component where paramteres are declared locally so I can't use the same query in another component and passing params there seems messy.

```
const queryParams = {
    customerId: localStorage.getItem("customerId") || "",
    siteId: "",
    shippingDate: now,
    endDate: weekAfterNow,
    sortedBy: "-shippingDate",
  };

  const [query, setQuery] = useState(queryParams);

  const { refetch } = useGetOrderListQuery(query);

  useEffect(() => {
    refetch(query);
  }, [query, refetch]);
```
 and in another component I just use hook without args:
 
`  const { data, isFetching } = useGetOrderListQuery();`

But I want to have the same data from the first component.
