### ISSUE TITLE
Regression in IE11 after upgrading to v1.6.0

### ISSUE THREAD

**Issue by sibiraj-s** [reduxjs/redux-toolkit#1255]
There is a regression in IE11 after upgrading to v1.6.0 from v1.5.0.

<img width="296" alt="Screenshot 2021-07-06 at 6 04 25 PM" src="https://user-images.githubusercontent.com/20282546/124603214-513f8280-de87-11eb-82da-a7d6c5f16698.png">

From

<img width="619" alt="Screenshot 2021-07-06 at 6 00 08 PM" src="https://user-images.githubusercontent.com/20282546/124603236-569ccd00-de87-11eb-8bbf-2bcfaeb18707.png">

**Comment by markerikson** [comment]
We've mostly tried to keep RTK IE11-compatible so far, but that only extends to syntax.  Pretty sure we also use some `Set`s internally too. I'd recommend polyfilling `Symbol` here.

Note that in an upcoming RTK 2.0 release, we'll be dropping any built-in compat for IE11 - it'll be up to you to transpile and polyfill yourself.

**Comment by sibiraj-s** [comment]
I agree with you, I have added the polyfill for now. 

But shouldn't this be a part of semver major? Assuming `toolkit` follows semver?

**Comment by markerikson** [comment]
We try to follow semver, but semver is always kinda shaky. What exactly constitutes a "breaking change", really? :)

In this case, we're using legal JS syntax and data types. This runs fine in browsers that _aren't_ IE11. So, no, I don't see this as a breaking change.

**Comment by sibiraj-s** [comment]
>  If you are planning to drop IE11 compatibility, you should be able to modify your bundler config to import the modern artifact instead...

I was confused by this. This still implies that there IE11 support. May be updating the release notes will be helpfull.

**Comment by markerikson** [comment]
We haven't had a formal policy, but we've maintained nominal IE11 support by compiling our syntax to ES5 so that the _syntax_ ought to work in IE11.

As I said, I'm pretty sure we've already been using some built-in data types like `Set`s that don't exist in IE11.  So, it's the end user's responsibility to ensure that things like that are polyfilled.

**Comment by sibiraj-s** [comment]
Thanks @markerikson
