### ISSUE TITLE
Auth header

### ISSUE THREAD

**Issue by vaqif14** [reduxjs/redux-toolkit#1256]
I want to add auth token to header in documatation of rtkquery example i get prepareHeaders from example but it doesnt work.
```
prepareHeaders: headers => headers.set('authentication', `Bearer ${​​​​​token}​​​​​`), 
```

**Comment by markerikson** [comment]
`prepareHeaders` expects that you return the `headers` value itself.  I don't think that `headers.set()` returns `headers`.  I'd recommend not using an implicit arrow function return here.
