### ISSUE TITLE
RTKQ: getDefaultMiddleware is not a function

### ISSUE THREAD

**Issue by MarcelPawlo** [reduxjs/redux-toolkit#1266]
Hi

I was following the RTK Query Quick Start and got an error by adding the api middleware to my store. 

![grafik](https://user-images.githubusercontent.com/24190670/124904662-882baa80-dfe5-11eb-8e80-f2df6f8984f6.png)

I've the suspicion that some functions like transformResponse do not work without the middleware. Any ideas?

Thank you in advance

**Comment by phryneas** [comment]
You have specified `middleware` as a child of `reducers`, but it is an option that needs to be nested less deep.

**Comment by MarcelPawlo** [comment]
Omg, thanks a lot!
