### ISSUE TITLE
RTK Query Code Splitting removes all states

### ISSUE THREAD

**Issue by Eskaaa** [reduxjs/redux-toolkit#1268]
Hello, 

Imagine I have two endpoints extending an API that I have built. I already use createSlice for my redux store.

- ./src 
- ./src/store.ts
- ./src/emptyApi.ts
- ./src/endpoints/EndpointA.ts
- ./src/endpoints/EndpointB.ts
- ./src/slices/MySliceC.ts

As soon as I call an automatically generated hook on an API endpoint, my application terminates because the slices, reducers and selectors in my application no longer work.

```
import {useApiEndpoint} from 'src/endpoints/EndpointA';


function Component() 
{
   const results = useApiEndpoint();
}
```

Here is my exception stack: 

```

Uncaught (in promise) TypeError: Cannot read property 'menuOpen' of undefined
    at selectors.ts:9
    at index.js:70
    at index.js:30
    at index.js:84
    at index.js:30
    at wrappedSelector (redux-toolkit.esm.js:105)
    at useSelectorWithStoreAndSubscription (useSelector.js:29)
    at useSelector (useSelector.js:125)
    at useMenuOpenSelect (useMenuOpenSelect.tsx:11)
    at Menu (Menu.tsx:42)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
    at renderRootSync (react-dom.development.js:22670)
    at performSyncWorkOnRoot (react-dom.development.js:22293)
    at react-dom.development.js:11327
    at unstable_runWithPriority (scheduler.development.js:468)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
    at flushSyncCallbackQueue (react-dom.development.js:11309)
    at batchedUpdates$1 (react-dom.development.js:22387)
    at Object.notify (Subscription.js:19)
    at Subscription.notifyNestedSubs (Subscription.js:90)
    at Subscription.handleChangeWrapper (Subscription.js:95)
    at Object.dispatch (redux.js:297)
    at dispatch (<anonymous>:3856:17)
    at rtk-query.esm.js:1279
    at rtk-query.esm.js:1177
    at rtk-query.esm.js:1137
    at rtk-query.esm.js:1051
    at rtk-query.esm.js:1000
    at rtk-query.esm.js:962
    at rtk-query.esm.js:1336
    at rtk-query.esm.js:1365
    at middleware.js:26
    at redux-toolkit.esm.js:382
    at index.js:11
    at redux-toolkit.esm.js:310
    at dispatch (redux.js:659)
    at redux-toolkit.esm.js:1141
    at step (redux-toolkit.esm.js:38)
    at Object.next (redux-toolkit.esm.js:19)
    at fulfilled (redux-toolkit.esm.js:69)
(anonymous) @ selectors.ts:9
(anonymous) @ index.js:70
(anonymous) @ index.js:30
(anonymous) @ index.js:84
(anonymous) @ index.js:30
wrappedSelector @ redux-toolkit.esm.js:105
useSelectorWithStoreAndSubscription @ useSelector.js:29
useSelector @ useSelector.js:125
useMenuOpenSelect @ useMenuOpenSelect.tsx:11
Menu @ Menu.tsx:42
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
batchedUpdates$1 @ react-dom.development.js:22387
notify @ Subscription.js:19
notifyNestedSubs @ Subscription.js:90
handleChangeWrapper @ Subscription.js:95
dispatch @ redux.js:297
dispatch @ VM207:3856
(anonymous) @ rtk-query.esm.js:1279
(anonymous) @ rtk-query.esm.js:1177
(anonymous) @ rtk-query.esm.js:1137
(anonymous) @ rtk-query.esm.js:1051
(anonymous) @ rtk-query.esm.js:1000
(anonymous) @ rtk-query.esm.js:962
(anonymous) @ rtk-query.esm.js:1336
(anonymous) @ rtk-query.esm.js:1365
(anonymous) @ middleware.js:26
(anonymous) @ redux-toolkit.esm.js:382
(anonymous) @ index.js:11
(anonymous) @ redux-toolkit.esm.js:310
dispatch @ redux.js:659
(anonymous) @ redux-toolkit.esm.js:1141
step @ redux-toolkit.esm.js:38
(anonymous) @ redux-toolkit.esm.js:19
fulfilled @ redux-toolkit.esm.js:69
Promise.then (async)
(anonymous) @ rtk-query.esm.js:1422
(anonymous) @ index.js:8
(anonymous) @ redux-toolkit.esm.js:310
dispatch @ VM207:14608
(anonymous) @ rtk-query-react.esm.js:102
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
performSyncWorkOnRoot @ react-dom.development.js:22269
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
Show 19 more frames

```

Personally, I think it's a not good that there isn't an working example of this not uncommon use case on the website 
The [React Hooks](https://redux-toolkit.js.org/rtk-query/usage/examples#react-hooks)-Example uses ```@rtk-incubator/rtk-query``` instead of ```@reduxjs/toolkit/query/react```.

 In ```@reduxjs/toolkit/query/react``` is no exported member ```ApiWithInjectedEndpoints```. 

The source code from the [sandbox](https://codesandbox.io/s/rtk-query-demo-lbp7n?file=/src/App.tsx) cannot be copied and pasted either. Numerous attempts to find and fix the errors did not work for me. 

My used packages
```

{
    "@reduxjs/toolkit": "^1.6.0",
    "@testing-library/jest-dom": "latest",
    "@testing-library/react": "latest",
    "@testing-library/user-event": "latest",
    "@types/react-router-dom": "^5.1.7",
    "connected-react-router": "^6.9.1",
    "date-fns": "^2.22.1",
    "immer": "^8.0.1",
    "markdown-to-jsx": "^7.1.3",
    "prop-types": "^15.7.2",
    "react": "latest",
    "react-dom": "latest",
    "react-redux": "^7.2.4",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.3",
    "react-world-flags": "^1.4.0",
    "recharts": "^2.0.9",
    "redux": "^4.1.0",
    "styled-components": "latest",
    "typescript": "latest"
  
```

My tsconfig

```

{
  "compilerOptions": {
    "target": "ES2015",
    "module": "esnext",
    "jsx": "react-jsx",
    "noEmit": true,
    "strict": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "removeComments": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "skipLibCheck": true,
    "sourceMap": true
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules"
  ]
}


```

I hope you can help me solve the problem.

**Comment by phryneas** [comment]
How do you setup your store - what does your `configureStore` look like?

**Comment by Eskaaa** [comment]
> How do you setup your store - what does your `configureStore` look like?

```

import {configureStore as configureStoreToolkit} from '@reduxjs/toolkit';
import {routerMiddleware} from 'connected-react-router';
import {createBrowserHistory} from 'history';
import {PreloadedState} from 'redux';
import createRootReducer from './reducers';
import emptyApi from './emptyApi';

/**
 * History instance.
 */
const history = createBrowserHistory()

/**
 * Configure redux store.
 *
 * @param preloadedState
 */
const configureStore = (
    preloadedState?: PreloadedState<{} | undefined>
) => (configureStoreToolkit({
    devTools: process.env.NODE_ENV !== 'production',
    middleware: (
        getDefaultMiddleware
    ) => (
        getDefaultMiddleware().concat(
            routerMiddleware(
                history
            ),
        ).concat(
            emptyApi.middleware,
        )
    ),
    preloadedState,
    reducer: createRootReducer(
        history
    ),
}))

export {
    history,
};

export default configureStore;

```

My reducers:

```

import {connectRouter} from 'connected-react-router';
import {History} from 'history';
import {combineReducers} from 'redux';
import {themeReducers} from "../../theme";
import endpointApi from './endpointApi';


/**
  * tyhe export of themeReducers looks like
  */
const themeReducersExample = {
    [name]: reducers,
};

/**
 * 
 * @param history
 */
const createRootReducer = (
    history: History
) => combineReducers({
    router: connectRouter(
        history,
    ),
    ...themeReducers,
    [endpointApi.reducerPath]: endpointApi.reducer,
});

export defau

```


My slice


```

import {createSlice, PayloadAction} from '@reduxjs/toolkit';
import {mediaPrefersDarkScheme} from '../utilities';

export interface ThemeState {
    darkMode: boolean,
}

const initialState: ThemeState = {
    darkMode: mediaPrefersDarkScheme(),
};

const slice = createSlice({
    name: 'theme',
    initialState,
    reducers: {
        darkModeSet(
            state,
            action: PayloadAction<boolean>
        ) {
            state.darkMode = action.payload;
        },
        darkModeToggle(
            state,
        ) {
            state.darkMode = !state.darkMode;
        },
    },
});

const name = slice.name

export {
    name,
};

export default slice;

```

**Comment by phryneas** [comment]
Hmm. And the file with the `Provider`?

**Comment by Eskaaa** [comment]
Sorry for the late reply, I did not receive any notification this time.

```

import React, {PropsWithChildren} from 'react';
import {Provider} from 'react-redux';
import configureStore from './configureStore';
import {PreloadedState} from 'redux';
import { setupListeners } from '@reduxjs/toolkit/query/react';

/**
 *
 */
const store = configureStore();

/**
 *
 * @param children
 * @param initialState
 * @constructor
 */
const Redux = (
    {
        children,
    }: PropsWithChildren<{initialState?: PreloadedState<{}>}>
) => {
    return (
        <Provider store={store}>
            {children}
        </Provider>
    );
};


setupListeners(store.dispatch);

export default Redux;

```


In the meantime, I think the error doesn't occur when I remove the setupListeners.

I just don't understand why and how to use it instead.

So far I haven't been able to test it sufficiently.

**Comment by phryneas** [comment]
That does not make any sense as none of all these things interfere with normal Redux being normal Redux. Unfortunately from your examples I don't spot any obvious glaring errors. Can you share a CodeSandbox that reproduces your problem?

**Comment by Eskaaa** [comment]
I tried to illustrate the problem with the examples. Unfortunately, the code is too complex to be quickly provided in a sandbox.

The problem is actually that the [examples](https://redux-toolkit.js.org/rtk-query/usage/examples) in the documentation cannot be executed with redux-toolkit, they still use ['@rtk-incubator/rtk-query'](https://codesandbox.io/s/rtk-query-demo-lbp7n?from-embed=&file=/src/app/services/split/index.ts). 

It is a bit painful to understand and use the full functionality. When to use redux-toolkit and when to use @rtk-incubator/rtk-query. How exactly does it work with code splitting and the caching. 
How to use related data in a single query. 

maybe somebody can provide a detailed example with redux toolkit and [Code Splitting](https://redux-toolkit.js.org/rtk-query/usage/code-splitting).

**Comment by phryneas** [comment]
Always use `@reduxjs/toolkit`. I just merged an example using code splitting for graphql:
https://github.com/reduxjs/redux-toolkit/tree/master/examples/query/react/graphql-codegen/src

In general though:
A RTKQ-Api interacts in two ways with your Redux store: 
* A reducer. A reducer can ony take influence of it's own structure.
* A middleware. A middleware can not change your store structure in any way.

So it just plain impossible that doing anything with RTKQ changes your store structure, resets it or anything else. RTKQ does no magic, it it normal Redux. A reducer and a middleware.

**Comment by phryneas** [comment]
My assumption is that your "loading extracted code" somehow makes your 
`const store = configureStore();` re-execute, which would leave you with a new store instance.
But that's probably more of a tooling bug than it has anything to do with Redux itself.

**Comment by Eskaaa** [comment]
Thank you, I will take a deper look in this example, maybe I can use it somehow to learn from it.
I also think the error is on my side. 
As I told, I tried to rebuild something like [this](https://codesandbox.io/s/rtk-query-demo-lbp7n?from-embed=&file=/src/app/services/split/index.ts:0-95) 

```

import { createApi, fetchBaseQuery, ApiWithInjectedEndpoints } from '@rtk-incubator/rtk-query';

export interface Post {
  id: number;
  name: string;
}

export type PostsResponse = Post[];

export const emptySplitApi = createApi({
  reducerPath: 'splitApi',
  baseQuery: fetchBaseQuery({ baseUrl: '/' }),
  entityTypes: ['Posts'],
  endpoints: () => ({}),
});

export const splitApi = emptySplitApi as ApiWithInjectedEndpoints<
  typeof emptySplitApi,
  [
    // these are only type imports, no runtime imports -> no bundle dependence
    typeof import('./posts').apiWithPosts,
    typeof import('./post').apiWithPost
  ]
>;


```


This as example, ApiWithInjectedEndpoints is not exported from ```@reduxjs/toolkit/query/react```, Fulltext search can find it only in exported documentation (\packages\toolkit\etc\rtk-query-react.api.md).

The documentation says in several places that it is important to use an API (createApi) for a domain. And that all endpoints should be split into individual files. That's good, and that's how I want to do it. But there is absolutely no documentation or an example that describes this in detail. I found out a lot about trial and error. Perhaps because of this, maybe mistakes crept into my source code. 

Another example, 

```

/** 
  * Doeas not work without ts-ignore, why?
  */
// @ts-ignore
providesTags: (
    result,
    error,
    id
) => [{
    type: 'MyTag',
    id: id,
}],

```

I'm also sorry to waste your time and I'm relatively new to TypeScript, but I think better examples and updated documentation would have helped a lot. I think most of the users of this package would like to use it with more than one endpoint and relations between the data sets. Furthermore, I am grateful for your effort and this project.

**Comment by phryneas** [comment]
`ApiWithInjectedEndpoints` has been removed. You don't need that. That example you are referring to was showing two different approaches, one which has been dropped.

Really, all you need to do is exactly what [The Code Splitting Docs](https://redux-toolkit.js.org/rtk-query/usage/code-splitting) are showing, not a thing more:

* define an empty api. Export as `emptySplitApi`.
* in another file, 
  * `import {emptySplitApi} from` ....
  * `const extendedApi = emptySplitApi.injectEndpoints({`
  * `export const { useExampleQuery } = extendedApi`
* when using `useExampleQuery`, import it from that extended file.


As for your TypeScript error: without knowing the error, I can't help with that.

**Comment by Eskaaa** [comment]
Okay, thank you, this information helps a lot.


This is the type error:

```

TS2322: Type '() => { type: string; id: string; }[]' is not assignable to type 'ResultDescription<never, CountResponse, BrowseParamsOptional, FetchBaseQueryError> | undefined'.

```

**Comment by phryneas** [comment]
For one, you need to declare the `tagType` in your `createApi` call or with your `injectEndpoints` call.

Also, your TS seems to cast your `type` to `string`, so mark it `as const`
```ts
[{
    type: 'MyTag' as const,
    id: id,
}],
```

**Comment by Eskaaa** [comment]
I edited my last post and added a more detailed example. The types are listed because they are distributed over several locations and are actually imported.

**Comment by Eskaaa** [comment]
```

const tagType = 'MyEndpoint';

providesTags: (
                result: MyEndpointAttributes| undefined,
                error,
                params
            ) => {
                return [{
                 
                    type: tagType as const,      
                    id: params.code,
                }];
            },

```

>  // Error: // A 'const' assertions can only be applied to references to enum members, or string, number, boolean, array, or object literals.

```

providesTags: (
                result: MyEndpointAttributes| undefined,
                error,
                params
            ) => {
                return [{
                    type: `${tagType}` as const,
                    id: params.code,
                }];
            },

```


> TS2322: Type '(result: MyEndpointAttributes | undefined, error: FetchBaseQueryError | undefined, params: BrowseParams & { code: string; }) => { ...; }[]' is not assignable to type 'ResultDescription<never, MyEndpointAttributes, BrowseParams & { code: string; }, FetchBaseQueryError> | undefined'.   Type '(result: MyEndpointAttributes | undefined, error: FetchBaseQueryError | undefined, params: BrowseParams & { code: string; }) => { ...; }[]' is not assignable to type 'GetResultDescriptionFn<never, MyEndpointAttributes, BrowseParams & { code: string; }, FetchBaseQueryError>'.     Type '{ type: "MyEndpoint"; id: string; }[]' is not assignable to type 'readonly FullTagDescription<never>[]'.       Type '{ type: "MyEndpoint"; id: string; }' is not assignable to type 'FullTagDescription<never>'.         Types of property 'type' are incompatible.           Type 'string' is not assignable to type 'never'.

**Comment by Eskaaa** [comment]
I also tried just copying one of the examples and using it. But here, too, comes this TypeScript error.
```examples/query/react/mutations/src/app/services/posts.ts```


```

getPosts: build.query<number, void>({
            query: () => 'count',
            providesTags: (
                result
            ) => [
                { type: 'Post', id: 'LIST' }
            ],
        }),

```


> TS2322: Type '(result: number | undefined) => { type: string; id: string; }[]' is not assignable to type 'ResultDescription<never, number, void, FetchBaseQueryError> | undefined'.   Type '(result: number | undefined) => { type: string; id: string; }[]' is not assignable to type 'GetResultDescriptionFn<never, number, void, FetchBaseQueryError>'.     Type '{ type: string; id: string; }[]' is not assignable to type 'readonly FullTagDescription<never>[]'.       Type '{ type: string; id: string; }' is not assignable to type 'FullTagDescription<never>'.         Types of property 'type' are incompatible.           Type 'string' is not assignable to type 'never'.

**Comment by phryneas** [comment]
```diff
export const emptySplitApi = createApi({
  reducerPath: 'splitApi',
  baseQuery: fetchBaseQuery({ baseUrl: '/' }),
-  entityTypes: ['Posts'],
+  tagTypes: ['Posts'],
  endpoints: () => ({}),
});
```

```diff
getPosts: build.query<number, void>({
            query: () => 'count',
            providesTags: (
                result
            ) => [
_                { type: 'Post', id: 'LIST' }
+                { type: 'Post' as const, id: 'LIST' }
            ],
        }),
```

**Comment by Eskaaa** [comment]
The last example helped me a lot, but it also leads to this error, that's only because **Post** in providesTags is not **Posts** from tagTypes in **createApi**.

> -                { type: 'Post', id: 'LIST' }
> +                { type: 'Posts' as const, id: 'LIST' }


My **tagType** also works now, but only as hardcoded string, not as variable and when I add it to **createApi**. In **enhanceEndpoints** it has no effect as far as I could test it. It works, but only with ts-ignore

**Comment by phryneas** [comment]
Well, `tagTypes` needs to list all possible tag types, so it would need to be `['Posts','Post'],` then.

Also, if you have multiple strings, you will have to give those a compatible type too, so not `string`, but `'Post' | 'Posts'` where you pass them in dynamically

**Comment by phryneas** [comment]
As for your edit: you need to add possible tag types first and then continue to work on the result of that. So,
```

// OR THIS approach
const enhanced = ApiEndpoint.enhanceEndpoints({
    addTagTypes: [
        'IsoLocales',
    ]
});
const injected = enhanced.injectEndpoints(...);

export const {...} = injected;
```

**Comment by Eskaaa** [comment]
Damn, your last comment solved the problem with the **providesTags**. 
I'm so happy and almost ashamed that I didn't make it myself.

**Comment by phryneas** [comment]
Well, you took the deep dive and did everything at once ;)

**Comment by Eskaaa** [comment]
That sounds exactly like me :)

When I finish it I'll try to take the time and provide a simple example of what I'm doing here. Maybe it will help another newcomer.
