### ISSUE TITLE
what is the proper string format for ignoreAction is serializableCheck

### ISSUE THREAD

**Issue by altruios** [reduxjs/redux-toolkit#1273]
specific issue:

https://stackoverflow.com/questions/68319564/what-is-the-proper-string-format-of-reduxs-getdefaultmiddlewares-property-ign

read through the docs. best I found for an example was:
```
//in redux docs on serializable data
       ignoredActions: ['your/action/type'],
```
which I define as
```
ignoredActions: ['server_sender/output'],
```
however I am still getting an error: the type of which is
```
index.js:1 A non-serializable value was detected in an action, in the path: //...
Take a look at the logic that dispatched this action:  {type: "server_sender/output" //...
```

I have tried several variations... I can't seem to get it to work.

**Comment by markerikson** [comment]
@altruios can you log the entire action, and show a screenshot of that here?

**Comment by altruios** [comment]
from console.log inside server_sender output.
```
{type: "server_sender/output", payload: Array(3)}
payload: Array(3)
0: "test"
1: {data: "initial state(sent to server)"}
2: Socket {receiveBuffer: Array(0), sendBuffer: Array(0), ids: 0, acks: {…}, flags: {…}, …}
length: 3
__proto__: Array(0)
type: "server_sender/output"
__proto__: Object
```

**Comment by altruios** [comment]
so this is moot: found away to do this without sending to the reducer. but curious as to why it was failing.

**Comment by markerikson** [comment]
Hmm. seems like that should have worked. Can you post a CodeSandbox that shows this happening?

**Comment by altruios** [comment]
Yes... hold on - saw this a bit late and had to dig though some commits - again: found a way around this: but this should have worked -- it would have been much fewer lines of code...


I can point you to a working repo - at the commit where works and is using that pattern (everything besides the error squashing)

...but it looks like in that commit... and in no commits did I save a "server_sender/output" in the ignore array... but this is a new projected - and i just didn't save the best example from this morning :(  just this tired brain's best attempt from night before... here's the commit and repo:

cleaner example:    2e1ffdd4016bf594b862ab6672f26a34c6cc68b8
repo: https://github.com/altruios/re-socket-dux

the only thing to do to match the code above is to replace the ignore array item with "server_sender/output" instead;

I'll post a min example sand box once I get one working after some sleep... 

I'm pretty sure also that I'm not going to do this pattern anyway - I think I found something I could extend further.

**Comment by msutkowski** [comment]
I can't recreate this. Make sure your store config looks similar to this:

```ts
export const store = configureStore({
  reducer: {
    counter: counterReducer,
  },
  middleware: (gDM) =>
    gDM({
      serializableCheck: {
        ignoredActions: ["server_sender/output"],
      },
    }),
});
```

**Comment by altruios** [comment]
reverting to the commit and trying that bit of code works!


And looking at the docs again... i still think this... should work?

```js
middleware: getDefaultMiddleware({    
         serializableCheck: {      
              ignoredPaths: ['server_sender/output'],      
          },  
     }),
```
however it does not?

**Comment by msutkowski** [comment]
> reverting to the commit and trying that bit of code works!
> 
> And looking at the docs again... i still think this... should work?
> 
> ```js
> middleware: getDefaultMiddleware({    
>          serializableCheck: {      
>               ignoredPaths: ['server_sender/output'],      
>           },  
>      }),
> ```
> 
> however it does not?

The issue here is the fn on middleware. I can't see your whole file, so I'm not sure if you're importing `getDefaultMiddleware` or not. Either way, I believe that is going to be deprecated and you need to just change it to:

```
// this is the important  part 👇👇👇👇👇
middleware: getDefaultMiddleware => getDefaultMiddleware({
         serializableCheck: {      
              ignoredPaths: ['server_sender/output'],      
          },  
     }),
     ```

**Comment by wiscgazf** [comment]
```
const userinfo = createSlice({
  name: 'server_sender',
  initialState: () =>({timer: null}),
  reducers: {
    output:{
      reducer(state, action: PayloadAction<{ timer: any }>){
        return { ...state, ...action.payload };
      },
      prepare() {
        return {
          payload: {
            timer: new Date(),
          },
        };
      }
    }
  },
});
middleware: getDefaultMiddleware => getDefaultMiddleware({
         serializableCheck: {      
              ignoredActions: ['server_sender/output'],    
              ignoredPaths: ['server_sender.timer']
          },  
     }),

/**
* ignoredActions and ignoredPaths uses them both together
* ignoredActions --> action path
* ignoredPaths --> initState [key]
*/
```
