### ISSUE TITLE
RTKQ: 201 no-content response throws because serialization fails

### ISSUE THREAD

**Issue by donatoaguirre24** [reduxjs/redux-toolkit#1278]
I have a mutation that returns 201 no-content responses. 

RTKQ returns the following error for success responses because the response serialization throws.

```JSON
{
  "message": "JSON Parse error: Unexpected EOF",
  "name": "SyntaxError", 
  "stack": ...
}
```

I managed to fixed it with the following workaround:

```JS
forgotPassword: builder.mutation({
  query: ({ email }) => ({
    url: authRoutes.forgotPassword,
    responseHandler() {}, // skips serialization
    method: 'POST',
    body: { email },
  }),
}),
```

probably the [handleResponse](https://github.com/reduxjs/redux-toolkit/blob/79850912059c1502fd3c9b2c00242ee1e2c8a43e/packages/toolkit/src/query/fetchBaseQuery.ts#L43) function should have a null check:

```js
const handleResponse = async (
  response: Response,
  responseHandler: ResponseHandler
) => {
  if (typeof responseHandler === 'function') {
    return responseHandler(response)
  }

  if (responseHandler === 'text') {
    return response?.text() ?? null // same here
  }

  if (responseHandler === 'json') {
    const text = await response?.text() ?? [] // maybe something like this or a simple if/else
    return text.length ? JSON.parse(text) : undefined
  }
}
```

@markerikson @phryneas or @msutkowski, if you guys can confirm that this is not what you intended, and give me some guidance on the desired solution, I can try to make a PR fixing it.

**Comment by msutkowski** [comment]
Part of this was addressed in https://github.com/reduxjs/redux-toolkit/pull/1250, which isn't released yet.

**Comment by donatoaguirre24** [comment]
> Part of this was addressed in #1250, which isn't released yet.

Great! If I'm not mistaken, the PR adds error handling but doesn't prevent the error from happening. 

Is it correct to throw an error for successful responses without a response body?

**Comment by phryneas** [comment]
if the response body is completely empty, it should already return `undefined`:
```
return text.length ? JSON.parse(text) : undefined
```

**Comment by donatoaguirre24** [comment]
@phryneas I just found the issue. The response body is actually a `" "` (whitespace) so the length isn't 0, and the `JSON.parse` throws an error. 

Clearly, this is a problem with our code and is not related to RTKQ 🤦🏻. Until the backend team solves this, I'll handle it using: `responseHandler: 'text'`

Sorry for the confusion, and thanks for the help!

**Comment by msutkowski** [comment]
I suppose we could trim this?

**Comment by markerikson** [comment]
or maybe only trim if `text.startsWith(' ')` ?

**Comment by msutkowski** [comment]
> or maybe only trim if `text.startsWith(' ')` ?

Yea, I'm honestly not sure of what the right thing to do here is because it's an unexpected server response. It's common to return a 200 with no body, but a body with a space is a little strange 😅. @phryneas any thoughts here?

**Comment by phryneas** [comment]
Well, assuming it is JSON, it would never have leading or trailing space, so we *could* trim it without invalidating/changing anything. But yeah, the question is if we should.
Programming errors like this, or just a non-content `echo` or `print` somewhere in the code happen and can introduce a newline or whitespace somewhere, so it seems like it might just make it more error-resilient. On the other hand, the question is: should we be? That error should better surface quickly. :thinking: 

Let's wait until a few more people report situations like this...? :laughing:
