### ISSUE TITLE
RTKQ 'Cannot read property 'apply' of undefined' in `executeEndpoint`

### ISSUE THREAD

**Issue by nicolas-chaulet** [reduxjs/redux-toolkit#1286]
Hi!
I am already a happy user of RTK and today I decided to give a shot to RTKQ but faced a challenge with the an error being thrown from RTKQ: `'Cannot read property 'apply' of undefined'`. This is thrown by the `executeEndPoint` method because `fulfillWithValue` is `undefined`. And just to be clear, the get request succeeds and I can log the returned data properly in the `transformResponse`. I have no idea how this can happen, any suggestion?
Below is the detail of my slice and store:
```slice.js
export const productsApi = createApi({
  reducerPath: "productsApi",
  baseQuery: fetchBaseQuery({
    baseUrl: `${apiUrl}/gateway`,
    prepareHeaders: (headers, { getState }) => {
      const token = (getState() as RootState).user.apiToken;
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }
      return headers;
    },
  }),
  endpoints: (builder) => ({
    getProduct: builder.query<IProduct, string>({
      query: (id: string) => `/products/${id}`,
      transformResponse: (d: IProduct) => {
        console.log(d);
        return d;
      },
    }),
    getKit: builder.query<IKit, string>({
      query: (id: string) => `/kits/${id}`,
    }),
  }),
});

```
```store.js
const store = configureStore({
  reducer: rootReducer,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      immutableCheck: false,
      serializableCheck: false,
    }).concat(productsApi.middleware),
  devTools: ACTIVATE_DEV_TOOLS,
});
setupListeners(store.dispatch);

```

**I am using RTK version 1.6.0**

**Comment by markerikson** [comment]
Can you show the rest of the stack trace, and hopefully also post a CodeSandbox that demonstrates this issue?

**Comment by phryneas** [comment]
A similar error usually happens when you have multiple apis with the same (or no) `reducerPath`, but doesn't seem to be the case here.

`fulfillWithValue` being `undefined` seem like you are using an older RTK version. Could there be multiple RTK versions be installed in your repo?

**Comment by nicolas-chaulet** [comment]
Thanks for the tips! I uninstalled and reinstalled rtk and now all is fine. Not sure why the upgrade did not work as expected...
