### ISSUE TITLE
TypeError: (0 , import_immer2.default) is not a function

### ISSUE THREAD

**Issue by nrakochy** [reduxjs/redux-toolkit#1297]
Hi there, 

Thanks for the great library. I ran into some failing tests and thought I would open a report. I have this in my package.json

```js
redux-toolkit: "^1.5.1"
```
upon deleting `yarn.lock` and regenerating, my Jest tests fell down. Reverting to `1.5.1` fixes them.

**Comment by markerikson** [comment]
I'm afraid this isn't really enough info for us to provide any help, other than the error message suggesting that the Immer import isn't working right.  After reinstalling things, did you actually have a copy of Immer installed into `node_modules` ?

**Comment by nrakochy** [comment]
Thanks for the note, and apologies on the sparse info. This was more of an fyi, as it also caused our CI to fail. Its *possible* that I borked the `yarn.lock` file on both local and remote, but I raised it just in case there's a new version released somewhere that is not building as expected.
