### ISSUE TITLE
useQuery refetch countlessly on api fail

### ISSUE THREAD

**Issue by tuannx2106** [reduxjs/redux-toolkit#1300]
First, I have to say that this library is great, saves me a ton of time and code lines.

But there is a critical issue, whenever you pass the param to useQuery hook with more than 2 levels of nested objects, it refetch countlessly.
![Screen Shot 2021-07-15 at 09 32 47](https://user-images.githubusercontent.com/36130241/125718879-d5826a8b-9379-4d5b-b287-e4d4a6b7bf57.png)

I have reproduced the issue on the Pokemon example as well. Please take a look at it:
https://codesandbox.io/s/friendly-darkness-3txlu?file=/src/App.tsx

**Comment by phryneas** [comment]
Heyo, that is a [documented pitfall](https://redux-toolkit.js.org/rtk-query/usage/queries#query-hook-options):

> caution
>
> The queryArg param is handed to a useEffect dependency array internally. RTK Query tries to keep the argument stable by performing a shallowEquals diff on the value, however if you pass a deeper nested argument, you will need to keep the param stable yourself, e.g. with useMemo.
