### ISSUE TITLE
How to do Unit Testing with RTK Query and redux-mock-store?

### ISSUE THREAD

**Issue by shikelong** [reduxjs/redux-toolkit#1301]
redux-mock-store not support pass reducers like rtk query's apiReducer into the mocking store.  so should I only mock useXXXQuery method when i write test case for Component? 

And should i test my code that creating api?

```typescript
const DemoApi = mockServiceApi.injectEndpoints({
  endpoints: (builder) => ({
    getDemoData: builder.query<IDemoItem[], void>({
      query: () => ({
        url: 'Demo/getDemoData',
        requestConfig: {
          method: 'GET',
        },
        customRequestConfig: {
          isAutoLoading: false,
        },
      }),
      transformResponse: (response: ServiceResponse<IDemoItem[]>) => {
        return response.data;
      },
    }),
    saveDemoData: builder.mutation<ServiceResponse<any>, SubmitModel>({
      query: (data) => {
        return {
          url: 'Demo/saveDemoData',
          requestConfig: {
            method: 'POST',
            data,
          },
        };
      },
    }),
  }),
  overrideExisting: true,
})
```

Thanks. 😊

**Comment by phryneas** [comment]
The api reducer is just a reducer - there is no difference to any other reducer in your codebase, so theoretically you can use it in tests the same way.

That said, I wouldn't use `redux-mock-store` in the tests, but just an instance of your fully configured real store and I wouldn't mock the hooks, but either something like `msw` to mock the api, or inject override your endpoints with a `queryFn` that just returns the desired value.

**Comment by shikelong** [comment]
Thank you!,  I got it.
