### ISSUE TITLE
RTKQ: Dependent query clarification

### ISSUE THREAD

**Issue by orshick** [reduxjs/redux-toolkit#1306]
In the comparison between similar libraries page on the [RTKQ site](https://redux-toolkit.js.org/rtk-query/comparison#comparing-feature-sets) "Dependent queries" are listed as being supported by each library. In [another issue](https://github.com/reduxjs/redux-toolkit/issues/1227), it was suggested that to do something similar I could simply use both queries and use a skipToken in the dependent one until the first one is done fetching. Is RTKQ considered to support dependent queries by having this api call skipping functionality?

I saw the `queryFn` [section ](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#performing-multiple-requests-with-a-single-query)on the site, but it seems it wouldn't let me leverage the api endpoints I've already defined elsewhere in the app.

When I saw dependent queries support, I was anticipating that there would be a way to define a dependency in `createApi`, and even use the data returned from the dependencies. Was a mistaken, or have I just missed something?

For context, the use-case I'm working on right now requires me to make 3 sequential requests in different places.
1. fetch data about a user.
2. fetch more data with this user information, to set a header for future requests
3. make a new requests that needs the header from step 2 to be in place

My current solution is to use a useEffect to lazily call api2, and then when complete to set value in the redux store that it's been set. Then I use a useEffect to call api3. This works, but doesn't seem safe since api3's dependencies are not explicit.

Thanks!

**Comment by phryneas** [comment]
AFAIK, all the libraries in that table solve dependent queries doing some kind of skip option. I think React-Query started calling it "dependent queries" and we just took their term.

The other way of doing it, as you noticed correctly, is calling `baseQuery` multiple times in a `queryFn`, but that will collapse all those into one cache key, so if you make a new iteration of query 3, nr. 1 and 2 have to run again, too.

So I'd just suggest going for the "three useQuery calls with skipToken" route. It will usually be safer than multiple hand-written useEffect calls.

**Comment by orshick** [comment]
Thanks for the reply! In that case, there are two things I'm wondering about:

1. Is something wrong with how I'm using skip token? I'm seeing errors that I'm putting a non serializable piece of data by putting in skip token as an argument into a query
2. Is there a way to use this skipToken pattern (or even the useEffect pattern) when the queries are spread between different files? I see that I can subscribe to the query state of another query, but I'd also have to then have the arguments for that query in this file as well, which is tighter coupling than I'm comfortable with. If I only want to have one piece of query results from an endpoint in memory at a given time, would I simply have to crate a slice and put it there as a side-effect of doing a successful fetch request?

Thanks again!

**Comment by phryneas** [comment]
As for 1., you already found the answer to that in #1308, just documenting that here for other readers in the future :)

As for 2., I would probably more put the arguments to that query into a slice and wrap your autogenerated hook into a custom one that also does a `useSelector` to get the right args.

**Comment by phryneas** [comment]
Generally, you could probably also use a lifecycle with `invoke` :thinking: 

Adjusted example from the "streaming updates" docs page:

```js
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

export const api = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: '/' }),
  endpoints: (build) => ({
    getMessages: build.query<Message[], Channel>({
      query: (channel) => `messages/${channel}`,
      async onCacheEntryAdded(
        arg,
        { updateCachedData, cacheDataLoaded, cacheEntryRemoved, dispatch }
      ) {
        let subscription;
        try {
          // wait for the initial query to resolve before proceeding
          await cacheDataLoaded

          // trigger other endpoint, creating a subscription 
          subscription = dispatch(api.endpoints.other.invoke(args))
        } catch {
          // no-op in case `cacheEntryRemoved` resolves before `cacheDataLoaded`,
          // in which case `cacheDataLoaded` will throw
        }
        // cacheEntryRemoved will resolve when the cache subscription is no longer active
        await cacheEntryRemoved

	    // unsubscribe the other endpoint
        if (subscription) { subscription.unsubscribe() }
      },
    }),
  }),
})

export const { useGetMessagesQuery } = api

**Comment by orshick** [comment]
Whoa, this is really cool. I'm guessing you mean using the `initiate` method, not `invoke` (which wasn't on the endpoint). Using `getCacheEntry` from the 2nd argument object I'd be able to actually sequence a bunch of api calls that depend on data from the previous call, and then I suppose use them with `useQueryState`.

Unfortunately this isn't quite appropriate for my case as I'm trying to have a query that runs only in some instances after query 1 and 2, but isn't called on each page. Queries 1 and 2 however are called on each page. I think your suggestion of wrapping the `useQuery` hook for the api with dependencies into a new hook that would encapsulate this dependency is probably the right one, though not sure how to write it just yet. Going to give it a shot and post here if I find a working pattern.

For the record, in the mean time I've gotten around this issue by having a page wrapper component that handles the required queries, and simply does not render any of its sub pages until the queries all they depend on have been fetched.

**Comment by orshick** [comment]
OK, the wrapping pattern totally works. I did something like:

```ts
const useApiWithDependency = () => {
  const { data: api1data } = api.useApi1Query()
  const { data: api2data } = api.useApi2Query(
    api1data ? api1data.foo : skipToken,
  )
  return api.useApi3Query(
    api1data && api2data ? { bar: api2data.baz } : skipToken,
  )
}
```

It's only a bit too bad though that this hook is going to be separate from the rest of the api calls, since I like to export the root api object and call hooks directly from it. And on top of that, it leaves the api that doesn't guarantee the dependency exposed for someone else to use. Oh well, I think this is the best I'm going to get right now. Thanks again for the help!
