### ISSUE TITLE
skipToken is non-serializable

### ISSUE THREAD

**Issue by CasperEngl** [reduxjs/redux-toolkit#1308]
Using RTK Query with `skipToken` when `projectId` is undefined results in the following error in the console.

```
A non-serializable value was detected in the state, in the path: `dashboardApi.queries.getProject(undefined).originalArgs`. Value: Symbol("skip selector") 
Take a look at the reducer(s) handling this action type: dashboardApi/executeQuery/fulfilled.
(See https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state)
```

Code: 
```
const { data: project } = useGetProjectQuery(projectId ?? skipToken)
```

Package versions:
```
{
  "@reduxjs/toolkit": "^1.6.0",
  "react-redux": "^7.2.4",
  "redux-persist": "^6.0.0"
}
```

**Comment by orshick** [comment]
Having the same issue in my project.

**Comment by justindomingue** [comment]
make sure you are importing from the right place: `import { skipToken } from '@reduxjs/toolkit/query/react'`

**Comment by phryneas** [comment]
Yup, the most likely reason for that is that you imported it from a wrong place and it is now a similar, but not the same, token that is not recognized by createApi.

**Comment by orshick** [comment]
Thanks! Yeah using that path works for me. Weird though, when I write `skipToken` in my code, intellisense pops up only one autoimport option, `@reduxjs/toolkit/dist/query`, and this one results in the non-serializable value error.

**Comment by phryneas** [comment]
We might just switch from `Symbol("skip token")` to `Symbol.for("RTK-Query skip token")` or something similar.
A PR would be welcome :)
