### ISSUE TITLE
RTKQ: File Uploading

### ISSUE THREAD

**Issue by ybelenko** [reduxjs/redux-toolkit#1315]
I use `queryFn` parameter to send `multipart/form-data`:
```js
endpoints: (build) => ({
  uploadFile: build.mutation({
    async queryFn(file, _queryApi, _extraOptions, fetchWithBQ) {
      // upload with multipart/form-data
      const formData = new FormData();
      formData.append('file', file);
      const response = await fetchWithBQ({
        url: '/files',
        method: 'POST',
        body: formData,
      }, _queryApi, _extraOptions);
      if (response.error) throw response.error;
      return response.data ? { data: response.data } : { error: response.error };
    },
  }),
}),
```

It works totally correct, but I have arguments serialization error in console:
```console
[Error] A non-serializable value was detected in the state, in the path: `api.mutations.EB07i6POmA2Xe9YPh5gpb.originalArgs`. Value: (2)
File {name: "message_saved.mp3", lastModified: 1625855746000, webkitRelativePath: "", size: 46478, type: "audio/mpeg", …}
"
Take a look at the reducer(s) handling this action type: api/executeMutation/rejected.
(See https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state)"
	(anonymous function) (main.js:5794)
	measureTime (main.js:5553)
	(anonymous function) (main.js:5789)
	(anonymous function) (main.js:5717)
	(anonymous function) (main.js:6546)
	step (main.js:5447)
	rejected (main.js:5486)
	promiseReactionJob
```

I tried to overwrite `serializeQueryArgs` option in `createApi` but it doesn't help. Can't even catch that request over there. It's weird that I see other GET requests inside `serializeQueryArgs`, but not that POST file mutation.
```js
serializeQueryArgs: (args) => {
  const { endpointName, queryArgs } = args;
  // try to overwrite uploadFile endpoint serialization
  if (endpointName === 'uploadFile') {
    const { lastModified, name, size, type } = queryArgs;
    const payload = JSON.stringify({
      lastModified, name, size, type,
    });
    return `${endpointName}(${payload})`;
  }

  // Sort the object keys before stringifying, to prevent useQuery({ a: 1, b: 2 }) having a different cache key than useQuery({ b: 2, a: 1 })
  return `${endpointName}(${JSON.stringify(queryArgs, (key, value) =>
    isPlainObject(value)
      ? Object.keys(value)
          .sort()
          .reduce((acc, key) => {
            acc[key] = value[key]
            return acc
          }, {})
      : value
  )})`;
},
```

Package version: `"@reduxjs/toolkit": "^1.6.0"`

**Comment by phryneas** [comment]
This is essentially #1239 - for now you need to blacklist that in the warnings, I'm sorry.

**Comment by ybelenko** [comment]
> This is essentially #1239 - for now you need to blacklist that in the warnings, I'm sorry.

So I cannot overwrite `serializeQueryArgs` to serialise file argument? It seems easy for me, size + client filename + media type might be unique enough string.

Reason why I want to use cache of mutation because I want to leverage `isLoading`, `isSuccess` return values instead of writing it with `useState` myself.
Or it's not related? I didn't check, maybe `isLoading` and `isSuccess` still usable even after non serializable value error.

**Comment by phryneas** [comment]
No, the return value of `serializeQueryArgs` is only used to calculate the cache key of queries. Now that you say it, it could really have been named better.

Right now this is just a warning, so everything will be usable as before. The only problem is that you now have a `File` in your Redux store, which is something that can cause problems with tools like redux-persist if you were to persist & restore that state. 

I'm in the process of opening a PR that will just keep `originalArgs` out of the store for mutations (which are regularly called with non-serializable data, just nobody did during our beta).

**Comment by phryneas** [comment]
See #1318 

You can already install it and try it following this link (contains instructions for npm and yarn): https://ci.codesandbox.io/status/reduxjs/redux-toolkit/pr/1318

Feedback welcome.

**Comment by markerikson** [comment]
Should be fixed in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.6.1

**Comment by hamzeloudev** [comment]
A utility package for integrating file upload/download with progress tracking into your Redux Toolkit Query API slices:

[rtk-upload-utils](https://www.npmjs.com/package/rtk-upload-utils)
