### ISSUE TITLE
[Enhancement] Remove store entities state in slice when not need it anymore - using createEntityAdapter

### ISSUE THREAD

**Issue by harrytran998** [reduxjs/redux-toolkit#1321]
When I use `createEntityAdapter` to normalize data and save it in the `slice`. It's OK! But I can not delete the entity which I use to contains the normalized data.

Bcs when I use `adapter.removeAll(state.something)` ==> It just clear the data and become the `adapter.getInitialState()` type. I want totally delete it from store.

Hopefully, someone can add this!

**Comment by markerikson** [comment]
I'm afraid I don't understand exactly what you're asking for here.  Can you give a more detailed example, preferably with some sample data showing what you want to happen?
