### ISSUE TITLE
FulfillWithMeta and RejectWithValue private _type makes ts typecheck fail

### ISSUE THREAD

**Issue by Grohden** [reduxjs/redux-toolkit#1323]
I know it's commented in the code about why a private readonly-never-read variable exists but:
https://github.com/reduxjs/redux-toolkit/blob/2ff1fa4364ce0dfa82dbbd3187aa0c63e57d5582/packages/toolkit/src/createAsyncThunk.ts#L69

Causes ts type checking (`tsc --noEmit`) to fail with:

```
node_modules/@reduxjs/toolkit/src/createAsyncThunk.ts:69:20 - error TS6133: '_type' is declared but its value is never read.

69   private readonly _type!: 'RejectWithValue'
                      ~~~~~

node_modules/@reduxjs/toolkit/src/createAsyncThunk.ts:81:20 - error TS6133: '_type' is declared but its value is never read.

81   private readonly _type!: 'FulfillWithMeta'
```

`@reduxjs/toolkit: 1.6.1`

> Note: I'm in a react native env

I'm also getting other errors.... maybe I have some incorrect peer dep (but I don't see any warning on install)?
<details>

```
node_modules/@reduxjs/toolkit/src/createAsyncThunk.ts:510:13 - error TS2322: Type '{ aborted: false; addEventListener(): void; dispatchEvent(): boolean; onabort(): void; removeEventListener(): void; }' is not assignable to type 'AbortSignal'.
  Object literal may only specify known properties, and 'addEventListener' does not exist in type 'AbortSignal'.

510             addEventListener() {},
                ~~~~~~~~~~~~~~~~

node_modules/@reduxjs/toolkit/src/createAsyncThunk.ts:540:32 - error TS2339: Property 'addEventListener' does not exist on type 'AbortSignal'.

540         abortController.signal.addEventListener('abort', () =>
                                   ~~~~~~~~~~~~~~~~
```

This is probably because the abort signal is from react-native instead of the webworker/dom

Here's the RN declaration (`@types/react-native: 0.64.2`) :
```typescript
declare class AbortSignal {
    /**
     * AbortSignal cannot be constructed directly.
     */
    constructor();
    /**
     * Returns `true` if this `AbortSignal`'s `AbortController` has signaled to abort, and `false` otherwise.
     */
    readonly aborted: boolean;

    onabort: (event: AbortEvent) => void;
}
```

Edit: changing the RN types to `0.64.12` (which may be dangerous.. I'm in RN `0.61.4`) seems to change the error.. now what doesn't seems to exist is the `dispatchEvent` 😢 .. I will make a patch package for that

</details>

Edit: any info needed just ask :D

**Comment by phryneas** [comment]
You should generally not be checking the source code of external libraries as that will 
* make your compilation process incredibly slow
* give you errors such as this when your `tsconfig.json` differs from the libraries `tsconfig.json` (which is the case here)
 
Fix: `skipLibCheck: true` in your `tsconfig.json`

**Comment by Grohden** [comment]
@phryneas yeah, but that may omit 'real' version/conflict issues... 

I recall having some issues due to incorrect types imported from incompatible libs (lib `A` depends on lib `B` type, but `B` version `x.y.z` doesn't have `X` type, so `A` type `Y = X` becomes `any` and leaks silently somewhere), that resulted in some `any`s leaking into my type checking, so that's why I'm not using `skipLibCheck: true`

**Comment by phryneas** [comment]
Well, you can also just exclude all `src` folders in your `node_modules`. Since these are not our distributed types, but, well, the sources. You definitely should not be checking those.

**Comment by Grohden** [comment]
@phryneas oooh :O 

Now I see, it's type checking wrong directories instead of only the ones pointed in the `types` section... thanks for pointing that out!
