### ISSUE TITLE
getDefaultMiddleware deprecated

### ISSUE THREAD

**Issue by honzahruby** [reduxjs/redux-toolkit#1324]
What's the reason to deprecate and eventually remove this function? I was only able to find https://github.com/reduxjs/redux-toolkit/issues/958#issuecomment-875538589 as a reasoning. We're using it for dependency injection in thunks and due to code-splitting, we need to do it post store creation (using `redux-dynamic-middlewares`). I don't see any way to do this using the callback notation. Is there any chance of this function not being removed? Great job with the library, by the way, thank you!

**Comment by markerikson** [comment]
The reasons are:

- `getDefaultMiddleware` was originally _just_ a separate export - we added the callback form of the `middleware` option that receives `getDefaultMiddleware` as its argument later.  That callback completely supersedes the reason to use the imported version
- In addition, the callback form has better type behavior than the import version

Can you give a specific example of where and how you're using the export version?

**Comment by honzahruby** [comment]
To give you some more context:
- 90% of our functionality is behind oauth login while storing the token in redux
- we inject generated API clients as thunk extra argument

The flow goes like this:
1. create a minimal store with a subset of reducers and `redux-dynamic-middlewares` as the only middleware
2. log in, lazily load inner-app components and their side-effects
3. enhance the store with all reducers and inject more middlewares, including the ones from `getDefaultMiddleware`

Because of the size of the injected thunk arguments, I want to avoid doing it in step 1, if that makes sense 🙂

**Comment by markerikson** [comment]
Hmm. I'm not clear on why you need to re-add the default middleware if you're using something like `redux-dynamic-middleware`.

I would expect that those only need to be defined and added once, and then `redux-dynamic-middleware` would let you add and remove middleware _after_ those without touching any of the defaults.

If you could put together some kind of a sandbox or something that demonstrates this, it would help me understand how this is supposed to behave.

**Comment by honzahruby** [comment]
Because I want to set up the thunk middleware after creating the store (not immediately in `configureStore`). 

What I can do as a workaround is to use the `getDefaultMiddleware` callback with `thunk: false` and add it later as a standalone middleware.

I'll try to prepare a sandbox.

**Comment by markerikson** [comment]
Yeah, that's part of what I don't understand. I can't see any reason to delay loading the thunk middleware, especially if you're modifying the list of middleware later.

Oh. You did say something about injecting an API client.

Mmm... what if you added the thunk middleware on startup, but gave it something like a `getApiClient` function as the extra argument that would let you set up the client later?

And yeah, skipping the thunk middleware on startup and then creating it yourself later would also be an option.

**Comment by honzahruby** [comment]
Yeah, the only reason is the stuff we're injecting as `extraArgument`. It's quite big and there's no benefit in loading & injecting it immediately, only after the user is logged in and the app is initialized. 

I agree this is not a common use case but having `getDefaultMiddleware` as a standalone export provides more flexibility than just the callback notation.

**Comment by phryneas** [comment]
> I agree this is not a common use case but having getDefaultMiddleware as a standalone export provides more flexibility than just the callback notation.

But also encourages a big chunk of our users to use an api that gives them less type safety and hurts them in the long run.

**Comment by markerikson** [comment]
Also true, and the corollary to that argument is that RTK is meant for the "80% use case" and to push people towards "correct Redux usage".
