### ISSUE TITLE
Trying to move my old redux react app to redux toolkit and typescript.

### ISSUE THREAD

**Issue by luluhoc** [reduxjs/redux-toolkit#1328]
Hey to all, I'm totally new to the redux-toolkit and still learning it, I'm kind of blocked at this step as I don't know how to implement  it with redux-toolkit.

I have a system of toasts build in my redux store and this was my action.

MY Action
===
```
const setAlert = (msg, alertType, timeout = 5000) => (dispatch) => {
  const id = uuidv4();
  dispatch({
    type: SET_ALERT,
    payload: { msg, alertType, id },
  });

  setTimeout(() => dispatch({ type: REMOVE_ALERT, payload: id }), timeout);
};
```

My Old reducer 
===
```
export default function (state = initialState, action) {
  const { type, payload } = action;

  switch (type) {
    case SET_ALERT:
      return [...state, payload];
    case REMOVE_ALERT:
      return state.filter((alert) => alert.id !== payload);
    default:
      return state;
  }
}
```

I was thinking about creating a react component to render when an alert array is longer than 0 with useEffect but I think it would be overkill. 

I was thinking also about creating createAsyncThunk action but I need to return the value of the alert so I can't set setTimeout as the function would return.

Is there a way to get the dispatch function in the reducer so it would dispatch removeAlert after timeout? 

```
const alertSlice = createSlice({
  name: 'alert',
  initialState,
  reducers: {
    setAlert(state, action) {
      const id = uuidv4();
      [...state, action.payload];
      toast[action.payload.alertType](msg);
      setTimeout(() => dispatch(removeAlert(id)), timeout);
    },
    removeAlert(state, action) {
      return state.filter((alert) => alert.id !== action.payload);
    },
  },
});
```

**Comment by markerikson** [comment]
The right answer would be to do this as part of a hand-written thunk:

https://redux.js.org/usage/writing-logic-thunks#async-logic-and-side-effects
