### ISSUE TITLE
Set auth0 access token in header

### ISSUE THREAD

**Issue by MarcosxDeveloper** [reduxjs/redux-toolkit#1331]
I want to add auth token to header in documatation of rtkquery example i get prepareHeaders from example but it doesnt work because this is not a hook.

```js
import { useAuth0 } from "@auth0/auth0-react";

const baseQuery = () => fetchBaseQuery({
    baseUrl: process.env.REACT_APP_AUDIENCE,
    prepareHeaders: async (headers) => {
        const { getAccessTokenSilently } = useAuth0;
        const access_token = await getAccessTokenSilently();
        if (access_token) {
            headers.set('Authorization', `Bearer ${access_token}`);
            headers.set('Content-Type', 'application/json');
        }
        return headers;
    }
});
```

I have a way to set the access_token dynamically in the useMethodApiQuery without the getState method? 

Sample code:

```js
const { getAccessTokenSilently } = useAuth0;
const access_token = await getAccessTokenSilently();
const queryParams = { ...args }
useMethodApiQuery(access_token, queryParams)
```

**Comment by phryneas** [comment]
Since RTK-Query exists completely independently of React, you would probably work directly with an `Auth0Client` from the https://github.com/auth0/auth0-spa-js package instead of using the `@auth0/auth0-react` package, which is also just a wrapper around that client.

**Comment by MarcosxDeveloper** [comment]
I Added react implementation in clasic Create Async Thunk + React Hook For Calling API.

[migrating to rtk query](https://redux-toolkit.js.org/rtk-query/usage/migrating-to-rtk-query)

But i dont know how to add auth0 getAccessToken in useEffect from the auto-generated CreateApi Hook.

**Comment by phryneas** [comment]
Well, how were you using it with `cAT`?

**Comment by msutkowski** [comment]
If you look at the source for the Auth0 hook, you can just extract the `getTokenSilently` from its dependent lib and use it the same way - or just make the request yourself without using any of the dependencies if they're not required.

**Comment by MarcosxDeveloper** [comment]
I tried to use getAccessToken inside create api method but doesn't work because Is not a Hook component.

Actually i want to replicarse this implementation for autogenerated RTK Query Hooks.

https://github.com/auth0/auth0-react/blob/master/examples/cra-react-router/src/use-api.ts

**Comment by phryneas** [comment]
That is what I am trying to tell you: RTKQ is not invoked as a "child" of React, you cannot use a library that is only be able to called within React for that purpose.

`@auth0/auth0-react` is just a wrapper around `auth0/auth0-spa-js` that ties that to React - use the parent package.

**Comment by MarcosxDeveloper** [comment]
thank you @phryneas 

I already made the change you mention, but now I have another type of problem and it is that the fetchBaseQuery does not execute if I put it asynchronously to be able to search for the token with auth0 / auth0-spa-js

**Comment by Nino3103** [comment]
For those who want to stick with the @auth0/auth0-react package and use the getAccessTokenSilently function outside a React Component, have a look at this comment: https://github.com/auth0/auth0-react/issues/67#issuecomment-662266455  

With this technique, you can use the getAccessTokenSilently function in the apiSlice file (and call it inside prepareHeaders)

**Comment by fatoyeus** [comment]
Awesome @Nino3103 got the token in apislice now
