### ISSUE TITLE
[QUESTION] dispatch arguments types

### ISSUE THREAD

**Issue by RobbeB** [reduxjs/redux-toolkit#1334]
I am not sure if it is a `react-redux`, `redux-toolkit` or webstorm issue. Any help would be appreciated.

I have the following async thunk
```
export const addCard = createAsyncThunk("cards/add", async ({ listId, cardName }) => {
	return await addCardApi(listId, cardName);
});
```

And the following component
```
const SomeComponent = () => {
    const dispatch = useDispatch()

    const someFunction = (event) => {
        dispatch(addCard({ listId: list.id, cardName: event.target.value }));
    }

    return null;
}
```

But webstorm gives me the following error on the dispatch function:
`Argument types do not match parameters`

**Comment by phryneas** [comment]
If this error is on `dispatch`, you have not typed your `useDispatch` hook correctly. https://redux-toolkit.js.org/tutorials/typescript#define-typed-hooks

If it is on `addCard`, it is a WebStorm bug. WebStorm generally tries to "guess" your TS to be faster than the TypeScript compiler. And oftentimes it just fails at that task. 
Bottom line: WebStorm totally fails as a TypeScript IDE and cannot reliably be used for TypeScript.  
See https://youtrack.jetbrains.com/issue/WEB-46527 and https://youtrack.jetbrains.com/issue/WEB-42559 for example.

**Comment by RobbeB** [comment]
Thank you for the quick response.

I should have clarified that I'm not using typescript, just javascript.
But I'm guessing it is a WebStorm issue either way?

**Comment by phryneas** [comment]
WebStorm tries to do all these tips using TypeScript internally. That gets even more unreliable when it does not get type information from TS code.
