### ISSUE TITLE
Possibility to add extra arguments when using custom query

### ISSUE THREAD

**Issue by ideffix** [reduxjs/redux-toolkit#1335]
I've been playing with RTK Query for a few days and I don't know if I'm missing something or just missunderstood the concept. In my project Im using custom query. I would like to have a possibility to pass extra arguments from place where my hook is being used. I think it would be great to have something like this:
```
const customBaseQuery = (
  args,
  { signal, dispatch, getState },
  extraOptions,
  hookOptions // <-- new param
) => {
  if (hookOptions.someFlag) {
    doSomeStuff()
  }
  if (Math.random() > 0.5) return { error: 'Too high!' }
  return { data: 'All good!' }
}
```
And then when using hook created by `createSlice`:
```
useMyApiQuery(myArgs, queryOptions, {someFlag: true})
```
or
```
useMyApiQuery(myArgs, queryOptions, {someFlag: false})
```
I would like to decide about my flag value in a place where Im using my hook. 

I know I can just add it as another field in `myArgs` object but then Ill need to type it in every place where `build.mutation/build.query` is used.

**Comment by hichemfantar** [comment]
So should this be closed?
Apparently It's fixed according to the previous comment.

**Comment by markerikson** [comment]
I think so, yeah.  Thanks!
