### ISSUE TITLE
Extending fetchBaseQuery results in extraReducers error

### ISSUE THREAD

**Issue by mjgwood** [reduxjs/redux-toolkit#1336]
I'm trying to implement authorization token refresh [as per the docs](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery), but setting the `baseQuery` to `baseQueryWithReauth` (from the docs example) I get this error `ReferenceError: can't access lexical declaration 'api' before initialization`, which points to `extraReducers` in my slice.

If I comment out `extraReducers` or switch back to using my previous `baseQueryFn` there's no error. But using both at the same time doesn't work.

api.ts
```
...
import {
  BaseQueryFn,
  FetchArgs,
  fetchBaseQuery,
  FetchBaseQueryError,
} from '@reduxjs/toolkit/query'
import { tokenReceived, loggedOut } from './authSlice'

const baseQuery = fetchBaseQuery({ baseUrl: '/' })
const baseQueryWithReauth: BaseQueryFn<
  string | FetchArgs,
  unknown,
  FetchBaseQueryError
> = async (args, api, extraOptions) => {
  let result = await baseQuery(args, api, extraOptions)

  if (result.error && result.error.status === 401) {
    // try to get a new token
    const refreshResult = await baseQuery('/refreshToken', api, extraOptions)

    if (refreshResult.data) {
      // store the new token
      api.dispatch(tokenReceived(refreshResult.data))

      // retry the initial query
      result = await baseQuery(args, api, extraOptions)
    } else {
      api.dispatch(loggedOut())
    }
  }
  return result
}

export const api = createApi({
  reducerPath: 'api',
  baseQuery: baseQueryWithReauth,
  endpoints: (builder) => ({
...
```

authSlice.ts
```
...
const authSlice = createSlice({
  ...
  extraReducers: (builder) => {
    builder.addMatcher(
      authApi.endpoints.login.matchFulfilled,
      (state, { payload }) => {
        const user: IUser = {
          username: payload.username,
          avatar: payload.avatar,
          name: payload.name,
        };
        state.isAuth = true;
        state.isLoading = false;
        state.user = user;
      },
    );
    builder.addMatcher(
      authApi.endpoints.refreshAccessToken.matchFulfilled,
      (state, { payload }) => {
        state.token = payload.access;
        state.tokenExpiry = payload.token_expiry;
      },
    );
  },
});
...
```

**Comment by mjgwood** [comment]
I've narrowed this down to being an issue with using `api.dispatch()` in `baseQueryWithReauth`. If I remove `dispatch` calls from `baseQueryWithReauth` the error no longer appears.

**Comment by phryneas** [comment]
I can't imagine why exactly, but it seems that it tries to access the global variable `api` instead of the function argument `api`. Maybe give both a different name?

**Comment by mjgwood** [comment]
No luck unfortunately. I still get the same error after renaming both.

![image](https://user-images.githubusercontent.com/12268867/126750081-b5b47893-3323-44cd-869b-5f51b587cbdc.png)

**Comment by phryneas** [comment]
I'll need a CodeSandbox reproduction to give you any feedback on this.

**Comment by mjgwood** [comment]
I've created this simplified example https://codesandbox.io/s/winter-tdd-ew88l?file=/src/features/auth/authSlice.ts

Strangely, the error I get here is different, but if I download the project and run it locally I get the same error that I had before.

`can't access property "endpoints", _baseApi.baseApi is undefined`

**Comment by phryneas** [comment]
The problem here is a circularity, and it is not the dispatch, but the `logoutSuccess` access:

* during the *creation* of `authSlice`, you access `baseApi.endpoints.refreshAccessToken.matchFulfilled` => `baseApi` has to be defined before `authSlice`.
* during the *creation* of `baseApi`, you access `baseQuery`, which accesses `logoutSuccess`, which in turn is a property of `authSlice`. => `authSlice` has to be defined before `baseApi`.

So your bundler now knows that `baseApi.ts` has to be loaded before `authSlice.ts` and vice versa - and fails.

Now you somehow have to break that cycle.

The easiest way of doing so is probably to move `logoutSuccess` out of your slice.
So create a new file
```js
import { createAction } from "@reduxjs/toolkit";
export const logoutSuccess = createAction("auth/logoutSuccess");
```
and move that reducer down to `extraReducers`:
```js
  extraReducers: (builder) => {
    builder
      .addCase(logoutSuccess, (state) => {
        state.errors = null;
        state.isAuth = false;
        state.user = nullUser;
      })
      .addMatcher(
        baseApi.endpoints.refreshAccessToken.matchFulfilled,
        (state, { payload }) => {
          state.user.token = payload.access;
          state.user.tokenExpiry = String(payload.access_expiry);
        }
      );
  }
```

**Comment by mjgwood** [comment]
Ahh of course it had to be that! I had just fixed a similar issue with circular dependency in a middleware so it only makes sense that I would go and create a new problem like it somewhere else haha

Thank you so much for spending the time identifying my issue, writing out such a detailed response, and for all the work you've put into this amazing library!
