### ISSUE TITLE
RTKQ: Property 'data' does not exist on type 'FetchBaseQueryError | SerializedError'

### ISSUE THREAD

**Issue by iakovosvo** [reduxjs/redux-toolkit#1337]
I am getting a `Property 'data' does not exist on type 'FetchBaseQueryError | SerializedError'`, when I try to access `error` like this: ` {JSON.stringify(error.data)}`. I am using a lazy query that I have exported from the api. 

This is how my api looks like
```
export const api = createApi({
  reducerPath: 'postApi',
  baseQuery: fetchBaseQuery({ baseUrl: url }),
  tagTypes: ['Post'],
  endpoints: (builder) => ({
    posts: builder.query<PostsResponse<Post>, PostPayload>({
      query: (params) => ({
        url: `posts`,
        params,
      }),
      providesTags: ['Post'],
    }),
  }),
});
```

**Comment by msutkowski** [comment]
This needs to be narrowed with a [type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html):

```ts
//anywhere:
const isFetchBaseQueryErrorType = (error: any): error is FetchBaseQueryErrorType => 'status' in error

// your file:
import { isFetchBaseQueryErrorType } from 'foobar'

// your component
const {data, error, refetch, isError, isLoading} = usePostsQuery();
if (isFetchBaseQueryErrorType(error)) {
  // now you can access error.data
}
```

In reality, you'd typically want to make a guard for the specific/known errors from your API.

**Comment by phryneas** [comment]
Alternatively you can just discriminate in-component by going

```
if ('status' in error){
  // you can access all properties of `FetchBaseQueryError` here
} else {
  // you can access all properties of `SerializedError` here
}
```

**Comment by makrandgupta** [comment]
Is this an expected error when you're not using lazy query? I am using the regular query and still having this issue. 

```ts
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

interface ILoginCredentials {
  email: string;
  password: string;
  rememberMe?: boolean;
}
// Define a service using a base URL and expected endpoints
export const authApi = createApi({
  reducerPath: 'authApi',
  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:3049/' }),
  endpoints: (builder) => ({
    login: builder.mutation({
      query: (loginCredentials: ILoginCredentials) => ({
        url: `/v1-login`,
        method: 'POST',
        body: loginCredentials,
      }),
    }),
  }),
});

export const { useLoginMutation } = authApi;
```


```ts

const LoginForm () => {
  const [login, { isLoading, isError, error, isSuccess }] = useLoginMutation();

  return (
    ...
    {error.data.message}
  )
}
```

The above usage also hits me with a 
```
Property 'data' does not exist on type 'FetchBaseQueryError | SerializedError'.
  Property 'data' does not exist on type 'SerializedError'.ts(2339)
```

**Comment by phryneas** [comment]
Yes, it is expected. Your code could also have thrown any random error, which would make the error shape completely different. As per the last replies above of your question, you will have to verify the shape of the error first.

**Comment by MrShortcut** [comment]
errors can be fixed
```ts
{ error: onErrorPostNewEntitieData } = useMutationEntitie()
export interface PostResponseFromRTK {
  data: {
    errors: string[];
  };
}

{('status' in onErrorPostNewEntitieData)
   && (onErrorPostNewEntitieData as PostResponseFromRTK).data.errors.map(
   (el, id) => <div>error {id}: {el}<br /></div>)}
```

**Comment by ChetanBhosale** [comment]
useEffect(() => {
    if (isSuccess) {
      toast.success("logged in successful!");
    }
    if (error) {
      if ("data" in error) {
        const errorData = error as any;
        toast.error(errorData.data.message);
      }
    }
  }, [error, isSuccess]);
  
  
  try this method for error

**Comment by nivans-pro** [comment]
Very weird philosophy by rtk authors. Of course there is an ocean of errors which could be thrown from API, but it does not mean that we can't type errors we can expect from API and work with them gracefully in Typescript.
