### ISSUE TITLE
RTKQ: Access "raw" queries for general use (i.e. with createAsyncThunk)

### ISSUE THREAD

**Issue by SeanRoberts** [reduxjs/redux-toolkit#1338]
This might not be a common use case or even remotely possible but I'm working on an app where the majority of our data fetching can be handled very nicely by RTKQ, but one complex section really needs a normalized state.  This is no problem at all and I'm just building this section using RTK with `createEntityAdapter` and `createAsyncThunk`.  However, one thing that would make this really nice would be the ability to still define the endpoints for this section in my `createApi` function and then pull them in to use with my thunks.  The reason for this is that it would let me not have to keep parallel API configuration for sending headers, credentials, etc. and also would let me continue to keep all my API definitions in one place.

So for example, I might want to just do something like this:

```typescript
const fetchItems = createAsyncThunk(
  'items/fetch',
  async (_, thunkApi) => {
    const result = await api.endpoints.fetchItems.fire();
    if (result.ok) {
      return result.data;
    } else {
      return thunkApi.rejectWithValue(JSON.stringify(result.error))
    }
  }
);
```

Any API here would be fine, the goal is just a way to run the request and get the data back without it being tied into the caching behaviour of RTKQ at all.  Is this currently possible?  If not is it something that would be considered for RTKQ's future?

**Comment by markerikson** [comment]
Yep, already possible.  All of RTKQ's core logic is UI-agnostic and actually defined using standard thunks internally.  Those are exposed on the endpoint definition items.

See the docs on "using RTKQ without hooks" here:

https://redux-toolkit.js.org/rtk-query/usage/usage-without-react-hooks

as well as things like the Svelte or Class Components examples:

https://redux-toolkit.js.org/rtk-query/usage/examples#svelte

**Comment by SeanRoberts** [comment]
Thanks Mark!  I did look at those docs but it wasn't clear that I could actually access the result, but it looks like I can.  This gets me pretty close to where I want to be, just with the downside of having the data repeated in my state (once under RTKQ's slice and once in the custom slice I'm building)

Here's what I ended up with as a starter:

```typescript
export const fetchItems = createAsyncThunk(
  'items/fetch',
  async (_, { rejectWithValue, dispatch }) => {
    const result = await dispatch(api.endpoints.fetchItems.initiate());

    if ('data' in result && result.data) {
      return result.data;
    } else {
      return rejectWithValue(result.error || 'Unknown error');
    }
  }
);

I tried calling `api.endpoints.fetchItems.initiate()` without dispatching it but it doesn't seem to return anything that I would need.  For now it's not a big deal to have this data in my state twice but it would be great to be able to run the query and get the result without dispatching.

**Comment by markerikson** [comment]
Yeah, _everything_ in Redux gets done by dispatching :)

I suppose if it really bothered you, you could write a custom middleware that would somehow filter out those specific RTKQ actions from hitting the reducers so the caching logic never sees them, but it's also not like it really costs anything to have that data sitting there either.

**Comment by SeanRoberts** [comment]
For sure, yeah I think this covers my use case just fine.  Thanks for the help as always!

**Comment by phryneas** [comment]
I think you don't even need to go that far. Just use normal endpoints as always and listen in your `extraReducers` for the endpoint's pending/fulfilled/rejected actions. They are eposed as matchers on `api.endpoints.yourQuery`

**Comment by SeanRoberts** [comment]
> I think you don't even need to go that far. Just use normal endpoints as always and listen in your `extraReducers` for the endpoint's pending/fulfilled/rejected actions. They are eposed as matchers on `api.endpoints.yourQuery`

Oh hey, thanks, this works great!  Same result and for much less code as I don't have to create any async thunks.  I'm going to share my slice as it is so far for anyone that might be trying to do something similar.  I'm doing cursor-based pagination with infinite scrolling here which is part (but not all) of the reason I wanted more direct control over my caching.  

```typescript
const itemsAdapter = createEntityAdapter<Item>();

const { reducer } = createSlice({
  name: 'items',
  initialState: itemsAdapter.getInitialState({
    metadata: { totalCount: 0, cursor: '' },
  }),
  reducers: {},
  extraReducers: (builder) => {
    // Fetch fulfilled
    builder.addMatcher(
      api.endpoints.fetchItems.matchFulfilled,
      (state, action) => {
        const data = action.payload;
        state.metadata = data.metadata;
        if (action.meta.arg.originalArgs.cursor === '') {
          // Filters have changed so we're back to "page 1"
          itemsAdapter.setAll(state, data.items);
        } else {
          itemsAdapter.addMany(state, data.items);
        }
      }
    );

    // Optimistic update
    builder.addMatcher(
      api.endpoints.updateItem.matchPending,
      (state, action) => {
        const { item, changes } = action.meta.arg.originalArgs;
        itemsAdapter.upsertOne(state, { ...item, ...changes });
      }
    );

    // Rollback optimistic update if update fails
    builder.addMatcher(
      api.endpoints.updateItem.matchRejected,
      (state, action) => {
        const { item } = action.meta.arg.originalArgs;
        itemsAdapter.upsertOne(state, item);
      }
    );
  },
});

export default reducer;

// Selectors
const selectors = itemsAdapter.getSelectors();

export const getItems = (state: RootState) =>
  selectors.selectAll(state.items);
```
