### ISSUE TITLE
RTKQ: Support getter for state slice

### ISSUE THREAD

**Issue by liamfd** [reduxjs/redux-toolkit#1346]
## Summary

If I'm understanding correctly, right now the only way to tell RTK-Query where your state lives is with `reducerPath`, which is a string. It might be useful to support more dynamic ways of accessing the root state slice, something like:

```ts
export const pokemonApi = createApi({
  reducerPath: (rootState: RootState) => {
     // some dynamic logic that returns a state slice
  },
  baseQuery: fetchBaseQuery({ baseUrl: 'https://pokeapi.co/api/v2/' }),
  endpoints: (builder) => ({
    getPokemonByName: builder.query<Pokemon, string>({
      query: (name) => `pokemon/${name}`,
    }),
  }),
});
```

## Use Case

My use case is that, for legacy reasons, my root state object is an Immutable.js Map (we're in the process of migrating off of Immutable, but it's a long term process). 

Actually storing the state is fine, because I can nest a plain JS object under the root Immutable map like:

```ts
export const myGlobalStateReducer: Reducer<Immutable.Map<string, any>> = (
  state,
  action
) => {
  const nextApiState = wwwApi.reducer(state.get(wwwApi.reducerPath), action);
  const nextState = state.set(wwwApi.reducerPath, nextApiState);

  return nextState;
};
```

(We've actually got it nested one level deeper, but the principle is the same).

To access this state, I need to call `rootState.get(pokemonApi.reducerPath)`.  However, RTK's selectors assume that state is available at `rootState[pokemonApi.reducerPath]`, so out of the box this doesn't work. If `reducerPath` optionally took a function (or if there were an equivalent separate param) I could just handle this complexity in the definition of `pokemonApi`. 

I imagine this could also be useful for anyone who'd like to nest their api state for whatever reason.

### Workaround

For anyone else who might need a feature like this, I've gotten RTK-Query working without having to restructure the rest of my store by writing a reducer like:

```ts
export const myGlobalStateReducer: Reducer<Immutable.Map<string, any>> = (
  state,
  action
) => {
  const nextApiState = wwwApi.reducer(state.get(wwwApi.reducerPath), action);
  const nextState = state.set(wwwApi.reducerPath, nextApiState);

  Object.defineProperty(nextState, wwwApi.reducerPath, {
    get() {
      return this.get(wwwApi.reducerPath);
    },

    // prevents errors when the no state changes happen and nextState === prevState so this is already defined
    configurable: true,
  });

  return nextState;
};
```

So the actual state lives in the Immutable Map, and we essentially proxy the requests made by RTK's selectors with the getter. As opposed to mutating the Immutable object by assigning the value directly (in which case, you'd still have to store the api state under an Immutable path or find some other way to manage your object identity). This proxying is likely a little overkill considering redux state objects in general should be considered immutable, but, it seemed easiest to reason about.

**Note that this has to be the last reducer applied.** An Immutable `set()` won't carry this property through. A plain JS spread would if you set `enumerable: true`, in which case the spread seems to call the getter and set its result as a static value in the new object, which I suppose should be fine since, again, your state object should be considered immutable.

-----

I understand this might be a little niche and not worth adding complexity to `createApi`'s interface, especially considering the fact that there's a workaround for my use case. Just thought it might be worth discussing!

**Comment by markerikson** [comment]
Hey, thanks for asking about this and providing some details on what you're doing.

My initial reaction is that we'd be unlikely to change this, for a few reasons:

- The `reducerPath` field ties into the static typing with TypeScript, which is a key part of RTKQ's design behavior
- The specified `reducerPath` lets us check to ensure that the reducer has actually been added to the store correctly and provide a runtime warning if not
- We specifically recommend against using Immutable.js with Redux today ( https://redux.js.org/style-guide/style-guide#use-plain-javascript-objects-for-state )
- As you pointed out, this is definitely an edge case

I could hypothetically imagine that the runtime check could also be done if a selector was involved, but not sure about the static typing part.  I'm also not sure there's enough wider benefit in changing this behavior.

All that said, I'm impressed with the workaround :)

**Comment by phryneas** [comment]
Yeah, I'm kinda going with Mark on that one. This is a very one-off case you have there. Generally this would not be a problem since usually you only ever have one api in your application and there is always space for one more property in the root state.

As for your specific case with `immutable`, I think if you can switch your root `Map` to a [`Record`](https://immutable-js.com/docs/v4.0.0-rc.14/Record/) that might make it a little easier - but on the other hand, you have a working workaround so I guess just keep it that way :)

**Comment by markerikson** [comment]
I'm going to go ahead and close this, but please feel free to follow up if you've got any further questions on this.

**Comment by liamfd** [comment]
Makes sense - thanks!

> As for your specific case with immutable, I think if you can switch your root Map to a Record that might make it a little easier - but on the other hand, you have a working workaround so I guess just keep it that way :)

That does look interesting, thanks for the heads up!
