### ISSUE TITLE
The expected type comes from property 'type' which is declared here on type 'FullTagDescription<never>'

### ISSUE THREAD

**Issue by matteobortolazzo** [reduxjs/redux-toolkit#1347]
Hi,

I am new to RTK, I am trying to invalidate cache on mutation and I followed the tutorial.
However, when using `invalidatesTags: [{ type: 'Posts', id: 'LIST' }]` 
I get `The expected type comes from property 'type' which is declared here on type 'FullTagDescription<never>'`.

Can you tell me know to fix it?

Thanks

**Comment by markerikson** [comment]
Can you post the entire slice file you're working it, or if possible a CodeSandbox that shows this issue?

**Comment by matteobortolazzo** [comment]
Here's the code (removing other endpoints), I am using Typescript 4.1.3

```typescript
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { NewMessageCommand, NewMessageCommandResponse } from '../commands';

const baseUrl = 'http://localhost:7071/api/';

export const puchApi = createApi({
    reducerPath: 'puchApi',
    baseQuery: fetchBaseQuery({ baseUrl }),
    endpoints: (builder) => ({      
      addChannelMessage: builder.mutation<NewMessageCommandResponse, { channelId: string } & NewMessageCommand>({
        query: ({ channelId: id, ...command }) => ({
          url: `channels/${id}/messages`,
          method: 'POST',
          body: command,
        }),
        invalidatesTags: [{ type: 'Messages', id: 'LIST' }]
      }),
    }),
  })

  export const {
    useAddChannelMessageMutation
  } = puchApi;
```

**Comment by msutkowski** [comment]
> Here's the code (removing other endpoints), I am using Typescript 4.1.3
> 
> ```ts
> import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
> import { NewMessageCommand, NewMessageCommandResponse } from '../commands';
> 
> const baseUrl = 'http://localhost:7071/api/';
> 
> export const puchApi = createApi({
>     reducerPath: 'puchApi',
>     baseQuery: fetchBaseQuery({ baseUrl }),
>     endpoints: (builder) => ({      
>       addChannelMessage: builder.mutation<NewMessageCommandResponse, { channelId: string } & NewMessageCommand>({
>         query: ({ channelId: id, ...command }) => ({
>           url: `channels/${id}/messages`,
>           method: 'POST',
>           body: command,
>         }),
>         invalidatesTags: [{ type: 'Messages', id: 'LIST' }]
>       }),
>     }),
>   })
> 
>   export const {
>     useAddChannelMessageMutation
>   } = puchApi;
> ```

You need to specify `tagTypes: ['Messages']` in `createApi` as well.

```ts
export const puchApi = createApi({
    reducerPath: 'puchApi',
    baseQuery: fetchBaseQuery({ baseUrl }),
    tagTypes: ['Messages'],
    endpoints: (builder) => ({      
      addChannelMessage: builder.mutation<NewMessageCommandResponse, { channelId: string } & NewMessageCommand>({
        query: ({ channelId: id, ...command }) => ({
          url: `channels/${id}/messages`,
          method: 'POST',
          body: command,
        }),
        invalidatesTags: [{ type: 'Messages', id: 'LIST' }]
      }),
    }),
  })
```

**Comment by matteobortolazzo** [comment]
I must have missed it! Thanks a lot for the super quick help, you guys are great :)
