### ISSUE TITLE
RTKQ addTagType using with typescript

### ISSUE THREAD

**Issue by huynd0902** [reduxjs/redux-toolkit#1352]
Hi. Thank for your awesome library.
I have a problem when use RTKQ with typescript. I have a base api is the central api. Then I'll inject the endpoint when I need.
The problem is when I injected the endpoint in different api file ex: vendorApi.ts, I don't know how to **providesTag**  for this endpoint with is very easy when I using javascript, just call enhanceEndpoints then addTagTypes. But it not working for typescript. See the codesanbox. https://codesandbox.io/s/young-https-9h0wx.
Please correct me if I make any mistake. Thanks

**Comment by msutkowski** [comment]
Swap the order so that you're enhancing endpoints first:

```ts
const vendorApi = baseApi
  .enhanceEndpoints({
    addTagTypes: ["VENDOR_LIST"]
  })
  .injectEndpoints({
    endpoints: (build) => ({
      getVendors: build.query<Array<Vendor>, any>({
        query: (params) => {
          return { url, method: "GET", params: params };
        },
        // transformResponse: res => res?.map(item => ({ ...item, key: item.id })),
        providesTags: ["VENDOR_LIST"]
      })
    })
  });
  ```

**Comment by huynd0902** [comment]
> Swap the order so that you're enhancing endpoints first:
> 
> ```ts
> const vendorApi = baseApi
>   .enhanceEndpoints({
>     addTagTypes: ["VENDOR_LIST"]
>   })
>   .injectEndpoints({
>     endpoints: (build) => ({
>       getVendors: build.query<Array<Vendor>, any>({
>         query: (params) => {
>           return { url, method: "GET", params: params };
>         },
>         // transformResponse: res => res?.map(item => ({ ...item, key: item.id })),
>         providesTags: ["VENDOR_LIST"]
>       })
>     })
>   });
> ```

Hi. Thank you. It working again.
