### ISSUE TITLE
RTKQ: real-time behavior 

### ISSUE THREAD

**Issue by melyourhero** [reduxjs/redux-toolkit#1359]
Hello, thank you for your amazing work on this library. 

I'm experiencing an issue when using the example from [Streaming Updates](https://redux-toolkit.js.org/rtk-query/usage/streaming-updates). 
In my case, when I received an error from the event I need to rerun the whole pipeline. (i.e. based on the example: run `getMessages` query and subscribe on events in `onCacheEntryAdded`, arguments stay the same). 

So I have two questions.

1) How can I rerun my pipeline for my case? (maybe i need an opportunity to manually remove cache entry in this case)
2) Is it ideologically, to hold a specific error inside the `data` property? (i.e. `streamError`)

Sorry, If I missed something from the documentation.

Thank you in advance for your help.

**Comment by bever1337** [comment]
Interesting question and one I'm trying to solve too. In your use-case, does 'rerunning the pipeline' also mean you want to close the WebSocket and connect a new one?

I'm sharing a socket between endpoints, used in both queryFn and onCacheEntryStarted. An RxJS behavior subject is used to resolve the socket between all the different contexts. Unlike fetch, the socket stream can't be abstracted into "The first request resolved, so the state of this request is always resolved."

I asked this question in discord:

> Can onCacheEntryAdded provide an error that changes the result state? E.g. useQuery() would return isError: true after the initial query/queryFn may have resolved successfully? I can only find examples of catching and ignoring errors at this point in lifecycle
> The use-case is websocket "endpoints" where the result state can change over time 
Ignoring network code and only looking at the cache/redux code, this is very similar to what we're working on: https://redux-toolkit.js.org/rtk-query/usage/streaming-updates#streaming-update-examples

@phryneas replied:

> No, that't not possible. It runs in parallel.

**Comment by bever1337** [comment]
I just realized how stale this thread is. What was your solution @melyourhero ?
