### ISSUE TITLE
configureStore.d.ts error TS1005 expected "="

### ISSUE THREAD

**Issue by ibrahimyaacob92** [reduxjs/redux-toolkit#1365]
![image](https://user-images.githubusercontent.com/58116068/127568740-eb4ec0f8-7532-4ae0-88a4-5d726e341e67.png)

**Comment by markerikson** [comment]
That's not really enough information for us to provide help.  At a minimum, we'd need to see a project that reproduces this error, along with some details like what version of TypeScript you're using and how it's configured.

I'm going to close this for now.  If you can put together a project that reproduces this we might be able to look, but odds are it's a configuration issue on your end.

**Comment by phryneas** [comment]
I would assume you are on a very old version of TypeScript though. 3.8 or older probably. Please note that we are backwards compatible with 3.9, but not with older versions.
