### ISSUE TITLE
Is it possible to use invalidateTags to invalidate queries between different APIs?

### ISSUE THREAD

**Issue by del-naz** [reduxjs/redux-toolkit#1368]
My application has several APIs. I have the case that a mutation in API_1 needs to rerun a query in API_2. Is this possible to do with invalidateTags?

**Comment by phryneas** [comment]
No. That is why we *very strongly recommend* to only have one api except if you have datasets that never have any correlation.

**Comment by del-naz** [comment]
Thanks for your response. 
My application uses more than 10 different services(URLs) to fetch and mutate the data. 
It doesn't make sense to me to have all these services in one huge API. 
I do want to keep them separate.
What pattern do you recommend to use to handle correlations?

Currently I use onQueryStarted to call a function to deal with the correlation:

            myEndpoint: build.mutation<any, any>({
            query: ({member, values}) => {
                return {
                    url: "myURL",
                    method: 'post',
                    data: values,
                };
            },
            onQueryStarted: async (args, {queryFulfilled}) => {
                try {
                    await queryFulfilled;
                    anotherAPI.anotherEndpoint.initiate(data, {subscribe: false, forceRefetch: true});
                } catch {}
            }

**Comment by phryneas** [comment]
If they should invalidate each other, they are clearly one connected dataset and should by the architectural decision which `createApi` was built upon be one api.

You can use the [code splitting](https://redux-toolkit.js.org/rtk-query/usage/code-splitting) mechanisms to split that one api into multiple files, but if there is interaction between endpoints they should be on the same api. Please don't try working around that, you are going to hurt yourself.

**Comment by del-naz** [comment]
Thanks for your advice.

**Comment by phryneas** [comment]
Generally, every endpoint can just specify an absolute url, even if it does not belong to the baseUrl. Only relative urls will be relative to the baseUrl.

I'm curious though, do you have related datasets on completely different domains?

**Comment by del-naz** [comment]
Yes. the app is for clinicians that work with many members. Members have their data delivered by many micro-services (personalInfo, medicalInfo, appointments, sessions, surveys, etc...)

**Comment by phryneas** [comment]
That did not really seem to answer my question.

All those microservices could be behind a gateway and share the same url. They could be on their own subdomains (and share the same domain). They could be on completely different domains. I could not read any of that from your answer.

Anyways, we tried to use "same domain" as an easy disciminator in the docs as in 99% of the cases it should make it clear, but I'll rephrase it here to make it more clear:

If you have one api for google, one for twitter and one for facebook, those will be three completely separate datasets that will never have any interaction with each other.   
Those are three `createApi` calls.
 
If you have data that is in any way more interconnected by that, it probably belongs on the same api slice. Depending on your setup, you might need to specify full urls instead of relative urls in `query` in that case.

**Comment by sebastienlabine** [comment]
If I understand correctly, this means that if we have multiple microservices, for example let's says a products API and a companies API, we can't use a different createAPI for each and manage their behaviour on a more isolated level?

From my understanding, I also felt that the invalidate tags were a way to invalidate cache across api. I feel like the code could get very messy if all our apis calls are regrouped under a single createAPI.

**Comment by phryneas** [comment]
@sebastienlabine you can still split this one api up into as many files as you want as described in [Code Splitting](https://redux-toolkit.js.org/rtk-query/usage/code-splitting). If data is connected in a way that one request should make something else refetch, they are logically part of the same api.

**Comment by sebastienlabine** [comment]
I see. Thanks!

**Comment by zousandian** [comment]
> Generally, every endpoint can just specify an absolute url in `query`, even if it does not belong to the baseUrl. Only relative urls will be relative to the baseUrl.
> 
> I'm curious though, do you have related datasets on completely different domains?

@[phryneas](https://github.com/phryneas) Any advices or best practice for datasets on different domains?
For example, I have a To-do app with different domains, to fetching different regions' todos data for the same user.
I need to show all the regions' todos on **one todos list** for the user. 
When the user complete the todo item, it need to be submitted to the corresponding domain. 
Can I use the `Streaming Updates` to do it?

PS: for data isolation provisions or other reasons, we can't merge these datas on the backend.
```
// query
GET http://us.data.com/todos  // default todos data, load first and show the UI ASAP
GET http://eu.data.com/todos  // EU todos data, loading slow, merged into the default todos after loaded
GET http://jp.data.com/todos  // JP todos data, loading slow, merged into the default todos after loaded


// mutation
POST http://us.data.com/todos/{id}/complete
POST http://eu.data.com/todos/{id}/complete
POST http://jp.data.com/todos/{id}/complete
```

**Comment by phryneas** [comment]
@zousandian You quoted me exactly right so I'm just going to repeat it:

> Generally, every endpoint can just specify an absolute url in query, even if it does not belong to the baseUrl. Only relative urls will be relative to the baseUrl.

=> build an **absolute** url beginning with `http://`|`http://`|`//` and the full domain in `query`. No problem, it will ignore `baseUrl`.
