### ISSUE TITLE
[Question]: Remove data from the state if the request was rejected

### ISSUE THREAD

**Issue by lakatostamas** [reduxjs/redux-toolkit#1372]
Hi,

I am wondering if it's possible to remove the old data from the state if the new request is rejected. I have the following component tree:
- App
  - PrivateRoute
    - Component
    
In the `App.tsx` I check whether the user has a valid JWT, and if so I start to fetch the user and mounting the PrivateRoute. The problem happens when the user has signed out and right after a different user signs in (without a page reload)

If I understood correctly, the following events are happening:
* user 1 signed in, account is stored under `api.queries.getAccount('me')` (status: fulfilled)
* user 1 signs out, the sign out action invalidates the `Account` tag
* the Account query is still referenced from multiple components but it was invalidated, so a new fetch happens. There is no JWT, so the request is rejected (as expected). However, the account is still stored under `api.queries.getAccount('me')`, only the status changed to 'rejected`
* user 2 enters valid credentials, JWT token created, account is being fetched again
* *bug or unpleasure feature*: while the account is being fetched, the name of `user1` is displayed for a short period of time, because it's data is still stored in the state. 

A possible fix is to not show anything until `isFetching`  or `isError` is true, but it would be great if I could get rid of the previous user's data when the request was rejected.

Question: Would it be possible to somehow remove the previous query result when the new query is rejected?

Thanks!

**Comment by phryneas** [comment]
In this case, I would have all private routes provide a "REQUIRES_AUTH" tag (or something similar) and invalidate that tag when you notice that the user is logged out. That way, all queries that are currently displayed will re-run end get a 403 and all non-displayed queries will be removed from cache.
