### ISSUE TITLE
RTKQ: Mutation gets stuck in 'Pending' despite rejection from the server.

### ISSUE THREAD

**Issue by abitbetterthanyesterday** [reduxjs/redux-toolkit#1376]
Hi,

On multiple places, since I've updated our package the mutation is stuck on 'Pending' even when an error is thrown.

See screenshot and code below.
The server returns 422, but the mutation doesn't get rejected. 

It works with fulfilled mutation, but not rejected ones.
I have the issue in multiple places in my codebase and had to revert back to handling the state manually.

Any clues?
Thank you!

```js
// Mutation
  verifyEmail: builder.mutation({
      query: ({ key, email }) => ({
        url: `membership/validate-email/${key}/${email}`,
        method: "PUT",
      }),
      
 // In my component

   const [
    verifyEmailMutation,
    { isLoading, isError, isSuccess, isUninitialized },
  ] = useVerifyEmailMutation();
  
  <button onClick={() => { isUninitialized && verifyEmailMutation({ key, email }); } > Button </button>
```

<img width="1439" alt="Screen Shot 2021-08-03 at 10 59 28" src="https://user-images.githubusercontent.com/17796338/127988854-35ba5ee0-040c-49e5-80e1-c2f85f1cb3d9.png">

**Comment by phryneas** [comment]
Could you try to create a reproduction for this?

**Comment by rana944** [comment]
@phryneas , I have a scenario where I have been using RTK mutation to fetch data from server on demand. When ever I get a 500 error, it gets logged to my middleware 

`export const rtkQueryErrorLogger: Middleware = (api: MiddlewareAPI) => (next) => (action) => {
    console.log(isRejected(action));
    if (isRejectedWithValue(action)) {
        console.warn('We got a rejected action!')
        console.log({ ...action?.payload, data: '', })
        ShowCustomError(action.payload);
        return next(action)
    }

    return next(action);
}`

but, the mutation is always in Pending state, not even giving any error state.

**Comment by phryneas** [comment]
@rana944 
> Could you try to create a reproduction for this?

this applies here as well. without any code showing this in a reproducable way I have no idea what is going on.

**Comment by rana944** [comment]
@phryneas ,

Thank you so much for such quick response.

I have managed to resolve this issue by using custom base query (Axios Base query).

This is how, I have achieved this,

```
export const testApi = createApi({
    reducerPath: 'trendingApi',
    baseQuery: axiosBaseQuery(),
    endpoints: (builder) => ({
        getTopTestItems: builder.mutation<TopTestItem[], TopTestParams>({
            query: (data) => getInterceptor(URLS.TEST1, data, data.token),
        }),
        getTestItems: builder.mutation<TestItem[], TestParams>({
            query: (data) => getInterceptor(URLS.TEST2, data, data.token),
            transformResponse: (response: { data: TrendingTicker[] }) => response.data
        }),
    }),
});

```
> This is the code my **GET** request interceptor

```
const getInterceptor = (url: string, params: any, token?: string | undefined) => {
    return {
        url,
        method: 'GET',
        params,
        headers: {
            'Content-Type': 'application/json;charset=UTF-8',
            'Authorization': `JWT ${token}`,
        },
    }
}
```

> This is the code for my custom base query

```
const axiossInstance = axios.create({
    baseURL: BASE_URL,
});

const axiosBaseQuery = (): BaseQueryFn<any> => async (
    requestOptions,
) => {
    try {

        const result = await axiossInstance({
            ...requestOptions,
        });
    
        return { data: result.data };
    } catch (e: any) {
        return { error: e?.message }
    }
}
```

> This is how I am calling the above mutation,

```
const testParams = { };
getTopTestItems({ ...testParams });
```

Thank you

**Comment by phryneas** [comment]
@rana944 I need a CodeSandbox, git repository or something else that *shows me the problem*, not the workaround. 
If there is a problem, we need to find and fix it in RTK-Query, so that not everyone has to go for the workarounds you have here.

But without a reproduction I have no idea what to look for.

**Comment by polaroidkidd** [comment]
Hi, I'm currently facing the similar issue and have a reproducible repo here: https://github.com/polaroidkidd/librephotos-frontend/tree/feat/migrate-ts--auth-state

I defined the request [here](http://github.com/polaroidkidd/librephotos-frontend/blob/19fcff91c15235e7f5bf06d7447b881d4a90abba/src/api_client/api.ts#L61-L61) and I'm using it on the signup page [here](http://github.com/polaroidkidd/librephotos-frontend/blob/19fcff91c15235e7f5bf06d7447b881d4a90abba/src/layouts/login/SignUpPage.tsx#L25-L25).

The successful query goes through as advertised, but when I try to sign up with the same user name twice, the api correctly returns 400 correctly and the rejected response is logged out [here](http://github.com/polaroidkidd/librephotos-frontend/blob/5406e1d3f0592fe346acae0745c22cbe7e6e5eae/src/store/auth/authSlice.ts#L38-L38), but the status [remains `pending`](http://github.com/polaroidkidd/librephotos-frontend/blob/5406e1d3f0592fe346acae0745c22cbe7e6e5eae/src/layouts/login/SignUpPage.tsx#L27-L27)


To get talking to the api you'd have to clone https://github.com/LibrePhotos/librephotos-docker, rename `librephotos.env` to `.env` and run `docker-compose up -d`. 

I'm fairly sure I've misconfigured something here somehwere since RTK-Query is still new to me, but seeing as there's already a ticket for it and you mention needing a reproducible example, I thought I'd throw my hat in the ring.

**Comment by polaroidkidd** [comment]
I did some further digging and found a bug in my zod declarations, which stopped the mutation from entering the fulfilled state. 

It wasn't related to this after all.

**Comment by nofear144** [comment]
Got the same issue when i use GET request with Lazy Query  and got 500 error from server,  status stacked in "Pending" position...

**Comment by phryneas** [comment]
@nofear144 I can only quote myself from this issue:

> without a reproduction I have no idea what to look for.

**Comment by phryneas** [comment]
Cool. 
Could **someone** at this point maybe even just *try* to create a reproduction of this instead of saying "I have this problem too"?

Because obviously we have never encountered this. We cannot help you otherwise.

**Comment by amandeep-qasource** [comment]
> Cool. Could **someone** at this point maybe even just _try_ to create a reproduction of this instead of saying "I have this problem too"?
> 
> Because obviously we have never encountered this. We cannot help you otherwise.

Thank you so much for your quick response!

I am calling a POST API twice in a component using mutation
For first-time mutation call on button click, it is working fine, getting response perfectly fine, but when the same API is called again from button click event it is pausing at the pending status and no output is coming.

**Comment by phryneas** [comment]
I need a reproduction with code that I can run on my machine and see it for myself.

That could be a GitHub repo, a CodeSandbix or a [Replay recording](https://www.replay.io/).

**Comment by v-x2** [comment]
Same problem. I know that you're looking for a snippet to reproduce the error. But actually it seems to be random (I tried to create a code sandbox for you but the error disappeared there..)

Till now, I've tried to change the API endpoint name and the tag and the issues seems to disappear for a while, but after _some time_ it appears again. Could be something related to the cache?

**Comment by phryneas** [comment]
@v-x2 I really can't tell. I'd at least need a replay of this happening once.

**Comment by dominikberse** [comment]
I encountered a similar problem, but it was probably just misusage from my side. For me the request kept hanging as pending because I had a request argument that depended on the current time, which of course changed with every execution. 

Something like this:

```
  const since =
    listState === 'closed'
      ? subDays(new Date(), 90)
      : listState === 'new'
      ? subDays(new Date(), 7)
      : undefined;

  const {
    currentData,
    error,
    isFetching,
  } = useGetDataQuery({
    since: since?.toISOString(),
  });
```

I resolved this by using the current date without time as a reference point, so `since` stays constant. Since this was probably just my fault, I did not take the time to set up a repository. However I thought I should just quickly share my finding. 

_If_ it is helpful to you, I can set up a repository reproducing this behavior as soon as I have the time.

**Comment by Geemarn** [comment]
i encountered similar issues but after removing the middleware am using, it worked as expected.

/** Log a warning and show a notification! **/
const rtkQuerySuccessLogger =
  (api: MiddlewareAPI) => (next: any) => (action: { meta: { arg: { type: string } } }) => {
    if (isFulfilled(action)) {
      if (action.meta.arg.type === 'mutation') {
        return message.success('Action Successful!');
      }
    }
    return next(action);
  };

**Comment by phryneas** [comment]
@Geemarn yes, that middleware will stop the actions from ever reaching the reducer.

```diff
/** Log a warning and show a notification! **/
const rtkQuerySuccessLogger =
(api: MiddlewareAPI) => (next: any) => (action: { meta: { arg: { type: string } } }) => {
if (isFulfilled(action)) {
if (action.meta.arg.type === 'mutation') {
+ next(action)
return message.success('Action Successful!');
}
}
return next(action);
};
```

You always have to call `next(action)` or the action will never reach the store.

Generally I'd recommend you look at the [Listener Middleware](https://redux-toolkit.js.org/api/createListenerMiddleware) for something like that

**Comment by Geemarn** [comment]
yeah, thanks..just observed it now

**Comment by Abolfazl2647** [comment]
I have the same issue and provide a [codeSandBox](https://codesandbox.io/s/trk-query-m1lbtd?file=/src/api/index.js) for you guys.

but I'm not sure if you can actually make a request to my server feel free to check out the code.
I must say I actually test this code and in my localhost, I am able to see a status freeze in pending for my ```getCandles``` query but ```getInstrument``` works as expected.

**Comment by phryneas** [comment]
@Abolfazl2647 your code just makes a new request every time the component rerenders.

Every time the component rerenders, `new Date().toISOString()` will be a different value, so now RTK Query goes ahead and starts another request. That way, you will never finish loading.

**Comment by Abolfazl2647** [comment]
@phryneas thank you, I should see that sooner. 
sorry to bother you.😖

**Comment by axinvd** [comment]
[codeSandBoxExample](https://codesandbox.io/s/trk-query-forked-71j06q?file=/src/store/authReducer.js)
Mutation is stuck in pending status if get error in reducer added by addMatcher

**Comment by markerikson** [comment]
@axinvd : yeah, that's to be expected. If an error is thrown in the reducer, then the state never actually gets updated.

**Comment by vasimshaikhh** [comment]
i am getting the same error in Post Mutation , but the Args i passed is Successfully originated inside originalArgs!! what should i do now

**Comment by azad-source** [comment]
Hello! Why this issue is closed and how fixed this problem?
Today is 2023 and I faced the same problem when I used RTK Query.

**Comment by phryneas** [comment]
@azad-source as you can read here, they had manual code in a reducer that was erroring. You likely have a different problem. Please open a new issue and provide a reproduction or a replay recording of the problem.

**Comment by azad-source** [comment]
@phryneas thanks! I'll try to hide my reducer's slice and I'll check if the problem goes away or not. May be I have the same reason. :)

**Comment by pmoradei** [comment]
Hello everyone, I ran into this problem because I was doing a mutation call into a popup react component that is unmounted after the mutation call : 
```
const [doMutation, res] = useSomeMutation();
  /* some code...*/
() => {
 doMutation({...});
 //this method call close the popup so react unmount the component
 onValidate();
}
```
Adding 'await' before the mutation call help resolve this because the "res" variable is updated before the component is unmounted:

```
async () => {
 await doMutation({...});
 //this method call close the popup so react unmount the component
 onValidate();
}
```
Hope it'll help someone  :)

**Comment by kouroshey** [comment]
> I did some further digging and found a bug in my zod declarations, which stopped the mutation from entering the fulfilled state.
> 
> It wasn't related to this after all.

Hi. I have same issue with ZOS&rRTKQ. Can u explain how to resolve this?

**Comment by kouroshey** [comment]
> > I did some further digging and found a bug in my zod declarations, which stopped the mutation from entering the fulfilled state.
> > It wasn't related to this after all.
> 
> Hi. I have same issue with ZOD & RTKQ. Can u explain how to resolve this?

solved :)

**Comment by JuanRdBO** [comment]
How did you solve it @kouroshey ?

**Comment by kouroshey** [comment]
> How did you solve it @kouroshey ?

Hey, Actually I don't remember what the problem was. Can you explain your case?
