### ISSUE TITLE
RTKQ + redux-dynamic-modules: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by travenec** [reduxjs/redux-toolkit#1381]
Hello everyone,

thank you for awesome library. I am trying to adopt RTK and now RTKQ in my boilerplate which utilizes `redux-dynamic-modules` for purpose of code-splitting. Things work fine when combining RTK and redux-dynamic-modules.

When I use RTKQ api, the `buildMiddleware` internal runs into infinite recursion causing `Maximum call stack size exceeded`.

The module configuration is following:
```
// petstore generated by rtk-incubator/rtk-query-codegen
import { api as petstoreApi } from "./petstore-api.generated";

export const getCoreReduxModule = (): IModule<any> => {
  return {
    id: "core",
    reducerMap: {
      [petstoreApi.reducerPath]: petstoreApi.reducer
    },
    middlewares: [petstoreApi.middleware]
  };
};
```

When given "core" module is loaded, the `buildMiddleware` starts cycling on "api/config/middlewareRegistered" action.

Anyone can help solving this? Are there any other ways to implement dynamic module loading other than redux-dynamic-modules? Can I anyhow dynamically inject/replace middleware in RTK?

**Comment by markerikson** [comment]
No idea what's going on here. We'd really need to see a CodeSandbox or a repo that demonstrates this issue in order to debug it.

**Comment by travenec** [comment]
I thought so. I stripped my code to the minimal reproduction, which is - fairly minimal.

There you go: https://gitlab.com/travenec/rtkq-issue-1381

**Comment by phryneas** [comment]
Without having looked deeper into `redux-dynamic-modules`:  RTK-Query assumes that every time it is called with `applyMiddleware`, it is added to a new store and tries to initialize for that. (It initializes in the outermost middleware scope, so when `api.middleware(storeApi)` is called.)

If that module does that over and over and over, that might run into an intialization loop. The normal Redux store would call that once at store initialization and never again.

**Comment by travenec** [comment]
At the moment I can only add to the discussion that `redux-dynamic-modules` utilizes `redux-dynamic-middlewares` to work with dynamic middlewares. That might narrow the problem a bit.

Is there any other way to inject reducers+middlewares to RTK dynamically? I am aware of `replaceReducer`, but what about middlewares?

**Comment by phryneas** [comment]
It's on the roadmap, but not very high priority (https://github.com/reduxjs/redux-toolkit/issues/1326).

**Comment by travenec** [comment]
> It's on the roadmap, but not very high priority (#1326).

The issue mentions slices-for-redux, which is an interesting alternative. But none of it (including the issue) talks about middlewares, which is necessary to split RTKQ.

For me, it is still untraceable where does the recursion come from...

**Comment by phryneas** [comment]
Why exactly do you need to split the middleware though? Usually, you should have just one API. 
Mount that one upfront, use the documented code splitting approaches for RTKQ to inject additional endpoints at runtime.

**Comment by travenec** [comment]
> Why exactly do you need to split the middleware though? Usually, you should have just one API.
> Mount that one upfront, use the documented code splitting approaches for RTKQ to inject additional endpoints at runtime.
Thank you for pointing me in the right direction. That was actually something I wanted to ask originally - do I need more middlewares if I use `createApi` more times (a middleware for each api) or do I need a single middleware? If single (which is then common for all apis), your idea would be even better than any other solutions.

The problem araises when you have multiple api targets (different servers). From what I understand, you cannot really have a `createApi` targeting `https://apiserver.com/api` and then just add endpoints targeting other e.g. `https://otherserver.com/api`. Therefore I don't see that as solution. Feel free to correct my ideas...

Moreover - and that's whole other topic - if I use `rtk-incubator/rtk-query-codegen` to generate api, it generates "sealed" `createApi` constructs which I cannot use to inject endpoints without touching the generated code.

**Comment by travenec** [comment]
Hello, thank you all for participation in the discussion.

For future reference - the result is following:
* we did not resolve the issue between RTKQ and redux-dynamic-modules inject middlewares functionality
* the best way to solve dynamic loading is to create an empty api and call `injectEndpoints` + `enhanceEndpoints` (see https://redux-toolkit.js.org/rtk-query/usage/code-splitting) - and that works greatly

**Comment by fostyfost** [comment]
Hi! If you are looking for a convenient way to manage code splitting, try [this library](https://github.com/fostyfost/redux-eggs).

**Comment by killbond007** [comment]
I use multi store for this case.
