### ISSUE TITLE
RTKQ: Caching behaviour

### ISSUE THREAD

**Issue by cretumarius** [reduxjs/redux-toolkit#1387]
Hello, 
I just encountered a situation and I really don't know if it is a bug or I'm doing something wrong.
Here is my code:
[CodeSandbox](https://codesandbox.io/s/recursing-bouman-rfyqc?file=/src/App.tsx)

I don't understand why after the first fetch, my query is cached (checked in redux devtools) for 60 seconds by default, but when I try to re-make the api call, previous error is emitted(I guess from cache) but the call is refetched and another error is emitted when the request is complete.

What I'm trying to understand is:
1. This is the wanted behaviour
2. I'm doing something wrong

My desired behaviour is to make the initial load, and after that if I set the same arg as previous, I want to get response from cache. I think using skipToken this is not possible but if my assumption is correct why some cached error is emitted after the first load and the call is refetched.

Thanks in advance!

**Comment by phryneas** [comment]
Generally, a query would try to re-query if
* the component mounts
* the arguments change (with a shallow comparison)

In the case that the query already has a successful cache value, no more query would be made - but your query is in an error state, so another query is made.

The reason why on your setter call no query is made is that the arguments do not really change.

But then your component unmounts and remounts. Another request is made.

**Comment by cretumarius** [comment]
So, in this case i understand why another request is made. But when I set query args `undefined` after my initial fetch, the query state becomes uninitialised and the error `undefined`. Then when I update the args again with another possible value to check, previous error is emitted and when second fetch is done another error is emitted. My question is why useEffect detects 2 changes on query error state instead of a single one after second query is finished. 
Thanks!

**Comment by phryneas** [comment]
I can't really tell as I don't know when exactly you are logging there - it's not in your linked sandbox.

**Comment by cretumarius** [comment]
It is the useEffect from App.tsx. It has the query error state in the dependencies array.
<img width="669" alt="Screenshot 2021-08-06 at 19 35 12" src="https://user-images.githubusercontent.com/64973825/128543044-123c4703-d87b-46fb-8792-3495e42f87c1.png">

**Comment by phryneas** [comment]
Logging a bit more explains it better:

![image](https://user-images.githubusercontent.com/4282439/128546378-fab28295-cf97-4ac3-8066-3232ba5642e4.png)


So you are going from cache entry `{quotationId: 1, cui: "12345"}` to the cache entry of `undefined`, then back to `{quotationId: 1, cui: "12345"}`, which is still the old error. After rendering that, in the next `useEffect` the new request is started and after a moment gives you the new error.
