### ISSUE TITLE
Before the component unmounts (as seen by useEffect), the streaming-updates query sets data to undefined and isLoading to true

### ISSUE THREAD

**Issue by silviubogan** [reduxjs/redux-toolkit#1388]
I discovered a bug.

I don't think this is the intended behavior. The details are [in this SO question](https://stackoverflow.com/questions/68689422/why-is-the-cleanup-of-an-useeffect-hook-seeing-the-result-of-an-rtkq-as-isloadin) and the code sandbox is [here](https://codesandbox.io/s/floral-sky-523zm?file=/src/index.tsx).

Please let me know if there is a way to avoid this issue with the current version of RTK.

Thank you!

**Comment by phryneas** [comment]
You just have a stale variable reference, I explained it in your SO.
