### ISSUE TITLE
How can we use add jsdoc to redux's auto generated action creators?

### ISSUE THREAD

**Issue by branlok** [reduxjs/redux-toolkit#1390]
For instance createAsyncThunk takes a callback and returns an action creator. when i provide a jsdoc, it will not appear.
This is the same goes for createSlice when it auto generates an action creator.

example:
```js
/**
 * example jsdoc text should should up
 * 
 */
export const addImage = createAsyncThunk("posts/pushImages", async (image) => {
  const response = await db.images.put({
    picture: image.source,
    id: image.id,
    tierlistId: image.tierlistId,
    dateAdded: Date.now(),
    fileName: image.source.name,
  });

  return image.imageURL;
});
``` 

However, im unable to retrieve the jsdoc like this. 
<img width="471" alt="Screen Shot 2021-08-08 at 4 54 34 PM" src="https://user-images.githubusercontent.com/73308970/128645431-8ee49dee-3c9f-4a32-9ed8-ae53b4253348.png">

**Comment by phryneas** [comment]
There's unfortunately nothing we can do on a library level about that. You will probably see that information when hovering `addImage` when you are not calling it but just referencing it as a variable, but in the end that's up to your editor.

**Comment by johnemau** [comment]
@branlok, I saw a similar issue filled on the [vscode repository](https://github.com/microsoft/vscode/issues?q=is%3Aissue+jsdoc), however I can't relocate it. If you are still having an issue, you can try asking there for help.
