### ISSUE TITLE
RTKQ: A zero-argument query will still stringify its arguments

### ISSUE THREAD

**Issue by taylorkline** [reduxjs/redux-toolkit#1395]
A query defined as:

```ts
    getPosts: builder.query<PostsResponse, void>({
      query: () => "posts",
    }),
```

will still attempt to stringify any args provided to it.

This causes an issue when providing the `trigger` from `useLazyGetPostsQuery` directly to an `onPress` within React Native, as the `onPress` will pass an `(event: GestureResponderEvent)` and a runtime exception will occur when stringifying the `event`.

It is expected that the `trigger` for a zero-argument query would simply ignore any provided argument.

**Comment by phryneas** [comment]
There is no reliable way of detecting that a method takes 0 or 1 arguments.

While there theoretically is `functionName.length` to return the number of arguments, that does not always hold true:

```js
(function(){ console.log("no args") }).length // 0
(function(arg){ console.log(arg) }).length // 1
(function(...test){ console.log(test) }).length // 0
(function(){ console.log(arguments) }).length // 0
```

This is double true as we don't know what a transpiler would do with it - it could just switch between all of those when transpiling.

In the end, you'll probably have to put `() => trigger()` in there. We can't handle that.

**Comment by taylorkline** [comment]
Got it, thanks!
