### ISSUE TITLE
Typeof store.dispatch changed in 1.6.0

### ISSUE THREAD

**Issue by alextrastero** [reduxjs/redux-toolkit#1397]
Just upgraded from `1.5.1` to `1.6.1` and suddenly the type of dispatch is throwing errors.

**store**
```jsx
import promise from 'redux-promise-middleware';
import { routerMiddleware } from 'connected-react-router';
...
configureStore({
  reducer: rootReducer,
  middleware: getDefaultMiddleware =>
    getDefaultMiddleware().prepend(routerMiddleware(history), promise)
});
...
export type AppDispatch = typeof store.dispatch
```

**error**
```jsx
// pseudo code
const dispatch = useDispatch<AppDispatch>();
...
const uploadImgAC = createAsyncThunk('foobar', myService);
...
dispatch(uploadImgAC())
```
`Argument of type 'AsyncThunkAction<string[], number, {}>' is not assignable to parameter of type 'AnyAction | AnyAction | LocationChangeAction<any>'.`

**Comment by phryneas** [comment]
You most likely now have Redux 4.0.5 and 4.1.0/4.1.1 installed in your project in parallel, which causes that to happen.

**Comment by alextrastero** [comment]
Yes indeed, that solved it

```diff
   "dependencies": {
-    "@reduxjs/toolkit": "^1.5.1",
+    "@reduxjs/toolkit": "^1.6.1",
-    "redux": "^4.0.4",
+    "redux": "^4.1.1",
```

**Comment by phryneas** [comment]
One tip: When using RTK, you generally should not have `redux` in your package.json at all. RTK re-exports everything from redux, so you can just import it from RTK and remove that dependency.

**Comment by alextrastero** [comment]
👍🏼 thanks

**Comment by pycraft114** [comment]
@phryneas if I understood right, having redux 4.1.1 version causes its behavior?

**Comment by phryneas** [comment]
> @phryneas if I understood right, having redux 4.1.1 version causes its behavior?

having 4.0.5 and 4.1.1 side-by-side is problematic. having either of them standalone should be fine.
