### ISSUE TITLE
Start typing on search field crash the app

### ISSUE THREAD

**Issue by AndreiMrakov** [reduxjs/redux-toolkit#1399]
**Steps**:
- open https://redux-toolkit.js.org/
- click `search` area
- type some text

**Result**: 
 - white/black backgroung
 - error in console: `TypeError: Cannot read property 'value' of undefined`
 
![Redux Toolkit](https://user-images.githubusercontent.com/21972136/129050239-5ac8dcb2-6cd9-4ec4-b410-6523fc353508.jpg)

**Comment by msutkowski** [comment]
I'm unable to recreate this in any browser. It's possible there was some unrelated issue at this time? 

Is this still happening? Can you provide browser specs or a screen recording of this? 

The screen is clipped so it's hard to figure out what some of this is, but I'm not even sure how you had a GET request to /api/ happen.

**Comment by AndreiMrakov** [comment]
@msutkowski I got this error inside Promise handler after request: 
`https://bh4d9od16a-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20JavaScript%20(4.9.1)%3B%20Browser%20(lite)%3B%20docsearch%20(3.0.0-alpha.39)%3B%20docsearch-react%20(3.0.0-alpha.39)%3B%20docusaurus%20(2.0.0-beta.4)&x-algolia-api-key=82d838443b672336bf63cab4772d9eb4&x-algolia-application-id=BH4D9OD16A`

At the same time I cannot reproduce it in **Private mode**.

**Function that fails**:
```
function He(e) {
    if (!e.__docsearch_parent && !e._highlightResult)
        return e.hierarchy.lvl0;
    var t = (e._highlightResult ? e._highlightResult.hierarchy.lvl0 : e.__docsearch_parent._highlightResult.hierarchy.lvl0).value; // error appears here because of calling "value" of undefined
    return t && Te.test(t) ? t.replace(_e, "") : t
}
```

**Browser**: Microsoft Edge Version 92.0.902.78 (Official build) (64-bit)
