### ISSUE TITLE
How much of redux can redux-toolkit query take upon itself?

### ISSUE THREAD

**Issue by gregordotjs** [reduxjs/redux-toolkit#1402]
We've just started to work with redux-toolkit query (RTQ) and we absolutely love it. However, currently I had a case where there was no need for a slice, since RTQ did all the work we needed. Then, there was a request that you can add a new entry and save it - or cancel it. Now, not wanting to create a store and rewrite stuff, I just did this below the injectEndpoints definition (simplified):

```ts
export const addNewAction = (): AnyAction =>
  api.util.updateQueryData(
    "getAllStuff",
    undefined,
    (draft) => {
      draft.SubDraft.unshift({
        Id: null,
        Code: "",
        Description: "",
        Hours: ""
      });
    }
  ) as unknown as AnyAction;

export const removeNewAction = (): AnyAction =>
  api.util.updateQueryData(
    "getAllStuff",
    undefined,
    (draft) => {
      const codes= draft.SubDraft.filter(
        (code: ICode) => code.Id
      );
      draft.SubDraft = codes;
    }
  ) as unknown as AnyAction;
```

Now we're not sure if it's okay to directly manipulate the RTQ's state like this. Is this violating and presumptions? Should I just create a slice and rewrite most of the logics?

**Comment by phryneas** [comment]
You have to be aware that this might get removed from the state at any time RTKQ thinks nothing is using that cache entry any more. And any kind of refetching will overwrite it with a new value from server. So I'd rather make a slice for it - but generally, you live as dangerously as you are comfortable with ;)

**Comment by gregordotjs** [comment]
I agree with you there. However, I'm working with an active subscription, so this shouldn't get lost and everything else is pretty fixed. Currently, it is not possible that this is overwritten (can happen later if there are new features that need to be implemented, though). I feel like I'm working with API slice instead of creating my own. But yeah, I am walking a very thin line here. So I assume this is totally an anti-pattern:)

**Comment by phryneas** [comment]
Cleaning up a bit and closing this - I think we kinda resolved the conversation :)
