### ISSUE TITLE
Code splitting requires `tagTypes` to be defined at the parent level `createApi`

### ISSUE THREAD

**Issue by mkdudeja** [reduxjs/redux-toolkit#1403]
Hi Team,

**Actual:**
Code splitting requires the `tagTypes` to be defined at the parent level itself ie. `createApi`

**Expected:**
While doing code-splitting, it should be a total separation of concerns and there should be a way to define `tagType` from the partial endpoints configuration itself.

**CodeSandbox:**
https://codesandbox.io/s/rtk-code-splitting-7dpin?file=/src/app/services/posts.ts

Not sure, if we can currently define `tagType` while injecting endpoints as i didn't found it in the docs.

Let me know if any further details are required.

Thanks,
Manish

**Comment by phryneas** [comment]
You can use `enhanceEndpoints` before `injectEndpoints` to add new tag types on the go

**Comment by mkdudeja** [comment]
@phryneas Cool, thanks.

We are good to close this issue.
