### ISSUE TITLE
Enhancement: Code splitting at reducer level/ API to inject reducer 

### ISSUE THREAD

**Issue by mkdudeja** [reduxjs/redux-toolkit#1404]
It would be great if we have the option to inject the reducer at run time.

I know, there was discussion earlier on this @ https://github.com/reduxjs/redux-toolkit/issues/636

It would be great to have this ticket open as an enhancement request.

Thanks,
Manish Kumar

**Comment by markerikson** [comment]
We already have #1326 open to cover this.
