### ISSUE TITLE
EndpointBuilder type is not exported

### ISSUE THREAD

**Issue by atelic** [reduxjs/redux-toolkit#1407]
I would like to separate out my endpoints into smaller, more organized modules like this:
```ts
// myApi.ts
export const myApi = createApi({
  // <snip>
  endpoints: builder => ({
    ...myFooEndpoints(builder),
    ...myBarEndpoints(builder),
  })
});

// some-other-file.ts
const myFooEndpoints = (builder: EndpointBuilder) => ({
  // ...
})
```

However, the `EndpointBuilder` type is not exported from `rtk-query` causing a TS error in the endpoint constructor function. Would it be possible for this type to be provided?

**Comment by phryneas** [comment]
No. Please use the normal code splitting approach using `.injectEndpoints`

https://redux-toolkit.js.org/rtk-query/usage/code-splitting

**Comment by atelic** [comment]
Thanks

**Comment by kuangshp** [comment]
I wrote it like this, but it still doesn't work
```typescript
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const baseApi = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:5000' }),
  endpoints: (builder) => ({}),
});

```

```typescript
import { baseApi } from './base';

interface IAccountVo {
  id: number;
  username: string;
  age: number;
}
const userApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getAccountList: builder.query<Promise<IAccountVo[]>, void>({
      query: () => '/account',
      transformResponse: (response: { data: Promise<IAccountVo[]> }) => {
        return response.data;
      },
    }),
  }),
  overrideExisting: false,
});
export const { useLazyGetAccountListQuery, useGetAccountListQuery } = userApi;
export default userApi;
```

**Comment by londonbarrett** [comment]
it creates circular dependencies, that approach is not appropriate for escalating apps

**Comment by londonbarrett** [comment]
@phryneas do you have a better approach for not creating circular dependencies?

**Comment by markerikson** [comment]
@londonbarrett What "circular dependency" are you referring to here?

**Comment by londonbarrett** [comment]
If I have the main api and then I have some endpoints in another module, then it creates a circular dependency because I need to import the api first, inject the endpoints, and then export the api again

**Comment by markerikson** [comment]
That's not a circular dependency. The feature slice file depends on the API slice file, and then other code should `import { api } from 'features/someFeature/featureSlice'`.

**Comment by londonbarrett** [comment]
In my case it is creating dependencies, so it would be easier to create a set of endpoints and then export it an inject it in the main api file, but it is not possible because I don't have access to the EndpointBuilder

**Comment by markerikson** [comment]
@londonbarrett It would really help if you could put together a CodeSandbox that shows what you're trying to do, and how injectEndpoints is causing a problem.

**Comment by londonbarrett** [comment]
It's impossible to not create circular dependencies with this approach, if there was a way of exporting the endpoints and then inject them into the api, it would be much better

**Comment by markerikson** [comment]
@londonbarrett we're having a circular argument here :)  I'm still genuinely not seeing how the suggested approach of using `injectEndpoints` will result in a circular dependency. _Please_ show some code that demonstrates this problem happening.

**Comment by golergka** [comment]
Can this be re-opened? I need `EndpointBuilder` exported too for another purpose. Is there any particular reason against exporting it?

Here's my use case for it. I have a helper function that looks like this:

```Typescript
const wrapEvent = <Event extends ClientServerSocketEvent>(
  event: Event,
  builder: EndpointBuilder<BaseQueryFn, string, 'api'>,
): QueryDefinition<
  {
    args: InferSocketEventArgs<Event>;
    socketConnection: ServerSocket | undefined;
  },
  BaseQueryFn,
  string,
  InferSocketEventResult<Event>,
  'api'
> =>
  builder.query({
    query: (args) => ({ ...args, event }),
  });
```

Although this wrapper is completely trivial at runtime, the purpose of this function is to maintain complex type constraints based on our API definition which comes from a separate package shared between server and client. As a result, I can write api definition like this:

```
createApi({
  baseQuery,
  endpoints: (builder) => ({
    exampleEndpoint: wrapEvent(ClientServerSocketEvent.exampleEvent, builder),
  }),
});
```

Without writing out all the types, as they're automatically inferred from the passed `exampleEvent`.
