### ISSUE TITLE
RTK Query - ApiProvider that could accept multiple api stores.

### ISSUE THREAD

**Issue by omerman** [reduxjs/redux-toolkit#1410]
Hi, I have a project without redux, but I love the way RTK query properly manages the server communications. My project has multiple Apis to work with. I wanted to know if there is a way to keep the Api objects(using RTK Query) separated and use them with `ApiProvider` instead of creating a redux store for this myself.

something like

```jsx
// This is what I want to have
<ApiProvider stores={[api1, api2]}>...</ApiProvider>

// I guess this is possible, but ugly, and also I have many Apis..
<ApiProvider store={api1}>
  <ApiProvider store={api2}>{...}</ApiProvider>
</ApiProvider>
```

Looking forward hearing from you,
Thanks again for the great work

**Comment by phryneas** [comment]
No, at that point you would just need to create a Redux store and use that. `ApiProvider` is just a convenience, but creating a Redux store is not a lot of extra code.

But to make that thing clear: unless in extremely rare edge cases, your application should only have one api.
If you communicate with Google and with Twitter, that are two apis. If you communicate with endpoints that somehow belong to the same dataset/database/server, it should always be one api.

**Comment by omerman** [comment]
I agree, thanks!

**Comment by kahramanX** [comment]
I'm thinking the same question. I'm using the one API source but that have a lot of queries. Therefore, i should split it createApi's to many folder. What can i do for that reason?

**Comment by markerikson** [comment]
@kahramanX : follow the instructions in the "Code Splitting" docs page to use `injectEndpoints`:

- https://redux-toolkit.js.org/rtk-query/usage/code-splitting
- https://redux.js.org/tutorials/essentials/part-8-rtk-query-advanced#injecting-endpoints

**Comment by hvolmer** [comment]
Hello. I am curious why one cannot use _many_ multiple API? We (I) missed this recommendation when setting up our application and with something like 35 slices, we are starting to experience problems registering middleware in Mac chromium (not Safari or PC). I'm going to convert it to single api, but I'm still curious why it is bad practice. The grouping of multiple slices in redux tools was very nice... Thanks! Love this package.

> No, at that point you would just need to create a Redux store and use that. `ApiProvider` is just a convenience, but creating a Redux store is not a lot of extra code.
> 
> But to make that thing clear: unless in extremely rare edge cases, your application should only have one api. If you communicate with Google and with Twitter, that are two apis. If you communicate with endpoints that somehow belong to the same dataset/database/server, it should always be one api.

**Comment by markerikson** [comment]
@hvolmer multiple reasons:

- Invalidation works within _one_ RTKQ API definition by default.  (It's _technically_ possible to trigger invalidations across API slices, but you have to do that manually)
- An API slice is supposed to be a black box. Set it up once, let it handle the details, don't worry about how it works inside.
- Each API slice requires a separate middleware added to the store. Every middleware you add runs checks _every_ time you dispatch an action.  Adding dozens of middleware is going to slow down _all_ dispatched actions and cause perf problems.
- And finally, there's just no _reason_ to do that. If you just want to split up the endpoints across multiple files, RTKQ lets you inject endpoints into an existing API slice definition.  There's no actual benefit from creating many different API slices.

**Comment by EskiMojo14** [comment]
the middleware isn't "gigantic", it's still the same size. you define your API endpoints and the middleware only looks them up when it needs them
