### ISSUE TITLE
RTK Query - Problematic typings for mutation result

### ISSUE THREAD

**Issue by omerman** [reduxjs/redux-toolkit#1411]
Hi again ;)

![image](https://user-images.githubusercontent.com/6780529/129483541-f5d69d76-ab89-49e8-8da3-fb1d6f9e3de8.png)

![image](https://user-images.githubusercontent.com/6780529/129483637-c79a98db-80d3-44f3-aa8b-d24dea113d01.png)

on the attached image you can see that there is no simple way to check if the result is an error or not.
I'd suggest having the result typed like this: 

type Res = {
  data: Ingredient,
  error: undefined,
} | {data: undefined, error: unknown}.

With my suggestion there is an easy way of figuring out if the operation was a success, and extracting the data from it without getting a shout from TS compiler.

Another possibility(My personal favorite) would be to throw(reject promise) incase of error, and then we would be able to write something like this -

```js
async function func () {
  try {
    const {data: result} = await myMutation();
  } catch (e) {
   // handle error
  }  
}
```

Hope this makes sense to you as well,
let me know what you think

**Comment by phryneas** [comment]
That is already possible:

```js
async function func () {
  try {
    const result = await myMutation().unwrap();
  } catch (e) {
   // handle error
  }  
}
```

**Comment by omerman** [comment]
@phryneas Brilliant! thank you
