### ISSUE TITLE
RTKQ - how to work with derived booleans without UI flickering

### ISSUE THREAD

**Issue by Vagabun** [reduxjs/redux-toolkit#1415]
Hi!
An interesting problem just occurred, but some context comes first.
I have a query and a mutation, they're interconnected via tags, so query should be fired only after successful mutation. To show this process in the UI I'm using some kind of a loader that depends on derived booleans - on `isFetching` from the query and on `isLoading` from the mutation, something like `isFetching={isFetching || isLoading}`. There is a moment when mutation successfully finished, invalidated query cache and triggered query refetch but both flags became false for a second and in result loader got removed from the DOM and inserted again and this is resulting in UI flickering (I suppose it's a correct term for this?) that I don't know how to fix.

So, a question - how to combine several derived booleans in some flag that won't be updated until several requests will be finished?

state of the derived booleans in this process looks like this:
![image](https://user-images.githubusercontent.com/16858610/129598101-8982d484-42d0-455e-bf57-ac2acb914d55.png)

**Comment by phryneas** [comment]
You could probably use something like https://usehooks.com/useDebounce/

**Comment by Vagabun** [comment]
@phryneas Hi, thanks for the reply

Sorry, but using something like debounce means that I need to work with some kind of manually specified time delay for awaiting the mutate/request process to finish and I don't think that this is a good solution. I think that I need something that's conceptually similar to manually handling status flags like all of us did inside thunks/sagas before. 
And don't you mind if I ask - have you ever discussed such use cases? Like, it's not uncommon to have 5 requests on a screen and have special business requirements to wait until 4 of them will finish to trigger fifth and until that moment you need to show some loading state, but with this problem of intermediate state of derived booleans where all of them are false for a split second between requests we'll be getting UI flickering and so on and so on.

**Comment by phryneas** [comment]
I am suggesting that you debounce the calculation of your intermediate state, so that there is no flickering.

`const isFetching = useDebounce(r1.isFetching || r2.isLoading)`

Generally, there is not much to be done. The fact that the mutation finished (which immediately is written to state) triggers a react rerender and at the same tick the start of the other requests, which also triggers a react rerender)

**Comment by Vagabun** [comment]
@phryneas oh, now I see

ok, will try to use this approach with debounced value, thanks

I suppose you're referring to this [discussion](https://github.com/reactwg/react-18/discussions/21)?

**Comment by phryneas** [comment]
Yup, that was what I am referring to. I *think* that should already take care of that. If not that, then probably suspense for data fetching.

**Comment by Vagabun** [comment]
ok, debouncing is the solution, I've tried to do as you've advised, it works!

thanks again for the help and explanations, I'm closing the issue
