### ISSUE TITLE
injectEndpoints Can't take effect

### ISSUE THREAD

**Issue by kuangshp** [reduxjs/redux-toolkit#1419]
I wrote it according to the documentation, but it doesn't work when it's used in a component,[The official address](https://redux-toolkit.js.org/rtk-query/usage/code-splitting)

```typescript
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const baseApi = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:5000' }),
  endpoints: (builder) => ({}),
});
```

```typescript
import { baseApi } from './base';

interface IAccountVo {
  id: number;
  username: string;
  age: number;
}
const userApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getAccountList: builder.query<Promise<IAccountVo[]>, void>({
      query: () => '/account',
      transformResponse: (response: { data: Promise<IAccountVo[]> }) => {
        return response.data;
      },
    }),
  }),
  overrideExisting: false,
});
export const { useLazyGetAccountListQuery, useGetAccountListQuery } = userApi;
export default userApi;
```

**Comment by phryneas** [comment]
"It doesn't work" is not descriptive enough to help you at all. What do you expect and what does happen? And *please* don't answer with "I get an error", but with the exact error message.

**Comment by kuangshp** [comment]
> "It doesn't work" is not descriptive enough to help you at all. What do you expect and what does happen? And _please_ don't answer with "I get an error", but with the exact error message.

Sorry, my problem is not clearly described. It is ok for me to use the method without splitting the code, but when I use the method of splitting the code, I do not make Ajax requests in the test component. I am not sure whether I omitted the method of splitting the code according to the official website or something is wrong

This is my test component code，Ajax requests can be made both proactively and by clicking on text
```typescript
import React from 'react';
import {
  useLazyGetAccountListQuery,
  useGetAccountListQuery,
} from './store/api/account';

export const Test: React.FC = () => {
  const { data } = useGetAccountListQuery();
  console.log(data, 'account');
  const [trigger] = useLazyGetAccountListQuery();
  const getData = () => {
    trigger();
  };
  return <div onClick={getData}>test</div>;
};
```

```typescript
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

interface IAccountVo {
  id: number;
  username: string;
  age: number;
}
const accountApi = createApi({
  reducerPath: 'accountApi',
  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:5000' }),
  tagTypes: ['account'],
  endpoints: (builder) => ({
    getAccountList: builder.query<Promise<IAccountVo[]>, void>({
      query: () => '/account',
      transformResponse: (response: Promise<IAccountVo[]>) => {
        return response;
      },
    }),
  }),
});
export const { useLazyGetAccountListQuery, useGetAccountListQuery } =
  accountApi;
export default accountApi;
```
However, I implement it according to the code splitting method stated on the official website. The code is as follows: I cannot initiate Ajax request when I am in the same test component as above. I wonder if there is something missing or something wrong
```typescript
import { baseApi } from './base';
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

interface IAccountVo {
  id: number;
  username: string;
  age: number;
}
const accountApi = baseApi.injectEndpoints({
  // reducerPath: 'accountApi',
  // baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:5000' }),
  // tagTypes: ['account'],
  endpoints: (builder) => ({
    getAccountList: builder.query<Promise<IAccountVo[]>, void>({
      query: () => '/account',
      transformResponse: (response: Promise<IAccountVo[]>) => {
        return response;
      },
    }),
  }),
  overrideExisting: false,
});
export const { useLazyGetAccountListQuery, useGetAccountListQuery } =
  accountApi;
export default accountApi;
```

**Comment by phryneas** [comment]
You still say

> I cannot initiate 

I have no idea how that looks.

Does just nothing happen and it stays in a loading state forever? Do you get an error message? Does the browser crash?

Please describe the actual behaviour!

**Comment by kuangshp** [comment]
> You still say
> 
> > I cannot initiate
> 
> I have no idea how that looks.
> 
> Does just nothing happen and it stays in a loading state forever? Do you get an error message? Does the browser crash?
> 
> Please describe the actual behaviour!

There are no errors, just no Ajax requests, but I'll give you a demo, maybe to get the point straight
[demo](https://codesandbox.io/s/stupefied-https-qwcrk?file=/src/App.js)

**Comment by phryneas** [comment]
You need to set up your baseApi (and **only your baseApi**) at the correct reducerPath in your store.

```diff
const rootReducer = combineReducers({
-  accountApi: accountApi.reducer
+  [baseApi.reducerPath]: baseApi.reducer
});
```

The same way you have to add the middleware for `baseApi` and **only the baseApi**.

To make this clear: calling `injectEndpoints` **injects (in other words, adds) the endpoints into your baseApi**. After that, they are part of your baseApi.

You just export them from the other files to make sure that the `injectEndpoint` call definitely happened before using them.

**Comment by kuangshp** [comment]
Thank you. The first thing I looked at was a variable that was defined on the inside, so I just wrote it in a dead way on the outside, and I could use it when I wasn't doing the split, so I didn't worry about it。
