### ISSUE TITLE
RTK: CreateSlice Reducer without Payload TS Error

### ISSUE THREAD

**Issue by jasoncomes** [reduxjs/redux-toolkit#1421]
Hi there - I'm by at no means a Typescript expert like your team is. I followed `Redux Toolkit` examples and can't figure out why its inferring `ActionCreatorWithPayload` interface and not `ActionCreatorWithoutPayload` interface when I'm dispatching an action with no payload declared in the reducer.

**TS Error**
```
Expected 1 arguments, but got 0.ts(2554)
createAction.d.ts(123, 6): An argument for 'payload' was not provided.
(alias) deactivateModal(payload: any): {
    payload: any;
    type: string;
}
import deactivateModal
Calling this redux#ActionCreator with an argument will return a PayloadAction of type T with a payload of P
```

By chance would you know what I'm doing incorrectly? Let me know if I need to include more context, thank you!

**createSlice**
![Screen_Shot_2021-08-18_at_10_37_28_AM](https://user-images.githubusercontent.com/5714439/129928197-5f1cb514-94fe-41fa-af71-574403e60363.png)

**dispatch of action in component**
![Screen_Shot_2021-08-18_at_10_40_08_AM](https://user-images.githubusercontent.com/5714439/129928682-609bd992-6c40-40fe-9b03-82cad9636b86.png)

**tsconfig.json**
![Screen Shot 2021-08-18 at 10 38 53 AM](https://user-images.githubusercontent.com/5714439/129928339-9452e79c-fbd6-47e7-b369-813f8a87cfd2.png)

**.eslintrc**
![Screen Shot 2021-08-18 at 10 50 42 AM](https://user-images.githubusercontent.com/5714439/129930287-2908f21f-6a42-4b60-b82b-1c37a4bfdf56.png)

**Comment by phryneas** [comment]
Generally, that should work. Some questions:

What editor are you using?
What TS version are you using?
Can you create a minimal reproduction for this?

**Comment by jasoncomes** [comment]
Hey @phryneas, here you go:

**What editor are you using?**
```
Visual Studio Code (VSC)
Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z (1 wk ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 19.6.0
```

What TS version are you using?

```
typescript@4.3.5
```

**Can you create a minimal reproduction for this?**

Absolutely -> https://github.com/jasoncomes/redux-toolkit-example

**Comment by phryneas** [comment]
The problem is this type annotation
![image](https://user-images.githubusercontent.com/4282439/130236447-591cf35e-12a2-49dd-9842-780471a81d30.png)


It converts your slice that has a very specific type down to a `Slice<any>`. Do not write type annotations like that - they erase important type information. Same goes for your store declaration.

**Comment by AndreySFN** [comment]
There is the same problem without type specification.
Vite config:
![image](https://github.com/reduxjs/redux-toolkit/assets/54359037/ae92bb96-1f44-4952-a82a-4eaba4f42bc9)
TS config: 
![image](https://github.com/reduxjs/redux-toolkit/assets/54359037/625c1944-5e6a-4b08-bdff-c31a350d82a7)
Slice: 
![image](https://github.com/reduxjs/redux-toolkit/assets/54359037/c190add8-b394-4bf0-ba89-7b13fc4a684c)
ESLint error:
![image](https://github.com/reduxjs/redux-toolkit/assets/54359037/fcd74cdf-e0ee-4f8d-8014-9e2c41afb1f9)

Intelij IDEA 2023.1.3
TS version: 5.0.2
Node: v18.17.0

**Comment by phryneas** [comment]
![grafik](https://github.com/reduxjs/redux-toolkit/assets/4282439/dc1950f3-4ec1-4c88-ac8d-9d7a3e174f21)
Remove this as well. We show that nowhere in our documentation. These parameters are to be inferred, not manually specified.

**Comment by AndreySFN** [comment]
Thank you. Reason of the problem was really it))
