### ISSUE TITLE
[reduxjs/toolkit + Expo] Could not resolve dependency react@"^16.14.0 || ^17.0.0" from @reduxjs/toolkit@1.6.1

### ISSUE THREAD

**Issue by Sixtisam** [reduxjs/redux-toolkit#1422]
I want to use `@reduxjs/toolkit` in combination with Expo (the latest Expo SDK 42).

When I'm trying to `npm i @reduxjs/toolkit@1.6.1 --save` in an Expo project the following error is shown (full log at end of post).

```
npm ERR! Could not resolve dependency:
npm ERR! peerOptional react@"^16.14.0 || ^17.0.0" from @reduxjs/toolkit@1.6.1
```

This is because Expo SDK has the following dependencies on react:

```
    "react": "16.13.1",
    "react-dom": "16.13.1",
```
I assume, the same will happen when using plain react-native.
My question:

**Why `@reduxjs/toolkit` has a peerDependency on react?** 

IMHO, `@reduxjs/toolkit` should be completely independent of react. The connection between redux and react should be inside `react-redux`.

-----------------------------------------------------------------------------------------------------------------------

Steps to reproduce (Expo SDK 42, choose blank template without typescript):
```
expo init testproject
npm i @reduxjs/toolkit --save
````

-----------------------------------------------------------------------------------------------------------------------

npm -v: 7.20.6
node -v: 14.17.1

Complete log:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @reduxjs/toolkit@1.6.1
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   peer react@"*" from @react-navigation/native@6.0.2
npm ERR!   node_modules/@react-navigation/native
npm ERR!     peer @react-navigation/native@"^6.0.0" from @react-navigation/native-stack@6.1.0
npm ERR!     node_modules/@react-navigation/native-stack
npm ERR!       @react-navigation/native-stack@"^6.0.4" from the root project
npm ERR!     peer @react-navigation/native@"^6.0.0" from @react-navigation/elements@1.1.0
npm ERR!     node_modules/@react-navigation/native-stack/node_modules/@react-navigation/elements
npm ERR!       @react-navigation/elements@"^1.1.0" from @react-navigation/native-stack@6.1.0
npm ERR!       node_modules/@react-navigation/native-stack
npm ERR!         @react-navigation/native-stack@"^6.0.4" from the root project
npm ERR!     3 more (@react-navigation/stack, @react-navigation/elements, the root project)
npm ERR!   peer react@"*" from @react-navigation/core@6.0.1
npm ERR!   node_modules/@react-navigation/native/node_modules/@react-navigation/core
npm ERR!     @react-navigation/core@"^6.0.1" from @react-navigation/native@6.0.2
npm ERR!     node_modules/@react-navigation/native
npm ERR!       peer @react-navigation/native@"^6.0.0" from @react-navigation/native-stack@6.1.0
npm ERR!       node_modules/@react-navigation/native-stack
npm ERR!         @react-navigation/native-stack@"^6.0.4" from the root project
npm ERR!       4 more (@react-navigation/elements, @react-navigation/stack, ...)
npm ERR!   12 more (@react-navigation/native-stack, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional react@"^16.14.0 || ^17.0.0" from @reduxjs/toolkit@1.6.1
npm ERR! node_modules/@reduxjs/toolkit
npm ERR!   @reduxjs/toolkit@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peerOptional react@"^16.14.0 || ^17.0.0" from @reduxjs/toolkit@1.6.1
npm ERR!   node_modules/@reduxjs/toolkit
npm ERR!     @reduxjs/toolkit@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by phryneas** [comment]
> Why @reduxjs/toolkit has a peerDependency on react?

Because the entry point @reduxjs/toolkit/query/react ships with hook support. 

It **is** an *optional* peer dependency though - your package manager should pick up on that and not force them to be installed:

```json
  "peerDependenciesMeta": {
    "react": {
      "optional": true
    },
    "react-redux": {
      "optional": true
    }
  },
```

Generally, you should also pretty much be able to just update your react version I assume?

**Comment by markerikson** [comment]
RTK has a peer dependency on React _and_ React-Redux, because we actually use both of them for the RTK Query hooks API:

https://redux-toolkit.js.org/rtk-query/overview#use-hooks-in-components

However, this usage is only through a specific additional entry point, `@reduxjs/toolkit/query/react`.  Both the `@reduxjs/toolkit` and `@reduxjs/toolkit/query` entry points are still entirely UI-agnostic. The only time the React dependency comes into play is if you're explicitly importing from that React-specific endpoint.

As far as the actual usage goes, React 16.13 ought to work fine.
