### ISSUE TITLE
actions don't get inferred when the type's fields are all optional

### ISSUE THREAD

**Issue by lourenci** [reduxjs/redux-toolkit#1423]
Hi, thanks for the library.

Probably, some mistake from my side. But, I don't get the action inferred when all the type's fields are optional. Shouldn't toolkit infer the action type by the generic of `PayloadAction`?

ok:
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/2339362/129956391-941d8474-ae35-4b88-b629-98b1d282ec48.png">

with error:
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/2339362/129956441-e69ce572-1d6f-4fb5-b1a1-0b4d72ab269e.png">

**Comment by phryneas** [comment]
Yeah, but at that moment it cannot distinguish it any more from `unknown` or the empty type (that pretty much equals `any`).
Could be solvable though. I'll add it to the list.

**Comment by lourenci** [comment]
Thank you for your reply, @phryneas. I would love to help on this, but I'm a layman with typescript right know.

Just out of knowing what are the side effects on this (probably, you already know): The `match` function is not being able to infer the payload action.

<img width="634" alt="image" src="https://user-images.githubusercontent.com/2339362/130236605-d60083d0-0eff-4ae1-bc6a-70e64bb99972.png">

**Comment by phryneas** [comment]
Yupp.

For your case, you could do something like an `AtLeastOne` type:

```ts
interface Filters {
  name: string
  age: number
  city: string
}

type AtLeastOne<T extends Record<string, any>> = keyof T extends infer K ? K extends string ? Pick<T, K & keyof T> & Partial<T> : never : never

type AtLeastOneFilter = AtLeastOne<Filters>
```

**Comment by boutahlilsoufiane** [comment]
I'm going to do this.

**Comment by markerikson** [comment]
For now we should probably add a docs entry in the "TS Usage" page.
