### ISSUE TITLE
What's the best approach when re-using reducer logic with TS?

### ISSUE THREAD

**Issue by aidan-keay** [reduxjs/redux-toolkit#1439]
I'm fairly new to redux/redux-toolkit and I'm currently trying to create reusable/generic slices. I also need to create some enhancer reducers that should be merged with these slices to add additional state and functionality, (i.e. loading, redo, undo, reset actions). I also need to prefix the slice action types so that each slice only responds to action types that are prefixed with its slice name.

What is the best way to do this? Should I be using createSlice most of time and passing reducers as an argument?:

```ts
export const createGenericSlice = ({
  name = "",
  initialState,
  reducers,
}) => {
  return createSlice({
    name,
    initialState,
    reducers: {
      start(state) {
        state.status = "loading";
      },
      ...reducers,  // Is there a way to do this with the builder callback notation instead?
    },
  });
};
```

Also, how would I prefix the generated action types? TS won't infer the correct action type if you use string interpolation (i.e. ```[`${prefix}_actionName`]: reducer```. To get around this I have not been using createSlice and have been creating action types manually but it was beginning to feel a bit hacky:

```ts
import { createReducer, createAction } from "@reduxjs/toolkit";

type ActionNameMap = Record<
  "add",
  string
>;
export const createObjectCollectionSlice = <T extends object>({
  add,
}: ActionNameMap) => {
  const actions = {
    add: createAction<T>(add),
  };
  const reducer = createReducer<T[]>([], (builder) => {
    builder
      .addCase(actions.add, (state, action) => {
        return [...state, action.payload];
      })
     .addCase(actions.remove, (state, action) => {
        return state.filter((object) => object.key !== action.payload);
      })
  });
  return { reducer, actions };
};
```

Is there a more appropriate solution?

**Comment by markerikson** [comment]
We've got some examples of wrapping `createSlice` with TS here - does this help?

https://redux-toolkit.js.org/usage/usage-with-typescript#wrapping-createslice

**Comment by aidan-keay** [comment]
> Note that generally the `name` field is the key to distinguishing actions between different slices, so `'sliceA/stuffHappened'` is different than `'sliceB/stuffHappened'`. So, just giving each slice a unique name should be sufficient.

Ah right, thanks I didn't realise the action types were automatically prefixed.

**Comment by markerikson** [comment]
Yep, that's one of the key points of `createSlice` :)
