### ISSUE TITLE
`setOne/setMany` missing from `createEntityAdapter` documentation

### ISSUE THREAD

**Issue by jjspace** [reduxjs/redux-toolkit#1447]
I recently stumbled across issue #954 when looking for something else. I saw that it was closed but I didn't even know those methods existed because they're not shown in the CRUD functions section of `createEntityAdapter` (see below). It would be great if these could be added and described there so people don't have to look through the change log to notice they were added.

https://redux-toolkit.js.org/api/createEntityAdapter#crud-functions

![20210826_132340](https://user-images.githubusercontent.com/8007967/131008213-3ca136d9-b0de-49c6-a61c-4be4591dfe68.png)

**Comment by markerikson** [comment]
I'd have to check the implementation, but I'm pretty sure the `set` functions completely replace any existing data, in a couple different ways.  So, `setOne/setMany` will guarantee that the items you just provided end up in the state exactly as-is, while leaving other items intact. `setAll` completely removes all existing data and replaces everything with exactly what you provided.

Agreed that we could use some better documentation here.  If you've got some time to submit PRs to improve this, I'd appreciate it!

**Comment by jjspace** [comment]
@markerikson I opened up a PR with some updated docs. Please take a look when you get a chance!
