### ISSUE TITLE
Why this causing an error?

### ISSUE THREAD

**Issue by 1alexvash** [reduxjs/redux-toolkit#1450]
I'm following redux toolkit tutorial, and I'm trying to extend the functionality of the counter, and I am wondering why this throws an error?
![image](https://user-images.githubusercontent.com/46556479/131225694-f2f30fd1-f5ec-4fb5-a6fc-f92b0f3a559d.png)

**Comment by markerikson** [comment]
The error says that you have more than one variable named `todos` inside of here. Can you post the complete code as code rather than a screenshot?

**Comment by 1alexvash** [comment]
I have added this to my TS config, and the issue doesn't occur anymore

```ts
"compilerOptions": {
    "lib": ["es6"]
  }
```

**Comment by markerikson** [comment]
Glad that's working!
