### ISSUE TITLE
store.dispatch infers as never

### ISSUE THREAD

**Issue by hydrognomik** [reduxjs/redux-toolkit#1454]
Hello. I'm trying to migrate on redux-toolkit. When I try to get `AppDispatch` type it infers as `never`. Can you help with this?
```js
export type TRootState = StateFromReducersMapObject<typeof reducer>;

export const initStore = (preloadedState: DeepPartial<TRootState>) =>
  configureStore({
    reducer,
    middleware: getDefaultMiddleware => getDefaultMiddleware().prepend(middlewares),
    devTools: process.env.NODE_ENV !== 'production',
    preloadedState: restoreState(preloadedState),
  });

export type TAppDispatch = ReturnType<typeof initStore>['dispatch']; // <= never
```

**Comment by markerikson** [comment]
Hmm. Setup is a bit different than what we usually show, but that _seems_ like it ought to work. Can you put together a CodeSandbox that shows this happening?

**Comment by hydrognomik** [comment]
Thank you for your response. Unfortunately on codesandbox, everything works as expected and I couldn't reproduce this behavior. Looks like the problem in middlewares because if I omitted middleware key then dispatch would infer, according to intellij, into something like:
```js
{} extends { thunk: { extraArgument: infer E } }
  ? ThunkMiddleware<any, AnyAction, E>
  : ThunkMiddleware<any, AnyAction, null> | ThunkMiddleware<any, AnyAction> extends Middleware<
      infer DispatchExt,
      any,
      any
    >
  ? DispatchExt extends Function
    ? IsAny<DispatchExt, never, DispatchExt>
    : never
  : never & Dispatch<any>;

```

**Comment by markerikson** [comment]
Is the error actually happening when you _compile_ your project, or just in the IDE?  We've seen a number of reports of IntelliJ/WebStorm not understanding RTK's TS types correctly.

**Comment by hydrognomik** [comment]
Both cases. At compile time I get a lot of errors like `dispatch can't handle thunks` because of that.

**Comment by markerikson** [comment]
Hmm. Yeah, we'd need to see some kind of reproduction to have a better idea what's going on here.

**Comment by hydrognomik** [comment]
`middlewares` is array of four middlewares.
```js
const middlewares = [
  middleware1,
  middleware2,
  // ...
];
```
Yeah, I see, I'll try to reproduce it somehow 🤔 , thanks.

**Comment by markerikson** [comment]
Yeah, but _what_ middleware, specifically? How are they typed?  It's quite possible that the typing for those middlewares is insufficient and/or broken in some way.

**Comment by hydrognomik** [comment]
`const middleware: Middleware<{}, TRootState> = store => next => action => …`

**Comment by phryneas** [comment]
And can you reproduce it with a variable of that type in the CodeSandbox?

**Comment by hydrognomik** [comment]
Sure, [here](https://codesandbox.io/s/eloquent-star-smc2r?file=/src/store.ts) it is, but it works as described in docs. We are using typesafe-actions, could this be the reason for such strange behavior?

**Comment by phryneas** [comment]
That should not mess with your store types. (But in general, there is no point using typesafe-actions as RTK does the same just with less TS code).

Can you verify that you don't have the types for Redux 4.0.5 and 4.1.0/1 both installed in your `node_modules`? That seems to do weird things to `dispatch` types in general.

**Comment by hydrognomik** [comment]
Turned out there were only types for `redux@4.0.4`, so I installed 4.1.0 explicitly, IntelliJ still shows AppDsipatch as never, but the result of `useDispatch()` typed properly. Thanks a lot for your help.

**Comment by phryneas** [comment]
The only fix for IntelliJ is unfortunately uninstalling it and using VSCode. 

There are issues about this in their issue tracker that they've been ignoring for years. That product is just bad for use at TS at this point, which is sad because generally it's great software.
