### ISSUE TITLE
RTK Query: How can I select the result after mutation from the store when I have two components?

### ISSUE THREAD

**Issue by GusevDV** [reduxjs/redux-toolkit#1458]
Hello!
Recently I started using RTK Query and I have a problem with selecting data from the store after mutation. I don't understand what is the best way to do this.
For example, I have two components. I trigger mutation in the first component and I need to get results in the second component. I can't use the useMutation hook because it works fine only in one component. Also I don't want to put a useMutation hook to a parent. 

My createAPI: 
```javascript
export const subscriptionApi = createApi({
  reducerPath: 'subscribe/create',
  baseQuery: fetchBaseQuery({ baseUrl: '/api' }),
  tagTypes: ['Subscription'],
  endpoints: (builder) => ({
    getSubscriptionStatus: builder.query<Subscription, string>({
      query: (serviceID: string) => `subscription/${serviceID}`,
    }),
    createSubscription: builder.mutation<Subscription, string>({
      query: (serviceID: string) => ({
        url: 'subscription/',
        method: 'POST',
        body: {
          serviceID,
        },
      }),
    }),
  }),
});

export const { useGetSubscriptionStatusQuery, useCreateSubscriptionMutation } = subscriptionApi;
```

My plan is to select the result from the store manually, but I don't know how I can do this the best way, because each request has a unique cache key. Please help me find any good solutions.

**Comment by GusevDV** [comment]
I seem to have a found solution but I'm not sure about if it's correct
```javascript
export const selectSubscriptionStatus = (state: GlobalState) => state[subscriptionApi.reducerPath];
```

**Comment by XiyuChen-95** [comment]
Hi did you figure this out by any chance?

**Comment by jeffohbabygames** [comment]
answer?

**Comment by EskiMojo14** [comment]
[`fixedCacheKey`](https://redux-toolkit.js.org/rtk-query/usage/mutations#shared-mutation-results), as linked in the PR.

**Comment by jeffohbabygames** [comment]
this is my code sir
```
export const LoginSlice = createApi({
  reducerPath: "login",
  keepUnusedDataFor: 30,
  tagTypes: ["login"],
  baseQuery: wrappedBaseQuery,
  endpoints: (builder) => ({
    login: builder.mutation({
      query: ({ user }) => ({
        url: "/api/email-login",
        method: "POST",
        body: user,
      }),
      providesTags: ["login"],
      keepUnusedDataFor: 30,
      invalidatesTags: ["login"],
    }),
  }),
});

export const { useLoginMutation } = LoginSlice;
```

`{"isError": false, "isLoading": false, "isSuccess": false, "isUninitialized": true, "originalArgs": undefined, "reset": [Function anonymous], "status": "uninitialized"}`
This is what im getting in 

 const [login, result] = useLoginMutation({
    fixedCacheKey: "mySharedKey",
  });


i still can't get the data using fixedCachedKey what do you is the problem here sir @EskiMojo14

**Comment by ZohaibAhmad786** [comment]
[https://redux-toolkit.js.org/rtk-query/usage/mutations#shared-mutation-results](https://redux-toolkit.js.org/rtk-query/usage/mutations#shared-mutation-results) This doc will help you to fix your query
