### ISSUE TITLE
RTKQ: how to accept a response of text/html

### ISSUE THREAD

**Issue by XiyuYoyoChen** [reduxjs/redux-toolkit#1463]
**Goal**
Display text on a page from a network request-response with content-type of text/html 

**Description**
I am trying to make a request to fetch the version of the backend and display it on the page using RTKQ. However, the response header's content-type is of `text/html`, the returning version text is a version such like `"ver1.2.3"`, the redux tool extension shows me a parsing error, and has an error message with `"SyntaxError: Unexpected token . in JSON at position 3"`. In this case, I could not use the data in my component as it will show an `undefined` value. I tried using `transformResponse` , but when I try to console log the `response.data` in `transformResponse`, I don't see anything printing out on the console. 

**Code Base**
```js
// index file with empty api
export const baseApi = createApi({
  reducerPath: "baseApi",
  baseQuery: fetchBaseQuery({ baseUrl: API_BASE }),
  endpoints: () => ({}),
});

// splitted file with different endpoints
export const apiWithVersion = baseApi.injectEndpoints({
  endpoints: (build) => ({
    fetchVersion: build.query<string, void>({
      query: () => {
        return {
          url: API_VERSION_ENDPOINT,
          method: "GET",
        };
      },
      // I tried to see if this will work
      transformResponse: (response: { data: any }) => {
        // console log the response.data to see what Im getting here
        // nothing is being printed on the console
        console.log("transformResponse: ", response.data);
        return response.data;
      },
    }),
  }),
});

export const { useFetchVersionQuery } = apiWithVersion;
```

**Behavior**
When I am trying to get the data from the response as `const { data } = useFetchVersionQuery()`, the variable `data` is always undefined due to the issue described above

**Action Tree from Redux Extension Tool**
```js
type: "base/Api/executeQuery/rejected"
payload: 
  status: "PARSING_ERROR"
  originalStatus: 200
  data: "ver1.2.3"
  error: "SyntaxError: Unexpected token . in JSON at position 3"
meta:
  baseQueryMeta:
    request: {}
    response: {}
  arg
    subscribe: true
    subscriptionOptions
      pollingInterval: 0
    endpointName: "fetchVersion"
    requestId: "123"
    rejectedWithValue: true
    requestStatus: rejected
    aborted: false
    condition: false
error:
  message: "Rejected"
```

How could I use `transformResponse` to accomplish this goal? or if `transformResponse` is not the right way to go with this case, how would I get the text to display on page using RTK Q?

**Comment by phryneas** [comment]
https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery#parsing-a-response

```
      query: () => {
        return {
          url: API_VERSION_ENDPOINT,
          method: "GET",
          responseHandler: 'text'
        };
      },
```

**Comment by XiyuYoyoChen** [comment]
@phryneas That is exactly what Im looking for. Been looking at the wrong place all this time. Now everything is working correctly. Thanks a lot!
