### ISSUE TITLE
`this` has been rewritten to `undefined`

### ISSUE THREAD

**Issue by soelen** [reduxjs/redux-toolkit#1466]
I recently integrated `redux-toolkit` in one of my projects and my rollup based building setup throws a warning out:

```
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules\@reduxjs\toolkit\dist\redux-toolkit.esm.js
1: var __extends = (this && this.__extends) || (function () {
                    ^
2:     var extendStatics = function (d, b) {
3:         extendStatics = Object.setPrototypeOf ||
...and 5 other occurrences
```

Perhaps this is nothing to be concerned about but I decided to create an Issue just in case.

I also integrated `redux-toolkit` in one of my public projects in order to make this issue reproduceable:

## How to reproduce

- clone [Workbox Tests](https://github.com/soelen/workbox-tests)
- run `npm i`
- run `npm run build`

## Files of interest

My whole redux setup is inside the [store](https://github.com/soelen/workbox-tests/tree/main/src/script/store) folder.  I use Webcomponents/Lit to establish a component architecture. My base class [page-element](https://github.com/soelen/workbox-tests/blob/main/src/script/pages/page-element.ts) is subscribed to the store and some of [my](https://github.com/soelen/workbox-tests/blob/main/src/script/pages/page-about.ts) [pages](https://github.com/soelen/workbox-tests/blob/main/src/script/pages/page-home.ts) make use of it.

**Comment by phryneas** [comment]
That's nothing to worry about, that's just one bundler complaining about code from another bundler that is a bit defensive ;)

**Comment by soelen** [comment]
Thanks a bunch @phryneas! For future googlers, For the time being I just put this in the rollup option `onwarn` prop; based on [https://github.com/rollup/rollup/issues/1518#issuecomment-321875784](this) solution:

```
// ...
export default {
  // ...
  onwarn(warning, warn) {
      if (warning.code === 'THIS_IS_UNDEFINED') return;
      warn(warning);
  },
  plugins: [
  // ...
```
