### ISSUE TITLE
[Query] Accessing cached data outside of a react component

### ISSUE THREAD

**Issue by ClementMindflow** [reduxjs/redux-toolkit#1472]
Hello !

We are in the process of integrating RTK query in our app.

Our current "architecture" is as follow:

All the business logic actions are written inside services which are plain JS classes.  
Those services are passed using react context in order for the component tree to be able to call services functions.

As of now those services were accessing the redux store directly to perform the appropriate logic.

Now that we are moving to RTK, accessing the RTK cache from a service is less trivial:  
As far as I can see, the only way to access it is via the [select][1] function of the relevant endpoint.

The point is that this method is a "selector factory" and using it outside of a react component doesn't seems to be the right way to go.

Here is an exemple:

    class TodoService {
       getTodoTitle( todoId: string ) {
         // This doesn't looks the right way to do it
         const todoSelector = api.endpoints.getTodo.select( {id: todoId } );
         const todo = todoSelector( state )
         return todo.data.title
       }
    }

Is there any way to implement safely the following code

    class TodoService {
       getTodoTitle( todoId: string ) {
          // Is there any way to do that kind of call ?
          const todoEntry = api.endpoints.getTodo.getCacheEntry( {id: todoId } );
          return todoEntry.data.title
       }
    }

I guess that the answer is "no" and I have to refactor our whole architecture, but before doing so I'd like to be sure that there is no alternate approach.

Note that I could build the cache entry key by myself, but that also doesn't sound like a robust approach...

  [1]: https://redux-toolkit.js.org/rtk-query/api/created-api/endpoints#select

**Comment by phryneas** [comment]
The thing is that you don't want to just get the cache entry - the selector does a little more for you than just that. 
So let's just stay with "please use the selector" and "we won't add *another* way of doing that" because, selectors is how your code should interact with Redux all the time - React or not.

If you are not calling this code from React where you would need a stable object reference, it is good as it is. The selector factory will create a new selector and thus you get an un-memoized result. This is not perfect, but if you are not relying on referential equality, it also does not hurt at all.

If you want to have the referential equality, you'll have to store the selector in some way, probably as a class property.

Something like this would be possible:

```js
class TodoService {
   getSelectorForTodo(todoId: string) {
     if (this._lastId !== todoId) 
       this._lastSelector = api.endpoints.getTodo.select( {id: todoId } )
     return this._lastSelector
   }

   getTodoTitle( todoId: string ) {
     const todo = this.getSelectorForTodo(todoId)(state)
     return todo.data.title
   }
}
```

**Comment by ClementMindflow** [comment]
Thx for the quick answer.
That's pretty clear, and we'll probably go that way.

However I'd like to discuss some details about your comments (to make sure i fully understand your answer):

What does the selector is doing appart creating the appropriate cache key and returning the value ?

In such scenario what could be the tradeoff of having a readonly direct access to the cache ?

**Comment by phryneas** [comment]
At the given moment, the selector does two things:

* It adds status booleans, but could in the future add more information - or remove some that is just not public
* It is a **documented api**. 
To make this clear: nothing in our docs mentions direct state access, and for good reason. It might be necessary for some very edge case scenarios, but we are not giving any guarantee that it won't break tomorrow. 
You should treat the state shape as a black box and only access it with the tools we provide you. 
We could completely refactor the state structure internally and would not consider it a breaking change - after all, that state structure is not part of the documented external interface of RTK-Q.

**Comment by ClementMindflow** [comment]
Okay make totally sense.
Thx
