### ISSUE TITLE
RTK Query with a single query for a Graph structure

### ISSUE THREAD

**Issue by saadflow** [reduxjs/redux-toolkit#1491]
Hi !
My team is integrating RTK Query to fetch and cache data from a graphQL API.
Initially, RTK Query seemed like a good candidate for our use case, but the more we connect our existing logic to it, the more it feels like either it's not a good fit, or we lack knowledge / patterns to move forward.

Our API serves objects that form a graph, and it looks something like this :

``` GraphQL
type Graph {
  id: String!
  nodes: [Node!]!
  edges: [Edge!]!
}

type Node {
  id: String!
  graphId: String!
}

type Edge {
  id: String!
  graphId: String!
  sourceNodeId: String!
  targetNodeId: String!
}
```

And we have a `getGraphById` endpoint, that returns our whole graph.

Having one query that returns everything, then selecting individual objects from the result is straightforward when using the `useQuery` hook, and passing a `selectFromResult` option, but if you need to do so inside a useEffect, or useCallback, with logic that is a little more complex (traversing the graph for example), it's less trivial.

The many mutations we perform on nodes and edges need to be reflected in the cache, so we have to do a lot of micro optimistic cache updates on one single query. This unique query beeing at the top level of our react tree, the whole app is re render on each update.
And we are unable to find a workaround for that.
Also, performing those updates feels like redux, but with more overhead. To me the point of RTK Query is not to have too much interactions with the cache.

I'm not going to explain our (many) issues in detail because it comes down to this:

Is RTK Query a good fit when working with one single query ?
Is RTK Query a good fit when working with graphs ?

Thanks a lot :D

**Comment by phryneas** [comment]
Phew. I've honestly never heard of anyone doing "one single query for the full application" in graphql at all. 
Personally I use graphql very differently, always querying what I need in the respective component - maybe with nesting, but also a lot of times just selecting something by a nodeId that comes in through a prop.

Generally: RTK-Q is a document cache (one query-argument pair, one cache entry). It sounds like you might be better of with a normalized cache. So if looking at alternatives don't look at SWR or React Query, but look at Apollo or URQL with the advanced cache.

**If** you want to stay with RTK-Q (I don't know if that makes sense, only you can really evaluate that), I'd probably recommend using a `selectFromResult` that only selects loading state, but no actual data (or a bare minimum) in the parent component and moving those `useEffects` in an immediate child that is a sibling, not a parent, to all the other components.
