### ISSUE TITLE
Async `condition` in `createAsyncThunk`

### ISSUE THREAD

**Issue by thorn0** [reduxjs/redux-toolkit#1494]
I need my thunk to detect that another instance of the same operation is already running and to fulfill the promise (without dispatching any actions) only after that other instance is done. The code that dispatches the thunk doesn't care who started the operation, it just needs it to complete. As I have more than one such place in my code, I'd prefer to encapsulate this logic into the thunk, which would be possible if `options.condition` could return a promise. That looks like a simple change. I can give a shot at a PR.

**Comment by phryneas** [comment]
Unfortunately, that could be seen as a breaking change. 
Right now, `pending` is dispatched synchronously. 

That guarantee would get lost. It *might* be possible to work around it somehow so it gets only async if the condition returns a promise, but I fear that would turn `cAT` in an even more unreadable monstrosity. 


If you can get to it without too many changes and while exactly keeping the current behaviour, it might be worth a shot, but that might really get tricky.

**Comment by markerikson** [comment]
Available in the 1.7 betas.
