### ISSUE TITLE
TypeError: getDefaultMiddleware is not a function

### ISSUE THREAD

**Issue by LuckyChou710** [reduxjs/redux-toolkit#1499]
@reduxjs/toolkit version 1.6.1

I followed the official website and wrote the following code and then i got an error

TypeError: getDefaultMiddleware is not a function

```ts
import { configureStore } from '@reduxjs/toolkit';
import counterReducer from './modules/counterSlice';
import logger from 'redux-logger';

export const store = configureStore({
  reducer: {
    counter: counterReducer,
    middleware: (getDefaultMiddleware: any) => getDefaultMiddleware().concat(logger),
  },
});

// Infer the `RootState` and `AppDispatch` types from the store itself
export type RootState = ReturnType<typeof store.getState>;
// Inferred type: {posts: PostsState, comments: CommentsState, users: UsersState}
export type AppDispatch = typeof store.dispatch;
```

<img width="1074" alt="截屏2021-09-11 上午11 10 11" src="https://user-images.githubusercontent.com/56244178/132934311-7bd03649-821f-487e-8716-fc95cdfd5e68.png">

**Comment by markerikson** [comment]
You've put the `middleware` option inside of `reducer.  It doesn't belong there - it needs to be at the top-level of the `configureStore` object.
