### ISSUE TITLE
about error handling question

### ISSUE THREAD

**Issue by kuangshp128** [reduxjs/redux-toolkit#1502]
I hope to request all the errors of the back-end interface to be presented uniformly in the error processing, but I use the case on the official website. I deliberately threw an error of 403 on the back-end interface, but the middleware of rtkQueryErrorLogger did not receive the error message, I wonder if the official website can provide a more specific demo

**Comment by phryneas** [comment]
Did you register the middleware in `configureStore`? That should pretty much work.

**Comment by shuihen001** [comment]
> Did you register the middleware in `configureStore`? That should pretty much work.

Yes, this can be implemented, the actual development of httpStatus does not meet the business needs, we will customize the return httpStatus = 200, but will be in the response body custom code= XXX, I hope is in the middleware can also obtain the content of the request response body, to determine, to intercept

**Comment by phryneas** [comment]
If you want to intercept, that definitely cannot be done in middleware. You'll have to wrap your baseQuery.
See https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery

**Comment by kuangshp128** [comment]
> If you want to intercept, that definitely cannot be done in middleware. You'll have to wrap your baseQuery.
> See https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery

Thank you, my problem is solved, I use this interceptor in BaseAPI, the middleware I used before is invalid, I don't know if it is designed that way, the interceptor will handle it and no middleware is needed, or what

**Comment by tumdav** [comment]
Hi there, my question ia related to the topic. How can I use rtkErrorHandlee middware if I am using ApiProvider and don't have a store configured myself?

**Comment by phryneas** [comment]
If you are using the api provider, you can't add any middleware. You can use the baseQuery wrapper style described by me, but for middleware you will have to expand out to a full store.
