### ISSUE TITLE
Docs: createSlice "an object full of reducer functions" wording

### ISSUE THREAD

**Issue by Firfi** [reduxjs/redux-toolkit#1506]
https://redux-toolkit.js.org/api/createslice

https://github.com/reduxjs/redux-toolkit/blob/cb3e158bb21dfbdc8426ec45a115bcb37b0cd55f/docs/api/createSlice.mdx

The doc reads `an object full of reducer functions` which

- is far from the correct definition - this task *doesn't* approach this issue, leaving this "far-ness" as is
- is redundant - `an object of reducer functions` should do just as fine
- seems to be misleading —  reading the docs, I had to stop and think about what is really an object "full" of functions and can it be half-full of functions just as a glass.

The proposal is to change it to `an object of reducer functions` — is just as far from the correct definition (`an object with the key names corresponding to action names and values corresponding to reducer functions`?) but still concise and cut to the chase. 

It removes redundancy and potential misreads from the doc.

**Comment by markerikson** [comment]
Sorry, I'm not sure what the concern is here - can you clarify?

**Comment by Firfi** [comment]
> Sorry, I'm not sure what the concern is here - can you clarify?

The concern is documentation clarity. If you can make your docs better, I can't see a reason why not do it. As to why it's a change for the better, *in my opinion* of course, please refer to the issue description.

**Comment by markerikson** [comment]
It's one word, so I'll merge it, but I'm honestly not sure it's any actual improvement or adds "clarity".
