### ISSUE TITLE
RTK Query - Unwrap lazy query

### ISSUE THREAD

**Issue by sebastienlabine** [reduxjs/redux-toolkit#1508]
Could we give the possibility to unwrap lazy query in the same way we can unwrap mutations?

**Comment by phryneas** [comment]
That requires some prerequisites that are part of #1277, but then we can finally do that, yes.

**Comment by harveyappleton** [comment]
Hey @phryneas - now that #1277 is merged, would this be an easy addition? It would be great to be able to unwrap lazy queries :)

**Comment by ronnaf** [comment]
Hey @phryneas @markerikson now that #1701 is merged, is it included in 1.7.0-beta?

**Comment by markerikson** [comment]
No. The last beta release was about 3 weeks ago, and this was just merged in last week. We haven't done another beta release since then.  It _is_ in the 1.7 integration branch and should be available in the CodeSandbox CI build that is automatically generated each time that integration branch is updated.

**Comment by markerikson** [comment]
Closing as the fix is merged - will be publicly available in the next 1.7 release (`beta.2` or final, whichever we end up doing)

**Comment by ZahirAbbasBKK** [comment]
Hey
I am facing an issue ,after send sms Successfull message is not showing wht i am doing mistake any one
  function isValidPayload(payload) {
    const requiredProperties = [
      'partner_id',
      'login_id',
      'msisdn',
      'message',
      'end_date',
      'schedule_date',
      'status',
    ]

    return requiredProperties.every((prop) => {
      return (
        payload.hasOwnProperty(prop) &&
        payload[prop] !== null &&
        payload[prop] !== undefined &&
        payload[prop] !== ''
      )
    })
  }
  const addSms = async () => {
    const payload = {
      partner_id: partnerId,
      login_id: loginId,
      msisdn: numbers,
      message: note,
      end_date: endDate,
      schedule_date: scheduledDate,
      status: 'outgoing',
      category: category,
    }
    const payloadSendSms = {
      msisdn: numbers[0].slice(2),
      text: note,
    }
    if (isValidPayload(payload)) {
      // Object has all required properties, none are null, and none are empty

      setNote('')
      setScheduledDate(currenDate)
      setEndDate(currenDate)
      try {
        await sendSmsToMsisdn({
          body: payloadSendSms,
        }).unwrap()
        const res = await postSms({ body: payload }).unwrap()
        dispatch(
          setAlertData({
            variant: 'success',
            title: 'Success',
            message: 'Message Sent Successfully!',
          }),
        )

        if (res) {
          dispatch(
            setAlertData({
              variant: 'success',
              title: 'Success',
              message: 'Message Sent Successfully!',
            }),
          )
        }
      } catch (error) {
        setAlertData({
          variant: 'error',
          title: 'Error',
          message: 'Something Went Wrong!',
        })
      }
    } else {
      dispatch(
        setAlertData({
          variant: 'error',
          title: 'Error',
          message: 'Something Went Wrong!',
        }),
      )
    }
  }
