### ISSUE TITLE
RTK Query: dispatch inside query or mutations

### ISSUE THREAD

**Issue by magistrfox** [reduxjs/redux-toolkit#1509]
I've tried to work with RTK Query and for now (IMHO) I think there is a decent cons  of using it especially when you work with Redux (exactly what this lib is for). 

**In a short details:**

I want to dispatch Redux actions after I get a response from query or mutation. But it's not possible. RTKQ doesn't provide any field to deal with dispatch. At all.

**For example**:

I need to query some API and then depends on a response I want to call some redux actions.
Yes, I saw in doc's example that we can just do it in a component but imagine if I would have to do this in NNN separate components? Again and again I should write the same logic? _"Hey you can do this in your custom hook"_ - you would say to me, but, hey, could not we do this just in a one file with the queries? That would be incredibly great if you make some feature to deal with response not in the way `transformReponse` does.
Especially when we use this with Redux (because loading&errors handling are great) obviously it would be great to provide some API to work with Redux actions.

**Comment by markerikson** [comment]
Can you give some specific examples of what you're trying to do, and how you would currently do that work _without_ RTKQ?

**Comment by msutkowski** [comment]
> I've tried to work with RTK Query and for now (IMHO) I think there is a decent cons of using it especially when you work with Redux (exactly what this lib is for).
> 
> **In a short details:**
> 
> I want to dispatch Redux actions after I get a response from query or mutation. But it's not possible. RTKQ doesn't provide any field to deal with dispatch. At all.
> 
> **For example**:
> 
> I need to query some API and then depends on a response I want to call some redux actions.
> Yes, I saw in doc's example that we can just do it in a component but imagine if I would have to do this in NNN separate components? Again and again I should write the same logic? _"Hey you can do this in your custom hook"_ - you would say to me, but, hey, could not we do this just in a one file with the queries? That would be incredibly great if you make some feature to deal with response not in the way `transformReponse` does.
> Especially when we use this with Redux (because loading&errors handling are great) obviously it would be great to provide some API to work with Redux actions.

@magistrfox  It exists in two places already depending on what you want to do, but you most likely want this: https://redux-toolkit.js.org/rtk-query/api/createApi#onquerystarted. There is an example showing `dispatch` usage when a request resolves.

**Comment by magistrfox** [comment]
> > I've tried to work with RTK Query and for now (IMHO) I think there is a decent cons of using it especially when you work with Redux (exactly what this lib is for).
> > **In a short details:**
> > I want to dispatch Redux actions after I get a response from query or mutation. But it's not possible. RTKQ doesn't provide any field to deal with dispatch. At all.
> > **For example**:
> > I need to query some API and then depends on a response I want to call some redux actions.
> > Yes, I saw in doc's example that we can just do it in a component but imagine if I would have to do this in NNN separate components? Again and again I should write the same logic? _"Hey you can do this in your custom hook"_ - you would say to me, but, hey, could not we do this just in a one file with the queries? That would be incredibly great if you make some feature to deal with response not in the way `transformReponse` does.
> > Especially when we use this with Redux (because loading&errors handling are great) obviously it would be great to provide some API to work with Redux actions.
> 
> @magistrfox It exists in two places already depending on what you want to do, but you most likely want this: https://redux-toolkit.js.org/rtk-query/api/createApi#onquerystarted. There is an example showing `dispatch` usage when a request resolves.

Yep, thank you very much! What you've linked is working for me. My eye have caught this moment but that was not pretty clear for me :( especially `queryFulfilled` parameter to take a response is not really self-describing for me without this example in the doc `const { data } = await queryFulfilled`.

**Comment by phryneas** [comment]
Adding to this, you generally should probably not be dispatching additional actions, but have your other slices react to the actions already being dispatched. You can add an extraReducer that just reacts to your endpoint resolving, as showcased in the [authentication using extraReducers example](https://redux-toolkit.js.org/rtk-query/usage/examples#using-extrareducers)

```js
const slice = createSlice({
  name: 'auth',
  initialState: { user: null, token: null } as AuthState,
  reducers: {},
  extraReducers: (builder) => {
    builder.addMatcher(
      api.endpoints.login.matchFulfilled,
      (state, { payload }) => {
        state.token = payload.token
        state.user = payload.user
      }
    )
  },
})
```

**Comment by hxeo** [comment]
> Adding to this, you generally should probably not be dispatching additional actions, but have your other slices react to the actions already being dispatched. You can add an extraReducer that just reacts to your endpoint resolving, as showcased in the [authentication using extraReducers example](https://redux-toolkit.js.org/rtk-query/usage/examples#using-extrareducers)
> 
> ```js
> const slice = createSlice({
>   name: 'auth',
>   initialState: { user: null, token: null } as AuthState,
>   reducers: {},
>   extraReducers: (builder) => {
>     builder.addMatcher(
>       api.endpoints.login.matchFulfilled,
>       (state, { payload }) => {
>         state.token = payload.token
>         state.user = payload.user
>       }
>     )
>   },
> })
> ```

I am not sure why, but for me its always throwing the following error: `TypeError: api is undefined`
I just got a simple api which fetches some collection of resources. That should be then stored in the reducer slice in order to be able to extract bits in other parts of my application, similar to the use case from @EliseyMartynov.

I added my endpoint fulfilled matcher to the extraReducer of the slice I would like to store that data. The types seem to be fine, but the app crashes on start up.

**Comment by markerikson** [comment]
@hxeo that sounds like a classic circular import problem.  Can you double-check the imports and see if that's the case?

You may also want to try https://github.com/reduxjs/redux-toolkit/releases/tag/v1.7.0-rc.0 , which has a fix for circular import issues in `createSlice`.

**Comment by hxeo** [comment]
I had the service in the same file. Thanks for the quick response! @markerikson

**Comment by markerikson** [comment]
@hxeo if they're both in the same file, and you're using `let` or `const` to declare them, then order of declaration matters - the API object does not exist until you get to the `const api = createApi()` line. So, that should go first in the file above the `createSlice()` call.

**Comment by BThomann** [comment]
Is there also a possibility to create an extraReducer that is called when a mutation is triggered - and not only when the mutation has been performed?

In the example from https://redux-toolkit.js.org/rtk-query/usage/examples#using-extrareducers a extraReducer in ``autSlice.ts`` that is called when the login mutation in ``services/auth.js`` is intially called with ``credentials`` of Type ``LoginRequest`` as its ``action.payload``. 
Thank you in advance!

**Comment by msutkowski** [comment]
> Is there also a possibility to create an extraReducer that is called when a mutation is triggered - and not only when the mutation has been performed?
> 
> In the example from https://redux-toolkit.js.org/rtk-query/usage/examples#using-extrareducers a extraReducer in ``autSlice.ts`` that is called when the login mutation in ``services/auth.js`` is intially called with ``credentials`` of Type ``LoginRequest`` as its ``action.payload``. 
> Thank you in advance!

https://redux-toolkit.js.org/rtk-query/api/created-api/endpoints#matchers

You can reference the matchers on an endpoint, so for your case, `api.endpoints.someMutation.matchPending`

**Comment by BThomann** [comment]
Thank you for your fast response. I tried your suggestion in the mentioned demo (https://redux-toolkit.js.org/rtk-query/usage/examples#using-extrareducers) by adding the following matcher in `authSlice.ts`:

```javascript
.addMatcher(api.endpoints.login.matchPending,
  (state, action) => {
    console.log(action) // {type: "api/executeMutation/pending", payload: undefined, meta: Object}
    console.log(action.payload) // undefined
  }
)
```

But sadly the `action.payload` here is `undefined` and not the `credentials` of type `LoginRequest` which would be prefered.

**Comment by markerikson** [comment]
`pending` actions always have an undefined payload.  Did you want `fulfilled` instead?

**Comment by markerikson** [comment]
@BThomann yeah, like I said, the `pendingAction.payload` field is always undefined. However, I think you should find the `credentials` value that's being passed in as `pendingAction.meta.originalArg` or something along those lines - check the contents of the `.meta` field and see what's in there.

**Comment by BThomann** [comment]
`pendingAction.meta.originalArg` was exactly what i was looking for! Thank you very much! Have a nice evening (or day )!

**Comment by CodyMoore240** [comment]
> @hxeo that sounds like a classic circular import problem. Can you double-check the imports and see if that's the case?
> 
> You may also want to try https://github.com/reduxjs/redux-toolkit/releases/tag/v1.7.0-rc.0 , which has a fix for circular import issues in `createSlice`.

Can confirm that the latest release fixed the issue for me.

**Comment by nurbekzhussip** [comment]
I get this error: ReferenceError: Cannot access 'baseQuery' before initialization

the baseQuery is in another file. It looks something like this https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery

**Comment by abb438** [comment]
"Does the query return a match for api.endPoints.login.matchFulfilled when it returns a cache? If I want to perform a dispatch in the same way when returning a cache, what should I do? I apologize for my poor English."

**Comment by hamzeloudev** [comment]
A utility package for integrating file upload/download with progress tracking into your Redux Toolkit Query API slices:

[rtk-upload-utils](https://www.npmjs.com/package/rtk-upload-utils)
