### ISSUE TITLE
Race condition with polling leads to optimistic update patch being ignored

### ISSUE THREAD

**Issue by mungojam** [reduxjs/redux-toolkit#1512]
I have a control, populated by RTK that users can then edit using a standard mutation with optimistic updates. I believe I am using RTK with querying in a very standard way as I have taken the code from the docs.

90% of the time it works well and the value they put in shows immediately, however 10% of the time, when it clashes with a poll, the value they put in is reset to the value from the API until the next poll when their update is then reflected.

It feels like a race condition between the optimistic update through `updateQueryData` and the regular polling.

Here is a redux capture of when it happens. I've noted that it always happens when there is a pending poll request (i.e. `api/executeQuery/pending` was the last event before the start of the mutation).

![image](https://user-images.githubusercontent.com/3154635/133433195-3d46f08b-d2b5-4cc4-af1a-334dad47a837.png)

It is as if the patch just gets ignored if an API poll was fired but not yet completed before the mutation starts.

I thought I could workaround this by setting `skip=true` before submitting the mutation and resetting it afterwards, but presumably the pending query would still complete and mess things up.

**Comment by markerikson** [comment]
Can you put together a CodeSandbox that reproduces the issue, or at least shows the code setup you're using?

**Comment by mungojam** [comment]
> Can you put together a CodeSandbox that reproduces the issue, or at least shows the code setup you're using?

Sure, I'll have a go. Unfortunately I've just been pulled off the tool I was working on to work on another project so it may be a few days until I get back to it.

I suppose I could try and mock the API calls by substituting the `queryFn` or something. That might help in reproducing it.

**Comment by phryneas** [comment]
Well, the behaviour is generally to be expected. These updates are just updating the current cache entry and every incoming response will overwrite them again, assuming that "server state" always beats "client state". 
Right now, the only way I could think of really well handling this would be to add multiple "cache layers" as apollo-client does, but to be honest, I really don't want to go that far, since the level of added complexity there is just absurd.

As it stands, optimistic updates are just "best effort". I also don't know if delaying requests to the server etc. here are a good idea. But I'm open for more ideas.

**Comment by mungojam** [comment]
Yeah, I guess I had assumed some sort of multi-layer cache was going on where the patches were a layer on top of the underlying query result, but I guess they just replace the current value in the cache.

I'm open to other solutions too, at least the pause in my current work means I can ponder what would work a bit more.

**Comment by mungojam** [comment]
> These updates are just updating the current cache entry and every incoming response will overwrite them again, assuming that "server state" always beats "client state".

Actually that makes total sense now, `updateQueryData` isn't adding a layer, it's just updating the currently cached value.

One thought I have as a workaround is that I could maintain a set of `patches` in redux which then get removed once the mutation completes. I would then apply these patches as part of the query transform. It's actually similar to what I had before I converted fully to RTK so I think I just need to resurrect it.

I can't yet think of a nice and simple addition you could make to RTK that would help.

**Comment by phryneas** [comment]
> One thought I have as a workaround is that I could maintain a set of `patches` in redux which then get removed once the mutation completes. I would then apply these patches as part of the query transform. It's actually similar to what I had before I converted fully to RTK so I think I just need to resurrect it.

You even get those patches for free: `updateQueryData` calculates a patch and sends it to the store as an action. You could record these actions and replay them after data was received until the patches are no longer active. Not really the *most* elegant thing, but should work :)

**Comment by mungojam** [comment]
One thing that would make this feel a little more natural and in line with other parts of RTK woud be if the `transformResponse` function was called with an immer draft and behaved like reducers in RTK. That way I could replay the patches in there quite easily.

That's also a potential way you could implement this, by having some `util.addPatches` and `util.undoPatches` methods that would just wrap `transformResponse`. That's what I am currently working on doing in our own code.
