### ISSUE TITLE
[Suggestion] Add api for creating simple (not async) thunk in RTK

### ISSUE THREAD

**Issue by mark-night** [reduxjs/redux-toolkit#1515]
Love the way how RTK makes things so much simpler and organized! Great job! BIIIIIIG THANKS!

While AsyncThunk is great, there are cases one might want to create simple thunks just to manage dispatches in a queue or to read a piece of information from the store before dispatching. Traditionally, this is as simple as creating a "regular" thunk, where the thunkAPI provides handy getState/dispatch tools to do just those. A thunk doe not have to be async.

I tried my best but I could not find any information regarding how to create regular (not async) thunks with RTK API. I hope it's just me missed something. 

AsyncThunk can of course do the same job, with only two concerns, remembering it's an `async` to be `await` and bear with bear with all those unnecessary sub actions (`fulfilled`, `pending`...).

Another possible way I could think of is just to create thunk as usual (leaving it outside RTK slice creator), and dispatch it as usual. This should be fine given redux-thunk is loaded by default. I didn't test but I think it can be hard somewhere if in typescript. (Just guessing, new to TS, struggling with getting correct typing all the time...)

I'd love to see if RTK indeed has a recommended way to do this. Thanks.

**Comment by phryneas** [comment]
Creating a normal thunk (which still works) is pretty much as simple as writing
```ts
const thunk = () => (dispatch: AppDispatch, getState: () => RootState) => { /* your code */ }
```
or
```ts
const thunk = (): AppThunk<ReturnValue> => (dispatch, getState) => { /* your code */ }
```

Essentially all we could do to simplify that would be to add a wrapper to add the types - but we would still need you to pass them in somehow. So it would come down to

```ts
const thunk = createThunk<Arg, AppDispatch, RootState, ReturnValue>(() => (dispatch, getState) => { /* your code */ })
```

which would be more code in the end.


There was the idea to have something like

```ts
const createThunk = store.bindThunkTypes()
const thunk = createThunk(() => (dispatch, getState) => { ... })
```
which would essentially be able to infer the types for `Arg` and `ReturnValue` from the method you pass in while correctly typing `dispatch` and `getState`, but in the end that never made it in.

It seems it's not really worth it for us to provide a tool for it - writing it by hand is just almost always simpler.

**Comment by markerikson** [comment]
Yeah, the point of `createAsyncThunk` is that there's a standard pattern for "create action types, make request, dispatch actions".  A "simple" thunk doesn't have any such pattern, and there really isn't anything to abstract here.

We do document how to type thunks in the TS Usage guide:

https://redux.js.org/usage/usage-with-typescript#type-checking-redux-thunks

**Comment by mark-night** [comment]
@phryneas Thanks for the hints!

I ended up with this solution, it's not as hard (in TS) as I thought. 
> Creating a normal thunk (which still works) is pretty much as simple as writing
>```
>const thunk = () => (dispatch: AppDispatch, getState: () => RootState) => { /* your code */ }
>```

Now I got confirmed and see the reason why/how an option for creating simple thunks with RTK api was left behind on purpose. I agree it requires less codes to be written.
 
On the other hand, as a user, I still feel kinda missing something, I meant, RTK loads redux-thunk by default, but only covers part of it in API, kinda like giving you `dispatch` but leaving `getState` behind.  If I were new to redux-thunk, I'd have totally missed the "simple thunk" possibility...

By the way, I think "more written codes" is more TS's thing, it doesn't harm a library's philosophy as long as it helps making it complete. Indeed, every time I need to write an async thunk, I do have to write more codes for typing requirements, but isn't that TS's nature? 

One reason I love RTK is it hides all other required tools, e.g. immer, redux-thunk, redux-dev-tools..., making itself an ONE-STOP library, this is HUGE for new users. I'd really love to see potentials like renaming `AsyncThunk` to `AsyncAction`, and combine simple thunk with action in some way, so there are only `simple action` and `async action`, which would be much more clearer. (Yes thunk is not action in concept, but from user perspective, it really only matters what to be dispatched and what should happen because of that dispatch.)

Anyway, thanks for clearing the thoughts. And again, great library, love it!

**Comment by mark-night** [comment]
> Yeah, the point of `createAsyncThunk` is that there's a standard pattern for "create action types, make request, dispatch actions". A "simple" thunk doesn't have any such pattern, and there really isn't anything to abstract here.
> 
> We do document how to type thunks in the TS Usage guide:
> 
> https://redux.js.org/usage/usage-with-typescript#type-checking-redux-thunks

Thanks for the link, I've read that before I looked into RTK. It's not about typing thunks, it's about how to do simple thunk with RTK api. Looks like it's only my personal struggle though.

Thank you.

**Comment by markerikson** [comment]
Yeah, ultimately I don't think there's anything specific we can add here.
