### ISSUE TITLE
RTKQ: Option to prefer cache in useLazyQuery

### ISSUE THREAD

**Issue by lukaszromerowicz** [reduxjs/redux-toolkit#1516]
Hello! Thanks for this amazing library 🙌🏻 

I have a question about `useLazyQuery`. Currently in my app I'm seeing that on every `trigger` call a new network request is spawned and the cache is not used. Is there any option to prefer cache with lazy queries? Or is this a problem with how I am using this hook?

**Comment by phryneas** [comment]
It actually can do that, but we forgot about adding it to the types :sweat: See #1278 #1280.

**Comment by lukaszromerowicz** [comment]
Alright, that's cool, thanks for a quick response! I think once the types are added this issue can be closed.

**Comment by phryneas** [comment]
I'll already close this here since it's essentially a duplicate of #1279 and that one is still open.
