### ISSUE TITLE
RTK Query - Optimistic Updates after API Response?

### ISSUE THREAD

**Issue by sebastienlabine** [reduxjs/redux-toolkit#1517]
Is it possible to manually update the cache after a mutation with the API response without triggering a refetch?

Let's say we create new entity and we want to use the response to add it to the list kept in cache by RKT Toolkit. Can this be done?

[Vercel SWR Implementation](https://swr.vercel.app/docs/mutation#mutation-and-post-request)

**Comment by msutkowski** [comment]
> Is it possible to manually update the cache after a mutation with the API response without triggering a refetch?
> 
> Let's say we create new entity and we want to use the response to add it to the list kept in cache by RKT Toolkit. Can this be done?
> 
> [Vercel SWR Implementation](https://swr.vercel.app/docs/mutation#mutation-and-post-request)

If I understand you correctly, you're looking for: https://redux-toolkit.js.org/rtk-query/usage/optimistic-updates#example

**Comment by sebastienlabine** [comment]
how can we access the api response?

**Comment by phryneas** [comment]
As the return value of awaiting `queryFulfilled` there

**Comment by sebastienlabine** [comment]
Could we have an option to disable the server refresh when doing an optimistic update? In my use case, the user can swipe up to refresh the list, so we use isFetching to show a loading indicator,  and when the users add something to the list, it triggers a refetch (showing that it's fetching to the server) even if I manually set the state. I would like to tell RKTQ that the data is supposed to be up to date after the update

**Comment by Shrugsy** [comment]
@sebastienlabine as long as you're not invalidating tags, your mutation won't cause anything to re-fetch by itself. If you're performing an optimistic/pessimistic update to cache data, you most likely don't want to invalidate tags that affect the corresponding query cache as well.

**Comment by sebastienlabine** [comment]
That was the problem! thanks. Also I also think it could be usefull to have some documentation on how to mutate the data. For example, to remove an item from a list, we can't use data = data.filter(), we need to use data.splice(index, 1), which is a little special compared to the usual redux mutation pattern

**Comment by Shrugsy** [comment]
> For example, to remove an item from a list, we can't use data = data.filter(), we need to use data.splice(index, 1), which is a little special compared to the usual redux mutation pattern

It actually follows the same mutation pattern as all reducers created with redux toolkit, being that it uses immers `produce` method.

When you do `data = data.filter()...`, you're falling into the pitfall described here: https://redux-toolkit.js.org/usage/immer-reducers#resetting-and-replacing-state

i.e. you're just re-assigning a local variable, which neither RTK or immer care about or will notice. You need to *either* mutate the draft object, *or* return a new state. So you *can* do `return data.filter()` if you want to, the same as you can do within a `createSlice` reducer

**Comment by sebastienlabine** [comment]
Thanks you!
