### ISSUE TITLE
how to use rtk-query download file

### ISSUE THREAD

**Issue by kuangshp** [reduxjs/redux-toolkit#1522]
If the backend interface returns data responseType: 'blob ', how can I download the file using RtK-query

**Comment by phryneas** [comment]
You should probably not do that, since using RTK Query would place that file in the cache - which means in the user's memory. Which, depending on the file size could even crash the user's browser. 

For file downloads, do that just like "before" RTK-Query or any similar library. There should be hundreds of blog posts on the topic out there :)

**Comment by kuangshp** [comment]
> You should probably not do that, since using RTK Query would place that file in the cache - which means in the user's memory. Which, depending on the file size could even crash the user's browser.
> 
> For file downloads, do that just like "before" RTK-Query or any similar library. There should be hundreds of blog posts on the topic out there :)

I want to use RTK-Query to download the file. So far I'm using AXIos to download the file and it's ok. Now that I'm using RTK-Query, I want to remove axios from the project and use RTK-Query to download the file. But I can't get the return value, and the interface doesn't run interceptors

```typescript
const baseQuery = fetchBaseQuery({
  baseUrl,
  prepareHeaders: (headers) => {
    const token: string = storage.getItem(authToken);
    if (token) {
      headers.set(authToken, token);
    }
    return headers;
  },
});

export const fetchWithIntercept: BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError> =
  async (args, api, extraOptions) => {
    const result: QueryReturnValue<unknown, FetchBaseQueryError, FetchBaseQueryMeta> =
      await baseQuery(args, api, extraOptions);
    return result;
    }
  };

export const baseApi = createApi({
  baseQuery: fetchWithIntercept,
  reducerPath: 'baseApi',
  endpoints: () => ({}),
});
```

```typescript
const tagihanApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    downFileApi: builder.mutation<Blob, Partial<Omit<ITagihanFormDto, 'pageSize' | 'pageNum'>>>({
      query: (data: Partial<Omit<ITagihanFormDto, 'pageSize' | 'pageNum'>>) => ({
        url: '/admin/api/v3/hso/loans/download',
        method: 'post',
        body: data,
        // responseType: 'blob',
      }),
    }),
  }),
  overrideExisting: false,
});
export const {
  useDownFileApiMutation,
} = tagihanApi;
export default tagihanApi;
```

**Comment by phryneas** [comment]
The purpose of RTK Query is not to "download something", but to "put it in memory so you can use it later".

You can happily use your `baseQuery` directly to start a download, but **please don't use RTK-Query for a download**. You run the risk of crashing the browser!

**Comment by AntoLC** [comment]
If you still want to do it:
> 
 ```ts
 const api = mainApi.injectEndpoints({
   endpoints: (builder) => ({
     reportExcel: builder.mutation<any, IReportExcelQuery>({
       query(args) {
         return {
           url: `/admin/api/v3/hso/loans/download`,
           method: "POST",
           body: args.dataset,
           responseHandler: async (response) => window.location.assign(window.URL.createObjectURL(await response.blob())),
           cache: "no-cache",
         };
       },
     }),
   }),
   overrideExisting: false,
 });
```

**Comment by RipaltaOriol** [comment]
This is the solution I use. The API I'm reaching returns a PDF file so the goal was to create an automatic download for the user.

```
import { apiSlice } from '../../api/apiSlice';
import { fetchBaseQuery } from '@reduxjs/toolkit/query'

export const pdfsSlice = apiSlice.injectEndpoints({
    baseQuery: fetchBaseQuery({ baseUrl: '/ ' }),
    endpoints: builder => ({
        downloadPDFFile: builder.mutation({
            queryFn: async ({ setupId, name }, api, extraOptions, baseQuery) => {
                const result = await baseQuery({
                    url: `/setups/${setupId}/file`,
                    responseHandler: ((response) => response.blob())
                })
                var hiddenElement = document.createElement('a');
                var url = window.URL || window.webkitURL;
                var blobPDF = url.createObjectURL(result.data);
                hiddenElement.href = blobPDF;
                hiddenElement.target = '_blank';
                hiddenElement.download = `${name}_report.pdf`;
                hiddenElement.click();
                return { data: null }
            }
        })
    })
})

export const {
    useDownloadPDFFileMutation
} = pdfsSlice;
```

**Comment by Pluto8195** [comment]
> The purpose of RTK Query is not to "download something", but to "put it in memory so you can use it later".
> 
> You can happily use your `baseQuery` as an alernative to `axios` directly to start a download, but **please don't use RTK-Query for a download**. You run the risk of crashing the browser!

How would we use the `fetchBaseQuery` as a means to fetch, it seems like it needs `BaseQueryApi` and such which comes from RTK?

**Comment by githero20** [comment]
> This is the solution I use. The API I'm reaching returns a PDF file so the goal was to create an automatic download for the user.
> 
> ```
> import { apiSlice } from '../../api/apiSlice';
> import { fetchBaseQuery } from '@reduxjs/toolkit/query'
> 
> export const pdfsSlice = apiSlice.injectEndpoints({
>     baseQuery: fetchBaseQuery({ baseUrl: '/ ' }),
>     endpoints: builder => ({
>         downloadPDFFile: builder.mutation({
>             queryFn: async ({ setupId, name }, api, extraOptions, baseQuery) => {
>                 const result = await baseQuery({
>                     url: `/setups/${setupId}/file`,
>                     responseHandler: ((response) => response.blob())
>                 })
>                 var hiddenElement = document.createElement('a');
>                 var url = window.URL || window.webkitURL;
>                 var blobPDF = url.createObjectURL(result.data);
>                 hiddenElement.href = blobPDF;
>                 hiddenElement.target = '_blank';
>                 hiddenElement.download = `${name}_report.pdf`;
>                 hiddenElement.click();
>                 return { data: null }
>             }
>         })
>     })
> })
> 
> export const {
>     useDownloadPDFFileMutation
> } = pdfsSlice;
> ```

This was a great help, thank you.
A small addition would be a cleanup function like this, to unload the document:

`
       setTimeout(() => {
          document.body.removeChild(hiddenElement);
          url.revokeObjectURL(result.data);
        }, 2000);
`

**Comment by forrestwilkins** [comment]
@phryneas Would you recommend just using `axios` instead to download the file?

**Comment by DevShahidul** [comment]
> > This is the solution I use. The API I'm reaching returns a PDF file so the goal was to create an automatic download for the user.
> > ```
> > import { apiSlice } from '../../api/apiSlice';
> > import { fetchBaseQuery } from '@reduxjs/toolkit/query'
> > 
> > export const pdfsSlice = apiSlice.injectEndpoints({
> >     baseQuery: fetchBaseQuery({ baseUrl: '/ ' }),
> >     endpoints: builder => ({
> >         downloadPDFFile: builder.mutation({
> >             queryFn: async ({ setupId, name }, api, extraOptions, baseQuery) => {
> >                 const result = await baseQuery({
> >                     url: `/setups/${setupId}/file`,
> >                     responseHandler: ((response) => response.blob())
> >                 })
> >                 var hiddenElement = document.createElement('a');
> >                 var url = window.URL || window.webkitURL;
> >                 var blobPDF = url.createObjectURL(result.data);
> >                 hiddenElement.href = blobPDF;
> >                 hiddenElement.target = '_blank';
> >                 hiddenElement.download = `${name}_report.pdf`;
> >                 hiddenElement.click();
> >                 return { data: null }
> >             }
> >         })
> >     })
> > })
> > 
> > export const {
> >     useDownloadPDFFileMutation
> > } = pdfsSlice;
> > ```
> 
> This was a great help, thank you. A small addition would be a cleanup function like this, to unload the document:
> 
> `setTimeout(() => { document.body.removeChild(hiddenElement); url.revokeObjectURL(blobPDF); }, 2000);`

How can I use this with the GET method instead of POST?

**Comment by phryneas** [comment]
> How can I use this with the GET method instead of POST?

You really really really stop using RTKQ for this and just make a download button :/

But that said, the code you are quoting is using `GET`, not `POST`.

**Comment by hamzeloudev** [comment]
A utility package for integrating file upload/download with progress tracking into your Redux Toolkit Query API slices:

[rtk-upload-utils](https://www.npmjs.com/package/rtk-upload-utils)
