### ISSUE TITLE
onQueryStarted function did not perform

### ISSUE THREAD

**Issue by kuangshp128** [reduxjs/redux-toolkit#1523]
When I used RTK-Query to query data, I wanted to store the data in the onQueryStarted method into a slice, but I didn't print the information in the hook method，[official address](https://redux-toolkit.js.org/rtk-query/api/createApi#onquerystarted)

```typescript
const postsApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    // query post list
    getPostsList: builder.query<Promise<IPostVo[]>, void>({
      query: () => '/posts',
      async onQueryStarted(id, { dispatch, queryFulfilled }) {
        console.log(id, 'current id');
        // `onStart` side-effect
        // dispatch(messageCreated('Fetching post...'));
        try {
          const { data } = await queryFulfilled;
          console.log(data, '=======');
          dispatch(postsSlice.actions.setPosts(data));
          // `onSuccess` side-effect
          // dispatch(messageCreated('Post received!'));
        } catch (err) {
          // `onError` side-effect
          // dispatch(messageCreated('Error fetching post!'));
        }
      },
      transformResponse: (response: { result: Promise<IPostVo[]> }) => {
        return response.result;
      },
    }),
  overrideExisting: false,
});

export const {
  useLazyGetPostsListQuery,
} = postsApi;
```

**Comment by phryneas** [comment]
Hmm, I don't know what is going on there, that should be working. Did you maybe forget to add the middleware of your `baseApi`?

Generally, you don't need `onQueryStarted` for this, you can also just add an `extraReducer` with `builder.addMatcher(api.endpoints.getPostsList.matchFulfilled, (state, action) => {})` to your slice and it will directly use the RTKQ-internal action without firing another one (which might save you some computing power).

**Comment by kuangshp128** [comment]
`baseApi` Is a foundation that I created using code splitting and interceptors [interceptor](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery) and [code split](https://redux-toolkit.js.org/rtk-query/usage/code-splitting)

```typescript
const baseQuery = fetchBaseQuery({
  baseUrl: 'http://localhost:5000/',
  prepareHeaders: (headers, { getState }) => {
    // const token = (getState() as RootState).auth.token;
    headers.set('token', '97aca8cabd58406db9afc7a094a57584');
    return headers;
  },
});
const baseQueryWithIntercept: BaseQueryFn<
  string | FetchArgs,
  unknown,
  FetchBaseQueryError
> = async (args, api, extraOptions) => {
  const result: QueryReturnValue<any, FetchBaseQueryError, FetchBaseQueryMeta> =
    await baseQuery(args, api, extraOptions);
  console.log(result, 'interceptor');
  return result;
};

export const baseApi = createApi({
  baseQuery: baseQueryWithIntercept, //fetchBaseQuery({ baseUrl: 'http://localhost:5000' }),
  reducerPath: 'baseApi',
  keepUnusedDataFor: 2 * 60,
  endpoints: () => ({}),
});
```

**Comment by kuangshp128** [comment]
> Hmm, I don't know what is going on there, that should be working. Did you maybe forget to add the middleware of your `baseApi`?
> 
> Generally, you don't need `onQueryStarted` for this, you can also just add an `extraReducer` with `builder.addMatcher(api.endpoints.getPostsList.matchFulfilled, (state, action) => {})` to your slice and it will directly use the RTKQ-internal action without firing another one (which might save you some computing power).

At first, when I didn't use RTK-Query, I used extraReducer to make Ajax requests using Axios in slices. But finally, when THERE were RTK-Query requests, I switched to rTK-Query for all ajax requests in the project. I see that there is a lifecycle hook function in the document, and I want to directly distribute data to the reducers function in the slice to store data in the hook function

**Comment by phryneas** [comment]
Yes, and that baseApi (and only that one) has to be added to your Middleware in your configureStore call. 

Am 18. September 2021 10:12:06 MESZ schrieb "水痕" ***@***.***>:
>`baseApi` Is a foundation that I created using code splitting and
>interceptors
>[interceptor](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery)
>and [code
>split](https://redux-toolkit.js.org/rtk-query/usage/code-splitting)
>
>```typescript
>const baseQuery = fetchBaseQuery({
>  baseUrl: 'http://localhost:5000/',
>  prepareHeaders: (headers, { getState }) => {
>    // const token = (getState() as RootState).auth.token;
>    headers.set('token', '97aca8cabd58406db9afc7a094a57584');
>    return headers;
>  },
>});
>const baseQueryWithIntercept: BaseQueryFn<
>  string | FetchArgs,
>  unknown,
>  FetchBaseQueryError
>> = async (args, api, extraOptions) => {
>const result: QueryReturnValue<any, FetchBaseQueryError,
>FetchBaseQueryMeta> =
>    await baseQuery(args, api, extraOptions);
>  console.log(result, 'interceptor');
>  return result;
>};
>
>export const baseApi = createApi({
>baseQuery: baseQueryWithIntercept, //fetchBaseQuery({ baseUrl:
>'http://localhost:5000' }),
>  reducerPath: 'baseApi',
>  keepUnusedDataFor: 2 * 60,
>  endpoints: () => ({}),
>});
>```

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by phryneas** [comment]
Let me preface this by: generally  you should only do either of this in extreme edge cases. Usually you should not copy data from Rtk Query out into other reducers. You should let Rtk Query handle your data for you, that's the whole point. Otherwise you have to handle it yourself again, which might lead to old data not being removed from store etc. 

That aside: if you use the lifecycle, Rtk Query internally dispatches a fulfilled action. That action triggers the lifecycle event. And a react rerender. Then you dispatch another action to get the data into your slice. And trigger another rerender. Of course you can do that, but it adds extra indirection. 
Generally you can just have your reducer directly react to the initial action without another rerender and without all the code for the lifecycle action. That is what I am suggesting with the extraReducer here. Rtk Query will still do its thing, but you access the data earlier and with fewer indirection. 

Am 18. September 2021 10:19:59 MESZ schrieb "水痕" ***@***.***>:
>> Hmm, I don't know what is going on there, that should be working. Did
>you maybe forget to add the middleware of your `baseApi`?
>> 
>> Generally, you don't need `onQueryStarted` for this, you can also
>just add an `extraReducer` with
>`builder.addMatcher(api.endpoints.getPostsList.matchFulfilled, (state,
>action) => {})` to your slice and it will directly use the
>RTKQ-internal action without firing another one (which might save you
>some computing power).
>
>At first, when I didn't use RTK-Query, I used extraReducer to make Ajax
>requests using Axios in slices. But finally, when THERE were RTK-Query
>requests, I switched to rTK-Query for all ajax requests in the project.
>I see that there is a lifecycle hook function in the document, and I
>want to directly distribute data to the reducers function in the slice
>to store data in the hook function

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by kuangshp128** [comment]
> Let me preface this by: generally you should only do either of this in extreme edge cases. Usually you should not copy data from Rtk Query out into other reducers. You should let Rtk Query handle your data for you, that's the whole point. Otherwise you have to handle it yourself again, which might lead to old data not being removed from store etc. That aside: if you use the lifecycle, Rtk Query internally dispatches a fulfilled action. That action triggers the lifecycle event. And a react rerender. Then you dispatch another action to get the data into your slice. And trigger another rerender. Of course you can do that, but it adds extra indirection. Generally you can just have your reducer directly react to the initial action without another rerender and without all the code for the lifecycle action. That is what I am suggesting with the extraReducer here. Rtk Query will still do its thing, but you access the data earlier and with fewer indirection.

Thank you, I tried the lifecycle hook function according to the strict case of the official website, but it still did not execute, I verified that there should be a problem with the hook

**Comment by phryneas** [comment]
As I said the lifecycle hook will only execute if you have set up the Middleware of your baseApi correctly in your configureStore call. Unless you verify that and share what code you are using there nobody will be able to help you any further with anything. 
-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by phryneas** [comment]
As I told you before, the lifecycle hook (and for that matter, most of the functionality of RtkQ) will only work if you have set up the Middleware of your baseApi in your configureStore call correctly. Please verify that and if you think you have done that and it still does not work, please share the code of your configureStore call.

Without that nobody here will be able to help you. 

Am 18. September 2021 11:57:40 MESZ schrieb "水痕" ***@***.***>:
>> Let me preface this by: generally you should only do either of this
>in extreme edge cases. Usually you should not copy data from Rtk Query
>out into other reducers. You should let Rtk Query handle your data for
>you, that's the whole point. Otherwise you have to handle it yourself
>again, which might lead to old data not being removed from store etc.
>That aside: if you use the lifecycle, Rtk Query internally dispatches a
>fulfilled action. That action triggers the lifecycle event. And a react
>rerender. Then you dispatch another action to get the data into your
>slice. And trigger another rerender. Of course you can do that, but it
>adds extra indirection. Generally you can just have your reducer
>directly react to the initial action without another rerender and
>without all the code for the lifecycle action. That is what I am
>suggesting with the extraReducer here. Rtk Query will still do its
>thing, but you access the data earlier and with fewer indirection.
>
>Thank you, I tried the lifecycle hook function according to the strict
>case of the official website, but it still did not execute, I verified
>that there should be a problem with the hook

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by kuangshp128** [comment]
> As I told you before, the lifecycle hook (and for that matter, most of the functionality of RtkQ) will only work if you have set up the Middleware of your baseApi in your configureStore call correctly. Please verify that and if you think you have done that and it still does not work, please share the code of your configureStore call. Without that nobody here will be able to help you. Am 18. September 2021 11:57:40 MESZ schrieb "水痕" ***@***.***>:
> […](#)
> > Let me preface this by: generally you should only do either of this in extreme edge cases. Usually you should not copy data from Rtk Query out into other reducers. You should let Rtk Query handle your data for you, that's the whole point. Otherwise you have to handle it yourself again, which might lead to old data not being removed from store etc. That aside: if you use the lifecycle, Rtk Query internally dispatches a fulfilled action. That action triggers the lifecycle event. And a react rerender. Then you dispatch another action to get the data into your slice. And trigger another rerender. Of course you can do that, but it adds extra indirection. Generally you can just have your reducer directly react to the initial action without another rerender and without all the code for the lifecycle action. That is what I am suggesting with the extraReducer here. Rtk Query will still do its thing, but you access the data earlier and with fewer indirection. Thank you, I tried the lifecycle hook function according to the strict case of the official website, but it still did not execute, I verified that there should be a problem with the hook
> -- Sent from my Android phone with K-9 Mail. Please excuse my brevity.

[My case address](https://codesandbox.io/s/react-reduxjs-toolkit-7bxi6)，I want the onQueryStarted function in the user.service.js file to be triggered when I click the button

**Comment by phryneas** [comment]
As suspected, you do not set up the Middleware. Please do so according to the documentation. https://redux-toolkit.js.org/tutorials/rtk-query#add-the-service-to-your-store
-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by nazmulM360ict** [comment]
> Hmm, I don't know what is going on there, that should be working. Did you maybe forget to add the middleware of your `baseApi`?
> 
> Generally, you don't need `onQueryStarted` for this, you can also just add an `extraReducer` with `builder.addMatcher(api.endpoints.getPostsList.matchFulfilled, (state, action) => {})` to your slice and it will directly use the RTKQ-internal action without firing another one (which might save you some computing power).

Thai just worked for me
