### ISSUE TITLE
feat: Functionality for Derived State Values 

### ISSUE THREAD

**Issue by akashshyamdev** [reduxjs/redux-toolkit#1528]
Does redux toolkit offer a relatively easy way of having derived/computed state values? I think this would be a great feature and we could implement something like recoil has done [here](https://recoiljs.org/docs/basic-tutorial/selectors/). 

Maybe we add a method like `createDerivedState` which is probably a computation of some other state value. For example, a cart. 

A cart would contain an array of items with a `name`, `description`, `quantity`, `price` etc. We then have a property in state called `total` which is the total price of all items

**Comment by phryneas** [comment]
You would usually write a selector and use that with the `useSelector` hook - that is a core concept of Redux data does not change in any way with Toolkit.

https://redux.js.org/usage/deriving-data-selectors

**Comment by akashshyamdev** [comment]
Yes @phryneas, it is a core concept of redux. What do you think about integrating something like reselect? A library like that would handle caching, avoid unecessary recomputations etc

**Comment by phryneas** [comment]
Reselect is re-exported by Redux Toolkit. You still have to write your selectors yourself since we have no idea what data you want to select.

**Comment by markerikson** [comment]
Yep, this is literally the point of `reselect` and `proxy-memoize`. Please read the linked "Selectors" docs page for more details.
