### ISSUE TITLE
RTK Query: Unhandled Rejection (Error): Promise never resolved before cacheEntryRemoved.

### ISSUE THREAD

**Issue by collinscangarella** [reduxjs/redux-toolkit#1538]
I have an application which uses RTK query to define endpoints, including a login endpoint. The frontend sends a basic authorization request to the login endpoint and receives a bearer token and the user id. From there, the endpoint dispatches an update to the store so that this data can be accessed permanently. The view redirects to the home page after the login request is successful.

Here's the endpoint code:
```
login: builder.mutation<LoginResponse, LoginForm>({
  query: (body) => ({
    url: 'auth/login/',
    method: 'POST',
    headers: {
      'Authorization': `Basic ${btoa(`${body.email}:${body.password}`)}`
    },
  }),
  onCacheEntryAdded: async (arg, {cacheDataLoaded, dispatch}) => {
    cacheDataLoaded.then(loginData => {
      dispatch(setAuth(loginData.data));
      dispatch(setLoggedInUser(loginData.data.user_id));
    });
  },
}),
```
And here's the redirect logic in the view:
```
useEffect(() => {
  if (loginData.isSuccess) {
    history.push('/')
  }
}, [history, loginData]);
```
Unfortunately, this is causing an issue where the cache entry is being removed (due to the redirect) before the 'onCacheEntryAdded' code is fully executed. How can I resolve this? 

Collin

**Comment by phryneas** [comment]
By writing this as thenables, you are disconnecting the promise flow from the lifecycle action. Either add a `return` or write it in-line with `await` and that error will be caught and handled correctly.

So either
```js
onCacheEntryAdded: async (arg, {cacheDataLoaded, dispatch}) => {
    return cacheDataLoaded.then(loginData => {
      dispatch(setAuth(loginData.data));
      dispatch(setLoggedInUser(loginData.data.user_id));
    });
  },
```
or
```js
onCacheEntryAdded: async (arg, {cacheDataLoaded, dispatch}) => {
    const loginData = await cacheDataLoaded
    dispatch(setAuth(loginData.data));
    dispatch(setLoggedInUser(loginData.data.user_id));
  },
```
Personally I'd highly prefer the second one due to readability, but technically they should be equal.

**Comment by collinscangarella** [comment]
Thanks!

**Comment by collinscangarella** [comment]
I was a bit too quick to close this issue. I made the onCacheEntryAdded method await the promise as you described:
```
onCacheEntryAdded: async (arg, {cacheDataLoaded, dispatch}) => {
  await cacheDataLoaded.then(loginData => {
    dispatch(setAuth(loginData.data));
    dispatch(setLoggedInAuth(loginData.data));
  });
},
```
This did in fact fix the error - however now the promise is not resolved at all. The redux store is not updated with `setAuth` or `setLoggedInUser`. This is the case if I return the promise or await the promise.

**Comment by markerikson** [comment]
@collinscangarella I'm not sure the snippet you're showing matches either of the examples that Lenz showed. Can you try tweaking to match the provided snippets and see what happens?

**Comment by collinscangarella** [comment]
@markerikson Sure!

In addition to what I described above I also tried
```
onCacheEntryAdded: async (arg, {cacheDataLoaded, dispatch}) => {
    const loginData = await cacheDataLoaded
    dispatch(setAuth(loginData.data));
    dispatch(setLoggedInUser(loginData.data.user_id));
  },
  ```
  and
  ```
onCacheEntryAdded: async (arg, {cacheDataLoaded, dispatch}) => {
  return cacheDataLoaded.then(loginData => {
    dispatch(setAuth(loginData.data));
    dispatch(setLoggedInUser(loginData.data.user_id));
  });
},
```
These both have the same result - the redux store is not updated.

**Comment by markerikson** [comment]
Yeah, I really am not sure what's going on here. Could you put together a CodeSandbox that shows this happening?

**Comment by collinscangarella** [comment]
I'm as confused as you are. I put together a CodeSandbox [here](https://codesandbox.io/s/infallible-ives-3cyt0) and everything works as expected (more or less, at least according to the redux devtools plugin). I just copied things over from my repo. 

So, I tried wrapping the redirect in a setTimeout and voila, everything worked as expected.
```
useEffect(() => {
  if (loginData.isSuccess) {
    setTimeout(() => history.push('/'))
  }
}, [history, loginData]);
```
🤷‍♂️

**Comment by phryneas** [comment]
My only other observation is that you generally should not use the **cache entry** lifecycyle, but the **request** lifecycle - `onQueryStarted`. This is not too important for mutations, since every mutation has their own cache entry, but for queries this will fire once and no matter how often you refresh it will not fire until your component has unmounted, the cache entry has been removed and you get a new one.

Also, in your component with a mutation, you can `trigger().unwrap().then(...)` instead of a `setTimeout`.

**Comment by collinscangarella** [comment]
Aha! I did not realize that that was possible with that method. I assumed that I would need to use a `onQueryFinished` method which does not exist. Thanks for the pointer. For those who come here from google, the code is as follows:
```
login: build.mutation<LoginResponse, LoginArg>({
  query: (queryArg) => ({
    url: '/api/v1/auth/login/',
    method: 'POST',
    headers: {
      'Authorization': `Basic ${btoa(`${queryArg.basicLogin.email}:${queryArg.basicLogin.password}`)}`
    },
  }),
  onQueryStarted: async (arg: any, {dispatch, queryFulfilled}: any) => {
    const loginData = await queryFulfilled;
    cookies.set(CookieType.AUTH.valueOf(), loginData.data);
    dispatch(setAuth(loginData.data));
    dispatch(setLoggedInAuth(loginData.data));
  },
}),
```
And the way to better way to handle query and mutation callbacks is as follows
```
const handleLogin = handleSubmit((form: LoginForm) => {
  login({basicLogin: form}).unwrap()
    .then(() => history.push('/'))
    .catch((error: ApiError) => {
      if (error.status === 401) {
        toast.dark(loginFailureMessage, {type: 'error'});
      } else {
        toast.dark(loginApiFailureMessage, {type: 'error'});
      }
    })
});
```
Thank you so much for spending the time on this library, @phryneas and @markerikson. It is an incredible library which substantially reduces frontend boilerplate. The `createSlice` stuff is great, the `createApi` stuff is awesome, and the `createApi` code generation is a godsend. Your work will keep redux relevant over the coming years - this library solves many of the problems that experimental builds of react have been trying to solve. Is suspense even coming out anymore? Anyway. Thanks again.

**Comment by markerikson** [comment]
@collinscangarella Great, glad you got this working!

And yeah, here's the current summary of what's going to be in 18 right away, and what's coming later:

- https://github.com/reactwg/react-18/discussions/98#discussioncomment-1318753

Note that the "Suspense for Data Fetching" stuff is still happening, just not right away.
