### ISSUE TITLE
What is the difference between getAll vs getAll().type ?

### ISSUE THREAD

**Issue by ShadabFaiz** [reduxjs/redux-toolkit#1539]
This is more of question. I'm using reduc-toolkit with react-saga
This is my reducer
```  react
export const counterSlice = createSlice({
  name: 'brokerOwner',
  initialState,
  reducers: {
    getAll
    : (state, action) => {
      console.log(action);
      state.loading = true;
      state.error = null;
    },
    
  }
});

export const { getAll } = counterSlice.actions;

export default counterSlice.reducer;

```

and this is my saga.
```  react
export function* watchAllSaga() {
  yield takeLatest(getAll, () => console.log(`helloo`));
}


export default function* rootSaga(getState) {
    yield all([
       watchAllSaga()
    ]);
}
```

Now my confusion is in function `watchAllSaga`, I'm passing `action creator` instead of `action type`. However If I replace the code in that function with this:
```
  yield takeLatest(getAll().type, () => console.log(`helloo`));
```
It will still work. So what is the difference between these two way. In both cases the code will work.

Does saga assume if we are passing a string, then it is an action type and if we are passing a function, it is action creator and internally execute action creator to get the action type?

**Comment by markerikson** [comment]
This is really much more a question of how Redux-Saga works than anything else.

Per https://redux-saga.js.org/docs/api#takepattern , the `take()` functions can accepts a string, or a function:

- if it's a string, `take()` will match this as an exact action type string
- if it's a function, `take()` assumes that this is going to return a value from inside the action and will match if the result is truthy. HOWEVER, if the function has a `.toString()` defined, then `take()` will instead call `.toString()` and use the string as an exact action type string match.

RTK's action creators do in fact have a `.toString()` defined which returns the same type string as `.type`, so `take()` will behave the same either way.
