### ISSUE TITLE
What is the recommended way to use Redux Devtools with React Native?

### ISSUE THREAD

**Issue by Dani-Boy92** [reduxjs/redux-toolkit#1544]
I am trying to use the redux devtools in React Native and am struggling to find a way to do it. Is there a recommended way to use the redux devtools with React Native.  

My current approach  (not working):

```
export const store = configureStore({
  reducer: {
    stories: storiesReducer,
    [idApi.reducerPath]: idApi.reducer,
  },
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(idApi.middleware),
  devTools: [devToolsEnhancer({ realtime: true })],

});
```
I expect that after successfully configuring the devtools, I should be able to use the devtools via the React Native debugger.

**Comment by Dani-Boy92** [comment]
Issue solved by using the stand alone React Native debugger (https://github.com/jhen0409/react-native-debugger/blob/master/docs/getting-started.md) not the web version.

**Comment by thenriquedb** [comment]
I use the pinball with the Redux Debugger plugin and it works perfectly.

https://github.com/jk-gan/redux-flipper
