### ISSUE TITLE
Rky-query is not very friendly for file uploads and file downloads

### ISSUE THREAD

**Issue by kuangshp** [reduxjs/redux-toolkit#1545]
I want to download the file using RTk-query. So far, I've used AXIos to download files without problem. Now that I'm using RTK-Query, I want to remove Axios from the project and download the file using RTK-Query. But I can't get the return value, and the interface won't run the interceptor. File uploads using const formData = new formData () are also warned

```typescript
const baseQuery = fetchBaseQuery({
  baseUrl,
  prepareHeaders: (headers) => {
    const token: string = storage.getItem(authToken);
    if (token) {
      headers.set(authToken, token);
    }
    return headers;
  },
});

export const fetchWithIntercept: BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError> =
  async (args, api, extraOptions) => {
    const result: QueryReturnValue<unknown, FetchBaseQueryError, FetchBaseQueryMeta> =
      await baseQuery(args, api, extraOptions);
    return result;
    }
  };

export const baseApi = createApi({
  baseQuery: fetchWithIntercept,
  reducerPath: 'baseApi',
  endpoints: () => ({}),
});
```

```typescript
const tagihanApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    downFileApi: builder.mutation<Blob, Partial<Omit<ITagihanFormDto, 'pageSize' | 'pageNum'>>>({
      query: (data: Partial<Omit<ITagihanFormDto, 'pageSize' | 'pageNum'>>) => ({
        url: '/admin/api/v3/hso/loans/download',
        method: 'post',
        body: data,
        // responseType: 'blob',
      }),
    }),
  }),
  overrideExisting: false,
});
export const {
  useDownFileApiMutation,
} = tagihanApi;
export default tagihanApi;
```

**Comment by phryneas** [comment]
File uploads (assuming you are using mutations) should work without warning in 1.6.1.

File downloads on the other hand should not go through RTK Query. The point of RTK Query is not "to receive something from a server", but "to put something in memory for later use". You dont't want to put multiple megabytes of downloads into memory for an undetermined amount of time if it is completely avoidable to do so.

Just use your `fetchWithIntercept` directly for downloads, do not cram them into memory in-between. Or just use `fetch` from the start.

**Comment by kuangshp** [comment]
> Just use your `fetchWithIntercept` directly for downloads, do not cram them into memory in-between. Or just use `fetch` from the start.

Thank you, I didn’t find any relevant information in the documentation. Do you mean that you shouldn’t use rtk-query to download files, use fetch, or even axios.

**Comment by phryneas** [comment]
If you use RTK Query for a file download, that file is being put into your redux store and kept in the user's memory until the downloading component downloads another file or is unmounted. Because that is what RTK-Q is made for.  
That is uneccessary if you want to trigger a "browser download".

=> Just use `fetch` or `axios` for downloads.

**Comment by hamzeloudev** [comment]
A utility package for integrating file upload/download with progress tracking into your Redux Toolkit Query API slices:

[rtk-upload-utils](https://www.npmjs.com/package/rtk-upload-utils)
