### ISSUE TITLE
@reduxjs/toolkit npm typo on unpacked size

### ISSUE THREAD

**Issue by oldi92** [reduxjs/redux-toolkit#1554]
I was working on a new project lately and when i was  installing @reduxjs/toolkit i saw and issue. On [reduxjs/toolkit](https://www.npmjs.com/package/@reduxjs/toolkit) i saw a problem on package info with the unpacked size was 10mb 😸 . 10 mb for a package is huge and i wonder if that is an issue.

<img src="https://user-images.githubusercontent.com/31727066/135302376-24899f76-d648-4791-9d27-4b3bc7989c58.png"  width="400"/>

**Comment by markerikson** [comment]
I assume that's not a typo. If you look at the package contents, we ship multiple build artifacts for the RTK core, RTK Query without React, and RTK Query with React: CJS, ESM, UMD, variations for dev and prod, and all with sourcemaps.  Those do take up a lot of disk space.

I'd _like_ to cut down the number of artifacts that are in there as part of a 2.0 release, but this is the nature of having a library that needs to support many different usage environments.

Besides, if you're building a browser app, that "unpacked" size is meaningless - what matters is the code size in _one_ build artifact, and how much of that might get used or tree-shaken.  As you can see, _that_ size is a lot smaller:

https://bundlephobia.com/package/@reduxjs/toolkit@1.6.1

> 32.1 kB Minified
> 10.5 kB Minified + Gzipped

So yes, that 10MB exists on disk in your local dev environment, but that's _not_ what's getting shipped to a browser :)

**Comment by oldi92** [comment]
Thank you @markerikson for the clarification. I thought that the unpacked size is somehow related to the project size package size. Also i check on my project the bandle size and it was 10.6k and was wondering if it was an issue.

**Comment by markerikson** [comment]
Yeah, the "unpacked" size is simply "size of the folder when you extract it into `node_modules`".  If I were to add a 50MB JPG file to our package the next time I published, that size would suddenly become 60MB total, but still irrelevant to the browser usage :)
