### ISSUE TITLE
Typescript error when adding RTK-Query middleware to a nested store

### ISSUE THREAD

**Issue by dnlaviv** [reduxjs/redux-toolkit#1571]
I'm trying to add the RTK-Query middleware to a nested store structure, I'm getting a very long and non-descriptive typescript error when I add the API middleware...

Here's my code:
```ts
export const rootReducer = combineReducers({
  foo: fooReducer,
  nested: combineReducers({
    bar: barReducer,
    [myFooApi.reducerPath]: myFooApi.reducer,  
  })
});

const store = configureStore({
  reducer: rootReducer,
  
  middleware: (getDefaultMiddleware) =>   // Getting TS2322 error: type is not assignable to type...
    getDefaultMiddleware().concat(tokenListsApi.middleware)

});
```
The error disappears when I move [fooApi.reducerPath] to the root of the reducer like so:
```ts
export const rootReducer = combineReducers({
  foo: fooReducer,
  bar: barReducer,
  [fooApi.reducerPath]: fooApi.reducer,  
});
```
I was looking for examples of a nested usage of the RTK-Query Api reducer but couldn't find any... what am I missing?

**Comment by markerikson** [comment]
Correct, the RTKQ logic currently requires that the generated reducer _must_ exist at the root of the state tree, and enforces that via both TS types and runtime checks.

Generally you want ever be interacting with the state inside that generated reducer from your own code - you'll use the RTKQ hooks to do it.  So, it shouldn't be something you would need to nest or move around.

Do you have a particular use case for wanting to nest it here?

**Comment by dnlaviv** [comment]
@markerikson Thanks for the quick reply!
I'm planning on hitting more than 10 different APIs I just figured it'll be better to nest in this case.

Also, it might be worth adding this requirement to the official docs for future noobies :) 

Thanks again!

**Comment by markerikson** [comment]
Can you give an example of the different APIs that you are planning to talk with?

We normally recommend that there should only be _one_ API slice at all in an app, unless you are truly communicating with _completely_ different servers:

https://redux-toolkit.js.org/tutorials/rtk-query#create-an-api-service

**Comment by dnlaviv** [comment]
Yeah, I saw that, it says in the docs one API per root URL, so I assumed that I could have more than one API reducer since I will be fetching data from multiple servers.

**Comment by markerikson** [comment]
Yep, you'll just need to give each of them a unique `reducerPath` field so that they don't stomp on each other.

Note that you could still even mix data from completely different servers inside a single API slice if you want to, you'd just have to spell out the full URLs in each endpoint rather than relying on `baseUrl` all the time.  This would especially be important if any of those endpoints need to interact with each other via invalidation.

**Comment by dnlaviv** [comment]
Makes sense! 

Thanks for the help @markerikson 😄
