### ISSUE TITLE
Reducer doesn't mutate the state

### ISSUE THREAD

**Issue by Sayton7** [reduxjs/redux-toolkit#1580]
Hello everyone,
have an authedUserSlice with the code as follows:

`import { createSlice } from '@reduxjs/toolkit'

export const authedUserSlice = createSlice({
    name: 'authedUser',
    initialState: null,
    reducers: {
        setAuthedUser: (state, action) => {
            return action.payload
        }
    },
})

export const { setAuthedUser } = authedUserSlice.actions

export default authedUserSlice.reducer`

My current store state is as follows:

`state = {
questions : {..., ...}
users : {..., ...}
}`

Whenever I dispatch setAuthedUser with an id the action gets dispatched and logged via Redux-Logger. However the state doesn't change no matter how I try to change the reducer function, I can't get it to change the state.

` prev state {users: {…}, questions: {…}}
action     {type: 'authedUser/setAuthedUser', payload: 'tylermcginnis'}
 next state {users: {…}, questions: {…}}`

I need the state to be as follows:

`next state {users: {…}, questions: {…}, authedUser: 'tylermcginnis'}`

What is wrong here

**Comment by phryneas** [comment]
That looks like you maybe forgot to register the `authedUserSlice` reducer at all in `configureStore`?

**Comment by Sayton7** [comment]
@phryneas That was it, just figured it out a couple of hours ago.
Thank you so much for your help.
