### ISSUE TITLE
fetchBaseQuery: baseUrl built from the state

### ISSUE THREAD

**Issue by andreasciamanna** [reduxjs/redux-toolkit#1583]
I'm quite new to redux-toolkit and even newer to RTK and still wrapping my head around it, so please forgive me if what follows makes little sense.

For a service (a little client to access GitLab APIs), I have something like that:

```ts
export const baseQuery = fetchBaseQuery({
  baseUrl: getAPIUrl(),
  prepareHeaders: (headers, { getState }) => {
    const token = (getState() as RootState).auth.gitlab.token;
    !!token && headers.set('PRIVATE-TOKEN', token);

    return headers;
  },
});
```

The headers contain a token that is retrieved from the `getState()` (a separate slice that stores data in the `localStorage`).

However, the URL is also part of this state (as the user can specify a different instance/url of the service).

`getAPIUrl()` is a dirty workaround that directly accesses the object stored in the `localStorage`, since I can''t access the state when setting the value of `baseUrl`.

When I change that URL in theUI, it does get saved as expected in the `localStorage`, however, the `baseQuery` still sees the old one, and this is expected, given the implementation.

The React app can't see the change until I reload the page.

Is there a smarter and better solution to this?

**Comment by bashidagha** [comment]
another example:
`
const baseQuery = fetchBaseQuery({
  baseUrl: 'https://api.your-really-great-app.com/v1/',
  prepareHeaders: (headers, { getState }) => {
    const token = (getState() as RootState).auth.token;
    // If we have a token set in state, let's assume that we should be passing it.
    if (token) {
      headers.set('authorization', `Bearer ${token}`);
    }
    return headers;
  },
})
`

**Comment by bashidagha** [comment]
```
const baseQuery = fetchBaseQuery({
  baseUrl: 'https://api.your-really-great-app.com/v1/',
  prepareHeaders: (headers, { getState }) => {
    const token = (getState() as RootState).auth.token;
    // If we have a token set in state, let's assume that we should be passing it.
    if (token) {
      headers.set('authorization', `Bearer ${token}`);
    }
    return headers;
  },
})
```
