### ISSUE TITLE
Requesting ENDPOINT context on prepareHeaders of fetchBaseQuery (RTK Query)

### ISSUE THREAD

**Issue by luchmewep** [reduxjs/redux-toolkit#1588]
Reference: https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery

Good day, RTK Team.

Currently, the `prepareHeaders` has this signature:

```
;(headers: Headers, api: { getState: () => unknown }) => Headers
```

Sir @phryneas told me before to merge `login` and `register` API slice to the `user` API slice since they are under the same parent API which is `/users`. And so I did. When I looked at the example on how to add Bearer token on each API call on the new `users` API slice, I encountered `prepareHeaders`. Everything is working, no issue found. The problem surfaced when I suddenly saw the `Authorization Bearer token` request headers on the `login` and `register` endpoints which do not make sense.

My idea is maybe we could give prepareHeaders an idea as to which endpoint it should apply the header. My proposed new signature would be something like this:

```
;(headers: Headers, api: { getState: () => unknown }, endpoint: string) => Headers
```

Using this, we can use a switch case to check if the endpoint is either login or register so that we can just skip it.

That's it! Have a nice day!

**Comment by markerikson** [comment]
#1656 is available in the 1.7 betas .
