### ISSUE TITLE
RTK useLazyQuery: Problems met when implementing lazy load tree

### ISSUE THREAD

**Issue by Benshakalaka** [reduxjs/redux-toolkit#1595]
Previously I thought lazy load tree would be easy to implement. However, when debugging I found some problems hard to solve. When user click expand icon, we would call lazy trigger to get children data of node. But when user wants to expand several nodes at the same time, the request would be covered by next request.
Can anyone help?

**Comment by phryneas** [comment]
I would make it a nested component structure.

```js
function TreeNode(props) {
  const {id, name} = props.id
  const [expanded, toggle] = useReducer(v => !v, false)

  const result = useDataQuery(id, { skip: !expanded })

  return (<>
    <div onClick={toggle}>
      toggle {name}
    </div>
    { result.isSuccess && result.data.items.map( 
      item => <TreeNode key={item.id} id={item.id} name={item.name} /> 
    )}
  </>)
}
```
