### ISSUE TITLE
About Interface Caching

### ISSUE THREAD

**Issue by kuangshp** [reduxjs/redux-toolkit#1596]
[The official address](https://redux-toolkit.js.org/rtk-query/usage/cache-behavior)，
Now I am form on each line there is a button, click on the state of the data switch, every time I click again when it switches for a form, request sent to obtain the data, access to data or the old data, but I've changed the database state, I think is a problem of cache, but I don't take effect, according to official such In this case, to set a separate interface to not cache how to set

**Comment by phryneas** [comment]
I am really not sure what you are asking.

I think you might want to use cache invalidation using `providesTags`/`invalidatesTags` [as described here in the docs](https://redux-toolkit.js.org/rtk-query/usage/automated-refetching) but I'm really not sure if I understood the question correctly.
