### ISSUE TITLE
RTK Query - Wait to update till after user action

### ISSUE THREAD

**Issue by nkeeslin** [reduxjs/redux-toolkit#1632]
Hey folks,

I'm trying to implement a caching strategy wherein we check the cache and also fire off a request to the server whenever data is required (to then update the cache if needed).  I also want to hold off on updating the UI when the new data returns until the user performs an action (presses OK on a banner for example). Is that possible using RTK Query, and if so how would you recommend it? I looked through the documentation and I didn't see any reference to this kind of fetch and wait to update the UI logic.

Thanks!

**Comment by jjl-genemod** [comment]
Couldn't you just keep a state variable, or boolean value in your redux store that controls the display of the data in your component?

**Comment by phryneas** [comment]
RTK-Query does not really come with a "cache-and-network" strategy, but you can set `refetchOnMountOrArgChange​` in your hook options to `true`, which kinda has that behaviour.

But as for the "holding up on updates", I'm sorry, that is very specific and I wouldn't know any library that does something like that.
