### ISSUE TITLE
RTK Query - Can baseUrl be set dynamically during runtime?

### ISSUE THREAD

**Issue by fvkramer** [reduxjs/redux-toolkit#1657]
Hello,

I want to set a base url in RTK Query that uses a nested resource. I don't know the nested resource id until the user logs in.
Before the user logs in, the baseUrl in RTK Query is `/api/v0`. After the user logs in I'd like to dynamically set the baseUrl to
`/api/v0/organizations/${currentUser.organizationId}`

Is there a way of doing so?

I've attempted

```Javascript

import { apiConfig } from "./apiConfig";

export const exampleApi = createApi({
   baseQuery: fetchBaseQuery({
     baseUrl: apiConfig.url
   })
})
```

and in a separate file before the exampleApi runs, but user logs in,

```Javascript
apiConfig.url = `${apiConfig.url}/organizations/${currentUser.organizationId}`
```

The above flow doesn't work. The baseUrl does not get updated.

The more sensible solution is probably to not attempt setting baseUrl during runtime and rather set organization configuration data in an API token, but want to check if there's a way to do so before I refactor.

Thank you

**Comment by hamzeloudev** [comment]
A utility package for integrating file upload/download with progress tracking into your Redux Toolkit Query API slices:

[rtk-upload-utils](https://www.npmjs.com/package/rtk-upload-utils)

**Comment by artuska** [comment]
> There is an example of building a dynamic baseUrl-eqiuvalent in the docs: https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#constructing-a-dynamic-base-url-using-redux-state

This example absolutely not showing how to make a dynamic `baseUrl` — this example shows how to change anything in final url except `baseUrl`.

**Comment by EskiMojo14** [comment]
it acts the same as customising the base url, it's just appending to a shared base URL. if you needed to talk to completely different domains, you could just not specify a base URL when setting up `rawBaseQuery` and instead prepend the entire base URL in the `dynamicBaseQuery`.
