### ISSUE TITLE
How to integrate optimistic updates with debounce?

### ISSUE THREAD

**Issue by adi518** [reduxjs/redux-toolkit#1675]
We have a scenario where we must use debounce to avoid excessive requests, a classic case. However, integrating debounce with optimistic updates does not seem obvious, hence this issue.

**Comment by phryneas** [comment]
This has nothing to do with optimistic updates.

After all, you want to debounce the requests themselves that are sent to the server, not only the updates on the client. 
And as for that: You have a `trigger` function for your mutation. You want to debounce calling it.  
Debouncing that is outside of the scope of Redux Toolkit and you can use any of thousands of external libraries for the job. 

A short google of "react debounce callback" brought up [this article](https://dmitripavlutin.com/react-throttle-debounce/) as first search result and it would probably work.
Another hit from the first page brings up the [use-debounce](https://github.com/xnimorz/use-debounce) library. Will probably work as well.

**Comment by adi518** [comment]
I'll provide more details on our use case. We have a text area which has to reflect any change immediately. If we debounce the RTK action, it will also debounce the optimistic update, effectively rendering it useless.

**Comment by markerikson** [comment]
It might help if you can clarify what exactly you're trying to "debounce" in relation to optimistic updates - the original statement really isn't clear.  Can you show an example?

**Comment by adi518** [comment]
I just added another post, which hopefully makes it clearer.

**Comment by phryneas** [comment]
So you don't want to do optimistic updates, but manual cache updates. Generally, you can use the cache manipulation tools in whatever way for that, but you will have to call them in your own code outside of the request lifecycle. Since we don't know your code there is no real guidance on that we can give you.

**Comment by adi518** [comment]
I do want to do optimist updates, but I need RTK to provide an option to debounce the request, which actually makes it a feature request.

**Comment by markerikson** [comment]
@adi518 : you're still not being clear at all on debouncing _what_ requests, _how_, or _when_.

_Please_ provide some examples of what you're trying to do here.

I don't know if you're referring to requests being triggered by passing a new cache key into a hook, manually triggered `dispatch(initiate())` calls, or something else.

The more details you can give, the better chance we'll be able to help you.  Right now you seem to be assuming we can read your mind, and that's not the case.

**Comment by adi518** [comment]
Sure, so I'm doing a simple mutation using a mutation hook, which I bind to a text area change event.

```ts
const [value, setValue] = useState()
const [updateContent] = useUpdateContentMutation();
const debouncedUpdateContent = useCallback(debounce(updateContent, 500));

function handleChange (e) {
  setValue(value);
  debouncedUpdateContent();
}

return <textarea value={value} onChange={debouncedHandleChange} />
```

As you can see, it's not possible to utilize optimistic updates this way.

**Comment by markerikson** [comment]
I'm afraid I still don't see any "optimistic updates" in there at all.  All I see is a call to a local `setState()`, and a call to a debounced mutation trigger.

Really seems like we're having trouble communicating here. Can you try to explain what you _want_ to happen, step by step, even if there's no API that does what you want atm?

**Comment by adi518** [comment]
See my updated snippet. I skipped adding more code that will revert the state if the request fails.

**Comment by markerikson** [comment]
I'm looking at it, and I _still don't know what you want to do_.

When you say "optimistic update", are you referring to updating the RTKQ cache data? or the local component state?  or something else?

**Comment by phryneas** [comment]
If we would add a debounce functionality, optimistic updates would still happen only for the debounced requests - since the way we are suggesting to do optimistic updates is bound to the **request lifecycle**. 

No request, no optimistic update.

That said, it would not give any benefits over just using an external library for the debounce, at the added cost of shipping a debouncing library to everyone not needing it.

If you want to make updates to the cache outside of the RTK Query request lifecycle, you can do that, but it is not a supported scenario, so you will have to do that manually.

**Comment by adi518** [comment]
I want to optimistically update the state that RTK creates for its API slice. That is to avoid maintaining server state as a local state.

**Comment by phryneas** [comment]
The term "optimistic update" means "when we make a request, we already assume the value the server will probably have in a bit on the client side". If there is no request, there is no "optimistic update" to make.

You just want to make a cache modification. And that is perfectly fine. You can do that using [`updateQueryData​`](https://redux-toolkit.js.org/rtk-query/api/created-api/cache-management-utils#updatequerydata), outside of the request lifecycle whenever you want. But it is not a supported use case, and you will have to do so on your own.

As I said, even if we were to integrate that, it would still be bound to the request and not do what you want.

> Alternatively, RTK can provide an option to tap the request handler and compose debounce or whatever else a user might need.

The request handler is `baseQuery`. You can wrap that in your own function and do any kind of debouncing there as you want. If you only want to do it for a single endpoint, you can also do that in `queryFn`.

**Comment by markerikson** [comment]
You can run this code basically anywhere you have access to `dispatch`:
https://redux-toolkit.js.org/rtk-query/usage/manual-cache-updates#optimistic-updates

```
        const patchResult = dispatch(
          api.util.updateQueryData('getPost', id, (draft) => {
            Object.assign(draft, patch)
          })
        )
        try {
          await queryFulfilled
        } catch {
          patchResult.undo()
        }
```

**Comment by adi518** [comment]
Thanks guys, I'll have a look at these solutions and close this issue if it resolves. I'll also post a snippet of the actual solution. 👍

**Comment by nikischin** [comment]
> Thanks, I'll have a look at these solutions and close this issue if it resolves. I'll also post a snippet of the actual solution.

Could you possible provide some snippet of your solution, as I am looking for the same functionality.

**Comment by adi518** [comment]
Unfortunately, I no longer have access to it, so I'm afraid not. I think we created a helper for `onQueryStarted` for simple cases and for more complex cases, where we needed to debounce the requests, we did empiric manual cache updates inside a thunk and used the `quernFn` option to pass an async denounce handler. Actually, it was even further since we used GraphQL, which allows you to do multiple transactions in one request, so with every change, we would accumulate a query/mutation into the request and when the debounce interval cleared, it put out a single request. To put this into better context for why it is needed. We essentially built an audio editing software in the browser, so you'd have lots of audio segments that you can move around and changes must reflect immediately, there's simply no other way to do it and still provide a good UX.

**Comment by nikischin** [comment]
Thank you so much @adi518 for your answer!

**Comment by nikischin** [comment]
So for anyone else wondering, I wrote an implementation like this, doing pretty much what is desired:

```
import { useState } from 'react';
import { useDispatch } from 'react-redux';
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { upperFirst } from 'lodash';

import useAutosave from './autoSaveHooks';
import { useAutosave } from 'react-autosave';

// Define functions based on endpoints, which are called for the optimistic updates from both autosave and mutations
const optimisticEndPointUpdates = {
    setPost: [
        ({ id, ...patch })=> [
            'getPost',
            { id: id },
            (draft)=> {
                //Override everything except id..., but only in data object, not in full draft
                Object.assign(draft, { data: { ...draft.data, ...patch } });
            }
        ]
    ]
};

function buildAutoSaveHook (endpointName) {
    return ()=> {
        const useQueryMutation = (generalApi)[`use${upperFirst(endpointName)}Mutation`];
        const [ mutation, ...mutationFunctions ] = useQueryMutation();
        const [ queryData, setQueryData ] = useState();
        const [ queryOptions, setQueryOptions ] = useState();
        const [ patchResult, setPatchResult ] = useState([]);
        const dispatch = useDispatch();

        const onSave = async ()=> {
            if (queryData !== undefined) {
                // Reset Very optimistic updates - mutation will now further handle it...
                patchResult.forEach(res=> {
                    console.log(res);
                    res?.undo();
                });

                mutation(queryData, queryOptions);
            }
        };

        useAutosave({ data: queryData, onSave: onSave });

        return [ (data, options)=> {
            setQueryData(data);
            setQueryOptions(options);

            patchResult.forEach(res=> {
                //Undo previous patches before setting new one
                res?.undo();
            });

            setPatchResult(optimisticEndPointUpdates[endpointName].map((funcs)=> {
                const optimisticDefParams = funcs(data);

                if (optimisticDefParams) {
                    return dispatch(generalApi.util.updateQueryData(...optimisticDefParams));
                }
            }));
        }, ...mutationFunctions ];
    };
}

const onQueryStartedOptimistic = (endpoint)=> async ({ id, ...patch }, { dispatch, queryFulfilled })=> {
    optimisticEndPointUpdates[endpoint].forEach(async (funcs)=> {
        const optimisticDefParams = funcs({ id, ...patch });

        if (optimisticDefParams) {
            const patchResult = dispatch(generalApi.util.updateQueryData(...optimisticDefParams));

            try {
                await queryFulfilled;
            } catch {
                patchResult.undo();
            }
        }
    });
};

// Define a service using a base URL and expected endpoints
export const generalApi = createApi({
    reducerPath: 'api',
    baseQuery: fetchBaseQuery({
        baseUrl: 'https://api.example.com',
    }),
    endpoints: (builder)=> ({
        /* QUERIES */
        getPost: builder.query({
            query: ({ id })=> 'getPost/' + encodeURIComponent(JSON.stringify({ id: id })),
        }),

        setPost: builder.mutation({
            query: (data)=> ({
                url: 'setPost',
                method: 'POST',
                body: JSON.stringify(data),
            }),
            onQueryStarted: onQueryStartedOptimistic('setPost'),
        }),
    }),
});

//Add auto generated AutoSaveMutation Endpoints
Object.values(generalApi.endpoints).forEach(endpoint=> {
    if (endpoint.useMutation) {
        const useAutoSaveMutation = buildAutoSaveHook(endpoint.name);
        Object.assign(generalApi.endpoints[endpoint.name], useAutoSaveMutation);
        (generalApi)[`use${upperFirst(endpoint.name)}AutoSaveMutation`] = useAutoSaveMutation;
    }
});

// Export hooks for usage in functional components, which are
// auto-generated based on the defined endpoints
export const {
    useGetPostQuery,
    useSetPostMutation,
    useSetPostAutoSaveMutation
} = generalApi;
```


```
//usage


const [setPost, { error }] = useSetPostAutoSaveMutation();

<input onchange={(e) => setPost({id: '123', title: e.target.value})} />
```

Unfortunately I wasn't able to make VSCode autosuggest the `AutoSaveMutations`, though anything else seems to work so far. If @markerikson or @phryneas would have some improvement recommendation on my code for this custom solution I could also post another update maybe.

Maybe this helps someone with a similar problem.

**Comment by adi518** [comment]
Please highlight your snippet by adding `js` after the first set of backticks. I'd also strongly advise to use TS.

**Comment by nikischin** [comment]
> Please highlight your snippet by adding `js` after the first set of backticks. I'd also strongly advise to use TS.
> 
> Also, is it supposed to feature debounce? because I don't see that.

Ah thank you so much for the tip! And it does indeed use debounce, I used the code 
`import { useAutosave } from 'react-autosave';` which also includes debounce.

**Comment by adi518** [comment]
That's okay if you want to use it from hooks, but what if you want to do it from a thunk? you need to break it down and use a more generic utility.

**Comment by nikischin** [comment]
I came up with an updated solution with Typescript which unfortunately still is far from perfect:

```ts
function buildAutoSaveHook (api, endpoint): UseMutation<any> {
    return ()=> {
        //const useQueryMutation = (baseApi)[`use${upperFirst(endpointName)}Mutation`];
        const [ mutation, ...mutationFunctions ] = endpoint.useMutation();
        const [ queryData, setQueryData ] = useState();
        const [ queryOptions, setQueryOptions ] = useState();
        const [ patchResult, setPatchResult ] = useState([]);
        const { dispatch, getState } = useStore();

        const onSave = async (concatinatedQueryData)=> {
            if (concatinatedQueryData !== undefined) {
                // Reset Very optimistic updates - mutation will now further handle it...
                patchResult.forEach(res=> {
                    console.log(res);
                    res?.undo();
                });

                mutation(concatinatedQueryData, queryOptions);
            }
        };

        useAutosave({ data: queryData, onSave: onSave });

        return [ (data, options)=> {
            setQueryData(data);
            setQueryOptions(options);

            patchResult.forEach(res=> {
                //Undo previous patches before setting new one
                //res?.undo();
            });

            setPatchResult(endpoint.optimisticUpdates?.map((funcs)=> {
                const optimisticDefParams = funcs(data, getState);

                if (optimisticDefParams) {
                    return dispatch(api.util.updateQueryData(...optimisticDefParams));
                }
            }) ?? []);
        }, ...mutationFunctions ];
    };
}

const onQueryStartedOptimistic = (api, endpoint)=> async ({ id, ...patch }, { dispatch, queryFulfilled, getState })=> {
    console.log('onQueryStarted: ', endpoint, id, patch);

    endpoint.optimisticUpdates?.forEach(async (funcs)=> {
        const optimisticDefParams = funcs({ id, ...patch }, getState);

        if (optimisticDefParams) {
            const patchResult = dispatch(api.util.updateQueryData(...optimisticDefParams));

            try {
                await queryFulfilled;
            } catch {
                patchResult.undo();
            }
        }
    });

    endpoint.optimisticUpserts?.forEach(async (funcs)=> {
        const optimisticDefParams = funcs({ id, ...patch }, getState);

        if (optimisticDefParams) {
            const patchResult = dispatch(api.util.updateQueryData(...optimisticDefParams));

            try {
                await queryFulfilled;
            } catch {
                patchResult.undo();
            }
        }
    });
};

function isMutationDefinition ({ type }: { type: string }): boolean {
    return type === 'mutation';
}

const customModuleName = Symbol();

export type CustomModule = typeof customModuleName

declare module '@reduxjs/toolkit/query/react' {
    export interface ApiModules<
        BaseQuery extends BaseQueryFn,
        Definitions extends EndpointDefinitions,
        ReducerPath extends string,
        TagTypes extends string
    > {
        [customModuleName]: AutoSaveHooks<Definitions>;
    }
}

//not yet implemented
type AdditionalArgsType = {
    optimisticUpdates?: { (...args: any): any[]; }[]
    optimisticUpserts?: { (...args: any): any[]; }[]
}

export type AutoSaveHooks<
    TDefinitions extends EndpointDefinitions
> = keyof TDefinitions extends infer Keys
    ? Keys extends string
    ? {
        [K in Keys as TDefinitions[K] extends MutationDefinition<any, any, any, any> ? `use${Capitalize<K>}AutoSaveMutation` : never]: UseMutation<
            Extract<TDefinitions[K], MutationDefinition<any, any, any, any>>
        >
    }
    : never
    : never;


const autoSaveModule = (): Module<CustomModule>=> ({
    name: customModuleName,
    init (api, options, context) {
        return {
            injectEndpoint (endpointName, definition) {
                if (isMutationDefinition(definition)) {
                    const anyApi = api as any as Api<
                        any,
                        Record<string, any>,
                        string,
                        string,
                        CustomModule | CoreModule
                    >;

                    Object.assign(definition, {
                        onQueryStarted: definition.onQueryStarted ?? onQueryStartedOptimistic(api, api.endpoints[endpointName])
                    });

                    api.endpoints[endpointName].optimisticUpdates = definition.optimisticUpdates;
                    api.endpoints[endpointName].optimisticUpserts = definition.optimisticUpserts;

                    const useAutosave = buildAutoSaveHook(api, api.endpoints[endpointName]);
                    Object.assign(api.endpoints[endpointName], {
                        useAutosave
                    });
                    (api)[`use${upperFirst(endpointName)}AutoSaveMutation`] = useAutosave;
                }
            },
        };
    },
});

export const createAutoSaveApi = buildCreateApi(coreModule(), reactHooksModule({
    hooks: {
        useDispatch: useDispatch,
        useSelector: useSelector,
        useStore: useStore,
    },
}), autoSaveModule());
```

It includes auto-suggestion of the hooks and optimistic updates and upserts. Those optimistic updates/upserts are actually very optimistic as they get fired before an HTTP request is even fired. 

Maybe this does help someone looking for some auto-save integration in RTK query or some debounce functionality and maybe also someone might have some suggestions for further improving this code in order to fully implement Typescript.
