### ISSUE TITLE
RTK query - generated Hooks asking for 1 - 2 arguments in typescript

### ISSUE THREAD

**Issue by rvmelkonian** [reduxjs/redux-toolkit#1676]
I'm getting the following Typescript error when I try to use the generated hooks from ``apiSlice``

```
Expected 1-2 arguments, but got 0.ts(2554)
buildHooks.d.ts(38, 143): An argument for 'arg' was not provided.
```

my apiSlice

```
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

export const apiSlice = createApi ({
    reducerPath: "apiSlice",
    baseQuery: fetchBaseQuery({
        baseUrl: process.env.NEXT_PUBLIC_BASE_URL,
    }),
    endpoints: (builder) => ({
        getUsers: builder.query({
            query: () => `/users`
        }),
    }),
});

export const { useGetUsersQuery } = apiSlice;
```

my store 
```
import { configureStore } from '@reduxjs/toolkit';
import { rootReducer } from "./reducers/rootReducer";
import { apiSlice } from '../features/apiSlice';

const store = configureStore({
  reducer: {
    rootReducer,
    [apiSlice.reducerPath]: apiSlice.reducer
  },
  middleware: getDefaultMiddleware => 
    getDefaultMiddleware().concat(apiSlice.middleware)
});

// Infer the `RootState` and `AppDispatch` types from the store itself
export type RootState = ReturnType<typeof store.getState>
export type AppDispatch = typeof store.dispatch

export default store
```

And my client code, where I'm getting the error under useGetUsersQuery()
```

import { useGetUsersQuery } from '../features/apiSlice'

function MyApp({ Component, pageProps }: AppProps) {

  const { data, isLoading, isSuccess, isError, error } = useGetUsersQuery();

  return (
    <Provider store={store}>
      <Wrapper>
        <GetLatestBlock />
        <Authenticate />
      </Wrapper>
    </Provider>
  )
}

export default MyApp
```

Any clues?

**Comment by markerikson** [comment]
Yes, you need to declare the generic arguments of your `builder.query()` call - they should be `builder.query<ReturnValueHere, ArgumentTypeHere>`.  If there is no argument, use `void`:

https://redux-toolkit.js.org/rtk-query/usage-with-typescript#typing-query-and-mutation-endpoints

**Comment by rvmelkonian** [comment]
thank you mark.

**Comment by gersomvg** [comment]
This example: https://redux-toolkit.js.org/rtk-query/usage/prefetching#recipe-prefetch-immediately

**Comment by markerikson** [comment]
Well, `void` is definitely the correct type for "this query does not require an argument".

That snippet is doing some types lookups and it's just a standalone snippet in the docs, so it's possible that it was written under the assumption that your query _does_ take an argument and not tried with the "no argument" case.

**Comment by gersomvg** [comment]
It does resolve the arg correctly to void, so the `prefetch` simply refuses to consume that as a type. The underlying types of `prefetch` are so daunting I have no idea where to start even, trying to find the issue 😅

**Comment by msutkowski** [comment]
> It does resolve the arg correctly to void, so the `prefetch` simply refuses to consume that as a type. The underlying types of `prefetch` are so daunting I have no idea where to start even, trying to find the issue sweat_smile

Just cast `arg` to any in the prefetch hook as a quick solution: https://codesandbox.io/s/useprefetchimmediately-9rr06?file=/src/usePrefetchImmediately.ts. It looks like our types have changed a bit since we first added that example snippet -- we'll need to look at the best way to unwrap the arg type there.

**Comment by Rocamonde** [comment]
Hi, may I suggest documenting this in the relevant page. Have been reading through the docs, and there is no clear example of how to type the case of no arguments. For users that do not master TypeScript's type system, this is not immediately obvious and it's far from ideal having to read through GitHub issues to figure it out. I am happy to help out write a few lines if needed.

Best wishes.

**Comment by markerikson** [comment]
@Rocamonde fwiw we do specifically mention that here:

https://redux-toolkit.js.org/rtk-query/usage-with-typescript#typing-query-and-mutation-endpoints

> If query doesn't have a parameter, then `void` type has to be provided explicitly.

although perhaps we ought to make that part more obviously highlighted?

**Comment by Rocamonde** [comment]
Hi Mark,

Thanks for your comment. I now see that it is mentioned there. However, I didn’t see it clearly explained in the quick start or in the examples, which is where I normally look to find things as it contains 80% of the use cases that I will ever need. I think making queries without parameters is a very common use case (GETting lists) and it should be discussed in those sections (it is shown but not using TypeScript).

Best wishes

**Comment by katoba86** [comment]
@Rocamonde 
i think it should ne be discussed. Very simple to use it without Parameters. Simple add void







`export const apiSlice = createApi({

   reducerPath:'api',
    baseQuery:fetchBaseQuery({baseUrl:'http://localhost:2000'}),
    endpoints: (builder) => ({
        getTodos: builder.query<any,void>({
            query: () => '/todos'
        })
    })
});`

**Comment by cjsilva-umich** [comment]
> Yes, you need to declare the generic arguments of your `builder.query()` call - they should be `builder.query<ReturnValueHere, ArgumentTypeHere>`. If there is no argument, use `void`:
> 
> https://redux-toolkit.js.org/rtk-query/usage-with-typescript#typing-query-and-mutation-endpoints

If the point about **if there is no argument, use 'void'** is in the documentation, I'm not seeing it while looking it over. Thanks for pointing this out.

**Comment by raselinfo** [comment]
thank you mark

**Comment by smark-Mahi** [comment]
Just write void ,any at builder.query<any,void>({
)}
It absolutely work....really

**Comment by phryneas** [comment]
@ChrisVilches as this is a perfectly valid use of `void`, I would recommend that you set the [`allowInGenericTypeArguments`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-invalid-void-type.md#allowingenerictypearguments) option of that rule to `true`.

Always remember: ESLint rules are there to help you, not to annoy you. If a rule doesn't spark joy, Marie Kondo it.

**Comment by ChrisVilches** [comment]
@phryneas That doesn't work. It still outputs the same error.

```
Error: void is only valid as a return type or generic type argument.  @typescript-eslint/no-invalid-void-type
```

On the other hand, if I set `allowInGenericTypeArguments` to `false`, I get a lot more errors, meaning it was already `true`.

**Comment by phryneas** [comment]
@ChrisVilches that honestly sounds like a bug in the eslint rule. Maybe open an issue over there?

**Comment by dsclassen** [comment]
...and where would I add `<any,void>` when injecting endpoints like this?

```
    refresh: builder.mutation({
      query: () => ({
        url: '/auth/refresh',
        method: 'GET'
      }),
      async onQueryStarted(arg, { dispatch, queryFulfilled }) {
        try {
          const { data } = await queryFulfilled
          const { accessToken } = data
          dispatch(setCredentials({ accessToken }))
        } catch (err) {
          console.log(err)
        }
      }
    })
```

**Comment by markerikson** [comment]
@dsclassen : right after either `builder.query` or `builder.mutation`, like: 

`builder.mutation<ReturnType, ArgType>({.......})`

**Comment by bravo-stack** [comment]
> ...and where would I add `<any,void>` when injecting endpoints like this?
> 
> ```
>     refresh: builder.mutation({
>       query: () => ({
>         url: '/auth/refresh',
>         method: 'GET'
>       }),
>       async onQueryStarted(arg, { dispatch, queryFulfilled }) {
>         try {
>           const { data } = await queryFulfilled
>           const { accessToken } = data
>           dispatch(setCredentials({ accessToken }))
>         } catch (err) {
>           console.log(err)
>         }
>       }
>     })
> ```
>     

Unless I'm mistaken, and please correct me if I'm wrong,
"mutations" are mostly use for POST, PUT and DELETE requests, and I believe that's the convention.

**Comment by EskiMojo14** [comment]
RTKQ doesn't really care what method you use (or even that you use fetch), the distinction is more that queries get data from the server and cache it, whereas mutations make one-shot requests that might modify something on the server

those tend to *correlate* with the purpose for specific methods, of course - but there are APIs out there where you need to get data by POSTing a body, for example

**Comment by bravo-stack** [comment]
> RTKQ doesn't really care what method you use (or even that you use fetch), the distinction is more that queries get data from the server and cache it, whereas mutations make one-shot requests that might modify something on the server
> 
> those tend to *correlate* with the purpose for specific methods, of course - but there are APIs out there where you need to get data by POSTing a body, for example

Alright, Understood.
And thanks for the clarification.

**Comment by Rashad-Stack** [comment]
getJobs: builder.query<Jobs[], void>({
      query: () => ({
        url: "/jobs",
        method: "GET",
      }),
    }), I include void that solve in to second argumnent

**Comment by baharalidurrani** [comment]
After adding `void` for arguments in:
```
fetchNotifications: builder.query<Array<PushNotification>, void>({
```
Now when I try to use `pollingInterval` like 
```ts
  const { data: notifications } = useFetchNotificationsQuery(undefined, {
    pollingInterval: 60 * 1000,
  });
```
or any other option without parameters it gives me the following error:
```
A non-serializable value was detected in the state, in the path: 
`notificationsApi.queries.fetchNotifications(undefined).data.0.ttl`.
```

**Comment by markerikson** [comment]
@baharalidurrani that's a completely separate problem from the TS question that was asked here - please file a new issue.  (That said, are you doing anything to put values like `Date` objects into your response when it gets received?)

**Comment by baharalidurrani** [comment]
Oops, my bad. Yeah, you’re right I'm getting some date objects in the response.
Thanks @markerikson

**Comment by superuserpro** [comment]
https://typescripter.space/questions/what-is-the-best-way-to-create-an-overload-signature-for-a-function-that-could-potentially-receive-either-1-or-2-arguments-when-called
