### ISSUE TITLE
Reflect react peer dependency of the react-redux package

### ISSUE THREAD

**Issue by stevebeauge** [reduxjs/redux-toolkit#1677]
Hello,

React-redux declare peer dependency to react:

https://github.com/reduxjs/redux-toolkit/blob/aefeb4625d5a018a3a9fcb6864f9a3d6074fca53/packages/toolkit/package.json?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L107

````json
{
 "peerDependencies": {
    "react": "^16.14.0 || ^17.0.0"
  }
}
````

Shouldn't this follow the react-redux peer dependency ?
Which is :

https://github.com/reduxjs/react-redux/blob/adade2069061e09eaa046b10389aee265048e034/package.json#L43

````json
{
  "peerDependencies": {
    "react": "^16.8.3 || ^17 || ^18"
  }
}
````

As far as I understand the node dependencies, it should be the same.

The background of my question is related to a project where I'm stick to react 16.13.1 (A sharepoint framework project if it matters). This is an issue due to strict dependencies check policy,

The install process emits peer dependency warning, because the 16.14.0 isn't installed.
But actually, the code should work with 16.8.3, from the react-redux package, which is the actual dependent on react.

Am I right ?

Thanks

**Comment by markerikson** [comment]
Yeah, I think that's correct - this _ought_ to work okay with 16.8+:

https://github.com/reduxjs/redux-toolkit/blob/aefeb4625d5a018a3a9fcb6864f9a3d6074fca53/packages/toolkit/package.json#L107
