### ISSUE TITLE
RTK Query: "settled" behavior

### ISSUE THREAD

**Issue by bryndyment** [reduxjs/redux-toolkit#1681]
Feature request:

E.g. I want to close a modal regardless of whether my mutation succeeded or failed.

(React Query has a "settled" concept that allows me to handle these cases in a single place.)

**Comment by phryneas** [comment]
What do you have to do currently? What do you want to be able to do?

**Comment by bryndyment** [comment]
> What do you have to do currently? What do you want to be able to do?

If I want to execute a line of JavaScript after a mutation "settles" (regardless of success/fail) is the recommended option to do this:

`myMutation(…).unwrap().finally(() => console.log('settled'))`

… or is there another way, such as the `onSettled` callback provided in React Query?

`onSettled: () => console.log('settled')`

**Comment by phryneas** [comment]
`myMutation(…).then(() => console.log('settled'))` would already do it.

If you don't unwrap it will just resolve both in a success and error case.
