### ISSUE TITLE
Having generic type for BaseQueryAPI 

### ISSUE THREAD

**Issue by JulienKode** [reduxjs/redux-toolkit#1685]
Currently if I want to type my custom base query I'll do it with `BaseQueryFn`

here is the current type
```typescript
export type BaseQueryFn<
  Args = any,
  Result = unknown,
  Error = unknown,
  DefinitionExtraOptions = {},
  Meta = {}
> = (
  args: Args,
  api: BaseQueryApi,
  extraOptions: DefinitionExtraOptions
) => MaybePromise<QueryReturnValue<Result, Error, Meta>>
```

This is really nice because it's templated for a lot of parameters:
- Args
- Result
- Error
- ExtraOptions
- Meta

but not for `BaseQueryApi` which can be different for each project, let's say I implemented redux thunk with extra argument then my `BaseQueryApi` will have different than the current one 

This is the current type of `BaseQueryApi`:
```typescript
export interface BaseQueryApi {
  signal: AbortSignal
  dispatch: ThunkDispatch<any, any, any>
  getState: () => unknown
  extra: unknown
}
```

Maybe we should have something like this for people that have their own extra
```typescript 
export type BaseQueryFn<
  Args = any,
  Result = unknown,
  Error = unknown,
  DefinitionExtraOptions = {},
  Meta = {},
  QueryApi extends BaseQueryApi = BaseQueryApi,
> = (
  args: Args,
  api: QueryApi,
  extraOptions: DefinitionExtraOptions
) => MaybePromise<QueryReturnValue<Result, Error, Meta>>
```

I've opened a PR, where we can check what is the best way to implement this https://github.com/reduxjs/redux-toolkit/pull/1684 (The current change are not relevent but it's just an idea)

if you think it's not relevent or if you think there are other way to type it, I can close this

**Comment by phryneas** [comment]
Hey, thanks for the suggestion & PR!

To be honest, unless we get the feedback a lot that this is needed, I'd prefer to keep it like it is at the moment and have people write a type assertion in BaseQuery like

```diff
const baseQuery: BaseQueryFn<string | FetchArgs,  unknown,  FetchBaseQueryError,  {},  FetchBaseQueryMeta> = async (arg, api) => {
+  const getState = api.getState as () => MyState;
+  const extra = api.extra as Something
}
```

I think this is not a very common use case and as long as TS Generic arguments are still positional and not named, each and every one we add makes using the whole type more weird to use, makes maintenance more difficult and locks us into certain decisions we might regret later down the path.

**Comment by JulienKode** [comment]
I totally understand your point of view, 
I wanted to avoid `as` but seems it's better to keep this in that way 

We do not have a way to have the generic type, and if it's not provided still keep the current default one without complexity the current TS Implementation ? 

Thanks for your feedback and help @phryneas

**Comment by thorn0** [comment]
@phryneas 

>  I'd prefer to keep it like it is at the moment and have people write a type assertion in BaseQuery
> `const getState = api.getState as () => MyState;`

This causes a circular reference issue. Please see it here https://codesandbox.io/s/elated-golick-b7kv2n?file=/src/index.tsx
