### ISSUE TITLE
rejectWithValue seems to break type resolution for createAsyncThunk for redux-toolkit@1.6.2

### ISSUE THREAD

**Issue by piotr-musiol** [reduxjs/redux-toolkit#1694]
I have a problem with automatic resolution for return type of createAsyncThunk with newest redux-toolkit - `1.6.2`. The same case works fine in `1.4`.

Given the example:
```
export const test = createAsyncThunk(`test`, async (_req: any, {rejectWithValue}) => {
    if (Math.random() > 0.6) {
        return rejectWithValue({});
    }
    return "TEST";
});
```

and then adding extraReducer:
```
        builder.addCase(test.fulfilled, (state, action) => {
            state.data = action.payload;
        });
```

I would like the action.payload to be `typeof "TEXT"`, not `unknown`.

Redux-toolkit@1.6.2:
![image](https://user-images.githubusercontent.com/78424333/140489254-4e373574-9678-4d3d-bda5-29841048bb20.png)

Redux-toolkit@1.4:
![image](https://user-images.githubusercontent.com/78424333/140489401-d25d481c-df55-44e8-aa11-4ddad10b03c4.png)

📓❗ Without using `rejectWithValue`, everything seems to be working as expected.

Is it something no longer supported?

**Comment by phryneas** [comment]
This should be solved in the next beta release: https://github.com/reduxjs/redux-toolkit/releases/tag/v1.7.0-beta.1

**Comment by piotr-musiol** [comment]
ah, thx for the info! I was looking through the latest issues, but couldn't find anything relating, tbh even those release notes wouldn't tip me off ;), but it's great to hear that. And wow, impressive answer speed!

**Comment by phryneas** [comment]
Yeah, it was in the release notes of beta-0 ;)

https://github.com/reduxjs/redux-toolkit/releases/tag/v1.7.0-beta.0
