### ISSUE TITLE
Handle changes to Redux DevTools Extension 3.0 configuration

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#1698]
Per https://github.com/reduxjs/redux-devtools/releases/tag/v3.0.0-beta.1 , the upcoming DevTools Extension 3.0 has some breaking changes. The biggest one is the renaming of options `actionsBlacklist` and `actionsWhitelist` renamed to `actionsDenylist` and `actionsAllowlist`.

We previously inlined our DevTools Extension config setup, because (if I remember right) the DevTools connection package wasn't written in ESM and was causing bundling de-opts.  That's currently in [`devtoolsExtension.ts`](https://github.com/reduxjs/redux-toolkit/blob/5fa0d4a3a7b2106fab56b5b489f4e8609d68fe61/packages/toolkit/src/devtoolsExtension.ts).

Perhaps we could switch back to having this as an external dep now that the extension and package are being actively maintained again.

@Methuselah96 , thoughts?

**Comment by Methuselah96** [comment]
Yeah, that sounds good to me. I plan on making some improvements to those types in the future so I think it would be good to not have the effort duplicated. I just released `@redux-devtools/extension@3.0.0-rc.1` with the new config changes.

**Comment by markerikson** [comment]
Seems like this would technically be a breaking change to RTK?

Technically we just pass through whatever options are supplied into the extension itself, so the _runtime_ behavior wouldn't change, but the type of the options would be very different here.

**Comment by Methuselah96** [comment]
I'm pretty sure the only changes to the types are that `actionsBlacklist` and `actionsWhitelist` are now deprecated. We didn't actually remove the types for those options they're just annotated as deprecated, so I'm not sure it's technically a breaking change.

**Comment by bdbvb** [comment]
Can this be fixed by at least adding the new options actionsAllowlist and actionsDenylist?

It currently throws a warning in the browser console, which kind-of ugly.

Only workaround I know of is to cast the devTools value to "any", which is a code smell.

**Comment by markerikson** [comment]
Yeah, if there's some changes that would help here, please file a PR!

**Comment by markerikson** [comment]
This actually bit me in Replay recently.  We should do this in the near future.
