### ISSUE TITLE
RTKQ - Question: How to call an endpoint without passing any arg to useQuery hooks?

### ISSUE THREAD

**Issue by Saad-Bashar** [reduxjs/redux-toolkit#1700]
This might be a very silly question but here I go, I have one endpoint that fetches all products. Where I do not need to pass any params. It looks like this 

```
endpoints: (builder) => ({
        getAllProducts: builder.query({
            query: () => `products`,
        }),
})
```
But when I want to use the hooks generated from it, it throws the error that I need to pass 1-2 arguments, 
![Screenshot 2021-11-06 at 11 08 28 PM](https://user-images.githubusercontent.com/13269141/140614379-c418342f-c786-4952-9898-28168ce65bb9.png)

I might be missing something but after searching a lot I could not figure out what to do in this case. Thanks a lot for any pointers.

**Comment by markerikson** [comment]
If you're using TS, you _must_ declare both the return type and the argument type as generics, like:

`getAllProducts: builder.query<SomeReturnType, SomeArgType({})`

If there are no arguments, use `void` for `SomeArgType`:

https://redux-toolkit.js.org/rtk-query/usage-with-typescript#typing-query-and-mutation-endpoints
