### ISSUE TITLE
Typed PayloadAction in builder.addCase() generates a typescript error

### ISSUE THREAD

**Issue by kevinmamaqi** [reduxjs/redux-toolkit#1707]
I have the following build.addCase():

```
builder.addCase(postAuthenticateUser.fulfilled, (state, action: PayloadAction<string>) => {
      console.log('action', action)
      //   window.localStorage.setItem('km-token', action.payload)
      //   state.token = action.payload
      state.isLoggedIn = true
      state.loginStatus = ReqStatus.SUCCESS
    })
```

But I get the following typescript error:

```
No overload matches this call.
  Overload 1 of 2, '(actionCreator: AsyncThunkFulfilledActionCreator<unknown, LoginInputs, {}>, reducer: CaseReducer<InitialStateI, PayloadAction<unknown, string, { ...; }, never>>): ActionReducerMapBuilder<...>', gave the following error.
    Argument of type '(state: WritableDraft<InitialStateI>, action: { payload: string; type: string; }) => void' is not assignable to parameter of type 'CaseReducer<InitialStateI, PayloadAction<unknown, string, { arg: LoginInputs; requestId: string; requestStatus: "fulfilled"; }, never>>'.
      Types of parameters 'action' and 'action' are incompatible.
        Type 'PayloadAction<unknown, string, { arg: LoginInputs; requestId: string; requestStatus: "fulfilled"; }, never>' is not assignable to type '{ payload: string; type: string; }'.
          Types of property 'payload' are incompatible.
            Type 'unknown' is not assignable to type 'string'.
  Overload 2 of 2, '(type: string, reducer: CaseReducer<InitialStateI, { payload: string; type: string; }>): ActionReducerMapBuilder<InitialStateI>', gave the following error.
    Argument of type 'AsyncThunkFulfilledActionCreator<unknown, LoginInputs, {}>' is not assignable to parameter of type 'string'.ts(2769)
```

Moreover the response is typed:

```
export const postAuthenticateUser = createAsyncThunk(
  'user/postAuthenticateUser',
  async ({ email, password }: LoginInputs, thunkAPI) => {
    try {
      const res = await axios.post<PostAuthenticateUserI>(process.env.REACT_APP_API_URL as string, {
        query: print(gqlAuthenticate),
        variables: {
          email,
          password,
        },
      })
      return res.data.data.authenticate.jwtToken
    } catch (err) {
      console.error(err)
      return thunkAPI.rejectWithValue(err)
    }
  }
)
```

Am I missing something? - Following the docs it seems to be correct, so why the error?

**Comment by phryneas** [comment]
Don't add an action type in the `.addCase`.

```
builder.addCase(postAuthenticateUser.fulfilled, (state, action) => {
```

The type from that comes from your `createAsyncThunk` call.

Yet, there is a bug in the current version of RTK where if you use `rejectWithValue`, the type for `createAsyncThunk` cannot be inferred correctly, so you need to either need to [type your createAsyncThunk](https://redux-toolkit.js.org/usage/usage-with-typescript#createasyncthunk) (which you should do anyways if you don't want your error to be `unknown`) or upgrade to the latest 1.7.0 beta.

**Comment by kevinmamaqi** [comment]
But I think I have it properly typed with Axios and the interface, see image below:

![Screenshot 2021-11-08 at 08 50 08](https://user-images.githubusercontent.com/972664/140703530-8b3d1a62-c441-4b67-ad55-87c5495462cf.png)

**Comment by phryneas** [comment]
`createAsyncThunk<I don't see any types here>(`

**Comment by swalahamani** [comment]
@phryneas Does the current latest version `v1.8.0` also require to [manually type ](https://redux-toolkit.js.org/usage/usage-with-typescript#createasyncthunk) the `createAsyncThunk` for correctly inferring `action.payload` type?

**Comment by phryneas** [comment]
@swalahamani `createAsyncThunk` does not need to be typed if all you have is the input type and the return type - those can be inferred. Any advanced use needs to be manually typed. That is a shortcoming of TypeScript, nothing we can do

**Comment by swalahamani** [comment]
Yes, I understand. But I missed one important detail. I was actually asking in the case of `rejectWithValue`. I'm getting the `thunkAction.fulfilled` `action.payload` types super cool.

**Comment by phryneas** [comment]
`rejectWithValue` cannot be inferred.
> Any advanced use needs to be manually typed. That is a shortcoming of TypeScript, nothing we can do

**Comment by swalahamani** [comment]
Got it, thanks 🙏
