### ISSUE TITLE
RTK Query - Error serializing undefined in getServerSideProps

### ISSUE THREAD

**Issue by elshanx** [reduxjs/redux-toolkit#1709]
as @phryneas asked, I reproduced the same error in [this repo](https://github.com/elshanx/rtkq-beta-ssr-error) with pokemon api

the problem occurs when dispatching a thunk in getServerSideProps without an argument like this `store.dispatch(getPokemon.initiate())`

but `store.dispatch(getPokemon.initiate(null))` works just fine

**Comment by phryneas** [comment]
Thank you!

**Comment by elshanx** [comment]
I noticed one other thing right now.
if I don't pass null just like I did here https://github.com/elshanx/rtkq-beta-ssr-error/blob/main/src/pages/index.tsx#L6 on line 6 the request is sent on the client-side
I'm almost sure about this as you can view in the browsers dev tools network tab.
and again, passing null as an argument seems to fix that issue.
hope this helps

**Comment by phryneas** [comment]
Does the problem generally go away with the build from #1711?

`yarn add @reduxjs/toolkit@https://pkg.csb.dev/reduxjs/redux-toolkit/commit/c43380ad/@reduxjs/toolkit/_pkg.tgz
`

**Comment by elshanx** [comment]
> Does the problem generally go away with the build from #1711?
> 
> `yarn add @reduxjs/toolkit@https://pkg.csb.dev/reduxjs/redux-toolkit/commit/c43380ad/@reduxjs/toolkit/_pkg.tgz `

That does fix the original issue.

> I noticed one other thing right now. if I don't pass null just like I did here https://github.com/elshanx/rtkq-beta-ssr-error/blob/main/src/pages/index.tsx#L6 on line 6 the request is sent on the client-side I'm almost sure about this as you can view in the browsers dev tools network tab. and again, passing null as an argument seems to fix that issue. hope this helps

Though this is still the same. if either one of the query or the thunk don't have the same exact argument it behaves differently i.e. fetching is (also?) done on the client-side. my guess would be because it couldn't find the argument's value/match (in the cache) and does a second request

That's not an issue for me, just a heads up

**Comment by phryneas** [comment]
Yes, the argument has to be the same with the only exception that  `useMyQuery()` is just short for `useMyQuery(undefined)`.

`useMyQuery(null)`, `useMyQuery(5)` and `useMyQuery({ foo: "bar" })` all will trigger other queries independently of `useMyQuery(undefined)`.

Endpoints are indexed by the serialized argument

**Comment by elshanx** [comment]
ah, that makes sense. I guess this issue can be closed now
