### ISSUE TITLE
Documentation Bug: Toggling language doesn't change file name

### ISSUE THREAD

**Issue by kothariji** [reduxjs/redux-toolkit#1724]
Link to the page - https://redux-toolkit.js.org/tutorials/quick-start

Here the file name is  **app/store.js**
![image](https://user-images.githubusercontent.com/60866749/141419160-4f3fd9da-0c65-4523-b3c1-0de7aa9e6e70.png)

#### But when I toggle from javascript to Typescript, then also the file name remains the same. ideally, it should change to 

```diff
- app/store.js
+app/store.ts
```
![image](https://user-images.githubusercontent.com/60866749/141419283-c07efdf5-a600-48c3-bf87-206404530f5f.png)

Please let me know if I can work on this issue

**Comment by phryneas** [comment]
I didn't even notice we had file names in there :sweat_smile: 

Sure, if you find a solution for that, that would be very welcome. But keep in mind that we also have multi-file examples like the second example in https://redux-toolkit.js.org/api/createAsyncThunk#examples that seem to face a similar inconsistency, just the other way round. Maybe there is a way to make them all more correct and beautiful?

**Comment by markerikson** [comment]
Yeah, if you can come up with a solution that'd be nice, but I really don't see this as a "bug".  And, based on the fact that those are applied at the Markdown level, I don't think there's anything we _can_ do about that.
