### ISSUE TITLE
[RTK Query] Clearing whole API for new user session

### ISSUE THREAD

**Issue by ayushsharma82** [reduxjs/redux-toolkit#1725]
Hi,

I'm using RTK Query in my React Native app and I would like to know if there is any way we can clear the whole API for new user session? What I'm trying to achieve is to reset all query hooks and mark them uninitialized. 

Please let me know if someone has found a way to do this. I'll mark this as a feature request for RTK query ( Feature: a reset function ). 

Thanks for the amazing library.

**Comment by Grapedge** [comment]
Is this what you need? [resetApiState](https://redux-toolkit.js.org/rtk-query/api/created-api/cache-management-utils#resetapistate)

**Comment by phryneas** [comment]
`resetApiState` alone will not reset the hooks, as the hooks are written to always keep the "last known state" in `data`. They have the `currentData` property in the `1.7` beta though, which would reset with that.

**Comment by ayushsharma82** [comment]
@phryneas  Thanks for the clarity on this topic! So should I try the 1.7@beta-1 release?

**Comment by markerikson** [comment]
@ayushsharma82 yes, please do! we'd appreciate any feedback on the new functionality overall.

**Comment by ayushsharma82** [comment]
One Question: Do we also mark them uninitialized with v1.7?

**Comment by phryneas** [comment]
Nope, not at this moment.

**Comment by ayushsharma82** [comment]
So I've tested v1.7.0@beta-1 with my app which is near to production. Everything seems to run smoothly and resetApiState seems to reset all data in the queries.

**Comment by ayushsharma82** [comment]
A function to reset all internal hooks like `isUnitialized`, `isSuccess` etc. would be a lot helpful as my placeholder components depend on it. Right now, data seems to be re-fetched after dispatching `resetApiState` but the internal hooks ( `is Uninitialized` etc ) break the loading state of the application.

**Comment by phryneas** [comment]
Yeah, I agree that using `resetApiState` should also reset the hooks. I'll see if I can find a quick fix. Would you be willing to do some testing with that?

**Comment by ayushsharma82** [comment]
Sure, I'll test your changes. Thanks for the effort.

**Comment by ayushsharma82** [comment]
Fixed with #1735

**Comment by bryantobing12** [comment]
is there a way to use `resetApiState` but only for certain endpoint, not the whole API?

**Comment by phryneas** [comment]
No, you can only rerun the query or stop using it.

**Comment by noahfaro** [comment]
I am curious as to why this is, given that the recommended style is to have one api with many endpoints while each of which could be handling very different types of data with different use cases. Would you mind elaborating on the reasoning behind this idea, or what the best approach is to navigating this issue?

For context, I have a `createSlice` whose state gets changed on a specific `createAsyncThunk` action, and this action also needs to invalidate the cache of a specific endpoint on a `createApi` (as the `createAsyncThunk` action ends up mutating the data that is pulled from the endpoint in my `createApi` slice).

**Comment by phryneas** [comment]
@noahfaro Because the job of RTK Query is to give you an easily accessible copy of data on the server.  
If your components don't need it any more, it will be automatically removed from the cache. You as a user should not care about clearing out that data at all - except for some scenarios like logging out (where you would usually clear the whole cache) or between tests (where you also clear the whole cache).

Clearing out data that is currently being displayed will just result in it being immediately re-fetched from the server - and if you want to do that, you can just as well use the `invalidateTags` functionality, which is meant for that.

If you have data that is not displayed and you want to remove it from the cache, that also works by just invalidating it - if a cache entry is not in use, it will just be removed from the cache instead of being refeteched.

**Comment by bryanltobing** [comment]
> except for some scenarios like logging out (where you would usually clear the whole cache) or between tests (where you also clear the whole cache).

I have many rtk query api's and currently implementing logout functinoality in react native, does that mean i have to call [resetApiState](https://redux-toolkit.js.org/rtk-query/api/created-api/cache-management-utils#resetapistate) for all of my api's?

like this

```ts
dispatch(userApi.util.resetApiState())
dispatch(postApi.util.resetApiState())
dispatch(notificationApi.util.resetApiState())
dispatch(transactionApi.util.resetApiState())
dispatch(othersApi.util.resetApiState())
...
```

Or is there a way to clear the whole cache by calling only one function for new user session?

**Comment by markerikson** [comment]
@bryanltobing : the first issue is that you _shouldn't_ have "many different RTK Query APIs" in one app, except in very rare cases. You should normally _only_ have one `createApi` call:

https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics#defining-an-api-slice

**Comment by bryanltobing** [comment]
hmm, I don't get it. so I have been wrong this all time. In my app, I have many features. if I only put it in one createApi call it's going to be a thousand lines of code. or if that is the case that I will move it to a different file, how do i get type safety.

My project structure is something like this

```bash
services/account/api.ts
services/user/api.ts
services/post/api.ts
```

every api.ts will have code that look like this

```ts
// post/api.ts

const reducerPath = 'postApi';

export const postApi = createApi({
  reducerPath: reducerPath,
  baseQuery,
  tagTypes: ['Posts'],
  endpoints: (builder) => ({
    getPosts: builder.query<Product[], void>({
      query: () => `/posts`,
      providesTags: ['Posts'], 
    }),
     // I will have other endpoints here, for other query or mutations related to post service/feature
  }),
});

export const { useGetPostsQuery } = postAPI;
export const postQueryReducer = { [reducerPath]: postAPI.reducer };
```

```ts
// user/api.ts

const reducerPath = 'userApi';

export const userApi = createApi({
  reducerPath: reducerPath,
  baseQuery,
  tagTypes: ['Users'],
  endpoints: (builder) => ({
    getPosts: builder.query<User[], void>({
      query: () => `/users`,
      providesTags: ['Users'], 
    }),
    // I will have other endpoints here, for other query or mutations related to user service/feature
  }),
});

export const { useGetUsersQuery } = postAPI;
export const userQueryReducer = { [reducerPath]: userAPI.reducer };
```

and then i will add all api that i defined to `configureStore`

```ts
export default configureStore({
  reducer: {
    ...postrQueryReducer,
    ...userQueryReducer,
  },
  middleware: getDefaultMiddleware =>
    getDefaultMiddleware().concat(apiSlice.middleware)
})

```

And if i want to implement logout for new user session. I need to call resetState for every api's i have
like this

```
const handleLogout = () => {
    dispatch(postApi.util.resetApiState())
    dispatch(userApi.util.resetApiState())
    navigate("SplashScreen")
}
```

is the structure I'm using not the right way to use rtk query?

**Comment by markerikson** [comment]
@bryanltobing : **no, it's _not_ how we want you using RTKQ!**

As I said, you _should_ only have **_one_** `createApi` call in your app, unless you're dealing with _completely_ different sets of servers and data fetching requirements.

Yes, as a default, we _would_ recommend putting all the endpoints in that one file.

_If_ you need to split them across multiple files, you can do that using `api.injectEndpoints`:

- https://redux.js.org/tutorials/essentials/part-8-rtk-query-advanced#injecting-endpoints
- https://redux-toolkit.js.org/rtk-query/usage/code-splitting

**Comment by erikmartinessanches** [comment]
How do I remove all data when a user logs out? `dispatch(userApi.util.resetApiState())` does not cut it and the data is still present in redux store.

**Comment by phryneas** [comment]
> Ok, I see the data inside the api object in the store is actually removed. I wanted to remove everything from redux store and have it empty (or set to initialState in the slices), is that advisable with RTK Query or not?

That just doesn't have anything to do with RTK Query. You should reset your RTK Query API slice with that dispatch you did there, as that also resets internal api state that is not in your Redux store.  
You can reset your full Redux store independently of that, after that. See for example this old [StackOverflow answer](https://stackoverflow.com/questions/35622588/how-to-reset-the-state-of-a-redux-store/35641992#35641992)

**Comment by n-ii-ma** [comment]
> > Ok, I see the data inside the api object in the store is actually removed. I wanted to remove everything from redux store and have it empty (or set to initialState in the slices), is that advisable with RTK Query or not?
> 
> That just doesn't have anything to do with RTK Query. You should reset your RTK Query API slice with that dispatch you did there, as that also resets internal api state that is not in your Redux store. You can reset your full Redux store independently of that, after that. See for example this old [StackOverflow answer](https://stackoverflow.com/questions/35622588/how-to-reset-the-state-of-a-redux-store/35641992#35641992)

Is there any way to clear the RTK Query cache inside the reducer?

I'm currently clearing the store in this way with one central `logout` action:

### In `authSlice.ts`:
```
// Logout user and reset state
export const logout = createAction("auth/logout");
```

### In `store.ts`:
```
// Root reducer (resettable)
const rootReducer = (
  state: ReturnType<typeof appReducer> | undefined,
  action: AnyAction
) => {
  // If the `logout` action is dispatched, clean the `Redux Persist` storage and reset the state
  if (action.type === "auth/logout") {
    storage.removeItem("persist:root");

    return appReducer(undefined, action);
  }

  return appReducer(state, action);
};
```

Is there any clean way of dispatching `resetApiState` (preferably in store) when the `logout` action is dispatched?

**Comment by HHK1** [comment]
> @bryanltobing : **no, it's _not_ how we want you using RTKQ!**
> 
> As I said, you _should_ only have **_one_** `createApi` call in your app, unless you're dealing with _completely_ different sets of servers and data fetching requirements.

Sorry for bumping this old thread, but I assume other people may run into it and may have the same question:

It's clear that the recommended way to use RTKQ is to use a single `createApi`. I missed that part of the documentation and ended up combining several apis in the root reducer. My question is: why is it bad? I feel like I'm missing something.

**Comment by markerikson** [comment]
@HHK1 : multiple reasons:

- Each RTKQ middleware adds additional layers to the `dispatch` call stack that run on _every_ dispatched action. If you add more API slices, that's more overhead for _every_ action, eating up CPU performance
- API slices can only do invalidation inside of themselves.  So, you can't have a mutation in API slice B that invalidates a query tag in API slice A
- Given that API slices can have endpoints injected, there's no technical _need_ to have multiple slices in most cases
