### ISSUE TITLE
v2.0 Request: Change from AnyAction to UnknownAction for `createSlice`

### ISSUE THREAD

**Issue by mq2thez** [reduxjs/redux-toolkit#1727]
Hey folks,

This is a followup to [this](https://twitter.com/sangster/status/1454563925480116225) Twitter thread, where @markerikson was soliciting requests for breaking changes in v2.0.

As mentioned in the thread, one of the things that was a repeated problem for Etsy devs as we began to adopt both RTK and TS was that the default type for an action in the "Map Object" notation is `AnyAction`. We generally encountered this when using the `createSlice` API.

The problem in this case is that for folks who are migrating JS files to TS files, it was easy to forget to add types to the `action` -- or to not know that it was necessary. This was also true for our folks who were just starting to learn how to use Redux Toolkit, as our previous "best practices" didn't have good typing options (a big factor in why we are migrating!).

[Per request](https://twitter.com/phry/status/1454751609842458625) by @phryneas, I created what I believe to be a test repo demonstrating the problem:
https://github.com/mq2thez/rtk-action-types

In general, I would love for there to be a preference for `unknown` (or `void`, which appears to be how `createAction` works) instead of `any` when working with `SliceCaseReducers`.

**Comment by markerikson** [comment]
Pretty sure we've got this in as of 2.0-beta.0:

- https://github.com/reduxjs/redux-toolkit/releases/tag/v2.0.0-beta.0
