### ISSUE TITLE
Testing mutation auto-generated hook with Jest

### ISSUE THREAD

**Issue by bad-encoder** [reduxjs/redux-toolkit#1739]
Sorry for the simple questions, but I could not find any documentation on this subject, what is the basic approach to testing components that use RTKQ?  what is the correct approach to mocking auto-generated hooks, or do they not need to be mocked? 
if i try mock hook like this:

`jest.mock('../api', () => ({
  useLoginMutation: jest.fn(),
}))
`

 there are some errors linked with store configuration:

```
[TypeError: Cannot read properties of undefined (reading 'reducerPath')

      12 |     user: userSlice.reducer,
    > 13 |     [loginApi.reducerPath]: loginApi.reducer,
         |                    ^
      14 |   },
](url)
```
I would be very grateful if you could clarify the situation with rtkq testing a bit,

**Comment by phryneas** [comment]
Use your real store and mock your network using something like https://github.com/mswjs/msw. Only then you can be sure that your application actually works.

**Comment by bad-encoder** [comment]
I don't need to mock the hook, only server?
And if I use a custom query fn and async sdk methods(react native firebase)? 
Maybe I need to read how msw actually works

**Comment by phryneas** [comment]
That sdk will at some point also send a request to the server and you can mock that with msw then. Or mock your sdk.

**Comment by arthedza** [comment]
@bad-encoder Hi! Have you managed to mock it?

**Comment by arthedza** [comment]
Have the same issue: https://github.com/reduxjs/redux-toolkit/issues/2478
