### ISSUE TITLE
How to use RTK with an already existent API layer of abstraction?

### ISSUE THREAD

**Issue by uriannrima** [reduxjs/redux-toolkit#1746]
I'm having a bit of doubt while trying to use RTK-Query with some already existing solution in a code base that I work.

So, we already use Redux with Redux Thunks on simple cases (the majority that I wish to replace with RTKQ) and some edge cases that were solved using Epics and RxJs (which so far I don't know if I'll be able to solve with RTKQ, but OK), and when I want to consume some endpoint from our backend, I use an object that exposes methods for each REST operation that we want to use:

e.g.:

```js
const postsService = {
  async getPosts() { /** Some async method that uses axios to consume our API*/ },
  async createPost(post) { /** Some async method that uses axios to consume our API */ },
};
```

Considering that the fetchBaseQuery uses fetch to consume the backend, and I need to keep using this "service" object to comunicate with my backend, what would be the best way to approach this situation to integrate the RTKQ?

I've been thinking about creating a baseQuery that uses functions that returns promises (async functions), to handle the "common" case (trycatch, transform response to json, etc), but don't know if I'm approaching it in the wrong way. Something like this:

```js
const asyncThunkQuery = async (asyncFn) => {
    try {
        const response = await asyncFn();
        const data = await response.json();
        return { data };
    } catch (error) {
        return { error }
    }
};

// Later on

const api = createApi({
    endpoints: builder => ({
        getPosts: builder.query({
            query: () => () => postsService.getPosts()
        })
    })
})
```

Would there be a better way?

**Comment by markerikson** [comment]
Close, but you probably want to use the `queryFn` option to provide your own fetching function.  `queryFn` lets you do any async work you want, and return a `{data}` object with the result:

https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#customizing-queries-with-queryfn

This would bypass `fetchBaseQuery` entirely for those endpoints, but given that you already have something that works that should be fine.

**Comment by uriannrima** [comment]
Oh great! I've seen from the documentation that baseQuery is mandatory for the createApi, if I'm going to use queryFn in the majority (maybe all) of the endpoints, giving to it some "noop" should give no trouble, right?

Thanks for answering so quickly @markerikson! Loving RTKQ so far. (Giving a training today in our company explaining how to use it)

**Comment by phryneas** [comment]
You can use `fakeBaseQuery` for that case, which will just throw an error if you accidentally use a `query` instead of `queryFn`

**Comment by uriannrima** [comment]
Great! Didn't knew that one @phryneas.

Don't know if I may ask something a bit unrelated here (to the abstraction topic) so please, if it is, tell me that I may open another issue or find another channel to make such question.

Most of our components are like dumb components that has some sort of data container (HOC) that pass all the data through props... Would it be bad to create a HOC function to pass the important pieces from the hooks through props? Something like this:


```js
// JUST AN SMALL EXAPLE!
// Would have to check performance-wise the impact of it
function withHooks(useHooks) {
    return function (Component) {
        var WrappedComponent = function (props) {
            const hooks = useHooks(props);

            return <Component {...hooks} {...props} />;
        };

        WrappedComponent.displayName = `Wrapped(${Component.name})`;

        return WrappedComponent;
    };
}

// Create something like a connect function...
const withUser = withHooks(({ userId }) => {
    const { isLoading, data: user } = useGetUserByIdQuery(userId);
    const { isLoading: isShopLoading, data: shops } = useGetShopsByUserIdQuery(userId);

    return {
        isLoading,
        isShopLoading,
        user,
        shops,
    };
});

// Wrap an component
withUser(SomeComponent);

```

I know that the majority of people would rather be away from HOCs, but we really like to keep our presentation components as is, to help unit test it, and at the moment, avoid having to rewrite all of ours tests because we started using hooks.
