### ISSUE TITLE
Dev tools don't work in Chrome Incognito with security off

### ISSUE THREAD

**Issue by sarmad1995** [reduxjs/redux-toolkit#1747]
When i open chrome via 

```
open -n -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --user-data-dir="/tmp/chrome_dev_test" --disable-web-security

```
and download the dev tools extension.

It won't work.
<img width="498" height="500" alt="Screenshot 2021-11-16 at 1 25 26 PM" src="https://user-images.githubusercontent.com/38377482/141943784-0a818f81-ce56-4e65-ad8c-9d3edf3b7453.png">
Not sure if this is dev tools issue or redux toolkit, posted it here to get some help.
If i open this in normal chrome mode, then it does work.

**Comment by phryneas** [comment]
Definitely not a toolkit problem. If this is at all possible or disabled by some browser security functionality, I can't say. You might need to search the issues over in the Devtools repo.
