### ISSUE TITLE
Struck in Entity within Entity creation

### ISSUE THREAD

**Issue by Siva-Leo** [reduxjs/redux-toolkit#1757]
![image](https://user-images.githubusercontent.com/68079920/142974795-ef311657-c319-4a03-818b-b0d6e8b7e2f8.png)

How i achieve that with createSlice with entityAdaper

**Comment by markerikson** [comment]
This is a usage question, and really better suited for the Discussions section than an issue.

That said, this gist should give you a good idea of how this works. It's "just" a matter of nesting the data:

https://gist.github.com/markerikson/ad319fd7b04bd4eecdcfe7bf51dce7b1
