### ISSUE TITLE
Having the reducer named to be compatible with deeppatel234/react-context-devtool

### ISSUE THREAD

**Issue by TCMiranda** [reduxjs/redux-toolkit#1760]
Hey there!

This is a nice new lib/extension that fits very well with the approach we use on our company: https://github.com/deeppatel234/react-context-devtool
It patches contexts and reducers to provide dev-tools for multiple contexts.

But the way it works for reducers is that it needs the reducer function to be named.
Would that be an acceptable change to the redux-toolkit?

Maybe using the slice name.
If that would make sense, I would be happy to tweak that.
Thanks

**Comment by markerikson** [comment]
I'm not sure that anything explicitly needs to be added to RTK itself. Looking at the example, it seems like the "naming" is doing `reducer.displayName = 'something'`.  This seems like something that would be easy enough to do in your own code.

**Comment by phryneas** [comment]
You can always do something like 

```js
function named(name, reducer) {
  return ({
    [name](...args){ 
      return reducer(...args)
    } 
  })[name]
}

export default named('foo', slice.reducer)
```

though

**Comment by TCMiranda** [comment]
Thanks @phryneas Yes, we do something like that right now, but would be nice not having to do it manually.

I mean, createSlice({ }) has a `name` property already and returns `slice.reducer` which is the function I would like named.
I think it's feasible @markerikson 

It should be possible to make the `slice.reducer` function to have the `name` provided when calling createSlice.
One way looks to be using Object.defineProperty
![image](https://user-images.githubusercontent.com/10077439/143092559-0d21b9e4-e708-4896-9756-42b2ba87241c.png)

**Comment by phryneas** [comment]
`Object.defineProperty` does not work in all environments. The only way is creating a new function with the correct name, like I did above.

Tbh, this is a very niche use case for shipping another 50 bytes or so to all users.

**Comment by TCMiranda** [comment]
Yeah that makes sense. Maybe I can try some tweaks in the other way around, at https://github.com/deeppatel234/react-context-devtool instead

**Comment by markerikson** [comment]
Closing this as I think it's outside our scope.
