### ISSUE TITLE
React umd files under dist overwrites each other

### ISSUE THREAD

**Issue by Antignote** [reduxjs/redux-toolkit#1761]
Hi!

I had some problem with importing the umd version of RTK and RTK Query at the same time from a cdn.
Both files overwrites the global RTK object with this line in the bundled file: 
`(global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global.RTK = {}));`

This results in that the last file that is loaded will overwrite the first file.

Affected files:
* @reduxjs/toolkit/dist/rtk-query.umd.js
* @reduxjs/toolkit/dist/query/rtk-query-react.umd.js

The issue can be seen here: https://codepen.io/Antignote/pen/gOxJJGB

Is there any solution to this or is it a bug?

**Comment by markerikson** [comment]
That would be a bug with the build scripts - the other entry points need to be given a different UMD global variable name.

**Comment by Antignote** [comment]
Thanks for the fast response.

The case is that I'm currently working in a very large legacy code base that is (unfortunately) highly dependent on umd files atm.
We are working on a solution where we will move away from umd files, but that will take time.

Meanwhile I have a dirty workaround with this problem where I cache the global RTK object between the script imports and after the last import reassign window.RTK.

I'd be very happy if there's any chance that this could be patched when there's time and if the umd files could be kept in the future.

**Comment by markerikson** [comment]
This is honestly lower priority for me atm, but it'd be great if you could submit a PR to fix this. See `packages/toolkit/scripts/build.ts` for the build logic - it'd need to be updated to have a different global variable name in the Rollup config step for the RTKQ bundles.

**Comment by Antignote** [comment]
Fully understood! 

Thanks for the help. I'll look into it and see what I can come up width
