### ISSUE TITLE
Middlware limit register

### ISSUE THREAD

**Issue by italobarzola** [reduxjs/redux-toolkit#1766]
Hello, the middlewares have some registration limit, I have 38 and if I add more it throws an error
![Captura de pantalla (45)](https://user-images.githubusercontent.com/92461415/143260620-7c1031c1-5449-4552-bb5d-05182f4f722b.png)

**Comment by markerikson** [comment]
Um. _Why_ are you adding 38 middleware?

If those are all RTK Query APIs, then you're doing it wrong. You _should_ only have **_one_ RTKQ API slice per app**, unless these are truly entirely different servers that the app is talking to.

**Comment by italobarzola** [comment]
@markerikson 
Hello thanks for taking your time and responding.
Actually each application module contains its apiSlice, is there a way to be able to divide without affecting it?

**Comment by italobarzola** [comment]
Currently my apiSlice looks like this, and then I import each module with its respective apiSlice

![Captura de pantalla (47)](https://user-images.githubusercontent.com/92461415/143280785-fade4427-0321-475c-ae92-04a47d8f7b35.png)

**Comment by markerikson** [comment]
Depends on what you mean by an "application module".

You can still have a single API slice defined, but split up the endpoint definitions across multiple files and inject them into the one API slice object:

- https://redux-toolkit.js.org/rtk-query/usage/code-splitting

**Comment by markerikson** [comment]
Going to close this because it's really a usage question and I believe it's been answered.
