### ISSUE TITLE
Custom equality check for determining argument changes in useQuery from rtk-query/react

### ISSUE THREAD

**Issue by ksandin** [reduxjs/redux-toolkit#1768]
This issue is referring to how `stableArg` is determined in `buildHooks.ts`/`useQuerySubscription`: 

https://github.com/reduxjs/redux-toolkit/blob/2ff1fa4364ce0dfa82dbbd3187aa0c63e57d5582/packages/toolkit/src/query/react/buildHooks.ts#L508

# The problem
> In the examples below, `useQuery` is pseudo code to refer to an arbitrary query hook generated by [@reduxjs/toolkit/query/react](https://redux-toolkit.js.org/rtk-query/api/created-api/hooks).

The current implementation performs a shallow equality check to allow the hook consumer to pass in inline objects without having to manually memoize these:

```tsx
useQuery({foo: 123, bar: "baz"}) // This is stable
```

However, if the consumer wants to use a nested object, the shallow equality will not be able to understand that no change has been made:
```tsx
useQuery({nested: {foo: 123, bar: "baz"}}); // This is not stable
```

To work around this the consumer would have to manually memoize the query argument, which easily becomes very verbose in larger projects with lots of queries and views, requiring an extra statement per query.
```tsx
const stableArg = useMemo(() => ({nested: {foo: 123, bar: "baz"}}), []);
useQuery(stableArg);
```

# Suggested solution

I suggest to provide the option to use any kind of equality checking:

```tsx
useQuery({nested: {foo: 123, bar: "baz"}}, {equalsFn: deepEquals}); // This is stable
```

In the above example, `useQuery` would determine whether the argument has changed by calling the provided `deepEquals` function, instead of the default `shallowEquals` function.

Additionally, a central configuration could be provided, to modify the default equality checking function for all queries:
```tsx
createApi({
  baseQuery: ...,
  endpoints: ...,
  useQueryArgEqualsFn: deepEquals
})
```

**Comment by markerikson** [comment]
I'm pretty sure this is already fixed in 1.7.0-beta?

https://github.com/reduxjs/redux-toolkit/releases/tag/v1.7.0-beta.0

https://github.com/reduxjs/redux-toolkit/pull/1533

**Comment by ksandin** [comment]
@markerikson You are absolutely right! I just tried the beta and it works exactly as I would like it to! 

My bad, thanks a lot!

**Comment by markerikson** [comment]
no worries :) glad to hear it works!
