### ISSUE TITLE
Request cancel (Query/mutation)

### ISSUE THREAD

**Issue by rhercb** [reduxjs/redux-toolkit#1770]
Is there a way to cancel requests, both query or mutation? I can't seem to find answers on https://redux-toolkit.js.org/

Since there is a problem, that changing a state creates new request. But the problem is when a user changes state multiple times in a row, causing many new requests.

Maybe this is not a problem with canceling of request, but the way how it need to work around this type of behavior from users? (some kind of debounce method)

**Comment by phryneas** [comment]
Generally, if you use a mutation, you can call `.abort()` on the mutation result. For queries, you do not have that option if using the `useQuery` hook.

In practice, this does not really do a lot of useful things though: at that point in time, the request is already sent to the server and even if you cancel the request, almost all servers will still fully prepare the response (unless you are in a streaming scenario maybe).

You probably rather want to debounce here. Something like https://github.com/xnimorz/use-debounce#simple-values-debouncing might be a good fit:

```js
const [search, setSearch] = useState("")
const result = useMyQuery(useDebounce(search, 100));
```

**Comment by rhercb** [comment]
Yes, thank you for answer. I already managed to find a fitting solution with debounce. That reali is the best case for this situation.
