### ISSUE TITLE
Codegen - how to add tags to queries and mutations

### ISSUE THREAD

**Issue by dnperfors** [reduxjs/redux-toolkit#1781]
I am trying out the openapi codegen for RTK Query and I am wondering about how I can make sure tags are added to the generated queries and mutations? Without those tags, I can't invalidate the cache in order to let it refresh the data.

**Comment by phryneas** [comment]
You would use [`enhanceEndpoints`](https://redux-toolkit.js.org/rtk-query/api/created-api/code-splitting#enhanceendpoints) in a file that imports from the generated file and the use the exports from that new file.

**Comment by dnperfors** [comment]
Thanks that worked. Might be worth to mention in the documentation of the code-generation, because I completely missed it.

**Comment by Morriz** [comment]
Can we please get a decent example in the docs describing this? It is not clear at all...

**Comment by phryneas** [comment]
@Morriz the docs are open source, a PR is very welcome.

In the end:
* generatedFile.ts
* enhancedGeneratedFile.ts

```ts
import { api } from './generatedFile.ts'

export const enhancedApi = api.enhanceEndpoints(...)

export const { ...hooks.. } = enhancedApi
```

**Comment by Morriz** [comment]
Thanks. I meant the part that is actually enhancing endpoints with tags btw.

It would be verry helpful to find docs explaining such common use cases. But I feel inadequate for that myself right now in this phase

**Comment by Nautman** [comment]
Is there a neat way to re-export the hooks without having to name them manually? @phryneas 

Right now I am very happy when it automatically generates hooks in the code that my IDE can recognize.

**Comment by Nautman** [comment]
I managed to figure it out. I did not realize I had to enhance the API that was generated from OpenAPI, i.e. the `enhancedApi` within `user.ts` for example.

If I do that, then it works. I have a working example on codesandbox. https://codesandbox.io/s/nostalgic-currying-in0g0l?file=/src/store/enhancedApi.ts

Do you know if there is any way for me to re-export all the hooks without having to name them individually manually? I really love the fact that the code generator you have built can automatically generate around a couple of dozen hooks for me.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/28629647/173519064-427a4fa6-88e6-41b2-912d-8c60f318b665.png">

**Comment by savcic-milorad** [comment]
> @Morriz the docs are open source, a PR is very welcome.
> 
> In the end:
> 
> * generatedFile.ts
> * enhancedGeneratedFile.ts
> 
> ```ts
> import { api } from './generatedFile.ts'
> 
> export const enhancedApi = api.enhanceEndpoints(...)
> 
> export const { ...hooks.. } = enhancedApi
> ```

This introduces some errors on each new code generation as the api from the generatedFile.ts is not exported by default, to fix this it is required to manually edit the generated file. Furthermore the exported hooks need to be based on the enchancedApi and not on the injectedApi.

**Comment by ihor-romanchuk** [comment]
Actually, `api.enhanceEndpoints`, and `api.injectEndpoints` mutates the same api object instance. So it doesn't matter whether you export hooks from generated file or the file where you call `api.enhanceEndpoints`.

The root cause is that your bundler excludes the file where you call `enhanceEndpoints` method, because this file is not imported anywhere in your app ([Tree Shaking](https://webpack.js.org/guides/tree-shaking/)).

The easiest solution would be to import this file, let's say in the `App.tsx`:
```
import './api/enhancedGeneratedFile';
```
And you can use all hooks exported from the generated file.

**Comment by phryneas** [comment]
@ihor-romanchuk Yes, but still we recommend using the injected/enhanced version, as that has all the most up-to-date types, and 100% ensures that everything has been imported without workarounds someone could forget about.

**Comment by wgpsutherland** [comment]
> This introduces some errors on each new code generation as the api from the generatedFile.ts is not exported by default, to fix this it is required to manually edit the generated file.

@savcic-milorad this does not seem to be the case anymore - I am using `@reduxjs/toolkit: 1.9.3` & `@rtk-query/codegen-openapi: 1.0.0` and my generated file contains the below, so your generated api is exported to use elsewhere without editing the file :)
``` typescript
export { injectedRtkApi as myApiName };
```
