### ISSUE TITLE
RTQK: Automatic re-auth - multiple requests

### ISSUE THREAD

**Issue by cmtmc** [reduxjs/redux-toolkit#1782]
Hi guys and thanks for the toolkit.

"Automatic re-authorization by extending fetchBaseQuery" from [customizing queries](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries) is pretty nice. But suppose we run several queries at once - all of them return 401, first reauth disables old refresh token on server - and all rest queries fail to reauth. What is the recommended way for such case?

Using axios, we can use its response interceptor - setInterval for all other queries after first (which does re-auth) and re-call them when re-auth is completed ([here](https://stackoverflow.com/questions/60941326/how-to-handle-jwt-refresh-token-on-client-side-with-multiple-requests-api-call) and [here](https://stackoverflow.com/questions/60749813/how-to-avoid-multiple-token-refresh-requests-when-making-simultaneous-api-reques)). Do I need to make Axios baseQuery​ (as setInterval needs promises to work with async)- or it is a typical thing with an easy solution?

Thanks!

**Comment by phryneas** [comment]
You can always add a [Mutex](https://blog.mayflower.de/6369-javascript-mutex-synchronizing-async-operations.html)

**Comment by andrew-moiseyev** [comment]
Thanks a lot, I've used [async-mutex](https://github.com/DirtyHairy/async-mutex) - and it seems to work fine now.

**Comment by andrew-moiseyev** [comment]
Thanks, using [async-mutex](https://github.com/DirtyHairy/async-mutex) :

```
const mutex = new Mutex();

const baseQueryWithReauth = async (args, api, extraOptions) => {
  let result = await baseQuery(args, api, extraOptions);

  if (result.error && result.error.status === 401) {
    if (!mutex.isLocked()) {
      const release = await mutex.acquire();

      try {
        const refreshResult = await baseQuery(
          {
            url: 'auth/refresh/',
            method: 'POST',
            body: { getToken(), getRefreshToken() },
          },
          api,
          extraOptions,
        );

        if (refreshResult.data) {
          api.dispatch(tokenUpdated(refreshResult.data));

          // retry the initial query
          result = await baseQuery(args, api, extraOptions);
        } else {
          api.dispatch(logout());
        }
      } finally {
        release();
      }
    } else {
      await mutex.waitForUnlock();
      result = await baseQuery(args, api, extraOptions);
    }
  }

  return result;
};

const baseApi = createApi({
  baseQuery: baseQueryWithReauth,
  endpoints: () => ({}),
});
```

Maybe append this to docs/FAQ?

**Comment by phryneas** [comment]
I think it might even make sense to wait with new requests if a reauth is going on:

```diff
const mutex = new Mutex();

const baseQueryWithReauth = async (args, api, extraOptions) => {
+ await mutex.waitForUnlock();
  let result = await baseQuery(args, api, extraOptions);

  if (result.error && result.error.status === 401) {
    if (!mutex.isLocked()) {
      const release = await mutex.acquire();

      try {
        const refreshResult = await baseQuery(
          {
            url: 'auth/refresh/',
            method: 'POST',
            body: { getToken(), getRefreshToken() },
          },
          api,
          extraOptions,
        );

        if (refreshResult.data) {
          api.dispatch(tokenUpdated(refreshResult.data));

          // retry the initial query
          result = await baseQuery(args, api, extraOptions);
        } else {
          api.dispatch(logout());
        }
      } finally {
        release();
      }
    } else {
      await mutex.waitForUnlock();
      result = await baseQuery(args, api, extraOptions);
    }
  }

  return result;
};

const baseApi = createApi({
  baseQuery: baseQueryWithReauth,
  endpoints: () => ({}),
});
```

could you try that and report back?

Generally, yes, we should add that somewhere as an example. Would you do a docs PR for that? 
Maybe below the basic reauth pattern in the docs?

**Comment by DeniKucevic** [comment]
I see this is not added yet in docs so I took time to do it 😅

https://github.com/reduxjs/redux-toolkit/pull/1947

**Comment by Remco4EF** [comment]
Just tried this approach. Seems Ok for my purpose but I have a question: 
first we do
`let result = await baseQuery(args, api, extraOptions);` to do the actual (original) request.
Later, if we do not have a locked mutex, we replay the original request again. 
Why?

**Comment by Remco4EF** [comment]
ah... now it makes sense. Thanks! Was focussing on the not-authenticated use case, not the phase we're authenticated again.

**Comment by tom3rr** [comment]
Hi there,

I am having trouble implementing this automatic re-auth logic with the axios base request example. Could someone point me in the right direction on what to look out for?

Thanks!

**Comment by gmonitoring** [comment]
> 

Hello, this is a question. baseQueryWithReauth do we use for all requests during which we need to be logged in? If so, does mutex.waitForUnlock() deprive us of asynchrony? Suppose when loading a page we request several queries in which the user must be authorized? Will it not turn out that they will be executed sequentially?

**Comment by tom3rr** [comment]
I don't seem to get why the initial request is tried again if the refresh fails. And a refresh request is also tried again after that second fail, resulting in a total of 4 requests:  initial + refresh + initial + refresh. Does anybody else experience this?

**Comment by phryneas** [comment]
@aamir-webosmotic you can also write your own mutex? Always your choice.

**Comment by lindapaiste** [comment]
Just wanted to say thank you for adding this example to the docs, it is extremely helpful!

**Comment by beforedisappear** [comment]
In this implementation, after a long downtime, there will always be a 401. It is more rational to first check the state of tokens, update them if necessary, and then execute the main request, isn't it?

**Comment by phryneas** [comment]
@beforedisappear  You have no way of checking the state of the tokens without making a request to the server. The clock on the user's system could be off by years.

**Comment by vinayroy1** [comment]
@phryneas i am using mutex same as you suggested but the issue is. i am using access token in baseapi. and my refresh token dnt require access token . so if i am not passing any header to refreash token api call then its picking base api default expired access token. and thatswhy i am refreash token api failing . how to avoid that.

 prepareHeaders: async (headers, {getState}) => {
    const token = getAccessToken(getState() as RootState);

    if (token) {
      headers?.set('Authorization', `Bearer ${token}`);
    }
    if (!headers?.has('Content-Type')) {
      headers?.set('Content-Type', 'application/json');
    }
    return headers;
  },
});

const mutex = new Mutex();

const baseQueryWithReauth: BaseQueryFn<
  string | FetchArgs,
  unknown,
  FetchBaseQueryError
> = async (args, api, extraOptions) => {
  const userData = getUserData(api.getState() as RootState);
  console.log('refresh token', userData);
  await mutex.waitForUnlock();
  let result = await baseQuery(args, api, extraOptions);

  if (result.error && result.error.status === 401) {
    if (!mutex.isLocked()) {
      const release = await mutex.acquire();

      try {
        const refreshResult = await fetchBaseQuery({
          baseUrl: `${Config?.base_url}/trax/sso/auth/refresh`,
          method: 'POST',
          body: JSON.stringify({refreshToken: userData?.refreshToken}),
          timeout: 100000,
        });

        console.log('refreash result', refreshResult);

        if (refreshResult.data) {
          api.dispatch(storeAccessToken(refreshResult.data));

          // retry the initial query
          result = await baseQuery(args, api, extraOptions);
        } else {
          // api.dispatch(clearAuthData());
          //navigateAndReset(MainRoutes.LOGINSCREEN);
        }
      } finally {
        release();
      }
    } else {
      await mutex.waitForUnlock();
      result = await baseQuery(args, api, extraOptions);
    }
  }

  return result;
};

**Comment by konstantinLyang** [comment]
i have error:
```
Cannot access 'baseApi' before initialization
```
