### ISSUE TITLE
Codegen - Broken fs import on programmatic usage

### ISSUE THREAD

**Issue by makrandgupta** [reduxjs/redux-toolkit#1784]
Following the current docs, I have the following code

``` ts
// store/baseApi.ts
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const baseApi = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: '/' }),
  endpoints: () => ({}),
});

```
``` ts
// store/companyApi.ts
import { generateEndpoints } from '@rtk-query/codegen-openapi';

const company = await generateEndpoints({
  schemaFile: 'http://localhost:3049/v1-get-openapi',
  apiFile: './baseApi.ts',
  filterEndpoints: ['company', 'companies'],
  hooks: true,
});
```

Codegen for some reason cannot find the `fs` module which is very strange. 

```
Module not found: Can't resolve 'fs'

Import trace for requested module:
./src/services/api/companyApi.ts
./src/services/api/index.ts
./src/store/index.ts
./pages/_app.tsx

https://nextjs.org/docs/messages/module-not-found
```

Generating via npx works just fine. I dont think I'm missing anything but if I am, would be happy to help improve the docs so more people dont get stuck with this.

**Comment by phryneas** [comment]
Are you executing this in `node` or in a browser environment? In a browser, `fs` would not be present.

**Comment by makrandgupta** [comment]
It is in a browser environment indeed. The idea I had was to generate the api client at build time within the frontend

**Comment by makrandgupta** [comment]
Do you think it makes sense to call this out in the docs? It's such an obvious thing now that I know what the issue is but it didnt occur to me when I was trying it out

**Comment by phryneas** [comment]
Well, I honestly thought it was very obvious. It generates TypeScript code - what would you even do with that on the client? :thinking:

**Comment by floatrx** [comment]
Try use `.json` instead `.ts`
```json
{
  "schemaFile": "***",
  "apiFile": "./src/store/emptyApi.ts",
  "apiImport": "emptySplitApi",
  "outputFile": "./src/store/testApi.ts",
  "exportName": "testApi",
  "hooks": true
}
```

**Comment by makrandgupta** [comment]
> Well, I honestly thought it was very obvious. It generates TypeScript code - what would you even do with that on the client? 🤔

The idea is that I build a fresh client at the build stage within my CI. This way my FE always has the latest code available. Let me know if there's a better workflow I can adopt.

**Comment by phryneas** [comment]
But your CI should have `fs` available?
