### ISSUE TITLE
Error when providing redux store to react-typescript application

### ISSUE THREAD

**Issue by Fah22** [reduxjs/redux-toolkit#1789]
I have set up my react typescript application and went on to install redux toolkit + react-redux. Configured my store then went on to provide for it in my index.tsx only to get an error that reads: "JSX element class does not support attributes because it does not have a 'props' property."

```
`import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';
import { store } from './app/store';
import { Provider } from 'react-redux';


ReactDOM.render( 
  <React.StrictMode>
    <Provider store={store}>
       <App />
    </Provider>
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
`

```

I can't seem to figure out how to fix this. Kindly advise

**Comment by phryneas** [comment]
On first look that seems to be a completely random error caused by local configuration or some dependency, but not really related to anything Redux.

I don't really know it we can help with that.
