### ISSUE TITLE
transformResponse typings doesn't match arguments

### ISSUE THREAD

**Issue by LoiKos** [reduxjs/redux-toolkit#1790]
Hi, 

Using RTK Query and defining an api through `api.injectEndpoints` i tried to `transformResponse`  on query but i have a trouble with the third arguments typings.

```ts
const localizationApi = api.injectEndpoints({
 searchLocations: builder.query<
      Place[] | Country[] | (Place|Country)[],
      { searchTerms: string; type?: LocationType; placeType?: PlaceType }
    >({
      query: ({ searchTerms }) => ({
        url: ...,
        params: { input: searchTerms },
      }),
      transformResponse: (response: Place[] | Country[] | (Place|Country)[], meta, arg) => {
        console.log(arg)
        // trouble here with arg 
        return response as Place[] | Country[] | (Place|Country)[]
      },
    }),})
```

So when i look at the `console.log(arg)` i can see this object : 

<img width="1089" alt="Capture d’écran 2021-12-01 à 16 56 45" src="https://user-images.githubusercontent.com/9548473/144269953-bafb2101-295b-47b7-900a-9d0fc13fcc21.png">

but in editor (`vscode`) i see arg typed as follow : 

<img width="895" alt="Capture d’écran 2021-12-01 à 17 10 29" src="https://user-images.githubusercontent.com/9548473/144270330-e0c30131-c853-4c61-ba03-1fac666271de.png">

There should be a missing type around the args provide by user.

**Comment by captain-yossarian** [comment]
I can pick it up if somebody will provide me with start point

**Comment by LoiKos** [comment]
Sorry this issue miss this information. 
I'm currently using : redux-toolkit v1.7.0-beta.1
