### ISSUE TITLE
Codegen - Cannot export interface from generated files in index.ts

### ISSUE THREAD

**Issue by elton2048** [reduxjs/redux-toolkit#1793]
This issue should be arose when using transpilers for the codebase. 

In generated client, `index.ts` exports all classes can used, it also re-exports interfaces for type contexts. However when using transpilers like babel the types are being erased, as a result it cannot export as normal. To handle this case, keyword `type` can be added in ts file for such case.

```ts
// Original code
export { Configuration } from "./configuration"

// Modified code
export type { Configuration } from "./configuration"
```

The generator should handle this case to cater for different usage for the clients.

**Comment by phryneas** [comment]
I'm a bit irritated - there is no `index.ts` being generated at all (unless you called it that) - can you please give more context?

**Comment by elton2048** [comment]
oops sorry for that, I open issue for the wrong repo
