### ISSUE TITLE
Codegen:  Couldn't resolve parser "babylon" when output file has js/jsx extension

### ISSUE THREAD

**Issue by zoubingwu** [reduxjs/redux-toolkit#1795]
[Prettier renamed `babylon` parser to `babel` in 1.16 and remove the deprecated one in 2.0](https://prettier.io/blog/2020/03/21/2.0.0.html#:~:text=parser%3A%20babylon%20(renamed%20to%20babel%20in%20v1.16.0)), guess everyone is using ts as output so no one reported this issue?

Just change the `EXTENSION_TO_PARSER` will solve the issue,  but seems it only generates ts code (with type annotations it still throws error when trying to prettify it with babel parser), not sure why it should have this paser map.

```diff
const EXTENSION_TO_PARSER = {
    ts: 'typescript',
    tsx: 'typescript',
-   js: 'babylon',
+   js: 'babel',
-   jsx 'babylon',
+   jsx: 'babel',
    'js.flow': 'flow',
    flow: 'flow',
    gql: 'graphql',
    graphql: 'graphql',
    css: 'postcss',
    scss: 'postcss',
    less: 'postcss',
    stylus: 'postcss',
    markdown: 'markdown',
    md: 'markdown',
    json: 'json',
};
```

**Comment by phryneas** [comment]
That should be pretty irrelevant - the codegen creates TypeScript, not JavaScript. You should not give the created files the extension js/x as that is just wrong.

**Comment by zoubingwu** [comment]
Yeah, I don't even realize that, just copied code from doc and trying to run it.

![image](https://user-images.githubusercontent.com/18644268/144392723-57e0a23a-3a11-4eba-adbf-edb8f0959dd5.png)

**Comment by zoubingwu** [comment]
@phryneas Hey I also run into a parsing error when testing this tool on an larger project:

![image](https://user-images.githubusercontent.com/18644268/144411599-b16d16c8-208d-4aaf-962e-d413f1134497.png)

This might related to prettier's ts parser not supporting some latest feature.  Is it possible to provide an option to skip the prettier process? Since normally we'll have a pre-commit hook to do that job.

**Comment by zoubingwu** [comment]
Hmm, found this is dependency issue, I had typescript v4.4.4 installed, downgrade to 4.3 solved it.

**Comment by phryneas** [comment]
I updated the file names in the docs to `.ts`, thanks for the catch. We might support down-transpilation to .js in the future, but right now it's not supported, so I'm going to close this issue.

As for the dependency issue: if you can create a reproduction for that, I'd like to take a look at it (but I'm swamped right now, so my feedback could take a while) - but please open a separate issue for that :)

**Comment by markerikson** [comment]
Should be live in https://github.com/reduxjs/redux-toolkit/releases/tag/%40rtk-query%2Fcodegen-openapi%402.0.0-alpha.0 ! Please try it out and let us know if it works.
