### ISSUE TITLE
Cannot perform 'get' on a proxy that has been revoked (When testing reducer with Jest)

### ISSUE THREAD

**Issue by maloguertin** [reduxjs/redux-toolkit#1798]
If you have a reducer that uses an util function and you wan't to mock and check the call of the function the test will break:

```js
const { reducer, actions } = createSlice({
  name: 'aSlice',
  reducers: {
    doSomething(state, action) {
      someUtilFunc(state, action.payload)
    }
  }
```

```js
test('reducer should call someUtilFunc with state and payload on action doSomething', () => {
  const myPayload = { name: 'foo' }
  
  const state = { name: 'bar' }
  
  reducer(state, actions.doSomething(myPayload))
  
  expect(someUtilFunc).toHaveBeenCalledWith(state, myPayload)
})
```

`expect(someUtilFunc).toHaveBeenCalledWith(state, myPayload)` this line will throw a `Cannot perform 'get' on a proxy that has been revoked` error.

I'm guessing this is because immerJs proxy is revoked when the reducer call is completed. I could pass `{...state}` to my `someUtilFunc` but this is impractical and I don't wan't my tests to influence my code.

**Comment by maloguertin** [comment]
I found a way around it, it's not the cleanest but it works, basically wrap your test in createNextState so that the proxy is not revoked. If anyone has a better suggestion I'd be glad to hear it.

Heres what I did: 

```js
test('reducer should call someUtilFunc with state and payload on action doSomething', () => {
  const state = { name: 'bar' }
  
  createNextState(state, state => {
    const myPayload = { name: 'foo' }
    reducer(state, actions.doSomething(myPayload))
    expect(someUtilFunc).toHaveBeenCalledWith(state, myPayload)
  }})
})

```

**Comment by Mikoz93** [comment]
Would it not be simpler/better to just test the output of the reducer instead of its implementation detail?

**Comment by markerikson** [comment]
Agreed. We specifically recommend testing reducers as:

````js
const actual = someReducer(exampleState, exampleAction);
expect(actual).toEqual(expected);
```

How it does that work internally should be irrelevant.

See https://redux.js.org/usage/writing-tests#reducers for examples.

**Comment by maloguertin** [comment]
> Would it not be simpler/better to just test the output of the reducer instead of its implementation detail?

> Agreed. We specifically recommend testing reducers as:
> 
> const actual = someReducer(exampleState, exampleAction);
> expect(actual).toEqual(expected);
> How it does that work internally should be irrelevant.
> 
> See https://redux.js.org/usage/writing-tests#reducers for examples.

Yes this is how I also prefer to test things, but if you have a behavior that is complex and reused in multiple reducers it is cumbersome to re-test something multiple times. I of course gave a super simple example for the issue here, but I think the main point is that if people want to test an implementation detail, it should be possible.

**Comment by markerikson** [comment]
This really isn't even an RTK issue specifically - it's about Immer only using proxies inside of `produce/createNextState`.

I don't think there's anything we can or should do here.

**Comment by maloguertin** [comment]
> This really isn't even an RTK issue specifically - it's about Immer only using proxies inside of produce/createNextState.
> 
> I don't think there's anything we can or should do here.

Sorry, I didn't mean that I didn't agree with you! I found a way to solve the problem anyways and it works pretty well. I just wanted to give some context on why I am testing with mocks in a reducer.

**Comment by N-pharmarack** [comment]
> > This really isn't even an RTK issue specifically - it's about Immer only using proxies inside of produce/createNextState.
> > I don't think there's anything we can or should do here.
> 
> Sorry, I didn't mean that I didn't agree with you! I found a way to solve the problem anyways and it works pretty well. I just wanted to give some context on why I am testing with mocks in a reducer.

Can you share your solution
