### ISSUE TITLE
retrieve data of another query when using onQueryStarted

### ISSUE THREAD

**Issue by connected-tcaceres** [reduxjs/redux-toolkit#1811]
Hello,
I was wondering if it was possible to retrieve the data of another query from within the onQueryStarted of a different query.

In the example below,
For my placeOrder endpoint, I would like to find the current 'item ids' in the cart, and then do a collection of API requests to delete each separate item.

getCartData: `[id: 1, id: 2, id: 3]`;
I would want placeOrder mutation to do 3 different API requests for each item. 
(I know the ask is weird - sorry, but if there was something similar to updateQueryData, such as getQueryData, this might work in my case)

e.g:
```js
export const restaurantApi = createApi({
    reducerPath: 'restaurantApi',
    baseQuery: axiosBaseQuery({ baseUrl: 'http://localhost:9001/' }),
    tagTypes: ['Cart'],
    endpoints: (builder) => ({
        getCart: builder.query({
            query: () => ({ url: 'cart', method: 'get' }),
            providesTags: ['Cart'],
        }),
        placeOrder: builder.mutation({
            queryFn: (arg, api, extraOptions, baseQuery) => {
                return { data: null };
            },
            onQueryStarted: async (
                _arg,
                { getState, queryFulfilled, getCacheEntry, dispatch, extra }
            ) => {
                // dispatch(restaurantApi.util.updateQueryData('getCart', undefined, (draft) => {}));
                // is there a getCartQueryData version of this - might solve the issue I'm having.
            },
        }),
    }),
});
```

**Comment by markerikson** [comment]
You have access to `getState` right there, so yes, you can read any data you want from the Redux store as usual.

**Comment by connected-tcaceres** [comment]
> 

Ah, perfect - thank you.
That works, I was able to access the data using:
`getState().restaurantApi.queries['getCart(undefined)'].data`

![Screen Shot 2021-12-07 at 5 42 23 PM](https://user-images.githubusercontent.com/42227095/145117259-7955cffa-5bfb-4cc1-acc4-c928fcb008f7.jpg)

**Comment by markerikson** [comment]
@connected-tcaceres also note you can simplify _that_ query specifically with:

```js
// no arg or `undefined` matches the default query arg value
const selectCartData = restaurantapi.endpoints.getCart.selector();
const queryContents = selectCartData(getState());
```

**Comment by connected-tcaceres** [comment]
> @connected-tcaceres also note you can simplify _that_ query specifically with:
> 
> ```js
> // no arg or `undefined` matches the default query arg value
> const selectCartData = restaurantapi.endpoints.getCart.selector();
> const queryContents = selectCartData(getState());
> ```

Did not know that was a thing, thank you so much. 👍 🙏 
Just started using RTK-query, and it's been a Godsend. Thank you for everything you do @markerikson
