### ISSUE TITLE
RTKQ: Stray subscription when performing query in getStaticProps causes refetch to occur on window focus

### ISSUE THREAD

**Issue by agusterodin** [reduxjs/redux-toolkit#1814]
For some reason my RTKQ appears to be subscribed to my "getAllSubscriptionDetails" query despite only using it in getStaticProps (no use of autogenerated hook whatsoever) and unsubscribing as shown in docs.

Running on Next 12.0.7 and RTK 1.7.0-rc.0.

```
export const getStaticProps = wrapper.getStaticProps(store => async () => {
  const result = store.dispatch(authSubscriptionApiEndpoints.getAllSubscriptionDetails.initiate())
  await Promise.all(authApi.util.getRunningOperationPromises())
  const allSubscriptionDetails = authSubscriptionApiEndpoints.getAllSubscriptionDetails.select()(store.getState()).data
  result.unsubscribe()
  if (!allSubscriptionDetails) throw new Error('couldn\'t fetch subscription details during build')
  const advancedSubscriptionDetails = allSubscriptionDetails.filter(subscription => subscription.name === SubscriptionPlan.Advanced)?.[0]
  if (!advancedSubscriptionDetails) throw new Error('couldn\'t find advanced subscription plan details in response during build')
  return { props: { subscriptionDetails: advancedSubscriptionDetails } }
})
```

Here is a devtools capture [state.json.zip](https://github.com/reduxjs/redux-toolkit/files/7678076/state.json.zip)

**Comment by phryneas** [comment]
The refetch only occurs on the client, right? I would assume you are using the hook there to use the data from the store and that hook creates a subscription?

Generally, subscriptions are not restored from the server to the client if you use the rehydration functionality.

**Comment by agusterodin** [comment]
Also side note: this code looks pretty complicated. Will there be convenience helpers for making SSR/SSG fetching a lot easier?

I love RTK query and realize how much boilerplate it reduces but in this particular scenario I can't help but think of this: https://twitter.com/dan_abramov/status/1191487232038883332. I mean this with no disrespect.

**Comment by agusterodin** [comment]
Yes, refetching is happening on client only. I am not using any hook whatsoever. Once I grab that data in getStaticProps I am feeding it directly into the component. This particular data fetch is strictly for grabbing data SSG during build-time.

**Comment by agusterodin** [comment]
In regards to my statement about potential helpers for ease of use: I have no issue understanding this code. I am strictly speaking for other people (other team members, people who are new to RTK query).

**Comment by phryneas** [comment]
Using that type of SSR, you will have pretty much the same code with React-Query or Apollo.  
The only alternative is actually fully rendering (including executing useEffect hooks) on the server, and Next is not built for that - as far as I know only some manual approaches do that.

**Comment by phryneas** [comment]
That apart, looking at your code, you are really making it more difficult for yourself with that "get data from the state and pass it in as props" instead of just using the hooks in the component then though.

This is how I would recommend doing it in SSR with Next: https://github.com/phryneas/ssr-experiments/blob/main/nextjs-blog/pages/pokemon/ssr/%5Bname%5D.tsx

**Comment by phryneas** [comment]
> Yes, refetching is happening on client only. I am not using any hook whatsoever. Once I grab that data in getStaticProps I am feeding it directly into the component. This particular data fetch is strictly for grabbing data SSG during build-time.

Are you rehydrating SSG Redux state on the client? If yes, how so?

**Comment by agusterodin** [comment]
> > Yes, refetching is happening on client only. I am not using any hook whatsoever. Once I grab that data in getStaticProps I am feeding it directly into the component. This particular data fetch is strictly for grabbing data SSG during build-time.
> 
> Are you rehydrating SSG Redux state on the client? If yes, how so?

I believe so (hopefully I didn't botch the setup),

```
import { AnyAction, combineReducers } from 'redux'
import { createRouterMiddleware, routerReducer } from 'connected-next-router'
import { HYDRATE, createWrapper } from 'next-redux-wrapper'
import { setAutoFreeze as setImmerAutoFreeze } from 'immer'
import { configureStore } from '@reduxjs/toolkit'
import { setupListeners } from '@reduxjs/toolkit/dist/query'
import { authApi } from 'carbon-lib-ui/authentication/api'

const rootReducer = combineReducers({
  router: routerReducer,
  [authApi.reducerPath]: authApi.reducer
})

const reducer = (state, action: AnyAction): ReturnType<typeof rootReducer> => {
  if (action.type === HYDRATE) {
    const nextState = {
      ...state,
      ...action.payload
    }
    if (typeof window !== 'undefined' && state?.router) {
      nextState.router = state.router
    }
    return nextState
  }
  else {
    return rootReducer(state, action)
  }
}

const routerMiddleware = createRouterMiddleware()

export const store = configureStore({
  reducer,
  middleware: getDefaultMiddleware => [...getDefaultMiddleware(), routerMiddleware, authApi.middleware],
  devTools: process.env.NODE_ENV === 'production' ? { shouldRecordChanges: false } : true
})

export const makeStore = () => {
  setupListeners(store.dispatch)
  return store
}

setImmerAutoFreeze(false)

// Types

export type Store = ReturnType<typeof makeStore>
export type State = ReturnType<typeof rootReducer>
export type Dispatch = typeof store.dispatch
export const wrapper = createWrapper<Store>(makeStore)
```

**Comment by phryneas** [comment]
That is actually the problem - you are rehydrating the full store, with everything in there. There is a specific rehydration helper that you should use for RTK-Q data.

https://github.com/phryneas/ssr-experiments/blob/c5ffbe904b4a9dfb93241dbad4032ae49c5d08be/nextjs-blog/lib/pokemonApi.ts#L8-L12

**Comment by phryneas** [comment]
And probably run
```diff
    }
-    return nextState
+    return rootReducer (nextState, action)
  }
  else {
    return rootReducer(state, action)
  }
}
```
because your current approach will swallow the hydration action.

**Comment by agusterodin** [comment]
Hell yeah, that did the trick.

Can't believe I forgot to add extractRehydrationInfo. I added it to one of my other projects when early testing your SSR implementation but forgot to add it to this project.

God bless!
