### ISSUE TITLE
action tracing problem with remote redux devtools

### ISSUE THREAD

**Issue by spirobel** [reduxjs/redux-toolkit#1815]
Because I am developing a chrome extension, I need to use the remote redux devtools, as mentioned in: 
https://github.com/reduxjs/redux-toolkit/issues/820#issuecomment-989199493
Sadly the action tracing does not work. The window just stays empty: https://imgur.com/eb47iWB
Also its kind of bothersome to pass in the actionCreators manually. Maybe redux-toolkit can help with that somehow.
Another issue is that I cant manually dispatch actions in the devtools. https://imgur.com/iA2zNp2 maybe it is related. 
thank you very much! <3
Spirobel

**Comment by markerikson** [comment]
These are really questions about the DevTools themselves, not RTK.  I see that you opened up an issue in the DevTools repo, so I'm going to go ahead and close this.

**Comment by spirobel** [comment]
If we get it to work, there would be the issue of passing the actionCreators to the remote redux devtools by redux RTK similar to what is being done with the normal redux devtools. But I guess I can open a new issue once we get there.

**Comment by markerikson** [comment]
I'm not familiar with what you mean by "passing action creators" here.  Can you point to an example of what you mean?

**Comment by spirobel** [comment]
Oh I just looked at the code: https://github.com/reduxjs/redux-toolkit/blob/cecda167c28ecf6e1c99f739ee33ab9ff9029680/packages/toolkit/src/configureStore.ts#L175 and saw that the actionCreators are not being passed. 
I got it from this example: https://github.com/zalmoxisus/redux-devtools-extension/commit/64717bb9b3534ff616d9db56c2be680627c7b09d  which was linked to here: https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Features/Trace.md so maybe it would also be an improvement for the "normal" redux devtools that get configured in configureStore to automatically pass the actionCreators. I just assumed that already happened. Thanks for your great work on the RTK toolkit by the way! It makes stuff a lot easier! <3

**Comment by markerikson** [comment]
I _think_ this is a misunderstanding of the options.  "Passing action creators" appears to be an entirely separate feature of the Redux DevTools that is unrelated to tracing actions - it's just that the one example you linked to is doing both at once:

https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actioncreators

**Comment by spirobel** [comment]
yes probably you are right. Most likely it's a cors issue in the redux devtools cli or in the remote redux devtools package https://imgur.com/a/BYzR0Nn every time I switch to the trace it shows this failed fetch in the devtools inspecting the redux devtools. So I am going to leave you alone here hihi :smile: 
Maybe look into automatically passing the actionCreators though, seems neat that they can be fired with one click from the redux devtools. 
But I recon it's probably harder to achieve than I thought, because it's just the reducers being passed to the `configureStore` redux toolkit API. And there are probably good reasons to not pass the slices directly, that you know better than I do hihi. 
Anyway, have a nice day! :+1:
