### ISSUE TITLE
Suggestion: RTK-Q - being able to access 'getState' from 'query'

### ISSUE THREAD

**Issue by connected-tcaceres** [reduxjs/redux-toolkit#1816]
Would it be possible to add the ability to access `getState` from  the query params in RTK-query.
(Note: I'm using Axios as my base query which is why it looks a bit different)

current:
```JS
getUser: builder.query({
    query: (_args) => ({ url: 'users' }),
});
```

suggestion (something like this):
```JS
getUser: builder.query({
    query: (_args, { getState }) => {
        const something = selectSomething(getState());
        return ({ url: `users/${something}`})
    },
});
```

**Comment by phryneas** [comment]
No this is a design choice. A query is currently only made if a new argument is provided - if you could access `getState` in there, some upstream state could change which means that actually the query would need to re-run, without us being able to detect that.

**Comment by phryneas** [comment]
@geekdaniels it is, as stated in my last comment very clearly discouraged to do so. If you need an escape hatch, use `queryFn` instead, but even then it will not circumvent the base problem: if state changes, there will not be a new request to the server.

**Comment by resetmerlin** [comment]
So rather than using getState() in query, pass it on to the parameter of query?

**Comment by EskiMojo14** [comment]
pass the *state* you depend on, not `getState`.

```ts
const arg = useSelector(selectMyArg);
const { data } = useMyQuery(arg);
```

**Comment by biganth** [comment]
Can we access state in transformResponse?

**Comment by phryneas** [comment]
@biganth no, as there is no way of ever reexecuting `transformResponse` if one of those other state values would ever change in the future. If you need them, you can add them to your query argument, or you fall back to `queryFn`, where you have state access but we don't guarantee for any data consistency since your code takes over.

**Comment by notaphplover** [comment]
@phryneas I feel this sort of confusing. I understand the reasoning for discouraging this approach of relying on the state. Having said that, aren't there any use cases to allow this? Considering [this example](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery), asuming my refresed access token is stored in the state (which is likely to happen reading the `tokenReceived` action), how should I access the refreshed access token in my second call? I'm probably missing something.

**Comment by phryneas** [comment]
@notaphplover prepareHeaders has store access, so if that doesn't solve the problem I might need more context.

**Comment by notaphplover** [comment]
> @notaphplover prepareHeaders has store access, so if that doesn't solve the problem I might need more context.

Hey @phryneas , oh, now I get it, so basically prepareHeaders might access the state and fetch the token.

After thoroughly thinking about it, I am not a huge fan of using prepareHeaders:

1. An HTTP API might get multiple authentication flows, some endpoints might need an API key in a header, some others might require a JWT bearer token and some others might not expect any authentication at all. prepareHeaders might not be suitable for this scenario.

2. If we follow the design choice of not providing getState at the query level, why should we provide it at prepareHeaders level? Some headers like Content-Type could mess with the cache. I am aware of Content-Type might not be the the best one to bring it to the argument 😄.

On the other hand, queryfn based solutions might access to the state so, isn't this design making the query approach a second class citizen?

Thank you so much for your quick response :)

**Comment by phryneas** [comment]
> An HTTP API might get multiple authentication flows, some endpoints might need an API key in a header, some others might require a JWT bearer token and some others might not expect any authentication at all. prepareHeaders might not be suitable for this scenario.

I'd say in such a case your API either has a design problem or you're actually talking with multiple (hopefully independent) APIs.

But yes, to a certain degree you can handle that with `prepareHeaders` - it gets a lot of information about the endpoint the request is being made for.

> If we follow the design choice of not providing getState at the query level, why should we provide it at prepareHeaders level? Some headers like Content-Type could mess with the cache. I am aware of Content-Type might not be the the best one to bring it to the argument 😄.

You have to get your token out of state (if you store it there) at some place. This at least enforces some level of best practice.

> On the other hand, queryfn based solutions might access to the state so, isn't this design making the query approach a second class citizen?

It makes `queryFn` a "you better know what you're doing or you'll shoot yourself in the foot" citizen/escape hatch.

**Comment by notaphplover** [comment]
Hey @phryneas :)

> But yes, to a certain degree you can handle that with prepareHeaders - it gets a lot of information about the endpoint the request is being made for.

I see, I didn't know that, ty for the insight.

> You have to get your token out of state (if you store it there) at some place. This at least enforces some level of best practice.

I see. It makes sense in most cases.

> It makes `queryFn` a "you better know what you're doing or you'll shoot yourself in the foot" citizen/escape hatch.

I think this is the degree of freedom I'm looking for, it would allow implementing reusable authentication flows that might be invoked by the `queryFn` of the affected endpoints. I prefer to avoid a `prepareHeaders` function to take this responsibility

I do appreciate your time :), it really helped me understand the current design motivation.
