### ISSUE TITLE
All autogenerated fields in REST response are optional

### ISSUE THREAD

**Issue by CameronJ26** [reduxjs/redux-toolkit#1822]
Not sure if this is a bug or a hidden configuration option, but all the fields on my autogenerated response type are set to optional. Don't see anything about this in existing issues or documentation.

**Comment by markerikson** [comment]
Can you show an example of what the original schema looks like, and ideally put together an example project showing this happening?

**Comment by CameronJ26** [comment]
Stupid mistake on my part, missed that swagger fields are optional by default 🤦‍♂️ 

https://stackoverflow.com/questions/40113049/how-to-specify-if-a-field-is-optional-or-required-in-openapi-swagger

**Comment by markerikson** [comment]
Haha, yes, you gotta add `required` to actually mark things that way.
