### ISSUE TITLE
× Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons

### ISSUE THREAD

**Issue by jetonk** [reduxjs/redux-toolkit#1824]
I'm trying to use `createApi` and import as a custom hook in a Component but immediately after I'm importing the slice it's throwing this error:
![Screenshot 2021-12-13 at 12 03 36](https://user-images.githubusercontent.com/10130015/145801433-d1aa8c0a-fb57-47dc-9eb7-fc5b3b8e506b.png)

****```mainApiSlice.js```****
```import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const apiSlice = createApi({
  reducerPath: "api",
  baseQuery: fetchBaseQuery({
    baseUrl: "https://reactnative.dev",
    prepareHeaders(headers) {
      return headers;
    },
  }),
  endpoints(builder) {
    return {
      fetchMovies: builder.query({
        query() {
          return `/movies.json`;
        },
      }),
    };
  },
});

export const { useFetchMoviesQuery } = apiSlice;
```
****```Main.js```****
```
import { useFetchMoviesQuery } from "./features/main/mainApiSlice";

function Main() {
  const { data, isFetching } = useFetchMoviesQuery();
  console.log("data", data);
  console.log("isFetching", isFetching);
.....

```

****```package.json```****

```
"dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.6",
    "@reduxjs/toolkit": "^1.6.2"
```

**Comment by markerikson** [comment]
As the error message says, this is really a React usage question. How are you using the `Main` component? Do any of the listed reasons in the error message apply here?

**Comment by jetonk** [comment]
I'm calling `Main` inside of `App.js`, I'm not sure if listed reasons apply here but what I did is: I wrote a custom hook and called it and it works perfectly, but when I try to create a slice using `createApi` it's breaking, anyway if listed reasons do not belong here even that in stack trace I see errors coming from redux toolkit libraries we can close this issue!

**Comment by agalligani** [comment]
I saw this because I got the same error and would like to comment that the error happened when I mistakenly had redux and react-redux both installed as well as the toolkit. IDK if this caused the posters error, but it may point the way towards understanding why it happened and maybe warnings can be added to the toolkit. My app works fine after I removed redux.

**Comment by markerikson** [comment]
@agalligani : hmm. that doesn't sound like it would be related.  You do need both React-Redux and either `redux` or `@reduxjs/toolkit` installed (and RTK includes `redux` automatically), and I wouldn't expect removing a redundant `redux` dependency to have any changes on React-related behavior.
