### ISSUE TITLE
ambiguous error: "path parameter id does not seem to be defined"

### ISSUE THREAD

**Issue by Richard87** [reduxjs/redux-toolkit#1825]
Could we add the current path to the error to help troubleshooting the error?, something like this:

```ts
throw new Error(`path parameter ${expression} does not seem to be defined for ${path}?`);
```

https://github.com/reduxjs/redux-toolkit/blob/4163a768eaf7a6d98b82d00ed6e50668f6d0e62e/packages/rtk-query-codegen-openapi/src/generate.ts#L416

**Comment by Richard87** [comment]
Also, if it could output a warning and skip the endpoint when something fails instead of bailing completley, that would be amazing!

Or, a "strict" property, that when set to false, could set the missing information as "any" instead of failing completley!

I really want to start using RTK Query+codegen in our app, but right now I don't know how to proceed to fix the error :/

**Comment by phryneas** [comment]
That error should not have any overlap with the codegen if you are using the new codegen?

**Comment by Richard87** [comment]
I'm not usre what you mean, I tried the codegen out today so I assume to have the latest version!

I seem to be running `1.0.0-alpha.1` which seems to be the latest version...

**Comment by phryneas** [comment]
Well, in the end you would have only one single `api` slice in your application and the codegen would not have anything to do with that - it would just inject endpoints into that one api slice. 

So I'm really not sure what a `path` would have to do with the codegen - you do that in the `createApi` call, outside of the codegen.

**Comment by phryneas** [comment]
Yeah, re-reading this, it seems reasonable. Could you file a PR? I'm not sure about skipping though. I think this should cause an unrecoverable error - ppl can still manually filter out the endpoint in the configfiles, but should not be able to just ignore this error.

**Comment by phryneas** [comment]
Going emails from top to bottom.. there is already a PR.. 😅  I'll take a look.

**Comment by Richard87** [comment]
Thanks for responding so fast!
