### ISSUE TITLE
RTKQ 1.7 build fails due to type definitions in dist being used instead of react

### ISSUE THREAD

**Issue by griffinodow** [reduxjs/redux-toolkit#1829]
Build fails due to type definitions when using 1.7 however succeeds when downgrading to 1.6.2. Included minimal project to reproduce type errors.

# Expected Behavior
Build succeeds with no errors

# Current Behavior
Build fails with error: `node_modules/@reduxjs/toolkit/dist/query/core/module.d.ts:100:183 - error TS2344: Type 'Definitions[EndpointName]' does not satisfy the constraint 'QueryDefinition<any, any, any, any, string>'`

# Temporary Workaround
Downgrade to 1.6.2

# Steps to Reproduce
Clone example project provided: https://github.com/griffinodow/rtk-query-1.7-build-bug

1. `npm install` dependencies
2. `npm run test` or run index.ts through tsc

**Comment by griffinodow** [comment]
While running a build through Vite for a project I'm working on I was able to observe this warning. Maybe it can be of help.
```
vite v2.7.2 building for production...
transforming...
Conflicting namespaces: "node_modules/@reduxjs/toolkit/dist/query/react/rtk-query-react.esm.js" re-exports "createApi" from both "node_modules/@reduxjs/toolkit/dist/query/react/rtk-query-react.esm.js" and "node_modules/@reduxjs/toolkit/dist/query/rtk-query.esm.js" (will be ignored)
```

**Comment by phryneas** [comment]
This seems to be TS 4.5 related, a patch is coming up in #1834.

**Comment by markerikson** [comment]
Should be fixed in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.7.1 .
