### ISSUE TITLE
IsUnknownOrNonInferrable results in ActionCreatorWithNonInferrablePayload when no index signature is present on payload object

### ISSUE THREAD

**Issue by DylanCulfogienis** [reduxjs/redux-toolkit#1835]
Environment Details:
- @babel/core: 7.12.3
- webpack: 4.44.2
- typescript: 4.1.2
- @reduxjs/toolkit: 1.7.0

Reproduction steps:

With a model defined as:

```ts
interface BazModel {
  a: string;
  b: number;
}

interface FooBarState {
  someState: BazModel;
}
```

And an action defined as such:

```ts
export const fooBarSlice = createSlice({
  name: 'fooBar',
  initialState,
  reducers: {
    setWorkingDashboard(state, action: PayloadAction<BazModel>) {
      state.someState = action.payload;
    },
  }
})
```

Any actions with payloads involving `BazModel` will be typed as `ActionCreatorWithNonInferrablePayload<string>`.

However, if the definition of `BazModel` is changed to:

```ts
interface BazModel {
  [key: string]: unknown;
  a: string;
  b: number;
}
```

Then the type will be correctly inferred as `ActionCreatorWithOptionalPayload<BazModel, string>`.

This seems either unintentional - i.e. `IsUnknownOrNonInferrable` is too sensitive and is triggering when it shouldn't be, or I've been defining my TypeScript interfaces incorrectly for a while now.

This is a problem because unless payload index signatures are defined, you lose typesafety when consuming action dispatches exported from a slice.

**Comment by phryneas** [comment]
I believe you might just have `strictNullChecks` or `strict` mode turned off in your `tsconfig.json`, could that be the case? We cannot support that since you are essentially dropping half of TypeScript's feature set with that.

**Comment by DylanCulfogienis** [comment]
Thanks for the quick response, I thought I was going insane for a second. `"strict": false` was indeed the problem, now I just need to figure out why it was set for this project...
