### ISSUE TITLE
1.7 version Type error: trigger Expected 1 arguments, but got 2.

### ISSUE THREAD

**Issue by wenzhang0220** [reduxjs/redux-toolkit#1837]
When the trigger function returned from a LazyQuery, it always initiates a new request to the server even if there is cached data. Set preferCacheValue(the second argument to the function) as true if you want it to use cache. 

but when we tried to pass the preferCacheValue into trigger function like:
`trigger(someArgument, true)
`
 and build it. it has the following error:

`Type error: Expected 1 arguments, but got 2.
`

**Comment by phryneas** [comment]
Did you update RTK to the latest version? (1.7.*)
