### ISSUE TITLE
RTKQ: Query is unsubscribed immediately after mounting in React 18 StrictMode

### ISSUE THREAD

**Issue by KurtGokhan** [reduxjs/redux-toolkit#1838]
I was doing some exploration in React 18 RC and noticed that RTK Query was causing endless loading screens in StrictMode only. I don't know if React 18 is supported yet, but thought this might be helpful.

This is how actions look in React 17 and non strict mode:

![image](https://user-images.githubusercontent.com/6034931/146396214-19da40bf-4d74-44e0-81e3-6828f75820c6.png)

This is how it looks in React 18 StrictMode:

![image](https://user-images.githubusercontent.com/6034931/146396349-06962057-85d8-432d-b45c-72eca984272d.png)

Two problems here.
1. For some reason the query unsubscribes. This can be a bug on React side. `useEffect` cleanup is called for no reason as if component is unmounted, even when the component is not unmounted. That causes RTKQ to unsubscribe.
2. Query doesn't (?) subscribe again and stays in loading indefinitely. This is non-deterministic, as sometimes it does finish loading. I think this is related to side effects in render.

Version: 1.7.1
[Sandbox link](https://codesandbox.io/s/blissful-brown-mpx3r?file=/src/index.tsx)

**Comment by KurtGokhan** [comment]
I see this was already discussed at reduxjs/react-redux#1732

My bad. Tried react-redux v8 beta. Seems to work. At least problem 2 does not happen.

Problem 1 still happens. But I guess it is a React behavior and nothing to do here. Issue can be closed as far as I am concerned.

**Comment by markerikson** [comment]
Yeah, the extra unmount is part of the new "Strict Effects" behavior as far as I know.

**Comment by phryneas** [comment]
@markerikson what does that do?

**Comment by KurtGokhan** [comment]
@phryneas  It is explained here: https://github.com/reactwg/react-18/discussions/19

> React intentionally double-invokes effects (mount -> unmount -> mount) for newly mounted components. (In strict mode)

I just learned about it.

**Comment by phryneas** [comment]
Interesting and kinda weird. Good to know, thanks!
