### ISSUE TITLE
Dependency cycle caused by `RootState` exported from `store.ts`

### ISSUE THREAD

**Issue by onosendi** [reduxjs/redux-toolkit#1849]
https://codesandbox.io/s/rtk-query-demo-lbp7n?from-embed=&file=/src/app/store.ts

In the example above there is a dependency cycle:
 
store.ts
```js
import { postApi } from './services/posts';
```

services/posts.ts
```js
import { RootState } from '../store';
```

Any way around this?

**Comment by markerikson** [comment]
This is a types-only cycle, so there's no actual problem here. TypeScript can handle that, because it's all resolved at compile time.  (It's also possible to end up with actual circular types dependencies, which is a different topic).

**Comment by onosendi** [comment]
Gotcha. How are you suppressing these errors in your editor?

**Comment by markerikson** [comment]
What are the "errors" you're seeing, specifically?

Usually when I see a report like this it's an ESLint rule that isn't able to distinguish between "imports of an actual JS variable" and "imports of a TS type".  Are you seeing an ESLint warning, a TS error, or something else?

**Comment by onosendi** [comment]
`1. Dependency cycle via ./store:2 [import/no-cycle]`

It's an eslint warning. `// eslint-disable-next-line import/no-cycle` works fine. I was just hoping there was a way to suppress types-only cycle dependencies. I don't see how it would be possible to tell eslint that, though.

**Comment by markerikson** [comment]
There may be a TS-based version of the rule, possibly, but I haven't looked at that myself.

**Comment by onosendi** [comment]
Thanks for your time. Much appreciated.
