### ISSUE TITLE
Property 'type' is missing in type 'AsyncThunkAction<TicketEntity[], void, {}>' but required in type 'AnyAction'. 

### ISSUE THREAD

**Issue by evgenoid** [reduxjs/redux-toolkit#1854]
TS2345: Argument of type 'AsyncThunkAction<TicketEntity[], void, {}>' is not assignable to parameter of type 'AnyAction'. Property 'type' is missing in type 'AsyncThunkAction<TicketEntity[], void, {}>' but required in type 'AnyAction'. 

`package.json`
```
"@reduxjs/toolkit": "1.7.1",
"react": "17.0.2",
"react-redux": "7.2.6",
```

`store.ts`
```
...
export const store = configureStore({
  reducer: {
    [EntityStoreName.Oem]: oemReducer,
    [EntityStoreName.Ccvs]: ccvsState.reducer,
    [EntityStoreName.CloudConnections]: cloudConnectionsState.reducer,
    [EntityStoreName.ChangeRequests]: changeRequestsState.reducer,
    [EntityStoreName.Locations]: locationsState.reducer,
    [EntityStoreName.Organizations]: organizationsReducer,
    [EntityStoreName.Tickets]: ticketsState.reducer,
    [EntityStoreName.TicketComments]: ticketCommentsState.reducer,
    [EntityStoreName.TicketAttachments]: ticketAttachmentsState.reducer,
    [StoreName.Session]: sessionReducer,
    [StoreName.Modal]: modalState.reducer,
  },
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      serializableCheck: {
        ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
      },
    }),
});

export const persistor = persistStore(store);

export type AppState = ReturnType<typeof store.getState>;
```

`repository.ts`
```
export const getTicketsList = createAsyncThunk(
  `${EntityStoreName.Tickets}/getList`,
  (_, { signal }): Promise<TicketEntity[]> => {
    const cancelToken = cancelationSubscribe(signal);

    return apiRequestCall<TicketEntity[]>({
      params: {
        method: 'GET',
        apiVersion: ApiVersion.V1,
        resource: ApiResource.Tickets,
        cancelToken,
      },
    });
  }
);
```

Type issue:
<img width="935" alt="Screen Shot 2021-12-21 at 12 45 45" src="https://user-images.githubusercontent.com/1290843/146917377-be4207dc-3519-4307-a434-976f9ec92143.png">

**Comment by phryneas** [comment]
Most likely you have two conflicting versions of `redux` somewhere in your `node_modules`. `4.0.x` and `4.1.x` are not compatible on a type level (and generally you should only have one redux version).
You can search those with `npm ls redux` or `yarn why redux`.

**Comment by evgenoid** [comment]
Ok. Thank you! Let's try...

**Comment by evgenoid** [comment]
Works! Thank you, @phryneas!

**Comment by phryneas** [comment]
@alissaVrk then you will need to get your dependencies in line - that is a problem of your package manager.

**Comment by alissaVrk** [comment]
@phryneas I forgot the "no".. sorry

it seems that it happens because of a typescript version:
it's fine with 4.5.5, but with 4.6.2 there is a problem

**Comment by phryneas** [comment]
@alissaVrk please share your `configureStore` call.

**Comment by phryneas** [comment]
There are some known problems at the moment when `preloadedState` is specified. Does the problem go away if you comment it out?

**Comment by alissaVrk** [comment]
nope
I'll try to recreate it a bit later in a simpler project

**Comment by alissaVrk** [comment]
ok, I have it, actually now it seems a slightly different error..
so maybe it should be a slightly different issue. anyway this is the code

the problem seems to be with the definition of dispatch in the thunkConfig

```
const store = configureStore({
  reducer: { },
});

type StoreType = typeof store;
type AppDispatch = StoreType['dispatch'];

type Config = {
  dispatch: AppDispatch;
};

const asyncActionFail = createAsyncThunk<any, void, Config>('prefix', () => {
  return Promise.resolve([]);
});

store.dispatch(asyncActionFail()); //this fails
```

the error is 
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'AsyncThunkAction<any, void, Config>' is not assignable to parameter of type 'AnyAction | ThunkAction<Promise<PayloadAction<any, string, { arg: void; requestId: string; requestStatus: "fulfilled"; }, never> | PayloadAction<unknown, string, { arg: void; requestId: string; requestStatus: "rejected"; aborted: boolean; condition: boolean; } & ({ ...; } | ({ ...; } & {})), SerializedError>> & { .....'.
      Type 'AsyncThunkAction<any, void, Config>' is not assignable to type 'ThunkAction<Promise<PayloadAction<any, string, { arg: void; requestId: string; requestStatus: "fulfilled"; }, never> | PayloadAction<unknown, string, { arg: void; requestId: string; requestStatus: "rejected"; aborted: boolean; condition: boolean; } & ({ ...; } | ({ ...; } & {})), SerializedError>> & { ...; }, any, u...'.
        Types of parameters 'dispatch' and 'dispatch' are incompatible.
          Type 'ThunkDispatch<any, undefined, AnyAction>' is not assignable to type 'Dispatch<AnyAction> & ThunkDispatch<any, null, AnyAction> & ThunkDispatch<any, undefined, AnyAction>'.
            Type 'ThunkDispatch<any, undefined, AnyAction>' is not assignable to type 'ThunkDispatch<any, null, AnyAction>'.
              Type 'undefined' is not assignable to type 'null'.
```

**Comment by alissaVrk** [comment]
on a side note, don't remember why I added the dispatch type there but if I remove it seems to work in both typescript versions.
but it is odd behavior still

**Comment by phryneas** [comment]
Huh, the default extra parameter it seems.

**Comment by phryneas** [comment]
@alissaVrk it doesn't seem to fail for me: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMYQHYDNgHMCuUCmAyjNPgDRxIECGM+AggM4CeqSAKgBY6oDWcAXzjooEEHADkAAQIATHAA8AVowD0JCABtewGBIBQ+lKkbxTpOAF5KaTLgLFSACgT64cOTiT4oALkSCZPoCAJQA3IYwzGD4cI4E7NGx1lExEOhw5gQRqbH0YGAAIsCMYLRInFZxJAlJANoSsiVlMBUSALoR+rlwAMK22FWu7k2l5Zz++UXN4xECXcamcNQsbPRIMMBoAGLUwJpVVPi0DKsc3HwAPNSozBQAbhDAshT9GNgAfE4SYASYChIKE4QlYPog3B58DA8Kg4AAFUQgEr4AB0BEYWnu+CcdXa4WC+P0WVRoxaFScK1YSHWmx2e00wPCcFU6k4JWE9MYQA

**Comment by alissaVrk** [comment]
sorry, I had 1.7.2 toolkit version, it's fixed in 1.8.0

**Comment by TulshiDas39** [comment]
I had same issue. It was problem with typing of @types/react-redux.  Now react-redux have its own type definition. I removed @types/react-redux and then worked perfectly.

**Comment by phryneas** [comment]
@flrnd please follow the [TypeScript QuickStart](https://redux-toolkit.js.org/tutorials/typescript) and define a typed `useAppSelector` hook.

**Comment by flrnd** [comment]
@phryneas  :facepalm: 

Thanks!

**Comment by david-mk-lawrence** [comment]
For me I had defined an AppThunkAction like

```typescript
export type AppThunkAction<R = void> = ThunkAction<R, RootState, never, Action>
```

and I kept getting the "Property 'type' is missing in type..." error when trying to dispatch. The problem turned out to be the `never`. I changed it to `unknown` instead and the error went away.

So now it looks like

```typescript
export type AppThunkAction<R = void> = ThunkAction<R, RootState, unknown, Action>
```

**Comment by arllan** [comment]
> const dispatch = useDispatch<AppDispatch>();

thank you so much for that, it helped a lot

**Comment by se-talha-juanid** [comment]
In my case it was because, I had middleware setup in application store but in tests I was not setting up the middleware.
