### ISSUE TITLE
Invalidate tags for another createApi

### ISSUE THREAD

**Issue by kmercer1** [reduxjs/redux-toolkit#1862]
Hello,

I have a use case where I would like to invalidate tags for another createApi instance. I saw this https://stackoverflow.com/questions/69243083/rtk-query-invalidate-cache-of-an-api-service-from-another-api-service, however, I am a bit more restricted (unless I am missing something).

Currently, we use RTK Query Codegen (https://github.com/rtk-incubator/rtk-query-codegen) to generate all the code for the endpoints, and our current structure has 4 different Swagger controllers, which result in 4 different createApi instances for us. All of which have their own baseUrl.

We have an instance where 1 controller/createApi is responsible for specific features, and when one of those endpoints are triggered, it needs to invalidate data on another controller/createApi. 

Being able to do tag invalidation across multiple controller/createApis would be great, if it could be supported. 

Currently, I'm thinking we may need to create a fake endpoint that invalidates tags, setup middleware to listen to certain actions between controllers, and dispatch new actions to trigger that fake endpoint. Maybe there is an easier way?

**Comment by msutkowski** [comment]
If I'm understanding you correctly... you can just use your own version of `api.util.invalidateTags` to do this. It's just a normal action, and the use case would look like this:

```ts
dispatch({
   type: `${reducerPath}/invalidateTags`,
   payload: ['SomeTag', 'AnotherTag'],
});
```

If you update to the newest codegen, I'd just recommend exporting the `reducerPath` from each one of the `baseApi`s.

**Comment by ChuckJonas** [comment]
I have a use case where we receive a web socket event and want to invalidate tags so the RTK will refresh those queries.  

I assume this is the best approach for that?

**Comment by phryneas** [comment]
@ChuckJonas you would just `dispatch(api.utils.invalidateTags(...))`?

**Comment by evgenijchul** [comment]
* api.**util**.invalidateTags

**Comment by ZahraMirzaei** [comment]
@phryneas I'm new in RTK Query, when I use dispatch(api.util.invalidateTags(...)), it shows an error on api and said <cannot find name 'api'> and I don't know what I should set instead of invalidateTags(?).

**Comment by ZahraMirzaei** [comment]
@phryneas  in my code, after the user login with a google account, userId should fetch with POST mutation from backend, and then receive userInfo with GET query, if user has userName then redirect to home, else redirect to signup page and set userName.
how to pass userId in signin page to GET query, right after fetch?
in [this NOTE](https://redux-toolkit.js.org/rtk-query/usage/manual-cache-updates#overview), mention that If an updateQueryData thunk action is dispatched that corresponds to no existing cache entry for the provided endpointName + args combination, the provided recipe will not be called, the provided recipe will not be called, and no patches or inversePatches will be returned. so can you please guide me, on how to use it?

**Comment by phryneas** [comment]
@ZahraMirzaei honestly I am not really sure, what you are asking, and it also doesn't seem to have anything to do with this issue.  
Could you please start a question in the "[discussions](https://github.com/reduxjs/redux-toolkit/discussions)" (the issues are there to report bugs in RTK), give a clear explanation of what you want to do, add code examples of what you are doing and the exact error messages you are getting?

**Comment by fkiDev** [comment]
Is there a way to invalidate a tag without refetch immediately. My use case: add post invalidate my posts, but do not fetch my posts till i enter the screen of my posts

**Comment by Tenhiz** [comment]
> @phryneas I'm new in RTK Query, when I use dispatch(api.util.invalidateTags(...)), it shows an error on api and said <cannot find name 'api'> and I don't know what I should set instead of invalidateTags(?).

I had the same problem. But I solved it so I can help you. In my case it was `userApi.util.invalidateTags(['User'])` where `userApi` it is a name of my API which I've created by `createApi`
