### ISSUE TITLE
RTK Query streaming updates - connect to websocket

### ISSUE THREAD

**Issue by nos-nart** [reduxjs/redux-toolkit#1866]
Hi. Thanks you for making this awesome package
I'm trying to connect to websocket server. Read the [streaming update docs](https://redux-toolkit.js.org/rtk-query/usage/streaming-updates#overview) I have the following code:
```ts
export const voiceApi = createApi({
  reducerPath: 'voiceApi',
  baseQuery: retry(
    fetchBaseQuery({ baseUrl: '/' }),
    { maxRetries: 5 }
  ),
  endpoints: (build) => ({
    getVoice: build.query({
      query: () => `/tts_api`,
      async onCacheEntryAdded(
        arg: { voice: string, paragraph: string },
        { updateCachedData, cacheDataLoaded, cacheEntryRemoved }
      ) {
        // create a websocket connection when the cache subscription starts
        const ws = new WebSocket("ws://my_published_server:81")
        try {
          // wait for the initial query to resolve before proceeding
          await cacheDataLoaded

          // when data is received from the socket connection to the server,
          // if it is a message and for the appropriate channel,
          // update our query result with the received message
          const listener = (event: MessageEvent) => {
            const data = JSON.parse(event.data)
            wsLogger.log('event -> ', event)

            updateCachedData((draft) => {
              draft.push(data)
            })
          }

          const onOpenWs = () => {
            wsLogger.log('Opening a connection...');
            const msg = {
              'text': arg.paragraph,
              'speed': 1.0,
              'voice': arg.voice,
              'full_mp3': 1,
            }
            ws.send(JSON.stringify(msg))
          }

          const onCloseWs = () => {
            wsLogger.log('Close connection!');
          }

          const onErrorWs = (evt: any) => {
            wsLogger.error(evt);
          }

          ws.addEventListener('close', onCloseWs);
          ws.addEventListener('error', onErrorWs);
          ws.addEventListener('message', listener);
          ws.addEventListener('open', onOpenWs);
        } catch {
          // no-op in case `cacheEntryRemoved` resolves before `cacheDataLoaded`,
          // in which case `cacheDataLoaded` will throw
        }
        // cacheEntryRemoved will resolve when the cache subscription is no longer active
        await cacheEntryRemoved
        // perform cleanup steps once the `cacheEntryRemoved` promise resolves
        ws.close()
      },
    }),
  }),
})

export const { useLazyGetVoiceQuery } = voiceApi
```
Try to connect by the exported query It will make a request to my localhost `http://localhost:3000/tts_api`
How could I change baseUrl to my websocker server?

**Comment by markerikson** [comment]
@nos-nart Yes, that's what happens when you provide a partial URL for the `query` result - `createApi` will combine that with the `baseUrl` you provided.

You'll need to provide a full URL here, like `query: () => 'http://my_published_server/tts_api'`.

**Comment by nos-nart** [comment]
@markerikson I'm trying to connect to websocket server It should have been started with **ws://** or **wss://** I tried to change follow above code It shows the error
> Fetch API cannot load ws://websocker_server/tts_api. URL scheme "ws" is not supported.

**Comment by phryneas** [comment]
The idea of those "streaming updates" is to get initial data using fetch from http and then get updates as they happen over a separate websocket. If you want a websocket connection from the beginning you would probably use `queryFn` instead of` `query` and initialize your state there without a http request.

**Comment by nos-nart** [comment]
@phryneas Could I trouble you to give a small code example of how to use `queryFn` with websocket. Great appreciate!

**Comment by phryneas** [comment]
For example you can just return an empty array for data and your `onCacheEntryAdded` can then fill it with values over time.
```
queryFn: () => {
  return { data: [] }
}
```
