### ISSUE TITLE
mutation initiate promise result is missing extra cache entry contents (consistency with query initiate)

### ISSUE THREAD

**Issue by hernanG89** [reduxjs/redux-toolkit#1867]
I was trying to test the services created by createApi from @reduxjs/toolkit/query/react and I got stuck while testing a mutation. 

I assumed that dispatching the initiate of a query and a mutation returns a Promise. Is it right?
I found that the return value of a mutation has just the data. Shouldn't It work in the same way as a query?

"@reduxjs/toolkit": "^1.7.1",
"jest": "^26.6.3",

EG: 
```
export const deliveriesService = createApi({
  reducerPath: "deliveries",
  baseQuery: fetchBaseQuery({ baseUrl }),
  endpoints: (builder) => ({
    getDeliveries: builder.query<Delivery[], void>({
      query: (): string => `deliveries`,
    }),
    finishDelivery: builder.mutation<Delivery, { delivery: Delivery; delivered: boolean }>({
      query: ({ delivery, delivered }) => ({
        url: `finishDelivery`,
        method: "POST",
        body: buildFinishDeliveryBody(delivery, delivered),
      }),
    }),
  }),
});
```

```
  test("getDeliveries", () => {
    fetchMock.mockResponse(JSON.stringify(deliveries));

    return storeRef.store
      .dispatch<any>(deliveriesService.endpoints.getDeliveries.initiate())
      .then((action: any) => {
        const { data, isSuccess } = action;

        expect(isSuccess).toBe(true);
        expect(data).toStrictEqual(deliveries);
      });
  });
  ```
  The .then receives:
  
```
     obj: {
      status: 'fulfilled',
      endpointName: 'getDeliveries',
      requestId: 'jDFUoAN4hnxE2p_rO1HnS',
      startedTimeStamp: 1640553689411,
      data: [...],
      fulfilledTimeStamp: 1640553689412,
      isUninitialized: false,
      isLoading: false,
      isSuccess: true,
      isError: false
    }
```
  ```
    test("finishDelivery", () => {
    fetchMock.mockResponse(JSON.stringify({ delivery }));

    return storeRef.store
      .dispatch<any>(
        deliveriesService.endpoints.finishDelivery.initiate({ delivery, delivered: true }),
      )
      .then((action: any, b) => {
        const { isSuccess } = action;

        expect(isSuccess).toBe(true);
      });
  });
  ```
  And this .then receives: 
  
  obj: {
```
data: {
        delivery: {
          address: '35273 Padberg Shores',
          city: 'Norwalk',
          zipCode: '53151',
          latitude: 9.1124,
          longitude: 165.8914,
          customer: 'Vera Homenick',
          id: '1'
        }
      }
  }
```

Am I doing something wrong?

Thanks in advance.

**Comment by phryneas** [comment]
While a query result can exist for a long time and as such be a hybrid of "this was successful in the past and now has an error", and as such can have `data` and `error` at the same time, a mutation result at that point can either be `success` (and have `data`) or `rejected` (and have an error). So exposing the whole mutation cache entry didn't really seem to make sense. 

Not that that has changed a bit with `fixedCacheKey`, but we haven't added the extra properties to the result yet. Might be a good idea to do this in the future.

**Comment by hernanG89** [comment]
> While a query result can exist for a long time and as such be a hybrid of "this was successful in the past and now has an error", and as such can have `data` and `error` at the same time, a mutation result at that point can either be `success` (and have `data`) or `rejected` (and have an error). So exposing the whole mutation cache entry didn't really seem to make sense.
> 
> Note that that has changed a bit with `fixedCacheKey`, but we haven't added the extra properties to the result yet. Might be a good idea to do this in the future.

That was fast!  It makes sense.  There should be a better way to test the services. Thank you!
