### ISSUE TITLE
How to access the data  from another slice file 

### ISSUE THREAD

**Issue by hayderjebur** [reduxjs/redux-toolkit#1868]
Hi there,
I am working on Redux-ToolKit to build an app that fetches the data from an API using createApi function as showing below:
export const solutionsApi = createApi({
  reducerPath: 'solutionsApi',
  baseQuery: fetchBaseQuery({
    baseUrl:'my URL'
  }),
  endpoints: (builder) => ({
    getSolutions: builder.query({
      query: (name) => `${name}`,
    }),
  }),
});
so now I can access the data by  const { data } = useGetSolutionsQuery() hook. My question is how can I modify the data that I got from another slice file? let say I want to filter or sort the data! how can I reach the data that has already been fetched from another reducer "slice" so I can run different actions? 
Thank you

**Comment by soundyogi** [comment]
Hm could you elaborate, I dont understand - It is unclear what you mean to me.

Are you trying to access data from a manually created slice created with createSlice() ?
https://redux-toolkit.js.org/tutorials/quick-start#use-redux-state-and-actions-in-react-components

Or are you only using createApi() (rtk-query), in that case you can just fetch the data again and sort / filter it.
If you need to persist the changes you can always use the entityAdapter or createSlice()?

**Comment by hayderjebur** [comment]
Hi thank you for your reply, I am using only createApi() (rtk-query), I do not have an issue accessing the data at the component level I can use the hook the RTK gave { data } = useGetPokemonByNameQuery, but I am having an issue when I am trying to access to this data from different createSlice(). The reason I want to access the data in the separated slice is so I can make many actions methods such as filter, sort ..etc

**Comment by markerikson** [comment]
@hayderjebur You can never access slice A's data inside of slice B's reducer in Redux.  Each slice reducer _only_ sees its own state.  This is by design:

https://redux.js.org/faq/reducers#how-do-i-share-state-between-two-reducers-do-i-have-to-use-combinereducers

**Comment by hayderjebur** [comment]
Thanks Mark for sharing the link and reading my question
