### ISSUE TITLE
Am I doing the mutation correctly in the component? #RTK Query

### ISSUE THREAD

**Issue by Saad-Bashar** [reduxjs/redux-toolkit#1872]
So this is my case, where I am using mutation inside component like this 
![Screenshot 2021-12-29 at 4 37 00 PM](https://user-images.githubusercontent.com/13269141/147642926-44c15f4c-8f30-4d7e-9d46-930680819bb5.png)

This works fine but React complains about this pattern after the API call is done. 

```
ExceptionsManager.js:179 Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
```

Does that mean I have to use this logic inside useEffect?
![Screenshot 2021-12-29 at 4 38 57 PM](https://user-images.githubusercontent.com/13269141/147643107-5d928bc8-af76-45cd-a9e2-8009e5b35c59.png)

**Comment by phryneas** [comment]
You never should have any kind of side effect inside of your function component code block. 
That might be executed by React multiple times before you even see anything on screen, and multiple more times for every subsequent render.

Always put logic like this into a `useEffect`.

**Comment by Saad-Bashar** [comment]
Thanks a lot for the kind response @phryneas , was thinking the same. Just curious if this looks okay to you? So any time I have a mutation I need to create an `useEffect` if I want to do side effect logic? This pattern is a bit new to me, since usually with  traditional API call, we do something like the following,

`
try {
const res = await API_CALL();
} catch (error) {
 // show error message
}


`

**Comment by phryneas** [comment]
You can also await the `createInvoice` function here just the same - both patterns are very common in React, it just depends on what you prefer.
