### ISSUE TITLE
`subscriptions/unsubscribeQueryResult` is fired before every `useLazyQuery` trigger

### ISSUE THREAD

**Issue by chandlervdw** [reduxjs/redux-toolkit#1873]
I'm using an auto-generated lazy query hook, `useLazyGetDynamicContentQuery` via the `injectEndpoint` method with the following params:
```
      query: ({contentId, displayParameters}) =>
        `v2/content/${contentId}?displayParameters=${displayParameters}`,
      transformResponse: response => {
        return parseDynamicContent(response);
      },
      keepUnusedDataFor: 120
```

--- 

Whenever I fire off the trigger that is returned as the first value from the hook, I see that `ttApi/subscriptions/unsubscribeQueryResult` is fired in Redux DevTools. This makes every request refetch instead of using cached data. With two back-to-back requests (fired via a refresh button), I get the following redux actions:
```
ttApi/subscriptions/unsubscribeQueryResult
ttApi/executeQuery/pending
ttApi/executeQuery/fulfilled
ttApi/subscriptions/unsubscribeQueryResult
ttApi/executeQuery/pending
ttApi/executeQuery/fulfilled
```

If I inspect the FIRST `ttApi/subscriptions/unsubscribeQueryResult` action, this is the raw `payload`:
```
{
  type: 'ttApi/subscriptions/unsubscribeQueryResult',
  payload: {
    queryCacheKey: 'getDynamicContent({"contentId":2222,"displayParameters":"{\\"timeSelect\\":\\"2021-12-01T04:00:00.000Z,2021-12-10T04:00:57.000Z\\",\\"userProvidedTimeLimits\\":true}"})',
    requestId: 'GkXhrq8WMprY2zwI_S66t'
  }
}
```
followed by the first `ttApi/executeQuery/pending` action payload:
```
{
  type: 'ttApi/executeQuery/pending',
  meta: {
    startedTimeStamp: 1640813327345,
    arg: {
      type: 'query',
      subscribe: true,
      forceRefetch: true,
      subscriptionOptions: {
        pollingInterval: 0
      },
      endpointName: 'getDynamicContent',
      originalArgs: {
        contentId: 2222,
        displayParameters: '{"timeSelect":"2021-12-01T04:00:00.000Z,2021-12-10T04:00:57.000Z","userProvidedTimeLimits":true}'
      },
      queryCacheKey: 'getDynamicContent({"contentId":2222,"displayParameters":"{\\"timeSelect\\":\\"2021-12-01T04:00:00.000Z,2021-12-10T04:00:57.000Z\\",\\"userProvidedTimeLimits\\":true}"})'
    },
    requestId: 'arGYW0NBx_JW3aJMCmTeI',
    requestStatus: 'pending'
  }
}
```
The `ttApi/executeQuery/fulfilled` is firing as expected with the new data and my component is showing the latest data from the api.

If I inspect the SECOND `ttApi/subscriptions/unsubscribeQueryResult` action, this is the raw `payload`:
```
{
  type: 'ttApi/subscriptions/unsubscribeQueryResult',
  payload: {
    queryCacheKey: 'getDynamicContent({"contentId":2222,"displayParameters":"{\\"timeSelect\\":\\"2021-12-01T04:00:00.000Z,2021-12-10T04:00:57.000Z\\",\\"userProvidedTimeLimits\\":true}"})',
    requestId: 'arGYW0NBx_JW3aJMCmTeI'
  }
}
```
It is invalidating the previous requestId: `arGYW0NBx_JW3aJMCmTeI` but the `queryCacheKey` is exactly the same for both. I checked in the console by setting some constants and using the `===` operator to be sure. What am I doing wrong here?

**Comment by phryneas** [comment]
`unsubscribeQueryResult` has nothing to do with it - that doesn't cause the refetch. Using the lazy trigger without setting the second parameter will cause a refetch.

**Comment by chandlervdw** [comment]
@phryneas thank you kindly. Might I suggest that you alter the documentation to push that up from being a note at the bottom of `useLazyQuery` to be listed with the parameters?

**Comment by msutkowski** [comment]
@chandlervdw Mind giving https://github.com/reduxjs/redux-toolkit/pull/1924 a peek and see if that helps? Should cover it :)
