### ISSUE TITLE
Line 2:23:  PayloadAction not found in '@reduxjs/toolkit'  import/named

### ISSUE THREAD

**Issue by jeyakumar-BTR** [reduxjs/redux-toolkit#1877]
Line 2:23:  PayloadAction not found in '@reduxjs/toolkit'  import/named

code:
// import { signInWithEmailAndPassword, firebaseAuth } from '@config/firebase.config';
import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { getAuth, signInWithEmailAndPassword } from 'firebase/auth';

const auth = getAuth();

interface AuthSliceState {
  userName: string;
  password: string;
}

const initialState = {
  isAuthenticating: false,
  auth: {},
};

export const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
    AUTHENTICATE: (state, action: PayloadAction<AuthSliceState>) => {
      console.log(action);
      state.isAuthenticating = true;
      state.auth = action.payload ?? ' ';

      const email = action.payload.userName;
      const password = action.payload.password;
      signInWithEmailAndPassword(auth, email, password)
        .then((userCredential) => {
          // Signed in
          const user = userCredential.user;
          console.log(user);
          // ...
        })
        .catch((error) => {
          const errorCode = error.code;
          const errorMessage = error.message;
          console.log(errorCode, errorMessage);
        });
    },
    AUTHENTICATION_DONE: (state) => {
      state.isAuthenticating = false;
    },
  },
});

export const { AUTHENTICATE, AUTHENTICATION_DONE } = authSlice.actions;

export default authSlice.reducer;

**Comment by phryneas** [comment]
This is not a help forum, this is an issue tracker to report bugs. I'm going to close your questions here as a result of that.

For usage questions, please ask at StackOverflow or in the #redux channel on Reactiflux.

Please also note that both of your questions contain so little extra information that they would probably be deleted (on SO) or ignored (in chat).

To make sure to get an answer there, please take the time to actually write down a nicely worded question in either of those communication channels, explaining what environment you are using (are you using TypeScript at all? Is this a create-react-app app or another setup? What editor are you using? Have you installed the package? Which version?) and what you have already tried to solve the problem yourself.
