### ISSUE TITLE
RTK Query Streaming Updates with Server Side Rendering

### ISSUE THREAD

**Issue by dickyindra** [reduxjs/redux-toolkit#1881]
I implemented websockets by following the steps at [https://redux-toolkit.js.org/rtk-query/usage/streaming-updates](https://redux-toolkit.js.org/rtk-query/usage/streaming-update)
And it doesn't work when I apply server side rendering, `onCacheEntryAdded` is always executed on server, not client side.

Is there any other way for websocket implementation keeping the server side rendering?

**Comment by phryneas** [comment]
You would probably need to skip the whole endpoint on the server and execute it only on the client. 
The lifecycle will not re-execute on hydration. 
That might be something we could add in the future, but we'd have to be careful about it I think, that might have unintended consequences 🤔

**Comment by dickyindra** [comment]
Thank you for answering my question.

But i need server side rendering for optimize SEO, maybe now i want to use another way for this.
I will wait for future updates 😁
