### ISSUE TITLE
Allow programmatic use of outputFiles in OpenAPI codegen

### ISSUE THREAD

**Issue by TranquilMarmot** [reduxjs/redux-toolkit#1887]
It's listed that you can generate multiple files using codegen here:
https://redux-toolkit.js.org/rtk-query/usage/code-generation#multiple-output-files

But it looks like that doesn't work if you're using it programmatically.

It's missing from this type here:

https://github.com/reduxjs/redux-toolkit/blob/4163a768eaf7a6d98b82d00ed6e50668f6d0e62e/packages/rtk-query-codegen-openapi/src/types.ts#L28

I would use a config file but I'm running into https://github.com/reduxjs/redux-toolkit/issues/1775

**Comment by phryneas** [comment]
It's not missing from the type, it's not supported.

The cli reads the configfile, parses it and then calls `generateEndpoints` in a loop.

If you use it programmatically, you have to call `generateEndpoints` in a loop yourself. `generateEndpoints` does not 1:1 support the config file format, but has it's own type signature.

That gives you much finer control over what it actually does, but it will need you to write a bit of logic.

**Comment by TranquilMarmot** [comment]
Makes sense! Thank you
