### ISSUE TITLE
createAsyncThunk condition assertions?

### ISSUE THREAD

**Issue by wuweiweiwu** [reduxjs/redux-toolkit#1888]
is there a way for the `condition` option in `createAsyncThunk` to also `assert` the condition in the main body of the thunk?

say i have an async thunk

```
export const testingThunk = createAsyncThunk<
  // return value
  void,
  // parameters
  string,
  // types for thunkAPI
  {
    dispatch: AppDispatch;
    state: RootState;
  }
>(
  'testing',
  async (args, thunkAPI) => {
      // can we somehow assert that someNullableValue is true here?
      // even though that value is read from state again

      const { someNullableValue } = thunkAPI.getState();

      // to typescript this value is still a nullable value
  },
  {
    condition: (args, thunkAPI) => {
      const { someNullableValue } = thunkAPI.getState();

      if (!someNullableValue) {
        return false;
      }

      return true;
    },
  }
);
```

the one thing that i'd like to avoid is to reassert the conditions inside the body of the thunk. either via `invariant` or a `return`

though the `invariant` would trigger a rejected action and the `return` will trigger a fulfilled action with an `undefined` body, both solution doesn't seem particularly great. 

I guess what I'm looking for here is a way to cancel the thunk before the pending action is dispatched without duplicating code (both in conditions and body of thunk) while keeping the assertions

**Comment by markerikson** [comment]
I don't think there's going to be any really easy answer here, unfortunately - those are completely different functions and there's no way to associate them in TS's control flow.
