### ISSUE TITLE
RTK query: Correct 'await' technique for multiple api requests

### ISSUE THREAD

**Issue by barryf001** [reduxjs/redux-toolkit#1891]
Hi, I have a question in relation to a use-case I need to port to RTK Query and the best approach to do this..

Currently we have a mechanism as follows which obtains 2 network resources, merges the data from both and loads into redux state - we do something as follows in an async action..
```javascript
Promise.all([fetch('url1'), fetch('url2']).then((r1,r2) => {
    //filter and extract data from r1 and r2 to produce stateData
    const stateData = r1.json() + r2.json();
    store.dispatch(stateDataRx(stateData));
})
```

Having read the docs I have seen that this could be achieved in 3 ways
1. createAsyncThunk - use this to create an action which wraps 2 dispatches of initiate to the rtk middleware
2. use selectors to derive the 'stateData' from the network cached data of the 2 network calls when the rendering occurs
3. use a custom [queryFn](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#performing-multiple-requests-with-a-single-query) to incorporate the multiple api calls into 1 cached resource

For me all 3 approaches of these have an issue that the original code does not
1. createAsyncThunk approach will mean that we cache the network response and cache a derived state object - so too much is cached
2. Use selectors approach has the downside (I think) that it is impossible to know if the data is well formed by the time the rendering occurs - I believe that for instance if the cache is invalidated by mutation then how is it possible to know that both network requests have finalised before a state-change->re-render occurs - I could lose the integrity of the data caches as there is no 'await' blocking the state change for any pending network request
3. Custom queryFn - has 3 distinct issues
- means that we could be pushing business logic down into the api layer
- unsure as to whether we can reference existing endpoints inside a custom queryFn - if so how is this possible pls
- not openapi codegen friendly
   
So my question is - what is the recommended approach to facilitate the simple use-case (code snippet) above in your opinion?

Just to add we are not using the react hooks api for our RTK query integration so if possible please could the any response take this into account.

Thanks in advance

**Comment by jgwiazdowski** [comment]
pretty much same problem here,
I call API, in the response got array with id's, then need to get call /id for each from the response,
any ideas? :|

**Comment by phryneas** [comment]
The distinction here is probably: do you need those two apis indivdually?

If you do not need them individually, [baseQuery is what we recommend in this example](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#performing-multiple-requests-with-a-single-query). That essentially creates one new endpoint out of them.

If you just have one endpoint depending on another, just call them in succession:

```js
const firstResult = useFirstQuery()
const secondResult = useSecondQuery(firstResult.isSuccess ? firstResult.data : skipToken)
// or
const secondResult = useSecondQuery(firstResult.data, { skip: !firstResult.isSuccess })
```

**Comment by jgwiazdowski** [comment]
glad to see your reply, thanks 
and yeah, looks like skip is what I need, I agree

I have found same link you sent, so I created endpoint with queryFn, passed there array of Id's as an argument and returned the result with Promises.all([promises]).then(...)
which seems silly? I expected to see some RTK way of handling multiple requests

to make sure we're one the same page
- on component render I call /getSomeItems 
- in the response I have an array(unknown length) of objects, where each object has an id
- then I need need to run /getSomeItemDetails/${id} for each id from the 1st request, so I might need to send 10 requests like this
again, I didn't find any other solution for that than Promise.all

**Comment by phryneas** [comment]
You are in the situation where you essentially want to call N hooks in a loop and cannot do that - that's a React restriction.
The easiest solution would be to call that "child hook" in a child component and render that N times.

**Comment by jgwiazdowski** [comment]
I understand that, question is whether is it ok to handle it with custom queryFn and Promise.all, 

true to be told, I am on NextJS, so I can work it out on the server side, but I really don't want to do that :|
I can't use use any RTK magic on the server side right, I did see next-redux-wrapper, but cmon

**Comment by phryneas** [comment]
You can do that, but with a custom `queryFn` you create one monstrous "blob" of a cache entry and cannot just have individual points refetched.
Consolidating two calls into one is one thing, but a few dozen is another.

You can totally use RTK Query on the server side, but you *will* need the wrapper for separation (otherwise all client calls share the same state) and rehydration (otherwise server side doesn't go over to the client). See https://redux-toolkit.js.org/rtk-query/usage/server-side-rendering

**Comment by jgwiazdowski** [comment]
right, so it seems like that's the way I need to go with considering my requirements,

I really hope I will keep using RTK, love the way one creates endpoint, hooks gets generated automatically and it's all connected with Redux <3

thank you @phryneas
