### ISSUE TITLE
[RTKQ]: copyWithStructuralSharing peformance issue

### ISSUE THREAD

**Issue by zoubingwu** [reduxjs/redux-toolkit#1896]
I was testing with mock data, some request returns an array of thousands of items, and it freezes for like 10+ second so I found this:

![image](https://user-images.githubusercontent.com/18644268/148364667-a988a8b3-aae1-4b4c-af02-88c7282aca4c.png)

I know with that amount of data it should be done with paginations or other techniques but this happens in real world. 

The `JSON.parse` is fairly quick, and most of the time it was executing `copyWithStructuralSharing`, so just wondering what it does and is it possible to make it better?

**Comment by phryneas** [comment]
Already 3 seconds for JSON.parse? 
Tbh, I would not have expected anyone to handle these amounts of data. 

At the moment, there is no way to skip it, but I could see us adding a `structuralSharing: false` option to endpoints.

**Comment by phryneas** [comment]
Hey @zoubingwu. @msutkowski has implemented an option for this over in https://github.com/reduxjs/redux-toolkit/pull/1954 - could you please try out the CI build and report back if it solves your problem?

**Comment by zoubingwu** [comment]
@phryneas Yep, just tried `https://pkg.csb.dev/reduxjs/redux-toolkit/commit/738faa66/@reduxjs/toolkit` this build and indeed it worked as expected. Thanks!

**Comment by phryneas** [comment]
Released in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.7.2
