### ISSUE TITLE
Toolkit: Does 'createAsyncThunk' work with redux-saga?

### ISSUE THREAD

**Issue by barryf001** [reduxjs/redux-toolkit#1899]
Sorry for this basic question but are is 'createAsyncThink' compatible with redux saga?

We need to integrate both libs in a new project and would like to know the recommded approach for integrating async actions.

Cheers

**Comment by phryneas** [comment]
You can dispatch asyncThunks from saga by using `yield put(myThunk())` and wait for resulting actions using `yield take (myThunk.fulfilled)`.

But generally, Redux saga has use in very few apps - in most apps it just adds unnecessary complexity without much benefit. You will need to have really complicated asynchronous dataflows to make good use of redux-saga. Data fetching is no such use case.
Are you sure you need it?

Also see the style guide on the topic: https://redux.js.org/style-guide/style-guide/#use-thunks-for-async-logic

**Comment by markerikson** [comment]
@barryf001 : my advice would be to _not_ use sagas in any new code unless you are _absolutely sure_ that you need them. 

Sagas _are_ useful for highly complex async workflows. However, they are absolutely overkill for basic data fetching.  Data fetching should be done with thunks by default, or even better, with RTK Query.

Can you provide some details on what problems you're looking to solve that you think would require sagas?

Also, note that we are working on [a new "action listener" middleware for an upcoming version of RTK](https://github.com/reduxjs/redux-toolkit/discussions/1648?sort=new), which is intended to solve a significant portion of the "async workflow" cases that previously required sagas or observables but with a smaller bundle size and simpler API.  You may want to look at that and see if it solves your use case.

**Comment by lukzfern** [comment]
Hey! I am working on an application that handles login, authentication, and fetch of different data (roles, information in arrays, etc.), im fetching data from the backend with axios, my question is kind of the same as this post author. I've to implement redux toolkit with redux saga but i've no clue how to do this while using the service from axios

**Comment by markerikson** [comment]
@lukzfern : that's a pretty broad question - I'd need to see actual code.  Also, this issue isn't the best place to provide advice.  I'd suggest dropping by the `#redux` channel in the Reactiflux Discord ( https://www.reactiflux.com ) and asking there.

Also note that we recommend using RTK Query as the default for data fetching:

- https://blog.isquaredsoftware.com/2022/05/presentations-evolution-redux-async-logic/

**Comment by dennismoha** [comment]
> Hey! I am working on an application that handles login, authentication, and fetch of different data (roles, information in arrays, etc.), im fetching data from the backend with axios, my question is kind of the same as this post author. I've to implement redux toolkit with redux saga but i've no clue how to do this while using the service from axios

This is easy. I have done so but I don't know how I can show you.
