### ISSUE TITLE
Call RTK mutation in custom middleware

### ISSUE THREAD

**Issue by hminkova** [reduxjs/redux-toolkit#1901]
Can I call RTK mutation in custom middleware?

Example:

`const customMiddleware: Middleware = (api) => (next) => async (action) => {
    try {
        if (isPending(action)) {
           api.login();
        }
        return next(action);
    } catch (error) {
        throw error;
    }
};`

**Comment by phryneas** [comment]
Sure, see [Usage Without React Hooks - Performing mutations](https://redux-toolkit.js.org/rtk-query/usage/usage-without-react-hooks#performing-mutations).

**Comment by hminkova** [comment]
When I tried to dispatch it from my custom middleware I get type error.

Ex: `api.dispatch(authenticationApi.endpoints.driverAppLogin.initiate(url));`

Error: `Argument of type 'ThunkAction<QueryActionCreatorResult<QueryDefinition<string, BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, never, Authentication, string>>, any, any, AnyAction>' is not assignable to parameter of type 'AnyAction'.
  Property 'type' is missing in type 'ThunkAction<QueryActionCreatorResult<QueryDefinition<string, BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, never, Authentication, string>>, any, any, AnyAction>' but required in type 'AnyAction'.`

**Comment by phryneas** [comment]
Your `dispatch` is probably not correctly typed to accept thunks. Make sure that your middleware definition includes `ThunkDispatch` in the third generic argument to `Middleware`.

**Comment by dmmarmolDA** [comment]
Hi @phryneas, thank you very much for your response. I came up to this thread facing the same issue as @hminkova mentioned and now I'm curious about your answer, do you think you could provide an example on how to accurately type this `Middleware`? I had to overcome this by using `any` but I'd prefer a stronger type

> Your `dispatch` is probably not correctly typed to accept thunks. Make sure that your middleware definition includes `ThunkDispatch` in the third generic argument to `Middleware`.

**Comment by markerikson** [comment]
@dmmarmolDA per https://redux.js.org/usage/usage-with-typescript#type-checking-middleware , you probably want something like:

```ts
export const exampleMiddleware: Middleware<
  {}, // Most middleware do not modify the dispatch return value
  RootState,
  ThunkDispatch
> = storeApi => next => action => {
  // middleware logic here
}
```

**Comment by shurshilov** [comment]
Hi i have same issue but my api inside middleware not have endpoints....
![image](https://github.com/reduxjs/redux-toolkit/assets/11828278/8b4730ca-3c24-47b5-8ebe-1e3cdf79fe0b)
