### ISSUE TITLE
How I remove authorization token from header 

### ISSUE THREAD

**Issue by bylly1** [reduxjs/redux-toolkit#1917]
95% of my APIs need token to receive data but I have also some APIs that I don t need token. How I remove the `authorization header` from my header query

```js
export const emptySplitApi = createApi({
    baseQuery: fetchBaseQuery({
        baseUrl: '/',
        prepareHeaders: (headers, { getState }) => {
            const token = getState().auth.token;
            if (token) headers.set('Authorization', 'Bearer ${token}');
            return headers
        }
    }),
    endpoints: () => ({})
});

export const authApi = emptySplitApi.injectEndpoints({
    endpoints: (builder) => ({
        load: builder.mutation({
            query: () =>
            ({
                url: 'http://localhost:5000/api/user',
                method: 'GET',
            })
        }),
        login: builder.mutation({
            query: credentials => ({
                url: 'http://localhost:5000/api/login',
                method: 'POST',
                body: credentials,
                headers:  {}  > Here I don t need token
            })
        }),
```

**Comment by msutkowski** [comment]
> From the back of my head:
> 
> ```js
>         prepareHeaders: (headers, { getState, endpoint }) => {
>             const token = getState().auth.token;
>             if (token && endpoint !== 'login') headers.set('Authorization', 'Bearer ${token}');
>             return headers
>         }
> ```
> 
> It could be `endpoint` or `endpointName` though.

It's `endpoint` :tada:. I've gone ahead and updated the docs + tests for this so it's more transparent.

**Comment by msutkowski** [comment]
Going to close this out: this information has been added to the docs. Thanks for bringing this up @bylly1

**Comment by sergeiivanow** [comment]
How to remove authorization marker from the header when re-registering another user from the same client?
