### ISSUE TITLE
Unexpected query behavior

### ISSUE THREAD

**Issue by aaronfulkerson** [reduxjs/redux-toolkit#1929]
Hi, I was hoping someone could help me understand if this is a bug or not. Is it by design that RTK Query goes from pending to rejected to fulfilled? If I add an extra reducer to a slice and match an API endpoint like this:
```
builder.addMatcher(
  (action) => true, // just send everything through
  (state, action) => {
    console.log(action);
  },
)
```
Log will happen 3 times showing action's type going from pending to rejected and then finally fulfilled. If that's not a bug that's super unintuitive. I expected the action's type to go from pending to fulfilled OR pending to rejected.

**Comment by msutkowski** [comment]
There's not enough information here to really help you with this. If you could make minimal repro on a codesandbox, that'd be great. In general, things can only go from pending->fulfilled or pending->rejected. If you look through the test suite, you can see that we assert the expected actions in insertion order.

If you're trying to do something in particular, the library ships a handful of useful matchers that you can use here. See: https://redux-toolkit.js.org/api/matching-utilities and for RTKQ specifically: https://redux-toolkit.js.org/rtk-query/api/created-api/endpoints#matchers

**Comment by aaronfulkerson** [comment]
Could it be that since I'm using the generated useQuery in two places, it's halting the pending action so it doesn't happen twice?

**Comment by aaronfulkerson** [comment]
I'm closing this because the exact reason is in the previous post, thanks!
