### ISSUE TITLE
UseQuery Expected 1-2 arguments, but got 0. 

### ISSUE THREAD

**Issue by WhoAmIRUS** [reduxjs/redux-toolkit#1950]
I use RTK Query with React. My createApi:

```
const rawBaseQuery = fetchBaseQuery({
  baseUrl: '/',
})

const dynamicBaseQuery: BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError> = async (args, api, extraOptions) => {
  const argumentURL = typeof args === 'string' ? args : args.url;
  const apiURL = `foo${argumentURL}`;

  const adjustedArgs =
    typeof args === 'string' ? apiURL : { ...args, url: apiURL }

  return rawBaseQuery(adjustedArgs, api, extraOptions);
}

export const api = createApi({
  baseQuery: dynamicBaseQuery,
  endpoints: () => ({})
})
```

```
const settingsApi = api.injectEndpoints({
  endpoints: (build) => ({
    loadSettings: build.query({
      query: () => './settings.json',
    }),
  }),
  overrideExisting: false,
})

export const { useLoadSettingsQuery } = settingsApi
```
```
const { data, isSuccess } = useLoadSettingsQuery()
```
And when I use hook `useLoadSettingsQuery`, I have TS Error `Expected 1-2 arguments, but got 0. `

When I opened the type of UseQuery I saw that arg is required field, but for my request I don't need args
`export declare type UseQuery<D extends QueryDefinition<any, any, any, any>> = <R extends Record<string, any> = UseQueryStateDefaultResult<D>>(arg: QueryArgFrom<D> | SkipToken, options?: UseQuerySubscriptionOptions & UseQueryStateOptions<D, R>) => UseQueryStateResult<D, R> & ReturnType<UseQuerySubscription<D>>;
`

TS: 4.4.3
RTK: 1.7.1

**Comment by markerikson** [comment]
At a minimum, your `build.query()` call needs to include generic args for response and argument types:

`build.query<ResponseType, ArgType>({})`

See https://redux-toolkit.js.org/rtk-query/usage-with-typescript#typing-query-and-mutation-endpoints

**Comment by WhoAmIRUS** [comment]
Thank you for help! I missed it :(
