### ISSUE TITLE
Listen on any API Request (RTK Query)

### ISSUE THREAD

**Issue by KwehDev** [reduxjs/redux-toolkit#1956]
Hello!

Is it possible to set up a global listener on any API Request to trigger a thunk beforehand?

We'd like to ensure the users' backend token isn't about to expire, and if it is, to refresh it, before performing any request.

Is there a configuration setting where this can be done?

**Comment by phryneas** [comment]
The recommendation is to do that in a `baseQuery` wrapper as [shown here in the docs](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery).

Alternatively, you could just do that extra request in `prepareHeaders`.

**Comment by KwehDev** [comment]
That works perfect, thank you!
