### ISSUE TITLE
The following error occurred in rtk-query. Is this expected?

### ISSUE THREAD

**Issue by kahirokunn** [reduxjs/redux-toolkit#1961]
An unhandled error occured processing a request for the endpoint "hogeApi".
In the case of an unhandled error, no tags will be "provided" or "invalidated". TypeError: Cannot read properties of undefined (reading 'includes')

**Comment by phryneas** [comment]
The stack trace might help here, can you please provide that?

**Comment by kahirokunn** [comment]
The problem occurred when I changed the branch many times while the nextjs dev server was running.
After clearing the cache with rm -rf .next, it started to work properly.
It was a problem with nextjs, not redux-toolkit, so I'll close it for now.
