### ISSUE TITLE
RTKQuery, When Constructing a Dynamic Base URL using Redux state: Data refetching on redux state change

### ISSUE THREAD

**Issue by KASOGIT** [reduxjs/redux-toolkit#1963]
I implemented a similar use case as described here: https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#constructing-a-dynamic-base-url-using-redux-state and it's working fine as long as the "projectId" does not change in the state.

What would be the best pratice to refetch automatically all the data when the projectId change in the state ?

The only way i see now is to manually invalidate the cache for the concerned queries but that would be cumbersome.

**Comment by msutkowski** [comment]
Depending on how you're modifying `projectId`, you can just leverage `resetApiState`. https://redux-toolkit.js.org/rtk-query/api/created-api/api-slice-utils#resetapistate. In most cases I've seen, you can do this at the component level as that's typically where you're going to change an `id` like that anyways. 

If you're reacting to some external event, you can dispatch that action creator in the same place you're changing the id. If you can't do that, you can do the same in middleware :)

**Comment by KASOGIT** [comment]
Yes that's what i thought, thanks for the interresting use cases ! In my case i'm doing it in a redux saga :)
