### ISSUE TITLE
RTX Query: Store does not update when trying to force refetch an endpoint multiple times

### ISSUE THREAD

**Issue by amitojsingh366** [reduxjs/redux-toolkit#1964]
Steps to recreate:
1) Setup rtk query's reducers and middlewares
  - Here's how I set up the reducers:
     ```js
     const reducer = combineReducers({
        ....
        [api.reducerPath]: api.reducer,
        ....
    })
  - Here's how I set up the middlewares:
    ```js
    export const createStore = () =>
    configureStore({
        reducer,
        middleware: getDefaultMiddleware =>
            getDefaultMiddleware(
                  immutableCheck: { warnAfter: 128 },
                  serializableCheck: { warnAfter: 128 }
             }).concat(api.middleware)
      })
    ```
    
2) Fetch an endpoint
3) Fetch a  different endpoint
4) Force refetch the same endpoint as in step 2 and notice how the store is not updated
  - I supplied `forceRefetch: true` on the endpoint initialize function to force refetch
     ```js
    api.endpoints.endpoint.initiate({}, {
        forceRefetch: true
    })
    ```

**Comment by markerikson** [comment]
Can you define "not updated"?  What are you expecting to see?

Could you provide a CodeSandbox that shows the same behavior?

**Comment by amitojsingh366** [comment]
> Can you define "not updated"? What are you expecting to see?
> 
> Could you provide a CodeSandbox that shows the same behavior?

@markerikson I have updated the issue I think this should cover your requirements? If not I can try creating a code sandbox for this

**Comment by markerikson** [comment]
Yeah, a sandbox would be really helpful, as well as some more details on what you expect to happen when you force the refetch.

**Comment by amitojsingh366** [comment]
this issue was due to an error on my side, sorry if I caused you guys trouble
