### ISSUE TITLE
[Question] What is the correct approach to use RTKQuery response data as a global state?

### ISSUE THREAD

**Issue by Saad-Bashar** [reduxjs/redux-toolkit#1965]
Sorry if this question is not a good one. But I am struggling to wrap my head around new rtkquery since I have been always working with the old way of using thunk to fetch API data. So here is my confusion,

Let's say we have an API that gets the user data. So without RTKQuery, I would be using `createAsyncThunk` to call the API and get the response. Once I get back the response I would set that data into our redux store `(User Reducer)`. Now from our app, we can just selector to get the user info anywhere from the user reducer. 

My question is how can we have the same pattern with rtkquery. I know the response data is cached inside the API reducer. But if I need that data globally or anywhere else I don't think we use the selector to get the user data from the API reducer (User API). In this case, do we use the rtkquery hook? let's say if I need user data on another screen and I have already fetched it before. Can I j just use `const { data } = useFetchAllUsers()`

**Comment by markerikson** [comment]
Yes, you can use the same query hooks in as many components as you want.  As long as you pass in the same cache key arg to each hook call (or in this example, _no_ cache key), all those components will share the same fetched data.

**Comment by Saad-Bashar** [comment]
Thanks a lot!! @markerikson

**Comment by msutkowski** [comment]
In addition to Mark's comment, there are a handful of things you can do here. 
- https://redux-toolkit.js.org/rtk-query/api/created-api/endpoints#select
- https://redux-toolkit.js.org/rtk-query/api/created-api/hooks#usequerystate

But, the easiest thing is just to use reuse the same query, or abstract it into a custom hook. For the example of `useFetchAllUsers`, that probably doesn't make sense though.

**Comment by Saad-Bashar** [comment]
Oh, this is super useful, @msutkowki , Thanks a lot! Wondering if there is any repo that I can check out to see them in action.
