### ISSUE TITLE
More control over serializableCheck option in middleware?

### ISSUE THREAD

**Issue by rvision** [reduxjs/redux-toolkit#1967]
I'm using redux-toolkit with redux-persist. In order to avoid serialization errors, middleware is configured to ignore redux-persist actions:

```
 serializableCheck: {
 		ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER]
},
```

I don't see a point of checking if actions are serializable if I am not using time-travel or other features. If action has a payload that is not serializable, it doesn't mean I am going to put that data as-is in the store. For example, my app works with dates and I would like to use dates in actions and store them in the state as strings. Or I might be using Set or Map to send data in action, but reducer will store that data as serializable data in the store.

Is there any option to skip checking **only for actions**? All of them? But leave this checking for the state.

I expected something like this, but this is not working:

```
 serializableCheck: {
 		ignoredActions: ['*']
},
```

**Comment by msutkowski** [comment]
@rvision Would you mind trying out the [CSB build + local install instructions](https://ci.codesandbox.io/status/reduxjs/redux-toolkit/pr/1984/builds/213982) and let me know if this addresses your concerns? You can just pass `ignoreActions: true` like

```ts
serializableCheck: {
  ignoreActions: true
}
```

Thanks!

**Comment by rvision** [comment]
@msutkowski 

Sorry, I have no idea how to try that out, never used something like that before.

But it looks like something I described above, thanks.

**Comment by phryneas** [comment]
@rvision you click on this header
![image](https://user-images.githubusercontent.com/4282439/151945196-75d8d326-56f3-42d8-8ba8-de25fb88fdd3.png)
and follow the instructions for your package manager
![image](https://user-images.githubusercontent.com/4282439/151945270-2f003762-f2f8-4c4f-b076-fbea079fe319.png)

**Comment by phryneas** [comment]
Released in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.7.2

**Comment by Aleksandr-Pod** [comment]
I work with typeScript and I have an error - in middleware
 "ignoreActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER]," can't be assigned boolean or undefined.
 How can I deal with is ?

**Comment by markerikson** [comment]
@Aleksandr-Pod covered in our docs, see here: 

https://redux-toolkit.js.org/usage/usage-guide#working-with-non-serializable-data

**Comment by TangoPJ** [comment]
> I work with typeScript and I have an error - in middleware "ignoreActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER]," can't be assigned boolean or undefined. How can I deal with is ?

Did you try use **ignoredActions** instead of **ignoreActions**? :)

**Comment by Aleksandr-Pod** [comment]
Good day.
Thanks for your reply. I already solved this issue using
*ignoredActions* instead
of *ignoreActions.*
