### ISSUE TITLE
Adding an ability to unsubscribe from results manually

### ISSUE THREAD

**Issue by Toxer10** [reduxjs/redux-toolkit#1970]
Hi, I would like to have an opportunity to manually unsubscribe from the results from createAPI middleware as shown on the screenshot.

![image](https://user-images.githubusercontent.com/25991946/151512028-cfe413db-16d2-4622-b52a-cfad6b0ac778.png)

As is described in the documentation - unsubscribeQueryResult is called when the component unmounts. In my specific case I have a couple of entities (screenshots provided), 

![image](https://user-images.githubusercontent.com/25991946/151512995-dde85820-1f42-41f8-8e9f-e138b817abd0.png)
![image](https://user-images.githubusercontent.com/25991946/151513009-d7c3cc09-30e2-406e-869a-5b8063c3dbc8.png)

which have useGetData alias hook, which reflects according useQuery from createAPI slice. Also I have the DashboardContent component, which uses this useGetData hook. The problem is: when I navigate from one page to another this unsubscribeQueryResult is not called because the component has not been unmounted. So I'm asking to provide an ability to manually unsubscribe from the query results.

![image](https://user-images.githubusercontent.com/25991946/151513055-1c5f6742-31a4-44e8-9dd1-ccdd92ceb908.png)

**Comment by phryneas** [comment]
Just do a `skip: true` and the component will unsubscribe.

**Comment by Toxer10** [comment]
Thanks, will try!

> Just do a `skip: true` in the query options or use `skipToken` as query argument and the component will unsubscribe.

**Comment by Toxer10** [comment]
> Just do a skip: true in the query options or use skipToken as query argument and the component will unsubscribe.

It did not work. The component was not even subscribed to the query results but the query hook was registered.

**Comment by phryneas** [comment]
Yes, setting to `skip` would be equivalent to "unsubscribing", but then your component would also never have access to data. If your component would get off-screen and you would not want it to be subscribed any more, you could set it to skip.

But from rereading your initial post I think your problem is a different one: you are violating the rules of hooks. 
You cannot swap one hook out for another by passing different hooks in as the same prop over time. That's just not a supported use case and we will never support that, as it is violating React core rules.

**Comment by Toxer10** [comment]
> Yes, setting to `skip` would be equivalent to "unsubscribing", but then your component would also never have access to data. If your component would get off-screen and you would not want it to be subscribed any more, you could set it to skip.
> 
> But from rereading your initial post I think your problem is a different one: you are violating the rules of hooks. You cannot swap one hook out for another by passing different hooks in as the same prop over time. That's just not a supported use case and we will never support that, as it is violating React core rules.

Could you tell if you have any ideas how to implement this in the right way?

**Comment by phryneas** [comment]
I fear at that point pretty much the basic premise is broken. You can use a higher order component to create components that are fixed bound to a hook, but you cannot swap out the hook at runtime.
