### ISSUE TITLE
RTK Query fails only on node v14 SSR node-fetch calls

### ISSUE THREAD

**Issue by springerkc** [reduxjs/redux-toolkit#1975]
I have been testing out RTK Query with next-redux-wrapper as described in the documentation [here](https://redux-toolkit.js.org/rtk-query/usage/server-side-rendering). When I run the app locally in node v16.13.2 I get no errors and everything works fine. If I run the app in node v14.18.3 (or deploy to Vercel as that is their latest available Node version) I get this error below. I am positive the wrapper is working because all my queries, api, and auth token is persisting the from wrapper.getInitialAppProps in my _app.tsx file. This error only occurs at the page level getServerSideProps Any ideas on what could be causing this or if I am missing a polyfill for v14?

My first thought is the Request type doesn't match what `node-fetch` is expecting but any help would be appreciated! 
Thank you in advance.

<img width="575" alt="Screen Shot 2022-01-29 at 5 12 32 PM" src="https://user-images.githubusercontent.com/43085071/151680569-f82305a7-6098-4e77-9059-d0713b0a7b89.png">

``` 
"dependencies": {
    "@reduxjs/toolkit": "^1.7.1",
    "next": "^12.0.9",
    "next-auth": "^4.1.2",
    "next-redux-wrapper": "^7.0.5",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.6"
  }


export const getServerSideProps: GetServerSideProps = wrapper.getServerSideProps((store: AppStore) =>
    async (context) => {
	store.dispatch(metal_user.endpoints.getUser.initiate());

	await Promise.all(getRunningOperationPromises());

	return {
		props: {
			showNav: true,
			protected: true,
		},
	};
});


An unhandled error occured processing a request for the endpoint "getUser".
In the case of an unhandled error, no tags will be "provided" or "invalidated". TypeError: Expected signal to be an instanceof AbortSignal
    at new Request (/Users/jspringer/packet/metal-console/node_modules/next/dist/compiled/node-fetch/index.js:1:60794)
    at /Users/jspringer/packet/metal-console/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:293:31
    at step (/Users/jspringer/packet/metal-console/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:23:23)
    at Object.next (/Users/jspringer/packet/metal-console/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:4:53)
    at fulfilled (/Users/jspringer/packet/metal-console/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:95:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by phryneas** [comment]
You will need to use the right `AbortController` polyfill in place that works together with your explicit `fetch` polyfill. Node 16 ships with AbortController, so you don't have that problem there any more.

I'm not sure what exactly you'll need in your situation, but there have been a few issues where people discuss the different polyfills so I'd recommend taking a look around.

**Comment by springerkc** [comment]
Thank you for the quick response. I will do some Googling around the `AbortController` polyfill. I figured it was something along those lines!

**Comment by springerkc** [comment]
`yarn install abortcontroller-polyfill` + `import 'abortcontroller-polyfill/dist/polyfill-patch-fetch'` solved it. Thanks again!
