### ISSUE TITLE
createSelector work good with Redux Toolkit

### ISSUE THREAD

**Issue by Kisilov-Vadim** [reduxjs/redux-toolkit#1978]
https://redux-toolkit.js.org/api/createSelector - There is information that we should use createDraftSafeSelector instead of createSelector cause: 

> Reselect's createSelector relies on reference comparisons to determine if inputs have changed, and if an Immer Proxy-wrapped draft value is passed in to a selector, the selector may see the same reference and think nothing has changed.

I tried to play with it, and createSelector works well. [Link to sandbox](https://codesandbox.io/s/epic-andras-6o8lq?file=/src/App.js).

**Comment by phryneas** [comment]
Yes, it works well, unless you use it on a drafted state in an immerized reducer:
```js

const selectValue = createSelector(
  (x) => x,
  (state: CounterState) => state.value
);

export const counterSlice = createSlice({
  name: "counter",
  initialState,
  reducers: {
    increment: (state) => {
      state.value += 1;
      console.assert(
        selectValue(state) === state.value,
        `asserting ${selectValue(state)} === ${state.value} failed`
      );
      state.value += 1;
      // this one will fail with createSelector
      console.assert(
        selectValue(state) === state.value,
        `asserting ${selectValue(state)} === ${state.value} failed`
      );
    },
    decrement: (state) => {
      state.value -= 1;
    }
  }
});
```
