### ISSUE TITLE
Service file are getting really large how can I do code splitting

### ISSUE THREAD

**Issue by Augustya-sharma** [reduxjs/redux-toolkit#1979]
I am working on an application and now service is getting really big because I have to call lots of of API endpoints.
Now I want to split my code into multiple files but I am really confused how to go for this. I try to read the docs but not being to understand much from. 
If I could get an example that would be really a great help for me 
I am not really that much experienced and  I have no one to ask for help so....😅

**Comment by markerikson** [comment]
Yeah, we do specifically cover this in our docs:

https://redux-toolkit.js.org/rtk-query/usage/code-splitting

You can also see the examples of this in the "Redux Essentials" tutorial:

https://redux.js.org/tutorials/essentials/part-8-rtk-query-advanced#injecting-endpoints

**Comment by Augustya-sharma** [comment]
Thank you so much for this. Have a great day :)
