### ISSUE TITLE
Doc: Type mismatch between docs and distributed types

### ISSUE THREAD

**Issue by wuweiweiwu** [reduxjs/redux-toolkit#1981]
in the docs for `createAsyncThunk` options

https://redux-toolkit.js.org/api/createAsyncThunk#options

`serializeError` should be able to return `any`

however in the latest version 1.7.1 the type that it enforces is actually the type inferred from thunk api config `serializedErrorType`

**Comment by phryneas** [comment]
Then using these features in TS, you have to explicitly specify the AsyncThunkConfig: https://redux-toolkit.js.org/usage/usage-with-typescript#createasyncthunk

**Comment by wuweiweiwu** [comment]
yeah. i guess this isn't really an issue. I just think it'd be misleading for people looking at the usage docs. I'd think that `serializeError` should be able to return `any` since those are ts annotations in the create async thunk docs (not the usage with typescript section)

**Comment by phryneas** [comment]
Tbh, I don't really know how to write it better - PRs would be welcome I think?

**Comment by markerikson** [comment]
Gonna go ahead and close this, but yeah, if you or someone else wants to file a PR to improve the docs that'd be appreciated!
