### ISSUE TITLE
Export the Abort() method from mutation / lazy query hook

### ISSUE THREAD

**Issue by sebastienlabine** [reduxjs/redux-toolkit#1985]
Could it be possible export the abort function, making it available directly from the hook ? 

```js
const [upload, { data, reset, abort  }] = useUploadMutation();
```

Most of the time the aborting takes place in a different function than where the lazy / mutation is called, which, right now, makes it really unpractical to abort request.

**Comment by phryneas** [comment]
No, since you do not abort "the mutation", but "this mutation".

Imagine that mutation would be called in three different components, twice with the same arguments and once with a different argument. Which of the three would you want to abort?

**Comment by sebastienlabine** [comment]
I understand. Not sure if possible, but do you think we could pass a ref to the mutation function so that we can access the mutation instance and just do 

```js
const mutationRef = useRef(null);

// somewhere
upload(mutationRef);

// somewhere else
mutationRef.current.abort();
```

Because the only way I see right now for me to achieve my use case would be to do:

```js
const [currentUpdate, setCurrentUpload] = useState(null);

// somewhere
const uploadMutation = upload();
setCurrentUpload(uploadMutation);


// somewhereElse
currentUpdate.abort();
setCurrentUpload(null);

```

**Comment by phryneas** [comment]
You can do something like that with a ref using `useImperativeHandle`, but at that point that's just "normal" React and has nothing to do with RTK Query any more.

**Comment by sebastienlabine** [comment]
don't we have access to the requestId? couldn't we trigger the abort for the particular request id?

**Comment by phryneas** [comment]
No, since there is no explicit internal mapping that keeps all of these running requests around by request id. 

If you can pass around the requestId you could also just pass around the `.abort()` function the same way?

**Comment by nidrizi** [comment]
Hi,

maybe I'm reading the docs wrong but this is misleading. According to this:

https://redux-toolkit.js.org/rtk-query/api/created-api/hooks#signature-4

the "trigger" function returned from the useLazyQuery is of type UseLazyQueryTrigger and returns a promise, however when I do something like:

`const [search, { isLoading, data: searchResult }] = useLazySearchQuery();`

the "search" function returns void and not a promise as described in the docs.

Is this docs wrong or am I am not using it as it was supposed to?

great work with the tool BTW 👍

**Comment by Ks89** [comment]
@nidrizi Did you find a solution?

**Comment by sebastienlabine** [comment]
@nidrizi you need to unwrap the promise. 

```await search.unwrap()```

**Comment by nidrizi** [comment]
@sebastienlabine Yeap, that's what I used! Thnx 👍 @Ks89

**Comment by siddharth17vaishnav** [comment]
how would we can abort an rtk query mutation api? can someone help me with this
