### ISSUE TITLE
TS Error when using nested reducers with Redux-Persist

### ISSUE THREAD

**Issue by KwehDev** [reduxjs/redux-toolkit#1987]
Hello,

We currently have a store structure like so;

```
const store = configureStore({
  reducer: {
    auth: authSlice.reducer,
    panel: panelSlice.reducer,
    settings: persistReducer(settingsPersistConfig, settingsSlice.reducer),
  }
})
```

This causes the following error;
```
Type 'Reducer<SettingsState & PersistPartial, AnyAction>' is not assignable to type 'Reducer<unknown, AnyAction>'.
  Types of parameters 'state' and 'state' are incompatible.
    Type 'unknown' is not assignable to type '(SettingsState & PersistPartial) | undefined'.
      Type 'unknown' is not assignable to type 'SettingsState & PersistPartial'.
        Type 'unknown' is not assignable to type 'SettingsState'.ts(2322)
```

With the following structures, the error is resolved;

```
  reducer: {
    auth: authSlice.reducer,
    panel: panelSlice.reducer,
  },

  reducer: {
    settings: persistReducer(settingsPersistConfig, settingsSlice.reducer),
  },
```

Could we potentially have an entry added to the documentation regarding nested persistence?
https://redux-toolkit.js.org/usage/usage-guide#use-with-redux-persist

**Comment by markerikson** [comment]
I don't think this is anything to do with "persistence", but rather TS itself.

This looks like a similar issue as #1831 , albeit there's no `getDefaultMiddleware` usage here.

I'm going to close this for now because I don't think there's much actionable we can do here.
