### ISSUE TITLE
createAsyncThunk with axios GET not resolving Promise to be rejected

### ISSUE THREAD

**Issue by msha1026** [reduxjs/redux-toolkit#1991]
We use axios to handle calling our APIs and then use createAsyncThunk, so that the correct `pending`, `fulfilled`, and `rejected` actions are created. We have one createAsyncThunk in one slice that gets data from one endpoint. When we force a response that is not 200, a `rejected` action is created like we expect. In another slice, we have another createAsyncThunk that is structured the same, but it is just calling a different path. When we force a response that is not 200, a `fulfilled` action is created instead. However when we log the response from the API, we are definitely receiving an error response back. We are not sure why `rejected` is working for one but not the other.

Here is the NOT working thunk and axios call:
```
/// detailsSlice.js
export const fetchDetail = createAsyncThunk(
  'details/fetchDetail',
  async (
    { accessToken, id },
    { getState, requestId }
  ) => {
    const { currentRequestId, fetchData } = getState().details.data.status
    if (fetchData == PENDING && requestId != currentRequestId) return
    const response = await fetchDetails(
      accessToken,
      id
    )
    return response.data
  }
)

///api.js
export const fetchWarehouseDetails = async (
  token,
  id
) =>
  await axios
    .get(baseUrl + 'details/' + id, {
      headers: {
        Authorization: 'Bearer ' + token
      },
      crossDomain: true
    })
    .then((response) => response)
    .catch((error) => error)
```

Here is the working thunk:
```
/// locationsSlice.js
export const fetchLocation = createAsyncThunk(
  'locations/fetchLocation',
  async (request) => {
    const { accessToken} =
      request

    const response = await fetchLocations(
      accessToken
    )
    return response.data
  }
)

/// api.js
export const fetchLocations = async (token) =>
  await axios
    .get(baseUrl + 'locations', {
      headers: {
        Authorization: 'Bearer ' + token
      },
      crossDomain: true,
    })
    .then((response) => response)
    .catch((error) => error)
```

**Comment by markerikson** [comment]
At first glance, I think that the issue is that the `.catch()` clause will swallow any rejections in front of it... **and return a _successfully resolved_ promise**.

In general you _shouldn't_ be trying to catch errors in an API wrapper with that, because `createAsyncThunk` depends on catching errors itself to know when to dispatch `rejected`.
