### ISSUE TITLE
Can't find redux

### ISSUE THREAD

**Issue by lzagar-comi** [reduxjs/redux-toolkit#1994]
Hey guys, I've just installed the newest version of toolkit and I am getting an error that it cannot find redux. Can anyone help me?
`error: Error: Unable to resolve module ../../../../redux from .../node_modules/@reduxjs/toolkit/dist/redux-toolkit.cjs.production.min.js: `

**Comment by phryneas** [comment]
Just guessing: does your project contain a folder named `redux` or a file names `redux.js` in the root?

**Comment by lzagar-comi** [comment]
One of developers on project has change something in babelrc, and created alias redux so toolkit tried to import it from there.

**Comment by Dror-Bar** [comment]
I had a folder named redux in src, but i changed the name to store and I still get this error.
What is going on?

**Comment by Dror-Bar** [comment]
Downgrading from 1.9.1 to 1.8.1 fixed the issue. Though I'm a bit dumbfounded how not more people have this issue.

**Comment by markerikson** [comment]
@Dror-Bar : we didn't change anything about the build setup for RTK's publishing between 1.8 and 1.9, so I'm really confused as to what's going on.

Can you put together a minimal repo that shows this error happening?

**Comment by Dror-Bar** [comment]
@markerikson 
It's a brand new project (npx react-native init)
MacBook Pro (Intel chip)

package.json:

```
{
    "name": "bonbon",
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "android": "react-native run-android",
        "ios": "react-native run-ios",
        "start": "react-native start",
        "test": "jest",
        "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
    },
    "dependencies": {
        "@react-navigation/native": "6.1.1",
        "@react-navigation/native-stack": "6.9.7",
        "@reduxjs/toolkit": "1.8.1",
        "react": "18.1.0",
        "react-native": "0.70.6",
        "react-native-safe-area-context": "4.4.1",
        "react-native-screens": "3.18.2",
        "react-redux": "8.0.5",
        "redux": "4.2.0"
    },
    "devDependencies": {
        "@babel/core": "7.12.9",
        "@babel/runtime": "7.12.5",
        "@react-native-community/eslint-config": "2.0.0",
        "@tsconfig/react-native": "2.0.2",
        "@types/jest": "26.0.23",
        "@types/react": "18.0.21",
        "@types/react-native": "0.70.6",
        "@types/react-test-renderer": "18.0.0",
        "@typescript-eslint/eslint-plugin": "5.37.0",
        "@typescript-eslint/parser": "5.37.0",
        "babel-jest": "26.6.3",
        "babel-plugin-module-resolver": "4.1.0",
        "eslint": "7.32.0",
        "jest": "26.6.3",
        "metro-react-native-babel-preset": "0.72.3",
        "react-test-renderer": "18.1.0",
        "typescript": "4.8.3"
    },
    "jest": {
        "preset": "react-native",
        "moduleFileExtensions": [
            "ts",
            "tsx",
            "js",
            "jsx",
            "json",
            "node"
        ]
    }
}
```

Project structure:

![Screenshot 2022-12-25 at 10 03 21](https://user-images.githubusercontent.com/34343333/209461158-ab2cd3d4-1683-4d2f-a23c-db4fd9577577.png)

**Comment by phryneas** [comment]
@Dror-Bar never create a folder that has the same name as a library. => do not create a folder called `redux` in your application.
You can find a suggested file strucutre [in the style guide](https://redux.js.org/style-guide/#structure-files-as-feature-folders-with-single-file-logic)
![image](https://user-images.githubusercontent.com/4282439/209461570-102376d6-cc12-45af-9951-1d9904209522.png)

**Comment by Dror-Bar** [comment]
@phryneas 
I understand
Yet, after renaming the folder to store (and having no other folder / file that shares a name with a library), uninstall node_modules, and reinstalling everything, I still had the same error.

**Comment by phryneas** [comment]
What error? Is it exactly character by character the same one as above, or is it only "like it"? Please share **your** error.

**Comment by Dror-Bar** [comment]
> What error? Is it exactly character by character the same one as above, or is it only "like it"? Please share **your** error.

It is the very same one, from which I copy&pasted

**Comment by phryneas** [comment]
Oh sorry, seeing that one now.

That error message still indicates that something is looking for `src/redux`. There is probably some bundler cache left somewhere that you need to clear.
![image](https://user-images.githubusercontent.com/4282439/209462159-2570245b-9af1-4e7c-b8cd-a5630fe01964.png)

**Comment by Dror-Bar** [comment]
@phryneas 
That's what I was thinking as well.
Looking at the error, that seems to be the case.
What is baffling to me is that after deleting node_modules and reinstalling the error persisted.
Perhaps that was not enough to clear the cache or something.

**Comment by phryneas** [comment]
Expo and Metro will have their caches elsewhere - usually you will have to delete some hidden folders or call the bundler with a flag like `--clear`. Generally we will probably not be able to help you with this.

**Comment by Dror-Bar** [comment]
I still wouldn't expect to hit this error by having a folder named redux, at the very least, perhaps the alias should be renamed to something a bit more specific.
Regardless, I suppose you could close this now. I didn't expect the project to break by having a folder in my src something generic like "redux" or "navigation" etc.
Thank for replying.

**Comment by phryneas** [comment]
You would get the same error if you had a folder named `react` and would write `import { something } from 'react'` in your project - your bundler is configured in a way to look for similar-named files and folders in your project first and into your `node_modules` second.  
That can be very convenient, but once you start naming your folders like libraries, you will get this error. It is nothing we can change though - it is a deliberate configuration of your project.

**Comment by Dror-Bar** [comment]
> You would get the same error if you had a folder named `react` and would write `import { something } from 'react'` in your project - your bundler is configured in a way to look for similar-named files and folders in your project first and into your `node_modules` second. That can be very convenient, but once you start naming your folders like libraries, you will get this error. It is nothing we can change though - it is a deliberate configuration of your project.

Thanks for clarifying. That does make sense I suppose this is my own configuration issue.
