### ISSUE TITLE
Can't make update request with formData

### ISSUE THREAD

**Issue by korbonya** [reduxjs/redux-toolkit#1995]
`updatePointSale: build.mutation({
	query: ({id,body}) => ({
		url: `/point-sales/${id}`,
                method:'POST',
		headers: {
		"content-type": "multipart/form-data",
		Accept: "application/json",},
		body,
	}),`
And I have this response
rejected, Object {
  "error": "TypeError: Network request failed",
  "status": "FETCH_ERROR",
}

**Comment by phryneas** [comment]
Seems like your `Network request failed`.
Could be anything from your PC not being connected to the network to the host url being wrong. Have you looked at your network devtools?

**Comment by korbonya** [comment]
I'm using expo.

> Seems like your `Network request failed`. Could be anything from your PC not being connected to the network to the host url being wrong. Have you looked at your network devtools?

I'm using react native (expo) and the request update the element but return this error.

**Comment by korbonya** [comment]
> probably something with the connection is wrong. this is not a RTK Query error. You would get exactly the same error from calling `fetch` by hand - we are just getting it from fetch.

ok thank you. I understood

**Comment by arpitprod** [comment]
I am calling a API
> const { data, isSuccess, isLoading, error } = useIsExistQuery({ otp })

and in Console Tab, error is

> {error: "TypeError: Failed to fetch", status: "FETCH_ERROR"}

but in Network Tab, status code is 401

![Screenshot 2022-03-16 at 5 15 17 PM](https://user-images.githubusercontent.com/19798516/158582995-a414756f-66ff-4ed0-b06f-7352edd498ab.png)

If I remove local storage then it's working fine and this API is not saving any data in browser cache and not sending auth token also

When I clear cache, This API working fine for few hours and getting same issue again

**Comment by phryneas** [comment]
"Failed to fetch" is really a 1:1 error you get back from calling `fetch` as well, so if you were to call `fetch` with the exact same arguments, I'm pretty sure you would be getting the same error.
