### ISSUE TITLE
Why `ignoreActions` and `ignoredActions` overrides `ignoreState`?

### ISSUE THREAD

**Issue by ZaValera** [reduxjs/redux-toolkit#1996]
I want to check the state but ignore the data that is passed to the action.. But i can`t do that.
Сonfiguration
```
{
    ignoreActions: true,
    ignoreState: false,
}
```
is identical
```
{
    ignoreActions: true,
    ignoreState: true,
}
```
Why not make these two checks independent?

**Comment by markerikson** [comment]
Yeah, that's a fair point.  We should probably restructure the logic here.

@msutkowski , want to try rearranging it so that skipping actions doesn't skip the state?
