### ISSUE TITLE
useQueryState & get data from fulfilled queries

### ISSUE THREAD

**Issue by jgwiazdowski** [reduxjs/redux-toolkit#1999]
Hi,

here is a scenario,

when app loads, in HOC I use 2 hooks to load data, both simple get requests,
first query runs with no parameters, seconds needs parameter(string) which is based on first query response, so to achieve this I use skip option on second query - works fine,

now, I need to access data from second query in one of the components,
I was thinking that I can just use api.endpoint.useSecondQuery.useQueryState(), but I need to pass same key parameter which I passed when I called the query right? 

so I guess I am really asking, what do I get data from the queries ? do I always have to pass same parameters when calling useQueryState? seems rather tricky

normally I would just create reducers and keep data from queries in them the old way, but I don't feel it's right approach since data is already in the store.

Thanks

**Comment by markerikson** [comment]
Yes, that's exactly the case. The cache key serves as just that - the key so that the hooks know where to find the data in the store.  If multiple components want to share the same cached data, they have to pass in the same cache key to the query hooks.

**Comment by jgwiazdowski** [comment]
ok thanks,
so, is it ok to simply have some hardcoded cache key item, like "posts", so then I can easily access data from it on any component I like?

**Comment by jgwiazdowski** [comment]
ok so here is my endpoint

```
getSomeData: builder.query<IContractApiResponse, Array<string>>({
      query: (params) => ({
        url: "/apiRoute",
        method: "get",
        params: JSON.stringify({
          data: {
            calls: params,
          },
        }),
      }),
```

and here is how I call it

`useGetSomeDataQuery(calls);`

where `calls` is an array of strings like

`['/getItem/1','/getItem/2' ]`

so the final get url may look like 

`API_URL/apiRoute?%7B%22data%22%3A%7B%22calls%22%3A%5B%22%2FgetItem%2F4%22%2C%22%2FgetItem%2F57%22%2C%22%2FgetItem%2F58%22%2C%22%2FgetItem%2F107%22%2C%22%2FgetItem%2F196%22%2C%22%2FgetItem%2F226%22%5D%7D%7D=`


so now, what do I need to put into parameter below? bo get data of request above in any component I want?
api.endpoint.useGetSomeDataQuery.useQueryState(PARAM )

**Comment by markerikson** [comment]
The exact same array of strings, which will get serialized and turned into the cache key.

**Comment by phryneas** [comment]
Really, you could also just use `useQuery` instead of `useQueryState` everywhere, actually I would even recommend that. `useQueryState` is just a part of the implementation of `useQuery` and we exposed it because we though *someone* might want to use it.

**Comment by jgwiazdowski** [comment]
@markerikson 
ideally I would like to be able to pass my array of string and key of my choice like "ABC" to be able to run
api.endpoint.useGetSomeDataQuery.useQueryState("ABC") and get cached data without giving an array of string again, it's simply a pain

thank you

@phryneas 
using same useQuery second time won't actually run a request right? I would just get cached data?

**Comment by phryneas** [comment]
@jgwiazdowski it would just be the cached data and not fire another request.

And no, we will not allow for manual definition of cache keys. Cache keys are internals and we will not expose them. Call the hook (doesn't matter if `useQuery`, `useQueryState` or `useQuerySubscription`) with the same argument again to get the result.
