### ISSUE TITLE
Inheritance in openApi code generation incorrect.

### ISSUE THREAD

**Issue by AlexBrad1ey** [reduxjs/redux-toolkit#2002]
[Swagger Inheritance & Polymorphism](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/) is not generating correctly from the OpenApi definition. this is directly related to #1940. But i am recording this as a seperate issue because it references a different case but is most probably a related error in the code.

I have striped down the situation as to not clutter the issue.
When a openApi schema has an `Entity` base type and a subtype called `Project`, and is defined simply as `Project -> allOf -> Entity` with no descriminators or anything just a simple inheritance the `Project` entity is not correctly generated.

RTK Generator produces the following type output:
```typescript
export type Entity= {
  id?: string | null;
  name?: string | null;
  description?: string | null;
  status?: string | null;
};
export type Project = Entity
```
This is incorrect and seems to have 2 mistakes:

1. all additional properties on a subtype are lost due to the `Project = Entity`.
2. the missing properties are caused because the code gen creates `type`s not `interface`s which cannot be extended.

**Comment by phryneas** [comment]
We use https://github.com/cellular/oazapfts for the type generation - I would assume that this is not a problem in the codegen, but in the upstream library - but I could go wrong. Either way, could you create a small reproduction? I can take a look and even if I come to the conclusion that you have to ask there, they will need that too.

**Comment by msutkowski** [comment]
If you could provide the swagger schema, that'd be great. I can confirm that this is an upstream issue have made a repro here: https://github.com/msutkowski/oazapfts-typesecript-codegen-repro.

I'm going to spend a little time investigating this and seeing if we can easily issue a patch for oazapfts, and if not, what our other options are.

**Comment by msutkowski** [comment]
@AlexBrad1ey can you try installing the local build of the linked PR in #2004? 

Any of these should work depending on your package manager.

```
# yarn 1
yarn add https://pkg.csb.dev/reduxjs/redux-toolkit/commit/9100477b/@rtk-query/codegen-openapi
# yarn 2, 3
yarn add @rtk-query/codegen-openapi@https://pkg.csb.dev/reduxjs/redux-toolkit/commit/9100477b/@rtk-query/codegen-openapi/_pkg.tgz
# npm
npm i https://pkg.csb.dev/reduxjs/redux-toolkit/commit/9100477b/@rtk-query/codegen-openapi
```

Thanks!

**Comment by Elewyth** [comment]
@msutkowski I just tested the PR with `npm i https://pkg.csb.dev/reduxjs/redux-toolkit/commit/9100477b/@rtk-query/codegen-openapi` and for my case it successfully generates the following:

Spec:
```yaml
    TokenResponseDto:
      allOf:
        - $ref: '#/components/schemas/TokenPatchDto'
      properties:
        id:
          type: number
      required:
        - id
        - type # <- This is a property from TokenPatchDto
```

TokenApi.ts:
```typescript
export type TokenResponseDto = TokenPatchDto & {
  id: number
}
```

Thank you for this fix :).

However, there is one further detail, that is not covered correctly:
In my `TokenResponseDto` (the one inheriting the properties) I specify some of the inherited properties as `required` (i.e. non-nullable in TypeScript). Since the generated type simply references the `TokenPatchDto` where all properties are nullable, the fields in the final `TokenResponseDto` type are still all nullable (except for the `id` which is declared directly on the type).

**Comment by msutkowski** [comment]
@Elewyth Sorry about resurrecting this so many months later! I was just doing some experimenting before we release a new version, and I'm unable to reproduce what you're describing. If I use a schema that requires properties on a response, they are generated correctly. If you're able to share your open API spec, I can test specifically against that. If you can't share that publicly, you can find me on Twitter/Discord and share privately - or just provide me with a minimal repro schema with obfuscated things.
