### ISSUE TITLE
what is the useMutation and useLazyQuery differences?

### ISSUE THREAD

**Issue by bs32g1038** [reduxjs/redux-toolkit#2010]
It seems I only need to use ```useLazyQuery```. I don't find any obvious difference from the documentation about them, why would I use ```useMutation```. is it just because of the semantic distinction?

**Comment by phryneas** [comment]
Also, workflow and data sharing.

Queries are for getting data from the server. You call a query with the same argument 5 times, they share their cache value by default. are treated as "the same resource" and will be the same result in all component. 

Mutations are an individual result in each component you use them, as it is assumed that each of them invokes an individual change on the server and has an individual result.

Also, mutations can invalidate tags and cause automatic refetching of queries - not the other way round.
