### ISSUE TITLE
TypeScript: how to work with partial types in actions

### ISSUE THREAD

**Issue by krutoo** [reduxjs/redux-toolkit#2012]
Hi, in my app i use  TypeScript with `@reduxjs/toolkit`

There is example of usage:

```ts
import { createReducer, createAction, PayloadAction } from '@reduxjs/toolkit';

interface AppParams {
  id: number;
  returnUrl?: string;
  context?: string;
  name: string;
}

interface AppState {
  name: string;
  params: AppParams | null;
}

const initialState: Readonly<AppState> = {
  name: 'foo',
  params: null,
};

const actions = {
  setParams: createAction<{ params: AppParams }>('app/SET_PARAMS'),
  updateParams: createAction<{ params: Partial<AppParams> }>('app/UPDATE_PARAMS'),
} as const;

// works perfectly
export function setParams(state: AppState, { payload: { params } }: ReturnType<typeof actions.setParams>): AppState {
  return { ...state, params };
}

export function updateParams(state: AppState, { payload }: ReturnType<typeof actions.updateParams>) {
  return { ...state, params: { ...state.params, ...payload.params } };
}

// provides TS error
export const reducer = createReducer(initialState, builder =>
  builder
    .addCase(actions.setParams, (state, { payload }) => ({
      ...state,
      params: payload.params,
    }))
    .addCase(actions.updateParams, (state, { payload }) => ({
      ...state,
      params: { ...state.params, ...payload.params },
    })),
);
```

And there is TS error causes by this example:

```
src/index.ts:36:3 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(actionCreator: ActionCreatorWithPayload<{ params: Partial<AppParams>; }, string>, reducer: CaseReducer<Readonly<AppState>, { ...; }>): ActionReducerMapBuilder<...>', gave the following error.
    Type '{ id?: number | undefined; returnUrl?: string | undefined; context?: string | undefined; name?: string | undefined; }' is not assignable to type 'WritableDraft<AppParams>'.
      Types of property 'id' are incompatible.
        Type 'number | undefined' is not assignable to type 'number'.
          Type 'undefined' is not assignable to type 'number'.
  Overload 2 of 2, '(type: string, reducer: CaseReducer<Readonly<AppState>, { payload: { params: Partial<AppParams>; }; type: string; }>): ActionReducerMapBuilder<Readonly<...>>', gave the following error.
    Argument of type 'ActionCreatorWithPayload<{ params: Partial<AppParams>; }, string>' is not assignable to parameter of type 'string'.
```

Regular functions works fine with `Partial` type utility in action payload

But `builder.addCase` provides error with same action

How can i properly solve this problem?

**Comment by markerikson** [comment]
I believe there was a previous issue related to using `Partial<SomeType>` as a payload, in that TS can't differentiate that from `unknown`.  See the workaround here:

https://github.com/reduxjs/redux-toolkit/issues/1423#issuecomment-902680573

Also, I would _strongly_ recommend that you write that code with `createSlice` instead :)  You really shouldn't ever try to write a bunch of `createAction` + `createReducer` usage yourself.  That's exactly what `createSlice` does for you.  For that matter, you're also still writing a bunch of object spreads for immutable updates, and you don't need to.  

A shortened version might look like:

```ts
const appSlice = createSlice({
  name: 'app',
  initialState,
  reducers: {
    paramsLoaded(state, action: PayloadAction<AppParams>() {
      state.params = action.payload
    },
    paramsUpdated(state, action: PayloadAction<Partial<AppParams>>) {
      Object.assign(state.params, action.payload);
    }
  }
})

export const { paramsLoaded, paramsUpdated } = appSlice.actions;
export default appSlice.reducer;
```

**Comment by krutoo** [comment]
> I believe there was a previous issue related to using Partial<SomeType> as a payload, in that TS can't differentiate that from unknown.

Thank you, maybe is it, but is interesting that regular functions works fine...

I have some subjective reason to avoid `createSlice`: if you want to add additional actions (that are not handled by the reducer), you have to mix them into the resulting object by `Object.assign` or spread operator

In this case the code becomes a bit inconsistent and in my case extra actions are very common

**Comment by phryneas** [comment]
Your 
```ts
export function updateParams(state: AppState, { payload }: ReturnType<typeof actions.updateParams>) {
  return { ...state, params: { ...state.params, ...payload.params } };
}
```
is just wrong. 

It could return `params` as a mix of `null` and `Partial<AppParams>`, which could end up being very incomplete. It is absolutely correct that TypeScript does not like that.

**Comment by krutoo** [comment]
@phryneas yes, thank you for your answer
