### ISSUE TITLE
TS4023: Exported variable has or is using name FulfillWithMeta from external createAsyncThunk but cannot be named

### ISSUE THREAD

**Issue by mlicciardi** [reduxjs/redux-toolkit#2016]
I've a mono-repo project with 3 workspaces:
- packages/app
- packages/common
- packages/web

In common package I user rtk but when I try to build I get this error:
```
TS4023: Exported variable 'register' has or is using name 'FulfillWithMeta' from external module "/Users/mlicciardi/git-triskel/opinio-react/node_modules/@reduxjs/toolkit/dist/createAsyncThunk" but cannot be named.

export const register = createAsyncThunk(
```

**Comment by markerikson** [comment]
As usual, we would need to see an actual repo that demonstrates the issue happening - _especially_ given that this isn't a typical repository setup.

**Comment by jaimebustose** [comment]
I see the problem in my project too, I think the problem is the `FulfillWithMeta` class type was not exported in the `createAsyncThunk.d.ts` file generated.
