### ISSUE TITLE
How to get initialState value of different createSlice in createSlice

### ISSUE THREAD

**Issue by lgf196** [reduxjs/redux-toolkit#2017]
###  a.js
```
const a= createSlice({
  name: 'a',
  initialState:{
  user:'xx'
 },
  reducers: {
    editUser(state,action) {
      state.user = action.payload
    },
  },
})
```
###  b.js
```
const a= createSlice({
  name: 'b',
  initialState:{
  sex:'xx'
 },
  reducers: {
    editUser(state,action) {
      state.sex= action.payload;
     ###  **problem：**
      **I want to get the user value in `a.js` here to do some operations, how can I do it?**
    },
  },
})
```

**Comment by markerikson** [comment]
By definition, you can't. Each slice reducer _only_ ever sees its own state, period. It's impossible for slice reducer A to see any of reducer B's state:

- https://redux.js.org/faq/reducers#how-do-i-share-state-between-two-reducers-do-i-have-to-use-combinereducers

Instead, we recommend having many reducers respond to the same actions to do updates:

- https://redux.js.org/style-guide/style-guide#model-actions-as-events-not-setters
- https://redux.js.org/style-guide/style-guide#allow-many-reducers-to-respond-to-the-same-action
