### ISSUE TITLE
TSConfig's keyofStringsOnly setting breaks PreloadedState

### ISSUE THREAD

**Issue by nathanhannig** [reduxjs/redux-toolkit#2022]
I came across an issue where the TSConfig option `keyofStringsOnly` when set to true breaks the Utility Type PreloadedState; by not setting the slices too be optional.

This might not be a defect; just an incompatibility. 

But it took me quite sometime to debug the issue and wanted to make a record for it incase anyone else runs into this issue; since I could not find related help with a web search.

At the very bottom of this example, when you hover over the preloadedState argument; you can see the ts error.

https://www.typescriptlang.org/play?keyofStringsOnly=true&ts=4.0.5#code/JYWwDg9gTgLgBAbzgYwiARsAdgUwEo4AmArsjlAM4A0KUOAhjDgMoA2wZNqWAZsAObE6zGNBw0AolgAW9LGUIixNAAr0Anqwj1CAQWQxgELKrpadREYxxwAvnB5Q0cAEQABOiQAeAKwoB6UQhWAGtgGBcAbgAoaOwmKB56MjgAeVwrJkRouDhCRnoALjgKGChsfjgAHzgsYlZWGNs4rASklIAVAHcITJsEHLyC4tLyrEqauoam2JwvSFgUY1K4YxZ2FIBeWgYmNg4cAAoB3Kx6EBxilzWXKkHscOB6Vj7ik9yhmCLa+tY73Ps9AoaQyXyY-zgnlI5Aob0GuWIYHyTAAIsM4IdStYaMlDMZimpNNo9AYjFgADyjCoAPgAlHBNtTsh8PlimAA6ZH0BlwXFk9lgDTmQgxFm2CHi6K2WkxaJzBbwbgrGA9fZbHbWNVHd5nC5XFUQW73LCPZ6vZkfLnFKZ-QaA4HdXpg8SDKFkShwlmI5E4NFfYqY5040n4uCE4X6PEUqnjOkMpnvFlsnCcgo8vnGAVC4mij6SgF3aWypXwJwQGAEEjunmoDDYfBEaGUY6DNbFNZa9lu8gQg3FA2d7tQQsy2bzaDwHjEeRRko4GCIpR0Q5gMzEyzOgD8BLXFkUzvJeAg5b6dOKUlk8g3YgtdAXUCwS14AiELFEy8TkMb7uKZYr357eE4FXHBhQ3bE7VHZo5XHRYYHUMAbCPE9nR5Ah7ywDoEJwcl4MQiAeEhY9-yrchqRieUJzgPCbF0MAwCXGxtnQoRMOw3DsIIucFwY98cHImCFWo7C4DosAUWAChBRgZBpB5MTGIAbRcQhJOk2SXAAXWLZZ4BAsD92sHl3jbRBPm+FxpFArQXDsKVohLEo+J5Ch50XPiV13QhwKYWlYiAA

**Comment by phryneas** [comment]
I think we cannot really do something about that, especially given that `keyofStringsOnly` is a deprecated compiler flag at this point. But it's probably good to have it mentioned in an issue so that people can find it.

One more thing regarding your code example here:
You should never do a function return type annotation like `EnhancedState` like in your example here:

```diff
-export function setupStore(preloadedState?: PreloadedState<RootState>): EnhancedStore {
+export function setupStore(preloadedState?: PreloadedState<RootState>) {
  return configureStore({
    reducer: rootReducer,
    preloadedState,
  });
}
```
that return type annotation will erase all information about state structure and the middleware/dispatch type of that store. It is recommended to not have any annotation there.

**Comment by nathanhannig** [comment]
@phryneas  

Thanks for your suggest, the issue is I export and then import the setupStore function in my own project and my typescript-eslint has a rule that warns when the return type is not explicitly set.

https://github.com/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md

Looks like the return type is a long composition that the tools truncate for easy copy and paste.

**Comment by markerikson** [comment]
In this specific case, you _must not_ supply the exact type. This _needs_ to be inferred, period.  Disable the lint rule for this file if you must.

**Comment by phryneas** [comment]
I am saying this once and very clear: if you follow that eslint rule, RTK will break in many places. 

Eslint rules should be enabled when you know what they are doing, why they are doing it and if you can agree on the purpose while knowing that the thing being enforced will not break anything.

This elsint rule being enabled by default is harmful.

**Comment by nathanhannig** [comment]
Sorry if it seemed like I was disagreeing; I agree with turning it off just trying to let you know that the rule is automatically included with @typescript-eslint/recommended library so it will potentially conflict unless explicitly turned off like you mention.
