### ISSUE TITLE
RTKQ: refetchOnFocus not working with react-navigation.

### ISSUE THREAD

**Issue by vanenshi** [reduxjs/redux-toolkit#2028]
react-navigation use a custom hook called [`useFocusEffect`](https://reactnavigation.org/docs/use-focus-effect/) to inform the focus change. I think I should use the customerHandler of the `setupListeners` to handle the focus event correctly

**Comment by phryneas** [comment]
It is not really clear what exactly is not working. Window focus events should not have anything to do with any other libraries you use?

**Comment by vanenshi** [comment]
I have a react native project. I confirm that I set up the listeners. I am expecting [useQuery](https://redux-toolkit.js.org/rtk-query/api/created-api/hooks#usequery) to automatically call the `refetch` when the user navigates to that page.

since `react-navigation` mounts all of the pages before the user even navigates to them. I want the `useQuery` to refetch the data when a page is getting visible to the user.

**Comment by phryneas** [comment]
But if you were using `requestOnFocus` with the premise that you trigger a focus every time a page is focused (the idea usually is: when your *app* is focused) and always render all pages, that means that it would always refetch data for all pages. That can't be a good solution.

**Comment by phryneas** [comment]
You could add `{skip: !useIsFocused() }` to all your query hook usages then it would only start fetching data once the page comes into view.

**Comment by Brma1048** [comment]
@vanenshi how did you solve it?
