### ISSUE TITLE
RTKQ: After the first failed request, subsequent failed requests update isLoading property.

### ISSUE THREAD

**Issue by kaZ133** [reduxjs/redux-toolkit#2029]
Let's say we have the wrong API.

The first request returned an error, then we send a second request, and that one also returned an error, and so on.
So every request will update isLoading: false -> true.

That is how it should be?

There doesn't seem to be any mention of this in the docs.

**Comment by phryneas** [comment]
I'm actually not really sure about the issue you are describing here. Could you create a small reproduction?

**Comment by kaZ133** [comment]
https://codesandbox.io/s/mystifying-benz-lkyv3?file=/src/App.js

**Comment by nilscam** [comment]
Hello, I faced a similar problematic situation.

Right now, when a query results in an error, "isLoading" is re-set to true the next time the same query is triggered.

This is problematic when 2 components are connected to the same query, requesting an unavailable resource (404 for example), it can create an infinite loop if both components use "isLoading".

Is there a reason for "isLoading" to be re-set to "true" when refetching after a failed query?
