### ISSUE TITLE
Return rich objects from queries

### ISSUE THREAD

**Issue by sazzer** [reduxjs/redux-toolkit#2034]
I'm using Siren for my HTTP API, which means there's a fair bit of (necessary) complexity to it. What I'd really like to be able to do is have the RTK queries return a rich object that abstracts away that complexity. 

Right now I'm doing this in my components, but that gets repetitive quite quickly:
```
const { data } = useGetUser(id);
const user = data !== undefined ? new SirenDocument(data) : undefined;
```

I know there are good reasons to not store rich objects in the state itself, but it would be very useful if there were some way to have RTK automatically wrap the value as it's returned. Effectively like `transformResponse` but applied to the value *after* it's been put in the state. (And, obviously, applied to the value on subsequent calls when it's loaded from the state instead of from the server)

That way I could write my API as:
```
    getUser: build.query<SirenDocument<User>, string>({
      query(url) {
        return {
          method: "GET",
          url,
        };
      },
      transformOutput: result => new SirenDocument(result),
    }),
```

And everywhere that uses it will get a `SirenDocument<User>` instead of just the raw data.

Cheers

**Comment by markerikson** [comment]
Lenz would have the final word here, but I don't think this is a thing we want to support directly.  The closest you'd get, I think, is `selectFromResult`.

**Comment by phryneas** [comment]
Yapp, sorry I didn't respond so far - I'm in the middle of marriage preparations. 

A `transformOutput` would add yet another argument to the generic of `build.query` and not add a lot of value for most users, so I don't really think we should go that way.
