### ISSUE TITLE
Type error if class of state has private modifier

### ISSUE THREAD

**Issue by yamakeeeeeeeeen** [reduxjs/redux-toolkit#2041]
When creating a slice, if the state has a class, a type error will occur if the class has a private modifier.

We have prepared a simple example for you to check.

https://codesandbox.io/s/reduxtoolkit-forked-tzsvwb?file=/src/slice.ts

**Comment by phryneas** [comment]
You should not store classes in Redux state - so that is pretty much an unsupported scenario.

https://redux.js.org/style-guide/style-guide/#do-not-put-non-serializable-values-in-state-or-actions

**Comment by phryneas** [comment]
But in this case, your types are just wrong:

```diff
type Reducer = {
-  setFoo: (state: State) => State;
+  setFoo: (state: Draft<State>) => Draft<State>;
};
```

**Comment by yamakeeeeeeeeen** [comment]
@phryneas 
I had forgotten that you can't put a class in a state. Thanks for letting me know.
I'll close this issue.
