### ISSUE TITLE
RTKQ: Automatic re-authorization is evoked while login is pending

### ISSUE THREAD

**Issue by mmgh900** [reduxjs/redux-toolkit#2045]
Hi,
I have used the sample code shown [here ](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery)to automatically re-authorize the client when some request fails with 401 status. The final code in my app looks like this:

```
const baseQueryWithReauth: BaseQueryFn<string | FetchArgs,
    unknown,
    FetchBaseQueryError> = async (args, api, extraOptions) => {
    let result = await baseQuery(args, api, extraOptions)
    if (result.error && result.error.status === 401) {
        // try to get a new token (silence refresh)
        const refreshResult = await baseQuery({url: 'user/RefreshToken', method: 'POST'}, api, extraOptions)
        const response = refreshResult.data as { data?: IUser, errorCode: ErrorCode }

        if (response && response.errorCode == ErrorCode.NoError) {
            // store the new token
            api.dispatch(setCurrentUser(response.data))
            console.log('User set in refresh token')
            // retry the initial query
            result = await baseQuery(args, api, extraOptions)
        } else {
            api.dispatch(setCurrentUser(null))
            console.log('User deleted when refresh token returned some error')
        }
    }
    return result
}

```

The problem is that I have used some query data in my navbar and when the client sends a login request, while the request is still resolving, the query in my navbar gets executed and evokes the automatic re-authorization. In other words, the client sends a RefreshToken API call when it should just wait for the result of the login request. This causes two token creations when the user wants to log in. Any solution?

**Comment by phryneas** [comment]
This has been documented in #1947 but I missed it and forgot to get it merged. It will be part of the docs in a few minutes, but you can already read it in the PR.

**Comment by mmgh900** [comment]
Thank you! That solved it.
