### ISSUE TITLE
Problems with providesTags/invalidatesTags

### ISSUE THREAD

**Issue by w1redl4in** [reduxjs/redux-toolkit#2051]
Im trying to invalidate a query request with a mutation request, but cant find how to do it. Im passing ['Transaction'] as tag but nothing happens

API.ts
```
export const whitelabelAPI = createApi({
  baseQuery: fetchBaseQuery({
    baseUrl: endpoints.url_whitelabel_api,
  }),
  tagTypes: ['Transaction'],
  endpoints: () => ({}),
});
```

endpoint.ts
```
import whitelabelAPI...

const apiWithTag = whitelabelAPI.enhanceEndpoints({
  addTagTypes: ['Transaction'],
});

const extendedApi = apiWithTag.injectEndpoints({
  endpoints: (build) => ({


    // Query that providesTags
    listTransactions: build.query<RequestResult, FindOptions>({
      query: ({
        page,
        perPage,
        status,
        startDate,
        endDate,
        startMoney,
        endMoney,
        id,
        type,
      }) => ({
        url: `/transaction`,
        params: {
          page,
          perPage,
          status,
          startDate,
          endDate,
          startMoney,
          endMoney,
          id,
          type: JSON.stringify(type),
        },
      }),
      providesTags: ['Transaction'],
      transformResponse: (response: RequestResult) => ({
        page: response.page,
        total: response.total,
        transactions: response.transactions,
        formattedTransactions: formatTransactions(response.transactions),
      }),
    }),


    // Mutation that invalidates tags
    approveOrDeny: build.mutation<Transaction, ApproveOrDeny>({
      query: ({ accountPassword, transactionId, type, reason }) => ({
        url: `/transaction/approve-deny/${transactionId}`,
        body: {
          accountPassword,
          type,
          reason,
        },
        method: 'POST',
      }),
      invalidatesTags: ['Transaction'],
    }),
  }),
});
```

**Comment by phryneas** [comment]
Did you register the middleware of `whitelabelAPI` as shown in the documentation?

**Comment by w1redl4in** [comment]
Looks like its getting data from cache

approveOrDeny is my mutation endpoint
listTransactionById query endpdoint 
listTransactions query endpdoint

![image](https://user-images.githubusercontent.com/43390533/154692581-7e73f5e4-e465-4d11-8c3d-fa1ce999a2b0.png)

**Comment by phryneas** [comment]
If those queries are not in use at that point in time (the components are unmounted), it will not immediately refetch them, but remove their values from cache. When you open those components again, they will retrieve new data.

**Comment by nichita-pasecinic** [comment]
@phryneas does the `providesTag` works for a mutation as well ?

**Comment by phryneas** [comment]
@nichita-pasecinic no, mutation results are not data you keep around for long and they are not synchronized in any way

**Comment by nichita-pasecinic** [comment]
Thx @phryneas , is there any way to refetch manually the mutation with exactly the same arguments (mb by `fixedCacheKey`) ?

**Comment by nichita-pasecinic** [comment]
@phryneas that would be great, will try now, hope it works ))
Thank you very much!

**Comment by w1redl4in** [comment]
> If those queries are not in use at that point in time (the components are unmounted), it will not immediately refetch them, but remove their values from cache. When you open those components again, they will retrieve new data.

My mutation is called from a modal and the screen that opens this modal uses the **useListTransactionsQuery()**

**Comment by phryneas** [comment]
> > If those queries are not in use at that point in time (the components are unmounted), it will not immediately refetch them, but remove their values from cache. When you open those components again, they will retrieve new data.
> 
> My mutation is called from a modal and the screen that opens this modal uses the **useListTransactionsQuery()**

It's hard to say anything from the screenshots you provided then. I suggest clicking through the devtools, seeing if the provided tags are shown there properly. Also, I noted you have multiple different apis. Did you set each of them to their own `reducerPath`? Otherwise they will conflict with each other.

**Comment by w1redl4in** [comment]
> > > If those queries are not in use at that point in time (the components are unmounted), it will not immediately refetch them, but remove their values from cache. When you open those components again, they will retrieve new data.
> > 
> > 
> > My mutation is called from a modal and the screen that opens this modal uses the **useListTransactionsQuery()**
> 
> It's hard to say anything from the screenshots you provided then. I suggest clicking through the devtools, seeing if the provided tags are shown there properly. Also, I noted you have multiple different apis. Did you set each of them to their own `reducerPath`? Otherwise they will conflict with each other.

Alright ill try to debug,  and yes, both APIs have their own reducerPath ut in this case im just using WhitelabelAPI

**Comment by phryneas** [comment]
Just wondering because I see a lot of `api` there which is the default value.

**Comment by phryneas** [comment]
@nichita-pasecinic yup my bad. Seems like you need to trigger the mutation again then. Generally: mutations are not really meant to hold data you retrieved. They are meant to cause a change on the server. That's also why they will never automatically "re-trigger" like a query.

**Comment by w1redl4in** [comment]
Btw do i have any other option for refetching the **useListTransactionsQuery**? the mutation and the query are from different places so i cannot use refetch() from **useListTransactionsQuery** after mutation

**Comment by nichita-pasecinic** [comment]
@phryneas ok, yes I understand this, but when you have advance filtering parameters on a simple request, you just cant stick with the `GET` request, so I'm forced to use a mutation instead and I would love to use it in redux similarly, mb that would be a nice feature to have )))
Thank for help

**Comment by phryneas** [comment]
@nichita-pasecinic queries can make POST requests what leads you to believe otherwise?

**Comment by nichita-pasecinic** [comment]
@phryneas I'm totally confused now 
I can have a `query` in rtk that does a `POST` and use it with `providesTag` as I would you it with a `GET` request ?

**Comment by phryneas** [comment]
@nichita-pasecinic  A "query" is the mental concept of "something that gets data". It is not bound to GET, POST or even HTTP. It could be an RCP call or a local function call. If you are using `fetchBaseQuery`, all `query` functions (both for mutations and queries) share the same possible arguments and will result in a `fetch` call.
Change your endpoint type from `mutation` to `query` and it will be a query that does a POST.

**Comment by w1redl4in** [comment]
> @w1redl4in maybe compare what you see in the devtools with what you see in the devtools on https://codesandbox.io/s/github/reduxjs/redux-toolkit/tree/master/examples/query/react/mutations

Thank you, found an interesting point:

`middlewareRegistered:"conflict"` on api.config
![image](https://user-images.githubusercontent.com/43390533/154704072-fafe2de5-9774-4929-9758-e6c312abd4e4.png)

**Comment by w1redl4in** [comment]
Apparently got it working without really know the reason, the only thing i changed was APIs middleware as an array

Before:
```
const configStore = configureStore({
  reducer: rootReducer,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      serializableCheck: false,
    })
      .concat(whitelabelAPI.middleware)
      .concat(bankAPI.middleware)
      .concat(sagaMiddleware)
      .concat(rtkQueryErrorLogger),
});
```

Now:
```
const configStore = configureStore({
  reducer: rootReducer,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      serializableCheck: false,
    })
      .concat([whitelabelAPI.middleware])
      .concat(sagaMiddleware)
      .concat(rtkQueryErrorLogger),
});
```

And start using `isFetching` instead of `isLoading`

**Comment by phryneas** [comment]
@w1redl4in what jumps to the eye is that this one does not have the `bankAPI` middleware. That is why I am asking again: did you specify the `reducerPath` option to `createApi` with different values for both? That is also what `"conflict"` there means and on your console you should be seeing the message
> There is a mismatch between slice and middleware for the reducerPath "${reducerPath}".
You can only have one api per reducer path, this will lead to crashes in various situations!
If you have multiple apis, you *have* to specify the reducerPath option when using createApi!

**Comment by phryneas** [comment]
Didn't you get that error message on the console?
