### ISSUE TITLE
RTQ: How to unsubscribe from a `useLazyQuery` 

### ISSUE THREAD

**Issue by nichita-pasecinic** [reduxjs/redux-toolkit#2055]
Hello 👋

In documentation https://redux-toolkit.js.org/rtk-query/usage/usage-without-react-hooks#removing-a-subscription
is specified a different way of subscription - un-subscription method for a `query`, but how to we do it with a hook ?

```
const [trigger, { data }] = useLazyEnpointQuery();
```
I cant pass a `skip` property to `useLazyQuery` that forces the unsubscription from the query, it can be used only with the `useQuery` hook. So how can I unsubscribe from a lazy query ?

Thanks for help!

**Comment by nichita-pasecinic** [comment]
Hi,
Any updates on it? wouldn't be nice if the `useLazyEndpointQuery()` returned something like `unsubscribe` here :
```javascript
const [trigger, { data, unsubscribe }] = useLazyEnpointQuery();
```

**Comment by phryneas** [comment]
At the moment, the only way to unsubscribe from a lazy query is to start a new one with a different argument or to unmount the component. 

It might be a nice to have to have an unsubscribe option, but it's not high in the priorities. PRs against `useLazyQuerySubscription` are welcome.

**Comment by bleedingAyush** [comment]
I think the feature is added.

**Comment by markerikson** [comment]
Out in https://github.com/reduxjs/redux-toolkit/releases/tag/v2.4.0 !
