### ISSUE TITLE
invalidatesTags not work when two mutation trigger it

### ISSUE THREAD

**Issue by mnm1001** [reduxjs/redux-toolkit#2056]
here is the demo https://codesandbox.io/s/redux-toolkit-bug-1rk72e?file=/src/mocks/db.ts

when i click add button to add post and delete the first post at the same time,(PostsManager.tsx:49)
<img width="689" alt="image" src="https://user-images.githubusercontent.com/20190235/154914618-6c5440c8-0bf7-4367-9aeb-fc810b7b8ac6.png">

and set the get posts api delay to 300(db.ts:49)
<img width="706" alt="image" src="https://user-images.githubusercontent.com/20190235/154914850-4be77bbf-39bb-40d9-9d34-f29846b4d05b.png">

the posts only refresh when add post(3 old posts, and 1 new post), but not refresh when delete post
<img width="698" alt="image" src="https://user-images.githubusercontent.com/20190235/154914906-061cf788-f294-4575-8dc8-874a54233e03.png">
so there are 4 posts, but we expect only 3 posts,

and there should be another get posts request after delete mutation finished, but not
<img width="1291" alt="截屏2022-02-21 下午4 32 45" src="https://user-images.githubusercontent.com/20190235/154917495-bee1f2b0-65fe-43ae-b27c-ee0f8609bc24.png">

when set the get posts api delay to 0, the  delete mutation trigger posts to refresh work well, so i guess when  two mutation  trigger the same query invalidate, when the second mutation is finished but the first query not finished, the second the query after second mutation will not be triggered. 

Is there a way to fix this question?

**Comment by markerikson** [comment]
Sounds like this is likely related to #2203 and #3105
