### ISSUE TITLE
Any action with PayloadAction<Partial<X>> is not inferrable

### ISSUE THREAD

**Issue by remleduff** [reduxjs/redux-toolkit#2061]
Typescript version is 4.5.4, so let me know if I just need to update (though I'm kinda stuck on this version for the moment).

(Actually, I'm not sure if that's the typescript that is being used. I'm telling what the inferred type is by hovering over the actionCreator in vscode and I think vscode uses its own bundled typescript)

Any Payload type that is fully optional currently results in a "ActionCreatorWithNoninferrablePayload" for me.

```

interface IModalParams {
    modalId?: number;
 }

interface IModalParams2 {
    modalId: number;
 }


export const modalSlice = createSlice({
    name: 'genericModals',
    initialState,
    reducers: {
        showModal: (state, action: PayloadAction<IModalParams>) => {
        },
        hideModal: (state, action: PayloadAction<Partial<IModalParams2>>) => {
        }
}

// I'm testing this in vscode by hovering over the following two variables
const { showModal, hideModal } = modalSlice.actions;
```

**Comment by markerikson** [comment]
Yeah, this is a known issue / TS limitation.  See https://github.com/reduxjs/redux-toolkit/issues/1423#issuecomment-902680573 for earlier discussion and the recommended workaround :

```ts
interface Filters {
  name: string
  age: number
  city: string
}

type AtLeastOne<T extends Record<string, any>> = keyof T extends infer K ? K extends string ? Pick<T, K & keyof T> & Partial<T> : never : never

// Use this type instead of `Partial<Filters>`
type AtLeastOneFilter = AtLeastOne<Filters>
```

This is probably something we ought to mention in the "TS Usage" docs somewhere.
