### ISSUE TITLE
Accessing action meta in baseQuery

### ISSUE THREAD

**Issue by travenec** [reduxjs/redux-toolkit#2069]
Hello everyone,

a brief question - I am trying to solve a typical problem: **Request authorization**.

The idea of mine is to have a session middleware which authorizes selected actions by adding authorization information (credential) to action's meta. This approach is very convinient way to solve certain session related problems.

For this reason I need to access action meta in baseQuery or anywhere else in the endpoint builder or similar.

Is there a way to do so?

**Comment by phryneas** [comment]
I'm honestly not sure what exactly you are trying to do here. What would that "authorizing" do? Certainly it's not authorizing with the server - that has already happened at that point?

**Comment by phryneas** [comment]
From basequery, you cannot read anything from any action. There is a `pending` action dispatched before the baseQuery runs, and one `fulfilled` action after - but those actions are just dispatched, the code that executes baseQuery does not have any "reading" access to those actions.

**Comment by phryneas** [comment]
It is a variable that does not exist in any codepath anywhere connected to it. We would have to rewrite the whole library.

**Comment by travenec** [comment]
@phryneas I think I know where my confusion comes from. Just to clarify...

The pending action is created **after** the request is been made (or at the same time). Therefore the baseQuery cannot access the meta of the pending action (which has not been dispatched yet).

The other approach would be, obviously, dispatching the pending action first and based on that action make the request (probably using a middleware). The sequence is different here and so the context.
