### ISSUE TITLE
Pattern RTK Query with JWT and refresh

### ISSUE THREAD

**Issue by rwanito** [reduxjs/redux-toolkit#2082]
Hello,

Thank you for your work, I really appreciate !
I have a question, I'm using your OpenAPI generator to use my API from NestJS.

And the auth system works with a JWT with an accessToken who expires 5m after its creation and a refresh token 1 month after.
How can I automatize :

Is my token expired ? Yes, get new pair.
No, continue the normal request.
Is my refresh token expired, change the state and go back to the login page.

I know how to do this, but I don't want something tricky !
And maybe, some of you had already done that before !

Thank you!

**Comment by phryneas** [comment]
This is documented in [Automatic re-authorization by extending fetchBaseQuery](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery)

**Comment by rwanito** [comment]
Hello,

Oh right, thanks !

Thanks for your work !
