### ISSUE TITLE
createSlice and createApi both are using then how to set my store

### ISSUE THREAD

**Issue by hiteshtSociosquares** [reduxjs/redux-toolkit#2087]
i tried so many things but we can't get proper solution to hot to set in store.js when we use both createSlice and CreateApi

**Comment by phryneas** [comment]
what *have* you tried? those don't impact each other at all, you put them into the same configureStore call.

**Comment by hiteshtSociosquares** [comment]
> what _have_ you tried? those don't impact each other at all, you put them into the same configureStore call.

got it now i set my store.js file like this.

`const reducer = { 
  [api.reducerPath]: api.reducer,
  auth: authReducer,
 };
  
export const store = configureStore({
   reducer,
   middleware: (getDefaultMiddleware) =>       getDefaultMiddleware().concat(api.middleware),
   devTools: process.env.NODE_ENV !== 'production',
});
setupListeners(store.dispatch);`
