### ISSUE TITLE
rtk-query-codegen-openapi: way to export useLazy hooks

### ISSUE THREAD

**Issue by jnavb** [reduxjs/redux-toolkit#2091]
Thank you for building such a fantastic library.

Currently the file generated by codegen only exports normal hooks. Ie

`export const { useGetUsersQuery } = injectedRtkApi;`

is there a way to export `useLazyGetUsersQuery` without modifying the auto generated file?

**Comment by jnavb** [comment]
I'm closing this issue, I wanted to have a `hooksLazy` sort of option at config-file like we have with `hooks`.

I can achieve the same result with a barrel file, it could be a nice out of the box export at the generated though.

**Comment by phryneas** [comment]
Yeah we should really look into https://github.com/reduxjs/redux-toolkit/pull/1953 getting merged. So long you can use the package from that PR's CI build. Feedback if it works well for you is very welcome.
