### ISSUE TITLE
Abstracting createAsyncThunk

### ISSUE THREAD

**Issue by yoerivdm** [reduxjs/redux-toolkit#2101]
Hi,

I am migrating our code from redux thunk action creators to RTK createAsyncThunk. The latter is more readable and compact. We have around 150+ redux calls and actions, all generated in TS from swagger definitions. 

Our previously generated api had the option to pass the condition as an argument so i'll need to encapsulate the createAsyncThunk to keep the calling-code intact eg ActionCreators.retrieveMessage({[inputMessage object]}, (...) => { [ConditionFunction] })

Is there an example of creating an createAsyncThunk abstraction?

**Comment by phryneas** [comment]
Before we are getting deeper into this (it's going to be tricky), just to make sure: you know about [RTK Query](https://redux-toolkit.js.org/rtk-query/overview) and the fact that it can autogenerate from [Swagger/OpenApi](https://redux-toolkit.js.org/rtk-query/usage/code-generation) definitions?

**Comment by yoerivdm** [comment]
Yes, yet we still use our own generators at the moment. This wouldn't solve my problem either.
The condition we pass to the actionCreators is not 'static', we can call the same action from different locations giving different conditions ... . Conditions are custom and not to be generated.

As an alternative, I could pass the condition as input-parameter in the args argument, and call it in the ActionCreator instead of using the createAsyncThunk options. I just don't like passing it that way :-)

**Comment by yoerivdm** [comment]
Okay, just did a quick scan for actions using the condition ... turns out there is only a handfull of actions using the condition.
I'm going to leave an option to override the generated action creators.

Closing this issue ...
