### ISSUE TITLE
Unsolicited Opinion: Just stop. This project's API is terrible.

### ISSUE THREAD

**Issue by crobinson42** [reduxjs/redux-toolkit#2106]
RTK Query is a CLUSTER f***. Making async calls does not need to be so convoluted.

When did it become so obnoxious to use an async action-creator?

To the lib authors/contributors - Stop implementing arduous and convoluted _solutions_. Take a step back, evaluate the API that your feature or solution is creating, then, think about how it can be made more **simple**, readable and familiar with all other front-end patterns & APIs.

~~[troll GIF](https://user-images.githubusercontent.com/5973579/157297785-98301ac1-90b2-4b04-a72f-9eaae6aab640.gif)~~

**Comment by markerikson** [comment]
I'm sorry to hear you feel that way.

FWIW we get highly positive feedback on RTK on a daily basis, like this thread:

https://www.reddit.com/r/reactjs/comments/px6kxy/redux_toolkit_is_awesome/

If you have _specific, concrete_ suggestions, we're always interested, but tbh rants like this don't help anyone.

**Comment by phryneas** [comment]
Actually, this kinda made my day.  

I think I'm gonna spend the evening adding another convoluted api.  
I'm not sure what though. Maybe we could do a twitter poll and reach out to the community (like we always do) and then have a few months of beta, asking for feedback and iterating on the api design (like we always do) to make something that this time is *really* horrible.
