### ISSUE TITLE
RTK-Query: Overriding header set in `prepareHeaders`

### ISSUE THREAD

**Issue by JoshAddington** [reduxjs/redux-toolkit#2107]
I'm setting the `"Content-Type", "application/json"` header for my endpoints in `prepareHeaders`.

```js
baseQuery: fetchBaseQuery({
    prepareHeaders: (headers) => {
      headers.set("Content-Type", "application/json");
      return headers;
    },
  }),
```

For a mutation declared in this `createApi` slice, I'm setting headers to `multipart/form-data` 
```js
 query: ({ formData }) => ({
          url: /setting,
          method: "PUT",
          headers: {
            "content-type": "multipart/form-data"
          },
          body: formData
      })
```

However, the request is failing because the content-type is still being set to `application/json` for this mutation. Is there any way to use `prepareHeaders` to set a global content-type and still be able to set a different content-type for individual endpoints?

I know that the documentation says that the `content-type` will automatically be set to `application/json` with no need to use `prepareHeaders`, however that's not the behavior I'm seeing. When the `content-type` header isn't set on a request, it's left out of the request headers.

**Comment by markerikson** [comment]
Looking at the code:

https://github.com/reduxjs/redux-toolkit/blob/v1.8.0/packages/toolkit/src/query/fetchBaseQuery.ts#L187-L208

I _think_ this is initializing the `headers` object instance with whatever you passed in from the endpoint, and then calls `prepareHeaders()` with that initialized value.

That suggests that you're immediately overwriting the value.

Can you try doing a conditional check in `prepareHeaders` to see if `content-type` is already set, and only set it if it's not filled out yet?

**Comment by JoshAddington** [comment]
OK, that's manageable. There was a line in the documentation that made me think that the priority in setting headers was inverse, with `prepareHeaders` setting a base header and individual endpoints being able to modify the header as needed.

**Comment by markerikson** [comment]
Hmm. That does sound more logical, really :)

@phryneas, @msutkowski : what's the intent here? Is this a thing we can rearrange?

**Comment by phryneas** [comment]
`prepareHeaders` is the last piece in the chain - it has access to the store in the end, so it could merge some header coming from the endpoint with a store value or similar things. 

Generally, it's the most powerful & most dynamic api, so it is called last in the chain and can override everything.

**Comment by avyakt17285** [comment]
A workaround for the same can be to check whether a header is already set in the `prepareHeaders` function itself. The `headers` variable passed in the `prepareHeaders` helps you access the headers which are already set. Using that you can conditionally add a header in the `prepareHeaders` function in the following way: 
```
baseQuery: fetchBaseQuery({
  prepareHeaders: (headers) => {
    if (!headers.has("Content-Type") {
      headers.set("Content-Type", "application/json");
    }
    return headers;
  },
```

**Comment by s4yed** [comment]
I got the same problem can't set `Authorization` header?

```
prepareHeaders: (headers, { getState }) => {
        const token = getState().auth.token;
        console.log(getState());
        if (!headers.has("Authorization") && token) {
            headers.set("Authorization", `Bearer ${token}`);
        }
        return headers;
    },
```

**Comment by phryneas** [comment]
@s4yed have you checked if it actually enters that `if`?

**Comment by s4yed** [comment]
nope but I think it never runs `prepareHeaders` at all when I remove the condition. However, I found a workaround solution, I hard-coded the header inside the query itself and it worked. :)

```
const userApiSlcie = apiSlice.injectEndpoints({
    endpoints: (builder) => ({
        updateData: builder.mutation({
            query: ({ token, body }) => {
                return {
                    url: "/some_endpoint",
                    method: "POST",
                    body,
                    headers: {
                        Authorization: `Bearer ${token}`,
                    },
                };
            },
        }),
    }),
});
```

**Comment by phryneas** [comment]
Have you added a few more console.logs? It should definitely run `prepareHeaders`.

**Comment by s4yed** [comment]
@phryneas  Yeh I've tried but still nothing!

**Comment by s4yed** [comment]
> Have you added a few more console.logs? It should definitely run `prepareHeaders`.

@phryneas  Yeh I've tried but nothin!!

**Comment by phryneas** [comment]
Could you show the code *around* `prepareHeaders`? The full `createApi` and `fetchBaseQuery` calls?

**Comment by s4yed** [comment]
> Could you show the code _around_ `prepareHeaders`? The full `createApi` and `fetchBaseQuery` calls?

Sure here's the code.
```
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

const apiSlice = createApi({
    reducerPath: "api",
    baseQuery: fetchBaseQuery({ baseUrl: "http://localhost:5000/api/" }),
    credentials: "include",
    prepareHeaders: (headers, { getState }) => {
        const token = getState().auth.token;
        console.log(getState());
        console.log("HEADERS", headers);
        // if (!headers.has("Authorization") && token) {
        //     headers.set("Authorization", `Bearer ${token}`);
        // }
        return headers;
    },
    endpoints: (builder) => ({}),
});

export default apiSlice;
```

**Comment by phryneas** [comment]
`prepareHeaders` is an argument to `fetchBaseQuery`, so is `credentials`.
```js
const apiSlice = createApi({
    reducerPath: "api",
    baseQuery: fetchBaseQuery({ 
        baseUrl: "http://localhost:5000/api/",
        credentials: "include",
        prepareHeaders: (headers, { getState }) => {
            const token = getState().auth.token;
            console.log(getState());
            console.log("HEADERS", headers);
            // if (!headers.has("Authorization") && token) {
            //     headers.set("Authorization", `Bearer ${token}`);
            // }
            return headers;
        },
    }),
    
    endpoints: (builder) => ({}),
});

```

**Comment by s4yed** [comment]
@phryneas  Oh my bad. Now it's working thanks 👍
