### ISSUE TITLE
Eslint "unbound method" error when using createEntityAdapter

### ISSUE THREAD

**Issue by alexplumb** [reduxjs/redux-toolkit#2111]
I wasn't sure if this was something on my end or not, but I noticed [this pull request](https://github.com/reduxjs/redux-toolkit/pull/1263) that addressed the issue for other methods and figured I'd report it. 

I've been migrating my legacy redux codebase to RTK and I'm now converting some of my entities to use the createEntityAdapter helper. This results in an error on the `removeAffiliate` definition:

```
import { createSlice, PayloadAction, createEntityAdapter } from '@reduxjs/toolkit';
import { Affiliate } from '@sda/interfaces/affiliate';
import { UpsertItem } from '@sda/utils/store/interfaces';
import { reducerUpsertHelper } from '@sda/utils/store';
import { FetchDataType } from '@sda/sdk/interfaces';

const affiliateAdapter = createEntityAdapter<Affiliate & FetchDataType>({
  sortComparer: (a, b) => a.name.localeCompare(b.name),
});

export const affiliatesSlice = createSlice({
  initialState: affiliateAdapter.getInitialState(),
  name: 'affiliates',
  reducers: {
    removeAffiliate: affiliateAdapter.removeOne,
    upsertAffiliate: (state, action: PayloadAction<UpsertItem<Affiliate & FetchDataType>>) => {
      const items = reducerUpsertHelper(state.entities, action.payload, 'id');

      state.entities = items;
    },
  },
});

export const {
  removeAffiliate, upsertAffiliate,
} = affiliatesSlice.actions;

export default affiliatesSlice.reducer;
```
![Capture](https://user-images.githubusercontent.com/7225271/157492013-b5297922-f8bc-408b-8738-b88c15f803bf.PNG)

Rewriting it as an arrow function resolves the error, e.g.:

`removeAffiliate: (state, action) => affiliateAdapter.removeOne(state, action)`

**Comment by alexplumb** [comment]
Here's the one line of code I used to fix it

![Capture](https://user-images.githubusercontent.com/7225271/157493447-78d0da8f-1df1-49d6-9733-f63247ceb0b0.PNG)

**Comment by markerikson** [comment]
Closing because this seems like primarily a lint issue.  If anyone wants to file a PR to improve our behavior here somehow, please do!
