### ISSUE TITLE
TypeError: Property 'meta' does not exist on type 'PayloadAction<undefined, string, { arg: ActionArgs; requestId: string; requestStatus: "pending"; } & GetPendingMeta<ThunkApi>, never>'

### ISSUE THREAD

**Issue by alexeymolchan** [reduxjs/redux-toolkit#2119]
@reduxjs/toolkit: 1.8.0

reproducible demo: https://codesandbox.io/s/typescript-forked-0d72on

Hi, thanks for great library. I'm trying to create generic function that will accept builder and async thunk action, but meta is missing when i pass generic ThunkApi to AsyncThunk type, if i simply pass Record<string, unknown> instead of generic ThunkApi type everything works fine. I think GetPendingMeta / GetFulfilledMeta / GetRejectedMeta somehow returns never type and intersection fails.

```
export const addAsyncCasesToBuilder = <State, Returned, ActionArgs, ThunkApi>({
  builder,
  action
}: {
  builder: ActionReducerMapBuilder<State>;
  action: AsyncThunk<Returned, ActionArgs, ThunkApi>;
}) =>
  builder.addCase(action.pending, (state, action) => {
    action.meta; -> Property 'meta' does not exist on type 'PayloadAction<undefined, string, { arg: ActionArgs; requestId: string; requestStatus: "pending"; } & GetPendingMeta<ThunkApi>, never>'.ts(2339)
  }).addCase(action.fulfilled, (state, action) => {
    action.meta -> Property 'meta' does not exist on type 'PayloadAction<Returned, string, { arg: ActionArgs; requestId: string; requestStatus: "fulfilled"; } & GetFulfilledMeta<ThunkApi>, never>'.ts(2339)
  }).addCase(action.rejected, (state, action) => {
    action.meta -> Property 'meta' does not exist on type 'PayloadAction<GetRejectValue<ThunkApi> | undefined, string, { arg: ActionArgs; requestId: string; requestStatus: "rejected"; aborted: boolean; condition: boolean; } & (({ ...; } & { [K in keyof GetRejectedMeta<...>]?: undefined; }) | ({ ...; } & GetRejectedMeta<...>)), GetSerializedErrorType<...>>'.ts(2339)
  });
```

I think something wrong with this type: 

```
export declare type PayloadAction<P = void, T extends string = string, M = never, E = never> = {
    payload: P;
    type: T;
} & ([M] extends [never] ? {} : {
    meta: M;
}) & ([E] extends [never] ? {} : {
    error: E;
});
``` 
if i simply remove conditions and intersections
```
export declare type PayloadAction<P = void, T extends string = string, M = never, E = never> = {
    payload: P;
    type: T;
    meta: M;
    error: E;
}; 
```
generic will work, but type assertions won't and i can take action.error that will be type of never in thunk.pending state for example. as i understand you want to filter out properties that are type of never but somehow typescript fails in my use case.

maybe instead of intersection you can remove never properties with something like this ? correct me if i'm wrong.

```
type FilterNever<T extends Record<string, any>> = {
    [K in keyof T as [T[K]] extends [never] ? never : K]: T[K]
}
```

**Comment by alexeymolchan** [comment]
also meta will be omitted if someone will pass { pendingMeta: never; fulfilledMeta: never;  rejectedMeta: never; } but i think its wrong behavior since you have base meta like

```ts {
    arg: ThunkArg
    requestId: string
    requestStatus: 'fulfilled'
}``` etc

what do you think ?

**Comment by phryneas** [comment]
> type FilterNever<T extends Record<string, any>> = {
>    [K in keyof T as [T[K]] extends [never] ? never : K]: T[K]
>}

This is an interesting one that wasn't possible before 4.1. It might be a good idea to play with that further, but introducing it will be not only "removing support", but "actively breaking" older TS version's users, so we have to be a bit careful with that.

> maybe instead of checking for never check for void - what do you think ?

That's not a possibility unfortunately - those types are used in tens of thousands of projects and probably hand-hardcorded in a lot of them (even though we don't recommend that). So we can't really do that - it would maybe even be too breaking in a master, as it is a very non-obvious change.

The real problem in your code example though is that `GetPendingMeta<ThunkApi>`  with an unknown `ThunkApi` cannot be resolved yet - and since `meta` is 
```ts
{
    arg: ThunkArg
    requestId: string
    requestStatus: 'pending'
  } & GetPendingMeta<ThunkApiConfig>
```
that will lead to the whole `meta` disappearing.

This is simply a project with TS being unable to work with non-yet-resolved generics inside a function.

I'd suggest you do something like
```ts
export const addAsyncCasesToBuilder = <State, Returned, ActionArgs>({
  builder,
  action
}: {
  builder: ActionReducerMapBuilder<State>;
  action: AsyncThunk<Returned, ActionArgs, any>;
}) => {
```
instead as there is generally no way that unless you already know what `ThunkApi` looks like you could write any runtime code that relies on it.

**Comment by phryneas** [comment]
PS: but yeah, passing in `never` here should be possible. That would warrant a bugfix PR if you want to open one :)

**Comment by alexeymolchan** [comment]
@phryneas thanks for the answer. i think using typecast like ```(action as any).meta``` is better then passing ```any``` straight to AsyncThunk generic. with typecasting i will get full meta base part + fulfilledMeta from thunkApi.

```ts
import { ActionReducerMapBuilder, AsyncThunk } from "@reduxjs/toolkit";

type Meta<ActionArgs, ThunkApi> = {
  arg: ActionArgs;
  requestId: string;
  requestStatus: "fulfilled";
} & ThunkApi;

export const addAsyncCasesToBuilder = <State, Returned, ActionArgs, ThunkApi>({
  builder,
  action,
  preparePayload
}: {
  builder: ActionReducerMapBuilder<State>;
  action: AsyncThunk<Returned, ActionArgs, ThunkApi>;
  preparePayload(payload: Returned, meta: Meta<ActionArgs, ThunkApi>): State;
}) =>
  builder.addCase(action.fulfilled, (state, action) => {
    preparePayload(action.payload, (action as any).meta);
  });
```
