### ISSUE TITLE
addOne query by adapters - how to add a resource to specific location

### ISSUE THREAD

**Issue by manorlh** [reduxjs/redux-toolkit#2121]
Hi, 
I am using adapters, and I wish to "addOne" to a specific place in the ordered entities

is it possible? 

I can do it manually by accessing directly to  entities state. I wonder if there is an alternative.

thanks

**Comment by markerikson** [comment]
I'm not sure I understand the question. Can you give an example of what you're trying to do?  (like some fake code, or show what you want the data to look like before and after)

**Comment by manorlh** [comment]
lets say we have a list of x1,x2,x3... as the entities of the adapter.

I would like to insert a new x between x2 and x3

**Comment by phryneas** [comment]
If your adapter is sorted, you just insert it. That will insert it at the end in the internal data structure, but if you use any selector, it will come back in the right order.

**Comment by markerikson** [comment]
The "sorting" is done by providing a `comparator` option when you create the adapter, and it updates the sorting of the `ids` array each time an update is done to the data.  There's nothing manual to do here.

**Comment by manorlh** [comment]
yep, but what happens if just wanna add an item to a specific place without defining any sorting.

**Comment by phryneas** [comment]
Then you need to use a different tool that has that functionality.
