### ISSUE TITLE
BaseQuery InjectEndpoints - TypeError: Undefined is not an object

### ISSUE THREAD

**Issue by colaquecez** [reduxjs/redux-toolkit#2126]
Hey Guys, I have 2 slices (wallet.slice and auth.slice) when I try to use a extraReducer with `matchFulfilled` but using the `authApi`, it works
<img width="469" alt="Screen Shot 2022-03-14 at 14 59 22" src="https://user-images.githubusercontent.com/38195454/158232979-9a538d4c-50b9-448b-8e7f-b83c8d8786ae.png">

but when I try to use the `walletAPi` its throw an error:
<img width="517" alt="Screen Shot 2022-03-14 at 15 00 08" src="https://user-images.githubusercontent.com/38195454/158233088-ba18b3e4-128f-46b0-8a43-53a9ae5d5177.png">

 wallet.slice its throw this error:
<img width="419" alt="Screen Shot 2022-03-14 at 14 58 13" src="https://user-images.githubusercontent.com/38195454/158232776-08a10527-e981-40e2-927a-c3695bf24ee9.png">

and if I remove this dispatch on my `baseQuery` the code works with the 2 extraReducers
<img width="630" alt="Screen Shot 2022-03-14 at 15 19 09" src="https://user-images.githubusercontent.com/38195454/158235923-17cca0cf-2c1e-4103-86b7-8afefbc45318.png">

**Comment by phryneas** [comment]
You probably have a circular import there. Maybe move the `logoutUser` action into a separate file with `createAction` and also add it to your `extraReducers` to break the circle.

**Comment by colaquecez** [comment]
Yeah man, that was it! thank you so much @phryneas, I just added on my other slice an `extraReducers` with `addCase` calling my action `logout` this break the circle :)
