### ISSUE TITLE
RTKQ: TS2339 when trying to create a generic injectEndpoints

### ISSUE THREAD

**Issue by devzenfr** [reduxjs/redux-toolkit#2127]
Hi! 

First, I would like to sincerely thank you for the amazing work done with RTK Queries. My projects always include many API calls and RTKQ is a blessing. 

I'm currently stuck with an idea: create a generic method that would generate all CRUD endpoints for a specific entity. That would avoid much code duplication.

Here is my current code:

```
const generateCrudApi = <T extends HydraMember, >(tag: string, route: string) => {
  const pascalCase = toPascalCase(route);

  const enhancedApi = emptySplitApi.enhanceEndpoints({ addTagTypes: [tag] });

  const entityApi: any = enhancedApi.injectEndpoints({
    endpoints: (build) => ({
      [`get${pascalCase}`]: build.query<HydraCollection<T>, any>({
        query: (params) => ({ url: route, method: 'GET', params }),
        providesTags: (result) => (result
          ? [
            ...result['hydra:member'].map(({ '@id': iri }) => ({ type: tag, id: iri })),
            { type: tag, id: 'LIST' },
          ]
          : [{ type: tag, id: 'LIST' }]),
      }),
      [`add${tag}`]: build.mutation<T, Partial<T>>({
        query: (data) => ({ url: route, method: 'POST', data: removeEmptyFields(data) }),
        invalidatesTags: [{ type: tag, id: 'LIST' }],
      }),
      [`get${tag}`]: build.query<T, string>({
        query: (iri) => ({ url: iri, method: 'GET', withoutBaseUrl: true }),
        providesTags: (result, error, iri) => [{ type: tag, id: iri }],
      }),
      [`update${tag}`]: build.mutation<T, Partial<T>>({
        query: (data) => ({
          url: data['@id'] ?? route, method: 'PUT', data: removeEmptyFields(data), withoutBaseUrl: true,
        }),
        invalidatesTags: (result, error, { '@id': iri }) => [{ type: tag, id: iri }],
      }),
      [`delete${tag}`]: build.mutation<void, string>({
        query: (iri) => ({ url: iri, method: 'DELETE', withoutBaseUrl: true }),
        invalidatesTags: [{ type: tag, id: 'LIST' }],
      }),
    }),
  });

  return entityApi;
};
```

(function toPascalCase is very explicit, function removeEmptyFields only change empty strings to null)

And here is how I use this generateCrudApi, inside a dedicated slice :

```
import { MyEntity } from '@Components/types/MyEntity';
import generateCrudApi from '@Components/utils/generateCrudApi';

export const myEntityApi = generateCrudApi<MyEntity>('MyEntity', 'my_entities');

export const {
  useGetMyEntitiesQuery,
  useAddMyEntityMutation,
  useGetMyEntityQuery,
  useUpdateMyEntityMutation,
  useDeleteMyEntityMutation,
} = myEntityApi;
```

This code works perfectly! The hooks are correctly generated even with the computed name. The only downside resides in this line :  `const entityApi: any = enhancedApi.injectEndpoints`. 

I have to type entityApi to `any`. If I don't, then I get many TS2339 errors looking like this one

```
[tsl] ERROR in /var/www/assets/components/Services/MyEntitySlice.ts(10,3)
TS2339: Property 'useGetMyEntitiesQuery' does not exist on type 'Api<BaseQueryFn<{ url: string; method: Method | undefined; params?: any; data?: any; withoutBaseUrl?: boolean | undefined; }, unknown, unknown, {}, {}>, ReplaceTagTypes<{}, string> & { ...; }, "myApi", string, unique symbol | unique symbol>'.
```

Which is an issue for me. Typing `entityApi` to `any` isn't optimal at all during development for obvious reasons. 
This works, but I wondered if there would be a way to make this work without any Typescript errors?

If someone has any idea, I would gladly accept it. Otherwise I would have to write all the endpoints for all my entities, which will all look the same. I think a generic solution could be useful.

**Comment by phryneas** [comment]
The point is: your problem is on type level here - your use of `toPascalCase` would turn everything to `string`, so the names of the functions get lost.

I just tried experimenting around with it, but you run into the problem of "yet-to-be-resolved generics" here: TypeScript doesn't carry the type information along far enough to be useful. 
These are my experiments: https://codesandbox.io/s/youthful-mcclintock-qpo89c?file=/src/index.ts

As for the code generation: tbh., it hardly matters to have that extra code. Any compression algorithm will pick up duplicate code like that and it will only make off a few extra bytes.

**Comment by devzenfr** [comment]
Maybe I should have removed toPascalCase from my code before sending it here, it's not mandatory in my code (if I need to send another param to generateCrudApi with the pascal-cased name, it's fine for me). 

I think the only issue there is with computed names. At least the endpoint injection works, but TypeScript seems to have a hard time understanding what's happening there. 

I tried your attempt from codesandbox into my project, unfortunately the issue remains. I also thought it was working when removing the get endpoint (why? no idea), vscode isn't complaining anymore and correctly guess the types for add/update/delete hooks. But ts compilation fails, same as before. 

-------

I'm not that concerned about the size of the extra lines I need to add into each slice if I define the endpoints manually without using generateCrudApi. But I loved the idea of making it generic and that would have been a delight to maintain: if we ever wanted to send an extra prop to every update operation, for example. 

If it's really not possible, I'm still helped a lot by RTK Queries 🙏 
Thanks again for your help and trying to make it work, that's very appreciated. 

That was my first issue published on Github, sorry if I'm a bit clumsy but what should I do now? Should I leave this issue opened for a while?

**Comment by phryneas** [comment]
It seems to fall back to `{ [key: string]: CorrectlyTypedStuff }` in any case, so your best chance would probably to inject each endpoint with an individual call and extracting those individually from the respective generated apis - it's not clean but may be a "kinda solution".

If you have nothing more to do, please just close the issue - generally don't worry, everything was okay with it ;)

**Comment by devzenfr** [comment]
> It seems to fall back to `{ [key: string]: CorrectlyTypedStuff }` in any case, so your best chance would probably to inject each endpoint with an individual call and extracting those individually from the respective generated apis - it's not clean but may be a "kinda solution".
> 
> If you have nothing more to do, please just close the issue - generally don't worry, everything was okay with it ;)

Thanks a lot! I don't know if I tried what you really meant but got something working out of it. 

I divided the generic generateCrudApi into five functions similar to this one: 

```TypeScript
export const injectGetItem = <T>(name: string, tag: string) => {
  const enhancedApi = emptySplitApi.enhanceEndpoints({ addTagTypes: [tag] });

  const entityApi = enhancedApi.injectEndpoints({
    endpoints: (build) => ({
      [name]: build.query<T, string>({
        query: (iri) => ({ url: iri, method: 'GET', withoutBaseUrl: true }),
        providesTags: (result, error, iri) => [{ type: tag, id: iri }],
      }),
    }),
  });

  return entityApi;
};

```

Same idea for injectUpdateItem, injectDeleteItem, ... 

I updated my slice, which gives this: 

```TypeScript
import { MyEntity } from '@Components/types/MyEntity';
import {
  injectGetItems, injectAddItem, injectGetItem, injectUpdateItem, injectDeleteItem,
} from '@Components/utils/generateCrudApi';

const tag = 'MyEntity';
const route = 'my_entities';

export const { useGetMyEntitiesQuery } = injectGetItems<MyEntity>('getMyEntities', tag, route);
export const { useAddMyEntityMutation } = injectAddItem<MyEntity>('addMyEntity', tag, route);
export const { useGetMyEntityQuery } = injectGetItem<MyEntity>('getMyEntity', tag);
export const { useUpdateMyEntityMutation } = injectUpdateItem<MyEntity>('updateMyEntity', tag, route);
export const { useDeleteMyEntityMutation } = injectDeleteItem<MyEntity>('deleteMyEntity', tag);
```

I also had to update TypeScript but that worked! Not sure why this current code works and not the previous one, but that's fine with me. I can inject only the required operations for each entity and if we ever need to change the logic behind a specific operation method, we can do it easily. 

I'll close this issue and improve this code a little bit. Have a nice day!

**Comment by gschuager** [comment]
Hi, I'm trying to implement the same kind of generic API building helper, and noticed that the approach proposed in the last post is not that different than the "any" typing of `entityApi` in the first one, as it will let you do the following without any compiler warning:

```
export const { useGetXxxxxxxxxQuery } = injectGetItem<MyEntity>('getMyEntity', tag);
```

Any suggestion about how to correctly type the return value of `injectGetItem` would be very appreciated.

**Comment by atakanteko** [comment]
@devzenfr Hi! I've checked out your repo and i could not see generic RTKQuery structure. Are there any example to examine it? If it is, let me know! Thanks in advance.

**Comment by devzenfr** [comment]
> @devzenfr Hi! I've checked out your repo and i could not see generic RTKQuery structure. Are there any example to examine it? If it is, let me know! Thanks in advance.

Hi!
Unfortunately it was a freelance work for a private company and I don't have access to this code anymore. 

I think it was very close to what I wrote on the 16th of March 2022, with few minors adjustments. It wasn't perfect at all but close enough. 

Good luck on your side!
