### ISSUE TITLE
[docs][TS]: provide types createAsyncThunk under api section

### ISSUE THREAD

**Issue by sgnilreutr** [reduxjs/redux-toolkit#2128]
The documentation is lacking some required type definitions in this section, mainly for the user-created argument in the createAsyncThunk function.

**Comment by markerikson** [comment]
Can you give some specifics about what you feel is missing? I'm not sure what you're referring to here.

**Comment by markerikson** [comment]
I'm still not exactly sure what you mean by "lacking types".  Are you wanting to see exact TS type signatures?  Can you show an example of what you'd like to see specifically?

**Comment by sgnilreutr** [comment]
Sure, like this; https://github.com/reduxjs/redux-toolkit/pull/2129/files#r829738265

You have it on other places in the docs - but I was following the API docs for the createAsyncThunk, which lacked the typing. Normally forgetting to set type wouldn't result in the error my IDE gave me;
<img width="769" alt="Screenshot 2022-03-16 at 18 54 41" src="https://user-images.githubusercontent.com/41041655/158953264-ff40b085-636b-4194-8b31-8c0b0f60e1da.png">

The solution for it, was to type the argument passed in the createAsyncThunk, which wasn't at all clear from the error provided.
