### ISSUE TITLE
createAsyncThunk vs Redux Thunks

### ISSUE THREAD

**Issue by HarrisonHemstreet** [reduxjs/redux-toolkit#2131]
I'm in a situation where I need to fetch data from a server and use said data in one of my store slices and then use that data in complex logic with the slice.

Which is preferred, Redux Thunks or createAsyncThunk?

I've also looked at RTK Query but that appears to be a tool only to be used from within my React components. Please correct me if I'm wrong!

Thanks in advance for the guidance!

**Comment by phryneas** [comment]
Quoting myself from twitter:

cAT is a thunk where you automatically have "lifecycle event" actions - so if you would write a thunk by hand that first dispatches a "I started" action, followed by your code and a "I succeeded/failed" action, that's where you want a `cAT` instead. That applies to most asynchronous operations.

Also, you *can* use RTK Query outside of components. 
But it is mainly used for a component to declaratively just say "I want this data" and after a while the data is there. it's meant less for imperative use.

What is your "out of components data fetching scenario" here?

**Comment by HarrisonHemstreet** [comment]
Thank you so much for your response!

I'm attempting to data fetch from my Redux store slice, so that I can add the data to the global store and use it in several portions of my app.

A simple example of this, would be making a request to this endpoint: `https://jsonplaceholder.typicode.com/users` (JSONPlaceHolder is an api full of fake data, in this case we are retrieving 10 fake users on a social media platform). From the data retrieved, I would like to then enact a series of mutations on the data that:
1. change the format of the name from First-name Last-name to Last-name, First-name
2. pull out their address data, and keep it in the slice until one of my slice's reducers are called to use that data
3. pull out their username and keep it in the slice until I eventually use the username as a param in another async api call within the slice

For these three use cases, is RTK Query able to do the job? If so, how?

If RTK Query is not preferred for this situation, should I use `cAT`?

Are there any examples in open source repos of a Redux-Toolkit implementation that uses RTK's async operations that you can think of? If so, will you please link me an example?

Thank you for answering my questions!

**Comment by markerikson** [comment]
@HarrisonHemstreet I'd recommend reading through our RTK Query tutorials at https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics and https://redux.js.org/tutorials/essentials/part-8-rtk-query-advanced , which cover most of RTK Query's features.
