### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'subscriptions')

### ISSUE THREAD

**Issue by MahmonirB** [reduxjs/redux-toolkit#2139]
I define config file for openApi to create automatically endpoints with types:

    const config: ConfigFile = {
      schemaFile: 'https://example.com/static/docs/swagger.json',
      apiFile: './api/index.ts',
      apiImport: 'api',
      outputFile: './api/sampleApi.ts',
      exportName: 'sampleApi',
      hooks: true,
    }; 
    export default config;

Then I define an index.tsx that has

    export const api = createApi({
      baseQuery: axiosBaseQuery({ baseUrl: '' }),
      endpoints: () => ({}),
    });

and So I generate successfully my sampleApi.tsx file with all of endpoints and types.
like here:

        const injectedRtkApi = api.injectEndpoints({
          endpoints: (build) => ({
             postUsersCollections: build.mutation<
          PostUsersCollectionsApiResponse,
          PostUsersCollectionsApiArg
          >({
          query: (queryArg) => ({
            url: `/users/collections`,
            method: 'POST',
            body: queryArg.postCollectionBody,
          }),
        }),
        getUsersCollections: build.query<
          GetUsersCollectionsApiResponse,
          GetUsersCollectionsApiArg
        >({
          query: (queryArg) => ({
            url: `/users/collections`,
            params: { name: queryArg.name },
          }),
        }),
        overrideExisting: false,
    });
    export const {
      usePostUsersCollectionsMutation,
      useGetUsersCollectionsQuery
    } = injectedRtkApi;

  1. when in a component I use hook function `useGetUsersCollectionsQuery` as bellow I got an error that  `TypeError: Cannot read properties of undefined (reading 'subscriptions')`. There is no lint typescript error related to typescript in my project.

    const { data: collectionData = [] } = useGetUsersCollectionsQuery({});

It's Interesting that this hook called and I see API call in network tab but immediately I got this error. I remove this line and error is disappeared. 

  2. And Also for mutation hook I send data within it but I got 400 error. as Below:
   
    const [postCollection, { data: newCollect }] =
        usePostUsersCollectionsMutation();
        ...
        const handleCreateItem = async () => {
          const response: any = await postCollection({
            postCollectionBody: { name: 'sample' },
          }); }

Please help me! I really thanks you for taking time.

I used :

    "@rtk-query/codegen-openapi": "^1.0.0-alpha.1"
    "@reduxjs/toolkit": "^1.7.2",
![image](https://user-images.githubusercontent.com/37932243/158990311-ea80aee5-2410-4dcf-b560-5c5eabfbdc02.png)

**Comment by MahmonirB** [comment]
I resolved it!
I should define reducerPath as this:
`export const api = createApi({
  reducerPath: 'api',
  baseQuery: axiosBaseQuery({ baseUrl: '' }),
  endpoints: () => ({}),
});`

**Comment by EdgarasMon** [comment]
This "issue" helped me too, thanks. :)

**Comment by tuncatunc** [comment]
export const store = configureStore({
  reducer: {
    [apiSlice.reducerPath]: apiSlice.reducer,
    mnemonic: mnemonicReducer
  },
})
I was missing apiSlice.reducerPath
