### ISSUE TITLE
Module reduxjs/toolkit has no exported member 'createStructuredSelector'

### ISSUE THREAD

**Issue by vkalchuk** [reduxjs/redux-toolkit#2140]
Hey, I read in the docs that a number of packages can be uninstalled since reduxjs/toolkit uses them under the hood - https://redux.js.org/tutorials/fundamentals/part-8-modern-redux#package-cleanup

However, this is not the case for 'reselect' package, particularly `createStructuredSelector` function. A [PR](https://github.com/reduxjs/redux-toolkit/pull/691) was created to fix this, but it was denied.

May be by chance you reconsidered the idea and would like to include `createStructuredSelector` in exports of reduxjs/toolkit?
If still no, could the docs be updated then? Probably there are some other functions from `redux`, `redux-thunk`, `reselect` packages that are not exported in reduxjs/toolkit? Would be nice to have a list of those.

Thank you!

**Comment by markerikson** [comment]
I don't want to have RTK re-export _everything_ from every package it depends on.  We re-export the major functions for convenience (`createSelector`, `produce/createNextState`) or specific functions that we recommend ( `current`).  To me `createStructuredSelector` still doesn't fall into either of those categories, and neither does something like `new Immer()`.  

Also note that the tutorial page is not intended to cover every last detail of either RTK or the related libraries.  The tutorial page as written is accurate - previously there was an explicit import of `createSelector` from Reselect, and now that RTK has been added it can be changed.

So, at the moment I don't feel that there's any changes we need to make here.
