### ISSUE TITLE
What is the query parameter during Streaming Update?

### ISSUE THREAD

**Issue by kahirokunn** [reduxjs/redux-toolkit#2151]
https://redux-toolkit.js.org/rtk-query/usage/streaming-updates#websocket-chat-api

getMessages: build.query<Message[], Channel>({
      query: (channel) => `messages/${channel}`,

**Comment by phryneas** [comment]
That example would get data from a HTTP endpoint (doing a GET request to `messages/${channel}`) to get all currently available chat messages and then open a WebSocket to receive future updates - it is the same `query` parameter as in every other endpoint definition.

**Comment by kahirokunn** [comment]
Are there any examples of using only WebSocket and not HTTP Get request?
For example, I am thinking of using firestore with RTK Query.

**Comment by phryneas** [comment]
You could use a `queryFn` that just returns `{ data:  [] }` or something similar.

If using a library like firestore, you are probably going to use `queryFn` for most things.

**Comment by kahirokunn** [comment]
I see! Understood.
I can write queryFn in the endpoint definition.
Thank you!

https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#examples---queryfn
