### ISSUE TITLE
RTK-Query: serializeQueryArgs get back the store state

### ISSUE THREAD

**Issue by elton2048** [reduxjs/redux-toolkit#2154]
I have a use case which want to customize queryCacheKey using `serializeQueryArgs`, which it refers to state in store. Is there any way to get the state back inside the customized function? Like the way which `baseQuery` returns such argument

**Comment by phryneas** [comment]
Just like the `query` function itself, we want to discourage accessing the state there. 

If you get the state in there, two queries with the same arguments can lead to two different cache entries while two requests with different arguments could end up being the same cache entry - we could never know when a new query would need to be triggered or not.
