### ISSUE TITLE
Incorrect typing

### ISSUE THREAD

**Issue by LonguCodes** [reduxjs/redux-toolkit#2156]
When i'm trying to compile my app (with typescript)  and i'm getting an error:
`
 Property 'abort' is missing in type '{ aborted: false; addEventListener(): void; dispatchEvent(): false; onabort(this: AbortSignal): void; removeEventListener(): void; }' but required in type 'AbortSignal'.
`

Any Ideas?

**Comment by phryneas** [comment]
Are you compiling the RTK Query source code within your application? Please make sure to import from `@reduxjs/toolkit` or `@reduxjs/toolkit/dist`, but not from `@reduxjs/toolkit/src`.

**Comment by LonguCodes** [comment]
You are right, I was importing from src. Sorry for bothering you.
