### ISSUE TITLE
design shared redux createApi library

### ISSUE THREAD

**Issue by deeeed** [reduxjs/redux-toolkit#2159]
Hi,

I have a monorepo with 4 differents projects re-using a similar redux toolkit logic and would like to put everything in a shared library to stop duplicating code.
Are there best practices to do that?
My issue is that createApi requires access to my RootState which is defined in the individual projects,  hence I cannot access it from the API (it would create circular dependencies).

Currently, I have a base API file in each of my projects and for which I override endpoints:
```ts
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { siteConfig } from '../config/site.config';
import { RootState } from '../context/store';

export const baseApi = createApi({
  reducerPath: 'myApiProject1',
  tagTypes: ['TypeA', 'TypeB', 'TypeC'],
  baseQuery: fetchBaseQuery({
    baseUrl: siteConfig.apiUrl,
    prepareHeaders: (headers, { getState }) => {
      const state = getState() as RootState;
      const token = state.Auth.tokens?.token;
      if (token) {
        headers.set('authorization', `Bearer ${token}`);
      }
      return headers;
    },
  }),
  endpoints: (builder) => ({}),
});
```
- Then I have multiple files to configure the endpoints (hereafter for my /training endpoint):
```ts
import queryString from 'query-string';
import { myBaseApi } from './base-api-slice';

const trainingApi = myBaseApi.injectEndpoints({
  endpoints: (builder) => ({
    getExercises: builder.query<PaginatedResult<Exercise>, FindExerciseDto>({
      query: (findDto) => {
        const urlParams = queryString.stringify(findDto);
        console.debug(`getExercises params`, urlParams);
        return `Training?${urlParams}`;
      }, 
    }),
//...
export const {
  useGetExercisesQuery
} = trainingApi;
```
How would you externalize the endpoints without requiring access to the store?

I have also posted on SO... [https://stackoverflow.com/questions/71566494/design-shared-redux-createapi-library](https://stackoverflow.com/questions/71566494/design-shared-redux-createapi-library)
Thanks

**Comment by phryneas** [comment]
Your RootState does only need to be the part of your state you want to access e.g. from `fetchBaseQuery` or in an endpoint lifecycyle event. So you can declare a partial state that is shared by all your stores - or even the empty state if nothing is shared. In that case you just wouldn't be able to access the store from `createApi`.

**Comment by deeeed** [comment]
For the `baseApi` I use config file to set  `baseUrl`.
Is there a way to overwrite the base url when I import `baseApi` in my client app?

**Comment by phryneas** [comment]
Not per default, but there is an example in the documentation that shows how to wrap `fetchBaseQuery` so it works with a dynamic baseUrl: https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#constructing-a-dynamic-base-url-using-redux-state

**Comment by markerikson** [comment]
Don't think there's anything actionable here, so closing.
