### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'structuralSharing')

### ISSUE THREAD

**Issue by myogeshverma** [reduxjs/redux-toolkit#2160]
Hello,
I am trying to implement RTK Query with Next JS SSR, but I am getting this error 
TypeError: Cannot read properties of undefined (reading 'structuralSharing')
<img width="1016" alt="error-next" src="https://user-images.githubusercontent.com/19171423/159472716-0cccc391-82f0-4a8e-8928-dfba9126e1b5.png">

"@reduxjs/toolkit": "1.8.0",
 "next": "12.1.0",

**Comment by markerikson** [comment]
I'm afraid that's not nearly enough information for us to understand what's going on.  Could you put together a Github repo that shows the app setup?

Also, did you add the RTKQ API slice reducer to the store?

**Comment by RSurya99** [comment]
recently, I got the same error. The problem is caused because you have two API service that has the same reducerPath name, so the solution is to change one of the API service reducerPath to another name

**Comment by anth0ni3** [comment]
> recently, I got the same error. The problem is caused because you have two API service that has the same reducerPath name, so the solution is to change one of the API service reducerPath to another name

How do I do this? I'm getting the same error.

**Comment by shayan-ziaarabshahi** [comment]
i gave below error trying to have optimistic update. 
 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '63303b31be2b82f51a947aaf')
i'm using nextjs / mongodb / rtk-query

db update is successful  but this error appears. 

1. component

```
const [increaseLike] = useLikePostMutation()

const handleLike = async (e, likeValue) => {
      await increaseLike({ postId: post.id, likeValue })
}

```
1. apiSlice

```
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

export const apiSlice = createApi({
    reducerPath: 'api', // optional
    baseQuery: fetchBaseQuery({ baseUrl: '/api' }),
    tagTypes: ['Post', 'User'],
    endpoints: builder => ({})
})
```

3. postSlice.js 

```
likePost: builder.mutation({
            query: ({ postId, likeValue, token }) => ({
                url: `/likePost`,
                method: 'Post',
                body: {
                    postId,
                    likeValue
                }
            }),
            async onQueryStarted({ postId, likeValue, token }, { dispatch, queryFulfilled }) {
                const patchResult = dispatch(
                    extendedApiSlice.util.updateQueryData('getPosts', undefined, draft => {
                        const post = draft.entities[postId]
                        if (post) {
                            post.likes += likeValue
                            post.interactions += 1
                        }
                    })
                )
                try {
                    await queryFulfilled
                } catch {
                    patchResult.undo()
                }
            }
        })
```


4. store.js

```
const store = configureStore({
    reducer: {
        [apiSlice.reducerPath]: apiSlice.reducer
    },
    middleware: getDefaultMiddleware =>
        getDefaultMiddleware().concat(apiSlice.middleware),
    devTools: true
})

export default store

```

**Comment by phryneas** [comment]
@shayan-ziaarabshahi  I am going to guess that the endpoint never got injected. Are you sure that your `postSlice.js` is being imported before you try to do this?

**Comment by shayan-ziaarabshahi** [comment]
i thing so. because the pessimistic update do the job. 
i added you to the repo. thanks for your help.

**Comment by phryneas** [comment]
@shayan-ziaarabshahi this error comes from the line `definitions[meta.arg.endpointName].structuralSharing` in the "query fulfilled" handler. The only ways I could explain this is if the endpoint hasn't been injected or if you have multiple apis with the same `reducerPath`.

**Comment by shayan-ziaarabshahi** [comment]
finally i found the bug. 
i changed this:
`post = draft.entities[postId]`
to this: 
`post = draft[postId]`
and it solved the problem.

one of the things in rtk-query is that its a little complicated and there is not so many good tutorial in youtube. also i think console.log in slices doesn't work that makes error handling a little hard. 

thanks phryneas for your time.

**Comment by phryneas** [comment]
Oh. Yeah. That makes sense. You had a completely different error message from the person creating this issue - I had assumed that you had the same error message. Next time please don't just latch onto someone else's issue but open a new one.

As for logging, please read https://redux-toolkit.js.org/usage/immer-reducers - you will find infos on how to get around that in there.

**Comment by muzhaqi16** [comment]
I got a similar error for having two different APIs, even though I wasn't trying to store anything from one of them, it was giving me this error.
