### ISSUE TITLE
Use selectFromResult with normalized data

### ISSUE THREAD

**Issue by aminta** [reduxjs/redux-toolkit#2161]
I suspect the answer is "no", but I would like your confirmation: it does make sense to use selectFromResult with normalized data?

Like:

```
export const commentaryAdapter = createEntityAdapter({
  // Assume IDs are stored in a field other than `book.id`
  selectId: commentary => commentary.attributes.id,
});

 const { selectAll: selectAllCommentaries, selectById: selectCommentaryById } =
    commentaryAdapter.getSelectors(state => {
      return selectCommentaryEvents(state);
    });

  const commentaries = useSelector(state => selectAllCommentaries(state));

const { commentaryEvents } =
    useGetMatchResultQuery(
      {
        matchId: matchId,
      },
      {
        selectFromResult: result => {
          return {
            ...result,
            commentaryEvents: commentaries,
          };
        },
      },
    );

```

Or, if you use normalized data, `selectFromResult` doesn't make sense?

**Comment by markerikson** [comment]
I'm actually not quite sure what that example is trying to show.  

`selectFromResult` is intended to let you pick out a subset of the data in the cache entry, such as skipping the status flags, grabbing one item out of an array, etc.

Here, it looks like you're adding an entirely different value that _already exists in scope_ to the `data` object, which seems redundant.

Can you clarify what you're trying to accomplish?

**Comment by aminta** [comment]
Yes @markerikson, sorry. The commentaries are only a subset of the cache entry (we have: `data: {matchResults: ...}, commentary: {...}}, so I would to understand if, when I have to pick out a subset of the data, I have to use either `selectFromResult` or selectors or I can use them together...

**Comment by markerikson** [comment]
Sounds like you probably want `selectFromResult` here, and _not_ `useSelector`.

There's some examples of that here:

https://redux.js.org/tutorials/essentials/part-8-rtk-query-advanced#transforming-responses

**Comment by aminta** [comment]
thanks @markerikson , I've read those examples, but my question is different: if I use normalized data can I still to use `selectFromResult` to pick out a subset of the data?

**Comment by aminta** [comment]
> Are you talking about using `createEntityAdapter` inside of `transformResponse` to reshape the way the data is cached in the store

Yes, this.

**Comment by markerikson** [comment]
Yeah, so what I was saying applies here.

If you do nothing, by default ` const { data } = useMyQuery()` will give you back the entire `{ids: [], entities: {}` structure you returned from `transformResponse`.

If you only want _part_ of that, like a single item by its ID, then you should use `selectFromResult` to pick out just that one piece.

**Comment by aminta** [comment]
Thanks @markerikson ,  so my "final" (and original answer) is: in that case (using `selectFromResult` after having normalized the data), how can I deal with the `result` as it were not a `{ids: [], entities: {}` but an array of entities?

**Comment by markerikson** [comment]
You'd want to use the entity adapter selectors.   Specifically, you'd need to use the "localized" versions, generated by calling `myAdapter.getSelectors()` _without_ an input selector:

https://redux-toolkit.js.org/api/createEntityAdapter#selector-functions

And then `const allItemsAsArray = selectors.selectAll(res.data)` in `transformResponse`.
