### ISSUE TITLE
Apollo Boost isn't a thing anymore

### ISSUE THREAD

**Issue by heygrady** [reduxjs/redux-toolkit#2164]
https://github.com/reduxjs/redux-toolkit/blob/de82d4d9fb326119c3dcfdd6d40801e37f3bae59/docs/introduction/getting-started.md?plain=1#L23

https://github.com/apollographql/apollo-client/blob/73a4797747b9d3f5d961c910ad1d88d716a0e631/docs/source/migrating/apollo-client-3-migration.mdx#apollo-boost

I just clicked the Apollo Boost link and ended up at a bit of a dead end. After clicking around some more I found that boost was more-or-less integrated directly into the Apollo client.

Not a big deal either way but it was striking to encounter out-of-date references on the "getting started" page for redux-toolkit.

https://github.com/apollographql/apollo-client/releases/tag/v3.0.0

> [BREAKING] Removed apollo-boost since Apollo Client 3.0 provides a boost like getting started experience out of the box.
[@hwillson](https://github.com/hwillson) in https://github.com/apollographql/apollo-client/pull/5217

**Comment by markerikson** [comment]
Yeah, could you file a PR to remove that from the README and the "Getting Started" page?
