### ISSUE TITLE
prepare headers getState token for server side request

### ISSUE THREAD

**Issue by bryantobing12** [reduxjs/redux-toolkit#2165]
I'm currently following this example in order to authenticate users when sending requests to the API. https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery#setting-default-headers-on-requests

```ts
import { fetchBaseQuery } from '@reduxjs/toolkit/query'
import type { RootState } from './store'

const baseQuery = fetchBaseQuery({
  baseUrl: '/',
  prepareHeaders: (headers, { getState }) => {
    const token = (getState() as RootState).auth.token

    // If we have a token set in state, let's assume that we should be passing it.
    if (token) {
      headers.set('authorization', `Bearer ${token}`)
    }

    return headers
  },
})
```

but the problem is, the token will always be empty on the server-side part. causing the request made will always client-side request. 
how do I resolve this issue?

I'm using nextjs, and i store the token using redux-persist. and i'm following this https://redux-toolkit.js.org/rtk-query/usage/server-side-rendering to setup hydration on nextjs. if the `api` doesn't need token the server side request works fine.

**Comment by phryneas** [comment]
Well, the Redux store is always empty on the server as well - SSR always uses a "new" Redux store since technically there is no way the client could communicate the full store contents back to the server witch each request.

If you want something like a token shared between client and server, you would have to put that into a cookie and in `prepareHeaders` access that cookie, not into your Redux store.

**Comment by bryantobing12** [comment]
ended up trying to move my token into cookies, https://www.npmjs.com/package/next-redux-cookie-wrapper. I found this lib https://www.npmjs.com/package/next-redux-cookie-wrapper for persisting redux state in cookies. do you think this is safe?

Or if we can just config how we set our cookies manually? could you provide an example on how to achieve that?

**Comment by phryneas** [comment]
You should not put your whole state into a cookie. That means it will be transferred on every request - and can be quite a lot of unnecessary overhead. On the other hand, there is a storage limit per cookie, so as soon as your state would go over 4kb, it would probably completely break down.

Just put exactly what you need into cookies. As for what is the best tool for that, I don't know. I don't use next and use cookies in a probably very different fashion.

**Comment by mouhamedaly** [comment]
> Well, the Redux store is always empty on the server as well - SSR always uses a "new" Redux store since technically there is no way the client could communicate the full store contents back to the server witch each request.
> 
> You can move data from the server store to the client store with each request (using the hydration options redux-next-wrapper offers), but never the other way round.
> 
> If you want something like a token shared between client and server, you would have to put that into a cookie and in `prepareHeaders` access that cookie, not into your Redux store.

How can i access cookies in prepareHeaders ?

**Comment by phryneas** [comment]
@mouhamedaly generally you should not set cookies from the client side - cookies should be set and read only by the server. If you just want to read cookies, you just read cookies via document.cookie or a library, there is nothing specific to `prepareHeadres`.

**Comment by d-sooter** [comment]
@bryantobing12 did u manage to get the jwt token in prepareHeaders using ssr? Im using nextauth and sometimes i have a session and sometimes i dont. Any case u found a solution maybe using cookies?

**Comment by bryantobing12** [comment]
Yes. I save the token in cookies eventually

**Comment by d-sooter** [comment]
@bryantobing12  Would you be interested in sharing how and maybe what libraries you used. Next auth already writes the jwt to the cookies but im not sure how to access it on the server

**Comment by yportfolio** [comment]
> @bryantobing12 Would you be interested in sharing how and maybe what libraries you used. Next auth already writes the jwt to the cookies but im not sure how to access it on the server. Since prepareHeaders doesn’t have access to the request

https://github.com/reduxjs/redux-toolkit/issues/2228 Here you can find the answer.
https://github.com/urhot/nextjs-rtk-query-ssr/commit/54d47f916f7bb219fa83e053fdf8e8a366a76796 In this repo you can find the example to access cookies in prepareHeaders with [next-redux-wrapper](https://github.com/kirill-konshin/next-redux-wrapper)

**Comment by ghostmurda** [comment]
> > @bryantobing12 Would you be interested in sharing how and maybe what libraries you used. Next auth already writes the jwt to the cookies but im not sure how to access it on the server. Since prepareHeaders doesn’t have access to the request
> 
> @d-sooter #2228 Here you can find the answer. [urhot/nextjs-rtk-query-ssr@54d47f9](https://github.com/urhot/nextjs-rtk-query-ssr/commit/54d47f916f7bb219fa83e053fdf8e8a366a76796) In this repo you can find the example to access cookies in prepareHeaders with [next-redux-wrapper](https://github.com/kirill-konshin/next-redux-wrapper)

Thanks! Great solution
