### ISSUE TITLE
Trying to call custom hook 'useFetch' from createAsyncThunk

### ISSUE THREAD

**Issue by ajitesh-sivakumar** [reduxjs/redux-toolkit#2166]
Hey,

I am trying to call a custom hook to from createAsyncThunk. But, it gets rejected right away. In network tab (Browser DevTools), I don't see any request being sent.

**authSlice.js**
`import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import useFetch from "../hooks/useFetch";

export const loginApiAsync = createAsyncThunk("Login API Async", (values) => {
  const options = {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.parse({
      userName: values.email,
      password: values.password,
    }),
  };
  const { data } = useFetch("/api/auth/login", options);
  return data;
});

const initialState = {
  accessToken: "",
};

export const authSlice = createSlice({
  name: "Authentication Slice",
  initialState,
  reducers: {},
  extraReducers: {
    [loginApiAsync.fulfilled]: (state, action) => {
      state.accessToken = action.payload;
    },
  },
});

// export const {} = authSlice.actions;

export default authSlice.reducer;
`
**useFetch.js**

`import { useEffect, useState } from "react";

const useFetch = (endpoint = "", actions = null) => {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const BASE_URL = process.env.REACT_APP_BASE_URL;

  useEffect(() => {
    const fetch = async () => {
      try {
        setIsLoading(true);
        const response = await fetch(BASE_URL + endpoint, actions);
        const responseData = await response.json();
        setData(responseData);
      } catch (err) {
        setError(err);
      } finally {
        setIsLoading(false);
      }
    };
    fetch();
  }, []);

  return { data, error, isLoading };
};

export default useFetch;
`

Thanks.

**Comment by markerikson** [comment]
Yes, you're trying to call a hook in the middle of the thunk, and you can _never_ call a hook outside of a function component:

```js
const { data } = useFetch("/api/auth/login", options);
```
