### ISSUE TITLE
Dynamically generate providesTags and invalidatesTags based on endpoint url

### ISSUE THREAD

**Issue by johnnymetz** [reduxjs/redux-toolkit#2170]
Let's say I have the following RTK query endpoints:

```
endpoints: builder => ({
  getTodos: builder.query({
    query: () => 'todos/',
    providesTags: ['todos'],
  getTodo: builder.query({
    query: id => `todos/${id}/`,
    providesTags: ['todos'],
  }),
  createTodo: builder.mutation({
    query: body => ({ url: 'todos/', method: 'POST', body }),
    invalidatesTags: ['todos],
  }),
  updateTodo: builder.mutation({
    query: ({ id, ...body }) => ({ url: `todos/${id}/`, method: 'PATCH', body, }),
    invalidatesTags: ['todos'],
  }),
  deleteTodo: builder.mutation({
    query: id => ({ url: `todos/${id}/`, method: 'DELETE' }),
    invalidatesTags: ['todos'],
  }),
})
```

I have a very large API and I would love to **dynamically** assign `providesTags` and `invalidatesTags` to every endpoint based on the path so I don't need to manually assign tags. That is, I want to write something so RTK reads the `url` field and automatically assigns the appropriate tag.

This can scale for longer, more complicated endpoints using some simple string manipulation. For example `/todos/${todoId}/subscribers/${subscriberId}/groups/` can evaluate to a tag like `'todos-subscribers-groups'` or `groups`, depending on the use case.

Is this possible?

Neither [providesTags](https://redux-toolkit.js.org/rtk-query/api/createApi#providestags) nor [invalidatesTags](https://redux-toolkit.js.org/rtk-query/api/createApi#invalidatestags) provides access to the endpoint URL so it doesn't look like this is currently possible.

**Comment by Harwex213** [comment]
Hello. I've had such problem too. And i find that `providesTags` can take a func with params `result, error, arg`. Last param arg - arguments of `query` func.
So, you can make something like that:
```
getEntities: builder.query({
    query: ({entityName}) => `${entityName}/`,
    providesTags: (result, error, {entityName}) => [entityName],
})
```
