### ISSUE TITLE
normalizr is no longer maintained

### ISSUE THREAD

**Issue by gzzo** [reduxjs/redux-toolkit#2174]
There's a couple of places in the documentation (https://redux-toolkit.js.org/usage/usage-with-typescript#using-createentityadapter-with-normalizr) that have examples of using normalizr along with RTK. As of a week ago, normalizr is no longer maintained: https://github.com/paularmstrong/normalizr/discussions/493#discussioncomment-2395540

Is there any chance that the redux team can take ownership of that library? I know it's a long shot, but these two utilities go hand in hand.

**Comment by markerikson** [comment]
It might be a possibility.  We'll look into it and see what turns up.

**Comment by markerikson** [comment]
Had a discussion with Paul Armstrong, the former Normalizr maintainer.

The conclusion was that he'd prefer _not_ to hand over the existing https://github.com/paularmstrong/normalizr repo, and instead have us fork and rebrand as `@reduxjs/normalizr` or something to help indicate the change.

It's something we're open to doing, but we're all busy enough there's no ETA on when we might try to do that.

**Comment by markerikson** [comment]
We have no plans to pick up maintenance of Normalizr at this point.
