### ISSUE TITLE
RTK Query: retry condition by http status code

### ISSUE THREAD

**Issue by kahirokunn** [reduxjs/redux-toolkit#2175]
It would be useful if the RTK Query provided retry function had an option to not retry depending on the HTTP Status.

It would be useful to be able to set both a common setting and a per endpoint setting for this.

It is not limited to HTTP Status, but there are cases where you may not want to retry some API Responses.

There is an idea to allow the user to pass a function that API Response takes as input value and return a boolean as the return value.

**Comment by kahirokunn** [comment]
@phryneas If this looks good, I'll implement it myself. 👀

**Comment by markerikson** [comment]
Sounds potentially useful, sure!

**Comment by phryneas** [comment]
@kahirokunn please go ahead :)

**Comment by kahirokunn** [comment]
done 💪 
https://github.com/reduxjs/redux-toolkit/releases/tag/v1.9.0-alpha.1
