### ISSUE TITLE
Reducer - Middleware Stop Working After 32+ Reducer Api- RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by ariel66degrees** [reduxjs/redux-toolkit#2177]
Hi All, 
First of all, thanks for this I have enjoyed working with RTK. 
I have a situation right now (its a bit urgent). I have been working based on this example https://codesandbox.io/s/rtk-query-demo-lbp7n?from-embed following the pattern of adding APIs paths to my reducer. But it just happened to me that somehow it reached its limit. (after aprox 32 apis paths) and now the app stops working and I get these:

Promise error  `{name: 'RangeError', message: 'Maximum call stack size exceeded', stack: 'RangeError: Maximum call stack size exceeded\n    a…st:3000/static/js/vendors~main.chunk.js:111569:22'}`

Warning `buildInitiate.ts:248 Warning: Middleware for RTK-Query API at reducerPath "userClaimsService" has not been added to the store.
Features like automatic cache collection, automatic refetching etc. will not be available.`

Any idea if there is a limit defined somewhere? if there is any other error happening? or what I can do in order to avoid this limitation?

Thanks,

~Ariel M

**Comment by phryneas** [comment]
Well, generally we do recommend that you should almost always only have one api in your application at all. An exception would be if you query against two completely different data sources, like Twitter and a Cake Wiki - but as soon as there is any relationship between data transmitted by the api, it should be the same api.

There is no limit set by us, but at some point you will reach browser engine limits it seems.

Better create one api and use the "code splitting" approach from the docs to split it over multiple files.

**Comment by ariel66degrees** [comment]
Hmmm, it is weird then than the examples/documentation look other way. But so you recommend me "code splitting" the endpoints and then concat them into just one api?

**Comment by ariel66degrees** [comment]
I supposed you mean to do something like this https://redux-toolkit.js.org/rtk-query/usage/code-splitting it was just confusing the examples were made differently. Anyway will give this a try. Thanks for the quick answer on this.

**Comment by ariel66degrees** [comment]
That worked like a charm! thank you so much.
