### ISSUE TITLE
Object literal may only specify known properties, and 'memoizeOptions' does not exist in type

### ISSUE THREAD

**Issue by miliko0022** [reduxjs/redux-toolkit#2182]
this my code

```
import { createSelector } from '@reduxjs/toolkit'

const selectNumCompletedTodos2 = createSelector(
    (state: RootState) => state.counter.ok.ok,
    (state: RootState) => state.counter.ok.ok,
    (ok: number, ok1: number) => `${ok} + ${ok1}`,
    {

        memoizeOptions: {
            equalityCheck: (a, b) => {
                return a === b;
            },
        }
    }
)
```

I get this error

>The last overload gave the following error. Argument of type '{ memoizeOptions: { equalityCheck: (a: any, b: any) => boolean; }; }' is not assignable to parameter of type '(res1: number, res2: number, res3: string) => unknown'. Object literal may only specify known properties, and 'memoizeOptions' does not exist in type '(res1: number, res2: number, res3: string) => unknown'.

**Comment by miliko0022** [comment]
"@reduxjs/toolkit": "^1.8.0"

**Comment by phryneas** [comment]
`yarn why reselect` or `npm ls reselect`

**Comment by miliko0022** [comment]
"reselect": "^4.1.5"

**Comment by markerikson** [comment]
That code should be valid with the current version of Reselect.  Can you post a CodeSandbox or repo that shows this happening?

**Comment by miliko0022** [comment]
[CodeSandbox ](https://codesandbox.io/s/loving-shadow-yq5fnh?file=/src/index.tsx)

**Comment by phryneas** [comment]
It seems to be working just fine in that sandbox?

```
const selectNumCompletedTodos2: ((state: {
    counter: CounterState;
}) => string) & OutputSelectorFields<((args_0: number, args_1: number) => string) & {
    clearCache: () => void;
}> & {
    clearCache: () => void;
}
```

**Comment by miliko0022** [comment]
to tell the truth, I don't understand what kind of codes were written here download Project from this [link ](https://github.com/miliko0022/memoizeOptions)and try it locally

**Comment by markerikson** [comment]
Hmm. Opening the repo as a sandbox, this _appears_ to compile okay.

I'm going to close this as a "can't repro" for now.
