### ISSUE TITLE
RTK Query: handle nullable data when data has already been fetched

### ISSUE THREAD

**Issue by raxell** [reduxjs/redux-toolkit#2184]
Hi, I would like to have some thoughts about the following.

How do you handle the possibly undefined data returned by the hook, **when you know that the data are already been fetched**?

For example, I have the following component:

```ts
const Post = () => {
  const { isFetching, isError } = usePostQuery({ id: 1 })

  if (isFetching) {
    return <PostSkeleton />
  }

  if (isError) {
    return <PostError />
  }

 return <PostData />
}
```

If error or loading, some static UI (`PostSkeleton` and `PostError`) is rendered, otherwise the actual post with data is rendered.
Now, inside `PostData` I know that `const { data } = usePostQuery(...)` is not undefined, but how can I handle it at the type level?
**NB**: I don't want to pass the data down as props, the subtree could be arbitrary deep, etc..

I can use the `!` to force non nullability, but it seems too unsafe/uncontrolled.
So I've defined the following util to give a "meaningful" message if some invariants are violated (e.g. something is being used in the wrong way):

```ts
export function assertDefined(value: unknown, msg: string): asserts value {
  if (value === null || value === undefined) {
    throw new Error(`Invariant Violation: ${msg}`);
  }
}
```

And I use it in the following way:

```ts
const PostData = () => {
  const { data } = usePostQuery({ id: 1 })
  assertDefined(data, '[usePostQuery] expect data to have already been fetched')

  // ...
}
```

This works well in general, but if the tree of `PostData` is made of a lot of other components that use `usePostQuery`, it becomes repetitive and creates too much noise. So, I'm thinking about abstracting it in a twin hook:

```ts
type GetPostResponse = ...

const api = createApi({
  // ...
  endpoints: (builder) => ({
    getPost: builder.query<GetPostResponse, { id: number }>({
      query: ({ id }) => `/posts/${id}`,
    }),
  }),
});

export const { useGetPostQuery } = api;

export const useGetPost = (
  params: Parameters<typeof useGetPostQuery>[0]
) =>
  useGetPostQuery(params, {
    selectFromResult: (args) => {
      assertDefined(args.data, "[useGetPost] expect data to have already been fetched");

      return args as typeof args & { data: NonNullable<typeof args["data"]> };
    },
  });

```

The type cast is not too clean but it should work. Now in all the subcomponents of `PostData` I can use `useGetPost` instead of `useGetPostQuery` and have the non-nullable data along with the invariant check.

Hoping this is all clear I would like to have some thoughts about it:
- is this a good approach or is there a more idiomatic way to handle this that I'm missing? In the docs I've not found anything in this regard
- if the approach is reasonable, could it make sense to integrate it directly in rtk-query? for example by providing an additional option as a second parameter of the hooks `const { data } = useGetPostQuery({ id: 1 }, { expectFetched: true })`

**Comment by phryneas** [comment]
This seems generally reasonable for you to do in your code base, but given that React 18 just released and once we have some kind of suspense integration, loading states and `undefined` go out of the window, we probably won't add something like this either.

**Comment by raxell** [comment]
Ok, makes sense, I didn't look into suspense yet.
So let me know if I've understood correctly: with suspense the query would throw while loading so the resulting data's type would never possibly be undefined?
