### ISSUE TITLE
RTK Query: How to invalidate cache after third-party managed authentication?

### ISSUE THREAD

**Issue by Dani-Boy92** [reduxjs/redux-toolkit#2194]
We use AWS Cognito for authentication, so it is not managed by RTK Query. After a user signs in, we need to invalidate the cache and refetch the active APIs with the user-specific data.  However, since the login (POST) is not managed by RTK Query, the question is how we can trigger the invalidation. 

```
 import { Auth } from 'aws-amplify';

async function signIn() {
    try {
        const user = await Auth.signIn(username, password);
    } catch (error) {
        console.log('error signing in', error);
    }

// do some rtk query invalidation
}
```

Our first idea was to send a dummy POST that invalidates the APIs after authentication...

**Comment by markerikson** [comment]
You should be able to use https://redux-toolkit.js.org/rtk-query/api/created-api/api-slice-utils#invalidatetags to manually trigger invalidation.

**Comment by msutkowski** [comment]
You can also wrap this function inside of a `queryFn` if you want to keep things centralized and only need to follow one pattern. An example of how you'd do that:

https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/tests/queryFn.test.tsx#L328-L336
