### ISSUE TITLE
originalArgs from hooks always return undefined

### ISSUE THREAD

**Issue by whysetiawan** [reduxjs/redux-toolkit#2195]
Hi, thanks for the wonderful library. I need to access originalArgs from the component in order to be executed by another Mutations

**here is the code :**
```
  const [resetPassword, { isLoading, ...res }] = useResetPasswordMutation({
    fixedCacheKey: "SHARED_EMAIL_FORGOT_PASSWORD",
  });
  console.log("original Args", res.originalArgs); // undefined
```

i also try to find the original Args from the traditional slice, to check if the mutations body isn't empty
```
      .addMatcher(authApi.endpoints.resetPassword.matchPending, (state, _) => {
        state.isLoading = true;
        console.log("meta ", _.meta.arg); // this works
      })
```

**Here is the result from the terminal** : 
<img width="567" alt="Screen Shot 2022-04-03 at 12 43 25" src="https://user-images.githubusercontent.com/32702491/161413587-c0e02294-cdad-45aa-a9bb-d86b9e4d996f.png">

**Comment by whysetiawan** [comment]
My bad, doesn't aware if  ` originalArgs?: unknown // Arguments passed to the latest mutation call. Not available if using the `fixedCacheKey` option`

**Comment by whysetiawan** [comment]
Seems like mutation is being created in a new component and can't persist the originalArgs. 
```
const componentA = () => {
    const [resetPassword, { isLoading, ...res }] = useResetPasswordMutation();
  console.log("original Args", res.originalArgs);
  
  const onSubmit = useCallback(async (email) => {
    const payload = await resetPassword(email).unwrap
    navigation.navigate("routeName")
  })
}



const componentB = () => {
    const [resetPassword, { isLoading, ...res }] = useResetPasswordMutation();
  console.log("original Args", res.originalArgs); // undefined
  
  const onSubmit = useCallback(async (email) => {
    const payload = await resetPassword(email).unwrap()
    navigation.navigate("routeName")
  })
}

```

**Comment by phryneas** [comment]
Yes, the point of a mutation is to change data on the server, not to receive data from the server. Thus, mutation results are "per-component" as you could have 10 buttons on the screen that all call the same mutation, but should be independent of each other -  imagine clicking a button and then all the buttons on the page go into a "loading" state - that's hardly desiable.

You can use `fixedCacheKey`, but as you already found out, while the result will be shared,  `originalArgs` will not be shared. `originalArgs` for mutations will never end up in the global store, since mutations are often called with non-serializable arguments (like File objects), that should never be stored in the store.

If you want to share the arguments, you will have to put them into the store yourself.

**Comment by whysetiawan** [comment]
I have to use transformResponse and concat `response` and `originalArgs` from params, correct?

**Comment by phryneas** [comment]
That is one way of doing it - or you'd keep it in a slice you handle manually, that's really your choice.

**Comment by baharalidurrani** [comment]
> I have to use `transformResponse` and concat `response` and `originalArgs` from params, correct?

We use a global `transformResponse` in our app. Keeping that in mind this solution worked for me:

```ts
    requestOtp: builder.mutation<{ message: string; username: string }, string>({
      query: (username) => ({
        url: `${apiResources.otp}/forgot-password/generate`,
        method: 'POST',
        body: { username },
      }),
      transformResponse: (res: any, _meta, originalArgs) => {
        const data = transformResponses.transformResponse<string>(res);
        return { message: data, username: originalArgs };
      },
      transformErrorResponse: transformResponses.transformErrorResponse,
    }),
```

interceptors.ts
```ts
/** If API uses `data.data` syntax for responses */
function transformResponse<T>(baseQueryReturnValue: { data: T }, _meta?: FetchBaseQueryMeta): T {
  return baseQueryReturnValue?.data;
}
/** If API uses `data.message` syntax for responses */
function transformErrorResponse(baseQueryReturnValue: FetchBaseQueryError, _meta?: FetchBaseQueryMeta) {
  if ('message' in baseQueryReturnValue) return baseQueryReturnValue.message || baseQueryReturnValue.data;
  return baseQueryReturnValue.data;
}
export const transformResponses = { transformResponse, transformErrorResponse };
```
