### ISSUE TITLE
[RTK Query] New feature or method for global spinner

### ISSUE THREAD

**Issue by atillaaliyev** [reduxjs/redux-toolkit#2204]
My project is in the coding phase. I was using axios + pure async thunk action for http requests. But RTK Query is awesome for manage these operations and I have decided using RTK Query. But I have a question or feature want. Before,I would like to point out that I have read the whole document for RTK Query.

While I using axios , I coded a hook and I could manage spinner process whole project. And when this hook detected http request, I was catching it and if the request had isLoading header (default has), I was showing spinner. But sometimes when I catch request, if it hasn't isLoading header, I wasn't showing it.

**useAxiosLoader.ts**
```

export default function useAxiosLoader() {
    const [counter, setCounter] = useState(0);
    const [cookies, setCookie, removeCookie] = useCookies(["accessToken"]);
    const {userName, password} = useAppSelector(userInfo);

    useEffect(() => {
        const reqInterceptor = httpDefaultClient.interceptors.request.use((config: any) => {

            config.headers["Authorization"] = `Bearer ${cookies.accessToken}`;
            setCounter(counter => counter + (config.headers.head["is-loading"] === "1" ? 1 : 0));
            config.headers.IsLoading = config.headers.head["is-loading"] === "1";
            return config;
        }, (error:any)=>{
            if (error.headers.head["is-loading"] === "1") {
                setCounter(counter => counter - 1);
            }

            return Promise.reject(error);
        });
        const resInterceptor = httpDefaultClient.interceptors.response.use((response:any)=>{
            setCounter(counter => counter - (response.config.headers["IsLoading"] ? 1 : 0));

            return response;
        }, (error:any)=>{
            setCounter(counter => counter - (error.config.headers["IsLoading"] ? 1 : 0));

            return Promise.reject(error);
        });

        return () => {
            httpDefaultClient.interceptors.request.eject(reqInterceptor);
            httpDefaultClient.interceptors.response.eject(resInterceptor);
        };
    }, []);

    return [counter > 0];}
```

This hook catching the all requests from axios default client.

**VLoading.tsx**
```
export default function VLoading() {
    const [loading] = useAxiosLoader();

    return (
        <div>
            <Backdrop
                open={loading}
                sx={{color: "#fff", zIndex: 999999}}
            >
                <CircularProgress color={"inherit"} />
            </Backdrop>
        </div>
    );
}
```
And I'm using the VLoading component at top level. It's easy and useful method but I didn't do same thing in RTK Query. The reason, useQuery hook is giving isLoading or isFetching parameter in  component that used. So, every time I have to manage the spinner based component. I am able to use special baseQuery for axios but I don't want to have lots of dependency.

Maybe you are able to add new feature(actually hook) that named **useHasValidFetching** (return bool value). Why am I say "Valid"? Because, for example, I have five query or mutation and I want to effect for spinner only three that triggering same time. And I should have a property for each endpoint **(default:true)** that named **isValidFetching** .If the endpoint has this property as false, it won't return true for **useHasValidFetching** hook as when I called **useQuery** hook. So I will remove **useAxiosLoader**, **VLoading.tsx** will be following;

```
export default function VLoading() {
    //Bool value will be return by this hook.
    const loading= useHasValidFetching();

    return (
        <div>
            <Backdrop
                open={loading}
                sx={{color: "#fff", zIndex: 999999}}
            >
                <CircularProgress color={"inherit"} />
            </Backdrop>
        </div>
    );
}
```

```

export const baseApi = createApi({
    reducerPath: "...",
    baseQuery: ...,
    endpoints: (builder) => ({
        getQueryOne: builder.query<void, void>({ query: () => `exampleOne`}) //isValidFetching default true
        getQueryTwo: builder.query<void, void>({ query: () => `exampleTwo` , isValidFetching : false}),
        getQueryThree: builder.query<void, void>({ query: () => `exampleThree`}) //isValidFetching default true
        getQueryFour: builder.query<void, void>({ query: () => `exampleFour`,  isValidFetching : false}),
    })
});

```

When I used **useGetQueryOneQuery**, **useGetQueryTwoQuery**, **useGetQueryThreeQuery** hooks in same component and completed first and third hook, I won't show spinner thanks to **isValidFetching** property.

**Comment by phryneas** [comment]
You can just do
```js
const isSomeQueryPending = useSelector(state => Object.values(state.api.queries).some(query => query.status === 'pending'))
```

Of course you can add additional logic into that `some` callback.

**Comment by atillaaliyev** [comment]
I don't understand state.**api**.queries. Because of , I can have a lot of api. Every time, will I write Object.values(state.**utilityApi**.queries), Object.values(state.**policyApi**.queries) etc?

**Comment by markerikson** [comment]
@atillaaliyev : We specifically recommend having _one_ API slice by default:

https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics#defining-an-api-slice

And the default top-level state slice name is `api`, so by default you'd be reading values from `state.api`.

_If_ you have multiple API slices added to the store, then yes, you'd repeat the process for any other API slices you have attached to the state.

**Comment by atillaaliyev** [comment]
@markerikson thank you, I got clearly. I made mistake creating new api slice for each feature.I will use injectEndpoint for each feature . So, i will get code split

**Comment by atillaaliyev** [comment]
I reopened this issue, because of I will ask a question about this.

`const isSomeQueryPending = useSelector(state => Object.values(state.api.queries).some(query => query.status === 'pending'))`

This solution is ok for me. But I have a problem. For example, spinner should not be affected by this query.
```
{
    "status": "pending",
    "endpointName": "getProductInformations",
    "requestId": "8w7OO-4ALp-lxjf9hKDNv",
    "originalArgs": {
        "addressNo": "string",
        "agentCode": "177749",
        "branchCode": 5,
        "endDate": "2023-01-10T00:00:00",
        "isDevelopmentMode": false,
        "insured": "0",
        "insuredBy": "0",
        "issueDate": "2022-01-31T00:00:00",
        "loadDate": "2022-04-11T09:24:07.737Z",
        "moduleName": "CREATESUPPLEMENT",
        "policyNumber": "51456622",
        "productCode": "FKS",
        "sourceCode": 7,
        "startDate": "2022-01-31T00:00:00",
        "supplementNumber": "2",
        "supplementCode": "03",
        "userName": "OZGURY",
        "listOfStatistics": [
            {
                "code": "TM1",
                "value": "003",
                "valueName": "TEMINAT LIMITLERI"
            },
            {
                "code": "NM7",
                "value": "001",
                "valueName": "PRİM ARTTIRIMI"
            }
        ]
    },
    "startedTimeStamp": 1649669047739
}
```
This is passive query, I have a solution but I don't like it. I will change my endpoint name getProductInformations->getProductInformationsAsync and If It's end with "Async", spinner won't effect. But I'm not sure , is it good solution?

**Comment by markerikson** [comment]
At this point it's entirely your code, so it's up to you to define what the intended logic and behavior should be.

If you're writing code that tries to determine "should there be a global loading spinner showing?", _you're_ the one who is defining what counts for that status.  So, write whatever logic you need to calculate that.

**Comment by mkdudeja** [comment]
I was looking for more generic approach like interceptors with axios, using which we can configure loader to request start and request complete/ error. Similar can be achieved with RTK query using wrapper functions over base query.

Following is the solution to handle loader at the global (common) level. It uses `nprogress` to show the loader. Anything can be configured in-place of `nprogress`. But overall implementation approach remains the same.

```typescript
import {
  BaseQueryFn,
  createApi,
  FetchArgs,
  fetchBaseQuery,
  FetchBaseQueryError,
} from "@reduxjs/toolkit/query/react";
import NProgress from "nprogress";

// NProgress setup
const nprogress = {
  counter: 0,
  start: function () {
    this.counter++;
    !NProgress.isStarted() && NProgress.start();
  },
  complete: function () {
    this.counter--;
    this.counter === 0 && NProgress.done();
  },
};

const baseQuery = fetchBaseQuery({ baseUrl: "/" });
const baseQueryWithNProgress: BaseQueryFn<
  string | FetchArgs,
  unknown,
  FetchBaseQueryError
> = async (args, api, extraOptions) => {
  try {
    nprogress.start();
    const result = await baseQuery(args, api, extraOptions);

    nprogress.complete();
    return result;
  } catch (err) {
    nprogress.complete();
    throw err;
  }
};

// initialize an empty api service that we'll inject endpoints into later as needed
const baseApi = createApi({
  keepUnusedDataFor: 60,
  refetchOnFocus: false,
  refetchOnReconnect: false,
  refetchOnMountOrArgChange: false,
  baseQuery: baseQueryWithNProgress,
  endpoints: () => ({}),
});
```

**Comment by yukiyokotani** [comment]
If you do not want the global flag to respond to a specific query, you could write the following.

```typescript
type EndpointName = keyof typeof someApi.endpoints;

const nonBlockingQuerySet: Set<EndpointName> = new Set([
  'getProductInformations'
]);

const shouldBlock = useSelector((state) =>
  Object.values(state.api.queries).some(
    (query) =>
      query?.endpointName &&
      !nonBlockingQuerySet.has(query.endpointName as EndpointName) &&
      query.status === 'pending'
  )
);
```

**Comment by hamzeloudev** [comment]
A utility package for integrating file upload/download with progress tracking into your Redux Toolkit Query API slices:

[rtk-upload-utils](https://www.npmjs.com/package/rtk-upload-utils)

**Comment by markerikson** [comment]
@hamzeloudev : **_do not_ spam issues like this**.
