### ISSUE TITLE
selectFromResult running too often?

### ISSUE THREAD

**Issue by einarq** [reduxjs/redux-toolkit#2208]
I thought, based on the docs, that selectFromResult would only run if the data returned from the query changes. But based on my testing it seems to update all the time.

I'm running an Array.filter in selectFromResult, and this updates the array on every render. To solve the issue I had to extract the filtering to a useMemo.

So instead of this:

```
  const {items, isFetching} = useGetFileLibraryItemsQuery(
    {companyId, folder: currentFolderId, orderBy, orderDirection, mimeTypeStartsWithFilters},
    {
      skip: !canSelect || combinedUploadState === UPLOAD_STATES.uploading || filesToDelete.length > 0,
      selectFromResult({data = defaultFiles, isFetching}) {
        return {
          items: filterFilesByMimeType({mimeTypeStartsWithFilters, files: data}),
          isFetching,
        };
      },
    }
  );
```

I had to do this:

```      
  const {data = defaultFiles, isFetching} = useGetFileLibraryItemsQuery(
    {companyId, folder: currentFolderId, orderBy, orderDirection, mimeTypeStartsWithFilters},
    {
      skip: !canSelect || combinedUploadState === UPLOAD_STATES.uploading || filesToDelete.length > 0,
    }
  );

  const items = useMemo(() => {
    return filterFilesByMimeType({mimeTypeStartsWithFilters, files: data});
  }, [mimeTypeStartsWithFilters, data]);
```

"defaultFiles" is just an empty array btw, defined statically outside the component.
"filterFilesByMimeType" is just doing an items.filter, based on the mimeTypeStartsWithFilters array.

The result is that "items" array is new on every render, whereas I was under the impression that it would only be a new reference if the data returned from the query changes.

**Comment by markerikson** [comment]
Hmm. Looking at our implementation here, it seems like we re-create the final selector every time `selectFromResult` changes, then we call it as part of an inlined selector passed to `useSelector`:

https://github.com/reduxjs/redux-toolkit/blob/637b0cad2b227079ccd0c5a3073c09ace6d8759e/packages/toolkit/src/query/react/buildHooks.ts#L810-L819

I'm actually not 100% sure just how often that will end up getting called.  Seems like a good time to make a Replay.  Could you use https://docs.replay.io/docs/recording-bug-reports-80c37d7d6753485f81497570625d06f0 and try recording an example of either your actual app or a smaller repro so we can look at the behavior?

**Comment by phryneas** [comment]
This is just like a Redux selector - if you are doing something like filtering, you should be using a memoized selector.

```js
const mySelector = useMemo(() => createSelector(result => result.data, data.filter(...))
const result = useMyQuery(arg, { selectFromResult: mySelector })
```

**Comment by einarq** [comment]
Ok. I might be reading it wrong, but I feel that this section from the docs
imply that the selector won't run unless the data from the query changes.
But your suggestion looks good, now I know. Thanks :)

"selectFromResult allows you to get a specific segment from a query result
in a performant manner. When using this feature, the component will not
rerender unless the underlying data of the selected item has changed."

**Comment by ssangervasi** [comment]
Just ran into this same question and I think I've pinpointed why the [documentation](https://redux-toolkit.js.org/rtk-query/usage/queries#selecting-data-from-a-query-result) is confusing: the code example constructs an object that would change constantly, but claims it won't rerender.

```ts
  // Will select the post with the given id, and will only rerender if the given posts data changes
  const { post } = api.useGetPostsQuery(undefined, {
    selectFromResult: ({ data }) => ({
      post: data?.find((post) => post.id === id),
    }),
  })
```

Based on my experiments ([sandbox](https://codesandbox.io/s/redux-toolkit-2208-selectfromresult-zgf1p9?file=/src/example.tsx)) and the discussion in this thread, it makes sense that you'd need a memoized selector and that this example is wrong. Maybe the example intended to return the found post directly (which wouldn't construct a new object)? Or this example should use `createSelector` as discussed here.

**Comment by markerikson** [comment]
@ssangervasi : that example _should_ be correct as far as I know.

Yes, it's returning a new object like `{post}`, but we explicitly do a _shallow_ comparison on whatever's returned.  So, as long as `result.post` doesn't change, this `useGetPostsQuery` hook won't force a re-render.

**Comment by ssangervasi** [comment]
@markerikson - Wow, I read that line and totally thought I had tried that option. You're right and the docs are right, thanks!
([fixed ](https://codesandbox.io/s/redux-toolkit-2208-selectfromresult-zgf1p9?file=/src/example.tsx:1639-1686)sandbox for posterity)
