### ISSUE TITLE
How properly import queries exported with createApi

### ISSUE THREAD

**Issue by EmanueleGuidotti** [reduxjs/redux-toolkit#2218]
I'm trying to create a simple RTK Query, but when I try to import the query inside my component I get an error `Uncaught TypeError: (0 , _services_movies_services__WEBPACK_IMPORTED_MODULE_0__.useGetPopularMoviesQuery) is not a function`.
Stack blitz example: https://stackblitz.com/edit/react-xxhhf7?file=src%2Fservices%2Fmovies.services.js

Any Idea about why this error happen?

**Comment by phryneas** [comment]
If you want to use the hooks, you have to use a different entry point:
```diff
-import { createApi } from "@reduxjs/toolkit/query";
+import { createApi } from "@reduxjs/toolkit/query/react";
```

**Comment by EmanueleGuidotti** [comment]
Thanks it worked

**Comment by Gripers** [comment]
> If you want to use the hooks, you have to use a different entry point:
> 
> ```diff
> -import { createApi } from "@reduxjs/toolkit/query";
> +import { createApi } from "@reduxjs/toolkit/query/react";
> ```

thanks a lot
