### ISSUE TITLE
RTK Query hook losing type after exporting

### ISSUE THREAD

**Issue by nickwang0808** [reduxjs/redux-toolkit#2221]
We have 2 repos, **common** contains the RTK query stuff, **app** uses the query hook exported from common.

![image](https://user-images.githubusercontent.com/63834422/162544449-34477f97-9087-4524-af9d-e83c1d801618.png)
with in the common repo, everything is working as expected

However when importing it into the app repo, the type is lost
![image](https://user-images.githubusercontent.com/63834422/162544518-fdd6623b-aea1-416a-9918-a86581f85f78.png)

Unsure what the issue is, both are using  "@reduxjs/toolkit": "^1.8.1",

Appreciate any help, thanks!

**Comment by markerikson** [comment]
Huh, weird. Unfortunately I don't think we're going to have any way to investigate this without seeing a repo that demonstrates the problem.

**Comment by nickwang0808** [comment]
> Huh, weird. Unfortunately I don't think we're going to have any way to investigate this without seeing a repo that demonstrates the problem.

let me try to setup a demo repo real quick

**Comment by flast1k** [comment]
Maybe it would be helpful for someone. 
I've faced the same problem and in my case, it was simply solved by adding
 ```
"references": [
    { "path": PATH_TO_MY_COMMON_PACKAGE }
]
```
to **tsconfig.json** in the **app**
