### ISSUE TITLE
RTK Query remains in the loading state(true) in React v18

### ISSUE THREAD

**Issue by wpcodevo** [reduxjs/redux-toolkit#2223]
Well I was using React/React Dom 17 with Redux toolkit and Material UI and everything was working correctly, upon the release of React/React Dom 18 I wanted to give it a try so I updated my project to use the latest versions of React/React Dom.

I also used the createRoot implementation  from react-dom/client  in my index.ts.

Am using RTK Query to fetch data from my backend and I could see that the isLoading state remains true even though the data was successfully fetched from my backend.

I changed the createRoot implementation in the index.ts to the old way and everything started working correctly but I was getting some warning in my console
(ReactDom.render is no longer supported in React 18)

So I had to fallback to React/React-dom 17 again.

Updated: later I realised React.StrictMode was the problem since it unmounts and remounts components with the previous state also re-runs effects.

After removing React.StrictMode everything works correctly now but am not sure it's good to remove StrictMode.

**Comment by phryneas** [comment]
There was a bug in react-redux that only resurfaced with the double-mounting behaviour of R18's StrictMode. That has since been fixed - have you updated your dependencies?

Also, you might want to try the react-redux v8 beta as that one works with new apis in R18 specifically created for that purpose.

**Comment by wpcodevo** [comment]
Thanks, I upgraded to React-redux v8 beta and everything works correctly.
