### ISSUE TITLE
[rtkq] - Infinite loop on bad response

### ISSUE THREAD

**Issue by hornta** [reduxjs/redux-toolkit#2226]
I've put together a minimal reproducible example which demonstrates what I think is a weird behaviour and I'm not sure if this is a bug or if it's the intended behaviour. I'm leaning towards this is intended because everything in this library is quite well thought out.

https://react-router-redux-toolkit-fetch-api-2edfcs.stackblitz.io/

What I expect to happen:
I expect RTKQ to cache the result of the endpoint and not try to do another request within the default cache time.

What happens:
RTKQ disregards the cache time for what I think are non-ok responses (<200 && >299) which results in a infinite request loop.

**Comment by phryneas** [comment]
This is a difficult situation in general:

At some point, RTK Query has to try to get data again or it will be stuck in an error forever.

RTK Query will try to request data on mount  if no data is present yet. 
The key here is "on mount" though - usually this is not a problem. It can become a problem however, if your component unmounts on error and quickly remounts after - which leads to an infinite loop of retrying.

Tbh., I can't think of a really "better" behaviour of the library, so the only thing you can do is probably to prevent this remount-loop to occur.

**Comment by Hypnosphi** [comment]
My rule of thumb for this is: whenever I handle a loading state, I should also handle an error state

**Comment by ogheneovo12** [comment]
I am having a hard time around this limitation, 
i have an api that returns a list of open stock positions,
there is the dashboard page that displays this stock positions.
i have some set of other global level modals, that also make a call to this api, and use the response to generate stock symbol options.

whenever there's a failure in fetching the stock positions, an infinite loops occurs.

the options i intend trying it is to first ask 
1. the backend to provide another api for fetching stock symbol, but that will still lead to the same issue as there are modals that still fetches that data.
2. ensure only one modal is mounted at a time (not feasible), and not mounted when not visible
3. use controlled queries in the modals, (useLazy)

**Comment by TangoPJ** [comment]
I faced the same problem.. infinite loop of request to API. Did someone find a solution?

**Comment by Nahiek** [comment]
We had this issue in one of our React apps. Avoid re-rendering to fix the issue.

**Comment by griffinbaker12** [comment]
what’s the fix?

**Comment by oricho123** [comment]
> what’s the fix?

As everyone said, Avoid re-rendering to fix the issue.
To achieve this you can add a return condition on error  before your `return` block, to not render any children
```typescript
  if (isError) {
    return <ErrorComponent />;
  }
```
