### ISSUE TITLE
(ts) How can I create a toggle function with a reducer?

### ISSUE THREAD

**Issue by simm4256** [reduxjs/redux-toolkit#2227]
i want to create a reducer that toggle some state value (boolean)

i tryed like this, but it shows compile error :(

i know that if state has only boolean type properties, it worked.
but i want to make it when state has various type properties.

```ts
import { createSlice, PayloadAction } from '@reduxjs/toolkit'

export interface ToggleInterface{
    toggleKey1 : boolean;
    toggleKey2 : boolean;
    toggleKey3: boolean;
    id: number; // if state hasn't this property, this cord will be worked.
}
const initialState: ToggleInterface = {
    toggleKey1 : true,
    toggleKey2 : false,
    toggleKey3: false,
    id: 1,
}

export const toggleSlice = createSlice({
    name: 'toggle',
    initialState,
    reducers: {
        toggleValue: (state, action: PayloadAction<keyof ToggleInterface>) => {
            // complie error : Type 'boolean' is not assignable to type 'never'.ts(2322)}
            state[action.payload] = !state[action.payload];
        }
    }
});
 
...
```

**Comment by simm4256** [comment]
oh i find it!

you should write action's type contains only boolean type properties in PayloadActions

e.g. 

```ts
toggleInfoValue: (state, action: PayloadAction<Exclude<keyof ToggleInterface, 'id'>>) => {
    state[action.payload] = !state[action.payload];
}
```

**Comment by phryneas** [comment]
Although I want to add that a "toggle" action is almost as bad as a "setter" action in most cases. Usually you should write [meaningful action names](https://redux.js.org/style-guide/style-guide/#write-meaningful-action-names) describing events that happened in your application and have the reducers figure out what state change should happen based on that
