### ISSUE TITLE
RTKQuery SSR custom auth headers. 

### ISSUE THREAD

**Issue by joel1st** [reduxjs/redux-toolkit#2228]
Hello :) 

I'm trying to work out the best approach to using RTKQuery with SSR and auth cookies/headers.

At the moment we are using cookies for our auth, which means that in a browser environment (client side) every fetch request automatically attaches the cookies and auth succeeds. 

On the server side, this is a little more tricky. We can access the cookies in next.js via the server side context prop. (eg `ctx.req.headers`), but then I'm not sure how this cookie header can be passed into rtkquery.

I can think of one option:

We can insert cookie data into the redux store on the server side and then in the `prepareHeaders` function we can access the store with `getState()` and set a cookie header - This way we only have the auth logic in one place, but I am weary about inserting cookie creds into the store. I guess I could dispatch an action afterwards to remove the cookies so they aren't hydrated to the client side.. but it sounds messy.

Is there a more established way of achieving this or does this sound right?

**Comment by phryneas** [comment]
Hmm. Can't you inject the current `request` into the store thunk's `extra` when you create the store in same way? That would be how I'd go about it 🤔

**Comment by joel1st** [comment]
> Hmm. Can't you inject the current `request` into the store thunk's `extra` when you create the store in same way? That would be how I'd go about it 🤔
> 
> `next-redux-wrapper`'s `makeStore` should have access to `Context`.

Thanks for the reply @phryneas - this approach sounds really promising. Just to confirm, are you suggesting to add to the extraArgument via genDefaultMiddleware https://redux-toolkit.js.org/api/getDefaultMiddleware and then consume that extra inside prepareHeaders? That sounds like it will work well (assuming extra is not hydrated to the client side).

**Comment by phryneas** [comment]
Yup, that's my suggestion. `extra` will not be hydrated, only the state.

**Comment by joel1st** [comment]
@phryneas - this worked perfectly, thanks for your help :)

**Comment by vanaf25** [comment]
> Yup, that's my suggestion. `extra` will not be hydrated, only the state.
Yup it is library?

**Comment by phryneas** [comment]
@vanaf25 "yup" in this context is me saying "yes"

**Comment by NikkiMather** [comment]
@joel1st How did you manage to consume that context? I'm trying to do the same thing, but don't really understand where I can access the context during SSR and have it end up in my `createApi`.

**Comment by wh5938316** [comment]
> > Hmm. Can't you inject the current `request` into the store thunk's `extra` when you create the store in same way? That would be how I'd go about it 🤔
> > `next-redux-wrapper`'s `makeStore` should have access to `Context`.
> 
> Thanks for the reply @phryneas - this approach sounds really promising. Just to confirm, are you suggesting to add to the extraArgument via genDefaultMiddleware https://redux-toolkit.js.org/api/getDefaultMiddleware and then consume that extra inside prepareHeaders? That sounds like it will work well (assuming extra is not hydrated to the client side).

I have similar problems, but I know how to `inject the current request into the store thunk's extra with genDefaultMiddleware `. Can you give me some suggestions or demo code please.

**Comment by NikkiMather** [comment]
> > > Hmm. Can't you inject the current `request` into the store thunk's `extra` when you create the store in same way? That would be how I'd go about it 🤔
> > > `next-redux-wrapper`'s `makeStore` should have access to `Context`.
> > 
> > 
> > Thanks for the reply @phryneas - this approach sounds really promising. Just to confirm, are you suggesting to add to the extraArgument via genDefaultMiddleware https://redux-toolkit.js.org/api/getDefaultMiddleware and then consume that extra inside prepareHeaders? That sounds like it will work well (assuming extra is not hydrated to the client side).
> 
> I have similar problems, but I know how to `inject the current request into the store thunk's extra with genDefaultMiddleware `. Can you give me some suggestions or demo code please.

Check @urhot’s commits above, it includes examples which I was able to use to solve  the same problem. Imo this should be covered more extensively in the docs.

**Comment by faisal212** [comment]
@NikkiMather  where is that commits or example? can you share the  link please

**Comment by karanshah229** [comment]
@phryneas Can you please add an example either here or in the docs to achieve this.

**Comment by n0ir1** [comment]
> @phryneas Can you please add an example either here or in the docs to achieve this.
@karanshah229 something like this

import { createWrapper } from 'next-redux-wrapper'
import { configureStore } from '@reduxjs/toolkit'
import { fetchBaseQuery } from '@reduxjs/toolkit/query'

const baseQuery = fetchBaseQuery({
  baseUrl: '/',
  prepareHeaders: (headers, { extra }) => {
    console.log(extra.cookies) // cookies is the name of the field added to the extraArgument

    return headers
  },
})

const makeStore = (context) =>
  configureStore({
    reducer: {
      [baseApi.reducerPath]: baseApi.reducer,
    },
    middleware: (getDefaultMiddleware) =>
      getDefaultMiddleware({
        thunk: {
          extraArgument: {
            cookies: context.ctx?.req?.cookies
          },
        },
      }).concat(baseApi.middleware),
  })

export const wrapper = createWrapper(makeStore)

**Comment by browyn** [comment]
I am trying to achieve the same thing this issue addressed, so far, I have been able to get access to the cookies in `prepareHeaders`. I console log it and I can see the cookie in the and the updated headers in my terminal, but when I look at my browser's request headers when making a request... the Bearer token ends up being `undefined`.

Here's my code

```
export const api = createApi({
  reducerPath: "api",
  baseQuery: fetchBaseQuery({
    baseUrl: "http://localhost:8000/api/v1/",
    credentials: "same-origin",
    prepareHeaders: (headers, { extra }) => {
      headers.set("Access-Control-Allow-Origin", "*");
      headers.set("Content-Type", "application/json");
      headers.set(
        "Authorization",
        `Bearer ${extra.context?.req?.cookies?.accessToken}`
      );

      console.log(headers);

      return headers;
    },
  }),
  extractRehydrationInfo(action, { reducerPath }) {
    if (action.type === HYDRATE) {
      return action.payload[reducerPath];
    }
  },
  tagTypes: ["User", "Property"],
  endpoints: () => ({}),
});
```


I also tried checking the `typeof window` before setting the headers, but same thing still happens

**Comment by n0ir1** [comment]
> I am trying to achieve the same thing this issue addressed, so far, I have been able to get access to the cookies in `prepareHeaders`. I console log it and I can see the cookie in the and the updated headers in my terminal, but when I look at my browser's request headers when making a request... the Bearer token ends up being `undefined`.
> 
> Here's my code
> 
> ```
> export const api = createApi({
>   reducerPath: "api",
>   baseQuery: fetchBaseQuery({
>     baseUrl: "http://localhost:8000/api/v1/",
>     credentials: "same-origin",
>     prepareHeaders: (headers, { extra }) => {
>       headers.set("Access-Control-Allow-Origin", "*");
>       headers.set("Content-Type", "application/json");
>       headers.set(
>         "Authorization",
>         `Bearer ${extra.context?.req?.cookies?.accessToken}`
>       );
> 
>       console.log(headers);
> 
>       return headers;
>     },
>   }),
>   extractRehydrationInfo(action, { reducerPath }) {
>     if (action.type === HYDRATE) {
>       return action.payload[reducerPath];
>     }
>   },
>   tagTypes: ["User", "Property"],
>   endpoints: () => ({}),
> });
> ```
> 
> I also tried checking the `typeof window` before setting the headers, but same thing still happens

Because this is the context from your server requests, on the client it will be an empty object and cookies must be received differently

You can use the cookies-next library and make something like this
```js
import { getCookies } from 'cookies-next'

const makeStore = (context) =>
  configureStore({
    reducer: {
      // your code
    },
    middleware: (getDefaultMiddleware) =>
      getDefaultMiddleware({
        thunk: {
          extraArgument: {
            cookies: getCookies({ req: context.ctx?.req, res: context.ctx?.res })
          },
        },
      }).concat(baseApi.middleware),
  })
```

**Comment by phryneas** [comment]
I am honestly very irritated that you would take things out of a cookie to send a header to the server. The whole point of a cookie is that it is automatically sent to the server by the client. Why the extra header? Shouldn't the server set the cookie and also receive the cookie, with the client not ever touching it?

**Comment by browyn** [comment]
Honestly, I am irritated as much as you are.
After reading about authentication best practices, the way you mentioned is one of the best way... but my hands are tied as I am not in charge of the backend application and all my efforts to talk with the developer in charge about best practices regarding this has not been productive so far

So I am stuck with having to make it work the way it is.

**Comment by browyn** [comment]
Honestly, I am irritated as much as you are.
After reading about authentication best practices, the way you mentioned is one of the best way... but my hands are tied as I am not in charge of the backend application and all my efforts to talk with the developer in charge about best practices regarding this has not been productive so far

So I am stuck with having to make it work the way it is.

**Comment by browyn** [comment]
Thanks @n0ir1 it works.

**Comment by browyn** [comment]
Also @phryneas I was able to get hold of the backend application and I am already transitioning from the current authentication flow to the one you suggested.

I was able to send the cookie to the browser, however the server expects me to send back the value of the **XSRF-TOKEN** back in the **X-XSRF-TOKEN** header, even with _credentials_ set to _include_ , it doesn't send the **X-XSRF-TOKEN** along with the header, I still have to go in and set this manually.

Laravel did say that some HTTP library or system won't be able to do this, but did say **axios** is capable of doing so.

I was wondering if I an achieve that with `fetchBaseQuery` before I move to build a baseQuery with axios

**Comment by phryneas** [comment]
@browyn every client-side fetching solution will allow you to set any possible header.

**Comment by browyn** [comment]
Yes correct, but Laravel suggests to allow the client side fetching solution to set this X-XSRF-TOKEN in the headers automatically and not me going in to explicitly set the headers to send the X-XSRF-TOKEN

**Comment by phryneas** [comment]
How would any solution do that without you telling it what value that token should have?

**Comment by browyn** [comment]
Laravel explains this in their sanctum documentation.

Perhaps I am missing something, but here's a [link](https://laravel.com/docs/10.x/sanctum#csrf-protection) to it

**Comment by phryneas** [comment]
Huh. `xsrfCookieName` is actually a feature. 
Tbh., I wouldn't change to axios based on that though. That's a few lines in `prepareHeaders` vs a 6-kb dependency.

**Comment by browyn** [comment]
How do I go about it.

Currently here's what I have 

```
prepareHeaders: (headers, { extra }) => {
      headers.set("Access-Control-Allow-Origin", "*");
      headers.set("Content-Type", "application/json");
      headers.set(
        "X-XSRF-TOKEN",
        `${extra.cookies?[XSRF-TOKEN]}`
      );
     
      return headers;
    },
```

This gets the cookie sent by Laravel and creates the X-XSRF-TOKEN header.

However, this lags behind.
Laravel says to call the "/sanctum/csrf-token" to set the cookie in the browser before calling the login endpoint.

So when I do that, and call the login endpoint, the header doesn't get added, even though the cookie is present until I give the page a full refresh and try again

**Comment by browyn** [comment]
Please 🥺, anyway to go about this except using this approach?

**Comment by browyn** [comment]
Well, I ended up building a baseQuery on top of axios to achieve what I need.
With axios I need not get cookie and set a header based on that cookie.

Building the baseQuery on top of axios was the way to go for me.

**Comment by browyn** [comment]
Unfortunately, with each step forward, I hit a stronger problem.

At the moment, I am successfully using RTK query in **getSeverSideProps** to access laravel API routes, however, when I try to access a protected API route in **getSeverSideProps**, it never works, but the hook call always go.

Laravel sanctum authentication requires a Cookie Header and a X-XSRF-TOKEN header to work properly, and none of this is being set whenever is initiate query inside of **getServerSideProps**, which prevents me from accessing protected API routes.

Please is there any possible way to go about this.

I had to try something unsafe (setting the Cookie Header explicitly using `getCookies` function from `cookies-next`), it still didn't work.

Please, I would really appreciate help on this, I have been on this for days. 😔

**Comment by Siumauricio** [comment]
I ended up doing the following to solve this issue 

First we set the token into the store, because if we dont do this we are not be able to retrieve the token in `prepareHeaders`
```ts
export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async ({ req, res }) => {
      // WE inject the token into the state
      store.dispatch(setToken(req.cookies.token));
      const token = store.getState().auth.token;
      console.log(token); // Then we got the token and we can use in to the prepareHeaders since is already in the state
      const response = await store.dispatch(GetProducts.initiate());
      console.log(response.data);
      return {
        props: {},
      };
    }
);
```

Then we can inject the headers as whatever you want 
```ts
import { GraphQLClient } from "graphql-request";
import { createApi } from "@reduxjs/toolkit/query/react";
import { graphqlRequestBaseQuery } from "@rtk-query/graphql-request-base-query";
import { RootState } from "../store";

export const client = new GraphQLClient(process.env.NEXT_PUBLIC_BACKEND_URL, {
  credentials: "include",
});

export const api = createApi({
  baseQuery: graphqlRequestBaseQuery({
    // @ts-ignore
    client,
    prepareHeaders: (headers, { getState }) => {
      const token = (getState() as RootState).auth.token;
      if (token) {
        // Can use 1 or both of these
        headers.set("Cookie", `token=${token}`);
        headers.set("Authorization", `Bearer ${token}`);
      }

      return headers;
    },
  }),
  endpoints: () => ({}),
});
```

I also drop the authSlice if anyone want to known....
```ts
import { createSlice } from "@reduxjs/toolkit";
import { AuthResponse, Roles } from "../../graphql/generated/generated";

const initialState: AuthResponse & { isAuthenticated: boolean } = {
  token: "",
  isAuthenticated: false,
  user: {
    creationDate: "",
    email: "",
    firstName: "",
    isActive: false,
    lastName: "",
    phoneNumber: "",
    rol: Roles.User,
    userId: "",
  },
};

export const authSlice = createSlice({
  name: "auth",
  initialState,

  reducers: {
    setProps: (state, action) => {
      const { user, token } = action.payload.login;
      state.user = user;
      state.token = token;
      state.isAuthenticated = true;
      localStorage.setItem("auth", JSON.stringify(state));
      return state;
    },
    setToken: (state, action) => {
      state.token = action.payload;
      return state;
    },
    logout: (state) => {
      state = {
        ...initialState,
      };
      localStorage.removeItem("auth");
      return state;
    },
  },
});

// Action creators are generated for each case reducer function
export const { setProps, logout, setToken } = authSlice.actions;

export default authSlice.reducer;
```
