### ISSUE TITLE
After the Redux data is updated in the transformresponse method, there is no change in the store,

### ISSUE THREAD

**Issue by fu1996** [reduxjs/redux-toolkit#2229]
codebox: [demo](https://codesandbox.io/s/rtk-entities-basic-example-with-normalizr-forked-bjy2l0?file=/src/features/articles/articlesSlice.js)

I have tried many writing methods, but I still can't change the data of the store through the transformresponse method,
Please open Redux devtool to view. This is the official way of writing, [redux-toolkit-demo](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#examples---transformresponse) I didn't find anything inappropriate in my writing

3Q。

**Comment by phryneas** [comment]
It seems to work just fine from what I can see
![image](https://user-images.githubusercontent.com/4282439/162805384-36d503c3-80b0-4fc4-8d54-8e1c78d16b21.png)

The result is an `entityAdapter` shape.

The only thing that doesn't seem to work is your `normalizer` call, but that is not a problem with RTK or RTK Query.

**Comment by fu1996** [comment]
> It seems to work just fine from what I can see ![image](https://user-images.githubusercontent.com/4282439/162805384-36d503c3-80b0-4fc4-8d54-8e1c78d16b21.png)
> 
> The result is an `entityAdapter` shape.
> 
> The only thing that doesn't seem to work is your `normalizer` call, but that is not a problem with RTK or RTK Query.

Yes, you're great, articles adapter Addmany accepts one state and one entity object before updating. Is addmany invalid because the state object obtained here is incorrect? Do you have a good way to make addmany update the state correctly? 3Q

**Comment by phryneas** [comment]
I think you are adding only one, not many. It doesn't look like normalizr normalized anything here before you added it.

**Comment by markerikson** [comment]
Closing because I don't think there's anything actionable for us here.
