### ISSUE TITLE
[Feature] Set custom error object in rtk-query/graphql-request-base-query  

### ISSUE THREAD

**Issue by antoniodinovi** [reduxjs/redux-toolkit#2231]
Proposal Feature:
`graphqlRequestBaseQuery` shoud  give the option to set the error response object, using the graphql response

Possible example:
```
export const api = createApi({
  baseQuery: graphqlRequestBaseQuery({
    client,
    customErrors: ({ name, message, request, stack, response }) => {
      return {
        name,
        stack,
        message: response?.errors[0]?.extensions?.errorMessage,
        errorCode: response?.errors[0]?.extensions?.errorCode
      };
    }
  }),
  endpoints: () => ({}),
  refetchOnMountOrArgChange: true
});
```

In the example the **`customError`** callback provides the error returned from the `graphql-response` client

**Comment by antoniodinovi** [comment]
I also add the link to the stackoverflow question which describes the problem https://stackoverflow.com/questions/71828943/how-to-handle-error-format-in-redux-toolkit-rtk-query-graphql-application

**Comment by faizanali1192** [comment]
@antoniodinovi have you solved this isssue?

**Comment by antoniodinovi** [comment]
Yes, here the pull request link https://github.com/reduxjs/redux-toolkit/pull/2232Antonio Di Novia:Piazzale Flaminio 19, 00196 Rome - Italy ---- On Tue, 19 Apr 2022 13:40:44 +0200  ***@***.***  wrote ----
@antoniodinovi have you solved this isssue?

**Comment by antoniodinovi** [comment]
Hi @phryneas @markerikson, do you will soon or later consider this feature to be merged in the next releases? This implementation is quite simple but is very helpful to handle errors in graphql response.

Thanks
Antonio

**Comment by phryneas** [comment]
Yeah, I'm very sorry - I mean I suggested you do this PR in the first place. Unfortunately I'm pretty much behind on everything right now. I'll try to get to it soon, but it's probably going to be end of next week.

**Comment by AleksandrukTad** [comment]
Any update on this one?

**Comment by phryneas** [comment]
My plan was to spend the day on PRs, so I'm getting to this one next :)

**Comment by phryneas** [comment]
Published as @rtk-query/graphql-request-base-query@2.1.0.
