### ISSUE TITLE
Clarify `configureStore` intent and behavior in API ref

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#2238]
The API ref for `configureStore` ( https://redux-toolkit.js.org/api/configureStore ) doesn't give any real details on what it actually _does_, how it compares to `createStore`, or why you should use it instead.  It just says it's a "friendly abstraction".

We should fill in a lot more details to explain the technical differences and intent.

Lenz has a good explanation in a Twitter thread starting here that we should copy-paste as a starting poing:

https://twitter.com/phry/status/1514338477810360322

(While we're at it, we should review the other docs pages to see if similar explanations should be added.)

**Comment by phryneas** [comment]
But we also should take care that it still makes sense for people who don't know about `createStore`, `combineReducers` and `applyMiddleware`
