### ISSUE TITLE
Cannot connect to redux dev tools

### ISSUE THREAD

**Issue by musabgulfam** [reduxjs/redux-toolkit#2248]
I can't connect to my react native metro bundler, which is running on localhost:8081.

This is my redux store

```
const composeEnhancers = composeWithDevTools({
    realtime: true,
    name: 'ReversationApp',
    hostname: 'localhost',
    port: 8081 // the port your remotedev server is running at
});

const store = createStore(reducer, composeEnhancers());
```
Redux dev tool doesn't display anything

<img width="856" alt="Screenshot 2022-04-17 at 2 04 47 AM" src="https://user-images.githubusercontent.com/40719485/163691327-726600ab-4270-483d-8656-f42cccd96047.png">

Trying to connect to localhost:8081, but to no avail.

<img width="856" alt="Screenshot 2022-04-17 at 2 08 41 AM" src="https://user-images.githubusercontent.com/40719485/163691410-edf3cd3e-d307-4246-a230-7d7185fe72d4.png">

**Comment by musabgulfam** [comment]
???

**Comment by phryneas** [comment]
You are asking a DevTools question in the Redux Toolkit repository here and your example is not even using Redux Toolkit, but the normal `redux` `createStory`. I'm not sure if this is the right place for you to ask.

But generally: if you use the host/port configuration, you also have to have a server running on that port and host - I don't see any mention of that here.

**Comment by mavrikio** [comment]
https://reactnative.dev/docs/next/other-debugging-methods

Remote debugging must be enabled to connect with react native debugger.

To do this, you need to import...

import NativeDevSettings from 'react-native/Libraries/NativeModules/specs/NativeDevSettings';

And add the following code to your main component:

const connectToRemoteDebugger = () => {
        NativeDevSettings.setIsDebuggingRemotely(true);
};
