### ISSUE TITLE
RTK Query, remove old cache

### ISSUE THREAD

**Issue by lpradopostigo** [reduxjs/redux-toolkit#2253]
I have an electron application that has a query that fetches data every second because I need to be in sync with a process running in the host machine. The problem is that when I manually update the cache seems like the old data is kept somewhere which I think is causing a memory leak, maybe there is a way to suppress that behaviour?. Below is the query:

```javascript
getState: builder.query({
      query: () => ({ handler: "get-state" }),
      providesTags: ["player"],
      async onCacheEntryAdded(
        _,
        { updateCachedData, cacheDataLoaded, cacheEntryRemoved }
      ) {
        let intervalId;
        try {
          await cacheDataLoaded;

          intervalId = setInterval(async () => {
             // get the current state of the process
            const { data } = await ipcQuery({ baseHandler: "player" })({
              handler: "get-state",
            });
       
            // if I comment this call the memory leak doesn't happen
            updateCachedData((draft) => {
              Object.assign(draft, data);
            }); 
          }, 1000);
        } catch {
          // this was intentional
        }

        await cacheEntryRemoved;
        clearInterval(intervalId);
      },
    }),
```

**Comment by phryneas** [comment]
Generally not, but each of those calls will dispatch an action and that might get cached by the Redux Devtools - does the problem occur without the Devtools active?

**Comment by lpradopostigo** [comment]
I tried disabling all the developer tools, i was only using the React. I closed the devtools too, here is what happened after 30min aprox: 

No memory leak, it started at ~150mb and ended at ~170mb
```javascript
 intervalId = setInterval(async () => {
            const { data } = await ipcQuery({ baseHandler: "player" })({
              handler: "get-state",
            });

            console.log(data);

            updateCachedData((draft) => {
              // Object.assign(draft, data);
            });
          }, 1000);
```

Memory leak, it started at ~200mb and ended at ~350mb
```javascript
 intervalId = setInterval(async () => {
            const { data } = await ipcQuery({ baseHandler: "player" })({
              handler: "get-state",
            });
            updateCachedData((draft) => {
              Object.assign(draft, data);
            });
          }, 1000);
```

Seem like getting the process state doesn't cause the problem, and only occur when the cache changes, I have to mention that my data is kinda heavy it has 3 base64 images and nested objects. I will appreciate any insight.

**Comment by phryneas** [comment]
Hmm, so the relevant code is 
https://github.com/reduxjs/redux-toolkit/blob/e7a98eba3fbef2137109dc68caff305f603f4d1d/packages/toolkit/src/query/core/buildThunks.ts#L218-L256
and
https://github.com/reduxjs/redux-toolkit/blob/8c23cd33971ae5a62bc19764adca6f6be2ed98ec/packages/toolkit/src/query/core/buildSlice.ts#L120-L132
tbh., none of these looks very suspicious for any kind of memory leak 🤔

**Comment by lpradopostigo** [comment]
I see, I measured the browser performance and the difference is the amount of listeners
![image](https://user-images.githubusercontent.com/79614460/163852453-7b0aa8ac-9b9c-4903-b20f-4e8f1363594d.png)

![image](https://user-images.githubusercontent.com/79614460/163852396-35cab821-64aa-4e7a-bd60-b4f738133333.png)

The second one leaks, currently at 1.5gb in the task manager on windows. Maybe it has to do with some side effects caused by the cache being updated, for now I'll check those

**Comment by phryneas** [comment]
It seems that you are somehow accumulating tons of listeners there. Maybe you subscribe listeners on every rerender or something?

**Comment by lpradopostigo** [comment]
I found the culprit, it was a component that comes from another library, the Slider component from Mantine , thanks I'll close the issue
