### ISSUE TITLE
Module '"@reduxjs/toolkit"' has no exported member 'createAsyncThunk'.

### ISSUE THREAD

**Issue by Standupic** [reduxjs/redux-toolkit#2256]
TypeScript does not see method createAsyncThunk from 'reduxjs/toolit'

**Comment by phryneas** [comment]
It very much does, otherwise all our tests and examples would fail building. 

If it does not do that for you, you will need to provide a reproduction, otherwise we have no idea what is going on on your end.

**Comment by Standupic** [comment]
Somehow I downloaded reduxjs/toolkit version of  1.2.5 when i change to 1.7.1 the problem has gone.
