### ISSUE TITLE
reducer definition with PayloadAction causes unexpected action type

### ISSUE THREAD

**Issue by shmoon2917** [reduxjs/redux-toolkit#2258]
Hello, I have a problem

In the offical docs, It says that
> As `createSlice` creates your actions as well as your reducer for you, you don't have to worry about type safety here. Action types can just be provided inline:

```ts
const slice = createSlice({
  name: 'test',
  initialState: 0,
  reducers: {
    increment: (state, action: PayloadAction<number>) => state + action.payload,
  },
})
// now available:
slice.actions.increment(2)
```

So after reading this part, I checked this action type but it typed with optional payload like below.

```ts
type IncrementAction = slice.actions.increment // ActionCreatorWithOptionalPayload<boolean, string>

slice.actions.increment() // no error even though I typed reducer with PayloadAction
```

I typed it with `PayloadAction`, but why is it optional? The most confusing part is when I deleting type, type error works well.
```ts
const slice = createSlice({
  name: 'test',
  initialState: 0,
  reducers: {
    increment: (state, action) => state + action.payload
  },
})

type IncrementAction = slice.actions.increment // ActionCreatorWithPayload<any, string>

slice.actions.increment() // error! Expected 1 arguments, but got 0.
```

This is unexpected result in my view, But maybe I don't know why it's implemented like this. 
It would be grateful if you could explain about this.

### ps.
Is there a convention that defines reducer used for slice from the outside? I'm struggling but It's not easy to resolving type issue :(

```ts
const reducers = {
  increment: (state) => {
    console.log(state);
  }),
  decrement: (state, action: PayloadAction<number>) => {
    console.log(action);
  },
};

// want to define reducers outside from slice
const slice = createSlice({
 ...
 reducers,
 ...
}
```

**Comment by phryneas** [comment]
I would assume that in your `tsconfig.json` you are either missing `strict: true` or have manually set `strictNullChecks: false` - in that case we cannot really infer if something should be there or optional and fall back to optional behaviour.

To be honest, non-strict TypeScript is a nightmare and we cannot guarantee that anything will work in such an environment. You are just disabling central features of the programming language.

As for your other question: that would work, but of course you have to specify a `state` type in that case, as it cannot be inferred. I wouldn't really recommend doing that as it has no real benefit.
