### ISSUE TITLE
In tsconfig, when using base url, it gets store.getState type error.

### ISSUE THREAD

**Issue by ahmetcaglayan** [reduxjs/redux-toolkit#2259]
In tsconfig, when using base url, it gets store.getState type error.

![a2](https://user-images.githubusercontent.com/13018803/163865687-f634ff22-651e-4b51-8939-3d1c244b63ae.png)

![a1](https://user-images.githubusercontent.com/13018803/163865665-3acdcf12-c87e-4281-8c8e-0f5622449e17.png)

but deleting the baseUrl property fixes the problem. But this time, there is a problem with my other imports.

![a3](https://user-images.githubusercontent.com/13018803/163865879-513bd595-ce30-46f1-bbb7-4896563527eb.png)

![a4](https://user-images.githubusercontent.com/13018803/163865885-852a6e75-3a85-4ac1-b1f4-1e3f835a83d5.png)

can you help me?

**Comment by phryneas** [comment]
Do you have a folder `redux` somewhere? Please rename it.

**Comment by ahmetcaglayan** [comment]
Ohh yes, 😊🙏 ty

**Comment by arundevkv** [comment]
I have same issue. I tried renaming my folder `redux` to `store`. But the type error is there.

**Comment by phryneas** [comment]
@arundevkv please specify: do you also have a base url or are you just getting an error? is it 100% the same error as shown here or a different error?

**Comment by arundevkv** [comment]
I have `"baseUrl": ".",` and this is my store file
```
import { configureStore, combineReducers } from '@reduxjs/toolkit'; 
import accountReducer from 'modules/Account/accountSlice';
import changeColorStatusbar from './reducers/statusbarReducer';
import userReducer from './reducers/userReducer';

const reducer = combineReducers({
    user: userReducer,
    statusbarColor: changeColorStatusbar,
    accounts: accountReducer,
});
const store = () =>
    configureStore({
        reducer,
    });

export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;

export default store;
```
Getting this type error
`Property 'getState' does not exist on type '() => EnhancedStore<CombinedState<{ user: any; statusbarColor: never; accounts: { accountData: {}; loading: string; error: null; }; }>, AnyAction, [ThunkMiddleware<CombinedState<{ user: any; statusbarColor: never; accounts: { ...; }; }>, AnyAction, undefined>]>'.ts(2339)`

**Comment by phryneas** [comment]
That is a completely different error.


In all our examples, it is
```js
const store = configureStore({
        reducer,
    });
```

**Comment by ahmetcaglayan** [comment]
@arundevkv copper that can add screenshots of reducers.

**Comment by ahmetcaglayan** [comment]
@arundevkv or try it with a simple reducer
