### ISSUE TITLE
Getting Return type of useXQuery

### ISSUE THREAD

**Issue by ChuckJonas** [reduxjs/redux-toolkit#2263]
I have a use case where I need to declare a type for the return type of a useQuery function.  I would expect to be able to do something like this:

```
type useGetPetByIdQueryResult = ReturnType<typeof useGetPetByIdQuery>
let x: useGetPetByIdQueryResult;
```

And `x.data` would be `Pet | undefined`.

However, the only properly that gets defined for `useGetPetByIdQueryResult` is `refetch`.

Perhaps there is an easier way to do this?

**Comment by phryneas** [comment]
Unfortunately not really - with a varying `selectFromResult` option, that hook can return *anything*.

You can try to use an Instantiation Expression in TypeScript 4.7 - assuming that also allows you to get the default value:

```ts
const withDefault = useGetPetByIdQuery<>
type useGetPetByIdQueryResult = ReturnType<typeof withDefault >
```

but I have not tried this yet myself
