### ISSUE TITLE
RTK Query: Native support for HTTP ETags

### ISSUE THREAD

**Issue by hahanein** [reduxjs/redux-toolkit#2264]
It would be great if there was native support for HTTP ETags because currently it is extremely awkward to handle them.

Basically, on receiving the ETag header. One would send the value of that header with a If-None-Match header on the next request.

It is extremely awkward to implement this behavior because there are no means to access `state` in `QueryAttribute`. Therefore, implementing this apparently means tracking queries in `BaseQueryFn`. This strikes me as extremely brittle because redux might use another procedure to tell whether 2 queries are the same.

**Comment by phryneas** [comment]
Do you have a solution for this or why are you closing it? Actually I think it's quite the interesting question (although i have no immediate solution for you).

**Comment by sashless** [comment]
Thanks you @hahanein. After reading more about ETags i think you are right. The browser seems to handle this for any kind of request.
