### ISSUE TITLE
TS: Explicitly typing the query options parameter, turns the return value to any

### ISSUE THREAD

**Issue by PEsteves8** [reduxjs/redux-toolkit#2265]
Hi,

I'm struggling with this weird behavior. If the options parameter is explicitly set (using the query itself), the return value will be typed as `any`.

In the following example, `returnedValue`  will be `any`

```
  const options: Parameters<typeof useSomeQuery>[1] = { refetchOnMountOrArgChange: false };
  
  const returnedValue = useSomeQuery(undefined, options); // typeof returnedValue === any
```

However, just casting the options to `any`, the returnedValue will be correctly typed. Like so:

```
  const options: Parameters<typeof useSomeQuery>[1] = { refetchOnMountOrArgChange: false };
  
  const returnedValue = useSomeQuery(undefined, options as any); // typeof returnedValue === ReturnType<useSomeQuery>
```

I'm typing the options because I use wrappers to add additional parameters, so I avoid repeating that step anywhere I call the hook.

I tried importing the options type from the rtk library, but that type doesn't seem to be exported.

This issue seems to have some similar aspects, but not sure if it's the same: https://github.com/reduxjs/redux-toolkit/issues/1831

Thanks for everything.

**Comment by phryneas** [comment]
It's more related to https://github.com/reduxjs/redux-toolkit/issues/2263 - is that enough info? :)

**Comment by PEsteves8** [comment]
hmm I don't really understand why the type that's derived directly from the hook would change anything, since presumably it's the same type if it's omitted, but that's due to ignorance on my part of typescript's intricacies.

I tried the ts4.7's Instantiation Expression but the syntax with the empty type params isn't valid (if I was doing it correctly).

In any case, I suppose I could just cast to `any` in the wrappers body for now. It's a little weird, but it works.

Thanks.

**Comment by markerikson** [comment]
Closing as I'm not sure there's anything specific for us to fix here.  If there's a suggestion please let us know!
