### ISSUE TITLE
createAsyncThunk redux toolkit with typescript rejecWithValue and Payload types error

### ISSUE THREAD

**Issue by anisamirouche** [reduxjs/redux-toolkit#2271]
I'm trynig to implement authentifiaction slice in redux toolkit with typescript, but typescript is complaining about rejectWithValue error type and the action payload, please note that i'm using Axios and that i'm following the documentation but still complaining this my code

```ts
import { createAsyncThunk } from '@reduxjs/toolkit';
import { axiosClient } from 'src/network/api-client';
import {AxiosError} from 'axios'

type RegisterPayload = {
  login: string;
  password: string;
  client: string;
  first_name: string;
  last_name: string;
  patronymic: string;
  date_of_birth: string;
};
export type User = {
  token: string;
  refresh_token: string;
  error : KnownError;
};
type KnownError = {
  errorMessage : string;
}
export const registerUser = createAsyncThunk<
{ token: string },
RegisterPayload,
{ rejectValue: KnownError }
>(
  'users/register',
  async (
    {
      login,
      password,
      client,
      first_name,
      last_name,
      patronymic,
      date_of_birth,
    },
    {rejectWithValue}
  ) => {
    try {
      const response = await axiosClient.post<User>('registration', {
        login,
        password,
        client,
        first_name,
        last_name,
        patronymic,
        date_of_birth,
      });
      if (response.status === 201) {
        localStorage.setItem('refresh', response.data.refresh_token);

        return {
          ...response,
          token: response.data.token,
        };
      }else {
        return rejectWithValue(response.data.error);
      }
    } catch (err) {
      const error: AxiosError<KnownError> = err;
      if (!error.response) {
        throw err;
      }
     
    }
);

```
and i'm having these errors, please see photos

![Screenshot 2022-04-21 at 1 44 13 PM](https://user-images.githubusercontent.com/36996198/164604043-45858882-c43e-4ff9-b180-cca0d5ece88d.png)

![Screenshot 2022-04-21 at 1 44 27 PM](https://user-images.githubusercontent.com/36996198/164604063-d6d71195-3130-4cc3-95db-6f1894e1c1b9.png)

![Screenshot 2022-04-21 at 1 44 39 PM](https://user-images.githubusercontent.com/36996198/164604083-ad9b7c36-22da-436b-b756-a9c821f02aca.png)

**Comment by phryneas** [comment]
First big error I spot is that there is a case where your method just returns `undefined`, if it does not have a code of 200, but also didn't throw an error. Fix that and see what's left.

**Comment by anisamirouche** [comment]
> First big error I spot is that there is a case where your method just returns `undefined`, if it does not have a code of 200, but also didn't throw an error. Fix that and see what's left

I updated the code please take a look

**Comment by phryneas** [comment]
And at least the second error is gone I guess? Honestly, with these screenshots this is almost impossible to see anything. 
You'd need to at least provide a [TypeScript playground](https://www.typescriptlang.org/play/) although honestly I have to say that this is not really suited for the "support channel" of a github issue in the first place - discord or stackoverflow would be better places for this.

**Comment by anisamirouche** [comment]
> 

I'm so sorry really, no second error is not gone
here is a typescript playground
[typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQQQM4CeAdsgCoAWArkQNZwC+cAZlBCHAOQAC6AJpQA8AVngD0MCBAA2NYDA4BuALAAoUJFiI4GAcAh4AwlOBoi8Rizac8UZKKJoYAd2g1RGMMAC0yY6fnKauDQ8Ag4uvoAolCsUBas7Bw6engcqqowBGBocABKaADmwHjYUAAKGARSEBi8cAC8iKpwcNVFRABccCVQwEQFgS1gGHh4LlC8XT19A80ofmZTML39g8zAUCUA+kQYIGhLK7MqLVIjMDt7B93LM2vDyxBEBCDAyId3c7xYaFsQTFsAEYbGDkD6rVT0QJoAQaeCZbJwACqeDQUAaTROcAkNFM4OOLXQLDQeHIWxxeJuRzWaNicC6AGkiBAnERorFAlCMlkckyWWyYtAMQg5rToABZEl4DAFHL4zmqGFwlBPEpwdBFEpolFojGoTDYfDEMhUWgAHlUSApnSpMwYABpVPlNaUKlUarxHSokOghGhkDAAGoYKSUa581nsoX0VQAPgAFHMOJRUZtRBriqUOF6WiNjXBE1iWiKiy1WhB2jmy0MRmNoJ65tXfCYzFXq0wNttdvs22Wzl2rr2a49nq9kEO4N9sH8AcDYORe-Rewhff6YAB1OTkYOhtAxrEASgascx1eWBFP1ZVRDV6DwkBvOUaGCcGDk2gihgWMAAdJASmaOpQAmHAZj0WB6EQ2aXle5aVo2V7DKM4wNqWTbfhOLQdpsFzdmgmGtOclw9gh1YPKwo5vARU6-P8QIggupEMAeazVsATAFneD6oj+JRYCmDT1I0ABMAAMACMR4lrBpwQMgIYAMoSFAMpoLxjgAJLYCA8agWgxKktBXGqmpU4YD+RJ3mS1osekaFlugMCUFARAwTJP4ecZj4ES01pdF5PFmT+1oEVy9n0GgUiom51aOc5rmrgGm6gjuYbxgFplYOZYpQLZ4UIYw8kwMg5AFrSUlMcgqrwDlXThCkUZQGaEYCrEJ6NLSrFluxBYAIQ5RZJLcWgFX2b55CsE4cCdUx+5XgVqgsUAA)

**Comment by phryneas** [comment]
If you change that
```diff
const error: AxiosError<KnownError> = err;
const error: AxiosError<KnownError> = err as any;
```
all the erros in that sandbox are gone.

And that is just a general TypeScript problem - this error could be anything. If you don't want to actually check what it is, but just assume that it is hopefully an AxiosError, you will have to `as any` it before.

**Comment by anisamirouche** [comment]
> If you change that
> 
> ```diff
> const error: AxiosError<KnownError> = err;
> const error: AxiosError<KnownError> = err as any;
> ```
> 
> all the erros in that sandbox are gone.
> 
> And that is just a general TypeScript problem - this error could be anything. If you don't want to actually check what it is, but just assume that it is hopefully an AxiosError, you will have to `as any` it before.

yes , but i'm still having the first error in my editor,  the error which has a link wuth types, represented in the first two photos attached, this is a long error message that's why i decided to show in photo

this is the message of the error 

```
Argument of type '({ login, password, client, first_name, last_name, patronymic, date_of_birth, }: RegisterPayload, { rejectWithValue }: GetThunkAPI<{ rejectValue: KnownError; }>) => Promise<RejectWithValue<KnownError, unknown> | { ...; } | undefined>' is not assignable to parameter of type 'AsyncThunkPayloadCreator<{ token: string; }, RegisterPayload, { rejectValue: KnownError; }>'.
  Type 'Promise<RejectWithValue<KnownError, unknown> | { token: string; data: User; status: number; statusText: string; headers: AxiosResponseHeaders; config: AxiosRequestConfig<...>; request?: any; } | undefined>' is not assignable to type 'AsyncThunkPayloadCreatorReturnValue<{ token: string; }, { rejectValue: KnownError; }>'.
    Type 'Promise<RejectWithValue<KnownError, unknown> | { token: string; data: User; status: number; statusText: string; headers: AxiosResponseHeaders; config: AxiosRequestConfig<...>; request?: any; } | undefined>' is not assignable to type 'Promise<{ token: string; } | RejectWithValue<KnownError, unknown>>'.
      Type 'RejectWithValue<KnownError, unknown> | { token: string; data: User; status: number; statusText: string; headers: AxiosResponseHeaders; config: AxiosRequestConfig<...>; request?: any; } | undefined' is not assignable to type '{ token: string; } | RejectWithValue<KnownError, unknown>'.
        Type 'undefined' is not assignable to type '{ token: string; } | RejectWithValue<KnownError, unknown>'.ts(2345)
Not all code paths return a value.ts(7030)
```

**Comment by mahmudipur** [comment]
@anisamirouche did you solve the issue?
I faced to same issue and I'm curious about how to solve it

**Comment by anisamirouche** [comment]
> @anisamirouche did you solve the issue? I faced to same issue and I'm curious about how to solve it
```ts
import { createAsyncThunk } from '@reduxjs/toolkit';
import { axiosClient } from 'src/network/api-client';
import { AxiosError } from 'axios';
import AsyncStorage from '@react-native-async-storage/async-storage';

// types declaration

export type KnownError = {
  message: string;
  description: string;
  code: number | undefined;
};

export interface LoginPayload {
  login: string;
  code: number;
  client: string;
}
export interface User {
  token: string;
  refresh_token: string;
  error: KnownError;
}

// Login action creator
export const loginUser = createAsyncThunk<
  User,
  LoginPayload,
  { rejectValue: KnownError }
>('users/login', async (loginPayload: LoginPayload, { rejectWithValue }) => {
  try {
    const response = await axiosClient.put<User>('login', loginPayload);
    const { data } = response;
    AsyncStorage.setItem('refresh_token', response.data.refresh_token);
    return data;
  } catch (err) {
    const error: AxiosError<KnownError> = err as any;
    if (!error.response) {
      throw err;
    }
    return rejectWithValue(error.response.data);
  }
});
```
This is the code i'm using now and it's wothout errors

**Comment by Devendra0110** [comment]
I was getting error `'error.response' is possibly 'undefined'.ts(18048)` on `error.response.data`. 
so I had to 
```diff
- { rejectValue: KnownError }
+{ rejectValue: KnownError | undefined} 
..
- return rejectWithValue(error.response.data);
+ return rejectWithValue(error.response?.data);
```
