### ISSUE TITLE
How to determine that the data came from the cache

### ISSUE THREAD

**Issue by progdog-ru** [reduxjs/redux-toolkit#2275]
Hi,
Thanks for this great tool!

I have problem with rtk-query: I need to know when the data are fetching from the cache?
is there analog of `onQueryStarted()` but for cache data?
Or how to implent it? 
Thanks for help!

**Comment by phryneas** [comment]
No, nothing of the sorts. You can always take a look into the cache using the selector from `api.endpoints.foo.select` before a request was made - or maybe look at the timestamp of when the last request was made though

**Comment by progdog-ru** [comment]
Thank you! :)
