### ISSUE TITLE
RTK Query automatic cache invalidation causes different component behavior that does not happen with manual refetch

### ISSUE THREAD

**Issue by ryerrappa** [reduxjs/redux-toolkit#2278]
I've encountered some unintended behavior when automatically invalidating tags from a mutation while inside a modal on a page which has the related get query. The modal closes and reopens instead of just staying closed.

This does not occur when not using cache tags, and manually using the refetch function returned from `use...Query`.

Please find the following 2 codesandbox reproductions. The first one uses the manual refetch and exhibits desired behavior, while the second one exhibits the issue of the modal reopening (the post and get request are firing off properly according to the network debugger).

The main files are:
1. `pages/index.js` which contains the get query
2. `components/user-create.js` which is the modal component and has the mutation
3. `service/reqres-service.js` which has the API slice using a publicly available API used for the purpose of the sandbox

Sandbox links:

1) working as intended: https://codesandbox.io/s/rtk-query-manual-refetch-working-t4pwtm?file=/pages/index.js

2) not working as intended: https://codesandbox.io/s/rtk-query-with-cache-tags-emsdqr?file=/components/user-create.js

Am I doing anything wrong?

**Comment by markerikson** [comment]
I'm not sure I understand how RTK Query is related to a modal's behavior.  Can you start from the beginning and explain how these are supposed to interact?

**Comment by ryerrappa** [comment]
Hello, thanks for the quick response.

- The goal is to have a page that displays a "list view" of a REST API collection (let's use users as an example).
- On that page will be a button to add another user. Pressing that button will open a modal with a form for creating a new user.
- Pressing the submit button on the modal will not immediately close the modal. Instead the request to the API will be made and the submit button will display a loading animation.
- Upon successful response from the API, the modal will close (the list view page will be in the foreground and "active again), and the list view should refetch data from the API

This works when I remove the cache tags from the API slice and manually use the refetch function in the onClose callback in the modal. The modal modal closes, and the list view is updated.

However, when I do not manually refetch, and instead use providesTags, and invalidateTags (removing the refetch from the onClose callback) the post request is successful, the modal closes for a second and the list view is updated, but then the modal is opened up again.

I think I've narrowed down the issue some what: if you check `components/user-create.js` in the useEffect:

```javascript
useEffect(() => {
    if (resultCreateUser.isSuccess) {
      handleOnClose();
    }
    if (resultCreateUser.isError) {
      if (resultCreateUser.error.status === 400) {
        setError("name", {
          type: "manual",
          message: "error ocurred"
        });
      }
    }
  }, [resultCreateUser, setError, handleOnClose]);
```

I think the `if (resultCreateUser.isSuccess)` branch is never entered and the value of `resultCreateUser.isSuccess` is never evaluvated as true. This branch does get entered when using manual refetch with no cache tags.

**Comment by ryerrappa** [comment]
Hi @markerikson, don't want to be annoying, but just wondering if got the chance to check this out?

**Comment by phryneas** [comment]
Do some `console.log(resultCreateUser)` and look at those results. There is a good chance it is behaving completely differently from what you expect. I'd recommend that instead you do an `await createUser().unwrap()` and then directly continue - having a `useEffect` on the result is incredibly flimsy. What if you execute the mutation twice?

**Comment by ryerrappa** [comment]
> Do some `console.log(resultCreateUser)` and look at those results. There is a good chance it is behaving completely differently from what you expect.

Hi @phryneas, thanks for the response. Yes, noticed that as well but didn't really understand why that happens only when using automatic cache invalidation.

Don't want to take more of your time but could you give me a hint of what topic to look into to understand this behavior? I'm new to the JavaScript and frontend world.


> I'd recommend that instead you do an `await createUser().unwrap()` and then directly continue - having a `useEffect` on the result is incredibly flimsy. What if you execute the mutation twice? 

Ahh that's a good point. Thanks for the tip. I will proceed using that method. Thanks!

**Comment by phryneas** [comment]
Well, if you share what you are seeing when you log that, I can try to see and give you an explanation, but like this I'm sorry I can't see your screen :/

**Comment by ryerrappa** [comment]
Hi @phryneas, unfortunately the same thing seems to be happening even when using unwrap(). I've added some log statements. It seems like the modal component is remounting when using rtk query. This causes various issues like the modal flickering open and close, and also not retaining any field errors (as they are reset on open/close) Please find the reproduction with various log statements here:

https://codesandbox.io/s/rtk-query-with-cache-tags-emsdqr?file=/pages/index.js

I've added two buttons on the index page, one modal uses the unwrap method, and one does not.

Within the "with unwrap" modal, I've added a button that shows what it should look like if the component wasn't remounted and the field error was retained. The endpoint that the "with unwrap" modal calls is set to always return a 400.

Also please find below another reproduction with 2 modals:

1. No cache tags and manual refetch. Still seems like this causes the modal to remount.
2. This one is just a dummy modal, doesn't do anything on submit but just closes the modal. There is no remount here

https://codesandbox.io/s/rtk-query-manual-refetch-working-t4pwtm?file=/pages/index.js

**Comment by phryneas** [comment]
Well... the sandbox is not loading for me, but you are very deliberately unmounting that modal before it can remount and execute it's effect. (in your `index.js`, if `isFetching` is true). 

And then it remounts again, because without the effect nothing ever tells it to close.


The "with unwrap" should work for a non-400-case, but since you are invalidating independently if the mutation was a success or not, it will also cause invalidation, a re-query and a unmount and remount in the 400 case. If you want to avoid that invalidation in an error case, use the callback notation for `invalidatesTags`.

**Comment by ryerrappa** [comment]
> but you are very deliberately unmounting that modal before it can remount and execute it's effect. (in your index.js, if isFetching is true).

😓 my bad. This was the issue. I will use the callback notation for `invalidatesTags` Learned some good stuff from this thread. Thank you!

**Comment by herosimo** [comment]
Hi @ryerrappa I went into a similar problem where my modal gets remounting when using invalidateTags. Could you give me an example code for using callback notation for invalidatesTags? I am looking at the documentation but still not sure which one is the callback notation.

**Comment by markerikson** [comment]
@herosimo:

In other words, `invalidatesTags: (result, error, arg) => ["a", "b", "c"]`, instead of just an array like `invalidatesTags: ["a", "b", "c"]`

**Comment by herosimo** [comment]
@markerikson Aa this one. Okay, thanks!
