### ISSUE TITLE
Mocking API endpoint actions for middleware tests

### ISSUE THREAD

**Issue by chrisjpurdy** [reduxjs/redux-toolkit#2284]
Hi! I'm building unit tests for some Redux middleware and need some way to mock a "fulfilled" action from an API slice endpoint. 

Currently, I'm doing something like the following:
`const addUserAction: any = {type: 'myApiSlice/executeMutation/fulfilled', meta: { args: { endpointName: "login" } }, payload: userObject};`

This feels a bit hacky, and I wondered if there was anything like this (akin to how you can use the endpoint object to match on actions):
`const addUserAction: any = apiSlice.endpoints.login.prepareFulfilledAction(userObject);`

The tests are failing currently, so I just wanted to rule out whether I'd done this incorrectly. Cheers!

**Comment by markerikson** [comment]
Hmm. Looking at the codebase, no, I don't think the actual thunk or its `pending/fulfilled/rejected` action creators are actually exposed anywhere right now - they're effectively internal implementation details.

**Comment by phryneas** [comment]
They are exposed as `thunk.fulfilled` etc., but they are not really ergonomic to use. I'd really recommend you instead mock away your server using something like `msw` and test actual "realistic" use cases.

**Comment by chrisjpurdy** [comment]
I gave `createAsyncThunk(...).fulfilled` a go but can't seem to specify `meta.args.endpointName` which I assume the endpoint matcher would check. As you say @phryneas perhaps a a different testing strategy would be better, but I still feel like there should be some convenient way to build actions corresponding to endpoints, some function in the API slice `util` maybe? Thanks for the pointers in any case!

**Comment by phryneas** [comment]
That's not really a way we recommend testing it at all, so we will also not be supporting it. Just mocking "a bit" just does not capture all the things that could happen in reality. You would essentially have to pass in a full valid `meta` into that action creator.
