### ISSUE TITLE
Odd type errors when using listener middleware and the connect utility from react-redux

### ISSUE THREAD

**Issue by i-hardy** [reduxjs/redux-toolkit#2285]
I'm in the process of slowly migrating an older React/Redux codebase to using Redux Toolkit and have run into a fairly perplexing type error when working with components using `connect` and mapping dispatch to props after adding listener middleware to the store.

I've created a minimal reproduction of the problem here: [https://codesandbox.io/s/divine-leaf-bv9v5q?file=/src/Form.tsx](https://codesandbox.io/s/divine-leaf-bv9v5q?file=/src/Form.tsx). The error on line 22 is:

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '(dispatch: ((action: Action<"listenerMiddleware/add">) => UnsubscribeListener) & ThunkDispatch<{ form: { name: string; email: string; }; }, undefined, AnyAction> & Dispatch<...>) => { ...; }' is not assignable to parameter of type 'MapDispatchToPropsParam<{ setName: (name: string) => void; setEmail: (email: string) => void; }, {}>'.
      Type '(dispatch: ((action: Action<"listenerMiddleware/add">) => UnsubscribeListener) & ThunkDispatch<{ form: { name: string; email: string; }; }, undefined, AnyAction> & Dispatch<...>) => { ...; }' is not assignable to type 'MapDispatchToPropsFactory<{ setName: (name: string) => void; setEmail: (email: string) => void; }, {}>'.
        Types of parameters 'dispatch' and 'dispatch' are incompatible.
          Type 'Dispatch<Action<unknown>>' is not assignable to type '((action: Action<"listenerMiddleware/add">) => UnsubscribeListener) & ThunkDispatch<{ form: { name: string; email: string; }; }, undefined, AnyAction> & Dispatch<...>'.
            Type 'Dispatch<Action<unknown>>' is not assignable to type '(action: Action<"listenerMiddleware/add">) => UnsubscribeListener'.
              Type 'Action<"listenerMiddleware/add">' is not assignable to type 'UnsubscribeListener'.
                Type 'Action<"listenerMiddleware/add">' provides no match for the signature '(unsubscribeOptions?: UnsubscribeListenerOptions | undefined): void'.ts(2769)
```

The problem only arises when using the listener middleware. I am still learning my way around Toolkit and am not sure if I'm just doing something wrong here, or if this is actually a bug.

**Comment by markerikson** [comment]
Hmm. I don't know what the actual issue is in this case. _But_, I have a workaround.  Use the "object shorthand" form of `mapDispatch` instead of the "function" form (and we've recommended to use the object form for years anyway), and the sandbox works:

```ts
const connector = connect(mapState, formActions);
```

**Comment by i-hardy** [comment]
I'll be completely honest, I'm not entirely sure- the codebase is a fairly old ecommerce site that needs to handle multiple different kinds of products, payment methods and currencies, and most of the Redux code pre-dates my joining the team.  It's currently quite convoluted and messy and doesn't really adhere to a lot of good practices, particularly concerning side effects.

I think that most of it is actually a lot simpler than it looks, and that the weirder stuff is just poor side effect management that we can handle much better with the listener middleware, but I can't say for sure as there's just so much mess. Part of the purpose of migrating/refactoring to use Toolkit is to hopefully significantly improve the code quality and make it easier for everyone on the team to understand and maintain.

**Comment by i-hardy** [comment]
👍 I think that's a good plan of action, and should help with simplifying the code too. Thanks again for your help, I think I'm happy to close this one.

**Comment by tal-rofe** [comment]
I have the same issue with the following code (after adjusting my code according to the provided fix here):
```ts
import React from 'react';
import type { PayloadAction } from '@reduxjs/toolkit';

import { type AppDispatch, appConnect } from '@/store/app';
import { authActions } from '@/store/reducers/auth';

import HeaderView from './Header.view';

interface IPropsFromDispatch {
	logout: () => PayloadAction;
}

interface IProps extends IPropsFromDispatch {}

const Header: React.FC<IProps> = (props: React.PropsWithChildren<IProps>) => {
	const onExitButton = () => {
		props.logout();
	};

	return <HeaderView onExitButton={onExitButton} />;
};

Header.displayName = 'Header';
Header.defaultProps = {};

const mapDispatchToProps = (dispatch: AppDispatch): IPropsFromDispatch => {
	return {
		logout: (): PayloadAction => dispatch(authActions.logout()),
	};
};

export default appConnect(null, mapDispatchToProps)(React.memo(Header));

``

my store file:
```ts
import { configureStore } from '@reduxjs/toolkit';
import { type Connect, connect } from 'react-redux';

import authReducer from './reducers/auth';

import authListenMiddleware from './middlewares/auth';

const store = configureStore({
	reducer: {
		auth: authReducer,
	},
	middleware: (getDefaultMiddleware) => getDefaultMiddleware().concat(authListenMiddleware.middleware),
	devTools: process.env.REACT_APP_NODE_ENV === 'development',
});

export type AppState = ReturnType<typeof store.getState>;

export type AppDispatch = typeof store.dispatch;

export const appConnect = connect as Connect<AppState>;

export default store;

```

@i-hardy 
@markerikson 

Could someone advice?

**Comment by markerikson** [comment]
@tal-rofe : so ironically I actually saw this myself in the app I work on a couple days ago.

The _best_ fix is **don't use `connect` any more - use the hooks API instead** :)

The second-best option is to use the object form of `mapDispatch`, not the function form.

The _third_ option is to pass `mapDispatch` as a function directly inline to `connect`.
