### ISSUE TITLE
Typing listenerApi.getState

### ISSUE THREAD

**Issue by realignedtechnologies** [reduxjs/redux-toolkit#2286]
Hi,

Thanks to the docs, useSelector can be typed quite easily the following way, and it works great:
```
export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector
const boardStore = useAppSelector(state => state.board);
console.log('store',boardStore.current)
```

can the same be achieved for listenerApi.getState() ?

Currently it returns CombinedState which does not resolve the individual reducer initialState:
```
const state = listenerApi.getState();
// @ts-ignore because of "TS2339: Property 'current' does not exist on type 'CombinedState '"
console.log('store',state.board.current)
```

Cheers!

**Comment by markerikson** [comment]
Yep, we have this covered in the API reference for the listener middleware:

https://redux-toolkit.js.org/api/createListenerMiddleware#typescript-usage
