### ISSUE TITLE
RTK formData PUT not working

### ISSUE THREAD

**Issue by fs-innonova** [reduxjs/redux-toolkit#2287]
I have this file input

```
<input
    type="file"
    id="desktop-user-photo"
    name="user-photo"
    className="absolute inset-0 w-full h-full opacity-0 cursor-pointer border-gray-300 rounded-xs"
    onChange={(e) =>  updatePicture(e.target.files ? e.target.files[0] : null)}
    />
```
that calls this method:

```
const [editPicture] = useEditPictureMutation();

const updatePicture = async (file: File | null) => {
  const formData = new FormData();
  formData.append('file', file);
  await editPicture({ formData }).unwrap();
}
```

here the API slice

```
editPicture: builder.mutation<Profile, { formData: FormData }>({
  query: ({ formData }) => ({
    url: `/picture`,
    method: 'PUT',
    body: formData,
  }),
  invalidatesTags: [PROFILE_TAG],
}),
```

When I'm calling this endpoint I have and error from BE: **[Nest] Unexpected end of multipart data**

<img width="802" alt="image" src="https://user-images.githubusercontent.com/93779923/165497310-37e9649e-6a38-4004-a035-9f7a021d5d10.png">

<img width="890" alt="image" src="https://user-images.githubusercontent.com/93779923/165497127-005b96a3-924d-40d7-8a99-8b5227160233.png">

If I try to use the same endpoint with swagger it works
<img width="697" alt="image" src="https://user-images.githubusercontent.com/93779923/165497057-40969634-8289-46c0-9267-09b7bba57ca3.png">

I'm using "@reduxjs/toolkit": "1.8.1"

Any ideas? Thank you in advance!

**Comment by markerikson** [comment]
Hmm. Actually, that may be part of the issue?  I don't think RTKQ is really meant for _file_ uploads.

Also, I think it tries to send the body as JSON by default.

So, may be some combination of those two things - if you're trying to send a file, you may have to alter the settings for the `fetch` send.

**Comment by msutkowski** [comment]
> Hmm. Actually, that may be part of the issue? I don't think RTKQ is really meant for _file_ uploads.
> 
> Also, I think it tries to send the body as JSON by default.
> 
> So, may be some combination of those two things - if you're trying to send a file, you may have to alter the settings for the `fetch` send.

We don't set headers when the body is `FormData` and file uploads should just work (I do this myself with RTKQ in many projects). You can see by the screenshots that it's generating the form boundary and such as expected. This is most likely an API issue.

**Comment by msutkowski** [comment]
@fs-innonova Can you try uploading a different file? That looks like it could be a poorly encoded jpeg?

**Comment by fs-innonova** [comment]
Indeed @msutkowski your code looks very similar to mine, it should just work.. I'll check the API.

We are using [nestjs](https://docs.nestjs.com/techniques/file-upload) and also from there looks so straight forward 

I also tried different files, and from the swagger UI the upload works :/

<img width="452" alt="image" src="https://user-images.githubusercontent.com/93779923/165572869-b88fa43e-c6d1-4eec-9a0e-119fa21c466f.png">

**Comment by phryneas** [comment]
If it works with `fetch`, it will work with RTK Query, as that is just a wrapper around `fetch`. I'd assume you are doing something here that would fail just the same if you were using `fetch` - can you verify that?

**Comment by fs-innonova** [comment]
yes @phryneas you are right, also fails with fetch so is not RTK issue. I'll close this now and thank you guys for your help!

**Comment by camsloanftc** [comment]
Coming here to say that, for me, I was also running into this issue and was driving me nuts, but it turned out to be because I was always setting the content-type to "application/json" within the `prepareHeaders` function, which overrides the default multipart-form headers.

To get around this, I updated my `prepareHeaders` code as follows:

```js
const api = createApi({
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({
    baseUrl: BASE_URL,
    prepareHeaders: (headers, { getState, endpoint }) => {
      const UPLOAD_ENDPOINTS = ['uploadEndpoint1', 'uploadEndpoint2'];
      if (!UPLOAD_ENDPOINTS.includes(endpoint)) {
        headers.set('content-type', 'application/json');
      }
      // ...rest of your header stuff
      return headers;
    },
  }),
  //... rest of the arguments for createApi
});
```

Couldn't figure out if there is a way to pass extra parameters from an individual endpoint (like somehow providing `ignoreDefaultHeaders: true`), so this is what I'm rolling with for now.

Hope this helps someone else!

**Comment by camsloanftc** [comment]
Oh interesting - thank you. I didn't realize there was both `headers` and `prepareHeaders`.

I knew that about not generally needing to specify content-type, but if I remember correctly there was some internal reason why I had to override it (likely something odd/specific in our app). I think what it may have been is that we have some PUT requests that don't provide any body data, and so they were not getting converted to "application/json".

 I will go with the static headers approach you suggested, which should be more maintainable solution.

**Comment by BelieveC** [comment]
This worked for me. https://flaviocopes.com/fix-formdata-multipart-fetch/

**Comment by ymoon715** [comment]
> yes @phryneas you are right, also fails with fetch so is not RTK issue. I'll close this now and thank you guys for your help!

It is indeed an issue with fetch. You can use axios instead of baseQuery.

https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#axios-basequery.

I used modified version of this example and got it to work.

**Comment by sayinmehmet47** [comment]
without changing the CreateApi you can implement it on mutation, it will works

````
 addProjectIssueWithViewpoint: builder.mutation<
      void,
      { projectSlug: string; data: FormData }
    >({
      query: ({ projectSlug, data }) => {
        return {
          url: `projects/${projectSlug}/bcf/createIssueWithViewpoint`,
          method: 'POST',
          body: data,
        };
      },
      invalidatesTags: [BcfIssueTags.PROJECT_BCF_TAG],
    }),
```

The trick is here **void**

**Comment by zebhasnat** [comment]
prepareHeaders: (headers) => {
          headers.set("Content-Type", "multipart/form-data");
          return headers;
        },
This will work

**Comment by xnagaev** [comment]
> > Hmm. Actually, that may be part of the issue? I don't think RTKQ is really meant for _file_ uploads.
> > Also, I think it tries to send the body as JSON by default.
> > So, may be some combination of those two things - if you're trying to send a file, you may have to alter the settings for the `fetch` send.
> 
> We don't set headers when the body is `FormData` and file uploads should just work (I do this myself with RTKQ in many projects). You can see by the screenshots that it's generating the form boundary and such as expected. This is most likely an API issue.
> 
> Reference: https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/tests/fetchBaseQuery.test.tsx#L675-L694

Thanks a lot!

**When uploading formData with RTK, content-type should be undefined - just do not set it in the headers**

https://github.com/reduxjs/redux-toolkit/issues/2287#issuecomment-1163565291 - 100% right and super helpful

**Comment by mosxe** [comment]
> > > Хм. Собственно, это может быть частью проблемы? Я не думаю, что RTKQ действительно предназначен для загрузки _файлов_ . 
> > > Кроме того, я думаю, что по умолчанию он пытается отправить тело в формате JSON. 
> > > Итак, может быть какая-то комбинация этих двух вещей - если вы пытаетесь отправить файл, вам, возможно, придется изменить настройки для отправки `fetch`.
> > 
> > 
> > Мы не устанавливаем заголовки, когда есть тело, `FormData`и загрузка файлов должна просто работать (я сам делаю это с RTKQ во многих проектах). На снимках экрана видно, что он генерирует границу формы и, как и ожидалось. Скорее всего проблема в API.
> > Ссылка: https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/tests/fetchBaseQuery.test.tsx#L675-L694
> 
> Большое спасибо!
> 
> **При выгрузке formData с RTK content-type должен быть undefined — просто не задавайте его в заголовках**
> 
> [#2287 (комментарий)](https://github.com/reduxjs/redux-toolkit/issues/2287#issuecomment-1163565291) — 100% правильный и очень полезный
> 
> _(upd.) Я оставил комментарий здесь несмотря на то, что тема закрыта, так как эта ветка хорошо индексируется в поисковике и здесь самая грамотная и понятная информация по теме_

THANKS! It's work for me!

**Comment by trangrock** [comment]
> This worked for me. https://flaviocopes.com/fix-formdata-multipart-fetch/

This works for me too. Thanks. 
In short: 
```
The solution was this: you must NOT set the headers.

I did set the multipart/form-data header as that’s what you do with files upload, but apparently that’s what is breaking the file upload through fetch.

Remove the headers from the fetch request and things should be working.
```

**Comment by siuols** [comment]
> I have this file input
> 
> ```
> <input
>     type="file"
>     id="desktop-user-photo"
>     name="user-photo"
>     className="absolute inset-0 w-full h-full opacity-0 cursor-pointer border-gray-300 rounded-xs"
>     onChange={(e) =>  updatePicture(e.target.files ? e.target.files[0] : null)}
>     />
> ```
> 
> that calls this method:
> 
> ```
> const [editPicture] = useEditPictureMutation();
> 
> const updatePicture = async (file: File | null) => {
>   const formData = new FormData();
>   formData.append('file', file);
>   await editPicture({ formData }).unwrap();
> }
> ```
> 
> here the API slice
> 
> ```
> editPicture: builder.mutation<Profile, { formData: FormData }>({
>   query: ({ formData }) => ({
>     url: `/picture`,
>     method: 'PUT',
>     body: formData,
>   }),
>   invalidatesTags: [PROFILE_TAG],
> }),
> ```
> 
> When I'm calling this endpoint I have and error from BE: **[Nest] Unexpected end of multipart data**
> 
> <img alt="image" width="802" src="https://user-images.githubusercontent.com/93779923/165497310-37e9649e-6a38-4004-a035-9f7a021d5d10.png">
> 
> <img alt="image" width="890" src="https://user-images.githubusercontent.com/93779923/165497127-005b96a3-924d-40d7-8a99-8b5227160233.png">
> 
> If I try to use the same endpoint with swagger it works <img alt="image" width="697" src="https://user-images.githubusercontent.com/93779923/165497057-40969634-8289-46c0-9267-09b7bba57ca3.png">
> 
> I'm using "@reduxjs/toolkit": "1.8.1"
> 
> Any ideas? Thank you in advance!

You can just remove the brackets in the formData.

> ```
> editPicture: builder.mutation<Profile, FormData>({
>   query: (formData) => ({
>     url: `/picture`,
>     method: 'PUT',
>     body: formData,
>   }),
>   invalidatesTags: [PROFILE_TAG],
> }),
> ```

**Comment by ThomasRhodz** [comment]
> > Hmm. Actually, that may be part of the issue? I don't think RTKQ is really meant for _file_ uploads.
> > Also, I think it tries to send the body as JSON by default.
> > So, may be some combination of those two things - if you're trying to send a file, you may have to alter the settings for the `fetch` send.
> 
> We don't set headers when the body is `FormData` and file uploads should just work (I do this myself with RTKQ in many projects). You can see by the screenshots that it's generating the form boundary and such as expected. This is most likely an API issue.
> 
> Reference: https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/tests/fetchBaseQuery.test.tsx#L675-L69

Good day Sir. Just want to ask is, what if, I have to set authorization header.

**Comment by patriciaTorre** [comment]
@ThomasRhodz , this works for me:

```javascript
    baseQuery: fetchBaseQuery({
        baseUrl: urlBase,
        prepareHeaders: ( headers ) => { 
            const token = // GET TOKEN FROM LOCAL STORAGE;
            if (token) {
                headers.set("x-token", `${token}`);
            }
            return headers;            
        }
    }),

```

**Comment by patriciaTorre** [comment]
I was going crazy with wis issue and this is what worked for me:

First, I prepared de FormData like this (thanks @Zaidzularsya ):
```javascript
const dataForm = ({ file= null }) => {
    const formData = new FormData();
    formData.append("archivo", file); // "Archivo" is the key that expects my backend for the file
    return formData;
}
``` 
Then I have my Api (secured) like this:
```javascript
export const yourNameApi = createApi({
    reducerPath: 'yourReducer', 
    baseQuery: fetchBaseQuery({
        baseUrl: urlBase,
        // headers: {'Content-Type': 'multipart/form-data' }, -> NOTICE THAT ARE COMMENTED. NO HEADERS!!
        prepareHeaders: ( headers ) => { 
            const token = // TOKEN FROM LOCAL STORAGE;
            if (token) {
                headers.set("x-token", `${token}`);
            }
            return headers;            
        }
    }),
    endpoints( builder ) {
        return {
            imageActividad: builder.mutation({
                query: ( data ) => {
                    return {
                        url: `yourURL/${ data.id }`,
                        method: 'PUT',                 
                        body: dataForm({
                            file: data.image
                        })
                    };
                },
            }),
        }
    }
});

```
