### ISSUE TITLE
Error when using Redux toolkit with next redux wrapper in typescript?

### ISSUE THREAD

**Issue by siamahnaf198** [reduxjs/redux-toolkit#2299]
I am facing one problem over 1 month. I can't get the solutions. I ask several question in Stack-overflow. But I am getting no answer. Please help me.

I want to configure Redux toolkit (`@reduxjs/toolkit`) with next redux wrapper(`next-redux-wrapper`). But I am facing one problem.

in Store.ts-

```
import { Action, AnyAction, combineReducers, configureStore, ThunkAction } from '@reduxjs/toolkit';
import { createWrapper, HYDRATE } from 'next-redux-wrapper';
import { getMovies } from "./Reducer/movieReducer";

const combinedReducer = combineReducers({
    counter: getMovies
});

const reducer = (state: ReturnType<typeof combinedReducer>, action: AnyAction) => {
    if (action.type === HYDRATE) {
        const nextState = {
            ...state,
            ...action.payload,
        };
        return nextState;
    } else {
        return combinedReducer(state, action);
    }
};

export const makeStore = () => configureStore({ reducer }); //I am facing problem here in reducer

type Store = ReturnType<typeof makeStore>;

export type AppDispatch = Store['dispatch'];
export type RootState = ReturnType<Store['getState']>;
export type AppThunk<ReturnType = void> = ThunkAction<
    ReturnType,
    RootState,
    unknown,
    Action<string>
>;

export const wrapper = createWrapper(makeStore);
```

Here in reducer when I try to configureStore, I am geting one error like this-

`Type error: Type '(state: ReturnType<typeof combinedReducer>, action: AnyAction) => any' is not assignable to type 'Reducer<CombinedState<{ counter: { value: any; }; }>, AnyAction> | ReducersMapObject<CombinedState<{ counter: { value: any; }; }>, AnyAction>'.`

If you can't understand where the problem arise, then see the image please-
![Screenshot (7)](https://user-images.githubusercontent.com/78312010/166151722-01e10761-58ba-4ed3-813b-7a1957acd8d5.png)
But I am not understanding what is the problem and why?

Here is my reducers.ts-
```
import { AnyAction } from "@reduxjs/toolkit";

const initialState = { value: 0 }

export const getMovies = (state = initialState, action: AnyAction) => {
    switch (action.type) {
        case 'increment':
            return { ...state, value: state.value + 1 }
        case 'decrement':
            return { ...state, value: state.value - 1 }
        case 'incrementByAmount':
            return { ...state, value: state.value + action.payload }
        default:
            return state
    }
}
```
Please give some time from your valuable times. Please help me. I am stacking it over 1 month. I am trying but not getting any solutions. Please help me. Please help me.

**Comment by phryneas** [comment]
As already noted in my StackOverflow answer, every reducer has to be able to be called with `undefined`.

To fix the problem, do
```ts
const reducer = (state: ReturnType<typeof combinedReducer>, action: AnyAction) => {
```

Although I'd do
```ts
const reducer: typeof combinedReducer = (state, action) => {
``` 
instead.
