### ISSUE TITLE
Return type issue createAsyncThunk with a rejectWithValue

### ISSUE THREAD

**Issue by remcovaes** [reduxjs/redux-toolkit#2305]
I am using createAsyncThunk with TypeScript and I want to check if the result of the dispatched thunk, that is created with `createAsyncThunk`, is fulfilled and then use the payload. This can be done using the `meta.requestStatus`, which should either be `fulfilled` or `rejected`.

I have simplified the example and this was the code I came up with:
```
import { createAsyncThunk, configureStore } from '@reduxjs/toolkit';

const store = configureStore({
	reducer: {},
});

type Returned = 'returnValue';
type Arguments = 'arguments';
type ThunkApi = { rejectValue: 'rejectValue' };

const creator = createAsyncThunk<Returned, Arguments, ThunkApi>(
	'temp',
	async (args, { rejectWithValue }) => {
		if ('') {
			return rejectWithValue('rejectValue');
		}
		return 'returnValue' as const;
	}
);

const go = async () => {
	const someResult = await store.dispatch(creator('arguments'));
	
	if (someResult.meta.requestStatus === 'fulfilled') {
		// Type according to TypeScript: const shouldBeTypedToReturnValue: "returnValue" | "rejectValue" | undefined
		const shouldBeTypedToReturnValue = someResult.payload;
	}
};

go();
```
I thought that this could be a limitation of TypeScript, but by putting a simple example in the TypeScript playground, it seems to work.
https://www.typescriptlang.org/play?#code/C4TwDgpgBAShwFcBOA7CATKBeKByJ8yKAagIYA2CEuA3AFCiRQCCSA5ggLYQrADO2PKXZce-Wg3DQ4AKwgBjYGUrQc+CHMXKqExtAAqACwQoA1szABLQQG8oBTUopUAXHgcKnK3FAC+9SSY4PgRyYFs6KCiobmBSNxtI6OSCAEcqPmAAZTjEPjdcADNQwstycgxcJKjfABpqqDBSEHIAe1J0NzhEVAw6XygAHyhE5Nj4kYaUiHSITJzSPIKPRUqGuoamlvbO2A1PbQh+ujp5VpRMqD5W7mDQ4C65+4jkrbaO5cJUQ9x6sfgJqNktE0hlsrkEPk8MVyKVymtkr5jnRLIUoAAKa63J5hAB041xoLm4MWkOwWDUMLhFXQuAAlJNkmcLuE+IZWqF0AAhCD6KTofStbpEQ6CLEQO54t47ei+IA

I have tried looking into where the typing happened and was not able to find the problem.

**Comment by remcovaes** [comment]
Thanks for the quick reply! 

It seems to be an actual bug, but indeed unwrap is what I needed (I did not know it existed, so thanks for that :smile:).

Should I close the issue or do you want to have it open? I am not planning on a deep dive into this as I suspect TypeScript to do something somewhere and mess up the type.

**Comment by phryneas** [comment]
Then let's close it for now. It's really not high on the list of priorities and from a quick glance, this seems to be a perfectly fine union type, so it would probably need a very deep dive.
