### ISSUE TITLE
Support HMAC authorization schemes

### ISSUE THREAD

**Issue by ericecook** [reduxjs/redux-toolkit#2307]
Hi RTK Team. First off, I'm a big fan of rtk, and excited for the direction this project is heading in. Thank you for your efforts!

Currently, `prepareHeaders` has this signature<sup>1</sup>:

```
;(
  headers: Headers,
  api: {
    getState: () => unknown
    extra: unknown
    endpoint: string
    type: 'query' | 'mutation'
    forced: boolean | undefined
  }
) => Headers
```

## Problem:

HMAC authorization schemes typically involve hashing the request method, path, query params, and body (among others) and adding the hash result as an authorization header<sup>2</sup>.

Ideally, the mentioned values would be available to consumers within the `prepareHeaders` function

## Proposal:

Add params to `prepareHeaders` at call time

 - `config` (https://github.com/reduxjs/redux-toolkit/blob/v1.8.1/packages/toolkit/src/query/fetchBaseQuery.ts#L197). This gives access to the request `body` and `method`
 - `url` (https://github.com/reduxjs/redux-toolkit/blob/v1.8.1/packages/toolkit/src/query/fetchBaseQuery.ts#L191). This allows parsing out `host` and/or `path`
 - `params` https://github.com/reduxjs/redux-toolkit/blob/v1.8.1/packages/toolkit/src/query/fetchBaseQuery.ts#L192. This allows parsing out `query` params

### Issues

There isn't an HMAC 'spec' that I'm aware of, so different implementations end up wanting different parts of the request details hashed. I think the above proposal covers the common implementation areas but its likely not 100%

References: 
 1. https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery
 2. https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html

**Comment by phryneas** [comment]
Tbh., `prepareHeaders` is just a little shortcut. If you want to do complex things like this I would highly recommend wrapping the baseQuery. We have a few examples for that in the docs, for example [this one](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery)

**Comment by vanities** [comment]
Thanks for the lead @phryneas, I've been looking at the example and have something like this

```
const baseQueryWithReauth: BaseQueryFn<
  FetchArgs,
  unknown,
  FetchBaseQueryError
> = async (args, api, extraOptions) => {
  if (args.url === "login/") {
    // add hmac headers based on args.body her
  }
  const result = await baseQuery(args, api, extraOptions);
  return result;
};
```

but it's not clear to me how to add a header at this point. Any help would be awesome!

**Comment by phryneas** [comment]
@vanities `args.headers = { ...args.headers, FooBarHeader: "fooBar!" }`

**Comment by vanities** [comment]
Thank you so much!!

**Comment by markerikson** [comment]
Sounds like this has been addressed, so I'll close this.
