### ISSUE TITLE
Is it possible to rename/restructure rtk-query apiSlice state tree?

### ISSUE THREAD

**Issue by RussellSanders1** [reduxjs/redux-toolkit#2311]
So my question is if transforming the structure of the state tree for an apiSlice would fundamentally break how rtk-query manages the data?

I've not used redux-toolkit for very long, so the answer to this may be obvious or I may be thinking of something that goes against the goal of rtk-query.  I'd like to keep the state tree containing the shape of our data as it would be defined with normal reducers.  an example would be like the following:

- someTopLevelDataFromApi
  - some
  - properties
- someOtherApiData
  - property

with rtk-query, after using `createApi` to setup the same API data, the state tree looks like:

- api
  - queries
    - getSomeTopLevelDataFromApi
      - data
        - some
        - properties  
    - getSomeOtherApiData
      - data 
        - property

Can the rtk-query state tree be restructured/extracted from to resemble more like the first option?

If I should post this elsewhere, let me know, but I'm mostly asking about the limitations of customizing the reducer produced by `createApi` so I figured I'd ask here, thanks.

**Comment by phryneas** [comment]
No, you can't. But it should also not matter to you - the structure of that slice is an implementation detail you should never care about. RTK Query provides you with selectors for anything - you would never access that slice directly. And for inspecting it, you have the RTK Query tab in the Redux Devtools.

**Comment by markerikson** [comment]
Yep. I'll actually flip the question around, though: _why_ do you want to rearrange the cache reducer state structure?  What's the end goal you want to accomplish?

**Comment by RussellSanders1** [comment]
I figured that was the case, and I don’t personally care about the structure, but one of my colleagues did, so I wanted to check to confirm it wasn’t possible and was unnecessary like I thought. Thanks for the time!
