### ISSUE TITLE
Suggestion: Update mapBuilders to make it easy to add thunks to a slice

### ISSUE THREAD

**Issue by edishu** [reduxjs/redux-toolkit#2316]
I've reviewed issues: #629 and #1045 and looks like due to TS complexity support for defining thunks in `createSlice` has not been possible.

However, a simpler solution can be adopted which can simplify many common use cases of using thunk in `createSlice`.
Adding a function like `addAsyncThunk` to [builder](https://github.com/reduxjs/redux-toolkit/blob/2c6fab0b691c029a0a48e3bfc9bd59c7322fa203/packages/toolkit/src/mapBuilders.ts#L136) object will help in setting loading conditions automatically for thunk related actions.

So presently when a user is adding thunk (myThunk) to a slice code looks like:
```
createSlice({
    name: "mySlice",
    initialState,
    reducers: {},
    extraReducers: (builder) => {
        builder
          .addCase(myThunk.pending, (state) => {state[loadingKey] = true})
          .addCase(myThunk.rejected, (state) => {state[loadingKey] = false})
          .addCase(myThunk.fulfilled, (state, action) => {state[loadingKey] = false; ...other updates})
    }
})
```
For a slice which has many thunks this becomes very long chain, hard to read and debug.
`addAsyncThunk` will simplify most common use cases in which pending/rejected actions only change the loading state.

So the above code will look like:
```
createSlice({
    name: "mySlice",
    initialState,
    reducers: {},
    extraReducers: (builder) => {
        builder
          .addAsyncThunk(myThunk, loadingKey: string, fulfilledCallback)
    }
})
```

**Comment by phryneas** [comment]
For what it's worth, this is possible to implement in userspace - if you know the trick:

```ts
import {ActionReducerMapBuilder, CaseReducer, AsyncThunk} from '@reduxjs/toolkit'
import {AsyncThunkFulfilledActionCreator} from '@reduxjs/toolkit/dist/createAsyncThunk'

function addAsyncThunk<S, Returned>(builder: ActionReducerMapBuilder<S>, thunk: AsyncThunk<Returned, any, {}>, loadingKey: keyof S, fulfilledCallback: CaseReducer<S, AsyncThunkFulfilledActionCreator<Returned, any, {}>>){
  builder.addCase(thunk.fulfilled, (s,a) => {
    s[loadingKey] = true
    fulfilledCallback(s,a)
  })
  builder.addCase(thunk.rejected, (s,a)=> {
    s[loadingKey] = false
  })
  builder.addCase(thunk.pending, (s,a)=> {
    s[loadingKey] = true
  })
}
```

This will still need a little more massaging around the types (I'm in a hurry), but it should show how you can do that with given tools already.

**Comment by edishu** [comment]
@phryneas this definition creates a standalone function  `addAsyncThunk`.  Extending `createSlice` such that `addAsyncThunk` is available in `extraReducers` callback argument improves usability. Otherwise users will have to know/remember to import `addAsyncThunk`.

**Comment by phryneas** [comment]
Exactly what Mark says. Loading logic is something that can be implemented in 20 different ways - and every of those ways makes more sense than anything else in some application. Someone could have an array of loading request ids. Or a counter of currently loading requests. Both of these could be centralized for all thunks, or just part of the same thunk that also receives the data. Or like you have it here, one loading indicator per thunk - which might totally not make sense if a thunk could run multiple times concurrently.

We don't know what you need, and given that we already ship one solution that takes care of all of that with RTK query, createAsyncThunk is more a building block for all of those other solutions, so shipping only one more solution while leaving all others behind feels wrong.

We could add a few different approaches as recipes to the docs though - if you feel like polishing the example i made here (or coming up with your own). 🙂

12.05.2022 18:42:42 Mark Erikson ***@***.***>:

**Comment by edishu** [comment]
@markerikson @phryneas Thanks for clarification! I can use a function like you have suggested.
