### ISSUE TITLE
Fetch a document with RTK Query

### ISSUE THREAD

**Issue by JohnBerd** [reduxjs/redux-toolkit#2322]
Thank you for this great tool you provided to us, I am using it in any React Native project.
It allows me to have all my API logic in one place.

I would like to fetch some documents with RTK Query.

I know it is not recommended at all since it will cache the response in the Redux store. So you recommend to use fetch instead of it.

If I use fetch, I will have those problems:
- I will have to duplicate my token and refresh token logic (which I can bypass this by using the baseQuery object)
- I will lose the advantage of having an auto-generated hook for getting isLoading, data and error states (this feature rocks)
- I will struggle with a new file structure in my project, with separated logic for documents and other queries.

All I need would be to disable the caching logic for some entry points. Is it possible, what would be your recommendation?

**Comment by JohnBerd** [comment]
@markerikson thank you for your answer.

It can be a PDF, an image (jpg, png...), a music or a video

**Comment by phryneas** [comment]
You could create the `baseQuery` outside of RTK Query and then use the `baseQuery` instead of `fetch`, but generally, yes, documents such as this should not go into your cache, and since the role of RTK Query is to be a cache, there is not really a lot you can do here.

Best I could think about would be a `queryFn` that downloads the file using the `baseQuery`, triggers a browser-download and then just does a `return { data: fileName }` or something.

**Comment by JohnBerd** [comment]
Thank you @phryneas 🙏

**Comment by JohnBerd** [comment]
Thank you @phryneas 🙏

**Comment by JohnBerd** [comment]
I am reopening this because I am still struggling.
Actually in my project I don’t care too much about caching, main reasons I am using RTK query are:
- auto-generation of hooks for query and mutations
- Easy debugging in redux dev tools
- Invalidation system

that is a shame not enjoying every features RTK query offers for some queries because of caching

Would it be possible to disable data caching for some request?

**Comment by phryneas** [comment]
No, as that is the main purpose of RTK Query before anything else. What have you tried after my last hints?

**Comment by JohnBerd** [comment]
Thank you for your quick reply

I used my baseQuery instance to take advantage of the baseApi, token and refreshToken logic.

I manually created an incomplete  useGetDocumentQuery hook in order to mimic the auto-generated hooks.

I don’t know where to put this hook in my folder structure and I am not satisfied with having a separated logic for this endpoint while I just want to not cache its result in the Redux store

**Comment by phryneas** [comment]
So you didn't try this out?

> Best I could think about would be a queryFn that downloads the file using the baseQuery, triggers a browser-download and then just does a return { data: fileName } or something.

**Comment by JohnBerd** [comment]
I am using React Native, I need to display a PDF in a secured app, so I don't have access to a browser, and the file shouldn't be stored at any point

**Comment by phryneas** [comment]
Then it will be in memory and it doesn't make any difference if it is just in a variable or in Redux state.

**Comment by JohnBerd** [comment]
It is a matter of consistency between endpoints, and taking advantage of the auto-generated hooks.

Anyway I understand, there is nothing to solve this problem directly with RTK Query and I have to find a workaround, I have to manually create a hook for document fetching in order to bypass the automatic caching of any data going through createApi (which can't be disabled for a specific endpoint)
It is a limitation in my case.

Thank you for the time you took for helping me solving my problem

**Comment by phryneas** [comment]
No, what I meant is: it does not make a difference if it is in memory anyways. You will not get any more performance doing it manually. Just use RTKQ normally then, you are in a worst case scenario either way.

**Comment by phryneas** [comment]
@haron-IV if this is a mutation, that's perfectly fine.

**Comment by Berci-Ionut** [comment]
Hi @phryneas ,

I did tried your suggestion ( 

> Best I could think about would be a queryFn that downloads the file using the baseQuery, triggers a browser-download and then just does a return { data: fileName } or something.
),
 
But I am still getting `TypeError: Cannot read properties of null (reading 'toJSON')`

My code:

```
    downloadData: builder.mutation<any, TExportReq>({
      queryFn: async ({ url, params, fileName }, _api, _extraOptions, baseQuery) => {
        const result = await baseQuery({
          url,
          method: params ? "POST" : "GET",
          body: params,
          responseHandler: (response) => {
            console.log("RESPONSE HANDLER: ", response) // this doesn't get called.
            return response.blob()
          },
        })
       // this also doesn't get called
        triggerDownload(result, fileName)
        return { data: fileName }
      },
```

Am I missing something? 

Thank you!

**Comment by leandro-ortiz-electric** [comment]
> Hi @phryneas ,
> 
> I did tried your suggestion (
> 
> > Best I could think about would be a queryFn that downloads the file using the baseQuery, triggers a browser-download and then just does a return { data: fileName } or something.
> > ),
> 
> But I am still getting `TypeError: Cannot read properties of null (reading 'toJSON')`
> 
> My code looks like this:
> 
> ```
>     downloadData: builder.mutation<any, TExportReq>({
>       queryFn: async ({ url, params, fileName }, _api, _extraOptions, baseQuery) => {
>         const result = await baseQuery({
>           url,
>           method: params ? "POST" : "GET",
>           body: params,
>           responseHandler: (response) => {
>             console.log("RESPONSE HANDLER: ", response) // this doesn't get called.
>             return response.blob()
>           },
>         })
>        
>         triggerDownload(result, fileName) // this also doesn't get called
>         return { data: fileName }
>       },
> ```
> 
> Am I missing something?
> 
> Or is there a way to just get the rtk setup for a fetch request for this? We used to have an axios service for this, and the approach I try to use is similar so we would be just as comfortable to use the js fetch api for downloading, but it would be redundant to have another set-up (api for dev/ prod + auth token + language)
> 
> Thank you!

I think your `responseHandler` is not even being recognized by the baseQuery, so it's using the default response handler, that is a `.toJSON` conversion. I really don't know why, but maybe you could try using it inside a `builder.query` instead of mutation...
