### ISSUE TITLE
How to use a result of query for another query using initiate?

### ISSUE THREAD

**Issue by Carabine** [reduxjs/redux-toolkit#2324]
![image](https://user-images.githubusercontent.com/51968280/168268715-3cb73615-8121-4755-ba69-f68ba8feeb86.png)
How to use a result of query for another query? Obviously store.dispatch doesnt return value, but I wanna get query result somehow. It's code in getServerSideProps. 
I can do that way, but I'm loading the same data 2 times.
![image](https://user-images.githubusercontent.com/51968280/168268925-2c509219-938a-46b9-bb3c-46b4ede0327f.png)

**Comment by phryneas** [comment]
You would need to `await` the result of the first dispatch and then log what you get back there and work from there.
