### ISSUE TITLE
createAsyncThunk rejectValue type always or with undefined

### ISSUE THREAD

**Issue by marcusjwhelan** [reduxjs/redux-toolkit#2326]
I am trying to really type this `createAsyncThunk` so that in my `createReducer` in my `addCase` my action is the correct type. Right now with `{rejectValue: string}` it always has action as `string | undefined`

How would I prevent this `| undefined` from being there. 

All the code paths return

```typescript
import { createAction, createAsyncThunk } from "@reduxjs/toolkit";
import axios, { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'
import { APIBaseUrl, IPokemonListItem } from "../reducers/apiReducer";


export interface IListPokemonParams {
  offset: number
  limit: number
}
export const listPokemon = createAction<IListPokemonParams>('api/listPokemon')
export const clearListPokemon = createAction('api/clearListPokemon')
export const resetListPokemon = createAction('api/resetListPokemon')

export const listPokemonAction = 
createAsyncThunk<IPokemonListItem[], IListPokemonParams, {rejectValue: string}>
(listPokemon.toString(),
  async (params: IListPokemonParams, thunkApi) => {
    try {
      return await axios.get(`https://pokeapi.co/api/v2/pokemon`, {params})
    } catch (err) {
      const errors = err as Error | AxiosError
      if (axios.isAxiosError(errors)) {
        return thunkApi.rejectWithValue(errors.message)
      } else {
        return thunkApi.rejectWithValue(errors.message)
      }
    }
  }
)
```

Expected return value should be a `string`

**Comment by Snowirbix** [comment]
Same issue, does anyone have an answer ?  
is that because the thunk can still throw errors and not return the value from rejectWithValue ?

**Comment by phryneas** [comment]
There could still be a thrown error that you didn't catch - and in that case, `payload` would be `undefined` and `error` would be set.

**Comment by phryneas** [comment]
I'm on mobile right now so i can't give a concrete code example, but an explanation:

That you expect it to reject with a payload does not mean that an actual bug could not cause your thunk to `throw` something else instead. So now your rejected thunk could either be "rejected with payload" or "rejected with unknown error". The first will have the payload populated and the error undefined, the other will have the payload undefined and the error populated.

You can check between those two cases by checking for `action.meta.rejectedWithPayload` (if my memory serves me well) and then your action.payload should also be guaranteed by typescript to not be undefined.

13.05.2022 23:34:16 Marcus ***@***.***>:

**Comment by lucky6894** [comment]
![Image](https://github.com/user-attachments/assets/e7e1748d-de17-4a91-b71f-1efd7f683be1)

![Image](https://github.com/user-attachments/assets/57e27503-e27e-40a2-ae1e-035cb53ac45d)

It throws an error, why this is happening?

**Comment by markerikson** [comment]
@lucky6894 please don't post comments that are unrelated to the actual question you have.

Note that you can't pass a potentially undefined action creator to `builder.addCase()`.
