### ISSUE TITLE
Force Refresh After Set Time W/O Remount/Arg Check

### ISSUE THREAD

**Issue by kirbyjs** [reduxjs/redux-toolkit#2335]
### Description
For a little context we are using `react-navigation` with rtk query in `react-native`, and with `react-navigation` if you navigate away from the screen it keeps the screen open behind the scenes. So using `refetchOnMountOrArgChange` isn't super useful for us since it might always leave the component open.

Also the issue that I am trying to solve is to delete the cache data at 6pm everyday because we then know that the data is stale and we can fetch new data from our api. 

I spent a good amount of the day trying to parse through the docs to see if there was something built in, but I didn't find anything. If worse comes to worse, we can just add a setTimeout and then force a `refetch` after. But does anything else come to mind for how to get this to work?

**Comment by phryneas** [comment]
At 6pm, you can just reset the full api with `dispatch(api.util.resetApiState())`. Apart from that, you could add either polling, or set the query to `skip` if it's not on screen.

**Comment by dlato97** [comment]
hi @kirbyjs,
how did you practically implement this?
how do you verify that it is  6pm, and then call dispatch(api.util.resetApiState())?
