### ISSUE TITLE
createAsyncThunk - Condition block, pending actions

### ISSUE THREAD

**Issue by middiu** [reduxjs/redux-toolkit#2336]
Hi there, 

is there a way in the createAsyncThunk condition block to know which action is in pending state?
I understand from the examples that having a "isLoading" property in the state would work, but in my case I have dozen of async actions in my slice, and I would end up having several properties "isLoadingUsers", "isLoadingPost", "isDoingThat" etc etc.

Also, If I had these variable in the state, I could use them to conditionally dispatch the action, and I would not need the condition block.

Anything that I missing?

Thanks!

**Comment by phryneas** [comment]
No, you would have to track that yourself.

Tbh., I would highly recommend you to look at RTK Query [tutorial](https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics) because that already does all of that "multipe requests, tracking which is running, which is already finished" etc. internally for you.

**Comment by middiu** [comment]
thanks for the info guys

**Comment by middiu** [comment]
I ended up having a string[] variable in the state with the list of action running, and then in the condition block check if an action with the same name is there.

```
	{
		condition: (nothing, { getState, extra }) => {
			const { appTenntPrjs } = getState();
			return appTenntPrjs.pendingRequests.indexOf('user/loadPrjInstruLineChartSettings') === -1;
		}
	}
```

then two generic reducers take care of adding/removing an action from this pendingRequest array:

```
.addMatcher(isPendingAction, (state, action) => {
				state.pendingRequests.push(action.type.replace('/' + action.meta.requestStatus, ''));
			})
			.addMatcher(isFulfilledAction, (state, action) => {
				state.pendingRequests = state.pendingRequests.filter(a => a !== action.type.replace('/' + action.meta.requestStatus, ''));
			})
```

What would really make the difference to make this solution even more reusable is passing the action name to the condition block like:  condition: (nothing, { getState, extra, **actionName** }) 

in this way I could write a generic function and re-use it multiple times.

@markerikson @phryneas do you think is something you would consider to implement?

**Comment by markerikson** [comment]
@middiu I'm not sure what you mean by "passing the action name into `condition`".

What "action name" are you referring to here?

**Comment by middiu** [comment]
> @middiu I'm not sure what you mean by "passing the action name into `condition`".
> 
> What "action name" are you referring to here?

Action Type Prefix.

export declare function createAsyncThunk<Returned, ThunkArg = void>(**typePrefix: string**, payloadCreator: AsyncThunkPayloadCreator<Returned, ThunkArg, {}>, options?: AsyncThunkOptions<ThunkArg, {}>): AsyncThunk<Returned, ThunkArg, {}>;

**Comment by markerikson** [comment]
@middiu Still not entirely sure I understand what you're asking for, but... if you're asking for "the string that is the first arg to `createAsyncThunk`"... why not just extract that as a variable in the module scope?

```js
const thunkPrefix = 'user/loadPrjInstruLineChartSettings'
const myThunk = createAsyncThunk(
  thunkPrefix,
  async () => {},
  {
    condition: (nothing, { getState, extra }) => {
      const { appTenntPrjs } = getState();
       return appTenntPrjs.pendingRequests.indexOf(thunkPrefix) === -1;
    }
  }
)
```

Nothing needs to be "passed in" there if that's what you're asking about.

**Comment by middiu** [comment]
@markerikson spot on, exactly what I was referring to.

Yeah of course your example would work, but would be much easier if the **thunkPrefix** would be passed in the condition function.

**Comment by markerikson** [comment]
@middiu I honestly don't see a reason to. The use case you're showing there is the first time I've ever seen anyone try this, and I don't think that justifies adding a new option field here.

**Comment by phryneas** [comment]
I've already told you, but have you actively looked at the RTK Query tutorial? RTK Query already does all of this for you.

Generally, if you want to have a generic `condition` function to use in multiple thunks and multiple files, make it a higher order function.
```js

function genericCondition(prefix) {
  return function condition(nothing, { getState, extra }){
    const { appTenntPrjs } = getState();
    return appTenntPrjs.pendingRequests.indexOf('user/loadPrjInstruLineChartSettings') === -1;
  }
}

// use like
	{
		condition: genericCondition("my/prefix")
	}
```
