### ISSUE TITLE
TypeError: Cannot read property 'subscriptions' of undefined

### ISSUE THREAD

**Issue by rue-oplo** [reduxjs/redux-toolkit#2337]
Am receiving this error in my test of a component that uses RTKQ to fetch data and I cannot figure out where it's coming from and how to get around/fix it.

My API looks like so:
```
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

interface PanelContentInterface { 
  header?: any;
  body?: any;
}

interface PanelRequestPayload {
  endpoint: string;
  caseID: string;
}

export const panelApi = createApi({
  reducerPath: 'panel',
  baseQuery: fetchBaseQuery({
    baseUrl: 'https://jsonplaceholder.typicode.com/'),
  }),
  endpoints: builder => ({
    panelData: builder.query<PanelContentInterface, PanelRequestPayload>({
      query: ({ endpoint, id }) => `${endpoint}/${id}`,
      transformResponse: (response: any) => response.data,
    }),
  }),
});

export const { usePanelDataQuery } = panelApi;

```

The test for the panel component is rather straight forward (redundant) but still fails. 

```
test('should render correctly', () => {
    render(<Panel endpoint="test-enpoint" testID="test-panel" />);
    expect(screen.getByTestId('test-panel')).toBeInTheDocument();
});
```

I receive both `Error: No data found at 'state.panel'. Did you forget to add the reducer to the store?` and `Error: Uncaught [TypeError: Cannot read property 'subscriptions' of undefined]`

Can anyone help? 

I'm using this very same method in multiple other places in the same project and they all seem to work fine. 

Additional Context:
```
const { data, isSuccess, isLoading } = usePanelDataQuery(payload);
```

This line pops up in the console too, but the issue I'm having is that this error only appears in the test and not in the component. The component receives the data and will render properly.

**Comment by phryneas** [comment]
Did you use a Wrapper with a fully configured store and the reducer of the api at  `state.panel`? The error message is pretty clear that that seems to not be the case.

**Comment by rue-oplo** [comment]
There is no `state.panel` though which is something I do not understand, I have other services and none of that stuff for them either and they all work in the UI and throw no errors in the test. But for reference this is what my `index.ts` looks like...

```
export const store = configureStore({
  reducer: {
    // ...
    [tableDataApi.reducerPath]: tableDataApi.reducer,
    [caseHeaderApi.reducerPath]: caseHeaderApi.reducer,
    [panelApi.reducerPath]: panelApi.reducer,
    [activityLogApi.reducerPath]: activityLogApi.reducer,
    [claimsEvidenceApi.reducerPath]: claimsEvidenceApi.reducer,
  }
});
```

**Comment by phryneas** [comment]
As I would assume that `panelApi.reducerPath` is `panel`, that comes down to `[panelApi.reducerPath]: panelApi.reducer,` defining `state.panel` here. I would assume that somehow you are not using *this* store setup. Do you maybe have a custom `render` function that adds a wrapper and imported a wrong one in your test?

Unrelated note: you really should only have **one** api in your app, not multiple ones.

**Comment by rue-oplo** [comment]
@phryneas oh I agree with the one api thing (an argument I lost with the Lead). 

Also, yes I see the issue now we don't use the `render` method of `@testing-library` we actually have a custom one. 

Rookie mistake. But thank you very much it's solved my issue.

**Comment by phryneas** [comment]
Please send your lead our way. They are crippling your app going forward, for no good reason.

**Comment by phryneas** [comment]
For separate files you don't need multiple apis. That is documented in the chapter [Code Splitting](https://redux-toolkit.js.org/rtk-query/usage/code-splitting).

If you ever want to have something like automatic refetching of endpoints with `invalidatesTags`/`providesTags`, those have to be in the same api.

Multiple apis make sense if you talk to completely independent data sources that will never have an overlap - say an api for cookie recipes and an api about dog breeds. If they ever interact or reference each other (say, a `comment` on a `post` with an `author`), those are **the same api**.
