### ISSUE TITLE
RTK-Query: Stop polling when window looses focus

### ISSUE THREAD

**Issue by Brookke** [reduxjs/redux-toolkit#2339]
Hello, is there a built in way in RTK-Query to disable polling when the window looses focus?

**Comment by kennysliding** [comment]
A proposed solution now is to use the `skip` flag, we can use an hook to get the state of whether the window is in focus, then pass that boolean into the query,

```
const isWindowFocused = useWindowFocus();
const { data, error, isLoading } = usePlaceHolderQuery(
    {},
    { pollingInterval: 5000, skip: isWindowFocused }
);
```

And the query will be skipped once the window is not focus

**Comment by phryneas** [comment]
Or
```js
const isWindowFocused = useWindowFocus();
const { data, error, isLoading } = usePlaceHolderQuery(
    {},
    { pollingInterval: isWindowFocused ? 5000 : undefined }
);
```
- this will only stop polling, while `skip` might get the data removed from the cache over time.

**Comment by stevenlafl** [comment]
https://redux-toolkit.js.org/rtk-query/usage/queries#query-hook-options

```tsx
const { data, error, isLoading } = usePlaceHolderQuery(null, {
  refetchOnFocus: false
});
```
