### ISSUE TITLE
Store.dispatch type error

### ISSUE THREAD

**Issue by ManishRaghavan** [reduxjs/redux-toolkit#2340]
typeof store.dispatch throws never

`This expression is not callable.
  Type 'never' has no call signatures.`

**Comment by phryneas** [comment]
How are you setting it up?

**Comment by ManishRaghavan** [comment]
```
export const store = configureStore({
  reducer: reducers,
  devTools: process.env.NODE_ENV !== 'production',
  middleware: [thunk] as const,
});

export const persistor = persistStore(store);
export type AppDispatch = typeof store.dispatch;
export const useAppDispatch = () => useDispatch<AppDispatch>();
```

when I tried using store.dispatch()  ,it gives me 

```
This expression is not callable.
  Type 'never' has no call signatures.

```

**Comment by phryneas** [comment]
```ts
  middleware: [thunk] as const,
```
is a new one for me, I've never seen anybody try that.

Can you please try without that line? Also, do you have a specific reason for that line as it is?

**Comment by markerikson** [comment]
Yeah, first answer is "don't do that" :)  `configureStore` already adds the thunk middleware, you don't need to manually set it up.
