### ISSUE TITLE
Couldn't cancel running listener instances. Repeated listener extries added.

### ISSUE THREAD

**Issue by binarybehemoth** [reduxjs/redux-toolkit#2344]
According to [the documentation](https://redux-toolkit.js.org/api/createListenerMiddleware#startlistening):

'The return value is an unsubscribe() callback that will remove this listener. By default, unsubscribing will not cancel any active instances of the listener. However, you may also pass in {cancelActive: true} to cancel running instances.

If you try to add a listener entry but another entry with this exact function reference already exists, no new entry will be added, and the existing unsubscribe method will be returned.'

I found that it is not true when I did [the following](https://codesandbox.io/s/redux-toolkit-configurestore-listener-middleware-hufku9?file=/src/store.js:0-1607):
```js
import reducer from "./reducer";
import {
  configureStore,
  createListenerMiddleware,
  createAction,
  isAnyOf
} from "@reduxjs/toolkit";

let increment = createAction("INCREMENT");
let decrement = createAction("DECREMENT");

const listenerMiddleware = createListenerMiddleware();

const listener = {
  matcher: isAnyOf(increment, decrement),
  effect: async (action, listenerApi) => console.log("INCREMENT or DECREMENT")
};
listenerMiddleware.startListening(listener);
listenerMiddleware.startListening(listener);
listenerMiddleware.stopListening({
  ...listener,
  cancelActive: true
});

export default configureStore({
  reducer, // ES6, ie.:  reducer:reducer
  preloadedState: 100,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().prepend(listenerMiddleware.middleware)
});
```

Anyway, what is the use of the unsubscribe() callback returned, if it can't cancel running listeners?

**Comment by phryneas** [comment]
I think you interpreted wording wrong here:

* unsubscribe will stop listening for future actions.
* unsubscribe will per default not stop functions that have already started because of an action in the past that are still running.
	*  you can cause those to also be stopped using `cancelActive` - and it will cancel them by throwing an exception as soon as any listener-specific api is called.

**Comment by binarybehemoth** [comment]
would appreciate it if you can write a demo on codesandbox on how unsubscribe() works and how to stop existing listeners with cancelActive....

**Comment by binarybehemoth** [comment]
Alright. Now I got it.

What about repeated listener entries. When I did the following:

listenerMiddleware.startListening(listener);
listenerMiddleware.startListening(listener);

console.log("INCREMENT or DECREMENT") was fired twice, which is not what the documentation describes.

**Comment by markerikson** [comment]
Hmm. _That_ sounds like it might technically be a bug - can you put together a sandbox that shows the issue?

The relevant code is:

https://github.com/reduxjs/redux-toolkit/blob/52e826f56bc48f00e9cb655c7f5859ba3d517a77/packages/toolkit/src/listenerMiddleware/index.ts#L329-L339

so based on that I would _expect_ this would only get added once, since it should be the same `effect` callback both times.

**Comment by binarybehemoth** [comment]
Here is the [sandbox](https://codesandbox.io/s/redux-toolkit-configurestore-listener-middleware-forked-0el74y?file=/src/index.js) that shows the issue. Notice on the console screen that the string 'INCREMENT or DECREMENT' is logged twice with each click on any of the buttons.

**Comment by binarybehemoth** [comment]
Now even when I did [this](https://codesandbox.io/s/redux-toolkit-configurestore-listener-middleware-forked-ktsz4s?file=/src/store.js:0-864), clicking 'unsubscribe' will not cancel the running listener.

**Comment by markerikson** [comment]
Drat.  I strongly suspect this is the same bug as https://github.com/reduxjs/redux-toolkit/commit/1ddda6c11303c838d5abbf8b7a40f4ee0f37c95c - we've got yet another `for..of someMap.values()`:

https://github.com/reduxjs/redux-toolkit/blob/52e826f56bc48f00e9cb655c7f5859ba3d517a77/packages/toolkit/src/listenerMiddleware/index.ts#L320

**Comment by markerikson** [comment]
Okay, should be fixed in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.8.2 .

Thanks for reporting this!
