### ISSUE TITLE
RTK Query: Avoid saving credentials in original args in store

### ISSUE THREAD

**Issue by on3iro** [reduxjs/redux-toolkit#2346]
Hi,

I just realized, that the original args from a login request etc. will also be serialized into the store.
Is there a way to prevent this? Currently this means, that a password entered at any point, which is being sent with an RTK query will be part of the store in plain text.

Thanks in advance

**Comment by phryneas** [comment]
Something like a login should be a mutation, not a query - and in that case it would also not save the originalArgs.

**Comment by on3iro** [comment]
> Something like a login should be a mutation, not a query - and in that case it would also not save the originalArgs.

Ahh I see, thanks for the quick response 👍
