### ISSUE TITLE
RTK Query : when isLoading is set to true

### ISSUE THREAD

**Issue by SunilPrasad** [reduxjs/redux-toolkit#2349]
In one of scenario , I have observed isLoading first initialized as false and after sometime  it's value  is assigned true . So is it guaranteed that whenever component will be mounted isLoading value will be true ?

```
export default function App() {
  const { data, error, isLoading } = useGetPokemonByNameQuery('bulbasaur')

  useEffect(()=>{
    console.log(`isLaoding -> ${isLoading}`);
  },[isLoading]);
  
  return (    
    <div className="App">
      {error ? (
        <>Oh no, there was an error</>
      ) : isLoading ? (
        <>Loading...</>
      ) : data ? (
        <>
          <h3>{data.species.name}</h3>
          <img src={data.sprites.front_shiny} alt={data.species.name} />
        </>
      ) : null}
    </div>
  )
}

```

**Comment by phryneas** [comment]
When the component is mounting, `isLoading` is true (unless there is already data in the cache). On refetch etc., `isFetching` will be true, but `isLoading` will not be.

**Comment by SunilPrasad** [comment]
Thanks for reply . This is very helpful for me while learning readux toolkit .

**Comment by pavelspichonak** [comment]
> When the component is mounting, `isLoading` is true (unless there is already data in the cache). On refetch etc., `isFetching` will be true, but `isLoading` will not be.

We use a hook like this:

```
const {
    data,
    isLoading,
    isFetching,
  } = useNewsQuery(newsId, {
    refetchOnMountOrArgChange: true,
  });
```
When we go to news page this hook get news from backend. After that we go to another page and then go to news page again. Because we use `refetchOnMountOrArgChange: true` we expect that `isFetching` will be `true` but it is `false` on first render and then it becomes `true`. Looks like it is a bug.
