### ISSUE TITLE
dispatch an async function twice in useEffect of react v18?

### ISSUE THREAD

**Issue by ManuRodgers** [reduxjs/redux-toolkit#2350]
```
//  this async action is in the post.slice.ts
export const getPostsAsync = createAsyncThunk(
  'posts/getPostsAsync',
  async () => {
    const response = await axios(POSTS_URL);
    return response.data;
  }
);
// and then call it in a react component 
 useEffect(() => {
    if (postStatus === 'idle') {
      dispatch(getPostsAsync());
    }
  }, [dispatch, postStatus]);
```
because getPostsAsync() is called twice, in the extraReducers, getPostsAsync.fulfilled will be called twice as well and obviously
I can get the post list data twice, which is not what I want.
Is there anything that I can do in the useEffect hook to avoid double calling the async thunk function

**Comment by markerikson** [comment]
FWIW this isn't a Redux question, this is a React question :)

And no, this _will_ happen twice in development when used inside of a `<StrictMode>` tag in React 18.

At least in cases like this, there shouldn't be any actual problem - the data will be fetched and loaded.
