### ISSUE TITLE
listenerApi.take() broken?

### ISSUE THREAD

**Issue by binarybehemoth** [reduxjs/redux-toolkit#2352]
listenerApi.take() of Redux Toolkit does not seem to be working, as can be seen from [this code sandbox](https://codesandbox.io/s/redux-toolkit-configurestore-listener-middleware-conditionals-forked-u4hour?file=/src/store.js).

Also, the listener seems to be fired only after the first dispatch.

**Comment by markerikson** [comment]
Mmm... the code in that sandbox seems a bit overly complicated and I'm not sure it's demonstrating useful behavior.  (I'd also suggest having it listen for a different action than the one that triggers the listener in the first place.

Can you rework it to show the issue more clearly?  Also, what _specific_ behavior is "not working"?

(also btw,

**Comment by binarybehemoth** [comment]
Alright. I have removed the unnecessary logging lines.

I expect the contents of r to be logged after '99', since isIncrement returns true.

**Comment by binarybehemoth** [comment]
...but when I clicked '-' on your sandbox, nothing was logged after 99.

**Comment by markerikson** [comment]
there's timing involved, and also the "Other" button.  Here's what I get when I click "Increment"`, "Decrement", wait a few seconds, and then "Other":

```
rendering 101 ... 
2
invoking listeners... 
2
rendering 100 ... 
88
99
2
invoking listeners... 
(3) [Object, 100, 100]
```

**Comment by binarybehemoth** [comment]
Why is [Object, 100, 100] logged three times?

**Comment by markerikson** [comment]
It's not "logged 3 times".  That's the console saying "this is an array with 3 items in it".

btw, if I click "Decrement", "Increment", wait a few seconds, and then "Increment" again in your sandbox, I see what I'd expect:

```
88
99
invoking listeners... 
(3) [Object, 100, 100]
```

Given that, I think it's safe to say this is working as intended.
