### ISSUE TITLE
Updating cache without invalidating it - optimistic updates

### ISSUE THREAD

**Issue by wmonecke** [reduxjs/redux-toolkit#2356]
Hey there! 

I am having a bit of trouble trying to accomplish the following:

- Fetch data (i.e. tags & folders in this case)
- Create or update a tag 
- Update cache via `onQueryStarted`
- NOT forcing a re-fetch (i.e. not invalidating cache)
- Show added tag in the UI 

I am using Firestore as my backend so it itself will retry requests and dispatch them on reconnect / cache requests until they eventually succeed. 
I am being very conservative with requests in my app so I would like to add a tag to the cache without re-fetching.
In the example below I add an entry by mutating the draft. I thought mutating the draft would update the cache just like a slice would to an incoming state proxy.

````
export const ProjectsApiSlice = createApi({
  reducerPath: "projectsApi",
  baseQuery: fakeBaseQuery(),
  tagTypes: ["TagsAndFolders"],
  endpoints: (builder) => ({
    fetchTagsAndFoldersFromServer: builder.query({
      async queryFn() {
        const [data, error] = await getFoldersAndTagsFromDb()
        if (error) return { error }
        return { data }
      },
      keepUnusedDataFor: 180, // 3mins
      providesTags: [{ type: "TagsAndFolders" }],
    }),
    createTagOrFolder: builder.mutation({
      async queryFn({ item, itemType = TAGS_AND_FOLDERS_ITEM_TYPES.tag }) {
        if (itemType === TAGS_AND_FOLDERS_ITEM_TYPES.tag) {
          const [data, error] = await saveTagIntoDb(item)
          if (error) return { error }
          return { data }
        }
        const [data, error] = await saveFolderIntoDb(item)
        if (error) return { error }
        return { data }
      },
      async onQueryStarted(payload, { dispatch, queryFulfilled }) {
        console.log("createTagOrFolder -> onQueryStarted", payload)
        const patchRecipe = ProjectsApiSlice.util.updateQueryData(
          "fetchTagsAndFoldersFromServer",
          undefined,
          (draft) => {
            if (payload.type === "tag") {
              return {
                ...draft,
                tags: [...draft.tags, payload.item],
              }
            } 

            return {
              ...draft,
              folders: [...draft.folders, payload.item],
            }
          }
        )
        const cachePatch = dispatch(patchRecipe)
        queryFulfilled.catch(cachePatch.undo)
      },
    }),
...
````

It works if I add:
invalidatesTags: [{ type: "TagsAndFolders" }],

But I do not want to re-fetch data. To me adding invalidatesTags is a half measure.
What if I am very sure the request will go through (i.e. Firestore manages the retries for me) and I just want to add an item to cache without forcing a re-fetch?

**Comment by phryneas** [comment]
Then you would do it with `onQueryStarted` and `updateQueryData` like you do here, but you also have to `dispatch` it or nothing will happen.

**Comment by wmonecke** [comment]
@phryneas But I am dispatching it here: `const cachePatch = dispatch(patchRecipe)`. That is why I am confused.

**Comment by phryneas** [comment]
And that cache entry exists, meaning you are calling `useFetchTagsAndFoldersFromServerQuery()` or `useFetchTagsAndFoldersFromServerQuery(undefined)`, but not with any other argument?

**Comment by wmonecke** [comment]
@phryneas `useFetchTagsAndFoldersFromServerQuery()` takes no arguments - it returns an object of tags and folders.

In the RTK docs, it shows the following code:

```
function handleClick() {
    /**
     * This will update the cache data for the query corresponding to the `getPosts` endpoint,
     * when that endpoint is used with no argument (undefined).
     */
    const patchCollection = dispatch(
      api.util.updateQueryData('getPosts', undefined, (draftPosts) => {
        draftPosts.push({ id: 1, name: 'Teddy' })
      })
    )
  }
```

**Comment by phryneas** [comment]
My question was if the cache entrie already exists and if it 100% sure has the cache key `fetchTagsAndFoldersFromServer(undefined)`.

You can also see that in the Redux Devtools.

**Comment by wmonecke** [comment]
@phryneas Huh, I guess there lies the problem. I can see state changes but queries are not being shown in the Redux Devtools. I have a starting point to debug this issue. Thank you!

**Comment by waltermonecke** [comment]
The issue not showing in the Redux Dev Tools was because I was filtering an action and it somehow affected this RTK API.

I can see now I do have key with undefined:

<img width="311" alt="image" src="https://user-images.githubusercontent.com/104456448/170706733-c0b05400-e396-4b50-a4cb-f1d9a91c7a36.png">

I am still not able to add an item to the cache without invalidating it. :/

**Comment by waltermonecke** [comment]
Nevermind I am a complete idiot. Thank you for your help!!
