### ISSUE TITLE
Unable to delete or add data in firestore using RTK-Query in react

### ISSUE THREAD

**Issue by trickjsprogram** [reduxjs/redux-toolkit#2358]
I am trying to achieve delete and add functionality in react using RTK-Query with firestore. It sound might be weird that I am using RTK Query to perform firestore operation in React. So, I have written service API file to delete and add operation with firestore. So, whenever I try to delete or add data in firestore with RTK Query, so I am getting some weird error in my console. However, when I refresh the application then I am seeing the updated data on my app after performing the add/delete operation. For some reason, initially it's not providing me correct result due to below error but after page refresh I am getting the updated value from firestore in my react app.

![image](https://user-images.githubusercontent.com/79596631/170631488-67580c0f-4ef1-41dd-b602-84ee936f3e8e.png)

Here is code of my service api

````
import { createApi, fakeBaseQuery } from "@reduxjs/toolkit/query/react";
import {
  addDoc,
  collection,
  deleteDoc,
  doc,
  getDocs,
  onSnapshot,
  serverTimestamp,
} from "firebase/firestore";
import { db } from "../firebase";

export const contactsApi = createApi({
  reducerPath: "api",
  baseQuery: fakeBaseQuery(),
  tagTypes: ["Contact"],
  endpoints: (builder) => ({
    contacts: builder.query({
      async queryFn() {
        try {
          const userRef = collection(db, "users");
          const querySnapshot = await getDocs(userRef);
          let usersData = [];
          querySnapshot?.forEach((doc) => {
            usersData.push({
              id: doc.id,
              ...doc.data(),
            });
          });
          return { data: usersData };
        } catch (err) {
          console.log("err", err);
          return { error: err };
        }
      },
      providesTags: ["Contact"],
    }),
    addContact: builder.mutation({ 
      async queryFn(contact) {
        try {
          await addDoc(collection(db, "users"), {
            ...contact,
            timestamp: serverTimestamp(),
          });
        } catch (err) {
          return { error: err ? err : null };
        }
      },
      invalidatesTags: ["Contact"],
    }),
    deleteContact: builder.mutation({
      async queryFn(id) {
        try {
          await deleteDoc(doc(db, "users", id));
        } catch (err) {
          if (err) {
            return { error: err };
          }
        }
      },
      invalidatesTags: ["Contact"],
    }),
  }),
});

export const {
  useContactsQuery,
  useAddContactMutation,
  useDeleteContactMutation,
} = contactsApi;
````

store.js file

````
import { configureStore } from "@reduxjs/toolkit";
import { contactsApi } from "./services/contactsApi";
import { setupListeners } from "@reduxjs/toolkit/query";

export const store = configureStore({
  reducer: {
    [contactsApi.reducerPath]: contactsApi.reducer,
  },
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      serializableCheck: false,
    }).concat(contactsApi.middleware),
});

setupListeners(store.dispatch);
````

**Comment by phryneas** [comment]
Quoting myself from StackOverflow:

A `queryFn` has to **always** return an object with either a `data` property or an `error` property - in your case you only do that in the error case.

Try adding a `return { data: 'ok' }` if you don't have any better idea.

**Comment by trickjsprogram** [comment]
You want me to write that one in catch block ?

**Comment by phryneas** [comment]
No. It has to **always** return. Not only in the error case. You already return something in the error case - but you are not returning anything if there is no error!

**Comment by trickjsprogram** [comment]
Yeah that's way it's working correctly. I think redux-toolkit team should come up with some kind of doc if somebody wanted to use firebase in rtk-query. There is not much info about that

**Comment by phryneas** [comment]
You can always open a PR to the docs.
By the way, you should have gotten a very big warning in the console the whole time among the lines of
```
Error encountered handling the endpoint ${arg.endpointName}.
              ${what} did not return anything.
              It needs to return an object with either the shape \`{ data: <value> }\` or \`{ error: <value> }\` that may contain an optional \`meta\` property.
              Object returned was:`,
            result
```

Did you not see that?

**Comment by trickjsprogram** [comment]
I didn't see this warning while adding, deleting or fetching the data from firestore. I got one warning "A non-serializable value was detected in the state, " but got solved by providing  `serializableCheck:` false.

**Comment by phryneas** [comment]
That is very weird, you should definitely get that when running a development build. You might want to check your setup if you are actually running in dev mode.

**Comment by trickjsprogram** [comment]
Is there anything else need to be done ?

**Comment by naimlatifi5** [comment]
Exactly, just return data as an object as {data: ok} and it works as it should
