### ISSUE TITLE
Unable to store a specific RTK Query  end point result in redux-presist.

### ISSUE THREAD

**Issue by OsamaAburabie** [reduxjs/redux-toolkit#2359]
I'm trying to make an offline app with react-native and rtk query.

Is it possible cach a specific endpoint in redux presist. 

ex. only store the result of "/cart" endpoint.

instead of presisting the whole api slice and all of its end points.

PS. I noticed that when I use redux-presist the useGetCart hook doesn't auto fetch on component mount.

I have to trigger the refetch() function manually via (useEffect) is that a normal behavior?

**Comment by phryneas** [comment]
You'd have to manually filter that somehow, maybe in a similar way to https://github.com/edy/redux-persist-transform-filter (that one doesn't seem to do it though).

> PS. I noticed that when I use redux-presist the useGetCart hook doesn't auto fetch on component mount.

RTK Query is a cache and if data is in the cache already it will not make another request. You can set [`refetchOnMountOrArgChange`​](https://redux-toolkit.js.org/rtk-query/usage/cache-behavior#encouraging-re-fetching-with-refetchonmountorargchange) to get some control there.

**Comment by OsamaAburabie** [comment]
Thank you.

**Comment by RRaideRR** [comment]
@OsamaAburabie Do you remember what you did here?
