### ISSUE TITLE
Type Error : Type 'ExcludeFromTuple' is not generic.  TS2315 

### ISSUE THREAD

**Issue by MuthurajD** [reduxjs/redux-toolkit#2369]
`/Users/muthuraj/project/node_modules/@reduxjs/toolkit/dist/getDefaultMiddleware.d.ts Type error: Type 'ExcludeFromTuple' is not generic.  TS2315`
Facing the above issue Searched internet but couldnt find any resolutions would you please help..

**Comment by markerikson** [comment]
Not sure what's going on here, but most likely you have `skibLibCheck: false` set in your `tsconfig`, and should change it to `true`.  

That said, given that there's no info provided on what your project settings look like, closing.
