### ISSUE TITLE
agnostic request && TS returned type

### ISSUE THREAD

**Issue by jgwiazdowski** [reduxjs/redux-toolkit#2370]
Hi,
here is a scenario, 
I have a POST request can take 2 arguments, request url and body parameters, 
something like this
`agnosticPost: builder.mutation<any, IAgnosticPostQuery>({`
` query: ({ url, body, method }) => ({url, body,method: 'post'
      }),
    })
`

as you can see "any" is set as returned type, question is probably obvious,
is there any way handle it? so basically I want  call this this post request multiple times, with different url, different params and I want to be able to set returned type

thanks

**Comment by phryneas** [comment]
You want a wildcard, you get a wildcard. There is really no good way of handling this - you'll have to cast it on use or better use some type guard functions.

**Comment by jgwiazdowski** [comment]
> You want a wildcard, you get a wildcard

sad, but true,

normally I would just have separate queries, but in the current project I have so many of them, it's simply annoying,

thanks anyway
