### ISSUE TITLE
Override reducer handler

### ISSUE THREAD

**Issue by yoerivdm** [reduxjs/redux-toolkit#2371]
Probably a bit of an unusual case ...

We do a lot of code-generation, all out actionCreators, reducers and selectors have a standard generated implementation.
I am moving from all the generated code to RTK (immer generates easier than immutability-helper for instance) but have some issues.

We often override action-handlers in custom reducers to modify the default generated reducer function, this was done by specifying the same action a second time, overwriting the default.  I don't see how (and if) this is possible using the builder.addCase syntax (we use typescript).

**Is there also an easy way to extend the default action types created by createAsyncAction?** 
The fullfilled action is currently handled in generated reducers, we often use an extra action to add some custom post-handling reducer functions, fired after the fullfiled with the same parameters. Eg. RegisterCustomer is handled by a generated reducer to put the newly created customer in the state.  An additional reducer (non-generated) could update a counter of active customers.

**Comment by phryneas** [comment]
What do you mean by "extend"? What is stopping you to just add the `.fulfilled` action to `extraReducers` of multiple slices?

**Comment by markerikson** [comment]
Yeah, really not sure what you're actually asking for here.  Specific examples would help.

**Comment by yoerivdm** [comment]
Sry if it is unclear ... 

We create a bunch of actions / reducers / selectors by generating TS-code. 
Actions are all created via CreateAsyncAction, reducers are created using builder.addCase ... 

Lets say I have a customer endpoint, this would generate customer actions and reducers.
eg: 
_CustomerActions.generated.ts_ file  which contains a RegisterCustomer (thunk) action.
_CustomerReducer.generated.ts_ file which contains a RegisterCustomer action reducer (which adds the created customer to the state)

Lets say the customer state has 2 properties, customers (generated) and newlyAdded (added), we generate a default state shape, we extend the interface with custom properties ... newlyAdded is such a custom proprty

Our code-generation can't generate logic for the newlyAdded state prop so we write custom reducers for that one.
The CustomerReducer.generated file contains all reducers and exports one function: addGeneratedCases(builder) ... it accepts the builder as argument. 

The CustomerReducer (non-generated) contains the building logic:
```
createReducer(initialState, (builder) => { 
     addGeneratedCases(builder);  // Add the generated reducers
     builder.addCase(...)  // Add custom reducers
}
```

And now for my 'problem' ... the addCase cannot 'override' the registerCustomer/fullfilled nor extend. 
Overriding is not possible because I would get 2 reducer functions for the same actionType in the same slice.
Extending ... would mean that I have some sort of post-fullfilled action fired ... could do the last if i'd use the actual action type strings instead of the action.fullfilled syntax.

Maybe an odd question ... we curently generate way too much code for 200+ action endpoints. RTK could bring this down significantly, stil have some gen-issues to conquer :-).

**Comment by markerikson** [comment]
Hmm. I don't think you'd get "2 reducers for the same action type", but that's because `createSlice` specifically throws an error if it sees the same action type show up twice.

Not sure I have a good suggestion here atm.

**Comment by phryneas** [comment]
If you use `.addCase`, you can only have one case per action type, but if you use `addMatcher` for the action, you can add any number of additional ones.

```ts
matcher.addMatcher(action.fulfilled.match)
```

**Comment by markerikson** [comment]
It sounds like they want to have net behavior of "provide a default handler for this action, but later be able to _replace_ that handler entirely", which works with a plain object because a later field definition overrides an earlier one.  So, I don't think you can _replace_ an already-defined handler with `createSlice`.

That said, I think the matchers do run in sequence (and after the cases), so it is possible to have multiple reducers run within one slice for one action.

**Comment by yoerivdm** [comment]
Hi, thanks for the suggestion!

As @markerikson states, currently we 'replace' by using plain objects and creating same field definitions to overwrite generated ones. I'll look into the addmatcher for the additional reducer stuff ... 

Thanks for the help and suggestions ...
