### ISSUE TITLE
Type safety in RTK query endpoints

### ISSUE THREAD

**Issue by nicmesan2** [reduxjs/redux-toolkit#2375]
I am trying to decouple the data access layer from the rest of my app (sort of a clean code good practice).

For that I implemented the following baseQuery: 

```
export interface DataResponseError {
    data?: never;
    error: 'string';
}

export interface DataResponseSuccess<T> extends DataResponseCommon {
    data: T;
    error?: never;
}

export type DataResponse<T = any> = DataResponseError | DataResponseSuccess<T>;

type DataAccessMethod = (payload?: any) => Promise<DataResponse<any>>;

const queryService: BaseQueryFn<DataAccessMethod, unknown, unknown> = async (dataAccessMethod, api) => {
    const { error, data } = await dataAccessMethod();

    if (error) {
        return { error };
    }

    return { data };
};
```

Then I will define an service interface, for example: 

```
export interface ExampleService {
    getNumber: () => Promise<DataResponse<number>>;
}
```

And then implement that interface:

```
export const exampleService: ExampleService = {
    getNumber: async () => {
        const response = await axios.get<number>("/number");

        return response;
    },
};
```

Finally create the hooks using the RTK utility:

```
export const extendedApiSlice = serviceSlice.injectEndpoints({
    endpoints: (builder) => ({
        getNumber: builder.query<number, void>({
                query: () => exampleService.getNumber,
            }),
    }),
});
```

In this case everything works as expected. But what would happen if I change the return value of the `getNumber` endpoint from RTK, say:

```
export const extendedApiSlice = serviceSlice.injectEndpoints({
    endpoints: (builder) => ({
        getNumber: builder.query<**string**, void>({
                query: () => exampleService.getNumber,
            }),
    }),
});
```

Typescript doesn't alert me that `exampleService.getNumber` returns a number and that that is incompatible with what the RTK endpoint definition (<string, void>) expects. 

I am a little bit lost on what class|type|module in RTK should I overwrite to achieve this kind of type safety.

Thanks in advance!

**Comment by phryneas** [comment]
You should not be using `query: () => ...` here, since the return value of that will be forwarded to the `baseQuery` - you'd have to return a `DataAccessMethod` from that.

Use `queryFn` instead.
```js
export const extendedApiSlice = serviceSlice.injectEndpoints({
    endpoints: (builder) => ({
        getNumber: builder.query<number, void>({
                queryFn: async () => {
                  try { return {data: await exampleService.getNumber() } catch (e) { return {error: e} }
                },
            }),
    }),
});
```

**Comment by nicmesan2** [comment]
I understand, but what if I want to implement some cross functionality when requesting the data. Let's say I want to pop a notification if the request failed. I planned to do that in the baseQuery definition once:

```
const queryService: BaseQueryFn<DataAccessMethod, unknown, unknown> = async (dataAccessMethod, api) => {
    const { error, data } = await dataAccessMethod();

    if (error) {
        notification.send('Error Ocurred')
        return { error };
    }

    return { data };
};
```

If I use `queryFn` I will have to do it every time I define an endpoint:

```
export const extendedApiSlice = serviceSlice.injectEndpoints({
    endpoints: (builder) => ({
        getNumber: builder.query<number, void>({
                queryFn: async () => {
                  try { 
                     return {data: await exampleService.getNumber() 
                  } catch (e) {  
                     notification.send('Error Ocurred')
                     return {error: e} 
                 }
                },
            }),
         anotherRequest: builder.query<number, void>({
                queryFn: async () => {
                  try { 
                     return {data: await exampleService.anotherService() 
                  } catch (e) {  
                     notification.send('Error Ocurred')
                     return {error: e} 
                 }
                },
            }),
    }),
});
```

**Comment by phryneas** [comment]
Well, otherwise you won't get your type safety since we generally assume that a `baseQuery` can return pretty much anything. You could add a type guard in `transformResponse`, but that's about it.

**Comment by markerikson** [comment]
(Side note: I'm also really confused with "wanting to do a `try/catch` or show a toast" has to do with "type safety in an endpoint")

**Comment by phryneas** [comment]
As for the toast, just using the `listenerMiddleware` to listen for the rejected action might be the better choice.

**Comment by nicmesan2** [comment]
> (Side note: I'm also really confused with "wanting to do a `try/catch` or show a toast" has to do with "type safety in an endpoint")

Doesn't have any specific relation. I just mentioned that I used the baseQuery as a central place where I put logic regarding all my data access calls. I could also dispatch a logout action from there if I receive a 403 status response. 

I didn't consider the option of adding that on the listenerMiddleware. That may be a better place to put all that logic. I could then use `queryFn` make all the requests and gain the type safety.

What do you think?

**Comment by lindapaiste** [comment]
> I understand, but what if I want to implement some cross functionality when requesting the data. Let's say I want to pop a notification if the request failed. I planned to do that in the baseQuery definition once:
> 
> If I use `queryFn` I will have to do it every time I define an endpoint:

The `queryFn` gets called with a bunch of arguments, one of which is the baseQuery of your API.  So you can add in any extra logic and then pass it off the the underlying `fetchWithBQ` function.
```
async queryFn(arg, queryApi, extraOptions, fetchWithBQ) {
```
Check out [this example in the docs](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#performing-multiple-requests-with-a-single-query).

If you want to get really fancy you can create a higher-order function which takes your `exampleService.getNumber` as an argument and returns a `queryFn`.  But whenever I do that sort of stuff it does involve a lot of TS types, some which are not exported from RTK at the root level, like `import { BaseQueryApi } from '@reduxjs/toolkit/dist/query/baseQueryTypes';` etc.

**Comment by markerikson** [comment]
Closing as I think this has been reasonably answered.
