### ISSUE TITLE
Redundant trailing slash is added when using root endpoint

### ISSUE THREAD

**Issue by ygrishajev** [reduxjs/redux-toolkit#2379]
Steps to reproduce:
1) declare an API with a `baseUrl`
2) add an endpoint that should query root `baseUrl` with params
3) call the endpoint

Expected url: `/api/foo?bar=baz`
Actual url: `/api/foo/?bar=baz`

As a result that redundant trailing slash added after path is causing issues in some apps/environments.
E.g. Next.js app would do a redirect to an endpoint without trailing slash, which would fail in iOS Chrome.

**Example client API declaration**:
```typescript
export const api = createApi({
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({ baseUrl: '/api/foo' }),
  endpoints: (builder) => ({
    findAll: builder.query({
      query: (params) => ({ url: '', params })
    })
  })
});
```

The issue is tracking down to [joinUrls](https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/utils/joinUrls.ts#L6) utility function and **could be fixed like so**:
```typescript
function joinUrls(base, url) {
    if (!base) {
        return url;
    }
    if (!url) {
        return base;
    }
    if (isAbsoluteUrl(url)) {
        return url;
    }
    base = withoutTrailingSlash(base);
    url = withoutLeadingSlash(url);
    
    const delimiter = url.startsWith('?') ? '' : '/' // <- detect a proper delimiter
  
    return base + delimiter + url;
}
```

I'm open to do a PR if this is a valid solution.

**Comment by markerikson** [comment]
Yeah, if you could file a PR that would be appreciated!

**Comment by ygrishajev** [comment]
> Yeah, if you could file a PR that would be appreciated!

@markerikson Sure, done. Pls review

**Comment by phryneas** [comment]
Unfortunately that one is not ready yet - I'll reopen it here so we don't forget about that :)
