### ISSUE TITLE
rtkQuery lifecycle hook to invalidate cache from side-effects

### ISSUE THREAD

**Issue by schadenn** [reduxjs/redux-toolkit#2389]
Hi everyone,

I am currently experiencing a use-case that seems like it is not treated at all at the moment:
I have a query that may have its results invalidated by a side effect that is not within my control (as in: I can't call the invalidate function when the side effect happens).
Now I'm thinking it would be great to have something like a `onQueryInitiated` lifecycle event which will be triggered before the `reject` action would be triggered and therefore provide an integration point to check if the mentioned side effects happened in the meantime and if yes - call the `invalidateTags` function.

At the moment the only way to do this would be to wrap the autogenerated hook, which feels a little cumbersome.

Wdyt? I'd try implementing this if it is considered to be a good idea.

**Comment by markerikson** [comment]
Sorry, not sure I'm following the described scenario here.  Can you give some concrete examples, and maybe show what the imaginary code for this feature might look like?

**Comment by markerikson** [comment]
Hmm. Is the https://redux-toolkit.js.org/rtk-query/api/createApi#onquerystarted basically what you're looking for, or is there some difference in behavior / timing from that function?
