### ISSUE TITLE
Dependency cycle detected in counterSlice.ts

### ISSUE THREAD

**Issue by jwlms** [reduxjs/redux-toolkit#2390]
It seems like there is a circular dependency in `src/app/features/counter/counterSlice.ts` which has the following import statement:

```tsx
import { RootState, AppThunk } from '../../app/store';
```

While in `src/app/store` that `counterSlice` is imported:

```tsx
import counterReducer from '../features/counter/counterSlice';
```

This creates a circular dependency that get's picked up by eslint which produces the following error message:

```
eslint: error
import/no-cycle - Dependency cycle detected.
```

**Comment by phryneas** [comment]
Do `import type { RootState, AppThunk } from '../../app/store';` instead. TypeScript types have different "circularity directions", eslint can just not distinguish between the two.
