### ISSUE TITLE
rtkQuery - Invalidate and refetch

### ISSUE THREAD

**Issue by wisekoci** [reduxjs/redux-toolkit#2393]
I have a `Main.tsx` page consisting of 3 very complex components ( `A.tsx` `B.tsx` `C.tsx`), each of these performs an 
API call with specific parameters.

> Main.tsx
```tsx
<div>
  <button onClick={refetchAllABCqueries}> Refetch All </button>
  <ComponentA />
  <ComponentB />
  <ComponentC />
</div>
```

I know that it is possible to manually invalidate the cache of an API call using the `api.util.invalidateTags` action

```ts
dispatch(api.util.invalidateTags([{ type: 'Post', id: 1 }]))
```

But of course if I invalidate the cache of the 3 API calls and I am on the page, the request is not made again, until I update the page or I return to the `Main.tsx` route

Is there a way using rtk-query to invalidate the cache, and perform a `refetch` or possibly know what the last API arguments were so we can redo the request?

**Comment by wisekoci** [comment]
I try to explain it with an example, from the `App.tsx` component I would like to be able to invalidate the tag "POKE" and refech the calls with the `provideTags: ["POKE"]`

```tsx
        <button onClick={() => pokemonApi.util.invalidateTags(["POKE"])}>
          Invalidate Caches
        </button>
```

Example: https://codesandbox.io/s/blue-fog-b12fi0?file=/src/App.tsx

is there a way to do this via rtk-query? 🤔

**Comment by phryneas** [comment]
That is what it does! That's why I ask "what leads you to believe this?".

Invalidating a tag will refetch (and of course update the components!) of all queries that are currently on screen and remove the rest.

You are asking for the key feature of `invalidateTags` here, that's why I'm so confused. Of course it does that! That's what it's there for!
