### ISSUE TITLE
Uncaught (in promise) TypeError: state.push is not a function

### ISSUE THREAD

**Issue by QuewinBridger** [reduxjs/redux-toolkit#2396]
Hi all,

For some reason I can't push a new "object" into my array.
I understand that in order to push into an array, it needs to be an array in the first place.
According to the initial state it is, but once inside my extraReducer it does not seem to be of array format anymore, it is now a "Proxy object"?

please let me know if anyone can assist:

```
import { createSlice, createAsyncThunk, current} from "@reduxjs/toolkit/";

const initialState = {
  clients: [],
  client: null,
  status: "idle", //'idle' | 'loading' | 'succeeded' | 'failed'
  error: null,
  isModalOpen: false,
};

export const clientsSlice = createSlice({
  name: "clients",
  initialState,
  reducers: {
    toggleModal: (state, action) => {
      state.isModalOpen = !action.payload;
    },
    setClient: (state, action) => {
      state.client = action.payload;
    },
    clientAdded: {
      reducer(state, action) {
        state.clients.push(action.payload);
      },
    },
  },

  extraReducers: (builder) => {
    builder
      .addCase(fetchClients.pending, (state, action) => {
        state.status = "loading";
      })
      .addCase(fetchClients.fulfilled, (state, action) => {
        state.status = "success";
        console.log(current(state.clients))
        state.clients = action.payload;
      })

      .addCase(fetchClients.rejected, (state, action) => {
        state.status = "failed";
        state.error = action.error.message;
      })

      .addCase(addNewClient.fulfilled, (state, action) => {
        console.log(state.clients);
        state.clients.push(action.payload);
      });
  },
});
```

![proxyobject](https://user-images.githubusercontent.com/77058704/172861319-af086f5d-b7df-45b1-9784-e67b927b594e.PNG)
![pushFail](https://user-images.githubusercontent.com/77058704/172861325-495e8a4e-a624-4150-8a39-c25c7539d4e5.PNG)

**Comment by phryneas** [comment]
Please take the time to make your issue readable.

**Comment by QuewinBridger** [comment]
> Please take the time to make your issue readable.

Ok i've tried trimming and formatting - hopefully that helps

**Comment by MikhailesU** [comment]
try this
`state.clients = [...state.clients, action.payload];`
may be it's help you
