### ISSUE TITLE
Reducers without immer

### ISSUE THREAD

**Issue by romgrk** [reduxjs/redux-toolkit#2405]
Hey,

I'm aware of the position of the maintainers regarding disabling immer, as stated in #242 and #183. However, both of those discussions are the top google results when searching `redux toolkit without immer`. After some time, I realized that I could both keep RTK and add additional reducers without immer, which is required in edge cases for performance reasons*. I've created a gist with the solution, if you're interested it could be nice to add the gist to the end of the discussion in #242, as that is the top-level result and I'm sure many people have been landing there without a clear way to solve their issue.

Here is the link: https://gist.github.com/romgrk/bb16d7b8d3827481d04eb535e8d1bc74

This issue can be closed.

\* I'm not sure what goes on inside immer's `produce()`, but in the edge-case I encountered, using a raw reducer took the runtime of a single action from ~200ms to ~2ms.

**Comment by phryneas** [comment]
Honestly, I'd not go so far. Check what slows it down instead. Usually those are reducers with a lot (thousands or tens of thousands) reads on the `state` proxy. In that case, just do one call to `const originalState = original(state)`, do normal immutable updates with that and just `return` the result.

**Comment by romgrk** [comment]
Ok, interesting. It would also be nice to have that information as a summary of #242, and in the docs. The docs talk at length about how immer won't have that big of a performance cost... but no word about what to do if there is a performance cost.

**Comment by phryneas** [comment]
Well, so far we had two reports of performance costs ^^

But if you want to dive in a bit and make a writeup to add for the docs, a PR would be welcome :)

**Comment by romgrk** [comment]
Ok sure, I'll send a PR for the docs in the next days.

About the `original()` from immer, is that function exposed to the users? Does the user need to dabble with peer dependencies or something? If you have a short demo or snippet it would help me test it out.

**Comment by EskiMojo14** [comment]
> About the `original()` from immer, is that function exposed to the users? Does the user need to dabble with peer dependencies or something? If you have a short demo or snippet it would help me test it out.

yes, it's one of the functions RTK [re-exports](https://redux-toolkit.js.org/api/other-exports#original).

**Comment by romgrk** [comment]
Alright, I've run some tests with both solutions, unfortunately `original()` doesn't seem to improve the performance.

Here is the code being tested: https://gist.github.com/romgrk/6aac91df09cdebf8a0761b9fb3afd20e (`lensPath` and `over` functions from rambda (not ramda)). Would you please review the solution with `original()` to confirm I'm using properly?

The result table below shows an example run for each solution. There has been some variation in the profiling run times, but the orders of magnitude stay the same. Any solution with immer is in the hundreds of ms range, and the solution without immer is in the 0-1ms range.

| Name | Run time |
| --- | --- |
| With immer | `760.95ms` |
| With immer + original | `770.74ms` |
| Without immer | `0.16ms` |

Immer
![immer](https://user-images.githubusercontent.com/1423607/173235188-931b67b0-9e44-4ce0-994e-44d58c7212cd.png)
Immer+original
![immer+original](https://user-images.githubusercontent.com/1423607/173235187-d5dee353-bdee-4907-969d-522632dae125.png)
No immer
![no-immer](https://user-images.githubusercontent.com/1423607/173235190-f08ab336-0d47-4d19-b7c4-5184720f15ca.png)

**Comment by EskiMojo14** [comment]
instead of 
```
      state.byId[id].metrics =
        state.byId[id].metrics?.map(metric =>
          metric.id !== metricId ?
            metric :
            { ...metric, ...newMetric }
        )
```
can you try doing
```
  const metric = tate.byId[id].metrics?.find((metric) => metric.id === metricId);
  if (metric) {
    Object.assign(metric, newMetric);
  }
```

**Comment by phryneas** [comment]
Would be interesting to see the dataset here, too.

**Comment by romgrk** [comment]
I've run again with the proposition from @EskiMojo14, it stays in the same order of magnitude. For comparison, I'm including profiling for both the original and the proposition.

| Name | Run time |
| --- | --: |
| Immer + .map() | `153.59ms` |
| Immer + Object.assign() | `153.74ms` |

So the performance is identical.
I can't share the dataset but think multi-MB JSON.

![image](https://user-images.githubusercontent.com/1423607/173239216-a879ace1-55cf-463f-af1a-7a3ee22a9ca0.png)

**Comment by romgrk** [comment]
The issue with immer is that for some reason, the performance is `O(n)` insead of `O(1)` as it should be. My guess is immer does some kind of deep check on new properties, so it visits everything that is added by the `newMetric` content.

**Comment by markerikson** [comment]
Can you share a fully running sandbox or repo that shows this behavior, with a meaningful dataset?

Also, note that Immer _does_ recursively freeze data by default.  Can't tell if that's the issue here because there's not enough of the perf capture shown in those screenshots. However, _if_ that is the issue, note that you can do an `Object.freeze(value)` on the top-level object to prevent Immer from recursing:

https://immerjs.github.io/immer/freezing

**Comment by romgrk** [comment]
Freezing the data brings the performance to the same level as not using immer. I'll send a PR to add the detail to the doc.
I know it's been said enough, but I really wish there was a way to use this module without immer; it adds too much magic to be comfortable to use.

![image](https://user-images.githubusercontent.com/1423607/173254450-32c5c4a1-57c9-4f6c-9744-805fe0bdf410.png)

**Comment by drop-george** [comment]
@romgrk what do you mean by freezing the data? Are you perhaps calling `Object.freeze` on something? 

I'm running into a similar performance issue which I suspect has to do with immer.

**Comment by phryneas** [comment]
@drop-george `return Object.freeze(whatYouWantToReturn)`

**Comment by markerikson** [comment]
Ah, forgot this was open :)

**Comment by caseycole589** [comment]
I also had this performance problem. Using freeze fixed the problem for any one that runs across this issue.

**Comment by gentlee** [comment]
@markerikson so what's the action item here?

1. Disable immer auto freeze [in dev] by default?
2. Make immer a peer dependency and/or option to disable it?

I guess everyone agrees that there neither should not be such issues with performance, nor everyone should read the whole doc for immer and enable/disable autofreeze, or freeze states manually to be able to use RTK efficiently.

**Comment by gentlee** [comment]
@markerikson no I'm just looking at this conversation and at our codebase where we added these lines some time ago:

```ts
// Performance optimization for Immer by disabling auto freeze in other envs than dev
// https://github.com/reduxjs/redux-toolkit/issues/2405
// https://immerjs.github.io/immer/freezing
setAutoFreeze(__DEV__)
```

As I see here are already some traces and perm metrics used, but solution is not included into any docs / PRs as I see. So I assume the problem still exists.

**Comment by markerikson** [comment]
@gentlee I'd recommend actually doing some perf benchmarking to see if it _is_ really an issue in your app's case.  

Use of Immer (and its freezing behavior) _is_ the right default behavior to prevent common bugs.  Accidental mutations _were_ the number one cause of Redux bugs prior to RTK, and since then they've been effectively eliminated.  Worst case, as your snippet there shows, freezing _can_ be disabled if absolutely necessary.

Also, note that this issue is multiple years old. RTK 2.0 includes Immer 10, which had some noticeable perf improvements.

**Comment by gentlee** [comment]
@markerikson I'll do some a bit later, just out of interest.

About redux bugs - I'm 100% sure these kind of bugs are happening only during the initial development of some feature and trying to understand why it doesn't work. It is hardly possible to make something work properly with mutations - subscriptions won't work.

So for sure such things help during development, but totally unnecessary in prod.

Most common bugs from my experience is breaking memoizations by returning [] or new objects / functions from not memoized selectors. I even proposed [this](https://es.discourse.group/t/lazy-inlined-constants/1806) some time ago.

**Comment by markerikson** [comment]
@gentlee I've spent 8+ years helping people with Redux, and answered _thousands_ of questions. Trust me when I say that pre-RTK, accidental mutations _were_ absolutely the most common bug :)

**Comment by phryneas** [comment]
There's one more thing to consider: afaik, the auto-freezing variant of immer became at some version faster than the non-auto-freezing variant. 
If I remember correctly, the freezing made it possible to have some assumptions which sped up the whole algorithm.

So at that point it's "immer" vs "not immer", and believe me, to this day we see enough broken code that we won't budge on that. 
If you need exceptional performance in one specific edge case reducer, you can simply opt out for that one bit and write that one reducer by hand. 
There would be enough people otherwise who are lead by a random badly-explained blog post outside of our control to turn immer off for "performance" without actually knowing of the implications, heavily shooting themselves in the foot.

**Comment by gentlee** [comment]
@markerikson @phryneas added benchmark in [separate issue](https://github.com/reduxjs/redux-toolkit/issues/4793).

**Comment by astandrik** [comment]
Ran into performance issues with immer dealing with case of frequent modifying arrow of hundreds of thousand object

**Comment by astandrik** [comment]
> [@astandrik](https://github.com/astandrik) : couple options. One would be to try to do as much of that work with new plain JS objects _separate_ from `state` as long as possible, and only assign the results to `state` as the very last step. That way you're not having to go through Immer's proxy wrapper:
> 
> * https://immerjs.github.io/immer/performance#for-expensive-search-operations-read-from-the-original-state-not-the-draft
> 
> Alternately, this may be a case where there's enough of a perf difference that it justifies writing an old-style reducer with handwritten immutable updates.

Thanks for your reply - I'll try both options

Could you point where to find "old-style" reducers examples or maybe docs as long as I used only createSlice-version and pretty new to @reduxjs/toolkit

**Comment by markerikson** [comment]
@astandrik : an "old-style" reducer would be the combination of writing the reducer function by hand (just a plain function, no `createSlice`, and using manual object spreads for the immutable updates, like:

```ts
type Todo = {
  id: string;
  text: string;
  completed: boolean;
}

type TodosState = {
  todos: Todo[];
}

export function todosReducer(state = {todos: []}, action: AnyAction) {
  switch(action.type) {
    case "todos/todoCompleted": {
      return {
        ...state,
        todos: state.todos.map(todo => {
          if (todo.id !== action.payload.id) return todo;
          
          return {
            ...todo,
            completed: !todo.completed 
          }
        })   
      } 
    }
    default: return state
  }
}
```

For reference, see:

- https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers
- https://redux.js.org/usage/structuring-reducers/immutable-update-patterns
- https://redux.js.org/usage/migrating-to-modern-redux#reducers-and-actions-with-createslice
