### ISSUE TITLE
Add a `skipToken` that resets the query hook if it's been initialized before (e.g. `skipOrResetToken`)

### ISSUE THREAD

**Issue by kasparkallas** [reduxjs/redux-toolkit#2411]
I'd like to see an easy way to reset the query to uninitialized without having to re-mount the component.

Example usage:
```ts
const accountData = useAccountDataQuery(accountId ? { id: accountId } : skipOrResetToken);
```
Passing the `skipOrResetToken` guarantees that there's no data (i.e. stale data) coming from the query. 

The use-case arose from the fact that the stale data with just the `skipToken` can be surprising when you have a user inputted conditional for whether to execute the query or not (e.g. "address", "item name", "username" etc).

**Comment by markerikson** [comment]
Seems plausible.  I also don't think we have a way to reset a single cache entry imperatively atm - you can reset the _entire_ API state, but not just one entry.

**Comment by phryneas** [comment]
I think the point here is more to reset the *hook* rather than the cache entry, right?

**Comment by kasparkallas** [comment]
> I think the point here is more to reset the _hook_ rather than the cache entry, right?

Yes, it's about resetting the hook -- I'll edit the title.

Here's a more detailed example of the type of code I _currently_ end up writing:
```ts
const { connectedAccount } = useAccountContext();
const accountSettingsQuery = useAccountSettingsQuery(connectedAccount ? { account: connectedAccount } : skipToken);
const accountSettings = connectedAccount ? accountSettingQuery?.data : undefined;

// and then render something based on the preferences
```

1. Most of the time the component is landed on without a connected account so the query result is uninitialized as expected with `undefined` data. 
2. Then the account is connected and the query has the account related data.
3. And then the account is disconnected and I would like to see `undefined` data again but in actuality I get the last result.

There's an argument to be made that I should just re-mount the component for such a context change (fair). Or that the extra variable solution is simple (which it is) but the main issue with it is that it's _easy to miss_. I mistakenly tend to take for granted that when `skipToken` is passed then I will surely not have any results.

**Comment by kasparkallas** [comment]
> @kasparkallas hmm. Would it help if you checked `accountSettingsQuery.currentData` instead? I _think_ that should be "the value from the absolute latest argument", whereas `data` is "the last _successful_ value".

Looks like that is indeed the case... :stuck_out_tongue: Thank you very much, sir!
