### ISSUE TITLE
Why not allow to pass options to graphql-request directly?

### ISSUE THREAD

**Issue by AleksandrukTad** [reduxjs/redux-toolkit#2418]
Hey,
so for of all I would like to thank you guys for this amazing project I love RTK. 
I am wondering why base graphql does not allow to pass credentials in this [line ](https://github.com/reduxjs/redux-toolkit/blob/a5cf61b366f23a868548d1ca7d56350c76610cbf/packages/rtk-query-graphql-request-base-query/src/index.ts#L21)
like so:

`
const client =
    'client' in options ? options.client : new GraphQLClient(options.url, { ...graphQLClientOptions })
`

When I was moving from Apollo to RTK with GraphQL, I was trying to pass credentials: "include" to graph request to pass along cookies. I found [this ](https://stackoverflow.com/questions/69430093/how-to-set-equivalent-of-fetchs-credentials-include-in-redux-toolkits-c) issue on Stackoverflow, which was dealing with the same problem but for regular REST calls. It was incredibly frustrating to not being able to apply similar solutions for the same problem but in graphql. The docs did not help much either. I had to go to he code and figure that i have to pass brand new client like so:

`
  const client = new GraphQLClient(
    API_URL,
    {
      credentials: 'include',
    }
  );
  export const baseQuery = graphqlRequestBaseQuery({
    client,
    customErrors,
  })
`
the worst thing is that I don't know if this is the correct way of doing this. I am writing this in faith that we could improve transition process for Graphql users from stuff like Apollo to RTK.

I am wondering if I could simplify this but aligning the "credentials: include" with what we already have in REST version of RTK query or add the correct way in doc.

**Comment by phryneas** [comment]
Simple answer: because it is only a shortcut for people who want the standard setup. If you have any more complicated setup, the official way of doing this is, as you have found yourself, to create a client and just pass that in.

```js
const client = new GraphQLClient( API_URL, { credentials: 'include', } ); 
export const baseQuery = graphqlRequestBaseQuery({ client, customErrors, })
```

That just has the benefit that no matter how many new signatures the `GraphQLClient` constructor gets and no matter what other stuff you want to do (including wrapping the client or mocking it or whatever), you can just do that without any required changes on our side.

**Comment by AleksandrukTad** [comment]
Okey makes sense. I am wondering, if we would like to simplify the process of finding the correct way of doing that for new users, should  we add example to the docs of that?

**Comment by phryneas** [comment]
A PR to the docs would be welcome for that. Usually your IDE should just offer it to you as a possible way though, since the TypeScript types contain all that information.

**Comment by AleksandrukTad** [comment]
Since I don't yet have much experience with RTK I will not even try to write whole new GraphQL section. I will add the credentials include as example right below this: https://redux-toolkit.js.org/rtk-query/usage/examples#react-with-graphql .
