### ISSUE TITLE
Authorization key from header

### ISSUE THREAD

**Issue by nistor-andrei** [reduxjs/redux-toolkit#2423]
I use RTK Query api for login, when the login is done with success, i get the token through the response header.

Is there any chance to access the 'Authorization' from the response header. I try it to build an custom baseQuery but i failed.

**Comment by phryneas** [comment]
Sharing your failed attempt might help us help you - although generally, this is not the place for "help", but the place for "bug reports and feature requests". 

Could you please either open a StackOverflow issue or ask in #redux on Reactiflux? We're active in both places as well, and so is a big community that might come to your help before we even get to see your question.
