### ISSUE TITLE
RTK Query throws error : () => string' is not assignable to type 'never'.`

### ISSUE THREAD

**Issue by dexkode4** [reduxjs/redux-toolkit#2426]
I get this error 
`Type '({ merchantCode, divisionId, operation }: { merchantCode: any; divisionId: any; operation: any; }) => string' is not assignable to type 'never'.`

API service function

```
const configurationApi = createApi({
  reducerPath: 'configurationApi',
  baseQuery: staggeredBaseQueryWithBailOut,
  endpoints: (builder) => ({
    getSmartRouteNetwortConfig: builder.query<IJsonResponse, IDefaultConfigRequestParams>({
      query: ({ merchantCode, divisionId, operation }) => `${merchantCode}/divisions/${divisionId}/smartrouting/${operation}/networks`,
    }),
})
```

interface IJsonResponse<T = IDefaultNetworkConfig> {
  resource: T;
  links: Record<string, any>;
}

interface IDefaultNetworkConfig extends Layout {
  id: string;
  configurations: DefaultConfiguration[];
}

**Comment by phryneas** [comment]
I can only assume that your `staggeredBaseQueryWithBailOut` is typed incorrectly. Does it work if you manually cast it to the same type as a normal `fetchBaseQuery`?

**Comment by dexkode4** [comment]
thanks , I reverted to normal fetchBaseQuery
