### ISSUE TITLE
Skipping all network requests if the user is offline as it keeps trying to refetch the data on failing.

### ISSUE THREAD

**Issue by rehmankhan-cloudways** [reduxjs/redux-toolkit#2428]
Currently, I can prevent an individual network request (query) with "skip" option provided by RTK Query. 

I want to skip all the queries from happening if the user is offline. 
what should I do to prevent recursive network request after failing as there's no option available to skip all the queries. 

I've tried using AbortSignal and maxRetries, but that didn't work for me. 

Is there's any better way to handle this ^.

**Comment by phryneas** [comment]
Not really at this moment, I'm sorry.
