### ISSUE TITLE
A non-serializable value error after dispatching addListener action

### ISSUE THREAD

**Issue by sevgeek** [reduxjs/redux-toolkit#2439]
Hello!
I am found some error about non-serializable value, when I tried [adding listener middleware](https://redux-toolkit.js.org/api/createListenerMiddleware#adding-listeners-inside-components) inside my custom hook. 
For dispatch action `addListener(...)` I am using [typed useAppDispatch hook](https://redux-toolkit.js.org/tutorials/typescript#define-typed-hooks).

```javascript
import { addListener } from "@reduxjs/toolkit";

...

React.useEffect(() => {
  const unsubscribeFunc = dispatch(
    addListener({
      type: "some/action",
      effect: console.log,
    })
  );

  return unsubscribeFunc;
}, [dispatch]);
``` 
![image](https://user-images.githubusercontent.com/60958933/175105634-2d478110-b598-4df1-be8b-082d09132a05.png)
```
A non-serializable value was detected in an action, in the path: `payload.effect`. Value: ƒ log() { [native code] } 
Take a look at the logic that dispatched this action:  {type: 'listenerMiddleware/add', payload: {…}} 
```
The effect itself works correctly and there are no errors in runtime.
Is it because of this error that the `redux-toolkit` developers do not recommend using this approach? Thanks!

Environment: `node@14.17.3`, `react-redux@8.0.2`, `@reduxjs/toolkit@1.8.2`

**Comment by phryneas** [comment]
DId you maybe forget to add the listener middleware to your `configureStore` setup?

**Comment by markerikson** [comment]
Can you show the store setup?

We specifically recommend putting the listener middleware _before_ any default middleware, both so that you can correctly dispatch thunks, and so that the listener middleware intercepts this particular action:

https://redux-toolkit.js.org/api/createListenerMiddleware#basic-usage

```ts
const store = configureStore({
  reducer: {
    todos: todosReducer,
  },
  // Add the listener middleware to the store.
  // NOTE: Since this can receive actions with functions inside,
  // it should go before the serializability check middleware
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().prepend(listenerMiddleware.middleware),
})
```
