### ISSUE TITLE
React 18 Strict Mode and data fetching 

### ISSUE THREAD

**Issue by tduraj** [reduxjs/redux-toolkit#2441]
React 18 introduced a remounting simulation of useEffect in Strict Mode. How to deal with this during data fetching? 
I prepared this simple example: https://stackblitz.com/edit/react-ts-sqdsmr?file=App.tsx
useEffect is triggering API call and the user can see the status (loading / not loading). Because of remounting user will never see "Loading" information, console logs is giving the answer why:
![image](https://user-images.githubusercontent.com/30274851/175162057-e8fcc58e-3203-4547-9e5f-4e2d5d4c97fd.png)
First action is not yet finished, but the second is already running. What should I do to get correct order (first reject, then run another action)? Or maybe is not possible and I should disable Strict Mode?

**Comment by markerikson** [comment]
The best answer here would really be to use RTK Query for data fetching, as it should ensure that only one request goes out:

https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics
[
That said: this also only happens in development, so it's not something to worry about.

**Comment by tduraj** [comment]
So it's not possible to deal with it without switching to RTK Query? Why this abort function is triggered with delay?

**Comment by markerikson** [comment]
React calls the cleanup function when it cancels the first `useEffect` call, just like it would when it unmounts your component.

You _could_ write a bunch of logic to handle this yourself...

but the point is RTKQ already does all that work for you anyway, so there's no reason to write all that same logic the hard way.

**Comment by alexmf91** [comment]
Not sure if that's something that has been added later, but this solution works for thunks:

- https://redux.js.org/tutorials/essentials/part-5-async-logic#avoiding-duplicate-fetches
