### ISSUE TITLE
"action.payload" object from one async_thunk unexpectedly showing on a different async_thunk's action.payload

### ISSUE THREAD

**Issue by shaogatalam** [reduxjs/redux-toolkit#2443]
// action.payload from one async_thunk unexpectedly showing on a different async_thunk's action.payload

file : a.js
extraReducers: {
    [get_custm_data.pending]: (state, action) => {
      state.status = "loading";
    },
    [get_custm_data.fulfilled]: (state, action) => {
      state.status = "success";
      console.log(action.payload);
    },
    [get_custm_data.rejected]: (state, action) => {
       state.status = "failed";
    },
},

// action.payload from above "extraReducers" showing on a different slice's extraReducers

file : b.js
** 
In [get_cusret_allcity.fulfilled] : 
When i console.log(action.payload), its is showing the " action.payload object " from a.js file  
[they are 2 different files with 2 different slices] 
**

extraReducers: {

            [get_cusret_allcity.pending]: (state, action) => {
                state.status = "loading";
            },
            [get_cusret_allcity.fulfilled]: (state, action) => {
                state.status = "success";
                if(action.payload !== 'null' && action.payload!== 'undefined') {
                   
                     // The Problem is here // 
                    // The Problem is here // 

                    console.log(action.payload); 
                    
                    // Showing the " action.payload - object " from "a.js" file
                    
                    // The Problem is here // 
                    // The Problem is here // 
                   
                
                 }
            },
            [get_cusret_allcity.rejected]: (state, action) => {
                state.status = "failed";
            },
        },

```

**Comment by phryneas** [comment]
You need to give your thunks unique names in the first argument to `createAsyncThunk`.
