### ISSUE TITLE
GraphQL error message issue

### ISSUE THREAD

**Issue by faizanali1192** [reduxjs/redux-toolkit#2445]
What i am using:
          I am using GraphQL api's and Code generator (which automatically generates queries and mutations).

````````````````````````````````````````````````````````````
Error return from the backend in Network:    
          `{"errors":[{"message":"Invalid data","locations":[{"line":2,"column":3}],"path":["testError"]}],"data":null}`

````````````````````````````````````````````````````````````````````````           
What rtk-query gives error in error message:
`Invalid data: {"response":{"errors":[{"message":"Invalid data","locations":[{"line":2,"column":3}],"path":["testError"]}],"data":null,"status":500,"headers":{"map":{"content-length":"108","content-type":"application/json; charset=utf-8"}}},"request":{"query":"\n    query ExampleQuery {\n  testError\n}\n    "}}`

````````````````````````````````````````````````````````````````````````
What i actually needs:
           "Invalid data"

**Comment by ASahak** [comment]
I had the same issue as you mentioned above and I resolved it by customErrors
https://stackoverflow.com/questions/71828943/how-to-handle-error-format-in-redux-toolkit-rtk-query-graphql-application

**Comment by louislebrault** [comment]
Why is this issue closed ? The example describe a standard way of receiving errors from a graphql endpoint, it seems odd to having to rely on a custom implementation for parsing them.
