### ISSUE TITLE
Should RTK have a fallback in case AbortController is not declared ? 

### ISSUE THREAD

**Issue by JulienKode** [reduxjs/redux-toolkit#2447]
Inside `createAsyncThunk` currently RTK have a fallback in case `AbortController` is not declared. https://github.com/reduxjs/redux-toolkit/blob/e307245e8e78868353c746531331257ea69ccab2/packages/toolkit/src/createAsyncThunk.ts#L530

This seems not the case for the `listenerMiddleware` https://github.com/reduxjs/redux-toolkit/blob/3d7bd2246df35a668a25d60a757f1f0b6df62798/packages/toolkit/src/listenerMiddleware/index.ts#L89

I do not know if it's considered as a bug or not, I've created a little PR for it https://github.com/reduxjs/redux-toolkit/pull/2446

**Comment by phryneas** [comment]
I answered on the PR :)

**Comment by JulienKode** [comment]
Thanks, I'll close the issue then
