### ISSUE TITLE
Remove abortcontroller polyfill 

### ISSUE THREAD

**Issue by JulienKode** [reduxjs/redux-toolkit#2448]
Currently there a polyfill of AbortController in createAsyncThunk but not in listeners middleware.

The goal of this issue is to remove the polyfill for the v2

Related to: https://github.com/reduxjs/redux-toolkit/pull/2446

**Comment by phryneas** [comment]
Thanks for the issue! :)

**Comment by JulienKode** [comment]
@phryneas I've created https://github.com/reduxjs/redux-toolkit/pull/2518 if you think this is useful
