### ISSUE TITLE
`UseQuery` hook's `data` is `undefined` after typeguarding that it's not

### ISSUE THREAD

**Issue by bn-piar** [reduxjs/redux-toolkit#2449]
Hello there.

[Codesandbox](https://codesandbox.io/s/admiring-bhabha-vriue8?file=/src/App.tsx:304-314)

**The problem**
`useGetSomeDataQuery` returns an object that includes `data`, `isLoading`, `error` and other properties. 

After making sure that it's not `isLoading`  and it there's no `error` the `data` property is still of type `SomeDataType[] | undefined` 

```javascript

const Component = () => {
  const { data, isLoading, error } = useGetSomeDataQuery();

  if (isLoading) return <p>loading...</p>
  if (error) return <p>error...</p>

  const renderData = (item: SomeDataType) => (/* do something with item */)
  
  return (
    <div>
      {data.map(renderData)}
      {/* ^ Object is possibly 'undefined'. */}
    </div>
  );
}
```

I tried adding more checks like 
```javascript
...
if (isError) {...}
if (isFetching) {...}
...
```
but still couldn't get the data not to be `possibly undefined`. 

**What I expect** 
`data` is of type `SomeDataType[]` when I type guard it

**Comment by phryneas** [comment]
Actually, this is possible and tested for in https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/tests/unionTypes.test.ts#L44

But there are four cases:
`isUninitialized`, `isLoading`, `isError` and `isSuccess`.
So either you test for `isSuccess` or you need to exclude the other two.
