### ISSUE TITLE
RTK Query Kitchen Sink example on website uses incorrect import name

### ISSUE THREAD

**Issue by KaylaKremer** [reduxjs/redux-toolkit#2456]
When viewing the Kitchen Sink example, there is an error of `postsApi` being undefined in `authSlice.ts`.

This can be fixed by changing the incorrect import of `postApi` to `postsApi`.

<img width="1534" alt="Screen Shot 2022-06-25 at 10 05 14 PM" src="https://user-images.githubusercontent.com/22095244/175796425-65ed2430-8d14-43cc-b1a7-84620981ad20.png">

**Comment by markerikson** [comment]
Thanks, could you file a PR to fix this?

**Comment by KaylaKremer** [comment]
@markerikson Just put up the PR for it!

**Comment by markerikson** [comment]
Thank you!
