### ISSUE TITLE
Add a dev-mode warning to `createSlice` to error if `initialState` is undefined

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#2459]
I've seen some folks misspell `initialState`, and thus end up with _no_ initial state.  

This leads to `combineReducers` doing the "Reducer `x` returned `undefined` blah blah" error, but it's not as helpful as it could be.

We should throw a dev-mode error inside of `createSlice` itself if the initial state is undefined.

**Comment by dannielss** [comment]
I would like to solve this.

**Comment by dannielss** [comment]
My first PR!! #2461

**Comment by markerikson** [comment]
That's merged, so I'll close this.
