### ISSUE TITLE
RTK Query | Kitchen Sink Example | Error in official site

### ISSUE THREAD

**Issue by bhanuxhrma** [reduxjs/redux-toolkit#2466]
![image](https://user-images.githubusercontent.com/11549130/176395734-cbc21fa3-230d-4368-9212-59cd84b78c7b.png)

**Comment by fregayeg** [comment]
Hello! Go to package.json file and donwgrade the **msw** version to `^0.39.2`.

**Comment by markerikson** [comment]
I _think_ this is fixed now
