### ISSUE TITLE
RTK Query | Not setting headers

### ISSUE THREAD

**Issue by MarioP-Dev** [reduxjs/redux-toolkit#2469]
I'm having trouble setting headers through prepareHeaders.
Apparently, the modified headers and the headers that are taken by default as indicated in the documentation are not applied.
In my case, the Content-Type header is always taken as text/plain even though the documentation says that application/json is taken by default. Also, it doesn't matter if you force the header modification, since it ignores it and continues sending the plain text.

FetchBaseQuery implementation:
![fetchBaseQuery](https://user-images.githubusercontent.com/40372021/176563002-f882ea6b-d314-4bd4-baac-b837515f04fa.png)

injectEndpoints implementation:
![injectEndpoints](https://user-images.githubusercontent.com/40372021/176563029-d92ae5bc-9e8a-467a-8cc0-923118cf0b2f.png)

Request made from the browser.
![image](https://user-images.githubusercontent.com/40372021/176562955-5608b603-d798-487a-a604-7eab00b20a83.png)

Appreciate that the content type is set to text/plain although I manually set it to JSON

Also, if I log the applied headers before returning them, I get an empty array, so no headers are applied

**Comment by markerikson** [comment]
Can you provide a CodeSandbox, repo, or Replay ( https://replay.io/record-bugs ) that reproduces the issue?

**Comment by codedbyjordan** [comment]
I am also facing this issue. Even when I hard code the value in it doesn't work. The `console.log` just prints an empty Headers object

```
baseQuery: fetchBaseQuery({
    baseUrl: process.env.REACT_APP_HEIRLOOM_API_BASE_URL,
    mode: 'no-cors',
    prepareHeaders: (headers) => {
      // If we have a token set in state, let's assume that we should be passing it.
      headers.set('Authorization', 'Bearer MY_TOKEN');
      console.log(headers);
      return headers;
    },
  }),
```

<img width="354" alt="image" src="https://user-images.githubusercontent.com/62375480/176769472-b3e46f3e-51dd-4bb8-a652-234ff1e11670.png">


here's the `EndpointBuilder`

```
getCredentialById: builder.query<Credential, string>({
    query: (id) => `credentials/${id}`,
}),
```

**Comment by jessebond2** [comment]
I'm also running into this issue when I set the `mode` option in `fetchBaseQuery`. It seems to override any headers set in `prepareHeaders`.

This was tested on v1.7.3

**Comment by markerikson** [comment]
Folks, just saying "running into this issue" isn't helpful.  Per my comment above, we really need a reproduction to be able to debug this.

**Comment by fregayeg** [comment]
Hello! I think this issue is due to backend-side config. I mean if you have a security config, please allow http option method and allow your client-side server as well to consume POST request. Hope it helps

**Comment by MarioP-Dev** [comment]
Hey! With the hints you gave me I finally found the problem. 
As @fregayeg said, part of the problem was in the backend configuration, specifically the CORS configuration. Also, in React the `apiSlice` was misconfigured, since to fix another problem I had. Changing the apiSlice mode from `'no-cors'` to `'cors'`, the pre-flight appears in the chrome network panel.

https://peaku.co/es/preguntas/54525-problema-de-redux-toolkit-rtk-query-cors

Then, in the backend I had to modify how I was implementing CORS, since it was applying CORS to all routes and origins and that configuration was not valid **with credentials** since it does not support wildcard. So the solution for this part was to set the CORS options like @fregayeg said

- https://stackoverflow.com/questions/19743396/cors-cannot-use-wildcard-in-access-control-allow-origin-when-credentials-flag-i
- https://expressjs.com/en/resources/middleware/cors.html

![apiSlice](https://user-images.githubusercontent.com/40372021/178077732-665f495c-7744-4731-9bc2-f9cc962ae06c.png)

![CORS](https://user-images.githubusercontent.com/40372021/178077747-8259391d-cfd3-494b-822d-4d385f33a3f8.png)

**Comment by Shaker-Pelcro** [comment]
For me, I had to set the "Accept" header to "application/json" in the `prepareHeaders` function.
I thought this was supposed to be the default behavior, and since I had no control over the back-end I had to do that.
I also tried "Axios" with the same "post" request that was failing just to be sure I'm not going mad or something, and the request was successful with "Axios", so the issue for me was to set the "Accept" headers.

```
headers.set("authorization", `Bearer ${loggedInUser.token}`);
headers.set("Accept", "application/json");
```

**Comment by ozergul** [comment]
Hi guys,
I faced this problem at Nextjs.
I have different codebase for my backend, with nodejs, expressjs.
I spent a lot of times to fix it but couldn't. 

But look what I found!
I created new project with vite. And everything works as expected! 
So my assume is the problem is nextjs in my case.

**Comment by ozergul** [comment]
I found solution

I used this approach, and basically used axios to send my requests. Not it works perfect.

https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#examples---basequery

**Comment by phryneas** [comment]
There are comments by about a dozen of people here by now.  
If any of you could have given us a reproduction of the problem you are describing here, we could have either fixed the problem (if it's a bug), or pointed out how to do it correctly.  

Using axios is not a good fix. It adds 6kb of bundle size to your application without any further benefit.

Although, at this point, I honestly believe that no two people in this thread have the same problem, but that all of you have completely different problems. Either way: **we need a reproduction to give any of you any feedback**.  
Please stop commenting here without a link to a CodeSandbox that shows your problem. It's incredibly frustrating.

**Comment by Stevedev7** [comment]
> I am also facing this issue. Even when I hard code the value in it doesn't work. The `console.log` just prints an empty Headers object
> 
> ```
> baseQuery: fetchBaseQuery({
>     baseUrl: process.env.REACT_APP_API_BASE_URL,
>     mode: 'no-cors',
>     prepareHeaders: (headers) => {
>       // If we have a token set in state, let's assume that we should be passing it.
>       headers.set('Authorization', 'Bearer MY_TOKEN');
>       console.log(headers);
>       return headers;
>     },
>   }),
> ```
> 
> <img alt="image" width="354" src="https://user-images.githubusercontent.com/62375480/176769472-b3e46f3e-51dd-4bb8-a652-234ff1e11670.png">
> 
> here's the `EndpointBuilder`
> 
> ```
> getCredentialById: builder.query<Credential, string>({
>     query: (id) => `credentials/${id}`,
> }),
> ```

Have you resolved your issue?

**Comment by phryneas** [comment]
Quoting myself from two comments above:

> Please stop commenting here without a link to a CodeSandbox that shows your problem. It's incredibly frustrating.

I am locking this issue now.

I am very happy about people opening issues regarding this that contain a CodeSandbox or repository that I can look at, run on my own machine and give feedback on.

I reserve the right to immediately close any issue new issue on this topic that is just "it's not working".   
I already said multiple times in this issue that that's not enough information to help you, and if you want help you have to put in the effort to give us enough information to actually help you.
