### ISSUE TITLE
fetchBaseQuery HTTP method case sensitive (400 bad request)

### ISSUE THREAD

**Issue by Rc85** [reduxjs/redux-toolkit#2471]
# Problem

Sending a `get` request is fine. Anything else, the method is not automatically converted to uppercase.
```
export const merchantApi = createApi({
  reducerPath: 'merchant/api',
  baseQuery: fetchBaseQuery({ baseUrl: '/' }),
  tagTypes: ['Restaurant Location'],
  endpoints: (builder) => ({
    toggleRestaurantLocation: builder.mutation<
      undefined,
      { restaurant_id: string | undefined; location_id: string }
    >({
      query: (params) => ({
        ...endpoints.merchant.location.toggle,
        params
      }),
      invalidatesTags: (result, err, arg) =>
        result ? [{ type: 'Restaurant Location', id: arg.location_id }] : []
    })
  })
});
```
`endpoints.merchant.location.toggle` is an object like so `{ method: 'patch', url: '/path/to/toggle/location'}`.

![image](https://user-images.githubusercontent.com/22307591/176616091-3cc516ab-f9af-4fca-8640-b49b4c648e34.png)

Because express.js uses lowercase for their router, it messes up my setup.
```
// router.patch
router[endpoints.merchant.location.toggle.method](endpoints.merchant.location.toggle.url, (req, resp) => {});
```

# Solution

1. Convert the method in `fetchBaseQuery` to uppercase.
2. Specify in the document that the method is not converted to save new developers time on debugging. Took me a good 30 min or so to figure it out.

# Workaround

Use a different `queryFn` like axios. Sadly, it's more boilerplate for a library that specifically emphasizes and aims for simplicity.

**Comment by phryneas** [comment]
We are just calling `fetch`, the browser's modern HTTP client implementation with what you provide us - it is essentially as if you were calling `fetch({ method: 'get' })` yourself. 

Yes, [HTTP methods are case sensitive](https://www.rfc-editor.org/rfc/rfc9110.html#name-overview), and yes, you will have to uppercase that. 
If `express` deviates from that standard and you rely on that, there isn't too much we can do - but you can always call `router[endpoints.merchant.location.toggle.method.toLower()](endpoints.merchant.location.toggle.url, (req, resp) => {});` or something similar.

**Comment by Rc85** [comment]
I found out `patch` is not listed as a spec in the fetch API. Using `put`, the api will convert to uppercase.

https://github.com/github/fetch/issues/37
