### ISSUE TITLE
invalidateTags result and error undefined when using queryFn

### ISSUE THREAD

**Issue by Rc85** [reduxjs/redux-toolkit#2472]
```
// createApi
  builder.mutation({
      queryFn: mutationFn,
      invalidatesTags: (result, err, arg) => {
        console.log(result, err, arg);

        return result ? [{ type: 'Restaurant Location', id: arg.params.location_id }] : [];
      }
    })
  })

const mutationFn = async (
  arg: {
    url: string;
    method: AxiosRequestConfig['method'];
    params?: AxiosRequestConfig['params'];
    data?: AxiosRequestConfig['data'];
  },
  api: { dispatch: ThunkDispatch<any, any, any> }
) => {
  api.dispatch(appLoading(true));

  try {
    const response = await axios(arg);

    api.dispatch(appLoading(false));

    return response.data;
  } catch (err) {
    api.dispatch(appLoading(false));

    return err;
  }
};
```
What am I doing wrong?

**Comment by phryneas** [comment]
It's no fun for us to guess what is happening by staring at partial code snippets. You could at least tell us what is happening on your computer. Are you getting an error? Is nothing happening? Did your PC grow wings?

**Comment by Rc85** [comment]
The `queryFn` is so that I don't have to repeatedly dispatch a loading state and remove it after. For context, `appLoading` displays an overlay over the entire page with a loading indicator. If I track the `isLoading` status, I have to do this everywhere I am triggering a mutation. I only want to do it once and mostly for mutations.

Anyways, I created a sandbox with two different `queryFn` to reproduce the problem.

https://codesandbox.io/s/exciting-rui-yokdj8

If you look at the console log, you will see undefined for `result` and `err` in both `retrieve` and `create` endpoint. If you change `queryFn` to `query`, they will be defined. Without `result` or `err`, I cannot invalidate tags in my mutation using `queryFn`.

**Comment by phryneas** [comment]
You should get that message in every development build, maybe your setup uses the production build?

As for a loading state, you can just do something along the lines of

```js
const someMutationRunning = useSelector( state => state.api.mutations.some(mutation => mutation.status == 'pending')
```

just from the back of my head and it might need a bit of shifting it to your use case, but you really do not need to handle that manually.

Also, you could run into deadlocks if you handle it manually: what if you have two mutations running and one finishes long before the other? All that stuff.

**Comment by Rc85** [comment]
How do I check which build I'm using?

Looks like your way is much more manual than mine. Do you really want to write that in every component that triggers a mutation?

Not sure what you mean by deadlock. For context, `appLoading(true)` will display a semi transparent overlay with a loading indicator over the page and prevent any interaction, so there can never be two mutations going on.
