### ISSUE TITLE
Server side rendering with getRunningOperationPromises

### ISSUE THREAD

**Issue by JulienKode** [reduxjs/redux-toolkit#2477]
Hi 

I've try to take a look at the ssr-experiment exemple here:
- https://github.com/JulienKode/ssr-experiments/pull/new/chore/demo
- https://codesandbox.io/s/naughty-robinson-47e9jt?file=/package.json

I've:
- added console log on `getRunningOperationPromises`
- Create a fake long query (10s)
- try to fetch with few seconds of delay the two pages:
    - http://localhost:3000/pokemon/ssr/bulbasaur
    - http://localhost:3000/pokemon/ssr/beedrill

On the `beedrill` fetch this is what I can see when displaying running promises:
  ```
  {
  "getPokemonByName(\"beedrill\")": {
    "arg": "beedrill",
    "requestId": "070QxaL_aSi7MV3VbQzDQ",
    "queryCacheKey": "getPokemonByName(\"beedrill\")"
  },
  "getPokemonByName(\"bulbasaur\")": {
    "arg": "bulbasaur",
    "requestId": "FdsRw3PmBbDP5sR7-kKPe",
    "queryCacheKey": "getPokemonByName(\"bulbasaur\")"
  }
}
  ```

- Is it normal that we are waiting for `bulbasaur` when our page are just concern about `beedrill` ? 
- Should the `runningPromises` created in the api be unique to each page and not sharing across different page ? otherwise on large scale apps this could be an issue if we are waiting for the queries of another page
- Does the `runningPromises` should be isolated to each page on SSR ? 
- like `createListenerMiddleware` should we have a `createApiMiddleware` ? Then on server side, we can have a different middleware instance for each page that does not share values

This is the debug line that I've added in redux:
```
  function getRunningOperationPromises() {
    console.warn("[DEBUG] RUNNING OPERATION PROMISES ", {runningQueries})
    console.warn(JSON.stringify(runningQueries, null, 2))
```

@phryneas  @markerikson

**Comment by phryneas** [comment]
Could you give some feedback over in #2481 please?

**Comment by markerikson** [comment]
Marking this as done because it's in 1.9 beta.

**Comment by JulienKode** [comment]
Thank you @markerikson @phryneas
