### ISSUE TITLE
patch method are not capitalized when api call (http method : patch)

### ISSUE THREAD

**Issue by yunyami0605** [reduxjs/redux-toolkit#2479]
I set createApi up like the code below.

And, api call when patch comment.

But, the patch method did not convert from lowercase to upper case automatically. (* I check network tab)

I guess that it is rtk bug.

Because The other http method(get, post, put, delete) was well converted from lower case to upper case automatically.

```
export const commentApi = createApi({
  reducerPath: "commentApi",
  baseQuery: fetchBaseQuery(commonBaseQueryOption("/comment")),

  refetchOnMountOrArgChange: 0,
  tagTypes: ["comment"],
  endpoints: (builder) => ({

   ...

    // api patch comment content
    patchCommentBoard: builder.mutation<
      number,
      { id?: number; body: { content: string } }
    >({
      query: ({ id, body }) => ({
        url: `/${id}`,
        method: "patch",
        body,
        credentials: "include",
      }),
      transformResponse: (response: IRes<number>) => response.data,
    }),

   ...

  }),
});
```

**Comment by phryneas** [comment]
This is a "bug" in the `fetch` specification and you will get the same behaviour with just normal `fetch`. See https://github.com/github/fetch/issues/37

So, this is essentially behaviour baked into your browser.

Best just stick to the HTTP standard and write HTTP methods uppercase from the start.

**Comment by phryneas** [comment]
Also see https://github.com/whatwg/fetch/issues/50  where this is discussed further: bottom line is you should be using uppercased methods from the start, allowing lowercase in the first place is just some legacy compatibility thing and they are not starting to expand that.

**Comment by yunyami0605** [comment]
oh! i understand this fetch spec.
Thank you for the comments.
