### ISSUE TITLE
ActionCreator types extend incorrect. 

### ISSUE THREAD

**Issue by arajg0909** [reduxjs/redux-toolkit#2490]
I have a situation where I need to infer if the action creator has a payload. 

I am attempting to use the reducer I got from createSlice with the `useReducer` hook. I need to wrap all the actions with this dispatch and then expose them via 
```
const slice = createSlice({
  ///
})

export const reducer = slice.reducer;
export const actions = slice.actions;
```

```
import { reducer, actions } from './slice';

const useHook = () => {
  const [state, dispatch] = useReducer(reducer, {});

  const wrappedActions = _.reduce(actions, (res, actions, key) => {
    res[key] = ( ...args ) => dispatch(action(args));
  }, { })
  
  return [state, { ...actions }
}
```

I have removed some of the type annotations from here for brevity. 

But basically the issue is I can get everything to work using 
```
type DoesItExtend<T> = T extends ActionCreatorWithPayload<infer R> ? 'yes' : 'no'; 
const action: ActionCreatorWithoutPayload<'something'>;    
const didActionExtend: DoesItExtend<typeof action>;
```

The only place this does not work is when using an ActionCreatorWithoutPayload because it is inferred as an ActionCreatorWithPayload<undefined> instead. 

```type Dispatched<T> = T extends ActionCreatorWithPayload<infer R>
  ? (args: R) => void
  : () => void 
```

This breaks because it expects exactly 1 argument of type undefined instead of the 0 arguments.

**Comment by phryneas** [comment]
Please give at least a working TS playground, it's pretty hard to say anything at all without that.

My guess would be that your application does not have `strict: true` in the `tsconfig.json` though.

If you want a library with pre-bound action creators and `useReducer`, you can by the way also take a look at [use-local-slice](https://www.npmjs.com/package/use-local-slice)

**Comment by arajg0909** [comment]
[URL to playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMBK6AmyDG6UcAvnAGZQQhwDkU6AhvjLQNwBQokscA+hSo1aAGwg5GqABbsu4aPCQBBFsAgA7AMINGMaAHVgMKQAVGATzGMcpQdToABBngAeAK1QB6PRBEBrI1kOdBceeHwNVHgwEQsiAEl1I2BGEQBlGF10AC44E1jzIgysuABeRA44OGBUfItgdQBzXJgoZHQAGkrq1AAhZHJyIgbmuFb2rqqazQ0YdHUYYthcXPJUjEmepRwAWXEcinXO7prtuvMR1aPNsCpGhlRUXIAGTbwoXTV1F83pCAB3c5EADyADciAUriINt0iFQoE84ABtAC6mxqiRgIihMJInGCoQU1QWRDWhDyBSKmTmFSmtQKlzgACMIL4mOpOHT+oNhk1ciy2YwOSdUDMSQslnMcPzWSJ2Zytrt9jLBcK6WcGXzmbL5d1bhB7uhHrl1MgQEyiAr3p8NCazRaoAq-oDKVAwRCLCq5UKFXDoIilFAPuYADxRKAjAB8CoxC2x2tVnBIHDkYUQcHwOjmaREwHJZEo9loTlwyHcXh8-kCnG4RKQZksEGsKhgX1sheEJdcHm8soCrHxDTmUDJ6DgxTmABUPupUMkNCG0pHaXAABQNZKpCcHNIASlyaSTHBg5jAY6BUG306Fc9bGjK4+p6Gvs-n6hDF+30ZTEVn4W9UDckMEZap+T4vrebblFEJSlMuq4IN0AB0KEwXM6J9AMwGMms0LHCQu74r+URwKgubkuUmZMNm5HoAh3TqIwIAHLQMRxJeT60OiSStluT65GxhRQIkm7pE+mzOAQRCIohVRVN0VQaJgnxNAAoi4Ri5GhY5wWuSAoUh2kdKRUgAhe7pQJChx4aQu6bFUDzoDAJh3A8iLaWU8H6ah4lwPqhrGnAzy2fZcAaC5Bpubkq4KXJRmxVUzB3t8eQWFYOAtl8IZIL+cwLJOoAHKa5qWhmszzDAAAiyAfMldolcQJCRqFu6eXpCVwAZ8VyXJ-lRXASVfEhYBpU2OBIblFUFcxoVVNadUDaoGjDaN1gTeVCzVbVXyhQRmwkF0BH4iEabEdErrYHghDENBtFIZJ12cCdRJnX5rqZZED5kXm6BIYNkT4imJ5nnAlU1CNMD4FIuAhpOy7lJOcAhHlOCoHAH1aFmBhGKYq04CGDTAXAmCRt0AD8a6MFAjSIpgrW6aCEDADg3TRfTy6M8z+LA2OYOoBDUNKCIIiw-DK5IiYxJwH46DmBA5BwJOKK5HzAvQ-jk4Syi354j+kTwGg6BgbBa7syur1IoJVJZMZODg7oUNwCiD6G5dUlQKuVtQG713GV7Im8WJWSESmVSeJ4ZV-otyVo+UslwOHcmOc5rlGoiq5m3b-MO1InvvUts73UaTkRQFqAZ3Z3SJ4p6jKa2akaTAbNtVnat5+xGOoEhSkqY06lGBXmzV2F6il-1CGR3lVU1Ta6jGZN+WFaQuQIAv0-bbacDFQ688bTA01FfaRAES39uQ7nXud93o+p48CFr1ts+7+K++FQRldhxHyah5HJH-bOD4+BFyunRS+BdUDGVXA8ZAIgYDGX-sZGW5gzbxwckaGBMAkRIIGmjJB8sxinnQPgsBMdnblFXAZKmNNchCmQafbO59Vz-yYdTVAu4Q49QYDAGq6g4DQNgQqA6iAyCSFBmfQWwsQw82IfnGOkZdwpm6FwnhyIvbbmMt5P64DSDO1EWdJMgMOCvUNpOI08ByEoO6BbIycBW45zISgDAxs5gZytOIqQ18x5pwnmvA+uQACMz8p6PwWv42ybiGFQyLhgFOkVvEcNse4zxt9y45T3iEr4ASglTUKgE8JP87Hn2SXEu+aSX5+LoAAJi4pPCqGTN60H8bQfJc0knhRSQhI63RClROAMLdAjRUg7CcqZHAriOC6yAA)

**Comment by arajg0909** [comment]
Just for clarity. The first 3 usages in the useTest should be legal and the last 3 should be illegal

**Comment by markerikson** [comment]
@arajg0909 : it works just fine if you do:

```ts
 const [playerState, reducerDispatch ] = useReducer(playerReducer, playerInitialState);
  reducerDispatch(playerActions.resetProgress())
```

so the issue is something about your custom hook's wrapping types.

**Comment by arajg0909** [comment]
I went ahead and simplified the question further 
```
import {
ActionCreatorWithPayload,
ActionCreatorWithoutPayload,
} from '@reduxjs/toolkit';

type DoesItExtend<T> = T extends ActionCreatorWithPayload<infer R>
  ? 'yes'
  : 'no';
const action: ActionCreatorWithoutPayload<'something'>;
const didActionExtend: DoesItExtend<typeof action>;

console.log(typeof didActionExtend);

```

didActionExtend is of type 'yes'. I tried it with an actual ActionCreatorWithoutPayload also. 

[URL to playground](https://www.typescriptlang.org/play?ssl=12&ssc=37&pln=1&pc=1#code/JYWwDg9gTgLgBAbwFAEEDGNgQHYGEoCmAhjNAOrAwAWACkQJ4A2ERAJgDSoZZ6EnmUqEAK4w6TFhyQBfOADMoEEHADkAAUKthADwBWAZwD0pCIwDWlFQG4kSGPTAE4AEQgF9ASRgBRbTALYrAA8ACoAfHAAvHAhcAR+Aaz6cOiYOPjEpFAU1OLMbEHA2HIEUHAASmFIcHAA-Kr07irVcABcqtgQ1kiMBPBE3DjtqTwZ-NmCImIM+cEq+kp9VEUA5iphNr3wrMCsIzi+-oHtru5eh4lB9o4QcnADadgbtmg4C70AdMwrABTXBLc4Ds9oNsBdAgBKKxAA)

**Comment by markerikson** [comment]
@arajg0909 I'm... honestly not sure what you're trying to show there.

As I said above, the actual issue here is that the wrapping functions you're trying to generate do not appear to be typed well.  My first suggestion is **don't try to wrap these action creators in the first place**.

If you still _really_ want to do that, then use the `bindActionCreators` method from Redux, which is re-exported from Redux Toolkit.

**Comment by arajg0909** [comment]
Just leaving a comment here incase someone keeps searching for something like this. 

I realized I was forgetting a ? after the args in 

```
  ? (args?: R) => void
  : () => void 
```
