### ISSUE TITLE
RTK Query hooks should use `useDebugValue` to better display data

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#2492]
I'm looking at a `useQuery` hook's values in the React DevTools, and I have to dig down to inspect the contents:

![image](https://user-images.githubusercontent.com/1128784/177621994-b4e14755-b5e9-4e9f-bce0-63eda713d022.png)

We should use the `useDebugValue` hook to show this better - at a minimum `data`, and possibly some of the flags too.

**Comment by mbaneshi** [comment]
Would you please mention some link to guide me how start figuring out what should do

**Comment by markerikson** [comment]
We need to add calls to `useDebugValue` inside the existing `useQuery` hooks (and possibly the `useMutation` hooks too?).

We should pass them the actual `data` that's being stored internally, or possibly the entire cache entry object.

See these resources:

- https://reactjs.org/docs/hooks-reference.html#usedebugvalue
- https://blog.logrocket.com/improve-custom-hook-debugging-with-usedebugvalue/
- https://blog.webdevsimplified.com/2021-11/use-debug-value/

And here's how it's used inside of `useSelector` in React-Redux:

https://github.com/reduxjs/react-redux/blob/1659df0d9512463ff09fccb17a0a1a155045d0aa/src/hooks/useSelector.ts#L61
