### ISSUE TITLE
Docs: minor tweaks to improve clarification of the createAPI

### ISSUE THREAD

**Issue by victor-cody** [reduxjs/redux-toolkit#2496]
Hello! 👋 I was reading about the [createAPI](https://github.com/reduxjs/redux-toolkit/blob/master/docs/rtk-query/api/createApi.mdx#createapi) and came across this sentence in the first paragraph.

> It allows you `to define a set of endpoints describe how to retrieve data from a series of endpoints`, including configuration of how to fetch and transform that data. 

The section highlighted in the quote is a bit unclear, and doesn't effectively communicates what the API is/does. 

### Ideas for improvement 

Adding a conjunction or rephrasing that part will definitely improve the flow and clarification of the createAPI. 😃

**Comment by fregayeg** [comment]
Hello! is it possible to join @victor-cody on trying to fix this ?
