### ISSUE TITLE
Add support for Automated Re-fetching to rtk-query-codegen-openapi

### ISSUE THREAD

**Issue by Briscoooe** [reduxjs/redux-toolkit#2502]
First, apologies if I have missed this configuration option somewhere. If it does exist, please direct me towards it. If not, read on.

The codegen library does not produce code that supports [Automated Re-fetching](https://redux-toolkit.js.org/rtk-query/usage/automated-refetching) as it doesn't output the `providesTags` or `invalidatesTags` properties. Lack of this feature means having to manually fetch data after data-changing operations which can add a lot of complexity and unnecessary code, given that RTK Query provides it out of the box anyway.

On my own fork of this repo [I have provided a naive implementation of how this would work](https://github.com/Briscoooe/redux-toolkit/commit/688f3cd0772cac63baf40ef18d59a6ebafe71580#diff-2458172608419f613306ffe4aa809c58d6a976618741880d28a45da168e9ce21R301). This works for me locally and it is sufficient. If there is interest in this feature I can complete it and submit a PR. 

The big missing piece is it does not call `api.enhanceEndpoints({ addTagTypes: [...]});` to automatically add all of the tags to the `tagTypes` property, lack of which can cause TS errors. I looked into the TS Compiler API as I saw it used a lot around the codebase but after a few attempts I gave up trying to call the function and figured I'd ask here if its worth the effort

**Comment by phryneas** [comment]
This should be available with https://github.com/reduxjs/redux-toolkit/pull/2071 but not published yet.

If you need more than that we recommend further enhancing the autogenerated api with `enhanceEndpoints`.

**Comment by Briscoooe** [comment]
Sweet, that is exactly what I was looking for. Any idea on a public release date?

**Comment by phryneas** [comment]
It should be pretty much ready for release, but @msutkowski wanted to do a little more tweaking I think

**Comment by Briscoooe** [comment]
cool, thanks!
