### ISSUE TITLE
Add support to mobile developers

### ISSUE THREAD

**Issue by fregayeg** [reduxjs/redux-toolkit#2507]
### Discussed in https://github.com/reduxjs/redux-toolkit/discussions/2505

<div type='discussions-op-text'>

<sup>Originally posted by **fregayeg** July 11, 2022</sup>
Hello! I'm a mobile app developer (React Native), currently, I'm using RTK and its feature Query. I read RTK docs almost everyday, really enjoying it 😍. 

However, I wish I could see some intros, guides or conclusions about mobile development using modern redux, I mean on the docs website, if its possible 🙏. 

Sometimes I find it difficult to follow an example (codesandbox example) from docs, which is ofc a web app, to make such in my mobile environment . I think it could be more better for people like me to find some ready examples in docs for mobile purpose. This [one](https://reactnative.dev/docs/0.64/getting-started#interactive-examples) is a demo with possibility to interact and see result in time. ([Expo snack](https://snack.expo.dev/))

As a **starting point**, I'd suggest to add `mobile` keyword to [this paragraph](https://redux-toolkit.js.org/rtk-query/overview#:~:text=It%20is%20designed%20to%20simplify%20common%20cases%20for%20loading%20data%20in%20a%20web%20application):
> It is designed to simplify common cases for loading data in a web application

So it becomes:
> It is designed to simplify common cases for loading data in a web & **mobile** apps.

Note: I know that many use cases are same as on web, so there are no big differences 🙂. I aim to **what is different**  like [mobile navigation](https://reactnavigation.org/), [notifications](https://github.com/wix/react-native-notifications), [bottom-sheet](https://gorhom.github.io/react-native-bottom-sheet/), [testing ](https://callstack.github.io/react-native-testing-library/) and for me the prior topic, could be about **fetching & caching data**. 

The advantages:
- ٌHelp any developers to discover what is common between web and mobile and what is not.
- Help mobile developers to use redux with less pain. 
- Redux will appear more powerful and effective compared to other tools.
- Attract the attention of mobile developers around the world, especially those working on large and complex systems.
- Get more contributors and fans 🤩

This idea is open to any criticism, enrichment, feedback</div>

### Action plan:
Following the discussion above, I'd start to try to give support to [React Native - Expo](https://expo.dev/) mobile development in Redux Toolkit website. 

My current plan is as follows:
- Add a new menu **in docs** like the example below:
![image](https://user-images.githubusercontent.com/40466585/178453380-d8cbba19-1019-4bf1-b7a5-efb3011f5a5e.png)
- In a 1st page:
  -  I'd give an **introduction to modern redux** for mobile developers.
  - Motivational expressions.
  - Suggestions about recommended tools.
  - A sample example to start with. (I'd use my own experience to express ideas).

I don't want to go further for now, just want to try this simple step (one page), to see how it goes. Any help or contribution is welcome. 🙌

**Comment by markerikson** [comment]
I don't think we actually need an entire separate docs category for this.  At most, we need a section in the Redux core docs about store/app setup with RN:

https://github.com/reduxjs/redux/issues/4035

Other than that, there really _isn't_ much different about using RTK with RN.

Sorry if I wasn't clear enough in that discussion thread.
