### ISSUE TITLE
support for graphql 16 @rtk-query/graphql-request-base-query ?

### ISSUE THREAD

**Issue by binarybaba** [reduxjs/redux-toolkit#2512]
Currently only upto graphql@15 is supported. Any plans when to support 16?

**Comment by phryneas** [comment]
Sure. For what it's worth, you should be able to currently use it with 16 without any problems - there is only one reference on type level in there:
```ts
import type { DocumentNode } from 'graphql'
```

**Comment by phryneas** [comment]
released as additional peerDependency in 2.2.0

**Comment by binarybaba** [comment]
Thanks @phryneas! :D
