### ISSUE TITLE
createAsyncThunk first parameter

### ISSUE THREAD

**Issue by felipehimself** [reduxjs/redux-toolkit#2517]
Hi everyone

I'm not really sure if this is an issue or if I have messed up on something, but I've gone over the documentation and I haven't found an explanation about that.

I have two different createAsyncThunk, each one responsible for managing two different states:

```
export const funcA = createAsyncThunk(
  '/api/products/id',
  async (id, thunkAPI) => {
    try {
      (...)
    } catch (error) {
      (...)
    }
  }
);

```
```
export const funcB = createAsyncThunk(
  '/api/products/id',
  async ({  id,  qty }, thunkAPI) => {
    try {
      (...)
    } catch (error) {
      (...)
    }
  }
);

```
 
As you can see, I've passed the same fist parameter for funcB and funcA (```'/api/products/id'```), and when I was on the component which dispatchs funcA, funcB was being called as well, even though its component was not being called (not even a piece), and it was changing the state managed by funcB.

Is this the correct behavior? I'm sorry if I've missed something on the docs, any explanation will be appreciated.

**Comment by markerikson** [comment]
Yeah, that's the problem. 

Internally, Redux still relies on action type strings to decide what reducers should run.

The first param to `createAsyncThunk` is a prefix.  In this case, `'/api/products/id'` will get turned into `'/api/products/id/fulfilled'` (and `/rejected` and `/pending`).  

When you create two thunks with the _exact_ same prefix, you're defining two different ways that actions with those type strings get dispatched, and that's going to cause problems with your reducer logic.  

So, **don't do that :)  give every `createAsyncThunk` a unique prefix string argument**.
