### ISSUE TITLE
Broken links related to rsk-convert-todos-example

### ISSUE THREAD

**Issue by JeffGuKang** [reduxjs/redux-toolkit#252]
There are broken links related to [rtk-convert-todos-example](https://github.com/reduxjs/rsk-convert-todos-example) in [intermediate-tutorial](https://redux-toolkit.js.org/tutorials/intermediate-tutorial).

This seems to be a problem while converting rsk to rtk.

Current address: https://github.com/reduxjs/rtk-convert-todos-example/commit/0c3542417ceb758b017fab5b388a1c5c11d5ec49

Right address: https\://github.com/reduxjs/rsk-convert-todos-example/commit/0c3542417ceb758b017fab5b388a1c5c11d5ec49

And I think it can be solved to change rsk-convert-todos-example to rtk-convert-todos-example. Thus, I did not make PR related this issue.

**Comment by markerikson** [comment]
Yeah, I didn't have a chance to rename the repos yet.  I've just done that, so those links should work now.

Having said that, I still need to rewrite the contents of the repos to match the new package name.  I'll try to do that in the near future.

This issue should be resolved now.  Thanks for reporting it!
