### ISSUE TITLE
InvalidateTags doesn't work with graphql

### ISSUE THREAD

**Issue by berlirumapea** [reduxjs/redux-toolkit#2523]
I'm trying to invalidate cache using automated refetching after the mutation is complete, but it seems like using `InvalidateTags` doesn't work. I tried using `refetch` and it's working. Any idea what's happening?

You can see my full code in [here](https://github.com/berlirumapea/graphql-client/blob/master/src/examples/rtk/services/github.ts)

**Comment by phryneas** [comment]
Your store setup is missing the middleware. You should even have a warning on your console about this.

**Comment by berlirumapea** [comment]
Ah you're right. I've been seeing `info` tab in console I didn't see the warning. Thanks a lot
