### ISSUE TITLE
All Types Missing

### ISSUE THREAD

**Issue by ianpaschal** [reduxjs/redux-toolkit#2529]
Somehow none of my RTK code has types. I suspect this is a bug... although I've been using RTK pretty widely and haven't seen it in other projects. So I'm trying to spot the difference in order to blame this on myself and I can't find any... although it's hot in Europe these days and there's no AC and I haven't been thinking straight.

The good news is, I did manage to recreate it in a reproduction repo. It could very well be that I'm just missing some important piece somewhere but I've stripped the repo pretty bare-bones, including `tsconfig.json` and it's still occurring.

You can find the repo here: https://github.com/ianpaschal/redux-repro

I've also made some screen shots showing what all doesn't have proper types, although it's pretty much "everything."

<img width="789" alt="001" src="https://user-images.githubusercontent.com/1137232/179996531-435f0ceb-dd50-4725-9735-8705fb5e89df.png">
<img width="789" alt="002" src="https://user-images.githubusercontent.com/1137232/179996525-997fe185-d23e-4d9d-bac4-d8d69431be82.png">
<img width="789" alt="003" src="https://user-images.githubusercontent.com/1137232/179996512-d08ecace-7272-44db-a14c-d305181136f1.png">
<img width="789" alt="004" src="https://user-images.githubusercontent.com/1137232/179996521-3ffaeee3-5402-49e0-a642-c1ee381ebba1.png">

Any insight would be greatly appreciated. And again, apologies if this is actually a support matter due to me coding sloppy.

**Comment by markerikson** [comment]
I _think_ there's two issues here.

First, your `tsconfig.json` isn't set to actually include the `services` folder.  When I add `services/**/*` to the `include` list, I start seeing some errors.

The second issue is that **you are importing the `store` into the API file and using it _inside_ the API definition!**  I think this is causing a circular type definition problem and TS doesn't know how to resolve anything.

If I comment out the `store.getState().user.userId` bit, _now_ I get TS types for everything:

![image](https://user-images.githubusercontent.com/1128784/180910439-56518e8d-0cf6-4c4d-92d7-bd63bf00e25c.png)

FWIW this is an example of why we specifically advise against trying to directly import the store into any other files :)

I'm not immediately sure of other options for getting the user ID inside of `query()`, beyond passing it in as part of the cache key argument.

As a last-resort fallback, you could inject the store into this file via a setter:

https://redux.js.org/faq/code-structure#how-can-i-use-the-redux-store-in-non-component-files

Hopefully that helps clarify things!

**Comment by phryneas** [comment]
You really should not call `store.getState()` in a `query` function. If we wanted you to call it there, we would pass it in as an argument. It's not safe - if your userId changes that query will not automatically re-execute. You need to pass that in as an argument.

**Comment by ianpaschal** [comment]
Sorry I forgot to reply to this. Makes sense.

I will say, just in the form of a "think about it" remark: It's a bit too bad because it makes it quite messy to pass the API parameters like some kind of standard organization ID or something like that if every time you want to use a `useFooQuery()` you have to first prefix it with `const orgId = useAppSelector(selectOrgId);` or whatever and pass in `orgId` as a `skipToken`/arg. I guess we could wrap all of our RTK Query hooks in a custom hook that does that but a big part of the selling point of RTK and RTK Query to me is the need to write less boilerplate.

Again, good point about the re-execution, that makes sense, but it's still kind of an unfortunate thing to work around.
