### ISSUE TITLE
Error messages appear to use placeholders

### ISSUE THREAD

**Issue by dwightwatson** [reduxjs/redux-toolkit#253]
Hey there, I'm trying to migrate to this from a new-ish standalone React/Redux set up. I'm using React Native through Expo. Obviously there's something wrong with my code and I'm trying to debug where I've gone wrong, but a number of the error messages I'm receiving simply have placeholders without complete context.

```
A non-serializable value was detected in the state, in the path: `%s`. Value: %o
Take a look at the reducer(s) handling this action type: %s.
(See https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state), messages.0.createdAt, 2019-11-14T05:30:38.729Z, messages/addMessages
- node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
- node_modules/@reduxjs/toolkit/dist/redux-toolkit.cjs.development.js:165:24 in <unknown>
- node_modules/redux-immutable-state-invariant/dist/index.js:55:36 in <unknown>
* screens/messages.js:23:38 in onSend
- node_modules/react-native-gifted-chat/lib/GiftedChat.js:115:34 in <unknown>
- node_modules/react-native-gifted-chat/lib/Send.js:26:27 in onPress
- ... 23 more stack frames from framework internals

A non-serializable value was detected in an action, in the path: `%s`. Value: %o
Take a look at the logic that dispatched this action:  %o.
(See https://redux.js.org/faq/actions#why-should-type-be-a-string-or-at-least-serializable-why-should-my-action-types-be-constants), payload.0.createdAt, 2019-11-14T05:30:43.585Z, Object {
  "payload": Array [
    Object {
      "_id": "3f72cd2c-fb9e-4806-a14b-3efcd6c77b75",
      "createdAt": 2019-11-14T05:30:43.585Z,
      "text": "Testing",
      "user": Object {
        "_id": 1,
      },
    },
  ],
  "type": "messages/addMessages",
}
- node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
- node_modules/@reduxjs/toolkit/dist/redux-toolkit.cjs.development.js:155:24 in <unknown>
- node_modules/redux-immutable-state-invariant/dist/index.js:55:36 in <unknown>
* screens/messages.js:23:38 in onSend
- node_modules/react-native-gifted-chat/lib/GiftedChat.js:115:34 in <unknown>
- node_modules/react-native-gifted-chat/lib/Send.js:26:27 in onPress
- ... 23 more stack frames from framework internals

```

**Comment by markerikson** [comment]
You're right, and I don't think it _ever_ worked right.

When I created the serializable middleware, I based it off the `redux-immutable-state-invariant` middleware.

The immutable middleware uses `invariant()`.  When I ported it, I apparently just used `console.error()`, which is, uh, not the same thing at all.

I gotta head to bed, but I'll try to fix this within the next couple days.  Thanks for reporting this!

**Comment by kevin940726** [comment]
I would like to help fix this.

I think we can just leverage template literals, no need to import invariant package as a dependency. Maybe just make the message a function?

**Comment by kevin940726** [comment]
TIL that most modern browsers support string substitutions out of the box.

![image](https://user-images.githubusercontent.com/7753001/68838951-a0590280-06fa-11ea-979c-868569ec2989.png)

I guess the issue here is that it's running in Expo? I'm not familiar with Expo though, is it still using chrome dev tools? Should we still change the implementation so that every environments will get the same output?

**Comment by dwightwatson** [comment]
Might not be Expo/React Native specifically - does Node support string substitutions?

**Comment by kevin940726** [comment]
@dwightwatson Yep node support string substitutions too.

![image](https://user-images.githubusercontent.com/7753001/68844187-5d9c2800-0704-11ea-9cb7-595bfb358c32.png)

Could you help identify the environment which causes this bug?

**Comment by dwightwatson** [comment]
Ah cool, that's that out then. 

I can debug the app using "React Native Debugger" which seems to use a Chrome developer console, which displays the error correctly. Expo also has an experimental feature that exports your app to a web app - when I trigger this error in a browser, the error appears correctly in the Chrome developer tools.

So I suspect the error is in whatever React Native/Expo is using for terminal logging. I'm relatively new to these so I'm not really sure where to go from here.

I suppose one could argue it's out of scope for this to have to support formatting in a terminal console output - you'd expect most of the time it's in a browser window - but if there's an easy solution that works both ways that would be great.

**Comment by markerikson** [comment]
Yeah.  If there's a relatively straightforward fix that works well in all environments, I'm on board.

**Comment by kevin940726** [comment]
Sure, we do want to preserve the default formatting and printing from the devtools right? For instance, logging an object like `{ a: 1 }` should not log `[object Object]` or JSON.stringify it, but should log an expandable object in the devtool.

String substitutions handles it nicely, but if we cannot use that, and we cannot just use a function to return a string either (as it obviously won't be formatted). We'll have to split the message into multiple parts and concat them together into a single `console.error` call.

I can try to do that, just to make sure we're on the same page 😉

**Comment by markerikson** [comment]
Right, we'd want to preserve as much loggable information as possible.

**Comment by RichiCoder1** [comment]
It's worth mentioned that the aforementioned `invariant` is supported again with the new TSDX setup: https://github.com/jaredpalmer/tsdx#invariant (If you'd like to support dropping messages in prod behavior).

I could send a PR that just re-implements that again and just uses good old fashion template strings & stringify using [tiny-invariant](https://www.npmjs.com/package/tiny-invariant)

**Comment by markerikson** [comment]
That'd be a possibility, although I'd prefer to inline the function rather than adding a separate dependency if it's something that gets pulled in at runtime.

**Comment by RichiCoder1** [comment]
The actual functionality is definetly nothing crazy: https://github.com/alexreardon/tiny-invariant/blob/master/src/index.js

Could easily be ported into a utils.

**Comment by kevin940726** [comment]
The case for `invariant` and `tiny-invariant` is that they don’t support logging rich content mentioned above. We can see in the source that they simply perform replacing strings or using template literals. However, in redux toolkit, we want to log non-serializable `value` which often means it cannot be transformed to strings (or will lose context by doing so). We could change the logging message though, but that’s out of this scope :thinking:
