### ISSUE TITLE
`UseQueryStateDefaultResult` not exported from the package

### ISSUE THREAD

**Issue by Lukas-Kullmann** [reduxjs/redux-toolkit#2540]
Hey there, 

in my application, I want to wrap the default `useQuery` hook with some custom functionality so that I can use this functionality in my whole application.
It should look something like this

```typescript
import type { QueryDefinition } from '@reduxjs/toolkit/dist/query/endpointDefinitions';
import type { UseQueryState } from '@reduxjs/toolkit/dist/query/react/buildHooks';

const wrapUseQuery = <TQuery extends UseQueryState<QueryDefinition<any, any, any, any>>>(useQuery: TQuery): TQuery => {
  return (parameter, options) => {
    const queryResult = useQuery(parameter, options);

    // do some other stuff that involves other hooks like `useState` and `useEffect`

    return queryResultEnhanced;
  }
}
```

The thing is that `useQuery` itself is generic (because of the `selectFromResult` option). I want to keep that logic. Hence my inner signature needs to look something like this:

```typescript
  return <TResult extends Record<string, any> = UseQueryStateDefaultResult<D>>(parameter, options) => {
    // ...
  }
```

**but** `UseQueryStateDefaultResult` is not exposed by RTK query (see https://github.com/reduxjs/redux-toolkit/blob/v1.8.3/packages/toolkit/src/query/react/buildHooks.ts#L371 - there is no `export` for the type).

Since this is a very complex type, I would rather import it from the library that duplicate it into my code base.
Is there a reason why this type is not exposed to the public?

**Comment by phryneas** [comment]
Mostly because every exported type is set in stone forever and we cannot refactor it afterwards - so we're very careful about what we actually export.
I just merged https://github.com/reduxjs/redux-toolkit/pull/2276 into the 1.9 integration branch - would those already help you for your use case?

**Comment by Lukas-Kullmann** [comment]
Yeah, that might help, thank you! 🙂
