### ISSUE TITLE
how to write endpoints from emtpyApi for pass transformResponse or for add custom fn

### ISSUE THREAD

**Issue by fatoldsun00** [reduxjs/redux-toolkit#2551]
Hi,

I try to generate endpoints from a openapi file, all is good but all my endpoint forward a x-total variable in the headers. I want retrieve this with a transformResponse(): 
``` transformResponse: (apiResponse, meta) => ({ apiResponse, total: Number(meta.response.headers.get('x-total')) }),```

Buthow pass this fn in the emptyApi.ts file used by generator ?

My emptyfile.ts looks like

```export const emptySplitApi = createApi({
  baseQuery: fetchBaseQuery({
    baseUrl: Config.TOWER_URL + '/',
    prepareHeaders: (headers, { getState }) => {

      const token = (getState() as RootState).login.token;
      if (token) {
        headers.set('authorization', `Bearer ${token}`);
      }
      return headers;
    },
  }),


  endpoints: (build) => {
    return build.query({
      transformResponse: (apiResponse, meta) => ({ apiResponse, total: Number(meta.response.headers.get('x-total')) }),
    });
  },
});```

Anybody can help me ?

Thank

**Comment by fatoldsun00** [comment]
Ok, i understand that i need t use enhanceEndpoints on my emptyApi.ts file export. But what it's the way to add transformResponse for all request ?

Thanks

**Comment by phryneas** [comment]
You could wrap your `baseQuery` in a custom function that modifies the result.

**Comment by fatoldsun00** [comment]
Hey, i find and other PR where ou advice this. I try this way with in createApi

```
baseQuery(...args) {
    const result = bq(...args);
    if (result?.data) {
      return { ...result, data: result.data.response, total: Number(result.meta?.response?.headers?.get('x-total')) };
    }
    return result;
  },
```
where bq it's 

```
const bq = fetchBaseQuery({
  baseUrl: Config.URL + '/',
  prepareHeaders: (headers, { getState }) => {
    const token = (getState() as RootState).login.token;
    if (token) {
      headers.set('authorization', `Bearer ${token}`);
    }
    return headers;
  },
```

but bq(...args) return either promise or data (if data is caching i purpose) so if(result?.data) doesn't exist yet on promise

If i async / await baseQuery() it's throw an error since baseQuery must return  {data: YourData}

any advice ?

Thanks for your answer by the way

**Comment by phryneas** [comment]
`baseQuery` can also return a `Promise<{data: YourData }>`, that should not throw any error.

**Comment by fatoldsun00** [comment]
you right, it's ok, i can return {data: {result:result.data, total : result.meta.header...} }, but result it's not really what i wish.

I wish add a total key on useGetCommentsQuery response like

```const { data, total } = useGetCommentsQuery({```

where total fill with repsonse.header

There are a way to do this ? :$

Thank

**Comment by phryneas** [comment]
You can never add anything outside of `data`, you'd have to add it inside of that.

**Comment by fatoldsun00** [comment]
ok, thank for your time
