### ISSUE TITLE
Unknown property in API response when mocking with Mock Service Worker

### ISSUE THREAD

**Issue by anthkris** [reduxjs/redux-toolkit#2552]
Hello, I wasn't sure where else to ask this question but I'm asking here instead of on MSW because RTK Query is what is throwing the error.

I am using RTK Query for some APIs built by my team. In a test, I am using MSW to mock the API response. This particular API has to call another API internally for authentication. I am also mocking the response of that internal API call. The test is passing and the mock appears to be working appropriately, but I receive the following error in the console:
```
Error encountered handling the endpoint ENDPOINT.
The object returned by baseQuery has the unknown property status.
It needs to return an object with either the shape { data: <value> } or { error: <value> } that may contain an optional meta property.
Object returned was: {
data: [dataArray],
status: 200,
statusText: 'OK',
headers: { 'x-powered-by': 'msw' },
...etc
}

at console.error (node_modules/@testing-library/react/dist/act-compat.js:55:34)
  at node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:327:19
  at step (node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:23:23)
  at Object.next (node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:4:53)
  at fulfilled (node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:95:32)
```

The mock implementation looks like this:
```
// Mock API responses
// Based on https://github.com/reduxjs/redux-toolkit/blob/master/examples/query/react/basic/src/test/server/serverHandlers.ts

import { rest } from "msw";

import {
  MockData
} from "../../src/static-data/test-data";

const handlers = [
rest.get("AUTHENTICATION_API", (*req*, *res*, *ctx*) *=>* {
// Mock token response for APIs

const mockApiResponse = "MockResponseWithToken";

return res(
ctx.body(mockApiResponse)
);

}),

rest.get("ENDPOINT", (*req*, *res*, *ctx*) *=>* {

const mockApiResponse = MockData;

return res(
ctx.json(mockApiResponse)
);
})
]

export { handlers };
```

I hypothesize that, because the ENPOINT mock has to call the AUTHENTICATION_API mock, that the two responses are being smushed together, but I don't know how to somehow clean the ENDPOINT response so that it only includes that data property.

Is there any way to return a clean response object or otherwise get rid of this error?

**Comment by phryneas** [comment]
It seems like that endpoint either uses a curom `baseQuery` or `queryFn`. Please show that.

**Comment by anthkris** [comment]
Thanks @phryneas You're right it does. I managed to fix the error by explicitly defining a custom base query like this:
```
const customActualsBaseQuery = (): BaseQueryFn => async (
  queryString
) => {
  try {
    const result = await CPTAxiosInstance({ url: queryString });
    return { data: result.data };
  } catch (axiosError) {
    const err = axiosError as AxiosError;
    return { error: { status: err.response?.status, data: err.response?.data } }
  }
}
```

One issue I'm running into is that error is of type unknown so I can't use the response message anywhere. Do you have any tips on defining the type for error?

**Comment by phryneas** [comment]
@anthkris generally: errors are just `unknown` unless you know better. They come from outside of your types, that could be anything. I'd write a type guard function and use that to find out what error you actually have.

**Comment by anthkris** [comment]
Thanks! Closing this.
