### ISSUE TITLE
Manually invalidateTags from anywhere or expose store context to invalidateTags()

### ISSUE THREAD

**Issue by AlexeiDarmin** [reduxjs/redux-toolkit#2556]
Hello, my primary problem is that I need the derive the invalidation tags not just from the response of the API request but also from some data within the redux store. I feel like it may be nice to have `getState()` available for the `invalidatesTags` function. 

- Is there a way to get the redux store from within `invalidateTags`? 
- Is there a way to trigger `invalidateTags()` from within `onQueryStarted` _(which supports a `getState` function to enable my use case)_

My use case:
- Get users by page (1, 2, 3, etc.)
- Delete a user from page 2
- Should invalidate the ordering of the users for page 2 and beyond.

I'm deriving tags by page, so `{ type: 'UsersPage', id: 1}` where `id` is the page number. If any user gets deleted from a page, that page and all subsequent pages should be invalidated. 

My workaround for now can be to pass the necessary state as an `arg` to the mutation request, such as the `maxPageCount`. After the request completes I'll be able to derive all the tags I need. This feels roundabout and introduces the possibility of accessing stale store state _(by relying on the value passed at the time of request-initialization)_.

**Comment by phryneas** [comment]
You can always `dispatch(api.utils.invalidateTags` from `onQueryStarted`.

**Comment by AlexeiDarmin** [comment]
That works, thank you! I didn't realize from the docs that `invalidateTags` could be dispatched manually, that's cool!
