### ISSUE TITLE
Refetch without parameters

### ISSUE THREAD

**Issue by YuriyDyachkov** [reduxjs/redux-toolkit#2558]
Hello, I have a paginated table in my application that is controlled on the backend. The table can be downloaded in xlsx format. Before downloading, I want to do a refetch without parameters. Since I need the complete table. Can I do it somehow?

```
const { data, refetch } = useGetTableQuery({
    page: pageNumber,
    pageSize: pageSizeNumber,
    sorting,
    tab,
  });

  
refetch(?)
```

**Comment by spacepolice10** [comment]
Hi. Can't you just store the whole set of args as a local state like 

```
const [args, setArgs] = useState({
      page: pageNumber,
      pageSize: pageSizeNumber,
      sorting,
      tab,
})

const {data} = useGetTableQuery(args)

```

and then when you want to refetch data you can just pass default args to state and rtk query hook will automatically trigger refetching. Hope it helps
