### ISSUE TITLE
Getting navigation context for routing 

### ISSUE THREAD

**Issue by jacksonHendric** [reduxjs/redux-toolkit#2560]
Hi,
I need a way to use a hook to get a navigation context. If the request returns a 401, I have an extended fetchBaseQuery function to navigate to a different screen (react native).

The issue is that you can't use hooks inside these functions. 

Is there another way to handle automatic 401 routing or how do I get the navigation context to navigate?

```
const baseQuery = fetchBaseQuery({
  baseUrl: appConfig.apiBase,
  prepareHeaders: async (headers) => {
    const user = await AsyncStorageService.getStoredData('auth')
    const hasUser = !!user && !!user!.access_token

    if (hasUser) {
      headers.set('Authorization', `Bearer ${user.access_token}`)
    }

    headers.set('Content-Type', 'application/json')

    return headers
  }
})
```

```
const baseQueryWithReauth: BaseQueryFn<
  string | FetchArgs,
  unknown,
  FetchBaseQueryError
> = async (args, api, extraOptions) => {
 
//TRYING TO DO: const navigation = useNavigation()   <<<<---------- Here 

  let result = await baseQuery(args, api, extraOptions)
  if (result.error && result.error.status === 401) {
    console.log(result.error)
  }
  return result
}
```

**Comment by phryneas** [comment]
Depending on what you are using, you can probably import a `history` from another file. but this is really completely out of the scope of this library or repository.
