### ISSUE TITLE
Decorate URL with query string

### ISSUE THREAD

**Issue by PavelA85** [reduxjs/redux-toolkit#2562]
I am using the `graphql-codegen` yarn package to generate React hooks `graphql-codegen --config codegen.yml`

I want to decorate every GraphQL endpoint call with an operation name, so I can see the operation name in the DevTools console:
![image](https://user-images.githubusercontent.com/2944514/182580991-04c39f13-688d-4160-a1ec-5e1012ff28f3.png)

My baseApi.ts looks like this:
```
import { createApi, retry } from '@reduxjs/toolkit/query/react';
import { graphqlRequestBaseQuery } from '@rtk-query/graphql-request-base-query';
import { Cookies } from 'react-cookie';
import { GraphQLClient } from 'graphql-request';

const client = new GraphQLClient(
  `${process.env.REACT_APP_API_URL}/api/graphql`
);
const cookies = new Cookies();
const token = cookies.get('.AspNetCore.Application.Id');
client.setHeader('authorization', `Bearer ${token}`);
client.setHeader('Content-Type', 'application/json');
client.setHeader('X-Requested-With', 'XMLHttpRequest');

export default client;

const staggeredBaseQuery = retry(graphqlRequestBaseQuery({ client }), {
  maxRetries: 2,
});

export const api = createApi({
  baseQuery: staggeredBaseQuery,
  endpoints: () => ({}),
  keepUnusedDataFor: 5,
  refetchOnMountOrArgChange: false,
});
```

My generated hook looks like this:
```
import * as Types from '../graphqlTypes';

import { api } from 'graphql/baseApi';
export type SetPreferenceMutationVariables = Types.Exact<{
  name: Types.Scalars['String'];
  value: Types.Scalars['String'];
}>;

export type SetPreferenceMutation = {
  __typename?: 'Mutation';
  setPreference?: boolean | null | undefined;
};

export const SetPreferenceDocument = `
    mutation setPreference($name: String!, $value: String!) {
  setPreference(name: $name, value: $value)
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    setPreference: build.mutation<
      SetPreferenceMutation,
      SetPreferenceMutationVariables
    >({
      query: (variables) => ({ document: SetPreferenceDocument, variables }),
    }),
  }),
});

export { injectedRtkApi as api };
export const { useSetPreferenceMutation } = injectedRtkApi;
```
I found this code: [graphql-code-generator/packages/plugins/typescript/rtk-query/src/visitor.ts ](https://github.com/dotansimha/graphql-code-generator/blob/e5b76273356acb93ed5497575a6e45b8ca494afa/packages/plugins/typescript/rtk-query/src/visitor.ts#L96) that generates hooks for me, but I can not find an option to update URL from this hook.
I expect to add URL option here: ` query: (variables) => ({ document: SetPreferenceDocument, variables, url: '????' }),` but could not figure out how to do it :(
I found this [Defining Query Endpoints](https://redux-toolkit.js.org/rtk-query/usage/queries#defining-query-endpoints:~:text=%7B%20url%3A-,%60post/%24%7Bid%7D%60,-%7D)%2C) but was unable to make it work.

**Comment by PavelA85** [comment]
any help would be greatly appreciated

**Comment by phryneas** [comment]
Hmm..

At that point, you could probably just do something like
```js
    ${operationName}: build.query<${Generics}>({
      query: (variables) => ({ document: ${documentVariableName}, variables, param: '${operationName}' })
    }),`);
```

to change the generated code.

The problem is that it won't "go through", due to this code:
https://github.com/reduxjs/redux-toolkit/blob/94d93d969f01ca6248ff481f0c154b43c6e903d3/packages/rtk-query-graphql-request-base-query/src/index.ts#L42-L48

You could do something like 
```js
    ${operationName}: build.query<${Generics}>({
      query: (variables) => {
        client.setEndpoint('someNewUrl')
        return ({ document: ${documentVariableName}, variables })
      }
    }),`);
```

or you copy&paste the graphqlbasequery in your code base and adjust the code to accept some additional `param` argument.

**Comment by jimitshah-dp** [comment]
I also had the same requirement, where in i would like to append operationName at end of /graphql for better devX and logging purpose.
From the thread i read, my understanding is, i need to have my version of graphqlbasequery and add this [code](https://github.com/reduxjs/redux-toolkit/issues/2562#:~:text=%24%7BoperationName%7D%3A%20build.query%3C%24%7BGenerics%7D%3E(%7B%0A%20%20%20%20%20%20query%3A%20(variables)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20client.setEndpoint(%27someNewUrl%27)%0A%20%20%20%20%20%20%20%20return%20(%7B%20document%3A%20%24%7BdocumentVariableName%7D%2C%20variables%20%7D)%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D)%2C%60)%3B).

Would be nice if we can make this configurable in rtk-query-graphql-request-base-query itself.

@PavelA85 How did you manage to achieve it?

Thanks

**Comment by PavelA85** [comment]
If I remember right we updated the latest version and it was already providing an operation name as query string out of the box.

**Comment by PavelA85** [comment]
```
import { createApi, retry } from '@reduxjs/toolkit/query/react';
import { Cookies } from 'react-cookie';
import { GraphQLClient } from 'graphql-request';
import { graphqlRequestBaseQuery } from './graphql-request-base-query';

const API_URL = `${process.env.REACT_APP_API_URL}/api/graphql`;

const middleware = <T extends RequestInit>(request: T) => {
  if (typeof request?.body === 'string') {
    const operationName = JSON.parse(request?.body).operationName;
    return {
      ...request,
      url: `${API_URL}?${operationName}`,
    };
  }
  return request;
};

const client = new GraphQLClient(
  API_URL,

  { requestMiddleware: middleware }
);
```

Here is our code.

**Comment by jimitshah-dp** [comment]
Thanks for the reference.
I achieved the same using below code
` const client = new GraphQLClient(options.url, {
    requestMiddleware: (request) => {
      // Middleware to add the operation name to the URL
      return {
        ...request,
        url: `${request.url}/${request.operationName}`,
      };
    },
  });`
