### ISSUE TITLE
How to add generic on payloadCreator function of createAsyncThunk?

### ISSUE THREAD

**Issue by Emiya0306** [reduxjs/redux-toolkit#2566]
Just like the picture, I would like to write login async function. The **connection** variable type is dynamic and return different response. So I would like to add **generic** on **payloadCreator**. But I failed in it, plz help.
<img width="868" alt="image" src="https://user-images.githubusercontent.com/12878132/182792707-6f54a531-b7bc-4d6e-9137-b8271102a626.png">

```
No overload matches this call.
  Overload 1 of 2, '(typePrefix: string, payloadCreator: AsyncThunkPayloadCreator<void, void, {}>, options?: AsyncThunkOptions<void, {}> | undefined): AsyncThunk<...>', gave the following error.
    Argument of type '<C extends AvaliableConnection>(connection: C) => Promise<void>' is not assignable to parameter of type 'AsyncThunkPayloadCreator<void, void, {}>'.
      Types of parameters 'connection' and 'arg' are incompatible.
        Type 'void' is not assignable to type 'AvaliableConnection'.
  Overload 2 of 2, '(typePrefix: string, payloadCreator: AsyncThunkPayloadCreator<void, unknown, AsyncThunkConfig>, options?: AsyncThunkOptions<unknown, AsyncThunkConfig> | undefined): AsyncThunk<...>', gave the following error.
    Argument of type '<C extends AvaliableConnection>(connection: C) => Promise<void>' is not assignable to parameter of type 'AsyncThunkPayloadCreator<void, unknown, AsyncThunkConfig>'.
      Types of parameters 'connection' and 'arg' are incompatible.
        Type 'unknown' is not assignable to type 'AvaliableConnection'.ts(2769)
```

**Comment by phryneas** [comment]
That function is mapped into another function. TypeScript cannot do that with generics - so due to restrictions in the type system of TypeScript, you cannot really use generic functions there. You'd have to live with `(connection: AvailableConnection)` there.

**Comment by Emiya0306** [comment]
@phryneas OK, I write multiple login functions to workaround this finally, just like `loginSYS1`, `loginSYS2`.
But if the `createAsyncThunk` support generic, please let me know. That will be very useful to call function in business more gracefully, like the code below: 😄 

```typescript
const dispatch = useAppDispatch();

// connection1 is SYS1 type, response1 is SYS1 type
const response1 = dispatch(actions.login(connection1))

// connection2 is SYS2 type, response2 is SYS2 type
const response2 = dispatch(actions.login(connection2))
```

**Comment by phryneas** [comment]
Unfortunately, unless TypeScript adds completely new features for that it will not happen - I'm sorry.
