### ISSUE TITLE
Cannot read properties of undefined (reading 'rtkQuery')

### ISSUE THREAD

**Issue by VictorPulzz** [reduxjs/redux-toolkit#2567]
Hello, I got this strange error: `Cannot read properties of undefined (reading 'rtkQuery')`
I have a project where the structure is like this:
```
...
rtk ----
    - modules
          - endpoints.ts
    - rtkQuery.ts
    - index.ts
```
And I want to make beautiful imports
so that both rtkQuery and individual modules with rtkQuery.injectEndpoints are imported in the index.ts file at the folder level
### endpoints.ts:
```ts
import { LoginRequest, LoginResponse, rtkQuery } from '~/services/rtk';

const authRtk = rtkQuery.injectEndpoints({
  endpoints: builder => ({
    login: builder.mutation<LoginResponse, LoginRequest>({
      query: data => ({
        url: '/token/',
        method: 'POST',
        data,
      }),
    }),
  }),
});

export { authRtk };
export const { useLoginMutation } = authRtk;
```
###  rtkQuery.ts:
```ts
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

import { cacher } from '~/services/rtk/utils';

export const rtkQuery = createApi({
  reducerPath: 'rtkReducer',
  baseQuery: fetchBaseQuery({ baseUrl: 'a' }),
  tagTypes: Object.values(cacher.tags),
  endpoints: () => ({}),
});
```

###  index.ts:
```ts
export { authRtk, useLoginMutation } from './modules/endpoints';
export { LoginRequest, LoginResponse } from './modules/types';
export { rtkQuery } from './rtkQuery';
```

And if I do that I get this error:
<img width="195" alt="image" src="https://user-images.githubusercontent.com/23406402/182960246-5fec9b64-581c-4811-8b3b-44fee0ffc6c2.png">

However, if I remove the authRtk import line from index.ts:
```ts
export { LoginRequest, LoginResponse } from './modules/types';
export { rtkQuery } from './rtkQuery';
```
Or I put the line export { rtkQuery } from './rtkQuery', work to
```ts
export { rtkQuery } from './rtkQuery';
export { LoginRequest, LoginResponse } from './modules/types';
export { rtkQuery } from './rtkQuery';
```

It's very stupid why the code does not work from the sequence of exports? If I put the line in the first place, eslint ordering (Run autofix to sort these exports!(simple-import-sort/exports)) starts to swear ..

I want to say that it works without problems on react-native!

**Comment by markerikson** [comment]
That looks to me like you've got a circular import problem, but I'd have to see the actual files to be sure.

**Comment by VictorPulzz** [comment]
@markerikson Hello!
here my files 
### services/rtk/modules/endpoints.ts:
```ts
import { LoginRequest, LoginResponse, rtkQuery } from '~/services/rtk';

const authRtk = rtkQuery.injectEndpoints({
  endpoints: builder => ({
    login: builder.mutation<LoginResponse, LoginRequest>({
      query: data => ({
        url: '/token/',
        method: 'POST',
        data,
      }),
    }),
  }),
});

export { authRtk };
export const { useLoginMutation } = authRtk;
```

### services/rtk/modules/types.ts:
```ts
export type LoginRequest = {
  email: string;
  password: string;
};
export type LoginResponse = {
  access: string;
  refresh: string;
};
```

### services/rtk/index.ts:
```ts
export { authRtk, useLoginMutation } from './modules/endpoints';
export { LoginRequest, LoginResponse } from './modules/types';
export { rtkQuery } from './rtkQuery';
```

**Comment by VictorPulzz** [comment]
Also I try to setup clear project and got this error:  `Cannot access 'rtkQuery' before initialization`
Wtf?? This link https://github.com/VictorPulzz/test

**Comment by markerikson** [comment]
Yeah, I'm about 99% sure you've got a circular import problem.  I can't trace the path all the way right now, but you're going back and forth between the store, the reducers, and the slice files, and that looks like it's resulting in a cycle.  You'll need to rearrange those files and imports somehow to avoid this.

Btw, as a side note, _please_ don't do this:

```ts
const coreReducer: Reducer = (state: RootState, action: AnyAction) => {
	return combinedReducer(state, action);
};
```

Not only is it useless and unnecessary, you're also throwing away the types.  The `combinedReducer` _is_ your root reducer, and you don't need to wrap it in another.

**Comment by VictorPulzz** [comment]
@markerikson Okay I will check this, about this code, I just cut include, in coreReducer I handle logout user, yep I need change this, thanks!
