### ISSUE TITLE
RTK Query docs general tag example confusion

### ISSUE THREAD

**Issue by Iftakharpy** [reduxjs/redux-toolkit#2570]
I have been reading the RTK Query invalidation behaviour I found an example under the [general tag](https://redux-toolkit.js.org/rtk-query/usage/automated-refetching#general-tag) confusing.

The particular example was  `[{ type: 'Post', id: 1 }, { type: 'User' }]`
The statement was If a general tag of `Post` were invalidated, endpoints whose data provided the tags would all have their data invalidated.

My question is `{ type: 'User' }` tag is not a type of `Post` tag will this make re-fetch all data for the `User` tag too or ignore the `{ type: 'User' }` and just re-fetch the specific tag `{ type: 'Post', id: 1 }`  only? Or is this a typo in docs perhaps?

**Comment by phryneas** [comment]
If one of the invalidate tags is contained in one of the provided tags of a cache entry, it will invalidate/refetch.

**Comment by Iftakharpy** [comment]
Thanks for your reply I understand it better now.
