### ISSUE TITLE
Poor types for createAsyncThunk

### ISSUE THREAD

**Issue by marcusjwhelan** [reduxjs/redux-toolkit#2577]
Currently attempting to type parts of createAsyncThunk to not have repeated code within the action.

Currently there are many issues open with attempting to extend the function or wrap it. I have seen some good examples but no solid way to type the thunk api that is passed into the createAsyncThunk. 

My current issue is that I am unable to even type the function `rejectWithValue` since the type `RejectWithValue` type isn't exported I am unable to type a custom function to take that type of a function. Let alone trying to type the thunkApi parameter itself which has many many unexported types that make it up. 

Please export the types

**Comment by markerikson** [comment]
Sorry, I'm afraid I'm not sure what you're asking.

Can you give a specific example of what you're trying to do, with code?

Which internal types are you asking for us to export?

**Comment by phryneas** [comment]
That would probably not really help you, while at the same time encouraging usage of these types in scenarios where people could very easily use them to shoot themselves into their foot.

If you are in a "not-yet-resolved-generic" situation, your "generic types" are unresolved to an extent that they are essentially `never`, no matter where you want to put them into - most types transforming on that will not work.

It might be more practical in your own code base to just accept a function with a custom signature as a "rejectWithValue" replacement and do a `as any` type assertion at some specific point. Due to the "not-yet-resolved-generic" situation, your types there are over-and-underspecific at the same time anyways, so this will at least highlight a dangerous type-unsafe situation instead of hiding it.

Of course, nothing stops you to use something like `yarn patch` to just export these types yourself - and if you can come up with patterns that really make up a significant win in those situations, we'd like to add those to the docs and then also export the types that are relevant for that. But we won't randomly start exporting all of these types. They are a footgun and there is a reason why they are not exported.

**Comment by marcusjwhelan** [comment]
As an aside, I would not assign yourselves responsible as the library maintainers for incorrect use of the library.

**Comment by markerikson** [comment]
Could you give an example of what code you would _like_ to write?  Pretend that all the pieces you're asking for are available - what would the final app code look like in your case?

**Comment by phryneas** [comment]
Probably you want to write something like
```js

function handleError<R>(thunkApi: { rejectWithValue(value: string) => R  }): R {
  return (error) => thunkApi.rejectWithValue(error.message)
}

  return axiosInstance.request(config)
    .then((res: AxiosResponse<IPokemonList>) => {
      return res.data
    })
    .catch(handleError(thunkApi))
```

You don't need all the properties of `thunkApi` typed correctly for that. For your function, all that matters is that it receives an object with a `rejectWithValue` function on it that accepts a string, and that your function will return whatever that `rejectWithValue` returns.

**Comment by marcusjwhelan** [comment]
@phryneas  This is a good example. I was able to get this to work properly and it typed correctly on the return as well which is great. 

You can close this. I think though an example like this on the docs would be a good resource.

**Comment by markerikson** [comment]
Sure - could you try filing a PR to update the docs with the info you'd like to see added?

**Comment by marcusjwhelan** [comment]
@markerikson I am unable to make a branch/pr but here are the changes I wanted to createAsyncThunk
### Using Promise style syntax inside `createAsyncThunk`
Below is an example of the `createAsynceThunk` function in a promise version

```ts
interface MyResponseModel {
  // ...
}
const getUser = createAsyncThunk<
  // Return type of payload creator
  MyResponseModel,
  number
>('users/get',
(id, thunkApi) => {
  const fetchOptions: RequestInit = {
    method: 'GET',
    signal: thunkApi.signal
  }
  return fetch(`https://reqres.in/api/users/${id}`, fetchOptions)
    .then((res: Response) => {
      if (!res.ok) {
        // or any reject string
        return thunkApi.rejectWithValue(response.statusText)
      }
      return response.json() as MyResponseModel
    })
    .catch((err) => thunkApi.rejectWithValue(err.message))
})
```
This can be helpful when dealing with 3rd party libraries which 
have their own types for errors such as `axios`.
```ts
interface MyApiResponse {
  // ...
}
const getUser = createAsyncThunk<
  // Return type of payload creator
  MyApiResponse,
  number
>('users/get',
(id, thunkApi) => {
  const fetchOptions: AxiosRequestConfig = {
    method: 'GET',
    url: `https://reqres.in/api/users/${id}`,
    signal: thunkApi.signal
  }
  return axios.request(config)
    .then((res: AxiosResponse<MyApiResponse>) => res.data)
    .catch((err: AxiosError) => {
      if (err.response && err.response.data) {
        return err.response.data
      }
      return thunkApi.rejectWithValue(err.message)
    })
})
```
### Spreading functionality of common tasks within `createAsyncThunk`
In some cases it can be useful to breakout common tasks within `createAsyncThunk` to reduce duplication of code
within your async actions.

In the example below the usage of request call is broken out since the code can be made generic.
```ts
function genericRequest<T, R>(config: AxiosRequestConfig, thunkApi: {rejectWithValue: (value: string) => R}) {
  return axios.request(config)
    .then((res: AxiosResponse<T>) => res.data)
    .catch((err: AxiosError) => {
      if (err.response && err.response.data) {
        return err.response.data
      }
      return thunkApi.rejectWithValue(err.message)
    })
}

const getUser = createAsyncThunk<
  // Return type of payload creator
  MyApiResponse,
  number
>('users/get',
(id, thunkApi) => {
  const fetchOptions: AxiosRequestConfig = {
    method: 'GET',
    url: `https://reqres.in/api/users/${id}`,
    signal: thunkApi.signal
  }
  return genericRequest(fetchOptions, thunkApi)
})
```
