### ISSUE TITLE
loader error with typescript + rtk query + graphql

### ISSUE THREAD

**Issue by alilahrime** [reduxjs/redux-toolkit#2578]
projectCasesByGeneSlice.js:
<img width="710" alt="Screen Shot 2022-08-10 at 10 38 21 AM" src="https://user-images.githubusercontent.com/90918464/183930188-f9b0c9e3-1061-4f0f-ac7b-c479ceb4bc69.png">
constants.ts:
<img width="681" alt="Screen Shot 2022-08-10 at 10 38 32 AM" src="https://user-images.githubusercontent.com/90918464/183930364-9981e211-80f5-4780-80ef-d923648cbf42.png">
tsconfig.json:
<img width="610" alt="Screen Shot 2022-08-10 at 10 39 08 AM" src="https://user-images.githubusercontent.com/90918464/183930520-2a28b00f-acd9-4491-a933-c19135a8125f.png">
next.config.js:
<img width="630" alt="Screen Shot 2022-08-10 at 10 39 27 AM" src="https://user-images.githubusercontent.com/90918464/183930646-0b10b14b-1376-4eaa-a726-089a9b1ee44f.png">

Here is the error that only shows when lines 13-28 of projectCasesByGeneSlice.ts are uncommented.
<img width="719" alt="graphQLAndRTKQuestion" src="https://user-images.githubusercontent.com/90918464/183929196-51333f67-b6d8-424f-b691-fd09ef6aa0ea.png">

Thank you for your time to take a look, any guidance/support is greatly appreciated. I enjoy these technologies and they're great on their own, but I think it could be very clean solution to combine them this way. I'm just not sure if its totally necessary to setup webpack or maybe add some configs to the existing rollup. any thoughts/suggestions please

**Comment by markerikson** [comment]
The main problem is that you have TS generic syntax in a `projectCasesByGeneSlice.js` file, which is a plain JS file. That's not valid JS syntax.  If your app is only set up to use JS, you have to remove all TS syntax. Otherwise, it needs to be a `.ts` file.

(Also, I'm not sure why you're trying to run the RTK libraries through `next-transpile-modules` - that shouldn't be necessary.)

**Comment by alilahrime** [comment]
> Hmm. Actually now I'm confused - the comment body says it's a `.js` file, but the error message says it's a `.ts` file.

yeah sorry, you're right. i edited the typo, the error message shows the right file format (projectCasesByGeneSlice.ts)

**Comment by markerikson** [comment]
It does still sound like this is a build setup / compilation issue.  Somehow your build setup doesn't seem to recognize this as a TS file, and so it's confused when it's seeing TS syntax.

This unfortunately isn't anything we can help with - it's not a bug in the library, it's a problem specific to your own project's build setup.

**Comment by alilahrime** [comment]
Thank you, this was helpful to narrow scope of what might be wrong. I'll look into build/compilation configurations instead.
