### ISSUE TITLE
fetchBaseQuery from query/react not defined in production

### ISSUE THREAD

**Issue by fedemp** [reduxjs/redux-toolkit#2584]
I used to have this code while developing my app.

```js
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
```

but today, when I finally tried a production build, I had to replace it with

```js
import { fetchBaseQuery } from "@reduxjs/toolkit/query";
import { createApi } from "@reduxjs/toolkit/query/react";
```

Is this an expected behavior? I'm using latest version redux-toolkit (1.8.4), TS 4.7.4 and Parcel 2.7.0.

**Comment by markerikson** [comment]
The second code will work, but you _should_ be able to import both of those from `/react`.

Can you put together a standalone project that reproduces this issue?

**Comment by fedemp** [comment]
https://github.com/fedemp/rt-fetchbasequery

As my original project, this uses Parcel and TS.

Running `npm start` will build the project in development mode and start a (Parcel) server at `localhost:1234`. You should see `fetchBaseQuery` and `createApi` logged in the console.

Then try with `npm run build` to build a production bundle and `npm run serve` to load a server that serves said bundle. Check again your console. `fetchBaseQuery` is `undefined`.

**Comment by markerikson** [comment]
Gotcha. Unfortunately, I've got a lot of other stuff on my todo list atm, and this is probably pretty low priority, so I don't know when I'll have time to investigate.

It might be a good idea to also file an issue with Parcel as well - at first glance, this _sounds_ like a bundler-specific issue, rather than an issue with the library itself.

**Comment by fedemp** [comment]
It sure does sound like a Parcel issue. Thanks for the heads up.

**Comment by markerikson** [comment]
I'm going to go ahead and close this for now. If the Parcel folks come back and say "it's something about the library package setup", go ahead and comment here and we can re-open this.
