### ISSUE TITLE
Change builder.mutation(...) to builder.query(...) and get TypeError

### ISSUE THREAD

**Issue by nlfiedler** [reduxjs/redux-toolkit#2585]
Starting from the `authentication-with-extrareducers` example in codesandbox.io change the `protected` endpoint from a `mutation` to a `query` and fix the name in the `export const` of `auth.ts`, and then fix the `import` and invocation in `ProtectedComponent.tsx` and you will get a TypeError:

```
Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
```

Why? I have poured over the docs for over an hour, switching back and forth from `mutation` to `query` and cannot understand why this is happening. Are the docs incorrect or is there a bug in the library, or am I missing something else?

**Comment by markerikson** [comment]
Sorry, I'm having trouble following what you're describing. Could you post a sandbox with the actual changes?

**Comment by nlfiedler** [comment]
Change the "protected" endpoint from a `mutation` to a `query`, which seems like it should work.

Here's the link: https://codesandbox.io/s/elated-joana-n15w85?file=/src/features/auth/ProtectedComponent.tsx

I'm getting a different error than when I just modify the original sandbox, not sure why. In fact, attempting to modify the original sandbox in an identical fashion is yielding yet another set of errors. I no longer trust the sandbox, so I'm going to make a repo and share that.

**Comment by phryneas** [comment]
You are likely to use the `query` hook in a `const [trigger, result] = useQuery()` fashion now, but a query hook is used `const result = useQuery(args)` fashion.

Generally: please don't do this. There is a reason that we have this in the docs as a mutation. This is not something that should stay in cache for longer than the component is mounted.

**Comment by nlfiedler** [comment]
"There is a reason that we have this in the docs as a mutation." Where in the docs does it say that query is to be avoided? In any case, this is the `protected` endpoint, not the username/password route that retrieves a token. I agree that should remain a POST/mutation, but the other route (in my app) is not a POST or a mutation, it is simply making a GET request. I believe I am following the docs and yet it is not working at all.

**Comment by markerikson** [comment]
@nlfiedler : literally, the problem here is that **query hooks and mutation hooks return _different kinds of return values_**.

A query hook returns **one single object** that looks like `{data, isFetching, etc}`.

A mutation hook returns **a 2-item tuple/array** that looks like `[triggerFunction, {data, etc}]`.

**You are trying to array-destructure an object, which is impossible :)**

That's the main problem. You're writing invalid code for using the query return value.

**Comment by nlfiedler** [comment]
Ah, thank you, that helps a lot. The webpack error that I originally saw was not helpful.
