### ISSUE TITLE
Reducer for pure client state in RTK Query slice?

### ISSUE THREAD

**Issue by TechSaq** [reduxjs/redux-toolkit#2586]
I have written a RTK Query slice for my REST APIs endpoints and for every endpoint I have defined a query which generates hooks and other things for each endpoint.

How can I write a reducer or manage pure client state (e.g. managing Modal State etc.) inside RTK Query slice?

Currently I am using  RTK slice to manage pure client side, not sure if this is the ideal way.

I need a better approach, any kind of help is appreciated.

Thanks

**Comment by phryneas** [comment]
RTK Query is just for library-managed api state. For your own state you will have to use a normal RTK slice as you are already doing.

**Comment by TechSaq** [comment]
Thanks, I thought I am missing something.
