### ISSUE TITLE
rtk-query: Invalidate tags on a mutation performs a refetch even if the mutation fails

### ISSUE THREAD

**Issue by sajitkhadka** [reduxjs/redux-toolkit#2588]
I am not sure if it is a bug or supposed to be like that, but I noticed even after the mutation failed the action did invalidate the cache and performed a refetch. It caused some unintended behaviour to my app.

**Comment by phryneas** [comment]
If you want different behaviour for success and error you can use the `invalidateTags` function notation and check if `result` or `error` are set and return an array of tags accordingly for your use case. If it's only an array, that will be used either way.

**Comment by sajitkhadka** [comment]
@phryneas Thank you for the quick reply. I wasn't aware it accepted a function as well. That's pretty clever. It seems a success response or undefined is passed through the function as below. It seems to work.
```
 invalidatesTags: (result) => {
          if (result) {
            return ["MyTag"];
          } else {
            return [];
          }
 },

```
