### ISSUE TITLE
Explanation of caseReducers & getInitialState in createSlice docs

### ISSUE THREAD

**Issue by NiedziolkaMichal** [reduxjs/redux-toolkit#2609]
[Documentation page of createSlice](https://redux-toolkit.js.org/api/createSlice) defined in [createSlice.mdx](https://github.com/reduxjs/redux-toolkit/blob/master/docs/api/createSlice.mdx) is missing explanation of properties caseReducers & getInitialState. While getInitialState() is self-explanatory, caseReducers is not and I had to check [createSlice.ts](https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/createSlice.ts#:~:text=caseReducers:%20SliceDefinedCaseReducers) documentation to make sure that I understand what exactly does it do.

**Comment by markerikson** [comment]
Could you file a PR to add a reasonable description to that page?
