### ISSUE TITLE
Add payload generic type variable in SliceCaseReducers type

### ISSUE THREAD

**Issue by rosczja** [reduxjs/redux-toolkit#2611]
Currently the type SliceCaseReducers only has one generic type variable for the state type and the action payload is always `any`. This leads to `createSlice` creating action creators which are not typesafe, because the payload is `any`.

Would it be possible to add a generic type variable to be able to specifiy the payload type?

**Comment by phryneas** [comment]
Could you please give an example on what you are trying to do? You should usually not have any need to ever use that type.

**Comment by rosczja** [comment]
I have for instance that simple slice:

```
const setRegionalConfiguration: CaseReducer<RegionalConfiguration, PayloadAction<RegionalConfiguration>> = (state, action) =>
    action.payload;

export const regionalConfiguration = createSlice<RegionalConfiguration, SliceCaseReducers<RegionalConfiguration>>({
    name: 'action',
    initialState: {
        dateFormat: 'MM/DD/YYYY',
        locale: 'en_GB',
    },
    reducers: { setRegionalConfiguration },
});
```

As you can see, the `setRegionalConfiguration`  action expects a payload of type `RegionalConfiguration`, as does the `initialState` of course.

If I want to create an action, I invoke `regionalConfiguration.actions.setRegionalConfiguration`. That creator should only accept payloads of type `RegionalConfiguration`, but the inferred type of the payload is `any`. So I could invoke the creator with an invalid payload such as `regionalConfiguration.actions.setRegionalConfiguration('Hello World')`, which would happily write `Hello World` into the store.

**Comment by phryneas** [comment]
You should **never** call `createSlice` with a generic argument - that **has** to be inferred!

Call it
```ts
export const regionalConfiguration = createSlice ({
    name: 'action',
    initialState: {
        dateFormat: 'MM/DD/YYYY',
        locale: 'en_GB',
    },
    reducers: { setRegionalConfiguration },
});

```

**Comment by rosczja** [comment]
Not inlining the reducer was not my idea, but suggested by the documentation to get a correctly typed payload.

If I remove the generic arguments, Typescript complaints that the `setRegionalConfiguration` reducer is not of the expected type.

**Comment by rosczja** [comment]
I have it working now:

```
const setRegionalConfiguration: CaseReducer<RegionalConfiguration, PayloadAction<RegionalConfiguration>> = (state, action) =>
    action.payload;

const initialState: RegionalConfiguration = {
    dateFormat: 'MM/DD/YYYY',
    timeFormat: TimeFormat.TwentyfourHour,
    decimalDelimiter: '.',
    locale: 'en_GB',
};

export const regionalConfiguration = createSlice({
    name: 'action',
    initialState,
    reducers: { setRegionalConfiguration },
});
```

The payload type of the action creator is correctly inferred. Maybe the documentation could be enhanced a bit to make it clear that the `initialState` needs to be explicitly typed. 

Thanks for the cool toolkit and pointing me in the right direction.

**Comment by phryneas** [comment]
What documentation are you following there...?

Correct, this would look like:

```ts
export const regionalConfiguration = createSlice({
    name: 'action',
    initialState: {
        dateFormat: 'MM/DD/YYYY',
        locale: 'en_GB',
    } as RegionalConfiguration,
    reducers: { 
      setRegionalConfiguration(state, action: PayloadAction<RegionalConfiguration>){
        return action.payload
      }
    },
});
```

**Comment by rosczja** [comment]
I am following the offical documentation: 

https://redux-toolkit.js.org/usage/usage-with-typescript#createslice

**Comment by phryneas** [comment]
> The payload type of the action creator is correctly inferred. Maybe the documentation could be enhanced a bit to make it clear that the initialState needs to be explicitly typed.

https://redux-toolkit.js.org/usage/usage-with-typescript#defining-the-initial-state-type ?

**Comment by rosczja** [comment]
Yes, sorry I somehow missed it and did not understand its importance. I am so used to generic type variables that I thought my problem could be solved with those.
