### ISSUE TITLE
createAction doesn't infer action.type type correctly when used with payload

### ISSUE THREAD

**Issue by Nodonisko** [reduxjs/redux-toolkit#2614]
Hi, this will be better explained in example:

```ts
const action1 = createAction<number>('myActionType1');
// action.type type is string
const action2 = createAction('myActionType2', (payload: number) => ({ payload }));
// action.type type is 'myActionType2'
```

I need always to have exact `action.type` value and not only generic `string` type. It could be achieved by using `prepare` as can see in `action2` but it's quite unpleasant do this only to get that type right. Is there any way how I can get right type from but using similar syntax as for `action1`?

Thanks!

**Comment by phryneas** [comment]
TS can either infer all generic arguments or none. So you either provide both in example 1 (`createAction<number, 'myActionType1'>`) or you infer both (with `prepare`) as in example 2.

That said, there is almost never any good reason to have the `action.type` be typed correctly. You should be using `action1.match(action)` if you want to narrow a type and not create action type unions anywhere in your application - we [consider that as unneccessary to the level of being an antipattern](https://phryneas.de/redux-typescript-no-discriminating-union)

**Comment by Nodonisko** [comment]
Thanks for explanation. Sadly we migrating big legacy codebase that heavily relies on correct action.type and we need to that by small chunks. I will go with that prepare workaround until everything will be migrated.

**Comment by markerikson** [comment]
@Nodonisko : The best answer here is to migrate an entire slice reducer at a time to `createSlice`, at which point you get all the action creators for free _and_ correctly typed.

**Comment by Nodonisko** [comment]
Sadly that's also impossible for us, lot of reducers is reacting to actions from other reducers and it will produce cyclic imports, so we need to keep action in extra file. Legacy codebase :(

**Comment by phryneas** [comment]
Update RTK to the latest version, even if those exports are cyclic that shouldn't matter as they are not evaluated at execution time in recent versions.
