### ISSUE TITLE
Incorrect type of query in endpoint definition when baseQuery has generics

### ISSUE THREAD

**Issue by Grapedge** [reduxjs/redux-toolkit#2616]
I have a baseQuery with generic T:

```typescript
type MyBaseQueryFn = BaseQueryFn<{ url: string }>;

const myBaseQuery = <T = any>(): MyBaseQueryFn => {
  return () => ({ data: {} } as any);
};
```

When I call `myBaseQueryFn` inline, 
```typescript
createApi({
  baseQuery: myBaseQuery(),
  // ...
}
```
the return value of query in the endpoint definition is inferred to be `any`:

```typescript
// ...
endpoints: (builder) => ({
    getPokemonByName: builder.query({
      // not working
      query: (name: string) => ({
        xxx: ""
      })
    })
  })
```

[code sandbox](https://codesandbox.io/s/determined-parm-oguhuu?file=/src/services/pokemon.ts:72-958)

**Comment by phryneas** [comment]
TypeScript sometimes just does things like this with inline calls - we see that in other places, too. I don't think this is something where we can do a lot though, I'm sorry!

**Comment by Grapedge** [comment]
Yes and thanks, I'm avoiding inline calls for now
