### ISSUE TITLE
Redux observables epics are not listening for dispatched action with rtk in mobile browsers.

### ISSUE THREAD

**Issue by vforvaios** [reduxjs/redux-toolkit#2624]
Hi everyone. Recently I am experiencing a problem with a local pet project using react, rtk and redux observables ONLY IN MOBILE BROWSERS (chrome, firefox etc). (desktop browsers are playing nice and easy)

Lets see an example:

**ACTION**
```js
const someAction = createAction('someAction')
```

**COMPONENT**
```js
.....
const dispatch = useDispatch();
....
<button onClick={() => dispatch(someAction())}
....
```

**EPICS**
```js
const someActionEpic = action$ => action$.pipe(
ofType(someAction.type),
map(.........)
)
```

**STORE**
```js
import { configureStore } from '@reduxjs/toolkit';
import rootEpics from 'models/epics/rootEpics';
import gameReducer from 'models/reducers/gameReducer';
import { combineReducers } from 'redux';
import { createEpicMiddleware } from 'redux-observable';
import { persistReducer } from 'redux-persist';
import storage from 'redux-persist/lib/storage/session';

const persistConfig = {
  key: 'state',
  storage,
};

const persistedReducer = persistReducer(
  persistConfig,
  combineReducers({
    gameReducer,
  }),
);

const epicMiddleWare = createEpicMiddleware();

const store = configureStore({
  reducer: persistedReducer,
  middleware: [epicMiddleWare],
  devTools: process.env.NODE_ENV !== 'production',
});

epicMiddleWare.run(rootEpics);
export default store;
```

With this example, the epic is not triggered. Its as if the action is dispatched but the epic is not listening.

If I change the rtk setup with the old redux setup, everything is fine!!!!!!!

Is there a limitation for rtk actions regarding middlewares in mobile????

Thanks in advance

**Comment by phryneas** [comment]
What does your old store setup look like? Also, are you deliberately disabling all middleware included in RTK here or is it an accident?

**Comment by vforvaios** [comment]
Thanks for taking the time and looking at my issue. Actually, it was my fault.
I had a request happening on a useEffect passing through an epic, but the request failed from the mobile, and then the epics stopped listening. Found it, and resolved it. Thanks again.
