### ISSUE TITLE
createAsyncThunk & useDispatch

### ISSUE THREAD

**Issue by ssmfs** [reduxjs/redux-toolkit#2627]
why report a ts type error when I use `useDispatch` to call `createAsyncThunk `
### my code
```
export const getAllCategory = createAsyncThunk(
  'category',
  async () => {
    const res = await request.get('*******')
    return res.data
  }
)

const dispatch = useDispatch()`
useEffect(() => {
  dispatch(getAllCategory())
}, [])
```
### error
`Argument of type 'AsyncThunkAction<CategoryItem[], void, {}>' is not assignable to parameter of type 'AnyAction'.`

**Comment by fabiobiondi** [comment]
Try  with
```
import { AnyAction } from '@reduxjs/toolkit';
export type AppDispatch = ThunkDispatch<RootState, any, AnyAction>;
```

and 
```
const dispatch = useDispatch<AppDispatch>()
```

**Comment by markerikson** [comment]
FWIW we specifically recommend creating a reusable `useAppDispatch` hook:

- https://redux.js.org/tutorials/typescript-quick-start#define-typed-hooks

**Comment by fabiobiondi** [comment]
@markerikson : sure!  I agree : )

Anyway I write the code below, just to be sure we're talking about the same think and for other people that read this comment:

```ts
export type AppDispatch = ThunkDispatch<RootState, any, AnyAction>;
export const useAppDispatch = () => useDispatch<AppDispatch>()
```

### Usage

```ts
const dispatch = useAppDispatch()
```
