### ISSUE TITLE
Update query cache for 2 or more endpoints on success of mutation

### ISSUE THREAD

**Issue by TechSaq** [reduxjs/redux-toolkit#2630]
I have a listing of posts for which I have defined an endpoint `getPosts`. On click of any post, post details is opened for which I have defined another endpoint `getPostById`.

Now I have another endpoint defined to edit the post details `editPost`. In editpost endpoint, I have implemented optimistic updates using `onQueryStarted` and I am manually updating the cache for `getPostById` to reflect the edited changes instantly.

But after editing the post, when I go back to post listing, I still have old post data as it is coming from cache.

How can I update the cache of `getPosts` manually on edit of a post? 

I can invalidate the cache and trigger automating refetching for the endpoints but I want to save the server call by updating both `getPostById` and `getPosts` cache.

Please suggest if is there a way to achieve this or if invalidating the cache is the only way to go.

**Comment by markerikson** [comment]
Pretty sure you're looking for `updateQueryData`:

- https://redux-toolkit.js.org/rtk-query/api/created-api/api-slice-utils#updatequerydata
- https://redux-toolkit.js.org/rtk-query/usage/manual-cache-updates
