### ISSUE TITLE
createSlice with single generic argument

### ISSUE THREAD

**Issue by gkielyellation** [reduxjs/redux-toolkit#2636]
Request:
Allow for inlining initialState in createSlice  by passing a single generic argument. Currently createSlice requires passing the state and case reducers or defining a separate variable.

Updated type:
```ts
export declare function createSlice<State, CaseReducers = SliceCaseReducers<State>, Name extends string = string>(options: CreateSliceOptions<State, CaseReducers, Name>): Slice<State, CaseReducers, Name>;
```

Example usage
```ts
interface CounterState {
  count: number;
}

export const counterSlice = createSlice<CounterState>({
  name: 'counter',
  initialState: {
    count: 0,
  },
  reducers: {
    increment(state) {
      state.count++;
    },
    decrement(state) {
      state.count--;
    },
  },
});
```

**Comment by gkielyellation** [comment]
It appears this causes an issue with dispatch possibly being undefined.  Feel free to close if it's not feasible.

**Comment by markerikson** [comment]
Yeah, `createSlice` is designed to _not_ have end users provide generic args, but rather to infer the types from what you provide as parameters.

In this case, the simpler answer is: `initialState: {value: 0} as CounterState`
