### ISSUE TITLE
useLazyQuery - option to populate data from cache

### ISSUE THREAD

**Issue by ymulenll** [reduxjs/redux-toolkit#2638]
### Context:
The `trigger` function from `useLazyQuery` has the `preferCacheValue` option that in case we set it as true it will immediately return a cached value if one exists.

Example:
```javascript
  const [
    trigger,
    { data: posts, isUninitialized },
  ] = useLazyGetPostsQuery();

  if (isUninitialized) {
    return (
      <button onClick={() => trigger(undefined, true)}>Fetch Posts</button>
    );
  }
```
Docs: https://redux-toolkit.js.org/rtk-query/api/created-api/hooks#uselazyquery

### Suggestion
It may be useful to have an option at the query level, to populate the initial `data` with the value from cache if one exists, so we won't have to call the trigger function to get the data in case we already have something on cache.

Example:

```javascript
  const [
    trigger,
    { data: posts, isUninitialized },
  ] = useLazyGetPostsQuery({
    // populate the initial data with the value form cache if one exists
    populateWithCacheValue: true,
  });

  if (isUninitialized) {
    return (
      <button onClick={() => trigger(undefined)}>Fetch Posts</button>
    );
  }
```

**Comment by phryneas** [comment]
In that case, you probably really should be using `useQuery` instead. `useLazyQuery` has no idea about what argument it might have at some point later - should `useLazyQuery` give you the cache entry for `trigger(undefined)`, `trigger(5)` or `trigger("blue")` if all 3 are in the cache?

**Comment by ymulenll** [comment]
> In that case, you probably really should be using `useQuery` instead. `useLazyQuery` has no idea about what argument it might have at some point later - should `useLazyQuery` give you the cache entry for `trigger(undefined)`, `trigger(5)` or `trigger("blue")` if all 3 are in the cache?

Good point! I guess another option will be to call the trigger in an `useEffect` with the `preferCacheValue` option in `true`, the issue is that I want to call the query programmatically, so I think useQuery will be tricky to use, even using the `skip` option. 

Another option could be to specify the argument I want to populate initially (like populateFromCache:"blue"), but probably that feature is not worth the time, thanks for the answer.

**Comment by phryneas** [comment]
Why not just
```js
const [arg, setArg] = useState(initialArg)
const result = useQuery(arg)


// instead of trigger
setArg("foo")
```
then?
