### ISSUE TITLE
"Redux Toolkit TypeScript Quick Start" guide is broken

### ISSUE THREAD

**Issue by 1alexvash** [reduxjs/redux-toolkit#2648]
I was following the guide, and I had encountered issues on it:

https://redux-toolkit.js.org/tutorials/typescript

![image](https://user-images.githubusercontent.com/46556479/187126010-9024e3e7-c798-47f1-9bfa-3d48bcc542cf.png)

![image](https://user-images.githubusercontent.com/46556479/187126025-029b7eaa-df0e-4ef6-89bd-aba967e4cb9f.png)

Can you address this issue, or maybe attach GitHub example for this guide, it makes it extremely hard for starters to understand how this whole library works

After reading the guide, I still got nothing working

**Comment by phryneas** [comment]
The TypeScript quickstart is about setting up the **TypeScript part** of the application. 

The TypeScript part of that code example (the additional code you have to write to set up TS) is highlighted in that code snippet. 

That TS QuickStart guide is not about setting up a whole application - for that, just follow the normal QuickStart guide.
