### ISSUE TITLE
Issues with the Advanced Tutorial

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#265]
Per https://www.reddit.com/r/reactjs/comments/e14qf3/reasons_to_use_redux_in_20192020/f8nl47k/ :

> - Cloning the initial source was not obvious. I ended up launching the sandbox and using the file -> Export to ZIP menu item.
> - rootReducer was not expanded as each slice was built
> - App.tsx overlooked some diffs
> `if (currentDisplay.type === 'issues') {`
> 
> becomes
> 
> `if (displayType === 'issues') {`
>
> and the corresponding
> 
> `} else {`
> 
> becomes
> 
> `} else if (issueId !== null) {`
> - commentsSlice.ts - `"`interface CommentsState`"` allowed `undefined` for `commentsByIssue`, which the compiler complained about at some point.

and:

> The repo code is correct. I meant that the reader is only told to expand rootReducer once during "Using the Slice Reducer". However, rootReducer eventually ends up with four slices being added to it and the tutorial is silent on the other three (other than the link to the repo).

**Comment by slim-hmidi** [comment]
@markerikson the tutorial will be updated or changed because there is the createAsyncThunk function can be added to slice files and update the code.
If you decide to keep it I can make a PR for the update of the example but if you think to update the documentation and examples it is ok.

**Comment by markerikson** [comment]
We're already planning to rewrite the tutorial sequence: #371 .

**Comment by markerikson** [comment]
Obsolete due to #905 .
