### ISSUE TITLE
Docs: Code Commenting

### ISSUE THREAD

**Issue by 90arther** [reduxjs/redux-toolkit#2651]
## Description

Unclean code comments raise doubts.

Locate: https://redux-toolkit.js.org/tutorials/quick-start#create-a-redux-store

## Screenshot

<img width="1563" alt="Screenshot 2022-08-29 at 7 58 51 PM" src="https://user-images.githubusercontent.com/3853101/187196350-0e1f12b9-31db-424f-9202-430b6a9b15e0.png">

**Comment by markerikson** [comment]
I'm not sure what you mean by "unclean comments" here.

I do see that there's a mismatch between the `reducer` arg in this example and the comment. I'd rather update the `reducer` line to include those three reducers instead of removing this comment.

**Comment by 90arther** [comment]
> I'm not sure what you mean by "unclean comments" here.
> 
> I do see that there's a mismatch between the `reducer` arg in this example and the comment. I'd rather update the `reducer` line to include those three reducers instead of removing this comment.

Those three reducers don't exist in the example Counter. How about updating the comment to match the exact reducer?
```
// Inferred type: {counter: counterState}
```
