### ISSUE TITLE
Adding middleware to `configureStore` throws TS `overload` error

### ISSUE THREAD

**Issue by greebl3** [reduxjs/redux-toolkit#2653]
## The error

Adding basic, synchronous middleware to  `configureStore` [as recommended](https://redux-toolkit.js.org/api/getDefaultMiddleware#intended-usage):

`middleware: (getDefaultMiddleware) => getDefaultMiddleware().concat(thunkMiddleware)`

 throws the error:

`No overload matches this call.
  Overload 1 of 2, '(items: readonly Middleware<any, any, Dispatch<AnyAction>>[]): MiddlewareArray<[ThunkMiddleware<CombinedState<{ playback: PlaybackState; }>, AnyAction, undefined>, ...Middleware<...>[]]>', gave the following error.
    Argument of type 'AppThunk<void>' is not assignable to parameter of type 'readonly Middleware<any, any, Dispatch<AnyAction>>[]'.
  Overload 2 of 2, '(...items: readonly Middleware<any, any, Dispatch<AnyAction>>[]): `

## What `store.ts` and `configureStore` look like 

[As recommended in the docs](https://redux.js.org/usage/usage-with-typescript#type-checking-middleware),  `AppState` (`RootState` in the docs) is defined as `export type AppState = ReturnType<typeof rootReducer>`, where `rootReducer` is the combination of a single, defined reducer: `const rootReducer = combineReducers({playback: playbackReducer})`

## What the middleware looks like

The custom middleware is defined as so:

`export const thunkMiddleware: AppThunk = () => (dispatch: AppDispatch) => {
    dispatch(testSyncFunction)
}`

where `AppThunk` is the [recommended typing](https://redux.js.org/usage/usage-with-typescript#type-checking-redux-thunks):

`export type AppThunk<ReturnType = void> = ThunkAction<`
`  ReturnType,`
`  AppState,`
`  unknown,`
`  AnyAction`
`>`

and the synchronous function to be called is basic:

`const testSyncFunction = () => {
    console.log("synchronous middleware called")
}`

**Comment by markerikson** [comment]
That's _not_ a middleware. That's a thunk action creator.  TS is correctly telling you that what you're passing in is not valid.

A middleware looks like:

```ts
const myMiddleware: Middleware = storeAPI => next => action {
  // custom middleware logic here, like checking something in `action`
  return next(action);
}
```

**Comment by greebl3** [comment]
Uh...oops. [I got the impression](https://redux-toolkit.js.org/usage/usage-guide#simplifying-store-setup-with-configurestore) that thunks were a subset of middleware:

> `redux-Thunk` is the most commonly used middleware for working with both synchronous and async logic outside of components

I'm trying to do just that - call a (synchronous) function after updating the state in a store created by `configureStore`, but there're only docs for `createAsyncThunk`

Isn't `getDefaultMiddleware` just that - the default middleware included by `configureStore`? Any custom functions I have (terminology aside for a second) have to be passed in *somewhere*, no? I was under the impression that's what the *concat* in the aforementioned docs was for

Appreciate the quick response - would you mind pointing me in the right direction?

**Comment by markerikson** [comment]
The *thunk middleware* is, indeed, a middleware:

https://redux.js.org/usage/writing-logic-thunks#how-does-the-middleware-work

```ts
const thunkMiddleware =
  ({ dispatch, getState }) =>
  next =>
  action => {
    // If the "action" is actually a function instead...
    if (typeof action === 'function') {
      // then call the function and pass `dispatch` and `getState` as arguments
      return action(dispatch, getState)
    }

    // Otherwise, it's a normal action - send it onwards
    return next(action)
  }
```

A "thunk action creator" and a "thunk function" are not middleware:

```ts
function myThunkActionCreator(id) {
  return function myThunkActionCreator(dispatch, getState) {
    // do some logic here
  }
}
```

The idea is that you add the thunk _middleware_ to the store setup, once.

Then, you dispatch thunk functions:

```ts
// action creator returns the thunk function, which is passed into `dispatch`
// the thunk middleware intercepts the thunk function and runs it
store.dispatch(myThunkActionCreator()) 
```

I'd recommend reading through that thunk usage docs page, as well as these tutorial pages:

- https://redux.js.org/tutorials/essentials/part-5-async-logic
- https://redux.js.org/tutorials/fundamentals/part-6-async-logic

Since RTK's `configureStore` already adds the thunk middleware to the store setup by default, there's nothing you actually need to do here. Just define thunks and dispatch them as usual.
