### ISSUE TITLE
[RTK Query] TypeError: Cannot destructure property 'store' of 't(...)' as it is null.

### ISSUE THREAD

**Issue by mingcnjs** [reduxjs/redux-toolkit#2655]
We are using RTK query, when I use this I am getting this error.
TypeError: Cannot destructure property 'store' of 't(...)' as it is null.
![image](https://user-images.githubusercontent.com/45022206/187337070-b9f29563-ec26-4b62-bf68-9216cd735a65.png)

The codes are working on the local environment, but throw error in production.

**Comment by phryneas** [comment]
That sounds like a problem with your bundler. Without at least source maps that show where that error is coming from it's impossible for us to help you in any way.
