### ISSUE TITLE
Feature Suggestion: `createSlice` to export `selectors`

### ISSUE THREAD

**Issue by Harris-Miller** [reduxjs/redux-toolkit#2658]
`@reduxjs/toolkit` has done an amazing job abstracting common functionality to reduce boiler plate. One thing that I feel is missing is that `createSlice` does not produce base selectors for the root keys of a `reducer`

So I would like to add `selectors` to the return object of `createSlice`

```typescript
{
    name : string,
    reducer : ReducerFunction,
    actions : Record<string, ActionCreator>,
    caseReducers: Record<string, CaseReducer>.
    getInitialState: () => State,
    selectors: Record<string, Selector> // new!
}
```

`selectors` has a key matching each key of `initialState` that is passed to `createSlice`. The idea is to simply allow us to reuse a pre-generated selector function the same way actions are generated

```typescript
// user.slice.ts
type UserState = {
  email: string;
}

const initialState: UserState = {
  email: ''
};

export const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    setEmail: (state, action: PayloadAction<string>) => {
      state.email = action.payload;
    }
  }
});

// UserInfo.tsx
import { userSlice } from '../user.slice';

const UserInfo = () => {
  const dispatch = useDispatch();
  // we should use selectors generated right from the slice
  const email = useSelector(userSlice.selectors.email);
  
  const onChange = (e) => {
    // the same way we use actions!
    dispatch(userSlice.actions.setEmail(e.currentTarget.value);
  };

  return (
    <input onChange={onChange} value={email} />
  );
}
```

The intention of these pre-generated selectors is simply to cover the most common use case of a reducer, one with a flat object where you just want to get the value of each key. No more, no less.

This addition would be incredibly simple to add with very little overhead and provides additional reduction of boilerplate. And while it would not _always_ be used for more complex reducers, I don't feel there would be much harm or overhead to including them regardless

Alternative to always including them:
* opt-in to their generation by passing `createSlice({ selectors: true });`
* granularly select which keys get generated `createSlice({ selectors: ['email'] });`, where `selectors: (keyof State)[]`

**Comment by EskiMojo14** [comment]
see #193 and #91 - it used to do this but was removed for reasons stated in the issue discussion (#91)

**Comment by markerikson** [comment]
Yep. We actually discourage having selectors for _every_ single field in a slice:

https://redux.js.org/usage/deriving-data-selectors#balance-selector-usage

and this really isn't something I want to add.

Another issue is that these selectors wouldn't know anything about the _root_ state type, which is what a typical selector expects as its first argument.  We _could_ hypothetically do something like the `entityAdapter.getSelectors(selectTheRightPieceOfData)` approach, but at that point there really isn't much benefit over just writing a couple of functions yourself.
