### ISSUE TITLE
RTK Query: builder.query from createApi should default to void for generic parameter QueryArg

### ISSUE THREAD

**Issue by fedemp** [reduxjs/redux-toolkit#2664]
For context, I mean the `builder.query` in this type of code:

```ts
export const api = createApi({
	endpoints: (builder) => ({
		login: builder.query({…
```

Currently, it accepts two generic argument types, one for return type and another for arguments.

````ts
query<ResultType, QueryArg>(
    definition: OmitFromUnion<QueryDefinition<QueryArg, BaseQuery, TagTypes, ResultType, ReducerPath>, 'type'>
): QueryDefinition<QueryArg, BaseQuery, TagTypes, ResultType, ReducerPath>;
````

The problem is that if I define the `ResultType`, I must define the `QueryArg` too. If I do `builder.query<string, void>`, then the following typescript-eslint rule is triggered: [`no-invalid-void-type`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-invalid-void-type.md). I know I could just disable the rule for the line, but wouldn't it be better if `QueryArg` defaulted to void?

````ts
query<ResultType, QueryArg = void>
    (definition: ...)
````

For the record, doing some like `builder.query<string, undefined>` would mean that I must always pass `undefined` as a parameter.

**Comment by markerikson** [comment]
No, I really don't think we want to have a default here, otherwise we'd end up with trouble going the other way. Users _should_ be declaring what the inputs and outputs are, and tbh that lint rule seems over-zealous and not really valuable.

**Comment by phryneas** [comment]
Also, that would defeat the other way of letting both those be inferred from `query(arg)` and `transformResult(...): ResultType`.
