### ISSUE TITLE
Uncaught TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_1__.useState) is not a function

### ISSUE THREAD

**Issue by Babeev** [reduxjs/redux-toolkit#2666]
I setting up react-native-web app with redux-toolkit and have an error:  Uncaught TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_1__.useState) is not a function at rtk-query-react.esm.js

<img width="505" alt="Снимок экрана 2022-09-02 в 12 45 45" src="https://user-images.githubusercontent.com/64578266/188067149-ed857a62-30b7-40ad-bb06-e646d2a42694.png">

This error appears in the buildMutationHook in the file rtk-query-react.esm.js

<img width="861" alt="Снимок экрана 2022-09-02 в 12 54 01" src="https://user-images.githubusercontent.com/64578266/188068142-9c86ec7c-4b61-4949-8004-ea0b02053c70.png">

useState was imported at the top of that file though
<img width="873" alt="Снимок экрана 2022-09-02 в 12 49 12" src="https://user-images.githubusercontent.com/64578266/188067569-c237063c-bed5-4693-bedc-ef984593b8b2.png">

And this import leads to the right place: node_modules/@types/react/index.d.ts
<img width="881" alt="Снимок экрана 2022-09-02 в 12 52 51" src="https://user-images.githubusercontent.com/64578266/188068024-a9fa89f2-b8de-4546-ad8c-1f2ba3b533bc.png">

store:
<img width="600" alt="Снимок экрана 2022-09-02 в 12 56 51" src="https://user-images.githubusercontent.com/64578266/188068549-4bd2eb11-55f8-40b8-b54d-6210335da832.png">

api:
<img width="722" alt="Снимок экрана 2022-09-02 в 12 58 01" src="https://user-images.githubusercontent.com/64578266/188068709-0a4bafb1-e4c0-4f1c-90c1-7f4c11f4ee95.png">

auth endpoint:
<img width="711" alt="Снимок экрана 2022-09-02 в 12 58 36" src="https://user-images.githubusercontent.com/64578266/188068763-182e664d-3b0e-49fe-a686-1f91ba2d68b9.png">

user endpoint:
<img width="572" alt="Снимок экрана 2022-09-02 в 12 59 02" src="https://user-images.githubusercontent.com/64578266/188068826-2b078d2c-e8c2-48b6-a0cf-16afb386d388.png">

custom hook:
<img width="777" alt="Снимок экрана 2022-09-02 в 12 59 42" src="https://user-images.githubusercontent.com/64578266/188068912-b77cdb9c-b3c7-4548-8726-9b3c4a9e7a9b.png">

component:
<img width="627" alt="Снимок экрана 2022-09-02 в 13 00 28" src="https://user-images.githubusercontent.com/64578266/188069024-bf775053-0002-4794-acff-2aba6075b5ab.png">

webpack:

``` 
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const path = require('path');
const webpackEnv = process.env.NODE_ENV || 'development';
const appDirectory = path.resolve(__dirname, '../');

module.exports = {
  entry: [path.resolve(appDirectory, 'web/index.web.js')],

  output: {
    filename: 'bundle.web.js',
    path: path.resolve(appDirectory, 'web/dist'),
    publicPath: '/',
    clean: true,
  },

  devtool: 'source-map',

  devServer: {
    historyApiFallback: true,
    open: true,
    compress: true,
    hot: true,
  },

  mode: webpackEnv,

  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              cacheDirectory: true,
              babelrc: true,
              filename: path.resolve(appDirectory, 'babel.config.js'),
            },
          },
        ],
      },

      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ['babel-loader'],
      },

      {
        test: /\.(?:ico|svg|gif|png|jpg|jpeg)$/i,
        type: 'asset/inline',
      },
    ],
  },

  plugins: [
    new HtmlWebpackPlugin({
      template: path.join(__dirname, 'index.html'),
    }),
    new webpack.HotModuleReplacementPlugin(),
    new CleanWebpackPlugin(),
  ],

  resolve: {
    alias: {
      'react-native$': 'react-native-web',
    },

    extensions: ['.web.js', '.js', '.jsx', '.ts', '.tsx'],

    modules: ['.', 'node_modules'],
  },
};

````

babel.config.js:

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-web'],
};
```

package.json:
```
{
  "name": "teacher",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "web:start": "webpack-dev-server --config ./web/webpack.config.js --hot --mode=development",
    "web:build": "webpack --config ./web/webpack.config.js --mode=production",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "unit": "jest",
    "e2e": "cypress open"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-navigation/native": "6.0.12",
    "@react-navigation/native-stack": "6.8.0",
    "@reduxjs/toolkit": "1.8.5",
    "jwt-decode": "^3.1.2",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.5",
    "react-native-encrypted-storage": "^4.0.2",
    "react-native-safe-area-context": "4.3.3",
    "react-native-screens": "3.17.0",
    "react-native-web": "0.18.9",
    "react-redux": "8.0.2",
    "react-scripts": "5.0.1",
    "whatwg-fetch": "^3.6.2"
  },
  "devDependencies": {
    "@babel/core": "7.18.10",
    "@babel/plugin-transform-runtime": "7.18.10",
    "@babel/preset-env": "7.18.10",
    "@babel/preset-react": "7.18.6",
    "@babel/preset-typescript": "7.18.6",
    "@babel/runtime": "7.18.9",
    "@react-native-community/eslint-config": "2.0.0",
    "@testing-library/jest-native": "4.0.11",
    "@testing-library/react-native": "11.0.0",
    "@types/jest": "29.0.0",
    "@types/react": "18.0.17",
    "@types/react-native": "0.69.6",
    "@types/react-redux": "7.1.24",
    "@types/react-test-renderer": "18.0.0",
    "babel-jest": "29.0.1",
    "babel-loader": "8.2.5",
    "babel-plugin-module-resolver": "4.1.0",
    "babel-plugin-react-native": "1.0.1",
    "babel-plugin-react-native-web": "0.18.9",
    "clean-webpack-plugin": "^4.0.0",
    "cypress": "10.7.0",
    "eslint": "7.32.0",
    "html-webpack-plugin": "5.5.0",
    "jest": "29.0.1",
    "jest-transform-stub": "2.0.0",
    "metro-react-native-babel-preset": "0.72.1",
    "react-test-renderer": "18.0.0",
    "typescript": "4.8.2",
    "url-loader": "4.1.1",
    "webpack": "5.74.0",
    "webpack-cli": "4.10.0",
    "webpack-dev-server": "4.10.1"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

**Comment by Babeev** [comment]
If I comment out this lines no errors appear and the rest works well
<img width="738" alt="Снимок экрана 2022-09-02 в 13 10 44" src="https://user-images.githubusercontent.com/64578266/188070335-bf0e7618-be4a-492c-b260-abdf919c9872.png">

**Comment by markerikson** [comment]
Unfortunately I don't think there's anything we can do here. We _know_ the library itself works right, and works right with React. I have to assume this is an issue with your bundler config / project setup somehow.  

Given that, and also that we don't use RN ourselves, I'm afraid I don't have any particular suggestions for what to change to fix this.  Sorry!

**Comment by andyjessop** [comment]
The only thing I can suggest is to use the non-react entry point for `creatApi`, which won't generate the hooks that are causing issues:

```ts
import { createApi } from '@reduxjs/toolkit/query';
```

**Comment by markerikson** [comment]
Looks like they are specifically trying to use RTKQ with React here, so I don't think that's going to solve the issue.

I _am_ a bit confused by seeing an RN project set up with Webpack - I thought those were usually bundled with Metro.  I guess it's being cross-compiled with `react-native-web`.

I can only assume that somehow `react` itself isn't being found by the bundler in this case.

**Comment by phryneas** [comment]
I am currently using RTKQ with a Expo React Native Web (hence webpack) setup at work and it works fine. This is really very very specific to your setup, I'm sorry!

**Comment by Babeev** [comment]
> Looks like they are specifically trying to use RTKQ with React here, so I don't think that's going to solve the issue.
> 
> I _am_ a bit confused by seeing an RN project set up with Webpack - I thought those were usually bundled with Metro. I guess it's being cross-compiled with `react-native-web`.
> 
> I can only assume that somehow `react` itself isn't being found by the bundler in this case.

Yes, I using react-native-web for setting up cross-platform app without expo. 
I have example repo for reproducing error: [github.com/Babeev/react-native](https://github.com/Babeev/react-native)

For reproducing please open src/pages/Auth/controller.ts and uncomment line 12 or line 13. After this you will see the error

**Comment by HarshuHacker** [comment]
In The createSlice check the spelling of reducers
It should be reducers: {} 
I had the same error because I used reducer

**Comment by yannik2480** [comment]
Had the same issue solved it by adding "use client"

**Comment by NathanZlion** [comment]
> If this is NEXT js Then converting the component into client component using 'use client'will solve this issue i had solved the similar issue just now

You are a life saver @Yogeshthangm , thanks

**Comment by shimazojaji** [comment]
> If this is NEXT js Then converting the component into client component using 'use client'will solve this issue i had solved the similar issue just now

Yes, that's right

**Comment by SaqlainYounas** [comment]
Use "Use Client" if you are using next js. It works!

**Comment by teddy-battalion48** [comment]
i cracked it



https://jqcode.space/questions/count-scroller-finding-a-solution-for-debounce
