### ISSUE TITLE
Possible to run updateQueryData before query is initiated 

### ISSUE THREAD

**Issue by frankleng** [reduxjs/redux-toolkit#2668]
I have an endpoint that doesn't need to fetch until a mutation occurs.

I'd like to implement optimistic update -
running `updateQueryData` once mutation starts, but has yet to be fulfilled..

but seems like running `updateQueryData` on an uninitiated query is a no-op. everything works fine if I fetch first.

is there a workaround? perhaps initiate it with empty state somehow?

**Comment by phryneas** [comment]
This just rolled out with the latest alpha: https://github.com/reduxjs/redux-toolkit/issues/1720

**Comment by frankleng** [comment]
> This just rolled out with the latest alpha: #1720

awesome. thank you!

**Comment by phryneas** [comment]
But please be aware that it seems there was a bug in that alpha release that prevented upserts from actually happening. See the thread above where we discussed that - #2669 contains a fix and a CodeSandbox CI build of the package you can install and use.
