### ISSUE TITLE
"import the middleware and directly add their listeners" is not working

### ISSUE THREAD

**Issue by zavvdev** [reduxjs/redux-toolkit#2670]
Hi! I'm using listener middleware and faced next problem.
My folder structure is:
```
store/
   theme/
      middleware.js
      slice.js
   rootMiddleware.js
   index.js
```
**index.js** file:
```
import {
  configureStore as createStore,
} from "@reduxjs/toolkit";
import { rootReducer } from "core/store/rootReducer";
import { httpApi } from "core/store/httpApi";
import { rootMiddleware } from "core/store/rootMiddleware";

const configureStore = (args = {}) => {
  const { initialState = {} } = args;
  return createStore({
    reducer: rootReducer,
    preloadedState: initialState,
    middleware: (getDefaultMiddleware) => {
      return getDefaultMiddleware()
        .prepend(rootMiddleware.middleware)
        .concat(httpApi.middleware);
    },
  });
};

const store = configureStore();

export { store, configureStore };

```

**rootMiddleware.js** file:

```
import { createListenerMiddleware } from "@reduxjs/toolkit";

export const rootMiddleware = createListenerMiddleware();

```

and **store/theme/middleware.js**:
```
import { toggleDarkMode } from "core/store/theme/slice";
import { selectIsDarkMode } from "core/store/theme/selectors";
import { saveDarkModeState } from "core/store/theme/utils";
import { rootMiddleware } from "core/store/rootMiddleware";

rootMiddleware.startListening({
  actionCreator: toggleDarkMode,
  effect: (_, listenerApi) => {
    const isDarkMode = selectIsDarkMode(listenerApi.getOriginalState());
    saveDarkModeState(!isDarkMode);
  },
});
```
As you can see I'm trying to use the second approach from [documented recommendations](https://redux-toolkit.js.org/api/createListenerMiddleware#organizing-listeners-in-files) but it seems not working at all. Dispatched action is not intercepted by middleware.
I tried to `concat` it like httpApi middleware in the index.js file but it still not work.

The last documented example is good as well but i'm not using typescript in my project so the second one is the best for me now.

My temporary workaround is to import all middlewares and assign it to the rootMiddleware like this:
```
export const rootMiddleware = createListenerMiddleware();

[themeMiddleware].forEach(rootMiddleware.startListening);
```
```
export const themeMiddleware = ({
  actionCreator: toggleDarkMode,
  effect: (_, listenerApi) => {
    const isDarkMode = selectIsDarkMode(listenerApi.getOriginalState());
    saveDarkModeState(!isDarkMode);
  },
});
```

It works, but here is the same problem like with the third documented approach. I'm not using typescript and all typings are lost. 

Thanks!

**Comment by phryneas** [comment]
If you never import that `store/theme/middleware.js` anywhere, it will never execute the code in the file. So you don't need to do anything with that import, but you need to have smne other file that is being executed point an import to this file for something to happen.
