### ISSUE TITLE
Using store.dispatch() - TypeError: undefined is not an object (evaluating '_api.api.middleware')

### ISSUE THREAD

**Issue by jacksonHendric** [reduxjs/redux-toolkit#2674]
Hi, 
I have a basic RTK Query setup with a store that has one authentication slice.

store.ts
```
export const store = configureStore({
  reducer: {
    [api?.reducerPath]: api.reducer,
    auth: authReducer
  },
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(api.middleware)
})

setupListeners(store.dispatch)

export type AppDispatch = typeof store.dispatch
export const useAppDispatch: () => AppDispatch = useDispatch
export type RootState = ReturnType<typeof store.getState>
export const useTypedSelector: TypedUseSelectorHook<RootState> = useSelector
```
authSlice.ts
```
import { createSlice } from '@reduxjs/toolkit'
import type { PayloadAction } from '@reduxjs/toolkit'

export interface State {
  token: string | undefined
}

const initialState: State = {
  token: undefined
}

export const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
    setStoreAuth: (state, action: PayloadAction<sometype>) => {
      return { token: action.payload.token }
    },
    clearStoreAuth: (state) => {
      return initialState
    }
  }
})

export const { setStoreAuth, clearStoreAuth } = authSlice.actions

export default authSlice.reducer
```

I am trying to dispatch the action clearStoreAuth on a 401 response like this 
```
const baseQueryWithReauth: BaseQueryFn<
  string | FetchArgs,
  unknown,
  FetchBaseQueryError
> = async (args, api, extraOptions) => {
  let result = await baseQuery(args, api, extraOptions)
  if (result.error && result.error.status === 401) {
    store.dispatch(clearStoreAuth())  <-------------HERE!!!
  }
  return result
}
```

I get the error 
`TypeError: undefined is not an object (evaluating '_api.api.middleware')`

Any idea what's going one here? Thanks!

**Comment by markerikson** [comment]
Are you directly importing `store` into the file with `baseQueryWithReauth`?  **Please don't do that**.  That's going to cause circular import issues.

**Comment by jacksonHendric** [comment]
> Are you directly importing `store` into the file with `baseQueryWithReauth`? **Please don't do that**. That's going to cause circular import issues.

Yes I did, how do you avoid doing this? Thanks

**Comment by markerikson** [comment]
In the worst case, you can inject the store into that file:

https://redux.js.org/faq/code-structure#how-can-i-use-the-redux-store-in-non-component-files

**Comment by jacksonHendric** [comment]
That worked! What is the standard way of going about this? How would I clear my store on a 401 response the correct way?

**Comment by markerikson** [comment]
Base queries _should_ have access to `dispatch` already as part of the second argument, `baseQueryApi`:

![image](https://user-images.githubusercontent.com/1128784/188324470-af6620fe-c4ef-4cfa-a1b5-11b8b07fe2ed.png)

**Comment by jacksonHendric** [comment]
Wow, should have read the documentation. Thank you for clearing everything up!
