### ISSUE TITLE
RTKQ "Code Splitting" usage page does not  cover `enhanceEndpoints`

### ISSUE THREAD

**Issue by BeijiYang** [reduxjs/redux-toolkit#2679]
In [this page](https://redux-toolkit.js.org/rtk-query/usage/code-generation), the link of "**enhanceEndpoints**" is wrong.

Currently it's https://redux-toolkit.js.org/rtk-query/usage/code-splitting
This page contains nothing about `enhanceEndpoints`.

It should be https://redux-toolkit.js.org/rtk-query/api/created-api/code-splitting#enhanceendpoints

**Comment by noanflaherty** [comment]
I've also been tripped up by this – thanks for sharing the right link!

**Comment by markerikson** [comment]
Hmm. Yeah, the "Code Splitting" usage page _doesn't_ mention `enhanceEndpoints`. That's a deficiency we should fix.

**Comment by BeijiYang** [comment]
Thank you @markerikson !
