### ISSUE TITLE
How to generate config for RTQ with tags?

### ISSUE THREAD

**Issue by IvanNavin777** [reduxjs/redux-toolkit#2681]
Hey guys.
I'm using React + RTQ + @rtk-incubator/rtk-query-codegen-openapi.
I use the following command to generate the config:
`npx @rtk-incubator/rtk-query-codegen-openapi --file ./src/store/services/query.generated.ts --baseQuery ./src/store/services/customBaseQuery.ts --hooks https://myBackend/backend/swagger/BlaBla/swagger.json `
And I want to be able to add tags to this generated config. To be able to do refetch when new data arrived. The backend is updated daily, so we generate the config every day. Question: How to generate config for RTQ with tags? Or how to clear the RTQ cache?

**Comment by phryneas** [comment]
You would use `enhanceEndpoints` in an additional file to add stuff like tags to the generated api.

https://redux-toolkit.js.org/rtk-query/api/created-api/code-splitting#enhanceendpoints

**Comment by IvanNavin777** [comment]
Thank you very much! This should help me!
