### ISSUE TITLE
Using selectInvalidatedBy with addTagTypes

### ISSUE THREAD

**Issue by nickkitto** [reduxjs/redux-toolkit#2683]
I am currently using RTK query 1.8.5

I am using code generation on my OpenAPI spec. As a part of this I am using `enhanceEndpoints` with `addTagTypes` to set up tags. I was looking at implementing some optimistic updates, particularly using the `selectInvalidatedBy` helper. However, it does not seem to support the tags added in here.

When doing this, the typing is not correct, ie:
```
tagTypes: [],
```
```
addTagTypes: ["post"]
```
```
api.util.selectInvalidatedBy(getState(), ["post"])) ...
```
results in
```
Type 'string' is not assignable to type 'FullTagDescription<never>'.
````

However, adding the tag manually into the generated code ie:
```
tagTypes: ["post"],
```
```
addTagTypes: []
```
```
api.util.selectInvalidatedBy(getState(), ["post"])) ...
```
Results in a successful compilation and expected behavior.

Looking at the docs, it seems like I could work around this using `tags` in the OpenAPI spec, but ideally wouldn't want to do this for several reasons.

Please let me know if any more information is required.

**Comment by markerikson** [comment]
I don't know a lot about the codegen side myself, but:

when you say `api.util.selectedInvalidatedBy()`, _which_ `api` variable are you using?

Note that the "original" `api` instance won't have any of the additional TS types baked in. The "injected/enhanced" one will.

(At runtime, these are actually all one single API object reference, but for TS typing purposes you should treat them as separate - TS only knows about the new tag types with the instance "returned" from `inject/enhance/etc`, so you should import that around and use it as needed.)

**Comment by nickkitto** [comment]
Ah, perfect, figured out the problem. Using the "enhanced" APIs version of `selectInvalidatedBy` was what I was missing and that resolved the problem. Sorry for this needless ticket.

**Comment by markerikson** [comment]
No worries, glad that's working for oyu now!
