### ISSUE TITLE
RTK Query - Is there existing example of Graphql subscriptions working with RTK Query??

### ISSUE THREAD

**Issue by AleksandrukTad** [reduxjs/redux-toolkit#2687]
Like in the title.

**Comment by phryneas** [comment]
No. If you want subscriptions, chances are you are better off with a single-purpose graphql library like urql or apollo.

Of course you can implement that somehow with a websocket, but I wouldn't really recommend it.

**Comment by Valliappan-Lakshmanan** [comment]
@phryneas I have been trying to implement graphql subscription using rtkquery and wanted to know if it is still recommended to use urql or apollo instead?

**Comment by phryneas** [comment]
@Valliappan-Lakshmanan yes.
