### ISSUE TITLE
Documentation Clarification: What is the RETURNED typed? Where does it came from? Is this a typo?

### ISSUE THREAD

**Issue by Jplus2** [reduxjs/redux-toolkit#2692]
So in this documentation 

https://redux-toolkit.js.org/usage/usage-with-typescript#type-safety-with-extrareducers

There is this code

```
const fetchUserById = createAsyncThunk(
  'users/fetchById',
  // if you type your function argument here
  async (userId: number) => {
    const response = await fetch(`https://reqres.in/api/users/${userId}`)
    return (await response.json()) as Returned
  }
)
```

The **Returned** is the one that confuses me as to where it came from as it is not really documented.

Maybe it is meant to say

```
return (await response.json()) as UsersState
```

Which is the interface declared below?

I know this is not a big deal but would help clarify the documentation.

**Comment by markerikson** [comment]
In other words, it's whatever type _you_ are returning from your payload function.  Maybe it's a `User`, or a `Post[]`.  The issue is that `fetch()` doesn't know what the real TS type of your data is.
