### ISSUE TITLE
RTK Query: Possibly misleading documentation for `overrideExisting` option in endpoint injection

### ISSUE THREAD

**Issue by PauloRSF** [reduxjs/redux-toolkit#2694]
The [docs for code splitting and endpoint injection](https://redux-toolkit.js.org/rtk-query/api/created-api/code-splitting#description) say:

> Any endpoint definitions defined using that builder will be merged into the existing endpoint definitions for this API slice using a shallow merge, so any new endpoint definitions will override existing endpoints with the same name.

And a few lines after:

> The `overrideExisting` flag controls a development-only warning that notifies you if there is a name clash between endpoint definitions. When set to `true`, the warning will not be printed.

This might lead someone (such as me :p) to believe that endpoints get overridden no matter what and `overrideExisting` only controls if the warning is shown or not.

Looking at the code, it seems that the intended behavior is that `overrideExisting` actually controls whether existing endpoints are, in fact, overridden or not:

https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/createApi.ts#L307-L321

So, it looks like that section of the docs could be updated to clarify this. If you agree, i can open a PR for that.

**Comment by phryneas** [comment]
Hmm yeah, that could be a bit clearer. I guess I assumed the name would be telling, but the comment tells a bit of a different story.

A PR would be very welcome :)
