### ISSUE TITLE
Returning my base html when I use the useQuery hook on my component

### ISSUE THREAD

**Issue by vitorlfaria** [reduxjs/redux-toolkit#2712]
When I use the generated useQuery hooks on my React component its returnig the html template from public folder.
This is my service code.
```
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

const cryptoApiHeaders = {
  'X-RapidAPI-Key': process.env.CRYPTO_API_KEY,
  'X-RapidAPI-Host': process.env.CRYPTO_API_HOST,
};

const createRequest = (url) => ({
  url,
  headers: cryptoApiHeaders,
});

export const CryptoApi = createApi({
  reducerPath: 'CryptoApi',
  baseQuery: fetchBaseQuery({ baseUrl: process.env.CRYPTO_API_URL }),
  endpoints: (builder) => ({
    getCryptos: builder.query({
      query: (count) => createRequest(`/coins?limit=${count}`),
    }),
    getCryptoById: builder.query({
      query: (coin_uuid) => createRequest(`/coin/${coin_uuid}`),
    })
  })
});

export const {
  useGetCryptosQuery,
  useGetCryptoByIdQuery
} = CryptoApi
```

This is my Store code.
```
import { configureStore } from "@reduxjs/toolkit"

import { CryptoApi } from "../Services/CryptoApi"

export const store = configureStore({
  reducer: {
    [CryptoApi.reducerPath]: CryptoApi.reducer,
  },
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(CryptoApi.middleware),
})
Here I inject the Provider.

import { store } from './app/store'

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <BrowserRouter>
      <Provider store={store}>
        <App />
      </Provider>
    </BrowserRouter>
  </React.StrictMode>
);
```
Here is where i call it in the component
```
import { useGetCryptosQuery } from '../Services/CryptoApi';

const Home = () => {

  const { data, error, isLoading } = useGetCryptosQuery(10);

  return (
    <>
      {
        error ? (
            console.error(error.error)
          )
        :
        isLoading ? (
          console.log(isLoading)
        )
        :
        data ? (
          console.log('Passed: ', data)
        ) : null
      }
    </>
  )
}

export default Home;
```
And this is the response
![image](https://user-images.githubusercontent.com/55730145/191540061-59e1534e-fa5e-4c11-a308-c218af75195f.png)

As you can see, it is returning my own html template in the error... I'm working on this all day and yet don't know how to solve it...

OBS: all the env properties are correctly formatted.

**Comment by phryneas** [comment]
Take a look into your network devtools. There you can see which url is being used for the request and you can see the response. You are making a wrong request here. Not really something we can help you with, I'm sorry.

As for that `createRequest` helper: there seems to be a tutorial out there teaching that. The person writing that seems to have pretty much missed the point. That's what `fetchBaseQuery` already does, via `prepareHeaders`. 
You really don't need such a function. 
Maybe go for another tutorial? (Also, can you link me which tutorial that is so that I can leave a comment there?)

**Comment by vitorlfaria** [comment]
> Take a look into your network devtools. There you can see which url is being used for the request and you can see the response. You are making a wrong request here. Not really something we can help you with, I'm sorry.
> 
> As for that `createRequest` helper: there seems to be a tutorial out there teaching that. The person writing that seems to have pretty much missed the point. That's what `fetchBaseQuery` already does, via `prepareHeaders`. You really don't need such a function. Maybe go for another tutorial? (Also, can you link me which tutorial that is so that I can leave a comment there?)

Thanks! the error was the way I was setting wrongly the .env variable, without REACT_APP_.
And I changed the API configuration to use prepareHeaders.
And finally this is the video: https://www.youtube.com/watch?v=9DDX3US3kss
