### ISSUE TITLE
RTK Query: injectEndpoint exports types borked - advice for typing mutation/query hooks

### ISSUE THREAD

**Issue by dylmye** [reduxjs/redux-toolkit#2713]
Hi lovely Toolkit people!

I have an issue that I suspect you already are aware of, but I can't find any issue ticket for - that the type definition of `injectEndpoints`' return doesn't include any of the endpoints defined within it. See [this code sandbox](https://codesandbox.io/s/jolly-tharp-ns1h29) based on the `@examples-query-react/basic` template, specifically the export of **src/services/endpoints.ts**:

> Property 'useGetPokemonByNameQuery' does not exist on type `Api<BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, {}, "api", never, unique symbol | unique symbol>`.

That second part of the `Api` type from injectEndpoints, `{}`, is where we expect the typed endpoints to be, right? 

I say that I think it's expected, as the documentation on [Code Splitting](https://redux-toolkit.js.org/rtk-query/usage/code-splitting) says "it [`injectEndpoints`] cannot modify the types for the original definition."

So my question is, if this behaviour is expected, what is the best way to type our mutation and query hook exports? Are we just supposed to `@ts-ignore` every export? We are going to be creating 30+ files for endpoints as we are migrating a large API so I want to make sure we are getting this pattern right the first time round.

Thanks for your time in advance.

**Comment by phryneas** [comment]
It should be `export const { useGetPokemonByNameQuery } = endpoints;`, not `export const { useGetPokemonByNameQuery } = pokemonApi;` - we cannot change the TypeScript types of variables defined in other files.

Is this really from one of our examples?

**Comment by dylmye** [comment]
Thank you! No, I adapted it from the advanced example, I just moved the endpoints into their own file to mimic the issue I was having on our proprietary setup.

I'll double check this fixes it for me tomorrow morning, and close the ticket if so 👍

**Comment by dylmye** [comment]
Weird, I'm still having issues on my local. The only difference I see between my code and the sandbox really is that `createApi` is imported from `@reduxjs/toolkit/query` instead of `@reduxjs/toolkit/query/react`.

Basically the module I'm making is sharing the store between a web (non-react) project and a mobile (react native) project. Perhaps I need to re-think this.

**Comment by dylmye** [comment]
Thanks for your speedy and helpful responses.
