### ISSUE TITLE
Recipe: Prefetch Immediately Implementation In Documentation Causing "TypeError: Cannot read properties of undefined (reading 'select')"

### ISSUE THREAD

**Issue by DevYemi** [reduxjs/redux-toolkit#2714]
Hi there, I'm following the template in the documentation on how to prefetch an endpoint immediately and i keep getting this Type Error

![redux-toolkit-error](https://user-images.githubusercontent.com/68167320/191587162-5c5669af-63ee-4ce4-8d53-1592ee2378cc.jpg)

This is my usePrefetchImmediately custom hook implementation

`function usePrefetchImmediately(endpoints, arg = {}, options = {}) {
    const dispatch = useDispatch()
    useEffect(() => {
        dispatch(apiSlice.util.prefetch(endpoints, arg, options))
    }, [arg, endpoints, options, dispatch])
}

export default usePrefetchImmediately;`

i use the custom hook in another component as 

`usePrefetchImmediately('getAllCategory');`

i'm using
"next": "12.2.5"
 @reduxjs/toolkit": "1.8.5"
"react-redux": "8.0.2"

**Comment by markerikson** [comment]
We'd really need to see a repo or CodeSandbox showing what you're trying to do.
