### ISSUE TITLE
Update mutation cache with fixedCacheKey from another mutation

### ISSUE THREAD

**Issue by DaimonX** [reduxjs/redux-toolkit#2716]
Hello. Is it possible to manually update the cache with 'fixedCacheKey' via 'updateQueryData' from another mutation in pessimistic way ?

I have a situation where I'm uploading file (kinda csv) with thousands rows and columns to the server for validation of each cell. This part is done using the mutation endpoint (response is huge array with validated fields, values, and error messages):
```js 
uploadFile: build.mutation({
      query: ({ formData, userId }) => ({
        url: "uploadfile",
        method: "POST",
        body: formData
      })
})
```

And in my components im using it is like:
```js 
const [triggerUploadFile, {
      isLoading: pricatIsLoading,
      data: pricatUploadResponse
    }] = api.useUploadFileMutation({
      fixedCacheKey: 'shared-upload',
    });
```

//elsewhere in component
```js
triggerUploadFile({formData, 'testId'})
```
After that im doing manual validation of each field through UI. And sending validation request for specific field which user want to revalidate and i dont want revalidate full file as i for sure now updates for specific field. I want just update it in cache at specific field.

I tried to do it inside another mutation `validateField` dispatching updateQueryData like

```js
const patchResult = dispatch(api.util.updateQueryData(
    'uploadFile',
    'shared-upload',
    (uplodedFileDraft) => {return updateduplodedFileDraft}
)
```
inside update functiomn i  see and can modify data but it does not updates my 'shared-upload' cahce.

Would be appreciated for any help and advice. Thank you.

**Comment by phryneas** [comment]
No, `updateQueryData` only updates **query** data. There is no mechanism to do this for mutations, because mutations are generally not really meant to stay around for long. In that case you probably have to copy data into a separate slice.

**Comment by DaimonX** [comment]
Thanks for so fast response. What approach i can take for my case ? Is RTK fit here at all ?

**Comment by DaimonX** [comment]
@phryneas hmm. Thanks, will try to do it as you suggest ❤️
