### ISSUE TITLE
RTK Query - InvalidateTags on persisted slices

### ISSUE THREAD

**Issue by manceau-jb** [reduxjs/redux-toolkit#2717]
Hey,

I need to invalidate some query tags via the mutation `invalidatedTags`, on a persisted API.
No problem if there is the queryCacheKey in the subscription slice.

```
{
   "queries":  {
        "getPosts({ "week": 38 })": { /*...*/ },
        "getPosts({ "week": 39 })": { /*...*/ },
   },
   "subscriptions": {
        "getPosts({ "week": 38 })": {}, // unsubscribed
        "getPosts({ "week": 39 })": { "3FllFUeQ6BOlCB_8VomBL" : { /*...*/ } }, 
   },
   // ...
}
```

Except that once the store is rehydrated, subscriptions no longer contain the queryCacheKey (`extractRehydrationInfo`...).

```
{
   "queries":  {
        "getPosts({ "week": 38 })": { /*...*/ },
        "getPosts({ "week": 39 })": { /*...*/ },
   },
   "subscriptions": {},
   // ...
}
```

So we do not pass the following condition, and therefore it is impossible for me to invalidate the tags.

https://github.com/reduxjs/redux-toolkit/blob/7c3129c46c173902801d4f6143cd9ef88b5ee553/packages/toolkit/src/query/core/buildMiddleware/invalidationByTags.ts#L74

How can I invalidate my queries after a rehydration ?

All help is welcome, thanks!

**Comment by phryneas** [comment]
Hm, it should probably be
```
        const subscriptionSubState = state.subscriptions[queryCacheKey] ?? {}
        if (querySubState ) {
```
can you test that and maybe open a PR?

Generally: correct behaviour here should be that that stuff gets removed if you invalidate it before having a component subscribe to it.
