### ISSUE TITLE
Accessing meta / raw response

### ISSUE THREAD

**Issue by alexandernst** [reduxjs/redux-toolkit#2723]
Is there a way to access the `meta` object or the raw `response` in a query handler?

Eg:

```js
const myApiSlice = createApi({ ... });

const [getFoo, { isFetching }] = myApiSlice.useLazyGetFooQuery();

getFoo({ ...params }).then(res => {
    console.log(res.meta); // <-- "meta" is not available here
});
```

Edit: I'd like to be able to access `meta` (or the raw `response`) in all my handlers, not just in the handler of a particular endpoint (`getFoo()` in this example).

**Comment by alexandernst** [comment]
@phryneas I'm making an educated guess that this reply is yours: https://stackoverflow.com/a/73835565/940158

I'm currently generating my API with `@rtk-query/codegen-openapi`. This means that I can't use `transformResponse` because I would have to copy&paste all the generated code and add the `transformResponse` to each endpoint (which would be really bad).

Can you consider adding the `meta` object to the object that is being passed to the fulfillment callback?

If "no", can you suggest me how should I work around this problem?

**Comment by phryneas** [comment]
@alexandernst you would not copy/paste that to another file.
You should import the auto-generated api into another file and use `enhanceEndpoints` to add your `transformResponse`. 

Unforunately, making `meta` available outside of `transformResponse` would mean moving non-serializable data into the store which would break SSR and persistence.

**Comment by alexandernst** [comment]
@phryneas I have my `apiSlice.ts` (manually created by me) and my `autoApiSlice.ts` (which is generated following your guide: https://redux-toolkit.js.org/rtk-query/usage/code-generation ).

This leaves me with the following situation:

### apiSlice.ts

```js
export const apiSlice = createApi({
    baseQuery: ... <my custom baseQuery with auth headers>,
})
```

### autoApiSlice.ts

```js
import { apiSlice as api } from "./apiSlice";
const injectedRtkApi = api.injectEndpoints({
   ... <generated code>
});
export { injectedRtkApi as autoApiSlice };
```

### openapi-config.js

```
const config = {
  schemaFile: "http://********************/docs/openapi.json",
  apiFile: "./src/store/apiSlice.ts",
  apiImport: "apiSlice",
  exportName: "autoApiSlice",
  outputFile: './src/store/autoApiSlice.ts',
  hooks: true,
}

module.exports = config;
```

I can't import `autoApiSlice` in my `apiSlice` because that would create a circular import. How can I use `enhanceEndpoints`?

----

> Unforunately, making meta available outside of transformResponse would mean moving non-serializable data into the store

Can you at least consider exposing the headers to the fulfilled callback? Headers are serializable.

**Comment by phryneas** [comment]
@alexandernst this is the recommended pattern with the api codegen:

### baseApi.ts

```js
export const baseApi = createApi({
    baseQuery: ... <my custom baseQuery with auth headers>,
})
```

### autoApiSlice.ts

```js
import { baseApi as api } from "./baseApi";
const injectedRtkApi = api.injectEndpoints({
   ... <generated code>
});
export { injectedRtkApi as autoApiSlice };
```

### actualApiSlice.ts

```js
import { autoApiSlice } from "./autoApiSlice";
export const finalapi = api.enhanceEndpoints({
   ... <your code to add `transformResult` to injected endpoints
});
```


That way that file in the middle can always be autogenerated.

> Can you at least consider exposing the headers to the fulfilled callback? Headers are serializable.

Headers are specific to http. RTK Query works with all different kinds of things, not only http.

**Comment by alexandernst** [comment]
> That way that file in the middle can always be autogenerated.

Thank you! I'll try this approach and let you know if it worked for me.

> Headers are specific to http

I do understand that, but:

a) Accessing headers is not an uncommon pattern
c) Serializing the headers and adding them [here](https://github.com/reduxjs/redux-toolkit/blob/028a990a41d76156135cf068ae83a73e07d85880/packages/toolkit/src/query/core/buildThunks.ts#L342) (only if the request/response were made via HTTP) won't cause any harm to nobody, it won't be a breaking change and it won't cause any performance issues. It will also make it possible for people to access headers directly, rather than patching the API with `enhanceEndpoints`.

I really can't see any negative sides for exposing the serialized headers in the fulfilled callback.

**Comment by phryneas** [comment]
> I really can't see any negative sides for exposing the serialized headers in the fulfilled callback.

RTK Query has no concept of "Headers". 
"Headers" are a concept that is in play only if you use `fetchBaseQuery`.

RTK Query itself is 100% agnostic of any type of transport being used. RTK Query calls a function (either only `queryFn`, or `query`, which will then be passed into `baseQuery`). Then it takes the result of that function and puts it into `data`.

If you want to put a response header into `data` every single time, you can wrap `baseQuery` somehow like this:


```js
const baseQuery = fetchBaseQuery(...)
function wrappingBaseQuery(...args){
  const result  = fetchBaseQuery(...args)
  if (!('data' in result))  return result

  return { data: { ...result.data, header: meta.response.headers.someHeader }, meta }
}
```

**Comment by alexandernst** [comment]
If I understand correctly this code, this will wrap the response from the backend (payload) in another object, which would force me to convert my code from:

```js
getFoo({ ... }).then(response => {
    do_stuff(response.data);
});
```

to

```js
getFoo({ ... }).then(response => {
    do_stuff(response.data.data);
});
```

which is not ideal.

Maybe there should be a way to modify the `response` object in my example, rather than modifying the `data` object inside the `response`?

**Comment by phryneas** [comment]
No, it would only add an additional property `header` on `data`. The return value of `baseQuery` is always in the form `{data, meta}` or `{error, meta}`.

**Comment by alexandernst** [comment]
Ah, indeed, I just tested it. It just adds an additional property to data. But, actually, this is even worse, because this approach assumes that `data` will be an object (which it won't if the API is returning an array; eg, when I'm fetching an endpoint that will enumerate stuff).

Fixing this would require me to do what I mentioned in my previous reply, which is not ideal.
Not really sure how to proceed form here 😕 . IMHO, what I said in the last part of my last message: there should be a way to modify the object that is passed to the fulfilled callback, rather than hacking the payload object itself.

**Comment by phryneas** [comment]
The object that is returned to the fulfilled callback is just a snapshot of the Redux store. 

This would require changing the whole internal data structure of RTK Query and tons of internal concepts as well as touching an enormous amount of types. I'm sorry, but this is not going to happen.  

Http requests are one use case of the library, but we are not going to shape the core after it.  
The nice thing is that you can use this with everything that returns a promise. Access a calendar in React Native? Sure. Use it server-side to query a database? Sure.

Promises also don't resolve to two values and neither are we going to start that. If you need something like that, you can nest. And all that is stopping you from doing that right now is your sense of aesthetics. (you can of course return something like `{ data: { data, headers} }`)

If something like
```js
.then(response => {
    do_stuff(response.data.data);
});
```
bothers you, write a helper that allows you to call
```js
.then(withData(do_stuff));
```
instead.

That'd be just
```js
function withData(callback) {
  return response => callback(response.data.data)
}
```
You just have to get a bit creative.

**Comment by phryneas** [comment]
All that said, I would say that in most cases you probably should not call `trigger().then(doSomething)` at all. 

If this is an always-side-effect, it should probably be part of the endpoint lifecycle (which can access `meta` as well). 

If it is something to happen only in the component, it sounds dangerously like deriving data and calling a state setter - and that should happen in a `useMemo` on next render.

**Comment by alexandernst** [comment]
I'm sorry if I made you believe I was suggesting to entirely change how RTK works, I was not.

Fair enough, I'll wrap my payloads.
