### ISSUE TITLE
Error when trying to access `error` props with typescript - RTK Query

### ISSUE THREAD

**Issue by LoyalPotato** [reduxjs/redux-toolkit#2732]
I have an api using `fetchBaseQuery` with a query.

In the component I'm using the exported hook for the query like so:

```js
  const {
    data,
    isFetching,
    isSuccess,
    refetch,
    error,
  } = useGetFooQuery({
    param,
  });
```

When I try to access a prop on the `error` object, such as `status`,
```js
    console.log(error?.status)
```
I get a typescript error with the following message:
>Property 'status' does not exist on type 'FetchBaseQueryError | SerializedError'.

Only if I cast the error object as `FetchBaseQueryError` can I access it.

**Comment by markerikson** [comment]
Yes, this is because the `error` field _could_ be one of two different types, which have different potential fields inside. You'll need to do a conditional check like `if ('status' in error)` to get TS to let you check that.
