### ISSUE TITLE
Protected property in an inherited class causes createSlice to error

### ISSUE THREAD

**Issue by vocko** [reduxjs/redux-toolkit#2733]
I think this is more a question than a bug. I was trying to look through other issues and blog posts but can't find an answer to a problem we are facing.

We are using Nswag to generate typescript api, using the class method. The problem we have is when a polymorphic structures are being generated. The structure looks generally like this:

```Typescript
export class ParentTypeDto implements IParentTypeDto {
    // own properties here...

    protected _discriminator: string;

    constructor(data?: IParentTypeDto ) {
        super(data);
        this._discriminator = "ParentTypeDto";
    }
    
    init(_data?: any) {
        super.init(_data);
        // property initializations
    }
    
    static fromJS(data: any): ParentTypeDto {
        // deserialization code here
    }

    toJSON(data?: any) {
        // serialization code here
    }
}

export class ChildTypeDto extends ParentTypeDto implements IChildTypeDto {
    // own properties

    constructor(data?: IChildTypeDto) {
        super(data);
        this._discriminator = "ChildTypeDto";
    }
    
    // init, fromJS, toJSON methods...
```

Because the `_discriminator` property is only defined in the parents and marked as protected, the Draft doesn't find it for some reason and createSlice call fails on an error on reducers (error shortened):

```
Types of property 'stateProperty' are incompatible.
Type 'WritableDraft<ChildTypeDto> | null | undefined' is not assignable to type 'ChildTypeDto | null | undefined'.
Property '_discriminator' is missing in type 'WritableDraft<ChildTypeDto>' but required in type 'ChildTypeDto'.
```

Could someone please point me into a direction how to resolve this? I'm quite new to the Redux toolkit library and thus my knowledge is not as broad, but could not find any source that would give me an understanding what is the actual problem.

**Comment by vocko** [comment]
@markerikson Hi Mark, thank you for a quick answer.

I think the problem is how NSwag generates the nested classes. It creates an interface for each class and then the interface is implemented by a class. However, if the class has an object as it's property, the object is listed with it's class name not the interface name. And here comes the problem for redux as the object is then not serializable.

```Typescript
class MyType implements IMyType {
    
    property: MyOtherType; // <-- here is the problem as this should be defined as IMyOtherType
}
```

The `_discriminator` issue comes with it when the property object that is listed as a class inherits from some other object and that's where the discriminator field comes to play.

Anyway, as per your answer, we have to avoid putting class objects into the store what should solve the whole problem. I think the problem lies in how the NSwag generates the objects or how we use it to generate them.

Thank you very much for your help, I'm closing this ticket now.

**Comment by markerikson** [comment]
Hah, yeah, that does sound confusing :)
