### ISSUE TITLE
rejectWithValue and fullfillWitValue seems to be wrong typed

### ISSUE THREAD

**Issue by pedrosantos-hotmart** [reduxjs/redux-toolkit#2744]
Hi there! We're trying to add meta to my fulfillWithValue/rejectWithValue functions on a asyncThunk.

When logging the thunk api from the thunk, we can see it as 2 arguments function, as it is described in the docs. But when trying to use it with typescript, it is typed with only one argument so we can only use it by disabling typescript for the line (or maybe creating another type).

<img width="872" alt="image" src="https://user-images.githubusercontent.com/81707488/193817845-418649d9-05a0-4a40-bf48-2891014904db.png">

**Comment by vbanuelos** [comment]
@pedrosantos-hotmart -- 
What was the resolution? I'm on the latest and still seeing this behavior.

**Comment by pedrosantos-hotmart** [comment]
You have to type the value you have to type your fulfilledMeta and/ir rejectedMetq
