### ISSUE TITLE
Typescript error when dispatching action in middleware with Redux Toolkit

### ISSUE THREAD

**Issue by andra961** [reduxjs/redux-toolkit#2747]
I have carefully set up everything as the documentation says.

```
const rootReducer = combineReducers({...})
const store = configureStore({
    reducer: rootReducer,
    middleware: (getDefaultMiddleware) => getDefaultMiddleware().concat(myMiddleware),
})
export default store
export type AppDispatch = typeof store.dispatch
export type RootState = ReturnType<typeof rootReducer>

export type ThunkAPI = {
    dispatch: AppDispatch
    state: RootState
    rejectValue: {errorMessage: string}
}
export const useAppDispatch = () => useDispatch<AppDispatch>()
```

However, if i try to dispatch actions from my middleware, i get this error: 

```
const websocketMiddleware: Middleware<
    {}, 
    RootState
> = (store) => {
    store.dispatch(mythunk()) //Argument of type 'AsyncThunkAction<void, void, ThunkAPI>' is not assignable to parameter of type 'AnyAction'
    ...
}
```

Do note that this happens only if i dispatch from the store given as input in the middleware. If i dispatch the same action from a component using the useAppDispatch() hook everything works fine.

**Comment by phryneas** [comment]
If you write a custom middleware that middleware per default only can assume that you have no other middlewares. If you need a specific type of dispatch to be available, you'll have to tell that to the types:
``
const websocketMiddleware: Middleware<
    {}, 
    RootState,
    ThunkDispatch
>
```
