### ISSUE TITLE
Add ability to clear data after request is executed for endpoints

### ISSUE THREAD

**Issue by marcusjwhelan** [reduxjs/redux-toolkit#2748]
This is hard to explain so I will do it in parts. First the steps and what is expected and also what would be useful all around

Steps for use case
1. get list of data (list is cached) great this works perfect
2. get specific element on select (it is cached) great
3. working on a form related to this data and submitting a patch (this form is not a new page and the user is focused back on the list component that also houses the get results, because it is the main page it never unmounted
4. Now the get data is still there and the component that only opens up when the get data is present opens and the user is now confused to why the component they just finished updating is opened again with the old data.

What would be useful
1. get list
2. get specific element (cached, but not left in the result data section)
3. working in form, form component closes
4. the form component doesn't open up because the useEffect watching the data doesn't see data in the result but the cache is still available in redux if needed in other use cases. 

Simply that queries would hold data but not hold it in the data section after the request. 

So steps like
1. get data
2. set response to data in result for instance like in `const [trigger, result]  = useLazyQuery()`
3. User useEffect on the data
4. the data is kept but not in the `data` of the result anymore so that useEffects watching for new data to fire off from don't re-execute because the component re-rendered and there is still data in the result.

If that is not possible within the api slice maybe another hook for query endpoints to clear out the data as an optional hook. Right now I make a custom hook to simply clear the data out.

```typescript
export const useInvalidateGet = (id: number | string) => {
  const dispatch = useAppDispatch()
  return () => dispatch(api.util.updateQueryData('get', id, (draft) => {
    draft.data = null
  }))
}
```

I think an alternative would be the ability to set the draft to undefined or null or {} or something similar to signify it being cleared

```typescript
export const useInvalidateGet = (id: number | string) => {
  const dispatch = useAppDispatch()
  return () => dispatch(api.util.clearUpdateQuery('get'))
}
// or better yet
export const {
  useClearGetQuery
} = api
```

**Comment by marlonschlosshauer** [comment]
> Steps for use case
> 
>     1. get list of data (list is cached) great this works perfect
> 
>     2. get specific element on select (it is cached) great
> 
>     3. working on a form related to this data and submitting a patch (this form is not a new page and the user is focused back on the list component that also houses the get results, because it is the main page it never unmounted
> 
>     4. Now the get data is still there and the component that only opens up when the get data is present opens and the user is now confused to why the component they just finished updating is opened again with the old data.

If I understood correctly, the data that you previously fetched should be invalidated, because you mutated it in some way? I use the [RTK Queries Tag](https://redux-toolkit.js.org/rtk-query/usage/automated-refetching#definitions) system for that. 

The`query` that fetches data uses `providesTags` and the `mutation` that changes related data uses `invalidatesTags` (with the same tag).  Result: As soon as the I run my `mutation`, my app begins to fetch data again.

Here is an example:
```js
const groupExtension = api.injectEndpoints({
    endpoints: builder => ({
	getHome: builder.query({
	    query: () => ({
		document: getGroups,
	    }),
	    providesTags: ['Groups'],
	}),
	joinGroup: builder.mutation({
	    query: name => ({
		document: joinGroupMutation,
		variables: { groupName: name },
	    }),
	    invalidatesTags: ['Groups'],
	})
    }),
})
``` 

Tags really allow you [to go crazy](https://redux-toolkit.js.org/rtk-query/usage/automated-refetching#general-tag).
