### ISSUE TITLE
DevTools - Nothing post @@init

### ISSUE THREAD

**Issue by eghernqvist** [reduxjs/redux-toolkit#2753]
Hi! Unsure which repo to post this issue in. Please redirect me if this is the wrong repo.

I'm setting up a stack with `next` and `@redux/toolkit` connected with `next-redux-wrapper`. After setting up a minimal example following [these](https://redux-toolkit.js.org/rtk-query/usage/server-side-rendering#server-side-rendering-with-nextjs) instructions, I get nothing beyond the initial `@@init` action in my devtools.

I've set up a [minimal reproduction repo here](https://gitlab.com/pincho-nation/next-redux-devtools-repro/-/tree/main).

## Steps to reproduce

1. Clone above repo
2. Run `npm run dev`
3. Inspect the page with redux devtools
4. Click button "Run a fetch via api via redux"
5. Note that there are no action logged in devtools

I've tried all steps applicable in [the redux devtools troubleshooting guide](https://github.com/reduxjs/redux-devtools/blob/main/extension/docs/Troubleshooting.md) to no avail.

Redux devtools version: 3.0.11
Chrome version: 106.0.5249.91
OS: Windows 10

Any clue what else to try?
Cheers!

PS.
Images of the devtools and logged actions from reducer:
![Create_Next_App_-_Google_Chrome_2022-10-06_15-41-02-722](https://user-images.githubusercontent.com/10044687/194328617-0943ee92-cf91-48db-b787-f331bfdcfdcb.png)
![Create_Next_App_-_Google_Chrome_2022-10-06_15-41-24-276](https://user-images.githubusercontent.com/10044687/194328621-94cdf68b-f03d-4e35-9908-fb51ed2ebc56.png)

**Comment by phryneas** [comment]
Your application is creating more than one store. (see the dropdown in the top right)

While your `wrapper` creates a store for your application, you also create an additional one before that and export it as `default`.

```js
const store = makeStore();
setupListeners(store.dispatch);

// this is the only of these lines that should stay!
export const wrapper = createWrapper(makeStore, { debug: false });

export default store;
```

It also means that you set up the listeners for one store and then the application uses another store.

**Comment by eghernqvist** [comment]
Oh my. What a silly mistake. Is there anywhere I would be able to see this being the issue, in some logs or anything? Otherwise it feels like quite an obscure thing to fail on.

Thanks for the help!

**Comment by phryneas** [comment]
We can't stop you from creating many store instances - often you even want to do that, e.g. during testing. So I'm sorry, there's nothing we really can do.
Weird that you have only one store in that dropdown - but just to confirm: it works after removing those lines?

**Comment by eghernqvist** [comment]
Fully understandable! Just wondered if you had some place I missed where you saw that being the cause 😊

Indeed, it does work properly after changing the store creation.

**Comment by eghernqvist** [comment]
Created a PR for the troubleshooting docs of devtools extension, which would have caught this for me early!
https://github.com/reduxjs/redux-devtools/pull/1237
