### ISSUE TITLE
error with typings in useMutation

### ISSUE THREAD

**Issue by im-isidorov** [reduxjs/redux-toolkit#2769]
package json:
  "@reduxjs/toolkit": "^1.8.6",
    "react-redux": "^8.0.4",

real code
<img width="853" alt="image" src="https://user-images.githubusercontent.com/106147668/195336401-f752796a-4455-452a-a1e7-352ea738e4cd.png">

from docs
<img width="976" alt="image" src="https://user-images.githubusercontent.com/106147668/195344641-93f91dc4-6b63-4832-8cfa-3777b81c8b8e.png">

**Comment by phryneas** [comment]
That example is not TypeScript. For TypeScript, see [type safe error handling](https://redux-toolkit.js.org/rtk-query/usage-with-typescript#type-safe-error-handling)

**Comment by im-isidorov** [comment]
> That example is not TypeScript. For TypeScript, see [type safe error handling](https://redux-toolkit.js.org/rtk-query/usage-with-typescript#type-safe-error-handling)

Can I reassign the error type without SerializedError? I want use only FetchBaseQueryError type.
Error handling becomes very uncomfortable because of SerializedError

**Comment by phryneas** [comment]
You cannot know it was not a `SerializedError`, that's why it's there. 
If any of your code throws an error anywhere, that will be a `SerializedError`.

We can't tell what it is, because it is your code. But we have to keep the option in mind that it could happen.
