### ISSUE TITLE
'RootState' circularly references itself

### ISSUE THREAD

**Issue by tsarapke** [reduxjs/redux-toolkit#2770]
Hello there!

We are migrating our applications to use `@reduxjs/toolkit` and faced with issue of `RootState` circularly references itself, and `store` implicitly has type `any` when we are trying to specify state type of `createAsyncThunk<Blob, { height: number, width: number }, { state: RootState }>`.

[Reproduction](https://codesandbox.io/s/suspicious-dust-21xs2b?file=/src/store/store.ts)

Screenshot:
![image](https://user-images.githubusercontent.com/7983863/195456607-50514eaf-b26e-4d04-906a-7d1b7185204d.png)

We've already read some of existing topics here, like:
https://github.com/reduxjs/redux-toolkit/issues/2462
https://github.com/reduxjs/redux-toolkit/issues/2237
https://github.com/reduxjs/redux-toolkit/issues/1126
https://github.com/reduxjs/redux-toolkit/issues/324

But don't found any solution to handle it.

In addition, it would be nice to have exposing of `AsyncThunkConfig` from `@reduxjs/toolkit`, as for now there is no way infer that type in slice/reducer custom factory (only by specifying `any`)
![image](https://user-images.githubusercontent.com/7983863/195457970-458ae017-1c2f-4cab-9561-08097652b491.png)

**Comment by markerikson** [comment]
The main fallback option for this sort of issue is to infer the `RootState` type from the root reducer separately, instead of from `store.getState`:

```ts
const rootReducer = combineReducers({
  a: sliceA.reducer
})

type RootState = ReturnType<typeof rootReducer>;
```

Does that help?

**Comment by tsarapke** [comment]
@markerikson Unfortunately no, it doesn't.
It solves the issue with type of `const store`, so it doesn't of `any` type anymore.
But `RootState` still circularly references itself.
![image](https://user-images.githubusercontent.com/7983863/195509422-0d4fc01b-66bc-4e7d-97e0-9d94fd69639d.png)

**Comment by phryneas** [comment]
One of your slices references `RootState`. In that case, you have to type that slice reducer on export.

So
```ts
export default slice.reducer
```
becomed
```ts
export default (slice.reducer as Reducer<typeof initialState>)
```

**Comment by tsarapke** [comment]
@phryneas 
It also doesn't help. At reproduction link, I've already specify return type of slice.

V1:
![image](https://user-images.githubusercontent.com/7983863/195524364-d6758851-c40c-4b68-83d7-4479995a13e1.png)

V2
![image](https://user-images.githubusercontent.com/7983863/195524484-b085e5ff-cc96-4ca2-853a-013f7ac0a3f2.png)

**Comment by phryneas** [comment]
Do `fetchImage2` or `ImageState` rely on the type of `RootState`?

**Comment by tsarapke** [comment]
`fetchImage2` rely on `RootState`. `fetchImage2` is async thunk where we want to use `getState`.
![image](https://user-images.githubusercontent.com/7983863/195790162-8e023641-b07e-475d-8a9f-a1bf0b90c8bf.png)

`ImageState` doesn't rely on `RootState`. `ImageState` is a part of `RootState`.
![image](https://user-images.githubusercontent.com/7983863/195790533-cc5e56c1-6b91-4fbe-b2cc-6a9099a855e5.png)

**Comment by phryneas** [comment]
Well, there you have your circular type reference.

Honestly, I can't do much with screenshots. If you give me a TypeScript playground that is complete enough to replicate your problem I can take a quick look and give a recommendation on how to solve it in your case.

**Comment by tsarapke** [comment]
@phryneas, actually I left link to playground at the topic-starting message (**[here is duplicate](https://codesandbox.io/s/suspicious-dust-21xs2b)**)

![image](https://user-images.githubusercontent.com/7983863/195825243-8dfe320e-2cae-4a3c-86fb-1902efd3d619.png)

If passing state to generic type of async thunk makes circular reference, why do we need it at all? From another side, how we will know about type returned by `getState`? Don't you find it strange?

**Comment by phryneas** [comment]
I'll take a look later, missed that part. Thanks.

Generally: something like this is usually not a problem if you just write normal logic. But if you add wrapping logic like you are doing here, it gets problematic. That's just TS being TS.

**Comment by phryneas** [comment]
So, after taking a look, you can interrupt that circle by doing something like
```js
const image1Slice = createImageSlice("image1", fetchImage1) as Reducer<ImageState, AnyAction>;
const image2Slice = createImageSlice("image2", fetchImage2) as Reducer<ImageState, AnyAction>;
```

The problem is really that the `fetchImage2` needs the type of `RootState`, which depends on `rootReducer`, which depends on `imageReducer`, which depends on `image2Slice` - which then depends on `fetchImage2` -  a circle. And you have to break the circle at one point.

Generally, if I may ask: 
* why are you writing this by hand instead of using RTK Query, which would do that job for you? You are essentially recreating that here.
* are you really *really* sure you want to store images in the Redux store? Those should usually not be in JavaScript memory at all.

**Comment by tsarapke** [comment]
Answering questions:
  - we are doing smooth migration step-by-step. We can't do it at one time. It very long process that must be done carefully. We have some middlewares that rely on current api wrapper. So we can't use RTK for now. We have micro frontend, about 8 apps with huge business logic. So.... yeah.
  - we don't store images in Redux store, it would be a really bad idea. These reducers stores `requestId`, but not the images themselfs. In our app it also could store some meta-info (`object`) along to `requestId`.

Regarding to recursion. It's sad that we forced to use type casting (not real fan of it). BTW, `createImageSlice` already returns `Reducer<ImageState, AnyAction>`. Why it doesn't help?
![image](https://user-images.githubusercontent.com/7983863/195855066-2da0cc45-903f-438a-88b1-a88dcf7dadad.png)

It seems to me like the issue is not in asyncAction usage by the slice, but in arguments types of factory. When you will remove generic type and make `asyncAction` to be `any` - it starts work fine. But usage of `any` is not safe though.
![image](https://user-images.githubusercontent.com/7983863/195860318-c08b50de-51ba-4017-aae6-7e6605797bd0.png)

**Comment by phryneas** [comment]
> Regarding to recursion. It's sad that we forced to use type casting (not real fan of it). BTW, createImageSlice already returns Reducer<ImageState, AnyAction>. Why it doesn't help?

Honestly, I do not know. This is a TypeScript quirk - we cannot do a lot about it.

And yes, changing your factory function in some way could also do that, but as you noticed it's not the best idea either.

In the next TS version, it will be possible to do
```ts
const image1Slice = createImageSlice("image1", fetchImage1) satisfies Reducer<ImageState, AnyAction> as Reducer<ImageState, AnyAction>;
const image2Slice = createImageSlice("image2", fetchImage2) satisfies Reducer<ImageState, AnyAction> as Reducer<ImageState, AnyAction>;
```
which is also not more beautiful but will at least be typesafe despite being a cast.

**Comment by tsarapke** [comment]
Yeah.
Anyway, for now we decided to use type casting as temp workaround until we get close to RTK. Good thing there aren't many places like this. Don't really like to break the code of conduct 🙂

Another question - why do you not expose `AsyncThunkConfig` from `@reduxjs/toolkit`, so it may help to create some predefined configs types by extending this one?

**Comment by phryneas** [comment]
> Don't really like to break the code of conduct slightly_smiling_face

You **really** should not have a code of conduct that disallows the `as` keyword. It should not be overused, but there will always be edge cases where the programmer knows something the compiler does not and in those cases it is perfectly fine to use it. Pretty much every TypeScript teacher/book author I know agrees on this.

> Another question - why do you not expose AsyncThunkConfig from @reduxjs/toolkit, so it may help to create some predefined configs types by extending this one?

Because you can just as well extend from an empty object - that base object has no value or meaning.

You will be thrilled about https://github.com/reduxjs/redux-toolkit/pull/2604 though - it is available in our 1.9 alphas.

**Comment by Emiya0306** [comment]
@tsarapke  You can resolve the problem by [this workaround](https://stackoverflow.com/questions/64793504/cannot-set-getstate-type-to-rootstate-in-createasyncthunk). Enjoy it.
```typescript
import { AsyncThunk, AsyncThunkPayloadCreator, Dispatch } from '@reduxjs/toolkit';

import { RootState } from './store';

declare module '@reduxjs/toolkit' {
  // https://stackoverflow.com/questions/64793504/cannot-set-getstate-type-to-rootstate-in-createasyncthunk
  type AsyncThunkConfig = {
    state?: unknown;
    dispatch?: Dispatch;
    extra?: unknown;
    rejectValue?: unknown;
    serializedErrorType?: unknown;
  };

  function createAsyncThunk<
    Returned,
    ThunkArg = void,
    ThunkApiConfig extends AsyncThunkConfig = {
      state: RootState;
    },
  >(
    typePrefix: string,
    payloadCreator: AsyncThunkPayloadCreator<
    Returned,
    ThunkArg,
    ThunkApiConfig
    >,
    options?: any
  ): AsyncThunk<Returned, ThunkArg, ThunkApiConfig>;
}
```

**Comment by tsarapke** [comment]
@Emiya0306 Many thanks! I would prefer yours one. Looks more reasonable than continuous type-casting. Love it.

Probably one note. Maybe it would be better to describe `options` property too? Like:
```
options?: AsyncThunkOptions<ThunkArg, ThunkApiConfig>
```

**Comment by EgorKlimenchuk** [comment]
@tsarapke Hi, I just try to make same implementation , but any way I have getState: () => unknown
<img width="824" alt="Screenshot 2023-03-10 at 12 04 44" src="https://user-images.githubusercontent.com/101469756/224301147-e3bae13e-6c45-45eb-bc0f-b9b7b75e3111.png">
<img width="980" alt="Screenshot 2023-03-10 at 12 06 02" src="https://user-images.githubusercontent.com/101469756/224301171-9137903d-a555-46de-8742-e385510687ff.png">
<img width="782" alt="Screenshot 2023-03-10 at 12 06 24" src="https://user-images.githubusercontent.com/101469756/224301187-a7d10126-e974-4c8c-bd86-a610147d8f4c.png">

**Comment by tsarapke** [comment]
Hi @EgorKlimenchuk. What version of toolkit do you use?
BTW, I think you didn't make anything wrong. It just because that workaround is doesn't work for toolkit > 1.8.6.

In 1.8.6 they was export creator like this:
![image](https://user-images.githubusercontent.com/7983863/224341984-281a8923-b054-46b0-9131-7b4568c46fe0.png)

But in 1.9.0 in was changed. "creator" is generated in IIEF (Immediately Invoked Function Expression)
![image](https://user-images.githubusercontent.com/7983863/224342491-22141b1a-afca-4bc7-b4d6-aad325463558.png)

So it does not allows to overload module type export correctly.

**Comment by EgorKlimenchuk** [comment]
I have updatedredux/toolkit to 1.9.0 , and unfortunally it did't help me((

<img width="454" alt="Screenshot 2023-03-10 at 15 38 47 1" src="https://user-images.githubusercontent.com/101469756/224344691-cf1016c1-4639-47e7-9ee3-da15a0078caa.png">
<img width="598" alt="Screenshot 2023-03-10 at 15 39 48" src="https://user-images.githubusercontent.com/101469756/224344728-dab523a2-cd6f-4c58-bef5-ec3db2f0641e.png">

**Comment by EgorKlimenchuk** [comment]
@tsarapke aaa okey, but before update I was on 1.8.5

**Comment by tsarapke** [comment]
@EgorKlimenchuk if you are using 1.8.6 or below, it depends on env. But you should check if your typescript takes into account your `custom.d.ts` file

**Comment by EgorKlimenchuk** [comment]
@tsarapke Yes if I declare the type in custom.d.ts , I can see difference. For example I can directly change AsyncThunkConfig 

<img width="531" alt="Screenshot 2023-03-10 at 15 53 25 1" src="https://user-images.githubusercontent.com/101469756/224347796-4ab739a2-83b3-4a6e-968f-7ef22eb08d30.png">
<img width="822" alt="Screenshot 2023-03-10 at 15 53 50" src="https://user-images.githubusercontent.com/101469756/224347816-909cf267-2707-4fda-b950-cc6dcb906231.png">

**Comment by phryneas** [comment]
`createAsyncThunk.withTypes` has shipped by now, maybe it would be better to use that instead of trying to overwrite our internal types.

**Comment by EgorKlimenchuk** [comment]
@phryneas Can I wrap createAsyncThunk or do I have to use withTypes every time?

**Comment by EgorKlimenchuk** [comment]
@phryneas when I use createAsyncThunk.withTypes and import RootState into slice I have this circular error

<img width="932" alt="Screenshot 2023-03-10 at 20 24 16 1" src="https://user-images.githubusercontent.com/101469756/224407883-03365749-7957-46fb-bfac-5aa84b9bae59.png">

**Comment by phryneas** [comment]
> Can I wrap createAsyncThunk or do I have to use withTypes every time?

You do that once per project.

This is not about importing it into the same file, it is because you create an actual type circle of calls. Usually, that happens because you are omitting the `{}` of an `extraReducers` function, but it's impossible to tell without access to your code. I'd suggest you try to boil it down to a minimal reproduction that you can show.

**Comment by EgorKlimenchuk** [comment]
The first of my problem, I have this error 

![Screenshot 2023-03-11 at 10 56 19](https://user-images.githubusercontent.com/101469756/224478333-519d381f-72a0-481d-96c0-f3288a308a3a.png)

I found one solution in typescript.ts add "declaration": false. But honestly I don't want to do it, cause I might create another problem

**Comment by EgorKlimenchuk** [comment]
@phryneas 
The second problem even I enable "declaration": false and try to use the CreateAppAsyncThunk I have 2 problems: 
1. RootSate has circularly references itself . 
2. CreateAppAsyncThunk return any, but I think it happens because of 1 point

store/index.ts
![Screenshot 2023-03-11 at 11 19 10](https://user-images.githubusercontent.com/101469756/224479062-8d5718e8-cdb6-47fc-be07-59bcf30a1249.png)
![Screenshot 2023-03-11 at 11 26 21](https://user-images.githubusercontent.com/101469756/224479171-dd405b60-b9f6-4bae-9e38-a23c0ade34d5.png)


store/reducers/EditorDataSliceReducer.ts
![Screenshot 2023-03-11 at 11 18 00](https://user-images.githubusercontent.com/101469756/224479121-888d6b08-feff-4f51-aaba-31137b8da213.png)

**Comment by phryneas** [comment]
Comment out all of your reducers. 
Comment in reducers until the problem comes up. 
Boil it down to a minimal reproduction. 
Show it here.

Please don't give incomplete screenshots - nobody can help you with that.
I have yet to see a single car mechanic that could tell you what's wrong on the inside of the motor when showing them a photo of the left back corner of a car.
