### ISSUE TITLE
ESM module usage causes Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by alex-ketch** [reduxjs/redux-toolkit#278]
Hello there and thanks for this library!

I recently encountered an issue when trying to consume the ESM version of this library using Rollup.
The issue happens at runtime due to the following usage of `require`:

https://github.com/reduxjs/redux-toolkit/blob/afc11d9aaf559f6143274fd0ab530ad1ad7fd602/src/getDefaultMiddleware.ts#L57-L62

As mentioned [here]( (https://github.com/rollup/rollup/issues/1058)) and [here](https://github.com/apollographql/apollo-link/issues/558), the relevant Rollup plugin is unable to handle mixed use cases.
> Mixing import and require is definitely discouraged. The only way for Rollup to handle require statements is with rollup-plugin-commonjs, but that plugin will skip any files with import or export statements.
> — https://github.com/rollup/rollup/issues/1058#issuecomment-254187433

---

I've been working successfully with a local fix by changing `getDefaultMiddleware` to an async function, and altering the import to:
```diff
- var createImmutableStateInvariantMiddleware = require('redux-immutable-state-invariant').default 
+ var createImmutableStateInvariantMiddleware = await import('redux-immutable-state-invariant');
```

Let me know if you'd like me to make a PR for these changes.

Thanks again 👋

**Comment by markerikson** [comment]
The problem is that code _can't_ be async.  It has to be loaded synchronously, because we need to use it immediately as part of the store creation call.

I agree that the behavior here is screwy, but it was the only thing I could come up with to get it to load only in dev, and not affect a production bundle.

If there's a better solution, yeah, I'm interested.

**Comment by phryneas** [comment]
This is a bit of a tooling problem. Before using `tsdx`, we had the `rollup-plugin-strip-code` (see https://github.com/reduxjs/redux-toolkit/pull/161/files) in place that allowed us to strip different lines in different builds. That way, we could have `import` only for dev builds and nothing at all in prod builds - which would remove the need of a dynamic require.

But I don't think this type of custom configuration is possible with tsdx any more. If you wanted to do some investigations there, that would be very welcome though.

**Comment by markerikson** [comment]
Wait, are we not even using the strip-code plugin now?

We _should_ still be able to use that, as TSDX is built on top of Rollup, and we already customize the Rollup config some.

**Comment by alex-ketch** [comment]
I've been trying to play around with the repo to find a potential solution.
The `strip-code` plugin is being used @markerikson, but [only for `UMD` builds](https://github.com/reduxjs/redux-toolkit/blob/master/tsdx.config.js#L15), not `ESM`.

Right now, I'm trying to confirm if having a top level import of `redux-immutable-state-invariant` will get stripped out in production usage of ESM builds.
