### ISSUE TITLE
Providing tags via callback in RTKQ

### ISSUE THREAD

**Issue by radulle** [reduxjs/redux-toolkit#2780]
When providing tags via callback like in example given in https://redux-toolkit.js.org/rtk-query/usage/automated-refetching#providing-errors-to-the-cache sets both UNAUTHORIZED and Post after user logs in (UNAUTHORIZED is not removed). I believe providesTags should ensure that only the result from the last callback should be in `api.provided` (old tags should be removed).

**Comment by phryneas** [comment]
See #2721 and #2717 - this is already merged into the integration branch for the next release.
