### ISSUE TITLE
Feature request: support for making endpoint build generics more responsive to argument in query

### ISSUE THREAD

**Issue by AmyBlankenship** [reduxjs/redux-toolkit#2782]
We have Django endpoints that use Django dynamic nested fields (https://github.com/rsinger86/drf-flex-fields). In a nutshell, when you hit a django ORM endpoint, it just gives you the matching result(s) from a single table. Where there's a relationship, you get the ID that points to the other table in that property. When you use the "expand" query param, it will go get the contents of that record and put them in that property instead. For example, say you have a shopping cart and your order object has a FK to a customers table. If you don't use expand, you would get a number in the "customer" field, but if you said expand=customer, the customer field would have firstName, lastName, etc.

I would like to be able to lift the property from the query argument "up" somehow and use the actual value it was called with in the generics to be able to infer whether that property will contain just a number or the expanded value. I figured out how to create a type that made the alterations needed, but not how to use it in the generics. If it's already possible, I couldn't figure out how to do it. I think the task would also be simpler if the query could take more than one parameter, so you didn't have to dig down in the argument to get the information you're looking for.

It's possible that the "meat" of this could be handled in the planned Typescript addition to the documentation, but I clearly lack the skill to write that.

**Comment by phryneas** [comment]
That's just not possible because of TypeScript limitations. Generics like that get lost on type mappings. I'd love to allow for something to make a connection between argument and result, but it's not possible. You would need to create two endpoints for that.

**Comment by AmyBlankenship** [comment]
I was able to do some things that were somewhat similar--I just wasn't able to figure out that last bridging step of how to use it within someone else's logic. Note that not everything I do here is a 1:1 mapping--I was playing around with the concepts.
https://www.typescriptlang.org/play?#code/PTAEFsHsBMFMBtQDNICdQHdagM6XLAC4CWBOo0ku+RAFsQHYDmFxSSsqsDhoAhrz64ADrADGbYmNABrWAE8AUGMgMcvYakhjYOPKnIBeUAG9FoC6ACuOTgC5QACgBufeA-WpGTAJShDAHxOJgx8BA6u8AC+PgA05pYE4ABGnDj0wjgOLm4ehF7MfoGgANqRALrxUfzkKmqEANyKhPKioAAKWjp6aADSCkayCpBIoC2iI6Ca2rr6OE2KIMhWDGIkqmNUAFY2vDKM0KCThPQMMvzJkFa8tJAYY-TkGFfwh8+oMsqq6vzQ0J2QYT+JyQZJbBwmEpyeR5ApMcqw7xRWJTLTCAByYVgDgB3X0-XkOBR02EADU3FZsbh8t4ikEzJZQFxCFZUAxTAA6LmgrYokokzEEBGomY9Az8tGC2DlRwk8nwSk+KKKKILJYnYjkcbYTUMADkvBwogkSCkoG4VyYtBRqTEfBs2CwFFUBtkDDu-AY8g1zAuV14PMWYBO2CQ7N1rqEhE4XlN0igcEQKHQIbGfBwn21TN0VngvGMACUiKyGAAVVqwAA82smfD+AOEAQWdR+kWBepQkD1ze+vHgmsIOK6sz6AxK5WBJT1DtQepReqSqQMGRwevKauAWdonB1TzQJ3gswsX3qIrxsEOxn76g5XGgVh0jkcPOJw7FUrpv3+aOfYNfov0KUUUiOJTBiJoW0gQ8OXgSAmFlN9bGgHxFCDLg62oAh+FQEgxEPIlqT4HCLweRh9l9Rh+FYdgdx4VguDWYhVCDTBsHUIjeAwYgTiorMMG3LhWL1QSmEgbxNiOZxOAwLxoyOBh4HkTDsBJHBmgrUAACF01gcs2mMBlLBnBwGCsFJOCaRlFzSFcTLMpdLMsSAQ1QOzzNQJplRY5J0zNBMEGQNBQFue5CCoSApNQLw4GUkVMnUtp0VgDA9OwYwAHlwG4yttNsVKUVxEdUAJHAggAMlMEoIuk2SdXZQqxRK4UixZNlUurCtJmmPE0BwKrIpk7jpQCZUln4gRgr4YRRDUUA2FYyapPNAAPfIhFUub2VTIjUD4eQAH4EuwUtdEIVLgUy7Lct0it5xJPUm1QpYACJkisYhXk4Z7llWdYttoCbt3gTJQDEdC5KEFYmK2jTky-cSws9bDdqUJYfKQ+TgsIQhMjsEBuCYRhYE4bwOUIPhkkPe0ORUcBgHQ+BFIAWjrVxVgvJntRwMHiGEQhOYrHAmbEABWABOAAGYnYHFvgAEYACYjtAABRZbhD4BhoE097PtQSs1Y1rW0iCAyEgsJZmRLcghAYZKfsYjYTkB9MHjYmlfX7aNdsQOs4EORHuK1CtDh2vbza-Q3NbgVzQErXoVujLXyE8bwgkcWB1ej+VKQcXpPwTzOk+gcgGvxAZQH21Ws61nWPpjg2a5j8gAB9QATgITNgSLHIt4MQ+RvajlGNxEEiSktQBm4+CW1JuC-C8I-H2B0qQbJPyj43xXXFVUKQFZHfZMHYAEWBN5juu9crUtE+4EuOkQ0dCXHAIcgVXQHFLPxDIsK22VMCOjI-bn3sHHQuq077kAAMoeyYK-TORtoA5ypOA4updH7FQGFXXoXdIqfmPqfEBqBL4x0cCULkHJl4EQQdnCk0o4iAMsMvVe69-BBHIVyKhE5XYtkIPERkypqh7wPn9UG4Mz5N04AAQSintRw38I5-yPuIohJDOBkPKD4TyqEszRnAECQsxY2oVg6hMUYBDoxEJkSjR6J4fg0K1tY4EFiJGIOkbI+Q8iOTAMkagRw05bCzh8JQuhq95EblAO6e47wZBqSzOlSK0VYAADF4B8CYIMGsowHHQGsahFi41eDzSdDsH4bgMB7XIA6KivDB4HTsXsBQAAZAck4AmcDXDUUGvYmhZhaeoc6xgslDHkP0wgytrF7WQTga+t9k6gCLHWVQilKyp2YC-U2oBSwlFMu5HeyskopQrArC6WVCA5R0vlEZxxOqjGhGM8qlVqqoEGnJSikz5DTNMbASY9yBwBGFM8152Ai6QIfgBJ+5Aq4tRLO1YZ3Uip9SBbVcondInd04F5LMABhcRCSYzEDgDM9KXhCahHgOdUF8zITQkRMwYUmt5DIlAPiqKhKbptCpffGlCg6XwmyERJgDhGWfkZcy1J6TKUQPmYsygCl5CrNgRs052USXEDJW4K5HyvkSqYKlAI5VFCQmRUNTaoBtV0Jmbq-VgKBq1TmffaEkxWVJNStCoxZYTEuvZalfqNUhqoocGqjVFKKx+peSirFGlDmpQAMzAlxSfaM3qiUXLyrdMYtyzyIpRMMv56gmygCemAWmyQiZzX0VoKShw3r104JgbitBQCJtPim3QysADiRASDMGxbBQJCa8WJPZTM66Vz4UYIIm23VpUInOzOKAeQVwsY4yyCAAg0BiBmRpvgYAtAKwGGEAJWAwsYC6GAKzTWOhoAC1ENzLwfMmbgCmqIG9XMWZayfWgE9yQRbQAlgrWNyRoAADYRaxrFsrZBq9r4olQWCp1oxSybO2b0fZWYADqjaiHAhMDk0BYqeynmjOoLDJwcMGXw7HHJ1jVTKyIfKYE0GkDfOOKdMjtAiEomelR56tiszki8BTQ8RYcC5kIMkkR0NG5uPQFy8gHGiGbMcIKhwRDPwtuTcO1NY6M0TohQYFEzGZPR04POKjD1HpAA
