### ISSUE TITLE
Feature request: better documentation and/or support for opting out of customized base queries in tests

### ISSUE THREAD

**Issue by AmyBlankenship** [reduxjs/redux-toolkit#2784]
It's a pain to have to figure out mocking of [authentication](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery) (and potentially other things that could be customized in baseQuery) to test anything that happens in RTK query. I handle it by setting up my endpoints outside of injectEndpoints and then creating a lean api slice for tests, but this is not documented and has its pitfalls. It would be great if there were a simpler way to turn customization off (there probably is that I'm not thinking of, which is why documentation could work, too).

**Comment by markerikson** [comment]
I'm not sure what you're trying to describe here, tbh.

What do you mean by "turn customization off"?  What documentation are you thinking of?

**Comment by AmyBlankenship** [comment]
So when you use the customization of the base query that handles authentication (linked to in my original post), then that logic happens when you are testing absolutely any RTK query in your codebase. Which means that if you don't take steps to mock it, it will fail (even though the logic you care about and are testing has nothing to do with the authentication piece). Like I said, I know how to turn it off, but creating the endpoints separately to injecting them is awkward and took me several hours to figure out. And I wind up having to use any types more than I'd like just because I don't have time to deconstruct the "inner" types.

Even if the way I'm doing this is the best way, documenting it (and the TS part) would save others the hassle I went through.

**Comment by markerikson** [comment]
Doing some issue cleanup, and I'm not sure there's a specific action we can take here. If you've got specific improvements you'd like to see, please file a docs PR!
