### ISSUE TITLE
useQuery with skip:true returns data for previous arg?

### ISSUE THREAD

**Issue by martpet** [reduxjs/redux-toolkit#2786]
I'm not sure if this is a bug.

https://codesandbox.io/s/boring-pike-rb2w0e?file=/src/App.tsx

If you click "ditto" and then "foo", the data returned from useGetPokemonByNameQuery is still for "ditto".

**Comment by phryneas** [comment]
It seems this happened in a few cases, but shouldn't. It will be fixed in the next release through https://github.com/reduxjs/redux-toolkit/pull/2779
