### ISSUE TITLE
RTK Query w/ react-router 6 loaders

### ISSUE THREAD

**Issue by mraymond77** [reduxjs/redux-toolkit#2788]
Has anyone been able to get RTK query integrated with react-router 6? I'm trying to figure out how to fire RTK queries via react-router `loader`'s. ([here](https://tkdodo.eu/blog/react-query-meets-react-router) is an analogous way react-query can be tied into react-router).

My problem is that a react-router `loader` can't take a hook, so any of my `useExampleQuery` type hooks generated by `createApi()` can't be used here. In the example article above, they get around this in react-query by firing the queries via methods on the `queryClient` object at a deeper level instead of the typical `useQuery` hook. A bit ugly, but works. Wondering if I can access a non-hook function in RTK query as well to do this sort of thing.

**Comment by markerikson** [comment]
We've got an open discussion thread on this at https://github.com/reduxjs/redux-toolkit/discussions/2751 - could you comment over there?

**Comment by phryneas** [comment]
I'll just link you over into [this discussion](https://github.com/TkDodo/blog-comments/discussions/84#discussioncomment-3837326) where I answered a similar question.

**Comment by mraymond77** [comment]
Thanks! Didn't find that one when searching for this.
