### ISSUE TITLE
How to use updateQueryData for getAllPosts

### ISSUE THREAD

**Issue by Ahmiimec** [reduxjs/redux-toolkit#2791]
The example given applies subscription based on singular posts and applies optimistic update on a single Post.

I'm trying to query all posts together at once , I wish to edit one post and optimistically update that post in my Get all posts query..

I tried doing this but I found out that my second argument for updateQueryData requires me to enter the same arguements used for getAllPosts query ( originalArg ) , if I use undefined or any other value it fails to run the callback and won't even return an error .

**Comment by markerikson** [comment]
Yes, `updateQueryData` specifically needs to know _which_ cache entry to look up and edit, so you do have to pass in the correct cache key value for it to work.

**Comment by phryneas** [comment]
On mobile right now, so I'm keeping it short: you can just api.util.selectInvalidatedBy to find out all cache entries (endpoint+args) that would be invalidated by a specific tag. That can help you discover those entries.

**Comment by Ahmiimec** [comment]
@markerikson Thanks for the quick reply, makes sense. Well we use getAllPosts once and while editing we don't have the cache key value at that time , is there any better way to access or handle this?


@phryneas Thanks for the answer , I will try this.

**Comment by Ahmiimec** [comment]
@markerikson Thanks again , we are using typescript in our project. The issue is that we have both req and res types set and I initially did change it to undefined but that didn't seem to help as we are actually sending some reqbody params and then again the unique cache identifier would fail...

**Comment by Ahmiimec** [comment]
My reducer path name is taskApi
my slice function name is tasksApi
I have Tags setup as well.
I'm using this 
tasksApi.util.selectInvalidatedBy(taskApi.reducer , ['Task']) 
I'm getting an error of 

TypeError: Cannot read properties of undefined (reading 'provided')

**Comment by phryneas** [comment]
It's a selector, you have to call it with your root state, not with a reducer - TypeScript *should* tell you that.

```js

tasksApi.util.selectInvalidatedBy(rootState, ['Task'])
```

**Comment by Ahmiimec** [comment]
Nice, if I weren't using typescript , what would be my root state object ?
Sorry for bugging

**Comment by phryneas** [comment]
Your Redux state. Like you get it from `store.getState()`.

**Comment by Ahmiimec** [comment]
Apologies , I did try importing my store and passing it like this 

"taskApi.util.selectInvalidatedBy(store?.getState(),['Task'])"

I'm getting this error "Cannot access 'taskApi' before initialization"

**Comment by phryneas** [comment]
You are calling that code in a line where `taskApi` has not been created yet. It's essentialy as if you were doing

```js
console.log(foo)
const foo = "test"
```

That just won't work.
