### ISSUE TITLE
Where is RTK Query cache stored in React Native ?

### ISSUE THREAD

**Issue by whysetiawan** [reduxjs/redux-toolkit#2794]
Hi Guys, Thanks for this amazing library. Really appreciate this. I wonder how RTK cache stored especially in React Native ? If it's in AsyncStorage, can i replace with another storage like MMKV or Realm?

**Comment by phryneas** [comment]
Redux is an in-memory store. If you want to persist it between sessions you would need to use `redux-persist`. That library has bindings for all kinds of storage backends, so I suggest reading their README.
