### ISSUE TITLE
useQuery: data with old arguments remains when new arguments passed to useQuery, but skip condition is true

### ISSUE THREAD

**Issue by plusch011** [reduxjs/redux-toolkit#2810]
Here is the [Sandbox](https://codesandbox.io/s/elastic-haibt-ypth0j?file=/src/App.js);
Steps:
- click on "Show Eddie friends"
- loading flag -> we see current user and his friends list
- click on "Show Robert Friends"
- no loading flag, we see Eddie's friends list

I think this behaviour is unexpected, because when i change arguments -> I expect to look data from new cache entry.
Maybe you should add flag that changes behavior?

**Comment by phryneas** [comment]
Good catch!

This has already been fixed a while ago but we did not release a new version yet - could you please try @reduxjs/toolkit@1.9.0-beta.0 to see if it works for you?

**Comment by plusch011** [comment]
Yeah, everything works fine! [Here is working Sandbox](https://codesandbox.io/s/elastic-montalcini-rbmbx0) for compare. 
PS: Can you please give ETA when 1.9 version will be released?

**Comment by plusch011** [comment]
nice, thanks a lot!
