### ISSUE TITLE
maxRetries not supported on mutations

### ISSUE THREAD

**Issue by AmyBlankenship** [reduxjs/redux-toolkit#2812]
"Customizing queries" says you can set the maxRetries for an "endpoint" if you don't want it to retry so much.  However, this doesn't work for mutations, so on a mutation it will keep trying (more and more slowly each time). This happens even if isUnhandled error is false (because the error is handled in the endpoint definition).

![image](https://user-images.githubusercontent.com/6306216/197557240-4f83f225-cf06-4075-a247-36f1becb5fe7.png)
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/6306216/197557452-0896b353-8d07-4306-94ae-74633062dd11.png">

**Comment by phryneas** [comment]
`maxRetries` needs to go into `extraOptions` - then it should work no matter if query or mutation:

```js
     doSometing: build.mutation({
       query: // ...,
       extraOptions: { maxRetries: 8 }, // You can override the retry behavior on each endpoint
     }),
 ```

**Comment by AmyBlankenship** [comment]
TY!

**Comment by adamplenti** [comment]
> `maxRetries` needs to go into `extraOptions` - then it should work no matter if query or mutation:
> 
> ```js
>      doSometing: build.mutation({
>        query: // ...,
>        extraOptions: { maxRetries: 8 }, // You can override the retry behavior on each endpoint
>      }),
> ```

For my mutations this don't working

api: 
```
const baseQuery = fetchBaseQuery({
  baseUrl: ...,
  prepareHeaders: () => {
    ...
  },
});

const baseQueryWithRetry = retry(baseQuery, {
  maxRetries: 2,
});
```

slice:

```
export const someApi = api.injectEndpoints({
  endpoints: (build) => ({
    sample: build.mutation({
      query(body) {
         ...
      },
      extraOptions: {
        maxRetries: 0,
      },
    }),

...
```

but set `baseQueryWithRetry` with `0` maxRetries don't work at all. It works as if the setting to 0 reset to the default.

my config:

```
"@reduxjs/toolkit": "^1.3.6",
"react-redux": "^7.2.0",
"redux": "4.2.0",
"redux-devtools-extension": "2.13.9",
"redux-thunk": "2.4.1",
"@types/react-redux": "^7.1.18",

"react": "18.2.0",
"react-dom": "18.2.0",
"react-hook-form": "7.35.0",
"react-redux": "^7.2.0",
"next": "12.3.0",
```
