### ISSUE TITLE
1.9.0-beta - forceRefetch doesn't trigger for queries with object as args

### ISSUE THREAD

**Issue by bradbooth** [reduxjs/redux-toolkit#2816]
New to rtkquery and was playing around with the merge & forceRefetch functionality for `1.9.0-beta.0` and it seems like forceRefetch doesn't work how Im expecting if a query has an object for the argument.

Sandbox reproduction: https://codesandbox.io/s/merge-query-sandbox-forked-jjo0y7?file=/src/services/pokemon.ts

For example if I have a query that looks like:
```
query: ({ pageNumber }) => `pokemon?limit=1&offset=${pageNumber}`,
...
forceRefetch: ({ currentArg, previousArg }) => {
        return true;
}
```
Im expecting the query to re-fire whenever pageNumber changes - which doesn't seem to be the case. However, if I change the query to a number argument for example:
```
query: (pageNumber) => `pokemon?limit=1&offset=${pageNumber}`,
...
forceRefetch: ({ currentArg, previousArg }) => {
        return true;
}
```
Then it seems to work as expected. The issue being if a query needs multiple arguments then I'm not sure how to trigger the forceRefetch. Not sure if I'm perhaps using forceRefetch incorrectly however.

**Comment by markerikson** [comment]
Interesting.  Thanks for the repro!  Will try to look at this in the next few days.

**Comment by dorsharonfuse** [comment]
This is causing us issues as well.
@markerikson Any update on this?

**Comment by markerikson** [comment]
Hmm. At first glance, it seems to be related to this check:

```ts
export function useStableQueryArgs<T>(
  queryArgs: T,
  serialize: SerializeQueryArgs<any>,
  endpointDefinition: EndpointDefinition<any, any, any, any>,
  endpointName: string
) {
  const incoming = useMemo(
    () => ({
      queryArgs,
      serialized:
        typeof queryArgs == 'object'
          ? serialize({ queryArgs, endpointDefinition, endpointName })
          : queryArgs,
    }),
    [queryArgs, serialize, endpointDefinition, endpointName]
  )
```

Still digging into this.

**Comment by markerikson** [comment]
Should be fixed now.  Will put out another beta later today.
