### ISSUE TITLE
Handling 302 status/redirect

### ISSUE THREAD

**Issue by derochedesign** [reduxjs/redux-toolkit#2818]
I've posted this on [stackoverflow](https://stackoverflow.com/questions/74185157/handling-302-status-with-rtk-query) but I'll ask here as well.

I have a POST request which returns a 302 when successful. I need to get the location response header which holds the url I'll need to redirect to. Currently I have this:

```
accountLogin: builder.mutation<any, any>({
   query: (body) => ({
      url: `/accounts/login`,
      method: 'POST',
      body,
      responseHandler: (response) => {
        console.log(response, response.headers);
        return response.text(); //.text() is just for testing purposes
      },
  }),
}),
```

If I look in the network tab of my browser the 302 is there, as is the location header with the proper URL. But the 'console.log' in responseHandler shows no headers. I can't find much about this in the documentation -- what am I missing?

**Comment by phryneas** [comment]
Just setting `redirect: 'follow'` is not an option for you?

**Comment by derochedesign** [comment]
> Just setting `redirect: 'follow'` is not an option for you?

Hm well I didn't know that was an option (is it in the docs anywhere?) but that hasn't seemed to change anything just yet. I noticed that my `validateStatus` only gets called when the status is 204 (in my case, no account found). When the status is 302 (account found), the console.log in validateStatus doesn't show. And in this case the response has `isError: true`, which I assume is what is preventing the redirect?

```
accountLogin: builder.mutation<any, any>({
  query(body) {
    return {
       url: `/accounts/login`,
       method: 'POST',
       body,
       validateStatus: (response, result) => {
         console.log(response);
            
         return (response.status === 200 || response.status === 302) && !result.isError;
       },
       redirect: "follow"
     }
   },
}),
```

**Comment by phryneas** [comment]
`fetchBaseQuery` accepts all options that you can also pass into `fetch` and passes those into `fetch`.

If `fetch` follows, that happens internally within that, so RTK Query will never even see the `302`. 

See https://developer.mozilla.org/en-US/docs/Web/API/Request/Request#parameters

Essentially: try to make the `fetch` call by hand - if that works it should also work with RTKQ.

**Comment by derochedesign** [comment]
[Apparently it's impossible](https://github.com/whatwg/fetch/issues/763) to get the `location` header and manually do the redirect; `redirect: "follow"` also doesn't work. So I guess I'm just SOL.

**Comment by phryneas** [comment]
Have you tried with a plain fetch? `"follow"` has definitely worked for me in the past.

**Comment by derochedesign** [comment]
Yeah attempting it with vanilla fetch is how I ran into that known fetch issue. For my case it seems like there's no way to do it other than using html form -- only problem with form is that you can't get the response. Anyway, I'll just have to adjust how our api works instead.

**Comment by phryneas** [comment]
Apart from that, maybe an XHR wrapper like axios might do the trick. Not sure.
