### ISSUE TITLE
BUG/RTK Query/Meta is not showing up on throwing error queryFn

### ISSUE THREAD

**Issue by MylesWardell** [reduxjs/redux-toolkit#2824]
#### 
The queryFn when throwing an error does not include the meta payload

```typescript
logUserIn: build.mutation<Bar, { shouldError: boolean }>({
      queryFn: (params) => {
		const { shouldError } = params
        if (!shouldError) {
          return { foo:  'test' }
        } else {
          throw { message: 'Error', meta: { foo: 'bar' } }
        }
      },
    }),
```

When logging the redux error doesnt show redux
![image](https://user-images.githubusercontent.com/55673046/197953627-756f2bc4-f73c-4374-8fca-0d0c9eb3a24f.png)
Although it does show up when logged
![image](https://user-images.githubusercontent.com/55673046/197953656-03054014-d5c6-4a48-b10d-f64087e8ff19.png)

**Comment by phryneas** [comment]
That's not a bug. `meta` is a way of temporarily passing some non-serializable data to some callbacks, but that data will never make it into the store and thus never into the component.

**Comment by MylesWardell** [comment]
I dont understand this does exactly what I want but the throw does? 
```typescript
return { error: { status: 500, statusText: 'Internal Server Error', data: "Coin landed on it's edge!" } }
```

**Comment by MylesWardell** [comment]
I have solved my issue at this point. But typescript still complains I am not following the error type format when doing this

```typescript
return { error: { status: 403, message: 'Error Message', metadata: { foo: 'bar' } } }
```

Is their any way to set a custom type for error? All our server errors have some form of code, message and optional metadata

**Comment by phryneas** [comment]
The error type comes from the `baseQuery` you use `fetchBaseQuery` has this format by default, but you could wrap or cast `fetchBaseQuery` to be of another error type. That would then tricke through.
