### ISSUE TITLE
state.push is undefined

### ISSUE THREAD

**Issue by mhal12** [reduxjs/redux-toolkit#283]
Been trying to update some slices of state with toolkit and have been having some issues..

Im dispatching the action creator from another action file (not a connected component) on successful login.
` dispatch(addTodo({id}));`

```
const slice = createSlice({
  name         : 'test',
  initialState : {
  },
  reducers : {
    addTodo(state, action) {
      const { id} = action.payload;
      state.push({ id});
    }
  }
});
```
When i debug the action, it says state.push is undefined....

Any help in the right direction? 😢 

![Screenshot 2019-12-17 at 14 40 32](https://user-images.githubusercontent.com/1902775/71005544-b7b15400-20db-11ea-855d-33f0cc316795.png)

**Comment by markerikson** [comment]
You're defining your initial state as an object, not an array.  `.push()` is an array method, so that can't exist.  Change it to `initialState: []`.

**Comment by mhal12** [comment]
Of course! All working now, returned the object and has updated state as expected 👍
