### ISSUE TITLE
Deep refs resolving in @rtk-query/codegen-openapi

### ISSUE THREAD

**Issue by abelgibayev** [reduxjs/redux-toolkit#2833]
We have OpenAPI specs with multiple files and some models contain multiple refs.

E.g:
**spec.yaml**
```
paths:
  /some/endpoint:
    post:
      requestBody: 
        $ref: './entity.yaml#/components/requestBodies/SomeEndpointParams'
```    

**entity.yaml**
```
components:
  requestBodies:
    SomeEndpointParams:
      content:
        application/json:
           schema:
             $ref: "#/components/schemas/SomeEndpointRequest

  schemas:
    SomeEndpointRequest:
      type: object
      properties:
        custom_field:
          $ref: "#/components/schemas/SomeEndpointCustomField"

    SomeEndpointCustomField:
      type: object
      properties:
        field_a:
          type: number
        field_b:
          type: number
```

The problem is next: running `npx @rtk-query/codegen-openapi openapi-config.ts` throws such error
`Can't find paths,/some/endpoint,post,requestBody,content,application/json,schema,properties,custom_field`.

The configuration is correct, openapi-fetch correctly generates classes and models from it.

**Comment by Aaron46** [comment]
What does your config file look like?

**Comment by evanjmg** [comment]
I am getting the same issue for nested on 2nd page. It works in all other cases

**Comment by evanjmg** [comment]
Happens with
```
 discriminator:
        propertyName: kind
        mapping:
          something: '#/components/schemas/something'
```

**Comment by gbataille** [comment]
I'm having the same issue. seems to come from `oazapfts`

Where I'm at at the moment is this:
when you have several files to define your open API doc, you can use this sort of reference
```
          $ref: 'common-swagger-v1.yaml#/components/schemas/common.Quantity'
```

It seems that when the main file uses such an import, the first time it is encountered, it is imported (as in "copy/paste") in the object structure
![image](https://github.com/reduxjs/redux-toolkit/assets/1113065/e9558a0f-a2b4-4bcc-b1dc-f7957b54d62a)

But then further similar references in the same main file will point to the resolved first occurence inside the main document, wherever this might be
![image](https://github.com/reduxjs/redux-toolkit/assets/1113065/a8f02f20-83c0-4caf-827f-934df1bf5942)

It seems that sometimes however, this (weird) link fails.

I'm going to try to track it further

**Comment by markerikson** [comment]
This is probably a problem with the underlying https://github.com/oazapfts/oazapfts library - could you file an issue over there with a repro? Thanks!
