### ISSUE TITLE
How to integrate RTK Query with existing API class

### ISSUE THREAD

**Issue by CarlosHdez** [reduxjs/redux-toolkit#2837]
Hi,
I know this might not be the objective of this library but it's worth the shot to ask any way. 
I'm trying to use RTK Query to make API requests my problem is that I need to use an already existing class that handles the requests for me so I can't use `createAPI`, at the moment I'm using `createAsyncThunk` and making my async calls there but I was thinking maybe there's a way to use `createAPI` without a baseQuery but getting all the other useful features like caching.
I see something like 
```
export const myAPI = createApi({
  reducerPath: 'myAPI',
  endpoints: (builder) => ({
     fetchData: builder.query({
      query: existingAPI.fetchData
    }),
  }),
})```

Thanks for the help, even if it's to clarify that this is indeed not possible.

**Comment by phryneas** [comment]
You can use [`queryFn`](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#customizing-queries-with-queryfn) instead of `query` for that.

**Comment by CarlosHdez** [comment]
Awesome I'll take a look into that, thanks for the pointer
