### ISSUE TITLE
RTK Query examples on redux-toolkit.js.org are not working 

### ISSUE THREAD

**Issue by drjackson** [reduxjs/redux-toolkit#2838]
The examples on redux-toolkit.js.org are not working.  They are returning this error:

TypeError
Cannot set property createApi of #<Object> which has only a getter

**Comment by taochu** [comment]
Happening for me too 👀 

https://redux-toolkit.js.org/rtk-query/usage/examples#kitchen-sink

**Comment by markerikson** [comment]
Hmm. That's extremely odd. This feels like it might be a CodeSandbox bug of some kind?

**Comment by markerikson** [comment]
Yeah, there's an open CSB issue within the last few days with this problem:

- https://github.com/codesandbox/codesandbox-client/issues/7076

Unfortunately that means there's nothing we can do on our end.

**Comment by markerikson** [comment]
Looks like this should be fixed now:

- https://twitter.com/CompuIves/status/1586752900239441921
