### ISSUE TITLE
Redux doesn't update the whole state

### ISSUE THREAD

**Issue by koroman17** [reduxjs/redux-toolkit#2839]
```
import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    data: ""
};

const dataSlice = createSlice({
    name: "data",
    initialState,
    reducers: {
        updateData: (state, action) => {
            state.data = action.payload;
            // payload is a string, e.g. payload = "text"
        },
        updateState: (state, action) => {
            state = { ...state, ...action.payload };
            // payload is an object, e.g. payload = { data: "text" } 
            console.log(state);
        },
    },
});

export const { updateData, updateState } = dataSlice.actions;

export default dataSlice.reducer;
```
The function updateData works properly while updateState doesn't work. The console still shows a new state when I use updateState, but in Redux devtool on the diff tab it says "states are equal". Does it mean I can't update the whole state like that?

**Comment by markerikson** [comment]
The line `state =` is always wrong - it will never trigger an update.  You'll need to _return_ a value here.

See the answer to this question in our docs here:

- https://redux-toolkit.js.org/usage/immer-reducers#resetting-and-replacing-state
