### ISSUE TITLE
RTK Query - Setting user-agent header doesn't work

### ISSUE THREAD

**Issue by khaledtag98** [reduxjs/redux-toolkit#2845]
Hello there,

I need to change the **user-agent** in the request header but it doesn't change. I tried to set another headers link **Accept, authorization, content-type**  and it does changed. Can **user-agent** be changed ? and how

```
import { fetchBaseQuery } from "@reduxjs/toolkit/query/react";

const API_URL = "my_base_url";

const baseQuery = fetchBaseQuery({
  baseUrl: API_URL,
  prepareHeaders: (headers, { getState }) => {
    const token = getState().auth.token;
    headers.set("authorization", `Bearer ${token}`); // working
    headers.set("user-agent", "web"); // not working

    return headers;
  }
});
```

### Request header:
![image](https://user-images.githubusercontent.com/55442919/198894798-bc712fb2-e17a-4e07-9fae-f28f2218abf1.png)

any help ?

**Comment by phryneas** [comment]
We just call `fetch` in `fetchBaseQuery` - and from a short google, it seems that `user-agent` there cannot be changed, as a deliberate choice by browser manufacturerst (although of course that might be outdated infrormation).

**Comment by khaledtag98** [comment]
Thank you @phryneas for your fast reply. I made a deep search and I think `user-agent` is changeable because I found some other libraries handling it like here: [https://github.com/panva/oauth4webapi/issues/13](url)

**Comment by phryneas** [comment]
According to https://bugs.chromium.org/p/chromium/issues/detail?id=571722 which is linked in that issue, it is not possible in Chrome.
