### ISSUE TITLE
Proper way to manually fetch async data with query params in React

### ISSUE THREAD

**Issue by emekaokoli** [reduxjs/redux-toolkit#2853]
Hi @markerikson 

 Prior to using the RTK query, I was using createAsyncThunk for doing things like GET/POST actions. I moved the project to RTK and I have been able to implement major features except that I have hit a snag on how to implement this 

**Before RTK** 

```
const handleFetchUserById = useCallback((userId) => {
    dispatch(getUserById(userId))
  }, [value, delay]);
```

**With RTK Query**
```

const [trigger, result] =  api.useLazyGetUserByIdQuery({
    preferCacheValue: true,  // get cached data first if not exists get a new one.
  });
```

```
 const handleFetchUserById = useCallback(
    async (e) => {
      e.preventDeafult();

      await trigger(
        {
          userId,
        }
        { skip: userId === ""}
      ).unwrap();
    },
    [trigger, userId]
  );
```

**in component**

```
function User(){

if(result?.isLoading) return loading
if(result?.isError) return <>{error?.data}</>

return (<> 
<button onclick={handleFetchUserById}>find user</button>
<div> {result?.data} </div>
</>
)
}
```

but this never works, it doesn't send userId to GET the user I searched for. 

NB. getUserById accepts userId in the query parameter.

am I doing it wrong? or should I use `useQuery ` instead of `useLazyQuery` for this? 

I am using useLazyQuery because I want o manually click a button to perform a search function.

can someone please school me on this? thanks.

**Comment by phryneas** [comment]
This is not actually runnable code - that `result` needs to come from somewhere inside that `User` component.

Please share real code here.
