### ISSUE TITLE
Update default branch name to main

### ISSUE THREAD

**Issue by samilieberman** [reduxjs/redux-toolkit#2858]
We should use inclusive design language in our code to foster an inclusive workplace where everyone feels they can belong. In order to achieve this, can we change the default branch name from master to main? As a result, we also need to update the README and other references to the main branch within the code. I can pick up this issue!

Thank you

**Comment by markerikson** [comment]
We may consider this at some point, but it's very low priority.

**Comment by coryfink** [comment]
@samilieberman - My company recently took a pledge to fix all non-inclusive design language in our repos by November 30th. We've already seen this initiative have a positive impact on our colleagues and customers. I definitely support a fix for this repo, and would be happy to help remediate the terms.
