### ISSUE TITLE
RTK Query: Allow passing arbitrary contextual values to queryFn

### ISSUE THREAD

**Issue by KurtGokhan** [reduxjs/redux-toolkit#2866]
Often when working with RTKQ, I find myself in a situation where I have to pass values to `queryFn` depending on where the query hook was called. The alternative right now is to keep the values as globals and use them inside `queryFn`. But that is not a pure functional solution.

## Proposal

Export a context provider (e.g. `ContextualValuesProvider`) that accepts a `value` property with an arbitrary Record object. A nested `ContextualValuesProvider` will merge its value with the parent context and provide that. Changes to contextual values will not cause a refetch.

Add a new parameter to `queryFn`, which is `contextualValues`. This will be the merged value from `ContextualValuesProvider` in the context query hook was used.

## Example

```jsx
// Main UI code

import { ContextualValuesProvider } from '@reduxjs/toolkit/dist/query';

function Cmp() {
  const { data, isSuccess } = useGetUsersQuery();

  if(isSuccess) {
    console.assert(data.a === 3);
    console.assert(data.b === 10);
  }

  return null;
}

function App() {
  return <ContextualValuesProvider value={{ a: 1 }}>
    <ContextualValuesProvider value={{ b: 2 }}>
       <Cmp />
    </ContextualValuesProvider>
 </ContextualValuesProvider>;
}


// Slice code

const apiSlice = createApi({
  endpoints: (builder) => ({
    getUsers: {
      queryFn(arg, api, extraOptions, baseQuery, contextualValues) {
        return {
          a: contextualValues.a * 3,
          b: contextualValues.b * 5,
        };
      },
    },
  }),
});
```

Note that unlike `api.getState()`, `contextualValues` can have non-serializable values such as classes or functions.

## Use cases

My main use case is WebSocket. We have an API which is kind of a JSON-RPC over WebSocket. The socket is kept open during the lifetime of the user session. Another WebSocket connection is created when user auth token changes (e.g. relogin). So the WebSocket instance depends on the auth token which is inside the redux store. Currently this is achievable only by keeping this WebSocket instance as a global variable.

Other use cases I can think of are logging or mocking.

**Comment by phryneas** [comment]
What if `Cmp` is rendered in two different "contexts"? 

The argument did not change between them, so whichever one is rendered first will be the request that is made - the second one will just use the cache entry created by the first rendered component - potentially containing data from the first context.

**Comment by KurtGokhan** [comment]
Maybe the cache key can be generated with the combination of `arg` and `contextValues`? That would imply a refetch will happen when context values change. I think that is also logical. 

I was trying to make this a simple request but seems like it isn't. Anyway, I am open to alternatives. The gist of my request is to be able to pass non-serializable arguments to queries, preferably using contexts.

**Comment by phryneas** [comment]
Tbh., I don't think you will get around something external and global here.

We calculate the cache key from the arguments passed into the query (and they have to be serializable for that) and we also have to save the arguments for later so the query can be rerun - and they also have to be serializable for that. Users could want to make a first request on the server and then call `.refresh` on the client.

My suggestion would be some kind of global map object (could also be stored in `thunkExtra`, which is available to `queryFn` and pass some kind of serializable key to the query hook.

**Comment by markerikson** [comment]
@KurtGokhan : this is exactly why we added the `serializeQueryArgs` option in RTK 1.9, so that you can pass in non-serializable values and then strip them out of the actual cache key:

- https://redux-toolkit.js.org/rtk-query/api/createApi#serializequeryargs-1

**Comment by phryneas** [comment]
@markerikson not 100% - this will still land as `originalArgs` in the store and possibly cause problems. We can't get rid of those unfortunately.

**Comment by KurtGokhan** [comment]
@markerikson  @phryneas  thank you for your answers. I understand the problem.

> My suggestion would be some kind of global map object

This is the way I am doing it right now, and it works. I will also try to experiment with `serializeQueryArgs`.

Issue can be closed as far as I am concerned.

**Comment by kasparkallas** [comment]
> @markerikson not 100% - this will still land as `originalArgs` in the store and possibly cause problems. We can't get rid of those unfortunately.

I was just trying out the `serializeQueryArgs` for the first time with `builder.query` and `queryFn` and to my surprise was getting `TypeError: cyclic object value` even though I was stripping that value from the `queryArgs` for serialization. The endpoint's `serializeQueryArgs` is not reached. The error seems to originate from `defaultSerializeQueryArgs` even though I have a custom serializer for the API slice. I can investigate further but maybe you can pinpoint right away that this is related to the `originalArgs`?

**Comment by markerikson** [comment]
@kasparkallas : can you share the actual arguments and the stack trace?  Also possibly a Replay ( https://replay.io/record-bugs )?
