### ISSUE TITLE
RTK-Query: add ability to get access to latest batch info when using merge

### ISSUE THREAD

**Issue by ivan-jelev** [reduxjs/redux-toolkit#2870]
`merge` prop introduced in v1.9.0 is super great and makes infinity scroll almost out-of-the-box experience!

However `merge` just give ability to accumulate data, but in some cases we need a bit more - we need to know what's inside the latest batch in order to consider if we should keep loading or not.

## Use Case
Infinite loading over unknown amount of pages with non guaranteed items count per page. For example we would like to set `skip: true` for a query when we know that latest batch had exactly 0 items.

Right now we can't achieve this as data in `data` & `currentData` props is accumulated data.

## Proposal
The proposal is to repurpose `currentData` for this case not to contain accumulated data, but only state of latest/current batch.
Or just introduce another prop which would hold this data (`latestData`/`latestBatch` or whatever you consider reasonable).

Example of what I would like to achieve:
```
const [hasMoreData, setHasMoreDataState] = useState(true);
const { data = [], latestBatch = [] } = api.useQuery(..., { skip: !hasMoreData });

useEffect(() => {
  const mightHaveMore = latestBatch.length > 0;
  setHasMoreDataState(mightHaveMore);
}, [latestBatch.length]);
```

Thank you!

**Comment by ivan-jelev** [comment]
Additionally I've found potential issue.. when we have some accumulated data and then at some point `skip` prop changes to `true` we are losing all the data.. `data` & `currentData` are empty when `{skip: true}`. My expectation would be to preserve the data when `skip` is changed.

**Comment by markerikson** [comment]
Filed #2871 to cover the data aspect, since that's a completely separate issue.

For this question, no, I don't think we would want to change `currentData`.  Its purpose is to keep the actual _accumulated_ data when a different query is started.

Not sure what an actual API solution would look like, but as a workaround, you could use `transformResponse` / `merge` to keep track of, say, `{items: Item[], mostRecentItems: number}` or something like that.

**Comment by ivan-jelev** [comment]
Yep.. it's achievable through `transformResponse` + `merge` to keep track latest batch and makes more sense to deal with on data level instead of API level.

Thanks for the idea!

**Comment by ser-emejia** [comment]
> Yep.. it's achievable through `transformResponse` + `merge` to keep track latest batch and makes more sense to deal with on data level instead of API level.
> 
> Thanks for the idea!

Hello, could you share your implementation, please 🙏
