### ISSUE TITLE
RTK Query: add access to meta/args inside merge method

### ISSUE THREAD

**Issue by ivan-jelev** [reduxjs/redux-toolkit#2874]
There is cases when conditional merging might be useful based on args/meta. Right now we have access to only currentCacheData/responseData which do not give full control
`merge?(currentCacheData: ResultType, responseData: ResultType): ResultType | void;` 

## Proposal
Change `merge` method to accept meta & arg:
`merge?(currentCacheData: ResultType, responseData: ResultType, meta: BaseQueryMeta<BaseQuery>, arg: QueryArg): ResultType | void;`

## Use case
We have infinite scroll with pagination key `page: number`. At some point we want to reset the scroll to its initial position (page=1). We expect data reset to happen when page=1 and accumulation to happen only when page > 1.

what we want to achieve:
```
merge(currentCacheData, responseData, _meta, args) {
  if (args.page > 1) {
    currentCacheData.items.push(...responseData.items);
    return currentCacheData;
  }
  return responseData;
}
```

## Workaround
It's possible to use a workaround by making args accessible as part of result data inside `transformResponse`.. however it's not good to make your query params part of response just to access it inside `merge` method and change return type signature.

```
transformResponse(items: Item[], meta, arg) {
  return { items, page: arg.page };
},
merge(currentCacheData, responseData) {
  if (responseData.page > 1) {
    currentCacheData.items.push(...responseData.items);
    return currentCacheData;
  }
  return responseData;
},
```

**Comment by markerikson** [comment]
Out in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.9.1
