### ISSUE TITLE
Consider exporting "TagDescription" from '@reduxjs/toolkit/dist/query'

### ISSUE THREAD

**Issue by heath-pack** [reduxjs/redux-toolkit#2876]
Right now `TagDescription` is defined at  '@reduxjs/toolkit/dist/query/endpointDefinitions'. It would be nice if it could be added to the index and exported from @reduxjs/toolkit/dist/query'  i.e. `import { type TagDescription } from '@reduxjs/toolkit/dist/query'

The `TagDescription` type would be nice to help just dry up code and share among multiple endpoints

The below example is a simplified version of what I am talking about, where TagTypes is an already defined Enum of tags.

```ts
function providesTagsForUserId(tagTypes: TagType[]) {
    return (_result: AnyObject | undefined, error: FetchBaseQueryError | undefined, userId: string) => {
        const tags: TagDescription<TagType>[] = [TagType.FrontRoyalStore];

        if (error) return tags;

        return tagTypes.reduce((prev, type) => [...prev, { type, id: userId }], tags);
    };
}
```
It would be nice if the above was possible and I could just set the `tags` variable to to be the correct type and not need to use
`as const` and ` tags as ({ type: TagType; id: string } | TagType)[],`all over the place to get this to work out.

**Comment by markerikson** [comment]
Out in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.9.1
