### ISSUE TITLE
What is the return type for `queryFn` or `query` for RTK

### ISSUE THREAD

**Issue by marcusjwhelan** [reduxjs/redux-toolkit#2877]
Attempting to find the return type for `queryFn` and not finding any stackoverflow or issues related to this. I am attempting to have an object which should be the type for the eventual return that will be sent as the http request and add params depending on the args. However I am not seeing any type definitions in the docs for this. 

For example
```typescript
queryFn: (args, queryApi, extraOptions, baseQuery) => {
  const config: /* unknown type here */ = {
    method: 'GET',
    url: '/user'
  }

  if (args.reason) {
    config.params = {...initDefaultParams} // currently error here saying params doesn't exist on this object type
  } else {
    config.params = args.params // currently error here saying params doesn't exist on this object type
  }
  return config
}
```
or should this be in `query` and in that case what is the return type there?

**Comment by phryneas** [comment]
The return type to `query` is the type of the first argument of the `baseQuery` you have (because the return value is passed in there).

The return type to `queryFn` is either `{ data: YourValueType }` or `{ error: TheErrorTypeOfYourBaseQuery }`

**Comment by marcusjwhelan** [comment]
Well maybe I worded this incorrectly. I will try and write it out in code
```typescript
query: (arg) => {
  const config: /* RIGHT HERE WHAT IS THIS TYPE ? */ = {
    method: 'GET',
    url: '/user'
  }
  return config
}
```

**Comment by phryneas** [comment]
I already wrote:
> the first argument of the baseQuery you have,

To make it more clear: If you use the `fetchBaseQuery` it is another type than the type of a hand-written `axiosBaseQuery` or the `graphQlBaseQuery`.

=> Hover your mouse over your `baseQuery`.

**Comment by marcusjwhelan** [comment]
For anyone who comes later the answer is `FetchArgs`, `import { FetchArgs } from '@reduxjs/toolkit/dist/query'`.

The first argument is `string | FetchArgs` but if you are looking to have intellisense let you know parameters are available for the object it might expect it is `FetchArgs`. I found this in the documentation https://redux-toolkit.js.org/rtk-query/api/createApi#query on the left nav bar under /RTK Query/API Reference/createApi and then in that page on the right nav bar under /query.

**Comment by phryneas** [comment]
For people coming to this later: That is correct **if, and only if, you use `fetchBaseQuery`**. 

This is not a generic answer to the question though - it might be `GraphqlRequestBaseQueryArgs` if you use `graphqlBaseQuery` and it will be whatever type your `axiosBaseQuery` implementation uses if you chose to use the `axiosBaseQuery` from the documentation or wrote your own.

Your code examples do not show `fetchBaseQuery` being used, so the question cannot be answered by `string | FetchArgs`. There are implementations of custom `axiosBaseQuery` out in the wild that have overlapping signatures with what you showed there.  
I gave you all the answer I could give you with the amount of code you shared.

**Comment by maksnester** [comment]
I'm still confused about this. So currently the return type is ANY

![image](https://github.com/user-attachments/assets/3ad8208f-719e-4381-a3e7-e29254dfe18e)

What do I need to do to have autocomplete in the obj I'm returning?

**Comment by EskiMojo14** [comment]
@maksnester what does your rootApiSlice look like?
