### ISSUE TITLE
Use of `global` in RTK code breaks RTK in service worker contexts

### ISSUE THREAD

**Issue by AntonOfTheWoods** [reduxjs/redux-toolkit#2879]
https://github.com/reduxjs/redux-toolkit/blob/2425f02fe68f7e186c21e009605022013778a2c5/packages/toolkit/src/query/core/buildMiddleware/batchActions.ts and https://github.com/reduxjs/redux-toolkit/blob/2425f02fe68f7e186c21e009605022013778a2c5/packages/toolkit/src/autoBatchEnhancer.ts have the following - `typeof window !== 'undefined' ? window : global`, which is great for normal windows and node but not so great for workers that have neither.

There is a comment above this code in one of the files `// TODO Remove this in 2.0`

This is pretty nasty... Can we add something slightly nastier, or must this wait for 2.0?

`typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : globalThis`

Would that work?

**Comment by markerikson** [comment]
Seems feasible. Also it didn't click with me we have that polyfill in _two_ places and we should really just have it in one.

As a side question: what are you doing with RTK/RTKQ in a service worker?

**Comment by AntonOfTheWoods** [comment]
> As a side question: what are you doing with RTK/RTKQ in a service worker?

I use the service worker basically as a server/proxy server for the actual server. The local DB (rxdb) and all actual server access goes through the service worker. It works the same way for the chrome extension I'm developing (which is one of the reasons for doing it like this...). That means I can have multiple tabs/extension instances and have reasonable control on how all the interfaces actually communicate with the server, and try and make things as fluid as possible when offline.

Certain parts of the code are common and using RTK on both sides seemed to make sense. Barring little issues like this, It works ok anyway!

**Comment by AntonOfTheWoods** [comment]
Thanks very much for this! (And yes, I should have submitted a PR but you beat me to it!)

**Comment by markerikson** [comment]
Yeah, there's some other fixes that I want to get out together in a 1.9.1.  Hopefully will get it out this week!
