### ISSUE TITLE
createSliceBuilder codemod deletes certain extra reducers

### ISSUE THREAD

**Issue by Chee7ah** [reduxjs/redux-toolkit#2880]
After running the codemod, some `extraReducers` got deleted (in my case those that just immediately delegated to an adapter).

Screenshot of a relevant part of the diff after running the `createSliceBuilder` codemod:

<img width="602" alt="Screen Shot 2022-11-07 at 4 56 04 PM" src="https://user-images.githubusercontent.com/16325672/200464252-7864da6d-72d1-4c82-b25a-0e32ec48553e.png">

**Comment by markerikson** [comment]
Published as `@reduxjs/rtk-codemods@0.0.3` .
