### ISSUE TITLE
Why is the actions object not created when using extraReducers?

### ISSUE THREAD

**Issue by jenya-yacovets** [reduxjs/redux-toolkit#2883]
Hello, I want an object with actions to be created automatically when using createSlice and extraReducers. But it is empty, and it is also not typed. What am I doing wrong or what could be the problem?

```js
import { createAction, createSlice } from '@reduxjs/toolkit';

import { CurrentUserState } from '../../types/currentUserTypes';

// Actions
const authenticationRequest = createAction<boolean, 'authenticationRequest'>('authenticationRequest')
const authenticationSuccess = createAction<boolean, 'authenticationSuccess'>('authenticationSuccess')

// Initial state
const initialState: CurrentUserState = {
    isAuthenticated: false,
    authenticatedLoading: false,
    authenticatedError: null
}

// Slice
const currentUserSlice = createSlice({
    name: 'currentUser',
    initialState: initialState,
    reducers: {},
    extraReducers: (builder) => {
        builder
        .addCase(authenticationRequest, (state, action) => {
            state.authenticatedError = null
            state.authenticatedLoading = true
        })
        .addCase(authenticationSuccess, (state, action) => {
            state.authenticatedLoading = false
            state.isAuthenticated = true
        })
    },
});

console.log(currentUserSlice.actions)
// Console -> {}

console.log(currentUserSlice.actions.authenticationRequest)
// IDE error TS2339: Property 'authenticationRequest' does not exist on type 'CaseReducerActions{}, "currentUser">'.

export default currentUserSlice.reducer
```

Output to the console on line 34: `{}`
There is an error in the IDE: `TS2339: Property 'authenticationRequest' does not exist on type 'CaseReducerActions{}, "currentUser">'`

#### Use:
- NodeJs: v18.12.1 (v16.18.1)
- TypeScript: 4.8.4 (4.1.6)
-  @reduxjs/toolkit: 1.9.0 (1.8.6)

**Comment by markerikson** [comment]
Yeah, you're misunderstanding how `createSlice` works.

For any case reducer function defined inside of the `reducers` object, `createSlice` will call `createAction` internally and generate a new action creator.  Those action creators are added to `slice.actions`.

`createSlice` does _not_ generate new action types for `extraReducers` - the whole purpose of `extraReducers` is to handle action types that were already defined _outside_ of the slice.
