### ISSUE TITLE
typeActionCreator is undefined for createAsyncThunk.withTypes

### ISSUE THREAD

**Issue by gitChaoslord** [reduxjs/redux-toolkit#2884]
## Description:

I followed the instructions of [defining a pre typed async thunk](https://redux-toolkit.js.org/usage/usage-with-typescript#defining-a-pre-typed-createasyncthunk) to use the new `createAsynkThunk.withTypes<AsyncThunkConfig>()` in order to have types available in my slices.

## Expected behaviour:
I expected to be able to access the ThunkApi properties defined in the AsynkThunkConfig in my created async thunks.

## Current behaviour:
The types are correctly inferred but the action creators are not being created and I receive the following error when I use the newly created `createAppAsyncThunk` function.

## Error Message:
```
Firefox
Message: can't access property "type", typeOrActionCreator is undefined
Error in @reduxjs/toolkit@1.9.0/dist/redux-toolkit.cjs.development.js (607:24)

Chrome 
Message: Cannot read properties of undefined (reading 'type')
Error in @reduxjs/toolkit@1.9.0/dist/redux-toolkit.cjs.development.js (607:108)
```

Here is a Stackblitz with my issue: https://stackblitz.com/edit/react-ts-jdymnd?file=store%2Ffeatures%2Fslice.ts

## Other Information:

RTK version 1.9.0
Typescript: 4.8.4
React 18.2.0
React-redux 8.0.5
Redux 4.20

**Comment by markerikson** [comment]
Yes, it appears that we lied to TypeScript and are returning a thunk function, not `createAsyncThunk` itself with more types attached.

This is a bug and we ought to fix it ASAP.

**Comment by markerikson** [comment]
Out in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.9.1
