### ISSUE TITLE
Cannot refetch a query that has not been started yet

### ISSUE THREAD

**Issue by brightsider** [reduxjs/redux-toolkit#2889]
We have a lot of issues with "Cannot refetch a query that has not been started yet" in Sentry when using refetchOnMountOrArgChange.
I can't reproduce this locally, but sentry has 1004 issues after a few days.
It happens on the latest versions of Chrome and redux-toolkit.
<img width="835" alt="image" src="https://user-images.githubusercontent.com/4996231/200766092-eda51787-668d-4a47-8230-85436d76ccf8.png">

**Comment by phryneas** [comment]
This has to come from code that you have written that calls `refetch` too soon - RTK Query itself will never call `refetch`.

**Comment by brightsider** [comment]
thank you for the info.
I will try to find it in the our code.

**Comment by brightsider** [comment]
I used try catch to handle this error and log all props of a query when this happens.
This query has already been fulfilled. How it can happen? How I can fix this issue?
`{
  "status": "fulfilled",
  "endpointName": "list",
  "requestId": "hOu5iY7h7YkmLwFd7RGEm",
  "originalArgs": {
    "page": 1,
    "search": ""
  },
  "startedTimeStamp": 1668165530445,
  "fulfilledTimeStamp": 1668165530902,
  "isUninitialized": false,
  "isLoading": false,
  "isSuccess": true,
  "isError": false,
  "currentData": {
    "users": ["data array here"],
    "count": 166
  },
  "isFetching": false
}`

**Comment by phryneas** [comment]
The query might already have been started elsewhere, but this component has at that point in the timing not had any chance to "latch onto" that query.

Again: where in **your code** do **you** call `.refetch()`? Do you do this synchronously in your component?

**Comment by brightsider** [comment]
No. It happens when the client gets a socket event.

**Comment by brightsider** [comment]
Maybe I need to use lazy query?

Example of code:
```
const { data, refetch }  = useListQuery(props);
const debounceRefetch = debounce(refetch, 1000);
useAblyEventChannel('queue_updated', debounceRefetch, ablyChannel);

export const actionQueueApi = createApi({
  reducerPath: 'actionQueueApi',
  baseQuery: apiQuery,
  endpoints: (build) => ({
    list: build.query<ActionQueue[], void>({
      transformResponse: (response: ActionQueueResponse) => {
        const result = response.data.data;
        return result;
      },
      query: () => ({
        url: URL.GET_ACTION_QUEUE,
        method: 'get',
      }),
    }),
  }),
});
```

**Comment by phryneas** [comment]
**Nobody will ever be able to help you in any way unless you start sharing code.**

I cannot tell you what is better than what you did before **if you don't share what you did before**.

**Comment by brightsider** [comment]
1. This code crashed in our clients, but on we can't reproduce.
2. How I can share a more code if this related to ably service?

**Comment by markerikson** [comment]
@brightsider: I'll echo what Lenz said here.

**You haven't shown almost any code yet, so we don't know what might be going on**.

Is there somewhere in your code that you are calling `.refetch()`?  If so, **please show as much of that code as possible**.

**Comment by brightsider** [comment]
@markerikson refetch used with debounce and called by ably event in **useAblyEventChannel**

**Comment by phryneas** [comment]
![image](https://user-images.githubusercontent.com/4282439/203491052-710ec241-fbd0-414e-a7f1-2f0d9c867cb2.png)


Please.... **PLEASE** stop talking about code, SHOW IT TO US.

**Comment by markerikson** [comment]
I'm going to close this due to a lack of information that we can work with.

_If_ you can actually show us the real code where the `refetch()` call is happening we can try to take a look.

**Comment by edapess** [comment]
This is one of the most iconic threads, guys, thanks :DDD

**Comment by haykerman** [comment]
> This is one of the most iconic threads, guys, thanks :DDD

Stop thanking, just show them some code!!! You haven't shown any code!
