### ISSUE TITLE
`configureStore()` middleware action typings are wrong

### ISSUE THREAD

**Issue by slikts** [reduxjs/redux-toolkit#289]
Currently the `middleware` option for `configureStore()` does not affect what action types `store.dispatch()` accepts; thunks are always accepted even if the thunk middleware is missing, and adding other middleware ignores its dispatch signature.

This is a regression from Redux, where the dispatchable action types are picked up correctly by `createStore()`.

Example:
```ts
const store = configureStore({
  reducer: rootReducer,
  // default thunk middleware disabled
  middleware: []
});
// expected compiler error missing
store.dispatch(() => {});
```

I've also made a [longer working example][example] that defines a number middleware that adds a number action type and shows that the types work with plain Redux but not RTK. I've tried to work around the issue by passing explicit type parameters like so: `configureStore<RootState, AnyAction | number>`, but it doesn't work due to always expecting a type property on the action.

[example]: https://codesandbox.io/s/redux-store-dispatch-overload-u8kcp

**Comment by phryneas** [comment]
Fascinating, I always assumed that `redux` did not do that (as it is impossible in TS to type this for an arbitrary number of middlewared`, but apparently the current types actually support the dispatch type of up to 5 middlewares.

Thank you for bringing that to my attention. @markerikson I guess we should add support for this as well then, shouldn't we?

In the meantime, the way to currently work around this is documented in the "Usage with TypeScript" documentation: [Extending the Dispatch type](https://redux-toolkit.js.org/usage/usage-with-typescript#extending-the-dispatch-type)

**Comment by slikts** [comment]
Thanks for the workaround, although it'd be slightly nicer if it were possible to use the type parameters instead.

**Comment by markerikson** [comment]
Yeah, definitely be nice if we can fix this.

**Comment by phryneas** [comment]
@slikts I just finished my work on the PR, so this will most likely make it into the next version of RTK.
If you want to already use it, you can use the [codesandbox build for the PR](https://ci.codesandbox.io/status/reduxjs/redux-toolkit/pr/304/builds/7607). Early feedback is highly welcome :)

**Comment by markerikson** [comment]
Should be fixed in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.2.2 .
