### ISSUE TITLE
[Website] All links are styled with the color for `a:visited` links in Firefox Nightly

### ISSUE THREAD

**Issue by Abhishek12345679** [reduxjs/redux-toolkit#2891]
This works fine with Chrome and Stable Firefox.

With Firefox/Chrome:

<img width="1095" alt="Screenshot 2022-11-09 at 18 45 42" src="https://user-images.githubusercontent.com/24722640/200840163-2f1bd54f-8bf3-447f-8cbf-b672e7a93b17.png">

With FIrefox Nightly:

<img width="1095" alt="Screenshot 2022-11-09 at 18 45 37" src="https://user-images.githubusercontent.com/24722640/200840223-7c9baf48-709c-4e72-b57d-67ce48bd91eb.png">

Inspecting any link and checking out the rules, the problem seems to arise from here:

<img width="315" alt="Screenshot 2022-11-09 at 18 41 03" src="https://user-images.githubusercontent.com/24722640/200839594-4195544d-f981-435b-837c-3162f9b0a415.png">

Unchecking color fixes the bug.

What i wanted to know was since FF Nightly is unstable, should i try to raise a PR for this in the near future or supporting nightly builds of browsers is not recommended?

Thanks :3

**Comment by markerikson** [comment]
We're definitely not going to make styling changes just for nightly browser builds :)

That seems like an FF compat issue to me - I'd suggest raising it over there!

But yeah, thanks for letting us know - if this does become an issue with a full release of FF maybe it's something we'd look at changing then.
