### ISSUE TITLE
createAsyncThunk payloadCreator  typescripts params is void

### ISSUE THREAD

**Issue by iamphr** [reduxjs/redux-toolkit#2893]
Hi
for example,
![image](https://user-images.githubusercontent.com/20217533/201024391-5f2c0eec-0420-4fd5-8935-8cbfedeb8988.png)
I think this prams  is "any" type  or  else in typescripts  ,but it is "void" .

I don't quite understand. I hope you can give me some advice.

thanks

**Comment by phryneas** [comment]
You need to give it an actual type by writing a type annotation for your argument. By defaul,t it will be `void`.

**Comment by iamphr** [comment]
Thank you for your reply
actually, I do this
I want to know why he defaults to void？
/**
 *
 * @param typePrefix
 * @param payloadCreator
 * @param options
 *
 * @public
 */
export declare function createAsyncThunk<Returned, ThunkArg = void>(typePrefix: string, payloadCreator: AsyncThunkPayloadCreator<Returned, ThunkArg, {}>, options?: AsyncThunkOptions<ThunkArg, {}>): AsyncThunk<Returned, ThunkArg, {}>;
Is it defined here？

**Comment by phryneas** [comment]
Because 
1. we want you to define a type and not accidentally introduce `any` into your code base (which would mask bugs)
2. if it were `any`, you would always have to call `myThunk(someArgumentHere)` - even if you don't want to use it with an argument.

And yes, that point in the code base.

**Comment by iamphr** [comment]
Thanks for your time
