### ISSUE TITLE
Circular RootState when using createAsyncThunk.withTypes

### ISSUE THREAD

**Issue by mezojm10** [reduxjs/redux-toolkit#2895]
Hello there!

I'm trying to define a pre-typed version of createAsyncThunk [as described here in the docs](https://redux-toolkit.js.org/usage/usage-with-typescript#defining-a-pre-typed-createasyncthunk), but I end up with a circular import for RootState that errors my slice (because I'm using createAsyncThunk in a slice that imports the RootState type from the store file that also imports the same slice I'm using).

<img width="801" alt="image" src="https://user-images.githubusercontent.com/26120659/201247330-0f16a5ba-b4ed-46b7-8ad2-4283719bf782.png">
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/26120659/201247468-0df1aafe-18cd-40f6-b2cb-2834ffcd664f.png">

Reproduction: 
https://codesandbox.io/s/redux-starter-kit-circular-slice-dependencies-example-forked-dferhs?file=/src/counterA.tsx
I created a minimal codesandbox for reproduction you can check it out here.

I checked the older issues and none of the fixes worked for me.
Issues I checked:
#2770 
#1126

**Comment by phryneas** [comment]
That doesn't look like a TypeScript error at all - this is a runtime error we fixed over in #2885 that will be released within the next few days as 1.9.1.  
Meanwhile, you can try to work with the CodeSandbox CI build from that PR.

**Comment by mezojm10** [comment]
Thank you. Yeah the CI build version is working fine for now, I'll wait until 1.9.1.

**Comment by Naggertooth** [comment]
This saved my hours
