### ISSUE TITLE
Difference between query/react and dist/query/react

### ISSUE THREAD

**Issue by Gytree** [reduxjs/redux-toolkit#2899]
Hi folks I'm testing the RTK query following the website examples, but when I made a build (using parcel) the result doesn't include the RTK query functions and I get errors like **xb.fetchBaseQuery isn't a function**. So, after a long research and testing, I find out that if i use the import with the **dist/query/react** import route instead of **query/react** the build include the lib correctly. 

What is the difference between the two?
thanks in advance.

**Comment by phryneas** [comment]
`query/react` is essentially an alias to `dist/query/react`. 

Usually, it should just work - but if you have very unconventional tooling, something might go wrong there.

What environment are you using?

**Comment by Gytree** [comment]
Hi @phryneas, thk for the fast answer. To build I using [Parcel](https://parceljs.org/) to build the bundle. Then if the paths are aliases must be something related with the way that the bundler load the scripts ?  Then i will ask to the parcel folks instead.
