### ISSUE TITLE
useLazyQuery control cache

### ISSUE THREAD

**Issue by colaquecez** [reduxjs/redux-toolkit#2900]
Hey guys, I would like to know if there's a way when we are using the `useLazyQuery` we get the cached value, so for example: 

- The user presses a button to get the products, I check the cache in order to see if there's any cache available, if so,  I just get the actual cache, otherwise, I call the API. It's basically the same function of the `useQuery` but with `useLazyQuery` in order to use a button.  

it would be like the `fetchPolicy` from Apollo.

**Comment by phryneas** [comment]
You mean passing `true` as an argument to the `trigger` function?

**Comment by colaquecez** [comment]
Hmm what do you mean? Can I pass a param to be able to do that? because when I call the trigger from the `useLazyQuery` it will call the API again even if I already did the API call,  is it possible to get the cache version instead of calling the API?

**Comment by phryneas** [comment]
`trigger(arg: Argument, preferCacheValue?: boolean | undefined):`

The `trigger` function has a second `preferCacheValue` argument.

**Comment by colaquecez** [comment]
Thank you @phryneas, it was very helpful!
