### ISSUE TITLE
RTK Query 1.9.0 miss types for InjectEndpoints - TS

### ISSUE THREAD

**Issue by rubentlc** [reduxjs/redux-toolkit#2907]
I'm using RTK Query in a project with TypeScript and GraphQL. 

Since I updated to use RTK Query 1.9.0, I need to typify the builder prop, but I can't find a way to that. For now, to keep the code running, I'm doing this:

`
const myApi = apiWithTags.injectEndpoints({
  endpoints: (builder: EndpointBuilder<any, any, any>) => ({
...
`

Can someone provide the correct way to fix this?

**Comment by phryneas** [comment]
The correct way of doing it is not writing any type there. That builder object is extremely complex - you just cannot write that by hand as it contains all information about your api at this point - it would be incredibly long.

`(builder) =>` without any type is the only correct way of writing it.

**Comment by rubentlc** [comment]
Thanks @phryneas . Yes sorry, my bad, it start working as before after restart visual code.
