### ISSUE TITLE
What is the best way to hold off on requests until auth header is set?

### ISSUE THREAD

**Issue by mraymond77** [reduxjs/redux-toolkit#2916]
We have an app with okta auth. On a fresh load or reload the access token isn't available immediately, so I find myself needing to add [`skip`](https://redux-toolkit.js.org/rtk-query/usage/conditional-fetching) logic everywhere that I use a query hook to avoid 401 errors on initial load.
e.g.
```javascript
   ...snip...
    const { authHeaderIsSet } = useSelector(state => state.user);
    // if authHeaderIsSet is false, the query will skip (skipToken).
    const queryArgs =
      authHeaderIsSet ? { name: myName, type: 'SOA' } : skipToken;
    const { data, loading, error } = useGetPokemonByNameQuery(queryArgs);
```

It works okay, but I feel like needing to do this everywhere I'm making use of a query hook is not ideal.
Is there a more centralized way to do this? In fetchBaseQuery constructor or something? been looking but not found anything. 
Thanks in advanced!

**Comment by einarq** [comment]
Maybe wrap it up in a custom hook?

**Comment by phryneas** [comment]
You know that `prepareHeaders` can be async and just wait for your token to be present?

**Comment by CallumKing90** [comment]
@mraymond77 I've been trying to solve the same problem recently too. I found the reauthentication example on RTK docs but tweaked it a little so it doesn't make any API calls unless `getState()` has a token value present.

`const baseQueryWithReauth = async (args, api, extraOptions) => {
 let result
 if (api.getState().token) {
    result = await baseQuery(args, api, extraOptions)
  }
  if (!api.getState().token || (result.error && result.error.status === 401)) {
    // try to get a new token
    const refreshResult = await baseQuery('/refreshToken', api, extraOptions)
    if (refreshResult.data) {
      // store the new token
      api.dispatch(tokenReceived(refreshResult.data))
      // retry the initial query
      result = await baseQuery(args, api, extraOptions)
    } else {
      api.dispatch(loggedOut())
    }
  }
  return result
}`

`prepareHeaders` would remain the same as in the second link I've included below. 

- [Automatic re-authorization by extending fetchBaseQuery](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery)

- [Setting default headers on requests](https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery#setting-default-headers-on-requests)

I was hoping to make it a bit smarter and be able to do something like below and use an extraReducer to set my token value but I've given up. Open to suggestions if somebody has cracked this problem in a cleaner way.

` prepareHeaders: async (headers, { getState }) => {
    // By default, if we have a token in the store, let's use that for authenticated requests
    const token = getState().auth.token;

    if (!token) {
      await myTokenApi.endpoints.getToken.initiate()
      // I know this isn't a promise but posting in the hope somebody can identify my errors and give me a pointer
    }

    if (token) {
      headers.set("authentication", `Bearer ${token}`);
    }

    return headers;
  },
`

**Comment by mraymond77** [comment]
Thanks @phryneas and @CallumKing90. Best solution I've found so far (and to @phryneas point about it being able to be async..) is to throw an error in `prepareHeaders` if the access token isn't there yet.
```javascript
const baseQuery = fetchBaseQuery({
  baseUrl: `${RDNS_SERVER_BASE_URL}/v2/`,
  prepareHeaders: async (headers, { getState }) => {
    headers.set('X-Source-Type', 'ui');
    const { tokenObj } = getState().user;
    if (tokenObj?.accessToken) {
      headers.set('Authorization', `Bearer ${accessToken?.accessToken}`);
      return headers;
    }
    // Throwing error causes promise to reject. Thus api call is not made.
    throw new Error('Auth header not ready.');
  },
});
```

**Comment by phryneas** [comment]
I was more thinking along the lines of
```js
 prepareHeaders: async (headers, { getState }) => {
    return new Promise(resolve => {
      function checkToken() {
        const { tokenObj } = getState().user;
        if (tokenObj?.accessToken) {
          headers.set('Authorization', `Bearer ${tokenObj.accessToken}`);
          resolve(headers;)
        } else {
          setTimeout(checkToken, 500) // try again in 500ms
        }
      }
      checkToken()
    })
  },
```

**Comment by phryneas** [comment]
@mraymond77 maybe add a few console.logs over the place and see what is going on? this is also just really something I made up in 2 minutes - it might need some tweaking.

Also, how does `state.user` get it's value?

**Comment by mraymond77** [comment]
@phryneas, spent some time looking into my issue, seems I cannot replicate after I deleted node_modules and package-lock.json and reinstalling. The setTimeout-and-poll solution seems to be working for me now. Thanks for the suggestion.

**Comment by RomanChervakov** [comment]
const controller = new AbortController();
  window.addEventListener('offline', () => {
    controller.abort('');
  });
const result = await baseQuery(
    args,
    { ...api, signal: controller.signal },
    extraOptions,
  );
