### ISSUE TITLE
Check for cancellation before starting payloadCreator (might have been cancelled during async `condition`)

### ISSUE THREAD

**Issue by phryneas** [reduxjs/redux-toolkit#2918]
### Discussed in https://github.com/reduxjs/redux-toolkit/discussions/2914

<div type='discussions-op-text'>

<sup>Originally posted by **KeisJS** November 16, 2022</sup>
Hello. I abort thunk before the condition is resolved. But after resolving the condition, the thunk is still executed.
```
export const sampleThunk = createAsyncThunk('sampleThunk', async () => {
  console.log('do something async');
}, {
  condition: () => new Promise((res) => {
    setTimeout(() => res(true), 1000);
  }),
});
```
```
useEffect(() => {
    const sampleThunkAction = dispatch(sampleThunk());

    sampleThunkAction.abort();
  }, [dispatch]);
```
Is this a bug or feature?</div>

**Comment by markerikson** [comment]
Out in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.9.1
