### ISSUE TITLE
reset state in createSlice

### ISSUE THREAD

**Issue by LLazyness** [reduxjs/redux-toolkit#292]
What is the best way to reset state to initial in createSlice? The only way I found is to assign new values in _reset_ reducer, but it looks terribly

const testSlice = createSlice({
    name: 'test',
    initialState: {
        elements: []
    },
    reducers: {
        reset(state) {
            //here I need to reset state of current slice
        }
    }
});

**Comment by phryneas** [comment]
You do not need to modify a state-draft in the reducer, you can also return a new (or old) one. Immer just requires you not no mix assignment and return value in the same reducer. 
So it could look like this:
```ts
const initialState = { elements: [] };
const testSlice = createSlice({
  name: "testSlice",
  initialState,
  reducers: {
    reset() { return initialState; }
  }
});
```

**Comment by LLazyness** [comment]
Thanks!
