### ISSUE TITLE
please rectify the error

### ISSUE THREAD

**Issue by UtsavKansal** [reduxjs/redux-toolkit#2923]
Property 'getState' does not exist on type 'ToolkitStore<any, AnyAction, [Middleware<ThunkDispatch<State, ExtraThunkArg, BasicAction>, State, ThunkDispatch<State, ExtraThunkArg, BasicAction>>]>'

**Comment by UtsavKansal** [comment]
import { configureStore } from "@reduxjs/toolkit";
import { sideDrawerReducer } from "./sidedrawer/sidedrawer-slice";

const store = configureStore({
  reducer: { sideDrawer: sideDrawerReducer },
});
export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
export default store;

**Comment by UtsavKansal** [comment]
`import { configureStore } from "@reduxjs/toolkit";
import { sideDrawerReducer } from "./sidedrawer/sidedrawer-slice";

const store = configureStore({
  reducer: { sideDrawer: sideDrawerReducer },
});
export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
export default store;`

**Comment by UtsavKansal** [comment]
`import { configureStore } from "@reduxjs/toolkit";
import { sideDrawerReducer } from "./sidedrawer/sidedrawer-slice";

const store = configureStore({
  reducer: { sideDrawer: sideDrawerReducer },
});
export type RootState = ReturnType{"<"}typeof store.getState{">"};
export type AppDispatch = typeof store.dispatch;
export default store;`

**Comment by UtsavKansal** [comment]
It is already true still not working

**Comment by phryneas** [comment]
If you look at the playground I linked, that code will work. 
Of course, there might be more to your setup that breaks it, but I cannot look into your computer. 
You will have to reproduce the problem in a way so I can see it on my computer or I won't be able to help you.

You could create a CodeSandbox showing the problem, or a GitHub repo with code showing the problem. Or try to recreate it in a TypeScript playground. But like this, all I can do is guess from the other end of the world.

**Comment by jameslawson** [comment]
I also encounted this, for my project the root cause was having `"preserveSymlinks": true` in my tsconfig.json - sharing, in case anyone else is debugging this.
