### ISSUE TITLE
Improve `extraReducers` docs to explain purpose

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#2926]
Per https://www.reddit.com/r/reactjs/comments/yzcegz/when_using_redux_it_is_better_to_go_basic_than/ix0g24j/ , the current `extraReducers` docs explain syntax, but not anything about the purpose or use cases for `extraReducers`.  We should rework this.

**Comment by markerikson** [comment]
Unrelated but throwing in here:

Apparently several links in https://github.com/reduxjs/redux-toolkit/blob/master/docs/api/matching-utilities.mdx are broken ( createAction, createSlice, createAsyncThunk, rejectWithValue ).

**Comment by AmyBlankenship** [comment]
This is actually already well-documented in the main Redux docs. It's unfortunate that the documentation is fragmented such that most of the best Redux Toolkit documentation is found on the main Redux site.
![image](https://user-images.githubusercontent.com/6306216/203876709-70bd87b5-7dfd-455d-8cb7-acfc100ca64a.png)

**Comment by phryneas** [comment]
@AmyBlankenship that is chapter 5 of the official Redux Tutorial - and also the tutorial that is linked in [the Redux Toolkit Tutorial section](https://redux-toolkit.js.org/tutorials/overview) directly after the "quick start" tutorial.
It has to be *somewhere* and we need to reach people going to the "redux" docs with modern Redux.

**Comment by AmyBlankenship** [comment]
My point is it's somewhere, but not in the Redux-toolkit docs. So the improvement that's being requested here already exists--somewhere else. Just copy that?

**Comment by ryota-murakami** [comment]
@markerikson I used to `extraReducer` for pagination.
Because total page number is depends on server side data, I think `extraReducer` is good place for to do any fetch data matter tasks. 

https://github.com/laststance/nsx/blob/5ab8207d3b23fb71d0b9d6ad5a82580c6e9d3783/src/redux/pagenationSlice.ts#L20-L27

**Comment by markerikson** [comment]
It's a starting point, but I think we can probably improve the explanation there.

**Comment by AmyBlankenship** [comment]
I think it would be good to call out specifically how you'd listen for actions coming from rtk query endpoints that have arguments and determine which ones you care about
