### ISSUE TITLE
why I dont get anything when I console log my draft RTK-QUERY?

### ISSUE THREAD

**Issue by shop-fluencer** [reduxjs/redux-toolkit#2928]
Hello,

I use rtk-query and want to add optimistic updates. The Problem is I didnt get any console log statement in "NotificationsApi.util.updateQueryData". After console.log('Start') nothing happens

Code:
```
export const NotificationsApi = createApi({
  reducerPath: 'NotificationsApi',
  baseQuery: fetchBaseQuery({baseUrl: `${API_ENDPOINT}/`}),
  tagTypes: ['ALL'],
  endpoints: (build) => ({
    // All
    notificationsAll: build.query<INotificationsAllListData[], { user_id: number; }>({
      query: (data) => ({
        url: '/notifications',
        method: 'POST',
        body: data
      }),
      providesTags: ['ALL']
    }),
    removeNotificationById: build.mutation<void, Pick<INotificationsAllListData, 'type'> & { user_id: number; notification_id: number; }>({
      query: (data) => ({
        url: '/remove_notification',
        method: 'POST',
        body: data
      }),
      async onQueryStarted({ user_id, notification_id, type }, { dispatch, queryFulfilled }) {
        console.log(notification_id);
        console.log('START');
        const patchResult = dispatch(
          NotificationsApi.util.updateQueryData('notificationsAll', undefined, (draft) => {
              console.log('DISPATCH'); // I DONT GET THIS!!
          })
        )
        try {
          await queryFulfilled
          
        } catch {
          console.log('HI');
          patchResult.undo();
  

          /**
           * Alternatively, on failure you can invalidate the corresponding cache tags
           * to trigger a re-fetch:
           * dispatch(api.util.invalidateTags(['Post']))
           */
        }
      },
      invalidatesTags: ['ALL']
    }),
  })
});
```

I get successfull data when logging notifications_id, type and user_id but I didnt get the console.log statement "DISPATCH". when I also console log draft nothing happens I dont get any console log in there. Whats the problem ? I have also used optimstic updates in other files that works but not here.

**Comment by markerikson** [comment]
Are you sure that the cache entry with the type `notificationsAll` and the key `undefined` actually exists at the time this runs?

**Comment by shop-fluencer** [comment]
> Are you sure that the cache entry with the type `notificationsAll` and the key `undefined` actually exists at the time this runs?

Where I can see my cache entry ? The problem is it does not dispatch so I can not even log my draft I dont get no one console log statement in the dispatch function.

**Comment by markerikson** [comment]
Yeah, I'm saying that I _think_ the issue may be that there isn't any data cached at all for the `notificationsAll` endpoint, so there's nothing to "update" and it won't run your update util.

You can see the data by looking in the Redux DevTools.

Do you actually have something like `useNotificationsAllQuery()` in your code?

**Comment by shop-fluencer** [comment]
> Yeah, I'm saying that I _think_ the issue may be that there isn't any data cached at all for the `notificationsAll` endpoint, so there's nothing to "update" and it won't run your update util.
> 
> You can see the data by looking in the Redux DevTools.
> 
> Do you actually have something like `useNotificationsAllQuery()` in your code?

thank you , you're right, if I use my notifitcationsAll with param user_id, I have to put the key user_id in my dispatch :

```
    removeNotificationById: build.mutation<void, Pick<INotificationsAllListData, 'type'> & { user_id: number; notification_id: number; }>({
      query: (data) => ({
        url: '/remove_notification',
        method: 'POST',
        body: data
      }),
      async onQueryStarted({ type, user_id, notification_id }, { dispatch, queryFulfilled }) {


        const patchResult = dispatch(
          NotificationsApi.util.updateQueryData('notificationsAll', {user_id}, (draft) => {
              console.log('HIII');
          })
        );
```

if I dont use any params I have to set updateQueryData with undefined:

```
        const patchResult = dispatch(
          NotificationsApi.util.updateQueryData('notificationsAll', undefined, (draft) => {
              console.log('HIII');
          })
        );
```

**Comment by markerikson** [comment]
Yes, that's how the cache utils work. They need to know both which endpoint to look up, and also which cache entry to work with, and the cache entry is determined based on that argument.

**Comment by shop-fluencer** [comment]
> Yes, that's how the cache utils work. They need to know both which endpoint to look up, and also which cache entry to work with, and the cache entry is determined based on that argument.

Thank you very much, can you help me at one thing ? I want to delete all notifications by id, I get successfull console log when the el.item.id is the same as notification id. So but they dont filter it, why ?

```
        const patchResult = dispatch(
          NotificationsApi.util.updateQueryData('notificationsAll', {user_id}, (draft) => {
            switch(type) {
              case 'SOLD':
                draft.filter((el => {
                  if(el.item.id === notification_id) {
                    return true;
                  } else {
                    return false;
                  }
                }));
              break;
            }
          })
        );
```
