### ISSUE TITLE
How can I reject the mutation or query when my service returns "isSuccess:false"? RTK Query

### ISSUE THREAD

**Issue by ahmtxonly** [reduxjs/redux-toolkit#2929]
I have specific case of my project,

When time my service return response data {isSuccess:false} this is a fault.

How can I implement this feature?

My api file: 
<img width="751" alt="image" src="https://user-images.githubusercontent.com/36918073/203278398-a8703232-ec51-49cd-9c2a-ffacdb798864.png">
Service file:
<img width="793" alt="image" src="https://user-images.githubusercontent.com/36918073/203278695-e05bcaf8-e920-4c75-8ddc-80fc36e3b707.png">
Slice file:
<img width="731" alt="image" src="https://user-images.githubusercontent.com/36918073/203278804-4243d7ad-2a99-46e9-934f-494201aa75d2.png">

**Comment by phryneas** [comment]
You can use a `validateStatus` function:

```js
fetchBaseQuery({
  ...,
  validateStatus(response, body) => {
    if (body.isSuccess == false) { return false }
    return response.code >= 200 && response.code < 300
  }
})
```

But generally, that server should really give propert http status codes

**Comment by ahmtxonly** [comment]
> 

I know but, I couldn't changed :(

Thank you for help, my problem is solved.
