### ISSUE TITLE
BUG: RTK Query: You can no longer set 'maxRetries' to 0

### ISSUE THREAD

**Issue by ritterb82** [reduxjs/redux-toolkit#2934]
In the latest update there was updates to the retry logic.  But the updates broke the ability to set maxRetries to 0.  I believe this is due to the `possibleMaxRetries` array that now exists and gets filtered by `Boolean`.  Which cause `0` to be tossed out.  

So then at that point, it just goes back to the default of 5.

https://github.com/reduxjs/redux-toolkit/blob/f7a828255e0612bed0856a0b6d1b9b8d6d6ac30d/packages/toolkit/src/query/retry.ts#L82-L87

**Comment by OliverRadini** [comment]
Would it be alright if I picked this up? Looking to find some issues to work on and this seems interesting

**Comment by markerikson** [comment]
Sure, please do!

**Comment by OliverRadini** [comment]
@markerikson  thanks, hopefully the code in the PR properly resolves the issue

**Comment by markerikson** [comment]
Out in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.9.1
