### ISSUE TITLE
docs page fonts are too large

### ISSUE THREAD

**Issue by grewal25** [reduxjs/redux-toolkit#2935]
Can we please make these fonts a little smaller? Whenever I go to the [docs page](https://redux-toolkit.js.org/tutorials/overview), I see this huge H1 (Tutorials Overview) and everything looks so odd to read. Not a good user experience. Please take this into the consideration.

**Comment by markerikson** [comment]
These are just the default Docusaurus fonts - compare with https://docusaurus.io/docs .
