### ISSUE TITLE
I wonder if RTK Query is considering Infinite Query support.

### ISSUE THREAD

**Issue by panda919** [reduxjs/redux-toolkit#2941]
![image](https://user-images.githubusercontent.com/25161426/203716569-44b2df8f-ee71-40c1-b30b-0d8ea2f98c44.png)
So far I have been working with reduce-toolkit for many years. So, I was attracted to RTK Query and chose RTK Query over react-query.
However, as in the screenshot mentioned above, RTK Query has a set of limitations compared to react-query.
In particular, Infinite Query and Automatic Refetching are very important.
Do you intend to support the above features in the future?
In particular, I think that it is necessary to have a function to change the cache value of the corresponding offset position when deleting, modifying or additional mutations.

**Comment by phryneas** [comment]
Automatic refetching is a core feature of RTK Query. I have no idea where you got that screenshot from, but it's plain wrong.

As for "infinite queries", that just is not a simple problem to solve as there are many different kinds of "infinite" on the server. Page-based, offset-based and cursor-based pagination work completely different and pretty much require different approaches.

The solution I propose [here](https://github.com/reduxjs/redux-toolkit/discussions/1163#discussioncomment-849158) should work perfectly nice for page-based and offset-based pagination. We could add a tool for that, but adding a tool like that would remove a lot of flexibility since everyone would try to use only that instead of thinking about their personal use case.

**Comment by panda919** [comment]
Thanks. 
But I have some limits at  your mentioned solution into flatlist react-native which includes delete/update mutation. 
[it is my issue](https://github.com/reduxjs/redux-toolkit/issues/2939)
Especially I checked SDK [doc.](https://redux-toolkit.js.org/rtk-query/comparison) 
![image](https://user-images.githubusercontent.com/25161426/203732208-5fb366b7-f8ed-490a-b955-0696a5e988aa.png)

**Comment by panda919** [comment]
` I have no idea where you got that screenshot from, but it's plain wrong.` 
I checked this [blog](https://blog.bitsrc.io/frontend-caching-with-redux-toolkit-query-14e008a632b1#:~:text=Comparison%20between%20RTK%20Query%20and%20React%20Query&text=For%20example%2C%20React%20Query%20uses,keys%20via%20endpoints%20and%20arguments)

**Comment by phryneas** [comment]
My suggested solution should work in a React-Native Flatlist. 
It creates a very long array that has just some parts around the current scroll position filled out.

**Comment by panda919** [comment]
![image](https://user-images.githubusercontent.com/25161426/203732954-5b8fda98-9db1-4ae9-88aa-6470e965650f.png)
I have some limit to decide correct currentPage in react-native flatlist. 
Do you have solution for it?

**Comment by phryneas** [comment]
You could abuse the `renderItem` method to see what index was most recently rendered into view and calculate a page number from that.

**Comment by panda919** [comment]
As I understand, we can not use hook in a render function. WOuld you share a code snippet?

**Comment by panda919** [comment]
Also, Would you help me with this [issue](https://github.com/reduxjs/redux-toolkit/issues/2939)?

**Comment by phryneas** [comment]
> As I understand, we can not use hook in a render function. WOuld you share a code snippet?

const [lastRenderedItem, setLastRenderedItem] = useState(0)
useMyHookQuery(...)


in render:
`debouncedVersionOfSetLastRenderedItem(idx)`

**Comment by panda919** [comment]
thanks. But Would you share more details code snippet and comments?

**Comment by phryneas** [comment]
I'm working right now and don't really have time to look into this.

The point is: you fetch this data in the parent component of your FlatList, so the `useQuery` hook is there. The `currentPage` is local state in that component. 
You should not directly call a state setter from  that Parent component during render (it would happen a lot), but you can have a debounced version of the `setCurrentPage` version that waits until no more calls are made and then sets the state in the parent, which will then update the page and load more data. Please read up on those concepts.

**Comment by phryneas** [comment]
As for your other question: you can get there by setting tags with the arguments included for each individual page, but at this point you need to track those possible tags elsewhere to invalidate them. We might add a feature in the future to make this use case easier.

**Comment by panda919** [comment]
you mean I have to keep all tags for each individual page?

**Comment by razor247** [comment]
Really sounds like they want you to use React-Query which has it built in. Based on any questions about infinite scroll here, it doesn't look to be coming to this library ever. "As for "infinite queries", that just is not a simple problem to solve" yeah I think that's why people were hoping to use a library..

**Comment by phryneas** [comment]
@razor247 you miss the point: there are a lot of different styles of "infinite scrolling" out there, as you can see from those discussions. If there were only offset-based infinite scrolling or page-based, we could just implement that. 
But there are also cursor-based paginations, some with only forward cursors, some also with backward cursors. 
And there are completely different pagination styles from that, I'm sure I forgot of half a dozen styles right now.  

Other libraries offer integrated tools, and those will work nicely with some of these styles and will have their problems with others. Ther is not one solution to solve "all infinite scrolling", no matter how big the checkmark is on the page of the respective library.

Infinite scrolling is one of those things where your choice of server implementation has a really big influence on how it has to be solved on the client. You write code on the server -> you have to write code on the client. It's just impossible that a library can solve all of that out of the box for you.

And if you have one of the simple cases: just take the snippet I posted in the "infinite scrolling" discussion and use that. It's so simple you don't need a full-fledged solution, it even has benefits over those.  
If that doesn't work, there is a good chance that any "batteries included" solution would also not work for your use case and you would have to write your own anyways.

**Comment by panda919** [comment]
> > As I understand, we can not use hook in a render function. WOuld you share a code snippet?
> 
> const [lastRenderedItem, setLastRenderedItem] = useState(0) useMyHookQuery(...)
> 
> in render: `debouncedVersionOfSetLastRenderedItem(idx)`

Honestly, I've tried to understand your solution so far, but I can't figure it out.
Could you at least share the source of debouncedVersionOfSetLastRenderedItem?
