### ISSUE TITLE
Whats the difference between these two updates ? Both works and which should I use ?

### ISSUE THREAD

**Issue by shop-fluencer** [reduxjs/redux-toolkit#2944]
Hello,

I use Optimistic Updates, and all works fine. I know the two difference of the both methods. The first use immuteable, but I want to ask you, is it necessary to use immuteable when dispatching data with optismistic update ? Get I problems when I use method 2 ?

Method 1:

```
        const patchResult = dispatch(
          NotificationsApi.util.updateQueryData('notificationsAll', {user_id}, (draft) => {
            return draft.map((el, i) => {
              if(el.item.watched === false) {
                return {
                  ...el,
                  item: {
                    ...el.item,
                    watched: true
                  }
                }
              } else {
                return {
                  ...el
                }
              }
            })
          })
        );
```

Method 2:

```
        const patchResult = dispatch(
          NotificationsApi.util.updateQueryData('notificationsAll', {user_id}, (draft) => {
             draft.map((el, i) => {
              if(el.item.watched === false) {
                draft[i].item.watched = true;
              }
            })
          })
        );
```

**Comment by phryneas** [comment]
1 is more code than 2. They do the same.
It is perfectly fine to write mutable logic in `updateQueryData`.

**Comment by markerikson** [comment]
Yep, `updateQueryData` wraps your callback in Immer:

https://redux-toolkit.js.org/usage/immer-reducers

**Comment by shop-fluencer** [comment]
> Yep, `updateQueryData` wraps your callback in Immer:
> 
> https://redux-toolkit.js.org/usage/immer-reducers

So I can use the short method from my code ?

**Comment by phryneas** [comment]
As I already said, yes. Please do that.
