### ISSUE TITLE
Typesafe is not working while create dynamic reducer

### ISSUE THREAD

**Issue by atillaaliyev** [reduxjs/redux-toolkit#2951]
I'm creating a custom library and I want to isolate other developers from RTK. They should be interested in only reducers. 

**store.ts**

```
import {
  Action,
  AnyAction,
  ReducersMapObject,
  Store,
  configureStore,
  createSlice,
} from '@reduxjs/toolkit'
import {
  Provider as ReduxProvider,
  TypedUseSelectorHook,
  useDispatch as useReduxDispatch,
  useSelector as useReduxSelector,
} from 'react-redux'
import layoutReducer from './layout/slice'
import { api } from './services/api'

const createStore = <S, A extends Action = AnyAction>(reducers: ReducersMapObject<S, A>) => {
  const store = configureStore({
    reducer: {
      layout: layoutReducer,
      [api.reducerPath]: api.reducer,
      ...reducers,
    },
    middleware: (getDefaultMiddleware) =>
      getDefaultMiddleware({
        serializableCheck: false,
        devTools: {},
      }).concat(api.middleware),
  }) as Store<S, A>
  const useDispatch = () => useReduxDispatch<typeof store.dispatch>()
  const useSelector: TypedUseSelectorHook<ReturnType<typeof store.getState>> = useReduxSelector
  return { store, useDispatch, useSelector }
}

export { ReduxProvider, createStore, createSlice }
```

But I have a problem. Every developer create store own project from my library @fiba-ui/core

```
import { createStore } from '@fiba-ui/core'

export const { store, useDispatch, useSelector } = createStore({
    example:ExampleReducer
})
export type RootState = ReturnType<typeof store.getState>
```

But when they coded selector,for example;
`export const getToolbarButtonAction = (state: RootState) => state.example.toolbarButtonAction
`

state.example didn't find.  Rootstate is inferring only layout and api reducer. I examined compiled file store.d.ts;

```
import { Action, AnyAction, ReducersMapObject, createSlice } from '@reduxjs/toolkit';
import { Provider as ReduxProvider, TypedUseSelectorHook } from 'react-redux';
declare const createStore: <S, A extends Action<any> = AnyAction>(reducers: ReducersMapObject<S, A>) => {
    store: import("@reduxjs/toolkit").EnhancedStore<{
        layout: import("./layout/types").IndexType;
        api: import("@reduxjs/toolkit/dist/query/core/apiState").CombinedState<{}, never, "api">;
    }, AnyAction, import("@reduxjs/toolkit").MiddlewareArray<[import("redux-thunk").ThunkMiddleware<{
        layout: import("./layout/types").IndexType;
        api: import("@reduxjs/toolkit/dist/query/core/apiState").CombinedState<{}, never, "api">;
    }, AnyAction, undefined>, import("redux").Middleware<{}, import("@reduxjs/toolkit/dist/query/core/apiState").RootState<{}, string, "api">, import("@reduxjs/toolkit").ThunkDispatch<any, any, AnyAction>>]>>;
    useDispatch: () => import("@reduxjs/toolkit").ThunkDispatch<{
        layout: import("./layout/types").IndexType;
        api: import("@reduxjs/toolkit/dist/query/core/apiState").CombinedState<{}, never, "api">;
    }, undefined, AnyAction> & import("redux").Dispatch<AnyAction>;
    useSelector: TypedUseSelectorHook<{
        layout: import("./layout/types").IndexType;
        api: import("@reduxjs/toolkit/dist/query/core/apiState").CombinedState<{}, never, "api">;
    }>;
};
export { ReduxProvider, createStore, createSlice };
```

I noticed, reducers parameter doesn't use. I didn't solved this problem. 

Do you have any idea for this problem?

**Comment by markerikson** [comment]
You declared `store` ` as Store<S,A>`.  _Never_ do that - you're throwing away any additional type information.  Always let TS infer the final type of `store` itself.

**Comment by atillaaliyev** [comment]
Hi, i didn't put as Store<S,A>, probably while i trying different solution, i forgot there this code.

Original code hasn't it.
Do you have any solution about this?

**Comment by phryneas** [comment]
Generally, I'd really want to discourage you from doing this - you take away all the customizability of Redux and really lock your users in. 
Simple stuff like adding a middleware becomes impossible, including stuff that may be useful for debugging.  
We have heard a lot of frustrated complaints from users that had to deal with stuff like this in the past.

Apart from that - this won't work without you adding manual types on top.  
`S` and `A` are generic and TS cannot combine these not-yet-resolved generic types with the known ones you have at the point you call `typeof`.  
You will have to type your state type by hand. Also, the action type is just irrelevant. You can probably just leave that away everywhere.
