### ISSUE TITLE
InvalidatesTags runs after isSuccess

### ISSUE THREAD

**Issue by Alb93** [reduxjs/redux-toolkit#2955]
On the context of _rtk-query_ the `invalidatesTags` function runs after `isSuccess` is returned (is there a clear chart of rtkq lifecycle anywhere?). This could allow the following behaviour:
- a component X calls an _rtk-query_ endpoint, with the invalidatesTags on data fetched by component Y
- on success, a redirect is performed to component Y
- component Y calls a _rtk-query_ endpoint
- the component Y endpoint is called with success, data are returned but only then the invalidates tags ends, resulting in undefined data

Is there any way to avoid this? I was trying to look for something like `isInvalidated: boolean` as rtkq hook return value but I wasn't able to find something similar.

**Comment by markerikson** [comment]
We don't have a specific chart anywhere, but that might be useful.

Currently, tags are invalidated synchronously after the `fulfilled/rejected` actions have been processed by the reducer, on the way back out of the RTKQ custom middleware.  Given that, I don't _think_ the scenario you described is possible.

**Comment by aagranovExtend** [comment]
@markerikson there is no way for `invalidatesTags` to know that `rejected` happened and not run?

**Comment by phryneas** [comment]
@aagranovExtend if you use the function notation to `invalidatesTags`, you either get the response or the error as an argument and can decide if you want to invalidate (and what) based on that.

**Comment by aagranovExtend** [comment]
@phryneas any reason to not have the invalidatesTags be more opinionated and never allow the cache entry to be invalidated on error?

**Comment by markerikson** [comment]
@aagranovExtend that's the point - it's entirely reasonable to _want_ tags to be invalidated on error, so that's intentional behavior.

**Comment by aagranovExtend** [comment]
@markerikson could you give me a use case? If I'm getting back HTTP 4xx, it's reasonable to assume no mutation occurred on the server and thus no reason to invalidate the local cache entry.

**Comment by phryneas** [comment]
And if it's a 5xx, the server could have crashed before modifying data in the database - or after, but before returning the response.

**Comment by phryneas** [comment]
@liansnail this doesn't have to do anything with the topic discussed here, and I'm also not really sure what exactly you are asking. 
If I *do* understand you correctly: Yes, the correct way to decide which tags are invalidated, based on `result` or `error`, is in the `invalidateTags` function (that you can abstract away as much as you want).
If you have any further questions, please start your own discussion instead of reviving old threads that don't have anything to do with the question..
