### ISSUE TITLE
[Feature] Add mapEntity callback param to createEntityAdapter

### ISSUE THREAD

**Issue by olconstant** [reduxjs/redux-toolkit#2957]
Add `mapEntity` callback param to `createEntityAdapter` so that payload data can be mapped / transformed before going to store.

For instance, i want to transform the data to be save in store:
```javascript
const colsAdapter = createEntityAdapter({
  selectId: ({ field, colId = field }) => colId,
  mapEntity: colDef => {
    const { field, colId = field, headerName = field } = colDef;
    return { ...colDef, colId, field, headerName };
  }
});
```

Could be a very useful feature in my opinion.

**Comment by markerikson** [comment]
I'm not sure what this API is intended to be used for.  Could you give a concrete example?

**Comment by olconstant** [comment]
Sometime we need to store in the state/reducer a data slightly different than the data in the input payload. For instance, for handling default values if field is missing or null, or add computed fields...
The `createEntityAdapter` could accept a callback param to transform the data passed to adaptater `setAll`, `addMany`, and `upsertMany` methods, so that we don't need to map/iterate the data before calling these functions.

**Comment by markerikson** [comment]
Given that this _is_ fairly straightforward to do in the way that you showed, I'm not sure it's something we'd want to add.

Also, out of curiosity: is there a reason you're hand-writing a reducer instead of using `createSlice`?
