### ISSUE TITLE
Unable to update individual state in slice

### ISSUE THREAD

**Issue by Blacktiger** [reduxjs/redux-toolkit#296]
Maybe I'm just mis-understanding something from the docs, but it looks like immer isn't working correctly to me?

Given this slice:

```
createSlice({
  name: 'test',
  initialState: {
    isLoading: undefined,
    settings: {
      enabled: false
    },
  reducers: {
    start: (state) => {
      state.isLoading = true;
    },
    success: (state, action) => {
      state.isLoading = false;
      state.settings = action.payload.settings;
    }
}
```

When I dispatch the start event, the initialState seems to get blown away and all I get in the state is the `isLoading` flag that I set. From my reading of the docs the Immer Proxy should notice that I updated the isLoading field and just change that field right?

**Comment by markerikson** [comment]
That sounds very wrong.  You should end up with a new state object that has `isLoading: true`, but the rest of the data should be the same.

Can you reproduce this problem in a CodeSandbox?

**Comment by Blacktiger** [comment]
In my local code I switched my reducer definitions to return the full object (ie `(state) => ({ isLoading: true, ...state })`) and things worked as expected. I'll see if I can generate a codesandbox that duplicates.

**Comment by Blacktiger** [comment]
Well, I tried to duplicate the problem in a codesandbox, but it seems to be working correctly there. https://codesandbox.io/s/redux-starter-kit-circular-slice-dependencies-example-81ed8 Not sure what I'm doing differently in my app, but failing to have a good example to share I'll close this until I get a chance to look deeper into what I'm doing wrong.
