### ISSUE TITLE
Is it possible to use an external AbortController for the createListenerMiddleware API?

### ISSUE THREAD

**Issue by GibsDev** [reduxjs/redux-toolkit#2969]
Currently the only mention of AbortSignals [in the documentation](https://github.com/reduxjs/redux-toolkit/blob/6c8ef7749b53e3ac5749e30e3ebcb143bfaa8984/docs/api/createListenerMiddleware.mdx) seems to be used internally. Perhaps I am not understanding the documentation correctly, but it does not seem like you can specify one when you add a listener.

I recently discovered the convenience of using an AbortController to remove multiple `addEventListener`s, and was hoping the same could be done with the createListenerMiddleware API.

For now I am tracking `unsubscribe` functions returned by `store.dispatch(addListener({}))` in an array and looping through all of them to call them for cleanup.

**Comment by markerikson** [comment]
Yeah, the `AbortController` usage is purely an internal implementation detail for how we mark effect callbacks as canceled.

And yes, alling `unsubscribe()` yourself would be the public API to do cancelation.

Can you give an example of where/how you'd want to provide an `AbortController`?

**Comment by GibsDev** [comment]
Perhaps as another option in the `addListener({ signal: ... })` function would work? The same would go for `startListeneing`

``` javascript
const controller = new AbortController();
const signal = controller.signal;

store.dispatch(addListener({
    // ...
    signal
}));

// or

listenerMiddleware.startListening({
    // ...
    signal
});

```

But then I'm not sure how you would specify the unsubscribe options. I'm not using them in my use case, so I did not really consider them when I first made the issue.

I suppose if the purpose is to group together listeners and clean them up with a single abort call, you could construct some sort of special unsubscribe controller class where you specify the unsubscribe options/behavior paired with the abort signal, and then pass that to the `addListener` and `startListening`.

So maybe something like:

``` javascript
const controller = new AbortController();
const signal = controller.signal;

const unsubscriber = new Unsubscriber({ /* unsubscribe options */ }, signal);

store.dispatch(addListener({
    // ...
    unsubscriber
}));

// or

listenerMiddleware.startListening({
    // ...
    unsubscriber
});

```

**Comment by phryneas** [comment]
But then you could just do something like
```js
function getUnsubscriber(){
  const functions = []
  return {
    add(fn){ functions.push(fn) },
    clear(){ functions.forEach(fn => fn()) }
  }
}
```
and use that like
```js
const unsubscriber = getUnsubscriber();

unsubscriber.add(store.dispatch(addListener({
    // ...
})));

// or

unsubscriber.add(listenerMiddleware.startListening({
    // ...
}));

unsubscriber.clear()
```
which would do the same, just without the added complexity of an AbortSignal, right?

**Comment by markerikson** [comment]
Doesn't seem like there's anything specific for us to add here, so closing.
