### ISSUE TITLE
RootState for getState in RTK Query 

### ISSUE THREAD

**Issue by einarq** [reduxjs/redux-toolkit#2974]
Are there any docs for how to correctly wire up rtk query so that api.getState is typed correctly according to the rootReducer?
Is it possible to do something similar to what is done with listenerMiddleware and createAsyncThunk?

**Comment by phryneas** [comment]
No, since that would get you a circular type. You will have to assert with `as RootState` in the places where you use `getState` in your api.

**Comment by einarq** [comment]
Ok. I’m usually trying to avoid using “as”, was under the impression it was considered bad practice. Fine with making an exception for these cases tho.
