### ISSUE TITLE
Cannot get access token from one query through getState in another query

### ISSUE THREAD

**Issue by tmarinov82** [reduxjs/redux-toolkit#2976]
The first query take the token:
```
export const authAPI = cloudAppAPI.injectEndpoints({
  endpoints: builder => ({
    getUserProperties: builder.query({
      queryFn: async () => {
        const account = msalInstance.getActiveAccount();
        if (!account) {
          throw Error("No active account! Verify a user has been signed in and setActiveAccount has been called.");
        }
        const loginAccessToken = await getAccessToken(loginScopeMGT);
        const imageURL = await getUserImage(loginAccessToken);
        const accessToken = await getAccessToken(loginScope);

        return {
          data: {
            fullName: account.name,
            userName: account.username,
            tokenExpiration: account.idTokenClaims?.exp,
            imageURL: imageURL,
            accessToken
          }
        }
      },
    })
const token = authAPI.endpoints.getUserProperties.select({})
export const getToken = createSelector(token, (tokenResult) => tokenResult.data?.accessToken)
```

the second query try to access the token through getState:

```
export const cloudAppAPI = createApi({
  // The cache reducer expects to be added at `state.api` (already default - this is optional)
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({
    baseUrl: `${c3po_endpoint}api/`, prepareHeaders: (headers, { getState }) => {
      // const token = (getState() as fullState).accessToken
      // If we have a token set in state, let's assume that we should be passing it.
      // if (token) {
      //   headers.set('Authorization', `Bearer ${token}`)
      // }
      const stateData = getState() as any
      const token = getToken(stateData)
      
      return headers
    },
  }),
  // refetchOnFocus: true,
  endpoints: builder => ({
  })
})
  })
})

```
In the console log I can drill to the props I need but I cannot get to them via dot notation:
![image](https://user-images.githubusercontent.com/51916751/205739645-51180a6c-e24a-48c1-b613-d0ca3436ec30.png)
 Then I tried to create a selector in the first slice
const token = authAPI.endpoints.getUserProperties.select({})
export const getToken = createSelector(token, (tokenResult) => tokenResult.data?.accessToken)
but when I use this selector in the second slice getToken (stateData ) typescript complain that fullState is not the correct state.
I saw some example in https://redux-toolkit.js.org/rtk-query/usage/customizing-queries
![image](https://user-images.githubusercontent.com/51916751/205740214-370d2c51-8e58-4b4d-829a-88ed701b098c.png)
but I can't see the imported files.

**Comment by phryneas** [comment]
Please, format that stuff, it's unreadable.

**Comment by tmarinov82** [comment]
> Please, format that stuff, it's unreadable.

Done

**Comment by phryneas** [comment]
You should not read out of a cache value like this. 

If you actually need to access a token from JavaScript (most time you should not do that and rather use a `httpOnly` cookie, which the browser will automatically send to the server anyways and which cannot be stolen from JavaScript), save it to a normal slice [like in this example](https://redux-toolkit.js.org/rtk-query/usage/examples#using-extrareducers) and read it from that slice, not directly from the cache.

**Comment by tmarinov82** [comment]
As far as I understand you for some data you recommend state without caching(normal slice). I wanted to move everything to RTK Query Caches. How to determine which data is for normal state which is for cache? I planned to use very long  value for keepUnusedDataFor and keep some data in cache almost permanently. The problem in my solution is only typescript. I added some code in the two code snippet in the starting message. In the first snippet
```
const token = authAPI.endpoints.getUserProperties.select({})
export const getToken = createSelector(token, (tokenResult) => tokenResult.data?.accessToken)
```
In the second in fetchBaseQuery:

```
const stateData = getState() as any
const token = getToken(stateData)
```
Can you recommend me what to use instead of any? I will follow your advise and keep auth. data in normal slice, but I want to know how to properly annotate getState()
