### ISSUE TITLE
[Jest] RTK Query + react native: Expected signal to be an instanceof AbortSignal

### ISSUE THREAD

**Issue by Alaa-Ben** [reduxjs/redux-toolkit#2982]
Hi !
I'm setting up some tests for a react-native app that uses RTK+RTK Query.
When testing a component that uses a simple rtk query request (useGetPokemonByNameQuery for example), I come upon the following issue: 
```
 at new Request (node_modules/node-fetch/lib/index.js:1244:10)
        at node_modules/@reduxjs/toolkit/src/query/fetchBaseQuery.ts:263:21
        at step (node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:23:23)
        at Object.next (node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:4:53)
        at fulfilled (node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:95:32)
        at tryCallOne (node_modules/promise/lib/core.js:37:12)
        at node_modules/promise/lib/core.js:123:15
        at flush (node_modules/asap/raw.js:50:29)
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

After further investigation, I got these additional logs:
```
'TypeError: abortController.signal.addEventListener is not a function\n' +
        '    at ....../node_modules/@reduxjs/toolkit/src/createAsyncThunk.ts:596:34\n' +
```

any ideas ?

Every package i'm using is up to date (jest v29, rtk = 1.9.1, node version = v16.18.1)

**Comment by markerikson** [comment]
This wouldn't be about package versions - it's a question of whether your runtime environment implements the `AbortController` type internally.

**Comment by phryneas** [comment]
Also, it you are using polyfills, your version of `fetch` and `AbortController` need to come from compatible polyfills.

**Comment by Alaa-Ben** [comment]
@phryneas @markerikson 
I'm not using anything, just the jest preset "react-native"
If I understand correctly, it's a node environment (node 16), so it should have an abort controller.
I've tried  in a setup file:
```
const controller = new AbortController()
console.log(controller.signal.addEventListener)
```
and it does exist.
So I don't understand why it would work in the setup file but not when rendering a component that uses rtk :/

**Comment by phryneas** [comment]
That error is from the `node-fech` polyfill, which you seem to be using (at least in your jest environment). I cannot stress it enough: if you use a polyfill, you need a **matching** implementation of AbortController. The error message indicates that you mix it with another version - and that could also be the node 16 implementation.

**Comment by Alaa-Ben** [comment]
@phryneas 
I understood that. It's just that jest seems to be using the node-fetch polyfill (without me explicitly saying so) and I am a bit of newbie in this. So bear with me please haha :D 
Any tips/steps on what should I do (how to know which matching implementation I need  for example, etc.) ?

Here's where I am for now:

If i go to my test file (for example login.test.js) and try:
```
const controller = new AbortController()
console.log(controller.signal.addEventListener)
```
This prints undefined

So I added the following to the top of the file
```
import { AbortController } from 'abortcontroller-polyfill/dist/cjs-ponyfill'
global.AbortController = AbortController
```
Now my test file prints    `[Function: addEventListener]`
So it's still not undefined anymore
But the test still fails with the same issue
Moreover, if i move the 2 lines above from login.test.js to my setup file setupJest.js, it prints undefined again.
So I'm kinda confused. I'd really appreciate it if you could abre with me and give any tips !
