### ISSUE TITLE
Rtk query POST data not upload files

### ISSUE THREAD

**Issue by SahilScript9099** [reduxjs/redux-toolkit#2989]
I am sending two files with req in my app but its showing an error like this:
![image](https://user-images.githubusercontent.com/107239486/206706997-ed5a1912-53d2-4c7b-a8f7-4ff0e80c7293.png)
![image](https://user-images.githubusercontent.com/107239486/206707986-525ca442-1d17-4204-8522-5a5cc2134c58.png)

I don't know how to solve it 
I am also sharing my service file 

![image](https://user-images.githubusercontent.com/107239486/206707384-5c05efdb-0535-418b-a76a-ca2f60f9343e.png)

and its payload is like this

![image](https://user-images.githubusercontent.com/107239486/206707645-d4d1e141-9416-4be9-8549-e1e4686b108e.png)

**Comment by phryneas** [comment]
RTK Query just calls `fetch`. Find out how you would call `fetch` with an upload like this and then return that from `query`.

**Comment by SahilScript9099** [comment]
can you provide any example ??

**Comment by vikasdev8** [comment]
Hi shahil,

did you find a solution to upload the file through RTK query?
if yes then please share that solution with me also i am facing the same problem in my code
