### ISSUE TITLE
How to setup RTK query to work with OAuth providers like Google or Facebook?

### ISSUE THREAD

**Issue by reza-ebrahimi** [reduxjs/redux-toolkit#2991]
How to setup RTK query to work with OAuth providers like Google or Facebook?

I couldn't find any example on the internet.

**Comment by blwinters** [comment]
After you get back the access token or other tokens from those OAuth providers, add them into your redux store. Then, when you call `fetchBaseQuery` inside `createApi` from RTKQuery, there you should implement the `prepareHeaders` argument, which gives you access to call `getState()`, get your tokens, and add them to the headers. This part looks something like:

```
const baseQuery = fetchBaseQuery({
  baseUrl: Config.baseUrl,
  prepareHeaders: (headers, { getState }) => {
    headers.set('Content-Type', 'application/json')

    const state = getState() as RootState
    const tokens = selectTokens(state)
    if (tokens) {
      headers.set('Authorization', `Bearer ${tokens.accessToken}`)
    }

    return headers
  },
})
```

**Comment by reza-ebrahimi** [comment]
> After you get back the access token or other tokens from those OAuth providers, add them into your redux store. Then, when you call `fetchBaseQuery` inside `createApi` from RTKQuery, there you should implement the `prepareHeaders` argument, which gives you access to call `getState()`, get your tokens, and add them to the headers. This part looks something like:
> 
> ```
> const baseQuery = fetchBaseQuery({
>   baseUrl: Config.baseUrl,
>   prepareHeaders: (headers, { getState }) => {
>     headers.set('Content-Type', 'application/json')
> 
>     const state = getState() as RootState
>     const tokens = selectTokens(state)
>     if (tokens) {
>       headers.set('Authorization', `Bearer ${tokens.accessToken}`)
>     }
> 
>     return headers
>   },
> })
> ```

@blwinters Thanks a lot, This code solved the problem.
