### ISSUE TITLE
React Redux Toolkit Type Errors Suddenly

### ISSUE THREAD

**Issue by Karsenh** [reduxjs/redux-toolkit#3002]
I worked on this project a couple months ago and deployed it to Heroku - everything was functional and then Heroku decided to end their free dynos so I opened the project back up only to be greeted with a red underline in almost every file, all of which have one thing in common; they're Redux / Toolkit methods with errors pertaining to Types.

![image](https://user-images.githubusercontent.com/21287816/207528996-e801f6b7-a486-4ee2-bdff-a76350fcc603.png)

![image](https://user-images.githubusercontent.com/21287816/207527892-d1adbbaa-6fcb-4d4d-9d70-1f2a043da156.png)
![image](https://user-images.githubusercontent.com/21287816/207528217-601fb8f2-3f93-4316-bd3d-49bbe348beec.png)

This one is not related to Redux (?)
![image](https://user-images.githubusercontent.com/21287816/207528387-cb73478c-ccc9-42b9-acd9-55665a120ce6.png)

Everything still works when compiling and running but all my files are red and there are countless red underlines on just about everything pertaining to Redux.

Can anyone tell me what's going on here?

EDIT: I'm no longer sure this is an issue with Redux considering not only is there another issue unrelated but also due to the fact that I have an earlier version of the project which is not experiencing red underlines everywhere. The only difference that I'm aware of is the file hierarchy (left working | right is full of errors). 

![image](https://user-images.githubusercontent.com/21287816/207531973-59dc9251-c289-402c-b392-6da6ac69dc23.png)

**Comment by phryneas** [comment]
You are using JavaScript - these are TypeScript errors. 
Since you are not using TypeScript and as a consequence not writing any type annotations, there is no way for TypeScript to know things like your state shape etc. (in TS, you would even have to use the hooks differently, by [creating typed hooks just for your application](https://redux-toolkit.js.org/tutorials/typescript#define-typed-hooks)).

This has nothing to do with Redux Toolkit and is probably an editor setting that now starts showing you TS errors.

**Comment by Karsenh** [comment]
> You are using JavaScript - these are TypeScript errors. Since you are not using TypeScript and as a consequence not writing any type annotations, there is no way for TypeScript to know things like your state shape etc. (in TS, you would even have to use the hooks differently, by [creating typed hooks just for your application](https://redux-toolkit.js.org/tutorials/typescript#define-typed-hooks)).
> 
> This has nothing to do with Redux Toolkit and is probably an editor setting that now starts showing you TS errors.

Thank you for the reply, Phryneas.

I actually _just_ figured out my issue which was apparently something breaking when I restructured my projects file hierarchy (pulling out my server into the root dir) for Heroku deployment.

Nothing to do with Redux indeed! Thanks again.
