### ISSUE TITLE
How to reset Redux toolkit query state (query, not mutation)?

### ISSUE THREAD

**Issue by mazebenz** [reduxjs/redux-toolkit#3013]
In Redux toolkit query we write as follows in mutations:
```js
const [purchase, { isLoading, isError, isSuccess, reset }] = useCreateOneSaleMutation()
```
and we can use the **reset** method to reset the state.

Is there a way I can do the same in the query hooks?
```js
const { isLoading, isError, isSuccess, reset } = useGetOneSaleQuery()
```
* we can do `refetch` which actually exists, but I need something to **reset** these states in a component on call, so I need a **reset** method. 

Is it supported in redux toolkit query? 

I depend on `isSuccess` in a useEffect to render some logic, and I need this `isSuccess` to reset back to false when the component unmounts.

I have a modal, and when this modal closes, it should reset back to false, because the useEffect looks as follows:

```js
useEffect(()=>{
   switch(true){
      case isSuccess:
        setText('Transaction completed successfully!')
      break
      default:
        setText('Please Enter The client id')
   }
}, [isSuccess])
```

so there must be something like
```js
useEffect(()=> ()=> reset())
```
in order for this kind of logic to work.

asked on stackoverflow as well https://stackoverflow.com/q/74829321/20779272

**Comment by phryneas** [comment]
Are you sure that this is really a query? From the wording, it sounds like something triggers some external side effect, which should be a mutation.

**Comment by mazebenz** [comment]
@phryneas , yes.

**Comment by mazebenz** [comment]
sorry, the question is wrong. just a minute, I'll correct it right away

**Comment by mazebenz** [comment]
yes now I'm sure again.

**Comment by mazebenz** [comment]
just to mention something, I'm not sure if this is related to the solution, I have created a wrapper hook for the useXXXQuery hooks. 

it works like the following:
```js
const [findOneUser, { isLoading, isSuccess, isFetching, isError, data }] = useCreateQuery(useGetOneUserQuery)
```
which basically skips on load, and initiate a query on function call, just like any useXXXMutation() hook.
so for instance, I can call `findOneUser()` and this will initiate the query, (sets skip to false and so on), 

here's the hook source code: (again, not sure if would be helpful to include it here):
```js
export default function useCreateQuery(useHook, initialQueryVal = null, hookArgs_) {
  const [state, setState] = useStates({ skip: true, queryArg: initialQueryVal })
  const hookArgs = mergeObjects({ skip: state.skip }, hookArgs_)
  const returned = useHook(state.queryArg, hookArgs)
  const createQuery = (queryArg) => {
    setState({ skip: false, queryArg })
  }
  return [createQuery, returned]
}
```

**Comment by mazebenz** [comment]
Perhaps the question should be, **How to prevent it from caching the result**,
but not everywhere, only in this component, there must be an option inside the query hook itself, maybe something like:
```js
const {isLoading, isSuccess, ...etc} = useGetOneUser(undefined, { disableCaching: true })
```

**Comment by phryneas** [comment]
Without actually understanding why you rely on that `isSuccess` here I'm afraid I can't really help you here. 
Generally, the point of RTK Query is to cache queries.
You could force it to use different cache entries by just generating a random number every time and using that as an argument, but tbh., I think you are just abusing the tool for something it isn't meant to - I just can't put the finger on it because you are not giving sufficient context.

**Comment by samislam** [comment]
> Without actually understanding why you rely on that `isSuccess` here I'm afraid I can't really help you here. Generally, the point of RTK Query is to cache queries. You could force it to use different cache entries by just generating a random number every time and using that as an argument, but tbh., I think you are just abusing the tool for something it isn't meant to - I just can't put the finger on it because you are not giving sufficient context.

ok let me think of a simpler example. 
maybe I'll do a sandbox on stackblitz.

anyway, isn't it right that there should be an option for the useQuery() hooks to prevent caching?

for example
```js
const {isLoading, isSuccess, ...etc} = useGetOneUser(undefined, { disableCaching: true })
```

**Comment by markerikson** [comment]
@samislam : but.... _why_?

As Lenz said, literally 90% of the point of RTKQ _is_ to cache data.

_Why_ would you ever want to _not_ cache the result?

**Comment by phryneas** [comment]
"preventing caching" would literally mean "the component fires a new request on every rerender".  
That is not very desirable.

"preventing global caching" would mean "we use local component state".  
At that point, we would have to actively **not** use Redux in "**Redux** Toolkit Query" which is a *caching library*. That also doesn't sound like a very good idea for a feature tbh. - at that point, we should rather recommend using another tool for that part of the job :/

I'm really curious about an example use case here though.

**Comment by phryneas** [comment]
> so doing polling, or _automatically refetches every 60 seconds_ in this scenario wouldn't be accurate, and is not the right solution. There must be a force-query technology from the client side to push the request any how to the backend without looking for the caches.

Then you would probably use `refetchOnMountOrArgChange`, but still have a value in having the last result immediately accessible.

**Comment by phryneas** [comment]
Also, you can always check if `isSuccess` and `isFetching` are both `true` if you use it with `refetchOnMountOrArgChange`. But still... without knowing hat you actually do, it feels like there might be a better general approach.

**Comment by phryneas** [comment]
By the way, what I referenced above: 
```js
const [timeOfMount] = useState(new Date().getTime())
const result = useSomeQuery({ at: timeOfMount})
```

**Comment by samislam** [comment]
Yes, you're right. 
I've thought about it, there is no reason to just ignore the cache and make up a new request. 
You might however `refetch` the data.

But we're still stuck in this `isSuccess` being always true due to the cache problem.

ok, let me think of another approach perhaps I can fix it in another way.

and having `isSuccess` set true is the right thing because that's how it's in the cache. 
so it doesn't make any sence to have a `reset` method. 

if we would have a reset method, then that `reset` job will be to clear the cache, and not to only reset the states back to false.

and as you mentioned, it's not an option.

However, I believe you already have some method to invalidate the cache from within the code in the components, I just have find that out in the documentation. 
maybe it's not inside the return value of the `useQuery`, ie:
```js
const { currentCacheObject } = usefindOneUserQuery()
 ```
but maybe it's somewhere else, perhaps
```
import mainApiSlice from '../services/mainApiSlice.js'

const cacheObject = mainApiSlice.endpoints.findOneUser.currentCacheObject;

cacheObject.invalidate("?clientId=123456&name=xyz")
```

I wouldn't do that though, I should better be fine finding another approach as you said to solve this problem.

**Comment by markerikson** [comment]
@samislam : "invalidate" has a very specific meaning, which is "force RTKQ to go try to refetch the data".  It sounds like what you want is to _remove_ the cache entry instead?

Reading the initial description, you said:

>  need this isSuccess to reset back to false when the component unmounts.

I'm not sure that's a good way to think about the logic.  Can you show more of the actual component / relevant code?

**Comment by samislam** [comment]
@markerikson, @phryneas, 
thanks for your recommendations. 
We solved the problem, as you said, I only need to find another approach for it. 
Now caching is not a problem anymore, let it cache, it's a win. 

Are you interested to see the code, if yes, I can make a sandbox for it?
Basically, I changed the `useEffect` in the modal from, to:
```js
// from:
useEffect(()=>{
   switch(true){
      case isSuccess:
        setText('Transaction completed successfully!')
      break
      default:
        setText('Please Enter The client id')
   }
}, [isSuccess])
```
```js
// to:
const [isQueried, setQueried] = useState(false)
useEffect(()=>{
   switch(true){
      case isSuccess:
        setText('Transaction completed successfully!')
      break
      default:
        setText('Please Enter The client id')
   }
}, [isSuccess, isQueried])

useEffect(()=> {
// this cleanup hook runs when the modal gets closed, or opened
setText("") // reset
setQueried(false) // reset
}, [isModalOpen])
```
And there's the form where everything gets started, basically.
```js
  const handleSubmit = (e) => {
    e.preventDefault()
    setQueried(true) // this is the new change
    findOneUser(`clientId=${clientId}`) 
  }
```

**Comment by phryneas** [comment]
I still don't know why you do not just go with 
```
const [timeOfMount] = useState(new Date().getTime())
const result = useSomeQuery({ at: timeOfMount})
```
if all you want is separate cache entries.

Take your solution and mount it twice - both mounted components will influence each other. If you want that stuff to be separate (like it seems to be the case here), also make sure they are separate.

**Comment by Tasin5541** [comment]
@phryneas having a `reset` option for query would definitely help. Take for example, we have a derived variable that reads from the result of 2 queries (whichever is present or the latest one fetched).

```
const { trigger1, { data: data1 } } = useData1LazyQuery();
const { trigger2, { data: data2 } } = useData2LazyQuery();
const derVal = data1 || data2 || null
```

We need the `derVal` to always point to the latest data. If `data2` is fetched after fetcing `data1`, `derVal` should be `data2`.

Having an option to reset the other query's state during triggering one query would definitely be the best approach here.

```
const { trigger1, { data: data1, reset: reset1 } } = useData1LazyQuery();

// trigger data2 handler
reset1(); 
trigger2();
```
