### ISSUE TITLE
How can I trigger my query but in other file ?

### ISSUE THREAD

**Issue by shop-fluencer** [reduxjs/redux-toolkit#3022]
Hello,

I show a list of items in my Order.tsx file. But I also have a HeaderOrder.tsx file. In the header file is a filter button when I press the button I want to trigger my LazyQuery in Order.tsx file. Is that possible ?

how can I trigger this in Order.tsx
`  const [trigger, { isLoading: isLoadingSearch, isFetching: isFetchingSearch, data: searchData }] = useLazyGetSearchedOrdersQuery();`

When I am on Header.tsx screen ?

**Comment by rubentlc** [comment]
If I understood your question, everytime that you need to get the information ,even in different components, you just need to trigger again the query. Take in consideration that if you are using a Lazy query, you need to pass the second prop of the query as true, if you want to get info from cache first.
