### ISSUE TITLE
Type of dispatch result

### ISSUE THREAD

**Issue by qramilq** [reduxjs/redux-toolkit#3025]
Hello.
I'm using the base CRA-Redux template
```shell
npx create-react-app my-app --template redux-typescript
```
What I need to do is to pass a dispatch result as callback to parent component. But I don't know which type should be the `dispatchResult`. Can you help me with this issue?
<img width="515" alt="image" src="https://user-images.githubusercontent.com/14158291/209328423-66a1e90e-22f9-424f-aa85-1a7d6c5c867d.png">

**Comment by phryneas** [comment]
Well... what do you need? 

TS is not about describing what is actually being passed around to the last little part of it, but about describing what you want to use.

So, take a look at it - it's a `Promise` of an action, either with a `payload` property or of an `error` property. Those might have values.

Do you really want to care about that? Then use
```js
Promise<
  | { payload: MyPayloadType }
  | { error: { message: string } } // describe the parts you actually are interested in here!
>
```

Or do you just want the success case?

Calling `const dispatchResult = dispatch(incrementAsync(incrementValue)).unwrap()` will give you a `Promise<TypeYouReturnFromtheThunk>`.

**Comment by qramilq** [comment]
Hello, @phryneas . Thanks for answering.
I want to, for example, send some analytics based on the result of some async operation by unwrapping actions.
```

const App = () => {

  const handleAfterAsyncIncrement = async ({dispathcResult})=>{
    try {
      await dispathcResult().unwrap()

      sendAnalytics('success incremented')
    } catch(e){
      sendAnalytics('incremented with error:', e)

    }
  }

  return <Counter onAfterAscyncIncrement={handleAfterAsyncIncrement}/>
};
```

I found some "hacky" way to get types of dispatch result using ReturnType twice, but I'm not sure is this is a good practice and maybe we have some more elegant and legal way)

```
onClick: ({dispatchResult}: {
  dispatchResult: ReturnType<ReturnType<typeof incrementAsync>>;
}) => void;
```
