### ISSUE TITLE
Better recommendation on no-param-reassign eslint rule in the docs?

### ISSUE THREAD

**Issue by Luk-z** [reduxjs/redux-toolkit#3036]
In the docs it's recommended to ignore param reassign on all `state` params. 
This applies to all functions and this isn't smart enough.
I just link @MikelArnaiz proposal on comment https://github.com/reduxjs/redux-toolkit/issues/521#issuecomment-1362655465.

I think the docs must be updated with that better recommendation.

**Comment by phryneas** [comment]
Then make a pull request? :)

**Comment by Luk-z** [comment]
done https://github.com/reduxjs/redux-toolkit/pull/3038

**Comment by markerikson** [comment]
Thanks!
