### ISSUE TITLE
How can I 'listen' for status=401 in RTX-query to logout and navigate the app to the homepage?

### ISSUE THREAD

**Issue by Ks89** [reduxjs/redux-toolkit#3040]
I have an app written with RTX Query with a `commonApi` like this one:

```
export const commonApi = createApi({
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({
    baseUrl: '/api/',
    prepareHeaders: headers => {
      headers.set('Content-Type', 'application/json');
      headers.set('Authorization', 'Bearer ' + token);
      return headers;
    }
  }),
  tagTypes: ['Homes', 'Profile'],
  endpoints: _ => ({}),
});
```

I don't have `/refreshtoken` on my server and I want to simply logout and redirect to the home page when an API returns status=401.
How can I implement this with RTX Query?

Thanks.

**Comment by markerikson** [comment]
Off the top of my head, you'd probably want to create a custom `baseQuery` that wraps around `fetchBaseQuery`, and checks the status:

https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#customizing-queries-with-basequery

**Comment by Ks89** [comment]
@markerikson thanks you, it worked!
I used this code https://github.com/reduxjs/redux-toolkit/discussions/2097#discussioncomment-3079703 as base to write my solution.
