### ISSUE TITLE
Does the case (Streaming Update Examples) provided in the document mean that each channel needs to establish a WebSocket connection?

### ISSUE THREAD

**Issue by ZivGit** [reduxjs/redux-toolkit#3043]
### Streaming Update Examples
Websocket Chat API: [https://redux-toolkit.js.org/rtk-query/usage/streaming-updates#websocket-chat-api](url)

### What should I do if the chat project only shares one WebSocket link?

**Comment by phryneas** [comment]
Then use only one websocket? That is one possible example, you do not *need* to create a new websocket for every cache entry.

**Comment by markerikson** [comment]
It's an example of _one_ possible way to use RTKQ, to give some ideas of what you _can_ do.  It's definitely not the _only_ thing you can do with RTKQ :)
