### ISSUE TITLE
Properly way to clean cache data

### ISSUE THREAD

**Issue by rubentlc** [reduxjs/redux-toolkit#3045]
I'm splitting my API using the injectEndpoints. But for my current project, when the user left same pages, we need to simple clean some data from cache and request again when the user back again. To do that I was thinking to use the property "resetApiState". 

So, for example, if I create an API slice with the name projectApi using the injectEndpoints, I was trying to clean the projectApi cache, with projectApi.util. resetApiState() dispatch. But I released that with this dispatch I was cleaning all the cache of all my API slices and not just my projectApi slice.

I also tried to use the invalidateTags but this this is firing again the request and it's not what we need.

So, there are a simple way to clean some data from cache?

Currently, the workaround that I'm doing is creating several API's and in this way I'm able to clean the data that I need when I need using the resetApiState dispatch.

Thanks for the help

**Comment by GeorchW** [comment]
> I also tried to use the invalidateTags but this this is firing again the request and it's not what we need.

`api.utils.invalidateTags` should not trigger a refetch if there are no subscribers, i.e. if no components are mounted that have a `useQuery` hook inside them. Do you want your components to keep being uninitialized?

**Comment by rubentlc** [comment]
> > I also tried to use the invalidateTags but this this is firing again the request and it's not what we need.
> 
> `api.utils.invalidateTags` should not trigger a refetch if there are no subscribers, i.e. if no components are mounted that have a `useQuery` hook inside them. Do you want your components to keep being uninitialized?

Thanks for the answer. Yes I figure it out and if works properly. I just forgot to close this. Thanks
