### ISSUE TITLE
Same store using in two different project

### ISSUE THREAD

**Issue by atillaaliyev** [reduxjs/redux-toolkit#3055]
Hi,
I have two projects: @fiba-ui/core-banking(You imagine there are a lot of independent projects like this) and @fiba-ui/features.
@fiba-ui/core-banking  **main.tsx**

```
createRoot(document.getElementById('root') as HTMLElement).render(
  <StoreProvider store={store}>
    <RouterProvider router={router} />
  </StoreProvider>,
)
```

store.ts

```
import { baseApi, createDispatch, createStore, createSelector, layoutReducer } from '@fiba-ui/core'

export const store = createStore({
  reducer: {
    layout: layoutReducer,
    [baseApi.reducerPath]: baseApi.reducer,
  },
  middleware: (gDM) =>
    gDM({
      serializableCheck: false,
      devTools: {},
    }).concat(baseApi.middleware),
})

export const useDispatch = createDispatch(store)
export const useSelector = createSelector(store)
export type RooState = ReturnType<typeof store.getState>

```

@fiba-ui/core-banking have a lot of pages and it's simple react project.

@fiba-ui/features is project that have side-effect components: CustomerSearch, AccountSearch,etc. But these components use some layoutReducer variables from store in @fiba-ui/core-banking or inject endpoint to baseApi.

I tried sending to @fiba-ui/features useDispatch and useSelector with Context.Then I tried using them. But I got "could not find react-redux context value; please ensure the component is wrapped in a <Provider>".

Do you have any solution?

**Comment by markerikson** [comment]
What are `createDispatch` and `createSelector`?  Are those creating unique React context instances of some kind?

**Comment by atillaaliyev** [comment]
It is basic useAppDispatch. It is little detail about project

https://redux.js.org/usage/usage-with-typescript

**Comment by markerikson** [comment]
The standard hooks won't cause context errors by themselves, so there has to be something going on with your project's build setup.  

The most likely cause would be multiple versions of React or React-Redux getting loaded into the page, and thus multiple instances of `ReactReduxContext` getting created.

**Comment by atillaaliyev** [comment]
This error is caused by using it in the @fiba-ui/features project. I need to use the store in the @fiba-ui/core-banking project in the @fiba-ui/features project. But @fiba-ui/features is a component project and how can I use store provider in component project, i dont know.

I will try ReactReduxContext solution.

**Comment by atillaaliyev** [comment]
I solved my problem another methods.
