### ISSUE TITLE
Comparing Feature Sets of RTK Query to urql is incorrect/inaccurate

### ISSUE THREAD

**Issue by Penguibird** [reduxjs/redux-toolkit#3057]
On this section of the page https://redux-toolkit.js.org/rtk-query/comparison#comparing-feature-sets it has a question mark for optimistic updates in urql.

Optimistic updates, however, do exist in urql. Viz https://formidable.com/open-source/urql/docs/graphcache/cache-updates/#optimistic-updates

In other minor things, most of the features described as '?' in urql could be implemented via a custom exchange with varying level of difficulty. At least for the easier examples, like Lagged queries, it may be more accurate to say 'requires manual code'.

**Comment by markerikson** [comment]
Yeah, if you see any issues with those comparisons, please file a PR to update them!

**Comment by phryneas** [comment]
Tbh., I don't see a lot of value in that page - maybe we could also think about removing it.
