### ISSUE TITLE
RTK Query graphql errors that have 200 codes

### ISSUE THREAD

**Issue by DominicGBauer** [reduxjs/redux-toolkit#3058]
## Description
When I receive graphql errors the standard is for the code to be 200 (which seems to be a standard - sorry if I'm wrong on this because I'm new to this graphql game) and have a response like:

```
data: null,
[
    {
        "message": "This session was created too long ago. Log in again before retrying.",
        "path": [
            "cp"
        ],
        "extensions": {
            "code": "stale_session"
        },
        "code": "stale_session"
    }
]
```

However, this isn't picked up as an error when using something like `{..., error, isError} = useSomeQuery()`.

Not sure if this is an issue for here but wondering if there is a way to get this 200 response to be an error client side or if there's a way around this?

**Comment by phryneas** [comment]
If `graphql-request` picks it up as an error, it will be handled as an error.

**Comment by DominicGBauer** [comment]
Oh my goodness @phryneas sorry I made an error. I was doing this (trying to set an error using catch clause):

```
  const handlePasswordChange = (currentPassword: string, newPassword: string) => {
    setChangePasswordErrorMessage('')
    checkPassword({ username, password: currentPassword })
      .then(() => {
        changePassword({ newPassword }).catch(() => {
          setChangePasswordErrorMessage('There was an error. Please try again.')
        })
      })
      .catch(() => setChangePasswordErrorMessage('Passwords do not match. Please try again.'))
  }
```

And assumed the error would be caught in the catch but you are right you can use `isError` or `error` from `useSomeQuery`. 

Sorry about that, thanks a lot!
