### ISSUE TITLE
Typescript types api as any when I concat a middleware array

### ISSUE THREAD

**Issue by LoyalPotato** [reduxjs/redux-toolkit#3059]
In my store configuration I have the following code:

```js
// Array of api middlewares (using createApi)
const midArr = [
 //... I have several apis that are typed correctly
 diarySvc.middleware // api that is causing typescript error
]

const store = configureStore({
reducer: {

// [diarySvc.reducerPath]: diarySvc.reducer
},
middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      serializableCheck: false,
    }).concat(midArr),
})
```

Or with the reducer:

```js
// Array of api middlewares (using createApi)
const midArr = [
 //... I have several apis that are typed correctly
 //diarySvc.middleware
]

const store = configureStore({
reducer: {
//... other api reducers
[diarySvc.reducerPath]: diarySvc.reducer
},
middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      serializableCheck: false,
    }).concat(midArr),
})
```

Here, with the `diarySvc` in the `midArr`, when concatenated with the return value of `getDefaultMiddleware`, will suddenly type it as `any`, while the rest of the apis are still correctly typed. The same happens if I just set it in the reducers *`[diarySvc.reducerPath]: diarySvc.reducer`* without having it in the `midArr` and concatenating with the default middleware.

But as soon as I stop using the `diarySvc` api in any point of the store configuration it stops typing the `diarySvc` api as `any`.

Api definition, using react version
![image](https://user-images.githubusercontent.com/10759876/210769364-11147027-b248-4a42-8343-b2c8e459f8be.png)

No concatenation
![Pasted Graphic 11](https://user-images.githubusercontent.com/10759876/210769249-b65bdd9e-60af-4b8b-a6aa-5a787d6f1d50.png)

After concatenation
![Pasted Graphic 12](https://user-images.githubusercontent.com/10759876/210769294-7cf9f450-4622-499b-a02b-beee53d4428d.png)

My typescript version is: 4.7.3
RTK: 1.9.1

**Comment by markerikson** [comment]
What does TS think the type of `diarySvc.middleware` is, in the file that you called `createApi`?  

Can you put together a CodeSandbox or repo that shows this happening?

**Comment by LoyalPotato** [comment]
It's also typing it as `any`:
>const diarySvc: any
'diarySvc' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)

But I found the culprit.

I didn't include in the screenshot of the api because I didn't think it'd be relevant, but it turns out that it is what's causing typescript to incorrectly type the api.
In an endpoint, I have a query definition and for the url I'm using the store state to get a value,
```js
url: store.getState().vm.user?.id ?? "",
```
And when I use it in the store it leads to the `any` typing.

Is it some sort of circular typing that causes the type to become `any` when used in the store?

**Comment by markerikson** [comment]
Yes, **_don't_ import the store back into the middleware!**

Depending on where you need it, there may be `getState()` available as an argument.  I don't _think_ it's available in the `query` option, so I'm not sure what the best solution is there.

**Comment by LoyalPotato** [comment]
I'll figure something out.
Thank you for your time! I'm gonna go ahead and close the issue then :)

**Comment by EskiMojo14** [comment]
fwiw @LoyalPotato you can use a [queryFn](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#customizing-queries-with-queryfn) to get getState access, e.g.
```ts
const api = createApi({
  baseQuery,
  endpoints: (build) => ({
    myEndpoint: build.query({
      queryFn: async (arg, { getState }, fetchWithBQ) => {
        return fetchWithBQ({ url: getState().vm.user?.id ?? "" });
      }
    }),
  }),  
})
```
the only caveat is that you're not able to use transformResponse with a queryFn, as you're expected to transform the data before returning it
```ts
const api = createApi({
  baseQuery,
  endpoints: (build) => ({
    myEndpoint: build.query({
      queryFn: async (arg, { getState }, fetchWithBQ) => {
        const resp = fetchWithBQ({ url: getState().vm.user?.id ?? "" });
        if (resp.error) {
          return resp;
        }
        const { data, meta } = resp;
        return { data: transformResponse(data, meta, arg), meta };
      }
    }),
  }),  
})
```

**Comment by LoyalPotato** [comment]
@EskiMojo14 Yeah that was I ended up using :)
Thank you anyways!
