### ISSUE TITLE
fetchBaseQuery doesn't override 'method' field

### ISSUE THREAD

**Issue by alex-vukov** [reduxjs/redux-toolkit#3061]
Using `fetchBaseQuery` it's possible to override the headers and other options for all requests in one place except for the `method` field. It's hardcoded as `GET`. Is there a reason for this? I have a use-case where all of my requests use `POST` so it would be convenient to have it overridden in a single place. It could be changed to fallback to `GET` by default.

**Comment by phryneas** [comment]
Have you tried it, or are you just assuming this? You should be able to pass any argument that would be passed into `fetch` directly into `fetchBaseQuery`, and they should be a default for all usages.

**Comment by alex-vukov** [comment]
I tried it. `method` passed to `fetchBaseQuery` is ignored.

**Comment by phryneas** [comment]
Huh, that was indeed an oversight. Could you please test the CodeSandbox CI package build from #3062 and give feedback if that works for you?

**Comment by alex-vukov** [comment]
Nice reaction time :) I tested it and it works correctly with this build! Also it correctly falls back to 'GET' if no method is specified.
