### ISSUE TITLE
Bug: Incorrect type inference for action matcher in listener middleware

### ISSUE THREAD

**Issue by Wedvich** [reduxjs/redux-toolkit#3066]
When adding a listener through the listener middleware and using one of the matcher utilities, the action type in the effect is incorrectly inferred to `AnyAction` instead of the matched type.

```ts
listenerMiddleware.startListening({
  matcher: isAnyOf(
    slice.actions.addString.match,
    slice.actions.addNumber.match
  ),
  effect: (action) => {
    // action is AnyAction, but this is the expected type:
    // {
    //     payload: string;
    //     type: "repro/addString";
    // } | {
    //     payload: number;
    //     type: "repro/addNumber";
    // }
  },
});
```

Minimal repro: https://github.com/Wedvich/redux-listener-inference-repro

**Comment by phryneas** [comment]
That's a TypeScript inference problem - if you move it into a variable declaration directly before, it behaves correctly:
```ts
const matcher = isAnyOf(
  slice.actions.addString.match,
  slice.actions.addNumber.match
)
listenerMiddleware.startListening({
  matcher,
  effect: (action) => {
```

unfortunately, there is not much we really can do about that.

**Comment by Wedvich** [comment]
Oh, okay! Thanks for clearing it up - that workaround works for me 👍
