### ISSUE TITLE
FETCH_ERROR with RTK Query, MSW, Vitest

### ISSUE THREAD

**Issue by albertofcasuso** [reduxjs/redux-toolkit#3069]
I'm trying to test a component in React that uses RTK Query + MSW + Vitest. It works fine on the browser but while testing RTK Query with vitest it throws this error:

`{ status: 'FETCH_ERROR', error: 'TypeError: fetch failed' }`

I've setup a [public repo](https://github.com/albertofcasuso/rtk-query-msw-vitest-error) with the configuration i'm using to replicate the error.

Another error RTK Query throws only while testing is:

`TypeError: Failed to parse URL from /api/test?page=1&limit=10`

This happens when i setup the fetchBaseQuery - baseUrl as empty or as a relative URL. I have to specify 'http://localhost...' or it wont work. But, it works in the browser.

[Repo with the error](https://github.com/albertofcasuso/rtk-query-msw-vitest-error)

Followed some articles on the matter with no success.
Searched Stackoverflow and found nothing.
Searched RTK query repo issues and found a similar issue but with jest instead of vitest
I've tried clearing query cache between tests - no success.

**Comment by markerikson** [comment]
Most likely you'll need to define `fetch` in a setup function, similar to how we do it in our own tests:

https://github.com/reduxjs/redux-toolkit/blob/67a69e876812282ad7fe5590d173a88bd7b80282/packages/toolkit/jest.setup.js

**Comment by targhs** [comment]
I got the same error. Did the suggested changes but not its saying that `Request is not a constructor`
