### ISSUE TITLE
How to cancel actions in middleware

### ISSUE THREAD

**Issue by loctary** [reduxjs/redux-toolkit#3070]
I'd like to cancel some/all pending actions on route change in middleware.
I think this is the proper way to do this, but there's no API to cancel them without actual promise. How do I achieve this?
```
import { createListenerMiddleware, isPending } from '@reduxjs/toolkit';
import { routerLocationSelector } from '../selectors';
import { Store } from '../../types';

const listenerMiddleware = createListenerMiddleware<Store>();
const cancelMiddleware = createListenerMiddleware<Store>();

const actions = {};

listenerMiddleware.startListening({
  effect: (action) => {
    if (isPending(action)) {
      actions[action.meta.requestId] = action;
    } else {
      delete actions[action.meta.requestId];
    }
  },
  predicate: () => true,
});

cancelMiddleware.startListening({
  effect: () => {
    console.log('this is the moment i want all my actions to cancel');
  },
  predicate: (action, currentState, prevState) =>
    routerLocationSelector(currentState) !== routerLocationSelector(prevState),
});

export { listenerMiddleware, cancelMiddleware };
```

**Comment by markerikson** [comment]
N ot 100% sure I fully understand what you mean by "cancel" in this context.  FWIW, the listener middleware intentionally _cannot_ cancel or stop actions from being processed, by design.  It can only _respond_ to actions.

If you want to cancel actions and prevent them from being processed by the reducers or other middleware, you'll need to write a custom middleware that inspects them and conditionally does _not_ call `next(action)`.

**Comment by loctary** [comment]
@markerikson yeah this could work if there woudn't be any logic inside those actions. I have actions with chain calls and I need not only to skip fulfilled/rejected actions, but actually abort them so they are not running and dispathing any more actions.

**Comment by markerikson** [comment]
@loctary : just to check, are you referring to "thunk" functions as "actions"?  If so, you can't abort or pause a thunk - it's just a function that will continue to execute.

**Comment by loctary** [comment]
Yes, I want to abort executing thunk just like [I can do in component with a promise ](https://redux-toolkit.js.org/api/createAsyncThunk#canceling-while-running)

**Comment by markerikson** [comment]
Yeah, you definitely _can't_ do that from the listener middleware, and it would be extremely difficult to do that even with a custom middleware.
