### ISSUE TITLE
isFetching is false on first render when refetchOnMountOrArgChange is true

### ISSUE THREAD

**Issue by pavelspichonak** [reduxjs/redux-toolkit#3071]
We use a hook like this:

```
const {
    data,
    isLoading,
    isFetching,
  } = useNewsQuery(newsId, {
    refetchOnMountOrArgChange: true,
  });
```
When we go to news page this hook gets news from backend. After that we go to another page and then go to news page again. Because we use `refetchOnMountOrArgChange: true` we expect that `isFetching` will be `true` but it is `false` on first render and then it becomes `true`. Looks like it is a bug.

**Comment by pavelspichonak** [comment]
We use useLayoutEffect like this:

```
useLayoutEffect(() =>, {
    if (!isFetching) {
      // some logic
    }
  }, [isFetching]);
```
and because on first render is `isFetching` is false our logic inside `if` is executed. But we would like to execute it only after data is refetched, in other words we expect that on first render `isFetching` is `true`, we get data and `isFetching` becomes `false`.

**Comment by markerikson** [comment]
This seems like a badly written effect condition to me.

On the very first render, `isFetching` _will_ be false, because it _hasn't_ started a fetch yet.  The fetch always gets kicked off in a `useEffect` _after_ the first render.

You'd need to rewrite this effect to have significantly different logic that only runs when the state has _changed_.

**Comment by pavelspichonak** [comment]
@markerikson if we use hook without `refetchOnMountOrArgChange: true` and there is no cache, on the first render `isFetching` is `true`. It is strange that it is `false` when `refetchOnMountOrArgChange: true`.

But anyway thanks for you answer.

**Comment by phryneas** [comment]
Yes, that is a convenience optimization, but as soon as you do other things like writing a custom `selectFromResults` option, that convenience optimization would also go away.

I see how it would be convenient in this case as well, but I believe it cannot easily be added.

**Comment by pavelspichonak** [comment]
@phryneas I see, thanks for explanation.
