### ISSUE TITLE
`preferCacheValue` couldn't get the types correctly

### ISSUE THREAD

**Issue by bryantobing12** [reduxjs/redux-toolkit#3072]
I have seen this discussion and believe that this has already resolved within the new version of rtk query

but as of my use, i still don't get the types correctly

![image](https://user-images.githubusercontent.com/46083126/211525580-786d6fd1-2db5-49f2-aa95-a45052ebb8de.png)

I thought because i'm not using the latest version

but i have upgraded my rtk query to the latest version, also i have updated my typescript to the latest version as well.

and still don't get the types of preferCacheValue correctly in the second argument of the trigger lazyQuery

```json
{
  "@reduxjs/toolkit": "^1.9.1",
  "typescript": "^4.9.4"
}
```

this is my tsconfig

```json
{
  "extends": "@tsconfig/react-native/tsconfig.json",
  "compilerOptions": {
    "incremental": true,
    "skipLibCheck": true,
    "baseUrl": "./src",
    "paths": {
      "@assets": ["assets"]
    }
  },
  "exclude": ["appium"]
}

```

Note: The functionality of works though, only the types that doesn't work

**Comment by phryneas** [comment]
You just put `true` or `false` in there, not an object.

**Comment by phryneas** [comment]
Yes. TypeScript is very explicit that the second argument should only be `boolean` and not an object with a boolean inside.
