### ISSUE TITLE
[TS] createAsyncThunk extra typings

### ISSUE THREAD

**Issue by tyv** [reduxjs/redux-toolkit#3076]
I am creating async thunk according to https://redux-toolkit.js.org/api/createAsyncThunk#payloadcreator
and it seems that `extra` typing does not work for me, am I missing something? 

<img width="1023" alt="Screenshot 2023-01-11 at 14 44 27" src="https://user-images.githubusercontent.com/122360/211824268-94a5ba45-1083-4f8b-af16-44ffad5ea5b9.png">

**Comment by phryneas** [comment]
You wrote exrta, not extra.

11 Jan 2023 14:56:52 Yuri Tkachenko ***@***.***>:

**Comment by tyv** [comment]
omg... 🤦🏻‍♂️ thanks
