### ISSUE TITLE
how can I execute two query at the same time ?

### ISSUE THREAD

**Issue by shop-fluencer** [reduxjs/redux-toolkit#3079]
Hello,

title says

```
  const { data, isLoading, isFetching } = useGetUsers({user_id});

  const { data: dataProf, isLoading: isLoadingProf } = useGetProfessor({user_id});
```

**Comment by markerikson** [comment]
What you've got there looks correct - is something not working the way you expect it to?

**Comment by shop-fluencer** [comment]
> What you've got there looks correct - is something not working the way you expect it to?

rtk query executes all queries parallel ? Nothing is wrong but I was thinking the second query executes after the first

**Comment by markerikson** [comment]
Each query is independent and separate, so yes, they'll both be kicked off in separate `useEffect` calls as soon as the first render is done.
