### ISSUE TITLE
Undo/ Redo

### ISSUE THREAD

**Issue by rjdlee** [reduxjs/redux-toolkit#308]
Hey, I was wondering if you guys have a recommended way for implementing undo/redo in RTK. `redux-undo` is incompatible and it looks like we can't use `immer` patches because createReducer doesn't use the `produce` function.

**Comment by markerikson** [comment]
Why would `redux-undo` be incompatible with RTK?

**Comment by rjdlee** [comment]
It might just be the Typescript definitions, but if I wrap my reducer with undoable in createSlice, I get a type error.

**Comment by phryneas** [comment]
Which type error?

**Comment by rjdlee** [comment]
```
// Looks like I need to re-call produce if I want to mutate state
addLane: undoable<MyState, PayloadAction<MyObject>>(produce((state, action) => {
        state[ action.payload.id ] = action.payload;
})),
```

Error:
```
Error:(16, 9) TS2322: Type 'Reducer<StateWithHistory<MyState>, AnyAction>' is not assignable to type 'CaseReducer<MyState, { payload: any; type: string; }> | CaseReducerWithPrepare<MyState, { payload: any; type: string; }>'.
  Type 'Reducer<StateWithHistory<MyState>, AnyAction>' is not assignable to type 'CaseReducer<MyState, { payload: any; type: string; }>'.
    Types of parameters 'state' and 'state' are incompatible.
      Type '{ [x: string]: { id: { bytes: { [x: number]: number; BYTES_PER_ELEMENT: number; buffer: { byteLength: number; slice: (begin: number, end?: number) => ArrayBuffer; } | { byteLength: number; length: number; slice: (begin: number, end?: number) => SharedArrayBuffer; }; ... 27 more ...; includes: (searchElement: numb...' is missing the following properties from type 'StateWithHistory<MyState>': past, present, future
```

**Comment by rjdlee** [comment]
Oh.. Now I understand. I have to wrap my initialState type with StateWithHistory.
```
createSlice({
    initialSlice: {} as StateWithHistory<MyState>,
    name: 'mySlice',
    reducers: {
        addLane: undoable<MyState, PayloadAction<MyObject>>(produce((state, action) => {
             state[ action.payload.id ] = action.payload;
        })),
    }
});

**Comment by satheshrgs** [comment]
@rjdlee Could you please provide a example for redux-undo with RTK. I am stuck with the same problem..!

**Comment by msutkowski** [comment]
@satheshrgs I added redux-undo to the official RTK TS template as a quick example - https://codesandbox.io/s/rtk-redux-undo-example-titr4. Hopefully, that helps you out. If you need any further assistance, try #redux on the Reactiflux Discord as there are many users that actively monitor that channel.

**Comment by satheshrgs** [comment]
I was stuck with the type errors. But managed to find a way to ignore type errors as mentioned in the official docs.
Thanks for your help..!!

**Comment by mjsokolo** [comment]
> @satheshrgs I added redux-undo to the official RTK TS template as a quick example - https://codesandbox.io/s/rtk-redux-undo-example-titr4. Hopefully, that helps you out. If you need any further assistance, try #redux on the Reactiflux Discord as there are many users that actively monitor that channel.

The non-TypsScript version of createSlice leads to TypeErrors - is there a way around this?

**Comment by phryneas** [comment]
With that amount of information nobody will be able to even try to help you. What non-TS-code? What errors?

**Comment by mjsokolo** [comment]
I am seeing ```TypeErrors``` when using ```UseSelector```. For example, with the slice defined below, ```const id = useSelector((state) => state.blocks.activeId)``` will be `undefined`:

**store.js:**
```
import { configureStore } from '@reduxjs/toolkit';
import blocksReducer from '../features/blocks/BlocksSlice';
import undoable from 'redux-undo';

export default configureStore({
  reducer: {
    blocks: undoable(blocksReducer),
  },
});
```
**BlocksSlice.js:**
```
import { createSlice } from '@reduxjs/toolkit';

export const BlocksSlice = createSlice({
  name: 'blocks',
  initialState: {
    activeId: 'id1',
  },
  reducers: {
    // Text Updates
    updateId: (state, action) => {
      state.activeId = action.payload;
    },
  },
});

export const {
  updateId,
} = BlocksSlice.actions;
export default BlocksSlice.reducer;
```

**Comment by phryneas** [comment]
According to the typings of react-undo, that should now be `state.blocks.present.activeId`

https://github.com/omnidan/redux-undo/blob/1eb3192fb04dbceb146be76f705f73ffdcf39d83/typings.d.ts#L4-L12

**Comment by mjsokolo** [comment]
Thank you! I missed the typings

**Comment by thidasapankaja** [comment]
> Thank you! I missed the typings

@mjsokolo how did you got it fixed

**Comment by mjsokolo** [comment]
@thidasapankaja 
Instead of `state.blocks.activeId` I used `state.blocks.present.activeId`.

**Comment by thidasapankaja** [comment]
> @thidasapankaja
> Instead of `state.blocks.activeId` I used `state.blocks.present.activeId`.

Thank you. But I'm having an issue with the reducers

 ```
  reducers: {
    onChange: (state, { payload }: PayloadAction<TreeStructure[] | []>) => {
      state.tree = payload;
    },
  },,
```

Here with the `state.tree` I'm getting this error

`Property 'tree' does not exist on type 'WritableDraft<StateWithHistory<ViewBuilderState>>'.ts(2339)
`

**Comment by zoubingwu** [comment]
@phryneas @markerikson sorry for bothering but any ideas on why adding middleware options in `configureStore` call will cause undoable error?

I forked the example repo here: https://codesandbox.io/s/jolly-feather-c4f4uh?file=/src/app/store.ts

The undoable will have a typing error like below:

```ts
Type 'Reducer<StateWithHistory<CounterState>, AnyAction>' is not assignable to type 'Reducer<unknown, AnyAction>'.
  Types of parameters 'state' and 'state' are incompatible.
    Type 'unknown' is not assignable to type 'StateWithHistory<CounterState> | undefined'.ts(2322)
```

ts code:

```ts
export const store = configureStore({
  reducer: {
    counter: undoable(counterReducer),
    globals: globalReducer
  },
  // remove middleware option will fix ts error on undoable
  middleware: (getDefaultMiddleware) => {
    const middlewares = getDefaultMiddleware({
      serializableCheck: false
    });
    return middlewares.prepend(listenerMiddleware.middleware);
  }
});
```

**Comment by markerikson** [comment]
@zoubingwu : I think that's a semi-known issue with RTK and TS somehow.  Try moving the `undoable` call out to be a separate line of code, like `const finalCounterReducer = undoable(counterReducer)`.

**Comment by chenhebing** [comment]
> @zoubingwu : I think that's a semi-known issue with RTK and TS somehow. Try moving the `undoable` call out to be a separate line of code, like `const finalCounterReducer = undoable(counterReducer)`.

A reducer created with @reduxjs/toolkit@2.2.6 and redux-undo@1.1.0 gets a reducer of type unkown.

![image](https://github.com/reduxjs/redux-toolkit/assets/12512045/ef88bcac-7bfa-4fa5-8252-e9c3c6aba7f5)

```typescript
import { configureStore, createEntityAdapter, createSlice } from '@reduxjs/toolkit';
import undoable from 'redux-undo';

export interface IFileNav {
  id: string;
  path: string;
}

const fileNavAdapter = createEntityAdapter<IFileNav>();

const fileNavSlice = createSlice({
  name: 'file_nav',
  initialState: fileNavAdapter.getInitialState(),
  reducers: {
    add: fileNavAdapter.addMany,
    remove: fileNavAdapter.removeMany,
  },
});

export const fileNavSelector = fileNavAdapter.getSelectors<RootState>(state => state.fileNav.present);
export const fileNavActions = fileNavSlice.actions;
export const fileNavReducer = undoable(fileNavSlice.reducer);

export const store = configureStore({
  reducer: {
    file: fileNavReducer,
  },
});

(window as any).store = store;

export type AppStore = typeof store;
export type RootState = ReturnType<AppStore['getState']>;
export type AppDispatch = AppStore['dispatch'];

```

**Comment by EskiMojo14** [comment]
for what it's worth, I've created a new library for working with undoable state, which is designed to compliment RTK: [history-adapter](https://eskimojo14.github.io/history-adapter/).

It won't ever be part of RTK itself, but it should feel fairly familiar for people used to working with `createEntityAdapter`, for example.

```ts
import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { createHistoryAdapter } from "history-adapter/redux";

interface CounterState {
  value: number;
}

const counterAdapter = createHistoryAdapter({ limit: 5 });

const { selectPresent, ...historySelectors } = counterAdapter.getSelectors();

const initialState = counterAdapter.getInitialState<CounterState>({ value: 0 });

export const counterSlice = createSlice({
  name: "counter",
  initialState,
  reducers: {
    incrementedBy: counterAdapter.undoableReducer(
      (state, action: PayloadAction<number>) => {
        state.value += action.payload;
      }
    ),
    undone: counterAdapter.undo,
    redone: counterAdapter.redo,
    pauseToggled(state) {
      state.paused = !state.paused;
    },
    historyCleared: counterAdapter.clearHistory,
    reset: () => initialState,
  },
  selectors: {
    ...historySelectors,
    selectCount: (state) => selectPresent(state).value,
  },
});

export const {
  incrementedBy,
  undone,
  redone,
  pauseToggled,
  historyCleared,
  reset,
} = counterSlice.actions;

export const { selectCount, selectCanUndo, selectCanRedo, selectPaused } =
  counterSlice.selectors;
```
