### ISSUE TITLE
‘responseHandler‘ argument  in  fetchBaseQuery doesn't work

### ISSUE THREAD

**Issue by york-chen** [reduxjs/redux-toolkit#3080]
export const markAPi = createApi({
    reducerPath: 'test',
    baseQuery: fetchBaseQuery({
        baseUrl: 'https://api.xingquzu.com/api',
        prepareHeaders: (headers, { getState }) => {
            // By default, if we have a token in the store, let's use that for authenticated requests
            const token = (getState() as AppState).index.count
            if (token) {
                headers.set('authorization', `Bearer ${token}`)
            }
            return headers
        },
        responseHandler(response) {
            debugger
            return Promise.reject()
            return response.text()
        },
        validateStatus:(response, body)=> {
            return response.status === 200 && !body.isError
        },
        timeout:60*1000
    }),
....

that is my code

but i read your origin code ,i thought that i found some problems,

export function fetchBaseQuery({
  baseUrl,
  prepareHeaders = (x) => x,
  fetchFn = defaultFetchFn,
  paramsSerializer,
  isJsonContentType = defaultIsJsonContentType,
  jsonContentType = 'application/json',
  timeout: defaultTimeout,
  validateStatus: globalValidateStatus,
  ...baseFetchOptions
}: FetchBaseQueryArgs = {}): BaseQueryFn<
  string | FetchArgs,
  unknown,
  FetchBaseQueryError,
  {},
  FetchBaseQueryMeta
> {
  if (typeof fetch === 'undefined' && fetchFn === defaultFetchFn) {
    console.warn(
      'Warning: `fetch` is not available. Please supply a custom `fetchFn` property to use `fetchBaseQuery` on SSR environments.'
    )
  }
  return async (arg, api) => {
    const { signal, getState, extra, endpoint, forced, type } = api
    let meta: FetchBaseQueryMeta | undefined
    let {
      url,
      method = 'GET' as const,
      headers = new Headers(baseFetchOptions.headers),
      body = undefined,
      params = undefined,
      responseHandler = 'json' as const,
      validateStatus = globalValidateStatus ?? defaultValidateStatus,
      timeout = defaultTimeout,
      ...rest
    } = typeof arg == 'string' ? { url: arg } : arg
    let config: RequestInit = {
      ...baseFetchOptions,
      method,
      signal,
      body,
      ...rest,
    }

the variable ‘responseHandler ’，it's value is depend on arg of function ,will not get from baseFetchOptions which is come from fetchBaseQuery

**Comment by york-chen** [comment]
my purpose is to handle the exceptions in one place

**Comment by phryneas** [comment]
Can you please make this whole issue readable?
