### ISSUE TITLE
how can I change all cached from one endpoint query data by specific id

### ISSUE THREAD

**Issue by shop-fluencer** [reduxjs/redux-toolkit#3082]
I have a problem.

I fetch data with 2 parameters.

user_id and movie_channel

so a user has multiple movie channels like 1,2 or 3.

I fetch now a query with this params:

user_id: 1, movie_channel: 1

obj:
```
return {
   user: {
     user_id: 1,
     username: 'assa',
     is_follow: false
   },
   movie_channel: 1,
   movies: []
}
```

then I get a list of movies from this channel and you get users information.

So anyone select now movie_channel 2, then I fetch again and get the obj with different movies.

in the header he can follow a person. (he is current now in movie channel 2)

he can now change the movie_channel to 1 and then I get the cached data. But now user is not followed because he followed in the channel 2. the cache shows the old obj.

how can I change all cached data where only the param is user_id ? 

```
    useGetProfileData: builder.query<IProfilePageData, { user_id: number; movie_channel?: number; }>({
      query: (data) => ({
        url: '/profile_data',
        method: 'POST',
        body: data
      }),
    }),

    followUser: builder.mutation<void, { user_id: number; follower_id: number; movie_channel?: number; }>({
      query: (data) => ({
        url: '/follow_user',
        method: 'POST',
        body: data
      }),
      async onQueryStarted({ user_id, follower_id, movie_channel }, { dispatch, queryFulfilled }){

        const patchResult = dispatch(
          ProfileApi.util.updateQueryData('useGetProfileData', { user_id, movie_channel  }, (draft) => {
            return {
              ...draft,
              user: {
                ...draft.user,
                is_follow: !draft.user.is_follow
              }
            }
          })
        );

        try {
          await queryFulfilled;
        } catch {
          patchResult.undo();
        }
      }
    }),
```

**Comment by phryneas** [comment]
You can use granular tags for that - take a look at [this StackOverflow answer](https://stackoverflow.com/a/69938861/2075944)

**Comment by shop-fluencer** [comment]
> You can use granular tags for that - take a look at [this StackOverflow answer](https://stackoverflow.com/a/69938861/2075944)

Thats for endpoint. But I mean for one endpoint that has many cache data. Like:

{ user_id: 1, movie_channel: 1 } has cache data and { user_id: 1, movie_channel: 2 } has also cache data, if I update the second then the first does not update

**Comment by phryneas** [comment]
If you have 20 cache entries for one endpoint, that will give you 20 entries with all the arguments for all those cache entries so you can change them.

All that said, generally you probably should use invalidateTags to refetch data from the server instead of doing manual optimistic updates in 100 different places.

**Comment by shop-fluencer** [comment]
> If you have 20 cache entries for one endpoint, that will give you 20 entries with all the arguments for all those cache entries so you can change them.
> 
> All that said, generally you probably should use invalidateTags to refetch data from the server instead of doing manual optimistic updates in 100 different places.

okey I understand thank you very much!
