### ISSUE TITLE
[RTK Query] Retain data on mutation error 

### ISSUE THREAD

**Issue by ovidius72** [reduxjs/redux-toolkit#3083]
Hi, I was wondering If RTK Query preserve data on errors.
E.g. I send a POST Request with a mutation and get back some data. If I send again the same POST request and get an error this time the data in undefined and not available anymore.
Is this a default feature for mutations ? I'm pretty sure data is preserved for queries. 
Thanks.

**Comment by phryneas** [comment]
Queries are shared by cache key - if you use the same argument key twice, they are the same "cache value".

But if you send the same mutation twice, e.g. "pay 20$", they will have different results and so they do not share cache entries. They are completely separate.

**Comment by ovidius72** [comment]
@phryneas  Thanks. I've managed to solve my use case using extraReducers to preserve the last successful response.
