### ISSUE TITLE
React redux TS - Cannot find name 'store'. Did you mean 'Storage'?

### ISSUE THREAD

**Issue by JimmyK1995** [reduxjs/redux-toolkit#3085]
Hey everyone, I am converting my current RTK project to Typescript, but am getting an error on my store: 

export type RootState = ReturnType<typeof store.getState>
export type AppDispatch = typeof store.dispatch
export const useAppDispatch: () => AppDispatch = useDispatch // Export a hook that can be reused to resolve types

The error I get is: 
`Cannot find name 'store'. Did you mean 'Storage'?`

Anyone knows why?

**Comment by markerikson** [comment]
Can't offer any advice without seeing the actual code.  But, this is a usage question, and we try to keep the issues focused on bugs and feature requests.  I'd suggest asking in the `#redux` channel in the Reactiflux Discord ( https://www.reactiflux.com ).

**Comment by phryneas** [comment]
Generally I would assume that you are not doing this in the file where you defined the variable `store` (by writing `const store = configureStore(...)`.
