### ISSUE TITLE
Media types of the content field is not compliant with RFC 6838

### ISSUE THREAD

**Issue by winstonphones** [reduxjs/redux-toolkit#3096]
Hello,
The RTKQ repository (https://github.com/rtk-incubator/oazapfts) does not allow (new) issues. 
However, it is used and forked by RTKQ. Hence, I send this issue in this repository.

We have a similar issue as : https://github.com/reduxjs/redux-toolkit/issues/2015

**Issue:** 
When generating a RTKQ API client from an OpenAPI (swagger) schema (i.e. openapi.json) it generates an unknown type. It is because it only accepts a 5 media / content types. 

**Expected:**
According the [OpenApi Swagger schema](https://swagger.io/docs/specification/media-types/) the content field should be compliant with [RFC 6838] https://datatracker.ietf.org/doc/html/rfc6838).

i.e. our content type is: application/vnd.xxx.yy.v1.response+json. However it should also accept other content types conform RFC 6838.

**Proposed Solution:**
I see you [use the function getSchemaFromContent](https://github.com/reduxjs/redux-toolkit/blob/master/packages/rtk-query-codegen-openapi/src/generate.ts)line 279 from the repository [@rtk-query/oazapfts-patched ](https://github.com/rtk-incubator/oazapfts) 

In the function [getSchemaFromContent](https://github.com/rtk-incubator/oazapfts/blob/master/src/codegen/generate.ts) line 548, from the repository @rtk-query/oazapfts-patched, i see that there is a hardcode list of only  5 accepted content types

Please make the function getSchemaFromContent to accept content types confirm RFC6838 or use a regex. 
If needed I can also make a pull request. In the repo (https://github.com/rtk-incubator/oazapfts)

**Reproduce the issue:**
Convert the next openapi.json file, via npx @rtk-query/codegen-openapi   xxx.
The first generated type is unknown (application/vnd.mycompany.myapp.v2+json), but the second type is correctly generated because it uses one of the 5 content types (application/json).

~~~
{
    "openapi": "3.0.1",
    "info": {
        "title": "bar",
        "description": "foo",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "https://dev.example.com",
            "description": "Generated server url"
        }
    ],
    "paths": {
        "/generatesUnknownType": {
            "post": {
                "tags": [
                    "synchronization-controller"
                ],
                "operationId": "generates-unknown-type",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/vnd.mycompany.myapp.v2+json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ValueColumnFilter"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/generatesKnownType": {
            "post": {
                "tags": [
                    "synchronization-controller"
                ],
                "operationId": "generates-known-Type",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ValueColumnFilter"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "ValueColumnFilter": {
                "type": "object",
                "properties": {
                    "columnName": {
                        "type": "string"
                    },
                    "values": {
                        "uniqueItems": true,
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "description": "bar",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}
~~~

**Comment by phryneas** [comment]
Our oazapfts repo is just a clone of the upstream repo that has pulled in some PRs that exist upstream because they had not been merged for a while. We do not maintain it actively apart from that and do not plan on adding new features on our side.

Please open PRs upstream and once they are merged in, open an issue so can we bump the version on our side (preferably going back to the original oazapfts without needing patches on our side).

**Comment by winstonphones** [comment]
Ok, I will make a PR in de upstream repo.

**Comment by winstonphones** [comment]
Hi @phryneas,

I checked out the upstream project and I see they already fixed the media type issue. it's because they are using a regex at the moment.

In your last message you indicate I should open an issue when it is fixed. I propose we continue in this issue, ok? 
Subsequently, can you update  the RTKQ generator (@rtk-query/codegen-openapi) with the latest upstream code (of [oazapfts/oazapfts](https://github.com/oazapfts/oazapfts)).

**Reproduce:**
You can check that the content type is correctly generated / fixed and reproduce it as follow:

• Check out the latest code of the [upstream repo oazapfts/oazapfts](https://github.com/oazapfts/oazapfts),  
• Over write the content of the file “demo/petstore.json” with the code from my first message, there referred to as openapi.json.
• run: `npm run generate-demo`
• You can see in the generated file “demo/api.ts” that twice a “fetchJson” is generated. Instead of one time a wrongly “fetchBlob” and one time a “fetchJson”
