### ISSUE TITLE
selectedInvalidatedByApi not works

### ISSUE THREAD

**Issue by shop-fluencer** [reduxjs/redux-toolkit#3098]
Hello,

I want to get all my data from my endpoint but I didnt see anything. I dont even see my console.log(endpointName)

What I am doing wrong ?

```
    followUserInProfile: builder.mutation<void, { user_id: number; follower_id: number; shop_id?: number; }>({
      query: (data) => ({
        url: '/follow_user',
        method: 'POST',
        body: data
      }),
      async onQueryStarted({ user_id, follower_id, shop_id, ...patch }, { dispatch, queryFulfilled, getState }) {
        for (const { endpointName, originalArgs } of ProductsApi.util.selectInvalidatedBy(getState(), [{ type: "PRODUCTS", id: user_id}])) { 
          // we only want to update `getPosts` here
   
          console.log(endpointName + 'END');
          const pd = dispatch(
            ProductsApi.util.updateQueryData('productBy', originalArgs, (draft) => {
                console.log(draft);
            })
          )

        }

        try {
          await queryFulfilled
        } catch(error) {
          console.log(error)
        }

      },
    }),
```

I also get a typescript error on getState() 

```
Argument of type 'RootState<any, any, "ProfileApi">' is not assignable to parameter of type 'RootState<{ productsDropdown: QueryDefinition<{ user_id: number; }, BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, "PRODUCTS", IProduct[], "ProductsApi">; productBy: QueryDefinition<...>; createPaket: MutationDefinition<...>; followUser: MutationDefinition<...>; }, string, "Pr...'.
  Property 'ProductsApi' is missing in type 'RootState<any, any, "ProfileApi">' but required in type 'RootState<{ productsDropdown: QueryDefinition<{ user_id: number; }, BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, "PRODUCTS", IProduct[], "ProductsApi">; productBy: QueryDefinition<...>; createPaket: MutationDefinition<...>; followUser: MutationDefinition<...>; }, string, "Pr...
```

**Comment by markerikson** [comment]
Can you put together a CodeSandbox or a repo that actually shows this happening?  We don't know what your code looks like from that snippet, including the TS setup and API creation.

**Comment by shop-fluencer** [comment]
> Can you put together a CodeSandbox or a repo that actually shows this happening? We don't know what your code looks like from that snippet, including the TS setup and API creation.

I solved it, 
I want to get the a state from ProductsApi but I am using this function in ProfileApi, but there is a other thing.

ProductsApi.util.selectInvalidatedBy(getState(), [{ type: "PRODUCTS", id: user_id}]))

I am on ProfileApi not on ProductsApi, so how can I get now the state of ProfileApi?

that I ProfileApi.state instead of getState() ?

**Comment by markerikson** [comment]
@shop-fluencer : there's only _one_ root state, and that's what `getState()` returns.

Like I said, I don't know what you're really trying to do here, and it's hard to provide suggestions without seeing the actual code.

**Comment by shop-fluencer** [comment]
> @shop-fluencer : there's only _one_ root state, and that's what `getState()` returns.
> 
> Like I said, I don't know what you're really trying to do here, and it's hard to provide suggestions without seeing the actual code.

I want to make optimistic UI and want change the state maybe update the state or delete. But I have to update it on different apis.

I have ProfileApi and ProductsApi. both in other files. 

I want to do this:

```
 const patchResult = dispatch(
          ProductsApi.util.updateQueryData('productBy', { user_id }, (draft) => {
            console.log(draft);
            return {
              ...draft,
              user: {
                ...draft.user,
                is_follow: !draft.user.is_follow
              }
            }
          })
        );
```

Update an state but this is for a specific one for with a specific cachte data. I want select all cached data and change all cached data that exists with selectInvalidatedBy.

So if I am on ProfileApi now and I use action FollowUser function

then this not work because the getState function returns the state from the current API. I am on ProfileApi right now, but I have to select the ProductsApi. So how can I select the ProductsApi state instead of getState()
```
 async onQueryStarted({ user_id, follower_id, shop_id, ...patch }, { dispatch, queryFulfilled, getState }) {
        for (const { endpointName, originalArgs } of ProductsApi.util.selectInvalidatedBy(getState(), [{ type: "PRODUCTS", id: user_id}])) { 
          // we only want to update `getPosts` here
```

**Comment by markerikson** [comment]
> the getState function returns the state from the current API

@shop-fluencer like I said, that's _not_ how Redux works. `getState()` _always_ returns the _entire_ root state.  _If_ you added two different APIs, you should have added both of them to the store setup.  Also, you should have given both of them a different `reducerPath` field.

That said, is there a reason why you have two _different_ APIs created?  You should normally only have _one_ in the entire app:

- https://redux-toolkit.js.org/rtk-query/api/createApi

**Comment by shop-fluencer** [comment]
> > the getState function returns the state from the current API
> 
> @shop-fluencer like I said, that's _not_ how Redux works. `getState()` _always_ returns the _entire_ root state. _If_ you added two different APIs, you should have added both of them to the store setup. Also, you should have given both of them a different `reducerPath` field.
> 
> That said, is there a reason why you have two _different_ APIs created? You should normally only have _one_ in the entire app:
> 
> * https://redux-toolkit.js.org/rtk-query/api/createApi

Oh, I think I had to do for each screen a api like this:

-store
--apis
---productApi.ts
----selectProducts, createProducts, changeProducts
---profileApi.ts
----getProfileData, changeProfileData
---shopApi.ts
---blogsApi.ts

I made it like this. So this is wrong ? I only should have one Api file where all apis are should there ?

**Comment by markerikson** [comment]
Yeah. _only_ do one API, and put all the endpoints in there.

**Comment by shop-fluencer** [comment]
> Yeah. _only_ do one API, and put all the endpoints in there.

Puhh I am very relived and thankful I had do it wrong so it was so complexity for me but now it should feel better and easier for me to do it with only one Api. thanks

**Comment by markerikson** [comment]
Yep!
