### ISSUE TITLE
Provide minimal RTK query custom SSR example

### ISSUE THREAD

**Issue by Ibadichan** [reduxjs/redux-toolkit#3100]
Hi! I want to migrate to RTK query from thunks in my react project.
Our project uses custom SSR solution (no next.js).
I am using this approach to preload the data on server:

```js
// route config
const Pricing = {
  path: pricingPath(),
  element: <Page />,
  prepareData(store, appState) {
    return store.dispatch(fetchPrices({
      query: {
        currency: appState.userCurrency,
      },
    }));
  },
};

// and then on server side i "prepare" the data before "renderToString":
await prepareData(globalStore, appState);

// using in the component:
const prices = useSelector((state) => state.prices);
```

How can i implement SSR with RTK query? Please extend the docs:
https://redux-toolkit.js.org/rtk-query/usage/server-side-rendering

Thank you very much.

**Comment by phryneas** [comment]
As you say: you use a custom SSR solution. There are millions of possibilities for how to implement something like that - so we cannot possibly know how you have to implement it. We don't have experience with that.

That said, there are some pointers on that docs site.

If you have more concrete questions than "please extend the docs", we can maybe help ☹️

**Comment by Ibadichan** [comment]
1) Next.js example uses this approach:
https://github.com/phryneas/ssr-experiments/blob/main/nextjs-blog/pages/pokemon/ssr/%5Bname%5D.tsx#L15
Does next.js automatically "unsubscribe" from query or it is not needed on server side?
https://redux-toolkit.js.org/rtk-query/usage/usage-without-react-hooks#removing-a-subscription

2) Can we "await" only dispatched thunk or it is needed to call:
`await Promise.all(dispatch(api.util.getRunningQueriesThunk()))`?

3) Next.js example also uses `extractRehydrationInfo ` option.
If we follow redux SSR guide can we omit this option and just pass preloaded state to client (according to the docs)?
https://redux.js.org/usage/server-rendering#inject-initial-component-html-and-state

Thanks.

**Comment by Ibadichan** [comment]
Can you provide a very basic react + rtk query ssr example? (without react-router)

**Comment by phryneas** [comment]
No, since none of us ever did that.
Even if we did, there is a 98% chance it won't apply to you. Frameworkless SSR is the wild west.


> Does next.js automatically "unsubscribe" from query or it is not needed on server side?
Next creates a new Redux store on each render and throws the old one away. There is no need to unsubscribe in that case, although calling `resetApiState` can make sense to clear up running timers.

> Can we "await" only dispatched thunk or it is needed to call:
> await Promise.all(dispatch(api.util.getRunningQueriesThunk()))?

You can, but I would recommend the latter

> Next.js example also uses extractRehydrationInfo option.
> If we follow redux SSR guide can we omit this option and just pass preloaded state to client (according to the docs)?

You have to use `extractRehydrationInfo ` as that removes "too much" information that would otherwise make you run into stale data on the client.

**Comment by Ibadichan** [comment]
So, as i understand, the common steps on server side are:
1) Dispatch needed actions:
```js
store.dispatch(api.endpoints.getPokemonByName.initiate(name))
```
2) Wait for each query to finish using:
```js
await Promise.all(dispatch(api.util.getRunningQueriesThunk()))
```
3) After getting the state reset the timers:
```js
const initialState = store.getState();
store.dispatch(api.util.resetApiState());
```
4) The `extractRehydrationInfo` option. I use `preloadedState` option with data from server to "setup" client redux store once. So there are no differences between client and server states, because client state is always empty. Can we omit the `extractRehydrationInfo ` option or it is still needed? 

thanks.

**Comment by phryneas** [comment]
That should be it, yes.

**Comment by Ibadichan** [comment]
Ok, so if `extractRehydrationInfo` config is not needed i am closing the issue. Thanks.

**Comment by phryneas** [comment]
I'm sorry, I misread your 4.

`extractRehydrationInfo` is 100% definitely required.

Otherwise, you recreate component subscriptions that exist on the server on the client - where they do not exist. The client cannot unsubscribe them and the cache values will never be cache-collected, even if no actual component ever uses them.

**Comment by Ibadichan** [comment]
Ok. Can you extend this example please? (or without using `redux-persist` as many developers do not use it)
https://redux-toolkit.js.org/rtk-query/usage/persistence-and-rehydration#redux-persist

**Comment by phryneas** [comment]
Yes, directly after store creation on the client is fine.

**Comment by Ibadichan** [comment]
Oh, thank you very very much.
