### ISSUE TITLE
How keepUnusedDataFor works ?

### ISSUE THREAD

**Issue by shop-fluencer** [reduxjs/redux-toolkit#3103]
Hello,

I fetch a lot and I dont want it to save it in cache, because its consuming storage. So when I use KeepUnusedDataFor and set it to 0, then its not in the cache ? Or what can I do to prevent the caching ?

**Comment by markerikson** [comment]
RTKQ _will_ keep data in cache as long as there are active subscriptions to that data - that's the entire purpose:

- https://redux-toolkit.js.org/rtk-query/usage/cache-behavior#default-cache-behavior

The short answer here is, "don't worry about this".  RTKQ will manage the cache data for you, and remove it when no part of your app needs that data any more.

**Comment by markerikson** [comment]
@shop-fluencer : yes, use https://redux-toolkit.js.org/rtk-query/usage/cache-behavior#encouraging-re-fetching-with-refetchonmountorargchange
