### ISSUE TITLE
Connection between devtools and browser's new-tab page

### ISSUE THREAD

**Issue by rezuan-riyad** [reduxjs/redux-toolkit#3111]
I am developing a chrome browser extension where I need to manipulate new tab page. I am using redux-toolkit for state management.
Default configuration for store is resulting undefined state in devtools or showing the previous state that might be connected from another project.
Is there any way to make connection between new-tab page and devtools with redux-toolkit?

**Comment by phryneas** [comment]
There are some pages where the browser guards against such interaction, I believe the "new tab" page is one of them.
