### ISSUE TITLE
Add a better example of writing an RTKQ `queryFn`

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#3113]
The RTKQ `queryFn` option is meant for making arbitrary async calls instead of calling through `baseQuery`.  This is most commonly used for making requests with a user-provided async function or an external SDK, like Supabase or Firebase.

However, the "Customizing Queries" page ( https://redux-toolkit.js.org/rtk-query/usage/customizing-queries ) doesn't show any examples along those lines.  It talks about the arguments, and shows an example with `Math.random()`, and then later at the bottom it shows a couple other examples, but they don't feel like they cover the most common use case, along the lines of:

```ts
createApi({
  baseQuery,
  endpoints: (build) => ({
    myCustomEndpoint: build.query({
      queryFn: async (someId) => {
        const result = someAsyncMethod(id);
        return {data: result};
      }
    })
  })
})
```

We should add a couple examples like this, ideally one with a user-provided method, and one with a real third-party SDK.

**Comment by jonra1993** [comment]
Hello, @markerikson does queryFn cache response?

**Comment by markerikson** [comment]
@jonra1993 : Yes, it's exactly the same caching behavior as always - the only difference is that you're manually writing the async code to do the fetching, instead of RTKQ doing all that internally for you.
