### ISSUE TITLE
Bug: Middleware not added correctly anymore since 1.9.0

### ISSUE THREAD

**Issue by dbartholomae** [reduxjs/redux-toolkit#3118]
Hi there!

I'm currently updating a project from version 1.8.6 to 1.9.0, and tests that were working before are failing now with the message:

> Warning: Middleware for RTK-Query API at reducerPath "automations" has not been added to the store.
> You must add the middleware for RTK-Query to function correctly!

The current setup creates 7 different apis instead of enhancing 1, and I think that this might have to do with the problem, but since the errors did not show up with 1.8.6, I thought that I should at least open an issue to let you know.

**Comment by phryneas** [comment]
Without a reproduction of this, it is pretty much impossible to comment on.

Do you create a new store on each test?

**Comment by dbartholomae** [comment]
I've just finished using one api instead of multiple, and the problem persists, so it seems to be something else.

> Without a reproduction of this, it is pretty much impossible to comment on.
I'll look into it more - just wanted to ask in case it immediately rings a bell due to knowing that the bug was introduced in `1.9.0`. But if this doesn't ring a bell, then I'll research a bit and come back with more info and ideally a reproducing repo.

> Do you create a new store on each test?
Yes.

**Comment by phryneas** [comment]
That error message really can only come up if your store does not have the middleware in place. Could you share how you create that test store?

**Comment by markerikson** [comment]
We did change the mechanism for determining if the middleware and reducer have been added correctly, but we do have a number of tests around that behavior.  So yeah, we'd really need to see how you're setting up your store.

**Comment by dbartholomae** [comment]
Here are the code snippets. They are strewn about the codebase, but I'll try to get a small reproducing repo out of it over the next days. If something already stands out to you, please let me know. I've ordered them in order they are called.

```ts
    const component = render(
      withRedux(
        <AccountView
          account={{ name: "AccountName", partner: {} } as Account}
          updateAccount={jest.fn()}
        ></AccountView>,
      ),
    );
```

```ts
  const renderWithContextAndStore = (children: React.ReactElement) => {
    const store = createMockStore();
    return render(
      <Provider store={store}>{children}</Provider>,
    );
  };
```

```ts
export const createMockStore = () => {
  return configureStore({
    reducer: rootReducer,
    preloadedState: {},
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    // eslint-disable-next-line
    middleware: (getDefaultMiddleware) => {
      return getDefaultMiddleware().concat(...middlewares);
    },
  });
};
```

```ts
export const middlewares = [
  flashMessages,
  crudRequests,
  feeTypesMiddleware,
  rtkQueryErrorLogger,
  rtkQuerySuccessLogger,
  ...authenticationMiddlewares,
  ...campaignsMiddlewares,
  ...accountMiddlewares,
  ...integrationsMiddleware,
  ...serviceMiddlewares,
];
```

```ts
export const services = [
  accountNotesApi,
  accountsApi,
  automationsService,
  campaignsApi,
  contractsApi,
  debtorsApi,
  downloadPrivateFileService,
  logisticProvidersApi,
  operationsApi,
  postageProductsApi,
  postageProvidersApi,
  pricingApi,
  testAccountsApi,
  vouchersApi,
  currenciesApi,
  premiumAddressProductApi,
  authApi,
];

export const serviceMiddlewares = services.map((a) => a.middleware);
```

```ts
export const currenciesApi = createApi({
  reducerPath: "currencies",
  baseQuery: fetchBaseQuery({
    baseUrl: `${API_HOST}`,
    credentials: "include",
  }),
  tagTypes: ["Currency"],
  endpoints: (builder) => ({
    getAll: builder.query<Currency[], void>({
      query: () => "currencies",
      transformResponse: (res: CurrencyListResponse) => {
        return res.currencies;
      },
    }),
  }),
});
```
(other apis are all defined similarly)

**Comment by dbartholomae** [comment]
And here's the [minimal reproducing example](https://codesandbox.io/s/dawn-tdd-zjo2t3?file=/src/App.tsx).

It has nothing to do with one or multiple middlewares, but somehow the interaction with other async middlewares:
```
const emptyMiddleware: Middleware = () => (next) => async (action) => {
  return next(action);
};
const middlewares = [emptyMiddleware, api.middleware];
```
If I remove the `async` in the middleware definition, the bug disappears.
Might also be that this violating the contract for middleware - but at least TypeScript says that the last function is `(action: any) => any`, which would include `(action: any) => Promise<any>`.

**Comment by phryneas** [comment]
That `async` keyword there makes the whole chain of all middlewares async, since each middleware returns the promise of the next one.

Where before `dispatch(something)` could be a normal value, it now is *always* a promise. And that causes a problem in our bug - since we assume that `dispatch(api.internalActions.internal_probeSubscription(...))` returns a normal value.

=> I'm sorry, but you will need to find a different way of writing that async middleware :/

**Comment by dbartholomae** [comment]
My workaround for now is to have the api middleware first, before any async middleware.
But is this an intended limitation for middleware? If not, I'm also happy to have a look into the current implementation and maybe raise a PR to help.

**Comment by dbartholomae** [comment]
If that is intended, it might make sense to add it to the documentation of Redux, or maybe even the types.

**Comment by phryneas** [comment]
There is no "intended" or "not intended" - it's in the nature of chained middleware, not only for Redux but everywhere that concept is used.

Any middleware can return whatever it wants, potentially modifying (or omitting) return values of later middlewares. That's part of the middleware contract. And you deliberately write code that changes that return value.

Take a look at redux-thunk:

```js
// yes, this is essentially a full implementation of redux-thunk
const thunkMw = api => next => action => typeof action == "function" ? action(api.dispatch, api.getState) : next(action)
```

If the dispatched action is a function, execute it and return the return value of the function. Otherwise, return the return value of the next middleware.

Now, the middleware you have written is equivalent to
```js
const asyncMw = api => next => action => Promise.resolve(next(action))
```

It just changes the return value of whatever comes later in the queue.

**Comment by phryneas** [comment]
This can also not really be reflected in the types - it is perfectly reasonable to have a middleware that returns a promise. Maybe sometimes, maybe always - in the "always" case the user should just be aware of what it does and where to put it in the middleware chain.

Given that we do not really recommend writing custom middleware in most cases, I'm not sure where to best document that, but it is certainly a pitfall. If you have an idea where it would go best in the docs, a PR would be welcome. (I guess somewhere in the Redux docs where middleware are introduced?)

**Comment by dbartholomae** [comment]
Maybe it belongs in the documentation for redux query api middleware then to make these assumptions explicit?

**Comment by phryneas** [comment]
RTK Query has nothing to do with it. Your async middlewares also break guaranteed redux-thunk behaviour and pretty much every other middleware that relies on `return`.

Another example of one such middleware would be
```js
// missing return
const breakingMw = api => next => action => { next(action) }
```

or

```js
// not calling `next`
const breakingMw = api => next => action => 5
```

In the end: if you write a middleware that changes the return value, you run the risk of breaking things. But it is really not RTKQ-specific.

**Comment by dbartholomae** [comment]
hmm, ok - I would hope that there are some rules that users of redux can follow to make sure that the middleware they write works with official redux middleware like thunk or rtk query, and that these rules would be documented somewhere.

**Comment by markerikson** [comment]
Yeah, we don't have a specific docs page that discusses "how to write a custom middleware" atm.

**Comment by dbartholomae** [comment]
Based on the discussion I would now close this issue and open a related one concerning documentation on the redux repo - does that makes sense?

**Comment by markerikson** [comment]
Yep, sounds good!
