### ISSUE TITLE
RTKQ useQuery hook does not refetch data after ```resetApiState()``` call

### ISSUE THREAD

**Issue by emcol** [reduxjs/redux-toolkit#3119]
The issue is likely a bug in RTKQ and should have been fixed by #1735, although it does not seem so.

I provide a minimal example that showcase the issue in isolation and I share the codebase [here](https://codesandbox.io/p/github/emcol/test-app/master?file=README.md&workspace=%257B%2522activeFilepath%2522%253A%2522README.md%2522%252C%2522openFiles%2522%253A%255B%2522README.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clg4ryw0h000x3b6ly4xppetr%2522%253A%257B%2522key%2522%253A%2522clg4ryw0h000x3b6ly4xppetr%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clg4s4qqi000x3b6lbc207pvk%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clg4s5cvr007v3b6l0bcmtqnz%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522clg4s5ard005a3b6lb59wzl0x%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clg4ryw0h000x3b6ly4xppetr%2522%252C%2522spacesOrder%2522%253A%255B%2522clg4ryw0h000x3b6ly4xppetr%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

### Below the steps to riproduce the bug:

- Run dev server;
- Notice that data is properly fetched;
- Click on reset button;

### Expected results:

Data is correctly re-fetched after the API reset, the useQuery first returns a loading status and then fulfills causing the component to be re-rendered since it is subscribed to the endpoint.

### Actual result:

The page gets stuck in a data loading state and useQuery hook does not fulfill blocking the user flow.

**Comment by trvbr** [comment]
The `useLazyQuery` hack worked for me, too. However, it would have involved a lot of code changes to update every request in my app, so I took a different approach.

First, I added a common tag to each endpoint. I used `Main` in this example, but you can use anything.

```js
export const exampleApi = createApi({
  // (...other API options here...)
  tagTypes: ['Main'],
  endpoints: (builder) => ({
    getThing: builder.query({
      query: (id) => `things/${id}`,
      providesTags: ['Main'],
    }),
    // (...other API endpoints here...)
  })
})
```

Then, I used `invalidateTags()` like this:

```js
dispatch(exampleApi.util.invalidateTags(['Main']))
```

**Comment by phryneas** [comment]
Unfortunately we didn't get to this in time (really sorry!) and the reproduction is gone. Could you please add another reproduction?

**Comment by emcol** [comment]
> Unfortunately we didn't get to this in time (really sorry!) and the reproduction is gone. Could you please add another reproduction?

Thank you very much for replying, the preview link should be updated now.

**Comment by emcol** [comment]
> The `useLazyQuery` hack worked for me, too. However, it would have involved a lot of code changes to update every request in my app, so I took a different approach that might work for others who are running into this bug.
> 
> First, I added a common tag to each endpoint. I used `Main` in this example, but you can use anything.
> 
> ```js
> export const exampleApi = createApi({
>   // (...other API options here...)
>   tagTypes: ['Main'],
>   endpoints: (builder) => ({
>     getThing: builder.query({
>       query: (id) => `things/${id}`,
>       providesTags: ['Main'],
>     }),
>     // (...other API endpoints here...)
>   })
> })
> ```
> 
> Then, I used `invalidateTags()` like this:
> 
> ```js
> dispatch(exampleApi.util.invalidateTags(['Main']))
> ```

Thanks for the reply. I have already implemented a workaround like this but I didn't expect it to be necessary.

I expected the application to work even if the slice is reset and the component to request the data again, since they are necessary for rendering. That's why I opened an issue here.

**Comment by phryneas** [comment]
After some investigation, I think this is because of our new `batchActions` approach - it seems we forgot to reset this internal state on the `resetApiState` action.

**Comment by phryneas** [comment]
Could you please test the [CI build](https://ci.codesandbox.io/status/reduxjs/redux-toolkit/pr/3333) from #3333? I just tested it in the repro and to me it seems to fix the problem.

**Comment by emcol** [comment]
I've just tested, I confirm that #3333 solves this issue. I have also updated again my [preview app](https://codesandbox.io/p/github/emcol/test-app/master?file=README.md&workspace=%257B%2522activeFilepath%2522%253A%2522README.md%2522%252C%2522openFiles%2522%253A%255B%2522README.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clg4ryw0h000x3b6ly4xppetr%2522%253A%257B%2522key%2522%253A%2522clg4ryw0h000x3b6ly4xppetr%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clg6kb1em000x3b6l3rpiald3%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clg6kb76500893b6lteymluwx%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522clg6kb4fb00343b6lwjj6avas%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clg4ryw0h000x3b6ly4xppetr%2522%252C%2522spacesOrder%2522%253A%255B%2522clg4ryw0h000x3b6ly4xppetr%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D) and seems to work, thank you again! 🤗
