### ISSUE TITLE
unused property responseHandler in get request method

### ISSUE THREAD

**Issue by arnurkuatov** [reduxjs/redux-toolkit#3121]
Hi!
I want to download file from backend server, and wrote get request method, here example: 
```
getReportsRetailDocument: build.query<Blob, void>({
      query: () => ({
        url: `${REPORTS}/managers/excel`,
        method: 'get',
        responseType: 'blob',
        responseHandler: async (response: {
          blob: () => Blob | MediaSource | PromiseLike<Blob | MediaSource>
        }) =>
          window.location.assign(
            window.URL.createObjectURL(await response.blob()),
          ),
        params: {
          office_ids: ['9709283c-c78d-4133-979f-bf7f6c96c4ae'],
        },
      }),
    }),
```
![image](https://user-images.githubusercontent.com/35806911/214676628-285b75aa-6be7-4ae0-b469-949f1eb17bd7.png)

So, as you can see at 66 line I got unused property :/
Can you help me to fix this problem

**Comment by phryneas** [comment]
Does it actually not execute the responseHandler or is this just your IDE? 
By the way, which IDE is this?

**Comment by markerikson** [comment]
Looks very much like a JetBrains IDE from that screenshot.

**Comment by arnurkuatov** [comment]
I'm sorry I forgot to mention the name of the IDE, but it's a jeJetBrains product (webstorm),
yes, for some reason this property is not executed and I even tried to pass the response arguments to another function

**Comment by arnurkuatov** [comment]
My IDE does not tell me that there is such a method, I don't think this method exists.
![image](https://user-images.githubusercontent.com/35806911/214771151-ea0e2b06-361a-4128-9cf5-878f6f48fda8.png)

**Comment by phryneas** [comment]
Your code is perfectly valid, as you can see [in this TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAcgAJQKYBMCuAPAVgZwHoYIIAbAa2BgQChRJY4BvOAYzQEMZUBBMYABo4AM1Qw2ACwBCnfKgCKmVFACewgGLipvKAHN8cAL6ioEEIhQYcBYqUrVC6YPhiEAjsrV1aHVNz4BAApmWjg4ACM5RS9VAC5RbRlopRVVIIBKQTC4VAA7dEhgPJh8BIjMYDJ0OABeAD44EJzwvXEAJVRGUs6YTiqAEQg2TBB8mHLK6oA6TzSAHmkyCAjhADcIYHR65vC9uDm1BMy6xt39vcwoMgSAA0IQTjzONqgiVGw2VDJb7Iu9sYwSQQdAJBBtGh-f5wND4SB5eQAFVUYFQYIiywiCCh-1h8PkAAknugyCoEnJVHk2E08RAEWiWC1oRiVscMqc4EsVnAAD5wACyGGAnAAyhArl9eXAAApmEAuVAAGWAFFQi0xUsFzlF4qgX3qTP2RnZDUNFwA7sV0BBzdNlmxuMA6dM5PhgHo8kEzf9LQUbdMAKrtRXTPwBADyEVwqDYMCDiqCnHN-XgtPp0xZEUyWW9exz0LgYE4UE4IDKjIL4QgIhEwC+AH0tuWANoIACcAHYAAxtgBMAA4AMxsAC0bA7-fQI4ALABGQeDkedtsiEcREQdkQANjYbZ3084qAQAF0cRcjGfwsaz9ecsbaPffHTXHAeK4EloJJJdAY6hW4FcNxwPcjzPK87yfN8vw5ICwKgogELYjkhCEHAkgqKgcCqOK7BPHA8iYUC3DAWmSIoqgtxwC4cCcLGmCcGQZCqHA5pmHkejTDkpGoMiqLopiSHhNxRIFKSUDkvglLUkE3EJKE+yZmyHJchEmpCjqEqYXysrmAqyqquq3J8lqwpippBpXiaFl7L61q2vajrOq67qematn+vGoZcDwkbRrG8aJsm1AwqgcLPqgGaYtmZ75oWxaluW8l7NWtYNk2CStp2PYDsOY4TlOc4LkuHYrmuG7bru+6HieUIXg+QA).

What is *not* valid though is `responseType`.

My guess here is that WebStorm does what it can do best: not support TypeScript. Honestly, I could go off on a 3-hour-rant about all the WebStorm bug reports we have gotten in the past. Bottom line is: WebStorm does not use the original TypeScript compuler for many of it's error messages, and apparently for the syntax highlighting. They have their own algorithm that is "faster", but in many many cases just plain wrong. I can't really do anything besides suggest that you change over to an IDE that actually integrates with TypeScript - like VSCode or even vim.

**Comment by arnurkuatov** [comment]
In fact, changing the editor does not change anything, since when running the code in the VSCode, it also did not execute

**and I was digging in the library here, and I did not find the type of responder handler**
![image](https://user-images.githubusercontent.com/35806911/214820984-fb00c31c-964e-4cad-828c-2685db8f8805.png)

**Comment by phryneas** [comment]
`reponseHandler` is a `fetchBaseQuery` option. 
If you use a custom `baseQuery`, you will have to pass in completely different options - the ones you would pass into your `baseQuery`.

**Comment by arnurkuatov** [comment]
Okay, I understand, thanks for the info!

But, can you tell me how to catch this responsehandler method or download a file from the server through this request

**Comment by phryneas** [comment]
You completely swapped out the core request-making mechanism of RTK Query for your own. All I can say is read the axios manual since that seems to be what you are using.

Or, as I said before: drop axios and use `fetchBaseQuery`. You gain nothing from this, apart from extra bundle size.

Also: if you want to trigger a download (as in the user gets a download dialog), you probably should not use RTK Query for that at all - RTK Query is there to keep data in memory so your components can access it. If you download a 50-mb-file, you probably don't want to keep that in memory.

**Comment by arnurkuatov** [comment]
Ok, I heard you. thanks again for your help.
