### ISSUE TITLE
InvalidatesTags not working

### ISSUE THREAD

**Issue by bylly1** [reduxjs/redux-toolkit#3127]
I want to refetch the payload when a new post is created, but `invalidatesTags` not working and I don't know where is the problem.... maybe someone can help me to solve it. Here is my code:

```js
# api.ts
const api = createApi({
 baseQuery: baseQueryWithReauth,
    endpoints: () => ({}),
});

#store.ts
const rootReducer = combineReducers({
    [api.reducerPath]: api.reducer,
});
const store = configureStore({
    reducer: persistedReducer,
    devTools: process.env.NODE_ENV !== 'production',
    middleware: getDefaultMiddleware => getDefaultMiddleware({
        serializableCheck: {
            ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER]
        }
    }).concat(api.middleware)
});

# postApi.ts
const enhancedApi = api.enhanceEndpoints({
    addTagTypes: ["Post"]
});

const postApi = enhancedApi.injectEndpoints({
 endpoints: (builder) => ({
   getPosts: builder.query<PostProps[], string | undefined>({
     query: (params) => ({
         url: `${ENDOPOINT}/${params}/feed`,
         method: "GET"
     }),
     providesTags: (result, error, args) =>
       result
          ? [...result.map(({ _id }) => ({    # i'm using mongodb as databse the `id` is `_id` as type `ObjectId`
              type: "Post" as const, id: _id })),
              { type: "Post", id: "LIST" }
             ]
          : [{ type: "Post", id: "LIST" }]
   }),
   createPost: builder.mutation<PostProps, Omit<PostProps, '_id'>>({
     query: (data) => ({
        url: `${ENDOPOINT}/${data.entity}/create`,
        method: "POST",
        body: data
     }),
     invalidatesTags: ['Post'],
   })
 }),
 overrideExisting: false
})
```
I don t know what i'm doing wrong...

**Comment by phryneas** [comment]
So you're saying that you have a component with a `useGetPostsQuery()` call and after you trigger the mutation, it's not refreshing?  
Have you taken a look at the network tab to see if another request to the feed is being made?

**Comment by bylly1** [comment]
> So you're saying that you have a component with a `useGetPostsQuery()` call and after you trigger the mutation, it's not refreshing? Have you taken a look at the network tab to see if another request to the feed is being made?

After the createPost mutation no other request is made

**Comment by bylly1** [comment]
> So you're saying that you have a component with a `useGetPostsQuery()` call and after you trigger the mutation, it's not refreshing? Have you taken a look at the network tab to see if another request to the feed is being made?

After the `createPost` mutation the request to the feed is made, I receive the new payload, but the post card is not updating.

**Comment by phryneas** [comment]
So how are you using this in your component?

**Comment by bylly1** [comment]
> So how are you using this in your component?

I found the problem. it s seems that the problem is not on RTK Query, but to the Lexical.js framework... After the `feed` is refetch ing again the Lexical is not changing his state and keeps the last post content. Thank you for helping me.
