### ISSUE TITLE
Do RTK query hooks run during "render" phase?

### ISSUE THREAD

**Issue by Ibadichan** [reduxjs/redux-toolkit#3140]
Hi. Thanks for the library!
https://redux-toolkit.js.org/rtk-query/usage/conditional-fetching#overview
>Query hooks automatically begin fetching data as soon as the component is mounted.

But why when i print the result of hook calling it returns:
```
{
  status: 'pending',
  isUninitialized: false,
  isLoading: true,
  isSuccess: false,
  isError: false,
  data: undefined,
  currentData: undefined,
  isFetching: true,
  refetch: [Function: refetch]
}
```
The `isUninitialized ` option is always `false`. 
So, do rtk query hooks run API request during render phase or the requests are sent in `useEffect`?
Thank you.

**Comment by phryneas** [comment]
`isUninitialized` is `false` during first render if you do not use `skip` or `selectFromResult` as a convenience for users so they don't have to handle an additional state. In reality, the request starts in a `useEffect` after render.

**Comment by Ibadichan** [comment]
Ok, sorry for the misunderstanding, thanks!
