### ISSUE TITLE
`InitialState` changes are not being reflected in the app

### ISSUE THREAD

**Issue by enrickdaltro** [reduxjs/redux-toolkit#3144]
Hello everyone! 

I'm facing this issue where if I add or remove a field in one of my slices initialState, that's not reflected in the app until I kill and reopen the app again (if the reducer is being persisted, I have to uninstall and install the app again). 

This only happens if the device already has a previous version of the app (i.e.: The device has version 1.0.0 installed and I added new state fields to my slice in the 1.0.1 version).

The bigger problem is that all of our users that have the previous version installed will have to kill and reopen that app at least once to see the new changes, which can lead to a bad user experience.

Is there anything that I couldn't find on issues or docs?  I also can provide screenshots or recordings.

**Environment**
```
"react-native": "~0.69.7"
"@reduxjs/toolkit": "^1.9.0-rc.0"
"react-redux": "^8.0.5"
"redux-persist": "^6.0.0"
```

**Comment by markerikson** [comment]
What do you mean by "add or remove a field in `InitialState`"?  Are you talking about making changes at runtime?  Mutating a literal variable named `initialState`?  Changing the definition of `InitialState` and then publishing a new build of the application?

My first guess is that this is most likely because you're persisting data and you need to write "migrations" to adjust the persisted data to match the new schema:

https://github.com/rt2zz/redux-persist#migrations

**Comment by phryneas** [comment]
That is kinda the point of `initialState`: it is used as the **initial** state the application starts with and then never looked at again. If you want to change a Redux state, you need to dispatch an action and trigger a state change in a reducer.

**Comment by enrickdaltro** [comment]
@markerikson @phryneas Thanks for the quick reply! Let me explain again to see if I can explain what I meant.

1. I have a perfectly running app with redux configured(Assuming all redux configuration works as the app is already in production). The app is installed in my iOS Simulator.
2. I have to add a feature in this app, which will take me to update our `example slice file`, after adding a couple of state fields and reducers functions to make the new feature work, this is how my initial state was and how it became:

Before
```
....
initialState: {
  time: [],
  expense: []
}
....
```

After
```
Before
....
initialState: {
  time: [],
  expense: [],
  unsyncedTimeActions: [],
  unsyncedExpenseActions: []
}
....
```

3. Now, I want to test my changes so I run the app in the iOS simulator. (Note that I already installed the app with the **before** code).
4. Once the app runs, I check my Reactotron devtools and notice that the `initialState` object of the slice I updated shows the **before** setup instead of the **after** setup. This means that the new code I just added to that example slice is not reflected in the app.
5. To fix that, I have 2 options: 1. If my slice is being persisted, I have to uninstall and run (install) the app again to see the changes. 2. If it's not being persisted, I just have to kill it and open the app again.

We plan to send a new app version with new features that updates a major slice of our app, but when installing the app from Testflight, having the previous version already installed, we are facing this problem where the new redux code is not being applied unless we do the steps mentioned above. (I added this slice reducer to the `persistReducer` blacklist, but the problem still occurs, I just have to kill the app instead of uninstalling it).

I'll definitely check the migrations you guys suggested, but in the meantime, I hope this makes more sense.

**Comment by PrakharDhyani** [comment]
@enrickdaltro hey buddy receiving the same error , can u tell me what do u mean by killing the app everytime to resolve this issue or like is your problem has been solved or not..?

**Comment by deniscole80** [comment]
You can store the previous

> @markerikson @phryneas Thanks for the quick reply! Let me explain again to see if I can explain what I meant.
> 
> 1. I have a perfectly running app with redux configured(Assuming all redux configuration works as the app is already in production). The app is installed in my iOS Simulator.
> 2. I have to add a feature in this app, which will take me to update our `example slice file`, after adding a couple of state fields and reducers functions to make the new feature work, this is how my initial state was and how it became:
> 
> Before
> 
> ```
> ....
> initialState: {
>   time: [],
>   expense: []
> }
> ....
> ```
> 
> After
> 
> ```
> Before
> ....
> initialState: {
>   time: [],
>   expense: [],
>   unsyncedTimeActions: [],
>   unsyncedExpenseActions: []
> }
> ....
> ```
> 
> 3. Now, I want to test my changes so I run the app in the iOS simulator. (Note that I already installed the app with the **before** code).
> 4. Once the app runs, I check my Reactotron devtools and notice that the `initialState` object of the slice I updated shows the **before** setup instead of the **after** setup. This means that the new code I just added to that example slice is not reflected in the app.
> 5. To fix that, I have 2 options: 1. If my slice is being persisted, I have to uninstall and run (install) the app again to see the changes. 2. If it's not being persisted, I just have to kill it and open the app again.
> 
> We plan to send a new app version with new features that updates a major slice of our app, but when installing the app from Testflight, having the previous version already installed, we are facing this problem where the new redux code is not being applied unless we do the steps mentioned above. (I added this slice reducer to the `persistReducer` blacklist, but the problem still occurs, I just have to kill the app instead of uninstalling it).
> 
> I'll definitely check the migrations you guys suggested, but in the meantime, I hope this makes more sense.

You can store the previous and new states in a json file on disk, whenever you rollout a new update to your user, then start the state from the json file.

**Comment by phryneas** [comment]
> You can store the previous and new states in a json file on disk, whenever you rollout a new update to your user, then start the state from the json file.


Please just use migrations as suggested - those are the tool meant for the job.

**Comment by markerikson** [comment]
Sounds like this is a persistence issue, so closing.
