### ISSUE TITLE
weird initialState of redux-toolkit in next js 13

### ISSUE THREAD

**Issue by vishalkumar2806** [reduxjs/redux-toolkit#3154]
i tried everything as per tutorial and connect my next js 13 with the provider with redux-toolkit but Im getting weird state not the state I defined. My code is exactly like the counter tutorial on react redux documentation. Anyone solution I was expecting a state with a counter variable with a value of zero.
![issue](https://user-images.githubusercontent.com/84777038/216563958-b75dc2d0-6cc0-4cfb-91bd-de2af20eb687.PNG)

**Comment by phryneas** [comment]
Take a look at the dropdown in the top right. That is not the internal state of the web site you are building, but the internal state of some "Freee Gift Card Generator" - maybe another tab you have open or a browser plugin that injected itself into your site?

**Comment by vishalkumar2806** [comment]
Yeah thats im building and its correct

**Comment by phryneas** [comment]
Still, have you checked that dropdown if there are any other stores in there that could actually be your Redux store that you are building? There can sometimes be multiple stores on one page, often accidentally.

**Comment by vishalkumar2806** [comment]
you can come to my desktop and fix this thing by yourself

**Comment by phryneas** [comment]
Did you accidentally import the wrong reducer in your store setup? Possibly from `@nextjs/client/components/reducer` or a similar place?

Please share your store setup file here, including imports.

**Comment by markerikson** [comment]
Yeah, that specifically looks like https://github.com/vercel/next.js/blob/4e2267ff61bcee74c26f16ec7675bf29338af141/packages/next/src/client/components/router-reducer/reducers/refresh-reducer.ts#L37 .

That tells me what you're looking at is definitely _not_ your own application code somehow.

**Comment by vishalkumar2806** [comment]
tree directory 
![directory tree](https://user-images.githubusercontent.com/84777038/216667738-6327b872-2fb1-484d-9475-63414ed2f262.PNG)
store.tcx
![store](https://user-images.githubusercontent.com/84777038/216667814-9ebe72af-66fa-417f-9bf5-057f4e3325b7.PNG)
counterReducer.tcx 
![counterslice](https://user-images.githubusercontent.com/84777038/216667902-bcb513f9-03a6-49a6-bc5e-182a797242f7.PNG)

**Comment by markerikson** [comment]
Store setup seems fine. Honestly, this just looks like the DevTools are somehow showing something that's not part of your app, and that's not an issue with RTK itself.

I'd double-check to see if there are any other options listed in the "Instances" dropdown menu.

**Comment by vishalkumar2806** [comment]
okie thankx

**Comment by vishalkumar2806** [comment]
![1](https://user-images.githubusercontent.com/84777038/216675413-fa9e9899-1d85-4f35-978d-7bd4c8eed4de.PNG)
yes you are correct its showing me the state of next-router now but my instance is not showing when I click the dropdown menu

**Comment by mxswat** [comment]
![image](https://user-images.githubusercontent.com/17874432/216701449-b6e5d0d1-9fe8-44a6-8c43-bcfb7e70c2e0.png)

I'm having the same issue; it's showing me the next router state

**Comment by markerikson** [comment]
Folks, whatever's going on here is not actually a Redux Toolkit problem specifically.  If anything, it's a Redux DevTools problem.

Your best bet is to file an issue in the Redux DevTools repo, with an app repo that demonstrates this problem happening.

**Comment by markerikson** [comment]
Short update: Looking at https://github.com/vercel/next.js/commits/canary/packages/next/src/client/components/router-reducer/reducers/refresh-reducer.ts , it does look like the Next folks have been working on this file recently. I've asked them if they made any recent changes that might be affecting the DevTools.

**Comment by markerikson** [comment]
Update: confirmed that this is a Next bug. They tried to wrap `useReducer` to talk to the Redux DevTools, but hardcoded the `instanceId`:

https://github.com/vercel/next.js/blob/0d7f7653e81a4f2aa16be7ead286e09b22761f52/packages/next/src/client/components/use-reducer-with-devtools.ts#LL144-L149C6

I've passed along a suggestion to have them fix that and call the Redux DevTools `connect()` method correctly.
