### ISSUE TITLE
Called `injectEndpoints` to override already-existing endpointName

### ISSUE THREAD

**Issue by devoren** [reduxjs/redux-toolkit#3157]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/99968085/217229777-45a3aa10-af95-46eb-a839-036f63157602.png">

I'm using RTK Query with React Native and I've split the main API with injectEndpoints. I have this problem when i set overrideExisting false (DEV mode)

**Comment by phryneas** [comment]
That is probably due to hot module reloading reloading the file when you apply changes to it.

You could try adding 
```js
overrideExisting: module.hot?.status() === "apply"
```
to the `injectEndpoints` call.

**Comment by devoren** [comment]
@phryneas Wow thanks for the quick response! The error is showing when I open the app for the first time and then if I change something the error is not shown

**Comment by phryneas** [comment]
The error occurs if you call `.injectEndpoints` for the same endpoint name multiple times. I can't tell how that happens in your specific situation.

**Comment by devoren** [comment]
I am calling useLoginMutation when I click a button. I don't have endpoints where I call inside useEffect or multiple times

Api: 
```
const baseUrl = API.HOST;

const baseQuery = fetchBaseQuery({
	baseUrl: baseUrl, 
       ...
});

export const api = createApi({
	reducerPath: 'api',
	baseQuery,
	tagTypes: ['User'],
	endpoints: () => ({}),
});
```

Inject endpoints: 

```
const userApi = api.injectEndpoints({
	endpoints: (builder) => ({
		login: builder.mutation<AuthResponse & ErrorResponse, LoginRequest>({
			query: (body) => ({
				url: ENDPOINTS.USERS.LOGIN,
				method: 'POST',
				body,
			}),
		}),
		signup: builder.mutation<AuthResponse, SignupRequest>({
			query: (body) => ({
				url: ENDPOINTS.USERS.SIGNUP,
				method: 'POST',
				body,
			}),
		}),
		...
	}),
	 // @ts-ignore
	overrideExisting: module.hot?.status() === "apply",
});
```
How i call it
```
const onLogin = () => {
        login(req)
		.unwrap()
		.then((data) => {
			console.log(data)
		});
	}
```

**Comment by devoren** [comment]
> That is probably due to hot module reloading reloading the file when you apply changes to it.
> 
> You could try adding
> 
> ```js
> overrideExisting: module.hot?.status() === "apply"
> ```
> 
> to the `injectEndpoints` call.

It helps, but I don't know if it works correctly and doesn't have any side effects in release mode.

**Comment by devoren** [comment]
I don't know how but the problem disappeared without this solution
> That is probably due to hot module reloading reloading the file when you apply changes to it.
> 
> You could try adding
> 
> ```js
> overrideExisting: module.hot?.status() === "apply"
> ```
> 
> to the `injectEndpoints` call.

**Comment by Ashfak-Hossain** [comment]
```ts
overrideExisting: module.hot?.status() === "apply"
```
With this typescript, the error

- `Property 'hot' does not exist on type 'NodeModule'.ts(2339)`

I solved it bt utilizing the module as any
```ts
overrideExisting: (module as any).hot?.status() === 'apply',
```

**Comment by onesmusmuna** [comment]
Hello Guys,
By adding `overrideExisting: true` worked for me

**Comment by memresahin** [comment]
> overrideExisting: module.hot?.status() === "apply"
> With this typescript, the error
> 
> * `Property 'hot' does not exist on type 'NodeModule'.ts(2339)`
> 
> I solved it bt utilizing the module as any
> 
> overrideExisting: (module as any).hot?.status() === 'apply',

How can I do it in react native?
