### ISSUE TITLE
Updating to react-scripts v5 from v4 with RTK breaks the app 

### ISSUE THREAD

**Issue by russ0133** [reduxjs/redux-toolkit#3159]
After updating to react-scripts v5, my application breaks and starts throwing errors **unless I remove RTK (basically remove the Provider):**

```
Uncaught TypeError: Cannot read properties of undefined (reading 'BlogCard')
    at Module.BlogCard (index.jsx:17:1)
    at Module.BlogCard (index.tsx:79:1)
    at registerExportsForReactRefresh (RefreshUtils.js:158:1)
    at Object.executeRuntime (RefreshUtils.js:193:1)
    at $ReactRefreshModuleRuntime$ (index.ts:1:1)
    at ./src/shared/index.ts (index.ts:1:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/card/index.jsx (index.tsx:7:1)
```

Module.BlogCard and ./src/card/index.jsx are basically empty components returning a div with "hello" for testing. And src/shared/index.ts whole code is export * from "./ui";

If I completely delete "BlogCard", I'll continue receiving the same error but it jumps to another component.

I have already:
Deleted node_modules and package-lock.json and installed again.
Created a fresh create-react-app and copied my src folder into the new one.

It seems to be something odd with webpack v5 and RTK/Redux/RTK-Query? I've also tried not updating react-scripts, just making a new app and updating webpack directly, with no success.

My Store and application is quite big so it would be almost impossible to share code here, we're using RTK for state management and RTK-Query for fetching.

**Comment by phryneas** [comment]
I'm sorry, but this seems to be some kind of problem with your bundling process, probably an import circle that was accidentally correctly resolved before and is now being bundled in another order that doesn't work any more. I don't believe this has anything to do with RTK.

**Comment by russ0133** [comment]
@phryneas At first I thought it was a problem with webpack and I have made an issue there too, but since finding that disabling RTK/redux removes the problem, I thought it might be a problem with RTK/redux.

What do you mean by import cycle? I've been crazy looking into that. It's also possible it's a problem with my code.

**Comment by phryneas** [comment]
I mean that you have two or more files that import in a "circle" from each other.

`store.js` imports `reducer.js`, `reducer.js` imports `component.js`, `component.js` imports `store.js`.

Now, there is no right way of determining which one to execute first, because each of them would have to be executed before all others.
Importing `store.js` first might work, but if your bundler suddenly decides to `import component.js` first, things might fail.

=> You have a bug in there that worked randomly, but will not work reliably.

**Comment by markerikson** [comment]
Yeah. This has to be a build issue, not related to RTK itself.
