### ISSUE TITLE
Issues with `store.dispatch` types and `createAsyncThunk` after upgrading to 1.9.2

### ISSUE THREAD

**Issue by mq2thez** [reduxjs/redux-toolkit#3163]
Hello friends,

I'm working on upgrading our codebase from `@reduxjs/toolkit@1.8.2` to `1.9.2` and I've run into a bit of an issue with deriving `dispatch` types.

The error in question is here:
```
Argument of type 'AsyncThunkAction<unknown, unknown, ThunkAPIConfig>' is not assignable to parameter of type 'AnyAction'.
  Property 'type' is missing in type 'AsyncThunkAction<unknown, unknown, ThunkAPIConfig>' but required in type 'AnyAction'.ts(2345)
```

A lot of other posts related to this referenced (mis)using `middleware`, and we _do_ have middleware, so I spent a while trying to figure out what was going wrong with those and fixing the types per the recommendations in the docs (using the `Middleware` type, etc).

However, in my attempts to generate a minimal reproduction case, I actually wound up with this:
```
import { configureStore } from "@reduxjs/toolkit";

const store = configureStore({
    reducer: () => "hello",
    preloadedState: "yes",
});

// RTK 1.8.2: type DispatchType = ThunkDispatch<string, undefined, AnyAction> & Dispatch<AnyAction>
// RTK 1.9.2: type DispatchType = Dispatch<AnyAction>
type DispatchType = typeof store.dispatch;
```

Of particular note, we're using TypeScript 4.5.4. I'm pretty okay with the answer to this being "upgrade to a newer version of TypeScript", but wanted to call out that this was an issue since the 1.9.0 release notes still specify compatibility down to TS 4.2.

**Comment by phryneas** [comment]
I just tried it [in this playground](https://www.typescriptlang.org/play?ts=4.5.5#code/JYWwDg9gTgLgBAbzgYwgOwGbAOYFcoCmAyjNAXAL5wZQQhwBEAAoQCa4AeAVgM4D0pCABsA1sBgMA3AFgAUHNRoe8ZWTgBeFOix5CJMgAoEcuKbhtcyAlABccAwEoNAPkYALAkKEQGAGhNmYITeAIasBKwkITAEdgwAngQ8fnIUDjLysnx8cABKACoA0nAAjAB0ABxlAEx2MPFg5AAiwDxg0chu+Q3kmvluuGgiLW0dbgA8ylDAaNi+cIPhWGgR8wCCaPFryDDA6K4AZHAj7TCd4xtbO3toznLZeUWlZQCcNXU9x62nnd2NGl9RmcJpdtrt9nJ6v8TmM-r04FCCBAMHBVIQyqxvmMMg8zHj8QTCUS4AA9AD8QA) with TS 4.5.5 and it works perfectly fine.
![image](https://user-images.githubusercontent.com/4282439/217824554-22ccea55-f8fa-409a-9b99-019f6f891150.png)
There must be something else going on on your end.

**Comment by mq2thez** [comment]
Oof, good to know. Guess I'll keep hunting. Thanks!

**Comment by mq2thez** [comment]
Note in case anyone else runs into this and finds this thread: the issue was that our `yarn.lock` settings were causing `node_modules/@reduxjs/toolkit` to have its own version of Redux, `node_modules/@reduxjs/toolkit/node_modules/redux`. Fixing the `yarn.lock` file by removing entries for Redux and RTK, followed by a reinstall, resolved everything correctly so that RTK was using `node_modules/redux` instead of its own version.
