### ISSUE TITLE
RTK Query not fetching data in React Native screen for the first time

### ISSUE THREAD

**Issue by devoren** [reduxjs/redux-toolkit#3165]
I am using RTK Query with React Native. My app contains screens using react-navigation/native-stack and react-native-screens. RTK Query data is undefined the first time. My api:
```
export const api = createApi({
    reducerPath: 'api',
    baseQuery,
    // tagTypes: ['User', 'Address'],
    endpoints: () => ({}),
});
const addressApi = api.injectEndpoints({
    endpoints: (builder) => ({
        getAddress: builder.query<AddressResponse, GetAddressRequest>({
            query: ({ id }) => ({
                url: ENDPOINTS.ADDRESSES.GET(id),
            }),
        })
    }),
    overrideExisting: false,
});

export const {
    useGetAddressQuery,
    useLazyGetAddressQuery,
} = addressApi;
```
And i use generated hook in my address screen:
```
const { data, isLoading, isSuccess } = useGetAddressQuery(
        { id: user.id! },
        {
            skip: !useIsFocused(),
        },
    );
```
I tried LazyQuery:

```
const [trigger, { isLoading, isSuccess }] = useLazyGetAddressQuery();
useFocusEffect(
        useCallback(() => {
            trigger({ id: user.id! })
                .unwrap()
                .then((data) => {
                    if (data.status) {
                        dispatch(setAddress(data.result.address));
                    } else if (data.message) {
                        Notice.Error(data.message);
                    }
                });
        }, []),
    );
```

The first time I go to the screen nothing happens, but after the second try everything works. Then I tried using the effect:

```
const fetchAddress =  () =>
        trigger({ id: auth?.user.id! })
            .unwrap()
            .then((data) => {
                if (data.status) {
                    dispatch(setAddress(data.result.address));
                } else if (data.message) {
                    Notice.Error(data.message);
                }
            });
useEffect(() => {
    fetchAddress()
}, [])
```
Same behavior:( Data  - undefined

**Comment by markerikson** [comment]
What do you mean by "undefined the first time", exactly?

RTKQ fetches data _after_ the first render. So, for any given component that is triggering a request, it's expected that there would be three renders:

- initial render, no data, not fetching yet
- status updated to `pending` because the fetch has started
- data has come back, status is `succeeded`

**Comment by devoren** [comment]
@markerikson  I have a list of screens and when I go to a certain screen I need to get the data. So the first time I go to the screen the data is returned undefined, then I open the screen again the data is fetched

**Comment by markerikson** [comment]
@devoren : so you're saying that when you use the hooks and open a screen, it _never_ updates with the data?  Because that sounds very broken.  

Can you put together an example that shows this actually happening?

**Comment by devoren** [comment]
@markerikson  I did everything wrong, I wanted to fetch data then dispatch it to slice and after that set the state from slice. After all of these steps show data in component using useState. I'm sorry for bothering you and many thanks for the prompt reply.

**Comment by markerikson** [comment]
@devoren : heh, I'm actually _more_ confused now :)

The point of RTK Query is that you don't have to write any code yourself to do the data fetching and re-rendering.  RTKQ will do that work for you - you just have to call `useGetSomeDataQuery()` in your component.

**Comment by devoren** [comment]
@markerikson I will try explain how i use it:
I want to fetch address from backend and save it in reducer that named setAddress. And when i fetched data, i want to dispatch(setAddress(data)) to use it in other screens.
```
const initialState: AddressState = {
	address: null,
};

const addressSlice = createSlice({
	name: 'address',
	initialState,
	reducers: {
		setAddress: (state, action: PayloadAction<IAddress>) => {
			state.address = action.payload;
		},
	},
});
```
So when i navigate to AddressScreen:
I select slice from store using useSelector:
```
const address = useAppSelector(state => state.address.address)
const [region, setRegion] = useState(address.region ?? "")
```
So when i call AddressQuery:
```
const {data} = useGetAddressQuery();
...
if (data.response.address) => dispatch(setAddress(data.response.address))
```
And my input where i use:
```
return ...
<Input
	label={lang.Region}
	setValue={setRegion}
	value={region}
	autoFocus
	editable={false}
/>
...
```
I've refactored the backend so I don't need getAddressQuery on the AddressScreen. I hope i was able to explain

**Comment by phryneas** [comment]
But **why** are you doing this? The data is already in the Redux store. You don't need to take it from the server, put it into the store, take it out of the store and put it back into the store. 

What do you need that `addressSlice` for if you can just call `const result = useAddressQuery()`?

**Comment by devoren** [comment]
@phryneas Do you mean that after call useGetAddressQuery, I can get the cached data from anywhere? Yes, I thought about it, but I was not sure that I can use it everywhere

**Comment by markerikson** [comment]
@devoren :that's the _other_ point of RTKQ :)

_Every_ component that calls `useGetSomeDataQuery(123)` gets the exact same cache entry, including status and current data.  RTKQ ensures that it only gets fetched once.

**Comment by devoren** [comment]
I knew that it only gets fetched once but I thought that in every component is called again. @markerikson  @phryneas Thank you both for the clear explanation🥇!  I'm sorry for bothering you!
