### ISSUE TITLE
Circular imports Using Multiple `injectEndpoints` and Slice Query Builders

### ISSUE THREAD

**Issue by Full-lifey** [reduxjs/redux-toolkit#3167]
We have an RTK application and are working on migrating from thunks to using RTK-Query. In order have a smooth migration process we have decided to do it in pieces as much as possible. The plan is pretty simple and will replace code in three steps: API > Components > Thunks.

Using the [extraReducers auth example](https://redux-toolkit.js.org/rtk-query/usage/examples#using-extrareducers) I started by building auth which works great. We also want to update a slice in this case so we don't need to worry about cache clearing in RTK-Q.

```
_auth.ts_

export const authEndpoints = acmeApi.injectEndpoints({
    endpoints: (builder) => ({
      login: builder.mutation<UserResponse, LoginRequest>({
        query: (credentials) => ({
          url: "/auth/login",
          method: "post",
          body: credentials,
        }),
      }),
    }),
})
```
```
_authSlice.ts_

  extraReducers: (builder) => {
    builder.addMatcher(acmeApi.endpoints.login.matchPending, (state) => {
      state.username = "";
      state.error = null;
    });
    builder.addMatcher(
      authEndpoints.endpoints.login.matchFulfilled,
      (state, { payload }) => {
        state.error = null;
        state.username = payload.username;
        state.tokens.access = payload.accessToken;
        state.tokens.refresh = payload.refreshToken;
      }
    );
    builder.addMatcher(
      authEndpoints.endpoints.login.matchRejected,
      (state, { payload }) => {
        state.username = "";
        state.error = payload?.data;
      }
    );
  },
  ```
  
  Perfect, it works great! Unfortunately, as soon as I attempt to do the same thing with a new set of injected endpoints in another slice I end up with a seeming circular import error. This is seemingly due to the new slice calling the new code-split injected endpoints, which import the same `acmeApi` so we get an error that we can't use it before initialization.
  
  Due to the use-cases of our application and the somewhat complicated async side we need the existing thunks working during this transition phase, which means persisting the data in our existing slices during migration.
  
  Is there a better solution than pulling actions out into the old enums way or adding all the endpoints into the `createApi` declaration?  These are the only two potential answers I've been able to find in 4 hours of searching and trying other solutions.

**Comment by Full-lifey** [comment]
Callout to #3166 as there are also few docs of updating existing state/slices with RTK-Query results.

**Comment by markerikson** [comment]
My first thought here is that there's not necessarily an RTK/RTKQ-specific issue here, but rather "just" a typical circular import cycle. Can you clarify what the import circle is?  What files are involved?  Where is the `const api = createApi()` call defined, and how do these files relate to each other?

**Comment by Full-lifey** [comment]
Both endpoint files import the same api from `api.ts`. We have two currently due to two different backend providers.

```
_api.ts_

export const trogdorApi = createApi({
  reducerPath: "trogdorApi",
  tagTypes: ["Scenario"],
  baseQuery: trogdorQuery(),
  endpoints: () => ({}),
});

export const acmeApi = createApi({
  reducerPath: "acmeApi",
  baseQuery: acmeQuery(),
  endpoints: () => ({}),
});
```

The endpoint files import the api and call `injectEndpoints` to define their endpoints as shown above. Here's the next set of endpoints and their slice:

```
_initialization.ts_
import { acmeApi } from "../api"

const initializationEndpoints = acmeApi.injectEndpoints({
  endpoints: (builder) => ({
    getEventTypes: builder.query<EntityState<EventType>, void>({
      query: () => ({
        url: "/db/get_all_event_types",
        method: "get",
      }),
      transformResponse(response: EventTypesResponse) {
        const eventTypes = response.body.map((eventType) => {
          return formatEventTypeResponse(eventType);
        });

        return eventTypesAdapter.addMany(eventTypesInitialState, eventTypes);
      },
    }),
  }),
});

export const { useGetEventTypesQuery, useLazyGetEventTypesQuery } =
  initializationEndpoints;
```

Everything still works. However, as soon as I import `initializationEndpoints` into the slice it's designated to update, I get the "unable to run before initialization" error.

```
_eventTypesSlice.ts_

import { initializationEndpoints } from "./endpoints/initialization"

... createSlice code.....

extraReducers: (builder) => {
    builder.addMatcher(initializationEndpoints.endpoints.getEventTypes.matchPending, (state) => {
 ...
 ```

**Comment by markerikson** [comment]
Hmm. I'd suggest using something like https://github.com/aackerman/circular-dependency-plugin , https://github.com/pahen/madge#orphans , https://github.com/sverweij/dependency-cruiser to check the codebase and see what import cycles are happening when you add that import.

Do those turn up anything useful?

**Comment by Full-lifey** [comment]
Mark,

I began re-building these slices and code-split endpoints and I don't appear to be having the issue any longer. I'm not sure what I did differently before but I think we would both rather it just work!

I applaud your hard work and outright incredible speed and attention on this issue. I will be closing it for now and will reopen if needed.

Thank you very much
