### ISSUE TITLE
Typescript cannot infere type for `updateQueryData` function

### ISSUE THREAD

**Issue by vadimyen** [reduxjs/redux-toolkit#3168]
I am encountering an issue with TypeScript type inference when using the `onQueryStarted` function. The query and its draft object are being inferred as having a type of never, however, the `getAlerts` query is still being detected as seen from the error message (refer to picture 1). There are correct types for the draft object and everything else in other places, e.g., inside `merge` function.

I would appreciate any help in resolving this issue and finding out what I might be doing wrong.

![image](https://user-images.githubusercontent.com/22547943/218255125-463eaa95-3314-4219-b289-9f47e20a8fce.png)
![image](https://user-images.githubusercontent.com/22547943/218255454-4f044d4a-243c-45cf-972d-ff74c0fc8392.png)

```typescript
export const api = createApi({
  reducerPath: 'api',
  baseQuery: baseQueryWithAuth,
  tagTypes: [TAG_ALERTS],
  endpoints: () => ({}),
});

const alertsApi = api.injectEndpoints({
  endpoints: (build) => ({
    getAlerts: build.query<GetAlertsListResponseData, GetAlertsListArguments>({
      query: (args) => ({
        url: '/alerts',
        params: args,
        method: METHOD_POST,
      }),
      async onCacheEntryAdded(
        args,
        { updateCachedData, cacheDataLoaded, cacheEntryRemoved }
      ) {
        await WS.startConnection();

        try {
          await cacheDataLoaded;
          WS.listenConnection((data: AlertString) => {
            const alert: Alert = JSON.parse(data);
            updateCachedData((draft) => {
              draft.entities.unshift(alert);
              draft.alertsCount += 1;
            });
          });
        } catch {}

        await cacheEntryRemoved;
        WS.stopConnection();
      },
      providesTags: [TAG_ALERTS],
      serializeQueryArgs: ({ endpointName }) => endpointName,
      merge: (currentCacheData, { entities, ...otherFields }) => {
        Object.assign(currentCacheData, otherFields);
        currentCacheData.entities.push(...entities);
      },
      forceRefetch({ currentArg, previousArg }) {
        return currentArg !== previousArg;
      },
    }),
    acknowledgeAlert: build.mutation<
      AcknowledgeAlertResponseData,
      AcknowledgeAlertArguments
      >({
      query: ({ alertId }) => ({
        url: `alerts/${alertId}`,
        method: METHOD_PATCH,
      }),
      async onQueryStarted({ alertId }, { dispatch, queryFulfilled }) {
        const patchResult = dispatch(
          api.util.updateQueryData('getAlerts', undefined, (draft) => {
            const restAlerts = draft.entities.filter(
              (alert) => alert.id !== alertId
            );
            draft.entities = restAlerts;
            draft.alertsCount -= 1;
          })
        );
        try {
          const response = await queryFulfilled;
          if (!response.data.success) {
            throw new Error("Couldn't acknowledge alert");
          }

          dispatch(
            showToast({
              message: 'Alerts was acknowledged',
              variant: 'success',
            })
          );
        } catch {
          patchResult.undo();
        }
      },
    }),
  }),
});
```

**Comment by phryneas** [comment]
Your `getAlerts` is already underlined red - because `getAlerts` is on the types of `alertsApi`, not of `api`.

=> 
```diff
- api.util.updateQueryData('getAlerts', undefined, (draft) => {
+alertsApi.util.updateQueryData('getAlerts', undefined, (draft) => {
```

**Comment by vadimyen** [comment]
Oh my bad, thank you, it was so obvious!

**Comment by vadimyen** [comment]
Now I get a new error. 

I am using `serializeQueryArgs`, `merge`, and `forceRefetch` which result in only one cache entry for the query and I need to update this entry with `updateQueryData`. However, Typescript requires a specific argument object, even though it doesn't matter in this case, and works fine with `undefined` at runtime. While I can pass a dummy object or make the argument nullable or use `| undefined`, these solutions may not accurately reflect the intended usage and semantics of the code. Is there a correct solution for resolving this error?

**Comment by markerikson** [comment]
@vadimyen : pass `void` as the generic argument for the request parameter:

- https://redux-toolkit.js.org/rtk-query/usage-with-typescript#typing-query-and-mutation-endpoints

**Comment by vadimyen** [comment]
@markerikson, I see this option. The fact is that in this way it will be possible to call the hook without arguments, which is not right for me, the request must always be called with arguments. I don't want to pass arguments only to `updateQueryData` since there is only one entry in cache

**Comment by markerikson** [comment]
@vadimyen : _Every_ RTKQ cache entry is identified by the combination of `endpointName + serializeQueryArgs(cacheKey)`.  Period.  You _must_ pass always pass in a cache key value, even if it's `undefined`.
