### ISSUE TITLE
Listener API stuck when JS thread reduced

### ISSUE THREAD

**Issue by MasonLe2497** [reduxjs/redux-toolkit#3172]
Hi, i facing a issue when use Redux toolkit and listener API for my  React Native project.
My authentication flow:
Step 1: call api login
Step2: when login succeeded, i set token to store. My UI check token to switch route
Each listener, i call function to show dialog loading. then listener end, i call 1 function to hide dialog loading
When i call set token (last line from listener api). My action (set token) took 200ms to end my listener api.
but my route change before listener api end.

My UI flow:
login action -> show dialog -> listener(1) (set token included end of code)-> hide dialog -> route will be switch when token change ->
app will go to home page -> call api get detail (did mount) -> show dialog( here, listener(1) end. it will hide my dialog)

I think listener api affected by JS thread.
Curren solution: move set token action to settimeout 0 ms.
My listener code:
```tsx
 export const takeLatestListeners =
  (withLoading?: boolean): StartAppListening =>
  (startListeningOption: any) => {
    return startAppListening({
      ...startListeningOption,
      effect: async (action, listenerApi) => {
        listenerApi.cancelActiveListeners();
        await listenerApi.delay(15);
        if (withLoading) {
          console.log('START_LOADING');
          listenerApi.dispatch(appActions.startProcess());
        }
        await startListeningOption.effect(action, listenerApi);
        if (withLoading) {
          console.log('END_LOADING');
          listenerApi.dispatch(appActions.endProcess());
        }
      },
    });
  };
```
My login action code:
```tsx
takeLatestListeners(true)({
  actionCreator: authenticationActions.login,
  effect: async (action, listenerApi) => {
    const { body, onError } = action.payload;

    const response = await NetWorkService.Post<LoginResponseType>({
      url: ApiConstants.LOGIN,
      headers: getHeaderConfig({ site_name: body.site }),
      body: body['2fa_code']
        ? {
            password: body.password,
            username: body.username,
            ['2fa_code']: body['2fa_code'],
          }
        : {
            password: body.password,
            username: body.username,
          },
    });

    if (validResponse(response)) {
      listenerApi.dispatch(appActions.setToken(response.data.access_token));
      // execFunc(onEnd, response.data.access_token);
    } else {
      // show error
    }
  },
});
```
My route code:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/43195241/218507212-f7dd68da-5d3c-4f32-bf86-3633de18f9a4.png">

Redux debuger on flipper:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/43195241/218507661-136dd33f-1ed6-4c9d-be58-ed1fcf71e6a2.png">
the end process action is belong to login action

My home code(didmount):
<img width="423" alt="image" src="https://user-images.githubusercontent.com/43195241/218508214-17ab4c4a-4cb1-4fbb-8856-e454fd8aa200.png">

My hot fix code:
```tsx
     setTimeout(() => {
        dispatch(appActions.setToken(response.data.access_token));
      }, 0);
```

**Comment by markerikson** [comment]
Sorry, I'm not sure I understand what you're trying to describe.  What do you mean by "JS thread reduced"?  What specific behavior is not working the way you want?

A listener is normal JS code, and it runs as part of the `dispatch()` cycle.  All the normal rules of JS event loop behavior apply here.

**Comment by MasonLe2497** [comment]
Yep, react native have 2 thread is JS thread and UI thread. when switch UI of route, JS thread will be drop(60 -> 30/40).
If listener is normal JS code, i think this is React Native thread issue. Thanks

**Comment by MasonLe2497** [comment]
BTW, listener so pretty cool

**Comment by phryneas** [comment]
Yes, but every `dispatch` will also happen on the same thread - if your listener doesn't activate, the most likely reason for that is that you either did not add it to the middlewares at all, or that you are not dispatching any actions. There is no  "threading" reason that dispatching would work, but the listener would not.
