### ISSUE TITLE
issue with withRedux 

### ISSUE THREAD

**Issue by Shivamycodee** [reduxjs/redux-toolkit#3173]
I don't understand why I'm getting this error:

TypeError: (0 , next_redux_wrapper__WEBPACK_IMPORTED_MODULE_4__.withRedux) is not a function

I'm just trying to use redux in next.js,

app.js file: 

<code>
import '@/styles/globals.css'

import { Provider } from "react-redux";
import {store} from "./store";
import { withRedux } from "next-redux-wrapper";

function App({ Component, pageProps }) {
  return <>
    <Provider store={store}>
   <Component {...pageProps} />
    </Provider>
  </>
}

export default withRedux(store)(App);

</code>

store file:-

<code>
import { configureStore, createSlice } from "@reduxjs/toolkit";

const counterSlice = createSlice({
  name: "counter",
  initialState: {
    value: 0,
  },
  reducers: {
    increment: (state) => {
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
  },
});

export const { increment, decrement } = counterSlice.actions;

export const store = configureStore({
  reducer: counterSlice.reducer,
});

</code>

**Comment by markerikson** [comment]
FYI, that's coming from `next-redux-wrapper`, which is a separate library. I think I heard someone say that they've had some major version changes recently.  I'd suggest asking over in that repo:

https://github.com/kirill-konshin/next-redux-wrapper
