### ISSUE TITLE
Alpha 2.0 - Cannot read properties of undefined (reading 'createApi') - Astro

### ISSUE THREAD

**Issue by BorjaRafolsMartinez** [reduxjs/redux-toolkit#3176]
Just tried to setup RTK with Astro using the most basic setup.

It looks to me that the 2.0 Alpha version is still not generating valid ESM modules. This is way beyond my knowledge.
It's worth nothing that import the base query version works, just not the React one.

`import query from '@reduxjs/toolkit/query'`
```
[Module: null prototype] {
  QueryStatus: {
    uninitialized: 'uninitialized',
    pending: 'pending',
    fulfilled: 'fulfilled',
    rejected: 'rejected'
  },
  buildCreateApi: [Function: buildCreateApi],
  copyWithStructuralSharing: [Function: copyWithStructuralSharing],
  coreModule: [Function: coreModule],
  createApi: [Function: baseCreateApi],
  defaultSerializeQueryArgs: [Function: defaultSerializeQueryArgs],
  fakeBaseQuery: [Function: fakeBaseQuery],
  fetchBaseQuery: [Function: fetchBaseQuery],
  retry: [Function: retryWithBackoff] { fail: [Function: fail] },
  setupListeners: [Function: setupListeners],
  skipSelector: Symbol(RTKQ/skipToken),
  skipToken: Symbol(RTKQ/skipToken)
}

```

`import query from '@reduxjs/toolkit/query/react'`
`undefined`

I pushed it to a repo here: [https://github.com/BorjaRafolsMartinez/astro-react-rtk](https://github.com/BorjaRafolsMartinez/astro-react-rtk)

I believe this is part of what you want to achieve on 2.0. Let me know if I can help.

**Comment by markerikson** [comment]
@BorjaRafolsMartinez Well, the first issue is that `import query` isn't a valid way to use RTKQ :)  We aren't trying to do a default export - it's all _named_ exports.

What happens if you do `import { createApi } from` in both entry point names?

(although I'll agree it's odd that one entry point returns a default object and the other doesn't.)

**Comment by BorjaRafolsMartinez** [comment]
Sorry about that, I used default export for debugging purposes:
`import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query'`
`[Function: baseCreateApi]`

`import {  createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'`
` error   Cannot read properties of undefined (reading 'createApi')`

**Comment by markerikson** [comment]
Hmm. That _is_ extremely odd. Okay, I'll try to take a look when I have time.  Thanks for reporting this and providing the repro!

**Comment by markerikson** [comment]
I'm going to _assume_ this is fixed by the more recent alphas and betas, and close this.

Could you let us know for sure if it does or does not work, either way?
