### ISSUE TITLE
Order of async thunk actions when aborting

### ISSUE THREAD

**Issue by LukaszGrela** [reduxjs/redux-toolkit#3180]
I have this peculari situation that I can't resolve, I have a fetch thunk action that is being aborted in `useEffect`. However the order of actions in redux dev tools are not in the expected order. I would expect, that calling abort will issue rejected action immediately:

```

useEffect(()=>{
   const promise = dispatch(fetchAction()); // pending action
   return () => {
       promise.abort(); // rejected action
   }
},[dispatch])

```
So the expected order would be as follows assuming useEffect was called 3 times
```
pending
rejected
pending
rejected
pending
fulfilled
```
however I receive it in the following order
```
pending
pending
pending
rejected
rejected
fulfilled
```

The async action (console logs and dispatch just for debugging):

```
const fetchAction = createAsyncThunk(
  'fetchAction',
  async (_, { signal, requestId, dispatch }) => {
    console.log('Calling #' + requestId);
    signal.addEventListener('abort', () => {
      console.log('Aborted #' + requestId);
      dispatch({ type: 'abort', requestId });
    });
    const response = await fetch('some/path/to/file.json', { signal });

    return JSON.parse(await response.text());
  }
);
```
console logs are in the correct order:
```
Calling #LM4Q
Aborting #LM4Q
Calling #ABcd
Aborting #ABcd
Calling #eFG1
```

also with the dispatching the action from the abort listener makes the order look correct

```
pending (requestId LM4Q)
abort (requestId LM4Q)
pending (requestId ABcd)
abort (requestId ABcd)
pending (requestId eFG1)
rejected (requestId LM4Q)
rejected (requestId ABcd)
fulfilled (requestId eFG1)
```
Is there something I'm missing here?

**Comment by markerikson** [comment]
@LukaszGrela can you post a CodeSandbox or a Replay ( https://replay.io/record-bugs ) that shows the actual code and what's happening?

Off the top of my head, what you may be seeing is the order that React runs effects.

React will run all effects in a given render sequentially, bottom-to-top.  Same with the cleanup functions, as far as I know.  So, yes, I would expect all of the `pending` actions first, then all of the `rejected` actions, because React would first run all the effect callbacks initially, then all the cleanup callbacks + all the effect callbacks again when there's a re-render that updates those.

**Comment by phryneas** [comment]
The problem here is that rejecting is an async process which will happen on next tick after you called `abort()` - and before that, more synchronous code can run.

**Comment by LukaszGrela** [comment]
Here is a [code sandbox with code replication](https://codesandbox.io/s/order-of-async-thunk-actions-when-aborting-3180-yizz03)

**Comment by phryneas** [comment]
As I said, this is to be expected - it is essentially the same as this example:
```js
function something(arg: string) {
    console.log("start " + arg)
    return () => Promise.resolve().then(() => console.log("end " + arg))
}

let cleanup
cleanup = something("foo1")
cleanup()
cleanup = something("foo2")
cleanup()
cleanup = something("foo3")
cleanup()
```

Which will log

>[LOG]: "start foo1" 
[LOG]: "start foo2" 
[LOG]: "start foo3" 
[LOG]: "end foo1" 
[LOG]: "end foo2" 
[LOG]: "end foo3"

**Comment by LukaszGrela** [comment]
well then, I'll stick with the following solution
```
    signal.addEventListener("abort", () => {
      console.log("Aborted #" + requestId);
      dispatch({ type: "abort", requestId });
    });
```

and handle this action in the reducer.

**Comment by phryneas** [comment]
You have not told us why this is a problem in the first place.

**Comment by LukaszGrela** [comment]
The reducer in the code sample is similar to the one from [examples on createAsyncThunk](https://redux-toolkit.js.org/api/createAsyncThunk#examples), it doesnt work well with aborting, when order of actions is not assured. On the code sample, the loaded JSON is never stored in reducer.

**Comment by phryneas** [comment]
Yeah I'm not too fond of that `idle` state there - a new incoming request should always take over to be the lastest request.

If you change it to
```js

    builder
      .addCase(fetchUserById.pending, (state, action) => {
          state.loading = 'pending'
          state.currentRequestId = action.meta.requestId
      })
```

order of operations does not matter.

(Generally for data fetching you should just use RTKQ though).
