### ISSUE TITLE
How to conditionally add headers?

### ISSUE THREAD

**Issue by mrnickel** [reduxjs/redux-toolkit#3183]
Hi there!

We use RTKQuery code generation for our swagger documentation and it works like a dream!

Our back end has an optional header `async-response` which by default is set to `false` if not specified by the client.

Sometimes (TM) from the client, we'd like to tell the server that we don't care about the response and we'd like to just go on with our day. In this case we'd like to CONDITIONALLY add the `async-response` http header.

I can't figure out how to do this via the `enhanceEndpoint` api, nor can I figure out how to do it via the hook syntax.

Our ideal would be to be able to specify the extra options in the hook and have that pass down to the `prepareHeaders`

Any suggestions?

Thanks again for such a wonderful library

**Comment by markerikson** [comment]
Hmm. Header functionality isn't specifically exposed at the hook or thunk level.  It's part of the endpoint definition itself, assuming you're using `fetchBaseQuery`.

One option could be to pass in an additional value as part of the cache key argument, and use that in the endpoint definition to help decide what the headers should be.  You may then want to exclude that value from the final calculated cache key via `serializeQueryArgs`.

**Comment by mrnickel** [comment]
Is that possible to do via the `.enhanceEndpoints` overrides? I'd prefer not to have to manually overwrite the code generated `injectEndpoints` definitions

**Comment by markerikson** [comment]
@mrnickel : you _should_ be able to pass in any of the endpoint fields in `enhanceEndpoints`, as far as I know.

**Comment by mrnickel** [comment]
@markerikson I'm getting some typescript errors.

Seems `serializeQueryArgs` does not exist on type:

```
Object literal may only specify known properties, and 'serializeQueryArgs' does not exist in type 'Partial<MutationDefinition<MoveApiArg, BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, (...redacted...), ReadCacheEntityResponse, "api">> | ((definition: MutationDefinition<MoveApiArg, BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, (...redacted...), ReadCacheEntityResponse, "api">) => void)'.
```

We're also running on the latest version of "@reduxjs/toolkit": "^1.9.2",


Definition of our "enhancer" is as follows:


```
export const enhanceEndpoints = odataApi.enhanceEndpoints({
  addTagTypes: [
    (... redacted...)
  ],
  endpoints: {
    (... redacted ...)
    move: {
        serializeQueryArgs: (args) => {
            console.log(args);
            return 'test';
        }
    }
  }
})
```

**Comment by markerikson** [comment]
Ah, I don't think mutations have a `serializeQueryArgs` option - that's only for query endpoints.

**Comment by mrnickel** [comment]
hrmm fair enough...

So that brings me back to my original question: How can I, using the enhancement overrides, conditionally add http headers?

It's kind of a niche use-case really as ideally all requests are the same.

Is there perhaps a way to send some sort of intent and capture that in the `prepareHeaders` and potentially switch based on the `endpoint`?

**Comment by markerikson** [comment]
@mrnickel : as one possible approach: if you're using `fetchBaseQuery`, you can pass any valid `fetch` option field as part of the object from `query`.  As an example:

```ts
    updatePost: build.mutation({
      query: ({ id, shouldAddExtraHeader...patch }) => ({
        url: `post/${id}`,
        method: 'PATCH',
        body: patch,
        headers: {
          "my-extra-header": shouldAddExtraHeader ? "42" : undefined
        }
      }),
```
