### ISSUE TITLE
RTKQ perf tweak ideas

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#3189]
In 1.9, we switched from storing subscription data in the Redux store, to an intentionally mutable object inside the RTKQ middleware, for perf improvements.

Currently, we do this inside of query hooks:

```ts
      // HACK Because the latest state is in the middleware, we actually
      // dispatch an action that will be intercepted and returned.
      let currentRenderHasSubscription = false
      if (queryCacheKey && requestId) {
        // This _should_ return a boolean, even if the types don't line up
        const returnedValue = dispatch(
          api.internalActions.internal_probeSubscription({
            queryCacheKey,
            requestId,
          })
        )
      }
```

We're using a mutable object, and that object should exist for the lifetime of the middleware.

What if we returned _that_ from `probeSubscription()`, and only did it _once_ when the hook first runs? that would save us the need to do `dispatch(probeSubscription())` on every hook run.

**Comment by markerikson** [comment]
Also see #3153 .

**Comment by phryneas** [comment]
I would want to measure if it makes a noticeable difference, but I'm not opposed. Just a little concerned that it might add a bit too much indirection.

**Comment by markerikson** [comment]
I can see it showing up in the perf capture, but not meaningfully so:

![image](https://user-images.githubusercontent.com/1128784/220242566-45eff4b1-8480-40da-909c-08e3f252c802.png)

Something to file away for later.
