### ISSUE TITLE
[Question]: Can you use Sets in Redux Toolkit?

### ISSUE THREAD

**Issue by mljlynch** [reduxjs/redux-toolkit#3197]
I find the Set API to be nice for certain data types, but I don't see a discussion in the [usage guide](https://redux-toolkit.js.org/usage/usage-guide) about whether or not they may cause problems. Has this been discussed? 

I see a discussion on the reduxjs library here: https://github.com/reduxjs/redux/issues/1499

**Comment by markerikson** [comment]
The exact same rules as standard Redux usage apply here:

- https://redux.js.org/style-guide/#do-not-put-non-serializable-values-in-state-or-actions

So, we specifically tell you _not_ to use Sets or Maps in Redux :)

**Comment by mljlynch** [comment]
Thanks @markerikson!
