### ISSUE TITLE
`store.dispatch` does not work in 1.2.2

### ISSUE THREAD

**Issue by yhnavein** [reduxjs/redux-toolkit#321]
After migrating to 1.2.2 `store.dispatch` stopped working with the following error message:

```
Argument of type 'ThunkAction<void, CombinedState<{ auth: AuthState; }>, null, Action<string>>' is not assignable to parameter of type 'AnyAction'.
  Property 'type' is missing in type 'ThunkAction<void, CombinedState<{ auth: AuthState; }>, null, Action<string>>' but required in type 'AnyAction'.
```

Dispathing through dispatcher from hook works fine though:

```
  const dispatch = useDispatch();
  ...
  dispatch(logOut());  // OK
```

I can't use React Hooks in the axios interceptor, so I was using this:

```
import store from '../../store';

store.dispatch(logOut());
```

**Comment by phryneas** [comment]
Could you please hover over `store.dispatch` and copy&paste what it gives you as definition there?

Also, are you using custom middlewares?

**Comment by jonjaques** [comment]
One more instance of error for ya:
```
Type 'ThunkAction<any, CombinedState<{ router: RouterState<any>; form: FormStateMap; user: IUser; cameras: IDuckState; users: IUsersState; global: IGlobalState; ... 7 more ...; connectionManager: IConnectManagerState; }>, { ...; }, IAction>' is missing the following properties from type 'LocationChangeAction<any>': type, payload
```

typeof store.dispatch:
```
EnhancedStore<CombinedState<{ router: RouterState<any>; form: FormStateMap; user: IUser; cameras: IDuckState; users: IUsersState; global: IGlobalState; ... 7 more ...; connectionManager: IConnectManagerState; }>, AnyAction | LocationChangeAction<...>, any[]>.dispatch: Dispatch
<AnyAction | LocationChangeAction<any>>(action: AnyAction | LocationChangeAction<any>) => AnyAction | LocationChangeAction<...>
```

**Comment by phryneas** [comment]
Hm. As for your comment: It's definitely a `&`, not a `|`. See [this playground](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=13&pc=21#code/JYWwDg9gTgLgBAbwIIDsCeSDGNgRQXzgDMoIQ4ByKAUwBMBXADwoFgAoUSWROAFQAt6KANYARYAGcwAQxiZ+cQiTKUaDRgFoYgkaw4oY1KEWmZqcAMoxZ5hOzhxakmXP4AuPjrHPZ8gDwo9CAARkYANIj4EagY2LgoAHxwAGRwABRpjB4ARIzZAJRwALxJAIz59nAA7qQoAObiUr7unkLeTa4BQaFQEQhRcDFYOHhJAD7pmTl5hSVw5ez47AA21PCMxXAADHDSErvou-tWNgDc7OyMAHROHfIZs0l7aCiY6Y88+BVs17cu97kChcflcangGj5XA9ik8JC83mkPghFN9rmD6o1-vw0oD8kA). Function signatures work that way.

How does your `middlewares` option to `configureStore` look? [You might need to add a `as const` there](https://redux-toolkit.js.org/usage/usage-with-typescript#correct-typings-for-the-dispatch-type)

**Comment by yhnavein** [comment]
> Could you please hover over `store.dispatch` and copy&paste what it gives you as definition there?
> Also, are you using custom middlewares?

```
(property) EnhancedStore<{ readonly [$CombinedState]?: undefined; } & { auth: AuthState; managePsw: ManagePswState; journal: JournalState; } & PersistPartial, AnyAction, (ThunkMiddleware<...> & { ...; })[]>.dispatch: Dispatch
<any>(action: any) => any
```

I am using only thunk middleware:
```
import thunk, { ThunkAction } from 'redux-thunk';

const store = configureStore({
  reducer: persistReducer(persistConfig, rootReducer),
  middleware: [thunk],
});

export type AppThunk = ThunkAction<void, RootState, null, Action<string>>;
```

**Comment by phryneas** [comment]
> > Could you please hover over `store.dispatch` and copy&paste what it gives you as definition there?
> > Also, are you using custom middlewares?
> 
> ```
> (property) EnhancedStore<{ readonly [$CombinedState]?: undefined; } & { auth: AuthState; managePsw: ManagePswState; journal: JournalState; } & PersistPartial, AnyAction, (ThunkMiddleware<...> & { ...; })[]>.dispatch: Dispatch
> <any>(action: any) => any
> ```
> 
> I am using only thunk middleware:
> 
> ```
> import thunk, { ThunkAction } from 'redux-thunk';
> 
> const store = configureStore({
>   reducer: persistReducer(persistConfig, rootReducer),
>   middleware: [thunk],
> });
> 
> export type AppThunk = ThunkAction<void, RootState, null, Action<string>>;
> ```
@yhnavein  I'll look into that. 
In the meantime: thunk is already integrated as a middleware, you don't need to specify that there. I guess skipping `middleware` altogether will solve your problem already.

**Comment by yhnavein** [comment]
If I delete line with `middleware: [thunk]` then my error is like this:

```
No overload matches this call.
  Overload 1 of 2, '(action: AnyAction): AnyAction', gave the following error.
    Argument of type 'ThunkAction<void, CombinedState<{ auth: AuthState; managePsw: ManagePswState; journal: JournalState; }>, null, Action<string>>' is not assignable to parameter of type 'AnyAction'.
      Property 'type' is missing in type 'ThunkAction<void, CombinedState<{ auth: AuthState; managePsw: Manag
ePswState; journal: JournalState; }>, null, Action<string>>' but required in type 'AnyAction'.
  Overload 2 of 2, '(asyncAction: ThunkAction<void, { readonly [$CombinedState]?: undefined; } & { auth: Auth
State; managePsw: ManagePswState; journal: JournalState; } & PersistPartial, undefined, AnyAction>): void', g
ave the following error.
    Argument of type 'ThunkAction<void, CombinedState<{ auth: AuthState; managePsw: ManagePswState; journal: JournalState; }>, null, Action<string>>' is not assignable to parameter of type 'ThunkAction<void, { readonly
 [$CombinedState]?: undefined; } & { auth: AuthState; managePsw: ManagePswState; journal: JournalState; } & P
ersistPartial, undefined, AnyAction>'.
      Type 'undefined' is not assignable to type 'null'.  TS2769
```

**Comment by phryneas** [comment]
> If I delete line with `middleware: [thunk]` then my error is like this:
> 
> ```
> No overload matches this call.
>   Overload 1 of 2, '(action: AnyAction): AnyAction', gave the following error.
>     Argument of type 'ThunkAction<void, CombinedState<{ auth: AuthState; managePsw: ManagePswState; journal: JournalState; }>, null, Action<string>>' is not assignable to parameter of type 'AnyAction'.
>       Property 'type' is missing in type 'ThunkAction<void, CombinedState<{ auth: AuthState; managePsw: Manag
> ePswState; journal: JournalState; }>, null, Action<string>>' but required in type 'AnyAction'.
>   Overload 2 of 2, '(asyncAction: ThunkAction<void, { readonly [$CombinedState]?: undefined; } & { auth: Auth
> State; managePsw: ManagePswState; journal: JournalState; } & PersistPartial, undefined, AnyAction>): void', g
> ave the following error.
>     Argument of type 'ThunkAction<void, CombinedState<{ auth: AuthState; managePsw: ManagePswState; journal: JournalState; }>, null, Action<string>>' is not assignable to parameter of type 'ThunkAction<void, { readonly
>  [$CombinedState]?: undefined; } & { auth: AuthState; managePsw: ManagePswState; journal: JournalState; } & P
> ersistPartial, undefined, AnyAction>'.
>       Type 'undefined' is not assignable to type 'null'.  TS2769
> ```

This seems to somehow be triggered by your `CombinedState` generic type... could you please share that type?

**Comment by belgattitude** [comment]
Same problem updating to latest, so here's a code snippet

The `store.ts` config:

```typescript
import { configureStore, Action } from '@reduxjs/toolkit';
import { ThunkAction } from 'redux-thunk';
import { authReducer } from './features/auth/auth.redux';

export const store = configureStore({
    reducer: {
        auth: authReducer,
    },
});

export type AppThunk = ThunkAction<void, RootState, null, Action<string>>;
export type RootState = ReturnType<typeof store.getState>;
```

The thunk in `auth.redux.ts`:

```typescript
export const runLogoutThunk = (deps?: { tokenStore?: ITokenStore }): AppThunk => async dispatch => {
    try {
        const { tokenStore = getTokenStore() } = deps || {};
        const token = tokenStore.getToken();
        tokenStore.removeToken();
        if (token) {
            const authResult = await authApi.logout(token);
        }
    } finally {
        /// HERE IT WILL COMPLAIN
        dispatch(getAuthLogout());
    }
};
```

And the TS error

```typescript
import { store } from '../../store';

export const createDefaultApiService = () => {
    const serverUrl = 'http://localhost:3000';
    const tokenStore = getTokenStore();
    const refreshTokenService = new RefreshTokenService({
        tokenStore: tokenStore,
        refreshTokenUrl: `${serverUrl}/auth/refresh-token`,
    });
    return new ApiService({
        serverUrl,
        refreshTokenService: refreshTokenService,
        tokenStore: tokenStore,
        onAuthFailure: (response): Response => {
           /// TYPESCRIPT IS COMPLAINING HERE ABOUT
           /// ------------------------------------------------------------------
           // error TS2769: No overload matches this call.
           // Overload 1 of 2, '(action: AnyAction): AnyAction', gave the following error.
           // Argument of type 'ThunkAction<void, { auth: AuthState; }, null, Action<string>>' is not assignable to parameter of type 'AnyAction'.
           // Property 'type' is missing in type 'ThunkAction<void, { auth: AuthState; }, null, Action<string>>' but required in type 'AnyAction'.
           // ...
            store.dispatch(runLogoutThunk());
            return response;
        },
    });
};
```

Don't know if it helps getting an idea... I'll try to investigate in the week-end if not found before. Any help appreciated and keep up the fantastic work !

**Comment by phryneas** [comment]
@belgattitude I think I can see the problem there. Does it work if you change it like this?
```diff
- export type AppThunk = ThunkAction<void, RootState, null, Action<string>>;
+ export type AppThunk = ThunkAction<void, RootState, undefined, Action<string>>;
```

**Comment by markerikson** [comment]
Both would probably be good, I guess.

**Comment by belgattitude** [comment]
@phryneas, 

> Does it work if you change it like this?
```diff
+ export type AppThunk = ThunkAction<void, RootState, undefined, Action<string>>;
```

Nope

```
error TS2345: Argument of type 'null' is not assignable to parameter of type 'undefined'.
55  await runLogoutThunk({ tokenStore: ts })(dispatch, getState, null);
```                                                                            

Setting it to `unknown` does the job, but I'm not sure about the implications.

**Comment by phryneas** [comment]
Nice, you went from 
> Type 'undefined' is not assignable to type 'null'.
to
> Argument of type 'null' is not assignable to parameter of type 'undefined'.
there :laughing: 

`unknown` should be a good bet there.

@ yhnavein and @jonjaques does that solve your problems as well? 
Then I'd try to do a PR over the weekend.

**Comment by yhnavein** [comment]
@phryneas For me it does indeed fix the issue and everything works fine :)

**Comment by phryneas** [comment]
Okay, I opened a PR for a fix.

Could you please try the [CodeSandbox build of that PR](https://ci.codesandbox.io/status/reduxjs/redux-toolkit/pr/329/builds/8873) with your original code and report if it fixes the problems?

> yarn add https://pkg.csb.dev/reduxjs/redux-toolkit/commit/933aa4a1/@reduxjs/toolkit
> or
> npm i https://pkg.csb.dev/reduxjs/redux-toolkit/commit/933aa4a1/@reduxjs/toolkit

**Comment by belgattitude** [comment]
@phryneas

Updated to `unknown` type and installed the sandbox... it seems to work ;) 

Thanks for your help, very clear and super pro... Amazing :)

**Comment by DanteDX** [comment]
store.dispatch<any>(myAction())
at least solved for me
