### ISSUE TITLE
[RTK Alpha]: Is ESNext output for all modules intended?

### ISSUE THREAD

**Issue by rschristian** [reduxjs/redux-toolkit#3210]
At the moment, all output files seem to be targeting `esnext`, which limits the support to the past couple years at a maximum. Fair enough if this was intended, but thought I'd ask, as there's a few comments in the build script which seem to indicate the idea (for the ESM at least) was to target ES2017: https://github.com/reduxjs/redux-toolkit/blob/ef49075675eacd75a80a03dc703d717e8b0e9f19/packages/toolkit/scripts/build.ts#L54

For example, here's the CJS output with optional chaining, an ES2020 feature: https://www.runpkg.com/?@reduxjs/toolkit@2.0.0-alpha.2/dist/cjs/redux-toolkit.cjs.development.js#1097

Edit: Generally, for maximum compatibility, you'd want to limit the output to ES2017 and only provide that via `"exports"`. There's no guarantees that something consuming `"main"` or `"module"` can consume ES2017+.

Edit2: I know optional chaining in particular will trip Webpack 4's parser, so users would need to make sure rtk is transpiled (which is very possible, of course): https://github.com/webpack/webpack/issues/10227

**Comment by markerikson** [comment]
Yeah, the comments need to be updated there.

And yes, my intent _is_ to ship 100% modern syntax with no transpiling if at all possible, and have it be up to users to transpile if their own build system / target app environment needs it:

https://github.com/reduxjs/redux-toolkit/releases/tag/v2.0.0-alpha.0

That said, yeah, the Webpack 4 situation _is_ the one thing that would make me hesitate slightly.  I've been debating whether the `main/module` artifacts ought to have that output limited.

**Comment by rschristian** [comment]
Oh wow, nice! Apologies,  Ididn't check the release notes there.

I think just about everyone using Webpack is happy to add `babel-loader` and/or a bit of custom config to tranpsile rtk if needed, so (IMO) that shouldn't hold you back too much.

Happy to close this / have this closed, wanted to avoid adding in another issue / PR if it was an accident as it'd easily get buried.
