### ISSUE TITLE
data bug in example app

### ISSUE THREAD

**Issue by jchris** [reduxjs/redux-toolkit#3217]
I am trying to update a Post in the mutations example app but get this error:

```
TypeError: comparatorFn is not a function
    at http://localhost:3000/static/js/bundle.js:32276:16
    at Array.reduce (<anonymous>)
    at http://localhost:3000/static/js/bundle.js:32245:41
    at Array.map (<anonymous>)
    at http://localhost:3000/static/js/bundle.js:32235:40
    at http://localhost:3000/static/js/bundle.js:32342:12
    at http://localhost:3000/static/js/bundle.js:32719:9
    at forEach (http://localhost:3000/static/js/bundle.js:32701:7)
    at Object.filter (http://localhost:3000/static/js/bundle.js:32718:3)
    at queryByPrimaryKey (http://localhost:3000/static/js/bundle.js:32340:24)
```

I think this is a problem with the data package, but [the code to reproduce it is here.](https://github.com/reduxjs/redux-toolkit/blob/master/examples/query/react/mutations/src/mocks/db.ts#L53)

here is a screenshot indicating the comparatorName is `"0"`

<img width="1840" alt="Screen Shot 2023-02-26 at 10 38 40 AM" src="https://user-images.githubusercontent.com/253/221430170-1a7e067e-f5dd-45d3-909d-da9cb247c563.png">

**Comment by phryneas** [comment]
Yeah, we probably have to pin that to a specific version of the `data` package :/

**Comment by fpetrakov** [comment]
@phryneas Fixed it up there ^
