### ISSUE TITLE
After second dispatch of the one action { ...state } returns {}

### ISSUE THREAD

**Issue by YoungProducer** [reduxjs/redux-toolkit#322]
![image](https://user-images.githubusercontent.com/37039996/72633233-b2585b00-3960-11ea-96bb-0f2cd2a86c24.png)
It's first dispatch.
![image](https://user-images.githubusercontent.com/37039996/72633287-cb610c00-3960-11ea-8349-44096061082d.png)
It's second dispatch.
![image](https://user-images.githubusercontent.com/37039996/72633349-f0ee1580-3960-11ea-9264-3fee274f42cd.png)
It's my code.
If you write for example console.log(...state.todos) it will shows you the content of state.todos but if you write console.log({...state.todos}) it will returns empty object ( {} ).
Also i've tried to rewrite code to default redux and it works well!

**Comment by markerikson** [comment]
Hmm.  That seems extremely odd.  Can you create a CodeSandbox that reproduces the issue?

Also, what happens if you use Immer to update the state, like:

```js
loadingGetTodos : (state, {payload}) => {
    state.loading = payload;
}
```

**Comment by YoungProducer** [comment]
> Hmm. That seems extremely odd. Can you create a CodeSandbox that reproduces the issue?
> 
> Also, what happens if you use Immer to update the state, like:
> 
> ```js
> loadingGetTodos : (state, {payload}) => {
>     state.loading = payload;
> }
> ```

That's all started not from todo's list. After I understood the problem I've tried to reproduce it on codesandbox and it work's well))). Than I copied and pasted from codesandbox to my app based on electron and I got this problem again. If it helps, I can commit all changes in my project and share link with you.

> Also, what happens if you use Immer to update the state, like:

I didn't try it but I will.

**Comment by markerikson** [comment]
I feel like I once saw someone else who had a similar problem in an Electron project, specifically, but I can't remember where or what the issue was.

**Comment by YoungProducer** [comment]
> I feel like I once saw someone else who had a similar problem in an Electron project, specifically, but I can't remember where or what the issue was.

If you mention or find the way to fix it, write me please. Thank you!

**Comment by YoungProducer** [comment]
> Also, what happens if you use Immer to update the state, like:
> 
> ```js
> loadingGetTodos : (state, {payload}) => {
>     state.loading = payload;
> }
> ```

So, it works work fine for me. Thank you!
