### ISSUE TITLE
How to update mutation cache when other mutation succeeds?

### ISSUE THREAD

**Issue by Irfanwani** [reduxjs/redux-toolkit#3220]
I have a login mutation which adds some cache and I added fixedCacheKey to the mutation as I wanted to keep the cache and wanted to share the same cache for multiple mutations. 

Now in the data returned, I have a key as `verified` which shows whether the user is verified or not and based on that I am eiher naviagting the user to the verification screen or the other screens if the user is verified.

Now what is want to do is if the user is not verified, he is redirected to verification screen where he gives the verification code and another mutation is called. 

When the verification mutation succeeds, I want to update the login cache and change the `verified` key to true there.

I didn't found anything related to this in the docs (update only works for queries for me, not mutations).

Though I can access the verification mutation cache too to make the things work but I wanted to know if there is any way to mutate the other mutation cache instead of using all the cache objects from different mutations.

**Comment by phryneas** [comment]
Generally: asking here, on StackOverflow, sending me a private email, and sending me another message on StackOverflow under a completely unrelated topic will not make me answer faster. 
I have been traveling.  
It isn't very pleasant to me to see your question get more and more privacy-invading.
At this point, I'm mostly answering out of fear that if I don't answer you might show up at my doorstep one day.
Please don't do that.

To answer the question: Mutations are there to change things on the server and look at the response for a brief moment, not for long-term data storage. So it doesn't make any sense to update them.

If you want to store parts of a mutation response for longer, we have documented ways of doing so in the docs, in [this example with `extraReducers`](https://redux-toolkit.js.org/rtk-query/usage/examples#using-extrareducers).

**Comment by Irfanwani** [comment]
Sorry for inconvenience, and thanks for the response.

**Comment by Irfanwani** [comment]
> Mutations are there to change things on the server and look at the response for a brief moment, not for long-term data storage. So it doesn't make any sense to update them

But as per docs, we can set a `fixedCacheKey` on mutations and keep the cache (persist the cache), then, why to save the same thing in a separate slice too (please correct me if i am wrong)?

**Comment by phryneas** [comment]
`fixedCacheKey` is a workaround if you have a button in one part of your application and want to display a loading state for the same mutation in another part of your application.  
It was not meant for data storage, so no data updating tools exist.

If you have a very "individual" use case like this, you will need to write code on your own.

**Comment by Irfanwani** [comment]
So, If I write the code on my own for updating the mutation cache only, is the rest all fine to be used directly in the app. What I mean is, is the cache management for the mutation alright to be used?

**Comment by phryneas** [comment]
If it only contains data from the server, received via that mutation, you can stay with `fixedCacheKey`. If you want to manually update those values, use a slice for that data instead.

**Comment by Irfanwani** [comment]
ok got it, thanks for the help. As I have to make a bit of updation to the data, I have to use slices.
