### ISSUE TITLE
Return types of useQuery not correctly inferred when using `Parameters<>`

### ISSUE THREAD

**Issue by TheDuc** [reduxjs/redux-toolkit#3221]
This could be a TypeScript mistake on my part, but please consider the following piece of code.

It is a function that accepts a `useQuery` function, and its params.
It is used to add certain filters to the query, but now reduced to a minimal reproduction example.

```typescript
export function useQueryWithFilters<QueryArg, BaseQuery extends BaseQueryFn, TagTypes extends string, ResultType, ReducerPath extends string = string>(
  queryFn: UseQuery<QueryDefinition<QueryArg, BaseQuery, TagTypes, ResultType, ReducerPath>>,
  ...params: Parameters<UseQuery<QueryDefinition<QueryArg, BaseQuery, TagTypes, ResultType, ReducerPath>>>
) {
  return queryFn(...params);
}
```

The problem is that this function does not correctly infer the data, it is shown as `any`:
```typescript
// 'originalData' is correctly typed according to 'useOriginalQuery'
const { data: originalData } = useOriginalQuery(originalParams);

// 'data' is typed as 'any'
const { data } = useQueryWithFilters(useOriginalQuery, originalParams);
```

UseQuery type from buildHooks is as follows:
```typescript
type UseQuery<D extends QueryDefinition<any, any, any, any, string>> = <R extends Record<string, any> = UseQueryStateDefaultResult<D>>(arg: QueryArgFrom<D> | SkipToken, options?: (UseQuerySubscriptionOptions & UseQueryStateOptions<D, R>) | undefined) => UseQueryHookResult<D, R>
```

For some reason `R` is not correctly inferred, and always typed as `Record<string, any>`

If I alter my `useQueryWithFilters` function to return `return queryFn(params[0]);` the typing works again, but that way I lose the ability to pass options

**Comment by TheDuc** [comment]
any update on this?

**Comment by markerikson** [comment]
Sorry, not clear what you're trying to do here or what would help.

**Comment by TheDuc** [comment]
wow, that's tough. Somebody could at least have asked further explanation instead of just closing.

The goal is to create a function that can be passed a useQuery hook, that does something to the params of that hook, and returns exactly the same data as the original useQuery would have returned.
As shown above, the params are typed as `Parameters<UseQuery<QueryDefinition<QueryArg, BaseQuery, TagTypes, ResultType, ReducerPath>>>`, and spread into the query function `queryFn(...params);`. This however does yield a return type of any, instead of the actual type of the original useQuery hook
