### ISSUE TITLE
Question:  entityAdapter selectTotal vs length

### ISSUE THREAD

**Issue by eddielee394** [reduxjs/redux-toolkit#3222]
Not an issue, but rather a question.  Having a discussion with a teammate and wasn't able to find a clear answer in the docs.  

When using an entityAdapter is there a material difference between using the `selectTotal` selector vs just checking the length returned by the `selectAll` selector? For example: 

```
const items = useSelector(selectAllItems); // 10 items
const itemsCount = items.length;

console.log(itemsCount); // 10 
```

vs

```
const items = useSelector(selectAllItems); // 10 items
const itemsCount = useSelector(selectTotalItems)

console.log(itemsCount); // 10
```

**Comment by markerikson** [comment]
It's the same thing:

- `selectAll` does `entityState.ids.map(id => entityState.entities[id])`, so the resulting array size is the size of `entityState.ids`
- selectTotal` _is_ just `entityState.ids.length`

So, same number, just different ways to get to it.

**Comment by eddielee394** [comment]
Thanks for the super fast response!  Closing the issue out.
