### ISSUE TITLE
Uncaught ReferenceError: Cannot access  slice before initialization

### ISSUE THREAD

**Issue by zhonglin0829** [reduxjs/redux-toolkit#3226]
Hello, I have a problem. I need to use redux outside the component，Response interception in axios，
When using the store, an error is reported and the slice cannot be accessed before initialization。
`
The version is as follows：
  "dependencies": {
    "@reduxjs/toolkit": "^1.9.2",
    "antd": "^5.1.7",
    "axios": "^1.3.2",
    "qs": "^6.11.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-redux": "^8.0.5",
    "react-router-dom": "^6.8.1",
    "redux-persist": "^6.0.0",
    "sass": "^1.58.0"
  },
  "devDependencies": {
    "@types/qs": "^6.9.7",
    "@types/react": "^18.0.27",
    "@types/react-dom": "^18.0.10",
    "@types/react-redux": "^7.1.25",
    "@vitejs/plugin-react": "^3.1.0",
    "typescript": "^4.9.3",
    "typescript-plugin-css-modules": "^4.1.1",
    "unplugin-auto-import": "^0.13.0",
    "vite": "^4.1.0"
  }
`
The error is reported as follows：
![微信图片_20230302125704](https://user-images.githubusercontent.com/53028653/222335042-c10be51c-57a6-4396-a586-56c87ce8c5c1.png)

`
// store   loginSlice
import { createSlice, /*PayloadAction 自定义action的数据--payload类型 ,*/ createAsyncThunk } from '@reduxjs/toolkit'
interface LoginState {
  loading:boolean,
  token:any,
  error:string | null | undefined,
  user:string
  pwd:string,
  isPromise:boolean
}

const initialState:LoginState = {
  loading:false,
  token:null,
  error:null,
  user:'',
  pwd:'',
  isPromise:false
}
export const loginRequest:any = createAsyncThunk(
  'login/loginRequest',
  async (params:{
    adminName:string,
    adminPassword:string
  })=>{
    const response = await apiPost('/admin/login',{
      adminName:params.adminName,
      adminPassword:params.adminPassword
    })
    return {
      data:response
    }
})
// 创建slice  它是action和reducer绑在一起的
export const loginSlice = createSlice({
  name:'login',//命名
  initialState,//初始化数据
  reducers:{
    logOut(state){
      state.token = null;
    },
    promisePwd(state,action){
      state.user = action.payload.user,
      state.pwd = action.payload.pwd,
      state.isPromise = action.payload.isCheck
    }
  },
  extraReducers:(builder)=>{
    builder
    .addCase(loginRequest.pending,(state)=>{//pending
      state.loading = true
    })
    .addCase(loginRequest.fulfilled,(state,action)=>{// success
      state.token = action.payload.data;
      state.loading = false
      state.error = null
    })
    .addCase(loginRequest.rejected,(state,action:any)=>{//error
      state.loading = false
      state.error = action.payload
    })
  }
})

`
The components using loginSlice are as follows：
`
  useEffect(()=>{
    if(token != null){
      navigate('/admin');
    }
  },[token])
  useEffect(()=>{
    if(isPromise){
      setUserName(user);
      setPassword(pwd);
    }
  },[])
`

**Comment by markerikson** [comment]
You're almost definitely creating a circular import problem.

**_Don't_ import the store directly into non-component files!**

See the example listed here:

- https://redux.js.org/faq/code-structure#how-can-i-use-the-redux-store-in-non-component-files

**Comment by zhonglin0829** [comment]
> You're almost definitely creating a circular import problem.
> 
> **_Don't_ import the store directly into non-component files!**
> 
> See the example listed here:
> 
> * https://redux.js.org/faq/code-structure#how-can-i-use-the-redux-store-in-non-component-files

Thank you for your answer and handled my question perfectly
