### ISSUE TITLE
WritableDraft Inconsistency Typescript

### ISSUE THREAD

**Issue by Grahamcraker** [reduxjs/redux-toolkit#3227]
Hoping someone could provide some information on this. In my slice below, I'm seeing the `foo` array being returned as `FooType[]` when calling useSelector() in a component. However, the `bar` array is returned as `WritableDraft<BarType>`. Why does RTK treat one differently than the other?

```
export type FooType= {
  id: string;
  type: ChatType;
  messages: Message[];
  members: Member[];
};

export type VarType= {
  queueId: string;
  chatId: string;
  content: string;
  userId: string;
  type: ItemType;
  status: QueueStatus;
};
export type IStateType = {
  foo: FooType[];
  bar: BarType[];
};

const initialState: IStateType= {
  foo: [],
  var: [],
};

const MySlice = createSlice({
name: "SliceName",
initialState,
reducers:{
...
}})
```

**Comment by markerikson** [comment]
Afraid that's not nearly enough info to go on.  Can you provide a CodeSandbox that shows this happening, and point to the specific location where you're seeing this?

`WritableDraft` is an Immer-internal type, and shouldn't be visible outside of the reducers.

**Comment by Grahamcraker** [comment]
Appreciate the sandbox recommendation. Actually led me to realizing I had written a reducer incorrectly, and the implied typing of the state was being changed based on the improper return type of the reducer.

**Comment by markerikson** [comment]
hah, nice :) and yeah, that's one of the reasons we _do_ ask for sandboxes / repros.  Not only does it give _us_ something more minimal to look at, it also verifies that it happens outside the context of the initial full application you might be working on.
