### ISSUE TITLE
Uncaught Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>

### ISSUE THREAD

**Issue by motionrus** [reduxjs/redux-toolkit#3228]
I want to write a useHook and make some store management methods public in another application. But when I do this I get an error

```ts
// My Redux Application which I published
export const useImage = () => {
  const dispatch = useAppDispatch()
  return {
    zoomIn: () => {
      dispatch(setZoom("zoomIn"))
    },
    zoomOut: () => {
      dispatch(setZoom("zoomOut"))
    },
    zoomFitToPage: () => {
      dispatch(setZoom("fitToPage"))
    },
  }
}
```

```ts
// is another application that wants to use public methods from the hook
import './App.css';
import {Markup} from "@cloud/markup-tools";
import "@cloud/markup-tools/dist/reset.css"
import React from "react"
import {useImage} from "@cloud/markup-tools";


function App() {
  const {zoomIn, zoomOut, zoomFitToPage} = useImage()
  return (
    <>
      <button onClick={zoomIn}>+</button>
      <button onClick={zoomOut}>-</button>
      <button onClick={zoomFitToPage}>Fit to Page</button>
      <Markup/>
    </>
  );
}

export default App;
```

**Comment by markerikson** [comment]
Two things:

- This is a React-Redux question, not a Redux Toolkit question
- Per the error, you need to make sure your React component tree is wrapped in `<Provider store={store}>`.  (If you _have_ already done that, another likely cause is accidentally having two copies of React or of React-Redux in the final JS bundle.)

**Comment by motionrus** [comment]
I have a question not about the error, but about the usage approach.

Can I create public APIs of my component. I used useImperativeHandle as a solution. But this option doesn't work for me, because I can only use public API in one place where I plug it in, which is inconvenient

If I have a hook that allows me to control the side from another React application, then I can use it anywhere. 

I found a way around the error, but I didn't find examples in the documentation to use it that way
```ts
export const useMarkup = () => {
  const {dispatch, getState} = store
  return {
    getStore: () => getState(),
    zoomIn: () => {
      dispatch(setZoom("zoomIn"))
    },
    zoomOut: () => {
      dispatch(setZoom("zoomOut"))
    },
    zoomFitToPage: () => {
      dispatch(setZoom("fitToPage"))
    },
  }
}
```

**Comment by motionrus** [comment]
I'm writing about this problem
https://stackoverflow.com/questions/38460949/what-is-the-best-way-to-access-redux-store-outside-a-react-component

**Comment by phryneas** [comment]
That seems to overcomplicate things a bit. Why not just import your store?

**Comment by yousuf4you** [comment]
### I am facing the same problem without any reason.
You can see it in my repo..

repo:  https://github.com/yousuf4you/memory-share

screenshot
![redux error](https://github.com/reduxjs/redux-toolkit/assets/60110696/e564bef3-12a1-467b-bd7d-75213df9e739)

**Comment by buscanopaul** [comment]
I think whenever you place const dispatch = useDispatch(); in any components you need to put 'use client' at the top.

**Comment by yousuf4you** [comment]
Th

> same here I'm doing nextjs with Ts I've wrapped the main layout's children within ![image](https://user-images.githubusercontent.com/58628870/239924433-fdd6ba56-c682-45d2-aeae-ba89f91f2534.png) I had the error but all was working well untill lately.

This is re-build time error.. dont worry.

**Comment by ART1377** [comment]
> I think whenever you place const dispatch = useDispatch(); in any components you need to put 'use client' at the top, in nextjs 13

worked for me thanks

**Comment by falkomerr** [comment]
> I think whenever you place const dispatch = useDispatch(); in any components you need to put 'use client' at the top, in nextjs 13

thx, worked for me

**Comment by Muzafar-Ali** [comment]
> I think whenever you place const dispatch = useDispatch(); in any components you need to put 'use client' at the top, in nextjs 13

thanks. it worked for me

**Comment by SJafarnia** [comment]
> I think whenever you place const dispatch = useDispatch(); in any components you need to put 'use client' at the top, in nextjs 13

worked! tricky one

**Comment by mizanmahi** [comment]
> I think whenever you place const dispatch = useDispatch(); in any components you need to put 'use client' at the top, in nextjs 13

Thanks, buddy! it saved me

**Comment by vasilemidrigan** [comment]
> I think whenever you place const dispatch = useDispatch(); in any components you need to put 'use client' at the top, in nextjs 13

Thank you! Worked!

**Comment by cyblogerz** [comment]
> I think whenever you place const dispatch = useDispatch(); in any components you need to put 'use client' at the top, in nextjs 13

Thank you ! saved my time :)
