### ISSUE TITLE
prepareHeaders seems to result in invalid request being issued

### ISSUE THREAD

**Issue by gruntruk** [reduxjs/redux-toolkit#3232]
First off, thanks for redux-toolkit! I'm using latest version 1.9.3 on node 18.14.2 and am seeing a strange issue when attempting to add an authentication header via `prepareHeaders`. Given the following:

```javascript
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

const baseQuery = fetchBaseQuery({
  baseUrl: "https://api.somewhere.com/v2",
  prepareHeaders: (headers, { getState }) => {
    headers.set("Authorization", `Bearer ${process.env.NEXT_PUBLIC_MY_API_KEY}`)
    return headers;
  },
});

export const myApi = createApi({
  reducerPath: "myAPi",
  baseQuery: baseQuery,
  endpoints: (build) => ({
    myEndPoint: build.query({
      query: () => ({
				url: "/myendpoint",
				params: {
					group_by: "whatever"
				}
      }),
    })
});

export const {
  useMyEndPointQuery
} = myApi;
```

Any modification of the headers seems to result in an invalid request being issued from the browser when the component mounts. From the raw headers in dev tools I can see it being included, however, the header prefix seems to be missing. If I replay the request from the dev tools it works fine.

Here's the invalid request being issued:

```
GET /myendpoint?group_by=whatever undefined
Host: api.somewhere.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: http://localhost:3000/
authorization: Bearer secretkey
Origin: http://localhost:3000
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Sec-GPC: 1
```

If I replay the request in devtools it works and I see the following (note that the HTTP version is now included):

```
GET /myendpoint?group_by=whatever HTTP/1.1
Host: api.somewhere.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: http://localhost:3000/
authorization: Bearer secretkey
Origin: http://localhost:3000
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Sec-GPC: 1
```

Any modification of the headers results in the request becoming invalid. Wanted to see if anyone else is encountering this or perhaps I'm donig something wrong. The implementation was derived from reading the current documentation so it seems right to me but perhaps I've done something incorrect. Any help is appreciated. Thanks!

**Comment by phryneas** [comment]
RTK Query just calls `fetch` with those headers, so if you can make it work with `fetch`, it will work with RTKQ as well. 

Maybe you have CORS issues here?

**Comment by gruntruk** [comment]
Oof... you're right. It's a CORS issue. Closing this now and thanks!
