### ISSUE TITLE
how to dispatch an thunk after the first thunk is fulfilled sequentially?

### ISSUE THREAD

**Issue by faiyaz032** [reduxjs/redux-toolkit#3233]
I am trying to dispatch another thunk after only the first thunk is fulfilled. In the extraReducers callback function, I don't have access to dispatch another thunk. So how Can I Do this sequentially one by one? Is there anyone who can help me on this?

**Comment by JulienKode** [comment]
@faiyaz032 it's possible to do this with a [listener](https://redux-toolkit.js.org/api/createListenerMiddleware#createlistenermiddleware-1)

**Comment by faiyaz032** [comment]
> 

thanks for your reply @JulienKode . Actually, I am using rtk in with vanilla nodejs project just for practicing, I am attaching my code, it may help you to describe more.


`const fetchRandomVideo = createAsyncThunk('video/fetchRandomVideo', async (_, thunkApi) => {
  const response = await fetch('http://localhost:9000/videos', {
    method: 'GET',
  });

  const randomVideo = await response.json();

  return fetchRelatedVideos(randomVideo.tags);
});`

Right now I am doing this. But fetchRelatedVideos is not firing only when the fetchRandomVideo  is fulfilled.

**Comment by JulienKode** [comment]
You can simply do this outside redux by doing this for example
```typescript
const onClick = async () => {
  try {
    const randomVideo = await dispatch(fetchRandomVideo()).unwrap()
    dispatch(fetchRelatedVideos(randomVideo.tags));
  } catch (rejectedValueOrSerializedError) {
    // handle error here
  }
}
```

Other possibilities:

You can also create another thunk:
```typescript
const mainThunk = createAsyncThunk('video/main', async (_, thunkApi) => {
 try {
    const randomVideo = await thunkApi.dispatch(fetchRandomVideo()).unwrap()
      thunkApi.dispatch(fetchRelatedVideos(randomVideo.tags));
  } catch (rejectedValueOrSerializedError) {
    // handle error here
  }
});
```
With a middleware you can do this for example:
```typescript
listenerMiddleware.startListening({
  matcher: fetchRandomVideo.matchFulfilled,
  effect: (action, api) => {
     const tags = tagsSelector(api.getState());
     api.dispatch(fetchRelatedVideos(tags));
  },
})
```

To implement your api and do API calls with redux I recommend you to take a look at [`RTKQ`](https://redux-toolkit.js.org/rtk-query/overview) because currently `fetchRandomVideo` does something that RTKQ can already do for you, which is to create thunks that use fetch to do your api call for example.

You can follow this guide: https://redux-toolkit.js.org/rtk-query/usage/migrating-to-rtk-query#converting-to-rtk-query

**Comment by faiyaz032** [comment]
> You can simply do this outside redux by doing this for example
> 
> ```ts
> const onClick = async () => {
>   try {
>     const randomVideo = await dispatch(fetchRandomVideo()).unwrap()
>     dispatch(fetchRelatedVideos(randomVideo.tags));
>   } catch (rejectedValueOrSerializedError) {
>     // handle error here
>   }
> }
> ```
> 
> Other possibilities:
> 
> You can also create another thunk:
> 
> ```ts
> const mainThunk = createAsyncThunk('video/main', async (_, thunkApi) => {
>  try {
>     const randomVideo = await thunkApi.dispatch(fetchRandomVideo()).unwrap()
>       thunkApi.dispatch(fetchRelatedVideos(randomVideo.tags));
>   } catch (rejectedValueOrSerializedError) {
>     // handle error here
>   }
> });
> ```
> 
> Then you'll just need to call `dispatch(mainThunk())`
> 
> With a middleware you can do this for example:
> 
> ```ts
> listenerMiddleware.startListening({
>   matcher: fetchRandomVideo.matchFulfilled,
>   effect: (action, api) => {
>      const tags = tagsSelector(api.getState());
>      api.dispatch(fetchRelatedVideos(tags));
>   },
> })
> ```
> 
> Then every time you `dispatch` `fetchRandomVideo` and this fulfilled, this will automatically `dispatch` `fetchRelatedVideos`
> 
> To implement your api and do API calls with redux I recommend you to take a look at [`RTKQ`](https://redux-toolkit.js.org/rtk-query/overview) because currently `fetchRandomVideo` does something that RTKQ can already do for you, which is to create thunks that use fetch to do your api call for example.
> 
> You can follow this guide: https://redux-toolkit.js.org/rtk-query/usage/migrating-to-rtk-query#converting-to-rtk-query

@JulienKode Thanks again for your brief Description. As I said there is no UI. I am doing it in a raw node javascript project. I've created another thunk to await both fetchRandomVideo and fetchRelatedVideos. It's now serving my purpose. But I am wondering if there is any way to determine in the 'fetchRandomVideo' thunk to determine if it's fulfilled. If it's fulfilled then we will dispatch another thunk.

**Comment by JulienKode** [comment]
You can use this function even without UI 
```typescript
const mainFlow = async () => {
  try {
    const randomVideo = await dispatch(fetchRandomVideo()).unwrap()
    dispatch(fetchRelatedVideos(randomVideo.tags));
  } catch (rejectedValueOrSerializedError) {
    // handle error here
  }
}
mainFlow().then(() => doStuff())
```

As far as I know there is no way to wait inside `fetchRandomVideo` that `fetchRandomVideo` is fulfilled, as `fetchRandomVideo` will be fulfilled when the thunk execution finish.

**Comment by JulienKode** [comment]
Should we close this issue ? 

cc @markerikson

**Comment by faiyaz032** [comment]
okay, thank you for the responses guys. I am closing the issue.
