### ISSUE TITLE
How to customize the error message in RTK query error handler at a macro level

### ISSUE THREAD

**Issue by LeoLeoLeoLei** [reduxjs/redux-toolkit#3235]
How to customize the error message in data?

![image](https://user-images.githubusercontent.com/69226461/223117526-bc45ef31-4e2b-4644-be6e-c5c349f62e81.png)

**Comment by markerikson** [comment]
That's entirely up to you and your app code.  This is _just_ an example of a thing you _could_ do.

In this case, the example is assuming that an error was thrown in the thunk payload function, and that the error somehow has a `.data.message` field in it.  (Which seems odd, really, but the point is it's up to you to determine what gets thrown and how it's handled.)
