### ISSUE TITLE
Accessing state from useSelector in React-Native doesn't throw an error

### ISSUE THREAD

**Issue by friyiajr** [reduxjs/redux-toolkit#3236]
I am migrating a codebase from Vanilla RN to RTK in a React-Native app. In some rare places though, there are developers that mistakingly made code changes like this:

```
const someValue = useSelector(someSelector)
someValue.newValue = 99
```

It was likely some junior developer or something that didn't understand Redux. Anyway, with `immutableCheck: true` I SHOULD see the app crash or some kind of warning when this happens, however, this is not the case. 

I would like to get these error messages in dev mode so developers can more easily debug this issue when it happens. This is what happens on the Web in an RTK project anyway. Instead, on React-Native, the result is unpredictable things like no mutation happening or the root state being manipulated. No error message is shown.

I have a reproducer where I try to do this and get no crashes or warnings in React-Native Expo. We are using Vanilla RN for my project but this is easier to get up and running for both of us. The behavior is the same on both platforms anyway. 

```
const MainApp = () => {
  const count = useAppSelector((state: RootState) => state.counter)
  count.value = 99
```

You can download the reproducer here:
https://github.com/friyiajr/StateMutationReproducer

Just do `npx expo start` to run it. Nothing special

**Comment by phryneas** [comment]
This might be an engine problem. From what I remember, non-`use strict` environments just "swallow" writes on frozen objects. Nothing that we can really do about it though ☹️

**Comment by PravinBagde** [comment]
Ddd
