### ISSUE TITLE
Add async thunk extra args after configureStore call

### ISSUE THREAD

**Issue by Guillaumez** [reduxjs/redux-toolkit#3238]
Hi ! 
Because some extras depends on React contexts (like notifications) and are available only when some parts of the app are loaded i'm wondering if it would be possible to add async thunk extra args after the configureStore call ?

Example:

```javascript
// Tried this kind of override but it doesn't work 😄 

const extraArgs = {notifications: undefined}

const useUpdateExtraArgs() {
   const notifsManager = useNotifications();
   extraArgs.notifications = notifsManager;
}

const store = configureStore({
    ...
    getDefaultMiddleware({ thunk: { extraArgument: extraArgs } })
});
```

Did i missed something ? Are there any alternatives ?

**Comment by Guillaumez** [comment]
Well, found an alternative. Should have used a callbacks... `getNotifications`

**Comment by markerikson** [comment]
Yeah, that's basically the right approach. Hard-code an object reference that gets passed in at store creation, and then mutate that object directly after that as the right pieces get filled in. A bit awkward, but it works!
