### ISSUE TITLE
Code Splitting and middleware

### ISSUE THREAD

**Issue by ValyaBabenkov** [reduxjs/redux-toolkit#3242]
Good afternoon, I wrote a function to connect dynamic redusers. But when I specify middleware TS swears.

The code below:

**createReduxStore.ts**

```
export function createReduxStore(
    initialState?: StateSchema,
    asyncReducers?: ReducersMapObject<StateSchema>,
) {
    const rootReducers: ReducersMapObject<StateSchema> = {
        ...asyncReducers,
        ...persistedReducer,
    };
    const reducerManager = createReducerManager(rootReducers);

    const store = configureStore<StateSchema>({
        reducer: reducerManager.reduce,
        preloadedState: initialState,
        middleware: (getDefaultMiddleware) =>
            getDefaultMiddleware({
                serializableCheck: {
                    ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
                },
            }).concat(
                authApi.middleware,
            ),
    });

    // @ts-ignore
    store.reducerManager = reducerManager;
    return store;
}
```

**persistedReducer.ts**

```
const reducers = combineReducers({
    auth: userReducer,
    api: apiReducer,
    [authApi.reducerPath]: authApi.reducer,
});

const persistConfig = {
    key: 'root',
    timeout: 99999,
    storage: AsyncStorage,
    whitelist: ['profile', 'api'],
};
export const persistedReducer = persistReducer(persistConfig, reducers);

```

**StateSchema**

```
export interface StateSchema {
    auth: AuthResponse,
    api: ISTANDS_API,
    [authApi.reducerPath]: AuthResponse,
}
export type StateSchemaKey = keyof StateSchema

export interface ReducerManager {
    getReducerMap: () => ReducersMapObject<StateSchema>;
    reduce: (state: StateSchema, action: AnyAction)
        => CombinedState<StateSchema>;
    add: (key:StateSchemaKey, reducer:Reducer) => void;
    remove: (key:StateSchemaKey) => void;
}

export interface ReduxStoreWithManager extends EnhancedStore<StateSchema> {
    reducerManager:ReducerManager
}
```

I would appreciate feed
<img width="945" alt="Снимок экрана 2023-03-08 в 17 05 21" src="https://user-images.githubusercontent.com/53038415/223733943-b7bd1b3a-dd30-4b6c-961d-0dc231341a10.png">
back. Thanks

**Comment by phryneas** [comment]
Can you try to recreate that error in a [TypeScript Playground](https://www.typescriptlang.org/play/)?

**Comment by zorin-mv** [comment]
I have the same issue

**Comment by YaelRosenblum523** [comment]
I have the same issue - has anyone got this solved?

**Comment by coder-tech-10** [comment]
I have the same issue. Has anyone solved this?

**Comment by EskiMojo14** [comment]
It's hard to advise for people who have the same issue without confirming whether they're using the code, but there's a few mistakes with the original code that set off alarm bells for me.

Firstly, `(state: StateSchema, action: AnyAction) => CombinedState<StateSchema>` is not a valid signature for a store reducer - it needs to be able to receive undefined, and return its initial state. I would recommend instead just putting `Reducer<CombinedState<StateSchema>>`.

Secondly, `configureStore<StateSchema>` is bad. Like most RTK utils, `configureStore` is set up to *infer* its type parameters from the argument provided to it, and by providing the first argument you break its ability to infer middleware, enhancers, etc.

Contrary to the example provided by the docs, I would also recommend using an enhancer to add the reducerManager property to store, so RTK (and TS) can properly infer that it exists.

With all of that said, I've created a [TS Playground example of a reducer manager](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQZQDbDJoA0KEIARsAHZoBKaAJgK5FQDOpyE1AZsAHNm6HDGgk4ABQwBPPBAyMAgshjAepBizbsAshjAB5CgCs0q0gGFyVWo1FYJW1miilR4gKLUAFhmpscAC+cLxQ5HAARAAC6CwAHibsAPRiEHgA1sAwkQBQoJCwiCjojkpgwKS8aDDIPgBCGOxoAIrMrjLBoeEgUbFMzIkpaZnZyYzA7DDJAI7tUDJ5BdDwSMzNHuik67hoeOZibnA7ACKTYFh1pAAqMmBMAKobewfQABIQEBldYRGRpaoALRxQZLcArYo7Ty8aqqH49KIAnK5XLcahTMjMajYKD4QhoOAAXhKmGweKIAAoELk4LS4NQMCA0AAuKLcLE4yLEGl0mjZYAYPAObCspAAN0F7VZAAZgty6XAQTpRTyFbSaKg0EzsayKVNHABKIkAPjgYogwEYcH12AAdBK8O0ANRO1XBXJBA0otEYsSMCDkgnEzWOQNUt0MpmsyJ+iDsLluvlqQXCllwADaAF04E1imoYPtWVMoDQBMEs3AAD7HaiMND8OzyulK1zsFVqumKRjXCD+3U2iQYVTqais6RyBTKYc8AA8SHzhetMBL1DLQWNRsJpupHY7A4A-LawOsfBSh2oeEfZPJFF7d+6FUEPV7UTwMf5ysAiSSyhVwwqKCaVp5hkVlqlqBogLaDoqU9JtaTQWtIBoGA2zgCkKGYYA8EYTdTX-XcBBqa4fFLVlMOwxhbTmGCd3vOkaIWXU8LgAByGBSNXVi3UfO86U9Z8URgO4CUMag8BkQwwAvBk8AAaTQGR2BnVNTWJDJFIgXhinTOS4BoOANJkLS4FTHN2AzLE6wbJhszQeJsFrCz01TXTM2zfc4D01laDFVxM1ZZd2ndXJ7MKeAUNcXghwJZw2H0BkiKgFSYEcbc3SImA4tcfQwGYk04GyjhcuMMxVBStKAG43RbKBWSKmdrEoGgmFTCrsGNY1qoVLtWRnPT7McxgLKMkzVIpIzWTk0havqgY2HatA3I3ArzUtbrmy1CA-N1Sa4DEiSpJkwUFKUxaVq3M0LUYDaEN8fw2FZTY0G8PwAlcOdFXmnL-AwJK5u0H7Eo+1Tgi6j0UTCiFeCxadqB-bAioSv6QdSjqKSTAU8CKtCcZK0wDnOo06NpZJkjgSxSmwHN4YgAm4QAd1Iuo4BAAwRsUiyxC+wGODdH14FqiziSQW0xcxwUcZChUyYpqmCQ4gkJbwMhmrsIq3X2eBuDVpgiu-HXbHob6OApIWXxl8mlHhjAoCgWQ4CZwgfH0iyditbm6y1gkB0MznHZ8RCeZcDgc3QL6QG2phNZqP2lJ7BhI529DRu01MDQrYksxRBUBeD+Lfv+wqTeRpLzu-Em1UypGDHyy6he5Hi6VlkiCXCCBBZN0JYZkuAoeaK0KE6DjJjgOmypgJvSfJkjR4Z7CVYoAkLnYAe4G5xWl3EKf89cfs0cHOGWMr+9ZYASW0-xOiFuA-D8uAl6D9Ak6YLh9n8Y4wHXwPgCgJdHFCL-KYO8FTAG0hNTmCctp+VtPsVcHE4CmmlMTEBu5fYizgGLW0vsQi5ivqgjsvBoDoS1nHMe2kjLsCgS-FB9E6FwC9jUH2B8ACE6YjKZgIWqJ89C1SUOoVHb82deFPi4bLE4LwBAAI3oHVWRsrS1S4egGAwh4aGxaowIqeoD6kHPCOPiHYgiN1PlbRgw0cz0jQAzXef954IM3uwe4yAwHACYHHHevUU6KRmibY+XCwHoRYUZKs1YhbsMUpmWhvDNoqKgNQLhojeGyyUGY7+bcu4yPSbzVmBgKiriUSbdg4SZDZmJIosR5MADiiFXAAIwJY6x6i7A2K4U0vWXdgw2BajjM2hSDHcOMbuWWico4WXqbVR22QXYOKcS4txRkd7PyjrtPxvC87BPUuZOOY0D7VX8eAoJikQlwBYWEjhUTolfVifEkROd6HDOgUreAvxeibwmWzMAeSBBcMYdTM5ES7l0OSakzewTMlwAIBiEylD14QBQO-eGzAwBcP4RAEZMDjzsFPEZC29yqk1PttTeptBGldOaYotZZL2nZM6brHp5sd5GMBWqRCb1HroVoA5FiFIsG2wEOwVZ9C85THEN+TlMAeViz5QK269FlGqMQFwhUWCRVbCVZtXmpdXAJMZW6HhMSFW1S1VACGr50Sd01YXVwBt5Y12BlAAitJ0zsmxK4QMtpIxoACpiV1uICBEFtLVeCGZYzus9d60N-q0CBpNsG9MH4Kgxt5tIDi3qE3ACTSHbkAkzUYlVUGMgfBBDCFwIcNAjqbGsiNVaqAma2DBpAJaRg+wGa2zTBSAQJxdAsU7boCkBpbRomQFgM81BPy2kbWYltbaDTBtZQ9VsrJ0zVvtbaed70oCcJzcJe4cByhgGet+HdaATL5r2cevdnyziOMuC7Yk+7nrpkiBMG9EFIiZnPSJQqnwYBmWJAwa5tx7gzgfWWp9mVUzvvBrm+AOxQOiuJDsQ9uZ+0FXg+gPZec4NXvOLeuupp93XouBBb8pxcMQUw2+WDzQH0vFUNAVkQHHjPH2PRqAHwvgzjoD+0GiGWOvCgJR81FNyCQFoNib8qHLqV2FWW0jNHPnPX7bKqEMIDgUik+le8+a61AxRrWrsFIXU4jDYyCQxm3VRt01AA0eztNlus8amNL8KTsV7HGVi-SjEZkifzKjsL-TC2OApg9dHDgaYHCxActpYwCpqjUBV1BmB4DwNVJ8QA).

You may also be interested in the new [`combineSlices`](https://deploy-preview-3089--redux-starter-kit-docs.netlify.app/api/combineSlices) API we're adding in RTK 2.0, which allows for lazy reducer injection - we'd love it for people to try out the beta and give feedback.
