### ISSUE TITLE
Automatic data normalisation and updates

### ISSUE THREAD

**Issue by klis87** [reduxjs/redux-toolkit#3248]
Hi, I created a https://github.com/klis87/normy library, which provides a similar experience like apollo client regarding automatic updates from mutation responses (but for anything, not graphql only).

This library allows an easy integration with libraries like `react-query` or `swr`, and hopefully `RTK Query`. Please let me know if you think `RTK Query` users would find it useful. There is already plugin for `react-query`, in similar fashion a plugin could be created for `RTK Query` too.

**Comment by markerikson** [comment]
Always interested in seeing Redux integrated with other tools - let us know if you come up with something!
