### ISSUE TITLE
Does it matter where in the repo we use `startAppListening`? Only works in certain locations for me

### ISSUE THREAD

**Issue by igorkoho** [reduxjs/redux-toolkit#3249]
Hey everyone!

I can't quite understand why using the `startAppListening` function (which I get from the typescript docs for the listener middle ware) works in some files, but not in others.

Where it works:
- in `App.tsx`
- in the same file where I create the slice for the actions I want the listener to listen to

Where it doesn't work
- In a file that sits on the same level as the slice file mentioned above
- anywhere else I've tried.

Does anyone have any idea why I might be doing wrong here?

Thanks!

**Comment by markerikson** [comment]
@igorkoho Can you clarify what you mean by "doesn't work"?  Could you show a CodeSandbox or a Replay ( https://replay.io/record-bugs ) that demonstrates what you're trying to do?

**Comment by phryneas** [comment]
Generally: only because it is on a file on your harddisk doesn't mean it will be executed on your client, or even bundled and shipped to the client.

Your application has *one* "entrance" file that will be guaranteed executed. All other files will only be executed if they are included by that file, or included by a file that is included itself.

**Comment by igorkoho** [comment]
> @igorkoho Can you clarify what you mean by "doesn't work"? Could you show a CodeSandbox or a Replay ( https://replay.io/record-bugs ) that demonstrates what you're trying to do?

Sure thing, here is the sandbox. I have the same listener in 3 files:
- feat1 slice file
- feat1 listener file
- app index file

All listeners are the same, except they log out their specific location names when they run. Clicking the toggle button dispatches the action, and we see the index and slice file's listeners run, but not the listener file's.

> Generally: only because it is on a file on your harddisk doesn't mean it will be executed on your client, or even bundled and shipped to the client.

> Your application has one "entrance" file that will be guaranteed executed. All other files will only be executed if they are included by that file, or included by a file that is included itself.

Interesting, so simply importing the `startAppListening` function into a file in the repo doesn't make it run? This is the sort of pattern I've been following with RTKQ api's and slice creation, and it has been working up till now.

**Comment by phryneas** [comment]
My point was more that you can call it a hundred times in a file that will not be imported, and it will never execute.

**Comment by igorkoho** [comment]
> And you don't seem to import feat1Listener.ts anywhere, so how should any code in there exceute?

So I think this is the part that I wasn't clear on. Where is it supposed to be imported?

I thought running `startListening` in that file registered the listener in the `feat1Listener.ts` file, without having to import it anywhere. Sort of like the `injectEndpoints` method works (in my understanding at least, since the returned value doesn't have to be imported anywhere for the queries to work).

**Comment by phryneas** [comment]
> Sort of like how (in my understanding) injectEndpoints works in RTKQ, since the returned value doesn't have to be imported anywhere for the queries to work.

It is designed in a way that you always have to import the file to access the endpoints.


> Where is it supposed to be imported?

In any other file that is being executed. JavaScript doesn't randomly execute every file on your harddrive. It goes through your code and follows it. If there is an `import` statement, it follows that and looks into that other file. If not, that file could just as well not exist.

**Comment by igorkoho** [comment]
> If there is an import statement, it follows that and looks into that other file. If not, that file could just as well not exist.

I think this was my misunderstanding. I thought that the listeners file having the `import` statement in it (to import `startAppListening` would be enough, but I guess it only works the other way -- when the file itself has some exported member in it, correct?

I think the confusion stemmed from this section in the organizing docs, where nothing is exported, but I suppose this is meant to be the file where the `listenerMiddleware` is exported from (and just omitted for brevity in the example)?

<img width="880" alt="image" src="https://user-images.githubusercontent.com/55111438/224499338-d5528dfa-790a-4e14-8d94-63cb2cf95d7a.png">

**Comment by phryneas** [comment]
You can always go `import 'app/listenerMiddleware'` without importing anything from it. 
But if you have no place in your code ever referencing that file, it could as well never exist.

**Comment by igorkoho** [comment]
Now I understand, thank you very much @phryneas and @markerikson !
