### ISSUE TITLE
Add  slice actions to reducer prop on Slice type

### ISSUE THREAD

**Issue by dorsett85** [reduxjs/redux-toolkit#325]
The return value of `createSlice` is a `Slice` type that has a reducer prop with the original State passed in to `Reducer`.

```typescript
export declare interface Slice<State = any, CaseReducers extends SliceCaseReducers<State> = SliceCaseReducers<State>> {
    /**
     * The slice name.
     */
    name: string;
    /**
     * The slice's reducer.
     */
    reducer: Reducer<State>;  // Why not Reducer<State, SliceAction>??
    /**
     * Action creators for the types of actions that are handled by the slice
     * reducer.
     */
    actions: CaseReducerActions<CaseReducers>;
    /**
     * The individual case reducer functions that were passed in the `reducers` parameter.
     * This enables reuse and testing if they were defined inline when calling `createSlice`.
     */
    caseReducers: SliceDefinedCaseReducers<CaseReducers>;
}
```

Can we have the second argument to `Reducer` passed in as well?  Otherwise this reducer (and any others pass into `configureStore` will mean `store.dispatch` will accept `AnyAction`.

**Comment by phryneas** [comment]
Every reducer does always accept any possible action. 
That's why every reducer has a default case that returns the original state. 
You can also always dispatch *every possible* action against your store, it just wouldn't do anything if no reducer would listen for it.

**Comment by dorsett85** [comment]
Here's a simplified example, but there would be the same error with `combineReducers` with each reducer type being defined with `State` and `Action` types (the store dispatch would then be a union type of all the possible actions, and error an action doesn't match).

Is there a way to recreate this with redux toolkit?  I think this would be the appropriate type checking since you would get instant feedback that your action isn't doing anything.

```typescript
import { Reducer, createStore, AnyAction } from 'redux';

interface InitAction {
    type: 'init',
    payload: boolean;
}

interface InitialState {
    init: boolean;
}

const initialState = {
    init: false
}

const reducer: Reducer<InitialState, InitAction> = (state = initialState, action: InitAction): InitialState => {
    if (action.type === 'init') {
        return { init: true };
    }
    return state;
}

const store = createStore(reducer);

store.dispatch({ type: 'init', payload: true });

store.dispatch({ type: 'bad'});
// Type '"bad"' is not assignable to type '"init"'
```

**Comment by markerikson** [comment]
I personally don't feel like there's a lot of useful value in trying to limit what actions can be passed to `dispatch`, but there do seem to be a number of people who feel like that's an important / necessary thing.

**Comment by phryneas** [comment]
If you want it to actually contain the `type` property in the `Action`, this is impossible.

Action types created with `createSlice` are concatenations of `slice.name` and the key of the the reducer.
As TypeScript cannot do string concatenation in types (so `type X = 'mySlice' + '/' + 'typeName';`) is impossible), we cannot define anything more accurate than `string` as the `type` of actions created with `createSlice`.

If you only want the actions, like `{ type: string; payload: Every | Possible | Payload }`, that's theoretically possible, but I'd say pretty pointless...?

And again: By doing what you suggest, you are lying to TypeScript, and that's not a good thing. The resulting `sliceReducer` will definitely be called by actions for other slices, so returning a `Reducer<State, OnlyThisSliceAction>` would be returning an incorrect type.

**Comment by dorsett85** [comment]
> If you only want the actions, like `{ type: string; payload: Every | Possible | Payload }`, that's theoretically possible, but I'd say pretty pointless...?

It wouldn't be all possible payloads in each action, it would be all possible actions (union type) as input for the dispatch function.

It seems the `Reducer` type in both `React` (with context api) and `redux` support this, but not the toolkit.  I don't think it would add a ton of value as Mark said, but would make it type safe if someone did happen to use an unsupported action type as an argument to the dispatch function.

**Comment by markerikson** [comment]
I think you're coming at it from the wrong direction.

The type-safety goal there isn't to prevent the "wrong" actions from being passed to the _reducer_.  It's to prevent the actions from being passed to `dispatch()`.

I think what you're actually looking for here is to combine all the possible action types, and then do something like:

```ts
export type AppDispatch = Dispatch<AllActionTypesCombined>;

// later, in a component:
import {AppDispatch} from "app/store";

// component
const dispatch: AppDispatch = useDispatch();
```

**Comment by dorsett85** [comment]
Yes exactly, sorry if I was unclear.

I have a custom hook: `const useAppDispatch = () => useDispatch<AllActionTypesCombined>();`

It's easy to have `AllActionTypesCombined` with context api and/or redux as it's part of my types already, but it would be nice to have access to `AllSliceActions` from the `Slice` type created by `createSlice`.

Something like:

```typescript
const someSlice = createSlice({ ... });

type SomeSliceActions = typeof someSlice.actions; // this is the action creators

type AllActionTypesCombined = SomeSliceActions | SomeOtherSliceActions | ...;
```

**Comment by phryneas** [comment]
Okay, above I meant
```ts
type SliceActions = { type: string; payload: Every } | { type: string; payload: Possible } | { type: string; payload: Payload };
```
for TS, that is essentially equivalent to what I wrote.

The point is: `type` will always be `string`, and it is not possible in TypeScript to infer that type.

With `type` always being string, this will possibly not be of any value for you.

**Comment by evertbouw** [comment]
I also have this problem. I think I'm going to use createReducer instead
```ts
const increment = createAction<number, "counter/increment">("counter/increment");
const decrement = createAction<number, "counter/decrement">("counter/decrement");

type IncrementAction = ReturnType<typeof increment>;
type DecrementAction = ReturnType<typeof decrement>;
type MyActions = IncrementAction | DecrementAction;

const counter = createReducer(0, {
  [increment.type]: (state, action: IncrementAction) => state + action.payload,
  [decrement.type]: (state, action: DecrementAction) => state - action.payload
});
```
Having to do `createAction` is a little more boilerplate but I don't really see a way around it

**Comment by dorsett85** [comment]
@phryneas, @markerikson and @evertbouw thank you for the responses.  Very happy to have something to reduce the redux complexity and looking forward to future updates.

**Comment by R-Bower** [comment]
> The point is: type will always be string, and it is not possible in TypeScript to infer or for us to validate/specify that type - as string literals cannot be concatenated on a type level

TypeScript version 4.1 brought [template literal types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html).  Does this change your answer from Jan 2020?

**Comment by phryneas** [comment]
@R-Bower we still support older TS versions, so from that perspective not really.

But even then: `AnyAction` is correct. A reducer *will* be called with any action, not only with the actions of that slice. So even if we can utilize TS 4.1 at some point to have `slice.actions` typed more accurately, we will not be changing the `Reducer` type.

Writing a test like
```
myReducer({ type: "thisDoesNotExist" }
```
is not only a valid call, but even something you should be doing if you are writing unit tests for action creators.

Granted, most bugs that can appear that way do not play a role if you use `createSlice`, but if you hand-write reducers, doing a `Reducer<State, SpecificActionType>` runs the risk of hiding bugs. That reducer *will* be called with other actions and it has to work correctly with them. Typing it like that in combination with TypeScript's type exhaustion might hide bugs in your application.
And even if you think you know all types: Middleware can dispatch actions of types you don't even know of internally, and the Redux INIT action has a random type string in development.

Generally, my take is: creating a union `Action` type is an antipattern. I have written a full [blog post](https://phryneas.de/redux-typescript-no-discriminating-union) on this.

**Comment by R-Bower** [comment]
@phryneas Thanks for the detailed reply.  I think your response is correct for a global redux store.  However, I'm also using redux toolkit for individual local state via useReducer hooks.  TypeScript type safety would be nice for these actions.  At any rate, @evertbouw proposed a solution that works for my use case.

**Comment by markerikson** [comment]
@R-Bower fwiw I don't see much benefit there either.

If you are using `createSlice`, it generates action creators for all the case reducers inside. Use those inside the component, and you know you're working with the actions the reducer can handle.  I've used `createSlice` + `useReducer` for that several times.
