### ISSUE TITLE
using debounce to change input

### ISSUE THREAD

**Issue by motionrus** [reduxjs/redux-toolkit#3250]
I store the state of the form in the reducer's . I would like to generate action not for every character, but by timeout. Is it possible to implement this in redux-toolkit? I couldn't find any examples in the documentation

For Example: https://usehooks-ts.com/react-hook/use-debounce
Thanks!

**Comment by phryneas** [comment]
You should debounce before dispatching, not after that - so in your component. Generally, we recommend against holding live form state in Redux. 
https://redux.js.org/style-guide/#avoid-putting-form-state-in-redux
