### ISSUE TITLE
More implicit typed slice-state

### ISSUE THREAD

**Issue by u-rogel** [reduxjs/redux-toolkit#3261]
First, thanks guys for the amazing work!

This one is more information for developers with a similar problem.

I have been using redux a lot and now trying to move to redux-toolkit. In a current project I wanted to write a general setter for my reducer, but came across a Typesctipt issue. Typescript complained that that it cannot ensure the setter would work because might be one of the `State` keys is not a string. Sure in JS it can be but I rarely came across such reducers state.

```.ts
interface State {
  isVisible: boolean
  title: string
}

const initialState: State = {
  isVisible: false,
  title: '',
}

const mySlice = createSlice({
  name: 'mySlice',
  initialState,
  reducers: {
    setMySlice: (state, action: PayloadAction<Partial<State>>) => {
      Object.keys(action.payload).forEach((key) => {
        state[key] = action.payload[key]
      })
    },
  },
})
```

In the end I added to my slice another type to enforce only strings as keys.

```.ts
interface ObjectWithStringKeys {
  [key: string]: any
}
```

And my new state type is:
```.ts
interface State extends ObjectWithStringKeys  {
  isVisible: boolean
  title: string
}
```

If anyone think it is of value I would gladly add it to the relevant docs part.

**Comment by markerikson** [comment]
FWIW, we normally recommend _against_ trying to write this kind of case reducer in the first place :)

- https://redux.js.org/style-guide/#reducers-should-own-the-state-shape
- https://redux.js.org/style-guide/#model-actions-as-events-not-setters

But if you _must_ write this sort of logic, there's some better ways to do it:

- You can do `Object.assign(state, action.payload)`
- You can do a check to ensure that `typeof key === "string"`
- You can do a check to see `if (key in state)`

etc
