### ISSUE TITLE
[RTK Query] Select by changed cache key in serializeQueryArgs

### ISSUE THREAD

**Issue by ghettojezuz** [reduxjs/redux-toolkit#3263]
Hi there!

Is there any way to select by changed cache key in serializeQueryArgs?

For example, I have createApi instance with endpoint that have many args (also there is a unique value `id` among them). I use `serializeQueryArgs` to make cache key looks like this unique `id`.
```typescript
export const someApi = createApi({
    reducerPath: 'someApi',
    baseQuery: axiosFetchBaseQuery({
        baseUrl: `${API_PREFIX}${someApiPath}`,
    }),
    endpoints: (build) => ({
        getInfo: build.query<GetInfoResponse, GetInfoArgs>({
            query: ({ id, arg1, arg2, arg3, ..., arg10 }) => ({
                path: services.someApi.getInfo.path,
                method: services.someApi.getInfo.method,
                data: { id, arg1, arg2, arg3, ..., arg10 },
            }),
            serializeQueryArgs: ({ queryArgs }) => queryArgs.id
        }),
    }),
});
```

Then I want to create selector to get state of endpoint from cache:

```typescript
export const getInfoStateSelector = (id: string) => 
createSelector(
    (state: RootState) => someApi.endpoints.getInfo.select(id)(state),
    (getInfoState) => getInfoState,
);
```

But I'm getting error because `select` expecting all args from GetInfoArgs. 

How to handle it? I will be grateful for any help!

**Comment by phryneas** [comment]
You can use pretty much everything that would result in your cacheKey, so on a runtime level it would be enough to call it with `{ id }` : `someApi.endpoints.getInfo.select({ id} )(state)`

You'll have to live with the fact that TS will complain about that, maybe add a `@ts-expect-error` annotation.

**Comment by ghettojezuz** [comment]
Well, I thought that I can avoid ts annotations, but ok, will deal with it :)
Thank you

**Comment by EskiMojo14** [comment]
alternatively you could just provide dummy data for any of the unused args - select({ id, arg1: '', arg2: 0 }) etc

**Comment by mahmudipur** [comment]
Hey guys,

I faced to similar issue but a little bit different, I have a query which receives filter and pagination as argument and I'm handling these two parameters in related slice and since I need these two argument as query string I wrote these code below:

```typescript
export const selectRevenueFilter = (state: RootState) => state.revenue.filter;

export const selectRevenuePagination = (state: RootState) =>
  state.revenue.pagination;

export const selectRevenueFilterAsQueryString = createSelector(
  selectRevenueFilter,
  (filter) => {
    return Object.entries(filter)
      .filter(([_, value]) => value !== undefined && value !== "")
      .map(
        ([key, value]) =>
          `${encodeURIComponent(`filter[${key}]`)}=${encodeURIComponent(value)}`
      )
      .join("&");
  }
);

export const selectRevenuePaginationAsQueryString = createSelector(
  selectRevenuePagination,
  (pagination) => {
    return Object.keys(pagination)
      .map(
        (key) =>
          `${encodeURIComponent(key)}=${encodeURIComponent(
            pagination[key as keyof typeof pagination]
          )}`
      )
      .join("&");
  }
);
```

now I'm going to select some data from the cache and hence I had the query string selector here I wrote another selector like this:

```typescript
export const selectedRevenueVendorFee = createSelector(
  selectRevenueFilterAsQueryString,
  selectRevenuePaginationAsQueryString,
  (state: RootState) => state,
  (filter, pagination, state) => {
    revenueApiSlice.endpoints.revenueList.select({filter, pagination})(state)
  }
);
```

but typescript yields at **state**.

it seems there is something wrong or maybe I chose a bad way to get access to the state could you please help me out with this code 🙏🏼
