### ISSUE TITLE
According to the documentation you don't recommend to use ApiProvider with Redux store why?

### ISSUE THREAD

**Issue by MaksZhukov** [reduxjs/redux-toolkit#3264]
Hey! According to the doc you don't recommend to use ApiProvider with Redux store together, but why exactly, where can be conflicts?
https://redux-toolkit.js.org/rtk-query/api/ApiProvider
![image](https://user-images.githubusercontent.com/23615115/224960113-4cb2bb41-c404-4216-9fa9-c073bdf57b80.png)

**Comment by EskiMojo14** [comment]
the ApiProvider creates its own redux store, and uses the default redux context provider. that means that if you already have a redux context provider set up, the innermost provider will override the context value provided by the outermost provider.
if you already use redux, you should add the reducer/middleware to your existing store - apiprovider is specifically for when you don't have an existing store.

**Comment by markerikson** [comment]
Yep. The _only_ time to use `<ApiProvider>` is in the exceedingly rare case when you don't already have  a Redux store in the app, and want to use RTK Query anyway.

Any other time, you should just configure the existing Redux store with the RTK Query pieces, and pass it down via `<Provider>` as usual.
