### ISSUE TITLE
Reducer action generic type: "Expected 0 type arguments, but got 1. ts(2558)"

### ISSUE THREAD

**Issue by julian-kingman-lark** [reduxjs/redux-toolkit#3271]
I'm trying to add a generic type to an action, and it does _actually_ work, as I can see the type of the payload is correctly inferred. However, I get a type error that says `Expected 0 type arguments, but got 1. ts(2558)`. I'm unclear whether I'm doing something wrong here (I don't think so?) or if this is a TS bug.

Thanks!

<img width="760" alt="Screenshot 2023-03-15 at 6 35 18 PM" src="https://user-images.githubusercontent.com/115734387/225467011-e1f2b6c5-7332-4c43-b9f8-ff971f8d8c8f.png">
<img width="444" alt="Screenshot 2023-03-15 at 6 33 27 PM" src="https://user-images.githubusercontent.com/115734387/225466807-ee974c7e-197d-4b75-a39a-4c008e0ffc45.png">

`@reduxjs/toolkit` version 1.9.1

**Comment by markerikson** [comment]
I'm pretty sure this is a TS problem, in that it's unable to carry the generic through all the layers somehow.

**Comment by phryneas** [comment]
TypeScript cannot map from one generic function to a new one - when we transform from the shape `(state, action) => state`  to `(payload) => action`, the generic gets lost.

What you are trying to do is not possible with nowaday's TypeScript.

**Comment by julian-kingman-lark** [comment]
Ah sad, thank you for the insight, I'll find another way!

**Comment by julian-kingman-lark** [comment]
Is there a way to type an action that yields a similar result?

**Comment by EskiMojo14** [comment]
it's not pretty, but i've used [type assertions](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQZQDbDJoA0cAChgJ54QYAmAgsjMBAHZwC+cAZlBCDgAiAALo6AVwAeAKwDOAehgQIeANbAYQgNwAoUJFiI4AIQxy0TFuwDC6LNC69+g0eOnylK9ZoV1gcjAKqJjYVqxsQrq6MJRgaHA4MFgJALyIunBZcIFQAFw5MFDAbADmetlwbBIgBdUgAEZoUHqc0cjsgTkERHDpISn4hGgAFAiZ2WwYIGgFAORyPWhzxBNZJZrAGHhJKQXjlZW58ytrh-UFAAxn3OaJydirle5EUHL7Z0doMABq2wUAHgA0nA0FJsGw6HI4Go0JQIDx7ikAHwjQJ7JGPYxgKg0ehcAoUai0RjMCIApCwygFIHaOAAN22ElmmLQAG0gQBdLjIgCUfWRGUOwsKKTZOOJ9AAdFTuekJXi6FLGXhmRURW1Km1OLz2p14EgLL9tk50othlKMGTOnoFAphQA9AD80SNfzwYxhcPmuRWDKZLMuXF1dqqEHgpTQbGahDgeRG0RK2CgPCtCRw33dzNB4KjUNM5ks1rYdlC0ApZypBSpCNZ6qyKuZBV22DZNcRLbQnNapCE5qICjd2yEgoO2WBOYh+fbrNRCpJ+y91LgtP9qpZnY53J1hNxJPC7ApS5pdMbG4e7K5PN0bV0HTYXStMAk2wzxvXfRymZNdzfWbQ0RPi+OzfuunpVnACxFH6Z5XMGQA) in the past. 
in general though it's worth considering if you definitely need generics to get the behaviour you want.

(disclaimer for possible future readers: the setVal example in the above playground is [**very bad**](https://redux.js.org/style-guide/#model-actions-as-events-not-setters). it's just an easy example of a reducer that would need generics)
