### ISSUE TITLE
Master/details where details updates it's own state

### ISSUE THREAD

**Issue by data-handler** [reduxjs/redux-toolkit#3273]
I'm sure there must be a very simple solution to this problem but I cannot seem to find one, or work out how to achieve it.

I have a master/details view:

a table of items where each item is a 'master'
a tab list where each tab displays additional details related to the currently selected item

Each tab needs to load it's data independently, in response to an item being selected or when the tab itself is selected
Each tab's data is retrieved from an async api call

I've created an 'itemsSlice' that handles loading the items (via an async thunk) and includes an 'itemSelected' reducer.

I dispatch the 'itemSelected' action when an item is selected (by clicking it)

I've created slices for each tab, but I don't know how to make a tab slice update it's data (by fetching it from an api) in response to an item being selected.

Initially, I thought I could add an extra reducer to each tab slice to handle 'itemSelected' actions and update it's data, but a reducer is not supposed to have side effects / call async api's, etc.

How best can I achieve this?

**Comment by data-handler** [comment]
So I've tried using createListenerMiddleware, and that works. I don't know if that's the best approach in this situation.

**Comment by markerikson** [comment]
"A slice for each tab" is generally not the right approach.  It would be better to have a single slice that has a "normalized" state, with a lookup table of tabs by ID:

- https://redux-toolkit.js.org/api/createEntityAdapter

Then, use RTK Query to handle the data fetching for that item:

- https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics

**Comment by data-handler** [comment]
Most tabs have their own tabular data to display and allow the user to add / update / delete items. There are 10 tabs. WOuld you still use a single slice in this case?
