### ISSUE TITLE
How do I get the response header information in an RTK Query

### ISSUE THREAD

**Issue by Jinxishihenian** [reduxjs/redux-toolkit#3275]

**Comment by phryneas** [comment]
https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#customizing-query-responses-with-transformresponse
![image](https://user-images.githubusercontent.com/4282439/225844663-90f0ae73-3c2e-4efc-a96d-28e8944f17a4.png)
(Sorry, but such a short question doesn't get many words as answer)

**Comment by Jinxishihenian** [comment]
Thank you very much for your reply. I have solved the problem through the method you provided.  Through this method I get the response header information. 
```
 transformResponse: (responseData: any, meta, ha: any) => {
               // Output 1（ Response header  X-Pagination-Current-Page: 1）
                console.log(meta?.response?.headers.get('X-Pagination-Current-Page'))
                return responseData;
            },
```
