### ISSUE TITLE
Can't get cookie to axiosbaseQuery/fetchBaseQuery when using RTK Query during SSR

### ISSUE THREAD

**Issue by browyn** [reduxjs/redux-toolkit#3278]
I'm building a fullstack app using next and Laravel.

At the moment, I am successfully using RTK query in getSeverSideProps to access laravel API routes, however, when I try to access a protected API route in getSeverSideProps, it never works, but the hook call always go on the client side.

Laravel sanctum authentication requires a **Cookie Header** and a **X-XSRF-TOKEN** header to work properly, and none of this is being set and sent whenever I initiate a query inside of getServerSideProps, which then prevents me from accessing protected API routes.

Please is there any possible way to go about this.

I had to try something unsafe (setting the Cookie Header explicitly using getCookies function from cookies-next), it still didn't work.

Please, I would really appreciate help on this, I have been on this for days. 😔

**Comment by phryneas** [comment]
Thanks for opening a new issue.

Getting the cookie **on the server** is a completely different thing as doing it on the client, because it needs to be scoped to the current request. Axios won't help (or hinder) you there, you will have to get those values by hand.

I am not sure how the `getCookies` function of `cookies-next` is unsafe. Without knowing the package, from the name it sounds as if it is exactly made for that?

**Comment by browyn** [comment]
The `cookies-next` package works just fine in retrieving the cookie, however, when I try to explicitly set the Cookie header of axiosBaseQuery or fetchBaseQuery, I get the following error **Refused to set unsafe header, Cookie**.

But I noticed that if I should just call plain axios inside of getServerSideProps and set the Cookie header, it works just fine without the error, but doing that with fetchBaseQuery or axiosBaseQuery throws the error.

**Comment by phryneas** [comment]
You are creating a new Redux store for every request here, and not keeping the same store around for all requests, right?

Meaning: are you using next-redux-wrapper?

**Comment by browyn** [comment]
Yes, I am using next-redux-wrapper, that's the one of the simplest way I have seen to use rtkquery during SSR.

However, just this morning I found a fix (don't know if it is the right way).

I was able to get the cookie from the context as I said earlier, but when I set the Cookie header and call a request on the client side, I get the error "Refused to set unsafe header".

So what I did was to set the Cookie header and the Origin header conditionally by using `typeof window === "undefined"`

So far it works, but it doesn't look right or I am just overthinking it. Either way, I would really appreciate a better workaround.

**Comment by phryneas** [comment]
Tbh., you are working with two very different environments here, so working conditionally per environment seems perfectly fine.

**Comment by browyn** [comment]
Alright @phryneas thanks.
If it's okay to drop a code or link to a commit that fixes the issue for future references, please do let me know so I can do that for those who may be finding it difficult too.

Once I do that, I'll close the issue.

**Comment by phryneas** [comment]
I guess you can put a bit of code into this issue, but generally you are very edge-casey here.

**Comment by browyn** [comment]
I am trying to get the user of my application by making a request to an endpoint inside of the Apps getinitialprops instead of trying to running it on every page getServerSideProps, so that no matter the entry point of the user tries to use to get into the application, his details would be available immediately.

I was able to do this per page inside of getServerSideProps as the current context was passed to the redux store and I was able to get the cookies in need to make the request, however trying to do this now with App.getInitialPropss doesn't work because the current context isn't passed along and I can't access the cookie.
I saw an answer you gave to someone on stackoverflow about wrapping the App component under another component in order to access the current store/context, but I don't seem to understand how to go about that.

Here's my current App.js

```
const App = ({ Component, ...rest }) => {
  const { store, props } = wrapper.useWrappedStore(rest);
  const { pageProps } = props;

  return (
    <>
      <Provider store={store}>
        <Component {...pageProps} />   
      </Provider>
    </>
  );
};

export default App;

MyApp.getInitialProps = wrapper.getInitialAppProps(
  (store) =>
    async ({ ctx, Component }) => {
      return await authMiddleware(store, {
        getProps: async (user) => {
          console.log(user);
        },
      });
    }
);
``` 

And here is my redux store

```
export const makeStore = (context) => {
  return configureStore({
    reducer: {
      [api.reducerPath]: api.reducer,
    },
    middleware: (gdm) =>
      gdm({
        serializableCheck: false,
        thunk: {
          extraArgument: {
            cookies: context?.req,
          },
        },
      }).concat(api.middleware),
  });
};

export const wrapper = createWrapper(makeStore, { debug: false });
```

**Comment by phryneas** [comment]
You go from 
```js
function App() {
  // redux initialization
// app contents
}
```
to
```js
function App() {
  // redux initialization
  return <Provider store={...}><InnerApp /></Provider>
}

function InnerApp() {
// app contents
}
```

**Comment by browyn** [comment]
Currently, this is what I have..

```
const App = ({ Component, ...rest }) => {
  const { store, props } = wrapper.useWrappedStore(rest);
  const { pageProps } = props;

  return (
    <>
      <Provider store={store}>
        <InnerApp Component={Component} pageProps={pageProps} />
      </Provider>
    </>
  );
};

const InnerApp = ({ Component, pageProps }) => {
  return (
    <>
      <ScrollToTop />
      <ThemeProvider theme={theme}>
        <Toaster />
        <NextNProgress color={color()} />
        <GlobalStyles />
        <IconContext.Provider value={{ size: "24px" }}>
          {Component.getLayout ? (
            Component.getLayout(<Component {...pageProps} />)
          ) : (
            <SiteLayout>
              <Component {...pageProps} />
            </SiteLayout>
          )}
        </IconContext.Provider>
      </ThemeProvider>
    </>
  );
};

export default App;
```

I'm to call the `getInitialProps` on the **App** right?

**Comment by phryneas** [comment]
Ah... on second thought, `getInitialProps` is actually a problem here. I don't think that's possible with the new way `redux-next-wrapper` does things.

**Comment by browyn** [comment]
Oh.. alright no worries, thanks.
I'll ask about that

**Comment by browyn** [comment]
Hey @phryneas I got it to work, I realized that the **context** being passed in `getServerSideProps` contains the {res, req} directly, which means that you can access the request as follows **`context.req`** however, the context of `getInitialProps` doesn't, and you have to access the request or response as follows **`context.ctx.req and context.ctx.res`**. When I discovered that, I had to do a conditional check to pass in the correct `req` to the thunk's extra

Here it is 

```
 thunk: {
     extraArgument: {
        cookies: context.req || context.ctx?.req,
     },
 }
```

So now it works :)
