### ISSUE TITLE
Add the ability to ignore non serializability for some "class"

### ISSUE THREAD

**Issue by vjau** [reduxjs/redux-toolkit#328]
I would like `serializable-state-invariant-middleware` to allow for customizing the serializability checking.
Use case for me is Meteor, which is including a `EJSON` feature https://docs.meteor.com/api/ejson.html which allows by default to serialize Date and Uint8Array but also to create your own data types.

If you agree to this, a possible implementation would be to offer the user to provide in configuration his own checking method which would be run in addition to the actual one. Another way (perhaps less dangerous) would be to allow the user to provide a list of whitelisted object "templates"

```js
const customizedMiddleware = getDefaultMiddleware({
    serializableCheck: {
      whiteListedObjects : [new Date()]
   }
})
```

**Comment by markerikson** [comment]
We already do exactly that.  You can supply an `isSerializable` method yourself in the options:

https://redux-toolkit.js.org/api/other-exports#createserializablestateinvariantmiddleware

Those options are also exposed via `getDefaultMiddleware()`:

https://redux-toolkit.js.org/api/getDefaultMiddleware#customizing-the-included-middleware
