### ISSUE TITLE
Is there query hook to only subscribe to data in the cache and trigger a re-fetch

### ISSUE THREAD

**Issue by browyn** [reduxjs/redux-toolkit#3282]
I am loading user's data from the `getInitialProps` of the `_app.js` in a next app.
Which I believe gives the app the flexibility and ease of bootstrapping the user no matter the route used by the user to get into the application.

Of course, I still make use of the hook(useQuery) to subscribe to the cached data if fetched successfully from `getInitialProps`... 
However, there's a tiny problem, this approach is only so perfect assuming the user is already authenticated, and since the **useQuery** hook will fetch data if when there's no data in the cache,  an error will be logged to the console when a component (like the public area **Header** component) makes use of the **useQuery** hook to try and read the user's data (to show a sign in button or profile image) since that endpoint is only supposed to be accessed when authenticated.

So I was thinking if there's a hook or a way to only subscribe to cached / no cached data and a re-fetched data when a mutation occurs and leave the initial fetching for the server in the `getInitialProps` function.

Also after successfully, fetching data from the `getInitialProps`, I assumed that data already exists in the cache and will be able to read this data if I set **skip** to _true_ when calling the **useQuery** hook, however this wasn't the case

**Comment by phryneas** [comment]
If you don't want to trigger a query, you can use `api.endpoints.myEndpoint.useQueryState`

But that will not create a "subscription" to the data, so it will be cache-collected after your `keepUnusedDataFor` time runs out.

As for `skip` and `true`, that will keep the data in the component if the hook had already fetched it and you turn `skip` on, but will not give you cache data if the component never requested it.

**Comment by browyn** [comment]
Alright thanks, but I need the component to subscribe to the cached data also.

So I was thinking of using both the `useLazyQuerySubscription` hook to subscribe to the cached data and use the `useQueryState` hook to get the cached data on the same component.

Since Lazy query will only trigger if I call it. (which I won't be doing)

However, I want to know if using this two hooks will cause the cached data to update when a mutation occurs
