### ISSUE TITLE
$ref schemas result in unknown type

### ISSUE THREAD

**Issue by Void0Walker** [reduxjs/redux-toolkit#3286]
We have encountered an issue with valid swagger files containing refs like this produce response type of `unknown`. 

```yaml
 responses:
        "200":
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/ProductProjections'
          description: Current projections for the requested product.
```

Looks like explicit definitions of object properties (meaning we don't reference) in every schema mitigates this, but it isn't a good solution.

**Comment by iliapnmrv** [comment]
hey! any updates on this?

**Comment by markerikson** [comment]
This is probably a problem with the underlying https://github.com/oazapfts/oazapfts library - could you file an issue over there with a repro? Thanks!
