### ISSUE TITLE
Cache tags: single vs plural?

### ISSUE THREAD

**Issue by dvislov** [reduxjs/redux-toolkit#3288]
I see in the documentation both using plural and singular for cache tags:
```
providesTags: (result, error, arg) =>
        result
          ? [...result.map(({ id }) => ({ type: 'Post' as const, id })), 'Post']
          : ['Post'],
```
or
```
providesTags: (result) =>
        result
          ? [
              ...result.map(({ id }) => ({ type: 'Posts' as const, id })),
              { type: 'Posts', id: 'LIST' },
            ]
          : [{ type: 'Posts', id: 'LIST' }],
```

Is there any difference between them? (Posts vs Post). 
I understand that from the point of view of programming, these are strings.
But maybe one of the variants is preferable?

**Comment by phryneas** [comment]
It totally depends on your personal preference. You can also write them uppercase, lowercase or backwards ;)
