### ISSUE TITLE
install redux toolkit

### ISSUE THREAD

**Issue by pierrybos** [reduxjs/redux-toolkit#3289]
Hi, i cant make anything to add reduxjs/toolkit in my existing project.

i tryed: 
`npm install @reduxjs/tooklit`
`yarn add @reduxjs/tooklit`
`npx expo install @reduxjs/tooklit`

`
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/reduxjs/toolkit.git
Directory: /home/pierry/TRF4/tests/app/eprocApp
Output:
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

its only with me, my connection?

**Comment by markerikson** [comment]
You definitely shouldn't be running `npx expo install @reduxjs/toolkit`.  That looks like it'll try to create a new _project_ using a Github repo as a template.

Your first two commands look like they have a typo - `tooklit`, when it should be `toolkit`.

So yes, normally `npm install @reduxjs/toolkit` or `yarn add @reduxjs/toolkit` should be what you need.
