### ISSUE TITLE
RTK Query how to optionally save data to Redux?

### ISSUE THREAD

**Issue by rajikaimal** [reduxjs/redux-toolkit#3290]
I have classified data in React components into the following categories,

1. Display only data (which is not essential to be stored in Redux) but fetched from an API
2. Shared data (shared between multiple components) suitable to be stored in Redux

I believe RTK Query is perfect for use case 2, however, is it possible to optionally save data in the Redux store with RTK Query for the use case 1?

If it's not possible, what is the solution recommended by RTK to fetch display-only data?

Possible solutions,
1. Use another data fetching library such as `useSWR` for display-only data fetching and use RTK Query for shared data
2. Just use RTK Query for everything?

**Comment by phryneas** [comment]
1. is a subset of 2. - it is perfectly fine to use RTK Query to get data that is only displayed in one component.

**Comment by rajikaimal** [comment]
@phryneas Thanks for the answer, do you think it will affect performance when an application gets scaled eventually?
If not could you please elaborate on why? 🙇‍♂️

**Comment by phryneas** [comment]
I don't think so. 
It's just a variable, that data will take the same amount of memory whether you have it in a local component, Redux, or SWR (which would just mean putting it into a global store again).

Also that data doesn't stay around forever - it will by default be removed from the cache 60 seconds after the last component using it will unmount.


Apart from that, to say this very clear: I assume that 95% of all RTK Query usages are only used in one component. This is not an edge case. It's a perfectly normal usage scenario.

**Comment by rajikaimal** [comment]
Thanks for the answer 🙏
