### ISSUE TITLE
fetchBaseQuery don't send body in POST after first request

### ISSUE THREAD

**Issue by noveogroup-amorgunov** [reduxjs/redux-toolkit#3291]
Hello! I have a problem, when try to send second request using `fetchBaseQuery`. Body is not sent with request.

My code is similar with https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#preventing-multiple-unauthorized-errors and my second request is query to refresh access token. But if i want pass body, its not pass with request:

```ts
export const baseQuery =
  fetchBaseQuery({
    baseUrl: '...', 
    prepareHeaders: (headers, { getState }) => headers,
  })

export async function baseQueryWithReauth(args, api, extraOptions) {
  await mutex.waitForUnlock()

  let result = await baseQuery(args, api, extraOptions) // this all works fine, body is sended

  if (isTokenExpired(result)) {
    if (mutex.isLocked()) {
      await mutex.waitForUnlock()
      result = await baseQuery(args, api, extraOptions)
    } else {
      const release = await mutex.acquire()

      await baseQuery({
        method: 'POST',
        url: '/refresh',
        body: { foo: 'bar' }
        // ^^^^^^^^^^^^^^^
        // this body don't send with request
      }, api, extraOptions)

     // .....
    }
  }
}
```

<img width="717" alt="Снимок экрана 2023-03-24 в 10 45 46" src="https://user-images.githubusercontent.com/21186268/227457423-117d2310-fa03-4d76-8ffb-02fd396e85c1.png">

Do you have any ideas how to fix it?

**Comment by phryneas** [comment]
That should work like that. Have you ruled out things like CORS here?

**Comment by noveogroup-amorgunov** [comment]
My bad, payload is sent, but don't display in devtools. I close issue, anyway thx for fast response
