### ISSUE TITLE
Problem with types on createAsyncThunk

### ISSUE THREAD

**Issue by rossicler-hostalky** [reduxjs/redux-toolkit#3300]
Hey, I've been trying to solve an issue with redux-toolkit action createAsyncThunk related to types. Below I'll put sample of the code and the errors I am getting.

## auth.action.ts
```
interface LoginPayload {
  username: string;
  password: string;
}

export const login = createAsyncThunk<
  string,
  LoginPayload,
  { rejectValue: string }
>(
  "auth/login",
  async (loginPayload: LoginPayload, { dispatch, rejectWithValue }) => {
    try {
      ...
      return token; // token is type string
    } catch (err) {
      return rejectWithValue("error!");
    }
  }
);
```

## Login.tsx
```
import { login } from "@reduxStore/auth/auth.action";
...

const Login = () => {
    const dispatch = useAppDispatch();
    
    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();

        if (username && password) {
          dispatch(login({ username, password })); // this gives me this error TS2554: Expected 0 arguments, but got 1.
        }
     };

...
}
```

## Errors
Besides the error on Login.tsx, I'm also getting this error from auth.action.ts:
```
TS2339: Property 'username' does not exist on type 'void'.
TS2339: Property 'password' does not exist on type 'void'.
```

**Comment by phryneas** [comment]
Are you perchance using WebStorm?

**Comment by rossicler-hostalky** [comment]
No, I'm not using WebStorm. If it's helpful the project is using electron + react with webpack as a bundler. If you need any more information about it, let me know

**Comment by phryneas** [comment]
Hmm, that is weird - it should certainly work [as you can see in this TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMZQKYEMaoIIGcCeAdkgCoAWAroQNYC+cAZlBCHAOQACaAJhQB4ArXAHoYECABtqwGGwBQc4ISxQG6JKjgAZCAHMlABXT4JEdN0Ry4cCrlRRC6EKgBccXDChLdAbitwwdFxcAHdobjcPL0JfOVoFVD5IWDgkCEIPOFN9QjgAXlS0TBwCYnIqagAefyjvABp-HRyjEzNuBusEODQBVCQYADV0CQpXd09vOHiAPgAKfwAidAoYMmFspQWOuCCiJDhZjcIW03M3JsNjU-bEOG5gXECYJDI67tRe-oB1GTIhkc0tAAlPlppZrNZPPhwRDrGkMvAxNRULkCgssB4Fv5YWgYBQHHAkSi-LD6EhMC8DvYoCCENiIbj8bken0YD9Vv9RrMFtToABCBZAkkQ+LWeJChRHWZdWz2RzONwLBjiLYBIKhcKKgBG6CgCymQKAA).

Do you maybe not have `strict: true` in your `tsconfig.json`? That sometimes causes problems.

**Comment by rossicler-hostalky** [comment]
I do have strict: true.

Here is my tsconfig
```
{
  "compilerOptions": {
    "target": "es2019",
    "moduleResolution": "node",
    "module": "esnext",
    "esModuleInterop": true,
    "resolveJsonModule": true,

    "jsx": "react",
    "sourceMap": true,
    "baseUrl": ".",
    "paths": {
      "@graphql/*": ["src/graphql/*"],
      "@reduxStore/*": ["./src/app-store/*"],
      "@pages/*": ["./src/pages/*"],
      "@realmDb/*": ["./src/realm-db/*"]
    },

    "strict": true,
    "noUnusedLocals": true,
    "noImplicitAny": true,
    "downlevelIteration": true,
    "skipLibCheck": true,

    "typeRoots": ["node_modules/@types"]
  },
  "include": ["src/**/*.ts", "src/**/*.tsx"],
  "exclude": ["node_modules", "build", "dist"]
}
```

**Comment by rossicler-hostalky** [comment]
I completely changed my project setup to use [electron-react-boilerplate](https://electron-react-boilerplate.js.org/) and it is working as expected now.
