### ISSUE TITLE
No support for cancel previous api request in case of continuous api calls

### ISSUE THREAD

**Issue by jaydeep075** [reduxjs/redux-toolkit#3306]
I am trying to implement a search bar which calls an get api on every character typed on it , i see an issue that there is no method through which we can cancel previous api call , like in axios we have this cancel token functionality which help in cancel previous request..

For eg. I have entered `t` , `e` , `x` , `t`, then api calls going in all four characters entered, i want to cancel first 3 api calls if i have want to get results on text input

**Comment by menasheh** [comment]
Server won't cancel the requests even if you ignore the response. Try using debounce.
