### ISSUE TITLE
Use websocket to update RTK Query data in SSR Next.js app

### ISSUE THREAD

**Issue by haapti** [reduxjs/redux-toolkit#3307]
### Setup

I have a list of radio stations. Im using Next.js ISR rendering method to SSR the page. RTK Query and Next.js app is configured using this https://github.com/phryneas/ssr-experiments/tree/main/nextjs-blog as an example and following this https://redux-toolkit.js.org/rtk-query/usage/server-side-rendering documentation. Overall everything works as expected and no problems having RTK Query and SSR in Next.js app!

### Challenge

Each radio station in a list is displaying now playing artist and song. When the page is SSR and cached the data will be stale. I dont even want to include _live_ (now playing artist and song) data in SSR RTK Query state. I could make RTK Query update the stale state on client after hydration but that would be a lot of polling, in every 30-60 secs since now playing is updating very frequently.   I would like to use websocket for adding and updating the live data in state right after the Next.js app hydrates on client.

#### SSR radio station item in array

```js
{
  stationId: 123,
  stationName: "Best 80s",
  stationNowPlaying: {
    nowPlayingTrack: null,
    nowPlayingArtist: null
  };
}
```
#### Websocket data

Each radio station subscribes its own websocket channel like `station_123` in order to receive live data updates

```js
{
  stationNowPlaying: {
    nowPlayingTrack: "Never Gonna Give You Up",
    nowPlayingArtist: "Rick Astley"
  };
}
```
#### 1. Streaming Updates and onCacheEntryAdded

https://redux-toolkit.js.org/rtk-query/usage/streaming-updates
https://redux-toolkit.js.org/rtk-query/usage/streaming-updates#websocket-chat-api

**Problem:** When using SSR `onCacheEntryAdded` wont trigger on client. This method works fine if you fetch the data on client side or fetch more items in paginated list.

On this example i just added `console.log` to see what happens.

```ts
export const stationsApi = createApi({
    baseQuery: fetchBaseQuery({
      baseUrl: "https://stations.api/"
    }),
    extractRehydrationInfo(action, { reducerPath }) {
      if (action.type === HYDRATE) {
        return action.payload[reducerPath];
      }
    },
    tagTypes: [],
    endpoints: (builder) => ({
        getStations: builder.query<Stations[], number>({
            query: (page) => `stations?_pp=10&_p=${page || 1}`,
            serializeQueryArgs: ({ endpointName }) => {
                return endpointName;
            },
            merge: (currentCacheData, responseData) => {
                currentCacheData.push(responseData)
            },
            forceRefetch({ currentArg, previousArg }) {
                return currentArg !== previousArg;
            },
        }),
        getStation: builder.query<Station, number>({
            query: (id) => `station?stationId=${id}`,
            onCacheEntryAdded: async (
            _arg,
            { cacheDataLoaded, cacheEntryRemoved }
            ) => {
                console.log("onCacheEntryAdded");
                await cacheDataLoaded;
                console.log("onCacheEntryAdded_LOADED");
                await cacheEntryRemoved;
                console.log("onCacheEntryAdded_REMOVED");
            },
        }),
    }),
  });
```
#### 2. Listening subscriptions with createListenerMiddleware

https://redux-toolkit.js.org/api/createListenerMiddleware

Listening subscriptions in `stationsApi.internalActions.subscriptionsUpdated` seems most promising solution for opening and closing websocket channels. This works also for SSR RTK Query state and when any of components are not anymore using the data in state, subscriptions are removed.

```ts
// Create the middleware instance and methods
const listenerMiddleware = createListenerMiddleware();

// Add one or more listener entries that look for specific actions.
// They may contain any sync or async logic, similar to thunks.
listenerMiddleware.startListening({
  actionCreator: stationsApi.internalActions.subscriptionsUpdated,
  effect: async (action, listenerApi) => {
    console.log(action, listenerApi);
  },
});

export const makeStore = () =>
  configureStore({
    reducer: {
      [stationsApi.reducerPath]: stationsApi.reducer,
    },
    middleware: (gDM) => {
      return gDM().concat([
        stationsApi.middleware,
        listenerMiddleware.middleware,
      ]);
    },
  });
```
![Näyttökuva 2023-3-29 kello 11 04 44](https://user-images.githubusercontent.com/9010889/228467813-15d50db6-f7f0-41c1-bdda-f7e1ec6a2c1b.png)

### Is it possible implement websocket with listener middlewares?

How i can open and close a websocket channel for each `getStation` subscription by `stationId` when subscriptions are updated? This is something what i have not figured out yet. For example; how i can get and update the state for active subscriptions?

**Comment by markerikson** [comment]
Belated response: appreciate the effort that went into writing this, but this feels like a usage question and is best asked over in the Reactiflux Discord.
