### ISSUE TITLE
How change isFetching value to onlfy if i refetch with same parameters

### ISSUE THREAD

**Issue by frannale** [reduxjs/redux-toolkit#3312]
Hi! Im working in react native with a pull to refresh, this refresh is asociated to isFetching value of a lazyQuery. 
The problem is when i change the parameter and re-execute the lazy query with a diferent parameter, isFetching changes to true.
I only want isFetching true when the user does a pull to refresh with same parameters.
 Y try with onQueryStarted but is not working.
Anyone have a possible solution fot this? Thanks

"@reduxjs/toolkit": "1.9.2"

```  const [
    getMatches,
    { data: matches, isLoading: isLoadingMatches, isFetching },
  ] = useLazyGetMatchesByWeekQuery();

 <RefreshControl
              isFetching={isFetching}
              onRefresh={refreshData}
 />

**Comment by phryneas** [comment]
There's no way to get the `useQuery` hook to do that, you'll have to apply some manual logic there, save the last parameters and keep a manual loading state or something.

**Comment by phryneas** [comment]
No, I don't think so, sorry.
