### ISSUE TITLE
RTKQ: can't automatically refresh data after mutation request

### ISSUE THREAD

**Issue by Reg93** [reduxjs/redux-toolkit#3319]
Hello! Thank you for your work!

I didn't find something similar in issues. I can configure data update after mutation. Function deleteStage has to delete stage and then i have to see new list of stages.

Page code:

![photo_2023-04-03_15-37-16](https://user-images.githubusercontent.com/94961770/229463457-298ee775-49fe-4495-a9da-aa14f83a9a73.jpg)

Basic api:

![photo_2023-04-03_15-37-21](https://user-images.githubusercontent.com/94961770/229464357-fd4778ad-7ae3-4788-aa71-543bb9f9814f.jpg)

Endpointes:

![photo_2023-04-03_15-37-19](https://user-images.githubusercontent.com/94961770/229464461-021e27ba-a1e4-43a9-b656-ae7d4e9e5d60.jpg)

How can i fix it?

**Comment by phryneas** [comment]
You cannot put functions inside the array returned by `invalidatesTags`. That's just a thing that doesn't exist and is documented nowhere. (Out of the blue: did ChatGPT make that up? We see lots of those "invented APIs" recently.)

You can read up the correct notation [here in the tutorial](https://redux.js.org/tutorials/essentials/part-8-rtk-query-advanced#invalidating-specific-items).

Since you only shared screenshots, there is no way for me to copy-paste and fix up your code, so I can't give you an example.

**Comment by Reg93** [comment]
> You cannot put functions inside the array returned by `invalidatesTags`. That's just a thing that doesn't exist and is documented nowhere. (Out of the blue: did ChatGPT make that up? We see lots of those "invented APIs" recently.)
> 
> You can read up the correct notation [here in the tutorial](https://redux.js.org/tutorials/essentials/part-8-rtk-query-advanced#invalidating-specific-items).
> 
> Since you only shared screenshots, there is no way for me to copy-paste and fix up your code, so I can't give you an example.

Yes, first i used documentation and programmer experience, but it didn't help. BUt i just understood what i did wrong.

**Comment by Reg93** [comment]
> You cannot put functions inside the array returned by `invalidatesTags`. That's just a thing that doesn't exist and is documented nowhere. (Out of the blue: did ChatGPT make that up? We see lots of those "invented APIs" recently.)
> 
> You can read up the correct notation [here in the tutorial](https://redux.js.org/tutorials/essentials/part-8-rtk-query-advanced#invalidating-specific-items).
> 
> Since you only shared screenshots, there is no way for me to copy-paste and fix up your code, so I can't give you an example.

Yes, first i used documentation and programmer experience, but it didn't help and i use bot. But i just understood what i did wrong.
Data which i get from server is object, not an array. And in the begining i wrote code wrong and that's why i didn't get error.

Now i wrote again as documentation tells and i got error that result is not iterable.

Thank you!

**Comment by phryneas** [comment]
Please share the code that you have tried. I cannot reach through the internet and just look at your computer to see what's wrong.

And **please** share code, not screenshots!

**Comment by Reg93** [comment]
> 

This is what i have now:

`import { apiSlice } from "../apiSlice";

export const tournamentApi = apiSlice.injectEndpoints({
  reducerPath: "tournamentApi",
  tagTypes: ["Tournament"],
  endpoints: (build) => ({
    getTournament: build.query({
      query: (id) => `tournament/${id}`,
      providesTags: (result) => result
      ? [
          ...result.map(({ id }) => ({ type: "Tournament", id })),
          { type: "Tournament", id: "LIST" },
        ]
      : [{ type: "Tournament", id: "LIST" }],
    }),
    removeTournament: build.mutation({
      query: id => ({
        url: `tournament/${id}`,
        method: "DELETE"
      }),
      invalidatesTags: [{ type: "Tournament", id: "LIST" }]
    }),
    addStage: build.mutation({
      query: (id, body) =>
      ({
        url: `tournament/${id}/stage`,
        method: "POST",
        body
      }),
      invalidatesTags: [{ type: "Tournament", id: "LIST" }]
    }),
    removeStage: build.mutation({
      query: ({id, stageId}) =>
      ({
        url: `tournament/${id}/stage/${stageId}`,
        method: "DELETE"
      }),
      invalidatesTags: [{ type: "Tournament", id: "LIST" }]
    })
  })
})

export const {
  useRemoveTournamentMutation,
  useGetTournamentQuery,
  useAddStageMutation,
  useRemoveStageMutation
} = tournamentApi;`

**Comment by phryneas** [comment]
I would assume that the result from your api is not an array, so you cannot map over it?
Assuming you get the error in line `...result.map` - and me partially inferring what the error message you have might be. Maybe you could share that as well - and an example result you are getting from the server?

**Comment by Reg93** [comment]
> I would assume that the result from your api is not an array, so you cannot map over it? Assuming you get the error in line `...result.map` - and me partially inferring what the error message you have might be. Maybe you could share that as well - and an example result you are getting from the server?

If you can say how to update this object by RTK, it would be great!

From server i get such object: 

```
{
  "name": "Single tournament",
  "description": "texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext",
  "stages": [
    {
      "id": "1",
      "number": 1
    },
    {
      "id": "2",
      "number": 2
    }
  ],
  "participants": [
    {
      "id": "1",
      "name": "John John",
      "pointes": 1
    },
    {
      "id": "2",
      "name": "John John",
      "pointes": 2
    },
    {
      "id": "3",
      "name": "John John",
      "pointes": 3
    }
  ]
}
```

**Comment by phryneas** [comment]
Now step back for a second, ignore Redux, ignore RTK Query... what happens if you call `.map` on that object? Right, a crash, because it's not an array. That object is your `request`. It seems like a single tournament. That doesn't even seem to have an id.
You can use the id you passed in as an argument though.

So you could work over that:

```js
// arg is the id you passed into the hook
providesTags: (result, error, arg) => [
  { type: "Tournament", id: "LIST" },
  { type: "Tournament", id: arg },
];
```

or you take it further

```js
providesTags: (result, error, arg) => [
  { type: "Tournament", id: "LIST" },
  { type: "Tournament", id: arg },
  ...(result
    ? result.stages.map((stage) => ({ type: "Stage", id: stage.id }))
    : []),
  ...(result
    ? result.participants.map((participant) => ({
        type: "Participant",
        id: participant.id,
      }))
    : []),
];
```

**Comment by Reg93** [comment]
> 

Thank you for your efforts. I added your code. This is what i have now

```
import { apiSlice } from "../apiSlice";

export const tournamentApi = apiSlice.injectEndpoints({
  reducerPath: "tournamentApi",
  tagTypes: ["Tournament"],
  endpoints: (build) => ({
    getTournament: build.query({
      query: (id) => `tournament/${id}`,
      providesTags: (result, error, arg) => [
        { type: "Tournament", id: "LIST" },
        { type: "Tournament", id: arg },
        ...(result
          ? result.stages.map((stage) => ({ type: "Stage", id: stage.id }))
          : []),
        ...(result
          ? result.participants.map((participant) => ({
              type: "Participant",
              id: participant.id,
            }))
          : []),
      ]
    }),
    removeTournament: build.mutation({
      query: id => ({
        url: `tournament/${id}`,
        method: "DELETE"
      }),
      invalidatesTags: [{ type: "Tournament", id: "LIST" }]
    }),
    addStage: build.mutation({
      query: (id, body) =>
      ({
        url: `tournament/${id}/stage`,
        method: "POST",
        body
      }),
      invalidatesTags: [{ type: "Tournament", id: "LIST" }]
    }),
    removeStage: build.mutation({
      query: ({id, stageId}) =>
      ({
        url: `tournament/${id}/stage/${stageId}`,
        method: "DELETE"
      }),
      invalidatesTags: [{ type: "Tournament", id: "LIST" }]
    })
  })
})

export const {
  useRemoveTournamentMutation,
  useGetTournamentQuery,
  useAddStageMutation,
  useRemoveStageMutation
} = tournamentApi;
```

I tried to remove one stage on website, but data wasn't updated automatically. Should i change json file on server and add tournament id?

**Comment by phryneas** [comment]
To be honest, since you always invalidate the "LIST" and never the id anyways, this doesn't seem to have anything to do with that. Did you maybe not add the middleware to your store?

**Comment by Reg93** [comment]
> To be honest, since you always invalidate the "LIST" and never the id anyways, this doesn't seem to have anything to do with that. Did you maybe not add the middleware to your store?

Stor has midllware. what should be the result of the server? Where i should add id?
```
import { configureStore } from "@reduxjs/toolkit";
import  tournamentReducer from "./tournamentsService/tournamentsSlice";
import playersReducer from "./playersService/playersSlice"
import { apiSlice } from "./apiSlice";


export const store = configureStore({
  reducer: {
    [apiSlice.reducerPath]: apiSlice.reducer,
    tournaments: tournamentReducer,
    players: playersReducer
  },
  middleware: (getDefaultMiddleware) => getDefaultMiddleware().concat(apiSlice.middleware)
});
```

**Comment by phryneas** [comment]
This seems like it should do something. Could you share a replay?

**Comment by Reg93** [comment]
> This seems like it should do something. Could you share a [replay](https://www.replay.io/)?

Hello. I tried to do it in sandbox. i included server here

https://codesandbox.io/s/mystifying-sun-czulus?file=/src/index.js

**Comment by Reg93** [comment]
> This seems like it should do something. Could you share a [replay](https://www.replay.io/)?

Hello, i found decision. It is so simple and i even didn't think of it. This code does what i need:

```
import { apiSlice } from "../apiSlice";

export const tournamentApi = apiSlice.injectEndpoints({
  reducerPath: "tournamentApi",
  tagTypes: ["Tournament"],
  endpoints: (build) => ({
    getTournament: build.query({
      query: (id) => `tournament/${id}`,
      providesTags: ["Tournament"]
    }),
    removeTournament: build.mutation({
      query: id => ({
        url: `tournament/${id}`,
        method: "DELETE"
      }),
      invalidatesTags: ["Tournament"]
    }),
    addStage: build.mutation({
      query: (id, body) =>
      ({
        url: `tournament/${id}/stage`,
        method: "POST",
        body
      }),
      invalidatesTags: ["Tournament"]
    }),
    removeStage: build.mutation({
      query: ({id, stageId}) =>
      ({
        url: `tournament/${id}/stage/${stageId}`,
        method: "DELETE"
      }),
      invalidatesTags: ["Tournament"]
    })
  })
})

export const {
  useRemoveTournamentMutation,
  useGetTournamentQuery,
  useAddStageMutation,
  useRemoveStageMutation
} = tournamentApi;
```

Thank you for your time!
