### ISSUE TITLE
Using @reduxjs/toolkit's createAsyncThunk to perform asynchronous operations to obtain data failed

### ISSUE THREAD

**Issue by litchi-iconfont** [reduxjs/redux-toolkit#3328]
Have any of you encountered the failure of using @reduxjs/toolkit's createAsyncThunk to perform asynchronous operations to obtain data, the browser's network shows a successful request, and the data can be obtained, but the result does not print out the value, the display is undefined, and vscode prompts that await It has no effect on the expression. The .then() method has also been tried, and the printing is not printed, and there is no error message in the console.

```
import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import { getHomeGoodPriceData } from "../../service";

export const fetchHomeDataAction = createAsyncThunk("fecthdata", async () => {
  const result = await getHomeGoodPriceData()
  console.log(result);
  return result
})
```

**Comment by litchi-iconfont** [comment]
dd

**Comment by litchi-iconfont** [comment]
dd

**Comment by litchi-iconfont** [comment]
dd

**Comment by markerikson** [comment]
Afraid we can't tell anything from that specific snippet. Can you put together a repro that shows this happening as a CodeSandbox or a Github repo, or record and link a Replay ( https://replay.io/record-bugs ) ?

**Comment by litchi-iconfont** [comment]
I solved the problem, the reason is that the interface I requested has no return, so I can't get the value, I was really stupid...
