### ISSUE TITLE
Request for a pre-made code template for using Redux Toolkit with Vite in a React application 

### ISSUE THREAD

**Issue by umeh-promise** [reduxjs/redux-toolkit#3329]
Is it possible to have a pre-made code template for using Redux Toolkit with Vite in a React application? I am looking for a starting point to integrate Redux Toolkit and Vite without having to manually configure the project setup. It would be helpful to have a boilerplate code that includes all the necessary dependencies, files, and configurations for a smooth integration.

Specifically, I want to use Redux Toolkit, which is a recommended way to manage state in a React application, and Vite, which is a build tool that offers fast development experience by optimizing build times. However, setting up the project from scratch can be time-consuming, and I would like to save time by using a boilerplate code that I can customize to fit my needs.

Thank you.

**Comment by markerikson** [comment]
Yeah, we've been wanting to set up an official Vite template for a while, but haven't had time.

https://github.com/nvh95/vite-react-template-redux is equivalent to our current CRA+TS template, and whenever we finally have time to make one ourselves, it'll basically be identical to that.

**Comment by phryneas** [comment]
There is also a starter by @ryota-murakami over at https://github.com/laststance/vite-rtk-query

**Comment by umeh-promise** [comment]
@phryneas  Thank you for taking the time to provide a solution to my request for a pre-made template for using Redux Toolkit with Vite in a React application. I appreciate your effort in creating this solution.

In my case, I do not require Tailwind CSS in the template. I feel that Tailwind CSS may not be necessary for certain projects that I am working on.. However, I think the solution would be more suitable for my needs if we remove this addition and focus solely on the integration of Redux Toolkit with Vite and Typescript in a React application.

Thank you.

**Comment by sobhardwaj** [comment]
Tailwind CSS is over hyped

**Comment by ryota-murakami** [comment]
I added `npm run remove:tailwind` script into https://github.com/laststance/vite-rtk-query for who don't need TailwindCSS.
I think is very balanced approach to both demands.

According to [The State of CSS 2022: CSS Frameworks](https://2022.stateofcss.com/en-US/css-frameworks/), TailwindCSS is most popular way to styling.

I am thinking of removing "TailwindCSS" from the templete as time goes by and it becomes less popular.

**Comment by markerikson** [comment]
This is available now!

https://redux.js.org/introduction/getting-started#create-a-react-redux-app
