### ISSUE TITLE
Redux Toolkit Query is broken with "yarn build"

### ISSUE THREAD

**Issue by gaanti** [reduxjs/redux-toolkit#3337]
I have an react application, where I used **Redux toolkit Query**. In development mode everything works perfectly. But at the production deployment stage I found out that it starts to have critical problems while the application is built (`yarn build`) and started by (`serve -s build`) - triggering cached data by keys makes app get into infinite loop, while in development mode (application started by "`yarn start`") everything works properly.

For example changing state (number) what triggers queryRefetch, causes infinite error and application stuck

  ```
const [number, setNumber] = useState(0);
  const { data: emptyData } = useEmptyQuery(number);
```
<img width="971" alt="Expanded error" src="https://user-images.githubusercontent.com/104729017/230787219-1ffad268-d2c6-40e6-8c58-286ed8b045aa.png">

How to fix it?

**Comment by phryneas** [comment]
If you have a new number every render, that seems to be expected - every time you do that, a new request will start with the new number as an argument.
