### ISSUE TITLE
High CPU usage by using onQueryStarted handler

### ISSUE THREAD

**Issue by Marcell123** [reduxjs/redux-toolkit#3346]
I'm learning RTK query with Redux-toolkit. Reading this article from docs: 
https://redux.js.org/tutorials/essentials/part-8-rtk-query-advanced#implementing-optimistic-updates
I wrote exactly the same blog from documentation, but got a big issue with CPU.

Even if I don't run the project, but my IDE is just open,- my CPU usage is loaded by 80-90% from the beginning. And onQueryStarted handler causes this. Because when I comment this handler out, - CPU usage immediately gets loaded by few %. 

[Screen Recording 2023-04-12 at 20.01.59.mov.zip](https://github.com/reduxjs/redux-toolkit/files/11214108/Screen.Recording.2023-04-12.at.20.01.59.mov.zip)

**Comment by phryneas** [comment]
I'm sorry, but this just sounds like the wildest thing. I fear it might not be something we can help you with, as that problem can be anything from a specific TypeScript version to a specific version of your IDE, or just any plugin you have installed there.

If you can reproduce that with a fresh project and a  plain install of VSCode without extra plugins, I would be very interested to see a reproduction of this - but I fear that without that we can't really do anything about it.

**Comment by Marcell123** [comment]
Found out that this default plugin caused the issue (php storm IDE): 
![photo_2023-04-18_00-27-53](https://user-images.githubusercontent.com/35539661/232617293-06807027-10f7-4b29-bd30-82e8fdc46cb4.jpg)

Even after when I turned it ON again, - everything is fine. Reloading IDE before didn't help, but this plugin does. Code works fine, no problems with CPU. Hope to never reproduce this in future=)

Thanks

**Comment by phryneas** [comment]
I can only recommend you try to use VSCode instead. WebStorm doesn't use the official TypeScript Type server, but some crutch they invented themselves they claim is "faster". That might fail in so many unexpected ways we cannot support - I'm sorry.
