### ISSUE TITLE
Re-exporting selectors gets caught in cyclical dependancy

### ISSUE THREAD

**Issue by rahulthewall** [reduxjs/redux-toolkit#3351]
Complete working code: https://github.com/rahulthewall/redux-error

I have my selectors defined in a file selectors.ts

```
import { createSelector } from '@reduxjs/toolkit';
import { RootState } from '../store/store';

const userState = (state: RootState) => state.userReducer;

export const user = createSelector([userState], (userSlice) => userSlice.loginUser.data);
export const userIsLoggingIn = createSelector([userState], (userSlice) => userSlice.loginUser.isFetching);
export const userLoginHasError = createSelector([userState], (userSlice) => userSlice.loginUser.hasError);

export const refreshUser = createSelector([userState], (userSlice) => userSlice.refreshUser.data);
export const userIsRefreshing = createSelector([userState], (userSlice) => userSlice.refreshUser.isFetching);
export const userRefrehHasError = createSelector([userState], (userSlice) => userSlice.refreshUser.hasError);
```

In a file `index.ts` in the same folder, I re-export them as follows

```
export * as userSelectors from './selectors';
```

Then, when I try to use this import in my component, it errors out. 

Here's how I use it.

```
import { userSelectors } from "./modules/user";

const user = useAppSelector(userSelectors.user);
```

The error I get is the following

```
Uncaught ReferenceError: can't access lexical declaration 'userReducer' before initialization
```

However, if I import it directly from the `selectors` file it works. 

```
import { user } from "./modules/user/selectors";

const userObject = useAppSelector(user);
```

Can anyone tell me what is the mistake I am making? I can't see it.

**Comment by rahulthewall** [comment]
`export * as` is supposed to work with TypeScript 3.8: https://stackoverflow.com/questions/42728140/is-it-possible-to-export-as-foo-in-typescript/59712387#59712387

Regardless, even if I export specifically it does not work. 

In index.ts

    export { user } from './selectors';

Then in App.tsx
    
    import { user } from "./modules/user";
    
    const userObject = useAppSelector(user);

This still fails. 

However, if I import from selectors directly, it works. 
    
    import { user } from "./modules/user/selectors";
    
    const userObject = useAppSelector(user);

I am sure I am doing something stupid, but I can't figure out what.

**Comment by phryneas** [comment]
Well, you have introduced *some* cycle there. This doesn't really have to do anything with Redux, but with your unique combination of bundlers. It's also impossible for us to debug unless we had full access to your source code, and even then I can say from personal experience that finding the right cycle can take hours.

Generally, I'd recommend against this type of barrel-export-file, as it will also make tree-shaking and lazy-loading impossible. And once you migrate your project to ESM, you're gonna have to import from `"./modules/user/index.js"`, so you didn't even gain any "removal of the last path part".

**Comment by rahulthewall** [comment]
Hey, thanks for the response. I did provide my full source code: https://github.com/rahulthewall/redux-error

I have removed everything from this code, and only have redux in it and I am still getting the error. 

>Generally, I'd recommend against this type of barrel-export-file, as it will also make tree-shaking and lazy-loading impossible. And once you migrate your project to ESM, you're gonna have to import from "./modules/user/index.js", so you didn't even gain any "removal of the last path part".

Can you please give me some more information on this part? I'd love to read up more.
