### ISSUE TITLE
Selectors with dynamic arguments

### ISSUE THREAD

**Issue by hakob-c8r** [reduxjs/redux-toolkit#3352]
I need to get some data from the state, but with dynamic arguments, but this kind of selector returns the new reference on each state change,  is there a possible way to avoid that ?

```
const stateGetter = ( state ) => state

const selector1 = createDraftSafeSelector(
  [arg1Selector, arg2Selector, stateGetter], (arg1, arg2, state) => {
    
    const getSelector = api.endpoints.getSomeThing.select( { firstArg: arg1, secondArg: arg2 } )
    
    return getSelector(state);
  }
);

export const selector2 = createDraftSafeSelector(
    [selector1], (response) => {
      // do something ...

    return response
    }
);
```

**Comment by markerikson** [comment]
An input function of `state => state` is _never_ a good idea. You're guaranteeing that one of the inputs is _always_ going to change.

Where/when/why/how are you trying to use this?

**Comment by hakob-c8r** [comment]
The values ​​`arg1Selector` and `arg2Selector` will always change, for example, every time the page is changed, so I need to get the data on the `arg1Selector` and `arg2Selector` values,  and render the `selector2` response in the component

**Comment by hakob-c8r** [comment]
since I am using the value `selector2` in a table that has many rows, I can't use just `useQuery`, to memoize the response, I need a `selector2` that will return the answer
