### ISSUE TITLE
[RTK Query] endpoint.useQuery does not fetch data on dynamic endpoint change

### ISSUE THREAD

**Issue by ivan-jelev** [reduxjs/redux-toolkit#3356]
In case when endpoint changes dynamically useQuery does not trigger request and stays in pending state.

Example:
```
const EntityLayout  = ({ endpoint }) => {
  const res = endpoint.useQuery();
  return res;
}
```
In this case query will be fetched initially, but not when endpoint changed.

Playground: https://codesandbox.io/s/reverent-joliot-swujhu?file=/src/App.tsx

![0dXlSp1Qie](https://user-images.githubusercontent.com/20439799/232025929-2dfd05f8-5afa-4fa4-818d-ef59623cecbf.gif)

**Comment by markerikson** [comment]
Can you clarify what you mean by "endpoint changes dynamically"?

**Comment by phryneas** [comment]
You are violating the rules of hooks here - you cannot just switch out a hook for another.

**Comment by ivan-jelev** [comment]
Thank you for pointing out! 🙂
