### ISSUE TITLE
[RTK Query]: transformResponse meta response headers are missing

### ISSUE THREAD

**Issue by ecalcutin** [reduxjs/redux-toolkit#3357]
I want to retrieve a date from the `date` response header. I created a new project on CodeSandBox that uses the jsonplaceholder API.

Store configuration
```ts
import { configureStore, combineReducers } from "@reduxjs/toolkit";
import { jsonPlaceholderApi } from "./api";

const rootReducer = combineReducers({
  [jsonPlaceholderApi.reducerPath]: jsonPlaceholderApi.reducer
});

export const store = configureStore({
  reducer: rootReducer,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat([jsonPlaceholderApi.middleware])
});

export type RootState = ReturnType<typeof rootReducer>;
```

API queries
```tsx
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const jsonPlaceholderApi = createApi({
  reducerPath: "jsonPlaceholder",
  baseQuery: fetchBaseQuery({
    baseUrl: "https://jsonplaceholder.typicode.com"
  }),
  endpoints: (builder) => ({
    fetchTodos: builder.query({
      query: () => ({
        url: `/todos`
      }),
      transformResponse: (response, meta) => {
        console.log(meta.response.headers.get('date')); // <----- Here should be date value
        return response;
      }
    })
  })
});

export const { useFetchTodosQuery } = jsonPlaceholderApi;
```

The console.log returns empty headers, but should be a Date.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/42963334/232025749-4975705a-a0b3-481c-9d38-2c604d17d662.png">

```ts
console.log(meta.response.headers.get('date'));
```

SandBox example: https://codesandbox.io/s/redux-toolkit-playground-forked-7hss1e

**Comment by Happymona** [comment]
i also face same issue ,not returning the api response headers

**Comment by zizzhangJohn** [comment]
same, and it seems like some other header contents are missing as well (compare to rest client result)

**Comment by alexa-infra** [comment]
Got similar issue, one important observation - for me meta.response contains a cors preflight response and not the final api response.

**Comment by zizzhangJohn** [comment]
> 

Okay, I thought it could be cors issue, but why is this working with tools like restclient and postman, the 'Date' header is present there.

**Comment by ecalcutin** [comment]
@zizzhangJohn I have googled about it, and was reviewing stackoverflow regarding that and even posted it here. 
However, the this is how fetch works.
If you take a look on RTK query docs https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery it is wrapper around `fetch`. 
So, you will have same results with `fetch` (no headers). 
Once you add `Access-Control-Allow-Headers` to your server (e.g. ngix) - you will receive it.
For example, I have an API returning array of items. I want to expose custom header describing pagination date (total count);

I do:
```
Access-Control-Expose-Headers: Item-Count
```

Then If I do simple fetch or use RTK query to query endpoint, Ill retrieve that header in response.

**Comment by ecalcutin** [comment]
The issue is closed, since it is not related to Redux Toolkit. But this is a nice example that docs should be updated to highlight this.
