### ISSUE TITLE
FETCH_ERROR "TypeError [ERR_INVALID_URL]: Invalid URL" for requests made in tests (after migration from `fetch` to RTK Query)

### ISSUE THREAD

**Issue by naXa777** [reduxjs/redux-toolkit#3383]
### Environment check

- [X] I'm using the latest redux-toolkit version (`"@reduxjs/toolkit": "^1.9.3"`)
- [X] Node.js version: 19.3

### Reproduction repository

https://github.com/OKitel/react2023Q1/tree/react.redux/react-playground

### Reproduction steps

```
cd react-playground
npm i
npm run test:ui
```

### Current behavior

tests fail with [FETCH_ERROR "TypeError [ERR_INVALID_URL]: Invalid URL" for requests made in tests](https://stackoverflow.com/q/76046546/1429387) (see this question for details)

### Expected behavior

tests pass. fake data is fetched from the mock server.

**Comment by phryneas** [comment]
That has nothing to do with Redux Toolkit. That error comes from fetch. Your baseUrl probably is a relative url, not an absolute url (with leading `https://`/`http://`), which would be required for any request running in node.

**Comment by naXa777** [comment]
no, I specify protocol like `export const BASE_URL = 'http://localhost:5173/api';` and then

```ts
export const apiSlice = createApi({
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({
    baseUrl: BASE_URL,
    // ...
```

**Comment by phryneas** [comment]
Well, `ERR_INVALID_URL` is an error from calling `fetch` with that url - you would get the same error without RTK Query. So you're doing *something* that `fetch` does not support. 
Honestly, I'm still guessing at that BASE_URL... Maybe try logging that out. Apart from that, I don't really have ideas.

**Comment by naXa777** [comment]
Update: the error has been fixed in msw.js repository https://github.com/mswjs/msw/issues/1597
