### ISSUE TITLE
Create React App is no longer recommended

### ISSUE THREAD

**Issue by cesarvargas00** [reduxjs/redux-toolkit#3384]
In redux-toolkit docs:

>The recommended way to start new apps with React and Redux is by using the [official Redux+JS template](https://github.com/reduxjs/cra-template-redux) or [Redux+TS template](https://github.com/reduxjs/cra-template-redux-typescript) for [Create React App](https://github.com/facebook/create-react-app), which takes advantage of [Redux Toolkit](https://redux-toolkit.js.org/) and React Redux's integration with React components.

The [new react docs](https://react.dev/learn/start-a-new-react-project) no longer recommends create-react-app as a starting point to any react app. Instead, it recommends to using [Vite](https://vitejs.dev/) or [Next.js](https://nextjs.org/).

**Comment by markerikson** [comment]
Yep, we're aware. We want to come up with an official Vite template, but haven't had time to do that.

**Comment by markerikson** [comment]
We've got Vite templates now, and the docs have been updated.
