### ISSUE TITLE
[Refactor] Rename reducers to actions

### ISSUE THREAD

**Issue by mohammad-taheri1** [reduxjs/redux-toolkit#3385]
Hey.
I was explaining to my students that how we can create a new slice. And they asked me an interesting question. It shows that we can change our `createSlice` to be more `Readable`. Let me show you the thing:

we use this syntax to create a new slice:
```
export const authSlice = createSlice({
   name: "auth",
   initialState,
   reducers: {
      setDarkMode: () => {},
      setLogin: () => {},
      setLogout: () => {}, 
   },
});

export const { setDarkMode, setLogin, setLogout } = authSlice.actions;

export default authSlice.reducer;
``` 

So, we define some reducers, But we export them as actions. Again we export reducer. This is a part that can be so confusing for new RTK learners.

I suggest that we rename `reducers: {}` to `actions: {}`. It is much more like old Redux actions so it would be easier to learn.

Let me know if this is a good idea so i can work on it. 
Thanks

**Comment by phryneas** [comment]
But those are reducers. Actions in legacy Redux should never have calculated new state. That has always been the job of reducers.

**Comment by markerikson** [comment]
No, that's a major misunderstanding of the intent here.

What you are _writing_ is "case reducer functions": functions that handle a given action type, and return an updated state.  Conceptually they are the same idea as:

```ts
function todosReducer(state, action) {
  switch(action.type) {
    case "todos/todoAdded": {
      return [...state, {id: action.id, text: action.text, completed: false}]
    }
    default: return state
  }
}
```

However, `createSlice` automatically _generates_ action creator functions whose names and action type strings correspond to the name of the case reducer function you wrote:

```ts
const todosSlice = createSlice({
  name: "todos",
  initialState: [],
  reducers: {
    // Your "case reducer" function
    todoAdded(state, action) {
      const {id, text} = action.payload;
      state.push({id, text, completed: false})
    }
  }
})

// results in this action creator being generated:
export const { todoAdded} = todosSlice.actions;

export default todosSlice.reducer;
```

but it's very important to understand that **what you are _writing_ is "reducers", not "actions" or "action creators"**.

So, the name `reducers` is correct here, and should not be changed.
