### ISSUE TITLE
RTK Query endpoints are not served from cache

### ISSUE THREAD

**Issue by kamalmalaklife** [reduxjs/redux-toolkit#3391]
I have 3 endpoints as shown:

```js
getAllGallery: builder.query({
      query: () => ({ url: `/gallery/all`, method: "GET" }),
      providesTags: (result) =>
        result
          ? [...result?.map(({ id }) => ({ type: "Image", id }))]
          : [{ type: "Image", id: "LIST" }],
    }),
    getImage: builder.query({
      query: (id) => {
        console.log("getImage", id);
        return { url: `/gallery/${id}`, method: "GET" };
      },
      providesTags: (result, error, id) => [{ type: "Image", id }],
    }),
    toggleImage: builder.mutation({
      query: ({ image_id, operation }) => ({
        url: `/gallery/toggle/${image_id}/${operation}`,
        method: "PUT",
      }),

      invalidatesTags: (result, error, args) => [
        { type: "Image", id: args.image_id },
      ],
    }),


```

getAllGallery triggers an endpoint where it received image items as a result.
whenever I need to show in a component a specific image that was already loaded to the cache by getAllGallery, the endpoint of getting an image is triggered.
eventhough it is listed as the same {type: ["Image"], id} that was previously cache filled by the getAllGallery endpoint.

I followed the documentation 1 / 1, something is could be preventing cache from working properly.

**Comment by phryneas** [comment]
Tags are only there for the sake of automatic refetching, they are really "tags". Think of post-its you slap on a folder to describe roughly what might be found in there. They do not in any way make a connection between the actual content. 

RTK Query is a document cache - every one of those endpoints is completely independent from each other. It's not a normalized cache. 

We describe that [here in the documentation](https://redux-toolkit.js.org/rtk-query/comparison#no-normalized-or-deduplicated-cache)
