### ISSUE TITLE
Multiple Providers context does not work with react rtk react api hooks

### ISSUE THREAD

**Issue by MantasSidabras** [reduxjs/redux-toolkit#3399]
I have a use case for multiple redux stores in my app. I've configures 2 stores as described in this [article](https://www.geekyhub.in/post/handling-multiple-stores-in-react-redux-application/), by providing a React context for each provider. 
Then I've created `customCreateApi` as described in the [docs](https://redux-toolkit.js.org/rtk-query/usage/customizing-create-api), by passing dispatch with the proper context.

When I attempt to use `useGetPokemonByNameQuery` in a component I face this error, of `Reach could not find react-redux context value; ` 
<img width="385" alt="image" src="https://user-images.githubusercontent.com/23079946/234329646-08e563f9-7d4f-43b4-96cf-923e480a5a87.png">

I've recreated the app with Create react app
repo: https://github.com/MantasSidabras/rtk-app
index, where providers are setup: https://github.com/MantasSidabras/rtk-app/blob/main/src/index.tsx
context is defined here:https://github.com/MantasSidabras/rtk-app/blob/main/src/store/appStoreHooks.ts
api: https://github.com/MantasSidabras/rtk-app/blob/main/src/store/exampleApi/example.ts

App will throw the same error even if I use single Provider with context. I've tried several different version of react-redux, no luck. 

Although, I can use RTK Query with by dispatching inititate action manually in useEffect, then selecting it with selector from cache, but thats a hassle. Provided this in example app as App2.tsx

**Comment by EskiMojo14** [comment]
you need to provide a `useStore` hook to your api react module too - create it with `createStoreHook` from react-redux.

**Comment by MantasSidabras** [comment]
Did the trick, thank you!
