### ISSUE TITLE
Help with refetch using redux-toolkit

### ISSUE THREAD

**Issue by TheMythologist** [reduxjs/redux-toolkit#3402]
Hi, I recently upgraded from Next.js 12 to 13 (and React 17 to 18), which comes with a lot of changes with how pages are rendered (via SSR) and hydration.

After upgrading, most of the code works fine, apart from refetching, which is stored in a `useEffect`:
```ts
const { data: execution, refetch } = useGetSubmissionExecutionQuery(
  submission?.id ?? skipToken,
  {
    pollingInterval: 10 * 1000,
  }
)

useEffect(() => {
  refetch()
}, [submission?.status, refetch])
```

The above code results in `Error: Cannot refetch a query that has not been started yet.`
I understand that I need to fetch the data at least once before attempting to refetch, but I have no idea how to do so. (Accessing the page that uses this `useEffect`, i.e. accessing `/submissions/[id]` from `/submissions` will not cause the error, but accessing `/submissions/[id]` directly will cause the error.)

I've read through some documentation, including
- https://redux-toolkit.js.org/rtk-query/usage/automated-refetching
- https://redux-toolkit.js.org/rtk-query/usage/server-side-rendering and the example shown
- https://github.com/kirill-konshin/next-redux-wrapper

Any tips on how I should go about resolving this bug? Thanks.

**Comment by TheMythologist** [comment]
_Update_: Just an attempt update, I added a delay to `useEffect`:
```ts
useEffect(() => {
  setTimeout(()=>{
    refetch()
   }, 5000)
}, [submission?.status, refetch])
```

Now, instead of erroring `Cannot refetch a query that has not been started yet` twice, I only get the error once.

**Comment by TheMythologist** [comment]
Sorry for the spam, but final update:

I've thought of using a `boolean` constant that keeps track of whether the hydration has succeeded, but I'm not sure if this is the right way going forward:

```ts
const [mounted, setMounted] = useState(false)

useEffect(() => {
  if (mounted) refetch()
  else setTimeout(()=>{
    setMounted(true)
   }, 1000)
}, [submission?.status, refetch, mounted])
```

**Comment by TheMythologist** [comment]
After some testing, I've come to the conclusion, let me know if this is the "proper" way to do this:

```ts
const [refetch, { data: execution }] = useLazyGetSubmissionExecutionQuery(
  {
    pollingInterval: 10 * 1000,
  }
)
 useEffect(() => {
  if (submission?.id) refetch(submission?.id)
}, [submission?.id, refetch])
```

Once again, I apologise for the spam 😢

**Comment by phryneas** [comment]
Uh... I'm a bit irritated. `useEffect` should not even execute anything on the server. Are you seeing these messages on the server?

**Comment by phryneas** [comment]
Also... could you maybe take a step back and explain what you are actually trying to do and why you are trying to do it?  
I think you might be doing something in a very complicated fashion here.

**Comment by TheMythologist** [comment]
I have something similar to a "pipeline" running in the backend, and the page containing this `useEffect` is a page that displays the output of the pipeline. On page load (`/submissions/[id]`) I display the results, but subsequently after page load, I wish to query an API endpoint `/api/submissions/[id]/execution` every 10 seconds to query if the execution state of this `id` has changed.

> Uh... I'm a bit irritated. `useEffect` should not even execute anything on the server. Are you seeing these messages on the server?

Yup I am seeing the requests to `/api/submissions/[id]/execution` being made, both before and after the upgrade to React 18.

**Comment by TheMythologist** [comment]
Hi after closer inspection, turns out you were right: there's no need for me to call `refetch` in `useEffect`. thanks for the help!
