### ISSUE TITLE
api.reducerPath adding undefined to key name in store

### ISSUE THREAD

**Issue by vickywar** [reduxjs/redux-toolkit#3405]
Customer API

```
const customerApi = createApi({
    reducerPath: "customerApi",
    baseQuery: fetchBaseQuery({ baseUrl: SERVER_CONFIG.BASE_URL }),
    endpoints: (builder) => ({
        customer: builder.query<Customer[], void>({
            query: () => "/customer"
        })
    })
});
```

Store definition

```
const customerApi = createApi({
    reducerPath: "customerApi",
    baseQuery: fetchBaseQuery({ baseUrl: SERVER_CONFIG.BASE_URL }),
    endpoints: (builder) => ({
        customer: builder.query<Customer[], void>({
            query: () => "/customer"
        })
    })
});
```

Result store format 

{
  customerApi: {
    queries: {
      'customer(undefined)': { ... 

Getting (undefined) concantenated in key name which is hard to query using useSelector.

**Comment by EskiMojo14** [comment]
> Getting (undefined) concantenated in key name which is hard to query using useSelector.
How are you using useSelector? you should either be using the generated useQuery/useMutation hooks, or use the .select() factory to generate a selector for you based on your argument (or lack of)

You shouldn't ever be doing `state.customerApi.queries['customer(undefined)']`, as I assume you're trying to do.

**Comment by markerikson** [comment]
To be clear, this isn't about the `reducerPath`.  The `undefined` there is referring to the query cache key value for the `customer` endpoint, and this is expected since you _don't_ have any arguments for that endpoint.

**Comment by vickywar** [comment]
> 

actually yes. i was about to use the useSelector as state.customerApi.queries['customer(undefined)'] .. 
i am not aware of how to query this instead , with undefined key .. may i know any other ways please ?

**Comment by phryneas** [comment]
but even if you were doing a manual selection from state, it would be

```js
const selector =  customerApi.endpoints.customer.select(undefined)
// or
const selector =  customerApi.endpoints.customer.select()

const customer = selector(state)
const customer = useSelector(selector)
```
