### ISSUE TITLE
Dynamic Reducers not working without redux dev tools extension

### ISSUE THREAD

**Issue by konampruthvirajkumar** [reduxjs/redux-toolkit#3406]
here I am using "@reduxjs/toolkit": "^1.8.5" and I see weird behavior when using code splitting reducer to inject reducer at runtime.

here is the code for configureStore
```
export const store = configureStore({
  reducer: { ...staticReducers },
  middleware: getDefaultMiddleware => getDefaultMiddleware(),
});
//@ts-ignore
store.placeholder = {};

export type AppState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
```

this function takes the store and replace / add new reducer at runtime

```
export const injectReducer = (store: any, { key, reducer }: { key: string; reducer: Reducer }) => {
  let keys = key.split('/');
  makeAsyncReducers(store.placeholder, keys, reducer);
  store.replaceReducer(makeRootReducer(store.placeholder));
};
```

store structure
```
key: 'section/summary', 'section/subsection-1/summary' ...etc
{
  "section": {
    "summary": { ... },
    "subsection-1": {
      "summary": { .... }
    },
    "subsection-2": {
      "summary": { ....}
    }
  }
}
```
dynamic reducers are getting into store without dev tools extension. everything is works fine with redux dev tools extension enabled

**Comment by markerikson** [comment]
I'm confused. What actual problem are you seeing?

**Comment by konampruthvirajkumar** [comment]
> I'm confused. What actual problem are you seeing?

**Comment by konampruthvirajkumar** [comment]
> I'm confused. What actual problem are you seeing?

unfortunately, I couldn't upload screenshot because of github upload issue.

in a high level when dev tools extension is enabled dynamic and static reducers are working.

with dev tools extension disabled only static reducers are working but dynamic reducers are undefined

**Comment by phryneas** [comment]
We would need a minimal reproduction for that - I've never heard of behaviour like that.
