### ISSUE TITLE
createApi doesn't returns a function.

### ISSUE THREAD

**Issue by Ayyubxon-coder** [reduxjs/redux-toolkit#3410]
![code](https://user-images.githubusercontent.com/81279078/235289419-0fb43073-8c7b-40e9-9659-14324cef8bb5.png)

I hev this code and if i tried to return a function from this code, it returns an error:

![image](https://user-images.githubusercontent.com/81279078/235289444-59830a02-3392-4880-983c-7fad16995729.png)

I can't export any function from this api.

**Comment by EskiMojo14** [comment]
make sure you're importing from @reduxjs/toolkit/query/react. without the /react, you will not get hooks generated.

**Comment by Ayyubxon-coder** [comment]
Thanks man, it's working fine right now!
