### ISSUE TITLE
RTK query is not allowing to display the actual api error msg it overides the serve error response with  some generic error messgae

### ISSUE THREAD

**Issue by Happymona** [reduxjs/redux-toolkit#3412]
https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/fetchBaseQuery.ts#L284

**Comment by EskiMojo14** [comment]
can you be more specific with the issue you're seeing?
the code you've linked to doesn't match the title you've written - the *status* is a known string/status code that the FetchBaseQueryError can be discriminated on. the *error* key is a stringified version of the error thrown.
