### ISSUE TITLE
Value undefined on the second nested array

### ISSUE THREAD

**Issue by mantegnous** [reduxjs/redux-toolkit#3426]
Hi, hi i have this in mi reduce

```

const { turnIndex, categoryId, data } = payload;

state.currentVenue.turns[turnIndex].categories[categoryId].products =
  [...(state.currentVenue.turns[turnIndex].categories[categoryId].products ?? []), data];

```

But products is always undefined... i have another same code that inserts category in categories and keeeping the old state 

`state.currentVenue.turns[turnIndex].categories= [...(state.currentVenue.turn[turnIndex].categories ?? [], data]`

In this case, the code work, but, when i try to do the same thing, by addind products in a category index, products is undefined (if exist or not, is always undefined)

If i change and, i decide to assign products not in an array but a normale key, i receive a Immer error..

What im doing wrong? I tried to write the code also in other more readable way and with the related checks, but it doesn't work

**Comment by EskiMojo14** [comment]
firstly, you can do this logic with mutable code as long as you're in a reducer: 

```ts
state.currentVenue.turns[turnIndex].categories[categoryId].products.push(data)
```

as for why your products are undefined, i'm assuming that either turnIndex or categoryId is incorrect.

**Comment by mantegnous** [comment]
@EskiMojo14  i have this reducer and it works:

`state.currentVenue.turns[payload.turnIndex].categories = [...(state.currentVenue.turns[payload.turnIndex].categories ?? []), payload.data]`

i tried with `push` but its the same problem, products is undefined.. and i dont unsterdand why.. 

turnIndex and categoryId are corrects, are index

**Comment by phryneas** [comment]
Yes, that reducer checks if there is an array and, if not, uses an empty array instead.

Similarly, you could do
```js
if (!state.currentVenue.turns[payload.turnIndex].categories) {
  state.currentVenue.turns[payload.turnIndex].categories  = []
}
state.currentVenue.turns[payload.turnIndex].categories.push(foo)
```
which is equivalent to
```js
state.currentVenue.turns[payload.turnIndex].categories ??= []
state.currentVenue.turns[payload.turnIndex].categories.push(foo)
```
which is equivalent to
```js
(state.currentVenue.turns[payload.turnIndex].categories ??= []).push(foo)
```

**Comment by mantegnous** [comment]
@phryneas same problem

**Comment by mantegnous** [comment]
@phryneas 

I did the same thing with the products, but I get the error I wrote in the first message 

`
const { turnIndex, categoryId, data } = payload;

state.currentVenue.turns[turnIndex].categories[categoryId].products =
  [...(state.currentVenue.turns[turnIndex].categories[categoryId].products ?? []), data];
`

**Comment by phryneas** [comment]
That code you show there is the code that you said would be working?

**Comment by mantegnous** [comment]
@phryneas exactly, when I go to write in a second nested array I have this problem, it says that products doesn't exist.. only works up to categories.. I tried to condition and check the existence of products by doing a push.. maybe I'm doing something wrong, maybe there are other ways to write so nested?

**Comment by phryneas** [comment]
...look at the code examples I gave and apply them one nesting level deeper?
