### ISSUE TITLE
[typescript] inject endpoints does not give new endpoint's type to the return

### ISSUE THREAD

**Issue by Jackmekiss** [reduxjs/redux-toolkit#3427]
Hi, when there is a use of inject endpoints. The return does not have the type of the new endpoints.

Example:
```
 let api = createApi({
    baseQuery,
    endpoints: () => ({}),
  });

  api = api.injectEndpoints({
    endpoints: (build) => ({
      example: build.query({
        query: () => 'test',
      }),
    }),
    overrideExisting: false,
  });

  api.endpoints.example.initiate();
```

And typescript give this following error: `Property 'example' does not exist on type '{}'`.

Dependencies:
```
 "dependencies": {
    "@reduxjs/toolkit": "1.9.5",
    "axios": "^1.4.0",
    "lodash": "^4.17.21",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-redux": "^8.0.5",
    "redux": "^4.2.1",
    "redux-persist": "^6.0.0"
  },
```

**Comment by EskiMojo14** [comment]
you need to save the result to a new variable - your let will not adjust its type based on the reassignment.

**Comment by Jackmekiss** [comment]
Thanks! sadly it's not on the documentation :(

**Comment by EskiMojo14** [comment]
The [code splitting](https://redux-toolkit.js.org/rtk-query/usage/code-splitting) page very specifically shows the injected API being saved to a new const. 😉

**Comment by phryneas** [comment]
And it's not a RTK limitation. TypeScript variables can not change their type after initial declaration.
