### ISSUE TITLE
Docs need improvement

### ISSUE THREAD

**Issue by Career404** [reduxjs/redux-toolkit#3431]
## Problem 1
* [This part of the docs](https://www.npmjs.com/package/redux-offline#executor-of-our-will) is absolutely crucial to understand the library
* It took me about an hour to find it

Why is it not in the [docs](https://redux-offline.github.io/redux-offline/)?

## Problem 2
* Redux Toolkit syntax feels great
* It's not covered at all, other than in some issues (unanswered too)- 
1 #454 
2 #489 
3 #490 
4 #506 
and even in redux-toolkit issues like [this](https://github.com/reduxjs/redux-toolkit/issues/583)

I strongly feel that more examples in the docs - especially those with RTK - would greatly improve the experience

**Comment by Career404** [comment]
I think I've just posted the issue to the wrong repo. I am so truly sorry

**Comment by markerikson** [comment]
Hah, okay :)
