### ISSUE TITLE
 Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>. Though I have wrapped <Provider> in my RootLayout component.

### ISSUE THREAD

**Issue by yousuf4you** [reduxjs/redux-toolkit#3437]
> ## Hope someone will help me to solve the problem.

I am facing a problem in nextjs13. I am facing the problem with any routes.  I also not facing the problem with my main page `/app/page.tsx`  but with others which I have like `/app/memories/create` `/app/memories/update`.

Error in the terminal or Error:
```sh
- error node_modules\react-redux\lib\hooks\useReduxContext.js (30:0) @ useReduxContext
- error Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>
    at UpdateMemory (./app/memories/update/page.tsx:14:83)
null
```

You can see it in my repo:  https://github.com/yousuf4you/memory-share.git

In the terminal:
![redux error](https://github.com/reduxjs/redux-toolkit/assets/60110696/6b744d87-503e-4531-8358-8bc9fdc84309)

`/package.json` :
![redux error package](https://github.com/reduxjs/redux-toolkit/assets/60110696/b00bd1a2-752d-4eb5-b685-2916baf11d92)

file paths: 
![redux error file path](https://github.com/reduxjs/redux-toolkit/assets/60110696/ddabcfe3-65b9-44e8-aba1-dc99c998e808)

**Comment by phryneas** [comment]
Your repo is private. Is your application wrapped in the React-Redux `Provider`?

(also, usage questions like this are usually not a case for the issue tracker, especially not in the wrong repository - this is redux-toolkit, not react-redux)

**Comment by yousuf4you** [comment]
Sorry, Sir, I made it public.

**Comment by phryneas** [comment]
That component is not wrapped in your `ReduxProvider` component. Add that in your `app/layout.tsx`.
