### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'actions')

### ISSUE THREAD

**Issue by arjunan123** [reduxjs/redux-toolkit#3438]
I am experiencing an issue with testing my Redux Toolkit code. Whenever I try to run the tests, I receive the following error message:
I am using @testing-library/react-native

FAIL __tests__/App-test.tsx
● Test suite failed to run

TypeError: Cannot read properties of undefined (reading 'actions')

  21 | });
  22 |
> 23 | export const {testAddReducer } = AppSlice.actions;
       |                                           ^
  24 | export default AppSlice.reducer;

  at Object.actions (app/redux/AppSlice.tsx:23:43)
  at Object.require (app/Store.tsx:2:1)
  at Object.require (App.tsx:5:1)
  at Object.require (__tests__/App-test.tsx:2:1)

Could someone please advise on how to solve this issue? Specifically, I would appreciate guidance on how to troubleshoot and fix the actions property issue in AppSlice.tsx.

**Comment by EskiMojo14** [comment]
could you post the whole file, including your createSlice call?

**Comment by phryneas** [comment]
My *guess* would be some kind of circular import triggered here by the jest module loader that due to some reason doesn't trigger in your real build. So.. keep an eye out for circular imports?

**Comment by arjunan123** [comment]
> 

this is my createSlice file 
import { createSlice ,PayloadAction} from "@reduxjs/toolkit";
import { appapi } from "../../api/apiClient";
import { hideAppSplash } from "./AuthSlice";
import { createMixpanelUser } from "../../config/util";

const appSlice = createSlice({
    name: "app",
    initialState: {
        user: null,
        loading: false,
        lastSession: {},
        todayStepsTarget: 0
    },
    reducers: {
        setUser(state, action) {
            state.user = action.payload;
        },
        resetUser(state) {
            state.user = null;
            state.lastSession = {};
        },
        setResetLoading(state, action) {
            state.loading = action.payload;
        },
        dailyTarget(state, action) {
            state.todayStepsTarget = action.payload;
        }
    },
});

export const { setUser, resetUser, setResetLoading,dailyTarget } = appSlice.actions;
export default appSlice.reducer;

**Comment by phryneas** [comment]
It doesn't seem like you export your slice, or it's `actions` object, so I think you also don't have anything called `AppSlice` in your test.
