### ISSUE TITLE
how to createSlice in a wrapper method and still let it infer types correclty

### ISSUE THREAD

**Issue by yurigenin** [reduxjs/redux-toolkit#344]
I'm new to TS and I need to convert a function that is a wrapper around the createSlice method.

The wrapper looks like this:

```
const createSliceWrapper = options => {
     <some extra code like logging>

     return createSlice(options);
}
```

when I call it like this:

```
const {actions: {test}} = createSliceWrapper({
   name: 'mySlice',
   initialState: {},
   reducers: {
        test: (state, {payload}) => {
              state.whatever = payload;
        }
   },
});
```
the test function does not get typed correctly and it is not callable. It seems that it has something to do with createSlice inferring types automatically and if I use the wrapper around it the types are not passed correctly. 

Can you suggest how to define the wrapper with generic parameters to overcome the issue?

Thank you!

**Comment by markerikson** [comment]
We've got an example of this in the docs at https://redux-toolkit.js.org/usage/usage-with-typescript#wrapping-createslice .  Also see #305 for a similar discussion.
