### ISSUE TITLE
transformResponse in enhanceEndpoints returning Promise type when trying to transform the type of the response

### ISSUE THREAD

**Issue by cini9** [reduxjs/redux-toolkit#3443]
Following the update to V1.9.4, with the ability to override TS type of the original data in transformResponse of enhanceEndpoints, the response type I am receiving in my components are being additionally transformed to add a Promise<> type of my desired response type. 

I am using codegen to generate types from my backend, but need to transform that response to extract lower-level data from the raw graphql query response.

```
type TransformedGetUser = GetUserQuery['getUser']
type TransformedGetUsers = GetUsersQuery['getUsers']

type Definitions = DefinitionsFromApi<typeof generatedUserApi>
type TagTypes = TagTypesFromApi<typeof generatedUserApi>

type UpdatedDefinitions = Omit<Definitions, 'getUsers' | 'getUser'> & {
  getUsers: OverrideResultType<Definitions['getUsers'], TransformedGetUsers>
  getUser: OverrideResultType<Definitions['getUser'], TransformedGetUser>
}

const userApi = generatedUserApi.enhanceEndpoints<TagTypes, UpdatedDefinitions>(
  {
    endpoints: {
      getUsers: {
        providesTags: ['User'],
        transformResponse: (response: GetUsersQuery): TransformedGetUsers =>
          response.getUsers,
      },
      getUser: {
        providesTags: ['User'],
        transformResponse: (response: GetUserQuery): TransformedGetUser =>
          response.getUser,
      },
    },
  }
)
```
This gives me the typing in the components in the screen shot below, with my correct type (id: string, firstName: string, etc) followed by the Promise<...> type.

![image](https://github.com/reduxjs/redux-toolkit/assets/56114997/4df6c49a-3ac6-45d8-b354-a02054ec989a)

When I try to use the data returned from these queries, I'm getting a 'property id does not exist on type Promise< .... >'

![image](https://github.com/reduxjs/redux-toolkit/assets/56114997/57bf894d-e854-4bcb-b64d-e6150f9077d6)

Is there any way to tell RTK to not add the Promise type when we are overriding the response type in transformResponse ?

Thanks in advance for your help !

**Comment by quentingirard** [comment]
@dmitrigrabov did you find any solution ?

Is there a way that I can help ?

**Comment by Mozzarella123** [comment]
The main problem is that transformResponse can return Promise in types. And when we use query data it become `MaybePromise`

<img width="949" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/22841455/9f61752c-30fd-41f1-8189-8464037f7d66">


https://github.com/reduxjs/redux-toolkit/blob/f31ff77ad01f6cdbdbbd4a701718ac8445e34b91/packages/toolkit/src/query/endpointDefinitions.ts#L79

**Comment by EskiMojo14** [comment]
Hi there, thanks for the report! Apologies for the slow response.

The issue appears to be that the utility type used to extract the result from the provided type didn't account for Promises, as the actual execution unwraps that promise.

I've opened #3500 that should fix this - if someone could try the build that's created from that PR, that'd be greatly appreciated.

In terms of overriding result types, we're investigating (over at #3485) the possibility of replacing `enhanceEndpoints` entirely, with two functions - `addTagTypes` and `enhanceEndpoint`. This would greatly simplify typings and use cases such as replacing return types.

```ts
const enhanced = api
  .addTagTypes('tag1', 'tag2')
  .enhanceEndpoint('query1', { providesTags: ['tag1'] })
  .enhanceEndpoint('mutation2', (definition) => {
    definition.invalidatesTags = ['tag2'];
  })
```

This is of course a big breaking change, so it would be held for RTK 2.0, clearly communicated, and a codemod would most likely be provided to ease the transition.

**Comment by cini9** [comment]
Hey @EskiMojo14 thanks for the fix ! I've checked it out as well and it seems to fix the Promise issue on my side as well !

**Comment by EskiMojo14** [comment]
great 😄

both of the other co-maintainers are at conferences this week so I'm unsure when we can get the fix reviewed, merged and published - will try to get it prioritised when possible 🙂

**Comment by quentingirard** [comment]
Hey @EskiMojo14,

Do you have any idea when it can be checked and released ?

**Comment by EskiMojo14** [comment]
it's been merged into master, but i'm not sure when the next release will be

**Comment by annaet** [comment]
@EskiMojo14 Any chance of getting a new release out including this fix? It would be really useful for my team 😄

**Comment by markerikson** [comment]
I'll look at trying to get out another release sometime today.

**Comment by quentingirard** [comment]
Hey !

Same as @annaet, would it be possible to get a new release this week ?

**Comment by annaet** [comment]
Hi @markerikson. Any updates on getting a new release out?

**Comment by cini9** [comment]
Hi @markerikson and @EskiMojo14, I hope you guys are doing well. Sorry to keep pushing this issue, but do you have any updates on when you plan to release this fix ? I am currently working with a specific commit bundle in my package.json, which I think may have expired and is no longer accessible as a yarn package. Any info would be greatly appreciated so that we can plan our releases accordingly.

Thanks !

**Comment by markerikson** [comment]
I'm on vacation for at least another week, and won't have time to think about doing any releases until after I'm back.

**Comment by cini9** [comment]
Alright thanks for the update ! Enjoy your vacation 🍸 🍺  🏖️

**Comment by annaet** [comment]
@cini9 If you are using yarn or pnpm you can use the `patch` command to apply this fix to your project. This is what I'm doing until we get a new release: https://yarnpkg.com/cli/patch

**Comment by EskiMojo14** [comment]
the npm equivalent would be using something like [patch-package](https://www.npmjs.com/package/patch-package)

**Comment by Valli-** [comment]
Would love to see this released @markerikson

**Comment by Davgus** [comment]
> Would love to see this released @markerikson

Isn't it already released in [v1.9.6](https://github.com/reduxjs/redux-toolkit/releases/tag/v1.9.6)?

**Comment by Valli-** [comment]
> > Would love to see this released @markerikson
> 
> Isn't it already released in [v1.9.6](https://github.com/reduxjs/redux-toolkit/releases/tag/v1.9.6)?

Ye, my bad, was on 1.9.5, a simpel upgrade solved my issue :)

**Comment by Innders** [comment]
Thanks @cini9 you really helped me solve this problem.

Now it's 2024 and we are on `2.2.5`. Has anything changed in your setup for this?

It seems that this part where you are overriding the types isn't very scalable, if you had 10 queries this would get pretty huge.
![image](https://github.com/reduxjs/redux-toolkit/assets/49156310/05535763-e3c4-47c3-8cd4-72c1f00958fc)

Also how do you find performance, it seems to take a good 20 seconds for my types to update, my macbook air M1 is struggling (for first time ever).

**Comment by cini9** [comment]
> Thanks @cini9 you really helped me solve this problem.
> 
> 1. Now it's 2024 and we are on `2.2.5`. Has anything changed in your setup for this?
> 2. How are you dealing with when you have to use `updateQueryData`. If you perform this on a query you have overwritten the types, the types of `draft` will still be the generated ones not your transformed ones.
> 3. Have you managed override the arguments type for queries/mutations?
> 4. How do you find performance, it seems to take a good 20 seconds for my types to update, my macbook air M1 is struggling (for first time ever).

Hey @Innders, I'm glad this discussion was able to help you solve this issue 😄. It is indeed useful to be able to modify the response type to fit our applications. I've tried to answer your questions above as best I could, but feel free to ask if you have any other questions. 

1.     Nothing has really changed in our setup for this. We are still using the OverrrideResultType utility that we're getting from the reduxjs lib. We try to code split as much as possible (where it makes sense of course) to simplify our files. My structure is as follows :
![Screenshot 2024-06-17 at 11 42 35](https://github.com/reduxjs/redux-toolkit/assets/56114997/e53e3fcb-54d6-4b81-9525-8a9654f703cd)
 Where "documents" is where we keep our graphql queries and mutations, "generated" is where codegen generates all of the types, APIs and so on, and "enhanced", where we essentially enhance the query and modify the type as needed :
![Screenshot 2024-06-17 at 11 44 29](https://github.com/reduxjs/redux-toolkit/assets/56114997/aeea59e0-c337-424f-a0cc-830985f39315)

2. I'm not 100% sure I understand what you mean for this one. We haven't used updateQueryData yet so I won't be able to provide any feedback on keeping the modified types for this one. If anyone else has this experience, please feel free to share your experience ! I'd also be glad to know if you figure out how to do this. 

3. We haven't yet had to modify the argument types for queries/mutations either. So far we've always defined exactly what we need for a mutation in our backend (which we try to keep as single source of truth), and codegen does a pretty good job of creating the input type. 

4. I have a Macbook Pro (pre M1) and honestly haven't noticed too much issue with performance. Typescript always takes a couple seconds to update everywhere when I change a type, but otherwise it doesn't lag too much.

**Comment by Innders** [comment]
> We try to code split as much as possible

Cool! I like your file structure... I might have to ~copy~ take inspiration from it. 😉 

> I'm not 100% sure I understand what you mean for this one. We haven't used updateQueryData

Let's say you enhance a simple query and then transform it so it just returns the number of edges in the response.

The first bit works great.

<img width="996" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/49156310/305b9374-ad8b-47ce-a862-271338a0a9cc">

Now let's say you want to update the cache of that same query using `updateQueryData` so you can optimistically update the cache or for whatever reason.

The draft for the cache uses the original query type not the transformed type (number).

<img width="1248" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/49156310/6232f89e-86c2-49a5-80c9-142d01b2eb4c">

Maybe this is a bug in `OverrideResultType` or something. If you haven't used it then I wouldn't expect any help but I'm just putting it out there for anyone else 😄 

> We haven't yet had to modify the argument types.

Makes sense as you would only ever need to have new arguments if you were using `onCacheEntryAdded`. It would be nice to have a place to pass "meta" or "other" data to queries that aren't explicitly tied to the query.

> I'd also love to get the community feedback.

This might be a good place: https://github.com/reduxjs/redux-toolkit/issues/3692

**Comment by EskiMojo14** [comment]
`enhanceEndpoints` cannot change the type of your existing API instance - you need to use the version it returns instead, which has updated types.

**Comment by Innders** [comment]
> you need to use the version it returns instead

That's so obvious 🤦

Works like a charm now, thank you so much! 🎉 

![image](https://github.com/reduxjs/redux-toolkit/assets/49156310/d9a55640-d9c1-4bbb-92e8-4fa75e2e5e18)
![image](https://github.com/reduxjs/redux-toolkit/assets/49156310/85b21a65-3db0-4505-aeec-c36ddf54660c)
