### ISSUE TITLE
RTK Query - Empty error object with custom $.ajax() baseQuery funciton

### ISSUE THREAD

**Issue by axonify-kwilson** [reduxjs/redux-toolkit#3445]
New to RTK Query and trying to create a custom `baseQuery` that uses `$.ajax()` instead of `fetch`. I have everything working for successful responses, however if an error occurs, the error object that is returned from the auto-generated api hook is always empty. I believe I've done everything asked [in the documentation here](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#implementing-a-custom-basequery).

My API:

```
export const someApi = createApi({
  reducerPath: 'someApi',
  baseQuery: ajaxBaseQuery({
    baseUrl: 'someUrl'
  }),
  endpoints: (builder) => {
    return {
      getSomeList: builder.query<void, void>({
        query: () => {
          return {
            url: 'someUrl'
          };
        },
      })
    };
  }
});

export const { useGetSomeListQuery } = someApi;
```

AjaxBaseQuery.ts:

```
export const ajaxBaseQuery = ({ baseUrl }: { baseUrl: string } = { baseUrl: '' }): BaseQueryFn<{
  url: string,
  method: string,
  params?: object,
  options: object
}> => {
  return ({
    url,
    method = 'PUT',
    params,
    options
  }) => {
    const ajaxOptions = {
      url: getUrl(baseUrl, url, (params as Record<string, string>)),
      type: method,
      ...options
    };

    return Promise.resolve($.ajax(ajaxOptions).then(getSuccess, (xhr: JQuery.jqXHR) => {
      return {
        error: {
          data: xhr.responseJSON
        }
      };
     });
   };
};
```

My component:

```
export default function GameScoresView(): JSX.Element {
  const queryObj = useGetSomeListQuery();
  const { data } = queryObj;
  ...
}
```

After the rejection occurs, I can see in my browser dev tools that RTK Query does in fact recognize that a rejection did occur, however the error object that I'm attempting to return in `AjaxBaseQuery.ts` is not there - instead just an empty object:
![image](https://github.com/reduxjs/redux-toolkit/assets/33638627/1facd55f-2e70-4db4-beec-79aed93bb5ae)

In my dev tools console, I do see `react_devtools_backend_compact.js` logging the error I was expecting from my `AjaxBaseQuery.ts` return:
![image](https://github.com/reduxjs/redux-toolkit/assets/33638627/4da931b3-6f60-4221-84ef-38c52aa07a8c)

I have tried stepping through some RTK Query source code to see if I can find a cause but finding that quite difficult. Any help is greatly appreciated.

**Comment by phryneas** [comment]
Have you tried adding a `console.log` in that error handling code, to see if it is actually called, and also to see what is being returned?

I'm sorry, but I stopped using jQuery for good half a decade ago (and tbh. had not expected to ever see it again), it might get hard to help you, especially just from screenshots.

**Comment by axonify-kwilson** [comment]
> Have you tried adding a `console.log` in that error handling code, to see if it is actually called, and also to see what is being returned?
> 
> I'm sorry, but I stopped using jQuery for good half a decade ago (and tbh. had not expected to ever see it again), it might get hard to help you, especially just from screenshots.

I have stepped through my error handling code and can confirm it's being called and returning what I expect. By the time my component renders again after this point however, the error property shows as an empty object returned from the hook sadly.

**Comment by phryneas** [comment]
And looking at the Redux devtools, what does the action look like?

**Comment by axonify-kwilson** [comment]
Action showing the same - empty error object like it cannot see what I attempt to return in the error handling logic

![image](https://github.com/reduxjs/redux-toolkit/assets/33638627/cb5fcf1e-0e7d-4ed7-bd2f-d021d85a7899)

**Comment by EskiMojo14** [comment]
out of curiosity, why *are* you using jQuery to fetch?

**Comment by axonify-kwilson** [comment]
> out of curiosity, why _are_ you using jQuery to fetch?

I won't get into details but this can be chalked up to limitations of legacy code at a higher level on the project I'm working on where we wish to integrate with RTK Query

**Comment by phryneas** [comment]
But it runs inside a browser that is not Internet Explorer, right? Fetch is part of every browser that shipped since 2015.

**Comment by axonify-kwilson** [comment]
> But it runs inside a browser that is not Internet Explorer, right? Fetch is part of every browser that shipped since 2015.

Correct but I'm required to support IE11 and an existing ajax layer in our architecture for reasons I'm not going to get into detail here. Looking for answers & workarounds not shame :P Really hopeful we can still move forward with RTK Query

**Comment by markerikson** [comment]
@axonify-kwilson I don't think there's anything we can do without being able to see the behavior for ourselves.  Can you capture a Replay of this happening and share it with us? 

https://replay.io/record-bugs

(If necessary, you can share it with just me/Lenz privately via adding our emails to the allowed list for the recording)

**Comment by phryneas** [comment]
Alternatively, go a few steps back: write a baseQuery without that jQuery ajax call and have that return an error, then slowly iterate from there, reintroducing your jQuery stuff.

(Just to make really sure: a [fetch polyfill](https://github.com/github/fetch) for IE is not an option? Adding jQuery here just means that you'll have even more difficulties ever migrating away from this)

**Comment by axonify-kwilson** [comment]
After working a little more at this, for reasons unknown, using async/await in place of `Promise.resolve` works just fine in error scenarios. Got this idea after studying `fetchBaseQuery`'s source a little more closely: 

```
export const ajaxBaseQuery = ({ baseUrl }: { baseUrl: string } = { baseUrl: '' }): BaseQueryFn<{
  url: string,
  method: string,
  params?: Record<string, string>,
  options: Record<string, unknown>
}> => {
  return async ({
    url,
    method = 'GET',
    params,
    options
  }) => {
    const ajaxOptions = {
      url: getUrl(baseUrl, url, params),
      type: method,
      ...options
    };

    let response;
    try {
      response = await $.ajax(ajaxOptions);
    } catch (e) {
       return {
         error: {
           data: xhr.responseJSON
         }
      }
    }

    return getSuccess(response);
  };
};
```
