### ISSUE TITLE
Pass ephemeral arguments to queries/mutations

### ISSUE THREAD

**Issue by szalayak-nttdata** [reduxjs/redux-toolkit#3447]
When using RTK query with nextjs (with next-redux-wrapper, as suggested by the documentation), I'd like to be able to pass in authorisation tokens or other ephemeral values to queries without them being stored in the redux store. I'm aware that JWT tokens in cookies can be used in most situations, but some APIs will not support that.

The issue is that in order to hydrate the component, the initialState of the store is passed in via pageProps to the page, which is visible in the Network tab of Chrome during client side navigation. 

The issue occurs when I make a call using a query during getServerSideProps, which I then replicate within the component with the use* hook for the same query (this correctly uses the cached value passed in from getServerSideProps). 

This creates a security vulnerability where my tokens that were previously only stored on the server become visible to the client. If there was another optional parameter (extraOptions/secretValues/etc.), it would also help passing in values that I don't want serialised in the key but need to use in the request anyway.

**Comment by phryneas** [comment]
I feel that you are abusing RTK Query for something it is not really meant for here - RTK Query is made for making requests from the browser, and SSR prefetching is only an edge case to preload some data. The purpose of RTK Query is not to make requests only on the server, and never on the browser. (And it seems like without your tokens, they would not be possible from the browser.)

If you want to make requests only on the server and never on the browser, why not just send off a `fetch` call and pass the result in as props?

Apart from all that: you should be able to do this if you add those tokens in `baseQuery`, not as part of the query args.
