### ISSUE TITLE
Pass ephemeral arguments to queries/mutations

### ISSUE THREAD

**Issue by szalayak** [reduxjs/redux-toolkit#3448]
When using RTK query with nextjs (with next-redux-wrapper, as suggested by the documentation), I'd like to be able to pass in authorisation tokens or other ephemeral values to queries without them being stored in the redux store. I'm aware that JWT tokens in cookies can be used in most situations, but some APIs will not support that.

The issue is that in order to hydrate the component, the initialState of the store is passed in via pageProps to the page, which is visible in the Network tab of Chrome during client side navigation.

The issue occurs when I make a call using a query during getServerSideProps, which I then replicate within the component with the use* hook for the same query (this correctly uses the cached value passed in from getServerSideProps).

This creates a security vulnerability where my tokens that were previously only stored on the server become visible to the client. If there was another optional parameter (extraOptions/secretValues/etc.), it would also help passing in values that I don't want serialised in the key but need to use in the request anyway.

**Comment by phryneas** [comment]
I feel that you are abusing RTK Query for something it is not really meant for here - RTK Query is made for making requests from the browser, and SSR prefetching is only an edge case to preload some data. The purpose of RTK Query is not to make requests only on the server, and never on the browser. (And it seems like without your tokens, they would not be possible from the browser.)

If you want to make requests only on the server and never on the browser, why not just send off a fetch call and pass the result in as props?

Apart from all that: you should be able to do this if you add those tokens in baseQuery, not as part of the query args.

**Comment by szalayak** [comment]
While I agree that it's a bit of an edge case, especially because I can only access the token as a request header, due to the authentication flow, so I can't use baseQuery prepareHeaders for this. I followed the official documentation when I set this up, and the claim is that SSR is supported. I also use it to make requests from the browser, but in some cases I'd like the data to be available when rendered on the server side as well. Although this will probably become obsolete with the new next approuter anyway.

**Comment by szalayak** [comment]
I tried that - the issue is if I put the token in the redux store, it'll still get passed in to the page on hydration, just in a different slice of the same store. I could put it into global memory/session if I must, but I thought having an extra set of ephemeral arguments could be useful for a number of reasons.

**Comment by phryneas** [comment]
You can remove it from the store before the end of your `getServerSideProps` function.

I don't think we will add any kind of `ephemeral arguments`. The point is that you need to always use the same arguments to access a cache value. These arguments also *need* to be kept around, or otherwise the `refetch` function would not work (because how would it ever know which arguments to refetch?).

**Comment by szalayak** [comment]
Yeah there is indeed a workaround - and you raise a good point with refetch. Thanks, I will try a workaround then!
