### ISSUE TITLE
[RED-18] Export buildHooks function

### ISSUE THREAD

**Issue by lucashm** [reduxjs/redux-toolkit#3450]
I have a specific use case, where I'm using redux-toolkit through module federation, so all my micro-frontends can access it. The problem is that every micro-frontend has its own React instance, and the exported hooks from the ReactModule won't work as we can't call one Hook from different React versions.

My current solution is basically copying and pasting the code from the `buildQueryHooks` and `buildMutationHooks` functions, but it would make everything way cleaner if the function `buildHooks` were available!

Thanks for reading

Edit: Already created a PR since it's a really small change: https://github.com/reduxjs/redux-toolkit/pull/3451

<sub>[RED-18](https://linear.app/redux/issue/RED-18/export-buildhooks-function)</sub>

**Comment by phryneas** [comment]
But you don't have half of the arguments for `buildHooks` available outside of the api.

Especially `context` is internal, and as we treat this api as internal, we will add any number of new arguments at any moment in time. Exporting the function would prevent us from doing that, and every new required argument we added would be a breaking change and need a new major release.

I'm sorry, but we cannot do that.
