### ISSUE TITLE
refetchOnMountOrArgChange got unexpected values on component's mount

### ISSUE THREAD

**Issue by d42f** [reduxjs/redux-toolkit#3453]
[Example](https://codesandbox.io/s/floral-cloud-bpfovp)

If I destroy a component (contains query hook which has option { refetchOnMountOrArgChange: true }) and render it again.
Then I get unexpected values during the first render. For example isFetching is false but I thing it has to be true.

**Comment by broshkabro** [comment]
I faced with the same issue: when `refetchOnMountOrArgChange` is `true`, `isFetching` is set to `false` during the first render.

**Comment by phryneas** [comment]
The first render is `isUninitialized: true` if you have a custom `selectFromResult` function. We just have the convenience in the default `selectFromResult` that fakes that a fetch started even before it actually started (fetching is an effect and as such will start after render), so you have one less case to handle.

**Comment by d42f** [comment]
> The first render is `isUninitialized: true` if you have a custom `selectFromResult` function. We just have the convenience in the default `selectFromResult` that fakes that a fetch started even before it actually started (fetching is an effect and as such will start after render), so you have one less case to handle.

I think you didn't correctly understand my example.

**Comment by phryneas** [comment]
Ah, yeah, that explanation was not clear to me.
Yes, that's to be expected - the data is there after all, even when it is being refetched (as it is an effect and effects are called after render, after the first render).   
Personally, I would always display that data and only gray it out while loading, but you can truly want to avoid that, you could do something like
```js
  const [initialRender, setInitialRender] = useState(true);
  useEffect(() => {
    setInitialRender(false);
  }, []);

  return (
    <>
      {initialRender || isFetching || isUninitialized ? (
        <p>Loading...</p>
 
```

**Comment by d42f** [comment]
> Ah, yeah, that explanation was not clear to me. Yes, that's to be expected - the data is there after all, even when it is being refetched (as it is an effect and effects are called after render, after the first render). Personally, I would always display that data and only gray it out while loading, but you can truly want to avoid that, you could do something like
> 
> ```js
>   const [initialRender, setInitialRender] = useState(true);
>   useEffect(() => {
>     setInitialRender(false);
>   }, []);
> 
>   return (
>     <>
>       {initialRender || isFetching || isUninitialized ? (
>         <p>Loading...</p>
>  
> ```

Yes, it's an expected workaround, I've just wanted to attract an attention for this case. Should I close this issue?

**Comment by phryneas** [comment]
Yeah, I'd say this should probably closed.  
In your case, `isLoading` is `false` - which indicates the presence of data, albeit slightly outdated one. I personally would only show a loading indicator and maybe gray the data out in a `isFetching` state.     
It's a bit unfortunate with what you want to do, but with React without suspense, we can only start fetching data after the component has rendered, not before.
