### ISSUE TITLE
Require enhancer to be a callback

### ISSUE THREAD

**Issue by EskiMojo14** [reduxjs/redux-toolkit#3457]
When the enhancers field is an array, it completely overrides enhancers and thus middlewares are not included (as of https://github.com/reduxjs/redux-toolkit/pull/3347).

This is too much of a footgun - instead, we should require enhancers to be a callback. This would make it more obvious that `getDefaultEnhancers` should be used.

**Comment by markerikson** [comment]
Done in #3461
