### ISSUE TITLE
configureStore returning any type

### ISSUE THREAD

**Issue by MarouaniALA** [reduxjs/redux-toolkit#3462]
`typeof store.getState` should return type of state but it returns any type here is my files
```
import {configureStore} from '@reduxjs/toolkit'
import LoaderSlice from "./features/LoaderSlice";

export const store = configureStore({
    reducer: {
        loader: LoaderSlice
    },
    middleware: (getDefaultMiddleware) => getDefaultMiddleware({
        serializableCheck: false
    })
})

// Infer the `RootState` and `AppDispatch` types from the store itself
export type RootState = ReturnType<typeof store.getState>
// Inferred type: {posts: PostsState, comments: CommentsState, users: UsersState}
export type AppDispatch = typeof store.dispatch

```
LoaderSlice.ts
```
import {createSlice} from '@reduxjs/toolkit'
import type {PayloadAction} from '@reduxjs/toolkit'

export interface LoaderState {
    isLoading: boolean
}

const initialState: LoaderState = {
    isLoading: false,
}

export const LoaderSlice = createSlice({
    name: 'loader',
    initialState,
    reducers: {
        updateLoader: (state, action: PayloadAction<boolean>) => {
            state.isLoading = action.payload;
        }
    },
})

// Action creators are generated for each case reducer function
export const {updateLoader} = LoaderSlice.actions

export default LoaderSlice.reducer

```

**Comment by phryneas** [comment]
If you look at [this TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMYQHYDNgHMCuUCmAyjNPgL5zpQQhwDkAAgQCY4AeAVgM4D0JEAGwDWwGHQBQoSLERICAQxhEBwJOUrVajFu258IgkWMnho8GAE8w+RAAV5FgRHnMAgkhjA0FKjXpN8Vk5efmFRCXF8Nml4YFQlKHR5NTgAGWdmfChiRRsEcThCuGAudJc4rAAuOAAjAwF8eVRxMnFxFFQuWNRRYHkBHKVqsszsmFy4AF5EAqKSkYrqpIEufAAaFraomLgOrrSMrMIVFOm5RqVj1XwACnyiuFR5EHxquicXLLoNh7je-sG61mhR0aigXGq9weRRwYGYuRGWWqNy6uTWcGSnjQ1Xsjgy7ixqAAPHVBI1UAA+ACUUwpM2hDLgqKUADp5hkKlMMR4vKgWWAHB9mABuYHQ1oPMgbMhUto8HhwAm83YKEjgjEEOBYfCoLK5ZiUaBwRpIAAWu3kqzgoKylBwqB5aEi0TMuzQ+wQsPhSkRUAo019VzULMxvK4bWdOz28C6pC5HUwuAIxFIdzFNqgkLFDyFSIOn2yJ3wLIzYqlYpAwGYzAaAHd5ARkdqYAARfBJHACGAAWSrNfw9YINMmdObbY7Xd71brDduUIZqygfRUAC95DUGgBhU34JBCJb9VZl2UyuUKgCSGFtMB3cAABgAlAwwQF3jGoA131xgMAtkoCmAzTfSxrC4DQ-BvGxY01URVgEdBI1dECbCfCAX3GJQuQffAYDwVAABUrHwIlkIgdAmTVYtm0BClxHlRloQAPQAfjPOBL3QLIWDgZDIUgLoITgWwIAEwF0RQEAXniQTNxoKSYC4MS4BwRdBIAVVUwFWm2JCiMVH8-y4ACzS5UjyOg4tmH-RQzTohUGKKFigA), that seems to work perfectly fine for me.

What IDE & TypeScript version are you using?

**Comment by MarouaniALA** [comment]
IDE: Intellij
"typescript": "^4.6.3"
i have an other project it works with the exact same configuations

**Comment by phryneas** [comment]
Please open the project in VSCode and see how it works there. IntelliJ has a number of known bugs with stuff like that, as they are not using the official TypeScript language server, but implemented their own version of it, which takes shortcuts to be "faster" and sometimes does very weird things.

**Comment by MarouaniALA** [comment]
the weird that i have another project with the exact same versions and all going right

**Comment by MarouaniALA** [comment]
problem solved go to settings -> languages & framework -> typescript and select typescript language service
