### ISSUE TITLE
rtk-query-codegen-openapi auth (custom headers for swagger url)

### ISSUE THREAD

**Issue by Mozzarella123** [reduxjs/redux-toolkit#3468]
## Problem 
I can't parse swagger schema with authorization required url

## Solution 

Would be great if i can pass headers or control auth in config file

https://github.com/reduxjs/redux-toolkit/blob/e92993813a95d9165e0df77cf52573d6021a6fa8/packages/rtk-query-codegen-openapi/src/index.ts#L14-L17

https://github.com/reduxjs/redux-toolkit/blob/e92993813a95d9165e0df77cf52573d6021a6fa8/packages/rtk-query-codegen-openapi/src/generate.ts#L97

https://github.com/reduxjs/redux-toolkit/blob/e92993813a95d9165e0df77cf52573d6021a6fa8/packages/rtk-query-codegen-openapi/src/utils/getV3Doc.ts#L8

https://github.com/APIDevTools/swagger-parser/blob/main/docs/swagger-parser.md#bundleapi-options-callback

> bundle(api, [options], [callback])
api (required) - string or object
A [Swagger Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object), or the file path or URL of your Swagger API. See the [parse](https://github.com/APIDevTools/swagger-parser/blob/main/docs/swagger-parser.md#parseapi-options-callback) method for more info.

> options (optional) - object
See [options](https://github.com/APIDevTools/swagger-parser/blob/main/docs/options.md) for the full list of options

https://github.com/APIDevTools/swagger-parser/blob/main/docs/options.md#resolve-options

> http.headers - You can specify any HTTP headers that should be sent when downloading files. For example, some servers may require you to set the Accept or Referrer header.

**Comment by markerikson** [comment]
Should be live in https://github.com/reduxjs/redux-toolkit/releases/tag/%40rtk-query%2Fcodegen-openapi%402.0.0-alpha.0 ! Please try it out and let us know if it works.
