### ISSUE TITLE
Dynamic tagTypes causing errors in the console

### ISSUE THREAD

**Issue by atakangktepe** [reduxjs/redux-toolkit#3469]
Hey,

First, thanks for this awesome project! It's truly a lifesaver for us. I'm currently facing an issue that occurs on my console when I try to generate tagTypes dynamically.

<img width="597" alt="Screenshot 2023-05-23 at 14 10 40" src="https://github.com/reduxjs/redux-toolkit/assets/12830048/1b6da30d-1994-4915-9a3c-58b101d72bcc">

## To clarify the process, here's how it works:

- We need to fetch tagTypes from an API since our users can generate and modify UIs from the same dashboard.
- We have been providing and invalidating the tags, as shown in the following code snippet:
<img width="782" alt="Screenshot 2023-05-23 at 14 15 57" src="https://github.com/reduxjs/redux-toolkit/assets/12830048/d5b7379f-f048-45ec-8bd0-9d4d55cb87a4">

Let me know if you need any further information or missing details in the context.

**Comment by EskiMojo14** [comment]
Tag types cannot be dynamic - they need to be provided either during createApi or enhanceEndpoints.

Only tag IDs can be dynamic.

**Comment by phryneas** [comment]
Which mean you could have `{ type: "generic", id: "collectionList:23" }` instead of `{ type: "collectionList", id: 23 }`

**Comment by atakangktepe** [comment]
BTW, it simply throws an error in the console, but it doesn't break any functionality. So, if there's a way to opt-out or disable the console errors, that would be great. And imo, the message should be printed with `console.warn` instead of `console.error` since it doesn't break anything.

**Comment by fkiDev** [comment]
Is there a way to invalidate a tag without refetch immediately. My use case: add post invalidate my posts, but do not fetch my posts till i enter the screen of my posts

**Comment by phryneas** [comment]
@fkiDev everything not on screen will not be refetched, but removed from cache. It will only be fetched when you visit a screen that needs this data again.

**Comment by fkiDev** [comment]
@phryneas the actual behaviour i had said the opposite, i have my posts screen and another screen to add post, if i enter directly to add post without passing by my posts screen it works fine without fetching my posts. But when i navigate first to my posts screen and then to add post, the invalidation refetch  my posts

**Comment by phryneas** [comment]
Are these React native screens? If yes, you are aware that  in some cases these never unmount, but just stay "to the side"? RTK Query has no way of knowing that.

**Comment by fkiDev** [comment]
@phryneas  yes react native and you are right, it was helpful. thank you

**Comment by Grapedge** [comment]
I have a similar scenario, I treat each tag as a subset, I would provide these tags:
```tsx
// for list:
[
  { type: "generic", id: "dynamicSource" },
  { type: "generic", id: "dynamicSource:LIST" },
  { type: "generic", id: "dynamicSource:23" },
  { type: "generic", id: "dynamicSource:24" },
]
```
