### ISSUE TITLE
createSlice hinders intellisense and causes import complexity

### ISSUE THREAD

**Issue by waynebloss** [reduxjs/redux-toolkit#347]
Today I started making a trial app with `@reduxjs/toolkit` and I can see that we're not going to be able to use it because all of the actions coming out of `createSlice` are defaulting to type `(payload: any): { type: string, payload: any }`. Also the issue of circular references mentioned in [the docs](https://redux-toolkit.js.org/api/createSlice#return-value) might cause problems for us and I'd hate to have to define slices differently for edge cases since the system we use now works in all cases.

I don't think you're going to be able to change this without completely reworking `createSlice`. However, I just wanted to show you what I'm coming from for comparison and to give you some insight from a senior dev at a large consulting firm that uses React/Redux heavily.

We define all of our actions, reducers and selectors for each slice of state in a separate file. Our project structure looks something like the tree shown below. With this very simple and straightforward structure, we're able to do everything we need to. Importing another slice's actions is a matter of doing `import { OtherSliceActions } from "../otherSlice/actions";` We also get perfect intellisense and as you can see - zero external imports in each file.

I know this is more boilerplate but it's really simple, non-magical boilerplate that we have snippets for. **Good intellisense and uniformity is more important to us than less boilerplate.**

### Project Structure

- assets/
- components/
- layouts/
- lib/
- pages/
- state/
  - auth/
  - prefs/
  - ui/
    - actions.js
    - selectors.js
    - state.js

In `state/ui/actions.js`:
```js
const type = {
  UI_LOADING_SET: "UI_LOADING_SET",
  UI_NOTIFICATION_SHOW: "UI_NOTIFICATION_SHOW",
  UI_NOTIFICATION_HIDE: "UI_NOTIFICATION_HIDE",
};

export const UIActions = {
  type,

  hideNotification() {
    return { type: type.UI_NOTIFICATION_HIDE };
  },

  setUILoading(value) {
    return { type: type.UI_LOADING_SET, value };
  },

  showError(message = "There was an error processing your request.") {
    return UIActions.showNotification(message, "error");
  },

  showNotification(message, variant, duration) {
    if (duration === undefined && variant !== "error") {
      duration = 15000;
    }
    return { type: type.UI_NOTIFICATION_SHOW, message, variant, duration };
  },

  showUpdated(message = "Your changes have been submitted.") {
    return UIActions.showNotification(message);
  },
};
```

In `ui/selectors.js`:
```js
export function uiLoading(state) {
  const {
    ui: { loading },
  } = state;
  return {
    uiLoading: loading,
  };
}

export function uiNotification(state) {
  const {
    ui: { notification },
  } = state;
  return {
    uiNotification: notification,
  };
}
```

In `ui/state.js`:
```js
import { UIActions } from "./actions";
/**
 * UI state (**NOT** persisted).
 * @example
 * {
 *    loading: false,
 *    notification: { duration: number, message: string, variant: "" | "error" }
 * }
 */
export const UIState = {
  name: "ui",
  persist: false,
  defaults: {
    loading: false,
  },
  handlers: {
    [UIActions.type.UI_LOADING_SET](state, { value }) {
      return {
        ...state,
        loading: value,
      };
    },
    [UIActions.type.UI_NOTIFICATION_HIDE](state) {
      return {
        ...state,
        notification: undefined,
      };
    },
    [UIActions.type.UI_NOTIFICATION_SHOW](state, { type, ...notification }) {
      return {
        ...state,
        notification,
      };
    },
  },
};

```

Some files not shown:

- state/
  - index.js - exports states.js, store.js and anything we need from `redux`, `react-redux` plus an enhanced version of `connect`.
  - states.js - exports all slice states as an array. exports all slice actions and selectors.
  - store.js - imports states.js array, builds reducers, sets up persist, exports store.

I can hear the criticisms already. "If I want better intellisense why not use TypeScript." and "Circular imports are indicative of a bad design." and so forth... suffice it to say though that we get cornered into a bad design once in a while and we don't do TypeScript for our frontends for reasons. Our opinions on Redux usage are just too different. So, I'm going to have to break up with you RTK - our relationship was very brief but I wish you the best of luck and thank you for your efforts!

**Comment by markerikson** [comment]
Erm... I'm confused.  None of the examples you're showing are uses of `createSlice`.

And yes, if you really do want correct intellisense, TS is the right answer.  I'm not sure how you'd get _any_ meaningful intellisense with something like this, at least in terms of knowing what the type of `value` is:

```js
  setUILoading(value) {
    return { type: type.UI_LOADING_SET, value };
  },
```

**Comment by waynebloss** [comment]
I cut out some of the docs. We typically use JSDoc comments to describe `@param` types and `@typedef`s for our more complex types.

These are not examples of `createSlice` as I mentioned - they are examples of a very clear and concise kit that we're currently using.

**Comment by waynebloss** [comment]
We don't use `payload` everywhere either. So, for instance `showNotification(message, variant, duration)` gives us a higher degree of intellisense.

**Comment by markerikson** [comment]
So... you're using JSDoc, and not TS?  Seems like that involves even more effort than it would to just use TS.  (Not saying you _have_ to use TS, just that it's a somewhat surprising approach to use.)

FWIW, both `createAction` and `createSlice` do support multi-arg action creators via the "prepare callback" syntax:

https://redux-toolkit.js.org/api/createAction#using-prepare-callbacks-to-customize-action-contents

https://redux-toolkit.js.org/api/createSlice#customizing-generated-action-creators

https://redux-toolkit.js.org/tutorials/intermediate-tutorial#implementing-todo-ids

**Comment by waynebloss** [comment]
Yes, we just use JSDoc to give intellisense where needed. We don't like TypeScript on the frontend because from what we've seen, it adds about 30% more work from just setting it up, typing everything and then working around it when typings don't describe reality.

I didn't see the `prepare` callback thing before - there was no intellisense for that - but I guess I should have read the docs more closely. This is not a rebuttal in any way - but I just don't like it. It's more complex than what we're doing.

I left this issue open for discussion; please close it at your convenience.

**Comment by markerikson** [comment]
Yeah, ultimately it's your codebase and you should do whatever you feel works best for your team.  I'd just argue that given the overall stated goals (uniformity, intellisense, etc), RTK + TS does directly address those concerns, and minimizes the actual amount of code you'd have to write.

**Comment by waynebloss** [comment]
@markerikson I got this working very nicely now. Thanks for addressing all of my objects, I really appreciate the push back.

I had to use Typescript to get any sort of decent intellisense, but doing it in Redux state is a great place to start using Typescript on the frontend IMO. Now I get perfect intellisense for calling Redux actions and getting state from selectors throughout the rest of the project.

Here's a little preview of my project structure if anyone else is looking:

In `state/ui/state.ts`:
```ts
import { createSlice, PayloadAction } from "@reduxjs/toolkit";

export interface UINotification {
  message: string;
  variant?: string;
  duration?: number;
}

export interface UIState {
  loading: boolean;
  notification: UINotification | undefined;
  sidebarWidth: number;
}

const uiSlice = createSlice({
  name: "ui",
  initialState: {
    loading: false,
    notification: undefined,
    sidebarWidth: 200,
  } as UIState,
  reducers: {
    hideUINotification(state) {
      state.notification = undefined;
    },
    setUILoading(state, { payload }: PayloadAction<boolean>) {
      state.loading = payload;
    },
    setUISidebarWidthDelta(state, { payload }: PayloadAction<number>) {
      state.sidebarWidth += payload;
    },
    showUINotification(state, { payload }: PayloadAction<UINotification>) {
      if (!payload.duration) {
        payload.duration = 15000;
      }
      state.notification = payload;
    },
  },
});

const stateInfo = {
  ...uiSlice,
  persist: false,
};
export default stateInfo;
```

In `state/ui/actions.ts`:
```ts
import { default as stateInfo } from "./state";

const { actions } = stateInfo;

export const UIActions = {
  ...actions,

  showUIError(message = "There was an error processing your request.") {
    return actions.showUINotification({ message, variant: "error" });
  },

  showUIMessage(message: string) {
    return actions.showUINotification({ message });
  },
};
```

In `state/ui/selectors` (very simple selectors just for testing...):

```ts
import { AppState } from "../states";

export function uiLoading(state: AppState) {
  return state.ui.loading;
}

export function uiNotification(state: AppState) {
  return state.ui.notification;
}

export function uiSidebarWidth(state: AppState) {
  return state.ui.sidebarWidth;
}
```

We tie it all together in `state/states.ts`:

```ts
import { default as ui, UIState } from "./ui/state";
import { AppStateInfo } from "./store";

// Export Actions, Selectors
export * from "./ui/actions";
export * from "./ui/selectors";

export type AppState = {
  ui: UIState;
};

const states: AppStateInfo[] = [
  // Export States
  ui,
];
export default states;
```

We export to the rest of the app from `state/index.ts`:

```ts
export { useDispatch, useSelector, useStore } from "react-redux";
// Local
export * from "./states";
export * from "./store";
```

And of course we create the store and combine our reducers in `state/store.ts`:

```ts
import { configureStore, getDefaultMiddleware, Slice } from "@reduxjs/toolkit";
import {
  KEY_PREFIX,
  persistCombineReducers,
  persistStore,
} from "redux-persist";
import storage from "redux-persist/lib/storage";
// Local
// import { __DEV__, REACT_APP_PERSIST_KEY } from "../config";
import appStates from "./states";

export interface AppStateInfo extends Slice {
  persist?: boolean;
  preload?: boolean;
  purge?: boolean;
}

const __DEV__ = process.env.NODE_ENV === "development";
const persistKey = "app"; // REACT_APP_PERSIST_KEY || "app";

// Map appState reducers.
const reducerMap = (function mapStates() {
  /** Slice names to purge from storage when `purgeStore` is called. */
  const defaultPurgeKeys: string[] = [];
  /** Slice names to prevent from storage. */
  const noPersist: string[] = [];
  /** Each sub-reducer function by slice name. */
  const reducers: any = {};
  /** States preloaded from localStorage by slice name. */
  let preloadedState: any;

  // Preload state
  const storageObject = (function preloadState() {
    // This is only possible since we're using localStorage which we can access
    // synchronously. It's simpler than using `redux-persist/PersistGate`.
    const storageKey = `${KEY_PREFIX}${persistKey}`;
    const storageValue = localStorage.getItem(storageKey);
    return storageValue ? JSON.parse(storageValue) : undefined;
  })();

  appStates.forEach(appState => {
    const {
      name,
      persist: shouldPersist = false,
      preload: shouldPreload = true,
      purge: shouldPurge = true,
    } = appState;
    if (!shouldPersist) {
      noPersist.push(name);
    } else if (shouldPreload && storageObject && storageObject[name]) {
      if (preloadedState === undefined) preloadedState = {};
      preloadedState[name] = JSON.parse(storageObject[name]);
    }
    if (shouldPurge && shouldPersist) {
      defaultPurgeKeys.push(name);
    }
    reducers[name] = appState.reducer;
  });
  return {
    defaultPurgeKeys,
    noPersist,
    reducers,
    preloadedState,
  };
})();

const rootReducer = persistCombineReducers(
  {
    blacklist: reducerMap.noPersist,
    debug: __DEV__,
    key: persistKey,
    storage,
  },
  reducerMap.reducers,
);

export const store = configureStore({
  middleware: getDefaultMiddleware({ serializableCheck: false }),
  preloadedState: reducerMap.preloadedState,
  reducer: rootReducer,
});

export const persistor = persistStore(store);
```

**Comment by waynebloss** [comment]
One last note for any readers: The `defaultPurgeKeys` built up in `function mapStates` is never used, you should just remove i.

**Comment by markerikson** [comment]
Cool, glad you got that working out!

**Comment by yuchant** [comment]
@waynebloss did you ever solve patterning issues when executing a thunk that is referenced in `extraReducers`? I feel like it's another circular import rabbit hole and I'm not sure what to do.

**Comment by markerikson** [comment]
@yuchant that's one reason why thunks typically ought to go in the same slice file.

**Comment by phryneas** [comment]
@yuchant if you get into a circular type dependency, you can break that on the type level by doing a single type declaration somewhere in the circle.
Usually the best place to do that is by typing the reducer explicitly, so
```ts
export default slice.reducer as Reducer<typeof initialState>
```

**Comment by waynebloss** [comment]
@yuchant I don't use `extraReducers`. Instead, I create a whole separate file called `actions.ts` and I import the return value of `createSlice` from my `state.ts` files and merge those actions into the object exported from my `actions.ts` file. You can see that in my last example.

**Comment by waynebloss** [comment]
Regarding the TypeScript types, I now have a `types.ts` file in my top `src/state` folder. It looks like this:

```ts
import { Action, Slice, ThunkAction, ThunkDispatch } from "@reduxjs/toolkit";
// Local
import { AppState } from "./states";

export type { AppState };

export interface AppStateInfo extends Slice {
  persist?: boolean;
  preload?: boolean;
}
/**
 * Type to return from async actions (redux-thunk).
 * `R` describes the return value of the thunk.
 * `E` describes the extra argument type given to the action thunk, e.g.
 * `(dispatch, getState, extraArgument) => {}`
 */
export type AppThunk<R = Promise<void>, E = unknown> = ThunkAction<
  R,
  AppState,
  E,
  Action<string>
>;
/**
 * Dispatch function for this application (AppState).
 * `E` describes the extra argument type given to the action thunk, e.g.
 * `(dispatch, getState, extraArgument) => {}`
 */
export type AppThunkDispatch<E = unknown> = ThunkDispatch<
  AppState,
  E,
  Action<string>
>;
```

**Comment by yuchant** [comment]
@waynebloss I meant _if_ you needed a reducer that imports actions inside `state.ts` which it turns out your pattern solves as well!

Thank you for sharing your pattern, its helped a lot! I was extremely stuck with this new redux pattern because the pattern to write "first pass" actions directly in `createSlice` differed from the way I'd write a future change like calling a thunk that depends on createSlice outputs. You know, the kind of change that happens organically in development. Create your actions, realize you needed a thunk later, have thunk dispatch more foundational actions.

With your method of moving actions to an `actions.ts` file, we can have a singular interface to import slice actions for both simple/complex patterns, while also getting the file separation necessary to avoid circular imports.

In this example I set up a thunk which calls `createSlice().actions` and which exports a reducer function which is added into `createSlice.extraReducers`

https://github.com/yuchant/redux-toolkit-folder-structure/tree/master/redux/slice

@markerikson thank you Mark for your response & work! I hope this helps others looking for a way to have a consistent import interface yet the flexibility to incrementally structure files that what would usually be a circular import later. I know you have a section on it, but wow I was stuck for a while for some reason!
