### ISSUE TITLE
Return function in createAsyncThunk() return second parameter as [object][object] describing errors

### ISSUE THREAD

**Issue by SiskoWeb** [reduxjs/redux-toolkit#3470]
**i sent  two params but the secend one return as objects or like this **
1. 
![carbon(1)](https://github.com/reduxjs/redux-toolkit/assets/100540300/3f1d4967-bfb5-4fdd-b9f8-b8f922b26a83)

2. 
![carbon(2)](https://github.com/reduxjs/redux-toolkit/assets/100540300/202e39fd-f1b3-47a2-8803-19bc8230e772)

supposed appear as formData but it's appear like this :
3.  the screen
![ssUntitled](https://github.com/reduxjs/redux-toolkit/assets/100540300/a7779ba1-c891-4fd1-a743-96a057d7bf02)

**Comment by markerikson** [comment]
Your call to the thunk is wrong.  `createAsyncThunk` functions _always_ take _one_ argument.  If you need to pass in multiple arguments, turn them into a single object, like:

```ts
dispatch(updateCategoryImage({id, formData}));
```

and then destructure those from the first arg in the payload function:

- https://redux-toolkit.js.org/api/createAsyncThunk#payloadcreator

**Comment by SiskoWeb** [comment]
i find a soulation that you have send two params but when you want Receive it  receive it as one params then use that params like this :

1. send both as object like this
![carbon(3)](https://github.com/reduxjs/redux-toolkit/assets/100540300/1e2e8f70-f03e-410d-a268-631910e40217)

2. and receive it as one params then use that params like this:
![carbon(4)](https://github.com/reduxjs/redux-toolkit/assets/100540300/0ea7ac0b-d281-46a5-a108-b75b6fbb4ed8)

**Comment by SiskoWeb** [comment]
> Your call to the thunk is wrong. `createAsyncThunk` functions _always_ take _one_ argument. If you need to pass in multiple arguments, turn them into a single object, like:
> 
> ```ts
> dispatch(updateCategoryImage({id, formData}));
> ```
> 
> and then destructure those from the first arg in the payload function:
> 
> * https://redux-toolkit.js.org/api/createAsyncThunk#payloadcreator

i try it but i got same problem id read normal but secend param not so i use trick i receive both params in one then call it from that param

**Comment by markerikson** [comment]
"Both params in one" is exactly what I just told you needs to be done :)  Put them as fields in a single object, and pass that _one_ object as the parameter.
