### ISSUE TITLE
2.0 alpha: TS errors when using actions from new builder.reducer util in rtk listener isAnyOf matcher

### ISSUE THREAD

**Issue by einarq** [reduxjs/redux-toolkit#3472]
Once I change the reducer syntax to use the new builder.reducer util I start seeing this error:

![image](https://github.com/reduxjs/redux-toolkit/assets/212751/03f417af-537a-4496-9a47-ecb4a6ee5624)

**Comment by EskiMojo14** [comment]
does this occur with tsc/VS Code, or just webstorm?

**Comment by einarq** [comment]
Happens when I run "npm run tsc", so not just webstorm.

**Comment by EskiMojo14** [comment]
Could you make a recreation in CodeSandbox? I've attempted to do so but [found no issue](https://codesandbox.io/s/potential-typing-issue-02obmg?file=/src/index.ts).

**Comment by einarq** [comment]
Hmm, I think it might be related to how the whole store and rootstate etc gets typed. Is there a canonical example you can point me to on how to correctly set up types in a large redux app? We're using combineReducers at the root.

**Comment by EskiMojo14** [comment]
[Usage with Typescript](https://redux.js.org/usage/usage-with-typescript) is the main place to look. `combineReducers` should be fine to use.

**Comment by einarq** [comment]
Ok, I'll take a look. 

One potentially related problem I'm seeing now is that the root state gets set to "unknown".

In the root reducer, we also create a global SELECTORS object, where we combine the different slice selectors into something that could be used on the global state.
I'm trying to do this, but now the root state is unknown.

```
export const SELECTORS = {
  SURVEYS: surveysSlice.getSelectors((state) => state[surveysSlice.name]),
}
```

Is this expected to work?

**Comment by EskiMojo14** [comment]
it's pretty hard to advise without a full picture of how each part plays into each other. in general, you shouldn't be creating selectors in a reducer anyway? 

it sounds like you may be causing a circular type somewhere, which is breaking inferrence.

**Comment by einarq** [comment]
>  in general, you shouldn't be creating selectors in a reducer anyway?

What do you mean? Co-locating selectors with the reducer was a recommendation from the beginning, and why you are now adding first-class support for this in createSlice I would guess?

**Comment by EskiMojo14** [comment]
I'm confused - are you creating them *in* the reducer, or just next to it?

**Comment by EskiMojo14** [comment]
gotcha - in that case it should be fine. we'd need a proper replication to be able to debug any further 😅

**Comment by EskiMojo14** [comment]
closing based on revelation from #3473 - slice was becoming `any` because slice selectors were using other selectors from the same slice and creating a circular type.

**Comment by einarq** [comment]
I might be a bit confused still on how to use the selectors on the global state. Is this supposed to work?

`const globalSelectors = slice.getSelectors((state) => state[slice.name]);`

Here `state` is still `unknown` even though the slice is no longer set to `any`.

**Comment by EskiMojo14** [comment]
getSelectors doesn't know your RootState type, you have to provide it.
`const globalSelectors = slice.getSelectors((state: RootState) => state[slice.name]);`

**Comment by einarq** [comment]
Right, tried that but easily gets into some circular dependency issues it
seems. I'll keep trying a bit.

**Comment by einarq** [comment]
Ok, I got one step closer now after reorganizing the code a bit.

But I guess it's safe to assume that any asyncThunk action created on the
slice with builder.asyncThunk will not be able to use the global selectors
inside? Since you then get the same circular type issue again.

**Comment by einarq** [comment]
So I guess if thats necessary, then cAT actions still need to be in a
separate file. Which is fine. At least that seems to solve it for me.

**Comment by EskiMojo14** [comment]
depends on how it's used - i've updated the codesandbox with an example of what would cause a circular type in an async thunk and how to break that cycle.

**Comment by einarq** [comment]
aha, nice. thanks!

**Comment by einarq** [comment]
One more thing I've noticed. If you create a reducer, using
builder.reducer, with no payload, then you now get a TS error on the
dispatch unless you pass in an argument of some sort.
https://codesandbox.io/s/slice-selector-circular-type-forked-exzu6c?file=/src/Counter.tsx
