### ISSUE TITLE
2.0 alpha: Accessing selectors within selectors causes slice to be typed as any

### ISSUE THREAD

**Issue by einarq** [reduxjs/redux-toolkit#3473]
Its quite common for us to use selectors within other selectors, like this for instance:

```
getFilter: ({filter}) => filter,
getFilters: ({filters}) => filters,
getHasFilter: (state) => {
  return surveysSlice.selectors.getFilter(state).trim().length > 0 || surveysSlice.selectors.getFilters(state).length > 0
},
```

When I do this though, the slice object itself gets the type "any".

If I change to this, then the type is correct again:

```
getFilter: ({filter}) => filter,
getFilters: ({filters}) => filters,
getHasFilter: (state) => {
  return state.filter.trim().length > 0 || state.filters.length > 0
},
```

**Comment by EskiMojo14** [comment]
yeah, there's nothing we can do about this - it causes a circular type, see [codesandbox](https://codesandbox.io/s/potential-typing-issue-02obmg?file=/src/index.ts).

The circle can be broken by annotating a return type for the selector.

Also as a note - `surveysSlice.selectors.getFilter` will expect a shape of `{ [surveysSlice.reducerPath]: surveysState }`, whereas `getHasFilter` will be passed *just* the slice state. Instead, you'd need to call `surveysSlice.getSelectors().getFilter(state)`.

**Comment by EskiMojo14** [comment]
yeah, that'll be it - your slice becomes `any` because of the circular type, and isAnyOf becomes a type guard for `unknown`.

**Comment by EskiMojo14** [comment]
I've added a [section](https://github.com/reduxjs/redux-toolkit/blob/v2.0-docs/docs/api/createSlice.mdx#selectors) in the `createSlice` 2.0 docs (#3409) which includes a note about circular types and how to avoid them.
