### ISSUE TITLE
Testing component that using cache select function.

### ISSUE THREAD

**Issue by kuzyo** [reduxjs/redux-toolkit#3479]
I'm trying to find example how to test component that using `select` function. Probably I missing some small thing I'm not able to figureout. Thank you.

I have such selector

```js
export const selectCoachSportHiddenAthleteResponse = createSelector(
  [
    (state: RootState) => state,
  ],
  (state) => {
    return searchApi.endpoints.getAllCoachHiddenAthleteIdsForSport.select({
      coachID: '1',
      sportSlug: 'football',
    })(state).data;
  },
);

```

I have msw setuped in jest to intercept that call. 

```js
    server.use(
      rest.get(
        `/search/hidden-athlete/coach-sport/1/football`,
        (_req, res, ctx) => {
          return res(ctx.status(200), ctx.json({ result: [1] }));
        },
      ),
    );

    render(<AthleteHideButton athlete={mockAthlete} />, {
      preloadedState: {
        coach: mockCoach,
        coachSports: {
          sports: [mockSportWithDefault],
          selectedSport: mockSportWithDefault,
        },
      },
    });


```

I'm sure that msw works because when I'm trying to get data inside my component using this approach, it return data as expected.

```js
  const { data } = useGetAllCoachHiddenAthleteIdsForSportQuery({
    sportSlug: 'football',
    coachID: '1',
  });


```

But using selector, data is always undefined

```js
  const data = useAppSelector(selectCoachSportHiddenAthleteResponse);

```

**Comment by EskiMojo14** [comment]
using the selector doesn't create a subscription, it will only retrieve the data if it's already in cache. If you want to fetch the data when it's not there, you should use the useQuery hook, which creates a subscription.

**Comment by kuzyo** [comment]
Could you please suggest any reliable way to test component that is using selector, without need to change component to use `useQuery` ? Thank you.

**Comment by EskiMojo14** [comment]
My main recommendation would be to use useQuery, but I suppose you could try using [`upsertQueryData`](https://redux-toolkit.js.org/rtk-query/api/created-api/api-slice-utils#upsertquerydata).

**Comment by kuzyo** [comment]
I need to write test for component that using jest and msw. Component works as I want, but I'm not able to find any example how people are writing tests for components that are using `select`. Thank you.

**Comment by EskiMojo14** [comment]
like I said, when you use select it **will not** make a network request. therefore it is irrelevant whether you are using msw.

**Comment by kuzyo** [comment]
Thank you, make sense. Is there any other approach to test component with select selector, maybe using preloadedState.

**Comment by kuzyo** [comment]
Thank you. It was really helpful. In case anyone is looking something similar - here is the way how it worked for me.

```js
    const preloadedState = {
      coach: mockCoach,
      coachSports: {
        sports: [mockSportWithDefault],
        selectedSport: mockSportWithDefault,
      },
    };

    const store = configureAppStore(preloadedState);

    const endpointName = 'getAllCoachHiddenAthleteIdsForSport';
    const args = {
      coachID: mockCoach.id,
      sportSlug: mockSportWithDefault.slug,
    };

    await store.dispatch(
      searchApi.util.upsertQueryData(endpointName, args, hiddenAthleteIds),
    );


    render(<AthleteHideButton athlete={mockAthlete} />, {
      store,
    });

```

**Comment by phryneas** [comment]
Why are you so hell-bent on not using the hooks? You should almost never use that selector on it's own in a component - it will have situations where it faces exactly the problems in your test: no data.

**Comment by kuzyo** [comment]
I guess its more about convenience, because real example relies on some additional state slices and in  component where it used we are sure that data is present in cache. But I get the point that preferable to use - `useQuery`

```js
export const selectCoachSportHiddenAthleteResponse = createSelector(
  [
    (state: RootState) => state,
    selectCoach,
    selectCoachSelectedSport,
  ],
  (state, coach, sport) => {
    return searchApi.endpoints.getAllCoachHiddenAthleteIdsForSport.select({
      coachID: coach.id,
      sportSlug: sport.slug,
    })(state).data;
  },
);

export const selectCoachSportHiddenAthleteIds = createSelector(
  [selectCoachSportHiddenAthleteResponse],
  ids => {
    if (!ids) return [];

    return ids;
  },
);

```

**Comment by phryneas** [comment]
That doesn't seem a lot more convenient than

```js
const emptyArr = [];
function useCoachSportHiddenAthleteIds() {
  return (
    useGetAllCoachHiddenAthleteIdsForSportQuery({
      coachID: useSelector(selectCoach).id,
      sportSlug: useSelector(selectCoachSelectedSport).slug,
    }).data ?? emptyArr
  );
}
```

(although `useSelector(state => selectCoach(state).id)` would potentially trigger less rerenders, but I'm keeping the theme of your selectors here)

**Comment by kuzyo** [comment]
Yeah, it also pretty concise. I will reconsider our approach. Thank you.
