### ISSUE TITLE
RTK Query + Redirect (302 status code)

### ISSUE THREAD

**Issue by retrabaud-code** [reduxjs/redux-toolkit#3502]
hello all

We have set up OpenId on the project
When a user enters the admin panel, a get request is made and if I get a 302 status code, I have to redirect it to the link in the location.

But I'm not able to implement it, I tried different methods, namely:

redirect: "manual" || redirect: "follow"

Also, I tried to get the status code, but I only get "Fetch Error"

I'm really confused, if anyone has advice I'll be happy

my api: 

import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/dist/query/react';

export const getFormsApi = createApi({
  reducerPath: 'getFormsApi',
  baseQuery: fetchBaseQuery({ 
    baseUrl: process.env.REACT_APP_BACKEND_API,
    prepareHeaders(headers) {
      return headers;
  }, 
    credentials: "include",
    }),
  endpoints: (builder) => ({
    getForms: builder.query<any, void>({
      query: () => 'here is my endpoind',
    }),
  }),
});

export const { useGetFormsQuery } = getFormsApi;

**Comment by log101** [comment]
You can check if you query is 'fulfilled' or 'rejected'. AFAIK while `transformResponse` handle the first, `transformError` handles the latter. If there is error other than 404 you backend logic should append the required info to the response.
