### ISSUE TITLE
Redux toolkit error when building for production

### ISSUE THREAD

**Issue by nisa10880** [reduxjs/redux-toolkit#3504]
I have a viteJS 4.3.4 app with redux-toolkit 1.9.5, my app works properly in dev mode but when I build the app runs, but I have these errors in the console and no state is used, and no action can be dispatched. It's been a week that I am struggling, I tried and checked my redux config. Does someone face this issue ? 

```
caught (in promise) TypeError: The "fn" argument must be of type function or an instance of AsyncFunction. Received an instance of Object
    at filter$1 (index-8e6c558a.js:148101:15)
    at find (index-8e6c558a.js:148083:44)
    at find (index-8e6c558a.js:148360:16)
    at freezeDraftable (index-8e6c558a.js:35678:25)
    at createReducer (index-8e6c558a.js:35805:36)
    at buildReducer (index-8e6c558a.js:35895:16)
    at reducer (index-8e6c558a.js:35913:24)
    at index-8e6c558a.js:35137:29
    at Array.forEach (<anonymous>)
    at assertReducerShape (index-8e6c558a.js:35135:29)
f
```

```
dex-8e6c558a.js:35843 Uncaught (in promise) Error: A case reducer on a non-draftable value must not return undefined
    at index-8e6c558a.js:35843:23
    at Array.reduce (<anonymous>)
    at reducer (index-8e6c558a.js:35828:29)
    at reducer (index-8e6c558a.js:35914:18)
    at combination (index-8e6c558a.js:35179:33)
    at reducer (index-8e6c558a.js:37370:16)
    at combination (index-8e6c558a.js:35179:33)
    at E (<anonymous>:1:33326)
    at I (<anonymous>:1:33613)
    at <anonymous>:1:37893

```

**Comment by phryneas** [comment]
Are you trying to store some kind of class object in the store there?

**Comment by nisa10880** [comment]
No, I don't store class object in store

**Comment by markerikson** [comment]
@nisa10880 what kind of value is it?  Can you reproduce this as either a CodeSandbox, or by recording a Replay ( https://replay.io/record-bugs ) ?

**Comment by nisa10880** [comment]
@markerikson here is a Replay https://app.replay.io/recording/tickie-app--ad82a64f-4778-4c66-ae22-3d453efafdd2

**Comment by markerikson** [comment]
@nisa10880 : Hmm. There's no sourcemaps, which makes this harder to investigate. BUT, I see a mention of `ERR_INVALID_ARG_TYPE` and `AsyncIterable`, which appear to be part of / used by Node's `readline` library?  

https://github.com/nodejs/node/blob/9f3466bcb646dc2f568569813379be1252753a72/doc/api/readline.md?plain=1#L843

and it seems like the reducer logic is somehow calling into a Node Stream?

```ts
    Stream$1.Writable = requireWritable();
    Stream$1.Duplex = requireDuplex();
    Stream$1.Transform = transform$1;
    Stream$1.PassThrough = passthrough;
    Stream$1.pipeline = pipeline;
```

Something really weird is going on here.

**Comment by nisa10880** [comment]
@markerikson here is a replay with sourcemap https://app.replay.io/recording/tickie-app-2--ee604610-d075-4c50-8e41-986178034434

In order to build, I use this plugin: https://github.com/davidmyersdev/vite-plugin-node-polyfills

**Comment by markerikson** [comment]
@nisa10880 thank you! This is really bizarre. Somehow the Immer `createNextState` method is showing up as a Stream function called `find`, which makes no sense at all:

![image](https://github.com/reduxjs/redux-toolkit/assets/1128784/1664c6f0-074b-460a-a58d-8699d4144703)

Do you actually _need_ this Node polyfills package? What happens if you remove it?

**Comment by nisa10880** [comment]
Yes, I need it because I use web3 packages that require polyfills

**Comment by markerikson** [comment]
@nisa10880 what happens if you switch to https://github.com/reduxjs/redux-toolkit/releases/tag/v2.0.0-beta.0 ?

**Comment by nisa10880** [comment]
```
export const store = configureStore({
  reducer: {
    [baseApi.reducerPath]: baseApi.reducer,
    [authSlice.name]: authSlice.reducer,
  },
  middleware: new Tuple(baseApi.middleware)
});
```

Is that the correct way to configure store in the new version ? because I have this error 

`Uncaught Error: Actions must be plain objects. Use custom middleware for async actions.
`

**Comment by EskiMojo14** [comment]
you should still use the getDefaultMiddleware callback, to include the thunk middleware.
```ts
export const store = configureStore({
  reducer: {
    [baseApi.reducerPath]: baseApi.reducer,
    [authSlice.name]: authSlice.reducer,
  },
  middleware: (getDefaultMiddleware) => getDefaultMiddleware().concat(baseApi.middleware)
});
```

**Comment by nisa10880** [comment]
@EskiMojo14 @markerikson Thank you ! 🙏  It's now working with the redux-toolkit beta version.

**Comment by markerikson** [comment]
sweet!

no idea _why_ that was happening - my only guess is some kind of build tool problem (Terser?)
