### ISSUE TITLE
Can only mutate state with 1 element array

### ISSUE THREAD

**Issue by tommycarpi** [reduxjs/redux-toolkit#3505]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM/React Native: 0.71.8
- Redux: 4.2.1
- React Redux: 8.0.7

### What is the current behavior?

I have the following slice

```
import { createSlice } from '@reduxjs/toolkit'
import Token from '../classes/Token'

const dataSlice = createSlice({
    name: 'data',
    initialState: {
        tokens: [] as Token[],
    },
    reducers: {
        setTokens: (state, action) => {
            state.tokens = action.payload
        }
    }
})

export const {
    setTokens,
} = dataSlice.actions

export default dataSlice.reducer
```

It was continuously throwing this error
`TypeError: Attempted to assign to readonly property.`

I tried to debug.
This code works ✅

```
reducers: {
        setTokens: (state, action) => {
            state.tokens = [new Token()]
        }
    }

```

this code doesn't ❌

```
reducers: {
        setTokens: (state, action) => {
            state.tokens = [new Token(), new Token()]
        }
    }

```

Despite the content of Token, it looks like it's only accepting 1 element arrays, which is insane to me 😅

Am I missing something?

### What is the expected behavior?

Accepting any number of elements within the array

### Which browser and OS are affected by this issue?

iOS

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by EskiMojo14** [comment]
Immer recursively freezes state, to prevent accidental mutation from outside the store.

Additionally, it sounds like you're storing non-serializable data inside your Redux store, which [isn't recommended](https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state).

**Comment by tommycarpi** [comment]
Hey, thanks for your reply.

I just didn't understand if I fix and store only serializable object will this issue disappear?

Honestly I'm just calling it once, so I don't understand why the freeze happens only when 2+ objects are within the array.

**Comment by markerikson** [comment]
@tommycarpi Can you provide a CodeSandbox, repo, or a Replay ( https://replay.io/record-bugs ) that reproduces the issue?

**Comment by tommycarpi** [comment]
I have another app with basically the same codebase (I copied/pasted the code, the same version of redux and react/native) and it works like a charm. Here it does not 😅

I'm surely missing something but I don't know what.
I've attached a screen recording to show you the error.

https://github.com/reduxjs/redux-toolkit/assets/10156527/e9f9f467-153d-45b1-972f-3df95dd4cdce

**Comment by phryneas** [comment]
I don't think that this is about one or two elements. I believe that at some point you replace that array with an outside value that is completely frozen. Is this maybe persisted data?

**Comment by tommycarpi** [comment]
I fixed it, it was not a bug of redux.
It seems like applying a .sort() to the array got from useSelector() made it crash. That's the reason why 1 element did not crash.

It used to work with old versions of redux, I'm actually upgrading all libraries from an existing codebase.
Still haven't figured out why, but moved the sorting within the state mutation function and it worked.

Thanks to all who had a look at this.

**Comment by EskiMojo14** [comment]
yep, .sort mutates the array in place, which isn't allowed

**Comment by markerikson** [comment]
@tommycarpi aha, yes, you've run across the reason why Immer does freeze state :)  because it helps catch errors like calling `someArray.sort()` after selecting it.  It makes sense that it "worked" before migrating to RTK, and then the switch to `createSlice` + Immer started freezing it.  In other words, this has fixed a real bug in the app :)
