### ISSUE TITLE
RTK Query lazy query leaves open handles in jest

### ISSUE THREAD

**Issue by DominicGBauer** [reduxjs/redux-toolkit#3509]
Note: I'm experiencing a similar issue as found here https://stackoverflow.com/questions/69538390/jest-not-exiting-properly-when-using-rtk-query-uselazyquery-with-reactnative

## ISSUE
When I have a component that uses `useLazyQuery` in `jest`. I think the caching behaviour causes issues in `jest` because the the promise does not finish.

```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

I have solved it following the example mentioned in the above link:
```js
const api = createApi({
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({
    baseUrl: 'any-base-url',
  }),
  keepUnusedDataFor: process.env.NODE_ENV === 'test' ? 0 : 60, // <- here
  endpoints: () => {
    return {
      // your endpoints
    };
  },
});
```
Wondering if this is a bug or if this is expected?

**Comment by phryneas** [comment]
Are you resetting the api in your tests? Generally, I'm sorry, but you're not giving us a lot of background on what you are doing :/

**Comment by DominicGBauer** [comment]
@phryneas sorry for the delayed response, I'm not resetting the API.

I'm using
```js
export function renderWithProviders(
  ui: React.ReactElement,
  {
    preloadedState = {},
    // Automatically create a store instance if no store was passed in
    store = setupStore(preloadedState),
    ...renderOptions
  }: ExtendedRenderOptions = {},
) {
  // eslint-disable-next-line @typescript-eslint/ban-types
  const Wrapper = ({ children }: PropsWithChildren<{}>): JSX.Element => {
    return (
      <Provider store={store}>
        <NavigationContainer>{children}</NavigationContainer>
      </Provider>
    );
  };

  // Return an object with the store and all of RTL's query functions
  return { store, ...render(ui, { wrapper: Wrapper, ...renderOptions }) };
}
```
To add the store and using MSW to mock API responses.

I then try to test the component assuming an API response based on MSW.

**Comment by phryneas** [comment]
An api like that would end up with timers going for 60 seconds after the last component unmounted, before data is removed. You probably want to reset the api between tests.
