### ISSUE TITLE
Enable noImplicitOverride Option in tsconfig

### ISSUE THREAD

**Issue by jkissel** [reduxjs/redux-toolkit#3521]
[`noImplicitOverride`](https://www.typescriptlang.org/tsconfig#noImplicitOverride) is a way to avoid overrides to get out of sync with their base implementation. We'd like to activate this option in our code base, but this results in type errors in redux-toolkit.

That's why I want to kindly suggest to enable noImplicitOverride also in redux-toolkit.

Thx in advance for your response!

**Comment by markerikson** [comment]
What type errors are you seeing? Why would _our_ TS config settings matter in your application code?

**Comment by EskiMojo14** [comment]
do you have skipLibCheck enabled? generally it shouldn't matter what tsconfig settings were used when writing the library (with [one](https://github.com/reduxjs/redux-toolkit/pull/3495/files) exception)

**Comment by jkissel** [comment]
> What type errors are you seeing?

```
node_modules/@reduxjs/toolkit/src/utils.ts:46:3 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Middlewares[number][]'.

46   concat<AdditionalMiddlewares extends ReadonlyArray<Middleware<any, any>>>(
     ~~~~~~

node_modules/@reduxjs/toolkit/src/utils.ts:50:3 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Middlewares[number][]'.

50   concat<AdditionalMiddlewares extends ReadonlyArray<Middleware<any, any>>>(
     ~~~~~~

node_modules/@reduxjs/toolkit/src/utils.ts:53:3 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Middlewares[number][]'.

53   concat(...arr: any[]) {
     ~~~~~~

node_modules/@reduxjs/toolkit/src/utils.ts:89:3 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Enhancers[number][]'.

89   concat<AdditionalEnhancers extends ReadonlyArray<StoreEnhancer<any, any>>>(
     ~~~~~~

node_modules/@reduxjs/toolkit/src/utils.ts:93:3 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Enhancers[number][]'.

93   concat<AdditionalEnhancers extends ReadonlyArray<StoreEnhancer<any, any>>>(
     ~~~~~~

node_modules/@reduxjs/toolkit/src/utils.ts:96:3 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Enhancers[number][]'.

96   concat(...arr: any[]) {
     ~~~~~~


Found 6 errors in the same file, starting at: node_modules/@reduxjs/toolkit/src/utils.ts:46
```

> Why would our TS config settings matter in your application code?
Only to avoid future type errors that are caused by implicit overrides.

> do you have skipLibCheck enabled?
Yes, I do, but it doesn't help, probably because the type errors are not in .d.ts files, but in a "normal" .ts file!? (see https://www.testim.io/blog/typescript-skiplibcheck/)

**Comment by phryneas** [comment]
You are typechecking the Redux Toolkit sources here, not the `dist` folder. Did you import anything from `@reduxjs/toolkit/src`?

**Comment by jkissel** [comment]
You're completely right, there was a src type import in one of our modules 🤦

Thx a lot for pointing that out! Changing that import fixed my issue 👍
