### ISSUE TITLE
how to reset multiple slices to their initial state

### ISSUE THREAD

**Issue by youesei** [reduxjs/redux-toolkit#3524]
Hi, I am new to react and I am creating a somewhat large project, I created several slices to manage the state of my application, the problem I have is when I want to reset the state of the slices I must `dispatch` a reducer `reset()` for each slice it seems to me that it is not the best way to do it, because it requires a lot of code and is used in several places in my application, my question is: if there is a better way to perform this task, I tried to use the `combineReducer` and create a `rootReducer` but its sitanxis is a bit confusing and when accessing the properties of my slices with `useSelector` I get an error in the console.

```
const combinedReducer = combineReducers({
  slice1: slice1.reducer,
  slice2: slice2.reducer,
});

const rootReducer = (state, action) => {
  if (action.type === 'logout') {
    state = undefined;
  }
  return combinedReducer(state, action);
};

export const store = configureStore({
  reducer: {
    reducer: rootReducer
  },
})
```
***useSelector Error***
`Uncaught TypeError: Cannot destructure property '....' of 'useSelector(...)' as it is undefined.`

**Comment by youesei** [comment]
Hello, thanks for answering, I have another question, how should I do the dispatch for this to work?

**Comment by markerikson** [comment]
Not sure I understand the question.  Dispatching always works the same way: `store.dispatch(actionObject)`, although it usually looks like `dispatch(someAction())` in the rest of your code like a component.

Is there a specific thing you're concerned about?

**Comment by youesei** [comment]
Hi, I'm sorry I didn't explain myself well. My question refers to how do I make this action of resetting the slices work? Do I have to create a new reducer in each slice? I'll give my logout function as an example.

```
export const startLogout = () => {
    return async( dispatch ) => {
        await logoutFirebase();
        dispatch( ); //As a dispatch so that the action of resetting the states works?
    }
}
```

**Comment by markerikson** [comment]
That's what I was saying above. If you do `dispatch(resetUserState())` in that thunk, there's (at least) two ways to write the reducer logic.  Either have every single `createSlice` call also handle `resetUserState` inside of `createSlice.extraReducers`, _or_ have the root reducer do all the work like I showed.

**Comment by youesei** [comment]
Thanks again for the help, I understood that the action that the rootReducer receives is sent when dispatching any reducer, for the logout example I created a reducer logout in one of my slices:

***slice1.js***
```
logout: (state) => {},
export const {
    logout,
    .....
} = slice1.actions;
```

which does not perform any action on the reducer, but that logout action is sent to the rootReducer which executes all the reset code:

***store.js***
```
const rootReducer = ( state, action ) => {
  // console.log(action); the action takes the value of logout when dispatching the reducer logout of my slice1 `dispatch(logut)`
  if (action.type === 'logout') {
    state = {...state}
    delete state.slice1
    delete state.slice2
  }
  return combinedReducer(state, action);
};
```

So if I want to do the same with the other slices I must integrate the reducer logout in each one of them, I still don't understand the other option that you mention?

**Comment by markerikson** [comment]
The per-slice approach would be doing something like this in every `createSlice` call:

```ts
createSlice({
  name: "someSlice",
  initialState,
  reducers: { /*  */ },
  extraReducers: (builder) => {
    builder.addCase(logout, () => {
      return initialState
    })
  }
})
```
