### ISSUE TITLE
Error in production: "Uncaught TypeError: i.fetchBaseQuery is not a function"

### ISSUE THREAD

**Issue by louh** [reduxjs/redux-toolkit#3533]
I have a very basic implementation of RTK Query that follows the ["Basic Usage"](https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery#basic-usage) instructions exactly:

```js
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

export const myApi = createApi({
  reducerPath: 'myApi',
  baseQuery: fetchBaseQuery({
    baseUrl: '/api/v1/'
  }),
  endpoints: (builder) => ({
    getUser: builder.query({
      query: (userId) => `users/${userId}`
    })
  })
})

export const { useGetUserQuery } = myApi
```

It works exactly as expected in development, but when I deployed to a production instance, the app crashes, with this error in the console:

```
Uncaught TypeError: i.fetchBaseQuery is not a function
```

Am I to gather from this error message that RTK Query didn't bundle properly? I am using Parcel.

**Comment by markerikson** [comment]
Presumably, yeah, which is really bizarre. Never seen anyone report a problem like that before.

**Comment by louh** [comment]
I was able to search issues for a few other related keywords and found a couple situations that seem similar to mine. Both users are using Parcel, like me.

https://github.com/reduxjs/redux-toolkit/issues/2584
https://github.com/reduxjs/redux-toolkit/issues/2899

I am trying their recommendations now.

**Comment by louh** [comment]
I see the issue has been filed at Parcel as well: https://github.com/parcel-bundler/parcel/issues/7622

**Comment by louh** [comment]
OK, it seems these previous comments tracked down the solution. In case anyone else has stumbled across this same error, the issue is that Parcel is somehow skipping aliased exports in RTK Query. The solution is to use write the import from two separate packages, like this:

```js
import { createApi } from '@reduxjs/toolkit/query/react'
import { fetchBaseQuery } from '@reduxjs/toolkit/query'
```

**Comment by markerikson** [comment]
Wow, that's screwy :(

Thanks for the heads-up!

**Comment by Saeid-Barzegar** [comment]
I'm getting the error like this
Global Error: TypeError: **S.current.isRequestSubscribed** is not a function
this functoin also exported from RTK Query

I'm using Next 14.2.8 and redux tooklit 2.2.7
tired the same solution with this issue but didn't work

**Comment by phryneas** [comment]
@Saeid-Barzegar did you forget to set up the middleware? In development mode you should get an error about that.

**Comment by Saeid-Barzegar** [comment]
> @Saeid-Barzegar did you forget to set up the middleware? In development mode you should get an error about that.

OMG! what was that fkng! mistake!!!
thatnks @phryneas , yes i didn't add my rtk queries to my production middleware :(
thanks for your help
you made and saved my day!
