### ISSUE TITLE
Fulfilled status bug

### ISSUE THREAD

**Issue by finom** [reduxjs/redux-toolkit#3548]
Hello. I have the following code:

```ts
import { createSlice } from '@reduxjs/toolkit';
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const testEntityApi = createApi({
  reducerPath: `TEST_ENTITY_api`,
  baseQuery: fetchBaseQuery({
    baseUrl: process.env.NEXT_PUBLIC_API_URL,
  }),
  endpoints: (builder) => ({
    getTestEntities: builder.query({
      query: () => '/test-entities',
    }),
  }),
});

const testEntities = createSlice({
  name: 'TEST_ENTITY',
  initialState: {},
  reducers: {},
  extraReducers: (builder) => {
    builder.addMatcher(testEntityApi.endpoints.getTestEntities.matchFulfilled, (state, action) => {
      console.log(state, action); // never executed
    });
  },
}).reducer;

export const { useGetTestEntitiesQuery } = testEntityApi;

export default testEntities;

```

In my component I call `useGetTestEntitiesQuery`. The middleware initialised and store is configured by `configureStore` as per the documentation.

For some reason when `useGetTestEntitiesQuery` is called `builder.addMatcher(testEntityApi.endpoints.getTestEntities.matchFulfilled ...)` is never executed. But If I use `matchPending` instead I get the callback called as expected. I was trying to understand what's going on in the store and there is what I found:

- Fulfilled action is executed 
- But query status is still pending

<img width="1394" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/1082083/15f17560-ddc4-42e8-89e3-1b3a42de9592">

Any idea how to fix that? The request to the server is run as expected: with 200 code.

**Comment by finom** [comment]
@markerikson I'm sorry, what exactly would you want to record with Replay? I don't have any UI, I'm just trying to make a basic request with redux-toolkit and update state at `extraReducers `.

**Comment by markerikson** [comment]
@finom it would let us see the actual JS execution of everything that happens, including all the RTKQ internal logic.

Assuming that the network request came back okay, that _should_ have triggered the `fulfilled` action, so I'd like to see what actually happened instead.

**Comment by finom** [comment]
I'm sorry, that was my issue with custom root reducer:

```
const rootReducer = (state: Root, action: Action) => {
  if (isFulfilled(action) && action.payload) {
// ...
return state; // this is the bug
   }

  return combineReducers({
    testEntities: testEntities,
    [testEntityApi.reducerPath]: testEntityApi.reducer,
  })(state, action);
};
```

**Comment by markerikson** [comment]
Hah, nice :)
