### ISSUE TITLE
Incompatibility to seamless-immutable?

### ISSUE THREAD

**Issue by KDederichs** [reduxjs/redux-toolkit#355]
Hey,

I've got a question:
Is redux-toolkit incompatible with seamless-immutable by chance?
I recently ported our reducers to redux-toolkit and now I'm experiencing errors like:

`Array.isArray cannot be called on a Proxy that has been revoked`

with a stack trace that goes like that:

<img width="1527" alt="Screenshot 2020-02-13 at 15 52 19" src="https://user-images.githubusercontent.com/24696606/74446886-d2ecd580-4e78-11ea-997c-58c1f55e9e54.png">

Is it incompatible? Or maybe a bug with immer.js?

**Comment by markerikson** [comment]
I haven't used `seamless-immutable`, but yeah, it's very possible that it and Immer don't play well together.

Given the existence of Immer, there really shouldn't be much need to keep using `seamless-immutable`.

**Comment by KDederichs** [comment]
Yeah that's what I figured after thinking about it for a bit.
Maybe you could make a note in the documentation somewhere for people transitioning to toolkit from older codebase with existing immutability pointing that out
