### ISSUE TITLE
Safari request/response local override is not working with rtk query

### ISSUE THREAD

**Issue by nouman91** [reduxjs/redux-toolkit#3550]
Hi,
I am trying to override the server response with local override and I have noticed it does not work with RTK query. My use case is the server does not have the data and I want to load data with Safari local override. But the trouble is RTK query can't seem to understand it and does not return the overridden data. 

I am sure this has been answered somewhere but I was not able to find it.

**Comment by markerikson** [comment]
We just use the built-in `fetch` API. I have no idea how Safari's overrides work, but I don't think it's going to be anything we have control over in RTKQ.

**Comment by nouman91** [comment]
Hmm.. Thank you for your quick reply. It seems I have to do some digging around to understand it. 

Brief description Safari local override: You can override the response returned by the server with whatever you want and instead of serving the server response it will serve you the local response. [Override](https://webkit.org/web-inspector/local-overrides/#:~:text=Local%20Overrides%20can%20be%20created,Override%2C%20and%20Block%20Request%20URL.)

I just did a quick test:
API-1 with rtk query; Does not work with local override always returns the original cached server response. 
API-2 without rtk query: Works as expected with local override.

**Comment by EskiMojo14** [comment]
as in, making a normal `fetch` request returns your override?

**Comment by nouman91** [comment]
Thank you! I think that's what I need in this case as data is cached. 
Looking into integrating resetApiState for my use case.

**Comment by nouman91** [comment]
Is there any way I can disable the cache completely?

**Comment by phryneas** [comment]
RTK Query *is* the cache, it doesn't do a lot beyond that. So, removing RTK Query would do that.
But honestly, if you don't manually persist your Redux store somewhere: press F5 and you start again with an empty cache.

**Comment by nouman91** [comment]
Closing this issue as it was related to caching.
Thanks for the quick help, I really appreciate it.
