### ISSUE TITLE
Type error: Property 'getState' does not exist on type 'ToolkitStore<any, AnyAction, MiddlewareArray<[Middleware<ThunkDispatch<State, ExtraThunkArg, BasicAction>, State, ThunkDispatch<State, ExtraThunkArg, BasicAction>>, ...any[]]>>'.

### ISSUE THREAD

**Issue by Sabin-Subedi** [reduxjs/redux-toolkit#3552]
./redux/store.ts:21:55
web:build: Type error: Property 'getState' does not exist on type 'ToolkitStore<any, AnyAction, MiddlewareArray<[Middleware<ThunkDispatch<State, ExtraThunkArg, BasicAction>, State, ThunkDispatch<State, ExtraThunkArg, BasicAction>>, ...any[]]>>'.
web:build: 
web:build:   19 | /* Types */
web:build:   20 | export type ReduxStore = typeof reduxStore;
web:build: > 21 | export type ReduxState = ReturnType<typeof reduxStore.getState>;
web:build:      |                                                       ^
web:build:   22 | export type ReduxDispatch = typeof reduxStore.dispatch;
web:build:   23 | 
web:build:   24 | export const wrapper = createWrapper<ReduxStore>(() => reduxStore);
web:build:  ELIFECYCLE  Command failed with exit code 1.
web:build: ERROR: command finished with error: command (/Users/sabinsubedi/sage/sageweb/app/apps/web) pnpm run build exited (1)

**Comment by phryneas** [comment]
Please share the code that got you to this error. Also, just to be sure please rename your `redux` folder into something else. 
In some project setups that can end up in `import from 'redux'` import from a folder with that name instead of the node module.
