### ISSUE TITLE
rtk-query-codegen-openapi: FilterEndpoints ambiguous matches OperationId 

### ISSUE THREAD

**Issue by georg-schwarz** [reduxjs/redux-toolkit#3553]
## Context 
I used the `filterEndpoint` in the configuration for `[rtk-query-codegen-openapi](https://github.com/reduxjs/redux-toolkit/tree/master/packages/rtk-query-codegen-openapi)` like this:
```
  filterEndpoints: [/^clientapps/],
```

## Problem

**Expected behavior:** The endpoints are filtered by their path according to the regex.
**Actual behavior:** The endpoints are filtered by `operationId` if given.

What is even more concerning to me is that some camel case magic is happening in the background. My controller had operationId `ProjectClientApps_create` but did not match to the regexp. I fixed it by using the regex `/^userClientApp/`.

## Suggested Solution

Also match for the API path.

## Disclaimer

I'm not sure if this really is a bug or intended behavior. Please treat this issue as documentation if it is not a bug. It took me forever to debug into the library to understand what's happening ;-)

**Comment by jolbol1** [comment]
It is matching by `operationName` which comes from the operationId, with some modifications.

They allow you to use an Endpoint matcher function, so for my use case where I wanted to filter on path, I used a function like so:
```ts
const pathMatcher = (pattern: RegExp): EndpointMatcherFunction => {
  return (operationName, operationDefinition) => {
    return pattern.test(operationDefinition.path);
  };
}
```

Then you can use this in filter endpoints with the regex to match a path:
```ts
filterEndpoints: pathMatcher(/whatever/i)
```

You can modify the function above to filter on anything in the operation definition.
