### ISSUE TITLE
Not able to reset to initial state in root reducer or even not able reset initial state of a slice

### ISSUE THREAD

**Issue by vismaya-haridas** [reduxjs/redux-toolkit#3557]
Attaching all the codr and issues
![IMG-20230625-WA0075](https://github.com/reduxjs/redux-toolkit/assets/71158635/dbb7e5dd-78c7-4a78-a0a2-5917e80ccd7b)
![Uploading IMG-20230625-WA0056.jpeg…]()

**Comment by vismaya-haridas** [comment]
This is not closed... I  am still facing same issue to reset initial state

**Comment by markerikson** [comment]
This isn't a bug or a feature request, and it also doesn't include any actual code.

For help questions, please ask over in the `#redux` channel in the Reactiflux Discord ( https://www.reactiflux.com ).

**Comment by phryneas** [comment]
Also, please, when you ask there, ask a real questions and don't post a bunch of photos without any comment and expect someone to understand that.
