### ISSUE TITLE
Actions don't work with TS

### ISSUE THREAD

**Issue by yeager-j** [reduxjs/redux-toolkit#356]
Dispatching actions don't seem to work in a TypeScript project. We copied code from the tutorial into a TypeScript project created with create-react-app and actions don't get dispatched. 

We could be missing something super obvious but we spent a lot of time on this.

https://github.com/yeager-j/redux-toolkit-test

**Comment by markerikson** [comment]
"Doesn't work" isn't a helpful description.  I appreciate the linked repo, but could you at least give some details here as to what you've specifically tried, and what behavior you're actually seeing?  Are you getting error messages of some kind?

**Comment by markerikson** [comment]
Ah.  Actually, looking at that, I see the exact problem:

```ts
const App = () => {
    const todos = useSelector((state: RootState) => state.todo);

    useEffect(() => {
        console.log(' add todo');
        addTodo({ id: 1, text: 'hello world' });
    }, []);
```

This isn't actually dispatching anything at all.  You're calling the `addTodo` action creator, and... the returned action object is being thrown away and ignored.  There's no "dispatching" going on here at all.

To fix this:

```ts
const App = () => {
    const dispatch = useDispatch();
    const todos = useSelector((state: RootState) => state.todo);

    useEffect(() => {
        console.log(' add todo');
        dispatch(addTodo({ id: 1, text: 'hello world' }));
    }, [dispatch]);
```

Please see the Redux Toolkit tutorials for examples, and especially the [Advanced Tutorial](https://redux-toolkit.js.org/tutorials/advanced-tutorial) for examples of using RTK with TS and React-Redux hooks.
