### ISSUE TITLE
DOCS: Code highligh is not accesible in darkmode

### ISSUE THREAD

**Issue by dannegm-adelaide** [reduxjs/redux-toolkit#3563]
I have wanted to make this observation for a long time. In the documentation, when you're in dark mode and you highlight some code, it's hard to read, especially with the words turning red.

I think the accessibility and readability of the code should be improved a bit. Either by changing the highlight color or by changing the color scheme that is used for the code.

I attach some screenshots so you can understand what I mean:

--

<img width="560" alt="Screenshot 2023-06-28 at 16 42 40" src="https://github.com/reduxjs/redux-toolkit/assets/106763009/d0cc42b6-b909-4b6e-bc6a-645e399d3f6c">

<img width="684" alt="Screenshot 2023-06-28 at 16 42 23" src="https://github.com/reduxjs/redux-toolkit/assets/106763009/4473ceff-b026-454e-b72b-011d5e5eb505">

<img width="479" alt="Screenshot 2023-06-28 at 16 41 54" src="https://github.com/reduxjs/redux-toolkit/assets/106763009/56eea00e-c778-41e4-9989-18d47b2c767d">

**Comment by markerikson** [comment]
We're always happy to accept PRs to improve the docs!
