### ISSUE TITLE
Impossible to avoid dispatch loops in custom middleware using thunks

### ISSUE THREAD

**Issue by ernestostifano** [reduxjs/redux-toolkit#3565]
Hello everyone!

Hope I'm actually missing something, but it seems to me that the fact that dispatched thunk actions are just functions, without any kind of other accessible data (see https://github.com/reduxjs/redux-toolkit/issues/750#issuecomment-720798439), makes it incredibly difficult, if not impossible, to perform any kind of check within custom middleware to avoid dispatch loops.

For example, I'm trying to implement a simple custom middleware that will check/refresh the authorisation token before thunks that make API calls execute.

My middleware looks similar to this:

```js
import {authThunks} from '../../slices/core/auth/auth.slice';
import {auth} from "../../thunks/core/auth/auth.services";

const tokenChecker =
    ({dispatch}) =>
    (next) =>
    async (action) => {
        if (typeof action === 'function') {
            await dispatch(authThunks.refresh());
        }

        return next(action);
    };

export {tokenChecker};
```

Please note that `authThunks.refresh` handles all the logic, including queuing multiple request, making them wait for a single refresh operation.

**Obviously, the above code will end up in an infinite loop, because `authThunks.refresh` is itself a thunk and will match the `typeof action === 'function'` condition.**

I know I could bring all the thunk logic inside the middleware, avoiding to call the thunk at all, but that's to close the eyes on the real issue. Beside that, I want to keep all my `auth` logic accessible (including the refresh logic) throughout the entire application.

With normal actions I could access so many information about the dispatched action inside the middleware (information from both the action creation and from the dispatch), but with thunks I cannot even do a function comparison of any sort to avoid the loop, because the dispatched function reference is created at dispatch time and changes constantly.

Ideally, I would have really loved to do something like this:

```js
const refresh = createAsyncThunk(
    'auth/refresh',
    async (payload, {dispatch}) => {
        return await auth.refresh().catch(() => {
            return dispatch(login());
        });
    }
);
```

```js
const readUsers = createAsyncThunk(
    'users/readUsers',
    async (queryParams) => {
        return await users.list(queryParams);
    },
    {
        meta: {skipTokenCheck: true}
    }
);
```

And then in my middleware:

```js
import {authThunks} from '../../slices/core/auth/auth.slice';
import {auth} from "../../thunks/core/auth/auth.services";

const tokenChecker =
    ({dispatch}) =>
    (next) =>
    async (action) => {
        if (
            typeof action === 'function' &&
            action.name !== 'auth/refresh' &&
            !action.meta.skipTokenCheck
        ) {
            await dispatch(authThunks.refresh());
        }

        return next(action);
    };

export {tokenChecker};
```

Receiving just a function inside the middleware is very limiting... What if other middleware want to accept special function actions too? It would conflict with thunks and it does not seem very community friendly. I understand that the function is needed, but why weren't them wrapped inside an object?

Something like this:

```js
{
    type: 'THUNK',
    fn: () => undefined, // THUNK FUNCTION HERE
    meta: {}
}
```

Then the thunk middleware would have just checked the type or a symbol or something else and get the `fn` which would be the same dispatched function as before.

Again, I really hope I am missing something, because this is preventing me to implement something that is very simple.

Thanks in advance!

P.S.:

As written here https://github.com/reduxjs/redux-thunk/issues/348, this could be implemented in multiple ways:

1. Do everything at Redux Toolkit level: Implement the wrapper at `createAsyncThunk` and add another middleware with `configureStore`, before the thunk middleware, to unwrap the action and pass it as a simple function as always.
2. Extend the thunk middleware to handle both classic functions and wrapped ones (with a special key, symbol or something). This way, there should not be any breaking changes and no additional middleware would be needed. Finally, wrapping can be implemented in `createAsyncThunk`.

**Comment by EskiMojo14** [comment]
generally, other middlewares that check for functions are pretty rare, so it's a safe assumption that a function being dispatched is solely for the thunk middleware to deal with.

with that said, your middleware could do something as simple as attaching a property to the generated thunk, then checking for it:
```js
import {authThunks} from '../../slices/core/auth/auth.slice';
import {auth} from "../../thunks/core/auth/auth.services";

const tokenChecker =
    ({dispatch}) =>
    (next) =>
    async (action) => {
        if (typeof action === 'function' && !action.noRefresh) {
            const refreshThunk = Object.assign(authThunks.refresh(), { noRefresh: true })
            await dispatch(refreshThunk);
        }

        return next(action);
    };

export {tokenChecker};
```

note that your middleware technically has a bug - by defining it as an async function, you're making it so that *every* action dispatched will create and return a promise.

Instead, do something like 
```ts
const tokenChecker =
    ({dispatch}) =>
    (next) =>
    (action) => {
        if (typeof action === 'function' && !action.noRefresh) {
            const refreshThunk = Object.assign(authThunks.refresh(), { noRefresh: true })
            return dispatch(refreshThunk).then(() => next(action));
        }

        return next(action);
    };
```

**Comment by phryneas** [comment]
You could also call `next(newThunk)` instead of `dispatch(newThunk)` in which case `newThunk` will never call this middleware again.
