### ISSUE TITLE
Throw error when custom action creator does not have `type` value

### ISSUE THREAD

**Issue by chawes13** [reduxjs/redux-toolkit#3570]
It'd be great to have a guard for passing in an action creator that **doesn't** have a truthy `type` string value.

I encountered this issue when migrating over to RTK. We built some custom action creators that we use in combination with a custom api middleware (we're not ready to switch to RTQ just yet - baby steps 😅!). While these have the `toString()` override, the builder `addCase` method is not using that _and_ it seems like this override is [getting deprecated in v2](https://github.com/reduxjs/redux-toolkit/pull/3425).

The following led to a fairly subtle bug, since it fails silently.
```js
extraReducers: (builder) => {
  builder.addCase(apiActions.fetchTodo, todoHandler) // fetchTodo.type === undefined
}
```
Since I'm working in JS, this issue is easier to run into. Although, I believe a guard may still be helpful to prevent accidental assignments of an empty string to the `type` attribute in the implementation of a custom action creator in TS.
https://github.com/reduxjs/redux-toolkit/blob/24fc34392d249573fd14088db8daea10e848de41/packages/toolkit/src/mapBuilders.ts#L158-L168

**Comment by EskiMojo14** [comment]
I'm sure we'd be open to a PR that throws an error if the `type` variable is undefined :)
