### ISSUE TITLE
await queryFulfilled never resolves on request failure

### ISSUE THREAD

**Issue by altr-jeremyscott** [reduxjs/redux-toolkit#3571]
In our application, we have a group of endpoints defined using `injectEndpoints`. The issue lies in a single mutation function utilizing `onQueryStarted` to throw specific snack bars depending on query success or failure. The callback is triggered as soon as the query starts as normal, but ONLY on failures `await onQueryStarted` never resolves, and the code underneath the promise is never reached nor are  `catch` or `finally`.

Example Query: 
```javascript
update: build.mutation({
  query: ({ id, ...patch }) => ({ url: `/source/${id}`, method: "patch", patch }),
  onQueryStarted: async (_arg, { dispatch, queryFulfilled }) => {
    try {
      await queryFulfilled; // queryFulfilled is never resolved and the rest of the function is not ran

      dispatch(showSuccess())
    } catch (err) {
       
      dispatch(showError())
    }
  }
``` 

Example call:
```javascript
export const Component = () => {
  const [ update ] = useUpdateMutation({ fixedCacheKey: "cache-key" });

  return <button onClick={() => update(values)}>Submit</button>
}
``` 

In the group of endpoints, we have other GET and POST functions that use `onQueryStarted` with `queryFulfilled` that work as expected, only this specific PATCH seems to have this issue and I have not been able to reproduce it otherwise. Also, utilizing redux dev-tools, I did confirm that this specific request is being rejected the same way as others.

Thanks!

**Comment by markerikson** [comment]
Could you record and share a Replay ( https://replay.io/record-bugs ) that shows what's happening in your app?

**Comment by phryneas** [comment]
We do have a test for this, so we really need a reproduction of your specific case (or a replay) to see this ourselves

https://github.com/reduxjs/redux-toolkit/blob/24fc34392d249573fd14088db8daea10e848de41/packages/toolkit/src/query/tests/queryLifecycle.test.tsx#L98

**Comment by altr-jeremyscott** [comment]
This issue has been resolved after I was able to look at it with fresh eyes this morning.

For reference, the bug:
```javascript
invalidatesTags: (result, _error, args) => {
  /*
  In this specific endpoint, my invalidate tags callback requires the context of the result.
  Due to the error, the result was undefined and I was not checking if the result was undefined or not.
  This error was causing the endpoint to throw silently. 
  */
  const { id } = result;
  
  return [{ type: "Type", id }];
}
``` 
I was able to successfully debug this issue by using `unwrap()` at the action call and catching it there. I was able to see the full stack trace, which pointed me to the `invalidateTags` callback. Most of my confusion came from the fact this caused `queryFulfilled` to neither resolve nor reject.

 In this specific case, is it expected that `queryFulfilled` would behave this way?
 
 I appreciate the quick responses and pointing me toward those tests! After seeing those, I assumed it had to be some funk on my side.

**Comment by EskiMojo14** [comment]
ah, that makes sense - both the tag invalidation and query lifecycle are managed by "sub-middlewares", and the invalidationByTags sub-middleware is before the queryLifecycle one. that means that an uncaught error would presumably prevent the chain from continuing, and thus the sub-middleware intended to resolve the lifecycle promise would never get called

https://github.com/reduxjs/redux-toolkit/blob/32e90810b8e4a7b9f274d47bc8cdad8776398947/packages/toolkit/src/query/core/buildMiddleware/index.ts#L46-L53

but yeah, with providesTags/invalidatesTags callbacks it's important to note that they'll be called both for successful and unsuccessful results, and it's up to you how to handle that based on whether result or error is defined
