### ISSUE TITLE
RTK Query: how to query data without hooks, and listen when the data becomes available

### ISSUE THREAD

**Issue by hkar19** [reduxjs/redux-toolkit#3575]
Hello, i have a problem where i need to fetch data from an array of string, which can be longer or shorter. because of this i cannot afford to use `useQuery` as by rule of hooks: `number of hooks call before should equal to number of hooks call after`.

My plan is i am going to create a custom hook where i can initiate data call in `useEffect` as in:
```ts
React.useEffect(()=>{
  const results = arr.map(a=> api.endpoints.getData.initiate({code: a}) );

  return ()=> results.forEach(r=>r.unsubscribe())
},[arr])
```

and return the data as in
```ts
return arr.map(a=>{
  const selector = api.endpoints.getData.select({code: a});
  const val = selector(store.getState());
  return val;
})
```

the thing is, the return values are not updated when the data becomes available. how do listen for that, what did i miss?

whole plan:
```ts
const useGetDataFromCodes = (arr: string[])=>{
React.useEffect(()=>{
  const results = arr.map(a=> dispatch(api.endpoints.getData.initiate({code: a})) );

  return ()=> results.forEach(r=>r.unsubscribe())
},[arr])

return arr.map(a=>{
  const selector = api.endpoints.getData.select({code: a});
  const val = selector(store.getState());
  return val;
})
}
```

**Comment by EskiMojo14** [comment]
you shouldn't ever be calling store.getState directly like that - and it won't set up a subscription to the data changing in store
instead, do something with useSelector, for example 
```ts
const selectors = useMemo(() => arr.map(a => api.endpoints.getData.select({code: a})), [arr])
const results = useSelector((state) => selectors.map(selector => selector(state)), shallowEqual) // the shallowEqual is important
return results
```

**Comment by hkar19** [comment]
I did it with your suggestion. thank you.

but it make me wonder, how do you select without using hook? 
but nonetheless as i am able to setup exactly one hook for this, your response is already workable.

**Comment by markerikson** [comment]
@hkar same as any other Redux data in general - some form of `store.getState().api.queries[key]`, etc.  Note that RTKQ's endpoints do most of that lookup work for you with `endpoints.someEndpoint.select(cacheArgs)`:

- https://redux-toolkit.js.org/rtk-query/usage/usage-without-react-hooks

**Comment by hkar19** [comment]
What i meant was how do i get the data without using `useSelector` but still with subscription.

In my case i am able to use the hook `useSelector` and pass my selector in order to get my state, but how do i get the state without using `useSelector`?

**Comment by markerikson** [comment]
@hkar19 that's exactly what I was saying.

`useSelector` inside is ultimately calling `return selector(store.getState())`, _and_ subscribing to the store to determine when to call the selectors again and force a re-render.

If you're not using the hooks, you have to do that same work yourself.
