### ISSUE TITLE
Re-export produce from immer?

### ISSUE THREAD

**Issue by rickysullivan-gallagher** [reduxjs/redux-toolkit#3578]
Is there anyway the export from immer could be re-exported by redux-toolkit so I don't have implicit imports?

`import { produce } from '@reduxjs/toolkit'` or something like that

**Comment by markerikson** [comment]
We do that already, as `createNextState`:

https://redux-toolkit.js.org/api/other-exports#createnextstate

What "implicit imports" are you referring to?

**Comment by rickysullivan-gallagher** [comment]
Oh rad. 

My own code where I'm using Immer. I was [implicitly adding it](https://www.npmjs.com/package/eslint-plugin-implicit-dependencies) and getting a warning with eslint.
