### ISSUE TITLE
Using RTKQUERY in the new Nextjs App Router for server components 

### ISSUE THREAD

**Issue by browyn** [reduxjs/redux-toolkit#3581]
I had avoided using the NextJs app router feature until now since it wasn't stable yet.
I plugged into it yesterday and I'm trying to set up redux in my application like I always do, setting redux up to use in client components is pretty straight forward, however I can't get my head around using it in server components.

Is there any way around this yet ?

**Comment by markerikson** [comment]
See links to other discussions in #3508 , as well as https://nextjs.org/docs/getting-started/react-essentials#rendering-third-party-context-providers-in-server-components .
