### ISSUE TITLE
Can't resolve redux in xx/node_modules/@reduxjs/toolkit/dist'

### ISSUE THREAD

**Issue by alicanertop** [reduxjs/redux-toolkit#3582]
Hello i have a problem a while when i tried to start my project with webpack, I m getting this error.

my project is right here -> https://github.com/alicanertop/MGT2Helper
just clone and `yarn webpack` or `npm run webpack`. 
Its working fine with react-scripts but i just want to figure out what's wrong my webpack config ?

<img width="1649" alt="Screenshot 2023-07-06 at 21 42 33" src="https://github.com/reduxjs/redux-toolkit/assets/40334071/3eaba9aa-3cfc-4fd2-be56-b1c02a9c0912">

**Comment by markerikson** [comment]
This seems like it's more likely an issue with your config than with our library.  Could you ask this in the `#redux` channel in the Reactiflux Discord ( https://www.reactiflux.com ) instead?
