### ISSUE TITLE
Cannot read properties of undefined (reading 'matchFulfilled')

### ISSUE THREAD

**Issue by coderb0yakash** [reduxjs/redux-toolkit#3593]
Hi I am using the latest version 

I am trying to grab an event using the 

`builder.addMatcher(
            ApiSlice.endpoints.getProfile.matchFulfilled,
            (state, { payload }) => {
                console.log(payload)
            }
        )`
this code but getting anerror Uncaught TypeError: Cannot read properties of undefined (reading 'matchFulfilled')

but same is working for another endpoints

**Comment by markerikson** [comment]
Presumably `endpoints.getProfile` is undefined, but we can't have any idea why without seeing the actual code or a Replay ( https://replay.io/record-bugs )
