### ISSUE TITLE
Endpoint name argument of updateQueryData is not assignable to parameter type QueryKeys<Definitions>

### ISSUE THREAD

**Issue by jalxby** [reduxjs/redux-toolkit#3609]
![image](https://github.com/reduxjs/redux-toolkit/assets/73418503/07fa7692-f494-4413-99ac-8596820cdc30)
Hi! May be it simple issue but can't get what wrong with that updateQueryData  fn. Thank you for participating.

**Comment by markerikson** [comment]
Unclear what the question is or how to reproduce it.

**Comment by EskiMojo14** [comment]
could you create a reproduction, in TS Playground or CodeSandbox?
