### ISSUE TITLE
RTKQ: Invalidate Tags for an ongoing fetch

### ISSUE THREAD

**Issue by Crayee** [reduxjs/redux-toolkit#3622]
I have a useQuery that fetches a lot of data and takes a few seconds to load. Meanwhile the user can edit the data quickly, firing a useMutation each time. I am using invalidateTags to invalidate the cache of the Query.

However when 2 or more Mutations get executed before the Query fetch was completed, I get a race condition, because invalidateTags just invalidates the Cache but doesn't trigger another refetch, while there is an ongoing fetch.

I would appreciate any help or advice on my problem :D

**Comment by EskiMojo14** [comment]
I believe this is what https://github.com/reduxjs/redux-toolkit/pull/3116 aims to solve - I'm unsure of where that stands in terms of getting merged currently.

**Comment by Crayee** [comment]
@EskiMojo14 Thank you. This looks to solve my issue, hope it gets merged soon.
