### ISSUE TITLE
Property 'originalStatus' does not exist on type 'FetchBaseQueryError'.  

### ISSUE THREAD

**Issue by jr00n** [reduxjs/redux-toolkit#3626]
When i try to get 'originalStatus' propery on a FetchBaseQueryError i get:

"Property 'originalStatus' does not exist on type 'FetchBaseQueryError'.
  Property 'originalStatus' does not exist on type '{ status: number; data: unknown; }'."

`const baseQueryWithReauth = async (args, api, extraOptions) => {`
`  let result = await baseQuery(args, api, extraOptions);`
`  if (result?.error?.originalStatus === 403) {`
`    api.dispatch(logOut());` 

I see that the FetchBaseQueryError type can handle originalStatus property in some cases, but still TS thinks it is not true.
What can be wrong?

**Comment by markerikson** [comment]
You probably need to do a TS narrowing check, like `if (result?.error && 'originalStatus' in result.error)`.
