### ISSUE TITLE
Help - How to create select for RTKQ endpoint with arguments?

### ISSUE THREAD

**Issue by nouman91** [reduxjs/redux-toolkit#3627]
Hi,
I have a use case where I want to create a selector for the RTKQ endpoint. The idea is to have an error selector for the endpoints and use that in the components. 
I have looked everywhere so far I have not found any example of how to create a selector with arguments. 
Example code:

```
export const myApi = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    getSomeData: builder.query<Type[], string[]>({
      query: (params) => ({
        params: { uuids: params.join(',') },
        url: 'url,
      }),
      transformResponse: (res: { results: Type[] }) => res.results,
          }),
  }),
});


const apiInfo = apiSlice.endpoints.getThreats.select(???? how to pass argument here)
export const apiErrorSelector = createSelector(apiInfo, state=>state.error);

```

**Comment by EskiMojo14** [comment]
the typical pattern is to make a new selector each time:
```ts
export const apiErrorSelector = createSelector(
  (state, arg) => apiSlice.endpoints.getThreats.select(state)(arg), 
  state=>state.error
);

apiErrorSelector(state, arg)
```
this however will suffer from incorrect memoisation. on the other hand, you could wrap your own selector creator:
```ts
const makeApiErrorSelector = (arg) => {
  const apiInfo = apiSlice.endpoints.getThreats.select(arg)
  return createSelector(apiInfo, state=>state.error);
}
```
This would allow for proper memoisation as long as you hold onto the selector instance.

To offer a completely different approach, have you considered using [`selectFromResult`](https://redux.js.org/tutorials/essentials/part-8-rtk-query-advanced#selecting-values-from-results)?

**Comment by phryneas** [comment]
Also, with some memoization:
```js
const createApiSelector = createSelector(
  arg => arg,
  apiSlice.endpoints.getThreats.select
>

export const apiErrorSelector = createSelector(
  state => state,
  (state, arg) => createApiSelector(arg), 
  (state, selector) =>selector(state).error
);
```

**Comment by nouman91** [comment]
Thank you! While these solutions work, I will go with a different approach as my idea was to show errors without much for business logic since this will require to know arguments it will not work for my use cases.

**Comment by nouman91** [comment]
Thank you! While these solutions work, I will go with a different approach as my idea was to show errors without much for business logic since this will require to know arguments it will not work for my use cases.

**Comment by andreisocaciu** [comment]
I think this solution should be included in the documentation. I searched a bit to find a solution, and I really think it would be easier if it was included in the [section](https://redux-toolkit.js.org/rtk-query/usage/usage-without-react-hooks#accessing-cached-data--request-status) about using RTK Query without hooks. Right now it only talks about simple queries that don't have any parameters.

**Comment by EskiMojo14** [comment]
yeah, in general that section is a little neglected - I'll see if I can add a bit to it today

**Comment by EskiMojo14** [comment]
@andreisocaciu thoughts on https://github.com/reduxjs/redux-toolkit/pull/3963?

**Comment by andreisocaciu** [comment]
@EskiMojo14 That is perfect.
