### ISSUE TITLE
[Question] RTKQ: Base query with global errors rejection using default "fetchBaseQuery" or interceptor using custom axios base query

### ISSUE THREAD

**Issue by nk11dev** [reduxjs/redux-toolkit#3630]
Hi. I am using RTK Query with custom axios base query, like in the docs. And it works well.
https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#axios-basequery

### The problem:
I am trying to implement automatic re authorization. I see example from docs for default `fetchBaseQuery` from `@reduxjs/toolkit/query`.

https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery

In example there is slightly different behavior of handling errors with default `fetchBaseQuery`: responses with errors are matched as `fullfilled`, not as `rejected` (as in custom axios base query). And when I use queries or mutations - `isError` property in result is false.

And this is a problem, because I am trying to repeat behavior with auto rejecting responses with `rejected `status. I read some comments and information in docs, that this is by design, as I can understand. 

Now I am thinking of implementing the auto rejecting error responses along with intercepting of error HTTP codes in base query in two different ways: using default `fetchBaseQuery` or using custom axios base query.

### My questions are:
**1) How exactly custom axios base query is setting `rejected `status and how I can repeat these behavior with default `fetchBaseQuery`?** 

```
// Example from the docs https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery

import { fetchBaseQuery } from '@reduxjs/toolkit/query'
import type {
  BaseQueryFn,
  FetchArgs,
  FetchBaseQueryError,
} from '@reduxjs/toolkit/query'
import { tokenReceived, loggedOut } from './authSlice'

const baseQuery = fetchBaseQuery({ baseUrl: '/' })
const baseQueryWithReauth: BaseQueryFn<
  string | FetchArgs,
  unknown,
  FetchBaseQueryError
> = async (args, api, extraOptions) => {
  let result = await baseQuery(args, api, extraOptions)
  
  // How can I set "rejected" status for responses with errors here?
  
  if (result.error && result.error.status === 401) {
    const refreshResult = await baseQuery('/refreshToken', api, extraOptions)
    if (refreshResult.data) {
      api.dispatch(tokenReceived(refreshResult.data))
      result = await baseQuery(args, api, extraOptions)
    } else {
      api.dispatch(loggedOut())
    }
  }
  return result
}
```

I suppose it is some default behavior, based on HTTP status codes in response. I saw  some information in docs about handling errors using `unwrap` or `unwrapResult`:
- https://redux-toolkit.js.org/api/createAsyncThunk#checking-errors-after-dispatching
- https://redux-toolkit.js.org/rtk-query/usage/error-handling#error-display-examples 

But it looks like a way of handling errors rejection "locally" (while I'm looking for a more "global" way of rejection).

**2) Is there any example how to implement interception of response statuses with custom axios base query?**

I am now working with handling of 401 HTTP status code for auth and think of axios interceptors feature, but I am not sure how to add it properly. For example, how https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#axios-basequery can be extended with axios interceptors? I think that it can be added to `catch` block, is there some best practices how to do it properly?

```
// Example from the docs https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#axios-basequery

const axiosBaseQuery =
  (
    { baseUrl }: { baseUrl: string } = { baseUrl: '' }
  ): BaseQueryFn<
    {
      url: string
      method: AxiosRequestConfig['method']
      data?: AxiosRequestConfig['data']
      params?: AxiosRequestConfig['params']
    },
    unknown,
    unknown
  > =>
  async ({ url, method, data, params }) => {
    try {
      const result = await axios({ url: baseUrl + url, method, data, params })
      return { data: result.data }
    } catch (axiosError) {
    
    // Is there some best practices or recommended approach how to implement re authorization here?
    
      let err = axiosError as AxiosError
      return {
        error: {
          status: err.response?.status,
          data: err.response?.data || err.message,
        },
      }
    }
  }
```

Thank you for your time.

**Comment by phryneas** [comment]
I am sorry, this is like 20 questions in 3 sentences - could you please make your question a bit more focused and clear?

Generally: any `baseQuery` either returns `{ data, meta }` or `{ error, meta }`. As long as your bq does that, it will set `isError` etc. correctly.

On top of that: we have `axios` in the docs because people ask for it, but we should really put more warning signs in front of that: you add 8kb of bundle size to your app without any benefit. Every axios feature that makes sense using with RTK Query can also just be replicated with `fetch`, which is already part of your browser. Do you have a specific reason why you are dabbling with axios in the first place here?

Also, to answer that question: reauthentication with `axios` works pretty much the same way as if you were using `fetchBaseQuery`, you would probably add some kind of `meta` to your baseQuery to add information about headers etc., but again: No need for axios in the first place. Just don't do that.

**Comment by nk11dev** [comment]
Thanks for response! 

Please, could you be more polite in communication? This is not "like 20 questions in 3 sentences". Sorry for some of the confusion, but I originally mentioned that the problem is that `isError` came as `false`. I mentioned that I have 2 implementation options (`fetchBaseQuery` or `axios`) of base query and listed them as two questions, which I highlighted in bold. If there is an answer to one, then this will be enough.

Your explanation about `isError` let me know that I did something wrong when I reproduced the example. I reproduced everything from scratch and everything worked as expected with `fetchBaseQuery`.

Answering your question about `axios` - I didn't use axios "in the first place", but because I tried several solutions for working with redux besides RTKQ. It was already in my project. And my application is a kind of sandbox for working out different solutions at the current stage. That's why I originally used the `axios` example - as a more familiar data retrieval option to me compared to `fetchBaseQuery`.

But I agree with you that it will be useful to indicate in the documentation that if you do not have `axios` for some specific reason, then `fetchBaseQuery` will be enough for you.
