### ISSUE TITLE
IsFetching work incorrect

### ISSUE THREAD

**Issue by VictorPulzz** [reduxjs/redux-toolkit#3631]
Hey, I'm faced with problem with isFetching.
When I use rtk query and lazy request for getting data I got incorrect isFetching behavior
I send request in useEffect, and I expect that I will have the following logic: first isLoading = false, then a request is made in useEffect and isLoading = true, and then false again. In this case, isFetching is always false, because I am making a request once. But for some reason isFetching shows this:
![image](https://github.com/reduxjs/redux-toolkit/assets/23406402/ff8272a5-2d7a-4d20-847f-2c845a0cd9a2)

code inside component:
![image](https://github.com/reduxjs/redux-toolkit/assets/23406402/b2eed822-8f6d-44ec-8f4f-6383a35e9d7e)
 
endpoint:
![image](https://github.com/reduxjs/redux-toolkit/assets/23406402/cf6af9b2-4c83-4487-8483-697503d96e33)

**Comment by phryneas** [comment]
Why do you say you expect specific values for `isLoading` and then log out `isFetching`?

As for what is visible here, the `isFetching` behaviour is exactly what I would expect. You call the trigger function, and probably already get an old value from cache, but you triggered a network request, so it is briefly `true`.

Also, why do you use `useLazyQuery` here? This is a prime use case of `useQuery` and you really should avoid `useEffect` whenever you can.

**Comment by VictorPulzz** [comment]
Hello @phryneas ! Thanks for answer, I meant that the logic of work is wrong and gave an analogy, there really was data from the cache, so I did keepUnusedDataFor = -1. And I use lazy because I have infinit scroll (which you don't like :D)

**Comment by phryneas** [comment]
I'm sorry, but I really don't understand what you mean.

What are you getting?
What do you expect?
