### ISSUE TITLE
.unsubscribe is not a function (on unmount, if trigger hasn't called yet)

### ISSUE THREAD

**Issue by olosegres** [reduxjs/redux-toolkit#3632]
Hello,

I wanted to use RTK Query in the hook that uses query data conditionally.

```
const useCurrentItem = () => {
  const params = useLocationParams();
  const id = params.get('id');

  const currentItem = useSelector(selectCurrentItem); // it updates via extraReducers and endpoints.getItemById.matchFulfilled
  const [trigger, { isLoading }] = useLazyGetItemByIdQuery();

  useEffect(() => {
    if (id) {
      trigger(id);
    }
  }, [id]);

  return { currentItem, isLoading };
};
```

But it throws error on hook unmount if trigger hasn't called.

In the sources react hook of RTQ Query calls `promiseRef.current.unsubscribe` without check has it subscribed or not.

It looks like it just wasn't thought about and it's easy to fix.

**Comment by phryneas** [comment]
Huh, curious - will have to look into this.

In the meantime: for conditional use, you really don't have to go the `lazy` route:

```js
  const { isLoading } = useGetItemByIdQuery( id ? id : skipToken);
```

Where `skipToken` is an import from RTK Query.

**Comment by olosegres** [comment]
@phryneas 
Thanks for the tip!

**Comment by olosegres** [comment]
I realized that the problem was on my side, in how the middleware is configured.
The error manifested itself due to one custom middleware that wraps the Promise (RTK Query seems to use a special Promise object with unsubscribe method).
