### ISSUE TITLE
[Question]: Getting "Uncaught in promise" error when using `.unwrap()`

### ISSUE THREAD

**Issue by koukalp** [reduxjs/redux-toolkit#3639]
I am using `rtk-query` and would like to ask whether the following behaviour is the intended design of the library or whether it means I am doing smthg wrong on my side. 

### Issue Description
1. I define an API with `rtk-query` and have a generic error handler / formatter in there:
```
export const api = createApi({
   // ... some setup
    baseQuery: graphqlRequestBaseQuery({
        customErrors: (gqlResponse) => {
            if (gqlResponse.response.errors) {
                  // ... some custom handling of the api
            return gqlResponse.response;
        },
    }),
    ...
```
2. I also have a error middleware for rtk-query taken over from the documentation: https://redux-toolkit.js.org/rtk-query/usage/error-handling
3. I create an api slice and have a simple mutation in there
4. I use the mutation with the .unwrap() like so
```
// in .tsx file
const [deleteLogo, {error}] = api.useDeleteLogoMutation();

const onDelete = useCallback((id) => {
   deleteLogo({id}).unwrap().then(
       // ... some custom behaviour
   )
   // there is NO catch block
```

It works as expected, however, when the GraphQL API returns an error for the mutation 
```
{data: undefined, errors: [{message: "Invalid request"}]}
```
the application "crashes" and shows the "red" page for an unhandled error

### My question
Is this the expected behaviour? Therefore, when using `unwrap()`, do I always have to provide a `.catch` block?

I assumed the error will get caught by rtk-query (btw both `customErrors` in the `createApi` and `errorMiddleware` run as expected) and I thought the error will be handled there and put into the `{error}` when using `useDeleteLogoMutation()`

**Comment by EskiMojo14** [comment]
By using .unwrap you are explicitly creating a promise that can reject, and are expected to handle that.

https://github.com/reduxjs/redux-toolkit/issues/3620#issuecomment-1651120132

**Comment by koukalp** [comment]
Thank you for the answer. The catch block can be empty and then everything works as expected, e.g. the `error` field gets populated etc. That's why it was looking strange to me. 

Is there a cleaner way to act on the API call resolution? The following looks suspicious in the code and needs a comment for other developers so that it doesn't get deleted:

```
deleteLogo().unwrap().then(() => // do something custom).catch(() => undefined // don't delete the catch block, it's necessary for the app to work and the eventual error from rtk-query to be displayed as expected)
```

**Comment by phryneas** [comment]
You could just not call unwrap, since that has the purpose of throwing an error. No error without it.

**Comment by koukalp** [comment]
I understood the the `unwrap` is necessary if I want to wait for the `deleteLogo` to `complete`

You are saying the following works the same and doesn't need the catch block???

```
deleteLogo().then(() => // do something custom)
```

**Comment by EskiMojo14** [comment]
without unwrap, the promise will always resolve, regardless of whether the request succeeded or failed. you would then need to check if the object the promise resolved with has a data property or an error property to determine if it was successful.

**Comment by koukalp** [comment]
Thank you a lot. I must have missed it in the documentation.

**Comment by phryneas** [comment]
Maybe it makes more sense looking at the sources?

https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/createAsyncThunk.ts#L730-L740

The point of it is to return action.paylpad or throw.

**Comment by koukalp** [comment]
Thank you very much for the support and sharing your expertise. Truly awesome.

**Comment by fhanggi** [comment]
Sorry I know this is closed but i did not see an answer to the question if  this code is ok
deleteLogo().then(() => // do something custom)

i tried this in my code and it seems to work. but i would just like to hear from RTKQ maintainers if this is really ok without the unwrap and catch. 

    await editApplication({ id: dataItem.id, formValues: dataItem }).then((data) => {
      console.log(data);
      if (!data.error) {
        console.log("ApplicationEdit: SUCCESSFUL EDIT");
        history.push("/admin/applications");
      }
    });
