### ISSUE TITLE
Writing about "Posts" in documentation for queries and mutations is confusing

### ISSUE THREAD

**Issue by flyingace** [reduxjs/redux-toolkit#3641]
When trying to suss out how to use RTK Query across different HTTP request methods it is very confusing to find example code peppered with references to "Post" and "Posts" given that POST is a common HTTP request method. Obviously this isn't an issue that should bring all further development to a halt until resolved but I'm surprised that this wasn't taken into consideration when writing out the documentation.

Consider the following example from [Defining Mutation Endpoints](https://redux-toolkit.js.org/rtk-query/usage/mutations#defining-mutation-endpoints)
```
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query'
import type { Post } from './types'

const api = createApi({
  baseQuery: fetchBaseQuery({
    baseUrl: '/',
  }),
  tagTypes: ['Post'],
  endpoints: (build) => ({
    updatePost: build.mutation<Post, Partial<Post> & Pick<Post, 'id'>>({
      // note: an optional `queryFn` may be used in place of `query`
      query: ({ id, ...patch }) => ({
        url: `post/${id}`,
        method: 'PATCH',
        body: patch,
      }),
      // Pick out data and prevent nested properties in a hook or selector
      transformResponse: (response: { data: Post }, meta, arg) => response.data,
```

**Comment by phryneas** [comment]
Well... POST is a HTTP verb - post, Post, pOSt and other variations are not. 
Also, you see forum posts, blog posts, and the likes are normal parts of the internet.

Is this really such a problem? 😕

**Comment by markerikson** [comment]
Agree that there's a bit of word overlap here, but also it's _hard_ to come up with good examples :)

**Comment by flyingace** [comment]
It's not a problem if you already understand the product you're working with. But if you're trying to figure out that in order to make a POST request you need to use a `mutation` instead of a `query` and you see `updatePost: build.mutation<Post, Partial<Post> & Pick<Post, 'id'>>({` you could be thrown off a bit.
And I get that it's hard to come up with good examples, naming things and all that and I didn't expect it to be moved to the top of the queue, I just thought you might like the feedback on how your docs might be read by a user. I didn't think that my passing this along would end up being "such a problem." 🎊

**Comment by markerikson** [comment]
Yeah, not trying to be dismissive - I definitely see how it could be confusing.  but tbh we're all feeling a bit burnt out and trying to take time off atm, and even then, tweaking existing docs is pretty low on the priority list. If you or someone else would like to file PRs to improve the docs (content, wording, examples, etc), we're _always_ interested! But past that, I don't think we have the energy to make wording tweaks to existing examples in the foreseeable future.

**Comment by phryneas** [comment]
I think you have a misconception here that has nothing to do with the word Post:

You can make POST requests with queries and GET requests with mutations. Queries and mutations are not about HTTP verbs, but about intent.

You want to get data? Use a query, even if the server accepts a POST request for it.

You want to change something on the server? Use a mutation.

Both work with the same syntax.
