### ISSUE TITLE
Document fragmentation of Redux, Redux-Toolkit, React-Redux

### ISSUE THREAD

**Issue by ryota-murakami** [reduxjs/redux-toolkit#3653]
During upgrade work for my [RTK & Query starter](https://github.com/laststance/vite-rtk-query) I want to know official recommended directory structure style.  
Firstly I went to [Redux-Tookit Docs](https://redux-toolkit.js.org/usage/usage-with-typescript#createslice), there is `createSlice()` API description and tutorial but I couldn't see bestpractice pert.

Next, I search Google and reach [Recommended folder structure for Redux-Toolkit?](https://www.reddit.com/r/reactjs/comments/tnna7t/recommended_folder_structure_for_reduxtoolkit/) reddit and answering @markerikson .
He navigated 2 original Redux document links, I also followed that.
https://redux.js.org/style-guide/style-guide#structure-files-as-feature-folders-with-single-file-logic
https://redux.js.org/tutorials/essentials/part-2-app-structure

My concern is Redux-Toolkit best practice written original Redux docs instead of Redux-Toolkit docs is confusable generally.
Why I can't reach Redux-Toolkit at Redux-Toolkit docs?
Why original Redux docs explain well with superset library & API that doesn't exist original Redux? 

If you have a any thought or intent, I'm glad to hear that.

**Comment by markerikson** [comment]
Yeah, I wrote up a long answer over in this issue describing why we have the docs split the way they are:

https://github.com/reduxjs/redux-toolkit/issues/2637#issuecomment-1229091424
