### ISSUE TITLE
Feature Request: transform data before its passed to fetch() in mutation

### ISSUE THREAD

**Issue by Stophface** [reduxjs/redux-toolkit#3655]
Thanks for Redux Toolkit and Redux Toolkit Query. I have a feature request.
It is possible to transform a response with `transformResponse()`. This works in `query` and `mutation`. Why is there no `transformPost()` or something similar that allows to transform the data _before_ its passed on to the `fetch()` wrapper implemented in Redux Toolkit Query? 

       addPostToUsersPostList: builder.mutation({
            query: (payload) => ({
                method: 'POST',
                body: payload,
                url: ...,
                headers: {
                    'Content-Type': 'application/json',
                }
            }),
          transformPost: ....
     }),

By implementing this, all the transformation that need to be done to interact with the API can be done in one place, the `apiSlice`. Currently, only the transformations of a response are gathered here, but the transformation of a post are scattered in the files where the hooks are called.

**Comment by EskiMojo14** [comment]
this is what `query` is for.

```ts
   addPostToUsersPostList: builder.mutation({
        query: (payload) => ({
            method: 'POST',
            body: transformPost(payload),
            url: ...,
            headers: {
                'Content-Type': 'application/json',
            }
        }),
 }),
```
