### ISSUE TITLE
Redux-toolkit Typescript error: Argument of type 'registerResponseBody' is not assignable to parameter of type 'WritableDraft<AuthenticatedUser>'

### ISSUE THREAD

**Issue by niralivasoya** [reduxjs/redux-toolkit#3657]
I have used redux-toolkit asyncThunk action for adding the user. I am attaching the initialStates and the used types as well. please help me to fix the issue.

This is my initial states:
`interface OrganizationUserState {
    users: AuthenticatedUser[];
    status: 'pending' | 'error' | 'success' | null;
    error: string | null;
}

const initialState: OrganizationUserState = {
    users: [],
    status: null,
    error: null,
};`

This is my adding user action

`// Invite a User to an Organization
export const inviteOrganizationUser = createAsyncThunk<registerResponseBody, registerRequestBody>(
    'organizationUserSlice/inviteOrganizationUser',
    async (user, thunkAPI) => {

        try {
            const response = await HttpService.post(`/organization/${user.organization}/invite`, user);
            return await response as registerResponseBody;
        } catch (error) {
            return thunkAPI.rejectWithValue('Error');
        }
    }
);`

This is my extraReducers cases

`.addCase(inviteOrganizationUser.pending, (state) => {
                state.status = 'pending';
                state.error = null;
            })
            .addCase(inviteOrganizationUser.fulfilled, (state, action) => {
                state.status = 'success';
                state.users.push(action.payload)
                // state.users = [...state.users, action.payload];
            })
            .addCase(inviteOrganizationUser.rejected, (state, action) => {
                state.status = 'error';
                state.error = action.payload as string;
            })`

This is the type for the registerResponseBody

`export type registerResponseBody = Success<AuthenticatedUser> | Fail;`

How can I push the newly added the user to the existing user state. I am having typescript error when I try to push the action.payload to the state.

**Comment by phryneas** [comment]
It doesn't seem like AuthenticatedUser and registerResponseBody have a similar shape? You probably have to make some tests if it is really the correct thing - that probably boils down to a TS question, not a RTK question though.
