### ISSUE TITLE
Bad link in documentation (RequestInit)

### ISSUE THREAD

**Issue by Matiaseid** [reduxjs/redux-toolkit#3667]
On this page https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery#using-fetchbasequery

On the word RequestInit
You have a link to https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch
that redirects to https://developer.mozilla.org/en-US/docs/Web/API/fetch
But this page has no mention of RequestInit

**Comment by markerikson** [comment]
It's a TS type, but it's describing the behavior shown in this example from the `fetch` page:

```ts
const myInit = {
  method: "GET",
  headers: myHeaders,
  mode: "cors",
  cache: "default",
};

const myRequest = new Request("flowers.jpg");

fetch(myRequest, myInit).then((response) => {
  // …
});
```

**Comment by phryneas** [comment]
Yeah the mdn sometimes calls it init, sometimes options.
