### ISSUE TITLE
Network Call Not Made and Only Using Cached Data After App Restart

### ISSUE THREAD

**Issue by Kaung-Htet-Hein** [reduxjs/redux-toolkit#3668]
**Issue: Network Call Not Made and Only Using Cached Data After App Restart**

**Description:**

I am encountering an issue with lazy loading in a React Native app using Redux Toolkit's RTK Query. The lazy loading functionality is working as expected during the initial usage. However, after restarting the app or remounting a component, the network call is not being made, and the app is only using the cached data. This behavior is not in line with the expected behavior, where the cache should be invalidated when the app starts or the component mounts.

**Steps to Reproduce:**

1. Initialize the app and navigate to a component that utilizes the `productList` RTK Query endpoint for lazy loading.
2. Observe that the network calls are made as expected and data is being fetched.
3. Close the app or navigate to a different screen.
4. Reopen the app or navigate back to the component from step 1.
5. Notice that the network call is not made, and the app displays cached data instead of fetching fresh data.

**Environment:**

- React Native version: 0.72.1
- "@reduxjs/toolkit": 1.9.5
- "react-redux": "^8.1.1",
- "redux-persist": "^6.0.0",

**Code Snippet:**

```javascript

const baseAPI = createApi({
	refetchOnMountOrArgChange: true,
	baseQuery: baseQueryWithInterceptor,
	endpoints: builder => {
		return {}
	},
})

export const productService = baseAPI.enhanceEndpoints({
  addTagTypes: ['ProductList', 'ProductDetail', 'ProductVariant'],
}).injectEndpoints({
  endpoints: builder => ({
    productList: builder.query<BaseResponse<Array<IProduct>>, any>({
      query: params => {
        return {
          url: endpoints.productList,
          params,
        };
      },
      forceRefetch: ({ currentArg, previousArg }) => {
        return currentArg?.skip !== previousArg?.skip;
      },
      serializeQueryArgs: ({ endpointName }) => {
        return endpointName;
      },
      merge: (currentState, incomingState) => {
        currentState.data.push(...incomingState.data);
      },
      keepUnusedDataFor: 0,
    }),
  }),
  overrideExisting: true,
});
```

**Expected Behavior:**

The expected behavior is that when the app is restarted or when the component is remounted, the RTK Query should invalidate the cache and perform a fresh network call to fetch the latest data. Currently, the app is using cached data even after restarting or remounting.

**Additional Information:**

I have tried checking for possible solutions or workarounds but haven't been able to find a suitable solution. It seems like the cache is not being invalidated as expected after the app restarts or the component mounts again.

**Comment by markerikson** [comment]
I'm pretty confused what you mean by "the app restarts". If the app restarts completely, there should be _no_ data in the Redux store.

You mentioned `redux-persist`.  Are you actually persisting the API slice and cached data?

**Comment by markerikson** [comment]
This seems like an example of why we generally recommend _not_ persisting API slice data in the first place.  Let RTK Query re-fetch it when the app loads.

**Comment by phryneas** [comment]
You're also not using the hydration setup we describe in the docs, which means after persisting and rehydration, so the components that existed before app restart are still subscribed, even if they don't exist anymore.

https://redux-toolkit.js.org/rtk-query/usage/persistence-and-rehydration
