### ISSUE TITLE
Retrieving property `refetch` via `selectFromResult` throws property does not exist error

### ISSUE THREAD

**Issue by TheMythologist** [reduxjs/redux-toolkit#3673]
```ts
export const extendedApiSlice = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    getData: builder.query<any, void>({
      query: () => 'api/data',
    }),
  }),
})

export const { useGetDataQuery } = extendedApiSlice
```

```ts
const { data, refetch } = useGetDataQuery(undefined, {
  selectFromResult: ({ data, refetch }) => ({
    data,
    refetch,
  }),
})
```

This throws the error:
`Property 'refetch' does not exist on type 'UseQueryStateDefaultResult<QueryDefinition<number, BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, "Config" | ... 4 more ... | "Organization", { ...; }, "api">>'.`

Is this unexpected behaviour with regard to Typescript types? I am able to use the `refetch` function as expected in the above function.

_Side note_: Is using `selectFromResult` the best way to retrieve only the values that I need to prevent my component from re-rendering excessively?

**Comment by markerikson** [comment]
`refetch` gets attached automatically as an extra field on whatever object you return from `selectFromResult`.  So, you don't have to list it at all.

And yes, that's the main purpose of `selectFromResult`.

**Comment by TheMythologist** [comment]
I see, thanks, working as intended now.

I think the documentation needs some slight improvement with regard to `selectFromResult` (perhaps a mention of this in the introduction guide?) But I won't harp on it (I browsed through old issues and can see that it's a WIP). Closing this.

Thanks once again :)
