### ISSUE TITLE
How to invalidate specific cache data only with a nested queryArg

### ISSUE THREAD

**Issue by DarrenCzen** [reduxjs/redux-toolkit#3676]
Hello, I am trying to find out how i can invalidate a specific cache data with a nested object as a queryArg. 

Most of the examples in RTK Query Document is using a string/number as an Id value to access the cache data and use it as part of invalidateTags/provideTags as an example.  `invalidatesTags: (result, error, id) => [{ type: "Post", id }]`

I would like to refetch the page data based on only specific object. How can i invalidate a tag such that it only invalidates a specific cache data with a TableFilter object `{ Filter:'randomstring', PageNo: 5, PageSize:50 }` (after updating an object in my table on page 5) instead of invalidating every single cachekey (the pages i navigated through in my table) e.g. `{ Filter:'randomstring', PageNo: 1, PageSize:50 }, { Filter:'randomstring', PageNo: 2, PageSize:50 }, { Filter:'randomstring', PageNo: 5, PageSize:50 }`

Would appreciate your help on this. Thank you in advance.

```
interface TableFilter {
  Filter: string;
  PageNo: number;
  PageSize: number;
}

export const SettingsApis = api
  .enhanceEndpoints({
    addTagTypes: ['UpdateSettings'],
  })
  .injectEndpoints({
    endpoints: (build) => ({
      getSettings: build.query<SettingsResponse, TableFilter>({
        query: (queryArg) => {
          return {
            url: Endpoint.GET_SETTINGS,
            body: queryArg,
            method: 'POST',
          };
        },
        providesTags: ['UpdateSettings'],
      }),
      updateSettings: build.mutation<UpdateResponse, SettingsModel>({
        query: (queryArg) => {
          return {
            url: queryArg.Id == 0 ? Endpoint.INSERT_SETTINGS : Endpoint.UPDATE_SETTINGS,
            body: queryArg,
            method: 'POST',
          };
        },
        invalidatesTags: ['UpdateSettings'],
      }),
    }),
    overrideExisting: false,
  });
```

**Comment by nzaytsev** [comment]
https://redux-toolkit.js.org/rtk-query/usage/automated-refetching#cache-tags

You can create custom tag for your query based on args, then invalidate it

```ts

endpoints: (build) => ({
    getPosts: build.query<Post[], void>({
      query: () => '/posts',
      // define tags
      providesTags: (result, error, arg) =>
        {type: 'Posts', id: generateTagFromArg(arg)},
    }),
})

// clear cache

dispatch(api.util.invalidateTags({type: 'Posts', id: generateTagFromArg(arg)}))
```
