### ISSUE TITLE
Typescript issues when adding custom middleware

### ISSUE THREAD

**Issue by dpyzo0o** [reduxjs/redux-toolkit#368]
From the docs, I can get the type of `dispatch` by using `typeof store.dispatch`, this works well with the default middlewares. However, when I add my custom middleware, the inferred type of `dispatch` becomes `Dispatch<AnyAction>`. My question is, how can I properly type the custom middleware to make everything work together?

Here is the code for my store set up:

```js
import { configureStore, getDefaultMiddleware, Action } from '@reduxjs/toolkit';
import { ThunkAction } from 'redux-thunk';
import { createLogger } from 'redux-logger';

import rootReducer, { RootState } from './rootReducer';

const middleware = [...getDefaultMiddleware<RootState>()];

if (process.env.NODE_ENV === 'development') {
  middleware.push(createLogger());
}

function configStore(initialState: any) {
  const store = configureStore({
    reducer: rootReducer,
    middleware,
    preloadedState: initialState,
  });

  if (process.env.NODE_ENV === 'development' && module.hot) {
    module.hot.accept('./rootReducer', () => {
      const newRootReducer = require('./rootReducer').default;
      store.replaceReducer(newRootReducer);
    });
  }

  return store;
}

export type AppDispatch = ReturnType<typeof configStore>['dispatch'];

export type AppThunk = ThunkAction<void, RootState, unknown, Action<string>>;

export default configStore;

```

with this setup, the inferred type of `dispatch` is 

<img width="522" alt="Screen Shot 2020-02-18 at 12 09 57" src="https://user-images.githubusercontent.com/24768249/74703300-b6b9b180-5247-11ea-9137-7511061361d1.png">

when I add my custom middleware, I just change 
```js
const middleware = [...getDefaultMiddleware<RootState>()];
``` 
to 
```js
const middleware = [...getDefaultMiddleware<RootState>(), customMiddleware];
```

then the inferred dispatch becomes
<img width="586" alt="Screen Shot 2020-02-18 at 12 12 07" src="https://user-images.githubusercontent.com/24768249/74703439-25970a80-5248-11ea-8519-6963add7fbc1.png">

This will cause ts to complain when I dispatch a thunk action
<img width="787" alt="Screen Shot 2020-02-18 at 12 15 24" src="https://user-images.githubusercontent.com/24768249/74703517-6131d480-5248-11ea-8c75-9e437564cdea.png">

Here is how I define my custom middleware
```js
const customMiddleware: Middleware<{}, RootState> = store => next => action => {
  console.log(store.getState());
  const res = next(action);
  console.log(res);
  return res;
};
```

I have tried the suggestions in the doc but it does not solve the problem. https://redux-toolkit.js.org/usage/usage-with-typescript/#correct-typings-for-the-dispatch-type

Could someone help me?

note: I'm using version 1.2.4

**Comment by phryneas** [comment]
This seems to be a problem with TS losing some of the types in the `middleware` array, making it a `Middleware[]` type. :/

Does it help if you define it in this order?
```ts
const middleware = [customMiddleware, ...getDefaultMiddleware<RootState>()] as const;
```

**Comment by dpyzo0o** [comment]
@phryneas nope, as long as I add a custom middleware, the middleware array types change from
<img width="646" alt="Screen Shot 2020-02-18 at 15 47 33" src="https://user-images.githubusercontent.com/24768249/74714754-2f2f6b00-5266-11ea-9977-f2aec52a7427.png">
to
<img width="755" alt="Screen Shot 2020-02-18 at 15 47 49" src="https://user-images.githubusercontent.com/24768249/74714761-322a5b80-5266-11ea-902f-b4444aa46519.png">

**Comment by phryneas** [comment]
For me it seemed to be to be working in https://codesandbox.io/s/elegant-water-zyyvh , but now after a reload it isn't :/
This type erasure is deeply unsatisfying and I'm a bit out of ideas right now :(

Could you maybe ask a TS question on StackOverflow how one would best preserve all array value types here and report back? 
There are some real type wizards over there, maybe one of them has a better idea.

**Comment by dpyzo0o** [comment]
@phryneas Thanks for the feedback. For sure I can post a question on StackOverflow but I'm not sure I can describe the problem properly since I'm just new to typescript.

**Comment by phryneas** [comment]
I could do so too, but at the earliest 10 hours from now. I'd say just give it a try, the wizards over there are pretty good to figure out the intentions of the question ^^
Make sure to mention that it's an unintended type information erasure or something like that ^^

**Comment by TylorShin** [comment]
I found that this issue caused by the order of custom middlewares. 
for example,
![image](https://user-images.githubusercontent.com/9796103/75521628-7cbc8c80-5a4b-11ea-85e0-fec27c27d982.png)

this works fine (...defaultMiddleware should be the last order)

![image](https://user-images.githubusercontent.com/9796103/75521686-9958c480-5a4b-11ea-8b88-1cddb723d7cc.png)

but this doesn't work

**Comment by TylorShin** [comment]
If you have to change the order of middlewares, you should annotate the middlewares type manually. For example, 
```
 const middleware: Array<Middleware<{}, AppState> | ThunkMiddleware<AppState, AnyAction, { axios: AxiosInstance }>> = [
    ...defaultMiddleware,
    ReduxNotifier,
    setUserToTracker,
    loggerMiddleware,
  ];
```

**Comment by 0xdevalias** [comment]
In case anyone ends up here from google like I did, my issue was that the middleware I was adding (`LogRocket.reduxMiddleware()`) returned it's type as `any`, which broke thunks as described above.

For me, the simplest solution I came up with was to use `as ReturnType<typeof getDefaultMiddleware>` for it (since it's the rightmost middleware anyway):

Cut down example from my code:

```typescript
export const store = configureStore({
  // ..snip.. 

  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(
      LogRocket.reduxMiddleware() as ReturnType<typeof getDefaultMiddleware>
    ),

  // ..snip.. 
});
```

**Comment by eisodev** [comment]
For anyone like me using Redux Toolkit with redux-flipper, this seemed to work for me for getting AppDispatch to have the right type:

```
import { configureStore } from '@reduxjs/toolkit';
import rootReducer from '../redux/rootReducer';

const middlewares = [];
  
if (__DEV__) {
    const createDebugger = require("redux-flipper").default;
    middlewares.push(createDebugger());
}

const store = configureStore({
    reducer: rootReducer,
    middleware: (getDefaultMiddleware) => getDefaultMiddleware().concat(middlewares as ReturnType<typeof getDefaultMiddleware>),
});

export type AppDispatch = typeof store.dispatch;

export default store;
```

Other examples uses getDefaultMiddleware outside configureStore but that seems deprecated. Not sure this is the correct way, feedback appreciated.

**Comment by Simon-Tang** [comment]
Based on https://github.com/reduxjs/redux-toolkit/issues/446, I was able to use a middleware array this way using `as const` where the `export` happens:

```typescript
// some-middleware.js
const someListener = createListenerMiddleware();
...
export const multipleMiddlewareInstances = [
  someListener.middleware,
] as const;
```

```typescript
// store.ts
middleware: (getDefaultMiddleware) =>
  getDefaultMiddleware(
    ...
  ).prepend(multipleMiddlewareInstances),
```

**Comment by Red-hot19** [comment]
> [@phryneas](https://github.com/phryneas) nope, as long as I add a custom middleware, the middleware array types change from <img alt="Screen Shot 2020-02-18 at 15 47 33" width="646" src="https://user-images.githubusercontent.com/24768249/74714754-2f2f6b00-5266-11ea-9977-f2aec52a7427.png"> to <img alt="Screen Shot 2020-02-18 at 15 47 49" width="755" src="https://user-images.githubusercontent.com/24768249/74714761-322a5b80-5266-11ea-902f-b4444aa46519.png">





https://reactdev.space/questions/the-implementation-of-reducers-in-redux-toolkit-and-typescript-allows-for-efficient-state-management-and

**Comment by markerikson** [comment]
@Red-hot19 : _don't_ use plain array spreads here - that _will_ lose some of the types.

Instead, use the specially-typed `getDefaultMiddleware().concat()` (or in your case, `getDefaultMiddleware().prepend()` ) methods, which should preserve the middleware types correctly.

(Also you don't need to pass a generic to `getDefaultMiddleware`.)
