### ISSUE TITLE
Sponsored issue: Support request

### ISSUE THREAD

**Issue by imtinanzia** [reduxjs/redux-toolkit#3684]
## Priority Support

- @imtinanzia is using  [Mintycode](https://mintycode.io) to fund this issue.
- You can receive ![amount](https://imageupload.io/ib/zwkd2EaAY6YpPsg_1693209112.png) if you provide priority support to @imtinanzia. 
- To view the support request and terms go to  [Mintycode](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=6783ef6e-0f2d-49b6-be45-357de18b62e4&owner=reduxjs&name=redux-toolkit).
- Thank you in advance for helping.

[![mintycode](https://imageupload.io/ib/LvxMwrPxam1JW9e_1693210482.png)](https://mintycode.io)

**Comment by phryneas** [comment]
I think something is broken here, but this doesn't seem actionable in any way.
