### ISSUE TITLE
Showing data for the longest api call instead of the latest api call redux toolkit

### ISSUE THREAD

**Issue by Mubasher-Skylinx** [reduxjs/redux-toolkit#3685]
I have a list of items. on which i click and get that items ID and get details from database according to that id. I have a form which create a new item and then refetch list of items and the also fetch the detail of latest item and show the latest item's detail.

the issue is when i create a new item and refetch list call and then instead of one network call for item there goes two network calls. One for the previous item and one for newly item. Now my UI is showing that user has selected newly item but data is showing for previous item because previous item's call took more time then the latest and state was replaced by the last call that was fullfilled.

Can someone assist me how i can cancel the previous call and only save data of the latest call instead of the last call's data in RTK Query

Showing items detail on changing seletected item

**Comment by phryneas** [comment]
This should be impossible - RTKQ doesn't do a second network call for the same endpoint and arguments while the first is already running. But without code, it's hard to say anything here. Mind sharing some code?

**Comment by Mubasher-Skylinx** [comment]
there is alot of code. it will be hard to extract
here is the live project
https://v3.xoommaps.com/

here is the demo

https://www.loom.com/share/917d443bea5c447a8ab96013502dd2f8?sid=79400e89-0da9-4035-abe6-73a8b11e2f7a

you can see there are two calls on the same endpoint but with different IDs

so the latest call completes first and data get stored in redux
but the previous call completes later and also saved in the same state (so its overriding the latest state value)

**Comment by Mubasher-Skylinx** [comment]
email: jack@mailinator.com
password: Hello@1234

**Comment by EskiMojo14** [comment]
If they have different IDs (and thus different arguments) then they'll be cached separately, they shouldn't replace each other's cache.

**Comment by Mubasher-Skylinx** [comment]
i want a logic that will check if there is a request going on in the same url then cancel the previous and start the new one

**Comment by phryneas** [comment]
That's not what RTK Query does. It will finish both requests and put their results in different places - so if you go back to the last url, you immediately have the result.
While this result will make it into the cache, it will never accidentally be displayed to your user.

Cancelling the request usually doesn't avoid any work on the server, so it's more of a harmful placebo (since as a consequence you might have to rerun requests that you could otherwise just have waited for in the first place.

**Comment by Mubasher-Skylinx** [comment]
no no thats the problem.
it doesn't store that into the cache 
if runs my useEffect and override the state

like i said there goes two calls 
latest one completes earlier and data is save into the state
and the previous one completes after and override the data into the state

here is the code for function and state

```JS

    const [getMapById] = useLazyGetMapByIdQuery();

    useEffect(() => {
        getMapById(mapId);
    }, [mapDashboardId]);
    
```

**Comment by phryneas** [comment]
I assume that's pseudocode, since the variable names are all wrong, but generally you should not use the trigger function from `useLazyQuery` in a `useEffect`.  
Use `useQuery` instead.
