### ISSUE TITLE
`updateSubscriptionOptions` is not a property...

### ISSUE THREAD

**Issue by actionakin** [reduxjs/redux-toolkit#3688]
I have a very simple api with an endpoint of `getConfig` which does a simple fetch for my application config json.  After dispatching the initiate and awaiting for the response, I'd like to call `updateSubscriptionOptions` to enable polling based on a value found in the config response.

Example:
```typescript
const configRequest = dispatch(api.endpoints.getConfig.initiate());
const config = await configRequest;

configRequest.updateSubscriptionOptions({ ... });
```

The following typescript error appears:
`Property 'updateSubscriptionOptions' does not exist on type 'ThunkAction<QueryActionCreatorResult<QueryDefinition<void, BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, "config", __MergeDeep<...>, "api">>, any, any, AnyAction>'`

When I log out `configRequest` it is indeed there.

**Comment by EskiMojo14** [comment]
It sounds like your dispatch type is wrong - it doesn't seem to understand what thunks will return.

Have you followed the [Typescript Setup](https://redux.js.org/usage/usage-with-typescript#define-root-state-and-dispatch-types) to get your RootState and AppDispatch types?

**Comment by phryneas** [comment]
I'd guess that your `dispatch` type is missing the `ThunkDispatch` middleware type. Where does your `dispatch` get it's type from?

**Comment by actionakin** [comment]
This is absolutely it.  Thank you!
