### ISSUE TITLE
Using isFetching and isLoading with selectfromresult in query returns false as default

### ISSUE THREAD

**Issue by kaio-eduardo** [reduxjs/redux-toolkit#3690]
When using select From Result and returning isFetching isLoading from the query instead of the default true value they are returning as false even though the query has not been initialized.

**Comment by markerikson** [comment]
@kaio-eduardo : we'd need a lot more details to offer any help. Can you provide a CodeSandbox or a repo that shows what's happening, or record and share a Replay (https://replay.io/record-bugs ) ?

**Comment by kaio-eduardo** [comment]
i will provide a replay, but just to show the change in behavior i used OBS to record the status change from the query:

https://github.com/reduxjs/redux-toolkit/assets/44307221/59aaed26-89dc-43d1-9ba3-e54d087377b1

first i start the query with no select from result, the Status start as pending so isLoading and isFetching default as true, with selectFromResult the query start as uninitialized, so the isLoading and isFetching start as false, the problem is that they start on different stages.

**Comment by kaio-eduardo** [comment]
> @kaio-eduardo : we'd need a lot more details to offer any help. Can you provide a CodeSandbox or a repo that shows what's happening, or record and share a Replay (https://replay.io/record-bugs ) ?
> 
> If you can do that, we can try taking a look.

https://codesandbox.io/s/sleepy-bhaskara-t6xftc?file=/src/App.js
just a simple query with a console log

**Comment by markerikson** [comment]
I'm not sure what you're expecting here.

On first render, the query does not exist yet at all, so it definitely can't be fetching, and `isFetching: false`.

On second render, the query is in progress, so `inFetching: true`.

The query finishes, and on the third render, `isFetching: false` because it's done.

**Comment by kaio-eduardo** [comment]
> 

That only happens with selectFromResult, without it the isLoading and isFetching start as true in the first log

**Comment by kaio-eduardo** [comment]
> I'm not sure what you're expecting here.
> 
> On first render, the query does not exist yet at all, so it definitely can't be fetching, and `isFetching: false`.
> 
> On second render, the query is in progress, so `inFetching: true`.
> 
> The query finishes, and on the third render, `isFetching: false` because it's done.

In the redux devtools both just show the query as pending, but with the selectFromResult it prints the uninitialized state, while without it the print start as pending, so i cant use the selectFromResult with just isFetching like the normal query, without also using the isUninitialized state

**Comment by markerikson** [comment]
Hmm. That _is_ an unexpected difference in behavior, but not sure when we'll have time to look into this further.

**Comment by phryneas** [comment]
No, that's normal. 

The default implementation of selectFromResult is essentially a little convenience helper that eliminates the uninitialized state and replaces it with loading/fetching.

Once you start using selectFromResult, you get access to the true value, so it's up to you to do that check.

**Comment by kaio-eduardo** [comment]
> No, that's normal.
> 
> The default implementation of selectFromResult is essentially a little convenience helper that eliminates the uninitialized state and replaces it with loading/fetching.
> 
> Once you start using selectFromResult, you get access to the true value, so it's up to you to do that check.

ok, so i need to use the isUninitialized when using the selectFromResult?
Just thinking, what is the advantage of this behavior?

**Comment by phryneas** [comment]
isUninitialized on first render is the standard behaviour of the hook - it was only later added as a convenience thing that it is replaced with isLoading on first render if you don't specify a selectFromResult, so people dont have to check for another status.

selectFromResult gives you more control back, so that one doesn't hide the extra status.
