### ISSUE TITLE
`reset` return value from `useMutation` not available in `selectFromResult`

### ISSUE THREAD

**Issue by bdugg-91** [reduxjs/redux-toolkit#3691]
I'm working on some code using RTK-query and I'm trying to use the `reset` return value from an instance of `useMutation`. I'm able to extract this in the normal destructuring way:

`const [completeUpload, { reset: resetCompletionState, uploadCompletionError }] = useCompleteUploadMutation({});`

But when I try to get it from `selectFromResult` I get a type error:

```
  const [completeUpload, { resetCompletionState, uploadCompletionError }] =
    useCompleteUploadMutation({
      selectFromResult: ({ isError, reset }) => ({
        resetCompletionState: reset,
        uploadCompletionError: isError,
      }),
    });
```

```
Property 'reset' does not exist on type '({ requestId?: undefined; status: QueryStatus.uninitialized; data?: undefined; error?: undefined; endpointName?: string | undefined; startedTimeStamp?: undefined; fulfilledTimeStamp?: undefined; } & { ...; }) | ({ ...; } & ... 3 more ... & { ...; }) | ({ ...; } & ... 2 more ... & { ...; }) | ({ ...; } & ... 2 more ....'.ts(2339)
```

Is this expected behavior or no?

**Comment by markerikson** [comment]
`reset` is added by the hook, to whatever object you _returned_ from `selectFromResult`. So no, it's not part of the plain data that is passed _in_ to `selectFromResult`.  You don't have to add that yourself.
