### ISSUE TITLE
 Cannot refetch a query that has not been started yet.

### ISSUE THREAD

**Issue by Mubasher-Skylinx** [reduxjs/redux-toolkit#3695]
```JS
  const {
        isLoading: allMapsLoading,
        data: allMapsData,
        error: allMapsError,
        refetch: refetchAllMaps,
    } = useGetAllMapsQuery(user.email, {});
    
    
    const [myMapState, setMyMapState] = useState({
        data: allMapsData || [],
        groupsData: [],
        secondGroupData: [],
        myGroupsSecondGroupData: [],
        pinsLoading: false,
    });

    useEffect(() => {
        if (allMapsData) {
            setMyMapState((prevState) => {
                return {
                    ...prevState,
                    data: allMapsData,
                };
            });
            dispatch(setMyMaps(allMapsData));
            if (firstTimeRender.current || allMapsData.length === 1) {
                dispatch(setMapDashboardId(location.state?.mapDashboardId || allMapsData[0]?._id));
                setShowEmptyMap(false);
            }
            firstTimeRender.current = false;
        }

        if (allMapsError) {
            errorMessage(allMapsError?.data?.message);
        }
    }, [allMapsData, allMapsError]);
    
     useEffect(() => {
        socket.on(CREATE_MAP_SOCKET, (res) => {
            // console.log("APP RES: ", res);

            if (!socket.child) {
                if (socket.id === res.socketID) {
                    if (res.completed) {
                        refetchAllMaps();
                    }
                }
            }
        });
    }, []);
    ```
    
    i am getting error
    
     Cannot refetch a query that has not been started yet.
     
     but this query has already triggered

**Comment by phryneas** [comment]
On first render, you are creating a closure over the `rerender` function during first render - which means that it is the rerender at the point in time where no query has run yet.

You are referencing a stale closure.

Also, you should probably not copy the query result into local state unless you have a very good reason to, and we generally discourage copying RTK Query results into custom slices, but **if** you do that, you should do that by adding an `extraReducer` in your slice, not by using a component with a `useEffect` to do that synchronization.

You are generally overusing `useEffect` a lot. I would really recommend that you look into alternative patterns.

**Comment by Mubasher-Skylinx** [comment]
Also, you should probably not copy the query result into local state unless you have a very good reason to, and we generally discourage copying RTK Query results into custom slices, but if you do that, you should do that by adding an extraReducer in your slice, not by using a component with a useEffect to do that synchronization.

Can you show me example
Its hard to find how one should work with RTK and RTKQ
also there is bad documentation for something like createSelector

**Comment by nileshvalere** [comment]
I am getting this issue in this code
 const { refetch: refetchVoteSettings } = useViewVoteSettingsQuery(
    currentCircle?.id,
    {
      skip: !!!currentCircle,
    }
  );
  useFocusEffect(
    useCallback(() => {
      StatusBar.setBarStyle("light-content");
console.log('currentCircle_provtae',currentCircle?.id)
      // setTimeout(()=>{
        refetchVoteSettings()
      //  getCircleVoteSetting({circleId:curreUser?.circle?.id})
      // },3000)

    refetchShowProfile();
    
      listCircleMembers({
        circleId: currentCircle?.id,
        from:'index'
        // currentCircle: currentCircle,
      });
    }, [])
  );
