### ISSUE TITLE
Change baseURL and Headers dynamically in RTKQ

### ISSUE THREAD

**Issue by Saad-Bashar** [reduxjs/redux-toolkit#3699]
I am trying to dynamically change the `baseUrl `and `headers` in my queries. Some of the API paths in our application use v1 and some use v2. Right now, I stripped the "v1" and "v2" strings from the `baseUrl` and attached them individually with each endpoint's query.  For example, 
```
query: ({id}) => {
        return {
          url: `/v2/..../${id}/....`,
          headers: {
            Accept: 'application/vnd.___.v2',
          },
        };
      },
```

and this is my global config for the API,
```
const baseQuery = fetchBaseQuery({
  baseUrl: ConfigConstants.api.base_path,
  prepareHeaders: async (headers, {}) => {
    if (!headers.has('Accept')) {
      headers.set('Accept', 'application/vnd.___.v1');
    }
    return headers;
  },
});
```

Is there a better approach to do this globally instead of individually updating each endpoint? Any help will be much appreciated. Thanks a lot!

**Comment by eric-crowell** [comment]
[RTK's Relevant Documentation](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries)

I implemented something similar. Hope it helps.

Start by making yourself a very simple **Base Query Function***. You'll use `baseQueryArgs` to determine what options to pass into `fetchBaseQuery`.

```ts
import { createApi, fetchBaseQuery, BaseQueryFn } from "@reduxjs/toolkit/query";

const baseQuery: BaseQueryFn = (...baseQueryArgs) => {
  return fetchBaseQuery(/** My Dynamic Options **/)(...baseQueryArgs);
};

export const myApiDynamic = createApi({
  reducerPath: "apiDynamic",
  baseQuery,
  endpoints: () => ({})
});
```

For example, you could change the options based on the fetch URL argument.

```ts
import { createApi, fetchBaseQuery, BaseQueryFn } from "@reduxjs/toolkit/query";

const baseQuery: BaseQueryFn = (...baseQueryArgs) => {
  const [args] = baseQueryArgs;

  // Set base URL based on the fetch args URL.
  const baseUrl = args.url?.endsWith("/checkout") ? "/v2" : "/v1";

  return fetchBaseQuery({
    baseUrl,
    prepareHeaders: async (headers) => {
      // Set headers based on the fetch args URL.
      if(args.url?.endsWith("/checkout")) {
        // ...
      }
      return headers;
    }
  })(...baseQueryArgs);
};

export const myApiDynamic = createApi({
  reducerPath: "apiDynamic",
  baseQuery,
  endpoints: (builder) => ({
    // Uses /v1
    checkout: builder.query({
      query: () => ({
        url: "/getComments",
        method: "GET"
      })
    }),
    // Uses /v2
    getPosts: builder.query({
      query: () => ({
        url: "/getPosts",
        method: "GET"
      })
    })
  })
});
```

Didn't test this code, but hopefully helps you get it doing what you need. You could also make a new slice on your state for configurations and select it from your store using `baseQueryArgs[1].getState()` though.

**Comment by Saad-Bashar** [comment]
Thank you so much, this really helps! I used the `extraOptions` to pass the version and then used that as a condition to change my `baseURL` and `headers`
