### ISSUE TITLE
Type for generic action (with or without payload).

### ISSUE THREAD

**Issue by luxcem** [reduxjs/redux-toolkit#370]
Hello, 
I'm trying to create a generic reducer with `createSlice`, I cannot figure out the type to use for the `action` parameter to allow actions with or without a `payload`

```typescript
import { createSlice } from '@reduxjs/toolkit'

interface State {
  loading: boolean
  item?: any
  errors?: any
  payload?: any
}

const initialState: State = {
  loading: false,
}

export const slice = createSlice({
  name: 'myslice',
  initialState,
  reducers: {
    // How to type action for allowing readRequest() or readRequest(somePayload)
    readRequest: (state: State, action: any) => {
      state.loading = true
      if ('payload' in action) {
        state.payload = action.payload
      }
    },
    readSuccess: (state: State, action: any) => {
      state.loading = false
      if ('payload' in action) {
        state.payload = action.payload
      }
    },
  },
})

const { actions } = slice
// error readSuccess is expecting 1 argument
actions.readSuccess()
```

In this example `readSuccess()` is expecting 1 argument event if its type is 
`ActionCreatorWithNonInferrablePayload<string> | ActionCreatorWithoutPayload<string>`

[Link to codesandbox](https://codesandbox.io/s/pensive-varahamihira-wdwq6)

**Comment by markerikson** [comment]
Hmm.  Does something like:

```ts
readRequest(state, action: PayloadAction<string | void>) {}
```

work for you?

**Comment by phryneas** [comment]
```ts
readRequest(state, action: PayloadAction<string | undefined>){}
```
is what you're looking for.

**Comment by luxcem** [comment]
With 
```typescript
readRequest(state, action: PayloadAction<string | void>) {}
```
`readRequest` is expecting 0 arguments (cannot pass a `string`)

with 
```typescript
readRequest(state, action: PayloadAction<string | undefined>){}
```
readRequest can accept a string or nothing but what I'm looking is `PayloadAction<any>`.
But with `any` the payload is mandatory.

What seems to work is to use 
```typescript
type anything =
  | number
  | string
  | boolean
  | bigint
  | symbol
  | null
  | object
  | undefined;
readRequest(state, action: PayloadAction<anything>){}
```
It does not seems right since `anything` is basically `any`.

**Comment by phryneas** [comment]
Yeah, that's essentially a design decision. Ee had to decide if `PayloadAction<any>` results in either a payload action creator that requires one argument that could be anything, or requires one optional argument.

Since we can't support both, the first one seemed the more common use case - so for your use case you'll have to use that workaround you have there.

My question here is: are you sure you *want* to write something like that at all? That sounds like you're giving up all type-safety down the road, at which point the question would be why you're using TS at all.
Maybe something going in the direction of [wrapping createSlice with a generic](https://redux-toolkit.js.org/usage/usage-with-typescript#wrapping-createslice) might help you keep type-safety.

**Comment by luxcem** [comment]
Thanks @phryneas for the answer, I understand the design decision. 

Indeed it looks like a TS anti-pattern, I was trying to understand the type decisions around Action, in the end I think I'll use a proper type for action payloads.

**Comment by matteo-bombelli** [comment]
hello!

what I'm trying to get is to reach this behavior: 

you can use both `dispatch(exampleAction())`, `dispatch(exampleAction({}))` and `dispatch(exampleAction({isOk:true}))`

```ts
    
const exampleSlice = createSlice({
    name: "example",
    initialState,
    reducers: {
        exampleAction: (state, action:PayloadAction<{isOk?:boolean}|undefined>) =>{
              state.isOk  = action.payload?.isOk
        }
    }
});

export const { exampleAction } = exapleSlice.action;
```

```ts
dispatch(exampleAction())
```

`exampleAction()` throws an error on typescript: `an argument for exampleAction was not provided`

the only way I found to obtain the desired result is casting the desired type on the action

```ts
    
const exampleSlice = createSlice({
    name: "example",
    initialState,
    reducers: {
        exampleAction: (state, action:PayloadAction<{isOk?:boolean}|undefined>) =>{
              state.isOk  = action.payload?.isOk
        }
    }
});

export const exampleAction = exapleSlice.action.exampleAction as ((payload?:{isOk?:boolean})=>unknown);
```

**Comment by EskiMojo14** [comment]
@matteo-bombelli do you have `strict` or at least `strictNullChecks` turned on?

After correcting typos (`exampleSlice.actions.exampleAction`) that snippet works correctly for me.
