### ISSUE TITLE
[v2] Typescript issues when trying to migrate with redux-persist

### ISSUE THREAD

**Issue by nanyaDev** [reduxjs/redux-toolkit#3705]
**Note:** Issue #3697 describes this exact problem. The author of that issue was able to solve their problems by "...removing my node_modules and refreshing the lock file" and closed the issue, but this approach did not work for me, so I have created a new issue with some further details. 

---

I am running into the problem first described in #3697, where after upgrading to the latest beta, I am getting a TS error for the `middleware` option of `configureStore`:

```
Type '(getDefaultMiddleware: GetDefaultMiddleware<{ Notifications: EntityState<Notification, string>; }>) => Tuple<[ThunkMiddleware<{ Notifications: EntityState<...>; }, UnknownAction>]>' is not assignable to type 'Tuple<Middlewares<{ Notifications: EntityState<Notification, string>; }>> | ((getDefaultMiddleware: GetDefaultMiddleware<{ Notifications: EntityState<Notification, string>; }>) => Tuple<...>) | undefined'.
  Type '(getDefaultMiddleware: GetDefaultMiddleware<{ Notifications: EntityState<Notification, string>; }>) => Tuple<[ThunkMiddleware<{ Notifications: EntityState<...>; }, UnknownAction>]>' is not assignable to type '(getDefaultMiddleware: GetDefaultMiddleware<{ Notifications: EntityState<Notification, string>; }>) => Tuple<Middlewares<{ Notifications: EntityState<...>; }>>'.
    Type 'Tuple<[ThunkMiddleware<{ Notifications: EntityState<Notification, string>; }, UnknownAction>]>' is not assignable to type 'Tuple<Middlewares<{ Notifications: EntityState<Notification, string>; }>>'.
      Type '[ThunkMiddleware<{ Notifications: EntityState<Notification, string>; }, UnknownAction>]' is not assignable to type 'Middlewares<{ Notifications: EntityState<Notification, string>; }>'.
        Type 'ThunkMiddleware<{ Notifications: EntityState<Notification, string>; }, UnknownAction>' is not assignable to type 'Middleware<{}, { Notifications: EntityState<Notification, string>; }, Dispatch<UnknownAction>>'.
          Types of parameters 'next' and 'next' are incompatible.
            Type 'unknown' is not assignable to type 'T'.
              'T' could be instantiated with an arbitrary type which could be unrelated to 'unknown'.ts(2322)
configureStore.d.ts(25, 5): The expected type comes from property 'middleware' which is declared here on type 'ConfigureStoreOptions<{ Notifications: EntityState<Notification, string>; }, UnknownAction, Tuple<Middlewares<{ Notifications: EntityState<Notification, string>; }>>, Tuple<...>, { ...; } | Partial<...>>'
```
In the linked issue, @EskiMojo14 says:

> ...seems to be because your copy of redux-thunk is using the definition of Middleware from Redux v4.x. Theoretically the latest releases of redux-thunk and RTK @markerikson made were meant to fix this - are you definitely using RTK v2.0.0-beta.1?

I am using `@reduxjs/toolkit:2.0.0-beta.1` in a RN/Expo app along with `redux-persist` (exactly like the original issue). I get the following result for `npm list redux`:

```
├─┬ @reduxjs/toolkit@2.0.0-beta.1
│ ├─┬ redux-thunk@3.0.0-beta.0
│ │ └── redux@4.2.1 deduped
│ └── redux@5.0.0-beta.0
├─┬ react-redux@8.1.2
│ └── redux@4.2.1
└─┬ redux-persist@6.0.0
  └── redux@4.2.1 deduped
```

As you can see, `redux@4.2.1` is present in the full dependency tree. After a fair amount of digging, I have discovered that running `npm uninstall redux-persist` followed by `npm dedupe` fixes the TS error and gives the following result for `npm list redux`:

```
├─┬ @reduxjs/toolkit@2.0.0-beta.1
│ ├─┬ redux-thunk@3.0.0-beta.0
│ │ └── redux@5.0.0-beta.0 deduped
│ └── redux@5.0.0-beta.0
└─┬ react-redux@8.1.2
  └── redux@5.0.0-beta.0 deduped
```

However, if I then try and add back `redux-persist` by running `npm install redux-persist`, along with another `npm dedupe` for good measure, then the original dependency tree and the TS error reappear. I continue to get the same result after deleting `node_modules` and `package-lock.json` and running `npm install`, which the OP of #3697 said fixed their issue.

 It seems `redux-persist` enforces `redux@4.2.1` as a nested dependency. Digging into `redux-persist`'s [`package.json`](https://github.com/rt2zz/redux-persist/blob/master/package.json) one can see:

```
"peerDependencies": {
    "redux": ">4.0.0"
  }
```

I thought that the `>` symbol would accept any greater version, including `redux@5.0.0-beta.0` but that doesn't seem to be the case.

Unfortunately I cannot share my source code, but the dependency tree above can be recreated by running the following in an new directory:

```
npm init -y
npm install @reduxjs/toolkit@beta
npm install redux-persist
npm list redux
```

**Comment by EskiMojo14** [comment]
yeah, this is essentially an issue that will stick around until we can get redux v5 released and packages begin to update their peer dependencies.

in the meantime, you can use npm [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) or yarn [resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to ensure that all packages use redux v5's beta.

(you may also want to use react-redux's [alpha release](https://github.com/reduxjs/react-redux/releases), which is built for redux v5)

**Comment by markerikson** [comment]
Yep, if you're gonna update, you'll have to use resolutions to enforce that.
