### ISSUE TITLE
Support for explicit resource management "using statements" on RTK Query subscriptions

### ISSUE THREAD

**Issue by jared-ca** [reduxjs/redux-toolkit#3707]
## Background
RTK Query is built around the concept of consumers subscribing and unsubscribing from endpoints as required. The subscription count is used to determine when data is in use and caches can be cleared.

This is quite nice in React when using hooks as the hook lifetime is directly coupled to the subscription lifetime.

RTK Query supports being used in other frameworks and outside of React components where the subscription must be manually unsubscribed when finished with. 

This makes it easy to introduce subtle bugs especially when dealing with exceptions so ideally every manual dispatch of an `initiate` action should be unsubscribed in a finally block which can get messy when dealing with multiple subscriptions.

## Explicit resource management
Explicit resource management is a stage 3 TC39 proposal to add `using` statements to Javascript to solve this exact problem. It was recently shipped as part of Typescript 5.2 and is available in Javascript using babel.

See:
 - https://github.com/tc39/proposal-explicit-resource-management
 - https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#using-declarations-and-explicit-resource-management
 - https://babeljs.io/docs/babel-plugin-proposal-explicit-resource-management

I would like to propose adding a `[Symbol.dispose]` method to the object returned from `dispatch(endpoint.initiate()` so it can cleaned up with a using block.

## What does that look like for consumers?

In this snippet we're cleaning up the subscriptions manually. I'm trying to simulate a real world scenario where the second subscription isn't always created so we need multiple finally blocks.

```
  const subscription1 = store.dispatch(pokemonApi.endpoints.getPokemonByName.initiate('bulbasaur'));
  try {
    const { data : pokemon1 } = await subscription1;
    processPokemon(pokemon1);
    if (shouldFetchPicachu()) {
      const subscription2 = store.dispatch(pokemonApi.endpoints.getPokemonByName.initiate('pikachu'));
      try {
        const { data : pokemon2 } = await subscription2;
        processPokemon(pokemon2);
      } finally {
        subscription2.unsubscribe();
      }
    }
  }
  finally {
    subscription1.unsubscribe();
  }
```

This is the same example again with using blocks demonstrating how much more ergonomic explicit resource management is.
```
  using subscription1 = store.dispatch(pokemonApi.endpoints.getPokemonByName.initiate('bulbasaur'));
  const { data : pokemon1 } = await subscription1;
  processPokemon(pokemon1);

  if (shouldFetchPicachu()) {
    using subscription2 = store.dispatch(pokemonApi.endpoints.getPokemonByName.initiate('pikachu'));
    const { data : pokemon2 } = await subscription2;
    processPokemon(pokemon2);
  }
```

**Comment by EskiMojo14** [comment]
For what it's worth, this seems fairly simple to add a util for in userspace:
```ts
const withDispose = <
  T extends { unsubscribe: Disposable[typeof Symbol.dispose] },
>(
  unsubscribable: T,
): T & Disposable =>
  Object.assign(unsubscribable, {
    [Symbol.dispose]: unsubscribable.unsubscribe,
  });

 using subscription1 = withDispose(store.dispatch(pokemonApi.endpoints.getPokemonByName.initiate('bulbasaur')));
  const { data : pokemon1 } = await subscription1;
  processPokemon(pokemon1);

  if (shouldFetchPicachu()) {
    using subscription2 = withDispose(store.dispatch(pokemonApi.endpoints.getPokemonByName.initiate('pikachu')));
    const { data : pokemon2 } = await subscription2;
    processPokemon(pokemon2);
  }

```
[playground](https://www.typescriptlang.org/play?target=99&ssl=11&ssc=6&pln=4&pc=1#code/JYWwDg9gTgLgBAbzgYwgOwGbAOYFcoCmAyjNAXAL5wZQQhwBEAAoQCa4AeAVgM4D0pCABsA1sBgMA3AChQkWIhSEAhjAIBBMMAA01AjGQALAELKeBAIq4CUAJ6VqteszadeAiMLEw+rYDx8AR2s7KWlpVDQAuAB3cUMAEX9IczgAXjgAHmk4OAAVOAIONTRWHkVcKNwAIx5kKGBqggAuOCSeFOVqoQIAbRhbMAIIDDgiWxBq4QA6Pw6IcwBdSm1pAD4AChy4Sp4auobqrp7WvNWASlO4ADI25IXj8jS17YB5aq4CZBhpsx4cNAbXb7eqNR66BDbXK9caTGZzFIERatYG1UFHboEaaog6NAirXIUc4yCLoaLKLTpJQEVQaLQbSG5I7mKw2WytDD6IymFkhWwbc4EwqlSDANAwHitDbVXDAISsc7pNZwBlQuDYfQABQWMFaMrlrGmwTZmSQwFYrQCDTQ2BWcCtYuwm0ZuVdxrsUvNiuecAABikfAASBDmii+oWEwXbImrIkkyLRAJkKmRLB4QgkMiq3KuZA2Vou6EU4DTXM2TWqQzIuDF0sEdh5qBCihCkDm1g9GLKQhS7AJACy3uVff7AumkWQqg2tbbrA7BC7hCjcfCuH+NrgYCc-iesXi7URW1yScIs2SqiM0600wIIogYol0w1MG1AWmYvEwFpGwYAEYGOcUbEuECbwIQexCPAGTKF24ibtu5jYmgMRQBSAoyEAA)

**Comment by markerikson** [comment]
Given that it's doable in userland atm, I'm going to close this one for now.
