### ISSUE TITLE
preferCacheValue not behaving as intended.

### ISSUE THREAD

**Issue by JasonYCao** [reduxjs/redux-toolkit#3711]
I'm using a lazy query with preferCacheValue set to false, but it is still preferring a cached value no matter how many times I'm calling it.

![image](https://github.com/reduxjs/redux-toolkit/assets/56234473/7310b0d0-126a-4812-bacc-e24e5bcb0c11)

I've noticed that it's just not refetching new values at all in this case, and just defaulting to a cached one. I understand that without a changed body, it doesn't normally fetch again, but I have preferCacheValue set to false with a lazy query, shouldn't it refetch anyways? For context, I'm basically having it repull data that may have changed after the page has loaded.

**Comment by markerikson** [comment]
Can you provide a CodeSandbox, repo, or Replay ( https://replay.io/record-bugs ) that reproduces the issue?

**Comment by rwilliams3088** [comment]
Probably the same as: https://github.com/reduxjs/redux-toolkit/issues/2802

**Comment by markerikson** [comment]
Should be fixed as part of #4651 .
