### ISSUE TITLE
Feature: Add `.dispatch(store)` to action's returned object

### ISSUE THREAD

**Issue by dutziworks** [reduxjs/redux-toolkit#3712]
This isn't a big issue, but a bit annoying when reading code.

Prettier formats our code automatically. With dispatch calls it look like this, most of the time:

```js
dispatch(
  currentProjectSet({
    isLoading: true,
    projectId,
    params: { projectIdSlug },
  })
);
```

I hope I'm not alone here thinking this looks meh... but to be honest, I don't see a better way to format this. 

If I want to manually make it look ok-ish I do this:

```js
const action = currentProjectSet({
  isLoading: true,
  projectId,
  params: { projectIdSlug },
});
dispatch(action);
```

What I think would be great, is if an RTK action would return a method called `dispatch` that will accept a store (I think this will be required for TS, not sure though).

Then we could do this instead:

```js
currentProjectSet({
  isLoading: true,
  projectId,
  params: { projectIdSlug },
}).disaptch(store);
```

**Comment by dutziworks** [comment]
@phryneas It seams feasible (technically, not sure if you'd like it in). Am I missing something?

**Comment by phryneas** [comment]
Sorry, but we're not going to ship additional bytes (and runtime code that consumes memory) to millions of consumers to satisfy personal code style preferences.

The current code is perfectly fine.

**Comment by EskiMojo14** [comment]
also worth noting that if you're working in React components, it's actually very rare to need/have a direct reference to the store. Normally you'd interact through `useDispatch` (returning only `dispatch`) or `useSelector` (allowing you to select state). Usage of `useStore` is almost never necessary.

**Comment by dutziworks** [comment]
@phryneas ah yeah, makes sense!

@EskiMojo14 yup, it's probably only for thunks.

**Comment by EskiMojo14** [comment]
thunks also don't have access to a store instance, just dispatch and getState 😛

**Comment by dutziworks** [comment]
Right, I meant state, not store :)
