### ISSUE TITLE
UpdateQueryData doesn't change useQuery data

### ISSUE THREAD

**Issue by Avircut** [reduxjs/redux-toolkit#3727]
Hello, I use updateQueryData to make optimistic update. With example from docs everything works fine if subsribe for each item. But if I want to subscribe to whole list I can't make optimistic update work. Cache data changes and in Redux dev tools queries array seems good, but data from query hook doesn't change before I get server response and executeQuery would be fulfilled. 
```
    FetchUserTodos: build.query<Todo[], string>({
      query: (userId) => ({
        url: '/todos',
        params: {
          userId,
          _embed: 'todos',
        },
      }),
      providesTags: () => ['Todo'],
    }),
    UpdateTodo: build.mutation<Todo, Todo>({
      query: (todo) => ({
        url: `/todos/${todo.id}`,
        method: 'PUT',
        body: todo,
      }),
      async onQueryStarted(patch, { dispatch, queryFulfilled, getState }) {
        const userData = getUserAuthData(getState() as StateSchema);
        if (userData) {
          const patchResult = dispatch(
            todosApi.util.updateQueryData('FetchUserTodos', userData?.id, (draft:Todo[]) => {
              const index = draft.findIndex((todo) => todo.id === patch.id);
              draft[index] = { ...patch };
            }),
          );
          try {
            await queryFulfilled;
          } catch {
            patchResult.undo();
          }
        }
      },
      invalidatesTags: () => ['Todo'],
    }),
```
Data I get like that.
```
  const user = useAppSelector(getUserAuthData);
  const { data: todos, isLoading, error } = useFetchUserTodos(user!.id);
```
And mutation query I fire like that:
```
const [updateTodo] = useUpdateTodo();
  const [removeTodo] = useRemoveTodo();
  const onDeleteClick = useCallback(() => {
    if (todo?.id) {
      removeTodo(todo.id);
    }
  }, [removeTodo, todo]);
  const onActiveChange = useCallback(() => {
    if (todo) {
      updateTodo({
        ...todo,
        isCompleted: !todo.isCompleted,
      });
    }
  }, [todo, updateTodo]);
```
Please help me to figure out what else I need to make cached data to appear on useQuery hook? Probably I missed something obvious

**Comment by dimitriskarakaxas** [comment]
I have the exact same problem!

**Comment by dimitriskarakaxas** [comment]
I'm not sure if this is gonna solve your problem, but I had a problem recently updating the Cache of a specific query(the cache was an array), and the way I used to make it work was by **returning** the new state. 

Here is an example:
`disconnectUser: build.mutation({
      query: (id) => ({
        url: "/disconnect",
        method: "PUT",
        body: { id },
      }),
      async onQueryStarted(id, { dispatch, queryFulfilled }) {
        try {
          await queryFulfilled;

          dispatch(
            apiSlice.util.updateQueryData(
              "getReady",
              undefined,
              (machines) => {
                return machines.filter((machine) => machine.id !== id);
              }
            )
          );
        } catch (error) {}
      },
    }),`
    
    But in my case the cached data was not even updating, but If I understand correctly you cache data update but doesn't reflect the change?(So the component that uses the query hook doesn't rerender)?

**Comment by Avircut** [comment]
But docs and types says there are updateQueryData should return void... And as I understand correctly you have pessimistic updates. I added return and that doesn't change anything. 
You correctly understood: in redux dev tools data array changes with QueryResultPatched query, but I see changes only when tags invalidated and data refetched from server.

**Comment by Avircut** [comment]
Also to make in clearer I tested with docs example to subscribe on each item of array and that worked. That doesn't work with array only. I don't think it's a good approach to send new request for each item.

**Comment by Avircut** [comment]
Tried to send update function as props to children, because thought that trouble could be because of different components that fetch data and mutates that. That doesn't worked.

**Comment by phryneas** [comment]
I think you both have a misconception:

`updateQueryData` updates the data returned from a query that has already happened.

```js
.util.updateQueryData("getReady", undefined,
```
will update the cache entry from calling `useGetReadyQuery()` or `useGetReadyQuery(undefined)`.

```js
updateQueryData('FetchUserTodos', userData?.id
```
will update the cache entry from calling `useFetchUserTodos(userData?.id)`.

If that cache entry doesn't exist, because you actually never called `useFetchUserTodos(userData?.id)` in your code, nothing will happen.

`updateQueryData('FetchUserTodos', userData?.id` will also **not** update `useFetchUserTodos()` in the array position for `userData?.id`. 
That's a completely different query. There is no black magic going on matching these together or anything. A cache entry is not normalized in any way - it's a blob, and you can edit that blob.

**Comment by Avircut** [comment]
I try to update cache entry from query that has already happened and I thought that draft array changes in Redux dev tools means that updateQueryData worked, isn't it? 
There are exists issues where ppl changed the array with selectInvalidatedBy, so I suppose it's possible. There are no way to optimistic update whole array without making requests for each item?

**Comment by phryneas** [comment]
> I try to update cache entry from query that has already happened and I thought that data array change in Redux dev tools means that updateQueryData worked, isn't it?

Yes, that totally should work - here it sounded like you wanted to create individual cache entries for the individual items.

**Comment by Avircut** [comment]
Hm... I found out that useQuery actually changes, but doesn't rerender children probably because it thinks data didn't changed, so the issue is not with redux. Sorry for disturb, thanks you for your replies!
