### ISSUE TITLE
Getting error for void return type for mutation RTK Query

### ISSUE THREAD

**Issue by AsuraKev** [reduxjs/redux-toolkit#3730]
Hi there,

I am implementing a mutation in my RTK query, this mutation will not return any data therefore its typed void. But I am getting typescript complaints

![image](https://github.com/reduxjs/redux-toolkit/assets/52765572/a957add9-b6d8-4226-b111-63d12e8d196e)

error: 

Type '(arg: CreateDealerCardPayload, { dispatch, signal, getState }: BaseQueryApi, extraOptions: {}, baseQuery: (arg: string | FetchArgs) => MaybePromise<QueryReturnValue<unknown, FetchBaseQueryError, FetchBaseQueryMeta>>) => Promise<...>' is not assignable to type '(arg: CreateDealerCardPayload, api: BaseQueryApi, extraOptions: {}, baseQuery: (arg: string | FetchArgs) => MaybePromise<QueryReturnValue<unknown, FetchBaseQueryError, FetchBaseQueryMeta>>) => MaybePromise<...>'.
  Type 'Promise<{ error: FetchBaseQueryError; } | undefined>' is not assignable to type 'MaybePromise<QueryReturnValue<void, FetchBaseQueryError>>'.
    Type 'Promise<{ error: FetchBaseQueryError; } | undefined>' is not assignable to type 'PromiseLike<QueryReturnValue<void, FetchBaseQueryError>>'.
      Types of property 'then' are incompatible.

**Comment by kokiqn** [comment]
How did you resolve this?

**Comment by AsuraKev** [comment]
use undefined instead of void
