### ISSUE TITLE
Mutation of arg in createAsyncThunk condition

### ISSUE THREAD

**Issue by sebastien-f** [reduxjs/redux-toolkit#3732]
While looking at potential optimisations in my app, I discovered that it's possible to mutate the arg properties from the condition callback of createAsyncThunk : 

```
export const myAction = createAsyncThunk(
    "myAction",
    async (arg) => {

        console.log(arg.newParameter == 42); // true
        console.log(arg.oldParameter == 43); // true
    }, {
    condition(arg) {
        arg.newParameter = 42;
        arg.oldParameter = 43;
        
        return true;
    },
})
```

```
dispatch(myAction(41));
```

I have a pretty heavy app that can manage multiple contents at different places, so I have a `status` field on every object to check if it's already loaded/loading/deleted/deleting/etc. The optimisation was to avoid a round trip with the server depending on the operation and the status. 

I have been using the condition callback to manage that so far, and it was working great when loading single items. We started batch-calling certain operations to reduce the number of server calls, and that's when the condition stopped being useful.

For example, if I have to load a bunch of items (that may or may not be loaded), I want to look at the status of each item and depending on it and the operation, trigger only the loading of the items that should be. 

While it would make my life so much easier to use that behavior, it also feels a bit wrong (using condition solely to mutate the arg instead of doing a proper filtering before calling the action). 

So : 
- Can you confirm that it's an unwanted behavior ?
- Is it so bad that there is a high chance that it will be fixed in a foreseeable future ?

**Comment by EskiMojo14** [comment]
it's definitely not something we'd expect (or encourage) `condition` to be used for, but I think it's unlikely that we'll do anything specific to *prevent* you from doing it.

in general it seems more intuitive to do whatever modifications you need to do inside the main payloadcreator.

**Comment by sebastien-f** [comment]
Yeah that's what I'm gonna do. Thank you for the clarification.
