### ISSUE TITLE
npm install @reduxjs/toolkit doesn't work

### ISSUE THREAD

**Issue by johnnynumberfive-coder** [reduxjs/redux-toolkit#3735]
Hi,

I'm trying to install redux toolkit, but when I do an npm install reduxjs/toolkit I get the following error:

$ npm install reduxjs/toolkit
info: please complete authentication in your browser...Completed in 0ms
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/reduxjs/toolkit.git
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in: C:\Users\John\AppData\Local\npm-cache\_logs\2023-09-21T15_58_57_957Z-debug-0.log

As you can see, it's trying to access toolkit.git when the actual url is tool-kit.git

How on earth can I fix this?  Thanks!

**Comment by johnnynumberfive-coder** [comment]
Forgot to mention.  I'm installing into an existing project, and using npm version 9.8.1

**Comment by markerikson** [comment]
You forgot the `@` :)  It thinks you're trying to install from an actual repo called `github.com/reduxjs/toolkit`.

**Comment by johnnynumberfive-coder** [comment]
I had the @ on the command line when I tried it.  Just tried it again.  Same error

**Comment by johnnynumberfive-coder** [comment]
Never mind, now it works.  Weird

**Comment by markerikson** [comment]
I can assure you that this is not a problem with the library :)  The package is published, and it works.  Please re-check your command.

Even if there _is_ something going on, it would be on the NPM side, and there's nothing we can do about that.
