### ISSUE TITLE
[RED-22] Improve performance of `createReducer`

### ISSUE THREAD

**Issue by acarabott** [reduxjs/redux-toolkit#3736]
We have a fairly large application and are seeing a lot of CPU being spent in `createReducer`, specifically by the calls to `.filter` and .`map`.

This could be optimized by combining these two loops into a single for loop, i.e.

## Before
```ts
let caseReducers = [
  actionsMap[action.type],
  ...finalActionMatchers
    .filter(({ matcher }) => matcher(action))
    .map(({ reducer }) => reducer),
]
if (caseReducers.filter((cr) => !!cr).length === 0) {
  caseReducers = [finalDefaultCaseReducer]
}
```

## After
```ts
const caseReducers: Array<CaseReducer<S, any>> = [];

if (actionsMap[action.type]) {
    caseReducers.push(actionsMap[action.type]);
}

for (const actionMatcher of finalActionMatchers) {
    if (actionMatcher.matcher(action) && !!actionMatcher.reducer) {
        caseReducers.push(actionMatcher.reducer);
    }
}

if (caseReducers.length === 0 && finalDefaultCaseReducer !== undefined) {
    caseReducers.push(finalDefaultCaseReducer);
}
```

Happy to submit a PR for this, wanted to check it would be accepted beforehand.

<sub>[RED-22](https://linear.app/redux/issue/RED-22/improve-performance-of-createreducer)</sub>

**Comment by markerikson** [comment]
I find that very surprising, tbh.

Can you provide a browser devtools CPU perf profile showing this as an issue?

**Comment by acarabott** [comment]
Looks like this might have been a bit of a red herring, I'm getting inconsistent results now. Happy for this to be closed and I'll return to it if I can better isolate it.

**Comment by markerikson** [comment]
@acarabott if you can attach a zipped CPU perf profile and give me an idea of what you're seeing, I can maybe take a look.
