### ISSUE TITLE
[2.0] Finalize docs

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#3744]
Figure out any docs changes that might be needed and update them:

## RTK

- [x] Remove deprecations
- [x] Document new features
- [x] Set up error codes page for RTK
- [x] Document `selectSlice`
- [x] Look for uses of `@reduxjs/toolkit/dist` in the docs
- [x] Update TS usage to mention `getState() as RootState` _plus_ an explicit return type
- [x] Mention `isAction` in the migration guide
- [x] Update repo README
- [x] Land the Next.js usage docs
- [x] Reselect `ParametricSelector` removal (and `weakMapMemoize` as default?)
- [x] Rename migration page and update release note links in existing RCs for completeness)
- [x] Make sure `middleware` comes before `enhancers` so we can infer types for `getDefaultEnhancers` correctly

## Core

- [x] Update repo README
- [x] Land the Next.js usage
- [x] Add error codes page to sidebar for core
- [x] Core docs TS changes?
- [x] Copy migration guide
- [x] document `isAction` and `isPlainObject`
- [x] Be sure to mention `createStore` deprecation in the core API ref

## Release Notes

- [x] Redux core
  - [x] `createStore` deprecation
- [x] RTK  
  - [x] `createStore` deprecation
  - [x] Reselect `weakMapMemoize`, `lruMemoize`, and dev checks
- [x] Reselect
- [x] React-Redux

**Comment by markerikson** [comment]
Should add the copy-paste of the extracted errors page, per #3374

**Comment by EskiMojo14** [comment]
new selectSlice method of slices will need documenting: #3838

**Comment by markerikson** [comment]
Check uses of augmentation like `"@reduxjs/toolkit/dist/query/whatever"`, per the RTKQ enhancement pages.

**Comment by markerikson** [comment]
Need to update the Redux templates, too.

**Comment by markerikson** [comment]
Not docs, but the other libs have a `$PACKAGE.browser.mjs` file, and RTK has `redux-toolkit.production.min.mjs`.  Make that consistent.

**Comment by markerikson** [comment]
Not 2.0 related, but we should add something to "RTK TS Usage" saying you need to explicitly cast `getState() as RootState` _and_ have an explicit return type to avoid circular type inference

**Comment by EskiMojo14** [comment]
as per https://github.com/reduxjs/redux-toolkit/issues/3895 we should probably mention `isAction` in the migration guide

**Comment by markerikson** [comment]
Land the Next usage docs PR here and in the core site

**Comment by markerikson** [comment]
Update all repo READMEs with whatever the latest template and descriptions are

**Comment by EskiMojo14** [comment]
since the migration guide mentions the stability dev check, it should mention the identity function check too
