### ISSUE TITLE
How to implement SWR Like behaviour ?

### ISSUE THREAD

**Issue by karanshah229** [reduxjs/redux-toolkit#3747]
### Does RTK Query currently have a SWR like functionality ? How can I implement it ?

i.e. When a request is made data is returned from the cache if it exists but also a revalidation query is sent in the background and if new data is received from the API then that new data is returned to the calling component.

React Query does this using 2 timers - `cacheTime` and `staleTime` - [Docs](https://tanstack.com/query/v4/docs/react/guides/caching)
Is there any such alternative for RTK Query ?

From the [RTK Query docs](https://redux-toolkit.js.org/rtk-query/usage/cache-behavior) it looks like we just have one timer - `keepUnusedDataFor` which is equivalent to React Query's `cacheTime`.
Do we have an alternative for `staleTime` ?

Read the Docs, but couldn't find this anywhere.

cc: @markerikson @phryneas @EskiMojo14

**Comment by markerikson** [comment]
I don't think we have separate options for this.

( Tagging the "Pain Points" thread for latter connections - #3692 )
