### ISSUE TITLE
Mutation replaces undefined fields with old data

### ISSUE THREAD

**Issue by PotatoTroll** [reduxjs/redux-toolkit#3755]
Hey there, sorry if this is expected behavior, but I can't find any information on this. 
using redux-toolkit 1.9.6

Say I receive an object with optional ids 
```
{
  id: 1,
  optionalIds: [1, 2, 3]
}
```

then after the form is updated the data is sent back without the `optionaIds` field (missing or `undefined`), but when looking into the network tab the old `optionalIds` are set back with the original values of `[1, 2, 3]`, this does seem to me like a bug, unless there's a legitimate reason for this kind  of behavior.

**Comment by markerikson** [comment]
This report isn't very clear. What are you actually trying to do?  Can you show some actual code, or record and share a Replay ( https://replay.io/record-bugs )?
