### ISSUE TITLE
createSelector re renders component after closing keyboard React Native

### ISSUE THREAD

**Issue by ZoHayk** [reduxjs/redux-toolkit#3759]
### Description

Hello, I noticed a strange bug in the work keyboard dismiss.
When we enter something in the input and closes the keyboard, it re renders component. If we take data from the store via redux. The important point is that after entering, not even after deleting, and even just opening and closing, but after entering this strange bug is happening.

If close the keyboard via Keyboard.dismiss(), a re-render occurs. And if close through the return button in the keyboard it works correctly. I haven't anything in the store about opening and closing the keyboard!

### React Native Version

0.72.5

### Output of `npx react-native info`

```
    "@reduxjs/toolkit": "^1.9.5",
    "react": "18.2.0",
    "react-native": "0.72.5",
    "react-redux": "^8.1.2",
```

### Steps to reproduce

[Video](https://drive.google.com/file/d/1mBBPzeLMrJthkrwAS9kBx0Lj_A02vEON/view?usp=sharing)

### Snack, screenshot, or link to a repository

```
import React from 'react';
import { TextInput, TouchableOpacity, View, Keyboard } from 'react-native';
import { createSelector } from '@reduxjs/toolkit';
import { useSelector, useDispatch } from 'react-redux';
import { RootState } from 'types';
import { changeTestInfo } from 'features/test/slice';

export const MenuScreen: React.FC = () => {
  const dispatch = useDispatch();
  const screenState = useSelector((state: RootState) => state.test);

  console.log(screenState);
  return (
    <View style={{ flex: 1, backgroundColor: 'green', paddingTop: 100 }}>
      <TextInput
        placeholder="Enter here"
        value={screenState.searchText}
        onChangeText={value => dispatch(changeTestInfo({ key: 'searchText', value }))}
        style={{ backgroundColor: 'white', height: 40, fontSize: 30 }}
      />
      <TouchableOpacity
        style={{ height: 100, width: 100, backgroundColor: 'yellow' }}
        onPress={() => Keyboard.dismiss()}
      />
    </View>
  );
};
```

If do the same with useState, it works correctly.

```
  const [searchText, setSearchText] = useState('');
```

Or do you need to specifically take from redux what you need.

```
  const searchText = useSelector((state: RootState) => state.test.searchText);
  ...
  value={searchText}
```

I don't understand why closing the keyboard causes re-rendering.

**Comment by ZoHayk** [comment]
Fixed this error
onEndEditing={() => false}

**Comment by EskiMojo14** [comment]
your selector is incorrectly memoised. an input selector that returns the entire root state means that your output selector will be recalculated whenever *anything* in store changes.

in your case you're not actually deriving anything, so you don't *need* createSelector at all. as you say, `(state) => state.test.searchText` works just fine.

**Comment by ZoHayk** [comment]
https://github.com/facebook/react-native/issues/39742

**Comment by ZoHayk** [comment]
@EskiMojo14 I don't store anything in the store about opening and closing the keyboard.

**Comment by ZoHayk** [comment]
@markerikson Thank you.
