### ISSUE TITLE
Restore bundle size CI job

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#3770]
We used to have one, and it stopped working at some point.  It'd be nice to see this again.

**Comment by markerikson** [comment]
No specific limit to enforce, I'm just looking for visibility (especially as we iterate on new features).

Things I'd like it to report:

- Changes to the _total_ size of the minified production artifact for each entry point
- Changes in tree-shaken import size for specific exported APIs (`configureStore`, `createSlice`, `createApi`, and maybe a couple others)

**Comment by aryaemami59** [comment]
I believe this one is resolved by #4083

**Comment by EskiMojo14** [comment]
yessir
