### ISSUE TITLE
RTK createApi with React Router 6 not updating state

### ISSUE THREAD

**Issue by anwarjaved** [reduxjs/redux-toolkit#3782]
I am trying to use RTK for first time, I was using redux manually before.

I am facing two issues. I have created an Api Slice and I need to create an endpoint to load all users from db. but it seems builder.query always requires two Type First is return type, second one is argument type, is there an way to avoid second option.

second issue is that  I am trying to use hooks like this

`const { data, error, isError, isSuccess, isLoading, isFetching } = useGetUsersQuery(undefined);` and it hits the endpoint and get the data  I can see it in Network Request but isLoading or isSuccess never updated and my components never updated with new data. What I am missing.

**Comment by EskiMojo14** [comment]
if you want to make the argument not required, you can pass void as the second type parameter.

Would you be able to make a reproduction or even a [Replay](https://replay.io) of the second issue? Your component should rerender and receive the new data.

**Comment by anwarjaved** [comment]
for first issue i tried using void but i still need to pass undefined to it on typescript 


for second issue i checked it's hitting server correctly just component not rerendering do we have to do something to make it work

**Comment by anwarjaved** [comment]
another thing do i have to use apiprovider or provider will work too

**Comment by markerikson** [comment]
The only time you would ever use `<ApiProvider>` is if you are _not_ already creating a Redux store in the app.

Otherwise, it's the usual `<Provider store={store}>`.

Unfortunately, right now we don't have enough information to help you - "doesn't re-render" isn't anything we can use to guess what might be happening.  We'd need a CodeSandbox, or a Github repo , or a Replay

**Comment by anwarjaved** [comment]
> The only time you would ever use `<ApiProvider>` is if you are _not_ already creating a Redux store in the app.
> 
> Otherwise, it's the usual `<Provider store={store}>`.
> 
> Unfortunately, right now we don't have enough information to help you - "doesn't re-render" isn't anything we can use to guess what might be happening. We'd need a CodeSandbox, or a Github repo , or a Replay

How I use replay. I can't share the repo as its private
