### ISSUE TITLE
Question: reading top level state in `createSlice`

### ISSUE THREAD

**Issue by smacpherson64** [reduxjs/redux-toolkit#379]
👋  Hey There, first off thank you, this toolkit is extremely helpful! 

**Question**:
Is there something special needed to read the top level state (including the initial state)? 

When I attempt to `console.log` the state returns`null` instead of the expected empty object `{}`. I did not know if this was intentional and couldn't find it in the docs.

```javascript
import { createSlice, configureStore } from "@reduxjs/toolkit";

const example = createSlice({
  name: "example",
  initialState: {},
  reducers: {
    setName: (state, action) => {
      console.log(state); // null
      state.name = action.payload;
    }
  }
});

const store = configureStore({
  reducer: example.reducer
});

store.dispatch(example.actions.setName("test"));
```

[![Edit exploration: react-toolkit empty state](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/strange-dream-vok6o?fontsize=14&hidenavigation=1&theme=dark)

Thanks for your time!

**Comment by markerikson** [comment]
Hmm.  I'm not seeing `"`null`"` when I step through this sandbox (and btw, _thank_ you for including a sandbox with this issue!).  What I'm seeing is `Proxy`: 

![image](https://user-images.githubusercontent.com/1128784/74980229-15289080-53fe-11ea-9cc6-bb73563aede5.png)

Where exactly are you seeing `null`?  Can you provide a screenshot?

**Comment by smacpherson64** [comment]
Thanks for checking it out! 

In the console logs for codesandbox:

<img width="473" alt="Screen Shot 2020-02-20 at 3 39 14 PM" src="https://user-images.githubusercontent.com/1659099/74981102-46519280-53f7-11ea-8a3d-c22f345db773.png">

<img width="621" alt="Screen Shot 2020-02-20 at 3 40 54 PM" src="https://user-images.githubusercontent.com/1659099/74981183-66815180-53f7-11ea-85f6-8225f5786e43.png">

**Comment by markerikson** [comment]
I'm going to chalk this up to something how logging Proxies works.

If I put a breakpoint in the reducer, and drill down inside of `state`, here's what I see as the contents inside the `Proxy`:

![image](https://user-images.githubusercontent.com/1128784/74982095-7a31b580-5401-11ea-8a61-6457508a8f0f.png)

So there is an empty object inside there.

After the `state.name = ` line, at the end of the function, here's what the resulting `Proxy` looks like:

![image](https://user-images.githubusercontent.com/1128784/74982164-9b92a180-5401-11ea-8853-60de56385bdd.png)

and now Immer shows that a copy has been made including the changes.

The Redux DevTools show that both stores were correctly updated.

So, I think this is _just_ an issue with how the Proxies are getting logged , not a functionality problem.

**Comment by smacpherson64** [comment]
Sounds good! Thanks again for looking into this, I am sorry it ended up being frivolous.

**Comment by iviireczech** [comment]
I have the same question as mentioned in question. How can I access state from another slice inside createSlice if there is dependency between slices?

**Comment by smacpherson64** [comment]
Hey @iviireczech!

I think you may be able to take advantage of thunks being inside of `@reduxjs/toolkit` for global state! Below is a bit simple and likely would need a lot of help but it does show the power of Thunk for getting global state. It does happen before the reducer so it wouldn't be inside the slice, but it would give you global state before it gets there!

Sincerely hope this helps your case!

```javascript
import { createSlice, configureStore, combineReducers } from "@reduxjs/toolkit";

const books = createSlice({
  name: "books",
  initialState: {},
  reducers: {
    add: (state, action) => {
      state[action.payload.id] = action.payload;
    }
  }
});

const movies = createSlice({
  name: "movies",
  initialState: {},
  reducers: {
    add: (state, action) => {
      state[action.payload.id] = action.payload;
    }
  }
});

const whitelist = createSlice({
  name: "whitelist",
  initialState: {},
  reducers: {
    add: (state, action) => {
      state.push(action.payload);
    }
  }
});

const store = configureStore({
  reducer: combineReducers({
    books: books.reducer,
    movies: movies.reducer,
    whitelist: whitelist.reducer
  }),
  preloadedState: {
    books: {},
    movies: {},
    whitelist: ["The Hound of the Baskervilles"]
  }
});

// Thunk has access to global state
function addNewItem(item) {
  return (dispatch, getState) => {
    const { whitelist } = getState();

    if (!whitelist.includes(item.title)) {
      console.log(`Rejected title ${item.title}, not in whitelist`);
      return;
    }

    if (item.type === "book") {
      dispatch(books.actions.add(item));
    } else if (item.type === "movie") {
      dispatch(movies.actions.add(item));
    }
  };
}

// adding the book fails because it is not in the whitelist
store.dispatch(
  addNewItem({
    type: "book",
    title: "20000 Leags Under the Sea",
    id: 9787538729368,
    url:
      "https://www.amazon.com/000-Leagues-Under-Signet-Classics/dp/0451531698"
  })
);

// movie gets added to state because it is in the whitelist
store.dispatch(
  addNewItem({
    type: "movie",
    title: "The Hound of the Baskervilles",
    id: "tt0031448",
    url: "https://www.imdb.com/title/tt0031448/"
  })
);

// updates whitelist to include new title
store.dispatch(whitelist.actions.add("20000 Leags Under the Sea"));

// book gets added to state because it is in the whitelist
store.dispatch(
  addNewItem({
    type: "book",
    title: "20000 Leags Under the Sea",
    id: 9787538729368,
    url:
      "https://www.amazon.com/000-Leagues-Under-Signet-Classics/dp/0451531698"
  })
);

console.log(JSON.stringify(store.getState(), null, 2));
``` 

[![Edit exploration: using redux-toolkit thunks for global state](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/exploration-using-redux-toolkit-thunks-for-global-state-6j3ew?fontsize=14&hidenavigation=1&theme=dark)

**Comment by phryneas** [comment]
But also keep in mind that you usually don't want to do that. 
A slice should be self-contained and not rely on the contents of other slices, but only on the last state of the slice and the information that came in via the action. 
If that doesn't work, the scope of your slice is probably wrong.

**Comment by smacpherson64** [comment]
True!

**Comment by iviireczech** [comment]
@phryneas: I think that having dependent slices is perfectly valid. See [this](https://github.com/reduxjs/redux/issues/749#issuecomment-141570236) or [this](https://github.com/reduxjs/redux/issues/749#issuecomment-164327121).

Maybe it is too uncommon use-case but I would like to know if this can be achieved using createSlice only without need for reduce-reducer or custom root reducer.

As I write above,  something like this would be great:

```
const example = createSlice({  
  name: "example",  
  initialState: {},  
  reducers: {  
    setName: (sliceState, action, globalState) => {}  
  }  
});
```

**Comment by phryneas** [comment]
> @phryneas: I think that having dependent slices is perfectly valid. See [this](https://github.com/reduxjs/redux/issues/749#issuecomment-141570236), [this](https://github.com/reduxjs/redux/issues/749#issuecomment-164327121) or [this](https://github.com/reduxjs/redux/issues/749#issuecomment-290942376)
> 
> Maybe it is too uncommon use-case but I would like to know if this can be achieved using createSlice only without need for reduce-reducer or custom root reducer.
> 
> As I write above, something like this would be great:
> 
> ```
> const example = createSlice({  
>   name: "example",  
>   initialState: {},  
>   reducers: {  
>     setName: (sliceState, action, globalState) => {}  
>   }  
> });
> ```

These cases all describe parallel reducers, with patterns that add additional information to a reducer is passed as an additional argument - but never with a pattern that passes the whole state as an argument. 
If we introduced that "hole state" argument, people would probably make heavy use of it, even in cases where it wasn't necessary and it would lead to a *lot* of spaghetti code down the line. 
And the reason for RTK is to provide an opinionated framework to prevent such code.

The approach offered in the comments you linked were (for a good reason) highly selected and narrowly-scoped.

My personal approach, if you really needed this, would be to add a middleware, that for some actions waited for the action to be processed, then take part of the derived state and put that (along with the old payload) onto a new action that would be processed by the second slice.

Or, more practically: just to create one slice that contained more information. If these states are so dependent on each other, most of the times they logically are the same slice and the divide between them is purely artificial.

**Comment by iviireczech** [comment]
@phryneas: Thanks for your ideas, they are interesting. Must give them a try

**Comment by markerikson** [comment]
Per the linked issues, this question actually has nothing to do with the `createSlice` itself.  It's really about how Redux's standard default approach for dividing up reducer logic is by "slice reducer" in general.

These two docs references summarize the suggested approaches for handling this:

https://redux.js.org/faq/reducers#how-do-i-share-state-between-two-reducers-do-i-have-to-use-combinereducers

https://redux.js.org/recipes/structuring-reducers/beyond-combinereducers
