### ISSUE TITLE
RTK Query Open API Code Gen - No Changelog, No Symantic Version(s)

### ISSUE THREAD

**Issue by elliot-huffman** [reduxjs/redux-toolkit#3796]
Hi Team,

I use the code generator for the RTK Query component and there were a series of updates recently that broke my code. I had to manually go over all the changed code (which is not checked in due to it auto generating) to find the breaking changes.

Also, the RTK Query package does not follow semantic versioning as a breaking change occurred on a non-major version. It happened on a point release.

I would like to request two things:
1. Follow semantic versioning for breaking changes like the new readOnly/writeOnly generation support which removed properties from the existing types that are generated, breaking build process.
2. Implement a changelog so that when breaking changes occur, they are listed so that troubleshooting doesn't have to be an extended reverse engineering endeavor, and migration steps are listed.

**Comment by markerikson** [comment]
Can you clarify what breaking changes happened?  We did intend that to be a minor version.

Also, this is only the first time we've even tried to release the codegen since we shipped the original version two years ago, and we also were trying out a new automated CI release step.  So, yeah, we ought to do release notes, but this was us trying to get the version shipped over a weekend and having a lot of differences from our typical release procedure.

**Comment by phryneas** [comment]
1. We try that. 
Unfortunately, none of us maintainers actually uses the OpenAPI Codegen for anything, and certainly not edge-case scenarios like `readOnly`. From reading the PR and the description of those modifiers, it seemed that any attempt sending a `readOnly` property to the server would end up as a protocol violation, result in an error from the server and as a consequence that *seemed* to us (on a "best knowledge" basis) as a non-breaking change.
2. We don't have a "changelog" process yet, as GitHub doen't really allow us for good "per-package" releases, and this is primarily the "Redux Toolkit" repository. 
But since v1.0.0, the codegen has seen one minor and four patch releases, each of them only containing a single commit, so I hope at this point this is still good enough to follow.
We'll see that we get something up though, once the codegen picks up in pace and release regularity.

As for a breaking change in RTK Query itself: to my knowledge, RTK Query hasn't had a breaking change that wasn't actually a bugfix (in that perspective, every fix is breaking of course). Could you give us some feedback what was breaking here?

**Comment by elliot-huffman** [comment]
> Can you clarify what breaking changes happened? We did intend that to be a minor version.
> 
> Also, this is only the first time we've even tried to release the codegen since we shipped the original version two years ago, and we also were trying out a new automated CI release step. So, yeah, we ought to do release notes, but this was us trying to get the version shipped over a weekend and having a lot of differences from our typical release procedure.

The issue that was caused on my side was that the read only properties were moved out of the normal object def. E.G.
Snippet of JSON for the Open API schema def I have.
```JSON
"ManagedDevice": {
                "description": "A computed device object. This is generated by combining multiple pieces of metadata.",
                "properties": {
                    "commissionedDate": {
                        "description": "This is the ISO 8601 string format of the time representing the commission date of the PAW.",
                        "example": "2023-02-04T05:06:09.601Z",
                        "format": "date-time",
                        "type": "string"
                    },
                    "displayName": {
                        "description": "Current computer name of the device according to Entra ID. Empty string indicates that the device has not joined Entra ID yet",
                        "example": "Priv-01534962354",
                        "maxLength": 15,
                        "minLength": 0,
                        "type": "string"
                    },
                    "groupAssignment": {
                        "description": "This is the ID of the Custom CSP Device Configuration that configures the local admin and local hyper-v group memberships.",
                        "example": "830d8b6f-2f6f-41f7-8800-0c07445abd36",
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$",
                        "type": "string"
                    },
                    "id": {
                        "description": "Read-only.",
                        "example": "9f237e13-9a04-4daf-b3d4-6d2beec3c2bf",
                        "format": "uuid",
                        "maxLength": 36,
                        "minLength": 36,
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$",
                        "readOnly": true,
                        "type": "string"
                    },
                    "parentDevice": {
                        "description": "DeviceID of the parent PAW device.",
                        "example": "81682cf5-0405-491d-8ab8-e07c778d7eaf",
                        "nullable": true,
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$",
                        "type": "string"
                    },
                    "type": {
                        "$ref": "#/components/schemas/SecurityClassList"
                    },
                    "uniqueGroup": {
                        "description": "The object ID of the unique security group that contains the managed Entra ID Device Identity.",
                        "example": "146964e0-8ca4-4af0-9c2a-894b32912463",
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$",
                        "readOnly": true,
                        "type": "string"
                    },
                    "userAssignment": {
                        "description": "The ID of the Settings Catalog that contains the user rights assignment of the specified PAW device.",
                        "example": "146964e0-8ca4-4af0-9c2a-894b32912463",
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$",
                        "readOnly": true,
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "uniqueGroup",
                    "type",
                    "displayName",
                    "commissionedDate",
                    "uniqueGroup"
                ],
                "title": "Managed Device Object",
                "type": "object"
            },
```

Generated Type object before:
```TypeScript
export type ManagedDeviceObject = {
  commissionedDate: string;
  displayName: string;
  groupAssignment?: string;
  id: string;
  parentDevice?: string | null;
  type: TypeOfSecurityClassTheObjectSBelongsTo;
  uniqueGroup: string;
  userAssignment?: string;
};
```

Generated Type Objects after changes:
```TypeScript
export type ManagedDeviceObject = {
  commissionedDate: string;
  displayName: string;
  groupAssignment?: string;
  parentDevice?: string | null;
  type: TypeOfSecurityClassTheObjectSBelongsTo;
};
export type ManagedDeviceObjectRead = {
  commissionedDate: string;
  displayName: string;
  groupAssignment?: string;
  id: string;
  parentDevice?: string | null;
  type: TypeOfSecurityClassTheObjectSBelongsTo;
  uniqueGroup: string;
  userAssignment?: string;
};
```

As you can see, it moved all read only objects out of the 'normal' object into a new type with the 'normal' object's name but suffixed as 'Read'.

It is for all intents and purposes the 'normal' object and I migrated my typing references to use the 'Read' types intead.

**Comment by elliot-huffman** [comment]
> Can you clarify what breaking changes happened? We did intend that to be a minor version.
> 
> Also, this is only the first time we've even tried to release the codegen since we shipped the original version two years ago, and we also were trying out a new automated CI release step. So, yeah, we ought to do release notes, but this was us trying to get the version shipped over a weekend and having a lot of differences from our typical release procedure.

The issue that was caused on my side was that the read only properties were moved out of the normal object def. E.G.
Snippet of JSON for the Open API schema def I have.
```JSON
"ManagedDevice": {
                "description": "A computed device object. This is generated by combining multiple pieces of metadata.",
                "properties": {
                    "commissionedDate": {
                        "description": "This is the ISO 8601 string format of the time representing the commission date of the PAW.",
                        "example": "2023-02-04T05:06:09.601Z",
                        "format": "date-time",
                        "type": "string"
                    },
                    "displayName": {
                        "description": "Current computer name of the device according to Entra ID. Empty string indicates that the device has not joined Entra ID yet",
                        "example": "Priv-01534962354",
                        "maxLength": 15,
                        "minLength": 0,
                        "type": "string"
                    },
                    "groupAssignment": {
                        "description": "This is the ID of the Custom CSP Device Configuration that configures the local admin and local hyper-v group memberships.",
                        "example": "830d8b6f-2f6f-41f7-8800-0c07445abd36",
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$",
                        "type": "string"
                    },
                    "id": {
                        "description": "Read-only.",
                        "example": "9f237e13-9a04-4daf-b3d4-6d2beec3c2bf",
                        "format": "uuid",
                        "maxLength": 36,
                        "minLength": 36,
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$",
                        "readOnly": true,
                        "type": "string"
                    },
                    "parentDevice": {
                        "description": "DeviceID of the parent PAW device.",
                        "example": "81682cf5-0405-491d-8ab8-e07c778d7eaf",
                        "nullable": true,
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$",
                        "type": "string"
                    },
                    "type": {
                        "$ref": "#/components/schemas/SecurityClassList"
                    },
                    "uniqueGroup": {
                        "description": "The object ID of the unique security group that contains the managed Entra ID Device Identity.",
                        "example": "146964e0-8ca4-4af0-9c2a-894b32912463",
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$",
                        "readOnly": true,
                        "type": "string"
                    },
                    "userAssignment": {
                        "description": "The ID of the Settings Catalog that contains the user rights assignment of the specified PAW device.",
                        "example": "146964e0-8ca4-4af0-9c2a-894b32912463",
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$",
                        "readOnly": true,
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "uniqueGroup",
                    "type",
                    "displayName",
                    "commissionedDate",
                    "uniqueGroup"
                ],
                "title": "Managed Device Object",
                "type": "object"
            },
```

Generated Type object before:
```TypeScript
export type ManagedDeviceObject = {
  commissionedDate: string;
  displayName: string;
  groupAssignment?: string;
  id: string;
  parentDevice?: string | null;
  type: TypeOfSecurityClassTheObjectSBelongsTo;
  uniqueGroup: string;
  userAssignment?: string;
};
```

Generated Type Objects after changes:
```TypeScript
export type ManagedDeviceObject = {
  commissionedDate: string;
  displayName: string;
  groupAssignment?: string;
  parentDevice?: string | null;
  type: TypeOfSecurityClassTheObjectSBelongsTo;
};
export type ManagedDeviceObjectRead = {
  commissionedDate: string;
  displayName: string;
  groupAssignment?: string;
  id: string;
  parentDevice?: string | null;
  type: TypeOfSecurityClassTheObjectSBelongsTo;
  uniqueGroup: string;
  userAssignment?: string;
};
```

As you can see, it moved all read only objects out of the 'normal' object into a new type with the 'normal' object's name but suffixed as 'Read'.

It is for all intents and pourposes the 'normal' object and I migrated my typing references to match, it would have been nice to know ahead of time.

> 1. We try that.
>    Unfortunately, none of us maintainers actually uses the OpenAPI Codegen for anything, and certainly not edge-case scenarios like `readOnly`. From reading the PR and the description of those modifiers, it seemed that any attempt sending a `readOnly` property to the server would end up as a protocol violation, result in an error from the server and as a consequence that _seemed_ to us (on a "best knowledge" basis) as a non-breaking change. (Same for `writeOnly`, the other way round).
>    Could you provide some feedback here on what we misinterpreted here?
> 2. We don't have a "changelog" process yet, as GitHub doen't really allow us for good "per-package" releases, and this is primarily the "Redux Toolkit" repository.
>    But since v1.0.0, the codegen has seen one minor and four patch releases, each of them only containing a single commit, so I hope at this point this is still good enough to follow.
>    We'll see that we get something up though, once the codegen picks up in pace and release regularity.
> 
> As for a breaking change in RTK Query itself: to my knowledge, RTK Query hasn't had a breaking change that wasn't actually a bugfix (in that perspective, every fix is breaking of course). We have a bunch of changes queued up for 2.0.0 because they would be breaking. Could you give us some feedback what was breaking here?

Responses:
1. No worries on not using it, I would have expected the Unit Tests to catch a change like this, although edge cases do slip through the cracks, I am guilty of this myself.
2. For changelogs, Microsoft does it in its own markdown file and JSON file in the package's folder for a multi-package repo (see [this for examples](https://github.com/microsoft/fluentui)). There are also [other projects](https://github.com/typescript-eslint/typescript-eslint) that use the GitHub releases system for all their packages, some where each package gets its own release (I personally separate each package into its own repo, instead of having a single mono-repo and submodule them together as needed or just pull straight from NPM for my build processes). There are pros and cons to mono-repos and ways to make micro-repos and mono-repos work in either case.
2.5. For specific details on what broke, see my previous reply.

**Comment by phryneas** [comment]
Ah, this is about types changing, not runtime code.

Generally, we try to keep those as similar as possible, but there can never be a guarantee that they declarations stay exactly the same - even if we never introduced changes, a lot of them are generated by our upstream dependency `oazapfts` and may change due to that.

> No worries on not using it, I would have expected the Unit Tests to catch a change like this, although edge cases do slip through the cracks, I am guilty of this myself.

Yeah, we were just not aware of `readonly` etc., so none of our tests contained it before the change - and the new tests only tested the new behaviour, not new vs old.

Generally, I want to really recommend that you also check in generated code - it will allow you to easily spot any changes in generated code. 


As for the aftermath of this change: I'm not sure what the best way forward here is. I don't feel that rolling back would help a lot - it would probably cause even more confusion.
Would you be interested in filing a PR that adds a configuration option that allows people to turn the old behaviour on?

**Comment by elliot-huffman** [comment]
I like the new behavior, just wish it were a major bump instead of a patch bump. Please don't roll back.

**Comment by phryneas** [comment]
Yeah, I'm sorry for that. I'll try to be more thorough next time.

**Comment by elliot-huffman** [comment]
I guess that just leaves the change log issue, would you be willing to make a changelog.md file in the code gen project root? That would allow for quick checks on what has changed across each version since there isn't anything that I could find in a blog post or in the release system.

**Comment by phryneas** [comment]
Generally yes, but all of us maintainers will be at conferences next week, so it'll take some time.

We'd accept a PR with a Changelog instantly though :)

**Comment by elliot-huffman** [comment]
I can totally make one :-)
You shall see a PR coming in shortly

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
