### ISSUE TITLE
Clarifying error message about type in addCase

### ISSUE THREAD

**Issue by inoyakaigor** [reduxjs/redux-toolkit#3799]
I am newbie in RTK and when I met error `'builder.addCase' cannot be called with two reducers for the same action type` I cannot recognize which one of my types is duplcated.
I solved my problem with devtools logpoint but it's not convenient at all
![image](https://github.com/reduxjs/redux-toolkit/assets/1235286/45847738-0573-40de-a5d6-48f59e053028)
![image](https://github.com/reduxjs/redux-toolkit/assets/1235286/8278f088-a35d-49e6-bf25-540d2dd9258c)

It would be great if error will contain type. For example:
`'builder.addCase' cannot be called with two reducers for the same action type ${type}`

**Comment by markerikson** [comment]
Sure, makes sense. Can you file a PR to tweak that?

**Comment by inoyakaigor** [comment]
@markerikson Sure!

**Comment by Kalibryyy** [comment]
@markerikson I made a PR for this issue
