### ISSUE TITLE
Feature Request (@rtk-query/codegen-openapi): Add option to generate zod types 

### ISSUE THREAD

**Issue by SaadBazaz** [reduxjs/redux-toolkit#3803]
Hey,
Love the autogen.

Could we have a flag to generate Zod types instead of just standard TypeScript types? APIs are usually used alongside forms, and having a form validation lib coupled with this codegen could really boost web app form capabilities.

**Comment by phryneas** [comment]
That's probably not possible - the types are generated by an upstream library, `oazapts` and not by us ourselves - so we don't really know their structure in our own code.

**Comment by SaadBazaz** [comment]
Okay I'll ask em. Thanks!

**Comment by nstadigs** [comment]
Another route would be to create a rtkq plugin for https://github.com/hey-api/openapi-ts. It would define the zod plugin as a dependency and build from there
