### ISSUE TITLE
Non-serializable warning `meta.baseQueryMeta` in RTK Query when setting `ignoredActionPaths`

### ISSUE THREAD

**Issue by rokiyama** [reduxjs/redux-toolkit#3804]
When I set `ignoredActionPaths` in `serializableCheck`, I get a non-serializable warning during RTK Query calls.

```ts
export const store = configureStore({
  reducer: {
    [apiSlice.reducerPath]: apiSlice.reducer,
  },
  middleware: (getDefaultMiddleware) => {
    return getDefaultMiddleware({
      serializableCheck: {
        ignoredActionPaths: ['my.action'],
      },
    }).concat(apiSlice.middleware)
  },
})
```

Warning message:

```
A non-serializable value was detected in an action, in the path: `meta.baseQueryMeta.request`.
```

![image](https://github.com/reduxjs/redux-toolkit/assets/57606749/c0909a83-71d3-4b09-b5f1-32afff74cd0b)

Workaround: Comment out `ignoredActionPaths` or add `meta.baseQueryMeta` to the ignore list.

Reproduction: https://github.com/rokiyama/example-rtk-query-non-serializable-warn

Environment: `@reduxjs/toolkit@1.9.7`, `react@18.2.0`, `react-dom@18.2.0`, `react-redux@8.1.3`, `redux@4.2.1`

**Comment by EskiMojo14** [comment]
ignoredActionPaths defaults to `['meta.arg', 'meta.baseQueryMeta']`. When you override this, it's your responsibility to add them back to your array.

**Comment by markerikson** [comment]
Just out of curiosity, what other actions are you ignoring here?

**Comment by rokiyama** [comment]
`my.action` is just an example, my application is in the middle of migrating from old Redux code, and there are some items I want to temporarily ignore until it's done. It might look odd, my ignore list is:

```ts
  ignoredActionPaths: [
    'meta.arg',
    'meta.baseQueryMeta',
    'payload.attachFiles',
    'payload.action.payload.action.payload.error',
    'payload.action.payload.action.payload.result',
    'payload.action.payload.event',
    'payload.action.payload.result',
  ],
```
