### ISSUE TITLE
RTKQ: even after explicitly setting the 'content-type', when making request the content-type changes to text/html

### ISSUE THREAD

**Issue by prashantmgk** [reduxjs/redux-toolkit#3808]
i am using RTK Query to POST images using FormData. When i set 'content-type' to 'multipart/form-data' explicitly for the mutation to post the images, the post request fails:
```
uploadImage: builder.mutation({
         query: ({data}) => {
            return {
               url: '/events/uploadImages',
               method: 'POST',
               body: data,
               headers: {
                  'content-type': 'multipart/form-data'
               },
               formData: true,
            };
         },
      }),
```
![image](https://github.com/reduxjs/redux-toolkit/assets/30362730/71feed03-7daf-4111-9237-e70d27e5fee5)

in case it's relevant, i have set just the Authorization of header to Bearer token

```
const baseQuery = fetchBaseQuery({
   baseUrl: 'http://localhost:3000/booking-service',
   credentials: 'include',
   
   prepareHeaders: (headers, { getState, endpoint } ) => {
      const token = getState().auth.token
      if (token) {
         headers.set("Authorization", `Bearer ${token}`)
      }

      return headers;
   },
})
```

i looked through several issues which were similar to mine but couldn't fix the outcome while using those instructions. Therefore, i can't help but turn it as a new issue

**Comment by phryneas** [comment]
Your screenshot shows the response headers and those are different from your request headers.

**Comment by prashantmgk** [comment]
@phryneas 
apologies.. the issue was on my end.. i consulted with the team and came to a solution
