### ISSUE TITLE
 rtk-query-codegen-openapi: Null values not always respected

### ISSUE THREAD

**Issue by mattoni** [reduxjs/redux-toolkit#3814]
I've recently upgraded my OpenAPI schema to 3.1, and while in most places the 

```
type:
    - "object"
    - "null"
```

style seems to generate the correct code, in other places it does not. 

For example, given this:
![image](https://github.com/reduxjs/redux-toolkit/assets/5110855/89235a40-e5c2-4de5-a5eb-6a5e7a785ea5)

The generated output is:
![image](https://github.com/reduxjs/redux-toolkit/assets/5110855/881dc9cc-17aa-4863-a3ad-033e719cee91)

Where `stack` is not also nullable. 

The same thing happens in various other spots, such as here in the password field of this nested object:
![image](https://github.com/reduxjs/redux-toolkit/assets/5110855/c14276b6-ff25-4842-87f6-793171d5e4f1)

The output being:
![image](https://github.com/reduxjs/redux-toolkit/assets/5110855/526b9924-fd60-46a9-85a6-285e6962326e)

It appears to generate correctly in circumstances such as this:
![image](https://github.com/reduxjs/redux-toolkit/assets/5110855/de69a6bd-4dcc-41de-9e41-dd0aeca3eb48)

Where I use an anyOf to reference another type that can also be null in this field, the generated being:
![image](https://github.com/reduxjs/redux-toolkit/assets/5110855/f12cfcb9-4275-4c37-ba7c-f241e69b3d0b)

It appears that the generator doesn't work correctly when you have a type with multiple values, and one of them is `null`. I think the codegen should support this since it is the recommended way to handle nullable values in the OpenAPI spec.

**Comment by markerikson** [comment]
I believe this is handled by the upstream https://github.com/oazapfts/oazapfts library

**Comment by mattoni** [comment]
Thanks, I've opened an issue there! It'd be nice to support at least the basics of 3.1.0 since it's been out for a few years now.

**Comment by mattoni** [comment]
@markerikson it looks like the upstream version has been updated to include this fix. Does the package version need to be bumped in RTK?

**Comment by SimonEggert** [comment]
@markerikson Unfortunately there's a major update involved and quite some exports of the package have changed or are not available anymore. So I think we might need to

1. Reexport things that this repo relies on on oazapft's side
2. Update the imports here to match the new paths
3.

I will try to figure out what's missing to make the generator work with the new version. My first impression was that the only thing missing completely in their exports was the `ApiGenerator`.

**Comment by markerikson** [comment]
@SimonEggert sorry, clarify what new version of `oazapfts` has the fix?

Looking at https://github.com/oazapfts/oazapfts/releases , I do see that they're working on betas for a v6 major, but I'm not clear what relates to this issue specifically.

**Comment by SimonEggert** [comment]
@markerikson Seems that there's a lot going on in that repo indeed 😉

The release that has the fix is [5.1.7](https://github.com/oazapfts/oazapfts/releases/tag/v5.1.7) which is a patch release in itself, but RTK is still using 4.8.0. In order to upgrade and include the bugfix we would need to adapt some breaking changes.

**Comment by SimonEggert** [comment]
FTR: I opened another issue in the upstream library asking about what the proper way for updating would look like: https://github.com/oazapfts/oazapfts/issues/577

**Comment by SimonEggert** [comment]
@markerikson I opened PR #4198 including the necessary `oazapfts` update if you'd like to take a look.

**Comment by mattoni** [comment]
@markerikson is there anything blocking the above from being merged? Would be great for us to be on the latest so we can support 3.1.0 versioned specs.
