### ISSUE TITLE
TypeError: Failed to fetch while using redux-toolkit with new msw v. 2.0.0

### ISSUE THREAD

**Issue by bukanidzee** [reduxjs/redux-toolkit#3818]
Hello everyone, I'm trying to write app and some tests for it with jest. In my app I'm using redux-toolkit-query and I tried to use new msw 2.0.0 for mocking as [docs suggest](https://redux.js.org/usage/writing-tests#writing-integration-tests-with-components), but I only get TypeError: Failed to fetch error in response to all attempts to mock request

### Recreate Issue
I was able to recreate this issue in simple app in this [repo](https://github.com/bukanidzee/recreate-msw-typeerror) to see it you need to:

- Clone repo
- run `npm i`
- run `npm run test`
or you can look this [codesandbox](https://codesandbox.io/p/github/bukanidzee/recreate-msw-typeerror/main?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clo5qlfis00073j6i3on55mld%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clo5qlfis00033j6ibzayv6ql%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clo5qlfis00053j6iktbd2jed%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clo5qlfis00063j6ih5g2dk3y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clo5qlfis00033j6ibzayv6ql%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo5qlfir00023j6iq8nzjs7l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.gitignore%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clo5qlfis00033j6ibzayv6ql%2522%252C%2522activeTabId%2522%253A%2522clo5qlfir00023j6iq8nzjs7l%2522%257D%252C%2522clo5qlfis00063j6ih5g2dk3y%2522%253A%257B%2522id%2522%253A%2522clo5qlfis00063j6ih5g2dk3y%2522%252C%2522activeTabId%2522%253A%2522clo5rng2x00ju3j6iub05j1o0%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clo5rng2x00ju3j6iub05j1o0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Flogin%2522%257D%255D%257D%252C%2522clo5qlfis00053j6iktbd2jed%2522%253A%257B%2522id%2522%253A%2522clo5qlfis00053j6iktbd2jed%2522%252C%2522activeTabId%2522%253A%2522clo5rx8ss00rs3j6i88dgodjs%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo5qlfis00043j6iuk9dnhvg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clo5qlfof0017ehes38jl80pw%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clo5qlgdr008f3j6ir3t1qmrr%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Fjavascript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clo5qnx6o00bg3j6iix91sk5x%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clo5rx8ss00rs3j6i88dgodjs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clo5rx8uw001lefjthhl6c9rp%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Node version
v18.18.2
### Packages versions
"react-redux": "^8.1.2",
"@reduxjs/toolkit": "^1.9.5"

### API reducer

```ts
const specificEndPoints = [
  'register',
  'postArticle',
  'updateArticle',
  'getArticleContent'
]

export const blogApi = createApi({
  reducerPath: 'blogApi',
  tagTypes: ['Articles', 'ArticlesDetail', 'ArticlesContent', 'Comments'],
  baseQuery: fetchBaseQuery({
    baseUrl: '/api/',
    prepareHeaders: (headers, { getState, endpoint }) => {
      const token = (getState() as RootState)?.user?.token

      if (token !== '') {
        headers.set('Authorization', `Token ${token}`)
      }
      if (!specificEndPoints.includes(endpoint)) {
        //   headers.set('Content-Type', 'multipart/form-data')
        // } else {
        headers.set('Content-Type', 'application/json;charset=UTF-8')
      }

      return headers
    }
  }),
  endpoints: () => ({})
})
```
### Tested endpoints

```ts
export type ILoginResponse = {
  token: string
  userId: string
  name: string
  picture: string
  isAdmin: boolean
}
export const userApi = blogApi.injectEndpoints({
  endpoints: build => ({
    login: build.mutation<ILoginResponse, ILoginData>({
      query: body => ({
        url: 'auth/login',
        method: 'POST',
        body
      })
    }),

    checkAuth: build.query({
      query: () => ({
        url: 'auth/check',
        method: 'GET'
      })
    }),

    register: build.mutation<IFetchSuccess, FormData>({
      query: body => {
        return {
          url: 'auth/registration',
          method: 'POST',
          credentials: 'include',
          body
        }
      }
    })
  })
})

export const { useLoginMutation, useRegisterMutation, useCheckAuthQuery } =
  userApi
```

### One of failed tests

```ts
const handlers = [
  http.post('/api/auth/login', () => {
    return HttpResponse.json({
      userId: 1,
      name: 'Kovalev Aleksandr',
      token: 'fsafsefaefaewf',
      picture: null,
      isAdmin: false
    })
  })
]

const server = setupServer(...handlers)

describe('Login page', () => {
  beforeAll(() => server.listen())

  afterEach(() => server.resetHandlers())

  afterAll(() => server.close())

  test('Login work', () => {
    renderWithProviders(<Login />, { router: 'browser' })
    const emailField = screen.getByLabelText('Email')
    expect(emailField).toBeInTheDocument()
    const passwordField = screen.getByLabelText('Password')
    expect(passwordField).toBeInTheDocument()
    const button = screen.getByRole('button')
    expect(button).toBeInTheDocument()
  })

  test('Login use', async () => {
    const { store } = renderWithProviders(<App />, {
      router: 'memory',
      routerProps: { initialEntries: ['/login'] }
    })
    const emailField = screen.getByLabelText('Email')
    fireEvent.input(emailField, { target: { value: 'test@gmail.com' } })
    const passwordField = screen.getByLabelText('Password')
    fireEvent.input(passwordField, { target: { value: '123456789' } })
    const button = screen.getByTestId('login-submit')
    fireEvent.click(button)

    const avatar = await screen.findByTestId('logged-avatar')
    expect(avatar).toBeInTheDocument()

    const articleTitle = await screen.findByText('Articles')
    expect(articleTitle).toBeInTheDocument()
    const unloginButtons = await screen.findAllByText(/Logout/i)

    expect(unloginButtons).toHaveLength(2)

    const state = store.getState()
    expect(state.user).toMatchObject({
      userId: 1,
      name: 'Kovalev Aleksandr',
      token: 'fsafsefaefaewf',
      picture: null,
      isAdmin: false
    })

    fireEvent.click(unloginButtons[0])

    const loginButtons = await screen.findAllByText(/Login/i)

    expect(loginButtons).toHaveLength(2)
  })
})
```

### Component
```ts
export type ILoginData = {
  email: string
  password: string
}

const Login: FC = () => {
  const [sendLogin, { data, error }] = useLoginMutation()

  console.log({ data, error })
  const dispatch = useAppDispatch()

  const { handleSubmit, control } = useFetchForm<ILoginData>(error)

  const onSubmit = async (data: ILoginData): Promise<void> => {
    await sendLogin(data)
  }

  useEffect(() => {
    if (data !== undefined) {
      localStorage.setItem('auth', JSON.stringify(data))
      dispatch(login(data))
    }
  }, [data, dispatch])

  return (
    <CenterContainer>
      <StyledFormBox component='form' onSubmit={handleSubmit(onSubmit)}>
        <Typography variant='h4'>Login</Typography>
        <HookedTextField
          control={control}
          defaultValue=''
          label='Email'
          name='email'
          required
          autoFocus
          fullWidth
          variant='standard'
          type='email'
          sx={{
            color: 'inherit'
          }}
        />
        <HookedTextField
          label='Password'
          variant='standard'
          control={control}
          defaultValue=''
          name='password'
          required
          fullWidth
          type='password'
          sx={{
            color: 'inherit'
          }}
        />
        <Button type='submit' variant='contained' data-testid='login-submit'>
          Login
        </Button>
      </StyledFormBox>
    </CenterContainer>
  )
}

export default Login
```

**Comment by EskiMojo14** [comment]
as per https://github.com/mswjs/msw/issues/1794, this is because you're using a relative URL in Node, which only supports absolute URLs.
