### ISSUE TITLE
What is the correct way to conditionally skip execution of a query with no arguments?

### ISSUE THREAD

**Issue by benosmond** [reduxjs/redux-toolkit#3821]
What is the correct way to conditionally skip a query such as this one?
```typescript
get: builder.query<string, void>({
    query: () => '/resource'
})
```

It is possible to call the query with a `skipToken` as an argument:
```typescript
const result = useGetQuery(skipToken);
```
This, however, never executes the query and is functionally pointless.

With the parameter defined as `void`, it does not appear possible to provide a value for the `skip` parameter (or any of the query options).
```typescript
// Error: Argument of type { skip: boolean } is not assignable to parameter of type 'void | unique symbol'
const result = useGetQuery({ skip: true });
```

Since `void` isn't a valid return value, ternary or any other kind of conditional logic gives a compiler error.
```typescript
// Error: Expression expected.
const result = useGetQuery(skip ? skipToken : void);
```

It appears to be possible to pass in a value of `undefined` without creating an error, though the resulting code is a little weird looking.
```typescript
const result = useGetQuery(skip ? skipToken : undefined);
```

It's also possible to make a local function which returns `void | skipToken`:
```typescript
function getArgs(skip: boolean) {
    if (skip) return skipToken;
    else return;
}
const result = useGetQuery(getArgs(skip));
```
As above, this gets the job done but is quite a clumsy approach.

The question is... what's the right way to do this? Is it one of the above, or something else?

**Comment by EskiMojo14** [comment]
passing `undefined `is the correct approach.
`useGetQuery()` and `useGetQuery(undefined)` are equivalent.
