### ISSUE TITLE
RTKQ: invalidatesTags doesnt work ?

### ISSUE THREAD

**Issue by Engazan** [reduxjs/redux-toolkit#3828]
i have ``postEditInvoicePaidStatus`` mutation that have ``invalidatesTags: ['Documents'],`` so it should invalidate ``Documents`` tags ( cache ) and refetch my ``providesTags: ['Documents'],`` queries if i m not wrong, but it does not :/

i use 
```
   "react": "18.2.0",
   "react-native": "0.72.5",
    "react-redux": "^8.1.3",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "@reduxjs/toolkit": "^1.9.6",
```

ApiReducer
```js
getInvoices: builder.query({
            providesTags: ['Documents'],
            query: (body: {
                uuid: string
            }) => ({
                url: `user/company/${body.uuid}/invoices`,
                method: 'GET',
            }),
        }),
        postEditInvoicePaidStatus: builder.mutation({
            query: (body: {
                companyUuid: string
                invoiceUuid: string
                paid: boolean
            }) => ({
                url: `user/company/${body.companyUuid}/invoice/${body.invoiceUuid}/paid`,
                method: 'POST',
                body
            }),
            invalidatesTags: ['Documents'],
        }),
```

they are called like this in component when user click on button 
```tsx
const [
        postEditInvoicePaidStatus,
        postEditInvoicePaidStatusResult,
    ] = ApiReducer.endpoints?.postEditInvoicePaidStatus.useMutation();
```

so when ``postEditInvoicePaidStatus({...})`` is called it should refetch my ``getInvoices`` right ? 

also i have ``middleware`` added to ``store`` config ( ``ApiReducer.middleware`` is from ``createApi`` )
```js
export const store = configureStore({
    reducer: persistedReducer,
    middleware: (getDefaultMiddleware) => getDefaultMiddleware({
        serializableCheck: {
            ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
        }
    }).concat([
        ApiReducer.middleware,
        thunk,
        // logger,
    ]),
});
```

**Comment by phryneas** [comment]
If you don't get any errors on your console, that should trigger it - but we'd need a Replay recording or CodeSandbox to see that ourselves.

**Comment by Engazan** [comment]
> If you don't get any errors on your console, that should trigger it - but we'd need a Replay recording or CodeSandbox to see that ourselves.

i made **small example** in **EXPO Go Stack** -> https://snack.expo.dev/@engazan/rtkq-invalidatestags-doesnt-work

its React native so you can test it Directly from WEB or on your phone device using Expo Go app, but its Reproducible in web too

- when you open app you see List of items with **CORAL** background, when u click item it calls ``postEditInvoicePaidStatus`` witch have ``invalidatesTags: ['Documents'],``, when u refresh page it updates cuz its refetched by "useEffect" hook 

ApiReducer -> /components/redux/reducers/ApiReducer
MainComponent where are hooks called -> /components/InvoiceList

also ignore "redux" beta package in "package.json", its not used anyways but its required to make Expo Go Stack happy ...

**Comment by phryneas** [comment]
If I click one of those buttons, I see a request against `/paid` (the mutation) and then another request against `/invoices` (the invalidated query).

What in addition to that do you expect to happen?

**Comment by phryneas** [comment]
If you want the `"loaded"` state to change, you have to watch `isFetching`, not `isLoading`. That's the only thing I could think of here.

**Comment by Engazan** [comment]
> If you want the `"loaded"` state to change, you have to watch `isFetching`, not `isLoading` (that one doesn't change after the initial load). That's the only thing I could think of here.

i expected that when i click on "PAID" component, it send "/paid" mutation to sevrer and chamnnge "paid" to "unpaid" but it does not reflect in UI, it only reflect when i call again "getInvoices" query ( it shold be done automatically when i invalide that cache ) or when i refresh page ( it calls "getInvoices" )

**Comment by phryneas** [comment]
Wouldn't you need to call `setFlatListData` again to get a data update?

**Comment by Engazan** [comment]
> Wouldn't you need to call `setFlatListData` again to get a data update?

ahh got it i need to listen to ```getInvoicesResult.isFetching``` in ``useEffect`` hook

Thanks this worked, i was little confused cuz "isLoading" not changed :/ somehow i missed "isFetching" from docs, thanksss again :)

**Comment by phryneas** [comment]
Honestly, the real problem is your use of `useLazyQuery` here. 

Use `useQuery`, throw away all of your `useEffect` calls and your `setFlatListData` local component state and compute derived state in a `useMemo` instead.

**Comment by phryneas** [comment]
You don't even need a `useMemo`, you are just way overcomplicating things.

Here is a clean solution:  https://snack.expo.dev/_QOlZiw3c

Rule of thumb: if you have a `useEffect` that calls a `useLazyQuery`, there's a 98% chance you shouldn't do that.

**Comment by Engazan** [comment]
yup i tried use it but required param "**uuid**" sometimes doesnt exist, that param get filled with user interaction thats why i need control over it and dont want fire it every time that my component get mounted, but listening to "isFetching" helped however i blocked my self from my own server cuz i made infinite loop and sent 5000+ requests ... its kindof dangerous, it needed few if check and it works :), thanks a lot

**Comment by phryneas** [comment]
Even then, this belongs in a click handler and **never** into a `useEffect`, and you should never have that `useState` setter for the derived value.

You can even avoid the `useLazyQuery` by using a `useState`:

```js
const [uuid, setUuid] = useState(null);

const getInvoicesResult = ApiReducer.endpoints?.getInvoices.useQuery(
  uuid
    ? {
        uuid,
      }
    : skipToken
);
```
