### ISSUE TITLE
Cannot refetch a query that has not been started yet

### ISSUE THREAD

**Issue by Ashraful-Mijan** [reduxjs/redux-toolkit#3834]
I initiate it like this ` const {refetch} = useGetMeQuery(null, {skip: true});`
and then use it when a function is called such as `const handleSubmit = async (e) => {
    const res = await login({ email, password });
    refetch()
  };`
![error1](https://github.com/reduxjs/redux-toolkit/assets/76747174/b117b7de-7f64-4b6f-b173-a6f8afed8ee0)
 If there is a need for more details code then I will share it.

**Comment by markerikson** [comment]
Can you provide a CodeSandbox, repo, or Replay ( https://replay.io/record-bugs ) that reproduces the issue?  This isn't anything we can work with.  Closing until there's a reproduction.
