### ISSUE TITLE
Typing issue for actions without payload created with `createSlice`

### ISSUE THREAD

**Issue by devniel** [reduxjs/redux-toolkit#3847]
Hello,

When creating a simple action with no payload via the `reducers` object of `createSlice`, Typescript gives an error stating that an argument is missing. A workaround is to use the `createAction` method.

```ts
const profileSlice: Slice<ProfileState> = createSlice({
  name: "profile",
  initialState,
  reducers: {
    clickPinLocationTool(state) {
      state.map.status = 'SELECTING_LOCATION';
    },
```

![image](https://github.com/reduxjs/redux-toolkit/assets/1231888/3eaabd20-5c73-49de-b488-da05facf7536)

Do you know how to resolve it? If it's not covered yet, maybe I can open a PR. Thanks !

**Comment by markerikson** [comment]
That _should_ work correctly. Do you have `strict: true` defined in your `tsconfig.json`?
