### ISSUE TITLE
[Question / Feature] Pick certain fields only

### ISSUE THREAD

**Issue by julien-tricent** [reduxjs/redux-toolkit#3851]
Hey!

I have a question that could be a feature request.
So I have a backend API which allows me to request only certain fields of a model. Something like this.

```typescript
@GET('/endpoint')
function get(request): Promise<Partial<MyModel>> {
  if (!('fields' in request.params)) return myModelRepository.all()
  return myModelRepository.all().select(fields)
}
```

I would like to know if I can override the BaseQuery in some way that if I provide the fields parameter, it maps the data type as `Pick<MyModel, fields>` 

```typescript
// here data would be typed as Array<Pick<MyModel, 'foo' | 'bar'>>
const { data } = useEndpointQuery({ fields: ['foo', 'bar'] }) 
```

If it can not be done in anyway at the moment, it could be a nice feature to have !

**Comment by phryneas** [comment]
Are you maybe looking for `selectFromResult` as shown in the examples [here](https://redux-toolkit.js.org/rtk-query/usage/queries#selecting-data-from-a-query-result)?

**Comment by julien-tricent** [comment]
@phryneas Thanks for the reply. Unfortunately this is not what I'm looking for.
I don't need to select specific data or apply any logic on it.

I am fetching dynamically structured data based on the fields provided to the request.
Since we know which property we are requesting, I thought it could nice to have the data properly typed

**Comment by EskiMojo14** [comment]
it's not possible for RTKQ to do this due the complex type mapping it needs to do between the endpoint definitions and final hooks.

you could maybe make a custom hook wrapper to cast the end result:
```ts
function getPickedData<Fields extends Array<keyof MyModel>>(fields: Fields) {
  const { data } = useEndpointQuery({ fields });
  return data as Pick<MyModel, Fields[number]> | undefined
}
```
