### ISSUE TITLE
rtk-query-codegen-openapi: circular reference definition

### ISSUE THREAD

**Issue by yizumi1012xxx** [reduxjs/redux-toolkit#3854]
An error occurs when generating a client for a definition that includes the following schema.
(schema has circular reference)
```yaml
    CategoryDto:
      type: object
      properties:
        parent:
          type: string
        sub:
          type: array
          items:
            $ref: '#/components/schemas/CategoryDto'
        id:
          type: string
        title:
          type: string
```

1.0.0 don't occur error, but 1.1.3 occur following error.
```txt
RangeError: Maximum call stack size exceeded
    at [Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at /Users/y.izumi/workspace/karakuri-web/node_modules/oazapfts/src/codegen/generate.ts:129:29
    at Array.map (<anonymous>)
    at refPathToPropertyPath (/Users/y.izumi/workspace/karakuri-web/node_modules/oazapfts/src/codegen/generate.ts:129:6)
    at ApiGenerator.resolve (/Users/y.izumi/workspace/karakuri-web/node_modules/oazapfts/src/codegen/generate.ts:322:18)
    at ApiGenerator.checkSchemaOnlyMode (/Users/y.izumi/workspace/karakuri-web/node_modules/oazapfts/src/codegen/generate.ts:781:41)
    at ApiGenerator.checkSchemaOnlyMode (/Users/y.izumi/workspace/karakuri-web/node_modules/oazapfts/src/codegen/generate.ts:794:16)
    at /Users/y.izumi/workspace/karakuri-web/node_modules/oazapfts/src/codegen/generate.ts:808:14
    at Array.some (<anonymous>)
```

**Comment by markerikson** [comment]
This is an issue with the upstream `oazapfts` lib - can you file or look for an issue there? Thanks!

**Comment by milotoor** [comment]
For what it's worth, this used to work with version 1.0 of `@rtk-query/codegen-openapi`. I imagine it has to do with [this commit](https://github.com/reduxjs/redux-toolkit/commit/acca228c) which switched from using the `@rtk-query/oazapfts-patched` package to "updated `oazapfts`".

**Comment by milotoor** [comment]
More helpfully, here's a [bug report](https://github.com/oazapfts/oazapfts/issues/507) in the `oazapfts` repo which looks to be the same as the one reported here. A commenter in that thread said they think the issue will be addressed in [this PR](https://github.com/oazapfts/oazapfts/pull/489), which will hopefully be merged in another week or two.

**Comment by milotoor** [comment]
I'm sorry to report to that the release in 4.10.1 does not resolve my problem, though it does lead to new undesirable behavior. Instead of erroring with a "Maximum call stack size exceeded" message it now just hangs and never completes. Running the codegen script took about 2.5 seconds on `@rtk-query/codegen-openapi@1.0` and is still running after 10 minutes using `@rtk-query/codegen-openapi@1.2` with `oazapfts@4.10.1`.
