### ISSUE TITLE
middleware type error 2.0.0-beta.4

### ISSUE THREAD

**Issue by rolanday** [reduxjs/redux-toolkit#3856]
Hello,

Needing to use 2.0 beta builds because I build for esm, and `2.0.0-beta.4` is producing type error. Pulled my hair out trying to resolve, then tried latest 1.x ver and no more type error (but fails at runtime). 2.0.0-beta.1 working for me though.

Using code sample straight from getting started docs:

https://redux-toolkit.js.org/tutorials/rtk-query

```
import { configureStore } from '@reduxjs/toolkit'
// Or from '@reduxjs/toolkit/query/react'
import { setupListeners } from '@reduxjs/toolkit/query'
import { pokemonApi } from './services/pokemon'

export const store = configureStore({
  reducer: {
    // Add the generated reducer as a specific top-level slice
    [pokemonApi.reducerPath]: pokemonApi.reducer,
  },
  // Adding the api middleware enables caching, invalidation, polling,
  // and other useful features of `rtk-query`.
  middleware: (getDefaultMiddleware) => // <==================== type error 
    getDefaultMiddleware().concat(pokemonApi.middleware),
})

// optional, but required for refetchOnFocus/refetchOnReconnect behaviors
// see `setupListeners` docs - takes an optional callback as the 2nd arg for customization
setupListeners(store.dispatch)
```

**Comment by markerikson** [comment]
What _specific_ TS error are you getting?

**Comment by rolanday** [comment]
Hi @markerikson , thanks for the quick response. The type error was a real mouthful. I couldn't repro the issue w/ a fresh project I was going to send, so I reset my node_modules folder and all is well now (it's a prototyping project so sees a lot of thrash). Thanks again! I'll go ahead and close this out.
