### ISSUE TITLE
`@rtk-query/codegen-openapi` missing dependencies

### ISSUE THREAD

**Issue by ondra-rejnek** [reduxjs/redux-toolkit#3857]
I am trying to run `@rtk-query/codegen-openapi` in my repository. Providing `openapi-config.ts` as TS file. Ends up with `Encountered a TypeScript configfile, but neither esbuild-runner nor ts-node are installed`. Both dependencies are installed tho. I am on MacOS (13.3.1 (22E261)), using zsh terminal

**Comment by dylmye** [comment]
I get this too running `npx @rtk-query/codegen-openapi <file-name>.ts`. Installing `esbuild-runner`/`ts-node` has no effect because of how npx works. I also tried `yarn rtk-query-codegen-openapi <file-name>.ts` and `node ./node_modules/@rtk-query/codegen-openapi/lib/bin/cli.js <file-name>.ts`. This is from a fresh install - anything I'm missing?

**Comment by dylmye** [comment]
Ah - found you need to install ts-node if you're providing a ts/tsx file.
So do what you did before: `yarn rtk-query-codegen-openapi <file-name>.ts`
but also install ts-node: `yarn add -D ts-node`
this should be in the docs

**Comment by ondra-rejnek** [comment]
I solved it also by installing `ts-node` as dev dependency. New error, however, arised. `RangeError: Maximum call stack size exceeded`. Locally, my node installation has access to 8GB of memory.

**Comment by Morozzko** [comment]
same problem, after updating npm to 10.2.4 its stop worked for me

**Comment by Erwol** [comment]
We ran into the same issue and figured out this error is only thrown with `node@20`. Using `node@17` `npx @rtk-query/codegen-openapi ...` works fine.

**Comment by sergeymakoveev** [comment]
node 16 - work fine, node 18 - error

**Comment by markerikson** [comment]
W just shipped a preview with a lot of updates to the build config that should hopefully improve things. https://github.com/reduxjs/redux-toolkit/releases/tag/%40rtk-query%2Fcodegen-openapi%402.0.0-alpha.0 - please try it out and let us know if it works!

**Comment by abbottdev** [comment]
Seems to be an issue again w/ node 22 :D

**Comment by dabi-vm** [comment]
same problem on:
macos 15.6.1
bun 1.2.21
node 20.15.1

npx works but when i installed these package as dev dependency: "ajv": "^8.17.1"
