### ISSUE TITLE
[Feature/codegen] Add `mergeReadWriteOnly` parameter

### ISSUE THREAD

**Issue by julien-tricent** [reduxjs/redux-toolkit#3859]
Hey,

Currently, the code generation splits readOnly and writeOnly types. I can see that oazapfts has an option `--mergeReadWriteOnly`  which merge readOnly and writeOnly types.

Please could you add this parameter in the config ? I'd like to be able to control wether or not I want to split my types

Thank you!

**Comment by phryneas** [comment]
Thanks! Will be released in a few minutes as 1.2.0.

**Comment by juliengbt** [comment]
@phryneas Yes I am (professional / personal accounts). Thank you for the quick response I am grateful for that !
