### ISSUE TITLE
setting up redux toolkit with Next 14.0.1

### ISSUE THREAD

**Issue by Nmncoded** [reduxjs/redux-toolkit#3865]
<img width="1470" alt="Screenshot 2023-11-11 at 9 43 37 AM" src="https://github.com/reduxjs/redux-toolkit/assets/92997264/d35eb913-6401-49f7-aa82-2bee52cf51f2">

**Comment by Nmncoded** [comment]
****/layout.tsx**
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import Sidebar from '@/components/sidebar'
import { Provider } from 'react-redux';
import {store} from '../store';

const inter = Inter({ subsets: ['latin'] });

type ReduxProviderProps = {
  children: React.ReactNode;
};

function ReduxProvider({ children }: ReduxProviderProps) {
  return <Provider store={store}>{children}</Provider>;
}

export const metadata:Metadata = {
  title: 'Kanban-board',
  description: 'kanban-board app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ReduxProvider >
      <body className="min-w-full min-h-screen bg-blue-100">
        <Header />
        <Sidebar />
        <main className='pl-40 pt-24' >
        {children}
        </main>
      </body>
      </ReduxProvider>
    </html>
  )
}

**Comment by markerikson** [comment]
You can't render `<Provider>` in a Server Component.  You can only use hooks in Client Components, and the React-Redux `<Provider>` uses hooks internally.  So, it needs to go into a Client Component instead.
