### ISSUE TITLE
Calling toString on actionCreator does not return action type in ^v2.0.0-alpha.4

### ISSUE THREAD

**Issue by radekmikeska** [reduxjs/redux-toolkit#3871]
What's up, guys. I was not able to get working `1.9.7` version in my ES modules Node.js repo. Switched to `^v2.0.0-alpha.4`, importing from esm works well. Unfortunately, calling toString on action creator suddenly returns the action creator function, not the action type.

**Comment by EskiMojo14** [comment]
This is an intentional removal (see https://github.com/reduxjs/redux-toolkit/issues/3370 for an explanation of why).
In general you should prefer .match where applicable or if you really need the type string, use .type.

Out of curiosity, where were you using the toString functionality?

**Comment by radekmikeska** [comment]
redux-saga:
`const chan = yield actionChannel(myActionCreator, buffers.expanding());`

**Comment by EskiMojo14** [comment]
gotcha - i believe we would advise doing `const chan = yield actionChannel(myActionCreator.match, buffers.expanding());`
in some cases that would provide better type narrowing as .match acts as a type guard

**Comment by EskiMojo14** [comment]
fwiw we're not entirely set on removing the toString override, but we haven't found any situations where it wouldn't be better to use .match or .type explicitly

**Comment by EskiMojo14** [comment]
hey there - just a heads up that as per https://github.com/reduxjs/redux-toolkit/issues/3876 we've decided to re-add the override. Removing it entirely was a bit too hasty, we'll instead encourage other approaches via the docs (likely a new style guide entry/note on migration).
