### ISSUE TITLE
Reselect final pieces

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#3899]
Putting this here for bookkeeping purposes:

- [x] Merge updated README for 5.0
- [x] New Reselect docs site?
- [x] Nail down the `defaultMemoize` vs `weakMapMemoize` question
- [x] Check on `weakMapMemoize` memory leak concerns

**Comment by aryaemami59** [comment]
Docs should be done within the next few days, then we can look into `weakMapMemoize` and perhaps if time allows look into `autotrackMemoize` 's stability issues.
