### ISSUE TITLE
Incorrect types in enhanceEndpoints with transformResponse

### ISSUE THREAD

**Issue by khmilevoi** [reduxjs/redux-toolkit#3901]
Codesandbox: https://codesandbox.io/s/redux-toolkit-rtk-query-forked-6plwhy?file=/src/services/pokemon.ts

Somebody had already fixed similar issues, but it was still a problem. 

Actual behavior:
When you add transformResponse to enhanceEndpoints, ResultType doesn't change according to transformResponse ReturnType.

Expected behavior:
ResultType should be matched with transformReposponse ReturnType.

Version: 1.9.7

**Comment by EskiMojo14** [comment]
see https://github.com/reduxjs/redux-toolkit/pull/2953 - the mechanism for overriding resulttype for enhanced endpoints is finicky.

currently you need to do a lot of manual work:
```ts
import type {
  DefinitionsFromApi,
  OverrideResultType,
  TagTypesFromApi
} from "@reduxjs/toolkit/dist/query/endpointDefinitions";
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const pokemonApi = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: "https://pokeapi.co/api/v2/" }),
  endpoints: (builder) => ({
    getPokemonByName: builder.query<object, string>({
      query: (name: string) => `pokemon/${name}`
    })
  })
});

type TagTypes = TagTypesFromApi<typeof pokemonApi>;
type Definitions = DefinitionsFromApi<typeof pokemonApi>;

type UpdatedGetPokemonByName = OverrideResultType<
  Definitions["getPokemonByName"],
  number
>;

type FinalDefinitions = Omit<Definitions, "getPokemonByName"> &
  UpdatedGetPokemonByName;

// Export hooks for usage in functional components
export const { useGetPokemonByNameQuery } = pokemonApi.enhanceEndpoints<
  TagTypes,
  FinalDefinitions
>({
  endpoints: {
    getPokemonByName: {
      transformResponse: (): number => 1
    }
  }
});
```

In order to better support this, we would need to take more drastic (breaking) changes to enhanceEndpoints (see https://github.com/reduxjs/redux-toolkit/pull/3485 for what that might look like)
