### ISSUE TITLE
RangeError: Maximum call stack size exceeded for bigger api schema

### ISSUE THREAD

**Issue by vladinko0** [reduxjs/redux-toolkit#3907]
I am running `npx @rtk-query/codegen-openapi ./src/store/openapi-config.ts`

My **openapi-config.ts**:

```
import type { ConfigFile } from "@rtk-query/codegen-openapi";
const config: ConfigFile = {
  schemaFile: "https://beapi.com/user/v3/api-docs",
  apiFile: "./emptyApi.ts",
  apiImport: "emptySplitApi",
    outputFile: "./petApi.ts",
  exportName: "petApi",
  hooks: true,
  tag: true,
};

export default config;
```

Result:

> RangeError: Maximum call stack size exceeded
>     at [Symbol.replace] (<anonymous>)
>     at String.replace (<anonymous>)
>     at prj123/node_modules/oazapfts/src/codegen/generate.ts:129:29
>     at Array.map (<anonymous>)
>     at refPathToPropertyPath (prj123/node_modules/oazapfts/src/codegen/generate.ts:129:6)
>     at ApiGenerator.resolve (prj123/node_modules/oazapfts/src/codegen/generate.ts:322:18)
>     at ApiGenerator.checkSchemaOnlyMode (prj123/node_modules/oazapfts/src/codegen/generate.ts:781:41)
>     at ApiGenerator.checkSchemaOnlyMode (prj123/node_modules/oazapfts/src/codegen/generate.ts:794:16)
>     at prj123/node_modules/oazapfts/src/codegen/generate.ts:808:14
>     at Array.some (<anonymous>)
> error Command failed with exit code 1.

Interesting thing is that `rtk-incubator/rtk-query-codegen-openapi` has no problem with the same API schema.

**Comment by markerikson** [comment]
@vladinko0 this looks like an issue with the upstream `oazapfts` library - could you file an issue there? Thanks!

(the difference here would be that the alpha `rtk-incubator` package used a much earlier version of `oazapfts`, so the behavior has changed on that side at some point.)
