### ISSUE TITLE
Custom reconciling in `extractRehydrationInfo`

### ISSUE THREAD

**Issue by nevnein** [reduxjs/redux-toolkit#3914]
Currently, `extractRehydrationInfo` is a black box receiving just the action and the reducer path. This makes it impossible to do even simple logic to reconcile the two states of the queries, here's a simple scenario
1. the hydration action is called with data A, now the query contains fresh data A
2. the query is refreshed, now the query contains fresh data B
3. the hydration action is called with data A again, now stale A has overwritten fresh B

Maybe I'm missing something, but right now there's no way to reconcile in a custom way to avoid scenarios like the one described above.

**Comment by phryneas** [comment]
Usually you'd rehydrate your Redux store before you even made the first request, so your store would be empty. Am I missing something here?

**Comment by nevnein** [comment]
> Usually you'd rehydrate your Redux store before you even made the first request, so your store would be empty. Am I missing something here?

That's not the case for next-redux-wrapper: an HYDRATE action is dispatched roughly at every page change, see https://github.com/kirill-konshin/next-redux-wrapper#state-reconciliation-during-hydration

**Comment by nevnein** [comment]
> RTKQ does not provide an opinion on _how_ to hydrate. 

Well, it actually does though, see https://redux-toolkit.js.org/rtk-query/usage/server-side-rendering#server-side-rendering-with-nextjs

> Here is an example of a userland hydration that doesn't blow away fresher data.
> 
> This is code ripped from my own codebase. I believe it is generally relevant and can be re-purposed.
> 
> ```ts
> import { QueryStatus } from "@reduxjs/toolkit/query";
> 
> import type { AppDispatch, RootState } from "..";
> 
> export const hydrateThunk =
>   (preloadedState: RootState["cache"]) => (dispatch: AppDispatch, getState: () => RootState) => {
>     const state = getState().cache;
>     return dispatch({
>       type: "hydrate",
>       payload: {
>         ...preloadedState,
>         mutations: {},
>         queries: Object.entries(preloadedState.queries).reduce(
>           (acc: typeof preloadedState.queries, [key, newEntry]) => {
>             const currentEntry = state?.queries?.[key];
>             /** do not rehydrate entries that were currently in flight. */
>             const newEntryResolved =
>               newEntry?.status === QueryStatus.fulfilled ||
>               newEntry?.status === QueryStatus.rejected;
>             /** do not upsert already fulfilled entries */
>             const currentEntryUnresolved = currentEntry?.status !== QueryStatus.fulfilled;
>             /** unless they are stale */
>             const currentEntryIsOlder =
>               (currentEntry?.fulfilledTimeStamp ?? 0) <= (newEntry?.fulfilledTimeStamp ?? 0);
> 
>             if (newEntryResolved && (currentEntryUnresolved || currentEntryIsOlder)) {
>               acc[key] = newEntry;
>             }
> 
>             return acc;
>           },
>           {}
>         ),
>       },
>     });
>   };
> ```

So I guess I should add an extra reducer and manually reconcile when the next-redux-wrapper HYDRATE action is dispatched, totally disregarding `extractRehydrationInfo`?

**Comment by bever1337** [comment]
Please see the logic for yourself: https://github.com/reduxjs/redux-toolkit/blob/cf2441945d29c0fe263a9cffa103f6b33ebcd7b3/packages/toolkit/src/query/core/buildSlice.ts#L251

1. Every action that is dispatched to redux is passed to `extractRehydrationInfo`
2. If `extractRehydrationInfo` returns a non-nullish value, RTKQ will attempt to hydrate
Caveat: RTKQ only hydrates queries that are fulfilled OR rejected

If the developer would like to fine-tune the rehydration data, that is fully-controllable within `extractRehydrationInfo`. In my example, I used a thunk so I could also have access to the `getState` API.

**Comment by bever1337** [comment]
Full example of statefully narrowing down hydration data:

```ts
import { createApi, fetchBaseQuery, QueryStatus } from "@reduxjs/toolkit/query";

export const hydrateThunk = (preloadedState) => (dispatch, getState) => {
  const state = getState().cache;
  return dispatch({
    type: "hydrate",
    payload: {
      ...preloadedState,
      mutations: {},
      queries: Object.entries(preloadedState.queries).reduce((acc, [key, newEntry]) => {
        const currentEntry = state?.queries?.[key];
        /** do not rehydrate entries that were currently in flight. */
        const newEntryResolved =
          newEntry?.status === QueryStatus.fulfilled || newEntry?.status === QueryStatus.rejected;
        /** do not upsert already fulfilled entries */
        const currentEntryUnresolved = currentEntry?.status !== QueryStatus.fulfilled;
        /** unless they are stale */
        const currentEntryIsOlder =
          (currentEntry?.fulfilledTimeStamp ?? 0) <= (newEntry?.fulfilledTimeStamp ?? 0);

        if (newEntryResolved && (currentEntryUnresolved || currentEntryIsOlder)) {
          acc[key] = newEntry;
        }

        return acc;
      }, {}),
    },
  });
};

export const api = createApi({
  baseQuery: fetchBaseQuery({}),
  endpoints() {
    return {};
  },
  extractRehydrationInfo(action) {
    if (action.type === "hydrate") {
      return action.payload;
    }
    return null;
  },
  reducerPath: "cache",
  tagTypes: [],
});

```

**Comment by phryneas** [comment]
I fear there isn't too much we *can* do, as the server and client can have wildly different timestamps - so there is no reliable way to always find out if the server data is newer or older. 
I think the base assumption we had when we added this was that if the server sends data for rehydration, you can always assume that it will be up-to-date the moment it's sent, and not stale, old data.

If that's not the case, you'll have to find *some* additional logic you manually apply.
