### ISSUE TITLE
1.3.0-alpha feedback for createAsyncThunk 

### ISSUE THREAD

**Issue by ph3b** [reduxjs/redux-toolkit#392]
Thank you for this project and great progress on 1.3.0! `createAsyncThunk` and `createEntityAdapter` are really useful and completes the "missing pieces" for me in terms of features I would need from a toolkit like this, great work!

I have two points of feedback/questions for `createAsyncThunk` in the current alpha-branch:

1. The native `AbortController` seems to be unsupported in Node.js-environment (non-browser). This is obviously an issue for SSR-environments. Could we use a polyfill such as [abortcontroller-polyfill](https://www.npmjs.com/package/abortcontroller-polyfill)? [Relevant code](https://github.com/reduxjs/redux-toolkit/blob/v1.3.0-integration/src/createAsyncThunk.ts#L150).

2. Typescript: Add/generate action typings for action-handlers in extraReducers that where generated by createAsyncThunk(

Consider the following async thunk:
```ts
const fetchUsers = createAsyncThunk<{ data: User[], page: number }>("users/fetch", async () => {
  const result = await usersApi.fetch();
  return {
      data: result.data,
      page: result.page
  }
})
```
When handling the dispatched actions from this thunk we add an entry for the action we want to handle in the extraReducers object:

```ts
const userSlice = createSlice({
  name: "users",
  initialState: { users: [], page: 0 },
  extraReducers: {
    [fetchUsers.fulfilled.type]: (state, action /* `action` is not typesafe */ ) => {          
         // Set state here
    },
    [fetchUsers.pending.type]: (state, action /*  `action` is not typesafe */ ) => {          
         // Set state here
    },
    [fetchUsers.rejected.type]: (state, action /* `action` is not typesafe */ ) => {          
         // Set state here
    }
  }
})
```

My impression is that the reducer handler has no way of knowing the return type from fetchUsers.fulfilled/pending/rejected because it is added by `.type` (string).

We can make it slightly better by manually adding the type but it is still error-prone:
```ts
 [fetchUsers.fulfilled.type]: (state, action: ReturnType<typeof fetchUsers.fulfilled>) => {          
         // Set state here
    }
```
Ideally redux-toolkit would automatically provide typings for the payload/action returned. I don't really have a suggestion for how to do this. I guess it will
be hard to achieve this using plain `extraReducer`-objects but it might be possible using the `builder`-api?

**Comment by phryneas** [comment]
> Thank you for this project and great progress on 1.3.0! `createAsyncThunk` and `createEntityAdapter` are really useful and completes the "missing pieces" for me in terms of features I would need from a toolkit like this, great work!

Heya :wave: thanks for the feedback and trying out the alpha!

> I have two points of feedback/questions for `createAsyncThunk` in the current alpha-branch:
> 
>     1. The native `AbortController` seems to be unsupported in Node.js-environment (non-browser). This is obviously an issue for SSR-environments. Could we use a polyfill such as [abortcontroller-polyfill](https://www.npmjs.com/package/abortcontroller-polyfill)? [Relevant code](https://github.com/reduxjs/redux-toolkit/blob/v1.3.0-integration/src/createAsyncThunk.ts#L150) [](/reduxjs/redux-toolkit/blob/HEAD@{2020-02-24T09:33:17Z}/src/createAsyncThunk.ts#L150).

`import 'abortcontroller-polyfill/dist/abortcontroller-polyfill-only'`
should work for you. Please report back if it does.

But you bring up a very good point. I didn't think about the node environment when dismissing this as "developers for IE are already adding a bunch of polyfilles".

So @markerikson, what do you think about shipping a "stub" AbortController that satisfies the relevant interfaces and prints errors in development, possibly even pointing users to a relevant polyfill?
Shouldn't be more than a few lines.

>     2. Typescript: Add/generate action typings for action-handlers in extraReducers that where generated by createAsyncThunk(

You can use the [builder callback](https://deploy-preview-374--redux-starter-kit-docs.netlify.com/usage/usage-with-typescript#type-safety-with-extrareducers) style for extraReducers, that will do exactly what you want.

**Comment by ph3b** [comment]
> import 'abortcontroller-polyfill/dist/abortcontroller-polyfill-only'
> should work for you. Please report back if it does.

Perfect! I'll give this a try and report back!

> You can use the builder callback style for extraReducers, that will do exactly what you want.

I completely missed this while reading the docs 🤦‍♂. This is exactly what I need! - Thank you.

**Comment by markerikson** [comment]
@phryneas yeah, I'd wondered about AbortController support.  Can you put that stub in?

**Comment by markerikson** [comment]
We've got the `AbortController` stub in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.3.0-beta.0 , so this should be resolved now.
