### ISSUE TITLE
v2.0.0-rc.2 inundates console with warnings from runIdentityFunctionCheck

### ISSUE THREAD

**Issue by christopherschroer** [reduxjs/redux-toolkit#3930]
v2.0.0-rc.2 inundates consoles with warnings from [runIdentityFunctionCheck](https://github.com/reduxjs/reselect/blob/master/src/devModeChecks/identityFunctionCheck.ts). This is evident in the console output for the tests that were ran as part of #3928 (https://github.com/reduxjs/redux-toolkit/actions/runs/7055909073/job/19207110065)

**Comment by markerikson** [comment]
@christopherschroer yeah, try using the CSB build from that PR:

```
# yarn 1
yarn add https://pkg.csb.dev/reduxjs/redux-toolkit/commit/f3736dc5/@reduxjs/toolkit
# yarn 2, 3
yarn add @reduxjs/toolkit@https://pkg.csb.dev/reduxjs/redux-toolkit/commit/f3736dc5/@reduxjs/toolkit/_pkg.tgz 
# npm
npm i https://pkg.csb.dev/reduxjs/redux-toolkit/commit/f3736dc5/@reduxjs/toolkit
```

We'll get out another RTK RC later today, along with a tweak to Reselect to include a stack trace.
