### ISSUE TITLE
RTKQ: Uncaught SyntaxError Unexpected token / missing : after property id

### ISSUE THREAD

**Issue by dimonik** [reduxjs/redux-toolkit#3932]
### Problem

Code below is throwing very strange error:
(CHROME) Uncaught SyntaxError: Unexpected token '>'
(FIREFOX) Uncaught SyntaxError: missing : after property id
both pointing to the line where 'getUserById' key is defined. **Cant get any clue what is the reason..**

```
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"
import { API_URL, API_KEY } from "../constants/apiconfig"
import { FakeUserT, FakeUsersT } from "../types/FakeUserT"

export const backendAPI = createApi({
  reducerPath: "backendAPI",
  baseQuery: fetchBaseQuery({ baseUrl: API_URL }),
  endpoints: (build) => ({

    getUserById: build.query<FakeUserT, string>({
      query: (id) => `/users/${id}`, //test URL https://jsonplaceholder.typicode.com/users/3
    }),
  }),
})

// use RTKQ auto-generated React Hooks
export const { useLazyGetUserByIdQuery } = backendAPI

export const { getUserById } = backendAPI.endpoints
```

Later in my App component i use
```
import { FC } from "react"
import { useLazyGetUserByIdQuery } from "../services/apiService"

export const ApiTest1: FC = () => {
  const [trigger, { data, isLoading, isError, isSuccess }] =
    useLazyGetUserByIdQuery()

etc...
}
```

type definition:
```
export type FakeUserT = {
  id: string
  name: string
  username: string
  email: string
}

export type FakeUsersT = FakeUserT[]
```

### versions:
"@reduxjs/toolkit": "^1.9.7"
"react-redux": "^8.0.5",
"react": "^18.2.0",
"vite": "^4.0.0",

**Comment by markerikson** [comment]
Silly question: are you actually compiling the code properly?  That looks like it's a complaint about TS generic syntax in a JS file.

**Comment by dimonik** [comment]
> Silly question: are you actually compiling the code properly? That looks like it's a complaint about TS generic syntax in a JS file.

It helped, i forgot to add '.ts' to the file name..)
