### ISSUE TITLE
Add a "Contributor's Guide" document

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#394]
Looks like I never actually added any kind of a "Contributor's Guide" / `CONTRIBUTING.md`.  

Can someone copy over the `CONTRIBUTING.md` from either Redux or React-Redux, and modify it as appropriate for this repo?

**Comment by ryota-murakami** [comment]
@markerikson Oh I don't do anything too much at the time.
I'm going to create PR about `CONTRIBUTING.md`

**Comment by markerikson** [comment]
Looks like someone else opened one already:

#395

**Comment by ryota-murakami** [comment]
Thanks, that's enough.

**Comment by markerikson** [comment]
Done.
