### ISSUE TITLE
Typing for predicate for `isHydrateAction` without causing circular reference to `RootState`

### ISSUE THREAD

**Issue by harry-gocity** [reduxjs/redux-toolkit#3947]
Hello!

Firstly, congrats on the v2 release 🎉

Been upgrading one of our sites to RTK 2.0 this morning and came across a classic circular reference issue as I updated the action handling in our api slice's `extractRehydrationInfo`:

- In `store/api.ts`, we have a `const api = createApi({...})`
- In `store/index.ts`, we create a reducer with `const reducer = combineSlices(api)`, and define the store type with `type RootState = ReturnType<typeof reducer>`
-  In `store/api.ts`, my `api`'s `extractRehydrationInfo` uses a type predicate to determine `action is PayloadAction<???>`

I can't type my predicate with `PayloadAction<RootState>` as this causes a circular reference. [The docs suggest that the type would be inferred](https://redux-toolkit.js.org/rtk-query/api/createApi#extractrehydrationinfo) and use `any` but is there a better way I'm missing to give the `PayloadAction` the generic it needs?

If this was a `createSlice({ name: 'foo', ... })` I'd use a partial like `PayloadAction<{ foo: FooState }>`, but obviously the state is much more complex with `createApi` and I don't see a clean way to do the same with the generic `CreateApi` type 🤔

**Comment by EskiMojo14** [comment]
ah, you're right - the docs example would cause a circular type ☹️ 

i guess you would have to manually annotate the return type as `any` to avoid that - that way *inside* the function you still have the necessary type safety.

will open a PR to get the docs fixed

**Comment by programm-ingovals** [comment]
Isn't the same true [here](https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery#setting-default-headers-on-requests)

Even though it is just an `import type` so it shouldn't cause issues, or what? My linter screams at me at least.

BaseQuery fetches RootState from Store
ApiReducer uses BaseQuery
Store uses ApiReducer
