### ISSUE TITLE
Function declarations are not allowed inside blocks in strict mode.

### ISSUE THREAD

**Issue by BerendPronkEndeavour** [reduxjs/redux-toolkit#3949]
Currently I am updating some packages, including all Redux related ones. This is the status:
- `@reduxjs/toolkit` from `^1.9.5` to `^2.0.1`
- `react-redux` from `^8.0.5` to `^9.0.1`
- `redux-thunk` from `^2.4.2` to `3.1.0`

A few things needed to change, but I managed to solve most issues — thanks to the https://redux.js.org/usage/migrations/migrating-rtk-2 page. There is just one issue that remains, and it might have to do with my project setup, though I never received this notification before.

It says:
`Function declarations are not allowed inside blocks in strict mode when targeting 'ES3' or 'ES5'. Modules are automatically in strict mode.`

Here is the error in full.
![image](https://github.com/reduxjs/redux-toolkit/assets/123187048/b4e94909-19a5-4f6d-8585-276f16f09df9)

**Comment by markerikson** [comment]
That looks like it's a TS config issue.  Try bumping your TS target output?

- https://stackoverflow.com/questions/60557890/how-to-fix-error-ts1251-function-declarations-are-not-allowed-inside-blocks-in

Note that per our release notes, we do target modern JS syntax with this release (and this one isn't even a "syntax" issue per se).

**Comment by BerendPronkEndeavour** [comment]
Thanks for the quick response! My `tsconfig.json` looks as follows:

```
{
    "compilerOptions": {
        "target": "es5",
        "lib": [
            "dom",
            "dom.iterable",
            "esnext"
        ],
        "allowJs": false,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "downlevelIteration": true,
        "isolatedModules": true,
        "jsx": "react-jsx",
        "rootDir": "./src",
        "noEmit": true,
        "sourceMap": true,
        "noFallthroughCasesInSwitch": true
    },
    "include": [
        "./src"
    ],
    "exclude": [
        "./node_modules",
        "__tests__"
    ],
    "typeRoots": [
        "./src/types",
        "../types"
    ],
    "compileOnSave": true
}
```

It excludes the `node_modules` and other than that, if I set `strict` to `false`, it still gives me this error.
I understand this is a configuration issue on my end.

**Comment by markerikson** [comment]
Yeah, try bumping `"target"` to something newer than `"ES5"`.

**Comment by BerendPronkEndeavour** [comment]
That didn't seem to work either, unfortunately.

However, I tried removing `./` from `./node_modules` and this seems to work! Hopefully my blunder will help someone in the future.

Thanks for the quick replies, and enjoy the rest of your day.
