### ISSUE TITLE
Type mismatch when trying to use saga middleware in store

### ISSUE THREAD

**Issue by vivekvdwivedi** [reduxjs/redux-toolkit#3950]
I am trying to add saga middleware to redux store, but it appears to have a type mis-match. I am getting this error:

```
Type '(getDefaultMiddleware: GetDefaultMiddleware<{ auth: LoginState; }>) => Tuple<[SagaMiddleware<object>]>' is not assignable to type '(getDefaultMiddleware: GetDefaultMiddleware<{ auth: LoginState; }>) => Tuple<Middlewares<{ auth: LoginState; }>>'.
  Type 'Tuple<[SagaMiddleware<object>]>' is not assignable to type 'Tuple<Middlewares<{ auth: LoginState; }>>'.
    Type '[SagaMiddleware<object>]' is not assignable to type 'Middlewares<{ auth: LoginState; }>'.
      Type 'SagaMiddleware<object>' is not assignable to type 'Middleware<{}, { auth: LoginState; }, Dispatch<UnknownAction>>'.
        Types of parameters 'next' and 'next' are incompatible.
          Type 'unknown' is not assignable to type 'T'.
            'T' could be instantiated with an arbitrary type which could be unrelated to 'unknown'.ts(2322)
configureStore.d.ts(25, 5): The expected type comes from property 'middleware' which is declared here on type 'ConfigureStoreOptions<{ auth: LoginState; }, UnknownAction, Tuple<Middlewares<{ auth: LoginState; }>>, Tuple<[StoreEnhancer<{ dispatch: {}; }>, StoreEnhancer]>, { ...; }>'
```

Here is my store configuration

```
import { configureStore } from "@reduxjs/toolkit";
import createSagaMiddleware from "redux-saga";
import reducers from "./reducers";
import rootSaga from "./sagas";

const sagaMiddleware = createSagaMiddleware();

export const store = configureStore({
  reducer: reducers,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      thunk: false,
    }).concat(sagaMiddleware),
  devTools: true,
});

sagaMiddleware.run(rootSaga);
// Infer the `RootState` and `AppDispatch` types from the store itself
export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;

---------- STORE FILE ENDS HERE ---------

// SAGA - Code from another file, here it's just for reference

import { all } from "redux-saga/effects";
import authSaga from "../contexts/auth/saga";

export default function* rootSaga() {
  yield all([...authSaga]);
}

// ROOT REDUCER  - Code from another file, here it's just for reference
import authReducer from "../contexts/auth/slice";

const reducers = {
  auth: authReducer,
};

export default reducers;
```

Here are the version details:

"@reduxjs/toolkit": "^2.0.1",
"react": "^18.2.0",
"react-redux": "^9.0.1",
"redux-saga": "^1.2.3",

Any help as to how I can fix this and what is the root cause of this issue?

**Comment by vaoan** [comment]
Is there an example how to force redux saga into middleware v5? I'm kind of new to overrides...

**Comment by puvaasam** [comment]
1. Add below configuration in `package.json` file to override the version from v4 to v5 (parallel to dependencies node) 
2. Delete node_module and package-lock.json 
3. Install `npm i`

```
"dependencies": {
   .....
  },
  "overrides": {
    "redux-saga": {
      "@redux-saga/core": {
        "redux": "^5.0.0"
      }
    }
  },
```

**Comment by EskiMojo14** [comment]
We've now updated our migration guide with a section on [overriding dependencies](https://redux-toolkit.js.org/usage/migrating-rtk-2#overriding-dependencies).

**Comment by ilbrando** [comment]
This doesn't solve the type problem for me. The issue is that that redux-saga `createSagaMiddleware` returns a `SagaMiddleware<>` type and redux `applyMiddleware` expects a `Middleware` type.

**Comment by ilbrando** [comment]
@EskiMojo14 You are right. Maybe my override didn't work then. I will try again.

**Comment by Moumit** [comment]
This version **combination still working**, though latest installation has these issues. 
```
    "@reduxjs/toolkit": "^1.9.7",
    "react-redux": "^8.1.3",
    "redux-saga": "^1.2.3",
```

**Comment by markerikson** [comment]
@Moumit that doesn't help answer the question of how to get the _latest_ versions working :)

Per comments above, the best answer is to override any deps/peerDeps, and force the entire project to only use the latest version of `redux`.

**Comment by Lakston** [comment]
Applying the overrides as suggested here with

**Comment by Lakston** [comment]
Applying the overrides as suggested here with
```
    "@reduxjs/toolkit": "^2.0.1",
    "react-redux": "9.0.4",
    "redux-saga": "1.2.3",
```

```
  "overrides": {
    "redux-saga": {
      "@redux-saga/core": {
        "redux": "^5.0.0"
      }
    }
  },
```

still gets me a typescript error

```
const sagaMiddleware = createSagaMiddleware();

const store = configureStore({
  reducer: appReducer,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      thunk: false,
    }).concat(sagaMiddleware),
  devTools: true,
});
```

**Comment by Lakston** [comment]
The override does not work with

```
    "@reduxjs/toolkit": "^2.0.1",
    "react-redux": "9.0.4",
    "redux-saga": "1.2.3"
```

**Comment by sw7x** [comment]
redux-logger also have some types issues

Type '(getDefaultMiddleware: GetDefaultMiddleware<{ counter: CounterState; }>) => Tuple<[ThunkMiddleware<{ counter: CounterState; }, UnknownAction>, ...(Middleware<...> | Middleware<...>)[]]>' is not assignable to type '(getDefaultMiddleware: GetDefaultMiddleware<{ counter: CounterState; }>) => Tuple<Middlewares<{ counter: CounterState; }>>'.
  Type 'Tuple<[ThunkMiddleware<{ counter: CounterState; }, UnknownAction>, ...(Middleware<...> | Middleware<...>)[]]>' is not assignable to type 'Tuple<Middlewares<{ counter: CounterState; }>>'.
    Type '[ThunkMiddleware<{ counter: CounterState; }, UnknownAction>, ...(Middleware<...> | Middleware<...>)[]]' is not assignable to type 'Middlewares<{ counter: CounterState; }>'.
      Type 'Middleware<...> | Middleware<...> | ThunkMiddleware<{ ...; }, UnknownAction>' is not assignable to type 'Middleware<{}, { counter: CounterState; }, Dispatch<UnknownAction>>'.
        Type 'Middleware<{}, any, Dispatch<AnyAction>>' is not assignable to type 'Middleware<{}, { counter: CounterState; }, Dispatch<UnknownAction>>'.
          Types of parameters 'next' and 'next' are incompatible.
            Type 'unknown' is not assignable to type 'T'.
              'T' could be instantiated with an arbitrary type which could be unrelated to 'unknown'.ts(2322)

**Comment by markerikson** [comment]
@sw7x this issue is about `redux-saga` specifically.

Note that `redux-saga@1.3.0` is out and should fix the original complaints.

Also see https://redux-toolkit.js.org/usage/migrating-rtk-2#overriding-dependencies

**Comment by ChristopherHButler** [comment]
This override solution mentioned above does not seem to work with the following versions. Does anyone know if there is there anything else I could try? Happy to share more of my code or work together on a solution if it helps.

```json package.json
{
  "dependencies": {
      "@reduxjs/toolkit": "^2.2.5",
      "react-redux": "^9.1.2",
      "redux-saga": "^1.3.0",
  },
  "overrides": {
      "redux-saga": {
        "@redux-saga/core": {
          "redux": "^5.0.0"
        }
      }
    }
}

```
