### ISSUE TITLE
extraOptions - retryCondition - Property 'originalStatus' does not exist on type 'FetchBaseQueryError'.

### ISSUE THREAD

**Issue by renanloboz** [reduxjs/redux-toolkit#3952]
The current implementation of the retryCondition function references a property called originalStatus in the result object, which is not present in the current structure.
```
extraOptions: {
  retryCondition(result, _, { attempt }) {
    if (result.originalStatus >= 400 && attempt < 3) {
      return true;
    }
    return false;
  }
}
```

am I doing something wrong?

Environment:
Version: 1.8.5

**Comment by EskiMojo14** [comment]
[`originalStatus`](https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/fetchBaseQuery.ts#L74) is only available if `result.status` is `"PARSING_ERROR"` - you probably want to check `result.status` instead.
