### ISSUE TITLE
Next js 14 with RTK Query build error on vercel.

### ISSUE THREAD

**Issue by Ab-Qadir1998** [reduxjs/redux-toolkit#3960]
Hi,
I have a next js 14 application that uses RTK Query. Everything works fine in the local environment but when i deploy my app to vercel it throws the following error:
![image](https://github.com/reduxjs/redux-toolkit/assets/47755161/2a4a11a7-35bb-4f2e-9bcc-068b8a96a3d8)

TypeError: Cannot destructure property 'store' of 'useReduxContext(...)' as it is null.

Altough I create a file in app directory by using "use client" directive like this : 

"use client";

import { Provider } from "react-redux";
import store from "../redux/store";

const StoreProvider = ({ children }) => {
  return <Provider store={store}>{children}</Provider>;
};

export default StoreProvider;

and wrapping like this in my layout.js file : 

<StoreProvider>
        <body>
          {loading ? (
            <ConfigProvider
              theme={{
                token: {
                  colorPrimary: "#052148",
                  fontFamily: "var(--poppins-font)",
                },
              }}
            >
              <main>{children}</main>
            </ConfigProvider>
          ) : (
            <PreLoader />
          )}
        </body>
      </StoreProvider>

Here is my dependency structure:

![image](https://github.com/reduxjs/redux-toolkit/assets/47755161/6f4724ea-ee43-4006-b4c2-5228ac8a3cd1)

How to solve this

**Comment by markerikson** [comment]
The error message suggests that something about the Provider setup is incorrect, but I don't know what, and there's not much we can to do help without a specific project to look at.

**Comment by Ab-Qadir1998** [comment]
Everything is working fine in my local development environment and there's no such error. The problem I am facing only when deploying on the server
