### ISSUE TITLE
endpointDefinitions not exported from @reduxjs/toolkit/query

### ISSUE THREAD

**Issue by zudenkovas** [reduxjs/redux-toolkit#3964]
Hello I am using some types from `endpointDefinitions` to define `transformedResponse `return type in my endpoint enhancing, the problem is that after updating  `@reduxjs/toolkit` to version 2.0.1 I am not able to import them from `@reduxjs/toolkit/query`, and this url is deepest I am allowed to go down the tree.

`"@reduxjs/toolkit": "^2.0.1",`

```
import {
  DefinitionsFromApi,
  OverrideResultType,
  TagTypesFromApi
} from '@reduxjs/toolkit/query';
```

**Comment by markerikson** [comment]
Can you show how (and why) you're using that type?

**Comment by KasimAhmic** [comment]
I'm experiencing the same exact issue when trying to enhance a codegened API.

If it helps in the interim, setting `moduleResolution` to `Node` in your `tsconfig.json` allows you to do a deeper import like I'm doing below. Vite sets it to `Bundler` by default starting with [Vite 5 as Rollup 4 requires it](https://vitejs.dev/guide/migration#rollup-4) so it probably makes sense to export the type.

```typescript
import { EntityState, createEntityAdapter } from '@reduxjs/toolkit';
import { DefinitionsFromApi, OverrideResultType } from '@reduxjs/toolkit/dist/query/endpointDefinitions';

import { FindAllCatsApiResponse, Cat, baseApi } from './base-api';

type Definitions = DefinitionsFromApi<typeof baseApi>;
type TagTypes = (typeof tags)[number];

type UpdatedFindAllCatsDef = OverrideResultType<
  Definitions['findAllCats'],
  EntityState<Cat, number>
>;

type UpdatedDefinitions = Omit<Definitions, 'findAllCats'> & {
  findAllCats: UpdatedFindAllCatsDef;
};

const tags = ['cats'] as const;

export const catsAdapter = createEntityAdapter<Cat, number>({
  selectId: (entity) => entity.id,
  sortComparer: (a, b) => a.createdOn - b.createdOn,
});

export const animalApi = baseApi.enhanceEndpoints<TagTypes, UpdatedDefinitions>({
  addTagTypes: tags,
  endpoints: {
    findAllCats: {
      providesTags: ['cats'],
      transformResponse: (response: FindAllCatsApiResponse) =>
        catsAdapter.setAll(catsAdapter.getInitialState(), response),
    },
  },
});
```

**Comment by mattoni** [comment]
As of 2.1.0, the types exported from that path (`DefinitionsFromApi, OverrideResultType `) are all resolving to the type "never" and my overrides that worked pre-2.0 are no longer working.

**Comment by mattoni** [comment]
![image](https://github.com/reduxjs/redux-toolkit/assets/5110855/1d234f02-64d3-4c94-a191-fa03f19489ec)

Those types don't exist at the 'normal' entry point :(

**Comment by EskiMojo14** [comment]
try a reinstall - we only released v2.2.0 in the last couple hours :)

**Comment by markerikson** [comment]
@mattoni the normal _RTK Query_ entry point :) `@reduxjs/toolkit/query` or `@reduxjs/toolkit/query/react` .

**Comment by markerikson** [comment]
I'm not clear if there's anything left to do with this issue. I'm going to close it, and if someone still has concerns please let us know.
