### ISSUE TITLE
RTK Query not skipping when cache invalidated

### ISSUE THREAD

**Issue by Ocoldwell** [reduxjs/redux-toolkit#3972]
I have a generated hook that's created from an OpenApi spec with a custom tag. We are invalidating the cached data from a modal and I'm passing the skip option to the hook:
`const {
    data: { reply: purchaseOrderHeader = [] } = {},
    isLoading: POLoading,
  } = useGetApiGetPurchaseOrderHeadersByIdQuery(
    {
      id: Number(purchaseorder),
    },
    { skip: !purchaseorder || buyListModalOpen}
  );`
  
The general idea is that when the modal is open the caching should wait to run, this is to avoid render cycles and flashes on the DataGrid component this populates, and this pattern works for 2 other hooks on the same page that are also invalidated. This always runs despite the skip, no matter the argument order, and looking at Redux Devtools a force refetch is passed in the meta arguments, which is not defined in the generated spec or enhanced endpoints. Am I misunderstanding something here?

**Comment by markerikson** [comment]
Hmm. Are you sure you're actually passing a condition of `{skip: false}`?

**Comment by Ocoldwell** [comment]
I've just checked again, and the skip condition above is resolving to true. I have other hooks using the exact same conditions in the same component that are skipping successfully every time using the same conditions. I've attached a screenshot of the hook, if there's anything else I can do let me know.
![Screenshot_20231212_212511](https://github.com/reduxjs/redux-toolkit/assets/75363386/666c2ea4-482a-4d74-93b0-1604b1ad0107)

**Comment by markerikson** [comment]
Can you clarify what the actual sequence / behavior is here? You said you're "invalidating the cached data".  How are you doing that?  Are you saying it's running a full fetch cycle after that happens, even though `{skip: true}` was passed in?

**Comment by Ocoldwell** [comment]
Sure. We mount the page on which this hook is defined, and it skips till purchaseorder is no longer undefined as it's a parameter from the Next.js router. We're currently using CSR across the Next application, nothing is in `/app` or `/pages`. The hook is a query generated from an OpenApi spec using @rtk-query/codegen-openapi and we've got some broad tags we're working with defined on the Swagger spec and we're using the tags option in the config. It's broad and the tag we're using is called PurchaseOrders. I can test out if the issue is with the generated hooks in the morning, and post the results. If that's the case it solves my issue and helps pinpoint. 

We use that data to populate a DataGrid that we can update and edit. We can then open a modal and make some edits on another DataGrid, and then have two options to either post the data or post the data and close the modal. The data we're posting from this modal is a generated mutation that posts and then invalidates the PurchaseOrders tag. This then invalidates all three generated hooks that I'm trying to skip. Two of the hooks skip as expected but the other I showed earlier always runs no matter what. The skip is to delay the re-fetching of the data until the modal is closed. The flicker that I'm fixing is caused by the hooks re-fetching the data and updating the DataGrid not in the modal. The full re-fetch cycle happens for one of the hooks and the others are skipping as expected with the same arguments as the one re-fetching which all evaluate to `{skip: true}`.

Does this clarify the sequence and behaviour better?

**Comment by refs05** [comment]
I think i have same problem, when i invalidate the tag the query that i invalidated is always fetching data from the cache

**Comment by markerikson** [comment]
Unfortunately I don't have any immediate ideas. 

Could you try recording a Replay and sharing that? That would make it a lot easier for me to dig in and see what's actually happening:

- https://replay.io/record-bugs

(if there's any concerns about sharing the recording publicly, you can share access to my work email, `mark@replay.io` )

**Comment by Ocoldwell** [comment]
I found the issue, we had another subscription in a component we use in the layout that didn't skip with the same condition. It was triggering the re-fetch on invalidation as it still had an active subscription.
