### ISSUE TITLE
Invalidation/refetch/OnMountOrArgChange/or any type of cache manipulation does not work with RTK Query.

### ISSUE THREAD

**Issue by alanusupov** [reduxjs/redux-toolkit#3978]
I am using Next js with redux/redux saga. We decided to optimise requests with rtk query. The GET requests work fine, caching works, however refetching doesn't always work after updates. It can work once after I wait a couple of minutes and a get request gets fired after edit mutations. I've tried using invalidating tags, refetching manually, updateQuery data, almost any kind of direct/manual cache manipulations. However nothing seems to work. Is there anything I could be missing?

This is my set up. The store is set up properly since the get requests work completely fine, its just that updated data does not change in the cache and I cant manipulate it at all.
"@reduxjs/toolkit": "^2.0.0",
"next": "^12.1.2",
"react": "^17.0.2"

![code](https://github.com/reduxjs/redux-toolkit/assets/38092287/013591e3-01bb-4e58-8d7d-14fcc7c68d30)
![code2](https://github.com/reduxjs/redux-toolkit/assets/38092287/b412c7a6-daae-41d7-8365-014911920d52)
![code3](https://github.com/reduxjs/redux-toolkit/assets/38092287/dd02c0c4-a02f-4fa1-93fc-f89320a7980c)
![code4](https://github.com/reduxjs/redux-toolkit/assets/38092287/e34acc6f-6673-43c0-a8a0-7e3e6b891fe3)

**Comment by markerikson** [comment]
Sorry, afraid that's not enough information to have any guess what might be happening. Could you provide a CodeSandbox or a Github repo that shows this happening, or record and share a Replay ( https://replay.io/record-bugs )?

**Comment by phryneas** [comment]
Did you add the middleware in your `configureStore` call?

**Comment by alanusupov** [comment]
> provide

https://app.replay.io/recording/untitled--6d7ec5fd-2499-400f-94cd-379b3b9fe93c?point=3458764513820540931&time=35&focusWindow=eyJiZWdpbiI6eyJwb2ludCI6IjAiLCJ0aW1lIjowfSwiZW5kIjp7InBvaW50IjoiMTA2MTE3NTY3MTEyNzE0MjQ3MjEwMjQ2MTE4MjkzMTEwNzg0IiwidGltZSI6NTIyNDR9fQ%253D%253D

**Comment by alanusupov** [comment]
> configureStore

yes I did 
![code](https://github.com/reduxjs/redux-toolkit/assets/38092287/7e504f8a-03c4-460c-89bb-fb1f82476e0b)

**Comment by phryneas** [comment]
I mean, looking at that replay, after every call to `edit-profile`, you get a call to `profile`, so can you maybe specify what's actually not working here?

**Comment by alanusupov** [comment]
> I mean, looking at that replay, after every call to `edit-profile`, you get a call to `profile`, so can you maybe specify what's actually not working here?

After every edit call and PUT request, the refetch does not pull from the server, but takes old data from the cache. You can see in the network tab after a PUT request to the profile, the GET request to '/me' does not get fired.

**Comment by phryneas** [comment]
I have to admit that there is much too much going on to conclude anything - maybe you should try to get this running on a single page without all the other stuff, and then proceed from there? With all of this, it's impossible to give any real comment.

**Comment by alanusupov** [comment]
After detailed code analysis I have found the problem. There was a third party axios caching library which cached the get requests. Removing it solved the problem.
