### ISSUE TITLE
Generic createSlice of initialState and payload

### ISSUE THREAD

**Issue by baeharam** [reduxjs/redux-toolkit#398]
I'm new to redux-toolkit and want to make generic function to generalize `createSlice` function.
What I want to generalize is that common request/success/failure logic of redux. I made generic function, but error is occurred. I read docs, but I don't understand how can I solve it.

```
interface IServerData<T> {
  result: T;
  error: string;
}
interface IServerPayload<T> extends IServerData<T> {}
interface IServerState<T> extends IServerData<T> {
  success: boolean;
  failure: boolean;
}

export default function createServerSlice<T>(
  name: string,
  initialState: IServerState<T>
): Slice<IServerState<T>, SliceCaseReducers<IServerState<T>>> {
  return createSlice({
    name,
    initialState,
    reducers: {
      request: (state: IServerState<T>) => state,
      success: (
        state: IServerState<T>,
        action: PayloadAction<IServerPayload<T>>
      ) => {
        state.result = action.payload.result;
      },
      failure: (
        state: IServerState<T>,
        action: PayloadAction<IServerPayload<T>>
      ) => {
        state.error = action.payload.error;
      }
    }
  });
}
```
What is the right approach to make generic function of `createSlice` ?

**Comment by phryneas** [comment]
If you encounter an error, it is always a wise idea to attach it to a github issue. Wrapping createSlice is complex and there can be plenty of errors. I don't know which one you are running into.

Some things:

```diff
export default function createServerSlice<T>(
  name: string,
  initialState: IServerState<T>
-): Slice<IServerState<T>, SliceCaseReducers<IServerState<T>>> {
+) {
  return createSlice({
```

Definitely remove that return value. The return value is inferred very complex and your usage of `SliceCaseReducers<IServerState<T>>>` will remove all actions from the return value. Just let TypeScript inference do it's job here.



[Read this part of the documentation](https://redux-toolkit.js.org/usage/usage-with-typescript#wrapping-createslice)


Also, typing your state type in the reducers like this might not work well as you are referencing an unresolved generic(T), depending on your TypeScript version and the used immer version. 
If everything else fails, you might need to do

```diff
      success: (
-        state: IServerState<T>,
+        _state: any,
        action: PayloadAction<IServerPayload<T>>
      ) => {
+        const state: IServerState<T> = _state;
        state.result = action.payload.result;
      },
```

**Comment by markerikson** [comment]
Yep.  Closing for now.  If the documentation doesn't resolve your issue, please comment here and let us know.
