### ISSUE TITLE
error TypeError: (0 , _lib_auth__WEBPACK_IMPORTED_MODULE_4__.getAuthSession) is not a function

### ISSUE THREAD

**Issue by Jheysen098** [reduxjs/redux-toolkit#3980]
when  i added the const session this error pops up and i cant seem to find any solution in google. 
I am using Next.JS in this project
![Capture](https://github.com/reduxjs/redux-toolkit/assets/115995052/de51e4dc-3704-4fdd-a208-95899f27a5de)
![Capture2](https://github.com/reduxjs/redux-toolkit/assets/115995052/8ba5b744-f8f1-4e72-a422-4a3884f5c3d0)

**Comment by markerikson** [comment]
This has nothing to do with RTK - this is an issue with your app's build setup.
