### ISSUE TITLE
aborted queries

### ISSUE THREAD

**Issue by FabienDeborde** [reduxjs/redux-toolkit#3987]
Hello, I am struggling to understand why my queries are aborted (mutations & queries).
Only the first query is working, every refetchs & updates are aborted (returning 200 from API but ignored by RTK).

This is an example of a rejected action:
```
{
  type: 'slack_queries/executeMutation/rejected',
  meta: {
    arg: {
      type: 'mutation',
      endpointName: 'updateChannelStatus',
      originalArgs: 'DBPDU4X63',
      track: true
    },
    requestId: 'LOCePIGJCdIKTUXqfrk9C',
    rejectedWithValue: false,
    requestStatus: 'rejected',
    aborted: true,
    condition: false
  },
  error: {
    name: 'AbortError',
    message: 'Aborted'
  }
}
```

I have no error message, no warning, it just get canceled.

I have used RTK a few times already without any problems, but it is the first time using RTK with react-native.

---
By the way, I am implementing the api like this:
api.ts
```ts
export const slackApi = createApi({
  reducerPath: 'slack_queries',
  baseQuery: fetchBaseQuery({
    baseUrl: config.api.url,
    timeout: config.api.timeout
  }),
  tagTypes: [SLACK_TAG],
  endpoints: (builder) => ({
    getMessages: builder.query<Record<string, SlackMessage[]>, unknown>({
      providesTags: [SLACK_TAG],
      query: () => ({
        url: 'monitoring/slack',
        method: 'GET'
      })
    }),
    updateChannelStatus: builder.mutation<null, string>({
      invalidatesTags: [SLACK_TAG],
      query: (id) => ({
        url: `monitoring/slack/${id}`,
        method: 'DELETE'
      })
    })
  })
})

export const {
  useLazyGetMessagesQuery,
  useUpdateChannelStatusMutation
} = slackApi
```

and using it like this:
myComponent.tsx
```ts
function Slack () {
  const [trigger, { data, isLoading, isError, error }] = useLazyGetMessagesQuery()

  useEffect(() => {
    trigger({}).unwrap()
      .catch(err => console.warn(err)
      )
  }, [trigger])

  const onRrefresh = () => {
    trigger({}).unwrap()
  }

  return (
    <Box>
      <ScrollView
        refreshControl={
          <RefreshControl
            refreshing={isLoading}
            onRefresh={onRefresh}
          />
        }
      >
        ...
      </ScrollView>
    </Box>
  )

export default Slack
```

---
Is there any way of getting more log about the abort reason ?
Am I missing something here that is different from usual Web stuff ?

I hope someone here can help me...

**Comment by FabienDeborde** [comment]
After hours looking at my code I realized my `config.api.timeout` was set in seconds instead of ms....
Fixing it fixed all the aborted requests.

I have no idea if this is possible, but it would be great if the error object gave a bit more context about the error.
Currently I got:
```ts
error: {
    name: 'AbortError',
    message: 'Aborted'
  }
```
Something like the following object would have helped a lot:
```ts
error: {
    name: 'AbortError',
    message: 'Aborted (timeout error)'
  }
```

**Comment by haider-codek** [comment]
any solution to that ?

**Comment by phryneas** [comment]
@haider-codek literally in the comment above yours. If that doesn't solve it you have a different problem and need to open your own issue with sufficient context.
