### ISSUE TITLE
Return type of selectFromResult must be Record<string, any> in useQueryState hook

### ISSUE THREAD

**Issue by KasimAhmic** [reduxjs/redux-toolkit#3989]
When using the `selectFromResult` option in the `useQueryState` hook, the return type is only allowed to be `Record<string, any>`. This limits the usability of the hook as it helps to be able to select a single primitive value in applications like ours where we have lots of values changing fairly rapidly. Functionally, there doesn't seem to be any reason for this limitation, at least none that I can see from taking a look at the source (could be way wrong though 🙂).

I've created a minimal reproduction repo here: https://github.com/KasimAhmic/select-from-result-repro. The `usePostSelector` hook has a type error but is otherwise working exactly as expected.

We have implemented something similar to the function below in our application and have been using it in production for over two years now with no issues whatsoever. The types here are a bit idealistic and in reality we have to do some extra casts here and there to get it past the type checker but this is what it does in essence.

```typescript
export const usePostSelector = <T extends (posts: EntityState<Post, number>) => ReturnType<T>>(
  selectorFn: T,
) => {
  /**
   * Select from state expects a return type of Record<string, any> | undefined but we want to be able
   * to return any arbitrary type from the selector function.
   */

  return jsonPlaceholderApiEndpoints.getPosts.useQueryState<ReturnType<T>>(undefined, {
    selectFromResult: (state) => selectorFn(state.data ?? postsAdapter.getInitialState()),
  });
};
```

Taking a look at the source code at `packages/toolkit/src/query/react/buildHooks.ts`, I was able to remove the `extends Record<string, any>` constraints without any issues and I was then able to return whatever I wanted from `selectFromResult`.

```diff
  export type QueryStateSelector<
-   R extends Record<string, any>,
+   R
    D extends QueryDefinition<any, any, any, any>
  > = (state: UseQueryStateDefaultResult<D>) => R

  export type UseQueryState<D extends QueryDefinition<any, any, any, any>> = <
-   R extends Record<string, any> = UseQueryStateDefaultResult<D>
+   R = UseQueryStateDefaultResult<D>
  >(
    arg: QueryArgFrom<D> | SkipToken,
    options?: UseQueryStateOptions<D, R>
  ) => UseQueryStateResult<D, R>

  export type UseQueryStateOptions<
    D extends QueryDefinition<any, any, any, any>,
-   R extends Record<string, any>
+   R
  > = { ... }
```

These changes result in:

```typescript
  // Succeeds as expected with no type error, name is type 'string'
  const name = jsonPlaceHolderApi.endpoints.getPosts.useQueryState(undefined, {
    selectFromResult: (state) =>
      postSelectors.selectById(state.data ?? postsAdapter.getInitialState(), postId).name,
  });

  // Fails as expected with a type error of:
  //     Type 'string' is not assignable to type 'Record<string, any>'.
  const name = jsonPlaceHolderApi.endpoints.getPosts.useQuery(undefined, {
    selectFromResult: (state) =>
      postSelectors.selectById(state.data ?? postsAdapter.getInitialState(), postId).name,
  });
```

Any thoughts on this?

---

Side note, this is tangentially related to #3650 where `selectFromResult` from `useQuery`'s options _must_ return an object conforming to the constraint `Record<string, any>` since `useQuery` attaches a `refetch` function to the result.

**Comment by phryneas** [comment]
Honestly, I'd prefer symmetry between both APIs here. 
Apart from code opticts, does this result in any measurable difference for you?

**Comment by KasimAhmic** [comment]
@phryneas If I return the the entire object, yes, since every component that uses one property of the object will re-render if any other property of the object changes.

Now alternatively, I could do something like this to prevent re-renders in PostBody when the title of the Post changes for example.

```typescript
export const PostTitle: FC<{ postId: number }> = ({ postId }) => {
  const { title } = jsonPlaceHolderApi.endpoints.getPosts.useQueryState(undefined, {
    selectFromResult: (result) => ({
      title: postSelectors.selectById(result.data ?? postsAdapter.getInitialState(), postId).title,
    }),
  });

  return <h3>{title}</h3>;
};

export const PostBody: FC<{ postId: number }> = ({ postId }) => {
  const { body } = jsonPlaceHolderApi.endpoints.getPosts.useQueryState(undefined, {
    selectFromResult: (result) => ({
      body: postSelectors.selectById(result.data ?? postsAdapter.getInitialState(), postId).body,
    }),
  });

  return <p>{body}</p>;
};

```

That said, this feels needlessly verbose for what I feel should just be a simple one liner and it makes it difficult to create a strongly typed wrapper function like we have been doing thus far. In my opinion, it feels wrong to force the return of an object if there's no legitimate technical reason for it. In `useQuery`, it totally makes sense there since you actually need to add on additional properties to the resulting object, not so much in `useQueryState`.

**Comment by KasimAhmic** [comment]
Just reaching out to see if opinions have changed on this at all or if I should just close this issue. This would really help my team but I understand if the requested change is not desired.

**Comment by KasimAhmic** [comment]
> @KasimAhmic sorry for the lack of response here.

No worries!

> > Functionally, there doesn't seem to be any reason for this limitation
> 
> The reason is that the query hooks then attach additional values to the return object, like the `refetch` function. You can't do that if the return value is a primitive.
> 
> You may be right that there could be some differences in behavior between `useQueryState` and `useQuery` - I haven't looked at that code in a while.

I took a look at `packages/toolkit/src/query/react/buildHooks.ts` and at first glance it doesn't appear that any additional values are added to the result of `selectFromResult`. It looks like the default selector is created first, a query selector is then assigned to be either the default selector or a newly created selector using the `selectFromResult` argument, the query selector is then executed, and finally the resulting value is returned with no modifications to it.

<details>
  <summary>Source Code</summary>

```typescript
    const useQueryState: UseQueryState<any> = (
      arg: any,
      { skip = false, selectFromResult } = {},
    ) => {
      const { select } = api.endpoints[name] as ApiEndpointQuery<
        QueryDefinition<any, any, any, any, any>,
        Definitions
      >
      const stableArg = useStableQueryArgs(
        skip ? skipToken : arg,
        serializeQueryArgs,
        context.endpointDefinitions[name],
        name,
      )

      type ApiRootState = Parameters<ReturnType<typeof select>>[0]

      const lastValue = useRef<any>(undefined)

      const selectDefaultResult: Selector<ApiRootState, any, [any]> = useMemo(
        () =>
          createSelector(
            [
              select(stableArg),
              (_: ApiRootState, lastResult: any) => lastResult,
              (_: ApiRootState) => stableArg,
            ],
            queryStatePreSelector,
            {
              memoizeOptions: {
                resultEqualityCheck: shallowEqual,
              },
            },
          ),
        [select, stableArg],
      )

      const querySelector: Selector<ApiRootState, any, [any]> = useMemo(
        () =>
          selectFromResult
            ? createSelector([selectDefaultResult], selectFromResult, {
                devModeChecks: { identityFunctionCheck: 'never' },
              })
            : selectDefaultResult,
        [selectDefaultResult, selectFromResult],
      )

      const currentState = useSelector(
        (state: RootState<Definitions, any, any>) =>
          querySelector(state, lastValue.current),
        shallowEqual,
      )

      const store = useStore<RootState<Definitions, any, any>>()
      const newLastValue = selectDefaultResult(
        store.getState(),
        lastValue.current,
      )
      useIsomorphicLayoutEffect(() => {
        lastValue.current = newLastValue
      }, [newLastValue])

      return currentState
    }

    // snip

    return {
      useQueryState,
      // ...
    }
```
</details>

Additionally, in my reproduction repo I have the below function that logs the members of a given object and in using it, I was unable to see any additional values added to the result.

```typescript
export function debugObject(name: string, obj: unknown) {
  const propertyNames = Object.getOwnPropertyNames(obj);
  const propertyDescriptors = Object.getOwnPropertyDescriptors(obj);
  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const prototype = Object.getPrototypeOf(obj);

  console.log('\n===============');

  if (obj && typeof obj === 'object') {
    console.log(name, 'hasRefetch:', Reflect.has(obj, 'refetch'));
  }

  console.log(name, 'propertyNames:', propertyNames);
  console.log(name, 'propertyDescriptors:', propertyDescriptors);
  console.log(name, 'prototype:', prototype);

  console.log('===============\n');
}
```

**Comment by phryneas** [comment]
https://github.com/reduxjs/redux-toolkit/blob/e46eb99f135dde5f047b8dc09113c42f20a54353/packages/toolkit/src/query/react/buildHooks.ts#L1048

`useQueryState` is essentially an implementation detail of `useQuery`. While it's possible to use on it's own, it doesn't create a state subscription and as a result data might get cache-collected if you don't also use `useQuery` for the same query with the same arguments at the same time - and that makes it a lot less useful on it's own.
In almost all cases, people use `useQuery` directly - adding functionality to `useQueryState` that is not compatible with "forwarding" from it in `useQuery` is something I don't really feel comfortable with.

**Comment by KasimAhmic** [comment]
> https://github.com/reduxjs/redux-toolkit/blob/e46eb99f135dde5f047b8dc09113c42f20a54353/packages/toolkit/src/query/react/buildHooks.ts#L1048-L1051
> 
> `useQueryState` is essentially an implementation detail of `useQuery`. While it's possible to use on it's own, it doesn't create a state subscription and as a result data might get cache-collected if you don't also use `useQuery` for the same query with the same arguments at the same time - and that makes it a lot less useful on it's own. In almost all cases, people use `useQuery` directly - adding functionality to `useQueryState` that is not compatible with "forwarding" from it in `useQuery` is something I don't really feel comfortable with.

I see, that's fair. In our application we basically call `useQuery` near the root of our app to load the data and then use `useQueryState` to retrieve pieces of that data throughout the rest of the app as a performance optimization. We have a large amount of data in the store and lot of that data that is constantly changing so calling `useQuery` everywhere ends up slowing things down quite a bit.

But if there's no interest in implementing this change, I'll go ahead and close the issue. I appreciate your time!
