### ISSUE TITLE
Reexport createSelectorCreator and defaultMemoize from Reselect

### ISSUE THREAD

**Issue by ytnytn1** [reduxjs/redux-toolkit#400]
Hello!

Is there any reason why `createSelectorCreator` and `defaultMemoize` are not reexported from the `reselect`?

I'm sure that `createSelector` is enough for most of the cases. But I faced a case where I need to pass additional options to `defaultMemoize` function and in that case, I have to explicitly add `reselect` as a dependency and import `createSelectorCreator` and `defaultMemoize` from there.

If there is no reason I think it will be very useful for those who faced the same issue and I can create a PR with that fix.

What do you think?

**Comment by markerikson** [comment]
That's actually kind of the point.  We're aiming for the 80% use case, and if you need to do more than what `createSelector` itself provides, your solution is exactly what we would suggest doing.

I don't see a need to explicitly re-export those further atm, but thanks for the suggestion!
