### ISSUE TITLE
[RTK Query]: Update graphql-request-base-query

### ISSUE THREAD

**Issue by vldslv-a** [reduxjs/redux-toolkit#4005]
Could you please update @rtk-query/graphql-request-base-query package to support @reduxjs/toolkit v2+?

<img width="657" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/97732940/ebcc4831-2fb6-45a4-a003-eaf42fef6341">

**Comment by phryneas** [comment]
released as [@rtk-query/graphql-request-base-query@2.3.0](https://www.npmjs.com/package/@rtk-query/graphql-request-base-query/v/2.3.0)

**Comment by vldslv-a** [comment]
> released as [@rtk-query/graphql-request-base-query@2.3.0](https://www.npmjs.com/package/@rtk-query/graphql-request-base-query/v/2.3.0)

It's not over yet :D


<img width="678" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/97732940/ecafef60-4a02-4577-adb4-07c835ede36a">

**Comment by phryneas** [comment]
wait what? I bumped that 😕

**Comment by phryneas** [comment]
Ugh, the devDependency but not the peerDependency 🤦 

I'll get to it later.

**Comment by vldslv-a** [comment]
Okay, thanks)

**Comment by phryneas** [comment]
Should be published in a minute or two, I've started the CI job.
