### ISSUE TITLE
[RTK Query] useLazyQuery's trigger does not retrigger for the same parameter when using streaming updates

### ISSUE THREAD

**Issue by nguyenlam123** [reduxjs/redux-toolkit#4008]
For the [streaming updates](https://redux-toolkit.js.org/rtk-query/usage/streaming-updates) example, the `trigger` function does not retrigger when passing the same parameter. According to [documentation](https://redux-toolkit.js.org/rtk-query/api/created-api/hooks#uselazyquery), the trigger function returned from a LazyQuery always initiates a new request to the server even if there is cached data. 

A codesandbox can be found [here](https://codesandbox.io/p/sandbox/redux-toolkit-query-uselazyquery-forked-dqt63p?file=%2Fsrc%2Fstore%2FpostApi.js%3A15%2C12-15%2C59&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqduy24x00063b6hqir8fgaf%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqduy24x00023b6hnvbovd3q%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqduy24x00033b6h5g4trj7e%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqduy24x00053b6hv39nq6f0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B55.86556338%252C44.13443662%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqduy24x00023b6hnvbovd3q%2522%253A%257B%2522id%2522%253A%2522clqduy24x00023b6hnvbovd3q%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqglg92100023b6hlvvu34jr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A20%252C%2522startColumn%2522%253A21%252C%2522endLineNumber%2522%253A20%252C%2522endColumn%2522%253A21%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqgls2z600023b6hzr01hy4k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A12%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A59%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fstore%252FpostApi.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqgls2z600023b6hzr01hy4k%2522%257D%252C%2522clqduy24x00053b6hv39nq6f0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqduy24x00043b6hdgh4qjcb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqduy24x00053b6hv39nq6f0%2522%252C%2522activeTabId%2522%253A%2522clqduy24x00043b6hdgh4qjcb%2522%257D%252C%2522clqduy24x00033b6h5g4trj7e%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqduy24x00033b6h5g4trj7e%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Steps to reproduce**
1. Go to the sandbox in the link above
2. Click on the button called `fetch post`
3. A network request is made to https://webcodingcenter.com/shared/get_post.php
4. Click on `fetch post` again

**Expected behaviour**
A network request should be made

**Actual behaviour**
No network request was made

Thank you so much in advance for all time spent for this issue 🤗 🙇

**Comment by riqts** [comment]
In this particular codesandbox example the `queryFn: () => ({ data: [] })` defined in the endpoint returns a static object without any data fetching involved. The data fetching exists in the `onCacheEntryAdded` so I don't think the trigger has any impact. Probably the expected behavior in the codesandbox at the very least.

**Comment by phryneas** [comment]
Yeah.
You placed your logic in `onCacheEntryAdded` - that will run once per cache entry (argument to your hook), never again.

This is working as intended from our side - if you want it to behave differently, you have to use a different lifecycle hook.

**Comment by nguyenlam123** [comment]
> Yeah. You placed your logic in `onCacheEntryAdded` - that will run once per cache entry (argument to your hook), never again.
> 
> This is working as intended from our side - if you want it to behave differently, you have to use a different lifecycle hook.

Thanks 🙇 , that was it! It works as intended with `onQueryStarted`. I'll close this issue
