### ISSUE TITLE
Challenges with Data Sync in RTK Query Across Multiple API Slices in React

### ISSUE THREAD

**Issue by deavac45** [reduxjs/redux-toolkit#4010]
Hello,

I am experiencing a challenge with RTK Query in my React application involving multiple slices - `MealApiSlice` and `DailyMenuApiSlice`. My application's structure is as follows:

- **store.js:** Configures the Redux store and includes `apiSlice.reducer`.
- **apiSlice:** A base slice that initializes RTK Query's `createApi`.
- **MealApiSlice:** Manages CRUD operations for meals. It defines endpoints like `getMeals`, `addMeal`, `updateMeal`, and `deleteMeal`, using appropriate `providesTags` and `invalidatesTags`.
- **DailyMenuApiSlice:** Manages operations for 'DailyMenu'. It fetches updated meal data and performs create, update, delete operations on daily menus. Here I create daily menus with the meals I add with MealApiSlice.

I have two pages and routes. "meals and dailymenu". The issue arises when I update a meal in the 'meals' route; the update works correctly. For example, I go to the meals route and added a meal. Then I go to the dailymenu route and added this meal to the daily menu. Then I come back to the meals route and update the name of the meal. When I go to the dailymenu route again, the meal name remains the same. However, when navigating to the 'dailymenu' route, the `rawMenuData` should reflect the updated meal but continues to show the old meal data. It does not receive fresh data. Fetches data from cache. My goal is that when I add a meal in the meals route, I can also see the change in the dailymenu route.  I only get fresh data if I refresh the page. or if I call the refetch function. 

Here are snippets from my slices for reference:

```
//store.js

import { configureStore } from "@reduxjs/toolkit";
import { apiSlice } from "./slices/apiSlice";

const store = configureStore({
	reducer: {
		[apiSlice.reducerPath]: apiSlice.reducer,
	},
	middleware: (getDefaultMiddleware) =>
		getDefaultMiddleware().concat(apiSlice.middleware),
	devTools: true,
});

export default store;
```

```
//apiSlice.js

import { fetchBaseQuery, createApi } from "@reduxjs/toolkit/query/react";
import { BASE_URL } from "../constants";


const baseQuery = fetchBaseQuery({
	baseUrl: BASE_URL,
});

export const apiSlice = createApi({
	baseQuery: baseQuery,
	tagTypes: ["Meals", "DailyMenus"],
	endpoints: (builder) => ({}),
});

```

```
/////////////////////////////////////////////////////////////////////

--------dailyMenuApiSlice.js
import { apiSlice } from "./apiSlice";
import { DAILY_MENU_URL } from "../constants";

export const dailyMenuApiSlice = apiSlice.injectEndpoints({
    endpoints: (builder) => ({
        getDailyMenus: builder.query({
            query: () => `${DAILY_MENU_URL}`,
            providesTags: ['DailyMenus'],
            keepUnusedDataFor: 5,
        }),
		.......
	
////////////////////////////////////////////////////////////////////////

-----------mealApiSlice.js
import { apiSlice } from "./apiSlice";
import { MEAL_URL } from "../constants";

export const mealApiSlice = apiSlice.injectEndpoints({
	endpoints: (builder) => ({
		getMeals: builder.query({
			query: () => ({
				url: `${MEAL_URL}`,
			}),
			providesTags: ["Meals"],
			keepUnusedDataFor: 5,
		}),

		addMeal: builder.mutation({
			query: (data) => ({
				url: `${MEAL_URL}`,
				method: "POST",
				body: data,
			}),
			invalidatesTags: ["Meals"],
		}),
	      updateMeal: builder.mutation({
			query: (data) => ({
				url: `${MEAL_URL}`,
				method: "PUT",
				body: data,
			}),
			invalidatesTags: ["Meals"],
		}),

////////////////////////////////////////////////////////////////////////
```

```
--------- meal route and page
...................
const {
	data: rawMealData = [],
	isLoading: mealLoading,
	refetch,
	} = useGetMealsQuery();
const [addMeal, { isLoading: addMealLoading }] = useAddMealMutation();
...............................

////////////////////////////////////////////////////////////////////////

------------dailymenu route and page

//
	const {
		data: rawMenuData = [],
		isLoading: menuLoading,
		refetch,
	} = useGetDailyMenusQuery();

//
```

Method I tried:
I tried to invalidate the DailyMenus using invalidateTags. But doesn't work
invalidatesTags: ["Meals","DailyMenus"],

**Comment by markerikson** [comment]
Tag invalidation only works inside of a single given API slice. In other words, a mutation in `apiSlice1` will not invalidate tags defined by queries in `apiSlice2`.

This is one of the reasons why we specifically advise that you should only have _one_ API slice in an app:

- https://redux-toolkit.js.org/rtk-query/api/createApi

**Comment by deavac45** [comment]
Thank you for your reply. So if I combine 2 slices into one slice, the problem is solved, right?
Also, is there any way to get fresh data when you go to a new route or page? I tried the method below but sometimes I get fresh data and sometimes I don't.

//refetchOnMountOrArgChange:true 

const {
	data: rawMenuData = [],
	isLoading: menuLoading,
	refetch,
} = useGetDailyMenusQuery(undefined,{refetchOnMountOrArgChange:true});

**Comment by deavac45** [comment]
> Tag invalidation only works inside of a single given API slice. In other words, a mutation in `apiSlice1` will not invalidate tags defined by queries in `apiSlice2`.
> 
> This is one of the reasons why we specifically advise that you should only have _one_ API slice in an app:
> 
> * https://redux-toolkit.js.org/rtk-query/api/createApi

Thank you for your reply. Actually there is only one api. the others are endpoint. I applied code splitting.

https://redux-toolkit.js.org/rtk-query/usage/code-splitting

export const BASE_URL ="http://localhost:5000/"
export const MEAL_URL = "/api/meal";
export const DAILY_MENU_URL = "/api/dailymenu";

When we do code splitting, it cannot be overridden because it is not in the same slice, right?
So if I combine 2 slices into one slice, the problem is solved, right?

Also, is there any way to get fresh data when you go to a new route or page? I tried the method below but sometimes I get fresh data and sometimes I don't.

//refetchOnMountOrArgChange:true

const {
data: rawMenuData = [],
isLoading: menuLoading,
refetch,
} = useGetDailyMenusQuery(undefined,{refetchOnMountOrArgChange:true});

**Comment by markerikson** [comment]
What actually matters is the number of `createApi` calls. It does look like you only have one API slice actually being created.

I don't know enough about your app from this description to have more advice or suggestions on what may be happening. If you can put up a CodeSandbox or a Replay ( https://replay.io/record-bugs ) , I might be able to take a look.

**Comment by deavac45** [comment]
> What actually matters is the number of `createApi` calls. It does look like you only have one API slice actually being created.
> 
> I don't know enough about your app from this description to have more advice or suggestions on what may be happening. If you can put up a CodeSandbox or a Replay ( https://replay.io/record-bugs ) , I might be able to take a look.

Thank you for your help, I've resolved the issue. Previously, I was using Create React App (CRA) for my application. When I prepared the code to send to you, I rebuilt it using Vite, and the problem was solved. Now, I can fetch fresh data during page transitions. With CRA, data was being cached during page transitions, and I'm not sure why that was happening.
