### ISSUE TITLE
RTK Query useQuery `isFetching` and `isSuccess` are `true` at the same time.

### ISSUE THREAD

**Issue by crabvk** [reduxjs/redux-toolkit#4021]
Hi. I'm using `useQuery` inside a component to fetch data from a server and log result to the console. One of the parameters for the query is chosen from a Select component (simple `<select>` with `<option>`s). When I first load the page there's nothing special about the returned values. But when I choose an option from the `<select>` and the query refetches, I got
```log
isLoading: false, isFetching: true, isSuccess: false
isLoading: false, isFetching: true, isSuccess: true
isLoading: false, isFetching: false, isSuccess: true
```
Given [the description](https://redux-toolkit.js.org/rtk-query/usage/queries#frequently-used-query-hook-return-values) of return values, how is that possible that `isFetching` and `isSuccess` are true at the same time? What does that state even mean?

**Comment by phryneas** [comment]
Quoting the docs you linked:

* isFetching - When true, indicates that the query is currently fetching, but might have data from an earlier request. This will be true for both the first request fired off, as well as subsequent requests.
* isSuccess - When true, indicates that the query has data from a successful request.

Both of these can be true at the same time. You might have data from a successful request in the past, and be fetching new data at the same time.

**Comment by crabvk** [comment]
> You might have data from a successful request in the past

Yes, I have. But then, why is the first line of the log says I don't, i.e. `isSuccess: false`?
