### ISSUE TITLE
`selectFromResult` runs on any change to the store

### ISSUE THREAD

**Issue by thisjeremiah** [reduxjs/redux-toolkit#4028]
## Problem

I've noticed that the `selectFromResult` callback in `useQuery` seems to be running any time any data in the store changes. 

I'm trying to understand if this behavior is necessary.

## Expected Behavior

I'd prefer `selectFromResult` to only run when the relevant data changes (on changes to loading state or  the response data).

## Benefit

The primary benefit of improving this behavior is that if someone (intentionally or accidentally) returns an unstable response from `selectFromResult`, the component will only re-render twice for every request that gets made (`isLoading` is set to `true` then `false`).

## Reproduction

I have a simple sandbox that illustrates this behavior [here](https://codesandbox.io/p/sandbox/rtk-query-demo-forked-l8stwf?file=%2Fsrc%2Findex.tsx%3A7%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqu156c900073b6iq7bpwr7i%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqu156c900033b6i4tmnvl8e%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqu156c900043b6i0drzl7wh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqu156c900063b6i6spigael%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqu156c900033b6i4tmnvl8e%2522%253A%257B%2522id%2522%253A%2522clqu156c900033b6i4tmnvl8e%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqu16ayw00633b6idv851oly%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqu16ayw00633b6idv851oly%2522%257D%252C%2522clqu156c900063b6i6spigael%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqu156c900053b6iz31idtcy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqu156c900063b6i6spigael%2522%252C%2522activeTabId%2522%253A%2522clqu156c900053b6iz31idtcy%2522%257D%252C%2522clqu156c900043b6i0drzl7wh%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqu156c900043b6i0drzl7wh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

I intentionally return an unstable reference in `selectFromResult` for `useQuery B` to show how many times `selectFromResult` is running. (The code sandbox was not reliably emitting console logs.)

## How to fix

The implementation of `selectFromResult` is [here](https://github.com/reduxjs/redux-toolkit/blob/e773cba789598e39275cd4c59c2b2fac92b6996e/packages/toolkit/src/query/react/buildHooks.ts#L925).

I wasn't clever enough to figure out a way to fix it myself, but my hope is that the `selectFromResult` selector can be modified to only run when the _relevant_ store data changes.

## Note

I noticed there are a couple of existing issues that may be relevant to the discussion:

- https://github.com/reduxjs/redux-toolkit/issues/2208
- https://github.com/reduxjs/redux-toolkit/issues/4002

I created a separate issue because I'm specifically looking to understand why this behavior is happening and whether it's possible to improve it.

**Comment by phryneas** [comment]
I believe [this change](https://github.com/reduxjs/redux-toolkit/discussions/3975#discussioncomment-7847761) could remedy that - could you give it a try and report back?

**Comment by thisjeremiah** [comment]
@phryneas That works! 🎉 

I don't have a way of showing this working in my sandbox, but I do have a vite reproduction with the patch [here](https://github.com/thisjeremiah/rtk-repro/tree/main).

I don't think there any regressions in the testing suite for the fix [here](https://github.com/thisjeremiah/redux-toolkit/commit/9a90cc6b2c59b14c6dd866d83c319c9ab1f915b8). (tested tests locally).

Is this a change that you're looking to make?

**Comment by phryneas** [comment]
It's on my list, but honestly I have no idea when I could get to it.

If you could open a PR and maybe add a test to the test suite that would have failed with the old behaviour, it would be very welcome!
