### ISSUE TITLE
`Argument of type 'AsyncThunkAction<any, void, AsyncThunkConfig>' is not assignable to parameter of type 'UnknownAction'.`

### ISSUE THREAD

**Issue by shifoc** [reduxjs/redux-toolkit#4032]
```ts
export const fetchEquipmentStatusData = createAsyncThunk('onBoard/fetchEquipmentStatusData', async (params) => {
        const response = await axios.get('/api/getEquipmentStatus', { params });
        return response.data;
});
```

```ts
import { useDispatch } from 'react-redux';
...
const dispatch = useDispatch();
...
const param = {
                    'equipment': 'car'
                };
dispatch(fetchEquipmentStatusData(param));
```

`Argument of type 'AsyncThunkAction<any, void, AsyncThunkConfig>' is not assignable to parameter of type 'UnknownAction'.`
`Expected 0 arguments, but got 1.`

**Comment by EskiMojo14** [comment]
You need to make a version of useDispatch that knows that your store allows hooks. See [Define typed hooks](https://redux.js.org/usage/usage-with-typescript#define-typed-hooks) in the Typescript guide.

**Comment by mrdulin** [comment]
@EskiMojo14 I made a [demo](https://stackblitz.com/edit/stackblitz-starters-vbgz2h?file=src%2FApp.tsx), it does not work after defining the typed hooks.

**Comment by EskiMojo14** [comment]
@mrdulin that looks to be a bug with stackblitz's typescript server, it works fine in [Typescript playground](https://tsplay.dev/NB16Dw).

**Comment by greatelv** [comment]
Maybe, "redux" version is wrong.
It shoud be v5^.

**Comment by EskiMojo14** [comment]
@greatelv it's v5 in the demo - the UnknownAction type was only introduced in v5.

**Comment by seafronthu** [comment]
> @mrdulin that looks to be a bug with stackblitz's typescript server, it works fine in [Typescript playground](https://tsplay.dev/NB16Dw).

This issue also exists in vscode.

**Comment by MiniOcean404** [comment]
How to solve it

**Comment by phryneas** [comment]
@MiniOcean404 https://redux.js.org/usage/usage-with-typescript#define-typed-hooks

**Comment by MiniOcean404** [comment]
> @EskiMojo14我做了一个[演示](https://stackblitz.com/edit/stackblitz-starters-vbgz2h?file=src%2FApp.tsx)，定义类型钩子后它不起作用。
I wrote it like demo like this，but I also read the document, but it is still wrong

**Comment by phryneas** [comment]
@MiniOcean404 looking at that, it seems to be a bug with StackBlitz. Locally in VSCode, this works. (You need to give the thunk argument a type, but that's a different problem)
