### ISSUE TITLE
`createSliceReducerBuilder` is not published in rtk-codemods

### ISSUE THREAD

**Issue by kirbysayshi** [reduxjs/redux-toolkit#4034]
Hello! I was trying to use the new `createSliceReducerBuilder` codemod, but it's not present in the published package and results in an error.

Error message:

```
Error: Cannot find module '/[PATHREDACTED]node_modules/@reduxjs/rtk-codemods/transforms/createSliceReducerBuilder'
```

```
ls -la /[PATHREDACTED]/node_modules/@reduxjs/rtk-codemods/transforms
total 0
drwxr-xr-x  4 drew  staff  128 Jan  2 18:25 .
drwxr-xr-x  7 drew  staff  224 Jan  2 18:25 ..
drwxr-xr-x  4 drew  staff  128 Jan  2 18:25 createReducerBuilder
drwxr-xr-x  4 drew  staff  128 Jan  2 18:25 createSliceBuilder
```

Looks like the rtk-codemods package hasn't been published in over a year, so I'm guessing it just needs a republish!:

<img width="968" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/90831/f09ed236-65e6-4852-8be6-411a1d30fb09">

To anyone else encountering this issue, here is the workaround for now:

- clone this repo
- run `yarn` inside of this repo
- `cd` to your target project folder
- run the command from there: 

```sh
$ pwd
/path/to/my/project
$ ~/github/redux-toolkit/packages/rtk-codemods/bin/cli.js createSliceReducerBuilder ./src/store/mySlice.ts
```

The codemod has a check that the target file is in the current working dir, so you must be in your project's tree, rather than within the rtk-codemod tree.

**Comment by EskiMojo14** [comment]
thanks for the report! that must have been missed in the many releases made at the same time 😛 

i've now bumped and released the package, so it should work - please let us know if there are any issues!

**Comment by kirbysayshi** [comment]
🎉 Thank you! Seems like an easy thing to miss, thanks for fixing it so quickly!
