### ISSUE TITLE
Adding dispatch(apiSlice.util.resetApiState()) inside mutation making isSuccess property always false

### ISSUE THREAD

**Issue by Tik1993** [reduxjs/redux-toolkit#4037]
Hi guys, I want to integrate OAuth 2.0 into my project. My goal is to allow users to click the logout button to log out. Once the user logs out, the state in Redux will be reset. I followed a tutorial, but it seems outdated, and I cannot find the solution.

In my code, I use the mutation hook from Redux and useEffect hook to keep track the logout feature
```
const navigate = useNavigate(); 
const [sendLogout, { isLoading, isSuccess, isError, error }] = useSendLogoutMutation();  
useEffect(() => {if (isSuccess) {console.log("success"); navigate("/");}}, [isSuccess, navigate]); 
```
In my authApiSlice.js, I create a sendLogout reducer for the sendLogout action
```
    sendLogout: builder.mutation({
      query: () => ({
        url: "/auth/logout",
        method: "POST",
      }),
      async onQueryStarted(arg, { dispatch, queryFulfilled }) {
        try {
          const { data } = await queryFulfilled;
          console.log(data);
          dispatch(logOut());
          dispatch(apiSlice.utils.resetApiState());
        } catch (err) {
          console.log(err);
        }
      },
    }),
```
I expect the page will be redirect to main page after clicking the logout button. However, it keeps remain the dash page. However, if I comment out below code in my authApiSlice.js. The page will go to main page, so I think below code has a problem but I don't how to fix it.
```
 dispatch(apiSlice.utils.resetApiState());
```

**Comment by markerikson** [comment]
The status booleans in the hooks are derived.  If there is no actual value cached, then yes, `isSuccess` will be false because there _isn't a value_.

This looks like a bad use of a `useEffect` to me.  You should probably change that to directly navigate in the event handler , in the same place that you're calling `dispatch(logOut())`.

- https://react.dev/learn/you-might-not-need-an-effect#sharing-logic-between-event-handlers

**Comment by markerikson** [comment]
Hmm. Okay, I'll caveat that by saying that I misread the code here - I thought that the  `logOut()` was in a click handler, and it's actually in an endpoint lifecycle method.

It's probably still better to figure out how to navigate directly as part of that endpoint handling sequence - that `useEffect` approach isn't going to work the way you want it to.

**Comment by Tik1993** [comment]
Here is my code in my Layout page:
```
const DashLayout = () => {
  const navigate = useNavigate();
  const [sendLogout, { isLoading, isSuccess, isError, error }] =
    useSendLogoutMutation();

  useEffect(() => {
    if (isSuccess) {
      console.log("success");
      navigate("/");
    }
  }, [isSuccess, navigate]);

  const onLogoutClicked = () => sendLogout();

  const logoutButton = (
    <button onClick={onLogoutClicked} title="Logout">
      Logout
    </button>
  );
  return (
    <>
    </>
  );
};
```

I waana make sure the useSendLogoutMutation is called successful before navigating to other page.  Anything works except adding dispatch(apiSlice.util.resetApiState()) into the try catch block in onQueryStarted(). Without adding dispatch(apiSlice.util.resetApiState()), when I click logout button, the isSuccess property will change to true so that I can navigate to the main page

**Comment by markerikson** [comment]
Yeah, change that to:

```ts
const onLogoutClicked = async () => {
  await sendLogout().unwrap();
  navigate("/");
}
```
