### ISSUE TITLE
Breaking Feature Request: rename `reducer` to `caseReducer` in `createSlice`

### ISSUE THREAD

**Issue by jmccarrell-lmi** [reduxjs/redux-toolkit#404]
So I finally got around to unit testing my slices and I realized I needed to define my case reducers, before adding them to createSlice, so I did so, but I named them caseReducer, because that's what they are. Calling them reducers is incorrect, because they don't have enough information to be reducers (missing the type switch).

This is a minor thing, this just means I can't use object shorthand when creating my slice:

`createSlice({ reducers: caseReducers })`, but I think I'm technically correct that it's a misleading name.

Would i recommend just changing this willy nilly, nah, but the next time the group wants to make a breaking change with createSlice, I'd recommend considering this key name change.

**Comment by markerikson** [comment]
I'm not sure what you're actually suggesting here, either in terms of naming changes or conceptually.

A reducer function does not need to contain a `switch` statement.  It simply needs to have the form of `(state, action) => newState`.  It can contain _any_ conditional logic inside that is needed to calculate `newState`.

Conceptually, a "case reducer" is exactly equivalent to a single `case` statement in a larger `switch`, hence the name.

Also, note that all the case reducers you pass via the `reducers` object to `createSlice` are available afterwards on the slice object, as `someSlice.caseReducers`.  That way, you can still define them inline (and take advantage of TypeScript type inference if you're using TS), but test them individually if you actually feel you need to.

**Comment by phryneas** [comment]
If you want to get hung up on technicalities: 

A reducer that reacts to every kind of action the same way is absolutely a valid reducer, too.

The name actually comes from the argument to the `Array.prototype.reduce` function. In that case, it is even usual for all items (or actions) to be handled the same way.



But more to the point: this library has way to many users to make such a change now. This would be too inconventient for all those users - and in addition it would be more to type for everyone.

**Comment by jmccarrell-lmi** [comment]
First of all `slice.caseReducers` was exactly what i was looking for for testing purposes. Thank you :).

I honestly didn't expect the change to happen, but I wanted to point it out, out of a feeling of obligation :p

IMPORTANT: the following is just a conversation. If you're busy or don't have the spoons, feel free to ignore it.

Yes, a caseReducer is also a reducer, and they're interchangable, but a caseReducer conceptually fits in a switch case in a reducer and abstracts away the case, so it has optional definition attached that a reducer does not.

More importantly, what is passed to `reducers` in createSlice isn't `(state, action) => state` it's `{ [actionType]: (state, action) => state | null` This is the difference I'm pointing out. I call these `caseReducers`, which is the name I'm giving `{ [actionType]: CaseReducer }` where `CaseReducer` is an alias for reducer, but one that is assumed to not have the `case logic` in the implementation.

If i were being unnecessarily technical I would make the definition of createSlice:
`createSlice({ name, caseReducers, reducer })` in otherwords, I'd rename `reducers` to `caseReducers` and `extraReducers` to `reducer`.

That said, would people understand what is meant by `caseReducers` as much as `reducers` even with the mild ambiguity? No. So my recommendation is silly.
