### ISSUE TITLE
Error: Can't resolve 'react-redux'

### ISSUE THREAD

**Issue by anil0403** [reduxjs/redux-toolkit#4045]
./redux/hooks.ts:4:0
Module not found: Can't resolve 'react-redux'

store.ts
import { configureStore } from "@reduxjs/toolkit";
// ...
import { counterSlice } from "./features/counter/counterSlice";
export const store = configureStore({
  reducer: {
    counter: counterSlice.reducer,
  },
});

// Infer the `RootState` and `AppDispatch` types from the store itself
export type RootState = ReturnType<typeof store.getState>;
// Inferred type: {posts: PostsState, comments: CommentsState, users: UsersState}
export type AppDispatch = typeof store.dispatch;

hooks.ts

import type { TypedUseSelectorHook } from "react-redux";
import type { RootState, AppDispatch } from "./store";

import { useDispatch, useSelector } from "react-redux";

// Use throughout your app instead of plain `useDispatch` and `useSelector`
export const useAppDispatch: () => AppDispatch = useDispatch;
export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector;

CounterSlice.ts

import { createSlice } from "@reduxjs/toolkit";
import type { PayloadAction } from "@reduxjs/toolkit";
import {RootState} from "../../store";

// Define a type for the slice state
interface CounterState {
  value: number;
}

// Define the initial state using that type
const initialState: CounterState = {
  value: 0,
};

export const counterSlice = createSlice({
  name: "counter",
  // `createSlice` will infer the state type from the `initialState` argument
  initialState,
  reducers: {
    increment: (state) => {
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
    // Use the PayloadAction type to declare the contents of `action.payload`
    incrementByAmount: (state, action: PayloadAction<number>) => {
      state.value += action.payload;
    },
  },
});

export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// Other code such as selectors can use the imported `RootState` type
export const selectCount = (state: RootState) => state.counter.value;

export default counterSlice.reducer;

  const count = useAppSelector((state) => state.counter.value);
  all the modules are properly installed but throwing an error :  Can't resolve 'react-redux' 
![image](https://github.com/reduxjs/redux-toolkit/assets/68494220/f62b66b8-a81a-42b8-8caa-8b1845e6c52f)

**Comment by phryneas** [comment]
Can you do a `npm ls react-redux`?

**Comment by eigood** [comment]
I ran into this too, just have @reduxjs/toolkit installed, while building an app using quasar(which sits on top of vue).  I don't see a need at all to have any of the react stuff installed.

**Comment by eigood** [comment]
Hmm, with reusable slices, and enhances(to support tree shaking, and shared git repos), the separate imports are pulling in the query/react variant.  If they are not suppose to do so, then how can we have shared non-specific react, but still shared between vue/quasar, react, and astro?

**Comment by phryneas** [comment]
As long as you never import anything in your code from `/react`, you will not get react-specific code, as soon as you do, you will get it.

Did you verify that you are not using `/react` imports, and can you demonstrate that you actually get react-specific code bundled?

If it's just **installed** on your system, but not bundled, that's a quirk of npm that installs optional peer dependencies by default since a few versions, we can do nothing about it - but you can complain to the npm folks.
