### ISSUE TITLE
Help Wanted: Related to baseQuery and baseURL

### ISSUE THREAD

**Issue by Pranav-Talmale** [reduxjs/redux-toolkit#4051]
I am having a setup where I use a jwt and http only cookie for auth in a MERN stack website.

In the frontend's API slice, I am using the following:
`const baseQuery = fetchBaseQuery({ baseUrl: 'http://localhost:3000' });`
where `http://localhost:3000` is my backend server's address.

When I use the above configuration, the request sent to backend server does not include the jwt auth cookie.

But when I use vite's proxy to handle connections to `http://localhost:3000`, everything seems to work normally and the request also has the jwt cookie in it.

I can't seem to get why this is happening

**Comment by gusazevedo** [comment]
Can you share your apiSlice definition code?

**Comment by Pranav-Talmale** [comment]
@gusazevedo this is the frontend setup I am trying to use:

Api slice:

```
import {createApi, fetchBaseQuery} from '@reduxjs/toolkit/query/react';

const baseQuery = fetchBaseQuery({
    baseUrl: 'http://localhost:3000',
    credentials: 'include',
});

export const apiSlice = createApi({
    baseQuery,
    tagTypes: ['User'],
    endpoints: (builder) => ({}),
});
```

usersApiSlice:

```
import { apiSlice } from './apiSlice';
const USERS_URL = '/api/users';

export const userApiSlice = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    login: builder.mutation({
      query: (data) => ({
        url: `${USERS_URL}/auth`,
        method: 'POST',
        body: data,
      }),
    }),
    logout: builder.mutation({
        query: () => ({
          url: `${USERS_URL}/logout`,
          method: 'POST',
        }),
      }),
      register: builder.mutation({
        query: (data) => ({
          url: `${USERS_URL}`,
          method: 'POST',
          body: data,
        }),
      }),
      updateUser: builder.mutation({
        query: (data) => ({
          url: `${USERS_URL}/profile`,
          method: 'PUT',
          body: data,
        }),
      }),
  }),
});

export const { 
  useLoginMutation, 
  useLogoutMutation, 
  useRegisterMutation,
  useUpdateUserMutation
} = userApiSlice;
```

authSlice:

```
import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    userInfo: localStorage.getItem('userInfo') ? JSON.parse(localStorage.getItem('userInfo')): null
};

const authSlice = createSlice({
    name: 'auth',
    initialState,
    reducers:{
        setCredentials: (state, action) => {
            state.userInfo = action.payload;
            localStorage.setItem('userInfo', JSON.stringify(action.payload));
        },
        logout: (state, action) => {
            state.userInfo = null;
            localStorage.removeItem('userInfo');
        }
    }
});

export const {setCredentials, logout} = authSlice.actions;

export default authSlice.reducer;
```

**Comment by riqts** [comment]
The JWT HTTP-only cookie in this instance should be handled entirely by the fetchBaseQuery and your implementation for that looks sufficient. RTKQ outside of the baseQuery doesn't even really know HTTP exists.

The error here is most likely in the actual HTTP handling of the cookie and the middleware or cors/https rules. Something that the vite proxy handles automatically I guess considering you said it works there.

If you wanted to narrow it down to being RTKQ's fault or not, you could just try call those 4 endpoints with the same conditions using a standard fetch and see if that works?

**Comment by Pranav-Talmale** [comment]
Resolved my problem after going through this closed issue:
https://github.com/reduxjs/redux-toolkit/issues/2095

In the end, the jwt cookie logic in the backend and the frontend redux logic needed some tweaking to resolve the issue
