### ISSUE TITLE
Validate my approach of calling multiple queries 

### ISSUE THREAD

**Issue by nouman91** [reduxjs/redux-toolkit#4088]
Hi, 
I am working on the Sankey Graph widget. I have to grab data from a few different endpoints and then transform that data for the widget to consume. 

I wanted to chain or call multiple queries together without putting the multiple useQuery calls in my component. In the past, I have been using multiple useQuery calls to chain query responses. While I am not against the approach it made my component needlessly complex. 

This time around I am using the `queryFn` function along with calling the queries manually. Here is what my code looks like. Please ignore any mistakes in the code I just wanted to throw the idea out there and ask for feedback

```
const sankeyGrpah = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
  getSankeyGraph: builder.query({
  async queryFn(args, queryApi, extraOptions, baseQuery){
     const sankeyGraphQuery = queryApi.dispatch(sankeyApi.endpoints.getSankeyGraphBase.initiate(arg));
      const { unsubscribe: unsubscribeFromSankeyGraphQuery } =
          sankeyGraphQuery;
        const { data } = await sankeyGraphQuery;
        
        if(data){
          const nodesDataQuery = queryApi.dispatch(nodesApi.endpoints.getNodesData.initiate(data.ids));
          const linksDataQuery = queryApi.dispatch(linksApi.endpoints.getLinksData.initiate(data.ids));
          
         const {unsubscribe: unsubscribeFromNodesDataQuery} = nodesDataQuery;
          const {unsubscribe: unsubscribeFromLinksDataQuery} = linksDataQuery
          const nodesData = await nodesDataQuery;
          const linksData = await linksDataQuery
          ///rest of transformation logic


          unsubscribeFromNodesDataQuery()
          unsubscribeFromLinksDataQuery()
          // return data in queryFn format
        }
  }
  })
  })
  })
 ```

**Comment by phryneas** [comment]
Hmm. I'd assume that you're probably better off just calling `baseQuery` instead of invoking other endpoints.

**Comment by nouman91** [comment]
Thank you @phryneas for responding. 
Would you mind explaining a bit more? I did not quite get it. How would I call baseQuery in this use case?

**Comment by phryneas** [comment]
Invoking other endpoints will save them in cache - but since you don't have a concept of a lifetime in your `queryFn` and thus immediately unsubscribe them, they will soon be cache-collected. Essentially, you add a lot of complexity around what should probably be "make three api requests in a row and safe a calculated final result".

**Comment by nouman91** [comment]
I hear you, and I think what you say makes sense. But here are a few points that I have:
- I have to do 5 API calls in total
- The API endpoints that I am calling have query building & response handling baked in. If I go with baseQuery route (I have explored it, thank you!) I need to reimplement that logic somehow here.
-  On the topic of subscription I am ok with not un-subscribing them. I was following the documentation, and for my use case, it's fine to keep them.
