### ISSUE TITLE
[RTK Query] Pending queries aborted

### ISSUE THREAD

**Issue by atillaaliyev** [reduxjs/redux-toolkit#4089]
Hi, 
I'm using RTK Query on a desktop application , you can think like Electron project. Anyway, when the query was started, backend creates new thread and it puts this thread into thread pool. Thread starting is pending status for me and I hava a lot of queries and threads in parallel. I am able to have one more thread in thread pool. And when I got a error, backend releases thread pool. This meaning, threads go to space and status of this pending won't change never.
Thus, I need to abort in pending queries if I got a error from any query. I didnt find anything about it.

**Comment by markerikson** [comment]
RTK Query doesn't really expose a way to abort queries. Our general assumption is that even if you switch from `useGetPokemonQuery("pikachu")` to `useGetPokemonQuery("bulbasaur")`, the previous request will complete and get cached.  If another component needs that data, great, if not it will get removed from the cache when the timer expires.

**Comment by atillaaliyev** [comment]
> RTK Query doesn't really expose a way to abort queries. Our general assumption is that even if you switch from `useGetPokemonQuery("pikachu")` to `useGetPokemonQuery("bulbasaur")`, the previous request will complete and get cached.  If another component needs that data, great, if not it will get removed from the cache when the timer expires.  

But my case is exception and i have to find solution. Maybe i can reset api slice, that time the pending status queries remove from api slice. But i will lost caching data. Do you have any solution in my case or my solution is one way in this situation?

**Comment by markerikson** [comment]
What does actually _mean_ to abort a pending query in this case?  What are you expecting to happen?

**Comment by atillaaliyev** [comment]
I show the Backdrop according to pending status.

```
  const isPendingQueries = useAppSelector((state: RootState) =>
    Object.values(state.api.queries).some((query) => {
      return !(query?.endpointName ?? '').endsWith('Async') && query?.status === 'pending'
    }),
  )
  const isPendingMutations = useAppSelector((state: RootState) =>
    Object.values(state.api.mutations).some((mutation) => {
      return !(mutation?.endpointName ?? '').endsWith('Async') && mutation?.status === 'pending'
    }),
  )


  const showDebouncedBackdrop = useDebounce(
    isPendingQueries || isPendingMutations
    1200,
  )
```

Because of this, I will show infinite loading after release the thread pool. I don't want pending status queries when I got error.

**Comment by atillaaliyev** [comment]
I solved my problem. I stored abort functions of all queries and mutations. 
```
const customFetchBaseQuery: BaseQueryFn<
  FetchArgs,
  unknown,
  FetchError | RipperError | DbLoggerError,
  Record<string, unknown>,
  Record<string, unknown>
> = async (arg, { getState, dispatch, abort }) => {
  const queryKey = uuid()
  const {
    layout: { pageData },
  } = getState() as RootState

  dispatch(commitRTKQueryAbortFuncs({ key: queryKey, fn: abort }))
  ......
}
```
After that, I call this callback;
```
const callbackFn = <T>(props: CallbackFnType<T>) => {
  const { resolve, reject, response, mapperFn, getState, queryKey,dispatch } = props
  const { layout } = getState() as RootState
  const { RTKQueryAbortFuncs } = layout ?? {}
  if (response) {
    const data = JSON.parse(response as string)
   ....

    if (Object.prototype.hasOwnProperty.call(data ?? {}, 'traceId')) {
      RTKQueryAbortFuncs.filter((x) => x.key !== queryKey).forEach(({ fn }) => {
        fn(`It was aborted by ${data.traceId} trace id.`)
      })
      reject({
        error: {
          message: data.message,
          traceId: data.traceId,
        },
      })
    } else if (Object.prototype.hasOwnProperty.call(data ?? {}, 'ERROR_MESSAGE')) {
      RTKQueryAbortFuncs.filter((x) => x.key !== queryKey).forEach(({ fn }) => {
        fn(`It was aborted by specific error.`)
      })
      reject({
        error: {
          message: data.ERROR_MESSAGE,
          traceId: '',
        },
      })
    } else {
      ......

      dispatch(removeRTKQueryAbortFuncs(queryKey))
      resolve({
        data,
        meta,
      } as unknown as T)
    }
  } else {
    RTKQueryAbortFuncs.filter((x) => x.key !== queryKey).forEach(({ fn }) => {
      fn(`It was aborted by system error.`)
    })
    reject({
      error: {
        message: 'Data getirirken sorun meydana geldi.',
        traceId: '',
      },
    })
  }
}
```

And after, in the loading.tsx, I coded this;

`  if (!(isPendingQueries || isPendingMutations)) dispatch(resetRTKQueryAbortFuncs())
`
