### ISSUE TITLE
Can't build RTK 2.0 with react-scripts

### ISSUE THREAD

**Issue by brightsider** [reduxjs/redux-toolkit#4097]
In the project, I use this `import { createApi } from '@reduxjs/toolkit/query/react';`.

The project has the last react version and node18.
When I try to build with the command `react-scripts build` I always get this error:

`Module not found: Error: Package path ./query//react is not exported from package PROJECT_PATH/node_modules/@reduxjs/toolkit (see exports field in PROJECT_PATH/node_modules/@reduxjs/toolkit/package.json)`

The package built well with version 1.9.7, but broke on 2.0.1 and 2.0.0.

**Comment by markerikson** [comment]
What version of `react-scripts` are you using?  We've tested and confirmed that RTK 2.0 builds with both CRA4 and CRA5.

**Comment by brightsider** [comment]
@markerikson "react-scripts": "5.0.1"

**Comment by markerikson** [comment]
@brightsider hmm. Could you attach a Github repo that shows this error happening when you build it?  Like I said, we actually build with CRA5 in our CI and it works there.

**Comment by brightsider** [comment]
looks like bug on our side with imports
