### ISSUE TITLE
Use a branded Promise type for always-resolved Promises

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [reduxjs/redux-toolkit#4101]
Coming over from https://github.com/typescript-eslint/typescript-eslint/issues/7008#issuecomment-1862478574: there is a known annoyance with the [@typescript-eslint/no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises) lint rule that it flags the Promises created by `createAsyncThunk` as _"floating"_ if not handled, despite those Promises being known "safe" ones that never resolve. There's no way for the lint rule to know that these Promises are safe.

That issue tracks adding an `allow` option to the lint rule that would let users allowlist these Promises. But in order to help with RTK, the known safe Promises would need some kind of specific type that can be added to the rule's allowlist. +1 to @phryneas's suggestion:

> So, it would be nice if we could mark those promises with some kind of branded type to them to signal to eslint that these promises can be handled, but don't need to.

We're up for adding in `allow` on our end if you're up for adding that branded type here! Is that something you're up for? Even if this issue is marked as blocked on us implementing the `allow` option, as long as that's the only blocker we're good to go.

I'd be happy to contribute the actual code change to RTK myself if you think it's doable for a first-timer. 😄

**Comment by markerikson** [comment]
Sure, happy to take that PR :)

I will say that the promise / error handling logic inside `createAsyncThunk` is fairly gnarly, but not impossible to deal with.

**Comment by JoshuaKGoldberg** [comment]
Btw I just edited the OP to make it clear what the changes in a user's ESLint config would be. Only realized after the fact I was never clear on that. Sorry 🙂
