### ISSUE TITLE
Typescript Errors for Custom Middleware 

### ISSUE THREAD

**Issue by DevPowers** [reduxjs/redux-toolkit#4105]
Typescript error: TS2719: Type is not assignable to type

This previously worked but since upgrading to 2.1 I am seeing this error. I also tried retyping fetchUserResourcesUponLogin as 'Middleware' but that just fails with another type error.  The documents could be more clear on how to set up custom middleware in Typescript.
 

MIddleware function:

```
export const fetchUserResourcesUponLogin =
    ({ dispatch, getState }) =>
    (next: Dispatch) =>
    (action: PayloadAction<any>) => {
        const result = next(action);
        if (action.type === loginAccount.type) {
            const state: AccountState = getState().account;
            if (state.isSubscriber) {
                dispatch(userAPI.endpoints.getUserResources.initiate());
            }
        }
        return result;
    };
```

Usage:

```
const store = configureStore({
    reducer: rootReducer,
    middleware: (getDefaultMiddleware) =>
        getDefaultMiddleware({ serializableCheck: false, immutableCheck: false })
            .concat(fetchUserResourcesUponLogin)
});

const { dispatch } = store;
export type RootState = ReturnType<typeof store.getState>;
```

**Comment by EskiMojo14** [comment]
As covered in the [migration guide](https://redux-toolkit.js.org/usage/migrating-rtk-2#middleware-type-changed---middleware-action-and-next-are-typed-as-unknown), Middleware is now typed so that `action` is an unknown value, because *anything* can be dispatched.

Assuming your `loginAccount` is a normal RTK action creator, you can use its [attached `.match` method](https://redux-toolkit.js.org/api/createAction#actioncreatormatch) to ensure it's a matching action:

```ts
export const fetchUserResourcesUponLogin: Middleware<
  {},
  RootState,
  ThunkDispatch<RootState, unknown, UnknownAction>
> =
  ({ dispatch, getState }) =>
  (next) =>
  (action) => {
    const result = next(action);
    if (loginAccount.match(action)) {
      const state = getState().account;
      if (state.isSubscriber) {
        dispatch(userAPI.endpoints.getUserResources.initiate());
      }
    }
    return result;
  };
```

**Comment by DevPowers** [comment]
@EskiMojo14 Thanks for the reply. I've also tried that and it does resolve the initial Type issue, but results in another one [TS2456: Type alias RootState circularly references itself.] Now I get a circular reference error due to the custom middleware referencing the RootState, and the RootState also containing the fetchUserResourcesUponLogin function. 



Code below and the fetchUserResourcesUponLogin function both show the same circular typescript error:
```
// Infer the `RootState` and `AppDispatch` types from the store itself SRC: https://redux-toolkit.js.org/tutorials/typescript#define-root-state-and-dispatch-types 
export type RootState = ReturnType<typeof store.getState>;
```

**Comment by EskiMojo14** [comment]
@DevPowers fair point - updated

**Comment by DevPowers** [comment]
@EskiMojo14 That resolve the type issue, thanks !

**Comment by DevPowers** [comment]
I stand by the docs should be updated to reflect an example with this though, that solution seems a bit tricky for someone to workout on their own. 🙏
