### ISSUE TITLE
undefined is not a function on config RTK with Typescipt

### ISSUE THREAD

**Issue by luanndm-dream** [reduxjs/redux-toolkit#4109]
A had a failing in 

<img width="319" alt="Screenshot 2024-01-22 at 16 06 09" src="https://github.com/reduxjs/redux-toolkit/assets/113851050/dc12705c-0271-4ea0-bb05-1a9d4ee70f12">
And this is all my file TS with RTK

Im using:
 "react": "18.2.0",
    "react-native": "^0.71.0",
    "react-redux": "^9.1.0",
    "@reduxjs/toolkit": "^2.0.1",
    "@types/react-redux": "^7.1.33",
**store.js**
import { configureStore } from "@reduxjs/toolkit";
import userReducer from './userSlice'

export const store = configureStore({
  reducer: {
    user: userReducer,
  },
  // middleware(getDefaultMiddleware) {
  //   return getDefaultMiddleware().concat(thunk)
  // },
})

export type RootState = ReturnType<typeof store.getState>
export type AppDispatch = typeof store.dispatch

**userSlice.ts**

// userSlice.ts
import { PayloadAction, createSlice } from "@reduxjs/toolkit";
import { RootState } from "redux/store";

export interface UserInfo {
  accessToken: string;
  role?: string | undefined;
}

const initialState: UserInfo = {

    accessToken: 'sadkjhgasdhjgashj',
    role: undefined,

};

const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    setUserInfo: (state, action: PayloadAction<UserInfo>) => {
      state.accessToken = '12312312312'
      state.role = '1'
    },
  },
});

export const { setUserInfo } = userSlice.actions;
export const userSelector = (state: RootState)=> state.user
export default userSlice.reducer;

**reduxHook.ts**
import { useDispatch, useSelector,TypedUseSelectorHook } from 'react-redux'
import type { RootState, AppDispatch } from './store'

// Use throughout your app instead of plain `useDispatch` and `useSelector`
export const useAppDispatch = () => useDispatch<AppDispatch>();
export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector

my folder RTK (sry about wrong write lice mistake ^^)
<img width="226" alt="Screenshot 2024-01-22 at 16 09 27" src="https://github.com/reduxjs/redux-toolkit/assets/113851050/a007fcb3-eb88-425a-9e73-bdfbe73f9ca8">

**Comment by markerikson** [comment]
I suspect you have multiple copies of the `redux` package in your project, and that it's loading Redux 4.x (which does not have `isPlainObject` loaded.

Try removing `@types/react-redux` (which you don't need anyway - React-Redux v8 and v9 include their own types), and check your lockfiles to make sure there are no other versions of Redux included in the project.

**Comment by mehranjavid** [comment]
<img width="442" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/39021904/6b1bbbd1-5673-4793-91cb-e12563c280de">
<img width="1078" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/39021904/fe36c70f-03e2-4bea-88ab-2ee3a4ab41fc">
<img width="613" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/39021904/b37ddedf-72a1-4f50-9e37-ce8613c96305">

I am gettting this error 
 my dependencies 
`
  "dependencies": {
    "@reduxjs/toolkit": "^2.2.5",
    "react": "18.2.0",
    "react-native": "0.74.1",
    "react-redux": "^9.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.74.83",
    "@react-native/eslint-config": "0.74.83",
    "@react-native/metro-config": "0.74.83",
    "@react-native/typescript-config": "0.74.83",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "babel-plugin-module-resolver": "^5.0.2",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
`
