### ISSUE TITLE
npm registry not found new latest version 

### ISSUE THREAD

**Issue by Aurorxa** [reduxjs/redux-toolkit#4111]
![image](https://github.com/reduxjs/redux-toolkit/assets/25677587/270648fe-f26a-45c9-8ac3-9cc26ae35658)

![image](https://github.com/reduxjs/redux-toolkit/assets/25677587/772bd264-89ce-4326-ae08-150d0d757a9e)

**Comment by markerikson** [comment]
Yeah, it looks like we tried to use our CI to publish 2.0.2, but the actual publish step failed due to test failures :)

We need to get some other changes out in the near future anyway.  Thanks for pointing this out!

**Comment by markerikson** [comment]
We removed the `2.0.2` tag, and have published `2.1.0`.

**Comment by Aurorxa** [comment]
thanks
