### ISSUE TITLE
Ensure 2.1.0 features are in docs

### ISSUE THREAD

**Issue by EskiMojo14** [reduxjs/redux-toolkit#4118]
some of the features added in [v2.1.0](https://github.com/reduxjs/redux-toolkit/releases/tag/v2.1.0) are currently undocumented - need adding to docs

**Comment by riqts** [comment]
Would love to jump in and document these, for reference, do you know off the top of your head which of these changes from 2.1.0 post have/have not been updated? I am happy to do some of my own research on the actual workings and what changed for the documentation update, but a small nudge in the right direction might be useful.

- adds withTypes methods to listenerMiddleware and createDraftSafeSelector
- ~adds a skipPollingIfUnfocused option to RTK Query~
- ~adds the ability to customise the createSelector instance used by RTK Query~
- reworks slice selector logic to avoid depending on this value (does this need documentation on the site?)
- fixes the order and inference of create.asyncThunk type parameters
- fixes requirements for meta fields returned from queryFns
- marks promises that will never reject as safe, in preparation for https://github.com/typescript-eslint/typescript-eslint/issues/7008

**Comment by EskiMojo14** [comment]
the last four don't need documentation, they're essentially bug fixes.

as you've noted, skipPollingIfUnfocused and createSelector for RTKQ are now documented, so it should just be making sure .withTypes is documented :)
