### ISSUE TITLE
Error while importing setupListeners from @reduxjs/toolkit/dist/query/core/setupListeners

### ISSUE THREAD

**Issue by pugsh** [reduxjs/redux-toolkit#4130]
I am trying to use `setupListeners` from the [example](https://redux-toolkit.js.org/rtk-query/api/setupListeners). But getting errors as below.
`
Module not found: Error: Package path ./dist/query/core/setupListeners is not exported from package /node_modules/@reduxjs/toolkit (see exports field in /node_modules/@reduxjs/toolkit/package.json)
`

Using `"@reduxjs/toolkit": "^2.1.0"` with Typescript `5.3.3`

**Comment by EskiMojo14** [comment]
you shouldn't ever be importing from dist/ directly, you should import from the "@reduxjs/toolkit/query" entry point.

**Comment by pugsh** [comment]
> you shouldn't ever be importing from dist/ directly, you should import from the "@reduxjs/toolkit/query" entry point.

Thanks for pointing out.
