### ISSUE TITLE
Difference in invalidatesTags between query and mutation

### ISSUE THREAD

**Issue by arp** [reduxjs/redux-toolkit#4133]
I've been trying to figure out why a lazy query I run doesn't invalidate another query via providesTags/invalidatesTags. Once I changed the lazy invalidating query to be a mutation in the API definition, without any other difference it started invalidating the tags correctly.

Is this behavior expected?

My query doesn't change anything, and it was getting executed every time when it was a query. So it wasn't a cache issue. The query was getting executed, but it didn't invalidate the tags.

**Comment by EskiMojo14** [comment]
queries can only provide tags, and mutations can only invalidate them. 

queries fetch data, and mutations modify them. queries shouldn't result in other queries needing refetching, mutations should.

**Comment by arp** [comment]
Thanks! That wasn't clear to me from the documentation, even though I see it there now.

My point for invalidating a tag by a query is that I might refresh data from the server, and thus would prefer such fetch to also invalidate all the derived data that might be stale compared to that most recent fetch.

Say, I have a query that requests all posts and also a query that requests all users who posted. By refreshing posts I would like to automatically refresh all the users who posted, too.
