### ISSUE TITLE
Old browsers are not supported

### ISSUE THREAD

**Issue by fedorovsky** [reduxjs/redux-toolkit#4140]
Hello. I have a problem when using in older browsers. Since you have removed support for older browsers and are no longer transpiling optional chaning.

My project needs to run on Chrome 62 version (for flash player) and it doesn't support optional chaning. I have made aliases and am trying to force transpilate your output files but another problem appears. You are using the latest version of Immer which also does not transpile optional chaning.

I can force your files to process using Babel but I can't get to the Immer output files

Tell me what to do in this situation.

I see in the my bundle:

<img width="979" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/7301838/b9320409-0b54-4dd2-9c6d-ad33b4c1d9e7">

My webpack config:

```
alias: {
      '@reduxjs/toolkit$': path.resolve('node_modules', '@reduxjs/toolkit/dist/redux-toolkit.legacy-esm.js'),
      '@reduxjs/toolkit/query$': path.resolve('node_modules', '@reduxjs/toolkit/dist/query/rtk-query.legacy-esm.js'),
      '@reduxjs/toolkit/query/react$': path.resolve(
        'node_modules',
        '@reduxjs/toolkit/dist/query/react/rtk-query-react.legacy-esm.js'
      ),
    },
```
.....
.....
.....
```
        test: /\.(js|jsx|ts|tsx)$/,
        include: [
          path.resolve('./src'),
          path.resolve('node_modules', '@reduxjs/toolkit/dist/redux-toolkit.legacy-esm.js'),
          path.resolve('node_modules', '@reduxjs/toolkit/dist/query/rtk-query.legacy-esm.js'),
          path.resolve('node_modules', '@reduxjs/toolkit/dist/query/react/rtk-query-react.legacy-esm.js'),
        ],
```

**Comment by markerikson** [comment]
Yes, you would also need to transpile Immer's bundle as well.

**Comment by fedorovsky** [comment]
Yes. But webpack allows you to include only 1 level of nesting.

For example

`path.resolve('node_modules', '@reduxjs/toolkit/dist/redux-toolkit.legacy-esm.js'),`

If I'm trying to include your internal dependencies

`path.resolve('node_modules', 'reselect'),`

This doesn't give the desired result

**Comment by fedorovsky** [comment]
Thanks, I added in aliases and it works for me

**Comment by mindhacker0** [comment]
@fedorovsky thanks![Image](https://github.com/user-attachments/assets/88ec76b5-36db-404e-befc-405ed2fb7152)
![Image](https://github.com/user-attachments/assets/15830682-41bf-4e1d-bb18-49ffbb031c54)
that slove the problem,i guess in .legacy-esm.js use es5 standards，no es6+ syntax been searched in those files.
