### ISSUE TITLE
Nullable/Optional array serializes to an empty array

### ISSUE THREAD

**Issue by IngoVals** [reduxjs/redux-toolkit#4148]
RTK Query with auto generated code via OpenAPI definition

Redux-Toolkit@1.9.5

PATCH action on a type that has an array property. The type object is autogenerated and defines the property correctly as both optional and nullable.

Sending either null or undefined in that property results in the payload of the fetch having an empty array.

Is this some problem with serialization or?

**Comment by markerikson** [comment]
Closing due to lack of further info or an example.
