### ISSUE TITLE
React-immutable-state-invariant Slows Performance

### ISSUE THREAD

**Issue by cole-robertson** [reduxjs/redux-toolkit#415]
Does Redux toolkit automatically come with the package React-immutable-state-invariant? I am getting terrible performance updating my state with some large objects since it seems that React-immutable-state-invariant has a detect mutations function that looks through all the the keys of this object multiple times.

I do not want to use this package. Looking at the github it seems to say that you should not use this in production. I don't want to even use it in development since Redux toolkit has immer for direct state mutations anyway.

How can I configure Redux Toolkit to not use this middleware? Thank you

**Comment by cole-robertson** [comment]
I see https://github.com/reduxjs/redux-toolkit/issues/412 
Is there not a current way to configure middleware right now?

**Comment by markerikson** [comment]
Just answered this on Reddit, but I'll answer here as well:

Yes, we use `immutable-state-invariant` by default, **in development mode only**.  And yes, it is a deep check of your entire state, so if you have a rather large state, that will slow things down.

Per the docs, [you can disable either of the dev check middleware by using `getDefaultMiddleware()` options](https://redux-toolkit.js.org/api/getDefaultMiddleware#customizing-the-included-middleware).

**Comment by phryneas** [comment]
See [the docs for configureStore](https://redux-toolkit.js.org/api/configureStore) - you can use different middlewares.

```js
const store = configureStore({
  reducer: {/*...*/},
  middleware: [...getDefaultMiddleware({immutableCheck: false})]
})
```

**Comment by ramiel1999** [comment]
Is there any place in the docs where it is mentioned that these development middlewares affect performance during dev. I was so upset about the performance of my react native app, so I dispatched an action that does nothing and I was able to see that it was still slow. I remembered something about additional development middlewares added, so I turned them off and suddenly it is much faster. 

This really need to be somewhere in the docs

**Comment by phryneas** [comment]
If the development middlewares take longer than 32ms per action, they will print warnings to your console.log.
Did you ignore that?

**Comment by ramiel1999** [comment]
```
// Ignores redux warning about serialization took a long time
LogBox.ignoreLogs(["SerializableStateInvariantMiddleware"]);
```

Yup there it is. My bad

**Comment by alexisgahon** [comment]
Update: `getDefaultMiddleware` ne s'importe plus.

```ts
const store = configureStore({
  reducer: {/*...*/},
  middleware: (getDefaultMiddleware) => [...getDefaultMiddleware({immutableCheck: false})]
})
```

**Comment by atultiwaree** [comment]
Will it affect my app in production mode ??

**Comment by balsick** [comment]
> Update: `getDefaultMiddleware` ne s'importe plus.
> 
> ```ts
> const store = configureStore({
>   reducer: {/*...*/},
>   middleware: (getDefaultMiddleware) => [...getDefaultMiddleware({immutableCheck: false})]
> })
> ```

In case of typescript, what worked for me is this:
```ts
middleware: getDefaultMiddleware =>
    getDefaultMiddleware({immutableCheck: false}),
```

**Comment by EskiMojo14** [comment]
yep - the spread is unnecessary, and in RTK 2.0 [Typescript users are now required to use a Tuple instance](https://redux-toolkit.js.org/usage/migrating-rtk-2#non-default-middlewareenhancers-must-use-tuple). If you want to add more middlewares to the defaults, you should use the provided `concat` and `prepend` methods from the returned Tuple instance.
