### ISSUE TITLE
I have tried all the above mentioned examples and nothing seems to work. I tried deploying to aws ec2 and faced the same errors and thought maybe I was configuring nginx the wrong way, I then opted for render.com only for it to work for a few hours and started giving errors of not authorised yet the cookies have been set on the browser.

### ISSUE THREAD

**Issue by FIDELIS-TUWEI** [reduxjs/redux-toolkit#4154]
I have tried all the above mentioned examples and nothing seems to work. I tried deploying to aws ec2 and faced the same errors and thought maybe I was configuring nginx the wrong way, I then opted for render.com only for it to work for a few hours and started giving errors of not authorised yet the cookies have been set on the browser. 

Here is my server file:

const dotenv = require("dotenv");
const path = require("path");
const connectDB = require("../config/connectDB");
const express = require('express');
let app = express();

connectDB();

// Server Setup
const PORT = process.env.PORT || 5500;

// Middleware
require("./middleware")(app);

//Routes
require("./routes/index")(app);

app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`)
});

// Create route
app.get("/", (req, res) => {
    res.send("Server is running");
})

process.on('unhandledRejection', error => {
    console.error('unhandledRejection', error)
});

index.js file: 
module.exports = (app) => {
    const express = require('express');
    const cors = require('cors');
    const rateLimit = require("express-rate-limit");
    const bodyParser = require('body-parser');
    const helmet = require("helmet");
    const morgan = require("morgan");
    const cookieParser = require("cookie-parser");
    const errorHandler = require("../middleware/error");
    const mongoSanitize = require("express-mongo-sanitize");
    const hpp = require("hpp");
    const addKey = require("./addKey");

    // Express trust proxy settings
    app.set('trust proxy', 1)
    app.get('/ip', (request, response) => response.send(request.ip))
    app.get('/x-forwarded-for', (request, response) => response.send(request.headers['x-forwarded-for']));
    app.set('trust proxy', ['loopback', 'linklocal', 'uniquelocal']) // specify multiple subnets as an array

    // Add Key Generator Middleware
    app.use(addKey);

    // Middleware
    let limiter = rateLimit({
        max: 200,
        windowMs: 10 * 60 * 1000,
        message: "Too many requests from this IP. Please try again later."
    });
    
    app.use('/hin', limiter);
    app.use(helmet());
    app.use(helmet.crossOriginResourcePolicy({ policy: "same-origin" }));
    
    if (process.env.NODE_ENV !== 'production') {
        app.use(morgan('dev'));
    }
    app.use(bodyParser.json({ limit: "5mb" }));
    app.use(bodyParser.urlencoded({ 
        limit: "5mb",
        extended: true 
    }));
    app.use(cors({
        credentials: true,
        origin: ["http://localhost:3000", "https://www.work-orders.online", "https://work-orders.online"],
        allowedHeaders: ["Authorization", "Content-Type"],
        maxAge: 3600,
        methods: ["GET", "POST", "PUT", "DELETE"],
    }));
    app.use(cookieParser());
    app.use(express.json()); // To parse JSON data in the request body
    app.use(express.urlencoded({ extended: true })); // To parse form data in the request body
    // Prevent HTTP Parameter pollution
    app.use(hpp());

    // Prevent XSS
    app.use(helmet.contentSecurityPolicy());

    // Prevent SQL Injection
    app.use(mongoSanitize());

    // Error Middleware
    app.use(errorHandler);
};

protect middleware: 

const protect = asyncHandler(async (req, res, next) => {
    try {
        const token = req.cookies.token;
        if (!token) {
            return next(new ErrorResponse("Not authorized, invalid token", 401));
        }

        // Verify token
        const verified = jwt.verify(token, process.env.JWT_SECRET);

        // Get user id from the token
        const user = await User.findById(verified.id);

        if (!user) {
            return next(new ErrorResponse("User not found, please login", 401));
        }
        req.user = user;

        next();
    } catch (error) {
        return next(new ErrorResponse("Not authorized, no token", 401));
    }

});

Redux rtk configuration files:

import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

const baseQuery = fetchBaseQuery({ 
    baseUrl: "",
    credentials: "include",
    prepareHeaders: (headers, { getState }) => {
        const token = getState().auth.token;
        if (token) {
            headers.set("authorization", `Bearer ${token}`);
        }
        return headers;
    } 
});

export const apiSlice = createApi({
    baseQuery,
    tagTypes: ["Users", "WorkOrder"],
    endpoints: (builder) => ({}),
});

import { apiSlice } from "../api/apiSlice";
const serverUrl = import.meta.env.VITE_SERVER_URL

export const authApiSlice = apiSlice.injectEndpoints({
    endpoints: (builder) => ({
        login: builder.mutation({
            query: (data) => ({
                url: `${ serverUrl }/login`,
                method: "POST",
                body: data,
            }),
        }),
        logout: builder.mutation({
            query: () => ({
                url: `${ serverUrl }/logout`,
                method: "POST",
            }),
        }),
    })
});

export const { 
    useLoginMutation, 
    useLogoutMutation, 
} = authApiSlice;

rtk to get employees:

import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
const serverUrl = import.meta.env.VITE_SERVER_URL;

const baseQuery = fetchBaseQuery({
    baseUrl: serverUrl,
    credentials: "include",
    prepareHeaders: (headers, { getState }) => {
        const token = getState().auth.token;
        if (token) {
            headers.set("Authorization", `Bearer ${token}`);
        }
        return headers;
    },
});

export const employeesApi = createApi({
    reducerPath: "employeesApi",
    baseQuery,
    tagTypes: ["Employee"],
    endpoints: (builder) => ({
        createEmployee: builder.mutation({
            query: (values) => ({
                url: `/new/employee`,
                method: "POST",
                body: values,
            }),
            invalidatesTags: ["Employee"],
        }),
        employees: builder.query({
            query: (page) => ({
                url: `/all/employees?pageNumber=${page}`,
                method: "GET",
            }),
            providesTags: ["Employee"],
        }),
        singleEmployee: builder.query({
            query: (id) => ({
                url: `/single/employee/${id}`,
                method: "GET",
            }),
            providesTags: ["Employee"],
        }),
        employeeData: builder.query({
            query: (id) => ({
                url: `/employee/data/${id}`,
                method: "GET",
            }),
            providesTags: ["Employee"],
        }),
        queryAllEmployees: builder.query({
            query: () => ({
                url: `/query/all/employees`,
                method: "GET",
            }),
            providesTags: ["Employee"],
        }),
        employeeWorkCount: builder.query({
            query: (id) => ({
                url: `/employee/work/count?id=${id}`,
                method: "GET",
            }),
            providesTags: ["Employee"],
        }),
        countAllEmployees: builder.query({
            query: () => ({
                url: `/count/employees`,
                method: "GET",
            }),
            providesTags: ["Employee"],
        }),
        editEmployee: builder.mutation({
            query: ({id, values}) => ({
                url: `/edit/employee/${id}`,
                method: "PUT",
                body: values,
            }),
            invalidatesTags: ["Employee"],
        }),
        deleteEmployee: builder.mutation({
            query: (id) => ({
                url: `/delete/employee/${id}`,
                method: "DELETE",
            }),
            invalidatesTags: ["Employee"],
        }),
    }),
});

export const {
    useCreateEmployeeMutation,
    useEmployeesQuery,
    useSingleEmployeeQuery,
    useEmployeeDataQuery,
    useQueryAllEmployeesQuery,
    useEmployeeWorkCountQuery,
    useCountAllEmployeesQuery,
    useEditEmployeeMutation,
    useDeleteEmployeeMutation,
} = employeesApi;

Can anyone help, please

_Originally posted by @FIDELIS-TUWEI in https://github.com/reduxjs/redux-toolkit/issues/2095#issuecomment-1926397612_

**Comment by phryneas** [comment]
Please, generally, when posting, make sure to format your code using the GitHub editor - without code highlighting, this is borderline unreadable.

That said, unfortunately you're in the wrong place for this question. RTK Query doesn't do anything to your cookies - we just call `fetch` with the options you provide. Cookies are a thing between your browser and your server, your in-browser JavaScript code (apart from `include`) has nothing to do with it.

What you can do is look at the cookies in your requests, check if the sent cookie domains are right, check your network tab (I believe chrome shows which cookies have been sent and why and which have not) and then read up on tons of documentation.

I'm sorry, but this not only has not a lot to do with our library, it's also very difficult to troubleshoot and all of that has to happen on your machine, so we can't help you with this.
