### ISSUE TITLE
File was processed with these loaders

### ISSUE THREAD

**Issue by deepaklegitbytes** [reduxjs/redux-toolkit#4156]
./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     return false;
|   }
>   if (cache?.has(value)) return false;
|   const entries = getEntries != null ? getEntries(value) : Object.entries(value);
|   const hasIgnoredPaths = ignoredPaths.length > 0;

**Comment by markerikson** [comment]
As of RTK 2.0, we ship fully modern JS syntax. If your build system or target environment doesn't support that, you'll need to either transpile it yourself, or alias your build setup to use the `legacy-esm` build artifact.
