### ISSUE TITLE
1.9 to 2.0 migration broke the typing of the `rtkQueryErrorLogger` example

### ISSUE THREAD

**Issue by tylerlaprade** [reduxjs/redux-toolkit#4159]
We are using error-logging middleware lifted almost exactly from [the documentation](https://redux-toolkit.js.org/rtk-query/usage/error-handling#handling-errors-at-a-macro-level). 
```
const rtkQueryErrorLogger: Middleware = (store: MiddlewareAPI) => (next) => (action: PayloadAction) => {
  if (isRejectedWithValue(action) && userHasAnyPermission(store.getState())) {
    toast.error(createToast(action));
  }

  return next(action);
};
```
This worked perfectly fine in 1.9, but the changes from `Any` to `Unknown` in 2.0 broke this. However, we've defined all our types correctly, as far as I can tell. Am I missing something obvious, or does the new version not play nicely with the example?

**Comment by markerikson** [comment]
What is "breaking", specifically? What errors are you seeing?  

Looking at this example, the use of `action: PayloadAction` is wrong, because the `action` argument _could_ be literally anything (which is why it's now typed as `unknown` by default).  So yeah, that does look wrong.

If you have code that assumes it's a `PayloadAction`, you'd need to use a type guard to do that check first, ie `isPayloadAction(action) && isSomethingThatExpectsAPayloadAction(action`).

**Comment by tylerlaprade** [comment]
Ah okay - I ended up removing the `PayloadAction` annotation as a temporary workaround anyway. I didn't realize that it was incorrect. This was my TypeScript error:

```
Type '(store: MiddlewareAPI<Dispatch<UnknownAction>, any>) => (next: (action: unknown) => unknown) => (action: { payload: void; type: string; }) => unknown' is not assignable to type 'Middleware<{}, any, Dispatch<UnknownAction>>'.
  Call signature return types '(next: (action: unknown) => unknown) => (action: { payload: void; type: string; }) => unknown' and '(next: (action: unknown) => unknown) => (action: unknown) => unknown' are incompatible.
    Type '(action: PayloadAction) => unknown' is not assignable to type '(action: unknown) => unknown'.
      Types of parameters 'action' and 'action' are incompatible.
        Type 'unknown' is not assignable to type '{ payload: void; type: string; }'.ts(2322)
```

**Comment by markerikson** [comment]
Yep, that error is "correct" in this case. The `action` value _could_ be anything, so for real type safety it's up to you to first do a typeguard check to verify what the _actual_ TS type is before you do anything with it. Thus, the type is `action: unknown` as the default, to force you to do that kind of check.
