### ISSUE TITLE
createAsyncThunk docs imply payloadCreator executes before pending action

### ISSUE THREAD

**Issue by dlwalsh** [reduxjs/redux-toolkit#416]
I understand `createAsyncThunk` executes in the following order:
1. Pending action
2. Payload creator
3. Fulfilled/rejected action

However this [code snippet](https://deploy-preview-374--redux-starter-kit-docs.netlify.com/api/createAsyncThunk#examples) implies something different:

```
const fetchUserById = createAsyncThunk(
  'users/fetchByIdStatus',
  async (userId, { getState }) => {
    const { loading } = getState().users
    if (loading !== 'idle') {
      return
    }
    const response = await userAPI.fetchById(userId)
    return response.data
  }
)
```

The `loading` flag is expected to be in the `idle` state. But by the time the payload creator is executed, the `loading` flag will have been changed to `pending`.

```
    [fetchUserById.pending]: (state, action) => {
      if (state.loading === 'idle') {
        state.loading = 'pending'
      }
    },
```

Is this a bug in the example code?

**Comment by markerikson** [comment]
Hmm.  Yeah, that does seem like a bug in the snippet.  The hazards of trying to write snippets that aren't necessarily executable :)

Can you file a PR against the `v1.3.0-integration` branch to change it to something more appropriate?

**Comment by dlwalsh** [comment]
Resolved by https://github.com/reduxjs/redux-toolkit/pull/417
