### ISSUE TITLE
[Question]: Getting single item from the list query with list specific params e.g sort

### ISSUE THREAD

**Issue by d-borys** [reduxjs/redux-toolkit#4162]
Hey! I hope this is the right place. 

So I'm pretty new to RTK Query, and I couldn't really find an answer online so I decided to post it here.  I'm wondering about handling following use case in my react-native app. 

I've got a screen that fetches details of a group, that group has a list of expenses and it accepts a `sort` param. 

In GroupDetailsScreen
`const {data: group, isLoading} = useGetGroupDetailsQuery({id, sort});`

Now I also have another screen, which allows seeing the details of a single expense. 
To my understanding, the general idea would be to reuse the query with selectFromResult like following: 
```ts
    const {groupId, expenseId} = route.params
    const {expense} = useGetGroupDetailsQuery({id: groupId}, {
        selectFromResult: ({data}) => ({
            expense: data?.expenses.find((expense) => expense.id === expenseId)!,
        }),
    })
```

This is the place where I'm getting my issue. Since the group details view uses a query with a sort param, I can't actually selectFromResult in a nested view, because I don't have that sort param that's only available in the list view (and only that request is cached).  A quick fix would probably be just passing the sort param to the nested expense details view, but that sounds wrong. 

I've come up with another idea which is adding a default sort value inside the serializeQueryArgs, but I'm not sure whether that's recommended or not. I'd appreciate any feedback and ideas. 

```ts
        getGroupDetails: builder.query<GroupDetailsResponse, {id: string, sort?: Sort}>({
            query: ({id, sort}) => ({
                url: `groups/${id}`,
                params: {
                    ...sort && {sort: `${sort.key},${sort.direction}`}
                }
            }),
            serializeQueryArgs: ({queryArgs}) => {
                return {id: queryArgs.id, sort: queryArgs?.sort || DEFAULT_SORT}
            },
            providesTags: (result, error, arg) => [{type: 'Group' as const, id: arg.id}]
        }),
```

**Comment by EskiMojo14** [comment]
you need the same arguments to retrieve the same cache entry. it's up to you how you make sure those same arguments are available to the components that need it, be it props or storing them in a slice.
