### ISSUE TITLE
Mistake in the last point for the example demonstration

### ISSUE THREAD

**Issue by 721-atikshaikh** [reduxjs/redux-toolkit#4163]
In the Pokemon example provided in the Redux Toolkit documentation, the demonstration of caching behavior is accurately explained through the first three points. However, the fourth point might give the impression that clicking on "Refetch" will cause all Pokémon to be refetched. It should be clarified that refetching is specific to the Pokemon for which the refetch action is initiated, not all Pokemons.

I would like to contribute to the docs but just want to confirm first whether this is correct or not !

Link : https://redux-toolkit.js.org/rtk-query/usage/queries#example-observing-caching-behavior
![image](https://github.com/reduxjs/redux-toolkit/assets/149864892/c9361ee0-d9bf-4778-8606-bff4f05dbef7)

**Comment by EskiMojo14** [comment]
i think it's implied by "of a particular pokemon type", but if you think it could be phrased more clearly a PR is welcome.

**Comment by 721-atikshaikh** [comment]
Sure @EskiMojo14 will do it ! Thanks for the prompt reply
