### ISSUE TITLE
Is there a way to include React components in the transformed response?

### ISSUE THREAD

**Issue by tothdanielax** [reduxjs/redux-toolkit#4170]
I'm curious if there's a way to include a React component in the transformed response using @reduxjs/toolkit version 2.0.1. What I'm trying to do is to construct a user-friendly template interface already in the RTK Query for viewing templates within the relevant child components. 

For example:

```tsx
        getTemplatesInDirectoryView: builder.query<TreeDataNode[]>({
            query: () => '/information',
            transformResponse: (response: Template[]) => {
                return response.map((template) => ({
                    key: template._id,
                    title: template.filename,
                    isLeaf: true,
                    icon: <FileOutlined />, // error
                }));    
            }
         })
```

``
A non-serializable value was detected in an action, in the path: `payload.0.icon.$$typeof`. Value: Symbol("react.element")  
``

**Comment by EskiMojo14** [comment]
No, you shouldn't ever store React components in your Redux state.
