### ISSUE TITLE
Issue with React version 18.2.0

### ISSUE THREAD

**Issue by bietkul** [reduxjs/redux-toolkit#4182]
I'm getting an error when using redux toolkit query hooks in a project created by create-react-app.
<img width="955" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/20393043/c7b84066-ef40-4314-8d12-0c02540ea3fd">

Code
<img width="896" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/20393043/7d84f9d8-c60c-498d-8785-de5c4de09308">

Please help me to identify the issue.
The counter-example works though, the only issue with redux toolkit query and mutations.

**Comment by phryneas** [comment]
Are you actually using `ComponentOne` in JSX?

Generally, we have thousands of users with that exact tech combination (although I would not recommend using CRA nowadays), so that can't be the reason for your problems. Could you maybe share a minimal reproduction?

**Comment by bietkul** [comment]
The issue happened in a yarn workspace because of a duplicate copy for `react` in a package. Marking the `react` as external dependency for that package solved the issue.
