### ISSUE TITLE
RTK Query examples broken due to misformatted tsconfig.json files

### ISSUE THREAD

**Issue by jacklin213** [reduxjs/redux-toolkit#4185]
Commit b0ce4df in #4135 ended up formatting `tsconfig.json` files throughout the repo and appended trailing `,` which is [not valid JSON](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas).

This is causing examples in code sandbox on https://redux-toolkit.js.org/rtk-query/usage/examples to fail with 

```
Error
We weren't able to parse: '/tsconfig.json': Parse error on line 18:
...  "noEmit": true,  },}
----------------------^
Expecting 'STRING', got '}'
```

Suggest to exclude any `.json` files from being formatted with trailing commas

**Comment by aryaemami59** [comment]
@markerikson Yes sir
