### ISSUE TITLE
Possibly missing exports in 2.2.0

### ISSUE THREAD

**Issue by mattoni** [reduxjs/redux-toolkit#4192]
I'm relying on a couple types that were previously in `dist` that I was able to import - 

```
import {
    MaybeDrafted,
    PatchCollection,
} from "@reduxjs/toolkit/dist/query/core/buildThunks";
```

It seems in 2.2.0 I'm unable to import them. I'm using them in some functions used to generate patches based on some signals from a webhook, like so: 
![image](https://github.com/reduxjs/redux-toolkit/assets/5110855/465a63b4-2865-4b08-9616-a14c463be15e)

**Comment by mattoni** [comment]
Understood - but it'd be nice to have a way to export the patches with the correct typing since it's just a wrapper for the `api.util.updateQueryData`, so I guess I'm asking if this can be moved to a non-internal typing.

**Comment by EskiMojo14** [comment]
out of curiosity, why not just use `Array<ReturnType<typeof api.util.updateQueryData>>`?

**Comment by mattoni** [comment]
mostly because i overcomplicated it on accident :)

**Comment by EskiMojo14** [comment]
as both the `Draft` and `Patch` types are exported from immer (and we re-export `Draft`) i think both of these types are easily recreated, and `PatchCollection` can also be obtained via `ReturnType<ReturnType<typeof api.util.updateQueryData>>. therefore i think this can be closed.
