### ISSUE TITLE
Per-route state issue

### ISSUE THREAD

**Issue by emreakdas** [reduxjs/redux-toolkit#4197]
https://redux-toolkit.js.org/usage/nextjs#per-route-state In my nextjs project I need to reset a value in SPA navigation, this is the suggested solution, but this solution

Warning: Cannot update a component (`Page`) while rendering a different component (`Detail`). To locate the bad setState() call inside `Detail`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render ```

when I did a little research, this usage was allowed before, but now it is not. https://github.com/facebook/react/issues/18178#issuecomment-596875175 @markerikson has a comment here. if this usage is not allowed, why is this usage recommended in the document?

**Comment by markerikson** [comment]
This isn't an _ideal_ pattern, and that example probably _should_ move the dispatch into a layout effect or something. That said, if it's happening in the root of a component tree, I'd also expect that there _aren't_ any components that are subscribed at that point.
