### ISSUE TITLE
`TypedUseMutationTrigger` should not contain the word "Use"

### ISSUE THREAD

**Issue by tylerlaprade** [reduxjs/redux-toolkit#4203]
`TypedUseMutationTrigger` is a helpful wrapper for `MutationTrigger` (thanks for adding it by the way! It resolved an issue I was facing). However, the name is inconsistent. `TypedUseMutation` is a wrapper for `UseMutation`. The extra `Use` breaks the parallel naming structure.

**Comment by EskiMojo14** [comment]
huh, good spot - that's annoying, as renaming it is technically a breaking change. in the linked PR i've currently included a deprecated alias to indicate the change, but considering it's only been available for 2 days I'm tempted to just forgo that as i imagine the number of users affected will be very small

**Comment by EskiMojo14** [comment]
released in 2.2.1
