### ISSUE TITLE
Export Type Definitions From Exported Packages

### ISSUE THREAD

**Issue by ctaylor4874** [reduxjs/redux-toolkit#421]
Would it be possible to export the type definitions for `reselect`? I'm trying to define types using the exported `Selector` type from `reselect` but it is not exported. Here's what I'd like to be able to do:
```typescript
import { Selector } from "@reduxjs/toolkit";

export type MySelector = Selector<{isActive: true}, boolean>
```

**Comment by markerikson** [comment]
Yeah, I can throw that into the next beta as well.  In the meantime, you can directly import it from `reselect` yourself.

**Comment by markerikson** [comment]
Done in 1.3.
