### ISSUE TITLE
How to query multiple parameters

### ISSUE THREAD

**Issue by ravi-devo** [reduxjs/redux-toolkit#4214]
How can i past arguments to the query as it only accepts one parameter. But I want to pass postId and data. Code snippet is below.
addComment: builder.mutation({
            query: (postId, data) => ({
                url: `${POST_URL}/${postId}/comment`,
                method: 'POST',
                body: data
            })
        }),
export const {useAddCommentMutation} = postApiSlice;

...

const addCommentHandler = async () => {
        try {
            const res = await AddCommentAPI('postIdhere', {text: "Sometext"}).unwrap();
            console.log(`Response ${JSON.stringify(res)}`)
            if(res.message === 'Comment added successfully'){
                console.log(`Comment added successfully`)
                dispatch(addComment(res.data));
            }
        } catch (error) {
            toast.error(`Internal server error ${JSON.stringify(error)}`)
        }
    }
<Button className="mx-2" onClick={addCommentHandler}>Add Comment</Button>

**Comment by EskiMojo14** [comment]
use an object with postId and data properties.
