### ISSUE TITLE
Type 'Type | null' is not assignable to type 'WritableDraft<Type> | null'

### ISSUE THREAD

**Issue by jonybekov** [reduxjs/redux-toolkit#4217]
Hi, I cannot update object inside my reducer.

<img width="798" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/39439363/5e7807bb-8654-4e51-99ea-3ced848de538">

It's a simple reducer but ts yelling me that I cannot re-assign to object.
<img width="661" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/39439363/bd309591-62c8-48bd-a075-ce5add7a8879">

Segment is just my custom type:
```typescript
import { DrawShape } from "@/lib/state";
import { LineConfig } from "konva/lib/shapes/Line";
import { RectConfig } from "konva/lib/shapes/Rect";

export type Segment = {
  id: string;
  color: string;
  type: DrawShape;
  shape: RectConfig | LineConfig;
};
```

How can I get rid of this error? Or am I missing something? 

TS version: 5.2.2
RTK: 2.2.0

**Comment by markerikson** [comment]
Can you show the complete slice file?

**Comment by EskiMojo14** [comment]
at a guess, it's probably because the [ShapeConfig](https://github.com/konvajs/konva/blob/master/src/Shape.ts#L28) can include an HTMLImageElement, which has known issues with Immer's Draft type.

Try using `shape: Omit<RectConfig, "fillPatternImage"> | Omit<LineConfig, "fillPatternImage">`.
