### ISSUE TITLE
selectById return type is misleading

### ISSUE THREAD

**Issue by swizes** [reduxjs/redux-toolkit#4219]
in `src/entities/models.ts`

The new `selectById` selector from entity adapter type declaration is like below

`selectById: (state: V, id: Id) => Compute<UncheckedIndexedAccess<T>>
`

In v1 it was like 

`selectById: (state: V, id: Id) => T | undefined`

Now in v2 

If I use,
`const item = useSelector(state => selectItemById(state,id) `

item will be typed as `ItemType`. The `| undefined` is missing.

in v1, it is declared as

`ItemType | undefined`

**Comment by EskiMojo14** [comment]
As noted in the [migration guide](https://redux-toolkit.js.org/usage/migrating-rtk-2#entity-adapter-type-updates), the behaviour is now determined by your `noUncheckedIndexedAccess` setting.
