### ISSUE TITLE
RTK query: Error with the name of the hooks

### ISSUE THREAD

**Issue by JanselLopez** [reduxjs/redux-toolkit#4220]
If I declare two with the same name on the endpoint, even if they are imported from different files, it takes it as if it were the same and keeps the first one that makes a request and the second no longer makes it.

Example:
In ‘/products.js’
const productsApi = baseApi.injectEndpoints ({
  endpoints: builder => ({
    getProducts: ...
  })
})

export const {
  useGetProductsQuery,
….
} = productsApi;

In ’/stats.js’
const statsApi = baseApi.injectEndpoints ({
  endpoints: builder => ({
    getProducts: ...
  })
})

export const {
  useGetProductsQuery,
….
} = statsApi;

**Comment by EskiMojo14** [comment]
this is intended and [documented behaviour](https://redux-toolkit.js.org/rtk-query/usage/code-splitting). in development mode, you'll get a warning in console about it. remember, you're injecting into the same api instance, not creating a new one.

see https://github.com/reduxjs/redux-toolkit/issues/3350 for further discussion of this.
