### ISSUE TITLE
How to access request headers in `FetchBaseQueryError`?

### ISSUE THREAD

**Issue by onlywei** [reduxjs/redux-toolkit#4221]
In this code snippet from the [documentation site](https://redux-toolkit.js.org/rtk-query/usage-with-typescript#inline-error-handling-example), how can I access the request headers? There does not appear to be anything in the `FetchBaseQueryError` type that has headers?

```
  async function handleAddPost() {
    try {
      await addPost(name).unwrap()
      setName('')
    } catch (err) {
      if (isFetchBaseQueryError(err)) {
        // you can access all properties of `FetchBaseQueryError` here
        const errMsg = 'error' in err ? err.error : JSON.stringify(err.data)

        // I want to access headers here....
      }
    }
  }
```

**Comment by markerikson** [comment]
I don't think we expose headers at this layer, because there's not even a guarantee that you're using `fetchBaseQuery` or an HTTP request specifically.
