### ISSUE TITLE
Support for OpenAPI const keyword in typescript codegen

### ISSUE THREAD

**Issue by yanatan16** [reduxjs/redux-toolkit#4226]
In OpenApi codegen using the x-const extension, a JSON-Schema field that looks like this:

```jsonschema
{"properties": {"literal_value": {"const": "value", "default": "value"},
 "title": "TestLiteralValue"}
```

produces a type in typescript of:

```typescript
type TestLiteralValue = {
  literal_value: any
}
```

but it should generate:
```typescript
type TestLiteralValue = {
  literal_value: 'value'
}
```

**Comment by markerikson** [comment]
This is probably a problem with the underlying https://github.com/oazapfts/oazapfts library - could you file an issue over there with a repro? Thanks!
