### ISSUE TITLE
Mutation queries does not work as expected

### ISSUE THREAD

**Issue by phymilad** [reduxjs/redux-toolkit#4230]
I have a mutation query in a page in my reactjs project.
I work properly and update user's profile in the main page. 
I navigate to other page and navigate back to the main page with useNavigate from react-router-dom. Now if I try to update user's profile again, everything works fine in the network tab of my browser, but result of calling update hooks remains in pending status and no result come back to the browser properly.
I think this is an issue and should be fixed.
Please let me know if you think like me and guide me to solve this problem.

Best regards.

![1111](https://github.com/reduxjs/redux-toolkit/assets/74359743/a206b75d-7456-4ea8-9075-91374ff56ba2)

define api hooks like this

```
const myBaseQuery = fetchBaseQuery({
	baseUrl: import.meta.env.VITE_EMDADGAR_EXPERT_URL,
	prepareHeaders: (headers, { getState }) => {
		const token = getCookie(expertTokenName)
		if (token) {
			headers.set('authorization', `Bearer ${token}`)
		}
		headers.set('Accept', 'application/json')
		// headers.set('Content-Type', 'application/json')
		return headers
	},
});

const baseQueryWith401Handling: BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}> = async (
	args,
	api,
	extraOptions
) => {
	let result = await myBaseQuery(args, api, extraOptions)
	if (result.error && result.error.status === 401) {
		clearCookie(expertTokenName)
		// localStorage.removeItem(expertTokenName)
		window.location.replace("/expert/login")
	}
	if (result.error && +result.error.status >= 500) {
		// window.location.replace("/500")
	}
	if (result.error && +result.error.status === 403) {
		// window.location.replace("/403")
	}
	return result
};


export const api = createApi({
	reducerPath: 'api',
	baseQuery: baseQueryWith401Handling,
	tagTypes: ['Profile'],
	endpoints(builder) {
		return {
			expertUpdate: builder.mutation<ExpertProfile, { first_name?: string, last_name?: string, national_code?: string, iban?: string, ready_to_service?: number, notification_key?: string, profile_image?: string, rescue_vehicle_id?: string, vehicle_plate?: string, service_type_ids?: number[] }>({
				query: ({ first_name, last_name, national_code, iban, ready_to_service, notification_key, profile_image, rescue_vehicle_id, vehicle_plate, service_type_ids }) => ({
					url: `/expert/profile`,
					method: 'PUT',
					body: { first_name, last_name, national_code, iban, ready_to_service, notification_key, profile_image, rescue_vehicle_id, vehicle_plate, service_type_ids }
				}),
				invalidatesTags: ['Profile'],
			}),

		}
	}
})

export const {
	useExpertUpdateMutation, 
} = api
```

a part of my component which calls hook api
```
import { useEffect } from "react";
import { useExpertUpdateMutation } from "@store/expert/slices/api";

export const ExpertBottomNavigation = () => {

  const [updateExpertTrigger, updateExpertResult] = useExpertUpdateMutation();

  useEffect(() => {
		if(updateExpertResult.isSuccess) {
			console.log(updateExpertResult)
		}
	}, [updateExpertResult.isSuccess])
  

  return (
    <button onClick={() => updateExpertTrigger({ready_to_service: 0})}>
	Update
</button>
  );
};
```

**Comment by phryneas** [comment]
@dragonlipz that looks interesting (might be a CORS problem where Javascript is prevented from reading the response?), but what does it have to do with this issue? 

This seems to be something completely different?

**Comment by dragonlipz** [comment]
@phryneas Seemed the same issue to me after a ton of searching/testing, but then not the expert :)
I can take this elsewhere if it's not related to an RTK issue, just seemed closest related to mutations not working properly of anything I've found.


CORS is enabled in this instance and the preflight call properly returns the below
*(I also tested with specific origin of http://localhost:5173)
```
Access-Control-Allow-Headers: Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,sec-ch-ua,sec-ch-ua-mobile,sec-ch-ua-platform,User-Agent
Access-Control-Allow-Methods: OPTIONS,DELETE,GET,POST,PUT
Access-Control-Allow-Origin: *
```

This happens to be an AWS APIGW with lambda authorizer - shouldn't matter but just for reference.
Both the POST action and pre-flights succeed when a valid bearer token is used AND I'm Allowed to perform the action. Then the call is all fine and I see `200` codes.

It's only on an error that I can't get the actual HTTP response information. Even though it is logged by  debug tools.
So when I change authorizer to Deny me (`403`) I get:
Preflight - `200` All OK and same as before.
Then the below dumps out (line numbers included for reference to the handler code block) which to me shows the proper status code coming back, but uncertain why a CORS complaint when it's just returning a proper `403` on the actual call?

**DevTool Logs**
```
Access to fetch at 'https://someurl/api/v1/actionendpoint' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
POST https://someurl/api/v1/actionendpoint net::ERR_FAILED 403 (Forbidden)   appApi.ts:74
result:  {error: {…}, meta: {…}}                                             appApi.ts:75
result.error:  {status: 'FETCH_ERROR', error: 'TypeError: Failed to fetch'}  appApi.ts:76
```

**Code referenced by line numbers above**
```typescript
const baseQueryWith401Handling: BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}> = async (
  args,
  api,
  extraOptions,
) => {
  let result = await baseQuery(args, api, extraOptions); // 74
  console.log("result: ", result);                       // 75
  console.log("result.error: ", result.error);           // 76
  console.log("result.error.status: ", result.error?.status);
  console.log("result.meta: ", result.meta);
  console.log("result.meta.response: ", result.meta?.response);
  console.log("result.meta.response.status: ", result.meta?.response?.status);

  if (result.error && result.error.status === 401) {
    window.location.replace("/login");
  }
  if (result.error && +result.error.status === 403) {
    window.location.replace("/403");
  }
  if (result.error && +result.error.status >= 500) {
    window.location.replace("/500");
  }
  return result;
};

```


And behavior is exactly the same when I get a `401` back when my token expires.
```
Access to fetch at 'https://someurl/api/v1/actionendpoint' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
GET https://wedgerock-dv.api.wedgerockengineeredsolutions.com/api/v1/frames net::ERR_FAILED 401 (Unauthorized) appApi.ts:74
result:  {error: {…}, meta: {…}}                                             appApi.ts:75
result.error:  {status: 'FETCH_ERROR', error: 'TypeError: Failed to fetch'}  appApi.ts:76
```

**Comment by phryneas** [comment]
I mean... it's a CORS error - it happens between your Browser and your Server, it has nothing to do with RTK Query.

You can try using a `fetch` call that does the same request and use that to debug the whole thing, and when that works, RTK Query will work, too.

The behaviour from the RTK Query side of things here is perfectly fine: CORS prevents it from reading any error details, so it can only give you a generic error.

Regarding this issue: This issue is about a mutation hook staying "pending". 
You get back an error, it doesn't stay in "pending", right? It's really a completely different problem.
