### ISSUE TITLE
Passing query args to `prepareHeaders`?

### ISSUE THREAD

**Issue by kyletsang** [reduxjs/redux-toolkit#4238]
I have a use case where some header values are dependent on the args passed to my query.  Could we pass `arg` into the `prepareHeaders` function [here](https://github.com/reduxjs/redux-toolkit/blob/ed9fc19027a31afee2234dea54fb36c8beef46ad/packages/toolkit/src/query/fetchBaseQuery.ts#L235)?

Happy to work on this if this feature is considered.

**Comment by markerikson** [comment]
Very belated, but yes, open to PRs here.
