### ISSUE TITLE
Feature request: Provide tag to query that causes it to be invalidated by any ID

### ISSUE THREAD

**Issue by elramus** [reduxjs/redux-toolkit#4239]
Unless I'm missing something, there's a scenario that's not really possible to cover well using the current tag system. I want to provide a tag to a query endpoint that declares it can be invalidated by a tag type of _any_ ID. 

Let's say users can have lists of widgets saved to their account. Then we have a widget searching page where user can do a widget search and get back results of which lists have that widget on it. 

How would I tag this? We'd probably start with a LIST tag for the user's overall list of widget lists. 
```typescript
{ type: 'WidgetList', id: 'LIST' }
```

But we also know that users can change around the widgets on their existing lists, so we'd want to also get the specific tags of the lists we get back, something like this:
```typescript
[
  { type: 'WidgetList', id: 'LIST' },
  ...response.map(widgetList => ({
    type: 'WidgetList',
    id: widgetList.id,
  }),
]
```

So far all well and good, except for one scenario: let's say user has lists A, B, and C. They search for some widget and get back lists A and C in the results. So we store the tags for A and C. Then user goes and adds the widget to list B. Because that wasn't in our response, we don't have any way to know to nuke this search result query. 

Is this what the "general" tag is for, like just `{ type: 'WidgetList' }`? The problem there is that my `addWidgetToList` mutation would need to explicitly invalidate `{ type: 'WidgetList' }`. That would be too broad because it would also clear ```{ type: 'WidgetList', id: 'foo' }```, ```{ type: 'WidgetList', id: 'bar' }```, etc. 

In summary, we currently have the ability to nuke all tags of a type regardless of ID in a mutation via the general tag, but sometimes I need the opposite: the ability to be nuked by all tags of a type regardless of ID in a query. According to the [tag invalidation behavior table](https://redux-toolkit.js.org/rtk-query/usage/automated-refetching#tag-invalidation-behavior), this isn't currently possible. 

In other words, I feel like it should be this:
![Screenshot 2024-02-25 at 3 03 07 PM](https://github.com/reduxjs/redux-toolkit/assets/24811404/67646ab2-abd7-4077-8729-24019e20789a)

Possible workaround would be to pass all of user's widget list IDs into the initial search request, or provide them in the API call response, so that we can exhaustively tag the query with all list IDs. That feels yucky though. 

Any guidance on this scenario?

Thanks for all the great work over the years on this package!

**Comment by markerikson** [comment]
Very belated response. I don't think I understand what you're asking for here. Are you asking how to achieve this behavior with the existing functionality, or are you proposing a tweak to the existing tags implementation / behavior?

**Comment by elramus** [comment]
A tweak to the existing behavior to make it work like I described above would make sense to me personally, but I'm assuming that's a pretty substantial breaking change. I’ll describe it anyway just in case for the sake of discussion 😄. The situation above was somewhat specific and we’ve actually run into this again since then, so I can more clearly outline my thoughts here. 

No complaints at all with the tagging system for situations where the query can provide an ID and the mutation can invalidate an ID. That’s all great. But for situations where you want to involve the “general” tag, I’d argue that the current behavior on queries is somewhat counter-intuitive. Here’s the gist:

When you **invalidate** the general tag, that’s a broad nuke. It widens the clearing to every query of the matching type, regardless of its ID. Probably not desirable for most situations and most mutations, but I’m sure there’s a time and a place for it. Generally 99% of the time I’m either clearing a specific ID or clearing LIST, but good to have the option. 

When you **provide** the general tag, you’re saying “only clear me when a mutation broadly nukes”. That means that if I provide this to a query, I’m putting the onus on all the mutations (which I usually have a lot of relative to the one query, so it’s potentially laborious and error-prone to work through one by one), plus it’s requiring that I do this baby-out-with-the-bathwater broad nuke operation on every one. Maybe others would disagree, but I struggle to see the utility of this behavior. Basically, it _narrows_ when this query can be cleared, rather than _widening_ it. My proposal would be to have queries that are provided the general tag get cleared by the invalidation of ANY tag of the same type - whether general or specific. 

For context, the general pattern that I see in our app (for our most heavily used API resources anyway), is we tend to have a high ratio of mutations to queries. As in, you have an endpoint that fetches a thing, and you have lots of other endpoints that mutate the thing in various ways according to what the users need to do. Because of that lopsided relationship, it’s a bit of a “nightmare scenario” to have to comb through your API code endpoint by endpoint, grepping for invalidations of a certain tag and deciding if you should also invalidate some new tag here too. This isn’t a big deal when first starting out on a project, but on the scale of years, as your DB models and their relationships evolve, it would be much easier to (where possible) describe on the query level. Happy to give more details if that's helpful, and thanks for your time.

**Comment by phryneas** [comment]
Frankly, it's for simpler apps. 
If you don't have too much in your cache, you won't deal with tag ids too much - you will *only* use the general tags.

In your case, you probably don't want to use general tags at all, but more something like a general tag with an imaginary id that you can explicitly invalidate as a placeholder.

**Comment by elramus** [comment]
> something like a general tag with an imaginary id that you can explicitly invalidate as a placeholder.

Yeah I like that idea too. Something like `{ type: 'Widget', id: 'ANY' }`. But that's still something that needs to be remembered and implemented by the team devs for every single mutation. Fine at the beginning of a project if you know ahead of time, but if your project is years old it's pretty daunting. We've dabbled in creating utils for handling the complexity of knowing which tags to invalidate, rather than describing the tags directly in the mutation. Perhaps we need to go all-in on a system like that.

**Comment by phryneas** [comment]
> but if your project is years old it's pretty daunting

I mean, this has been documented as the solution for this exact problem since the beginning of RTKQ, so you have never looked at the docs? :/

![grafik](https://github.com/user-attachments/assets/bc7ac02e-3ec3-47cf-90d6-a01d6d5bb668)
https://redux-toolkit.js.org/rtk-query/usage/automated-refetching#advanced-invalidation-with-abstract-tag-ids

**Comment by elramus** [comment]
Yes I’m aware of your docs, and I do appreciate how thorough they are and have spent much time with them! I guess the point I’m trying to make here is that you don’t know how your project is going to evolve over time, so any solution that requires you to have known it in advance and set it up just so from the beginning is going to be difficult to apply later down the road. But yes, I see your point, what I’m describing is entirely solvable with abstract tag IDs.

Does my assertion that the current behavior of providing the general tag seems opposite hold any water with you guys? If not I’ll go ahead and close the issue! Thanks.

**Comment by phryneas** [comment]
> Does my assertion that the current behavior of providing the general tag seems opposite hold any water with you guys? If not I’ll go ahead and close the issue! Thanks.

Yes. Wven if we had a very long discussion and you'd convince us that another behaviour would be better -  we can't just change that, it would require a major release and then it would be something most people would likely miss in the changelog, so it would break people's applications in unexpected ways. It's pretty much set in stone as it is.

**Comment by elramus** [comment]
Yup makes perfect sense, thanks.
