### ISSUE TITLE
@rtk-query/codegen failed when openApi file refs to another file with schemas

### ISSUE THREAD

**Issue by vilola** [reduxjs/redux-toolkit#4241]
I have multiple .yml files with api documentation. Few of them uses schemas refs with another files. Rest of them have refs only within  one file.

With the api docs with cross file refs, rtk query codegen has problem and returns (seemingly unrelated) error. The other files are ok and it generates types and everything probably well. We didnt find any other difference then the refs. 

The error:
```
PS C:\Workspace\project> npm run rtk-codegen

> project@1.2.0-SNAPSHOT rtk-codegen
> npx @rtk-query/codegen-openapi openapi.config.ts  

Generating ./src/core/serverApi/generated/users.ts
Error: Can't find paths,/transactions,get,responses,200,content,application/json,schema,properties,content,items,oneOf,0,allOf,0,properties,data,properties,amount
    at ApiGenerator.resolve (C:\Workspace\project\node_modules\oazapfts\src\codegen\generate.ts:334:13)
    at check (C:\Workspace\project\node_modules\oazapfts\src\codegen\generate.ts:823:32)
    at check (C:\Workspace\project\node_modules\oazapfts\src\codegen\generate.ts:850:24)
    at ApiGenerator.checkSchemaOnlyMode (C:\Workspace\project\node_modules\oazapfts\src\codegen\generate.ts:858:12)
    at ApiGenerator.getRefAlias (C:\Workspace\project\node_modules\oazapfts\src\codegen\generate.ts:441:44)       
    at ApiGenerator.getBaseTypeFromSchema (C:\Workspace\project\node_modules\oazapfts\src\codegen\generate.ts:580:19)
    at ApiGenerator.getTypeFromSchema (C:\Workspace\project\node_modules\oazapfts\src\codegen\generate.ts:563:23) 
    at ApiGenerator.getBaseTypeFromSchema (C:\Workspace\project\node_modules\oazapfts\src\codegen\generate.ts:647:27)
    at ApiGenerator.getTypeFromSchema (C:\Workspace\project\node_modules\oazapfts\src\codegen\generate.ts:563:23) 
    at C:\Workspace\project\node_modules\oazapfts\src\codegen\generate.ts:547:16
```

Example of the ref in put action: 
```
requestBody:
        content:
          application/json:
            schema:
              $ref: './project-schema.yml#/components/schemas/UpdateUser'
```

**Comment by markerikson** [comment]
This looks like it's a problem with the underlying https://github.com/oazapfts/oazapfts library - could you file an issue over there? Thanks!

**Comment by naxim92** [comment]
I got exactly the same error, pls help

**Comment by vilola** [comment]
> I got exactly the same error, pls help

I did not solve it. I tried different versions of oazapfts package, but didnt work either. It seemed like it has problem with bigger files, but I am not sure with that. I was also consodering if there are some problems with open api files. Maybe try to run them through some validators - I found out a bunch of errors in mine, which was not reported by rtk generator. But in the end I did not know if that would solve this first problem. I switched to openapi-ts generator to generate the types and wrote my queries by myself 🙃

**Comment by naxim92** [comment]
Try to switch to version 1.0.0 of redux codegen, it's worked for me right now. In my case I assume the problem was related with a big nesting level in openapi spec files.

**Comment by vilola** [comment]
> Try to switch to version 1.0.0 of redux codegen, it's worked for me right now. In my case I assume the problem was related with a big nesting level in openapi spec files. 

Yep. 1.0.0 is working, but I was using enums across the whole app, which 1.0.0 cant geterate (and also some more minor differences was there) so I switched the generator completely 😁

**Comment by markerikson** [comment]
Note that we've published 2.0 alphas for the RTKQ OpenAPI codegen, which contain major changes including an `oazapfts` upgrade:

- https://github.com/reduxjs/redux-toolkit/releases/tag/%40rtk-query%2Fcodegen-openapi%402.0.0-alpha.0

Please try that out and see if it helps!

**Comment by naxim92** [comment]
Nope, got the same error

**Comment by naxim92** [comment]
Pls reopen issue

**Comment by markerikson** [comment]
> Pls reopen issue

Per my original comment, this must be an upstream problem - please file issues there.
