### ISSUE TITLE
enhanceEndpoints added tagTypes cannot be invalidated from other injectEndpoints

### ISSUE THREAD

**Issue by sian022** [reduxjs/redux-toolkit#4242]
```
const exampleApi = emptyApi
  .enhanceEndpoints({ addTagTypes: ["TagTypeExample"] })
  .injectEndpoints({
    endpoints: (builder) => ({
      example: builder.query({
        query: (params) => ({
          url: "/example",
          method: "GET",
          params,
        }),
        providesTags: ["TagTypeExample"],
        transformResponse: (response) => response.value,
      }),
    }),
  });
```

I do the thing where you enhanceEndpoints to add tag types and then injectEndpoints to the main api.

However, my issue with this is that I can't invalidatesTags through different enhanceEndpoints + injectEndpoints instances. The only way I can invalidate tags through different injectEndpoints is by adding that tag type in the base createApi.

Is the any other way to work around this?

**Comment by EskiMojo14** [comment]
no, tags need to be added before you can use them.

however, you can add the same tag as many times as you want without an issue.


```ts
const exampleApi = emptyApi
  .enhanceEndpoints({ addTagTypes: ["TagTypeExample"] })
  .injectEndpoints({
    endpoints: (builder) => ({
      example: builder.query({
        query: (params) => ({
          url: "/example",
          method: "GET",
          params,
        }),
        providesTags: ["TagTypeExample"],
        transformResponse: (response) => response.value,
      }),
    }),
  });

const exampleApi2 = emptyApi
  .enhanceEndpoints({ addTagTypes: ["TagTypeExample"] })
  .injectEndpoints({
    endpoints: (builder) => ({
      example: builder.mutation({
        query: (body) => ({
          url: "/example",
          method: "POST",
          body,
        }),
        invalidatesTags: ["TagTypeExample"],
        transformResponse: (response) => response.value,
      }),
    }),
  });
```

**Comment by lordlpua** [comment]
Hi, @EskiMojo14, sorry that I reopened this question, but I have almost the same question.
Could we use such a thing to extend invalid tags

`const exampleApi = emptyApi
  .enhanceEndpoints({ addTagTypes: ["TagTypeExample"] })
  .injectEndpoints({
    endpoints: (builder) => ({
      example: builder.query({
        query: (params) => ({
          url: "/example",
          method: "GET",
          params,
        }),
        providesTags: ["TagTypeExample"],
        transformResponse: (response) => response.value,
      }),
    }),
  });

const exampleApi2 = emptyApi
  .enhanceEndpoints({ 
    addTagTypes: ["TagTypeExample2"],
    endpoints: {
            someMutation: {
                invalidatesTags: ["TagTypeExample2"],
            },
        },
})
 .injectEndpoints({
    endpoints: (builder) => ({
      example: builder.query({
        query: (params) => ({
          url: "/example",
          method: "GET",
          params,
        }),
        providesTags: ["TagTypeExample2"],
      }),
    }),
  });

const exampleApi3 = emptyApi
.enhanceEndpoints({ 
    addTagTypes: ["TagTypeExample3"],
    endpoints: {
            someMutation: {
                invalidatesTags: ["TagTypeExample3"],
            },
        },
})
.injectEndpoints({
    endpoints: (builder) => ({
      updateExample: builder.mutation({
        query: (body) => ({
          url: "/example",
          method: "GET",
          body,
        }),
        invalidatesTags: ["TagTypeExample3"],
      }),
    }),
  });`

So, my expectation is - will the someMutation have invalidatesTags:["TagTypeExample", "TagTypeExample2", "TagTypeExample3"] all 3 tags? Or no?

Could it be that this method will not work with a different connection (injectEndpoints) sequence?
Or should enhanceEndpoints not be used at all for such a situation?

A little more information - our project uses a lot of queries, keeping them in one place is not convenient, for this we try to split it into different files. Sometimes, such a case appears when we need to invalidate several tags that are found in completely different files

**Comment by EskiMojo14** [comment]
enhanceEndpoints uses a shallow merge of the definition when provided an object (meaning the invalidatesTags array would be completely overwritten), you would need to use a function to merge tags.
```ts
const exampleApi2 = emptyApi
  .enhanceEndpoints({ 
    addTagTypes: ["TagTypeExample2"],
    endpoints: {
            someMutation(definition) {
                (definition.invalidatesTags ??= []).push("TagTypeExample2")
            },
        },
})
```

**Comment by lordlpua** [comment]
@EskiMojo14 Thx! So I could easily use this example from you, yes?
According to the documentation, enhanceEndpoints should merge it, but not replace it. [https://redux-toolkit.js.org/rtk-query/api/created-api/code-splitting#enhanceendpoints](url)

> Unlike injectEndpoints, the partial endpoint definitions will not replace existing definitions, but are rather merged together on a per-definition basis (ie, Object.assign(existingEndpoint, newPartialEndpoint)).
> 
> Returns an updated and enhanced version of the API slice object, containing the combined endpoint definitions.

And the last question, maybe you have an example somewhere, what to do with the approach above and TS, for example, it will provide an error TS2353, because TS doesn't no  - someMutation exists or not, definition - any

**Comment by EskiMojo14** [comment]
> According to the documentation, enhanceEndpoints should merge it, but not replace it.

It merges the *definition*, not individual properties of that definition.
https://github.com/reduxjs/redux-toolkit/blob/af3e75bb9e6a51e13603d2a5684ef3ba1da07e3b/packages/toolkit/src/query/createApi.ts#L417-L424

> And the last question, maybe you have an example somewhere, what to do with the approach above and TS, for example, it will provide an error TS2353, because TS doesn't no - someMutation exists or not, definition - any

You can only enhance endpoints that exist on the api instance you're enhancing. If someMutation isn't defined in emptyApi, you would need to call enhanceEndpoints on the version of the api with it defined.

**Comment by lordlpua** [comment]
@EskiMojo14 Thank you!
