### ISSUE TITLE
issue with types when create endpoints

### ISSUE THREAD

**Issue by VleriaYanova** [reduxjs/redux-toolkit#4243]
![photo_2024-02-27_20-41-55](https://github.com/reduxjs/redux-toolkit/assets/101396805/26e97346-5c63-4c42-a19a-c47c414f0b96)

**Comment by markerikson** [comment]
A screenshot with no other code or context is not something we can help with.

Please supply a CodeSandbox or a Github repo that demonstrates this issue.
