### ISSUE TITLE
issue with types when creating endpoins 

### ISSUE THREAD

**Issue by VleriaYanova** [reduxjs/redux-toolkit#4244]
https://github.com/VleriaYanova/future-academy/blob/master/admin-space/src/redux/cApi.ts

sorry, please help with this issue i dont understand whats im doing wrong.
when im create endpoint i have issue 'Argument type {invalidatesTags: {id: string, type: "Post"}[], query: (body: any) => {method: string, body: QueryArg, url: string}} is not assignable to parameter type OmitFromUnion<MutationDefinition<Partial<Post>, BaseQuery, TagTypes, Post, ReducerPath>, "type"> '

**Comment by markerikson** [comment]
I tried cloning your repo, installing, and opening up `cApi.ts`, and I don't see any TS errors.

Where and how are you seeing that error?  What editor are you using?

**Comment by VleriaYanova** [comment]
As it turned out, the error was only in Phpstorm 2022.1.4, I opened it in vscode and there was no error there, thanks for your time

**Comment by markerikson** [comment]
Yeah, the WebStorm IDEs have consistently had issues processing RTK's TS types properly.

**Comment by koalex** [comment]
Downgrade TS to 4.9.5 fix the problem with WebStorm. But maybe somebody know another way to use WS with TS5?

**Comment by phryneas** [comment]
They roll their own implementation of TypeScript instead of using the TypeScript language server in many cases, so there's nothing we can do about it - it's a deliberate choice on their side.
