### ISSUE TITLE
[RTK Query] Doing one-off-queries with `myEndpoint.initiate(arg, { subscribe: false })` not working as expected

### ISSUE THREAD

**Issue by pmk1c** [reduxjs/redux-toolkit#4247]
I'm currently trying to do some one-off-queries with RTK Query. What do I mean with one-off queries? I mean queries, that I don't need to subscribe to, that should only give me a result once, that I can work with immediately and where the result doesn't even need to be written into cache (although it may be).

Although one-off queries do not use most of the features RTK Query provides and could potentially be handled without RTK Query, we want to do them through RTK Query, since this is our one API implementation, we want to do queries with.

I was expecting, that I could do something like this, to make this work:

```js
await data = dispatch(myEndpoint.initiate(arg, { subscribe: false })).unwrap()
```

Unfortunately `data` is always `undefined`. I guess the reason is, that with no subscribers, the cache will never get filled and `initiate` will return an empty state, since it does not return the query response data directly, but the cached data after awaiting the query. So we've come to this solution:

```js
export const myOneOffQuery =
  (arg) => async (dispatch) => {
    const result = dispatch(
      myEndpoint.initiate(arg)
    );
    const data = await result.unwrap();
    result.unsubscribe();

    return data;
  };

const data = await dispatch(myOneOffQuery(arg));
```

But this seems overly complicated. Is there another way to do this, that I'm not seeing? Or is it possible to fix `myEndpoint.initiate(arg, { subscribe: false })` to provide the queried data after unwrapping even without subscribers?

**Comment by phryneas** [comment]
Have you tried updating to RTK 2.0? Afaik, that bug was fixed back then.

**Comment by pmk1c** [comment]
Thanks for the quick response! Sorry, I didn't find a bug report on that. But you may be on the right track. We didn't take the time to update to RTK 2 yet. I'll try this on Monday when I'm back in office.

**Comment by pmk1c** [comment]
The update was easier than I initially thought and it fixes the problem. Thanks again for the quick response and the good work!
