### ISSUE TITLE
type mismatch on `middleware` property of `configureStore` when also using `enhancers`

### ISSUE THREAD

**Issue by burtek** [reduxjs/redux-toolkit#4248]
```ts
import { configureStore } from '@reduxjs/toolkit';
import { createLogger } from 'redux-logger';

export const store = configureStore({
    enhancers: getDefaultEnhancers => getDefaultEnhancers(),
    middleware: getDefaultMiddleware => {
        return getDefaultMiddleware().prepend(createLogger())
    },
    reducer: {}
});
```

reports TS 2322 error on `middleware` key:

```
Type '(getDefaultMiddleware: GetDefaultMiddleware<any>) => Tuple<[Middleware<{}, any, Dispatch<UnknownAction>>, ThunkMiddleware<any, UnknownAction>]>' is not assignable to type '(getDefaultMiddleware: GetDefaultMiddleware<any>) => Tuple<[ThunkMiddleware<any, UnknownAction>]>'.
  Type 'Tuple<[Middleware<{}, any, Dispatch<UnknownAction>>, ThunkMiddleware<any, UnknownAction>]>' is not assignable to type 'Tuple<[ThunkMiddleware<any, UnknownAction>]>'.
    Type '[Middleware<{}, any, Dispatch<UnknownAction>>, ThunkMiddleware<any, UnknownAction>]' is not assignable to type '[ThunkMiddleware<any, UnknownAction>]'.
      Source has 2 element(s) but target allows only 1.
```

![image](https://github.com/reduxjs/redux-toolkit/assets/2940958/2875e922-a471-4c3c-a765-7fc452914d2f)

-------

This does not happen if the `enhancers` key is not provided:

![image](https://github.com/reduxjs/redux-toolkit/assets/2940958/a9dfd43e-8b15-4cf2-8314-353873f1d269)

NB: It's not the case of "remove enhancers key since you're not doing anything there" - in my project I do add more enhancers. Here I provided minimal repro code.

-------

Using:

lib | version
---|---
@reduxjs/toolkit | 2.2.1
redux-logger | 3.0.6
typescript | 5.3.2

**Comment by EskiMojo14** [comment]
the type of `getDefaultEnhancers` depends on the result of your `middleware` callback, move the `enhancers` key *after* the `middleware` key.

i thought we had documented this somewhere but I can't seem to find it

**Comment by burtek** [comment]
How the heck do types depend on keys order  o.O

Anyway, it worked. Thanks. Would be nice to document that properly :)

**Comment by markerikson** [comment]
We mentioned it in the migration guide:

- https://redux.js.org/usage/migrations/migrating-rtk-2#configurestore-field-order-for-middleware-matters

but not sure it's in the actual docs.

**Comment by burtek** [comment]
Well, I wasn't migrating, so I never found that part :/ Good to hear it's in at least that place.

Happy to close this issue unless you want to use it to track any related docs changes
