### ISSUE TITLE
Errot in type StateFromReducersMapObject

### ISSUE THREAD

**Issue by AleksRap** [reduxjs/redux-toolkit#4250]
Hi everybody. I found an error inside the StateFromReducerMapObject type.

It plays back when I use async reducers.

For example

My state schema:
`
interface SyncStateSchema {
  counter: CounterSchema;
  user: UserSchema;
}
`
`
export type AsyncStateSchema = {
  loginForm?: LoginSchema;
  profile?: ProfileSchema;
};
`
`
export type StateSchema = SyncStateSchema & AsyncStateSchema;
`

where the loginForm and profile props are optional and are added to the global state (as well as cleared from there) when required

My type for reducers
`
ReducersMapObject<StateSchema>
`

when I use the combineReducers function by passing my list of reducers to it, I get a function with the type:
`
 Reducer<{counter: CounterSchema, user: UserSchema, loginForm?: undefined, profile?: undefined}, UnknownAction, ...>
`

This is not exactly what I expected. I was waiting for the type:
`
 Reducer<{counter: CounterSchema, user: UserSchema, loginForm?: LoginSchema | undefined, profile?: ProfileSchema | undefined}, UnknownAction, ...>
`

this is true, because when the loginForm or profile state is connected, the reducer for it will exist, it will not always be undefined

**Comment by AleksRap** [comment]
To fix this error, the StateFromReducersMapObject type must be replaced with the following
`
type StateFromReducersMapObject<M> = M[keyof M] extends Reducer<any, any, any> | undefined ? {
    [P in keyof M]: M[P] extends Reducer<infer S, any, any> | undefined ? S : never;
} : never;
`

**| undefined** after **Reducer<infer S, any, any>** - can fix the problem

**Comment by phryneas** [comment]
I am sorry, could you please give a few examples of runtime code here? 
You should never write out any of those TypeScript types in your codebase, so it's hard to go based on them alone.
