### ISSUE TITLE
`POST` as query

### ISSUE THREAD

**Issue by tylerlaprade** [reduxjs/redux-toolkit#4256]
I'm looking for examples for how to create a query that uses `POST` so I can attach an arbitrary JSON body when fetching data. It shouldn't be a mutation, since I'm not modifying any data. When I search the documentation, I see far too many results matching `post`, since that's the business object of choice, so I'm uncertain whether this is possible to do.

**Comment by markerikson** [comment]
Yeah, just return an object for the `query` field and provide any additional `fetch` options like `method`:

```ts
  getUsers: build.query({
    query: () => ({
      url: "/users",
      method: "POST"
    })
  })
```

**Comment by tylerlaprade** [comment]
Oh perfect, thanks! I thought I tried that, but I must've messed up my syntax somewhere.
