### ISSUE TITLE
TypeError :subscriptionSelectorsRef?.current.isRequestSubscribed is not a function (it is undefined) in rtk-query-react.development.cjs

### ISSUE THREAD

**Issue by ashishimg27** [reduxjs/redux-toolkit#4257]

**Comment by ashishimg27** [comment]
![screenshot-1709804030791](https://github.com/reduxjs/redux-toolkit/assets/95354816/181f4619-68e8-4e0f-84de-97065826ed2a)

**Comment by EskiMojo14** [comment]
have you definitely added the middleware for RTKQ to your store?

**Comment by ashishimg27** [comment]
@EskiMojo14 yes 
store file code -
import { configureStore } from '@reduxjs/toolkit';
import { setupListeners } from '@reduxjs/toolkit/query';

import rootReducer from 'app/redux/reducers';
import validateDomainMiddleware from 'app/redux/middellware/domain';
import validateSignInWithCredential from 'app/redux/middellware/signIn';
import { feeds } from 'app/redux/reducers/app/feeds';
import { userById } from 'app/redux/reducers/app/user';
import { chats } from 'app/redux/reducers/app/chat';
import userSignInMiddleware from 'app/redux/middellware/user';
import { profile } from 'app/redux/reducers/app/profile';
import rtkQueryErrorLogger from 'app/redux/middellware/error';

export const store = configureStore({
  reducer: rootReducer,
  middleware: getDefaultMiddleware =>
    getDefaultMiddleware({ serializableCheck: false }).concat(
      validateDomainMiddleware,
      userSignInMiddleware,
      validateSignInWithCredential,
      rtkQueryErrorLogger,
      feeds.middleware,
      userById.middleware,
      chats.middleware,
      profile.middleware
    )
});

setupListeners(store.dispatch);

**Comment by haasampath** [comment]
Please check your middleware order, that can be matters, i have had the similar experience...

**Comment by EskiMojo14** [comment]
i think middleware order shouldn't matter *as long as* every middleware definitely returns the result of calling `next(action)` (apart from cases where it's specifically intending to return something different)

```js
const brokenMiddleware = api => next => action => {
  console.log(api.getState())
  next(action)
  console.log(api.getState())
}

const workingMiddleware = api => next => action => {
  console.log(api.getState())
  const result = next(action)
  console.log(api.getState())
  return result
}
```

you should also make sure no middleware is marked with the `async` keyword, which will cause every dispatch result to be wrapped in a promise

```js
const brokenMiddleware2 = api => next => async action => {
  console.log(api.getState())
  const result = next(action)
  console.log(api.getState())
  return result
}
```

**Comment by markerikson** [comment]
Closing due to lack of info.
