### ISSUE TITLE
configureStore TypeScript errors despite following Redux Toolkit documentation example

### ISSUE THREAD

**Issue by trooperandz** [reduxjs/redux-toolkit#4258]
- In the `TypeScript Quick Start` guide [here](https://redux-toolkit.js.org/tutorials/typescript), the following example is given for creating and typing the store:
 
<img width="961" alt="Screenshot 2024-03-07 at 11 00 09 AM" src="https://github.com/reduxjs/redux-toolkit/assets/14365371/94146be0-c276-42d1-85a4-bf00a150c100">

 - However, I am getting TypeScript errors and my `RootState` is getting defined as `any`, which leaves me with incomplete redux state type checking in the codebase.  My reducer slices are coming from `createSlice()` per the exact documentation as well. See the errors below (the `RootState` error is: `Type alias 'RootState' circularly references itself.`:
<img width="914" alt="Screenshot 2024-03-07 at 11 11 40 AM" src="https://github.com/reduxjs/redux-toolkit/assets/14365371/e36e698f-a279-4c8f-9018-b3d6080bb4c0">

I am not quite sure how to fix these errors; perhaps the documentation is out of date with the latest TS/Redux libraries? Does anyone have suggestions as to how to fix this?

My major lib versions are as follows:
```
"react-redux": "^9.1.0"
"@reduxjs/toolkit": "^2.2.0"
"typescript": "^5.0.4"
```

**Comment by markerikson** [comment]
Looks like there's a type circularity issue of some kind.  

What does `downtownerApi`'s declaration and contents look like?

**Comment by EskiMojo14** [comment]
presumably, at least one of your slices are using the RootState type in a way that causes a cycle.

try commenting out each line of your reducers object until it's happy, to identify which slice is causing the issue

**Comment by trooperandz** [comment]
Thank you all.  I found the root of the problem after going through each slice as you suggested.  In all reducers except for the one that _was not_ throwing the TS error, I was setting the `state` type equal to `RootState` as follows:
```
setParams: (state: RootState, action: PayloadAction<string>) => { ... };
```

Removing this `RootState` assignment altogether (and letting the lib infer the `state` type) fixed it!

Thank you for your help.

**Comment by EskiMojo14** [comment]
yep, along with causing a circular type, that annotation is straight up wrong - the slice reducer only receives the slice's state, not the whole root state shape 😉

**Comment by acelaya** [comment]
I hate bringing this thread back to life, but I'm facing this same issue and can't find a way to solve the circular type dependency when one of the slices uses an async thunk that has been created with `createAsyncThunk.withTypes<{ state: RootState }>()`.

Basically, you need to create the store to "infer" `RootState` -> to create the store, you first need all the reducer slices -> one or more of the reducer slices may depend on async thunks -> async thunks created with `createAsyncThunk.withTypes<{ state: RootState }>()` depend on the `RootState`, and we are back at square one.

The only solution I have found so far is not typing `createAsyncThunk` via `withTypes`, and use `createAsyncThunk` as is instead, but then when I need to access the `getState` and/or `dispatch` from `thunkApi` param, I have to do an inline type cast, which seems suboptimal.

I reckon there's really no solution for this, but just in case someone has found a workaround.

**Comment by EskiMojo14** [comment]
@acelaya your slice type shouldn't depend on your async thunks - are you returning something inside extraReducers? it shouldn't have anything returned

**Comment by acelaya** [comment]
> [@acelaya](https://github.com/acelaya) your slice type shouldn't depend on your async thunks - are you returning something inside extraReducers? it shouldn't have anything returned

I'm trying to build a super basic reproduction, and so far things that I assumed would fail seem to work. Of course my real app has a few more layers of indirection and wrappers.

I'm going to try get as close as possible. Hopefully, in the process I'll find the way to solve the issue for me.
