### ISSUE TITLE
createSlice actions TypeScript typings for the payload does not have Intellisense support

### ISSUE THREAD

**Issue by RPDeshaies** [reduxjs/redux-toolkit#426]
## Context
When using the `createSlice` api with Typescript, it generates actions that can be called using two overloads

1. `payload?: undefined`
2. `<PT extends MY_PAYLOAD>(payload?: PT)` where `MY_PAYLOAD` would be the typing provided inside the `PayloadAction` of the reducer

I have the impression that because of that, Typescript is not able to generate the autocomplete properly even though it is still able to validate the object.

## Example

```typescript
const mySlice = createSlice({
  name: "mySlice",
  initialState: {
    foo: 3
  },
  reducers: {
    setFoo(
      state,
      action: PayloadAction<{
        foo: number;
      }>
    ) {
      state.foo = action.payload.foo;
    }
  }
});

mySlice.actions.setFoo(); // is valid
mySlice.actions.setFoo({}); // is not valid 
```

The error message you get is

![image](https://user-images.githubusercontent.com/6224111/76424795-1571d700-637f-11ea-8036-a2afbf9034ff.png)

Which is perfect, but if you try to toggle the intellisense inside the anonymous object of the second call to `setFoo` you get this:

![image](https://user-images.githubusercontent.com/6224111/76424863-30444b80-637f-11ea-8610-72b4316a1817.png)

## Expected behavior

We should be able to see that the only property the payload can receive is `foo: number`

## Versions
```
"@reduxjs/toolkit": "1.2.5",
"typescript": "3.7.2",
```

**Comment by phryneas** [comment]
I guess you have `strictNullChecks: false` in your `tsconfig.json`?

Please see [this answer](https://github.com/reduxjs/redux-toolkit/issues/399#issuecomment-592691295)

**Comment by RPDeshaies** [comment]
It's turned off by default and turning it on does indeed fix the issue.
Just read the other **Issue**. Thanks for looking into it.

Closing the issue

**Comment by phryneas** [comment]
Every `tsconfig.json` generated by `tsc --init` since TypeScript 2.3 should have `strict: true`, which turn on all the strict options.
It's only off by default to preserve backwards compatibility with pre-2017-code. You might want to check your other `strict` settings ;)

**Comment by phryneas** [comment]
Hey @RPDeshaies, I put in a PR that might improve the autocompletion for people with `strictNullChecks: false` (#428) - could you give it a test and give me feedback if it improves the situation to before?

```
yarn add https://pkg.csb.dev/reduxjs/redux-toolkit/commit/982da2ca/@reduxjs/toolkit
npm i https://pkg.csb.dev/reduxjs/redux-toolkit/commit/982da2ca/@reduxjs/toolkit
```

**Comment by RPDeshaies** [comment]
I'll check it out today!

**Comment by RPDeshaies** [comment]
This works like a charm @phryneas
