### ISSUE TITLE
Rejected query is persisted

### ISSUE THREAD

**Issue by fikkatra** [reduxjs/redux-toolkit#4260]
I'm combining redux-toolkit with redux-persist in a React Native app, to cache data in case the user is offline. I noticed that sometimes, a rejected query is being persisted. This is what's written to async storage:

```
{
   "queries":{
      "getPoints(undefined)":{
         "status":"rejected",
         "endpointName":"getPoints",
         "requestId":"RyaEcDx84aSiTkq4dzPm-",
         "startedTimeStamp":1709916189671,
         "error":{}
      },
   },
// ...mutations, provided, subscriptions, config, _persist
}
```

I believe the cause of the failed query is a refetch when there is no network connection. However, I'd expect failed queries to not be persisted. 

Is this expected behavior? If so: how can I prevent such queries to be persisted? I only want to persist actual data.

**Comment by phryneas** [comment]
It's part of the store, and you persist the store, so of course it gets persisted. 
Apart from not being what you expect - do you see any form of unwanted application behaviour from that?

**Comment by fikkatra** [comment]
Well the goal is to display the cached data in case it can't be retrieved, e.g. when the user if offline or when a server error occurs. We execute `refetch` on app load, in case it comes back successfully, we display the updated data. In case there is an error, we display the cached (and potentially stale) data. 

From what you're saying, I gather I should tap into the flow somewhere, catch the error, and transform it back to the current data in the store? Is there a way to get to the current data? We're using a custom `queryFn`.

**Comment by phryneas** [comment]
You can on persisting switch all `status: 'rejected'` cache entries that have `data` over to `status: 'fulfilled'` if you really want to, but tbh., it just seems really weird to me.

If your api failed it seems fine to keep the data in view that you had before, but when navigating to a new screen, I would not start out with data that's almost certainly outdated (after all, you refetched it for a reason).

**Comment by phryneas** [comment]
> Where can I hook into "on persisting"?

That would be a feature of your persistance library or persistance layer.

**Comment by fikkatra** [comment]
Closing this. Haven't found an easy solution to do this with redux-toolkit and redux-persist, it feels like I'm trying to do something that doesn't match with the core concepts of this library. It seems [react-query](https://tanstack.com/query/latest) combined with [persistQueryClient](https://tanstack.com/query/latest/docs/framework/react/plugins/persistQueryClient) is a better fit for our use cases. By default, it only persists successful queries.

**Comment by phryneas** [comment]
[Redux-persist has transforms.](https://github.com/rt2zz/redux-persist?tab=readme-ov-file#transforms)

> Transforms allow you to customize the state object that gets persisted and rehydrated.

**Comment by adityacfcs** [comment]
@fikkatra i am facing similar issue in which i use redux persist with toolkit. my app is used in low network are so i persist all my states. Its giving me error on login some times. i think this is due to the above issue .

did you find any solution to above problem?

**Comment by fikkatra** [comment]
@adityacfcs as stated here, we moved to react-query's persist feature, which provided a closer fit for our use cases (which are similar to yours, namely caching data for offline use).

> Closing this. Haven't found an easy solution to do this with redux-toolkit and redux-persist, it feels like I'm trying to do something that doesn't match with the core concepts of this library. It seems [react-query](https://tanstack.com/query/latest) combined with [persistQueryClient](https://tanstack.com/query/latest/docs/framework/react/plugins/persistQueryClient) is a better fit for our use cases. By default, it only persists successful queries.

**Comment by phryneas** [comment]
@adityacfcs as stated above, if you want to change what is being persisted, please look at the documentation of your persistance library, e.g. [transforms for redux-persist](https://github.com/rt2zz/redux-persist?tab=readme-ov-file#transforms).

Neither RTK Query nor Redux Toolkit are doing the persisting.
