### ISSUE TITLE
 selectFromResult

### ISSUE THREAD

**Issue by kukuruku62** [reduxjs/redux-toolkit#4261]
Hi, I am new to rtk-query and would like to know if I understand the use of selectFromResult correctly. In one of my react components I need to get only the first element from an incoming array.
![image](https://github.com/reduxjs/redux-toolkit/assets/101480999/a7c07a9b-9e49-4ca0-8cf7-5770d45e015d)

```
export const About = () => {

  const { data } = useGetAllEventsQuery(undefined, {
    selectFromResult: (result) => ({
      data: result.data[0],
    }),
  });
  console.log(data)

  return (...);
};
```
If I specify the array index  **data: result.data[0]** , I get an error **TypeError: Cannot read properties of undefined (reading '0')**

What's my mistake? Maybe I need to take an array element directly from data without using selectFromResult ?

**Comment by markerikson** [comment]
`result.data` may not exist yet if the query hasn't completed.  You can safety-check it using optional chaining or other existence checks, like `result.data?.[0]`.

**Comment by kukuruku62** [comment]
thanks! it works:)
