### ISSUE TITLE
Causes rendering twice

### ISSUE THREAD

**Issue by Z-Hayk** [reduxjs/redux-toolkit#4262]
https://github.com/reduxjs/redux-toolkit/issues/3783

https://github.com/reduxjs/redux-toolkit/issues/3783#issuecomment-1752596799

<img width="1005" alt="Screenshot 2024-03-09 at 15 58 17" src="https://github.com/reduxjs/redux-toolkit/assets/122481542/a2156d9a-e87a-467e-a812-c01d8855fb75">

@markerikson It’s clear that there’s a problem, but I don’t understand why they’re closing issue.

**Comment by phryneas** [comment]
Mainly because you're in the wrong repository. As stated, this is either a `react-redux` issue, a `react` issue or a `react-native` issue.
