### ISSUE TITLE
Invalidating cache entry is not working

### ISSUE THREAD

**Issue by AsuraKev** [reduxjs/redux-toolkit#4270]
I have the following when I get an item and tag it with a property e.g a string

![image](https://github.com/reduxjs/redux-toolkit/assets/52765572/5155d920-6e70-4acc-912a-1a4f8c7faa8b)

When I update the entity and change the string from say test-1 to test-2,  after request is completed I navigate so that the url is pointing to /test-2 then after timeout i remove cache entry for test-1 as it no longer exists. However using InvalidateTags and Api.util doesnt seem to work, when i browse test-1 i still see cache data.

![image](https://github.com/reduxjs/redux-toolkit/assets/52765572/827d8858-dc14-45dd-a3de-5fa52c640bd2)

**Comment by markerikson** [comment]
Not sure I understand the question. If you can provide a repro as a CodeSandbox we might be able to take a look.
