### ISSUE TITLE
`getDefaultEnhancers` is not a function

### ISSUE THREAD

**Issue by mikirejf** [reduxjs/redux-toolkit#4276]
Hello. I'm trying to migrate to RTK 2.0 following the migration guide. I'm getting "`getDefaultEnhancers` is not a function"  error. I can't figure out what I'm doing wrong with configuring the store. There is no TS error.

```
const store = configureStore({
  reducer: rootReducer,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      immutableCheck: true,
    })
      .prepend(listenerMiddleware.middleware)
      .concat(mainApi.middleware),
  enhancers: (getDefaultEnhancers) => {
    // console.log('getDefaultEnhancers', typeof getDefaultEnhancers, getDefaultEnhancers);
    return getDefaultEnhancers().concat(createSentryEnhancer());
  },
});
```

![image](https://github.com/reduxjs/redux-toolkit/assets/8895894/28cfbdf5-1535-4fae-88ae-a7cf88f47d35)

**Comment by EskiMojo14** [comment]
it sounds like you're calling configureStore from 1.x somehow - the callback receives an array in 1.x, and a function in 2.x

try running `yarn why @reduxjs/toolkit` or `npm ls @reduxjs/toolkit`

**Comment by mikirejf** [comment]
`npm ls @reduxjs/toolkit` returns 

![image](https://github.com/reduxjs/redux-toolkit/assets/8895894/6a9129f3-390d-4039-913b-f53a67119755)

**Comment by EskiMojo14** [comment]
huh, that's really odd - any chance you could put together a reproduction or share the repo?

**Comment by mikirejf** [comment]
Sorry, I can't share the repo ... 

You definitely put me in the right direction. There is indeed 1.x code running 

![image](https://github.com/reduxjs/redux-toolkit/assets/8895894/7be6461b-430b-4447-b3b6-9757bd33b6a3)


It's weird because I also had to make changes to `EntityState` typings (had to explicitly pass the id type) which I understand is a 2.x thing. Will debug more a bit later and report back.

**Comment by mikirejf** [comment]
@EskiMojo14 

I had to remove the "dist" keyword from the import path of some utils/types, for example:
![image](https://github.com/reduxjs/redux-toolkit/assets/8895894/dfa5d144-4ec7-4293-b846-d30be698366d)
