### ISSUE TITLE
My TS analyzes redux-toolkit

### ISSUE THREAD

**Issue by Honan** [reduxjs/redux-toolkit#4277]
TypeScript analyzes code redux-toolkit. I tried to add to ignore in tsconfig.json ("exclude": ["node_modules"]).  Does not work

"@reduxjs/toolkit": "1.9.7"

<img width="727" alt="Снимок экрана 2024-03-16 в 22 36 02" src="https://github.com/reduxjs/redux-toolkit/assets/14319036/70211785-4c07-4ae7-91a4-c596befafa55">
<img width="1706" alt="Снимок экрана 2024-03-16 в 22 43 37" src="https://github.com/reduxjs/redux-toolkit/assets/14319036/7906b01f-8b9e-4d38-bbf4-73547b2eb757">

**Comment by EskiMojo14** [comment]
make sure you don't have any imports from @reduxjs/toolkit/src, you should only be using our public entry points.

**Comment by phryneas** [comment]
Did you maybe accidentally import from `src` in your code?

**Comment by Honan** [comment]
> make sure you don't have any imports from @reduxjs/toolkit/src, you should only be using our public entry points.

Yes, I had an import

`import { UseQueryHookResult } from '@reduxjs/toolkit/src/query/react/buildHooks'`

Thanks a lot for the tip!
