### ISSUE TITLE
UMD distributions from 2.0 onwards

### ISSUE THREAD

**Issue by tommasobratto** [reduxjs/redux-toolkit#4278]
Hi, I've recently read your article about [migrating to 2.0](https://redux.js.org/usage/migrations/migrating-rtk-2), specifically the section about dropping UMD builds.

I might be one of the unlucky folks stuck with having to use an UMD distribution to import RTK in our codebase.

Not-so-short summary: in my company we are using a 3rd party-licensed cross-platform mobile/web framework that uses legacy JS patterns in order to develop our applications. 

We are using RequireJS to load the modules and since we do not have access to the framework codebase nor their build tools, we are unable to setup a bundler to work with anything other than AMD modules. We also cannot use NPM directly, so we're also stuck manually updating our packages in the codebase.

Your UMD distributions (specifically v1.9.5) have allowed us to revolutionise our development patterns.

Since we've been using Redux our code quality has skyrocketed and we are finally capable of delivering decent UI experiences at a fraction of the time needed before RTK's adoption, not to mention the impact on our codebase maintainability. Thanks to RTK we have managed to create a sort of reactivity layer in the quasi-MVC framework we use, not to mention the impact of state management done right. 

I sincerely thank you for your efforts in developing and maintaining Redux Toolkit and RTK Query.

All that said, I won't ask you to restore UMD builds if you do not find the need for it or see the effort as too much of a fuss.

I would ask though if you could please provide some suggestions how to replicate your previous UMD builds in the 2.0 codebase, so that we could try to generate our own distributions for our internal use.

Many thanks and keep up the good work.

**Comment by markerikson** [comment]
Hey! Appreciate the kind words about RTK.

Our build setup for RTK 1.x used a custom wrapper around ESBuild. Since ESBuild doesn't support UMD files, I had to then add an additional step where Rollup took the CJS output and converted it into a UMD file:

https://github.com/reduxjs/redux-toolkit/blob/b74b4f82480317f82a79e0b1c475676d2a132248/packages/toolkit/scripts/build.ts#L249-L279

You could probably replicate that as a standalone step yourself.  Run Rollup as a CLI tool, point it at RTK 2.0's CJS bundles, and tell it to convert that to UMD.

Out of curiosity, if you can't use NPM, how are you installing and using the RTK package?  Also, what _does_ your current project build setup look like?

**Comment by tommasobratto** [comment]
Thank you, I really appreciate the suggestion and will definitely try it out.

To answer your questions:
(beware the wall of text)

The framework we use offers us an IDE to perform the build process without giving any sort of CLI tools or flexibility in the build process for that matter. As it's a licensed product, it's closed source and we are unable to change the build process ourselves. The product's name is Kony Quantum Visualizer.

As long as we stick to RequireJS modules with ES6 syntax we are able to put together a codebase that the framework can build. There is no native NPM support in the IDE though, so for the moment we hacked up a quick and dirty solution to import the files manually into the codebase.

We store the NPM packages separately from the application codebase itself. I'm thinking of creating a script to generate and import UMD modules in the codebase from our NPM packages folder, that we could then run as a job in an Azure pipeline. This would give at least some sort of package management to our workflow.

This might just be one of the weirdest integrations of Redux Toolkit in a stack. We aren't using hooks and we have our custom patterns in order to apply RTK to the framework, but so far it's working excellently and it's compatible with our mobile build as well. 

Between using Redux with Async Thunks and Selectors plus RTK Query API custom query endpoints which wrap around the framework SDK we have a pretty good pattern to build upon.

Combining a store observer pattern with selectors and binding UI subscribers to that has given us a sort of reactive logic we are leveraging to build our UI components. I think we will share our repo of the utilities we developed for our integration once it's cleaned up and ready.

I used to use "old" Redux with "old" React (class-based, no hooks) in another company. I have to say RTK is a huge step up in ease of configuration, extensibility and maintainability. The addition of RTK Query is the icing on the cake.

I'm looking forward to further developments of Redux Toolkit.

**Comment by phryneas** [comment]
As an alternative thought: can you add HTML/your own script tags?

You could use ESM with source maps:

```js
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Untitled</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <!--
    JSPM Generator Import Map
    Edit URL: https://generator.jspm.io/#U2VhYGBkDM0rySzJSU1hcChKTSmtyCrWL8nPz8nOLHEw0jPSMwQAbXQLHCUA
  -->
   <script type="importmap">
  {
    "imports": {
      "@reduxjs/toolkit": "https://ga.jspm.io/npm:@reduxjs/toolkit@2.2.1/dist/redux-toolkit.modern.mjs"
    },
    "scopes": {
      "https://ga.jspm.io/": {
        "immer": "https://ga.jspm.io/npm:immer@10.0.4/dist/immer.mjs",
        "redux": "https://ga.jspm.io/npm:redux@5.0.1/dist/redux.mjs",
        "redux-thunk": "https://ga.jspm.io/npm:redux-thunk@3.1.0/dist/redux-thunk.mjs",
        "reselect": "https://ga.jspm.io/npm:reselect@5.1.0/dist/reselect.mjs"
      }
    }
  }
  </script>
  
  <!-- ES Module Shims: Import maps polyfill for older browsers without import maps support (eg Safari 16.3) -->
  <script async src="https://ga.jspm.io/npm:es-module-shims@1.8.3/dist/es-module-shims.js" crossorigin="anonymous"></script>
  
  <script type="module">
    import * as Toolkit from "@reduxjs/toolkit";
  
    // Write main module code here, or as a separate file with a "src" attribute on the module script.
    console.log(Toolkit);
  </script>
</body>
</html>
```

Or, even without a source map:
```
<script src="https://esm.sh/@reduxjs/toolkit@2.2.1"></script>
```

**Comment by tommasobratto** [comment]
> As an alternative thought: can you add HTML/your own script tags?
> 
> You could use ESM with source maps:
> 
> ```js
> <!doctype html>
> <html>
> <head>
>   <meta charset="utf-8">
>   <title>Untitled</title>
>   <meta name="viewport" content="width=device-width, initial-scale=1">
> </head>
> <body>
>   
>    <script type="importmap">
>   {
>     "imports": {
>       "@reduxjs/toolkit": "https://ga.jspm.io/npm:@reduxjs/toolkit@2.2.1/dist/redux-toolkit.modern.mjs"
>     },
>     "scopes": {
>       "https://ga.jspm.io/": {
>         "immer": "https://ga.jspm.io/npm:immer@10.0.4/dist/immer.mjs",
>         "redux": "https://ga.jspm.io/npm:redux@5.0.1/dist/redux.mjs",
>         "redux-thunk": "https://ga.jspm.io/npm:redux-thunk@3.1.0/dist/redux-thunk.mjs",
>         "reselect": "https://ga.jspm.io/npm:reselect@5.1.0/dist/reselect.mjs"
>       }
>     }
>   }
>   </script>
>   
>   
>   <script async src="https://ga.jspm.io/npm:es-module-shims@1.8.3/dist/es-module-shims.js" crossorigin="anonymous"></script>
>   
>   <script type="module">
>     import * as Toolkit from "@reduxjs/toolkit";
>   
>     // Write main module code here, or as a separate file with a "src" attribute on the module script.
>     console.log(Toolkit);
>   </script>
> </body>
> </html>
> ```
> 
> Or, even without a source map, use a CDN that already does some precompilation for you:
> ```
> <script src="https://esm.sh/@reduxjs/toolkit@2.2.1"></script>
> ```

Thanks for the suggestion. I could add script tags for the web build, but our codebase needs to be mobile-ready, so all necessary modules need to be present in order to produce a valid mobile build.

We are unable to differentiate the build steps for the two builds without some fundamental divergence in the codebase. The framework does not offer that level of customization in the build process and we already had issues with maintaining a divergent branching strategy for two of our mobile applications using the same codebase.

Essentially we need to maintain almost 1-to-1 interoperability between our web and our mobile builds in order to share feature development. We use the framework SDK to manage some cross-platform device/browser APIs and some external integrations are managed with native code on mobile side, but the core features need to be fully cross-platform.

**Comment by tommasobratto** [comment]
Just an update. I've made a demo script to produce viable distros that the framework build step is able to digest.

I had to configure each toolkit dependency for the task, pointing Rollup at:
- redux-toolkit.browser.mjs
- rtk-query.browser.mjs
- redux.browser.mjs
- redux-thunk.mjs
- reselect.browser.mjs
- immer.production.mjs

Had to go straight for the browser distributions as others needed ```
process.env.NODE_ENV
``` defined, for which I couldn't even create a stub.

I set up Rollup to use ```
rollup/plugin-babel
``` in order to convert the .mjs targets to ES2015 and output them in AMD format.

I still need to tinker a bit with the module IDs but just from a test run on one of our applications it seems like this could do the trick.

I will post the results once I have the script set up, if anyone else with the same issue comes by.

**Comment by tommasobratto** [comment]
Wrapping it up: [redux-toolkit-umd-distribution](https://github.com/tommasobratto/redux-toolkit-umd-distribution)

I encountered issues with AMD module IDs when importing the generated files so I switched back to targeting UMD output. I tried to get the output as close as possible to the 1.9.* UMD distros for maximum compatibility. 

I've ended up targeting  the _*.mjs_ builds for all packages.
