### ISSUE TITLE
`useStableQueryArgs` chokes on BigInt

### ISSUE THREAD

**Issue by rkofman** [reduxjs/redux-toolkit#4279]
When serializing a query object that includes a `BigInt`, rktQuery blows up with:
```
TypeError: Do not know how to serialize a BigInt
```

This seems to be due to this code in `buildQueryHooks`:
```
useStableQueryArgs(skip ? skipToken : arg, defaultSerializeQueryArgs, context.endpointDefinitions[name], name);
```
Which uses `defaultSerializeQueryArgs` instead of user-supplied overrides (i.e. `serializeQueryArgs`) -- where users could override the behavior and make bigints safe to serialize.

**Comment by riqts** [comment]
Worth noting that currently the `buildQueryHooks` code intentionally overrides the endpoint definitions `serializeQueryArgs` so that refetching and cache lifecycles proceed as intended when a queryArg changes.

My thoughts on how to approach it:

1. Add handling for BigInt inside `defaultSerializeQueryArgs`

    * This might be the obvious answer I am not sure if there's a clear reason why BigInt was not handled in the first place or not
    * Alternatively there might be an obvious reason why its not lol 

2. Add an option to bypass `defaultSerializeQueryArgs`

    * Kind of a risk as users may not understand they are taking on the responsibility of managing refetch and unique keys themselves
    * really simple to implement :D

**Comment by EskiMojo14** [comment]
> This might be the obvious answer I am not sure if there's a clear reason why BigInt was not handled in the first place or not
> Alternatively there might be an obvious reason why its not lol

because JSON.stringify doesn't handle it and we haven't added any special behaviour to it
![image](https://github.com/reduxjs/redux-toolkit/assets/18308300/4d807fc7-9613-49c0-90c8-e3aad3a5a467)


the only thing defaultSerializeQueryArgs does before calling JSON.stringify is ensuring keys are in a predictable order, so `{ foo: 1, bar: 2 }` serializes to the same string as `{ bar: 2, foo: 1 }`

**Comment by rkofman** [comment]
`serializeQueryArgs` [is documented](https://async-transformresponse--rtk-query-docs.netlify.app/api/createapi/#serializequeryargs) as:

> Accepts a custom function if you have a need to change the creation of cache keys for any reason.

To me, it is surprising that changing how cache keys are created _doesn't_ affect refetching and cache lifecycles. The example documenting the per-endpoint version reinforces this:

>     // Example: an endpoint with an API client passed in as an argument,
>     // but only the item ID should be used as the cache key

The API client isn't likely to change and isn't likely to trigger new requests.

If I understand correctly (and I very well might not), the reason to _not_ just use the user-provided `serializeQueryArgs` is to allow e.g. infinite-loading paginated endpoints. The storage cache-key remains the same, but when the page param changes, the query still needs to fire and fetch new data (whose merging is then perhaps managed somewhat manually).

In my mind, the ideal API would be to use the use-provided `serializeQueryArgs` override for both storage and lifecycle. Users would then be able to use `forceRefetch` to force fetching.

Alternately, if two separate cache key implementations really are useful; it might be best to allow users to override either one. Conceptually, I would think of them as: `serializeQueryArgsForFetching` and `serializeQueryArgsForStorage`.

**Comment by riqts** [comment]
> Worth noting that currently the buildQueryHooks code intentionally overrides the endpoint definitions serializeQueryArgs so that refetching and cache lifecycles proceed as intended when a queryArg changes.

My apologies, I was wrong here. The reason `defaultSerializeQueryArgs` is used instead of the user provided `serializeQueryArgs` is to ensure the hooks dependancy retriggers when the queryArgs change.

**Comment by rkofman** [comment]
Since the serialization for `StableQueryArgs` _doesn't_ need to be reversible, would it be useful to just implement a mapping of `bigint` values to _some_ serialized form directly in `StableQueryArgs`? That way it just.. silently has the correct behavior w/o any user impact.

**Comment by rkofman** [comment]
Anything I can do to facilitate a code review / merging of my PR above?

**Comment by phryneas** [comment]
Unfortunately, right now we're just all pretty preoccupied - we'll get around to the PR eventually, but I'm sorry I can't guarantee a time frame on it.
That said, the PR contains a PR build in the CodeSandbox preview that you can add to your `package.json` in the meantime - I hope that makes it already usable for you.

**Comment by rkofman** [comment]
I appreciate the pointer to the CodeSandbox preview. It's definitely a better workaround than I had landed on -- and something I totally overlooked as a possibility. Will follow-up on other comments in the PR!
