### ISSUE TITLE
`redux-toolkit.legacy-esm.js` not actually compatible with Webpack 4 due to optional chaining

### ISSUE THREAD

**Issue by Zacqary** [reduxjs/redux-toolkit#4282]
Upgrading to Redux Toolkit 2.x on a Webpack 4 repo fails due to this line:

```js
if (cache?.has(value))
```

Webpack 4 doesn't support optional chaining without some additional plugins that can break many large projects. Is it possible to switch back to the pre-2.x transpiling method for the legacy build?

**Comment by markerikson** [comment]
Yeah, you're right, that's not getting transpiled properly - that build _should_ have optional chaining being compiled away.

......

whoa. _That's_ clearly not right:

```ts
  // ESM, embedded `process`: fallback for Webpack 4,
  // which doesn't support `exports` field or optional chaining
  {
    format: 'esm',
    name: 'legacy-esm',
    target: 'esnext',
    minify: false,
    env: '',
  },
```

I can try to fix that this evening.

Actually rather surprised no one reported this yet.

That should be `target: 'es2017'`.

**Comment by Zacqary** [comment]
> Actually rather surprised no one reported this yet.

I guess this is useful data on how many codebases still on Webpack 4 are trying to upgrade Redux (not many). 

Thanks for the quick response!

**Comment by markerikson** [comment]
Okay, that's out in https://github.com/reduxjs/redux-toolkit/releases/tag/v2.2.2 !
