### ISSUE TITLE
Argument of type 'AsyncThunkAction<{ id: number; }, void, AsyncThunkConfig>' is not assignable to parameter of type 'UnknownAction'.

### ISSUE THREAD

**Issue by seafronthu** [reduxjs/redux-toolkit#4299]
@EskiMojo14 I made a [demo](https://stackblitz.com/edit/stackblitz-starters-vbgz2h?file=src%2FApp.tsx), it does not work after defining the typed hooks.

_Originally posted by @mrdulin in https://github.com/reduxjs/redux-toolkit/issues/4032#issuecomment-1874789490_

**Comment by seafronthu** [comment]
This issue also exists in vscode.
``` javascript
const initialState: StateINF = {
  selectedTabId: 0,
  isDragging: false,
  value: []
}
export const addTab = createAsyncThunk('tabs/addTab1', async (): Promise<{ id: number }> => {
  return {
    id: 1
  }
})
const tabsSlice = createSlice({
  name: 'tabs',
  initialState,
  reducers: {
    // addTab(state, action: { payload: { id: number; url: string } }) {
    //   state.value = [...state.value, action.payload]
    // },
    changeTab(state) {
      state.value = []
    },
    delTab(state) {
      state.value = []
    }
  },
  extraReducers(builder) {
    builder.addCase(addTab.fulfilled, (state, action: PayloadAction<{ id: number }>) => {
      console.log(state, action)
    })
  }
})
export const useTabsSelector = () =>
  useSelector<{ tabs: StateINF }>((state) => state.tabs) as StateINF
export const { changeTab, delTab } = tabsSlice.actions
export const useAddTabDispatch = () => {
  const dispatch = useDispatch()
  return () => dispatch(addTab())
}
export default tabsSlice
```
![image](https://github.com/reduxjs/redux-toolkit/assets/50374650/61641144-39ea-47ff-8eab-db72f623c9e3)
![image](https://github.com/reduxjs/redux-toolkit/assets/50374650/f85bba0b-2f23-4580-8337-b1668897f4e7)
version: "@reduxjs/toolkit": "^2.2.2" "react-redux": "^9.1.0",

**Comment by iliapnmrv** [comment]
hey! any updates on this?

**Comment by seafronthu** [comment]
> hey! any updates on this?

`"react-redux": "^9.1.0"`
`"@reduxjs/toolkit": "^2.2.2"`
`"@types/react": "^18.2.47"`
`"@types/react-dom": "^18.2.18"`
`"typescript": "^5.4.3"`
I don't know what caused it, it's too uncomfortable.

**Comment by EskiMojo14** [comment]
Please follow our [standard Typescript setup](https://redux.js.org/usage/usage-with-typescript#standard-redux-toolkit-project-setup-with-typescript), you shouldn't be annotating a type on your store and you should be using pre-typed versions of the hooks.
