### ISSUE TITLE
flattenArg:true - does NOT work.

### ISSUE THREAD

**Issue by krasevych** [reduxjs/redux-toolkit#4304]
I have scheme like this:
```
//......
   "parameters": [
          {
            "name": "keys",
            "in": "query",
            "description": "test",
            "required": false,
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ]
//.....
```
take a look on ` "required": false`.

gen result when `flattenArg:true` is `type RequestArg = string[]` - wrong!
gen result when `flattenArg:false` is `type RequestArg ={ keys?: string[]` } - good! because `?`

Expected result when `flattenArg:true`: `type RequestArg = string[] | undefined`

**Comment by markerikson** [comment]
Should be live in https://github.com/reduxjs/redux-toolkit/releases/tag/%40rtk-query%2Fcodegen-openapi%402.0.0-alpha.0 ! Please try it out and let us know if it works.
