### ISSUE TITLE
Add a createMiddleware utility

### ISSUE THREAD

**Issue by will-stone** [reduxjs/redux-toolkit#431]
Firstly, thanks @markerikson and gang for this project. It really helps with TypeScript-based projects.

My team and I have just started using the `builder` callback of `createReducer` on a work project and it really helps with passing through types (we were previously casting on `action` to force types in). We also use custom middleware (over thunks, sagas, observables etc.) and have used the `.match()` method to correctly type the payload:

```ts
const middleware = (): Middleware => store => next => async action => {
  const result = next(action);

  // actionName
  if (actionName.match(action)) {
    setInterval(
      () => store.dispatch(asyncActionHappened(action.payload)),
      5000
    );
  }

  // anotherActionName
  else if (anotherActionName.match(action)) {
    const data = await fetch(action.payload).then(resp => resp.json());
    store.dispatch(dataFulfilled(data));
  }

  return result;
};
```

I was wondering if it the team would be interested in something similar to `createReducer` but for middleware? I have it working and will submit the PR shortly.

```ts
const customMiddleware = createMiddleware(builder =>
  builder
    .addCase(actionName, (action, dispatch) => {
      setInterval(() => dispatch(asyncActionHappened(action.payload)), 5000);
    })
    .addCase(anotherActionName, async (action, dispatch) => {
      const data = await fetch(action.payload).then(resp => resp.json());
      dispatch(dataFulfilled(data));
    })
);
```

**Comment by phryneas** [comment]
I feel this treads into #237 territory and could be one of many possible ways we could go. Have you read that thread?

**Comment by will-stone** [comment]
Hi @phryneas, to be honest I hadn't read that thread for a couple of weeks. Obviously I'm biased, but I do quite like the simplicity of my solution: https://github.com/reduxjs/redux-toolkit/pull/432

**Comment by phryneas** [comment]
The problem I'm seeing is that this suggestion/#432 doesn't tick all the boxes we have identified in #237.

While I do like the use of the builder notation here (obviously, the biased one here is me, as I've introduced that one to RTK :laughing:), this does currently not integrate with getDefaultMiddleware or configureStore and even if it would, it doesn't address post-configureStore adding and removing of additional cases.

**Comment by will-stone** [comment]
Hmmm, indeed I haven’t looked into those. Are they things that just won’t work with the builder technique? Or could this coexist with another method?

**Comment by phryneas** [comment]
There's no general conflict with the builder technique here, it would just need to tick a lot of additional boxes. And up until now I'm not sure that we've really identified all the things we'd expect from such a middleware in the end.

So I guess a first step would be to go through #237, collect all the requirements and discuss if we might still be missing anything. From that, #432 *might* be a starting point - or we'll notice that we'd have to go a completely different route. I'm not really sure on this. 

Right now, we're focusing on finishing #374 to release 1.3.0 with the entityAdapter and asyncThunkCreator APIs, so we won't be adding anything new before that.

But if you want to go on and start by summarizing all requirements of #237, that could be a start on what we're going to do next. If you're up to that, I suggest continuing this in #237 :)

**Comment by will-stone** [comment]
Okay, I'll close this in favour of #237 and add a comment there. Thanks.
