### ISSUE TITLE
Expect fetch to have been called with url in test

### ISSUE THREAD

**Issue by bigmasonwang** [reduxjs/redux-toolkit#4318]
When using `fetch` API, in the test I can simply write 
```
expect(fetch).toHaveBeenCalledWith(
  "https://pokeapi.co/api/v2/pokemon/bulbasaur",
);
```
But after migrate to `rtk-query`, I got the error:
```
AssertionError: expected "spy" to be called with arguments: [ Array(1) ]

Received: 

  1st spy call:

  Array [
-   "https://pokeapi.co/api/v2/pokemon/bulbasaur",
+   Request {
+     "agent": undefined,
+     "compress": true,
+     "counter": 0,
+     "follow": 20,
+     "size": 0,
+     "timeout": 0,
+     Symbol(Body internals): Object {
+       "body": null,
+       "disturbed": false,
+       "error": null,
+     },
+     Symbol(Request internals): Object {
+       "headers": Headers {
+         Symbol(map): Object {},
+       },
+       "method": "GET",
+       "parsedURL": Url {
+         "auth": null,
+         "hash": null,
+         "host": "pokeapi.co",
+         "hostname": "pokeapi.co",
+         "href": "https://pokeapi.co/api/v2/pokemon/bulbasaur",
+         "path": "/api/v2/pokemon/bulbasaur",
+         "pathname": "/api/v2/pokemon/bulbasaur",
+         "port": null,
+         "protocol": "https:",
+         "query": null,
+         "search": null,
+         "slashes": true,
+       },
+       "redirect": "follow",
+       "signal": AbortSignal {},
+     },
+   },
  ]


Number of calls: 1
```
Why this happened? Here is the sandbox [link](https://codesandbox.io/p/devbox/morning-moon-xpzhky?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluhrdtbf00073b87rna76bba%2522%252C%2522sizes%2522%253A%255B56.19153675200445%252C43.80846324799555%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluhrdtbf00023b87p0vgon6s%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluhrdtbf00043b87cajq0ehd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluhrdtbf00063b870nivubxi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B53.75828116303239%252C46.24171883696761%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluhrdtbf00023b87p0vgon6s%2522%253A%257B%2522id%2522%253A%2522cluhrdtbf00023b87p0vgon6s%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Froot%252F.cache%252Fnpm%252F_logs%252F2024-04-02T02_29_08_706Z-debug-0.log%2522%252C%2522id%2522%253A%2522cluhrj1ck00g93b87v1f96gpi%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluhrj1ck00g93b87v1f96gpi%2522%257D%252C%2522cluhrdtbf00063b870nivubxi%2522%253A%257B%2522id%2522%253A%2522cluhrdtbf00063b870nivubxi%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cluhsc6jf00f43b873jm9qvhn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluhsc6jf00f43b873jm9qvhn%2522%257D%252C%2522cluhrdtbf00043b87cajq0ehd%2522%253A%257B%2522id%2522%253A%2522cluhrdtbf00043b87cajq0ehd%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluhrfojp00dl3b877wld56vu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cluhrfoqz003sdjipdbrt1467%2522%257D%252C%257B%2522id%2522%253A%2522cluhsdvik00op3b8744r0n27k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cluhsdvom004ddjipgwm083lq%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluhsdvik00op3b8744r0n27k%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by phryneas** [comment]
`fetch` has [two different signatures](https://developer.mozilla.org/en-US/docs/Web/API/fetch#syntax):
```js
fetch(url, options)
```
and
```
fetch(requestObject)
```

`fetchBaseQuery` uses the second one.

I'd recommend that you use something like `msw` to intercept outgoing requests, but you probably can also mock, but then you'd have to inspect the Request object passed into the mock closer.

**Comment by bigmasonwang** [comment]
Thanks @phryneas , and this works for me

```js
  // vitest-fetch-mock
  fetch.mockResponseOnce(JSON.stringify({ name: "bulbasaur" }));
  const expectedRequest = new Request(
    "https://pokeapi.co/api/v2/pokemon/bulbasaur",
    { signal: new AbortController().signal },
  );
  expect(fetch).toHaveBeenCalledWith(expectedRequest);
```
