### ISSUE TITLE
remove implicit conversion to camel case of openapi operation id.

### ISSUE THREAD

**Issue by tombohub** [reduxjs/redux-toolkit#4322]
if open api schema states `operationId: house_inventory_items_retrieve` 

than this should work in RTK query code generation: `filterEndpoints: [/inventory_items/i],`

For a library that promotes no side effects this should not happen.

**Comment by phryneas** [comment]
> For a library that promotes no side effects this should not happen.

You just earned yourself an issue close with a salty comment. We will definitely not help you unpaid in our free time with that behaviour.

**Comment by tombohub** [comment]
@phryneas You are right, I apologize. I was salty at the moment and harshly opened issue instead of composing myself. Please forgive me! 

Can we work around it? Could we please just have a sentence in documentation that says operationId is converted to camelCase?

**Comment by phryneas** [comment]
You're welcome to open a PR to the docs.
