### ISSUE TITLE
RTK purges the data even if white listed

### ISSUE THREAD

**Issue by maheshchandgl** [reduxjs/redux-toolkit#4323]
How to reproduce:
Step 1: Open an inner screen for which data need to be persisted.
Step 2: Keep the screen open lock the android device.
Step 3: Unlock the device after a minute.
The persisted data is purged by RTK even we white listed the data to be persisted.

Let me know if further details are required.

**Comment by markerikson** [comment]
Yeah, afraid this doesn't give me any idea what you're actually referring to.

What do you mean by "persisted" here? are you talking about `redux-persist`?

At a minimum we'd need to see a full repo that demonstrates this happening in order to investigate.
