### ISSUE TITLE
RTK Optimistic Updates in "Select" element default value not working without refreshing page

### ISSUE THREAD

**Issue by rosgeorg** [reduxjs/redux-toolkit#4326]
### Discussed in https://github.com/reduxjs/redux-toolkit/discussions/4325

<div type='discussions-op-text'>

<sup>Originally posted by **rosgeorg** April  4, 2024</sup>
Hello, I'm facing this situation where I'm trying to modify the default value of a select (dropdown) element using optimistic updates, but even when my query's cache is correctly updated after mutation, the default value of this select won't change until I refresh the page. Is there a way to fix this?

I also added a "div" with the same data inside of it, and it get's updated correctly inside of the div, but not in the default value
 
**** So, this was marked as resolved but maybe I did not explain myself correctly, and I think I was missing some important details:

Even if I pick value or defaultValue it is the same result. The thing is I have 2 select/dropdown elements in different parts of the UI which control and display the same data. One of them is inside a modal with a "Save" button which triggers a mutation, which optimistically updates the cache from the query with the selected value. 

What I'm trying to do is to make the other select/dropdown to display the data submitted by the first select as soon as the mutation gets triggered, and of course, that modified value should become the new "defaultValue" for that 2nd select element****

<img width="803" alt="Screenshot 2024-04-04 at 7 44 15 p m" src="https://github.com/reduxjs/redux-toolkit/assets/15363871/a4f24607-c637-48ff-9b2c-e84861e799aa">

Thanks in advance for your help
</div>

**Comment by markerikson** [comment]
FWIW, I _did_ already answer your question over in the other thread :)

**Comment by rosgeorg** [comment]
Hello, I did look at the answer, but again, maybe I'm not explaining myself clearly? I think that answer is for a different question. In this case, I'm looking to have a "defaultValue" because that's the value that I want the user to see everytime it opens that modal. So "value" is not what I'm trying to update but the initial (or. default) value

**Comment by markerikson** [comment]
That's my point, though. `defaultValue` only sets the _initial_ value of an input in React. It does not ever _update_ the value at all.
