### ISSUE TITLE
Option to provide an initial data to the query endpoint

### ISSUE THREAD

**Issue by duskpoet** [reduxjs/redux-toolkit#4334]
I have an application with some data preseeded in the back-end (and it's not written in JavaScript). Some of that data may be invalidated at some point, so I want to fetch it with an RTK query when that happens.
Here is how it may look:
```ts
const initialState = window.globalInitialState.user;
const api = createApi({
  reducerPath: 'user',
  tagTypes: ['User'],
  endpoints: (builder) => ({
    getUser: builder.query({
      providesTags: ['User'],
      query: '/api/user',
      initialState,
    })
  }),
});
```

**Comment by hardikhere** [comment]
@duskpoet 
you can give a default value when using this hook, `useGetUsersQuery()`
`const {data = initialState} = useGetUsersQuery()`

**Comment by duskpoet** [comment]
But that would unwillingly trigger the api request

**Comment by duskpoet** [comment]
Like what? The initial state can behave like the request successfully made behind the scenes, so it should be the same as the current behavior.

**Comment by markerikson** [comment]
You should be able to do this via the hydration process:

https://redux-toolkit.js.org/rtk-query/usage/persistence-and-rehydration

**Comment by hardikhere** [comment]
Yes hydration is fine but useSWR has better way, they take `fallback` object
https://swr.vercel.app/docs/advanced/understanding.en-US#fallback

**Comment by phryneas** [comment]
The fallback option would be horrible here, honestly. 

We have cache collection of data that's not used anymore.

Imagine your hook starts out with `initialData` from 3am. 
Then you fetch and get data from 5pm. 
Then your component unmounts for a minute, the new data gets removed from the cache and the next moment your component mounts again you are back at data from 3am.
Your data would go backwards in time.

**Comment by duskpoet** [comment]
I can try to prepare a PR if this feature does seem reasonable.

**Comment by phryneas** [comment]
Like I said, I'd rather avoid it - it can be quite confusing. I'd assume that for what you want right now, you could use rehydration.

**Comment by duskpoet** [comment]
Is there any example of how to achieve this with rehydration? The docs on the topic are very scarce, and the API is complicated.

**Comment by DaniAcu** [comment]
@duskpoet Maybe you are looking for something like api.util.updateQueryData

https://redux-toolkit.js.org/rtk-query/api/created-api/api-slice-utils#updatequerydata

**Comment by duskpoet** [comment]
@DaniAcu yea, that's a possibility, though it complicates the usage - need to issue this call and wait for its effects before attaching the store to react, otherwise, there will be an unnecessary API call.

**Comment by phryneas** [comment]
> Is there any example of how to achieve this with rehydration? The docs on the topic are very scarce, and the API is complicated.

Sorry I didn't get around to answer back then.

1. On the server, make all requests with RTK Query. Dump your slice into a script tag or something that will end up in a `window.foo` global in the browser.
2. In your api:
```js
createApi({
  // ...
  extractRehydrationInfo(action) {
    if (action.type == "rehydrateMe") return action.payload
  },
})
```
3. In the browser `dispatch({ type: "rehydrateMe", payload: window.foo })`

**Comment by dacunagm** [comment]
@duskpoet I found that extractRehydrationInfo should return the state structure specifically for a createApi slice, maybe the case that @phryneas shared is not enough for your case. I found this work around checking the internals of of the library, maybe it could helps you in this case.

```js
import { nanoid } from "@reduxjs/toolkit";

createApi({
  // ...
  extractRehydrationInfo(action) {

    if (action.type === "rehydrateMe") {
      return {
        queries: {
          "getUser()": {
            status: 'fulfilled',
            endpointName: 'getUser',
            requestId: nanoid(),
            originalArgs: "",
            startedTimeStamp: Date.now(),
            data: action.payload,
            fulfilledTimeStamp: Date.now()
          },
        },
        mutations: {},
        provided: {},
        subscriptions: {}
      }
    }
  },
})
```

Then you could dispatch:

```js
store.dispatch({ type: "rehydrateMe", payload: window.foo })
```

**Comment by DaniAcu** [comment]
@duskpoet I found that extractRehydrationInfo should return the state structure specifically for a createApi slice, maybe the case that @phryneas shared is not enough for your case. I found this work around checking the internals of of the library, maybe it could helps you in this case.

```js
import { nanoid } from "@reduxjs/toolkit";

createApi({
  // ...
  extractRehydrationInfo(action) {

    if (action.type === "rehydrateMe") {
      return {
        queries: {
          "getUser()": {
            status: 'fulfilled',
            endpointName: 'getUser',
            requestId: nanoid(),
            originalArgs: "",
            startedTimeStamp: Date.now(),
            data: action.payload,
            fulfilledTimeStamp: Date.now()
          },
        },
        mutations: {},
        provided: {},
        subscriptions: {}
      }
    }
  },
})
```

Then you could dispatch:

```js
store.dispatch({ type: "rehydrateMe", payload: window.foo })
```

**Comment by phryneas** [comment]
That was my step 1 above, yes. "Dump your api slice..." ;)

**Comment by amitdahan** [comment]
> 1. On the server, make all requests with RTK Query

In my case, the server is written in Go, is this the only option for using `extractRehydrationInfo`?

**Comment by phryneas** [comment]
@amitdahan 
You can also dump an api slice once, look at it's shape and replicate that in go, but you might need to re-do that at one point in the future if we change our spi slice shape.

**Comment by duskpoet** [comment]
This approach still requires to hold off react mounting store to avoid the api request, right?

**Comment by phryneas** [comment]
How else would you provide "initial data"? 
Yes, you have to know the initial data before you mount your React component that needs that initial data.

The example you gave in the initial post would require that, too.

**Comment by duskpoet** [comment]
in our case we have it injected into the page by server renderer, so we can access it like a global variable anytime in the javascript code

**Comment by DaniAcu** [comment]
@phryneas Ou I didn't get well then, sorry. I hope the example helps in some way at least. 

@duskpoet I think depends on what you mean by "hold off", the dispatch should run before render. But doesn't need to wait for anything. 

In my exploration I did:

```js
dispatch({ type: 'Hydrate', payload: window.foo })


const root = createRoot(document.getElementById('root'));

root.render(<App />);
```

And didn't throw the request because it was already in the store. I would recommend pay attention to parameters of the endpoint but you don't have params in you getUser endpoint.

**Comment by duskpoet** [comment]
Right, in our case, the store is created inside the react tree cause it depends on the routing, so it goes deeper than the react router. And I think the following wouldn't work too:
```jsx
  const store = createStore(...);
  store.dispatch({ type: 'Hydrate', payload: window.foo });
  return (
    <Provider store={store}>
       {children}
    </Provider>
  );
}
 ```
because of the thunk middleware

**Comment by phryneas** [comment]
> because of the thunk middleware

What do you mean by that?

**Comment by duskpoet** [comment]
If the chain of reaction to this action will emit an async action, then the react effect may fire first, initiating the API request

**Comment by phryneas** [comment]
Unless you have a custom middleware that is `async`, the reducer will always execute synchronously on dispatch.

**Comment by duskpoet** [comment]
Ok, thanks! Let's close the issue then
