### ISSUE TITLE
isFetching does not seem to act like document suggests.

### ISSUE THREAD

**Issue by grosenberry-Novetta** [reduxjs/redux-toolkit#4344]
We have a pretty normal use case where we provide a useEffect based on the loading and fetching states of our useQuery hook.  When a cache is not returned the flags isLoading and isFetching work correctly however when that hook returns a cached result isFetching is always false.  Documentation to me suggests that isFetching would be set to true when the hook is being fired.  If this is not the intended case I'd like to understand why.  I've scoured the internet for this answer and am surprised to see now results. 

Current version is 1.9.5

**From the docs**
![image](https://github.com/reduxjs/redux-toolkit/assets/45113388/47de5482-2c9e-4977-8416-ff675169f4f3)

**Comment by EskiMojo14** [comment]
if you subscribe to something that's already in cache, you don't need to fetch anything - thus no fetching occurs

**Comment by markerikson** [comment]
Yep, that flag indicates that an actual request is in progress. If there's a cache hit, it _won't_ trigger a request.

**Comment by EskiMojo14** [comment]
could you give an example of what you're trying to do? generally the loading flags are tied to what you'd want to do with the UI:
- `isLoading` - i have no data to display yet, so I'd want some sort of skeleton UI or perhaps a larger spinner replacing the final UI
- `isFetching` - i might have data already, but I'm fetching something new, so I might want a less intrusive spinner while I keep the previous data visible

neither of these UI phases seem desirable to be displayed when you've got a cache hit, you would just want to display your normal data view.

i disagree that the docs don't accurately convey this, but am open to specific suggestions of improvements.

**Comment by markerikson** [comment]
Seems like the fact that `data` _exists_ indicates a cache hit, as does `isSuccess`.
