### ISSUE TITLE
Inconsistency in Documentation of Quick Start

### ISSUE THREAD

**Issue by jdKheppar** [reduxjs/redux-toolkit#4346]
### Issue Description

In the [quick-start](https://redux-toolkit.js.org/tutorials/quick-start) page of the documentation, the filename is not correctly mentioned. It should be .ts instead of .js as highlighted by the below screenshot
![Screenshot (301)](https://github.com/reduxjs/redux-toolkit/assets/130550913/48e974c0-73b3-4fc7-b056-30c448798bc5)

### Solution

The name of the file should be .ts

**Comment by sayedulkrm** [comment]
Yeah, but I think it doesn't matter. The person who came this far must have some knowledge of when to use what :))
