### ISSUE TITLE
Netlify lowercasing and adding trailing slash (docusaurus)

### ISSUE THREAD

**Issue by bravo-kernel** [reduxjs/redux-toolkit#435]
Hi, just wanted to share that we (finally) figured out how to prevent Netlify from altering the docusaurus links (and thus causing 301 and 404 problems).  

https://github.com/facebook/docusaurus/issues/2394#issuecomment-599039072

Changes settings take effect immediately, Try by browsing directly to e.g. https://redux-toolkit.js.org/api/createAction.

**Comment by markerikson** [comment]
Nice!  Updated that setting for all the Redux docs sites.  Thanks!
