### ISSUE TITLE
You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux.

### ISSUE THREAD

**Issue by jonathanstiansen** [reduxjs/redux-toolkit#438]
@markerikson you look to have looked on this problem before.

We're using the standard Expo config for webpack (just like create react app we don't even have our own webpack config file). 
Redux-toolkit version is: 1.2.5

`
You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
`

The command to run expo, which calls webpack, is `expo start` if I call `NODE_ENV=production expo start` it still doesn't go away. I'm not sure why that would be either.

Any debug steps or insights you might have?

**Comment by markerikson** [comment]
Nothing specific, unfortunately.  I can only suggest reviewing exactly what files are getting included in the build process and how they're getting transformed.
