### ISSUE TITLE
Typescript throws error when trying to configure the option of getDefaultMiddleware()

### ISSUE THREAD

**Issue by huntdream** [reduxjs/redux-toolkit#439]
![image](https://user-images.githubusercontent.com/7903755/77149758-48c60b80-6acd-11ea-9a84-2bf1e6cda3ae.png)

**Comment by phryneas** [comment]
With the tooltip all over your code, this is gonna be a tricky one.

But without seeing your code: when you use getDefaultMiddleware, you can either specify
* no generic arguments
* one generic argument (State) and pass no argument
* specify *all* generic arguments.

Without seeing your code - it looks like you didn't do that.

**Comment by huntdream** [comment]
@phryneas  Hi, this is part of my code, it seems I can only configure these options with `true`
```
export const store = configureStore({
  reducer: persistedReducer,
  middleware: [
    ...getDefaultMiddleware<RootState>({
      serializableCheck: {
        ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
      },
      immutableCheck: true,
      thunk: true,
    }),
    logger,
  ] as const,
})
```
![image](https://user-images.githubusercontent.com/7903755/77151908-e0c5f400-6ad1-11ea-9dc8-eb17115066d9.png)
![image](https://user-images.githubusercontent.com/7903755/77152540-220ad380-6ad3-11ea-88e8-03262ec9d4a5.png)

**Comment by phryneas** [comment]
As I said, when you are passing a generic argument and a function argument, you have to pass ALL generic arguments - something like (probably a little bit different, try around):

```ts
getDefaultMiddleware<RootState, {
      serializableCheck: {
        ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
      }
}>({
      serializableCheck: {
        ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
      }
})
```


This is due to the fact that TS can either infer all arguments or none. If you provide `RootState`, but not the second argument it falls back to the default.

**Comment by huntdream** [comment]
Thanks for your help, It worked ! 🎉 

```
export const store = configureStore({
  reducer: persistedReducer,
  middleware: [
    ...getDefaultMiddleware<
      RootState,
      {
        serializableCheck: {
          ignoredActions: string[]
        }
      }
    >({
      serializableCheck: {
        ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
      },
    }),
    logger,
  ] as const,
})
```
Learned something new, thanks again!

**Comment by Aleksandr-Pod** [comment]
Gosh, I spent a lot of time breaking my mind.
But finally I wrote simple
`const store = configureStore({
  reducer: {
    user: persistedUserReducer,
    // vacancies: persistedVacancy
  },
  middleware: getDefaultMiddleware => [
    ...getDefaultMiddleware({
      serializableCheck: {
        ignoreActions: true,
      },
    }),
  ],
});`

**Comment by markerikson** [comment]
@Aleksandr-Pod : note that you shouldn't have to spread the `getDefaultMiddleware()` result at all - just return it directly.

**Comment by phryneas** [comment]
And if you want to add other middleware, use 
```
configureStore({ 
  ..., 
  middleware: getDefaultMiddleware => getDefaultMiddleware({ ... }).concat(otherMiddleware)
})
```

[as we show it in the documentation](https://redux-toolkit.js.org/api/getDefaultMiddleware#intended-usage).

Any other form of spreading will erase important type information.
