### ISSUE TITLE
`refetchQuery` triggers `queryThunk` without partaking in `runningQueries` deduplication

### ISSUE THREAD

**Issue by phryneas** [reduxjs/redux-toolkit#4391]
This was kinda reported in #2802, but actually has nothing to do with lazy queries, so that issue went on a very wrong direction.

**Comment by markerikson** [comment]
#4650 may be basically the same thing, hopefully fixed in #4651 .

**Comment by markerikson** [comment]
Out in https://github.com/reduxjs/redux-toolkit/releases/tag/v2.2.8
