### ISSUE TITLE
isSuccess value turning true while status: "pending"

### ISSUE THREAD

**Issue by Jeekwar** [reduxjs/redux-toolkit#4397]
**Why isSucces turning into true while status "pending"**

I try to fetching a query using RTK method POST and I console the response like below:
`useEffect(() => {
    console.log(responseCheckPromoCode.isError, responseCheckPromoCode.isSuccess, responseCheckPromoCode.status);
    } ,[responseCheckPromoCode]`
    
after running the project responseCheckPromoCode rendered 3 times like below:

![image](https://github.com/reduxjs/redux-toolkit/assets/79134153/45a3180b-0e3d-4da5-99e2-c45a0e3dcc62)

any answer and suggestions would be appreciated, Thanks.

**Comment by aryaemami59** [comment]
If you provide a minimal repro or a replay I can take a look.

**Comment by Jeekwar** [comment]
i can't give the repo but maybe i can give the slice of code.

**Comment by Jeekwar** [comment]
> If you provide a minimal repro or a replay I can take a look.

i can't give the repo but if you mind maybe i can give the slice of code.
