### ISSUE TITLE
Export DraftableEntityState, IsAny, UseQuery and other types

### ISSUE THREAD

**Issue by chenhebing** [reduxjs/redux-toolkit#4401]
https://github.com/microsoft/TypeScript/issues/58474

**Comment by aryaemami59** [comment]
Seems like this is related to #4066

**Comment by chenhebing** [comment]
> Seems like this is related to #4066

Thanks for the reply. It seems to be the same problem, so I will close this issue directly.

**Comment by aryaemami59** [comment]
@chenhebing Thanks, I'm still working on resolving this issue in a way that doesn't involve exporting internal types.

**Comment by markerikson** [comment]
Fixed in https://github.com/reduxjs/redux-toolkit/releases/tag/v2.2.7 !
