### ISSUE TITLE
retryCondition() in retry() in version 2.2.4 no longer type checks

### ISSUE THREAD

**Issue by tristanls** [reduxjs/redux-toolkit#4404]
Types work fine in 2.2.3 for the following:

```typescript
import { retry } from "@reduxjs/toolkit/query/react";

const myRetry = retry(
    ...,
    {
        retryCondition: (error, args, ...) =>
           ...
    }
);
```

In version 2.2.3 the type of `error` is `FetchBaseQueryError`.
In version 2.2.4 the type of `error` is `unknown`.

**Comment by EskiMojo14** [comment]
this is intentional, and noted in the [release notes](https://github.com/reduxjs/redux-toolkit/releases) - previously it was giving you FetchBaseQueryError even if you were using a base query with a different error shape.

**Comment by tristanls** [comment]
Thank you. Apologies, I couldn't find release notes for some reason. I see them now.

**Comment by markerikson** [comment]
@devintyler : as with other cases where a variable is `unknown`, you'd want to use a type guard function to check runtime values and convince TS that this variable really is a specific type:

```ts
function isMyCustomError(error: unknown): error is {status: string | number} {
  return typeof error === "object" && error !== null && 'status' in error
}

// later
if (isMyCustomError(error)) {
  // status checks here
}
```

**Comment by markerikson** [comment]
Yeah, a sizeable amount of TS usage amounts to "LOOK TYPESCRIPT I KNOW WHAT I'M DOING JUST _TRUST ME AND LET ME DO THIS ALREADY_!" :)
