### ISSUE TITLE
[request]: Global utility to clear all API cache

### ISSUE THREAD

**Issue by joshuaellis** [reduxjs/redux-toolkit#4413]
## Description

You can currently reset the state of a specific API state by calling the `resetApiState` method on an individual API, this is great if you're only using one API however, in Strapi we utilise a "plugin" system to be extensible, so parts of the codebase are treated as individual spaces, the same goes for third party plugins. We therefore don't have access to every API thats been added to the redux store when someone logs out to call the function.

It'd be really helpful to have a global action that can be ran to clean all API states (if there is already one, i couldn't find it in the docs). This way we can be confident that the cache is reset for all plugins & information across users is not leaked to individuals that shouldn't see it.

I've current done a (bad) workaround that finds all the API reducers based on a standardised name process, this won't reliably extend to third party plugins. I know we can probably list for the logout mutation and react that way, but that then requires developers to implement this in each of their plugins which I find unrealistic... Let me know what you think, happy to contribute if it's straight forward (which is probably isn't, it never is).

## Related information

* You can see how we've added a sort of hacky workaround here – https://github.com/strapi/strapi/pull/20318

**Comment by markerikson** [comment]
Given that we generally recommend that there should normally only be _one_ API slice per application, I'm not sure this is a thing we would really want to add more specific handling for.  That feels like enough of an edge case that it's something that should be handled at the app level.

FWIW, cleaning the state is easy, and you could always write a custom reducer that does that. The trickier part is that the API middleware is stateful and tracks current subscriptions, and watches for the reset action to overwrite those subscription values.

The other tricky part of this is that we couldn't just switch over to _only_ having a single global "reset" action - you might have multiple API slices, and but only want to reset one of them.

**Comment by joshuaellis** [comment]
Thanks for the quick reply @markerikson! 

> Given that we generally recommend that there should normally only be one API slice per application, I'm not sure this is a thing we would really want to add more specific handling for. That feels like enough of an edge case that it's something that should be handled at the app level.

This is fair, we have currently handled it. Although primarily we started out with multiple slices due to `tagTypes` but re-reading the docs, it looks like we can chain `api.enhanceEndpoints({ addTagTypes: [] }).injectEndpoints()` and be able to use those types, so perhaps it is better to use one API across the app & export that for other domains of the application to use in this fashion, so logout can still use the same `resetApiState` call? 🤔 

> The other tricky part of this is that we couldn't just switch over to only having a single global "reset" action - you might have multiple API slices, and but only want to reset one of them.

Yeah I agree, it's probably more tricky handling both?

Anyway, thanks for talking about it, if you do think it's an edge case the library shouldn't be supporting then feel free to close the issue 🙇🏼‍♀️

**Comment by markerikson** [comment]
Yeah, if at all possible, we'd recommend using a single API slice instance with `injectEndpoints()` instead of multiple separate instances.  (This also will improve overall app perf, because each added API middleware is additional function calls that have to run in response to every dispatched action even if it's not related to the API logic.)

I'll go ahead and close this, but thanks for filing the request and discussing the idea!
