### ISSUE TITLE
dispatch does not work, when i try to manually update cache in pessimistically or optimistically. Also show an error in apiSlice.util.updateQueryData("getTodos", undefined, (draft) => {} line show this error "getTodos" "Argument of type 'string' is not assignable to parameter of type 'never'"  

### ISSUE THREAD

**Issue by Jahid1499** [reduxjs/redux-toolkit#4419]
**src/features/api/apiSlice.ts**
/* eslint-disable @typescript-eslint/no-unused-vars */
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
export const apiSlice = createApi({
    reducerPath: 'api',
    baseQuery: fetchBaseQuery({ baseUrl: import.meta.env.VITE_API_URL }),
    tagTypes: [],
    endpoints: (builder) => ({})
})

**src/app/store.ts**
import { configureStore } from "@reduxjs/toolkit";
import { apiSlice } from "../features/api/apiSlice";

import filterSliceReducer from '../features/filters/filterSlice';
import todosSliceReducer from '../features/todos/todosSlice';

export const store = configureStore({
    reducer: {
        [apiSlice.reducerPath]: apiSlice.reducer,
        todos: todosSliceReducer,
        filter: filterSliceReducer,
    },
    devTools: import.meta.env.VITE_ENVIRONMENT_SERVER !== "production",
    middleware: (getDefaultMiddlewares) => getDefaultMiddlewares().concat(apiSlice.middleware),
});

**src/features/todos/todosApi.ts**
export const todosApi = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    
    getTodos: builder.query({
      query: () => "/todos",
    }),

    addTodos: builder.mutation({
      query: (data) => ({
        url: "/todos",
        method: "POST",
        body: data,
      }),

      // Pessimistically update start
      async onQueryStarted(arg, { queryFulfilled, dispatch }) {
        const todo = await queryFulfilled;

        if (todo?.data?.id) {
          console.log(todo); // show todo
          // update todo cache pessimistically start
          dispatch(
            apiSlice.util.updateQueryData("getTodos", undefined, (draft) => {
              console.log(JSON.stringify(draft));
              return draft;
            })
          );
          // update todo cache pessimistically end
        }
      },
    }),
    updateTodos: builder.mutation({
      query: ({ id, data }) => ({
        url: `/todos/${id}`,
        method: "PATCH",
        body: data,
      }),

      async onQueryStarted(
        { id, data: { color, completed, text } },
        { queryFulfilled, dispatch }
      ) {
        console.log(id, color, completed, text);

        dispatch(
          apiSlice.util.updateQueryData("getTodos", undefined, (draft) => {
            console.log("TODOS ARRAY DRAFT", draft);
          })
        );

        const result = await queryFulfilled;
        console.log(result);
      },
    }),
    deleteTodos: builder.mutation({
      query: (id) => ({
        url: `/todos/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

export const {
  useGetTodosQuery,
  useAddTodosMutation,
  useUpdateTodosMutation,
  useDeleteTodosMutation,
} = todosApi;

My expectation, when i create or update a todo, then update todo list without fetching getTodos query
Github repo: https://github.com/Jahid1499/advanced-todo-application

**Comment by EskiMojo14** [comment]
use `todosApi.util.updateQueryData` instead, it will know about your injected endpoints.

**Comment by Jahid1499** [comment]
getTodos: builder.query({
  query: () => "/todos",
}),

addTodos: builder.mutation({
  query: (data) => ({
    url: "/todos",
    method: "POST",
    body: data,
  }),

  async onQueryStarted(arg, { queryFulfilled, dispatch }) {
    const todo = await queryFulfilled;
    if (todo?.data?.id) {
      console.log(todo);           // show todo
      // update todo cache pessimistically start
          dispatch(
                 apiSlice.util.updateQueryData("getTodos", undefined, (draft) => {
                        console.log(JSON.stringify(draft));
                        return draft;
                  })
           );
      // update todo cache pessimistically end
    }
  },
}),

this dispatch doesn't work correctly, because i think, i passed incorrect argument. but i don't undustand what is the correct argument? please help me. 

**Expectecion:**  When create a new todo, then update in todolist. (optimistacally or passimistically)

**Comment by phryneas** [comment]
If you call `useGetTodosQuery()` or `useGetTodosQuery(undefined)`, this is right.
If you call `useGetTodosQuery(5)` you need to `apiSlice.util.updateQueryData("getTodos", 5, (draft) => {`

Does that make sense?

**Comment by Jahid1499** [comment]
Manay many thanks @phryneas, i undustood my problem and solved it.
