### ISSUE TITLE
createEntityAdapter add an item on the top on the list instead of the bottom

### ISSUE THREAD

**Issue by XeeshanAnsari** [reduxjs/redux-toolkit#4424]
I want to add an item top of the list instead of the bottom.

```
addCase(createPost.fulfilled, (state, action) => {
   postEntityAdaptor.addOne(state, action.payload);
})
```
it's adding item at the bottom. How can i add an item on the top of list.

**Comment by markerikson** [comment]
This entirely depends on whether you have defined a sorting comparator for the adapter or not.

Without sorting, the item IDs are listed in insertion order.

With sorting, it's up to you how you sort them.

Alternately, you can do the sorting work at the UI layer.

**Comment by XeeshanAnsari** [comment]
I used a sorting comparator but it's not working somehow.

Sorting at the UI layer is not a good idea.

My issue
I have a list of posts when the user creates a new post so it should be added to the top of the array. but when I am using postEntityAdaptor.addOne so it adds an item at the bottom of the list.

**Comment by markerikson** [comment]
@XeeshanAnsari then most likely your sorting comparator isn't written correctly.

**Comment by XeeshanAnsari** [comment]
You are right there was something wrong on my sorting comparer. It have fixed this issue using sortComparer. Thank you @markerikson 

const postEntityAdaptor = createEntityAdapter({
  sortComparer: (a, b) => b.createdAt - a.createdAt,
});
