### ISSUE TITLE
Selectors don’t have types?

### ISSUE THREAD

**Issue by Razorshnegax018** [reduxjs/redux-toolkit#4425]
Using toolkit for server side entity management. Trying to create a selector, hover over selector function and it’s typed as “any”.
 Hovering over slice.selectors gives types w/ selector names adding dot gives selector names as suggestions, but those selectors are typed as “any”

Decide to use createSelector function instead, create a variable w/ create selector and it’s typed as “any”. Ctrl + click doesn’t bring me to type definitions

what? Did I not install something?

**Comment by phryneas** [comment]
Please give some example code showcasing how you use it.
