### ISSUE TITLE
Missing single reducer during INIT

### ISSUE THREAD

**Issue by cheechongtey** [reduxjs/redux-toolkit#4426]
Hello 👋

I'm facing an issue where my `profile` reducer went missing on the first INIT. I can't seems to find out what's the root cause due to it is happening on and off. Searched through online and i can't seems to find any resource related to this issue. I've tried to use redux toolkit and logger to debug and indeed my profile reducer went missing but other reducers are fine.

This is the brief setup of my redux store and also the profile slice.
https://codesandbox.io/p/devbox/redux-missing-reducer-5gqxjl

or perhaps is it caused by how we access the state? but it doesn't matter because there is initial state right there. So should be able to read the state.profile

```
const {
  highestQualification: { qualification: userHighestQualification },
  isProfileReady,
} = useAppSelector((state) => state.profile);
```

Do let me know if need more information. Thank you!

**Comment by phryneas** [comment]
That CSB seems to be private.
