### ISSUE TITLE
SyntaxError: Unexpected token '??=' when running unit tests with Redux Toolkit 2.2.5 and Jest

### ISSUE THREAD

**Issue by wandersonaadsantos** [reduxjs/redux-toolkit#4429]
I am encountering an issue when trying to run unit tests with Redux Toolkit 2.2.5 and Jest.

**Error:**

```
Jest encountered an unexpected token

Details:

/...projetcname/node_modules/@reduxjs/toolkit/dist/query/cjs/rtk-query.development.cjs:1011
        draft[arg.queryCacheKey] ??= {
                                 ^^^

SyntaxError: Unexpected token '??='

> 1 | import { createApi } from '@reduxjs/toolkit/query/react'
    | ^
```

**Steps to reproduce:**

1. Cloned the basic example available at [Redux Toolkit Basic Example](https://github.com/reduxjs/redux-toolkit/blob/master/examples/query/react/basic/package.json).
2. Updated Redux Toolkit to version 2.2.5 and msw to version 0.47.3.
3. Ran the unit tests with Jest.

**Result:**

The same syntax error occurred.

**Question:**

Do you have any examples of projects using version 2.2.5 of Redux Toolkit for unit tests? The example I am using is not working, and I had to downgrade the version to make it work.

**Environment:**

- Redux Toolkit: 2.2.5
- msw: 0.47.3
- Jest: 29.7.0
- @testing-library/react: 14.3.1

I appreciate any guidance or examples that can help me resolve this issue.

![Screenshot 2024-05-28 at 13 26 36](https://github.com/reduxjs/redux-toolkit/assets/95881233/d61d5965-5476-48e6-828a-7f7945b77f47)

**Comment by markerikson** [comment]
This is presumably an issue with Jest not supporting that modern JS syntax.

You may need to configure Jest to transpile the RTK package in `node_modules` to convert that to older JS syntax.
