### ISSUE TITLE
[TS2742] The inferred type of '...' cannot be named without a reference to ...

### ISSUE THREAD

**Issue by ryuujo1573** [reduxjs/redux-toolkit#4448]
> Related to https://github.com/microsoft/TypeScript/issues/58743

It is not working if I try to export reducers/slices from a package.

Is this an actual TS issue?

Here's a possible [reproduction](https://github.com/ryuujo1573/rtk-ts2742-demo)

```
src/logic/client/user.ts:11:7 - error TS2742: The inferred type of 'userSlice' cannot be named without a reference to '../../../node_modules/@reduxjs/toolkit/dist/createSlice'. This is likely not portable. A type annotation is necessary.
```

**Comment by telephant** [comment]
same here

**Comment by telephant** [comment]
emm, don't export `nikkiSlice`, only export `nikkiReducer`

**Comment by aryaemami59** [comment]
Related to #3962.

**Comment by aryaemami59** [comment]
It seems like in your case we have to export the `CaseReducerDefinition` interface from the main `index.d.ts` file.

Side note: It seems like if a type is exported from an internal `.d.ts` file, but not exported from `index.d.ts`, then the error becomes: `The inferred type of 'nikkiSlice' cannot be named without a reference to '../../node_modules/@reduxjs/toolkit/dist/createSlice'. This is likely not portable. A type annotation is necessary.`

But if that same type is not exported at all the error message becomes much clearer like this: `Exported variable 'nikkiSlice' has or is using name 'CaseReducerDefinition' from external module "RTK-issue-3962/node_modules/.pnpm/@reduxjs+toolkit@2.2.5/node_modules/@reduxjs/toolkit/dist/createSlice" but cannot be named.`
which actually tells us which type is the problematic one.

**Comment by EskiMojo14** [comment]
@aryaemami59 that makes sense, thanks. i think we wouldn't be against exporting CaseReducerDefinition - in fact my open PR https://github.com/reduxjs/redux-toolkit/pull/3894/files#diff-5278ccae8e99ae0373490ef372d1953e0f3da303d948485ef7e00bd7de7fffa3 exports more that we can export just in case.

**Comment by aryaemami59** [comment]
@EskiMojo14 Wonderful, I have a list of types that need to be exported, thankfully they're not that many (as of now, might add more to the list if I discover more problems), will _hopefully_ put up a PR soon for a partial fix.

**Comment by aryaemami59** [comment]
Can you run this command and try again to see if it fixes the issue:

```bash
pnpm add https://pkg.csb.dev/reduxjs/redux-toolkit/commit/da50c578/@reduxjs/toolkit
```

**Comment by atsiapas-mellon** [comment]
> Can you run this command and try again to see if it fixes the issue:
> 
> ```shell
> pnpm add https://pkg.csb.dev/reduxjs/redux-toolkit/commit/06a30ee4/@reduxjs/toolkit
> ```

It did fix the issue for me. Thank you.

**Comment by glasody** [comment]
for me adding `"baseUrl": ".",` to tsconfig fixed it

**Comment by markerikson** [comment]
Fixed in https://github.com/reduxjs/redux-toolkit/releases/tag/v2.2.7 !
