### ISSUE TITLE
How to Enable TypeScript Autocompletion for Auto-Generated Hooks in RTK Query ?

### ISSUE THREAD

**Issue by sadraliev** [reduxjs/redux-toolkit#4456]
Hi!
RTK Query is a fantastic tool! My team uses it every day.
I love the auto-generation of hooks.
I became curious about how you implemented the auto-generation of hooks (useNameQuery, useNameMutation). I repeated your code but it didn’t work.

TypeScript does not know about the existence of the generated hooks. Could you reveal the magic?
How can I make TypeScript suggest the generated hooks? I would be very grateful.

I apologize if this question is inappropriate.

That piece of code:
```ts
if (isQueryDefinition(definition)) {
            const {
              useQuery,
              useLazyQuery,
              useLazyQuerySubscription,
              useQueryState,
              useQuerySubscription,
            } = buildQueryHooks(endpointName)
            safeAssign(anyApi.endpoints[endpointName], {
              useQuery,
              useLazyQuery,
              useLazyQuerySubscription,
              useQueryState,
              useQuerySubscription,
            });
            
            (api as any)[`use${capitalize(endpointName)}Query`] = useQuery;
            (api as any)[`useLazy${capitalize(endpointName)}Query`] =
              useLazyQuery
          
            } else if (isMutationDefinition(definition)) {
            const useMutation = buildMutationHook(endpointName)
            safeAssign(anyApi.endpoints[endpointName], {
              useMutation,
            })
            ;(api as any)[`use${capitalize(endpointName)}Mutation`] =
              useMutation
          }
```

**Comment by EskiMojo14** [comment]
see [namedHooks.ts](https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/react/namedHooks.ts) and the [react hooks module type](https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/react/module.ts#L69) 🙂
