### ISSUE TITLE
Argument of type AsyncThunkAction is not assignable to parameter of type UnknownAction

### ISSUE THREAD

**Issue by Yashiandr** [reduxjs/redux-toolkit#4457]
When I try to dispatch async thunk action in a component, typescript send me error (first picture), 
![image](https://github.com/reduxjs/redux-toolkit/assets/115163286/7ab83804-ac5b-494f-8f05-dcd26c6cc3a2)

store:
![image](https://github.com/reduxjs/redux-toolkit/assets/115163286/6d6ccb3d-631b-42ce-a641-ecff4cd3121f)

AsyncThunk:
![image](https://github.com/reduxjs/redux-toolkit/assets/115163286/666ac3ce-9187-46d8-8452-5f6bcd8526bd)

ThunkConfig:
![image](https://github.com/reduxjs/redux-toolkit/assets/115163286/2c0446b8-9e60-4554-9690-69b8e1f9acf3)

If I set the type ThunkExtraArgument for extraArg inside async thunk and set the extra field in the TrunkConfig as unknown, then the errors disappear and the types for the extra argument work.

![image](https://github.com/reduxjs/redux-toolkit/assets/115163286/e7909d10-6bbd-4346-93f2-579ae3bd0ad5)
![image](https://github.com/reduxjs/redux-toolkit/assets/115163286/a93eeaf6-7115-4276-bf8d-09d4e3133162)
![image](https://github.com/reduxjs/redux-toolkit/assets/115163286/e8912ea4-d499-4581-b883-2d28d0105fc9)

But I'm not sure if this is the right thing to do, and then why do I need to prescribe types for the extra argument in createAsyncThunk with a third generic

**Comment by phryneas** [comment]
Pretty sure that your type annotation of `ReduxStoreWithManager` erases a ton of useful type information here. Generally, annotations like this are often harmful. What happens if you remove it?

**Comment by Yashiandr** [comment]
> Pretty sure that your type annotation of `ReduxStoreWithManager` erases a ton of useful type information here. Generally, annotations like this are often harmful. What happens if you remove it?

Yeah, this works, thx, But now I need to think about how to add the reducer Manager field to the store. I don't want to use ts ignore

**Comment by EskiMojo14** [comment]
the inference is usually pretty good with `return Object.assign(store, { reducerManager })`

**Comment by Yashiandr** [comment]
> the inference is usually pretty good with `return Object.assign(store, { reducerManager })`

thx, this work fine
