### ISSUE TITLE
Multiple table-of-contents__link--active in the documentation especially "Usage Guide" 

### ISSUE THREAD

**Issue by jippy89** [reduxjs/redux-toolkit#4459]
Well, the title itself is explanatory.
Here's another visual that can help.

Guess where am I at?
![image](https://github.com/reduxjs/redux-toolkit/assets/80033934/59ad9eae-7841-40a3-b8e5-39fba1f037e1)

**Comment by EskiMojo14** [comment]
we do have https://github.com/reduxjs/redux-toolkit/pull/4050 to look into it - it just kinda slipped under the radar at some point.
