### ISSUE TITLE
vite build creates source folder in dist when importing from @reduxjs/toolkit

### ISSUE THREAD

**Issue by fjakop** [reduxjs/redux-toolkit#4469]
### Bug description

I'm creating a vite library relying on @reduxjs/toolkit. When I use "vite build", the output goes to "dist", where a index.js and index.d.ts is placed.
When any import from @reduxjs/toolkit is in at least one of the source files, the output folder structure changes and the index.d.ts is placed in dist/src/index.d.ts, which breaks the types declaration in package.json. Also an additional node_modules folder is created in dist, containing a strange file uncheckedindexed.d.ts.

### Reproduction

https://github.com/fjakop/vite-build-error

### Steps to reproduce

Error case:

* Run npm install
* Run npm run build
* look into dist folder

Success case:

* Remove the import of FetchBaseQueryError from src/index.ts and change the usage to e.g. "string"
* Run npm install
* Run npm run build
* look into dist folder -> the structure is now correct

### Components

* npm 10.8.1
* vite 5.3.1
* @reduxjs/toolkit 2.2.5

Since I cannot see whether this is vite (maybe) or @reduxjs/toolkit (my personal guess) related, I've also opened https://github.com/vitejs/vite/issues/17522 fyi.

**Comment by aryaemami59** [comment]
What does your `vite.config.ts` look like?

**Comment by aryaemami59** [comment]
Thanks for the repro. I can take a look at it today.

**Comment by aryaemami59** [comment]
I believe if you make the following changes on this [line](https://github.com/fjakop/vite-build-error/blob/027f83f1d9a22c8f5919c31a7c656dcf8d7765e9/vite.config.ts#L18) , the problem _should_ go away:

```diff
- plugins: [react(), typescript()],
+ plugins: [react(), typescript({ rootDir: 'src' })],
```

**Comment by fjakop** [comment]
Thanks for that hint @aryaemami59, works well, although I do not really understand why this behaviour is only with reduxjs/toolkit imports. The whole project has a lot of dependencies more...
