### ISSUE TITLE
`extraReducers` type problem

### ISSUE THREAD

**Issue by yhnavein** [reduxjs/redux-toolkit#447]
Hi,

I wanted to check out the new `createAsyncThunk` and I stumbled with the following issue raised by TypeScript:
![image](https://user-images.githubusercontent.com/516709/77745141-0e9fc100-701b-11ea-88e2-1016cfbf57d3.png)

I can write `[loadDates.fulfilled as any]` to get rid of this error, but this feel very off.
Am I doing something wrong?

I am using `"typescript": "3.8.3"`

**Comment by phryneas** [comment]
https://redux-toolkit.js.org/usage/usage-with-typescript/#type-safety-with-extrareducers

@markerikson This seems to confuse people all the time - what are your thoughts on making the builder notation the default in the documentation?

**Comment by rrebase** [comment]
You could also use the type explicitly e.g `[loadDates.fulfilled.type]`

**Comment by phryneas** [comment]
He could, but then he wouldn't have inferred action types. Using the map object notation with TypeScript is pretty much useless.

**Comment by markerikson** [comment]
I don't think we need to make it the _default_ in the docs, but I do think we should update the `extraReducers` section in the API reference with examples of both syntaxes, and emphasize there that the builder notation is preferred for TS usage.

**Comment by markerikson** [comment]
Covered by #460 .
