### ISSUE TITLE
Extra reducers should have a more descriptive name 

### ISSUE THREAD

**Issue by esharmony** [reduxjs/redux-toolkit#4476]
Just a thought, but the name extra reducers I think is a bit weak, maybe I am wrong and missing something, but something like internalReducers would be more descriptive as they respond to actions that are not directly called on the slice. 

Not a biggy, just a thought :)

**Comment by markerikson** [comment]
I'm the one who's responsible for coming up with that name back in 2019 :)

- https://github.com/reduxjs/redux-toolkit/pull/83

I agree that `extraReducers` is not a _great_ name. But, there weren't any other really good alternatives suggested at the time, and now that it's been around for several years we aren't going to change it.  Sorry!
