### ISSUE TITLE
How to use useAppSelector with nested combineSlices?

### ISSUE THREAD

**Issue by devanecondition** [reduxjs/redux-toolkit#4477]
Sorry if this is in the docs somewhere, I couldn't find it.  If have a slice with `selectors`, like this:

```
export const ui = createSlice({
  name: 'ui',
  initialState: initialState,
  reducers: {
     setIsDirectoryDrawerOpen : (state, {payload}: PayloadAction<boolean>) => {
      state.isDirectoryDrawerOpen = payload;
    },
  },
  selectors: {
    getIsDirectoryDrawerOpen: state => state.isDirectoryDrawerOpen,
  },
});
```

and that slice is in a nested part of the state, like this:

```
const state1Reducer = combineSlices(
  ui,
  // other state 1 slices
);

const state2Reducer = combineSlices(
  // state 2 slices
);

const rootReducer = combineSlices({
  state1: state1Reducer,
  state2: state2Reducer,
});
```

At the component level, if I wanna call `getIsDirectoryDrawerOpen`, do I have pass in the nested state to the selector like this?

```
const isDirectoryDrawerOpen = useAppSelector(state => getIsDirectoryDrawerOpen(state.state1));
```

Just wondering if there's not a way to set it to just do ` useAppSelector(getIsDirectoryDrawerOpen);`

Thanks!

**Comment by markerikson** [comment]
The slice selectors _give_ you the slice state as the argument, but they default to assuming that the slice itself is already in `rootState[slice.name]` (in this case, `state.ui`), and accept the root state as the argument.

So, you can already pass `getIsDirectoryDrawerOpen` directly to `useAppSelector`.

**Comment by EskiMojo14** [comment]
when your slice is nested, you need to call `.getSelectors` with a custom selector, instead of using `.selectors`.

For example, your case would be: 
```ts
const { getIsDirectoryDrawerOpen } = ui.getSelectors((state: RootState) => ui.selectSlice(state.state1))
```

**Comment by markerikson** [comment]
Whoops, my bad, I misread the original question, sorry!
