### ISSUE TITLE
createImmutableStateInvariantMiddleware not actually exported

### ISSUE THREAD

**Issue by exogen** [reduxjs/redux-toolkit#448]
Hello! 👋 

The [Other Exports](https://redux-toolkit.js.org/api/other-exports) docs say that `createImmutableStateInvariantMiddleware` is exported, but it doesn't seem to actually be there: https://github.com/reduxjs/redux-toolkit/blob/master/src/index.ts

**Comment by markerikson** [comment]
Good catch!  Can you file a PR to export things from that file?

Also, out of curiosity, do you have a specific use case for needing to call it directly, or is this just observing a bug?

**Comment by exogen** [comment]
Done!

My app currently uses most of the pieces of the toolkit piecemeal instead of the higher level helpers (it uses `redux-dynamic-modules` for instance, so we have our own store creation). But in this particular case I may be able to use `getDefaultMiddleware`, assuming it doesn't matter whether other middleware comes before the immutable state invariant one.

**Comment by markerikson** [comment]
Yeah, ideally the immutable and serializable check middleware come last in the sequence so they can catch things downstream of thunks and such anyway.
