### ISSUE TITLE
The inferred type of 'useLatestProductsQuery' cannot be named without a reference to '../../../node_modules/@reduxjs/toolkit/dist/query/react/buildHooks'. This is likely not portable. A type annotation is necessary.  How to resolve this error?  

### ISSUE THREAD

**Issue by Abhishekiitb25** [reduxjs/redux-toolkit#4498]
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import { AllProductsResponse, CategoriesResponse } from "../../types/api-types";

export const productAPI = createApi({
  reducerPath: "productApi",
  baseQuery: fetchBaseQuery({
    baseUrl: `${import.meta.env.VITE_SERVER}/api/v1/product/`,
  }),
  endpoints: (builder) => ({
    latestProducts: builder.query<AllProductsResponse, string>({
      query: () => "latest",
    }),
    allProducts: builder.query<AllProductsResponse, string>({
      query: (id) => `admin-produc?id=${id}`,
    }),
    categories: builder.query<CategoriesResponse, string>({
      query: () => `categories`,
    }),
  }),
});

export const {
  useLatestProductsQuery,
  useAllProductsQuery,
  useCategoriesQuery,
} = productAPI;

**Comment by aryaemami59** [comment]
Can you run this command and try again to see if it fixes the issue:

```bash
npm install https://pkg.csb.dev/reduxjs/redux-toolkit/commit/93cbe554/@reduxjs/toolkit
```

**Comment by Karangetang** [comment]
I had the same issue. Added the commit as requested, and error was gone.

**Comment by devsrsihab** [comment]
> Can you run this command and try again to see if it fixes the issue:
> 
> ```shell
> npm install https://pkg.csb.dev/reduxjs/redux-toolkit/commit/06a30ee4/@reduxjs/toolkit
> ```

Thanks i have run it and fixed the typescript Error, thanks man.

**Comment by glasody** [comment]
for me adding `"baseUrl": ".",` to tsconfig fixed it

**Comment by markerikson** [comment]
5Fixed in https://github.com/reduxjs/redux-toolkit/releases/tag/v2.2.7 !
