### ISSUE TITLE
Version bump and Publish needed

### ISSUE THREAD

**Issue by Lasto13** [reduxjs/redux-toolkit#4515]
Hello, 
I stumbled upon this closed ticket https://github.com/reduxjs/redux-toolkit/issues/4455
the PR is merged, yet the code is not published, the version of the package is still at 1.2.0, which is latest at 
https://github.com/reduxjs/redux-toolkit/pull/4198 and the published code is without those changes.
https://github.com/reduxjs/redux-toolkit/pull/4198/files
Even though tsconfig and oazapfts versions are already in master, might you have forgotten to bump the package version itself and publish it ? Would be great to have it :) Thanks

**Comment by aryaemami59** [comment]
#4509 should be merged first.

**Comment by Lasto13** [comment]
Thanks, I will keep an eye out for that

**Comment by markerikson** [comment]
Should be live in https://github.com/reduxjs/redux-toolkit/releases/tag/%40rtk-query%2Fcodegen-openapi%402.0.0-alpha.0 ! Please try it out and let us know if it works.

**Comment by SimonEggert** [comment]
Works like a charm for me. I could finally get rid of the monkeypatching 😉 Thanks!
