### ISSUE TITLE
Expose SwaggerParser's HTTP resolver options in GenerationOptions

### ISSUE THREAD

**Issue by KasimAhmic** [reduxjs/redux-toolkit#4521]
# Description

`@apidevtools/swagger-parser` supports passing HTTP resolver options to the `SwaggerParser.bundle` method which is useful for cases like #3468 when you need to pass custom headers to the underlying HTTP request, however this option is not currently exposed.

We are currently required to keep our Swagger docs behind authentication and as such it makes it difficult to codegen the API. We have to run the server locally, disable the authentication, then run the codegen against the local instance of the server. This works but it is sub-optimal considering we could just hit the already running server in CI.

# Example

```typescript
import type { ConfigFile } from '@rtk-query/codegen-openapi'

const config: ConfigFile = {
  schemaFile: 'https://petstore3.swagger.io/api/v3/openapi.json',
  apiFile: './src/store/emptyApi.ts',
  apiImport: 'emptySplitApi',
  outputFile: './src/store/petApi.ts',
  exportName: 'petApi',
  hooks: true,
  httpResolverOptions: {
    headers: {
      Accept: 'application/json',
      Authorization: 'Basic cmVkdXgtdG9vbGtpdDppcy1ncmVhdA==',
    }
  }
}

export default config
```

~I can open a PR for this shortly.~ PR opened: #4522

**Comment by markerikson** [comment]
Should be live in https://github.com/reduxjs/redux-toolkit/releases/tag/%40rtk-query%2Fcodegen-openapi%402.0.0-alpha.0 ! Please try it out and let us know if it works.
