### ISSUE TITLE
Unwrap() catch block doesn't work

### ISSUE THREAD

**Issue by Mormen** [reduxjs/redux-toolkit#4526]
I am using RTK query for comunication with API. When mutation fails, I need dispatch some alert, like follows:

```
const [addPost, {
    isError,
    error,
}] = useAddPostMutation()
...
useEffect(() => {
    if (isError) {
        dispatch(setAlert(error))
    }
}, [isError])
```

It works ok. 

But now, I would like to omit `useEffect` and I found in official docs (https://redux-toolkit.js.org/rtk-query/usage/error-handling) this code.

```
addPost({ id: 1, name: 'Example' })
  .unwrap()
  .then((payload) => console.log('fulfilled', payload))
  .catch((error) => console.error('rejected', error))
```

`then` block works ok, but there is some problem with `catch` block. I got this error message:

```
rejected TypeError: description(...) is undefined
```

I tried it without `unwrap()`, it falls every time into `then` block and get same error.
```
addPost({ id: 1, name: 'Example' })
  .then((payload) => console.log('fulfilled', payload))
  .catch((error) => console.error('rejected', error))
```

```
fulfilled 
Object { error: TypeError }
```

What am I missing? Is it a mistake on my side or is it a bug in RTK query?

**Comment by markerikson** [comment]
What is `description`? Sounds like it's a variable in your code somewhere?  Can you show the `addPost` mutation definition?

**Comment by Mormen** [comment]
I tried some another mutation `addRecipe` from my codebase and it works. So I look at differencies and I found it in action creators.

```
addRecipe: build.mutation({
    query: (payload) => {
        const { form } = payload
        return {
            url: '...',
            method: 'POST',
            body: form
        }
    },
    invalidatesTags: []
}),
```
-->
```
rejected 
{
  "status": 400,
  "data": {
    "message": "..."
  }
}
```

```
addPost: build.mutation({
    query: (payload) => {
        const { form } = payload
        return {
            url: '...',
            method: 'POST',
            body: form
        }
    },
    invalidatesTags: (result, error, arg) => {
        if (result) return ['...']
    }
}),
```
-->
```
rejected TypeError: description(...) is undefined
```

So the problem is in `invalidatesTags` section. Actually I don't remember why I don't use the first one method - ` invalidatesTags: []` everywhere.

Solution is probably quite easy.
```
invalidatesTags: (result, error, arg) => {
    if (result) return ['...']
    return [] // I have to return empty array of tags
}
```

**Comment by markerikson** [comment]
Ah, yep, that would do it.
