### ISSUE TITLE
unexpected behaviour of dispatching action in redux

### ISSUE THREAD

**Issue by Y-Moshe** [reduxjs/redux-toolkit#4528]
well, everything is explained here: 

https://stackoverflow.com/questions/78788216/unexpected-behaviour-of-dispatching-action-in-redux

i just don't get why,

```
  extraReducers(builder) {
    builder
      .addCase(projectActions.refreshProject.pending, (state) => {
        state.isRefreshing = true
      })
      .addMatcher(
        isAnyOf(
          projectActions.refreshProject.rejected,
          projectActions.refreshProject.fulfilled
        ),
        (state) => {
          state.isRefreshing = false
        }
      )
  },
```
based on this `extraReducers` it should change back to `false `only when its `fulfilled `or `rejected` 

```
const refreshProject = createAsyncThunk(
  '[Project API] Refresh Project',
  async (project: IKProject, { dispatch }) => {
    await dispatch(projectActions.unLoadProject(project))
    await dispatch(projectActions.loadProject(project))

    console.log('After refreshing')
  }
)
```

**Comment by markerikson** [comment]
The payload callback is succeeding, so the `fulfilled` action will be dispatched as soon as `refreshProject` completes. 

(Also, the way you're dispatching multiple actions inside of `createAsyncThunk` seems unnecessary - you're not actually doing real async work in `createAsyncThunk`, and your other thunks are dispatching actions like `resetState` and not making use of the `fulfilled/rejected` actions that `createAsyncThunk` dispatches automatically.)

**Comment by Y-Moshe** [comment]
sorry, why is that "closed" as not planned? i should have planned something?

anyway, I still don't understand because as explained in StackOverflow, I do see the `console.log('After refreshing')` after the last action `fulfilled` (the `loadProject `action) and that's why I expected that only **then** the `isRefreshing `should change back to `false` but what's happened it changes back immediately

please explain that to me, because i really do want to understand this.

why does the "The payload callback is succeeding" and not wait for other's actions to be resolved? as should?

@markerikson

**Comment by markerikson** [comment]
@Y-Moshe : the payload callback _is_ doing _some_ waiting.  But, as soon as the payload callback function finishes, the thunk "succeeds", and the `fulfilled` action is dispatched, which will then immediately mark `state.isRefreshing` as `false`.

**Comment by Y-Moshe** [comment]
ok ..., what do you mean "some waiting"?

in my case, where and when does it exactly dispatch the `fulfilled` action?

i mean, from your writes, "as soon as the payload callback function finishes", from my understanding, this moment is when the callback I gave (an async callback), reaches it's last line of executed line, the `console.log`..., exactly how a Promise works and async callbacks, is it not so?

**Comment by markerikson** [comment]
> what do you mean "some waiting"?

You have a thunk whose payload callback is:

```ts
 async (project: IKProject, { dispatch }) => {
    await dispatch(projectActions.unLoadProject(project))
    await dispatch(projectActions.loadProject(project))
```

So yes, the payload callback function is waiting for those other two thunks to complete.

> where and when does it exactly dispatch the fulfilled action?

Immediately as soon as the payload function finishes. In your case, immediately after the `console.log('After refreshing')` line, because that's when the payload function ends.

**Comment by Y-Moshe** [comment]
exactly, that's what I'm saying, i agree with you, but for some reason, this is not the case, you see, **this** `refreshProject `action finished Immediately without waiting for the actions `unLoadProject` & `loadProject `to finish, and that's the problem and why I don't get why the `isRefreshing `changing Immediately.

@markerikson

**Comment by markerikson** [comment]
Not sure what to tell you atm. The code looks acceptable at first glance, although as I said earlier, I think your use of dispatching multiple actions inside of `createAsyncThunk` is a confusing and unnecessary approach for what you're trying to do.

**Comment by Y-Moshe** [comment]
well, I did that because in my application, there are multiple places where I want to **refresh** the project, so I thought maybe to create an action for this in one place (app store), and then just dispatch this action as you see...

but then I figured that I could make use of the actions I created, `unLoadProject` and `loadProject`, because that's the exact logic I need to refresh the project...

how else do you suggest doing this?

and what's wrong about dispatching other thunk actions inside a thunk action? is that wrong?

**Comment by markerikson** [comment]
Dispatching other actions inside of thunks is fine, in general - that's why thunks have access to `dispatch` in the first place, and that includes `createAsyncThunk` too.

But, the real purpose of `createAsyncThunk` is to do async work, and then dispatch the `fulfilled/rejected` actions at the end.  Using `createAsyncThunk` to _only_ dispatch other actions  or thunks is _legal_, but feels very unusual.

I think some of the extra dispatching you're doing could be eliminated by relying on the actual `fulfilled/rejected` actions.  For example, instead of:

```ts
const loadProject = createAsyncThunk(
  '[Project API] Load Project',
  async (project: IKProject, { dispatch }) => {
    await kProjectService.loadProject(project)

    localStorage.setItem(STORAGE_KEY, project)
    dispatch(projectActions.setLoadedProject(project))

    // Loading & saving the project configuration
    const config = await kProjectService.getProjectConfig(project)
    dispatch(projectActions.setProjectConfig(config))
  }
)
```

You could rely solely on the `createAsyncThunk` behavior:

```ts
const loadProject = createAsyncThunk(
  '[Project API] Load Project',
  async (project: IKProject, { dispatch }) => {
    await kProjectService.loadProject(project)

    localStorage.setItem(STORAGE_KEY, project)
    // Loading & saving the project configuration
    const config = await kProjectService.getProjectConfig(project)
    return {project, config};
  }
)
```

and then have the slices listen for `loadProject.fulfilled` to set the current loaded project and fill in the config value, rather than dispatching separate actions.

(This isn't necessarily related to the `state.isRefreshing` issue, but simplifying the logic here is a good thing in general.)

**Comment by phryneas** [comment]
It's also very likely that `dispatch(projectActions.resetState())` also sets your `isRefreshing ` to `false`.

Generally: we can't say anything beyond the code we read here - you'd need to give us a reproduction (e.g. a CodeSandbox) so we can actually see the behaviour.

**Comment by Y-Moshe** [comment]
Thank you so much @phryneas, looks like it was me all the time...... i should have known that, thanks.

@markerikson Thank you too, at least i learned a better way of dispatching actions
