### ISSUE TITLE
Do not cancel retry requests on route change

### ISSUE THREAD

**Issue by felri** [reduxjs/redux-toolkit#4532]
I'm facing a problem related to how changing routes during a retry request cancels the retry request and starts the query again. I would like to not have a cancelled request when i change the URL or remounting a component.

```js
const retryBaseQuery = retry(fetchBaseQuery({
  baseUrl: import.meta.env.REACT_APP_AUTH_URL,
}), { retryCondition, backoff });

export const authApi = createApi({
  reducerPath: 'authApi',
  baseQuery: retryBaseQuery,
  prepareHeaders,
  timeout: 60000,
  endpoints: (builder) => ({
    refreshIdToken: builder.mutation({
      query: () => ({
        url: '/token',
        method: 'POST',
        body: {
          grantType: 'refreshToken',
          refreshToken: [...]
        },
      }),
      transformResponse: (response) => {
        const { data } = response;
        if (data?.access_token) {
          saveNewTokens(response);
          return { data };
        }
        return { error: data };
      },
      transformErrorResponse: (error) => {
        redirectToErrorPage(error);
        return error;
      }
    }),
  }),
});
```

```js
const AuthContext = createContext();

export const AuthProvider = ({ children }) => {
  const [refreshIdToken, { isLoading }] = authApi.useRefreshIdTokenMutation({
    fixedCacheKey: 'refresh-token',
  });

  const checkAndRefreshToken = () => {
    if (shouldUpdateToken()) {
      refreshIdToken();
    }
  }

  return (
    <AuthContext.Provider value={{ checkAndRefreshToken, isLoading }}>
      {children}
    </AuthContext.Provider>
  );
};

export const useAuth = () => useContext(AuthContext);
```

I thought fixedCacheKey would fix this problem and the flow I was thinking was:

1. User gets in the app
2. Refresh tokens flow starts - (retrying can take up to 8 seconds)
3. User changes route
4. Retries continue in the background

Right now I'm getting:

1. User gets in the app
2. Refresh token flow starts
3. User changes route
4. Request/Retry is cancelled and a new refresh token flow starts

Any idea if it's possible to do what I want?

**Comment by phryneas** [comment]
RTK Query doesn't do any cancellation of that kind. Are you sure you're not accidentally recreating the whole store?

**Comment by felri** [comment]
> RTK Query doesn't do any cancellation of that kind. Are you sure you're not accidentally recreating the whole store?

Welp, we are using <Redirect /> from react-router for some routes change, and it does a 3XX, effectively recreating the whole store. Thank you, I was losing my mind over this.
