### ISSUE TITLE
`refetchOnFocus`: Unintended refetch when iframe exists in the page

### ISSUE THREAD

**Issue by autologie** [reduxjs/redux-toolkit#4533]
In my React project I'm using RTK-Query with `refetchOnFocus` enabled globally.
This is for ensuring fresh data on UI when users keep the app open in the browser all the time, and has been working fine.

The problem I'm encountered with is that this option generates unwanted refetches every time after users interact with components built with the iframe element. While this technically makes sense, I can hardly think of a point in refetches after interacting with the iframe.

I'm hoping focus events via iframes to be excluded from the condition to trigger refetches, but according to my quick survey, it seems it's impossible to tell whether the `focus` event comes from an iframe or else.
For my use case, `visibilitychange` on the window object is probably closer to the event I'd like to trigger refetches on.

I'd like to know what the maintainers think.

**Comment by autologie** [comment]
Another scenario where `refetchOnFocus` generates unnecessary refetches is when I go back-and-forth between the browser's devtools and the UI while development, making the network in the devtools tab noisy. I'm realizing that `visibilitychange` won't be triggered in this scenario as well (unless the devtools are in a separate window).

Would it make sense to add something like `refetchOnVisible` to the public API, which triggers refetches when `document.visibilityState` becomes `"visible"`?

**Comment by phryneas** [comment]
You can easily set up your own interpretation:

```js

setupListeners(dispatch, (dispatch, action) => {
  const handleVisibilityChange = () => {
    if (window.document.visibilityState === 'visible') {
      dispatch(action.onFocus())
    } else {
      dispatch(action.onFocusLost())
    }
  }

  window.addEventListener(
    'visibilitychange',
    handleVisibilityChange,
    false,
  )

  // same for focuschange, online and offline

  return () => {
    window.removeEventListener(
      'visibilitychange',
      handleVisibilityChange
    )
  }
})
```

**Comment by autologie** [comment]
Thank you, this worked perfectly for me.
