### ISSUE TITLE
Slow typescript intellisense caused by createSlice

### ISSUE THREAD

**Issue by simon-paris** [reduxjs/redux-toolkit#4534]
`createSlice` calls cause typescript intellisense to be slow, even when editing unrelated files. Any calls to createSlice anywhere in the project will cause slowdown when generating typescript suggestions anywhere. The slowdown is significant in large projects, it scales with the size of the state types passed to initialState.

I've prepared a repo to help reproduce the issue: https://github.com/simon-paris/rtk-ts-slowness
Here's a CPU profile when using `const initialState: VeryVerySlowType`: [slow.cpuprofile](https://github.com/user-attachments/files/16409464/slow.cpuprofile)
And here's a CPU profile when using `const initialState: FastType`: [fast.cpuprofile](https://github.com/user-attachments/files/16409469/fast.cpuprofile)
The slowdown in this demo is similar to what I get in my work project.

Example:
```typescript
// Importing and using a large type is not slow
const initialState: VeryVerySlowType = {};

export const slowExport = createSlice({
  name: "SlowSlice",
  initialState,
  reducers: {
    slowReducer: (
      // But this is slow - it's converting this to a Draft<VeryVerySlowType> which should not be necessary
      state: VeryVerySlowType,
      action: PayloadAction<{}>
    ) => {}
  }
});
```

Referencing `VeryVerySlowType` doesn't inherently cause intellisense issues, slowness only happens when createSlice converts it to `Draft<VeryVerySlowType>`. That conversion will happen on every keystroke, anywhere in the project.

Logically, it shouldn't need this. When preparing for intellisense commands, typescript only cares about the types of exported symbols. We don't need to export `Draft<VeryVerySlowType>`. In slice.actions, the first parameter of each CaseReducer doesn't affect the returned action types. And in slice.caseReducers, it's exported as-is, there should be no need for inferring anything.

Additionally, I can't work around this. It seems like you'd be able to prevent the conversion to `Draft<T>` by explicitly naming the type of the state parameter. But it still does the conversion even when it's unused.

Hypothetically, this would fix it, but I'm sure there's a better way.

```diff
export type CaseReducer<S = any, A extends Action = UnknownAction> = (
-  state: Draft<S>,
+  state: S,
  action: A,
-) => NoInfer<S> | void | Draft<NoInfer<S>>
+) => NoInfer<S> | void
```

**Comment by EskiMojo14** [comment]
the Draft type is needed, because it makes readonly types mutable. if you made your initial state readonly, you'd still want to be able to mutate inside your case reducers.

**Comment by simon-paris** [comment]
It's only for checking the reducer bodies, intellisense only cares about exported types and shouldn't need it

**Comment by EskiMojo14** [comment]
it *is* exported, because your case reducers are exported as is. if we didn't, you'd be allowed to do this:
```ts
interface MyReadonlyState {
 readonly foo: boolean;
}

const initialState: MyReadonlyState = { foo: true }

const slice = createSlice({
  name: "slice",
  initialState,
  reducers: {
    flipFoo: (state) => { state.foo = !state.foo }
  }
});

slice.caseReducers.flipFoo(initialState, slice.actions.flipFoo()) // initialState gets mutated here
```

**Comment by phryneas** [comment]
>  You can already do that in the current version. Typescript lets you assign immutables to mutables.

Not always, for example not with arrays:

```ts
function foo(x: {a: string[]}){}

const x: {a: readonly string[]} = {a: []}
// Argument of type '{ a: readonly string[]; }' is not assignable to parameter of type '{ a: string[]; }'.
foo(x)
```

This could probably be done rewriting all of `createSlice`'s types from scratch to use reverse mapped types, which was not possible in the days of TS 3.2, when these types were written - but such a rewrite would be an enormous amount of work. I'm not sure that the maintainers currently have the bandwith for that.

**Comment by markerikson** [comment]
I'm _very_ sure we maintainers don't currently have the bandwidth for that :)

That said, we have extensive type tests to verify expected behavior, so if @simon-paris or someone else would like to take a crack at reworking the types to improve perf, we're definitely open to looking at that.

**Comment by EskiMojo14** [comment]
not sure reverse mapping would work for prepared reducers - we need to preserve both the args for the prepare callback, and the resulting action shape for the reducer.

**Comment by simon-paris** [comment]
Yeahhh, I don't have the time to rewrite all the types either 😓 

But, I could set up an opt-out, by allowing users to bring their own implementation of Draft. Would this be something you'd want?

In user code:
```ts
declare global {
  namespace ReduxToolkit {
    interface Draftable<T> {
      draft: MyCustomDraftImplemenation<T>
    }
  }
}
```

In RTK:
```ts
declare global {
  namespace ReduxToolkit {
    // The type of `draft` in this interface is used in place of immer's Draft. Immer's Draft is used if nothing is defined.
    interface Draftable<T> {}
  }
}
interface DefaultDraftable<T> {
  draft: ImmerDraft<T>
}
export type Draft<T> = 
  (ReduxToolkit.Draftable<T> extends { draft: unknown } ?
    ReduxToolkit.Draftable<T> :
    DefaultDraftable<T>
  )["draft"]
```

**Comment by phryneas** [comment]
I'd prefer a `declare module` enhancing `@reduxjs/toolkit`, but generally I guess something like that could be explored
