### ISSUE TITLE
Redux Toolkit not compatible with React 19? Could not resolve dependency.

### ISSUE THREAD

**Issue by joshuarichards001** [reduxjs/redux-toolkit#4540]
Hey there, I'm trying out the React Compiler on the React 19 beta but when running `npm install` on the latest `@reduxjs/toolkit` I'm getting `Could not resolve dependency` errors. Below is the full error, is this a known problem?

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @reduxjs/toolkit@2.2.7
npm ERR! Found: react@19.0.0-rc-a7d1240c-20240731
npm ERR! node_modules/react
npm ERR!   react@"19.0.0-rc-a7d1240c-20240731" from the root project
npm ERR!   peer react@"*" from react-canvas-confetti@2.0.7
npm ERR!   node_modules/react-canvas-confetti
npm ERR!     react-canvas-confetti@"^2.0.7" from the root project
npm ERR!   1 more (react-dom)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional react@"^16.9.0 || ^17.0.0 || ^18" from @reduxjs/toolkit@2.2.7
npm ERR! node_modules/@reduxjs/toolkit
npm ERR!   @reduxjs/toolkit@"^2.2.7" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@18.3.1
npm ERR! node_modules/react
npm ERR!   peerOptional react@"^16.9.0 || ^17.0.0 || ^18" from @reduxjs/toolkit@2.2.7
npm ERR!   node_modules/@reduxjs/toolkit
npm ERR!     @reduxjs/toolkit@"^2.2.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by phryneas** [comment]
React 19 is not released yet. 
With a pre-release version you are the beta tester for the whole ecosystem and will probably have to override this in your `package.json`.

There's no reason that `react-redux` wouldn't work with React 19, but before React 19 has been released and we tested it with it we can't guarantee that it will work. 
Even if it worked with a release candidate now, there's no guarantee that between now and the final React 19 release, something wouldn't get broken.

**Comment by markerikson** [comment]
To put it another way:

- React-Redux v9 should work fine with React 19
- RTK Query's React integration will also continue to work fine
- But React 19 isn't final yet, so we haven't published any releases that say React 19 is an acceptable peer dependency
- And NPM is notoriously picky and errors when there aren't valid peer deps

So, either use NPM's options to override the installation behavior, or use a better package manager that _doesn't_ yell at you like this :)

**Comment by aryaemami59** [comment]
Just as a side note I have working PRs migrating to React 19. They will most likely sit in draft until after the stable release of React 19, but they should circumvent the peer dependency issues for the time being.

For [Redux-Toolkit](https://github.com/reduxjs/redux-toolkit/pull/4409):

```bash
npm install https://pkg.csb.dev/reduxjs/redux-toolkit/commit/436d29c1/@reduxjs/toolkit
```

For [React-Redux](https://github.com/reduxjs/react-redux/pull/2172):

```bash
npm install https://pkg.csb.dev/reduxjs/react-redux/commit/3271037e/react-redux
```

**Comment by phryneas** [comment]
Yes, React 19 still has not been released.

**Comment by just-abdullah-dev** [comment]
what's the update right now, cause I am also facing the npm err while installation.

**Comment by markerikson** [comment]
@just-abdullah-dev there is no update, because React 19 is still not final yet.

**Comment by heshamabdelazim** [comment]
Make it React 18

**Comment by zguo123** [comment]
From react.dev: ![Image](https://github.com/user-attachments/assets/0bc36dbf-b1b5-4af8-b6ab-f67f7e96cb6c)

**Comment by markerikson** [comment]
@zguo123 yes, _now_ that it's officially out, we'll be bumping our peer deps accordingly.

**Comment by mehmoodahmed** [comment]
I am trying to use redux toolkit with react 19.

Can you guide me ?
