### ISSUE TITLE
Problems trying to migrate to toolkit

### ISSUE THREAD

**Issue by Lewis-00** [reduxjs/redux-toolkit#4541]
Hi,
I'm trying to migrate a normal version of redux into toolkit, I've already tried to build up the store, but I'm struggling to add old custom epics, those are a bunch of epics combined with combineEpics

this is the current store, but I'm getting errors and epics don't work

```typescript
const epicMiddleware = createEpicMiddleware();
export const store = configureStore({
    reducer: rootReducer,
    middleware: (getDefaultMiddleware) => getDefaultMiddleware().concat(epicMiddleware)
})
epicMiddleware.run(rootEpics)
export type AppDispatch = typeof store.dispatch
``` 

I got these type of errors: 
```typescript
A non-serializable value was detected in an action, in the path: `meta.successAction`. Value: ƒ (succPayload, meta) {
            return {
              type: successActionType,
              payload: succPayload,
              meta: meta
            };
          } 
Take a look at the logic that dispatched this action
``` 

I've tried some solutions like:

```typescript
const epicMiddleware = createEpicMiddleware();

export const store = configureStore({
    reducer: rootReducer,
    middleware: [epicMiddleware]
})

epicMiddleware.run(rootEpics)
export type AppDispatch = typeof store.dispatch
``` 
this was working until I tried to dispatch an async thunk function, I was getting an error due to the type of the dispatch, also tried to add dispatch<AppDispatch>() but still nothing, so going back to the doc store config the dispatch started working but epics don't
hope someone can help.
If you need other details just ask, thx in advice.

**Comment by markerikson** [comment]
What is in that `meta.successAction` field?

**Comment by lamhungypl** [comment]
redux payload should be serializable and you receive the warning because you violated that rule
