### ISSUE TITLE
Previously accessible types are no longer accessible from 2.2.6 -> 2.2.7

### ISSUE THREAD

**Issue by JP250552** [reduxjs/redux-toolkit#4554]
With the consolidated types change in 2.2.7, certain types are no longer available. 
While I understand these may be considered "internal" types, they are really helpful when utilizing a custom base query. 

I would ask for your consideration in exposing at minimum the following:

`@reduxjs/toolkit/dist/query/baseQueryTypes`
- `BaseQueryError`
- `BaseQueryMeta`

`@reduxjs/toolkit/dist/query/endpointDefinitions`
- `MutationExtraOptions`
- `QueryExtraOptions`
- `ResultDescription`

As a workaround, it looks like these are available in the `src` directory.

**Comment by markerikson** [comment]
Can you give some examples of where / how you're trying to use these types?

**Comment by JP250552** [comment]
Yes certainly. 

We've created a base query that handles API functions generated from our open api schema. We have some utilities created to make creating fully typed endpoints based on those functions. 

Here is an example of where we create a custom `EndpointBuilder` and `QueryExtraOptions` to handle queries. 

```ts
// Extended types

export type CustomEndpointBuilder<T = unknown> = EndpointBuilder<
  BaseQueryFn<QueryCallback<T>>,
  string,
  'api'
>;

export interface CustomQueryExtraOptions<T extends (...args: any) => any>
  extends Omit<
    QueryExtraOptions<
      any,
      BaseQueryReturnType<T>,
      QueryArgs<T>,
      BaseQueryFn<QueryCallback<T>>,
      'api'
    >,
    'type'
  > {
  providesTags?: ResultDescription<
    any,
    BaseQueryReturnType<T>,
    QueryArgs<T>,
    BaseQueryError<BaseQueryFn<QueryCallback<T>>>,
    BaseQueryMeta<BaseQueryFn<QueryCallback<T>>>
  >;
}
```

```ts
// Utility functions for working with custom API functions

export function createQuery(builder: CustomEndpointBuilder) {
  return <T extends (...args: any[]) => QueryCallback>(
    apiFn: T,
    options?: CustomQueryExtraOptions<T>,
  ) =>
    builder.query<BaseQueryReturnType<T>, QueryArgs<T>>({
      ...options,
      query: apiFn,
    });
}
```

**Comment by AndreasNH** [comment]
I have a usecase where we use the QueryReturnValue type to create a reposehandler to enrich our logging middleware with metadata. 

```ts
/**
 * This is a utility for parsing responses from an API that follows the REST API conventions.
 *
 * The metaOpts makes it possible to carry extra info on actions. An example is adding { shouldLog412: true } so that
 * the error logging middleware is able to know if API errors should be logged or not.
 *
 * @param resultPromise The result
 * @param metaOpts      These options end up on the response
 */
export const handleResponse = <T, MetaOpts>(
  resultPromise: Promise<JsonQuery<Resultstash<T>>>,
  metaOpts?: MetaOpts,
): Promise<QueryReturnValue<Resultstash<T>, BaseQueryError<any>, QueryMeta<MetaOpts>>> => {
  return resultPromise.then(
    (query) => {
      const { response, request, json } = query;

      if (response.ok) {
        return {
          data: json,
          meta: { response: serializeResponse(response), request: serializeRequest(request), metaOpts },
        };
      } else {
        return {
          error: responseToError(query),
          meta: { response: serializeResponse(response), request: serializeRequest(request), metaOpts },
        };
      }
    },
    (err) => {
      return {
        error: normalizedError(err),
      };
    },
  );
};

// Mock useage of handleResponse
const fetchTextBlobFn = (build: EndpointBuilder<InternalFetchBaseQuery, BaseApiTagTypes, "api">) =>
  build.mutation<
    IResultstash<TextBlob>,
    { params: FetchCriteria; metaOpts?: QueryMeta["metaOpts"] }
  >({
    queryFn: ({ params, metaOpts }, api) =>
      handleResponse(
        fetchTextBlob(params),
        metaOpts,
      ),
  });

export const api = baseApi.injectEndpoints({
  endpoints: (build) => ({
    fetchText: fetchTextBlobFn(build),
  }),
});


```

**Comment by arthurmmedeiros** [comment]
I was also using `MutationLifecycleApi` and  `QueryLifecycleApi ` from `@reduxjs/toolkit/dist/query/endpointDefinitions` for some utility functions. I have some endpoints that share the same logic in `onQueryStarted`, and having these types available let me write a single function to be passed to `onQueryStarted`.

Any chance to have these types exported again?

**Comment by jamesmontalvo3** [comment]
We were using:

```typescript
import type { AsyncThunk, BaseThunkAPI } from "@reduxjs/toolkit/dist/createAsyncThunk";
```

**Comment by jamesmontalvo3** [comment]
@EskiMojo14 I was using it to create a wrapper on `createAsyncThunk` called `appCreateAsyncThunk` that provides the app's `RootState`, `AppDispatch`, etc. I think I've cleaned it up to use exports from `@reduxjs/toolkit` without reaching into `/dist`.

**Comment by EskiMojo14** [comment]
@jamesmontalvo3 have you seen [`createAsyncThunk.withTypes()`](https://redux-toolkit.js.org/usage/usage-with-typescript#defining-a-pre-typed-createasyncthunk)?

**Comment by jamesmontalvo3** [comment]
I had not. Thanks!

Inclusion of the rejectValue in the reusable function seems strange. Each thunk could have different rejected values.

**Comment by EskiMojo14** [comment]
it's just giving the example of possible thunk config options, i agree you're not likely to specify rejectValue there 😛

**Comment by kokchuankoh** [comment]
Would it also be possible to expose the type definition LazyQueryTrigger that was exported from @reduxjs/toolkit/dist/query/react/buildHooks ? LazyQueryTrigger is the type defintion for fetchTrigger returned by useLazy...Query functions.

I tried pointing the type definition to @reduxjs/toolkit/src/query/react/buildHooks, but I'll get a type error in line 848 of @reduxjs/toolkit/src/query/react/buildHooks . The error message is 'This comparison appears to be unintentional because the types '"development" | "production" | "test"' and '"removeMeOnCompilation"' have no overlap.'

Thank you

**Comment by markerikson** [comment]
@kokchuankoh possibly, but can you show an example of where / how / why you need to use that type?

**Comment by EskiMojo14** [comment]
@kokchuankoh we export a TypedLazyQueryTrigger type instead.

https://github.com/reduxjs/redux-toolkit/blob/a9362fbcec6cb66bdb3e6dc52bbf3d69ea6f2b22/packages/toolkit/src/query/react/buildHooks.ts#L298-L302

**Comment by kokchuankoh** [comment]
Sure, I have components that use a custom type named LookupPersonSearchProps . That prop type definition is as follows:
```
.....
import { LazyQueryTrigger } from '@reduxjs/toolkit/dist/query/react/buildHooks';
import {
  BaseQueryFn,
  FetchArgs,
  FetchBaseQueryError,
  FetchBaseQueryMeta,
  QueryDefinition,
} from '@reduxjs/toolkit/query';

export interface LookupPersonSearchProps {
  data?: EmployeeFilters;
  /**
   * Will be executed when the primary button is pressed
   */
  getData: LazyQueryTrigger<
    QueryDefinition<
      EmployeeFilters,
      BaseQueryFn<
        string | FetchArgs,
        unknown,
        FetchBaseQueryError,
        object,
        FetchBaseQueryMeta
      >,
      'Employee' | 'Department',
      EmployeeListReponse,
      'lookupsApi'
    >
  >;
  /**
   * Will be executed when the secondary button is pressed
   */
  callbackfunction: Dispatch<SetStateAction<string>>;
  /**
   * Will be executed when either button is pressed
   */
  handleClose: () => void;
}
.....
```
From a parent component, I referenced the lazy version of a rtk basequery and passed a fetchTrigger function to children components as follows:
```
.....
  const [fetchTrigger, { data, error, isFetching }] = useLazyGetemployeeQuery( {} );
.....

switch (nextStep) {
    case 'Child component1':
      component = (
        <ChildComponent1
          getData={fetchTrigger}
          handleClose={onClose}
          callbackfunction={setnextStep}
        />
      );
      break;
    case 'Child component2':
      component = (
        <ChildComponent2
          getData={fetchTrigger}
          handleClose={onClose}
          callbackfunction={setnextStep}
        />
      );
      break;
    ....
    default:
      component = <NotFound />;
  }
```

**Comment by EskiMojo14** [comment]
@kokchuankoh 
```ts
getData: TypedLazyQueryTrigger<
      EmployeeListResponse,
      EmployeeFilters,
      ReturnType<typeof fetchBaseQuery>
    >
  >;
```

**Comment by kokchuankoh** [comment]
> @kokchuankoh
> 
> ```ts
> getData: TypedLazyQueryTrigger<
>       EmployeeListResponse,
>       EmployeeFilters,
>       ReturnType<typeof fetchBaseQuery>
>     >
>   >;
> ```

That worked. Thanks so much @EskiMojo14 !

**Comment by jakubjochymek** [comment]
hey, do you have any solution to "QueryReturnValue" ? anything i can use instead?

**Comment by EskiMojo14** [comment]
i don't think we'd be against a PR adding QueryReturnValue to our exports, it's a pretty simple type (and is actually detailed in [our docs](https://redux-toolkit.js.org/rtk-query/usage-with-typescript#typing-a-basequery))

**Comment by Audrey-Ann** [comment]
Also now I can't import `ResultDescription`, `QueryExtraOptions`, `UseLazyQuery`, `QueryStateSelector` which were/are used to declare custom types in our project... it would be very useful to include them back please??

**Comment by EskiMojo14** [comment]
could you please show how you were using them?

**Comment by Audrey-Ann** [comment]
Yes of course @EskiMojo14, thanks for your reply here are the location where I imported those types: 
```
import { QueryStateSelector, UseLazyQuery } from '@reduxjs/toolkit/dist/query/react/buildHooks';
import { BaseQueryError, BaseQueryMeta } from '@reduxjs/toolkit/dist/query/baseQueryTypes';
import { QueryExtraOptions, ResultDescription } from '@reduxjs/toolkit/dist/query/endpointDefinitions';
```
So simply, the locations are: 
- `[...]/dist/query/react/buildHooks`
- `[...]/dist/query/baseQueryTypes`
- `[...]/dist/query/endpointDefinitions`

Hope this helps?

For context here are the custom types I created in our project using the above ones: 
```
type ApiInjectionType<ResponseDTO, RequestDTO> = {
  apiURL: string;
  routeUrl?: string;
  method?: AxiosMethod;
  keepUnusedDataFor?: number;
  providesTags?: ResultDescription<
    TagTypesType[number],
    ResponseDTO,
    RequestDTO,
    BaseQueryError<any>,
    BaseQueryMeta<any>
  >;
  onCacheEntryAdded?: QueryExtraOptions<any, any, any, any>['onCacheEntryAdded'];
};
```
and 
```
export type UseLazyQueryType = UseLazyQuery<QueryDefinition<any, any, any, IPaginatedDataDTO<any>>>;

interface Props {
  useLazyQuery: UseLazyQueryType;
  selectFromResult?: QueryStateSelector<any, any>;
  [...]
}
```

If you have any suggestion on how to actually improve/simplify the above custom types, then your feedback would be much appreciated. Otherwise adding back those types would fix the import errors 🙏 
- `ResultDescription`
- `QueryExtraOptions`
- `UseLazyQuery`
- `QueryStateSelector`

**Comment by Audrey-Ann** [comment]
Hi @EskiMojo14 any news on the type access? thanks!

**Comment by markerikson** [comment]
We got a few of these out in https://github.com/reduxjs/redux-toolkit/releases/tag/v2.2.8 , and hope to have the rest out soon after.

**Comment by markerikson** [comment]
Okay, the rest of these should be out in https://github.com/reduxjs/redux-toolkit/releases/tag/v2.3.0 !  Let us know if there's any further problems.

**Comment by Audrey-Ann** [comment]
Thank you very much! :) 

I upgraded to `^2.3.0` and here are the changes now for anyone using the same types! 

```
import { QueryExtraOptions, ResultDescription } from '@reduxjs/toolkit/query';

...

type ApiInjectionType<ResponseDTO, RequestDTO> = {
  apiURL: string;
  routeUrl?: string;
  method?: AxiosMethod;
  keepUnusedDataFor?: number;
  providesTags?: ResultDescription<
    TagTypesType[number],
    ResponseDTO,
    RequestDTO,
    BaseQueryError<any>,
    BaseQueryMeta<any>
  >;
  onCacheEntryAdded?: QueryExtraOptions<any, any, any, any>['onCacheEntryAdded'];
};
```

And 

```
import { TypedQueryStateSelector, TypedUseLazyQuery } from '@reduxjs/toolkit/query/react';

...

type UseLazyQueryType<T> = TypedUseLazyQuery<IPaginatedDataDTO<T>, any, any>;
type SelectFromResultType<T> = TypedQueryStateSelector<IPaginatedDataDTO<T>, any, any>;

interface Props<T> {
  useLazyQuery: UseLazyQueryType<T>;
  selectFromResult?: SelectFromResultType<T>;
  [...]
}
```

**Comment by kkatsi** [comment]
I also noticed that in the latest version, the `QueryFulfilledRejectionReason` type is no longer exported, but I still need this type for handling query errors.

In my code, I have this block where I handle the queryFulfilled promise:

```js
async onQueryStarted(_, { queryFulfilled }) {
  try {
    await queryFulfilled;
  } catch (err) {
    // want to check the error type
  }
}
```
I used to use `QueryFulfilledRejectionReason` to type the error like this:

```ts
type QueryFulfilledError = QueryFulfilledRejectionReason<
  BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError>
>;

export function isQueryFulFilledError(err: unknown): err is QueryFulfilledError {
  return 'error' in (err as QueryFulfilledError);
}
```
But now, the `QueryFulfilledRejectionReason` type is not available anymore in the new version. This makes it difficult to correctly handle and type the error.

Is there a generally recommended approach on how to deal with catch error and type checks or any plan to re-export this type?
