### ISSUE TITLE
UseQuery can't be imported anymore

### ISSUE THREAD

**Issue by eugene-g13** [reduxjs/redux-toolkit#4558]
Not possible to import UseQuery type anymore (as well as ResponseHandler type).
Error:
Cannot find module '@reduxjs/toolkit/dist/query/react/buildHooks' or its corresponding type declarations.ts(2307)

Please, help! How to import UseQuery?

"@reduxjs/toolkit": "^2.2.7",

**Comment by EskiMojo14** [comment]
Anything under /dist/ should be considered internal, and may break at any time without us considering it to be a breaking change.

Our public entry points are:

- @reduxjs/toolkit
- @reduxjs/toolkit/react
- @reduxjs/toolkit/query
- @reduxjs/toolkit/query/react

We intentionally don't export the UseQuery type, but we do export a TypedUseQuery helper that accepts friendlier type parameters.

It looks like we don't export the ResponseHandler type.

Could you show how you're using these types?

**Comment by eugene-g13** [comment]
Thank you so much, @EskiMojo14! 
Idk how I missed the `TypedUseQuery` .

Btw, I have a question about `TypedUseQuery`: Why `BaseQuery` type is required here?
` type TypedUseQuery<ResultType, QueryArg, BaseQuery extends BaseQueryFn>`

`ResponseHandler` is actually not a big problem. May be I use it wrong since it handles _blob_ responses. My code:

```
// import { ResponseHandler } from '@reduxjs/toolkit/dist/query/fetchBaseQuery';
type ResponseHandler = 'content-type' | 'json' | 'text' | ((response: Response) => Promise<any>);

const defaultRtkValidateStatus = (response: Response) => response.status >= 200 && response.status <= 299;

export const blobResponseHandler: ResponseHandler = (response: Response) =>
	defaultRtkValidateStatus(response) ? response.blob() : response.json();
```

inside `createApi`:

```
exportItemToExcel: builder.mutation<null, { items: Item[] }>({
	queryFn: async ({ items }, api, extraOptions, baseQuery) =>
		downloadBlob({
			queryResult: await baseQuery({
				method: 'POST',
				cache: 'no-cache',
				url: 'items/xlsx',
				body: items,
				responseHandler: blobResponseHandler,
			}),
			fileName: `${'items'}.xlsx`,
		}),
         }),
```

**Comment by EskiMojo14** [comment]
BaseQueryFn is required because some types from the hook return value is based on it - in particular, the error type.

your blobResponseHandler doesn't need the ResponseHandler annotation - all you need to annotate is that the parameter is a Response instance, like you already have.
