### ISSUE TITLE
ceateSlice: Make the last 4 generic arguments optional.

### ISSUE THREAD

**Issue by TheColorRed** [reduxjs/redux-toolkit#4570]
Version: 2.2.7

When using `createSlice`, it takes 5 generic arguments, 4 of which could be optional (in my opinion).

<details>
  <summary>Show Image Error</summary>

![image](https://github.com/user-attachments/assets/91aceaed-ed76-4d07-b44c-08ca7a846ee6)
</details>

Looking at the DTS, it looks like the last 4 arguments could be deduced from the first argument this:

![image](https://github.com/user-attachments/assets/66b8b1fe-65aa-44ef-89ef-c1cfe93082bb)

Resulting in this (which seems to work locally for me):

```ts
declare const createSlice: <
  State, 
  CaseReducers extends SliceCaseReducers<State> = SliceCaseReducers<State>, 
  Name extends string = string, 
  Selectors extends SliceSelectors<State> = SliceSelectors<State>, 
  ReducerPath extends string = Name
>(options: CreateSliceOptions<State, CaseReducers, Name, ReducerPath, Selectors>) => Slice<State, CaseReducers, Name, ReducerPath, Selectors>;
```

The reason I say this, is because in my project I have a store which is setup like this:

```ts
export interface StoreState {
  projects: ProjectState;
}

configureStore<StoreState>({
  reducer: {
    projects: projectsReducer,
  },
})
```

I then define the project like this (where stuff starts to break for me):

- I create an interface defining the data
- I export an selector

The problem that I am having is that `createSlice` and `selectActiveProject` don't have a type link in common unless I pass 5 generic arguments to `createSlice`, so refactoring the code causes issues (such as renaming `activeId` to `id`). So you need to remember to refactor in multiple places instead of just one when using the rename tool (unless you pass at least 4 generics to `createSlice`).

```ts
export interface ProjectState {
  projects: Project[];
  activeId: string;
}

export const projectsSlice = createSlice({
  initialState: {
    projects: JSON.parse(localStorage.getItem('projects') || '[]') as Project[],
    activeId: '',
  },
  // ...
});

export const selectActiveProject = (state: StoreState) => state.projects.projects.find(p => p.id === state.projects.activeId);

export default projectsSlice.reducer;
```

```ts
// SomeComponent.tsx
export default () => {
  const active = useSelector(selectActiveProject);
  // ...
};
```

As we can see in this image, there is only 1 references to `activeId`, when there should be many.
<details>
  <summary>Show Image</summary>

![image](https://github.com/user-attachments/assets/8bc9535a-45cd-4fc0-8d14-460076f17674)
</details>

After updating with the 4-5 arguments (all of which are useless to me except the first), you see the reference count increases to 6 (most of which are in my collapsed code).

<details>
  <summary>Show Image</summary>

![image](https://github.com/user-attachments/assets/81a86c73-4b6f-4b20-b8c0-2b46468ab62c)
</details>

**Comment by EskiMojo14** [comment]
both `configureStore` and `createSlice` are designed to use inferrence - you shouldn't be passing any generic arguments to them yourself.

if you want to make sure your slice state matches a specific shape, you could do something like:

```ts
export interface ProjectState {
  projects: Project[];
  activeId: string;
}

const initialState: ProjectState = {
  projects: JSON.parse(localStorage.getItem('projects') || '[]') as Project[],
  activeId: '',
}

export const projectsSlice = createSlice({
  initialState,
  ...etc
});
``` 

or if you really wanted to define it inline:

```ts
export interface ProjectState {
  projects: Project[];
  activeId: string;
}

export const projectsSlice = createSlice({
  initialState: {
    projects: JSON.parse(localStorage.getItem('projects') || '[]') as Project[],
    activeId: '',
  } satisfies ProjectState as ProjectState,
  // ...
});
```

**Comment by TheColorRed** [comment]
Thanks, `satisfies ProjectState as ProjectState,`, I have never liked doing it this way as it seems messy to me but I can work with that.
