### ISSUE TITLE
TypeError: Failed to execute 'fetch' on 'Window': Cannot construct a Request with a Request object that has already been used.

### ISSUE THREAD

**Issue by Arsenalist** [reduxjs/redux-toolkit#4573]
Getting this error:

```
TypeError: Failed to execute 'fetch' on 'Window': Cannot construct a Request with a Request object that has already been used.
```

On all POST calls on Vercel. GET works fine and locally everything works fine. This just started happening a few hours ago, and only affects calls made using React Toolkit. I'm on the latest version 2.2.7. Any idea what this might be about? It started happening

**Comment by markerikson** [comment]
No idea. We just call `fetch`, nothing special about it:

https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/fetchBaseQuery.ts#L268-L282

**Comment by BharatNischal** [comment]
We are also facing the same issue after chrome update. @markerikson due you get any work around?

**Comment by anubhavmalik** [comment]
Same here, something to do with the latest chrome version : 127.0.6533.120

**Comment by Arsenalist** [comment]
For me it was PostHog. I got rid of it and it started working. They probably introduced a breaking change today.

**Comment by BharatNischal** [comment]
Thanks @Arsenalist posthog was the actual problem
