### ISSUE TITLE
Add history.push() to createAsyncThunk

### ISSUE THREAD

**Issue by slim-hmidi** [reduxjs/redux-toolkit#458]
I use an async action creators to fetch data:
```
updateCaseRequest = (caseToUpdate: ReportedCaseToUpdate): AppThunk => async (dispatch) => {
  try {
    dispatch(start());
    const updatedCase = await updateReportCaseApi(caseToUpdate);
    dispatch(updateReportedCaseSuccess(updatedCase));
    history.push("/report-case-list");

  } catch (error) {
    let errorMessage = "Internal Server Error";
    if (error.response) {
      errorMessage = error.response.data.message;
    }
    dispatch(fail(errorMessage));
  }
};
```
But I found that in the recent version, there is `createAsyncThunk`, I tried to update my code:
```
const updateCase: any = createAsyncThunk(
  "reportedCases/updateCase",
  async (caseToUpdate: ReportedCaseToUpdate, { rejectWithValue }) => {
    try {
      const updatedCase = await updateReportCaseApi(caseToUpdate);
      return updatedCase;

    } catch (error) {
    let errorMessage = "Internal Server Error";
    if (error.response) {
      errorMessage = error.response.data.message;
    }
    dispatch(fail(errorMessage));
  }
  },
);
```
But how I can add the `history.push("/report-case-list")`?

**Comment by markerikson** [comment]
Two thoughts:

- Your payload creator shouldn't need to be dispatching anything - `createAsyncThunk` [already dispatches a failure action if the payload creator returns a rejected promise](https://redux-toolkit.js.org/api/createAsyncThunk#promise-lifecycle-actions).

If you do want to customize the contents of the error action, you can have a `catch` block, then use `rejectWithValue`:

```js
const updateCase: any = createAsyncThunk(
  "reportedCases/updateCase",
  async (caseToUpdate: ReportedCaseToUpdate, { rejectWithValue }) => {
    try {
      const updatedCase = await updateReportCaseApi(caseToUpdate);
      return updatedCase;

    } catch (error) {
    let errorMessage = "Internal Server Error";
    if (error.response) {
      errorMessage = error.response.data.message;
    }
    rejectWithValue(errorMessage);
  }
  },
);
```

As for the `history.push()` aspect, I would suggest doing it as the last line before `return updatedCase`, because by that time you know the request has succeeded.

**Comment by slim-hmidi** [comment]
@markerikson thank a lot for you answer.

**Comment by khmais93** [comment]
Hi, @slim-hmidi  did you solve your problem, if yes how?
I imported useHistory, created the history variable and then pushed the path I need, but now my action is doing nothing, it can't be dispatched but if I remove anything related to useHistory, my action can be dispatched again. 

`import { createAsyncThunk } from '@reduxjs/toolkit';
import streams from '../apis/streams';
import { useHistory } from 'react-router-dom';

export const createStream = createAsyncThunk(
  'stream/createStream',
  async (formValues, thunkAPI) => {
    let history = useHistory();
    const { userId } = thunkAPI.getState().auth;
    const response = await streams.post('/streams', { ...formValues, userId });
    history.push('/');
    return response.data;
  }
);`

**Comment by phryneas** [comment]
@khmais93 in your devtools you will see a rejected action which tells you that hooks can only be used in React components. `useHistory` is a hook. You do not need to import that, but the `history` variable itself from where you define it.

**Comment by nox-machina** [comment]
> @khmais93 in your devtools you will see a rejected action which tells you that hooks can only be used in React components. `useHistory` is a hook. You do not need to import that, but the `history` variable itself from where you define it.

This worked perfectly.

**Comment by flq** [comment]
May I ask from where you get the history instance in your async action?

**Comment by phryneas** [comment]
import it probably. `history` has absolutely nothing to do with Redux or Redux Toolkit, it comes from a completely different library.

**Comment by ArpeshSH** [comment]
Hey @phryneas, `history` function comes from the `useHistory` hook which comes from the `react-router-dom` library, and "we cannot use hooks outside of react component". So could suggest where should I import the history function?

**Comment by phryneas** [comment]
@ArpeshSH unless that changed at some point, you can also create a `history` variable outside of React Router and plug it into React Router. Then you can also import that `history` variable in different places (e.g. Redux) to use it there.
