### ISSUE TITLE
Rtk query is not exporting useQuery options types

### ISSUE THREAD

**Issue by MateuszGroth** [reduxjs/redux-toolkit#4600]
### The options type is something that should be exported 

I implemented the following method to create a useQuery hook with default options, as the library does not provide a way to define the refetchOnMountOrArgChange option at the query level:

```ts
export const getUseQueryHookWithDefaultOptions =
  <
    D extends QueryDefinition<any, any, any, any> = QueryDefinition<
      any,
      any,
      any,
      any
    >,
  >(
    useQueryHook: UseQuery<D>,
    defaultOptions: DistributiveOmit<
      SubscriptionOptions & UseQueryStateOptions<D, ReturnType<UseQuery<D>>>,
      "selectFromResult" | "skip"
    > & { refetchOnMountOrArgChange?: number | boolean },
  ): UseQuery<D> =>
  (arg, options) => {
    return useQueryHook(arg, { ...defaultOptions, ...options });
  };
```

usage

```ts
export const useGetPostsQuery =
  getUseQueryHookWithDefaultOptions(
    postsApi.useGetPostsQuery
    { refetchOnMountOrArgChange: false },
  );
```

But with the latest update - `@2.2.7`, the `SubscriptionOptions` and `UseQueryStateOptions` types are no longer exported

- [x] I am willing to open a pr to export them :)

**Comment by aryaemami59** [comment]
The `SubscriptionOptions` type is already exported and I just put up #4604 which exports `UseQueryStateOptions`.
