### ISSUE TITLE
queryFn doesn't update on error, and continues on pending state

### ISSUE THREAD

**Issue by jesusaguiardev** [reduxjs/redux-toolkit#4620]
Hello!, i'm implementing an api with a single mutation using queryFn

From the [docs](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#queryfn-function-return-value) I understand that, the queryFn is expected to return an object with the following pattern `{ error: {...} }`, but for some reason, when i return an error, the mutation doesn't finish and continues on `pending` state

this is the code (i'll remove the non-essentials)

```
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import dynamicURL from "../dynamicURL";


const baseQuery = fetchBaseQuery({
  baseUrl: API_BASEURL,
});


const paperlessApi = createApi({
  reducerPath: "paperlessApi",
  baseQuery: baseQuery,
  endpoints: (builder) => ({
    validateDatablob: builder.mutation({
      providesTags: ["Paperless"],
      queryFn: async ({ data, env }, api, extraOptions) => {
        const { icgid, dataToDecode, setMetada, setError } = data;

        const decodedData = changeAlgorithm(dataToDecode, setMetada, setError);
        if (!decodedData) {
          return {
            error: { status: 400, message: "Failed to decode the data blob" },
          };
        }

        const dataToValidate = {
          icgid,
          data: { ...decodedData },
        };

        try {
          const setup = {
            method: "POST",
            body: dataToValidate,
            env,
            endpoint: `/courier/document/validate`,
          };
          const requestConfig = dynamicURL(setup);

          const validationResponse = await baseQuery(
            requestConfig,
            api,
            extraOptions
          );

          if (validationResponse?.error) {
            return {
              error: { status: 500, ...validationResponse.error },
            };
          }

          return { data: decodedData };
        } catch (error) {
          return {
            error: {
              status: 500,
              message:
                error.message || "An unknown error occurred during validation",
            },
          };
        }
      },
    }),
  }),
});

export const { useValidateDatablobMutation } = paperlessApi;

export default paperlessApi;
```
and for clarification, the success path works as expected, if i return `{ data: whatever }` the mutation finalize as expected

this is how im using the mutation

```
  const [
    validateDataBlob,
    {
      isLoading: isValidatingDatablob,
      isSuccess: dataBlobIsValid,
      isError: dataBlobHasBeenTampered,
    },
  ] = useValidateDatablobMutation();
  ```
  
 and calling validateDataBlob inside a useEffect that has other logic, the versions i have are:

 ```
 "@reduxjs/toolkit": "1.9.5",
"react-redux": "^8.0.4",
```

**Comment by EskiMojo14** [comment]
yes it does :)

would happily help you if provided any actual details

**Comment by jesusaguiardev** [comment]
LOL idk how u got the issue bc i didn't click on Submit new issue @EskiMojo14 , i was going to change the title obviously with the proper error im having haha

**Comment by EskiMojo14** [comment]
haha, odd - feel free to edit it and I'll reopen

**Comment by jesusaguiardev** [comment]
i updated the issue @EskiMojo14 thank you for taking my mistake with a lil of humor hahahaha

**Comment by EskiMojo14** [comment]
hmm, i don't see anything obvious - have you added some console logs to work out which `return { error }` line is happening?

**Comment by jesusaguiardev** [comment]
Yea, i even tried to return the error even before executing the query, like :( 
```
queryFn: async ({ data, env }, api, extraOptions) => {  return {error { ... } } }
```

**Comment by jesusaguiardev** [comment]
One finding, on the useEffect i execute the validateDatablob, i have this logic

```
 const result = await validateDataBlob({
        data: {
          icgid: "",
          dataToDecode: data,
          setMetada,
          setError,
        },
        env: iframeEnv.env?.toUpperCase() || "DEV",
      });
      if (result?.data) {
        setPurchasedProduct(result.data?.type);
        setDecodedBlob(result?.data);
      } else {
        setIsDataBlobValid(false);
      }
    };
```
If i console log the result when i return an error, it has the error, but idk why the other out of the box states from RTK are not updating

**Comment by EskiMojo14** [comment]
do you have any other reducers that are listening for the rejected action (validateDataBlob.matchRejected) that might be throwing errors?

**Comment by markerikson** [comment]
Closing due to lack of additional info.
