### ISSUE TITLE
I'm trying to pass the dispatch() function of asyncThunk as an argument, but I can't figure out the correct type

### ISSUE THREAD

**Issue by Stobles** [reduxjs/redux-toolkit#4626]
I have a hook like this

![image](https://github.com/user-attachments/assets/222173a8-7c58-4616-a519-36b5f5eb5abc)

And i'm trying to pass this function () => dispatch(createAttendanceEvent(eventId)) to createAction argument

![image](https://github.com/user-attachments/assets/be3735d5-44c0-4168-8435-73b1d5c2d59e)

But i get an error

`Type 'Promise<PayloadAction<unknown, string, { arg: number; requestId: string; requestStatus: "fulfilled"; }, never> | PayloadAction<unknown, string, { arg: number; requestId: string; requestStatus: "rejected"; aborted: boolean; condition: boolean; } & ({ ...; } | ({ ...; } & {})), SerializedError>> & { ...; } & { ...; }' is not assignable to type 'Promise<{ payload: void; type: string; }>'`

What type of argument should i use to be able to pass this () => dispatch(createAttendanceEvent(eventId))

**Comment by markerikson** [comment]
Hmm. Maybe try `() => Promise<PayloadAction<any>>`?

**Comment by EskiMojo14** [comment]
yeah, the payload defaults to void if not provided

**Comment by Stobles** [comment]
@markerikson Yes, it works, thanks. Is it possible to type this more specifically without using any
