### ISSUE TITLE
Getting client side exception in RTK query documentation 

### ISSUE THREAD

**Issue by Mohitkumar6122** [reduxjs/redux-toolkit#4632]
Attaching SS 
![image](https://github.com/user-attachments/assets/6474e9b4-d909-4024-b1c7-bee16b1a266a)

**Comment by Mohitkumar6122** [comment]
Here is the browser console SS


![image](https://github.com/user-attachments/assets/b555c74a-160a-4e47-9095-ad06998581fd)

**Comment by markerikson** [comment]
That's an embed from Egghead, and not part of our docs directly. Don't think that's something we can fix ourselves.

**Comment by Mohitkumar6122** [comment]
@markerikson Agreed
But can you raise this issue to there end ?

**Comment by markerikson** [comment]
We can't do anything about the error - it's just an embedded iframe:

```html
<iframe 
    src="https://app.egghead.io/lessons/redux-course-introduction-and-application-walk-through-for-rtk-query-basics/embed?af=7pnhj6" 
```

But yeah, we can try to ping them.

**Comment by Mohitkumar6122** [comment]
@markerikson I believe this is the best solution 
But lets not close this issue until its fixed.
Since I visited redux website its your duty to maintain each and every page including the iframes embedded ?

**Comment by markerikson** [comment]
@Mohitkumar6122 I appreciate the enthusiasm, but this truly is a third-party problem. Yes, we embed the video player in our docs, but it's not _our_ code and we can't fix it ourselves.  

We try to only keep issues open if there's actually something _we_ can do to fix a problem and we are still planning to do that thing, so in this case it's appropriate to close it.

**Comment by Mohitkumar6122** [comment]
Thanks @markerikson for confirming

**Comment by phryneas** [comment]
I gave the guys over at egghead a ping so they'll take a look.

> Since I visited redux website its your duty to maintain each and every page including the iframes embedded ?

Meanwhile, can I offer you a refund of the money you paid to access our free content? 
But seriously: we do this for free, in our spare time. We do it for users like you. You're welcome, but please understand that nothing here is our "duty".

**Comment by Mohitkumar6122** [comment]
@phryneas 
 Thank you for reaching out to egghead and for the quick response.

I completely understand and appreciate the hard work you and your team put into maintaining Redux, especially in your spare time. I apologize if my message came across as overly demanding—that wasn’t my intention. I’m not looking for a refund, as I highly value the free resources you provide.

My goal was simply to point out that when users encounter issues on the site, such as embedded content not working, it can reflect on the overall experience. I just wanted to raise awareness in case it's something that might need attention.

Thanks again for all your efforts, and I really appreciate your work for the community!
