### ISSUE TITLE
Website doc typo: `UseMutationResult.fulfilledTimestamp` should be `fulfilledTimeStamp`

### ISSUE THREAD

**Issue by thom-nic** [reduxjs/redux-toolkit#4634]
from https://redux-toolkit.js.org/rtk-query/api/created-api/hooks#usemutation

>  fulfilledTimestamp?: number // Timestamp for when the mutation was completed

should have a capitalized 'S' as `fulfilledTimeStamp`

For the record since timestamp is a compound word I would not have expected the S to be capitalized however this project seems to have used that as a convention.  So the doc will match the API at least.

**Comment by EskiMojo14** [comment]
PR welcome :)

agreed on Timestamp vs TimeStamp, but can't change it now 😄

**Comment by MarvinCorro** [comment]
quick PR for this fix, adding here for tracking 😃 
https://github.com/reduxjs/redux-toolkit/pull/4665

**Comment by markerikson** [comment]
Thanks!
