### ISSUE TITLE
Allow `useStrictShallowCopy` from `immer` to be configurable in `configureStore`

### ISSUE THREAD

**Issue by orkhanrustamli** [reduxjs/redux-toolkit#4639]
### Issue
Accessors (`getters/setters`) Are Not Copied After `immer@10` Update

### Description:
Starting with `Immer v10`, the library stopped copying accessors (i.e., `getters/setters`) during object updates in drafts. This has caused issues for objects in my state that rely on `getters`, as these accessors are removed after the next state update due to Immer's behavior.

### Proposed Solution:
Would it be possible to introduce new `Immer` settings that can be passed through `configureStore`, or perhaps `export useStrictShallowCopy` alongside the other Immerexports in Redux Toolkit, so this behavior can be enabled as an opt-in feature?

**Comment by markerikson** [comment]
No, this isn't something we'd want to support. Your state should be plain objects that _don't_ rely on getters in the first place, and this isn't something we'd want to provide as an option in `configureStore`.

Just out of curiosity, what are you _doing_ with your state objects that has you putting getters in there? And _how_ are you adding getters to the objects?
