### ISSUE TITLE
invalidatesTags - minor improvement

### ISSUE THREAD

**Issue by croraf** [reduxjs/redux-toolkit#4644]
I want this logic in invalidatesTags:

```
invalidatesTags: (_, __, body) => {
        return body.meetingId ? ["Meetings", "Meeting Item"] : ["Meetings"];
      }
```

but maybe would be nice if in the returned array falsey values get ignored, so I could then write:

```
invalidatesTags: (_, __, body) => {
        return  ["Meetings", body.meetingId && "Meeting Item"]
      }
```

Or at least throw an error, because in this latter variant no error is thrown but the Meetings dont refresh.

P.S. I mean, I guess I can chain the returned array with `.filter(i => i)`

**Comment by phryneas** [comment]
That seems like a reasonable idea :)

PRs are welcome!

**Comment by croraf** [comment]
Cool. I checked the code trying to implement but was too hard for me so I quit. GJ for pierroberro

**Comment by markerikson** [comment]
Out in https://github.com/reduxjs/redux-toolkit/releases/tag/v2.4.0 !
