### ISSUE TITLE
How I pass useQuery as prop to component?

### ISSUE THREAD

**Issue by bylly1** [reduxjs/redux-toolkit#4646]
I m trying to build an autocomplete reusable component using mui, react-hook-form, typescript and I want to pass the useQuery as prop to that reusable, but I have some types errors

What I did:

```js
import { Control, FieldValues, Path, useController } from 'react-hook-form';

import {
    TypedUseQuery,
    BaseQueryFn,
    FetchBaseQueryError,
    FetchArgs,
} from '@reduxjs/toolkit/query/react';

type BaseQueryArgs = { page: number; limit?: number };
type QueryArg<T extends BaseQueryArgs> = T | FetchArgs;

interface AutocompleteProps<
    TFieldValues extends FieldValues,
    TData,
    TQueryArg extends BaseQueryArgs
> {
    name: Path<TFieldValues>;
    control: Control<TFieldValues>;
    useQuery: TypedUseQuery<
        TData,
        QueryArg<TQueryArg>,
        BaseQueryFn<QueryArg<TQueryArg>, unknown, FetchBaseQueryError>
    >;
}

const RusableAutocomplete<
    TFieldValues extends FieldValues,
    TData,
    TQueryArg extends BaseQueryArgs
> (
   props: AutocompleteElementProps<TFieldValues, TData, TQueryArg>
) => {
const { name, control, useQuery } = props;
const [open, setOpen] = useState(false);
const [currentPage, setCurrentPage] = useState(0);

 const {
        field: { value, onChange },
        fieldState: { error },
    } = useController({ name, control });

const queryArg: QueryArg<TQueryArg> = {
        ...(dependentField ? { [dependentField.paramName]: dependentValue } : {}),
        page: currentPage,
    } as QueryArg<TQueryArg>;

const { data, isFetching, refetch } = useQuery(queryArg, { skip: !open });

const options = data ? getOptions(data) : [];

return (
  <Autocomplete 
      options={options}
       ...rest of the code
  />
)
}

```
but when I pass the useQuery as props:
``` js
  import { useGetDataQuery } from './api'
  
  const ParentComponent = () => {
   return (
     <RusableAutocomplete 
         useQuery={useGetDataQuery }
         ...rest of props
     />
   )
  } 
```
I receive this error:
`Type 'UseQuery<QueryDefinition<void | QueryParams, BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError>, "Data", FetchResponseProps<DataProps>, "api">>' is not assignable to type 'TypedUseQuery<FetchResponseProps<DataProps>, QueryArg<BaseQueryArgs>, BaseQueryFn<QueryArg<BaseQueryArgs>, unknown, FetchBaseQueryError>>'.
  Types of parameters 'arg' and 'arg' are incompatible.
    Type 'unique symbol | QueryArg<BaseQueryArgs>' is not assignable to type 'void | QueryParams | unique symbol'.
      Type 'FetchArgs' is not assignable to type 'void | QueryParams | unique symbol'
`

What I'm doing wrong?

**Comment by phryneas** [comment]
For one, you probably shouldn't be passing hooks as props into components - you're violating the rules of hooks with that, as the calling component could swap out the hook, which could either cause weird behaviour or ever crash React.

If you're absolutely focused on doing that, though, I would recommend that you don't recreate the full signature of `useQuery` here, but only the part that your component will actually be calling.

Something like

```ts
(arg: TFieldValues & { page: number }) => { data?: TData }
```

**Comment by bylly1** [comment]
> For one, you probably shouldn't be passing hooks as props into components - you're violating the rules of hooks with that, as the calling component could swap out the hook, which could either cause weird behaviour or ever crash React.
> 
> If you're absolutely focused on doing that, though, I would recommend that you don't recreate the full signature of `useQuery` here, but only the part that your component will actually be calling.
> 
> Something like
> 
> ```ts
> (arg: TFieldValues & { page: number }) => { data?: TData }
> ```

Do you know a way to create form reusable components using rtk query. Right know I need to create a middle component between form and react-hook-form reusable component to fetch the data

**Comment by phryneas** [comment]
You could avoid breaking the rules of hooks by creating your reusable component by a higher order component approach, in which case the hook wouldn't be passed by prop later, and could not potentially break the rules.

But you might also just be trying to abstract a bit too much here?

**Comment by bylly1** [comment]
Right now I'm doing like this:

**Comment by bylly1** [comment]
Right know I'm doing like this:

```js
// Form.tsx
import { useForm, SubmitHandler } from 'react-hook-form';


const ExampleForm = () => {
 const { handleSubmit, control } = useForm();
 return (
    <AccountAutocomplete 
      name="user"
      control={control}
    />
 )
}
```
```js
// AccountAutocomplete.tsx
import type { FieldValues, Control, Path } from 'react-hook-form';
import { useGetAccountsQuery } from './api';

interface AccountAutocompleteProps<TFieldValues extends FieldValues> {
    name: Path<TFieldValues>;
    control: Control<TFieldValues>;
}

const AccountAutocomplete = <TFieldValues extends FieldValues>(
    props: AccountAutocompleteProps<TFieldValues>
) => {
    const { name, control } = props;
    const { data, isFetching } = useGetAccountsQuery();

    return (
        <RHFAutocomplete
            name={name}
            control={control}
            loading={isFetching}
            options={data?.results ?? []}
        />
    );
};
```
```js
// RHFAutocomplete.tsx - reusable component
import { type Control, type FieldValues, type Path, useController } from 'react-hook-form';

type BaseAutocompleteProps<
    TFieldValues extends FieldValues,
    TData
> = Omit<AutocompleteProps<TData>, 'renderInput'> & {
    name: Path<TFieldValues>;
    control: Control<TFieldValues>;
};

const RHFAutocomplete = <
    TFieldValues extends FieldValues,
    TData,
>(
    props: RHFAutocompleteProps<TFieldValues, TData>
) => {
    const { name, control, ...rest } = props;
    const {
        field: { value, onChange, ref, ...fieldProps },
        fieldState: { error },
    } = useController({
        name,
        control,
    });

    return (
       <Autocomplete
            {...rest}
            {...fieldProps}
            value={value}
            onChange={(event, newValue) => {
                onChange(newValue);
            }}
            renderInput={(params) => (
                <TextField
                    {...params}
                    {...textFieldProps}
                    label={label}
                    error={!!error}
                    helperText={error?.message}
                    inputRef={ref}
                />
            )}
    )
```

I was thinking to simplify things by removing `AccountAutocomplete` and integrate inside RHFAutocomplete. this is why I wanted to pass the `useQuery` as props
