### ISSUE TITLE
How use endpoint.select() outside of hooks?

### ISSUE THREAD

**Issue by lainas262** [reduxjs/redux-toolkit#4648]
This is mostly a question really... 

I am reading this https://redux-toolkit.js.org/rtk-query/usage/usage-without-react-hooks#accessing-cached-data--request-status
but I am having some trouble actually pulling the data.

I have a query which pulls data based on some args object. So let's call it useValidateDataCombination({valueA, valueB, valueC})

I see an entry within redux api slice under 

queries: {
  validateData({"valueA":"somevalue1","valueB":"somevalue2","valueC":"somevalue3"})
...
}

How can I create a selector  outside of hooks that will return the cached value for that payload combination. Also, each inidivual value has it's own selector.

i.e 

selectValueA = (state) => state.valueA,
selectValueB = (state) => state.valueB,
selectValueC = (state) => state.valueC,

selectApiResult = apiSlice.endpoints.validateData.select(valueA, valueB, valueC) ?

Thanks

**Comment by phryneas** [comment]
The same you would also call the hook/initiate 
```js
const selectApiResult = apiSlice.endpoints.validateData.select({"valueA":"somevalue1","valueB":"somevalue2","valueC":"somevalue3"})
```
