### ISSUE TITLE
Feature Request: Limit number of concurrent requests

### ISSUE THREAD

**Issue by nikischin** [reduxjs/redux-toolkit#4654]
I noticed, in some cases, especially on some cache invalidations I run into some issue with `createApi` triggering many requests at once and running into some concurrency limits on my server. 

Therefore I was wondering if it would be possible to limit the number of parallel requests?

The cache invalidation works just fine as expected, it's just in some cases I require the frontend to have data from 10 or more apis at the same time, and it seems to run into some issues on my server because the client has too many open connections.

**Comment by EskiMojo14** [comment]
Without testing, it sounds like you could implement this with a promise queue and a custom base query:

```ts
import pLimit from "p-limit";
import { fetchBaseQuery } from "@reduxjs/toolkit/query";

const baseQuery = fetchBaseQuery({ baseUrl: "/api" });

const limit = pLimit(10);

const baseQueryWithLimit: typeof baseQuery = (arg, api, extraOptions) => {
  if (api.type === "mutation") return baseQuery(arg, api, extraOptions); // if you wanted to run mutations immediately, for example
  return limit(baseQuery, arg, api, extraOptions)
}
```

**Comment by markerikson** [comment]
I'll add this as a recipe in the "Customizing Queries" docs page.

**Comment by nikischin** [comment]
Thank you so much! I really appreciate your fast support and quick help!


> Without testing, it sounds like you could implement this with a promise queue and a custom base query:
> 
> import pLimit from "p-limit";
> import { fetchBaseQuery } from "@reduxjs/toolkit/query";
> 
> const baseQuery = fetchBaseQuery({ baseUrl: "/api" });
> 
> const limit = pLimit(10);
> 
> const baseQueryWithLimit: typeof baseQuery = (arg, api, extraOptions) => {
>   if (api.type === "mutation") return baseQuery(arg, api, extraOptions); // if you wanted to run mutations immediately, for example
>   return limit(baseQuery, arg, api, extraOptions)
> }

I just tested and it does the job! :)
