### ISSUE TITLE
state.filter changes nothing

### ISSUE THREAD

**Issue by M1dnight-ofcl** [reduxjs/redux-toolkit#4660]
I'm having a problem where `state.filter` refuses to work. I made it log the chaneg before and after the filter which showed that it was deleted but it won't update the state to resemble that. instead it just keeps the state the same even though I set it to overwrite it. I tried just using `state.filter` and `state=state.filter` but neither worked.

Here is my todo.js slice:
```js
import { createSlice } from '@reduxjs/toolkit';
import { generateId } from '../../modules/lib';
export const todoslice=createSlice({
  name: 'todo',
  initialState: [
    {//template
      title:"Test: Hello, World",
      desc:"Lorem ipsum odor amet, consectetuer adipiscing elit.",
      id:generateId(),
      meta:{
        creationTime: Date.now(),
        checked: false,
      }
    },{//template 2 (for test)
      title:"Test: Hello, World 2",
      desc:"Ipsum ullamco magna mollit quis quis veniam consectetur minim eu dolor reprehenderit consequat eu.",
      id:generateId(),
      meta:{
        creationTime: Date.now(),
        checked: true,
      }
    },{//template 3 (for test)
      title:"Test: Hello, World 3",
      desc:"Consequat cillum irure et laboris laboris amet ut officia aute mollit sit velit.",
      id:generateId(),
      meta:{
        creationTime: Date.now(),
        checked: false,
      }
    },
  ],
  reducers: {
    addTask:(state,action)=>{
      state.push(action.payload);
    },
    removeTask:(state,action)=>{
      console.log(`removing: ${action.payload}`)
      state=state.filter((item)=>item.id!==action.payload);
    },
    modifyState:(state,action)=>{
      state[state.findIndex(data=>data.id==action.payload.target)]=action.payload.new;
    },
  }
});
export const {
    addTask,
    removeTask,
    modifyState,
}=todoslice.actions;
export default todoslice.reducer;
```
And this is how I tried to refrence the `removeTask` Reducer (id is supplied as a prop to the component using a `state.map`):
```js
dispatch(removeTask(id));
```

I can include the whole component if anyone needs.
Does anyone know why this doesn't work? everything says it should but it doesn't. I've done a little research and nobody had a fix for this either, or none that worked for me. Please help. This bug is frustrating

**Comment by markerikson** [comment]
Yes, assigning `state = ` is always incorrect in an Immer-powered reducer. You need to _return_ a value if you want to replace the entire `state`:

- https://redux-toolkit.js.org/usage/immer-reducers#resetting-and-replacing-state

**Comment by M1dnight-ofcl** [comment]
I tried using return too but it js breaks everything. for some reason, `state=` is the only thing that works

**Comment by M1dnight-ofcl** [comment]
idk I'm currently in the process of completely reseting how I originally set up my redux because when I use return it results in errors and sm`state=` is the only thing that works. I've tried following the docs and most of my code was pasted from there so I dont know why its like this.

**Comment by markerikson** [comment]
I can assure you that `state =` _does nothing at all_. Ever. It is a no-op. It will not result in any actual Redux state being updated.

**Comment by M1dnight-ofcl** [comment]
I found a fix! The reson it was error was not a redux problem, but was a problem with how my component was running. I fixed it. `return` was the way to go! Thanks for the advice
