### ISSUE TITLE
Unable to resolve `redux-devtools-extension` and `redux-immutable-state-invariant`

### ISSUE THREAD

**Issue by JosephSemrai** [reduxjs/redux-toolkit#467]
Upon upgrading `redux-toolkit` in a React Native project, in development mode, I get thrown resolve errors surrounding the above packages.

I understand that `redux-toolkit` has recently began including these dependencies inline, so I'm wondering why these modules (referenced in `\node_modules\@reduxjs\toolkit\dist\redux-toolkit.cjs.production.min.js`) cannot be found.

If there are dependencies/co-dependencies to be installed manually, please just let me know and I'll close this issue. Thanks.

**Comment by markerikson** [comment]
Yeah, we inlined those in 1.3.0.

I'd suggest clearing whatever build tool caches may exist, because it sounds like you've got some leftover artifacts.  The only references to those that are left at this point are links in the docs - nothing in `package.json` or the code.

**Comment by JosephSemrai** [comment]
That ended up working. For future reference, it required clearing npm/yarn cache, using the Expo cache clearing tool, and resetting the cache on the testing device. Thanks.

**Comment by markerikson** [comment]
Fun times! :)

**Comment by Stas-Buzunko** [comment]
i get this error on windows and clearing everything doesn't help.

**Comment by phryneas** [comment]
Those two packages are definitely not a dependency of RTK any more.
Please check if you maybe have an old version of RTK installed by `yarn why @reduxjs/toolkit`.
You could also try running something like `npx yarn-deduplicate` - that MIGHT help if you have some duplicate dependencies in different versions.

**Comment by Stas-Buzunko** [comment]
i installed with npm

installing with yarn worked
