### ISSUE TITLE
Alternative suggestion to ducks pattern: Microservices & CQRS way

### ISSUE THREAD

**Issue by Can-Sahin** [reduxjs/redux-toolkit#469]
RTK might not be the place for this issue, but since it supports and encourages the `ducks pattern` I wanted to present another opinion. 

RTK is truly great and I am recently implementing it in [react-boilerplate-typescript](https://github.com/react-boilerplate/react-boilerplate-typescript), however after reading all the docs about **ducks**, **folder-by-feature** and **rtk-github-issues** example repo I have a different opinion on `slices` being shared with other `features`: 

### A complex and dependent system
Imagine multiple feature folders depends on each others' slices and actions. **A** can call **B** and **C** actions and uses their states in its selectors and so does others. If the application grows this creates quite a lot of dependencies  between features and you start loosing `folder-by-feature` paradigm since now the features are tangled with others and the slices are now no different than globally used reducers and actions under the same folder. I mean, if I create a folder for something to manage and it effects 10 other folders it kinda drives away idea of having a `independent feature folder` where the logic is encapsulated. Dependency is a big problem when the code grows. 

**Different approach**
I am working with `microservices` and `CQRS` and `event-driven systems` and there is pattern there can also be implemented in this scenario. Imagine, Feature **A** can never call or use feature **B**'s state and actions, but only can **listen** them. A has to keep its own state listening the external actions from everyone and keep kinda duplicate state. So, it only bothers with its own state and not with others and only can change state with others' actions. This way, all the slicers states are reserved for the feature they manage. In a react-function you only import actions from your own slice and use your own state in selectors. If the other features wants to be dependent on you they need to listen your actions and create their own replicated state. This is how `microservices` communicate in scalable architectures. They keep a database of their own and only depend on that **instead of depending on other modules**

This is never mentioned in any redux style guide or anywhere I could check. This favors scalability, independently managed, less-dependent architectures. 

Any opinions?

**Comment by markerikson** [comment]
Can you point to an actual example of what this suggestion looks like in practice?

And yeah, this doesn't have anything to do with RTK specifically - it's really about Redux app architecture in general.

**Comment by Can-Sahin** [comment]
I forked the `rtk-github-issues` repo on codesandbox. You don't need to run. Just `features` folder tells the story.
https://codesandbox.io/s/rtk-issue-469-example-ntgil

This doesn't illustrate what I meant because the nature of the problem requires complex and tangled code where here I have very basic features to demonstrate but I'll try. 

There are 4 feature folders A B C D. **A** is the focus here.

Imagine that there are lot of features like these and **A** has complex inner logic. It has no knowledge about how other features are done and shouldn't care because there are no **no explicit dependency** on other features and it's only logic is covered in its own feature folder. However, **B** can call **A's** actions and cause its state to change and **C** thinks that it only depends on **A** but actually it depends on **B** too unknowingly. However, feature **D** does it differently. It creates its own action instead of calling **A**. Now, **A** can explicitly decide to listen it and change its own state(comment-out code does that in A slice)

**It doesn't make any sense now** cause we can clearly keep track of simple dependencies. But, as the application and the **implicit** dependencies grow you loose track of these and independent features are lost and tangled all together. Like **B** decides to change the user name with a formatted string and now **A**'s logic has to be updated and **C's** too. It's very hard to maintain each feature independently and bug-free(as you are making changes in the other features) and also hard to write tests.


These kind of dependencies causes trouble, especially in backend development when the manipulation of data comes into play (like databases). It's up to developers choice of course to design its structure but all the docs and examples are mentioning a single pattern(duck) and I think its good to point out other possibilities using still ducks pattern.

**Comment by markerikson** [comment]
To be honest, this all feels rather vague and theoretical.

Redux doesn't dictate the overall application architecture, and I've seen many variations in how people build things.  That's how it _should_ be, because different apps have different needs.

The "features+ducks" suggestion is primarily just about folder structures, and keeping code that changes together close in the filesystem.  How you actually have those features interact with each other is up to you.

Since there's nothing actionable here, I'll go ahead and close this.
