### ISSUE TITLE
React component using `useQuery` fails to render data when using `jest.useFakeTimers`

### ISSUE THREAD

**Issue by ensconced** [reduxjs/redux-toolkit#4693]
See [here](https://github.com/ensconced/rtk-fake-timers-bug/blob/master/test.spec.js) for details on how to reproduce this issue.

You should be able to reproduce the issue just by cloning that repo, running `npm install` and then `npm run test`. 
There are two tests, each pretty much the same except that one uses fake timers, which seems to cause it to fail.

From what I can tell, the store is always updated with the data from the (stubbed) API response, but when using fake timers this does not result in the react component actually being rendered with the data.

**Comment by ensconced** [comment]
It seems that passing `{ doNotFake: ['clearTimeout'] }` into `jest.useFakeTimers` fixes this. (This isn't viable as a workaround for me - just mentioning in case it helps the investigation).

**Comment by phryneas** [comment]
I mean, you're configuring your runtime to not run per the specification. That *will* break every tool using `setTimeout` and `clearTimeout` - and RTK Query uses those.

So honestly I don't know what we could do to fix that - RTKQ needs them to work :/

**Comment by ensconced** [comment]
Sorry if this wasn't clear, but the reason I expect this to work is that the `findBy` functions provided by react testing library internally advance fake timers if they detect that jest is using fake timers. 

I've done some more digging and I'm pretty sure this is the problem: https://github.com/reduxjs/redux-toolkit/blob/24286f1745e42217448de1f3486886fa8558c1b5/packages/toolkit/src/autoBatchEnhancer.ts#L20

`requestAnimationFrame` is read into `rAF` at the top level of that module, meaning it will always use the real version of `window.requestAnimationFrame` and never the fake version inserted by jest.

**Comment by ensconced** [comment]
If I move the assignment of `rAF` into the `autoBatchEnhancer` function, just before it's used, it fixes my test.

**Comment by ensconced** [comment]
Let me know if there's anything else I can do to help this get merged 🙂

**Comment by markerikson** [comment]
Out in https://github.com/reduxjs/redux-toolkit/releases/tag/v2.4.0 !
