### ISSUE TITLE
RTK query - cache key is randomly getting deleted resulting in a loss of data

### ISSUE THREAD

**Issue by thoughtworks-tcaceres** [reduxjs/redux-toolkit#4697]
What's happening?
A cache key is getting removed automatically resulting in data being lost.

When the app is loaded, there is a custom hook that goes through every combination of year and id and does an `initiate` request to fetch all the data for each combination.
There is a main UI component screen that has the `useQuery` hook that performs requests for the current year/id combination.
There is a hook on the main UI component screen that listens when the device goes back online and does a refetch of data.
Sometimes when toggling between offline and online - the cache key (somehow) gets cleared **_resulting in a loss of data._**

The set up:
- a custom hook that loops through years / ids and does a request for each combination using initiate with `{subscribe: false}`
- a component that uses useQuery
- a custom hook in a component (the one above) that listens for device connectivity going between online and offline --- when it goes online, it automatically does a refetch (using the function extracted from useQuery hook)

Versions:
@reduxjs/toolkit: "2.2.8"
react-redux: "^9.1.2"

**Comment by phryneas** [comment]
If you aren't using a cache entry in a component for 60 seconds, it will be removed to save memory. Is that what you're seeing?

**Comment by thoughtworks-tcaceres** [comment]
> If you aren't using a cache entry in a component for 60 seconds, it will be removed to save memory. Is that what you're seeing?

Ah, i forgot to mention this sorry.
In the keepUnusedDataFor -- for the hook that gets initiated and the one on the UI screen (they are the same one) -- i have used Number.MAX_SAFE_INTEGER.
I saw this as a solution somewhere on these threads before, which seems to have been working so far.

The issue started arising once I started going back and forth between offline and online and closing and reopening the app.
Extra info: we're also persisting the data from redux-persist, in case that might be affecting something as well.

**Comment by thoughtworks-tcaceres** [comment]
> And you are using the integrations for redux-persist as laid out in the documentation?

Very similar.

```
 extractRehydrationInfo(action, { reducerPath }): any {
    if (isRehydrateAction(action)) {
      if (!action.payload) return;
      if (action.key === OFFLINE_MODE_STORAGE_KEY) return action.payload[reducerPath];
    }
  },
```

We used [reducerPath] with action.key because the other way didn't seem to work.
This way has worked so far in persisting the data -- except when we added in the extra custom hook logic when it goes from offline to online and uses unwrap.

^ We've tried 2 different ways for this - one way used the regular refetch function from useQuery. The other way used lazyQuery - both ways seemed to result in a loss of data.

```
const useOnlineRefetching = (
  fetchTriggers: (() => QueryActionCreatorResult<any>) | (() => QueryActionCreatorResult<any>)[],
) => {
  const isOnline = useAppSelector(selectIsConnected);
  const dispatch = useAppDispatch();
  const previouslyOffline = useRef(!isOnline);

  useEffect(() => {
    const triggerQuery = async () => {
      if (previouslyOffline.current && isOnline) {
        dispatch(setBannerStatusWithoutOffline('syncing'));
        try {
          if (Array.isArray(fetchTriggers)) {
            await Promise.all(fetchTriggers.map(f => f().unwrap()));
          } else {
            await fetchTriggers().unwrap();
          }
          dispatch(setBannerStatusWithoutOffline('syncCompleted'));
        } catch {
          dispatch(setBannerStatusWithoutOffline('syncFailed'));
        }
      }
    };

    triggerQuery();

    return () => {
      previouslyOffline.current = !isOnline;
    };
  }, [dispatch, fetchTriggers, isOnline]);
};

export default useOnlineRefetching;
```

**Comment by thoughtworks-tcaceres** [comment]
One additional thing to note is that we also use refetchOnMountOrArgChange - which isAffected by whether or not the device is online.
if it's online --> refetchOnMountOrArgChange is true, if it's offline --> refetchOnMountOrArgChange is false.

```
  const {
    currentData
    isFetching
    isError
    isUninitialized,
    error,
    refetch,
    fulfilledTimeStamp,
  } = useFakeQuery(
    selectedAgency?.salesAgencyId && salesYear
      ? {
          agencyId: selectedAgency.salesAgencyId,
          salesYear,
        }
      : skipToken,
    { refetchOnMountOrArgChange: isOnline },
  );
```

^ something like this is what calls the functions on the main screen.

**Comment by markerikson** [comment]
I don't think we have enough info to provide an answer without seeing an actual reproduction of the issue (either a repo or a [Replay](https://replay.io/record-bugs).

**Comment by thoughtworks-tcaceres** [comment]
> I don't think we have enough info to provide an answer without seeing an actual reproduction of the issue (either a repo or a [Replay](https://replay.io/record-bugs) ).

I think I was able to figure it out (finally).
It has to do with the customHook that calls the .initiate functions for each combination of id and year.
Sometimes it doesn't get triggered --- and I guess it's using the GLOBAL "keepUnusedDataFor" (60s) instead of the specific query's "keepUnusedDataFor" (Number.MAX_SAFE_INTEGER) -- which results in the "api/queries/removeQueryResult" dispatched actions.

When I'm persisting the data to the cache, we're currently only storing the api.queries -- do we need to additionally store the api.provided or api.subscriptions data as well? So that when we rehydrate the queries -- it will keep them for the specific query's Number.MAX_SAFE_INTEGER?

**Comment by phryneas** [comment]
> When I'm persisting the data to the cache, we're currently only storing the api.queries -- do we need to additionally store the api.provided or api.subscriptions data as well? So that when we rehydrate the queries -- it will keep them for the specific query's Number.MAX_SAFE_INTEGER?

Again, you need to use the tools we provide and document for persistence, everything else will end up with things randomly hanging around in your cache forever or being cleaned out for no good reason.

After that is ensured, we can take a look at the rest.

> Is there a way to do a initiateQuery with a delay

You could have a `baseQuery` wrapper that just staggers outgoing requests I assume

**Comment by thoughtworks-tcaceres** [comment]
> > When I'm persisting the data to the cache, we're currently only storing the api.queries -- do we need to additionally store the api.provided or api.subscriptions data as well? So that when we rehydrate the queries -- it will keep them for the specific query's Number.MAX_SAFE_INTEGER?
> 
> Again, you need to use the tools we provide and document for persistence, everything else will end up with things randomly hanging around in your cache forever or being cleaned out for no good reason.
> 
> After that is ensured, we can take a look at the rest.
> 
> > Is there a way to do a initiateQuery with a delay
> 
> You could have a `baseQuery` wrapper that just staggers outgoing requests I assume

Thanks for the response.
We have set the keepUnusedDataFor to Number.MAX_SAFE_INTEGER to keep the cache permanently for now.
