### ISSUE TITLE
Typescript doesn't find created actions when using createAsyncThunk

### ISSUE THREAD

**Issue by satvikpendem** [reduxjs/redux-toolkit#470]
I'm trying to use Typescript with createAsyncThunk and I can create the thunk just find but I'm not exactly sure how to use the created actions. When I export the actions at the end, they are not found and the code in fact doesn't compile. I use the `builder.addCase` way of creating the reducers so they should be created.

```typescript
import { createSlice, PayloadAction, createAsyncThunk } from "@reduxjs/toolkit";

type AuthenticationParameters = {
  email: string;
  password: string;
};

type LoginPayload =
  | ({
      type: "PROVIDER";
    } & AuthenticationParameters)
  | ({
      type: "USER";
    } & AuthenticationParameters)
  | { type: "UNAUTHENTICATED" };

const initialState = {
  loginType: { type: "UNAUTHENTICATED" } as LoginPayload
};

const requestLogin = createAsyncThunk(
  "authentication/login",
  async ({ email, password }: AuthenticationParameters) => {
    const response =
      await fetch(process.env.REACT_APP_API_URL + "/login", {
        method: "post",
        body: JSON.stringify({ email, password })
      });
    return response;
  }
);

const authenticationSlice = createSlice({
  name: "authentication",
  initialState,
  reducers: {},
  extraReducers: builder => {
    builder.addCase(requestLogin.pending, (state, action) => {
      console.log(action);
    });
    builder.addCase(requestLogin.fulfilled, (state, action) => {
      console.log(action);
    });
    builder.addCase(requestLogin.rejected, (state, action) => {
      console.log(action);
    });
  }
});

export const {
  login,
  loginSuccess,
  loginFailure
} = authenticationSlice.actions; // Typescript doesn't find "login" actions

export { authenticationSlice };
```

**Comment by phryneas** [comment]
Well, you are not *defining* any `login` action. The `createSlice.actions` only contains the action from the `reducers` option. You can just export your `requestLogin` and I believe that might be what you are looking for?

**Comment by satvikpendem** [comment]
I thought from the examples that the "authentication/login" name is supposed to define a `login` action in the `authentication` slice , or is that not how it works? If I wanted to use the actions in a slice as I would normally with RTK, what would I need to do, just export the `requestLogin` like you said?

**Comment by phryneas** [comment]
What you *are* defining is that your slice reacts to the action types `authentication/login/pending`, `authentication/login/fulfilled` and `authentication/login/rejected`.

But you would never manually dispatch any of those. You would `dispatch(requestLogin({username: "test", password: "test"}))`, which would lead to `authentication/login/pending` being dispatched, followed by either `authentication/login/fulfilled` or `authentication/login/rejected`. But you won't actively do any of that.

**Comment by satvikpendem** [comment]
I see, thanks I was able to make my code work now!
