### ISSUE TITLE
graphqlRequestBaseQuery "util.inherits is not a function"

### ISSUE THREAD

**Issue by barnabasbartha** [reduxjs/redux-toolkit#4702]
Using graphqlRequestBaseQuery from "@rtk-query/graphql-request-base-query": "^2.3.1" throws "util.inherits is not a function".
Anyone faced the same issue?

**Comment by phryneas** [comment]
I don't think that's from our codebase - could that be cause by the `graphql` package?

**Comment by barnabasbartha** [comment]
I don't know. I just wonder how it is supposed to be used as the npm package home page leads to redux-toolkit readme.

**Comment by markerikson** [comment]
@barnabasbartha what is the entire call stack of the error?

**Comment by markerikson** [comment]
Closing due to lack of repro, and this seems to be outside of our codebase.
