### ISSUE TITLE
`upsertQueryEntries`: `any` value assignment

### ISSUE THREAD

**Issue by JacobJaffe** [reduxjs/redux-toolkit#4712]
Hello, I'm working on migrating to use `upsertQueryEntries` (and _very_ excited about it!)

Any use of `upsertQueryEntries` seems to trip my `typescript-eslint/no-unsafe-call` / `typescript-eslint/no-unsafe-assign`linting. 

I haven't encountered this elsewhere using RTK -- I'm not sure what's going on here, since the action creator seems like it would be well typed. 

Here's a minimal example of this:

```ts
const newApi = createApi({
  reducerPath: "foo",
  baseQuery: fetchBaseQuery({ baseUrl: "/api" }),
  endpoints: (builder) => ({
    getFoo: builder.query<string, string>({
      query: (foo) => `/${foo}`,
    }),
  }),
});

const uqe = newApi.util.upsertQueryEntries;
```

![Image](https://github.com/user-attachments/assets/8e3a5518-72d8-4b17-8db0-8cfbf016fd30)

**Comment by markerikson** [comment]
That seems pretty odd.

Can you share a project or CodeSandbox that shows this happening?

What does TS show as the actual type of `newApi.util.upsertQueryEntries` itself?

**Comment by JacobJaffe** [comment]
The TS type of `upsertQueryEntries` appears to be the same:
```ts
(property) upsertQueryEntries: UpsertEntries<{
    getFoo: QueryDefinition<string, BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, never, string, "foo">;
}>
```

![Image](https://github.com/user-attachments/assets/ad0327cd-4a9b-4db6-b97f-ab70d25abcc1)

I'll put together a minimal sharable project that reproduces this shortly

**Comment by JacobJaffe** [comment]
I've been unable to reproduce this in a fresh environment, and am no longer seeing this in my project after reinstalling dependencies. Closing this issue.
