### ISSUE TITLE
Remove unnecessary export inside Quick Start documentation

### ISSUE THREAD

**Issue by maqsudtolipov** [reduxjs/redux-toolkit#4719]
I think the **export** inside [Quick Start](https://redux-toolkit.js.org/tutorials/quick-start#create-a-redux-state-slice) documentation should be removed. 
- It confuses beginners as they might think **counterSlice** will be used somewhere in their code. 
- Also this export is not being used

![Image](https://github.com/user-attachments/assets/2bba77a1-e16c-420e-949d-27ecccf78f21)

**Comment by markerikson** [comment]
Thanks for the suggestion, but I don't think this really needs to be changed.
