### ISSUE TITLE
Dispatching initiate() function resolves with a status of pending

### ISSUE THREAD

**Issue by npfitz** [reduxjs/redux-toolkit#4720]
I'm currently running into a situation where I call `initiate()` on an endpoint that currently has a request in flight (due to tag invalidation), but the value I'm returned is the previously cached entry, alone with some metadata such as `isLoading: true` and `status: pending`. For example:
```
await dispatch(cardApi.endpoints.getCard.initiate({id}, {forceRefetch:true})
```
returns an object like
```
{
    "status": "pending",
    "endpointName": "getCard",
    "requestId": "JOhITYA33zsbG75F0IuRo",
    "originalArgs": {
        "id": 18
    },
    "startedTimeStamp": 1732104749367,
    "data": {
        /* Cached data entry */
    },
    "fulfilledTimeStamp": 1732104744906,
    "isUninitialized": false,
    "isLoading": true,
    "isSuccess": false,
    "isError": false
}
```

For some reason, even though there is an in flight request we are resolving the promise immediately with cached data. However, if I delete the cache entry before my call to initiate, awaiting `initiate` will work as expected. So my current work around is to dispatch `cardApi.internalActions.removeQueryResult` before calling `initiate`. 

Is this expected behavior? Is there any way to access the promise of the in flight response above? Thanks in advance.

Edit:
This is using `@reduxjs/toolkit@2.2.5`

**Comment by EskiMojo14** [comment]
I suspect you should be able to use [`getRunningQueryThunk`](https://redux-toolkit.js.org/rtk-query/api/created-api/api-slice-utils#getrunningquerythunk-and-getrunningmutationthunk) to get the promise from the request currently in flight.

**Comment by npfitz** [comment]
Interesting! I'll give that a try and report back. Thanks @EskiMojo14

**Comment by npfitz** [comment]
@EskiMojo14 It seems to be returning undefined. When I try dispatching `getRunningQueriesThunk` I get back an empty array

**Comment by npfitz** [comment]
@phryneas Absolutely! Do you mean my original issue, or `getRunningQueriesThunk` returning an empty array? Is there any chance there is a code sandbox available with a dummy app? haha

**Comment by phryneas** [comment]
Ideally both, but I'm more intrigued about `getRunningQueriesThunk` returning an empty array - if we can see that, we can probably answer both questions.

You could e.g. start with https://codesandbox.io/p/sandbox/github/reduxjs/redux-toolkit/tree/master/examples/query/react/basic but please update the RTK versions, that's unfortunately quite outdated

**Comment by npfitz** [comment]
@phryneas good news! I set up a code sandbox that illustrates my issue, and I was using `@reduxjs/toolkit@2.2.5` like we are in our environment. I was able to reproduce it, but in the sandbox I updated to `2.3.0` and the issue appears to be resolved. I'll try updating on our end to see if that helps!

Sandbox[ is here](https://codesandbox.io/p/sandbox/patient-platform-l3sygt) if you're curious

**Comment by markerikson** [comment]
@npfitz that seems surprising, because nothing in 2.3.0 should have changed any of that behavior:

- https://github.com/reduxjs/redux-toolkit/releases/tag/v2.3.0

**Comment by npfitz** [comment]
@markerikson Is seems that `2.2.8` is where the issue was fixed, based on what I'm seeing in the sandbox by changing the version numbers up and down

**Comment by markerikson** [comment]
Ah, okay, that might be related to the changes in https://github.com/reduxjs/redux-toolkit/pull/4651

**Comment by npfitz** [comment]
I think we can close this issue then. Thanks all for the help in diagnosing!
