### ISSUE TITLE
second call of cached rkt query  never get  true

### ISSUE THREAD

**Issue by ivaylo-stoilov-i** [reduxjs/redux-toolkit#4724]
ihave get query with no argument which take a more time to finish .

```ts
getEnvironments: build.query<
      GetEnvironmentsApiResponse,
      GetEnvironmentsApiArg
    >({
      query: () => ({ url: `/environments` }),
        
    }),
```

in React project one component execute this query for first time (query take a time to executed )
Another component executed this query again (it hit cache new request is not created  this is correct  )  but first one is not finished yet 
in second execution never get isSuccess true even after query is finessed .

```ts
const { data: loadedEnvironments = [], isSuccess: isLoadingEnvironments } =
    useGetEnvironmentsQuery();
```

"react-redux": "^7.2.6"

**Comment by markerikson** [comment]
I'm sorry - I realize that English is probably not your first language, but I don't understand the problem you're trying to describe.

If you can create a CodeSandbox or a Github repo that shows this happening we can maybe take a look, but I'll have to close this until then.
