### ISSUE TITLE
isRejectedWithValue does not return true on HTTP 403

### ISSUE THREAD

**Issue by nikischin** [reduxjs/redux-toolkit#4725]
I would like to logout my users if my session expired in the backend. As the login state is saved in a reducer I have a action `setCurrentAccount ` I would like to dispatch on any 403 HTTP return codes.

My implementation below unfortunately does not work as I would expect it. The rejected API calls with HTTP 403 unfortunately do not trigger the `isRejectedWithValue(action)` so I was wondering if I might have some error in my implementation or possibly even in RTK?

```
export const rtkQueryErrorLogger: Middleware =
    (api: MiddlewareAPI) => (next) => (action) => {
        // RTK Query uses `createAsyncThunk` from redux-toolkit under the hood, so we're able to utilize these matchers!
        if (isRejectedWithValue(action)) {
            if (action.payload?.status === 403) {
                console.error('LOGOUT');
                api.dispatch(baseApi.util.resetApiState());
                api.dispatch(setCurrentAccount({ account: null }));

                toast.error('You are not logged in');
            } else {
                console.error('We got a rejected action!', action);

                // Takes both transformed and untransformed backend errors
                const title = (typeof action.payload === 'string') ? action.payload : (typeof action.payload?.data?.error === 'string' ? action.payload?.data?.error : (typeof action.payload?.status === 'string' ? action.payload?.status : 'Loading failed ' + (action.payload?.status ?? '')));
                toast.error(title);
            }
        } else {
            console.log('SUCCESSFUL', action);
        }

        return next(action);
    };

export const store = configureStore({
    reducer: combinedReducer,
    // Adding the api middleware enables caching, invalidation, polling,
    // and other useful features of `rtk-query`.
    middleware: (getDefaultMiddleware) =>
        getDefaultMiddleware().concat(baseApi.middleware).concat(loadingBarMiddleware({
            promiseTypeSuffixes: [ 'pending', 'fulfilled', 'rejected' ],
        })).concat(rtkQueryErrorLogger),
    enhancers: (getDefaultEnhancers) => getDefaultEnhancers().concat(
        rememberEnhancer(
            window.localStorage, // or window.sessionStorage, or your own custom storage driver
            [ 'filter' ]
        )
    )
});
```

My console log for the failed request below:
![Image](https://github.com/user-attachments/assets/7dcf7021-94f1-421d-b612-d3e50707687d)

**Comment by EskiMojo14** [comment]
how is your getTasks endpoint defined?

that rejected action isn't rejected with a value, so I'm not sure where it's getting raised from.

**Comment by nikischin** [comment]
> how is your getTasks endpoint defined?
> 
> that rejected action isn't rejected with a value, so I'm not sure where it's getting raised from.

It is implemented like this:
```
getTasks: builder.query<TaskOverviewItemType[], GetTasksApiParams>({
            query: ({ contact, user }) => ({
                url: 'getTasks',
                method: 'POST',
                body: JSON.stringify({ contact, user })
            }),
            transformResponse: ({ tasks }) => tasks,
            transformErrorResponse: transformErrorResponse,
            providesTags: provideTags((result, error, queryArgs) => [
                { type: 'task', id: 'ALL' },
            ])
        }),
```

So from your question, I suspect the transformErrorResponse could produce the error?

It is implemented as below:
```
export const transformErrorResponse = (response: { status: number, data: { error: string } }) => response.data.error;
```

**Comment by nikischin** [comment]
So the issue was indeed within `transformErrorResponse`. My intended usage was to be able to directly use error as I would use data.

`const { currentData, isFetching, isError, error } = useGetTasksQuery();`

So I would have error directly be the error message from my API. It wouldn't be a problem to be an object of status and data for me, however, I would prefer the error object to always be consistent, and from my experience, depending on the type of error I might find the actual error message at a different parameter. What is the best practice for unifying error handling?

I would like to use the error like this

```
return (isError ? 
    <Alert>{error.message}</alert> : 
    <div>{currentData.map(item => (
        <div key={item.id}>{item.title}</div>
    )}</div>
);
```

Thank you very much again @EskiMojo14!
