### ISSUE TITLE
Giving warning in next.js 15

### ISSUE THREAD

**Issue by anishkumar127** [reduxjs/redux-toolkit#4747]
**versions** 
"@reduxjs/toolkit": "^2.3.0",
 "react": "19.0.0-rc-66855b96-20241106",
 "react-dom": "19.0.0-rc-66855b96-20241106",
 "next": "15.0.3",

**warnings**

 WARN  Issues with peer dependencies found
.
├─┬ react-redux 9.1.2
│ ├── ✕ unmet peer react@^18.0: found 19.0.0-rc-66855b96-20241106
│ └─┬ use-sync-external-store 1.2.2
│   └── ✕ unmet peer react@"^16.8.0 || ^17.0.0 || ^18.0.0": found 19.0.0-rc-66855b96-20241106
├─┬ @reduxjs/toolkit 2.3.0
│ └── ✕ unmet peer react@"^16.9.0 || ^17.0.0 || ^18": found 19.0.0-rc-66855b96-20241106
└─┬ @fluentui/react-components 9.56.1
  └─┬ @fluentui/react-alert 9.0.0-beta.124
    └─┬ @fluentui/react-avatar 9.6.42
      └─┬ @fluentui/react-popover 9.9.24
        └─┬ @fluentui/react-context-selector 9.1.69
          └── ✕ unmet peer scheduler@">=0.19.0 <=0.23.0": found 0.25.0-rc-66855b96-20241106

Done in 11s

**Comment by markerikson** [comment]
We don't currently explicitly list React 19 in our peer dependencies because it's not final yet. We'll update that when React 19 officially comes out. That said, it should _work_ fine at runtime.

**Comment by anishkumar127** [comment]
@markerikson React 19.0.0 Officially stable now.
