### ISSUE TITLE
typed dispatch with createAsyncThunk

### ISSUE THREAD

**Issue by adammlr** [reduxjs/redux-toolkit#475]
This is more of a Typescript question, but relates directly to code usage with createAsyncThunk.
I'm creating a wrapper for the dispatch hook from react-redux to implement error handling and was hoping to pass through the type of the response in createAsyncThunk so that my result of dispatch also is typed:
```
  function dispatchHook(actionCreator: any, options: dispatchOptions = {}) {
    if (!actionCreator) {
      throw new Error('dispatch called without action');
    }

    return dispatch(actionCreator)
      .then(unwrapResult)
      //error handling code
```
in my component:
`const response = await dispatch(ApiThunkFromState())`

Can i type the ActionCreator param so that response is typed?  This hook is only used with createAsyncThunk.  I should note that I can accomplish this by making dispatchHook generic, but I am essentially repeating the type that I've already passed into createAsyncThunk.
Thanks for this library and keep up the good work!

**Comment by phryneas** [comment]
You can do something like (just pseudocode, gotta figure out the details for yourself ^^)
` function dispatchHook<R>(actionCreator: () => ThunkAction<R, State, unknown, unknown> , options: dispatchOptions = {}): Promise<R> { /* ... */ } `, but you cannot access `R` within that function as at that time it is still unresolved - it can be used outside of it though, so if you call something like `dispatchHook(()=>()=>"test")`, the return value will be inferred as `Promise<string>`.
