### ISSUE TITLE
Error "'enableES5' is not exported from 'immer'" in v1.3.x

### ISSUE THREAD

**Issue by FdezRomero** [reduxjs/redux-toolkit#476]
I'm updating `@reduxjs/toolkit` from `v1.2.4` to the latest `v1.3.2` in a Create-React-App and the build fails with this error message:

```
./node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js
Attempted import error: 'enableES5' is not exported from 'immer'.
```

I also tried `v1.3.0` and `v1.3.1` but both give me the same problem, so I guess it has something to do with `immer@6.0.x`.

I'm using the latest `react-scripts@3.4.1` with `typescript@3.8.3`.

Does anyone have any idea of what might be happening?

Thanks!

**Comment by phryneas** [comment]
https://github.com/reduxjs/redux-toolkit/issues/466

**Comment by FdezRomero** [comment]
Thanks a lot @phryneas! I'll follow the issue on https://github.com/facebook/create-react-app/issues/8750

**Comment by actionjacks** [comment]
> I fixed it with `yarn add immer` and adding this at the top of the file where I have the `configureStore()` call:
> 
> ```ts
> import { enableES5 } from 'immer';
> enableES5();
> ```

tnx
