### ISSUE TITLE
Search not working on a website

### ISSUE THREAD

**Issue by bbtools-ps** [reduxjs/redux-toolkit#4767]
### Issue:

When visiting https://redux-toolkit.js.org/ and clicking the **Search** button nothing happens.

![Image](https://github.com/user-attachments/assets/7f211b8a-2861-476b-8ce2-f001f24a3a06)

### Expected behavior:

A popup would open after clicking the **Search** button, prompting the user to type and search the documentation.

**Comment by markerikson** [comment]
Yeah, this is related to #4766

**Comment by markerikson** [comment]
Fixed!
