### ISSUE TITLE
Copy Code Function Not Working

### ISSUE THREAD

**Issue by theaiemperor** [reduxjs/redux-toolkit#4773]
I am experiencing an **issue with** the **Copy Code** functionality on the **Redux Toolkit documentation website**. When I click the "Copy Code" button next to code snippets, the **code does not get copied** to the clipboard as expected. This issue persists consistently across different pages of the Redux Toolkit documentation.

**Comment by markerikson** [comment]
Yeah, there's a known issue with the docs site atm - see #4766 and #4767 . 

I'll close this as a duplicate for now.

**Comment by markerikson** [comment]
Fixed!
