### ISSUE TITLE
It would be nice if each endpoint in an api object got unique fulfilled actions

### ISSUE THREAD

**Issue by steinarb** [reduxjs/redux-toolkit#4778]
In redux devtool on the webapp I'm currently in the process of transforming to RTK query, I see three interesting payloads go by, that I could have made use of in other reducers:
![Image](https://github.com/user-attachments/assets/fea3fbb4-4061-4d29-92ae-6d67b440bf00)
![Image](https://github.com/user-attachments/assets/c664c719-8ebd-4018-b4e6-9b6d6b2ea42e)
![Image](https://github.com/user-attachments/assets/9b079911-6cf4-43de-8a37-3a4c41679448)

Unfortunately they all have the same redux action type.

It's possible that one could look into the meta structure to find something to switch on, but:

1. A lesson learned early in my redux use was that switching on something other than the type is a bad idea
2. The meta data struture isn't easy to figure out and is probably intended to be opaque and will possibly/probably change without notice...?

But making the action type unique for each endpoint of the api object would make the redux value easy to use in other reducers.

**Comment by phryneas** [comment]
> A lesson learned early in my redux use was that switching on something other than the type is a bad idea

You would use the matchers provided by RTK Query:

```
if (api.endpoints.myEndpoint.matchFulfilled(action)) {
 // you can be sure it's for that endpoint, and it's also automatically typed correctly.
}
```

**Comment by steinarb** [comment]
Thanks for the pointer! I will try.

**Comment by steinarb** [comment]
Worked perfectly! Changed from: https://gist.github.com/steinarb/8e90728fa60ff81a692bfd3422c95b81#file-storeidreducer-js-L4
To: https://gist.github.com/steinarb/13d45b35e7fc3dd058e24071b2372e7e#file-storeidreducer-js-L3

Drop in replacement and lowered line count (could delete the action itself).

**Comment by steinarb** [comment]
Closing this, as the functionality is already available.

**Comment by steinarb** [comment]
Finger trouble. Shouldn't have been "duplicate", should have been "Wont fix". Sorry!
