### ISSUE TITLE
TS circular type errors when dispatching async thunk from middleware

### ISSUE THREAD

**Issue by alexey-kozlenkov** [reduxjs/redux-toolkit#4784]
**Setup:** 

I have pretty simple use case: application loads `user info` on startup, and if user have particular `permission`, app needs to load additional chunk of data.

I'm trying to do this via middleware: when `user info` thunk fulfilled, dispatch another async thunk if criteria match.

**Issue**
In order to dispatch thunk (my 2nd load action) from the middleware, `Dispatch` type there should be `AppDispatch` as it knows how to dispatch thunks. This leads to a TS circular reference error.

**Reproduction link**
https://codesandbox.io/p/sandbox/async-thunk-middleware-y33xlz

I'd appreciate any help overcoming this, thanks! 🙏

**Comment by EskiMojo14** [comment]
The AppDispatch type can't be used by middleware, since it's directly derived from them. You would need to use the ThunkDispatch type manually.

**Comment by alexey-kozlenkov** [comment]
@EskiMojo14 I see, thanks!
