### ISSUE TITLE
[BUG] Copy Button on Redux Toolkit Website Not Functioning

### ISSUE THREAD

**Issue by Siddhram** [reduxjs/redux-toolkit#4785]
**Description**

The "Copy" button on the [Redux Toolkit website](https://redux-toolkit.js.org/) to copy the npm install @reduxjs/toolkit command is not working. Clicking the button does not copy the command to the clipboard.

**Steps to Reproduce**

1. Go to [Redux Toolkit website](https://redux-toolkit.js.org/).

2. Find the npm install @reduxjs/toolkit command.

3. Click the "Copy" button.

4. Paste the copied text into a text editor or terminal.

**Expected Behavior**

The command should be copied to the clipboard.

**Actual Behavior**

The button does not copy the command.

**Browser**: [Specify browser and version, e.g., Chrome 117.0.0]

**OS**: [Specify operating system, e.g., Windows 11 / macOS Ventura]

**Suggested Fix**

Check the JavaScript clipboard functionality of the "Copy" button and ensure it works across all browsers.

**Screenshot of the Issue:**

![Image](https://github.com/user-attachments/assets/0c4ba79b-5398-4734-a6b0-2facdd3bcf97)

**Comment by alexey-kozlenkov** [comment]
Honestly bunch more stuff isn't working, like 
* can't activate search field
* collapse button on section in navigation

https://github.com/user-attachments/assets/3b9fb74a-1f91-41f6-8813-ada90aa4a99c

**Comment by markerikson** [comment]
Yeah, known issue and we're working on it - see #4766

**Comment by markerikson** [comment]
Fixed!
