### ISSUE TITLE
Issue with Installing @reduxjs/toolkit in Next.js 15

### ISSUE THREAD

**Issue by tokasravi9000** [reduxjs/redux-toolkit#4792]
I'm encountering an issue while trying to install @reduxjs/toolkit in a Next.js 15 project. After running npm install @reduxjs/toolkit, I'm facing compatibility issues, possibly due to dependencies or changes in Next.js 15 that affect Redux toolkit integration.

I would appreciate any insights on:

Whether Next.js 15 has introduced breaking changes that affect Redux or Redux Toolkit.
Suggested solutions or workarounds for integrating Redux Toolkit with Next.js 15.
Looking forward to hearing your thoughts and any advice on how to resolve this issue. Thanks!

**Comment by EskiMojo14** [comment]
could you be more specific about the issues you're seeing?

**Comment by phryneas** [comment]
The error message would really help. It usually gives a quite detailes breakdown about what's going wrong.

**Comment by tokasravi9000** [comment]
when I run this codethan below error genrate npm i @tanstack/react-query
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: laundry-app@0.1.0
npm error Found: react@19.0.0-rc-66855b96-20241106
npm error node_modules/react
npm error   react@"19.0.0-rc-66855b96-20241106" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^18 || ^19" from @tanstack/react-query@5.62.10
npm error node_modules/@tanstack/react-query
npm error   @tanstack/react-query@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/ravi/.npm/_logs/2024-12-27T10_20_53_673Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/ravi/.npm/_logs/2024-12-27T10_20_53_673Z-debug-0.log

**Comment by phryneas** [comment]
What has `@tanstack/react-query` to do with Redux Toolkit?

**Comment by tokasravi9000** [comment]
Oh I am sorry actuly when I got an issue with installation with RTK then I try @tanstack/react-query I will update it to the RTK error here below:

(base) ravi@ravis-MacBook-Air laundry-app % npm install @reduxjs/toolkit
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: @reduxjs/toolkit@2.5.0
npm error Found: react@19.0.0-rc-66855b96-20241106
npm error node_modules/react
npm error   peer react@"^18.2.0 || 19.0.0-rc-66855b96-20241106" from next@15.0.3
npm error   node_modules/next
npm error     peer next@"^14.0.0-0 || ^15.0.0-0" from next-auth@5.0.0-beta.25
npm error     node_modules/next-auth
npm error       next-auth@"^5.0.0-beta.25" from the root project
npm error     next@"15.0.3" from the root project
npm error   peer react@"^18.2.0 || ^19.0.0-0" from next-auth@5.0.0-beta.25
npm error   node_modules/next-auth
npm error     next-auth@"^5.0.0-beta.25" from the root project
npm error   4 more (react-dom, react-icons, styled-jsx, the root project)
npm error
npm error Could not resolve dependency:
npm error peerOptional react@"^16.9.0 || ^17.0.0 || ^18 || ^19" from @reduxjs/toolkit@2.5.0
npm error node_modules/@reduxjs/toolkit
npm error   @reduxjs/toolkit@"*" from the root project
npm error
npm error Conflicting peer dependency: react@19.0.0
npm error node_modules/react
npm error   peerOptional react@"^16.9.0 || ^17.0.0 || ^18 || ^19" from @reduxjs/toolkit@2.5.0
npm error   node_modules/@reduxjs/toolkit
npm error     @reduxjs/toolkit@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/ravi/.npm/_logs/2024-12-27T08_02_51_483Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/ravi/.npm/_logs/2024-12-27T08_02_51_483Z-debug-0.log

**Comment by EskiMojo14** [comment]
it looks like Next is using the RC version of React, and needs to be updated to use the stable release. I don't think there's anything we can/should do on our end.

**Comment by tokasravi9000** [comment]
I use this version of "next": "15.0.3", and currently NextJS provides this version of "next": 15.1.2.

**Comment by EskiMojo14** [comment]
yes
