### ISSUE TITLE
Inconsistent line endings in new project

### ISSUE THREAD

**Issue by mradenovic** [reduxjs/redux-toolkit#482]
When a new project is created with `npx create-react-app my-app --template redux`, almost all of the files have `CRLF` line endings. `package.json` and `yarn.lock` have `LF` line endings.

This is also opposite from the default `create-react-app` template where all files haven `LF` endings.

**Comment by markerikson** [comment]
Please file issues on the actual template repos - this is just the repo for the Redux Toolkit library.
