### ISSUE TITLE
Type issue with action returned from dispatching async action

### ISSUE THREAD

**Issue by StagasaurusRex** [reduxjs/redux-toolkit#485]
I have this asyncAction
![Action](https://user-images.githubusercontent.com/4968936/78627000-fbc89000-7855-11ea-9735-141d44abac1a.png)
and I am using it like this,
![Dispatch](https://user-images.githubusercontent.com/4968936/78627385-eef86c00-7856-11ea-946d-adf1e0f440d4.png)
but typescript complains about the type of the responseAction with

`error TS2345: Argument of type '(dispatch: ThunkDispatch<CombinedState<{ ajax: AjaxState; app: AppMetaState; auth: AuthState; online: OnlineState; settings: SettingsState; socket: SocketState; themes: ThemeState; user: UserState; }>, unknown, AnyAction>, getState: () => CombinedState<...>, extra: unknown) => Promise<...> & { ...; }' is not assignable to parameter of type 'Action<unknown>'.
  Property 'type' is missing in type '(dispatch: ThunkDispatch<CombinedState<{ ajax: AjaxState; app: AppMetaState; auth: AuthState; online: OnlineState; settings: SettingsState; socket: SocketState; themes: ThemeState; user: UserState; }>, unknown, AnyAction>, getState: () => CombinedState<...>, extra: unknown) => Promise<...> & { ...; }' but required in type 'Action<unknown>'.
`

Can anyone point me in the right direction?
Do I need to type my `useDispatch()` hook somehow ?

Thanks

**Comment by phryneas** [comment]
Could you please try to create a reproduction CodeSandbox?

**Comment by StagasaurusRex** [comment]
[Here you go.](https://codesandbox.io/s/redux-toolkit-v85k7?file=/src/features/posts/PostList.tsx)

**Comment by msutkowski** [comment]
@StagasaurusRex I believe you're looking for this: https://redux-toolkit.js.org/usage/usage-with-typescript#getting-the-dispatch-type

Updated your example to follow that: https://codesandbox.io/s/redux-toolkit-typed-appdispatch-cd4fw

@phryneas will most likely have a better answer though :)

**Comment by phryneas** [comment]
Essentially what @msutkowski is saying.

I'd do

```ts
export type AppDispatch = typeof store.dispatch;
export const useAppDispatch = () => useDispatch<AppDispatch>();
```

and then use `useAppDispatch` wherever you had been using `useDispatch`, that should solve all your problems.

**Comment by markerikson** [comment]
`const dispatch: AppDispatch = useDispatch()` is also an option.

**Comment by phryneas** [comment]
> `const dispatch: AppDispatch = useDispatch()` is also an option.

Yup, that's what @msutkowski suggested - but you'd have to type that in every file.

**Comment by msutkowski** [comment]
@markerikson @phryneas I'll open a PR to update the docs that show this usage to include this info. As of right now, there is no hint in line with the code examples.

**Comment by markerikson** [comment]
Yeah, I've seen multiple folk ask about how to type dispatching thunks correctly.  Can you update the Redux core docs page too?

**Comment by StagasaurusRex** [comment]
So this definitely seems like the solution, but I'm still having issues. I've simplified my store/ reducers quite a bit to try and find the solution but no luck.

This is my entire store,
![store](https://user-images.githubusercontent.com/4968936/78723096-66c6a500-78f0-11ea-869e-5d65e31b8258.png)

My root reducer,

![reducer](https://user-images.githubusercontent.com/4968936/78723110-70500d00-78f0-11ea-9f7e-98170bebbcd3.png)


my only slice,

![slice](https://user-images.githubusercontent.com/4968936/78723116-734afd80-78f0-11ea-92b0-991941251902.png)

and how I'm using the action (which is the same as my first post)

![use](https://user-images.githubusercontent.com/4968936/78723144-83fb7380-78f0-11ea-8a43-ad877cba12d0.png)

and typescript complains with 
`Argument of type '(dispatch: ThunkDispatch<CombinedState<{ auth: AuthState; }>, unknown, AnyAction>, getState: () => CombinedState<{ auth: AuthState; }>, extra: unknown) => Promise<...> & { ...; }' is not assignable to parameter of type 'AnyAction'.
  Property 'type' is missing in type '(dispatch: ThunkDispatch<CombinedState<{ auth: AuthState; }>, unknown, AnyAction>, getState: () => CombinedState<{ auth: AuthState; }>, extra: unknown) => Promise<...> & { ...; }' but required in type 'AnyAction'.`

It seems like the issue is that it's inferring the AnyAction type somehow, but I don't know where that could be coming from. Any thoughts would be appreciated.

Thanks.

**Comment by StagasaurusRex** [comment]
The crux of my issue seems to be that AppDispatch is being inferred as `Dispatch<AnyAction>`, whereas in the sandbox I see that it is being inferred as `ThunkDispatch<RootState, null, AnyAction>`

**Comment by phryneas** [comment]
That might be the case if you are using custom middlewares. TypeScript tends to throw away type information there.
Try the solutions laid out in https://redux-toolkit.js.org/usage/usage-with-typescript#correct-typings-for-the-dispatch-type, or use the getDefaultMiddleware result last, or just type the middleware array by hand.

**Comment by StagasaurusRex** [comment]
I saw that but I've removed all my middleware and the issue persists. I've also tried it with my only middleware being `getDefaultMiddleware<RootState>()` i.e. 
`
const store = configureStore({
  reducer: rootReducer,
  middleware: getDefaultMiddleware<RootState>()
});
`

I can solve the issue by exporting AppDispatch as
`export type AppDispatch = ThunkDispatch<RootState, null, AnyAction>;`
but I was hoping to find the root of my issue.

**Comment by phryneas** [comment]
If you can somehow reproduce it, I can take a look - without that, sadly I cannot do anything.
From the back of my head, there might be problems with old versions of TypeScript, which version are you using?

**Comment by StagasaurusRex** [comment]
I'm using 3.8.2 which I believe is the newest.

**Comment by phryneas** [comment]
If you copy these lines into your codebase, what is the resulting type?

```ts

type DispatchForMiddlewares<M> = M extends ReadonlyArray<any>
  ? UnionToIntersection<
      M[number] extends infer MiddlewareValues
        ? MiddlewareValues extends Middleware<infer DispatchExt, any, any>
          ? DispatchExt extends Function
            ? DispatchExt
            : never
          : never
        : never
    >
  : never

type UnionToIntersection<U> = (U extends any
? (k: U) => void
: never) extends (k: infer I) => void
  ? I
  : never

const middlewares = getDefaultMiddleware<RootState>();
type ResultingType = DispatchForMiddlewares<typeof middlewares>
```

**Comment by StagasaurusRex** [comment]
`ThunkDispatch<CombinedState<{auth: AuthState}>, null, AnyAction> & ThunkDispatch<CombinedState<{auth: AuthState}, undefined, AnyAction>`

**Comment by phryneas** [comment]
Hm. That *does* look right, so `DispatchForMiddlewares` is working for you.

So 
![store](https://user-images.githubusercontent.com/4968936/78723096-66c6a500-78f0-11ea-869e-5d65e31b8258.png) is definitely giving you `Dispatch<AnyAction>` as `typeof store["dispatch"]`?

**Comment by StagasaurusRex** [comment]
Yup.

<img width="407" alt="Screen Shot 2020-04-07 at 5 36 55 PM" src="https://user-images.githubusercontent.com/4968936/78725951-6c26ee00-78f6-11ea-901d-5e96a17fac1f.png">

**Comment by phryneas** [comment]
This is highly irritating. My last idea would be that you do not have `strict: true` in your `tsconfig.json` and TypeScript thus acts a bit unpredictable?

Can't really think about anything else without a reproduction, sorry.

Also, I'm heading to bed now. If you find a way to make this reproducible, I'll try to take a look tomorrow.

**Comment by StagasaurusRex** [comment]
I appreciate your help. When I copy all my code to a codesandbox it infers the type correctly so I've no idea whats going on. I will probably just explicitly type my AppDispatch and move on.

Thanks again.

**Comment by StagasaurusRex** [comment]
Also I do have `strict: true` set in my tsconfig

**Comment by Neodern** [comment]
Exactly same problem here. :( 
Only solution is : `export type AppDispatch = ThunkDispatch<AppState, null, AnyAction>;`
But it smells more as a workaround than a real solution. :( 

<img width="774" alt="Capture d’écran 2020-05-13 à 21 06 09" src="https://user-images.githubusercontent.com/5598626/81854048-9dca4f00-955d-11ea-91b7-f9f0c08e5920.png">

**Comment by phryneas** [comment]
@Neodern could you please open a new issue for this - possibly with a reproduction repo/codesandbox or at least with your `configureStore` call and the ways you tried to extract `AppDispatch`?

Also, if you are using additional middlewares and spread, to combine them, that might have to do with https://github.com/reduxjs/redux-toolkit/issues/552

**Comment by Neodern** [comment]
Thanks you for the link to #552. Solved my problem !
A bit verbose to have extra types for redefined and wrap `getDefaultMiddleware` but it works, thanks ! 

spread & additional middlewares seems to be a nightmare for typing. :( 


```js
const defaultMiddleware = getDefaultMiddleware<AppState, DefaultMiddlewareOptions>({
  serializableCheck: {
    ignoredActions: ["notifications/addNotification"],
  },
});

const wrappedDefaultMiddleware = defaultMiddleware as AsCustomReadonlyArray<typeof defaultMiddleware>;

const store = configureStore({
  reducer,
  middleware: Array.from(wrappedDefaultMiddleware.concat(tokenMiddleware)),
  preloadedState: {},
  enhancers: []
});

export type AppDispatch = typeof store.dispatch;
```

**Comment by phryneas** [comment]
Yeah, spread just widens types, which is really not optimal. I'm probably gonna add those helpers, but for now you're gonna have with the workaround, sorry.
