### ISSUE TITLE
Extending createAsyncThunk with Typescript

### ISSUE THREAD

**Issue by dagstuan** [reduxjs/redux-toolkit#486]
I'm trying to write a generic extension of `createAsyncThunk` in Typescript, so that I dont have to repeat the thunkApiConfig every time. I'm trying to write it such as this:

```ts
type ThunkApiConfig = {
  dispatch: MyDispatch:
  rejectValue: MyErrorType;
};

export const createAppThunk = <Returned, ThunkArg = void>(
  type: string,
  payloadCreator: (
    arg: ThunkArg,
    thunkAPI: GetThunkAPI<ThunkApiConfig>,
  ) =>
    | Promise<Returned | RejectWithValue<GetRejectValue<ThunkApiConfig>>>
    | Returned
    | RejectWithValue<GetRejectValue<ThunkApiConfig>>,
) => createAsyncThunk<Returned, ThunkArg, ThunkApiConfig>(type, payloadCreator);
```

However, this doesnt work since the types `GetThunkAPI`, `RejectWithValue`, and `GetRejectValue` are not exported. Is there any other recommended way of doing this? Or can you export the types needed to extend `createAsyncThunk`?

**Comment by dsyncerek** [comment]
I encountered the same problem.

In `react-redux` types there is exported interface `DefaultRootState` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux/index.d.ts#L47) which can be augmented by users to add default types for the root state. So instead of reapeating `useSelector<AppState, ...>()` or creating generic wrapper, we can write once:
```typescript
declare module 'react-redux' {
  interface DefaultRootState extends AppState {}
}
```

It would be great if something similar will be possible in `@reduxjs/toolkit`. I mean:
```typescript
declare module '@reduxjs/toolkit' {
  type AsyncThunkConfig = {
    state?: AppState;
    dispatch?: AppDispatch;
    extra?: null;
    rejectValue?: HttpError;
  }
}
```

**Comment by phryneas** [comment]
Hmm. While most everything else would usually stay the same, especially the `rejectValue` would be something that could change on a `asyncThunk` to `asyncThunk` basis, so adding a `DefaultAsyncThunkConfig` that could be overwritten by module augmentation would imho be the wrong approach.

Also note that the `react-redux`-types are community-driven on DefinitelyTypes and this is the first time I hear of that type - this has probably been added without any of the redux maintainers even noticing. I'm not really sure if I'm a fan of that, to be honest.

But back on topic: I'm evaluating what we could do to make this possible.

I could agree on exporting `GetThunkAPI`, but I'm a bit hestitant on exporting `RejectWithValue` and `GetRejectValue` as I'd like to keep these implementation details.

What would you think about exported types (in addition to `GetThunkAPI`) like
```ts
export type AsnycThunkPayloadCreatorReturnValue<
  Returned,
  ThunkApiConfig extends AsyncThunkConfig
> =
  | Promise<Returned | RejectWithValue<GetRejectValue<ThunkApiConfig>>>
  | Returned
  | RejectWithValue<GetRejectValue<ThunkApiConfig>>

export type AsyncThunkPayloadCreator<
  Returned,
  ThunkArg = void,
  ThunkApiConfig extends AsyncThunkConfig = {}
> = (
  arg: ThunkArg,
  thunkAPI: GetThunkAPI<ThunkApiConfig>
) => AsnycThunkPayloadCreatorReturnValue<Returned, ThunkApiConfig>

```

I believe that should enable api-wrapping like in the first post.

**Comment by Nimdis** [comment]
Faced the same issue today. It would be great to have an official solution for the issue.
@phryneas looks great

**Comment by markerikson** [comment]
Should be resolved by https://github.com/reduxjs/redux-toolkit/releases/tag/v1.3.5 .

**Comment by smrq** [comment]
I have the same use case; however, as far as I can tell, there's no way to get a type for the *return* type of `createAsyncThunk`.  (In the above example, this would mean that you can't declare a return type for `createAppThunk`; the compiler has to infer it.)

This is a problem for me specifically because I'm trying to declare overloads for my equivalent function to `createAppThunk`, and the typings for these overloads have to have a declared return type because they can't be inferred.  But I imagine it would come up in any context in which you have to declare the full type of a wrapper around `createAsyncThunk`.

**Comment by markerikson** [comment]
@smrq not sure what you're trying to do there, specifically.  Can you open a new issue and provide some concrete examples?

**Comment by trickeyd** [comment]
Having trouble with this - ben trying to make a wrapper too, but keep getting type errors. 
Almost there, apart from any thunk that doesn't require a payload says it s expecting one argument.
Any chance someone provide an example of a wrapped createAsyncThunk the latest types?

**Comment by phryneas** [comment]
@trickeyd could you link a few typescript playgrounds to see what you are trying to do and what errors you are getting?
"wrapping `cAT`" could mean so many different ways of wrapping that I doubt that any example here would help you otherwise

**Comment by trickeyd** [comment]
Hey @phryneas.

Thanks I really appreciate you taking the time to answer

I'm not really sure how to use a playground with a in conjunction with a lib like redux-toolkit, but I can show you exactly what I am trying to achieve. It is similar to what others are doing in various threads I've seen, tho the exact implementation still alludes me. 

```
export const createMyOwnAsyncThunk = <Returned, ThunkArg = any>(
  type: string,
  thunk: AsyncThunkPayloadCreator<Returned, ThunkArg>,    // <-- very unsure of this - have tried many things here
): AsyncThunk<Returned, ThunkArg, ThunkAPIConfig> => {
  return createAsyncThunk<Returned, ThunkArg, ThunkAPIConfig>(
    type,
    async (arg, thunkAPI) => {
      try {
        // do some stuff here that happens on every action
        return await thunk(arg, thunkAPI)
      } catch (err) {
        // do some stuff here that happens on every error
        return thunkAPI.rejectWithValue(null)
      }
    },
  )
}
```

It works fine - I just don't seem to have the typings down properly. As I said, the only side effect at the moment is that when i create a thunk with this, which requires no payload i get the following

`dispatch(myThink()). // expected 1 argument but got none`

**Comment by phryneas** [comment]
@trickeyd see [this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMZQKYEMaoIIGcCeAdkgCoAWAroQNYA0eRplNACuvgDYToAmAwmkzR6BYuSrUAvnABmUCCDgByAAJoeFAB4ArXAHoYECB2rAYSgFAXghLFBnokqOOJrYWAST4RCM4AHNESStUTUhYOCQfXHgUDCwAWXwAeQB3QgYxZmo4AF44AB4AJVQYCihCVB5aF2zsKED89EJ8AD4ACgs4OBh8MFQALjgYqBt-Wi6e7KHMpgk2Tm5+QUMoYtLyyuraiXr-VpruuD09QoBaM7gAN1QofDgqXHLnCBkp4Fw4S7J0G57RqpwEDNe4wMhjT5kW6oCwAShmojmNHWZQqVRqrmoewxdU83l8AVaeSJCEmaFRhEiKxwiMxKM26J2bgaON2eJ8fn2nSOPT6qAmPPQiLg7XQLKmbI8sOJiEmPJgd1lPJ5JzgPAgwwUzhiFBkbyhaCmmDgPzA-UInx8cFQN0VjhgwB8cuV5M2cHQqXQZglNFF4rBkthzu60iQmCQZBFtyg0tJyqOqvVmpA2rKepN0KN8FN5stlJtt3u0egwaOroqPqxngAdGhtKgkDAAOpmMgANXQHAoqHahAoHA4QfjwR5kgFcCDwQsUQt8BA+ExeSp8VQSTSGVp2XaACIZEZtzV2tLckTd-ugxZVWCPnAb4Y4AAjZyhfqNxn4CAUNXAHhwQgQeBen6d0Gh6DUAAMrggH9wIsedMSPKwZxiIEF2yAAmJc4kwVcUnSWY6RGMZaCgn8OjPCADxFY9Tz3SiL3gjCjyAA)

**Comment by trickeyd** [comment]
Aaaaah of course! Amazing thanks!

**Comment by marcusjwhelan** [comment]
@trickeyd where do you get that "Returned" type and "ThunkArg" type from?

**Comment by phryneas** [comment]
> @trickeyd where do you get that "Returned" type and "ThunkArg" type from?

Those are placeholders for what you want to specify as the return value of the thunk and the argument to pass into the thunk. Replace them in your code.

**Comment by fernando140alto** [comment]
That playgroud saved my life. Thank you ! @phryneas

**Comment by Rinta01** [comment]
I've been trying to solve the same problem by either extending the library's types or creating my own version of the function alike @phryneas answer.
And then I stumbled upon [this section](https://redux-toolkit.js.org/usage/usage-with-typescript#defining-a-pre-typed-createasyncthunk) in RTK documentation. So global typing of `createAsyncThunk` was basically resolved since RTK@1.9.
---
However I have still yet to find a viable solution for global error handling instead of writing `try-catch` blocks in every single thunk

**Comment by markerikson** [comment]
@Rinta01 what do you mean by "global error handling" ?

**Comment by Rinta01** [comment]
@markerikson something like https://redux-toolkit.js.org/rtk-query/usage/error-handling but for createAsyncThunk.

**Comment by EskiMojo14** [comment]
if you're talking about the middleware, you can use the code there - the point is that RTKQ *uses* cAT so you can use the [async thunk matchers](https://redux-toolkit.js.org/api/matching-utilities).
