### ISSUE TITLE
How to get derived state or computed state like in easy-peasy

### ISSUE THREAD

**Issue by nainardev** [reduxjs/redux-toolkit#487]
for example i want to get length of an array directly from store

**Comment by markerikson** [comment]
You'd use the standard React-Redux APIs for pulling state into a component (`connect` and `useSelector`), and either return the array or just the length.  If you need to optimize it, you'd do so with selectors.  See [the React-Redux docs](https://react-redux.js.org/) and the Redux docs page on [Computing Derived Data](https://redux.js.org/recipes/computing-derived-data).

**Comment by nainardev** [comment]
Wow @markerikson thanks your help to this community, you help everyone learn Redux. Thank you 😊

**Comment by geekact** [comment]
I have getting a great idea to implement `computed` state which compatible with ES5 based on redux and react-redux, it works both hooks and class component, move to [here](https://github.com/foca-js/foca/tree/master/src/reactive) to have a look.
