### ISSUE TITLE
Couldn't work with 'immerable' custom Class

### ISSUE THREAD

**Issue by Aldeee** [reduxjs/redux-toolkit#490]
It seems that there are few problems with immerable Classes.

Imagine following class

```
import { immerable } from 'immer';

export class DocLoading {
  [immerable] = true;
  constructor(data = {}) {
    this.documentId = data.documentId;
  }
  setDocumentId(docId) {
    this.documentId = docId;
  }
}
```

This class is used as initialState for the following reducer

```
createSlice({
  name: 'documentLoading',
  initialState: new DocLoading(),
  reducers: {
    setDocumentId(state, { payload }) {
      state.setDocumentId(payload);
    }
  }
})
```

I see two issues:
- I have to turn `serializableCheck` off
- when i try to dispatch following action
```
dispatch({ type: 'documentLoading/setDocumentId', payload: 'documentId1' });
```
I have got an error from `ImmutableStateInvariantMiddleware`
`A state mutation was detected inside a dispatch, in the path: 'documentViewer.documentLoadingMetaData.documentId'. Take a look at the reducer(s) handling the action {"type":"documentViewer/setDocumentId","payload":"doc123"}. (http://redux.js.org/docs/Troubleshooting.html#never-mutate-reducer-arguments)
`

Please let me know if I'm doing something wrong or let me few tips how to deal with immerable custom Classes in RTK.

Thx

**Comment by phryneas** [comment]
Generally speaking, `immerable` classes are (like any classes in the state) something we'd advise against, as they are still not seriallizable/deserializable without additional workarounds and will likely break tooling like the redux-devtools and integration with a lot of middlewares.

That said, the example you are giving calls `createReducer` with the syntax of `createSlice`, so I don't really know what you have going on there. Could you please provide a working reproduction (like a CodeSandbox)? Then I could take a look. But no guarantees, this is not really in the "supported use case" of the library from what I can see.

**Comment by Aldeee** [comment]
@phryneas thx for you reply, I meant `createSlice`, updated in the first post

**Comment by markerikson** [comment]
Yeah, this isn't something we support - [we strongly recommend against keeping non-serializable values in your state](https://redux.js.org/style-guide/style-guide#do-not-put-non-serializable-values-in-state-or-actions).

The serializability middleware is separate than Immer processing things in a reducer, so that's why you're seeing the warning.

**Comment by Aldeee** [comment]
@phryneas you've provided valid example. It seems that I had an issue with `redux-devtools` while trying dispatch an action within it. Thx for clarification. Code works as expected [in your's experiment](https://codesandbox.io/s/blue-cookies-k9pl6?file=/src/index.tsx).

@markerikson could you please explain what is the best place within RTK to use Data Models (ES Classes)? I would like to use it like in the example above. But also I could do this by using in the selector. Is it ok, or could you suggest better place?

```
const getDocumentLoading = (state) => state. documentLoading;
const documentLoadingSelector = createSelector(
  getDocumentLoading,
  (documentLoading) => new DocLoading(documentLoading);
)
```

**Comment by markerikson** [comment]
As I said, the right approach is to _not_ use classes for data, period.  This is true for both React and Redux in general.

**Comment by phryneas** [comment]
When using classes, you're esentially duplicating everything - the accessors/getters of your class are duplicating what already happens in your selector, while the setters are duplicating what aready happens in reducers. You're just introducing additional points of indirection and your code becomes even more spread out through your codebase.

**Comment by Aldeee** [comment]
@markerikson @phryneas thx guys. Got it.
