### ISSUE TITLE
Outdated documentation of immutable invariant options on the homepage

### ISSUE THREAD

**Issue by ntamas** [reduxjs/redux-toolkit#491]
The [API reference on the homepage](https://redux-toolkit.js.org/api/getDefaultMiddleware#api-reference) currently states that the paths to ignore in the immutable state middleware can be configured with the `ignore` key. This is not true; when the middleware was merged in the most recent version, the key was renamed to `ignoredPaths`, relying on the old `ignore` key has no effect. (The new middleware also has a `warnAfter` key for what it's worth). The API reference on the homepage should be updated to avoid confusion. Also, it would probably be a good idea to treat `ignore` as an alias for `ignoredPaths` in order not to break backwards compatibility in a minor release.

Thanks a lot in advance!

**Comment by markerikson** [comment]
Could you file a PR to update the docs accordingly?

And yeah, looks like the PR from @msutkowski (#381) had the new key name and I didn't catch that that was different than the original lib.  It'd be great if you could file a PR to fix that as well.

**Comment by msutkowski** [comment]
@ntamas Very sorry about that! I was intending to keep the API surface of the middleware consistent and forgot to alias it 🤦‍♂️

**Comment by ntamas** [comment]
Thanks guys, you were faster than me - I was planning to send a PR tonight after the kids went to bed.
