### ISSUE TITLE
How to set initial value for createEntityAdapter API

### ISSUE THREAD

**Issue by ouweiya** [reduxjs/redux-toolkit#493]
`getInitialState` how to set some initial values,
I did this below but it didn't work.

```js
const sizeAdapter = createEntityAdapter();

export const { reducer, actions } = createSlice({
  name: 'responseSize',
  initialState: sizeAdapter.getInitialState([
    {
      id: 'a',
      todo: 'one'
    },
    {
      id: 'b',
      todo: 'two'
    }
  ]),
  reducers: {
    changeSize: sizeAdapter.updateOne
  }
});
```

![Snipaste_2020-04-12_00-45-30](https://user-images.githubusercontent.com/28357731/79049569-fce32e00-7c56-11ea-92df-292e113e514c.png)

**Comment by msutkowski** [comment]
I think what you're looking for is `preloadedState` in [configureStore](https://redux-toolkit.js.org/api/configureStore#preloadedstate). The usage of `getInitialState()` is for adding additional properties to the reducer and setting their default values like:

```js
adapter.getInitialState({ loading: '', errorMessage: '' })
```

**Comment by ouweiya** [comment]
But I cannot use the `CRUD` method to manipulate the data outside of these `Entity`, for example: addOne, addMany, removeOne, updateOne ... etc.

**Comment by markerikson** [comment]
The `getInitialState()` function just returns an empty `{ids: [], entities: {}}` object.

You could use the CRUD methods to further manipulate that outside the slice, then use the result as the initial state:

```js
const emptyInitialState = sizeAdapter.getInitialState();
const filledState = sizeAdapter.upsertMany(emptyInitialState, items);

const sizeSlice = createSlice({
  name: "responseSize",
  initialState: filledState,
  reducers: {}
})
```

**Comment by EskiMojo14** [comment]
As of [v2.2.0](https://github.com/reduxjs/redux-toolkit/releases/tag/v2.2.0), you can now pass a second parameter to getInitialState, which then calls `setAll` for you:

```js
const filledState = sizeAdapter.getInitialState(undefined, items)
// is essentially
const filledState = sizeAdapter.setAll(sizeAdapter.getInitialState(), items)
```
