### ISSUE TITLE
Can I translate the official document into Korean?

### ISSUE THREAD

**Issue by SoYoung210** [reduxjs/redux-toolkit#495]
If possible, would it be possible in the form of https://ko.redux-toolkit.js.org/?

Currently, im proceeding with github pages in our personal store.
> link: https://soyoung210.github.io/redux-toolkit/introduction/quick-start

**Comment by markerikson** [comment]
Sure, go ahead!

Supposedly Docusaurus has support for translations, but we've never done anything with that, so doing it separately for now is fine.

**Comment by SoYoung210** [comment]
@markerikson  Thx! 


First of all, I'll do the translation, and once it's done, I'll share it with the redux team! 

If you want, you can close this issue. 🙂

**Comment by Mazuh** [comment]
Looking forward of doing the same for Portuguese. Keep the thread updated, @SoYoung210! :smile:

**Comment by SoYoung210** [comment]
I translated quick start, basic and intermediate tutorials. :)
