### ISSUE TITLE
prepare method for extraReducers to add custom meta datas ? 

### ISSUE THREAD

**Issue by Neodern** [reduxjs/redux-toolkit#496]
Hello, 

Today, we can use `prepare` method to add some extra meta datas from the actionCreator into the reducer. 
Is there a way to do this from createAsyncThunk ? 

```javascript
export const fetchOrganization = createAsyncThunk(
    "organization/fetchOrganisation",
    async (userId: string, thunkAPI: ThunkApiArgs) =>   // <-- i need userId from this line later
        await fetch(endpoint);
);

export default createSlice({
    name: "organization",
    initialState: { byId: {}, isLoading: false },
    reducers: {},
    extraReducers: (builder) => {
        builder
            .addCase(fetchOrganization.pending, (state, action) => {
                state.isLoading = true;
            })
            .addCase(fetchOrganization.fulfilled, (state, { payload }) => {
                state.isLoading = false;
                state.byId[payload.content.id] = payload.content;
            })
            .addCase(fetchOrganization.rejected, (state, { payload }) => {
                state.isLoading = false;
                state.byId[userId] = null; // <-- I need the userId from createAsyncThunk here.
            });
    },
});
```
I had a way to do this with redux-api-middleware with meta datas. Is there a way to do this with RTK ? `prepare` seems to be the way for classic reducers but not implemented for extraReducers. So i need your help here. :/ 

Sorry if I missed something, and sorry for my english and thanks you for your amazing work. :)

**Comment by phryneas** [comment]
I believe `action.meta.arg` might be the value you are looking for.

**Comment by Neodern** [comment]
Thanks you for your answer. :) 

Yes for sure, but can we populate it inside `createAsyncThunk `  ?
I didn't find a way to do this.

**Comment by phryneas** [comment]
You can always return a different value to get a different `fulfilled` payload, or you can use `thunkApi.rejectWithValue` to modify your `rejected` payload.

The `pending` action is dispatched before your `payloadCreator` is run, so no way to modify that.

**Comment by Neodern** [comment]
oh, great ! 
I hoped i could do this without to have to modify the original payload. But i will do this. thanks you for your help. :)

**Comment by markerikson** [comment]
Yeah, this is part of the tradeoff of using an abstraction like `createAsyncThunk`.  It does a lot of work for you, but that means the customization is limited.
