### ISSUE TITLE
Seems some of files aren't processed to be es5 compatible

### ISSUE THREAD

**Issue by deser** [reduxjs/redux-toolkit#499]
Hey, my webpack build with uglifyJS fails at:
```
// A type of promise-like that resolves synchronously and supports only one observer

const _iteratorSymbol = /*#__PURE__*/ typeof Symbol !== "undefined" ? (Symbol.iterator || (Symbol.iterator = Symbol("Symbol.iterator"))) : "@@iterator";

const _asyncIteratorSymbol = /*#__PURE__*/ typeof Symbol !== "undefined" ? (Symbol.asyncIterator || (Symbol.asyncIterator = Symbol("Symbol.asyncIterator"))) : "@@asyncIterator";
```

**Comment by markerikson** [comment]
That's not enough information to go on.  What kind of error are you seeing?

**Comment by deser** [comment]
For some reason development version is taken instead of production when I'm building my project with webpack (in production mode). All the packages have latest version. I suspect something's wrong in dist/index.js file:
![image](https://user-images.githubusercontent.com/3010698/79128373-121da100-7dac-11ea-85d0-91706472847d.png)

I can confirm that react is build using production file in the same build

**Comment by markerikson** [comment]
Can you create a repo that reproduces the issue?

**Comment by deser** [comment]
here you go: https://github.com/deser/redux-toolkit-issue

Instructions:
1. Run `npm run build`
2. See that in `dist/main.js` development version of  `@reduxjs/toolkit` is included

**Comment by phryneas** [comment]
This is not bundling one of the pre-transpiled CommonJS modules, but the ESM module. That is not transpiled on purpose, as transpiling ESM would defeat the purpose of having a clean start with a non-backwards-compatible new technology. 
It's up to your bundler to either use the `main` entrypoint (CommonJS) or use the `module` entrypoing (as it currently does) and transpile those down to the desired target.

**Comment by deser** [comment]
Hm, I'm looking into esm module and seems it is transpiled incorrectly:
![image](https://user-images.githubusercontent.com/3010698/79196333-9158b680-7e38-11ea-93eb-c1bf7a54be3a.png)

See that everywhere there is `var` but just in one place there is `const`. Webpack, seems, doesn't transpile imported node_module using babel

**Comment by phryneas** [comment]
The ESM module *is not transpiled* except for translating it from TypeScript to modern JavaScript.

You'll have to transpile ESM modules for *most libraries* yourself *to your target*, and you'll have to configure your webpack to do that.

The point is to deliver one version of the library that you can transpile to the target you want to, potentially gaining 50% of size when you only target a modern browser and don't need most of the backwards-compatible workarounds that eat up size & performance.

That an unconfigured webpack prefers the ESM and does not transpile it is unfortunate, but on the other hand, you don't have any transpiler for your own code in place that could even do that.

**Comment by deser** [comment]
OK thanks a lot for explanation!

**Comment by phryneas** [comment]
Just for completeness: this is how create-react-app transpiles all dependencies:

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L447-L485
