### ISSUE TITLE
How to deal with discriminated union types in createReducer / createSlice?

### ISSUE THREAD

**Issue by C-Higgins** [reduxjs/redux-toolkit#505]
```typescript
type State = {something: number} &
  ( {
    state: "loading"
    result: null
    error: null
  }
  | {
    state: "error"
    result: null,
    error: any
  }
  | {
    state: "done"
    result: Result[]
    error: null
  })

createReducer({} as State, {
  setLoading: (store, action) => {
    store.state = "loading"
    store.result = null
    store.error = 'oops' // this is allowed
  }
})
```

Am I right in thinking you cannot use immer for this purpose and must return a new state, with the typical spread pattern, or is there a better way?

**Comment by phryneas** [comment]
Unfortunately there's not really something else you can do - TypeScript expects the object to always have the correct shape so you cannot really switch from one to the other - in this case you probably have to stick to object spread.
