### ISSUE TITLE
Passing an immer draft to a createReducer reducer returns no changes

### ISSUE THREAD

**Issue by AndrewCraswell** [reduxjs/redux-toolkit#508]
I'm building a library that wraps existing reducers and provides change rollback functionality via Immer patches. This has been working great with Redux, except I've just realized that it doens't work with reducers that were created with `createReducer()` from Redux Toolkit.

```typescript
      function injectImmer(state: IEndpointState & State, action: AnyAction) {
        const result = produce(state, (draft: any) => {
          reducer(draft, action);
        }, (patches, inverse) => {
          // Library is listening for these patches...
          //   but none are received when using Redux Toolkit reducers
        });

        return result;
      }

      rootReducer(injectImmer(state, action), action);
```

I'm taking the reducer, wrapping it in a `produce` statement, and passing the `draft` to the `createReducer` reducer. The result I get back from the reducer has no changes, even though I can debug and see that the reducer executed, and changes were made.

Here is the relevant section in the `createReducer.ts` file:

```typescript
  return function(state = initialState, action): S {
    return createNextState(state, (draft: Draft<S>) => {
      const caseReducer = actionsMap[action.type]
      return caseReducer ? caseReducer(draft, action) : undefined
    })
  }
```
[[createReducer.ts; line 111](https://github.com/reduxjs/redux-toolkit/blob/master/src/createReducer.ts#L111)]

It doesn't seem like this block is checking if the `state` passed to this function `isDraft(state)`, although it is being checked in other areas of the toolkit:

```typescript
    if (isDraft(state)) {
      // we must already be inside a `createNextState` call, likely because
      // this is being wrapped in `createReducer` or `createSlice`.
      // It's safe to just pass the draft to the mutator.
      runMutator(state)

      // since it's a draft, we'll just return it
      return state
    } else {
      return createNextState(state, runMutator)
    }
```
[[state_adapter.ts; line 26](https://github.com/reduxjs/redux-toolkit/blob/a1e8becbb2e4653d721bdc1d2363a45562c526a2/src/entities/state_adapter.ts#L26)]

Unfortunately this is a blocker for my release in the current state.

**Comment by markerikson** [comment]
What kind of change in behavior are you looking for, here?

**Comment by AndrewCraswell** [comment]
It should be possible to nest producers without Redux Toolkit swallowing the changes. I can propose a PR change, but there are some typing issues that I will need advice on.

**Comment by markerikson** [comment]
I'd be open to a PR that alters `createReducer` to do some kind of `isDraft` check,  yeah.

**Comment by AndrewCraswell** [comment]
Yeah, I think that would be all that is necessary. I've submitted PR #509 to get some advice on the typings.
