### ISSUE TITLE
Property 'then' does not exist on type 'AsyncThunkAction '

### ISSUE THREAD

**Issue by mfabre42** [reduxjs/redux-toolkit#517]
Hello there,

I'm using redux-toolkit since yesterday and in the process of refactoring large parts of my app.

In the process I found a bug, or at least a missing type because I have the error "Property 'then' does not exist on type 'AsyncThunkAction '" when I use .then after dispatching a createAsyncThunk.

```typescript
export const SomeService=
{
    async deleteSome(id): Promise<boolean>
    {
        // don't know why we use get here but same probleme everywhere
        return AjaxService.get(`api/${id}`);
    }
}
```

```typescript
// same problem whether I type myself 
// or if I let createAsyncThunk use the request type to guess the return type
export const deleteSome = createAsyncThunk<boolean, string>(
    'apiData/some/deleteSome',
    async (id) =>
    {
        const response = await SomeService.deleteSome(id);
        return response;
    },
);
```

```typescript
    const handleDelete = (e: MouseEvent, id: string): void =>
    {
        e.preventDefault();
        dispatch(deleteSome(id))
            // same problem with or without unwrapResult
            .then(unwrapResult)
            // work as intended and console the response
            .then((res) => console.error(res));
        }
    };
```

Pretty sure the problem come from the typing (maybe on my side though) since I can run the app and it works as intended (but ts checker say there is an error so I can't push it to prod obv).

My extraReducers are also aware of the returning promise type etc so I'm a bit lost there.

Thanks for the help.

**Comment by phryneas** [comment]
You have to type the `useDispatch` hook to correlate to the `Dispatch` type of your application, as the default `Dispatch` type does not include the `AsyncThunk` typings:
https://react-redux.js.org/using-react-redux/static-typing#typing-the-usedispatch-hook

**Comment by mfabre42** [comment]
Perfect, that was the problem.

Couldn't find any soluce since hours and I was sure it was my fault cause it would have been an obvious bug... 

Thanks a lot and sorry for the disturbance :).

**Comment by nishimura-yuji** [comment]
Sample code to solve this problem

```src/@types/redux-thunk/index.d.ts/index.d.ts```


```
import { ThunkAction } from 'redux-thunk'

declare module 'redux' {
  export interface Dispatch<A extends Action<any> = AnyAction> {
    <TReturnType, TState, TExtraThunkArg>(
      thunkAction: ThunkAction<TReturnType, TState, TExtraThunkArg, A>
    ): TReturnType
  }
}
```
