### ISSUE TITLE
Do we want to recommend the `no-param-reassign` eslint rule in the docs?

### ISSUE THREAD

**Issue by phryneas** [reduxjs/redux-toolkit#521]
I just had this idea when another user tried to assign to the `state` function argument.
There is actually an eslint rule for that:
[no-param-reassign](https://eslint.org/docs/rules/no-param-reassign)

I'd suggest we either add that rule as a recommendation somehwere in the docs or go even one step farther and create a [shareable config package ](https://eslint.org/docs/developer-guide/shareable-configs).

That way we could add some more recommended rules in the future.

I'm thinking of later-on adding a self-written eslint-typescript rule that disallows assigning to anything of the type `Draft` or something similar.

**Comment by markerikson** [comment]
Pretty sure that rule also forbids mutating `someParam.field = 123`, which doesn't work well with Immer.

**Comment by phryneas** [comment]
Only if you override the default configuration of `{ "props": false }` to `{ "props": true }`.
Over in https://github.com/immerjs/immer/issues/189, mwestrate essentially recommends the rule in its default config.

**Comment by elramus** [comment]
Long time user of redux here, new to RTK / Immer. Running into ESLint complaining that I'm reassigning state in createSlice. But this is fine though, right, because RTK is using `produce` under the hood? If so, how do you recommend using the `no-param-reassign` rule? I know you can do `ignorePropertyModificationsFor`, but in some cases I'd like to just completely rewrite state in the reducer, not just a property, for example if we're holding a loading on/off boolean. 

```
const searchingSlice = createSlice({
  name: 'searching',
  initialState: false,
  reducers: {
    setStatus: (state, action: PayloadAction<boolean>) => {
      state = action.payload  // Error
    },
  },
})
```

**Comment by markerikson** [comment]
Assigning `state =` never does anything useful.  All that does is change what the local variable `state` is pointing to, which is always a no-op.

If you want to return a completely new state value / replace the existing state, you need to actually return it: `return action.payload`.

**Comment by elramus** [comment]
Ohhh okay, thanks much.

**Comment by phryneas** [comment]
And that's *exactly* why I suggest recommending this eslint rule xD

**Comment by markerikson** [comment]
So what does it mean to "suggest" it in this case, exactly?  Where would we document that info?  How would we encourage people to do so?

**Comment by phryneas** [comment]
Hmm, that's the question.

Maybe in the style guide, hand-in-hand with the `immer` and `RTK` recommendations, and/or in the documentation for `createReducer` and `createSlice`?

**Comment by markerikson** [comment]
That could work, yeah.

**Comment by StuartMorris0** [comment]
I'm interested to know what the proposed solution/information to be in the style guide would be here.

If you use the standard eslint setup and use an example from RTK such as:
```
const issuesDisplaySlice = createSlice({
  name: 'issuesDisplay',
  initialState,
  reducers: {
    displayRepo(state, action: PayloadAction<CurrentRepo>) {
      const { org, repo } = action.payload
      state.org = org                                     // <-- Error
      state.repo = repo                                 // <-- Error
    },
```

You would get the reassignment errors on the `state.` lines. What is the proposed solution here? Thanks

**Comment by phryneas** [comment]
@StuartMorris0 that is most definitely not the standard eslint setup, as the `props` option to that rule defaults to `false`. 
Are you extending some overly restrictive eslint config like the airbnb config? (Which in my personal opinion has outlived it's usefulness and is not a good default).

A correct configuration would be just `no-param-reassign: "error"` or `no-param-reassign: ["error", { "props": false }]` (which is equalivalent)

**Comment by StuartMorris0** [comment]
You're right it is the airbnb extends causing the issue, I have reverted the rule to its default.
`"no-param-reassign": ["error", { "props": false }]`

**Comment by markerikson** [comment]
> Airbnb has outlived its usefulness and is not a good default

Yes, this, 💯 	:)

**Comment by StuartMorris0** [comment]
Does anyone know of any other good defaults I could review please?

**Comment by BenjiTheC** [comment]
> > Airbnb has outlived its usefulness and is not a good default
> 
> Yes, this, 💯 :)

If Airbnb rule set has outlived its usefulness, is there a newly recommended one? Thx!

**Comment by phryneas** [comment]
@BenjiTheC what about the defaults that ship with eslint?

**Comment by ackalhan** [comment]
What I normally do is

- All my reducers are in a single directory called reducers.
- Then I want to force the eslint to disable `no-param-reassign` for the `reducers` directory only.
- Then I create a new eslint config file(`.eslintrc.json`) inside the `reducers` directory, and add `"no-param-reassign": ["error", { "props": false }]` to it.

so the `.eslintrc.json` in `reducers` directory is like below

```
{
  "rules": {
    "no-param-reassign": ["error", { "props": false }]
  }
}
```

**Comment by markerikson** [comment]
Now covered in our docs:

https://redux-toolkit.js.org/usage/immer-reducers#linting-state-mutations

**Comment by stevedeighton** [comment]
l'm a bit late to the party but I create my slices with naming convention of `x.slice.ts`, then use an override to only apply this rule to slices:

`{
      "files": ["src/**/*.slice.ts"],
      "rules": {
        "no-param-reassign": "off"
    }
}`

**Comment by Luk-z** [comment]
> l'm a bit late to the party but I create my slices with naming convention of `x.slice.ts`, then use an override to only apply this rule to slices:
> 
> `{ "files": ["src/**/*.slice.ts"], "rules": { "no-param-reassign": "off" } }`

better solutions, update the docs with this logic ?

**Comment by MikelArnaiz** [comment]
> l'm a bit late to the party but I create my slices with naming convention of `x.slice.ts`, then use an override to only apply this rule to slices:
> 
> `{ "files": ["src/**/*.slice.ts"], "rules": { "no-param-reassign": "off" } }`

You should probably not turn off the rule completely, otherwise it won't warn you when reassigning `state`. What I have is:

```js
// @filename .eslintrc.js
module.exports = {
  ...
  overrides: [
      {
        files: ['scr/**/slice.ts'],
        rules: { 'no-param-reassign': ['error', { props: false }] },
      },
    ],
}
```
