### ISSUE TITLE
createAsyncThunk - pending fulfilled rejected

### ISSUE THREAD

**Issue by victorykong** [reduxjs/redux-toolkit#522]
version: @reduxjs/toolkit lastest

This will be a lot of redundant, whether there is a better way to write recommended~

![image](https://user-images.githubusercontent.com/50655436/80271409-87fe0280-86f2-11ea-8962-5d6e268cbe5c.png)

**Comment by markerikson** [comment]
Can you clarify what you're asking?  All I see is a screenshot of code.

What specifically are you trying to accomplish, or concerned about?

**Comment by victorykong** [comment]
How to encapsulate transformation or have similar middleware package to achieve such as only need to addCase once, will affect the pre-set loading and error equivalence in state, using useSelector in TSX can get the corresponding state value. The current situation is like the above screenshot, each createAsyncThunk needs to write three casereducers, thanks for your guidance~

**Comment by AndrewCraswell** [comment]
You are concerned about having to set the `isFetching` flag on/off? You can setup another reducer that handles just this, then have that reducer wrap this one.

**Comment by markerikson** [comment]
I'm not sure what the point of concern is here, exactly. 

You have three different things that are happening, and the state needs to be updated in three different ways.  So, three different reducer functions.

If you want to do the same thing for many different slice reducers, you may want to read through https://redux.js.org/recipes/structuring-reducers/reusing-reducer-logic .
