### ISSUE TITLE
Redux DevTools Extension freezes when view Actions

### ISSUE THREAD

**Issue by TrueWill** [reduxjs/redux-toolkit#524]
Working through the [basic tutorial](https://redux-toolkit.js.org/tutorials/basic-tutorial), I've found that Redux DevTools will freeze on Chrome on macOS when viewing a raw Action. This happens with both actions created with `createAction` and ones extracted from `createSlice`.

This appears to be the [Excessive use of memory and CPU](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Troubleshooting.md#excessive-use-of-memory-and-cpu) issue. Could the library create an action sanitizer to resolve this? There's a lot of extraneous detail on generated actions.

**Comment by markerikson** [comment]
That's not anything specific to RTK.  However, you can customize the default DevTools Extension setup by [passing any of the supported DevTools options to `configureStore`](https://redux-toolkit.js.org/api/configureStore#devtools).
