### ISSUE TITLE
Return 'type' prop in createAsyncThunk

### ISSUE THREAD

**Issue by alexispcode** [reduxjs/redux-toolkit#525]
I'm implementing a loading/error reducer to manage async states and I think it would be a good idea to return type property. This way I could use selectors like:

`// thunk`
`const login = createAsyncThunk('login', () => {})`
`// login.type --> 'login'`

`// selector`
`const isLoading = useSelector(selectLoading([login.type]));`

**Comment by phryneas** [comment]
`createAsyncThunk` dispatches three different actions with different types and all are already accessible. In your case:

`login.pending.type`, `login.fulfilled.type` and `login.rejected.type` which will be `login/pending`, `login/fulfilled` and `login/rejected`.

So you could use either of those. 

It might be an idea to also make `loading` itself accessible, but that's not really a `type` property as it has no correlating action. `login.name` might be a candidate, as we already use that for `createSlice`. @markerikson what do you think about that?

**Comment by markerikson** [comment]
I know there were a couple other requests for exposing that value.  I'm still not sure I see much of a real benefit to it, but I guess it doesn't hurt to add it?

**Comment by phryneas** [comment]
Just took another look at this. Since the returned thunk-actionCreator is a function, we cannot override it's `name` property. I'm still against using `type` here, since that would make it very easily confusable with a normal actionCreator (and people might accidentally use it in reducers, even though the created Thunk will never reach a reducer).

Any ideas/suggestions?

**Comment by markerikson** [comment]
`baseType`? `providedType`? `typePrefix`? `thunkName`?

**Comment by phryneas** [comment]
Hm. I like `typePrefix` and `thunkName` most :)
Preferences?

**Comment by markerikson** [comment]
Arbitrary decision: let's go with `typePrefix`.
