### ISSUE TITLE
Self-reference issues when attempting to provide ThunkApi parameter types.

### ISSUE THREAD

**Issue by ph3b** [reduxjs/redux-toolkit#526]
I'm following the documentation for providing types to the ThunkApi parameter [here](https://redux-toolkit.js.org/usage/usage-with-typescript#createasyncthunk), specifically this section:
```typescript
// From https://redux-toolkit.js.org/usage/usage-with-typescript#createasyncthunk
const fetchUserById = createAsyncThunk<
  // Return type of the payload creator
  MyData,
  // First argument to the payload creator
  number,
  {
    dispatch: AppDispatch
    state: State
    extra: {
      jwt: string
    }
  }
>('users/fetchById', async (userId, thunkApi) => {
  const response = await fetch(`https://reqres.in/api/users/${userId}`, {
    headers: {
      Authorization: `Bearer ${thunkApi.extra.jwt}`
    }
  })
  return (await response.json()) as MyData
})
```

 However, after piecing everything together I get the following error:
```
'store' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
```
I've made a simple reproduction in this [Codesandbox](https://codesandbox.io/s/epic-mirzakhani-ifupz). Am I missing something here? 

Thanks for your hard work on this project! So far it's been a great experience to use!

**Comment by phryneas** [comment]
This way you're getting a circular reference.

What seems to be working in this case is to wrap the builder callback into a method body so it has no return value.

```diff
const numberReducer = createReducer({ counter: 0 }, builder =>
+ {
   builder.addCase(fetchNumber.fulfilled, (state, action) => {
    state.counter = action.payload;
  })
+ } 
);
```

That way the method does not have the return value `Builder<StoreType>` and the circular reference goes away.

**Comment by ph3b** [comment]
Perfect! That did indeed solve it. Thank you! Here is an updated working [codesandbox ](https://codesandbox.io/s/wild-morning-g9gn1) if anyone else stumbles upon this.

**Comment by illuminist** [comment]
Specifying builder function return type to be `any` seems to work too.

```ts
const numberReducer = createReducer({ counter: 0 }, (builder): any =>
```

Advantage is it retains JS equivalent code as without function body, but only if you're cool with using `any` type, but type doesn't matter in this case anyway.
