### ISSUE TITLE
State changing to undefined value. I'm using redux-toolkit with redux-persist

### ISSUE THREAD

**Issue by higor21** [reduxjs/redux-toolkit#531]
I'm trying change my state in the **login** reducer, but after the `state.user = data.user` operation, the `console.log` prints _undefined_.

My authSlice:

```
import { createSlice } from '@reduxjs/toolkit';
import api from '../../config/api';

const authSlice = createSlice({
  name: 'auth',
  initialState: {
    user: null,
    token: '',
  },
  reducers: {
    async register(state, action) {
      console.log(action);
      await api
        .post('users', action.payload)
        .then(({ data }) => {
          state = data.data;
          console.log(state);
        })
        .catch((err) => {
          console.log(err);
        });
    },
    async login(state, action) {
      try {
        const { data } = await api.post('sessions', action.payload);
        console.log(state);
        state.user = data.user;
        console.log(state);
        state.token = data.token;
      } catch (err) {
        console.log(err.response && err.response.data.error);
      }
    },
  },
});

const { actions, reducer } = authSlice;

export const { register, login } = actions;
export default reducer;
```
My store:

```
import {
   configureStore,
   combineReducers,
   getDefaultMiddleware,
 } from '@reduxjs/toolkit';
 import { AsyncStorage } from 'react-native';
 import {
   persistReducer,
   persistStore,
   FLUSH,
   REHYDRATE,
   PAUSE,
   PERSIST,
   PURGE,
   REGISTER,
 } from 'redux-persist';
 
 import { authReducer, newsReducer } from '../features';

 const rootReducer = combineReducers({
   authReducer,
   newsReducer,
 });

 const persistConfig = {
   key: 'root',
   storage: AsyncStorage,
   whitelist: ['auth'],
 };

 const persistReducers = persistReducer(persistConfig, rootReducer);

 const store = configureStore({
   reducer: persistReducers,
   middleware: getDefaultMiddleware({
     serializableCheck: {
       ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
     },
   }),
 });

 export const persistor = persistStore(store);

 export default store;
```

In addition, when I configure my middleware property from configureStore to 
```
middleware: getDefaultMiddleware({
    serializableCheck: {
      ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
    },
}),
```
That prints the following error in my console:

![image](https://res.cloudinary.com/higor21/image/upload/v1588173540/fjbkdfycafijrrchtkds.png)

**Comment by phryneas** [comment]
Reducers have to be pure functions without side-effects. They can never be asynchronous, so this code cannot work.

If you want to do asynchronous actions, you need to use a middleware. A commonly used one is `redux-thunk`. In that context you might also want to take a look at `createAsyncThunk`.

**Comment by higor21** [comment]
Ok, I'll try to solve it here. Thanks for your tips!

**Comment by royhirakp** [comment]
"I get the value and data as "undefiled". "

import { createSlice } from "@reduxjs/toolkit";
import type { PayloadAction } from "@reduxjs/toolkit";
export interface CounterState {
  value: number;
  data: any[];
}
const initialState: CounterState = {
  value: 0,
  data: [],
};

const cartSlice = createSlice({
  name: "test",
  initialState,
  reducers: {
    addToCart: (state, payload) => {
      console.log(state, "state===state form text");

      console.log(state.data, "data===state form text");
      console.log(state.value, "value====state form text");
      console.log(payload, "paylode===state form text");
    },
  },
});
