### ISSUE TITLE
Is this bug?: createAsyncThunk

### ISSUE THREAD

**Issue by JaeYeopHan** [reduxjs/redux-toolkit#533]
## Description

i use `createAsyncThunk` in redux-toolkit!

like this:
```ts
const fetchUserInfo = createAsyncThunk(`${name}/fetchUserInfo`, async () => { /* */ });

const _ = createSlice({
  name,
  initialState,
  extraReducers: {
    [fetchUserInfo.fulfilled]: /* */,
    [fetchUserInfo.pending]: /* */,
    [fetchUserInfo.rejected]: /* */,
  },
});
```

But, i got this type error

![스크린샷 2020-05-04 오후 12 03 13](https://user-images.githubusercontent.com/17924127/80933571-4b6f8c80-8dff-11ea-8417-41aeef1bb676.png)

So,

```ts
  extraReducers: {
    [`${fetchUserInfo.fulfilled}`]: /* */,
    [`${fetchUserInfo.pending}`]: /* */,
    [`${fetchUserInfo.rejected}`]: /* */,
  },
```

is this bug?

### Reference

https://redux-toolkit.js.org/api/createAsyncThunk

**Comment by markerikson** [comment]
Please use the "builder callback notation" form of `extraReducers` to get correct type safety, per the docs:

https://redux-toolkit.js.org/usage/usage-with-typescript#type-safety-with-extrareducers

**Comment by JaeYeopHan** [comment]
@markerikson thanks for answer!

Is there any type infer support for the case of proceeding with object notation instead of builder callback notation?

**Comment by phryneas** [comment]
No, because TypeScript has no way of correlating a dynamic string to a type somewhere else in the code.
