### ISSUE TITLE
Documentation on testing extraReducers?

### ISSUE THREAD

**Issue by martpie** [reduxjs/redux-toolkit#535]
Hello 👋

I spent a lot of time reading the documentation and examples:

- https://redux-toolkit.js.org/tutorials/intermediate-tutorial#updating-the-todos-tests
- https://github.com/reduxjs/rtk-convert-todos-example/commit/b603312ddf55899e8a75522d407c40474948ae0b

Testing simple reducers is extremely easy and straightforward, but I could not find any indication on how to test `extraReducers` and in particular `createAsyncThunk`. Did I miss something? Or are those features I should not test?

Can I contribute to the docs somehow regarding this issue?

for some context, here is my slice:

```tsx
const addPerson = createAsyncThunk(
  'family/createPerson',
  async (payload: { person: Person }) => {
    const _id = nanoid();

    const newPayload = {
      _id,
      person: payload.person,
    };

    return newPayload;
  },
);

const familySlice = createSlice({
  name: 'family',
  initialState,
  reducers: {
    removePerson: (/* ... */) => {
      // ...
    },
    editPerson(/* ... */) {
      // ...
    },
  },
  extraReducers: (builder) => {
    builder.addCase(addPerson.fulfilled, (state, action) => {
      const { person, _id } = action.payload;

      state.personsCreated++;
      state.persons[_id] = person;
    });
  },
});
```

_sidenote: if it feels unnecessary, I am creating a thunk because I need to get back the person ID in order to do a redirection based on this ID._

**Comment by markerikson** [comment]
All the case reducers in both the `reducers` and `extraReducers` fields will get added into `familySlice.reducer`.  So, you can test that logic as per any other Redux reducer:

```js
const actual = someReducer(testState, testAction);
expect(actual).toEqual(expectedState);
```

It's up to you how you generate `testState`, `testAction`, and `expectedState`, including either writing the actions by hand or using action creators to generate them.

**Comment by martpie** [comment]
So for other people reading the issue, it looks like what I was looking for is the "sub-actions" created by `createAsyncThunk` + https://github.com/reduxjs/redux-toolkit/issues/494

```
const action = familyActions.addPerson.fulfilled(
      {
        person: person1,
        _id: 'someRandomString',
      },
      '',
      { person: person1 },
    );

    expect(familySlice.reducer(
        someInitialState,
        action,
    )).toStrictEqual({
        // ...
    });
```

**Comment by tim-rohrer** [comment]
@martpie, can you elaborate on what parameters you're passing to `familyActions.addPerson.fulfilled`?

**Comment by martpie** [comment]
So from what I understand, `.fullfilled` create an action creator based on the data you passed to it.

The TS Typings and Docs are really unclear at this subject.

- the first argument is the returned success value of your thunk (in my case, a `Person` with an additional `_id` property)
- the second argument is apparently a string (I have no idea what id does)
- the third param is something for the `ThunkArg`, again, I have no idea what it does, but it was typed for me already.

Sorry, I am not of a big help, but some internals of the toolkit are quite hard to get.

**Comment by phryneas** [comment]
If you take a look at the source, it's a `createAction` call with a `prepare` argument:

https://github.com/reduxjs/redux-toolkit/blob/2712541e4be5319137f6f063582338ca2c0a0b18/src/createAsyncThunk.ts#L243-L251

So the signature of the final action creator is:
```
function fulfilled(result: Returned, requestId: string, arg: ThunkArg): {
  type: string
  payload: Returned
  meta: { arg: ThunkArg, requestId: string }
}
```

Where `arg` is what you initially passed into the `asyncThunk` and `requestId` is a string that is unique for the whole pending/fulfilled/rejected triplet.

**Comment by markerikson** [comment]
When in doubt, read the source :)

**Comment by bilsak18** [comment]
Here is a way you could test the `fulfilled` sub-action of your `family/createPerson`  action.

`const addPersonPayload = {
}`

**Comment by bilsak18** [comment]
Here is a way you could test the `fulfilled` sub-action of your `family/createPerson` action.

```javascript
import reducer from 'path/to/your/family/slice'

const addPersonPayload = {
  person: person1,
  _id: 'someRandomString'
}
const addPersonArg = {
  person: person1
}

// Mock/Stub your addPerson function to return/resolve the addPersonPayload when called with addPersonArg as its argument
// I used Cypress, you can use whatever tool to mock/stub your function
// Here's how it would look like with Cypress
const addPersonStub = cy.stub({addPerson}, 'addPerson'}).withArgs(addPersonArg).resolves(addPersonPayload)

const nextState = reducer(
  someInitialState,
  store.dispatcher({
    type: 'family/createPerson/fulfilled',
    payload: await addPersonStub(addPersonArg)
  })
)

const rootState = {family: nextState}

expect(someSelector(rootState)).to.equal(addPostPayload) // Chai's to.equal syntax that Cypress uses
```

**Comment by gonwms** [comment]
> So for other people reading the issue, it looks like what I was looking for is the "sub-actions" created by `createAsyncThunk` + #494
> 
> ```tsx
> const action = familyActions.addPerson.fulfilled( // <-- THIS
>   {
>     person: person1,
>     _id: 'someRandomString',
>   },
>   '',
>   { person: person1 },
> );
> 
> expect(familySlice.reducer(someInitialState, action)).toStrictEqual({
>   // ...
> });
> ```

But, how I can test the createAsyncThunk function instead of passing the payload in the action parameters of the test?
I understand that here is tested only de reducer, but not de async functions who fetch the data

**Comment by markerikson** [comment]
@gonwms Generally, our recommendation is to test the code as similarly as possible to how it would actually be _used_.

Ideally, we'd recommend just testing your Redux-using components at the UI level, per https://redux.js.org/usage/writing-tests#components .  Create a store, render the component with a provider, use React Testing Library to mock-click the "Fetch Some Data" button, verify that a short time later the list of items shows up in the component (which will only be true if the data was fetched and the reducer logic worked as expected).

Since this would typically involve a network call, we recommend using https://mswjs.io/ to mock out the network request itself, so that none of your code has to change.

If you don't want to render the entire UI, you could still create a Redux store with the real reducers, set up MSW to handle this request, and then dispatch the thunk to the store and verify the resulting state is what you expect.

**Comment by gonwms** [comment]
Sorry if my question doesn't make sense. But I need guidance.
How can I access the getPosts and createPost function inside postSlice in order to test the API? My test only test the reducers, but I can't access the functions.

Here is my postsSlice
```javascript
import { createSlice, createAsyncThunk} from '@reduxjs/toolkit';
import {  gql} from 'graphql-request';
import { sendRequest } from 'API/dbRequest';

// INITIAL STATE ---------------------------
const initialState = {
  data: [],
  status: 'idle',
  error: null,
};

// GET POSTS  ----------------------------------------------------
export const getPosts = createAsyncThunk('post/getPosts', async () => {
  //************************* HERE START WHAT I WANT TO TEST
  const query = gql`
    {
      posts {
        id
        title
        body
      }
    }
  `;
  // *********************** HERE ENDS  WHAT I WANT TO TEST
  return sendRequest(query);  // THIS IS WHAT SHOULD MOCKUP?
});
// ADD POST ----------------------------------------------------
export const createPost = createAsyncThunk('post/createPost', async (values) => {
//************************* HERE START WHAT I WANT TO TEST
  const mutation = gql`
    mutation Mutation($title: String!, $body: String!) {
      createPost(title: $title, body: $body) {
        id
        title
        body
      }
    }
  `;
// *********************** HERE ENDS  WHAT I WANT TO TEST
  return sendRequest(mutation, values);  // THIS IS WHAT SHOULD MOCKUP?
});

// UPDATE POST ----------------------------------------------------
export const getPostFake = createAsyncThunk('post/getPostFake', async () => {
  // return new Promise((resolve) => setTimeout(() => resolve({ data: [{ title: 'norma leandro', body: 'leandro' }] }), 500));
  return new Promise((resolve) =>
    setTimeout(
      () =>
        resolve({
          posts: [
            { id: 1, title: 'norma leandro', body: 'leandro' },
            { id: 2, title: 'norma legrand', body: 'leandro' },
          ],
        }),
      50
    )
  );
});

// REDUCER SLICE  -------------------------------------------------
const postsSlice = createSlice({
  name: 'posts',
  initialState,
  reducers: {},
  extraReducers: {
    /*-- GET POST -- */
    [getPosts.pending]: (state, action) => {
      state.status = 'pending';
    },
    [getPosts.fulfilled]: (state, action) => {
      state.status = 'succeeded';
      state.data = [...action.payload.posts];
      state.error = null;
    },
    [getPosts.rejected]: (state, action) => {
      state.status = 'rejected';
      state.data = null;
      // console.error(action.error);
      action.error.message === 'Unauthorized' ? (state.error = 'Unauthorized') : (state.error = 'an error has occurred');
    },
    /*-- CREATE POST -- */
    [createPost.pending]: (state, action) => {
      state.status = 'pending';
    },
    [createPost.fulfilled]: (state, action) => {
      state.status = 'succeeded';
      state.error = null;
      state.data.push(action.payload.createPost);
    },
    [createPost.rejected]: (state, action) => {
      state.status = 'rejected';
      state.error = 'post could not be added';
      console.error(action);
    },
  },
});

export const { listPost } = postsSlice.actions;
export default postsSlice.reducer;
```


This is my API dbRequest.js
```javascript
import { request, gql, GraphQLClient } from 'graphql-request';

const ENDPOINT = 'http://localhost:5000/graphql';
// REQUEST ---------------------------------------
export async function sendRequest(operation, values) {
  const CLIENT = new GraphQLClient(ENDPOINT, {
    headers: {
      authorization: `Bearer ${sessionStorage.getItem('token')}`,
    },
  });

  try {
    const response = await CLIENT.request(operation, values ? values : null);
    return response;
  } catch (error) {
    // const errorMessage = error.message.split(':')[0];
    const errorMessage = error.message;
    throw new Error(errorMessage);
  }
}
```

Here is my test. 
Here Im only testing the reducers I can't access the functions.

```javascript
import postSlice, { listPost, getPosts, createPost, deletePost, updatePost } from './postsSlice';
import { render, screen, waitFor } from '@testing-library/react';

describe('Testing getPosts', () => {
  const initialState = {
    data: [{ title: 'Title 1', body: 'some text' }],
    status: 'idle',
    error: null,
  };

  it('should handle slice getPosts fulfilled', async () => {
    const action = getPosts.fulfilled({
      posts: [
        { id: 1, title: 'norma ', body: 'leandro' },
        { id: 2, title: 'norma ', body: 'legrand' },
      ],
    });
    const actual = postSlice(initialState, action);
    expect(actual.status).toEqual('succeeded');
    expect(actual.data).toEqual([
      { id: 1, title: 'norma ', body: 'leandro' },
      { id: 2, title: 'norma ', body: 'legrand' },
    ]);
  });
  it('should handle slice getPosts pending', async () => {
    const action = getPosts.pending;
    const actual = postSlice(initialState, action);
    expect(actual.status).toEqual('pending');
  });
  it('should handle slice getPosts rejected Unauthorized', async () => {
    const action = getPosts.rejected('Unauthorized');
    const actual = postSlice(initialState, action);
    expect(actual.status).toEqual('rejected');
    expect(actual.error).toEqual('Unauthorized');
  });
  it('should handle slice getPosts rejected ', async () => {
    const action = getPosts.rejected('error');
    const actual = postSlice(initialState, action);
    expect(actual.status).toEqual('rejected');
    expect(actual.error).toEqual('an error has occurred');
  });
});

```

**Comment by markerikson** [comment]
@gonwms Tbh, I would _not_ try to test an async thunk that just makes a request :)  There's no benefit to it - it doesn't give you confidence that the app overall works correctly.

**Comment by gonwms** [comment]
Now I am trying to test the Components as you recommended, from a user's point of view. But, despite that I feel that small part of the thunk is going to be forever untested.... That's why I was asking if there is any way to access that function to send the parameters?  But maybe it is not the right way to do it?

**Comment by markerikson** [comment]
@gonwms : that goes back to my original point.  If you want to test different request behaviors, then use MSW to mock out the network request.  A good network response will test the `pending` and `fulfilled` cases.  A failed network response, or one that returns bad data / etc, will test the `rejected` case.  But like I said, trying to test the body of the thunk by itself is not helpful.
