### ISSUE TITLE
Suggestion: createSelectorCreator

### ISSUE THREAD

**Issue by JaeYeopHan** [reduxjs/redux-toolkit#536]
### Current

```ts
const name = 'info' // Slice name! (very useful 😀)
const _ = createSlice({
  name,
  initialState,
  reducers: { /* */ },
})

const infoState = (state: RootState) => state[name];
const someValue = createSelector([infoState], state => state.foo.someValue);
```

When create selector to some value in slice, always created with module namespaced state called `infoState`.

So, how about `createSelectorCreator`?

### Expected

```ts
const infoSelector = createSelectorCreator(name); // create selector with slice name!
const someValue = infoSelector(state => state.foo.someValue);
```

## Reference

https://github.com/reduxjs/reselect#createselectorcreatormemoize-memoizeoptions

**Comment by markerikson** [comment]
There's no guarantee that a given slice's name will be used as the state key it's mounted at.  Also, as you just showed, that function is a pretty trivial thing to write yourself if desired.
