### ISSUE TITLE
How to combine this with library redux-saga-routines?

### ISSUE THREAD

**Issue by cuongdevjs** [reduxjs/redux-toolkit#537]
I tried to combine them but it's not working?
This is my code:
**slide.js**
````
export const routine = createRoutine('GithubRepoForm');

const githubRepoFormSlice = createSlice({
  name: 'githubRepoForm',
  initialState,
  reducers: {
    changeUsername(state, action: PayloadAction<string>) {
      state.username = action.payload;
    },
    [routine.REQUEST]: state => {
      state.loading = true;
      state.error = null;
      state.repositories = [];
    },
    [routine.SUCCESS]: (state, action: PayloadAction<Repo[]>) => {
      const repos = action.payload;
      state.repositories = repos;
      state.loading = false;
    },
    [routine.FAILURE]: (state, action: PayloadAction<RepoErrorType>) => {
      state.error = action.payload;
      state.loading = false;
    },
  },
});

export const { actions, reducer, name: sliceKey } = githubRepoFormSlice;
````

**saga.js**: I was put actionCreator on sagas, but when I check type of actions, it's still not exist these actions which redux-saga-routines created before?
````
import { actions, routine } from './slice';
yield put(actions[routine.FAILURE](RepoErrorType.USERNAME_EMPTY));
````

**Comment by cuongdevjs** [comment]
<img width="759" alt="Screen Shot 2020-05-06 at 00 26 41" src="https://user-images.githubusercontent.com/33604446/81096223-452cfd80-8f30-11ea-938b-4a80ddab5d47.png">

**Comment by markerikson** [comment]
Any actions that are not generated by the `createSlice` call need to be handled by referring to them in the `extraReducers` field, not the `reducers` field:

https://redux-toolkit.js.org/api/createSlice#extrareducers
