### ISSUE TITLE
Inserting lots of entities at once

### ISSUE THREAD

**Issue by arjunnaha** [reduxjs/redux-toolkit#542]
Looking at the `createEntityAdapter` with normalizr [example](https://redux-toolkit.js.org/usage/usage-guide#using-createentityadapter-with-normalization-libraries), would there be a way to insert lots of entities at once?

I'm looking at structuring my state to something like:
```typescript
{
  articles: {
    ids: [...],
    entities: [...],
  },
  entities: {
    users: {
      ids: [...],
      entities: [...],
    },
    comments: {
      ids: [...],
      entities: [...],
    }
  }
}
```
Where the 'main' data type (articles) is stored in it's own slice, and other types (users, comments) are stored in their own slice within the entity object, to be potentially used by other slices/rest of the code.
******

I started to make a function to accomplish this:
```typescript
export const upsertEntities = (entities: { [key: string]: Object }) => {
  const state: TRootState = store.getState();
  for (let [key, value] of Object.entries(entities)) {
    if (key === 'comments') {
      commentsAdapter.upsertMany(state.entities.comments, value as { [id: string]: Comment });
    }
  }
};
```
and called it from the slice:
```typescript
[fetchArticle.fulfilled]: (state, action) => {
      upsertEntities({ comments: action.payload.comments })
      articlesAdapter.upsertMany(state, action.payload.articles)
    }
```

But I wasn't able to access the global state from `upsertEntities`, and the state in the reducer only contains the slice state (https://github.com/reduxjs/redux-toolkit/issues/379).

While in this example, there are only a few entities, my application has lots of entities that are shared across most of the reducers, and it would be handy if I could have a single function that inserted them into the relevant state, rather than having the reducers in each entity slice inserting them manually.

I might be going about this the wrong way, but any ideas would be much appreciated!

**Comment by msutkowski** [comment]
In your comments slice, you would do this:

```js
[fetchArticle.fulfilled]: (state, action) => {
      commentsAdapter.upsertMany(state, action.payload.comments)
  }
```

And the same in the users slice. Each slice can listen to the one action type (`fetchArticle.fulfilled`) and respond to it. In the example you mention, you can see this happening where the one createAsyncThunk result is listened to by each slice and they update their own state accordingly.

**Comment by arjunnaha** [comment]
Thanks for the quick reply Matt, that's worked!
