### ISSUE TITLE
How to manage non-serializable data

### ISSUE THREAD

**Issue by anomaaly** [reduxjs/redux-toolkit#543]
Is there a canonical  way to work with non-serializable data? For example, I'm trying to dispatch an action to upload a file. I get the following error: `A non-serializable value was detected in an action, in the path: 'payload.file'.` I'm not just looking for a quick fix, I'd like to understand how this is typically done using good form. My research has turned up nothing so any direction on this would be greatly appreciated.

**Comment by anomaaly** [comment]
I just found in the redux style guide that it's ok to pass in non-serializable data as long as it's heading to a middleware.

**Comment by markerikson** [comment]
Yeah, if an action is actually going to reach the reducers (and the DevTools), it shouldn't contain anything non-serializable.

_If_ a middleware is going to intercept that action and prevent it from reaching the reducers, then you can put whatever you want inside of it.

What's happening with this particular action?

**Comment by anomaaly** [comment]
Just that, it's being sent to a saga to be posted. I'm just trying to upload a file so I don't need it in any reducers. I'll go ahead and close, thanks.

**Comment by markerikson** [comment]
Yeah, the issue there is:

- The saga middleware always passes the action on to the reducers first before processing it
- That also means it doesn't _stop_ the action from the reaching the reducers.

So, if you're using sagas here, that warning is going to happen.

You might want to add an exception to the serializable check middleware to ignore that particular action type.

**Comment by anomaaly** [comment]
I added an exception for it with `createSerializableStateInvariantMiddleware` but since you're saying it's actually reaching the reducer, I'm having second thoughts. Would you recommend using some other middleware instead of `redux-saga`? Also, I'm not adding a case for this action in any of my reducers (only the API response) so no unserialzable data is actually hitting the store. Is this still considered bad practice?

**Comment by markerikson** [comment]
That is a good point.  The main reason to avoid non-serializable valeus is so that time travel debugging works right (and any state you might be trying to persist is valid).

Given that this action really isn't being handled by the reducers at all, that aspect won't matter.  So, yeah, probably just add the action type exception and move on.

**Comment by anomaaly** [comment]
Great I'll leave it as is then, thanks for your assistance!
