### ISSUE TITLE
Pass only the `payload` to `createReducer` action reducers

### ISSUE THREAD

**Issue by moodysalem** [reduxjs/redux-toolkit#545]
Because they are keyed by the action type name, it is not necessary to pass the action object and almost always leads to unnecessary destructuring/renaming

Would be much better if I could just name the parameter according to the payload type instead of it always being action

**Comment by phryneas** [comment]
There is also the `meta` key on some actions created by `createAction`, and as `createReducer` also works with actions that might be manually written non-FSA-actions, in reality there might be just about anything besides `payload` in actions passed into the reducer.

In addition to that, this would be a breaking change for an already very large userbase and steer away from these caseReducers actually being valid "reducers" in the sense that they still have the signature `(state, action) => state`, so people might get confused by that.

So thanks for the suggestion, but there is a lot speaking against that, I don't believe we're going to do that.
