### ISSUE TITLE
createReducer parameter order [Docs]

### ISSUE THREAD

**Issue by wgarvey** [reduxjs/redux-toolkit#548]
https://github.com/reduxjs/redux-toolkit/blob/master/docs/tutorials/basic-tutorial.md

The docs have several mentions of code snippets like such:

```
const increment = createAction('INCREMENT')
const decrement = createAction('DECREMENT')

const counter = createReducer(0, {
  [increment.type]: state => state + 1,
  [decrement.type]: state => state - 1
})
```

I was following this tutorial and I kept getting this exception on the `createReducer()`:
`funcMap need to be a plain object`

After pulling my hair out for a while I realized that maybe the order was changed since the funcMap seems to be the 2nd parameter. Changing it to this:

```
const counter = createReducer({
  [increment.type]: state => state + 1,
  [decrement.type]: state => state - 1
}, 0)
```

made it work fine. So I assume something was updated and the docs just didn't get the update, or there's something wrong with my setup.

my package.json:
```
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-toolkit": "^1.1.2",
```
node v8.11.4

**Comment by phryneas** [comment]
Nah, you've got the wrong package ;)

RTK is published under the package name `@reduxjs/toolkit`, not under `redux-toolkit`. 

redux-toolkit is a completely different package. Sorry for the confusion.

**Comment by phryneas** [comment]
Oh, and if you're just starting and have questions: we're pretty active in the reactiflux discord channel #redux, so come over and ask away :)

**Comment by wgarvey** [comment]
Thanks for the quick response! Really helpful.
