### ISSUE TITLE
Feature Request: Implement `default` condition in plain reducers in `createReducer` function.

### ISSUE THREAD

**Issue by chumlee132** [reduxjs/redux-toolkit#551]
Let's consider the following simple reducer
```javascript
const foo = (state, action) => {
    switch(action.type) {
        case 'abc':
            //some code;
            return updatedStated;
        case 'def':
            //somecode;
            return updatedState;
        case 'ghi':
            //somecode;
            return updatedState;
        default:
            //somecode;
            return updatedState;
    }
} 
```
For the `createReducer` we are passing object with actions as keys and reducer functions as values. How can we implement the `default:` case with `createReducer` function?

**Comment by markerikson** [comment]
`createReducer` (and thus `createSlice`) already implement the standard behavior of returning the existing state when an action is not recognized.  

If by some unlikely chance you need your reducer to do something else in the default case, you'll need to write a custom reducer that does what you want.
