### ISSUE TITLE
A tale of type archeology: configureStore middleware typings, the spread operator and Typescript

### ISSUE THREAD

**Issue by phryneas** [reduxjs/redux-toolkit#552]
I might make a blog article out of this on a later date, but for now I'll use this issue to document some weird behavior, important findings and the possible road to a fix.

Triggered by @msutkowski, I went a bit on a hunt.

"What is the issue", you ask? Typing the `middleware` parameter of `configureStore`, I answer.
The following works just fine:

```ts
const myCustomMiddleware: Middleware<(_: "foo" )=> "bar"> = () => next => action => {
  if (action === "foo") return "bar"
  return next(action);
}

const store = configureStore({
  reducer: () => ({}),
  middleware: [myCustomMiddleware, ...getDefaultMiddleware()]
})


const shouldBeBar: "bar" = store.dispatch("foo")
const shouldBeBaz: "baz" = store.dispatch(function thunk(){ return "baz" as const})
```

Whereas, when we turn the parameters around and move the spread to the front, it doesn't:

```ts
const myCustomMiddleware: Middleware<(_: "foo" )=> "bar"> = () => next => action => {
  if (action === "foo") return "bar"
  return next(action);
}

const store = configureStore({
  reducer: () => ({}),
  middleware: [...getDefaultMiddleware(), myCustomMiddleware] // => readonly Middleware<{}, AnyAction, Dispatch<AnyAction>>[]
})

// these two will error out
const shouldBeBar: "bar" = store.dispatch("foo")
const shouldBeBaz: "baz" = store.dispatch(function thunk(){ return "baz" as const})
```

So I've undertaken quite the journey as you can see in this [TypeScript playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXxAA8AHcDAFQE9SAecgPgApgAucgShfnIG4AoUJFgIU6bHnjAsAZ2JQMYABYAxHDBoBZAoQwhUwafACCMGFEoAZLAGsQmrMGAQQAd2H0mrDZ3gARGXIKKmoaDk6uwtKa9Px8APQAVAnwYMjSGDgAtvCZYc5ucPAJcQLg0IVgeOk5LvBcoY75wjSMiDg4XADkAEawnezwALz08D1QAF6d9PFJ8BiKaNY5eRGFxaVCFVUYc9lc5Auo1g3hBXYA3gC+ADTGqJRGmLioMTPJ0lkIOPMgMMuNqwQ60E5QQlVQ1SydXgJyacBoV1uRnuj3EL1iIOEKW2cyg0MYA2G8AARPNFqjnsS+PE4ik0hlsrkAWd4BIsBhOoYcC58C41NZpHwiKRMFRaMTeuNiZ4AvIlKoYIwANqZFwAXXYjAlsGJ7HY1POfHB1SZp0iQ3gKpctwwmTV8CghmNGCFJDIYrs2qlMtkcuCitNcJA0k12pguv1wvd1E9ZKOFLw0uYsqCCsYgcBIcYGCger4lz4hud-zNcEMg0tttuqvtjuxEJdUdFMZoXqTUl9qbU6ZWZyzYYjrpFFBbpMO1gTqHbKfl3Yzfc1ObzBaNONgMAAjBalVkbXbVw2HaYAEzb3e7WtO7YGg8m3vmitW24AOlf643l-r6SH0fFkunnazgG95lqGvThnmTYjuKcYTk8iY+oEQE9sykSLrmAxxLSGTwN0CBQSAwC3O+8AyPAqDfF+LoroaWHwLIcBQMArKkGYGR-PIcyKAgeEAOZYKgqACbx8C2CAxCGC4Dh6IR9GVKQt47POD6Wq+z7vtW6oOleh50USjHAHgECUDCIEXDcdwPPBqC3P4gGKDQyJWWiHhKmqP7Nn+EwAUh-ooaWwZgTqkFup5sbjpOPl+mmymgdmGH5jedHgmAnFiRJ8BSaAqCydI8kgIpJZBuWR6bs+KXyOmLiYbS+kgExRkmbCgIIhZTmTrZM4Oe11mue5UEeq2-6IdFc5mf24GDgNo6wZFI1dsBqFxUu+oroWhWxcG26qi+b4np+zoedBnrDcm9kxeNQUQZGoXHa2s3WVFC3+cV6HLtS610Qx9XMTgrHyGoDo7D8uEgPxgnCfRIAgJkhg4RAODSAgUAQBA9EilgiBYGA7KUBt43bmp67HppB04npIzwAZjWmUt5lIii1mdfZjmMy59BuUdg1tvNyGbRNwU3cO3MPWiT185d8XvZ9tIVTsKMIy4hhMVIqAiXW7KkVemSBFg3TOHMODwAABqqxu3N0yA7IZW0UfLjikRyhgAG4o8gCAYDG+N0yVxPlXgqUYFVNVDCM1OoMZtMBa1DPOc8zO+azcd4H1XOjqdHa+RdPtXVNt0ixFj2835-Nvat1J0cSADC9JZAASj9jUmGYlDEpl7KKKyzu-DAYR6CSctt5kIDzDgwAbKCVGlQAzFwNfpPXjcRw8pjmDQnukDgiCstkAA+cwxlvuyvEWOL8xa67T-76CVVaGpp153pnVnY051qk0hcLM2F2LxfZwFWYVqJVPoec+FZL7X0DsHB+J1vJ-1fgA3On9fzhXJEXZ+o1FqIKluXGkSA1BgDBI6bAatDbwHngyBuDVl7N3MIVdcAAWC+J5tLGGkBQxe1DjK0MoOvQ+29iYn29gA5hMAGGQNvjWIWKChpwIwc9Uu79BYwPuj-Sk8CsGvRwcA4RxVRHiLltA6aj9xYl0lgOZBYVVFoN-vIiWb8gFrTogAWlcW49x3AYySBAFjISaJDCIBgFCOu5AADS8B3GROcdSLAOs1A7HOM1M4SImaWUnJcJAQTsidDgMAZAhBOh8FicQeJ8BzgHEWEk4QtwKnxlSbU6wdlfIZMCVCHJhF8nONgoUocpSN4ICaZgqpZZogWi0EQXQ+hDA8KsLYGgUB7jTHgPAAA-PAAAqkJPA5AcAAElUC6BgEjayNA+DLPOTCJUqBkCZDwjAe0Ey9AGFIqgRAvwo5BgAGpu2DGci55y1nDJAN8iA7tDCPKmR8lqAk3l-EGUEAAojoYi9wUWUCWf8i5az4VKCRTsCFzzlBoGsn8zFWK-BdTxaSslyyuA5W7jAalmK6UgAZUy85LK2UXIxZy34FckhnOSFXPADL5YbK2fgfpJtGBGF3gAIXYMbMhCzmICUOcc54B9SDSqMAAMgVcbQVJQpWbOeDs-Z6qyDPBoOskYFZGDrO0JM55Cy8ZrMYNYLg6zCQjGdjgBwfBeUwAGASwwHquAwvebsn18A-UBuWWs3Zfyg0fTVb8RAUBCHkNrpkKhhkaGr14QwJ1TzDAAHlcgYBoHmpuha6D0FuJ0OWUwyl-Llo5EtkLhU3wwDw+ZiymDri4EYHwHDc1L24XW8g8B95GCuTcu5aoMXtqMJ255NaC0t37eipgRNTDDtHTmjdk6t3TtnfO25vwl2JWpFKow7Cj0TpXqetdhhj3PrXq6jwFox3vr7eQC9i76BAA)

While I cannot fix the spread operator and `concat` out of the box is not really a solution either, I *can* override `concat` on the return value of `getDefaultMiddleware` with a custom method signature that fixes this behaviour.

The fixed behaviour looks like this - [playground](https://www.typescriptlang.org/play/?#code/FDCWDsBcFMCcDMCGBjaACAwgVwM6QPYC2AStIgCb7gA2AngIKyyK0A8AKgHxrQAeM4cjjQB5QqEitSFKnUbM2XADRoA5MirJEkVdwDewNGg3gtk+j37RBwjJu3yWrROFqdOACkRMAXGnoAlH7YeETSlDQMTE7saAA+-gDa4FiEAEZwALqchsb25pYCQmjhslEKzq7uHgB0dd6wfoHBuAQkZBFy0YrxSSnpWTkAviDAkLQADuj0OCFtpZGOPXxFwgtdFS5u3AC8mK1hHWVLHMmpGbDZIKCEE-iwkGh6AObQkAAi0EhY1JAAsqByORqNAAO7eaAqEzwUDPLCwaAAZQICKGaHgsCIagAAgjyFheAArHAAegI+GoAGsJKowLd7o89ACgSDwaj0ZjCGo8QTaWNJuhiPh8JBkfd0Hs9CNgCY8GhyF9ED9-oDgWCIWg9q8Porlcy1WzoFJhaKUdBPAEANwgWWPUHMCZTcifb6-fWsjV7BWulUs9UItCIYQzOaHGSLbqscZTfDweW6t2qj0InK2tAigAWcHd-ugfhzhtYHgA+n4AETwYVltABHbcMtpbxl3ZoDwBTXccArDuB5CQUBUHsGIygONePsD8CanZ7CtV9sIyDwqcNpu5RfLtBd-jj-tUK3AaVp0IBvbQ2HwpFmjzDtA81CNVvtuutqUBJS5cR+w1Nbo1DFEB49qII60DOgmvoGhCNQmGYHiZtmSa5gEASHqhMpUHKOAZvgPzkAAQtA+HeOWjawNWewntANTkKAOATNoyAZh4c74GWqHHjheGEcRABepGILxFFoFRNF0QxkBMR48BYKYe5TpAGayZSbZ6HebybquQmBsItpDAEQA)

```ts
interface CustomReadonlyArray<T> extends Omit<ReadonlyArray<T>, 'concat'> {
  concat<A extends ConcatArray<any>>(arr: A): CustomReadonlyArray<T | A[number]>
  concat<A extends ReadonlyArray<any>>(...arr: A): CustomReadonlyArray<T | A[number]>
}


type AsCustomReadonlyArray<T extends ReadonlyArray<any>> = CustomReadonlyArray<T[number]>

import {getDefaultMiddleware, configureStore} from '@reduxjs/toolkit'
import {Middleware} from 'redux'

type RootStore = {}

const defaultMiddleware = getDefaultMiddleware<RootStore>();

const wrappedDefaultMiddleware = defaultMiddleware as AsCustomReadonlyArray<typeof defaultMiddleware>
const otherMiddleware: Middleware<(_: "foo" )=> "bar"> = () => next => action => {
  if (action === "foo") return "bar"
  return next(action);
}

const store = configureStore({
  reducer: () => ({}),
  middleware: Array.from(wrappedDefaultMiddleware.concat(otherMiddleware))
})

const shouldBeBar: "bar" = store.dispatch("foo")
const shouldBeBaz: "baz" = store.dispatch(function thunk(){ return "baz" as const})
```

So right now, and without patching RTK, this already works with some shenanigans:

A cast:
```ts
const wrappedDefaultMiddleware = defaultMiddleware as AsCustomReadonlyArray<typeof defaultMiddleware>
```

and then converting it back into an array:
```ts
  middleware: Array.from(wrappedDefaultMiddleware.concat(otherMiddleware))
```

So, now there's the question: should I integrate this behaviour? It should cut down our Middleware-related typings issues immensely.
And, as this only solves our "beginning spread" problems, and not our "in the middle spread problems" (I didn't test those, but I guess we'll have those as well), that about adding a `prepend` method that does the opposite?

So with all that integrated, it would look like 

_one middleware at the end_
```ts
const store = configureStore({
  reducer: () => ({}),
  middleware: defaultMiddleware.concat(otherMiddleware)
})
```
or
_two middlewares at the end_
```ts
const store = configureStore({
  reducer: () => ({}),
  middleware: defaultMiddleware.concat(otherMiddleware, otherMiddleware2)
})
```

or
_multiple middlewares at the end (array concat)_
```ts
const store = configureStore({
  reducer: () => ({}),
  middleware: defaultMiddleware.concat([otherMiddleware, otherMiddleware2, otherMiddlewar3])
})
```
if we went full in with a prepend,
_one middleware at the beginning, one at the end_
```ts
const store = configureStore({
  reducer: () => ({}),
  middleware: defaultMiddleware.prepend(otherMiddleware).concat(otherMiddleware2)
})
```

**Comment by markerikson** [comment]
Uh... yipes!

Supposed to be working atm, so I can't devote full mental attention to this.  

I'm generally in favor of whatever simplifies our typings the most and enables the use cases we want to support :)

**Comment by phryneas** [comment]
Give it a look-over sometime the next few days - I won't start that one anytime soon ;)

**Comment by markerikson** [comment]
Fixed, by you, ~~in the library with the candlestick~~ in #549 and #559 :)

(would still love to see some blog posts by you, btw!)

**Comment by farah** [comment]
@phryneas +1 for the blog post :)
