### ISSUE TITLE
Usage with redux-offline

### ISSUE THREAD

**Issue by DCKT** [reduxjs/redux-toolkit#555]
Hello,

I'm using redux-offline and I would like to use redux-toolkit but the problem is redux-offline use a special keyword (offline) in the action object and this is ignored from redux-toolkit.

Is there a workaround for this ? 
For the moment, I recreate the `createAction` function to allow `offline` object.

Thanks for your work !

**Comment by phryneas** [comment]
If you need to set `meta.offline`, you can use the prepare callback notation:

```ts
createAction('test', (x: string) => ({ payload: x, meta: { offline: { /*... */}} }));
```

Something similar is available for `createSlice` if you need it, just take a look at the docs :)

**Comment by DCKT** [comment]
Oh my bad ! I miss-used redux-offline, sorry for the issue ! 

Thanks for your quick answer, have a good day 😃

**Comment by ifitzsimmons** [comment]
Sorry to comment on a closed thread, but in the above example, how do you create the reducer for that action?

That action could presumably have a few different actions types: Commit, Rollback and the initial action. I've been struggling all day with creating a reducer and haven't found any documentation.

**Comment by nguyenhoanglam** [comment]
@phryneas Could you give me an example about how to add **offline** object to **createSlice**?

**Comment by phryneas** [comment]
@nguyenhoanglam 
```js

const todosSlice = createSlice({
  name: 'todos',
  initialState: [],
  reducers: {
    addTodo: {
      reducer: (state, action) => {
        state.push(action.payload)
      },
      prepare: (text) => {
        return { payload: text, meta: { offline: ... } }
      },
    },
  },
})
```

**Comment by sunnybhakta296** [comment]
Thanks for providing solution and sorry for asking question on closed queation

But where can I get detailed tutorial with redux-toolkit.


How to dispatch actions for offlime

**Comment by phryneas** [comment]
@sunnybhakta296 with my example above

```js
dispatch(todosSlice.actions.addTodo("text"))
```

**Comment by sunnybhakta296** [comment]
> Sorry to comment on a closed thread, but in the above example, how do you create the reducer for that action?
> 
> That action could presumably have a few different actions types: Commit, Rollback and the initial action. I've been struggling all day with creating a reducer and haven't found any documentation.



> Sorry to comment on a closed thread, but in the above example, how do you create the reducer for that action?
> 
> That action could presumably have a few different actions types: Commit, Rollback and the initial action. I've been struggling all day with creating a reducer and haven't found any documentation.

Can you share some code if you succeed with rtk

**Comment by phryneas** [comment]
I don't use redux-offline and know nothing about it. This was just a question on how to set `meta.offline` on RTK actions.

**Comment by sunnybhakta296** [comment]
Any one has idea where can I get full docmentation  to integrate redux-toolkit with redux-offline. Is there any implementation avalilavle. Because I'm not able to find proper docentation

**Comment by Career404** [comment]
Since this is maintaned again, seeing more documentation and especially things related to Redux-Toolkit would be a blessing

**Comment by inthisar-hamza** [comment]
@phryneas can you provide more implementation of code, how it's it's redux offline updates the state and how to manage if anything gets wrong in api call, because there are no example implementation on internet fo redux toolkit so please provide details code. thanks for collobaration

**Comment by phryneas** [comment]
@inthisar-hamza I have never used Redux-offline, so I have no idea how to do that or if it even makes sense/is possible, I'm sorry.

**Comment by avinash797** [comment]
> Hello,
> 
> I'm using redux-offline and I would like to use redux-toolkit but the problem is redux-offline use a special keyword (offline) in the action object and this is ignored from redux-toolkit.
> 
> Is there a workaround for this ? For the moment, I recreate the `createAction` function to allow `offline` object.
> 
> Thanks for your work !

@DCKT I'm trying to implement redux-offline in my app that's using redux toolkit. Do you have any resources/code that I can take inspiration from? Thank you!
