### ISSUE TITLE
What would be best way to reset the full nested state.

### ISSUE THREAD

**Issue by manthena08** [reduxjs/redux-toolkit#556]
let say I have my store with nested combineReducers as below

const rootReducer = () =>
        combineReducers({
                agent,
                customer: customerReducer
        });

const customerReducer = combineReducer({
    profile,
    account
})

In this case if I want to reset the full customer state to its initial state how can I do that?

Note:     "@reduxjs/toolkit": "^1.3.5",
    "typescript": "^3.8.3"

**Comment by omarryhan** [comment]
I personally prefer to create a single destroy (or logout) action that is then read by each reducer. This action should make the reducer return the initial state.

If you want to achieve this by using the combined reducer. You first need to combine your initial state as well. AFAIK, Redux doesn't provide such utility.

I have a NextJS app that uses the NextJS redux wrapper. It magically provides the initial combined state to my Redux store. Here's how I have it setup:

```typescript
import {

combineReducers, AnyAction, Reducer,

} from 'redux';

import { HYDRATE } from 'next-redux-wrapper';

import { reducer as userReducer } from './user/reducer';

import { reducer as profileReducer } from './profile/reducer';

import { reducer as playlistsReducer } from './playlists/reducer';

import { reducer as playlistItemsReducer } from './playlistItems/reducer';

import { reducer as tracksReducer } from './tracks/reducer';

import { reducer as tracksAudioFeaturesReducer } from './tracksAudioFeatures/reducer';

import { CombinedStateType } from './types';

const allReducers = {

user: userReducer,

profile: profileReducer,

playlists: playlistsReducer,

playlistItems: playlistItemsReducer,

tracks: tracksReducer,

tracksAudioFeatures: tracksAudioFeaturesReducer,

};

export const combinedReducer = combineReducers(allReducers);

export const rootReducer: Reducer = (

state: CombinedStateType, action: AnyAction,

): CombinedStateType => {

if (action.type === HYDRATE) {

return {

...state,

...action.payload,

};

}

return combinedReducer(state, action);

};


```

**Comment by phryneas** [comment]
Somehow I seem to have missed this ticket.

You can also do something like

```js
const resetRootReducer = (state, action) => {
  if (action.type === 'store/reset') {
    return rootReducer(undefined, action);
  }
  return rootReducer(state, action);
}

```

**Comment by krishnaUIDev** [comment]
> Somehow I seem to have missed this ticket.
> 
> You can also do something like
> 
> ```js
> const resettableRootReducer = (state, action) => {
>   if (action.type === 'store/reset') {
>     return rootReducer(undefined, action);
>   }
>   return rootReducer(state, action);
> }
> ```

This will just clear the `store/reset` action, but what if i have more than 1 reducer ?

**Comment by markerikson** [comment]
@krishnaUIDev I think you're misreading that example :)

- It only runs the reset process _if_ the `'store/reset'` action is dispatched....
- But in that case, **it calls the _root reducer_ to produce an entirely new _root_ state!**  Not just one slice.

**Comment by andymcgunagle** [comment]
I'm using "@reduxjs/toolkit": "^1.8.3" and "typescript": "4.7.4" and trying to figure out how to implement @[phryneas](https://github.com/phryneas)'s example.

I'm getting an error under the reducer in configure store. Am I way off base here? Is there a simpler way to reset the state of the entire store with RTK? 

Apologies for my ignorance - I've been going through the docs and trying to figure this out for the past few hours. Thanks in advance!

```typescript
import { Action, AnyAction, CombinedState, combineReducers, configureStore, Reducer } from '@reduxjs/toolkit';
import { useDispatch } from 'react-redux';

import { conversationsReducer } from './conversationsSlice';
import { userReducer } from './userSlice';

const reducers = {
  conversations: conversationsReducer,
  user: userReducer,
};

const rootReducer = combineReducers(reducers);

const resettableRootReducer = (state: ReturnType<typeof rootReducer>, action: AnyAction) => {
  if (action.type === 'store/reset') {
    return rootReducer(undefined, action);
  };

  return rootReducer(state, action);
};

export const store = configureStore({
  reducer: resettableRootReducer,
  devTools: process.env.NODE_ENV !== 'production',
});

export type RootState = ReturnType<typeof store.getState>;

export type StoreDispatch = typeof store.dispatch;
export const useTypedDispatch = () => useDispatch<StoreDispatch>();
```

The error:
Type '(state: ReturnType<typeof rootReducer>, action: AnyAction) => CombinedState<{ conversations: ConversationsState; listing: ListingState; user: UserState; }>' is not assignable to type 'Reducer<CombinedState<{ conversations: ConversationsState; listing: ListingState; user: UserState; }>, AnyAction> | ReducersMapObject<...>'.
  Type '(state: ReturnType<typeof rootReducer>, action: AnyAction) => CombinedState<{ conversations: ConversationsState; listing: ListingState; user: UserState; }>' is not assignable to type 'Reducer<CombinedState<{ conversations: ConversationsState; listing: ListingState; user: UserState; }>, AnyAction>'.
    Types of parameters 'state' and 'state' are incompatible.
      Type 'CombinedState<{ conversations: ConversationsState; listing: ListingState; user: UserState; }> | undefined' is not assignable to type 'CombinedState<{ conversations: ConversationsState; listing: ListingState; user: UserState; }>'.
        Type 'undefined' is not assignable to type 'CombinedState<{ conversations: ConversationsState; listing: ListingState; user: UserState; }>'.
          Type 'undefined' is not assignable to type 'EmptyObject'.ts(2322)
configureStore.d.ts(21, 5): The expected type comes from property 'reducer' which is declared here on type 'ConfigureStoreOptions<CombinedState<{ conversations: ConversationsState; listing: ListingState; user: UserState; }>, AnyAction, [...]>'

**Comment by phryneas** [comment]
@andymcgunagle your `state` in your `resettableRootReducer ` needs to be `| undefined`.

**Comment by n-ii-ma** [comment]
> Somehow I seem to have missed this ticket.
> 
> You can also do something like
> 
> ```js
> const resettableRootReducer = (state, action) => {
>   if (action.type === 'store/reset') {
>     return rootReducer(undefined, action);
>   }
>   return rootReducer(state, action);
> }
> ```

Is there any way to exclude one slice from being cleared in this approach?

**Comment by EskiMojo14** [comment]
@n-ii-ma just change what you pass to the reducer

```ts
const resettableRootReducer = (state, action) => {
  if (action.type === 'store/reset') {
    return rootReducer({ counter: state.counter }, action);
  }
  return rootReducer(state, action);
}
```

**Comment by n-ii-ma** [comment]
> @n-ii-ma just change what you pass to the reducer
> 
> ```ts
> const resettableRootReducer = (state, action) => {
>   if (action.type === 'store/reset') {
>     return rootReducer({ counter: state.counter }, action);
>   }
>   return rootReducer(state, action);
> }
> ```

I get a type error if I do that:

```
Type '(IntroSliceState & PersistPartial) | undefined' is not assignable to type 'IntroSliceState & PersistPartial'.
  Type 'undefined' is not assignable to type 'IntroSliceState & PersistPartial'.
    Type 'undefined' is not assignable to type 'IntroSliceState'.
```

This is how I'm reseting the whole store at the moment:

```
// Root reducer (resettable)
const rootReducer = (
  state: ReturnType<typeof appReducer> | undefined,
  action: AnyAction
) => {
  // If the `logout` action is dispatched, clean the `Redux Persist` storage and reset the state
  if (action.type === "auth/logout") {
    storage.removeItem("persist:root");

    return appReducer(undefined, action);
  }

  return appReducer(state, action);
};
```

To summarize, I have a React Native app (using TypeScript and RTK Query) in which I want to show an intro slider only for the first app launch. I have created a slice for its visibility state and am using redux-persist to keep the data and I also have separated the `persistence` config of my intro slice so that I can keep it into storage even after the logout:

```
// Root persistence config
const rootPersistConfig = {
  key: "root",
  version: 1,
  storage,
  blacklist: ["intro", api.reducerPath],
};

// Intro slides persistence config
const introPersistConfig = {
  key: "intro",
  version: 1,
  storage,
  blacklist: [api.reducerPath],
};

// Top-level reducers
const appReducer = combineReducers({
  [api.reducerPath]: api.reducer,
  auth: authSliceReducer,
  intro: persistReducer(introPersistConfig, introSliceReducer),
});
```

I'm trying to keep the `intro` slice from being cleared by the `resettableRootReducer`.
