### ISSUE TITLE
Is there a way to add custom fields to the action

### ISSUE THREAD

**Issue by dorsharon** [reduxjs/redux-toolkit#557]
I'd like to add an additional field to the action, and Iddon't want it to be in the payload.

Is there some workaround or something?

**Comment by markerikson** [comment]
Can you describe what you're actually wanting to do, specifically?

RTK uses [the "Flux Standard Action" convention](https://github.com/redux-utilities/flux-standard-action), where the only allowed fields in the action object are `type`, `payload`, `meta`, and `error`.

What you actually put into `payload` and `meta` is up to you, and RTK's APIs let you customize how those fields are constructed.

**Comment by dorsharon** [comment]
How can I customize `meta`?

**Comment by markerikson** [comment]
You write a "prepare callback" that returns a field with a `meta` object in it:

https://redux-toolkit.js.org/api/createAction#using-prepare-callbacks-to-customize-action-contents

https://redux-toolkit.js.org/api/createSlice#customizing-generated-action-creators

**Comment by dorsharon** [comment]
Does this work for `createAsyncThunk` as well?

**Comment by markerikson** [comment]
No, because the point of `createAsyncThunk` is that it automatically defines and dispatches the actions for you without you needing to write them yourself.

Can you give more details on what you're _specifically_ trying to do?  It's hard to give answers without knowing more about the use cases you're trying to solve.

**Comment by dorsharon** [comment]
Well, I have a notification that pops up and alerts about the success/failure of many of our thunk actions, and that notification message is managed via Redux.

Every time our developers implement new thunks and reducers, they also have to remember to add a use case in the notification reducer for their new thunk type to display the message.

We wanted to place the messages in some neat way in the actions themselves, so that a simple middleware could always snatch the appropriate field and do the work for us (by dispatching the notification action)

However, we wanted to avoid polluting our payloads with these fields if possible.
Any idea?

**Comment by markerikson** [comment]
What kinds of messages are we talking about?  Are these unique per thunk, something that's auto-derived / hardcoded, ... ?

**Comment by dorsharon** [comment]
They're unique per thunk.
"new item was added successfully / deleted" type of thing

**Comment by markerikson** [comment]
There's two potential options here.  I'm not sure if you're going to be _happy_ with either of them, but they may at least satisfy your technical requirements:

- Actually include the message in the payload, like

```
    return {
        items: response.data.items,
        message: "Loaded the items!"
    }
```

- Whatever argument you pass in to the thunk when you dispatch it become available as the first parameter to the payload creator.  It also will be automatically added to the `action.meta` field when it's dispatched.  So, let's say you are fetching a user by ID:

```js
dispatch(fetchUserById({id: 123, message: "User fetch succeeded"}));

// later, the action will look like:
{
  type: "users/fetchUserById/fulfilled",
  payload: [ /* some users here returned by the payload callback */],
  meta: {
    requestId: "12345678",
    arg: {id: 123, message: "User fetch succeeded"}
  }
}
```

**Comment by dorsharon** [comment]
Thank you for being so responsive! 

So, initially I actually went with the first option, but on rejected actions I couldn't get to the message in the payload. Is this supposed to work with rejected actions too?

**Comment by phryneas** [comment]
You have control over the rejection payload by using `rejectWithValue`:

```
const updateUser = createAsyncThunk(
  'users/update',
  async (userData, { rejectWithValue }) => {
    const { id, ...fields } = userData
    try {
      const response = await userAPI.updateById(id, fields)
      return response.data.user
    } catch (err) {
      // Note: this is an example assuming the usage of axios. Other fetching libraries would likely have different implementations
      if (!err.response) {
        throw err
      }

      return rejectWithValue(err.response.data)
    }
  }
)
```
