### ISSUE TITLE
[Docs] Circular dependency section

### ISSUE THREAD

**Issue by silver-snoopy** [reduxjs/redux-toolkit#562]
Dear Redux-toolkit members,

I am writing you because of the section of **Circular Slice Dependencies**.

Based on the feature based slice structure compare to th aforementioned guideline section - Would it be possible to provide an example which fits the recommended approach? Where those shared action types could be placed under the feature folder?

I would be very grateful if you could provide an example.

**Comment by markerikson** [comment]
Your file structure is always up to you.  Is there a specific question you have about how to do this kind of thing?

**Comment by silver-snoopy** [comment]
Based on this section, maybe it would be nice/worth to involve a common “feature” example to the github example in the advanced example project.

I understand that to extract and uplift thr common part but i do not see how it fits the feature approach.

Does this make sense? :)

**Comment by markerikson** [comment]
@silver-snoopy it doesn't matter _where_ you put this new file, as long as it's a separate file that both the slices can import from.  Put it in `features/featureA/sharedActions.js`, or `common/sharedActions.js`, or wherever you want.

**Comment by markerikson** [comment]
Closing for now as I think we have sufficient info in the docs atm.  If you or anyone else would like to contribute a PR that adds more details, please do so.
