### ISSUE TITLE
createAsyncThunk accessing state best practices

### ISSUE THREAD

**Issue by robin-farmx** [reduxjs/redux-toolkit#563]
In the example in the docs below, the users state is accessed using the getState method.
```
const fetchUserById = createAsyncThunk(
  'users/fetchByIdStatus',
  async (userId, { getState, requestId }) => {
    const { currentRequestId, loading } = getState().users
    if (loading !== 'pending' || requestId !== currentRequestId) {
      return
    }
    const response = await userAPI.fetchById(userId)
    return response.data
  }
)
```
This issue I see with this is that your slice code must have an understanding of the layout of your state hierarchy. It must know that the users slice state is located at the top level `users`. 

Is this the best way to access state? or is there some other way to get around this?

**Comment by markerikson** [comment]
By definition, any use of `getState` has access to the entire Redux state tree.  This is entirely intended usage.
