### ISSUE TITLE
Code Splitting not working

### ISSUE THREAD

**Issue by sanpanthera** [reduxjs/redux-toolkit#564]
I have a react project consists of js/jsx files. It has some loadable components. After migrating from Redux to Redux-toolkit code splitting not working i.e in the prod bundle chunk files are getting merged.

**Comment by phryneas** [comment]
A little more context would definitely be nice to understand what exactly is going on there. 
Can you create a reproduction repo?

**Comment by markerikson** [comment]
This doesn't sound like it's related to RTK.  If you've got some specific examples of how RTK is actually affecting this, let us know, but closing until then.
