### ISSUE TITLE
Handle errors with Sentry.io

### ISSUE THREAD

**Issue by paveleremin** [reduxjs/redux-toolkit#565]
1) How to properly handle errors with Senty in a single place?

**Comment by phryneas** [comment]
We have no way of knowing your application and don't know what kind of errors are being thrown there, so there is no possible way for us to answer that from a single sentence on your side.

Also this is an issue tracker and not really a help/discussion forum. It might be better suited if you move this discussion over to the #redux channel on the Reactiflux discord or to stackoverflow (although I believe discord might be a better place to discuss this).
