### ISSUE TITLE
dispatch in compoenents

### ISSUE THREAD

**Issue by paveleremin** [reduxjs/redux-toolkit#566]
Is it possible to use dispatch in components like this
```javascript
try {
  await dispatch(..).then(unwrapResult)
}
catch (err) {
  formik.setErrors(err.errors)
}
```
I read the documentation and I didn't like some magic constructions, like
```javacript
if (createItem.rejected.match(resultAction)) {
  ....
}
```
any suggestions?

**Comment by paveleremin** [comment]
Maybe it is possible to use it somehow with catch instad of then
```javascript
try {
  await dispatch(..).catch(unwrapResult)
}
catch (err) {
  formik.setErrors(err.errors)
}
```

**Comment by phryneas** [comment]
No, the `then` route is correct. We don't throw by default from a catch, as that would result in a *lot* of uncaught promise rejections for people who would not want to do error handling on a per-component-base, but rather from a reducer or a middleware.

`.then(unwrapResult)` changes this behaviour to "throwing".

As you already have both correct solutions in your initial post: why are you asking? Is it somehow not working?

**Comment by paveleremin** [comment]
@phryneas 
> As you already have both correct solutions in your initial post: why are you asking? Is it somehow not working?
I'm trying to find a clean and code friendly solution for my project

> .then(unwrapResult) changes this behaviour to "throwing".
What do you mean could you share some example please?

**Comment by paveleremin** [comment]
Here is how my action looks like
```javascript
export const createItem = createAsyncThunk(
    `${name}/create`,
    async(values, { getState, rejectWithValue }) => {
        const { user } = /** @type authSelector */ authSelector(getState());

        const { city, ...data } = values;
        const dataToSend = {
            ...data,
            city_id: city.id,
            photos: values.photos.map((photo) => photo.src),
        };

        try {
            await api.post(`/users/${user.id}/items`, dataToSend);
        }
        catch (err) {
            if (!err.response) {
                throw err
            }
            return rejectWithValue(err.response.data)
        }
    }
);
```
I don't what to add async/await in each action to get errors in component for Formik

**Comment by phryneas** [comment]
> @phryneas
> 
> > As you already have both correct solutions in your initial post: why are you asking? Is it somehow not working?
> 
> I'm trying to find a clean and code friendly solution for my project
> 
> > .then(unwrapResult) changes this behaviour to "throwing".
> 
> What do you mean could you share some example please?

All I can do is copy & paste your initial example, as it was absolutely correct:

```js
try {
  await dispatch(..).then(unwrapResult)
}
catch (err) {
  // you can handle the error here just fine
  // doing a `console.log(err)` here and exploring the contents or err might resolve all your questions?
}
```

**Comment by paveleremin** [comment]
@phryneas 
I use axios. And in this case, err just empty object - {} without any data.

**Comment by phryneas** [comment]
> Here is how my action looks like
> 
> ```js
> export const createItem = createAsyncThunk(
>     `${name}/create`,
>     async(values, { getState, rejectWithValue }) => {
>         const { user } = /** @type authSelector */ authSelector(getState());
> 
>         const { city, ...data } = values;
>         const dataToSend = {
>             ...data,
>             city_id: city.id,
>             photos: values.photos.map((photo) => photo.src),
>         };
> 
>         try {
>             await api.post(`/users/${user.id}/items`, dataToSend);
>         }
>         catch (err) {
>             if (!err.response) {
>                 throw err
>             }
>             return rejectWithValue(err.response.data)
>         }
>     }
> );
> ```
> 
> I don't what to add async/await in each action to get errors in component for Formik

Then write that code into a function and call that from every action? This isn't conceptually different from any other programming just because it's redux. You can of course build your own abstractions.

But as you are using formik and the next person will be using something completely different, we cannot provide these abstractions. These are specific to your project.

**Comment by phryneas** [comment]
> @phryneas
> I use axios. And in this case, err just empty object - {} without any data.

Then probably `err.response.data` was `{}`?

**Comment by phryneas** [comment]
As this, like your other issue #565 is not a bug report or feature request, but a usage discussion - could you please move that over to one of the support channels?

This is really just the place to discuss bugs and feature requests. If we were to do usage support here, this would become very chaotic very quickly.

**Comment by paveleremin** [comment]
Here is my code
```javascript
export const createItem = createAsyncThunk(
    `${name}/create`,
    (values, { getState }) => {
        const { user } = /** @type authSelector */ authSelector(getState());

        const { city, ...data } = values;
        const dataToSend = {
            ...data,
            city_id: city.id,
            photos: values.photos.map((photo) => photo.src),
        };

        return api.post(`/users/${user.id}/items`, dataToSend);
    }
);
```
and in component
```javscript
try {
    await dispatch(createItem(values)).then(unwrapResult);
}
catch(err) {
    console.log(err);
    console.log(err.response);
}
```

**err**
{"name":"Error","message":"Request failed with status code 422","stack":"Error: Request failed with status code 422\n    at createError (https://localhost:3000/static/js/5.chunk.js:38071:15)\n    at settle (https://localhost:3000/static/js/5.chunk.js:38292:12)\n    at XMLHttpRequest.handleLoad (https://localhost:3000/static/js/5.chunk.js:37546:7)"}

**err.response**
undefined

**Comment by paveleremin** [comment]
@phryneas 
So the issue is: I can get only a string or an object {message: string} in my catch(err) {} block
