### ISSUE TITLE
TS | createSlice | createAsyncThunk | normalizr | reducers not called

### ISSUE THREAD

**Issue by man-trifork** [reduxjs/redux-toolkit#569]
Hi all, I have a slice:

```
const boats = createSlice({
    name: 'boats',
    initialState: boatsAdapter.getInitialState({
        loading: LoadingState.idle
    }),
    reducers: {},
    extraReducers: builder => {
        builder.addCase(fetchBoats.pending, (state, action) => {
            console.log(action)
            state.loading = LoadingState.loading
        })
        builder.addCase(fetchBoats.fulfilled, (state, action) => {
            console.log(action)
            boatsAdapter.setAll(state, action.payload.boats)
        })

    }
})
```

a thunk:

```
const trip = new schema.Entity('trips')
const boat = new schema.Entity('boats', {
    trips: trip
})

const boatListSchema = new schema.Array(boat)
const boatsAdapter = createEntityAdapter()

export const fetchBoats = createAsyncThunk(
    'boats/index',
    async () => {
        const data = await boatService.index()

         const normalized =  normalize<
             any,
             {
                 boats: { [key: string]: Boat }
                 trips: { [key: string]: Trip }
             }
             >(data.data, boatListSchema)
         return normalized.entities
    }
)
```

The `extraReducers` are not called even though the action is dispatched:

<img width="730" alt="Screenshot 2020-05-20 at 03 03 37" src="https://user-images.githubusercontent.com/58421983/82390139-90720080-9a46-11ea-910a-edf9423f6861.png">

After hours of trial/error I cannot manage to make it work

**Comment by markerikson** [comment]
Silly question: is the `boatsSlice.reducer` actually added to your store?

Also, can you post a CodeSandbox that reproduces the issue?

**Comment by man-trifork** [comment]
@markerikson Do I have to add also the `caseReducers` to my store? 

Right now I am doing this: 

```
const { reducer } = boats
export default reducer
```

```
import {reducer as boats} from "../slices/boats"

const adminReducers = combineReducers({
    boats
})
```

**Comment by man-trifork** [comment]
> Also, can you post a CodeSandbox that reproduces the issue?

I felt like it is something that can be tracked easily. I will post a CS tomorrow.

**Comment by markerikson** [comment]
That should be sufficient.  If you've got something like `state.admin.boats` in the state tree, the reducer is hooked up and should be responding to those dispatched actions.

**Comment by man-trifork** [comment]
God, how did I miss that, thank you

**Comment by markerikson** [comment]
:)
