### ISSUE TITLE
Missing loading variable at the Documentation examples for createAsyncThunk using rejectWithValue

### ISSUE THREAD

**Issue by franjorub** [reduxjs/redux-toolkit#572]
Hi, I was reviewing the documentation for use createAsyncThunk for use it with axios and, in the examples for rejectWithValue there is a loading prop destructured from the selector, but that loading is not used in the code example and is not defined in the initial state.

Is not an issue at all, but I am new in the createAsyncThunk API and in the first attemp I was thinking that loading was injected by the thunk, but I confirm that is not the case because the first example has it defined already

![image](https://user-images.githubusercontent.com/24401350/82501590-7de9dc80-9ac3-11ea-993f-f58d4c53543c.png)

**Comment by msutkowski** [comment]
@franjorub Thanks, good catch.

**Comment by franjorub** [comment]
happy to help
