### ISSUE TITLE
Is there anyway to have the prepare function of a createAction be called as a response to an external action?

### ISSUE THREAD

**Issue by chanced** [reduxjs/redux-toolkit#577]
This is likely outside of the scope of Redux Toolkit but maybe its possible already. I'm using [next-redux-wrapper](https://github.com/kirill-konshin/next-redux-wrapper/) which has a hydrate action that gets dispatched in order to keep the SSR & client stores in sync.

That isn't a problem because slices come with `extraReducers` (awesome!). I just have to create one that handles the action for each slice which is ideal anyway. The only caveat is that I'm working in TypeScript and I'd like to use the builder strategy. That's somewhat problematic because the payload is the entirety of the root state. 

This works: 

```js
import { patch, diff } from 'jsondiffpatch';

const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
  //...
  },
  extraReducers: {
    [HYDRATE /* "__NEXT_REDUX_WRAPPER_HYDRATE__" */]: (state, action) => {
      if (action && action.payload && action.payload.auth) {
        const delta = diff(state, action.payload.auth);
        if (delta) {
          patch(state, delta);
        }
      }
    }
  }
})
```
But it doesn't provide typing and I can't use the builder strategy later on down the road. 

Ideally, I'd like to be able to do something like the code below but due to the action being external, the prepare function is never called.

```js

const hydrateAuth = createAction(HYDRATE, (hydration: Partial<RootState> | null) => {
  return {
    payload: hydration && hydration.auth ? hydration.auth : null
  };
});

const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
  //...
  },
  extraReducers: builder => 
    builder.addCase(hydrateAuth, (state, action) => {
      // determine how &  if data should be merged
      if(action.payload) {
         const delta = diff(state, action.payload);
         patch(state, delta)
      }
    })
  })
})
```

Just as an aside, thank you guys for putting redux-toolkit together. I took a rather long hiatus from development (several years). When I left, I was an early adopter of AngularJS and came back to React+Redux everrryyyyywhere. The patterns of Redux are clever but holy boilerplate! This package truly abstracts away a lot of the rituals surrounding state management in React and made the process of onboarding a lot easier. The tutorials are incredibly well written and easily digestible. There's no way I'd grok redux this quickly without the toolkit and the supporting documentation.

Kudos and thank you.

**Comment by markerikson** [comment]
Thanks for the positive feedback!

Yeah, the "prepare callbacks" are specifically internal to the action creator.  `createAction` is meant as a replacement for hand-written action creators, but it requires the calling code to pass in the entire payload by default.  Prepare callbacks restore the capability of customizing what goes into the action.

If I understand your use case right, I _think_ that your best bet would be to have the case reducer for this slice explicitly check `if(action.payload && action.payload.auth)`.  Technically, slice reducers don't "know" where they're going to be mounted in the state tree.  A reducer named `"a"` could be mounted as `combineReducers({ randomOtherName: reducerA})`, or even nested further inside the tree.

In practice, folks usually put their slice reducers at the obvious key name in the root state (ie, `combineReducers({auth: authReducer})`, and it's not unreasonable to go with that assumption in the code itself.  (This especially comes into play when writing selectors in a slice file that also accept the root state as an arg).

So, I'd just go ahead and have your hydration case reducer specifically check to see if the expected slice of state exists in the hydration action.

**Comment by chanced** [comment]
A case reducer for may make sense. For now, I'm going to try and maintain separation, where slices are solely responsible for their slice of the state.

This is a bit of extra code but it provides proper typings for the `builder`:

```js
const hydrateAuth = createAction(HYDRATE, (hydration: Partial<RootState> | null) => ({
  payload: hydration
}));
const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: { /*...*/ },
  extraReducers: builder => {
    builder.addCase(hydrateAuth, (state, action) => {
      if (action && action.payload && action.payload.auth) {
        const delta = diff(state, action.payload.auth);
        if (delta) {
          patch(state, delta);
        }
      }
    });
  }
});
```

Thank you for the feedback!
