### ISSUE TITLE
TypeScript error with wrapped "createSlice" + Reducer + Prepare function 

### ISSUE THREAD

**Issue by miguelCT** [reduxjs/redux-toolkit#580]
## Explanation
I am working with a custom wrapper created using the [documentation about wrapping `createSlice` in TS ](https://redux-toolkit.js.org/usage/usage-with-typescript#wrapping-createslice) and everything work as charm, but I'm having a problem with the **reducers with _"prepare"_ function**.

The main problem is, when I add an additional reducer to my wrapper instance that contains a "prepare" function, like this: 
```tsx
reducers: {
    multiply: {
      reducer: state => state,
      prepare: (value: number) => ({
        payload: value || 2
      })
    }
  }
```

In this case, there is something wrong with the type inference and the compiler tells the created action ("_multiply_") has the following signature when called with the param:

![image](https://user-images.githubusercontent.com/7680090/82805577-81df7b00-9e84-11ea-8c30-09611d0b5d4f.png)

Inferred signature:

![image](https://user-images.githubusercontent.com/7680090/82805378-3927c200-9e84-11ea-9b01-8fb1f334cca2.png)

So the action can't be called with any parameter, as the inferred parameters are `(...args: never[])`

This only reproduces with the **wrapped slices**. I tried the same code, but in a _"createSlice"_ and there is no problem.

## Playground
Here is a Condesandbox with the same code as the docs, where you can reproduce the previously explained:
https://codesandbox.io/s/rtk-wrapping-slice-prepare-9420g?file=/src/store/genericSlice.ts:1169-1203

### Related issues
I tried to find something similar a the stated here, but I couldn't find anything similar. Correct me if I'm wrong please.

Thanks in advance.

**Comment by phryneas** [comment]
Yeah. That's just the end of the magic there - something internal (don't ask me what) is probably throwing away some important type info there.

I got it to work by doing it this way:

```ts

const createGenericSlice = <T, Reducers extends SliceCaseReducers<GenericState<T>>>({
  name = "",
  initialState,
  reducers
}: {
  name: string;
  initialState: GenericState<T>;
  reducers: ValidateSliceCaseReducers<GenericState<T>, Reducers>;
}) => {
  const extension = {
    start(state: GenericState<T>) {
      state.status = "loading";
    }
  };

  return createSlice({
    name,
    initialState,
    reducers: {
      ...extension,
      ...reducers
    }
  }) as Slice<GenericState<T>, Reducers & typeof extension, typeof name>;
};
```

but you won't get around that final cast unfortunately.

**Comment by miguelCT** [comment]
Ah, well at least there is a solution. Maybe it's not the cleanest because of the final cast, but it "solves" the problem for now.

Maybe this issue should be kept open to until the internal types are reviewed? I know it might not be a common problem for other people, but just in case this is hiding other problems...

PD: Thanks for the fast response @phryneas :wink:

**Comment by phryneas** [comment]
From what I've gathered, this is not really a problem with our internal types, but a problem with TypeScript itself "losing" some type guarantees on spread & similar operations. We've had this with arrays (#552), but apparently it also happens with object spread in some situations, too.

It's not common enough to write additional helpers for this, which would be required for handling it, so I'll just close this for now.

**Comment by denchen** [comment]
Hi,

I know this issue is old and resolved, but I'm having a slight issue with the proposed solution by @phryneas . For the majority of my use cases, the solution perfectly fine. But if I try to override a default reducer, it doesn't pick up the new types. As an example, if I implement the `createGenericSlice()` as such:

```typescript
const createGenericSlice = <
  T,
  Reducers extends SliceCaseReducers<GenericState<T>>
>({
  name = '',
  initialState,
  reducers
}: {
  name: string;
  initialState: GenericState<T>;
  reducers: ValidateSliceCaseReducers<GenericState<T>, Reducers>;
}) => {
  const extension = {
    start(state: GenericState<T>) {
      state.isLoading = true;
    },
    update: {
      reducer(state: GenericState<T>, action: PayloadAction<T>) {
        state.data = action.payload;
        state.isLoading = false;
      },
      prepare(num: number) {
        return {
          payload: num
        };
      }
    }
  };

  return createSlice({
    name,
    initialState,
    reducers: {
      ...extension,
      ...reducers
    }
  }) as Slice<GenericState<T>, Reducers & typeof extension, typeof name>;
};

const myNewSlice = createGenericSlice({
  name: 'NEW_SLICE',
  initialState = { data: 0, isLoading: false },
  reducers: {
    update: {
      reducer(state: GenericState<T>, action: PayloadAction<T>) {
        state.data = action.payload;
        state.isLoading = false;
      },
      prepare(num: string) {
        return {
          payload: Number(num)
        };
      }
    }
  }
});
```

Then I try to use the overridden update function:

```typescript
myNewSlice.actions.update("4");
```

This will complain that "4" is not a `number`, even though `myNewSlice` overrides the update action. I'm not sure how to solve this.

**Comment by phryneas** [comment]
Probably something (untested) like this:

old:
```ts
as Slice<GenericState<T>, Reducers & typeof extension, typeof name>;
```
new:
```ts
as Slice<GenericState<T>, Omit<typeof extension, keyof Reducers> & Reducers, typeof name>;
```
