### ISSUE TITLE
Action creators with generic payload generators

### ISSUE THREAD

**Issue by viters** [reduxjs/redux-toolkit#584]
Recently I've been working on a use case, where I could benefit from specifying generic action payload generator, by which I mean something like:
```typescript
const action = createAction('code', <A extends string>(payload: A) => ({
  payload,
}));
```
Right now, such action payload generator will be reduced to super type `string` and the action generator will not be generic itself.

To introduce more specific example, I am working on a filters state and I have such code:

```typescript
enum OptionFilter {
  Language = 'Language',
}

enum RangeFilter {
  Price = 'Price',
}

type FilterKind = OptionFilter | RangeFilter;

type OptionFilterValue = string[];
type RangeFilterValue = [number, number];

type FilterValueKindMap = {
  [OptionFilter.Language]: OptionFilterValue;
  [RangeFilter.Price]: RangeFilterValue;
};

type FilterState = {
  [P in FilterKind]: FilterValueKindMap[P];
};
```

Such state allows me to easily implement a lot of filters with different types.
My initial thought was to create a type-safe action, which will allow to change value of any filter:
```typescript
const changeFilterValue = createAction(
  'changeFilterValue',
  <T extends FilterKind>(kind: T, value: FilterValueKindMap[T]) => ({
    payload: { kind, value },
  })
);
```

Sadly, this action generator will have flattened types and will become `(type: FilterKind, value: OptionFilterValue | RangeFilterValue)`. So this code throws no error:
```typescript
changeFilterValue(RangeFilter.Price, ['a']); // perfectly legal
```

Possible reason behind it may be that handling such action would be impossible from the reducer's perspective, because you would not know the specific types associated with action instance. 
Although I think the action generator itself should remain generic, but the generics could be flattened when handling such action in reducer. To be more specific:

```typescript
changeFilterValue(RangeFilter.Price, ['a']); // should throw a typescript error

// [...] within reducer
.addCase(changeFilterValue, (state, action) => {
    /** 
      action payload should have type
      { kind: OptionFilter | RangeFilter; value: string[] | [number, number]; }
      so it is my responsibility to handle payload using type guards if needed
    */
  })
);
```

Or maybe this type flattening is a TypeScript limitation?

**Comment by h0tw4t3r** [comment]
+1

Would be nice to have

**Comment by egorzekov** [comment]
I faced the same issue today.

Here is an example of logic I would like to implement:
```typescript
interface State {
  key1: string
  key2: boolean
}

const state: State = {
  key1: '',
  key2: false,
}

const doStuff = <T extends keyof State, K extends State[T]>(key: T, value: K): State => {
  const newState = { ...state }
  newState[key] = value

  return newState
}

doStuff('key1', '12') // ok
doStuff('key2', false) // ok

doStuff('key1', 2) //error
doStuff('key1', true) //error
doStuff('key2', 'invalid') //error
doStuff('key3', 'invalid') //error
```

Here the same stuff but with `redux-toolkit`:
```typescript
//state
export interface SettingsState {
  settingOne: boolean
  settingsTwo: string
}

// actions
const preparePayload = <T extends keyof SettingsState, K extends SettingsState[T]>(
  key: T,
  value: K
) => ({
  payload: {
    key,
    value,
  },
})

export const setSetting = createAction('SET', preparePayload)

// reducer
export default createReducer<SettingsState>(initialState, builder =>
  builder
    .addCase(actions.setSetting, (state, action) => {
      state[action.payload.key] = action.payload.value // error: TS2322: Type 'string | boolean' is not assignable to type 'never'.   Type 'string' is not assignable to type 'never'.
    })
)
```

**Comment by phryneas** [comment]
This is just not possible in TypeScript. We cannot detect if an action we get passed in is generic, so we cannot act on that.

=> I'm gonna close this one as I'm just cleaning up.

**Comment by NordlingDev** [comment]
Bit late to the party but this is how I solved it:

```ts
export const setAppConfigValue = ((action) => {
  return <K extends AppConfigItem>(key: K, value: AppConfigState[K]) => action(key, value);
})(
  createAction("appConfig/setValue", (key, value) => ({
    payload: { key, value },
  })),
);

```

**Comment by TimoLange98** [comment]
> Bit late to the party but this is how I solved it:
> 
> ```ts
> export const _untypedSetAppConfigValue = createAction("appConfig/setValue", (key, value) => ({
>   payload: { key, value },
> }));
> 
> export const setAppConfigValue = <K extends AppConfigItem>(key: K, value: AppConfigState[K]) =>
>   _untypedSetAppConfigValue(key, value);
> ```
> 
> I would use the `_untypedSetAppConfigValue` for passing to the reducer but expose `setAppConfigValue` as the dispatch action.

Thank you for this solution! Definitely works for most parts but I came across a problem: So I have set up the action the exact same way than you did. The code in my reducer looks like this:

```
...
.addCase(_updateFilterAction, (state, action) => {
      state.filter[action.payload.prop] = action.payload.value;
      state.filter.isInitialized = true;
    });
```
Actually here Im getting the error `Type 'any' is not assignable to type 'never'` width the `state.filter[action.payload.prop] `. 
This seems to happen because the `filter` object has properties which are of a string literal type. 

So this will work:
```
type Filter = {
  id: number;
  text: string;
}
```

This on the other hand throws the error:
```
type Country = 'us' | 'en'
type Filter = {
  ...
  countries: Country
}
```

If someone could tell me why that is I would really appreciate it!

Cheers

**Comment by moneydance** [comment]
Does https://redux-toolkit.js.org/usage/usage-with-typescript#createaction The withPayloadType example not solve for this?
