### ISSUE TITLE
Documentation: Usage with Typescript - createAction() Improved Clarity

### ISSUE THREAD

**Issue by majew7** [reduxjs/redux-toolkit#585]
In the [Usage with Typescript Documentation: createAction()](https://redux-toolkit.js.org/usage/usage-with-typescript#createaction) there is a sentence that reads:

> In some setups, you will need a literal type for action.type, though.

Currently this is confusing, because the need is not clear.  What is an example, of when  a literal string would be required/needed?  I'm very curious.

Thanks! :)

**Comment by phryneas** [comment]
In exactly the cases where you as a programmer decided to go that route and have an existing code base that relies on that feature ;)

Since TypeScript introduced type guards in 1.6 there isn't really any *need* (or benefit) to do so, but there are some established patterns that rely on it.
