### ISSUE TITLE
Typescript error when dispatching a thunk: Argument of type 'ThunkAction<void, CombinedState<...>>' is not assignable to parameter of type 'AnyAction'.

### ISSUE THREAD

**Issue by dvakatsiienko** [reduxjs/redux-toolkit#587]
I've followed the docs to setup typescript typings in redux app and struggled with this strange error.

Full typescript error:
```
Argument of type 'ThunkAction<void, CombinedState<{ MY_APP_STATE }>, unknown, Action<...>>' is not assignable to parameter of type 'AnyAction'.
  Property 'type' is missing in type 'ThunkAction<void, CombinedState<{ MY_APP_STATE }; }>, unknown, Action<...>>' but required in type 'AnyAction'.ts(2345)
```

The types that I use:

```
/* Core */
import { Action, ThunkAction } from '@reduxjs/toolkit';
import { useDispatch, useSelector, TypedUseSelectorHook } from 'react-redux';

/* Instruments */
import { rootReducer } from '../rootReducer';
import { initializeStore } from '../store';
import { authReducer } from '../domains/auth/reducer';

const store = initializeStore();

export type ReduxState = ReturnType<typeof rootReducer>;
export type AuthStateType = ReturnType<typeof authReducer>;

export type TypedDispatch = typeof store.dispatch;
export type TypedThunk<R = void> = ThunkAction<R, ReduxState, unknown, Action>;

export const useTypedDispatch = () => useDispatch<TypedDispatch>();
export const useTypedSelector: TypedUseSelectorHook<ReduxState> = useSelector;
```

How thunk is used with `dispatch`:
```
...
import {
    useTypedDispatch,
} from '@/lib/redux';

const LoginPage: NextPage = () => {
    const dispatch = useTypedDispatch();
    useEffect(() => {
        ...
        await dispatch(signInAsync(decodedEmail, decodedPassword)); // Error here
        ...
```

Pretty much strange because `dispatch` that is available inside of a thunk function seems to work okay.
Tried to mark third argument of ThunkAction<R, ReduxState, `unknown`, Action> as `unknown` as suggested one of the issues but that did't worked for me.

**Comment by phryneas** [comment]
How are your `initializeStore` and `signInAsync` looking?

**Comment by dvakatsiienko** [comment]
@phryneas `initializeStore` is a function that retruns `configureStore` invocation (I use `nextjs` with `redux` and `apollo` bindings`

```
/* Core */
import { configureStore } from '@reduxjs/toolkit';

/* Instruments */
import { rootReducer } from './rootReducer';
import { middleware } from './middleware';
import { initialState as authInitialState } from './domains/auth/reducer';

const initialState = {
    auth: authInitialState,
};

export const initializeStore = (preloadedState = initialState) => {
    return configureStore({
        reducer: rootReducer,
        preloadedState,
        middleware,
    });
};
```

And here is `signInAsync`:

```
/* Instruments */
import { TypedThunk } from '@/lib/redux';

/* Actions */
import {
    setAuthFetching,
    setAuthStep,
    setFirstLogin,
    setAuthenticated
} from '../actions';

export const signInAsync = (
    email: string,
    password: string,
): TypedThunk => async dispatch => {
    dispatch({ type: 'SIGN_IN_ASYNC' });
    dispatch(setAuthFetching(true));

    // ... rest of the thunk
    
    dispatch(setAuthenticated(true));
    await dispatch(saveRefreshTokenAsync()); // there is no `dispatch` error with thunk here

   // ... rest of the thunk
};
```

**Comment by phryneas** [comment]
Okay, next step is your `middleware` declaration (I had hoped that would already be in there) - because the `Dispatch` type correlates directly to the `middleware` array given there. Also, please hover over that `middleware` array and determine what type it currently is.
It should be something along the lines of `Array<Middleware<{}, ReduxState, {}> | ThunkMiddleware<ReduxState, AnyAction, unknown>>` - so `ThunkMiddleware` should be explicitly mentioned as possible array member.

**Comment by dvakatsiienko** [comment]
@phryneas Oh yes, missed that, sorry. Here is the `middleware` file:

```
/* Core */
import { Middleware, getDefaultMiddleware } from '@reduxjs/toolkit';

/* Instruments */
import { ReduxState } from './types';

const middleware: Middleware[] = [ ...getDefaultMiddleware<ReduxState>() ];

if (__DEV__) {
    const { createLogger } = require('redux-logger');

    const logger = createLogger({
        duration:  true,
        timestamp: false,
        collapsed: true,
        colors:    {
            title:     () => '#139BFE',
            prevState: () => '#1C5FAF',
            action:    () => '#149945',
            nextState: () => '#A47104',
            error:     () => '#ff0005',
        },
        predicate: () => process.browser,
    });

    middleware.push(logger);
}

export { middleware };
```

And here is on-hover tooltip of `middleware` variable:

```
const middleware: Middleware<{}, any, Dispatch<AnyAction>>[]
```

**Comment by phryneas** [comment]
Yup, you got it!

Type erasure by explicitly defining a type ;)

Maybe that's a good thing in general: TS is great at inferring types, you should only ever define variable types if really necessary ;)

**Comment by shinoshu** [comment]
TypeScript is type puzzle.

**Comment by markerikson** [comment]
@boy51 : actually, you should _not_ manually spread the middleware. Instead, call `getDefaultMiddleware().concat(myMiddleware)`, which is a specially-typed version of `Array.concat()` that better retains the types.

**Comment by boy51** [comment]
Thanks, I updated my comment :)

Finally I can sleep peacefully knowing my dispatch is strongly typed.

**Comment by potatoqualitee** [comment]
This thread helped me fix my own problem, thank you both so much!

**Comment by ryanrouleau** [comment]
For anyone that is still having issues: make sure your `@reduxjs/toolkit` and `redux` versions are compatible 😮‍💨

**Comment by RaillyH** [comment]
If anyone is using only `redux` and `redux-thunk`, here is my solution:

```ts
/* Core */
import { useDispatch, useSelector, TypedUseSelectorHook } from 'react-redux';
import { createStore, applyMiddleware, AnyAction } from 'redux';
import { composeWithDevTools } from '@redux-devtools/extension';

/* Instruments */
import thunk, { ThunkAction, ThunkDispatch } from 'redux-thunk';
import { rootReducer } from './reducer';
import { logActions } from './middlewares';

/* Store */
export const store = createStore(
  rootReducer,
  composeWithDevTools(applyMiddleware(thunk, logActions)),
);

/* Types */
export type AppDispatch = typeof store.dispatch;
export type ReduxState = ReturnType<typeof rootReducer>;
export type TypedDispatch = ThunkDispatch<ReduxState, any, AnyAction>;
export type TypedThunk<ReturnType = void> = ThunkAction<
  ReturnType,
  ReduxState,
  unknown,
  AnyAction
>;
export const useTypedDispatch = () => useDispatch<TypedDispatch>();
export const useTypedSelector: TypedUseSelectorHook<ReduxState> = useSelector;


```

**Comment by daominhsangvn** [comment]
For any persion who getting this issue, i have tried all above method and none of them are working to me but except the below one:

```
const store = configureStore({
  ...
  middleware: getDefaultMiddleware => getDefaultMiddleware(), //->> This is the magical happen.
});
```

Note: I have not install `redux` in my project because the toolkit already have it as dependencies

**Comment by pgross41** [comment]
> @boy51 : actually, you should _not_ manually spread the middleware. Instead, call `getDefaultMiddleware().concat(myMiddleware)`, which is a specially-typed version of `Array.concat()` that better retains the types.

This fixed mine!!! I could dispatch via `useDispatch` but it didn't like calling thunks from thunks until I changed my middleware definition. I never would have figured that out, thanks!

**Comment by dulara1994** [comment]
@boy51 could you show an example for your scenario?
