### ISSUE TITLE
createAsyncThunk customize rejected error serialization

### ISSUE THREAD

**Issue by orenklein** [reduxjs/redux-toolkit#588]
There are some scenarios in which I would want to globally 'listen' to rejected enhanced errors and act upon them (for the current example - act with logging and dispatching general global error action). 

The current SerializedError automatically added to rejected action is as follows:
```
interface SerializedError {
  name?: string
  message?: string
  code?: string
  stack?: string
}
```

CommonAPIError might contain other significant information and there's no easy way to enhance it.

Assuming we have an API and we're creating async thunk for each endpoint. 
Adding rejectWithValue to the end of each payloadCreator after enhancing the error will result in code repeating

As for the 'listening' and acting options I thought of - 
1. using middleware/redux-saga/redux-observable - listen to every action that its type contains '/rejected' and act
2. add beforeRejection callback to payloadCreator promise chain as a workaround which will also allow enhancing the error

To get rid of the repeating I implemented the second option:

//storeHelpers.ts
```
import { createAsyncThunk } from '@reduxjs/toolkit';
import { AppDispatch } from 'app/store';
import { actions as globalErrorActions } from './reducers/globalError';

export function createAsyncThunkWithBeforeRejectionFactory(
    beforeRejection: (err: any, dispatch: AppDispatch) => void
) {
    let createAsyncThunkWithBeforeRejection: typeof createAsyncThunk = function (
        typePrefix,
        payloadCreator,
        ...rest
    ) {
        let payloadCreatorBeforeRejection: typeof payloadCreator = (...args) => {
            return Promise.resolve(payloadCreator(...args)).catch((err) => {
                beforeRejection(err, args[1].dispatch);
                throw err;
            });
        };

        return createAsyncThunk(typePrefix, payloadCreatorBeforeRejection, ...rest);
    };
    return createAsyncThunkWithBeforeRejection;
}


export const createAsyncThunkGlobalError = createAsyncThunkWithBeforeRejectionFactory(
    (err, dispatch) => {
        // handleGlobalAPIError is where you act on global error (logging, dispatch other actions, etc..)
        dispatch(globalErrorActions.handleGlobalAPIError(err));
    }
);

```

// reducers/authSlice.ts
```
const registerUser = createAsyncThunkGlobalError(
    'auth/registerUser',
    async (payload, ThunkAPI) => {
        try {
            await myApi.registerUser(payload);
        } catch (err) {
            let error: Error | myApi.ErrorsTypes = err;

            // specific errors to be handle by caller
            if (error instanceof myApi.ValidationError) {
                return ThunkAPI.rejectWithValue(error.detail);
            }  else if (error instanceof myApi.AuthenticationError) {
                return ThunkAPI.rejectWithValue(error.detail);
            }
            //any other not handled error
            throw err;
        }
    }
);
```

It is a weird workaround and I'm not satisfied with it at all. 
Any other suggestions?
Should error serialization be configurable?
Perhaps it is too much flexibility needed from an opinionated library (redux-toolkit), and maybe it is not that bad to repeat yourself in that case (rejectWithValue in each payloadCreator).

**Comment by phryneas** [comment]
Honestly, that's a fine solution for your specific problem.

You could also do a wrapper along the lines of (pseudocode from the back of my head)


```
function handleRejections(fn) {
	return (arg, api) => {
		try {
			return fn(arg, api);
		} catch {
			return api.rejectWithError(/* your logic */)
		}
	}
}

const asyncThunk = createAsyncThunk(handleRejection(myApi.registerUser));
```

The thing is: the idea behind RTK is to make the 80% use case easy. Personally, I feel adding some kind of generic extra error-handling doesn't really play into those 80% and would make the api a lot more confusing - especially as `api.rejectWithError` is already a thing.

So I'd say we won't probably add any more logic at this point - the building blocks are there after all.

I hope you understand :)
