### ISSUE TITLE
Error while using createAsyncThunk with redux-persist 

### ISSUE THREAD

**Issue by rikinshah23** [reduxjs/redux-toolkit#589]
Hi All,

I intend to persist user state after login. 
Currently, I can login but when reload the app, it starts from login screen. 

I am using redux-toolkit and creating authSlice to call login api.

**my authSlice.js** 
```
import {createSlice, createAsyncThunk} from '@reduxjs/toolkit';
import {doLogin} from '../../../services/UserServices';

// First, create the thunk
export const signInAsync = createAsyncThunk(
  'auth/signInAsync',
  async (args, thunkAPI) => {
    console.log('args', args);
    const response = await doLogin(args.userName, args.password);
    console.log(response);
    return response;
  },
);

export const signOutAsync = createAsyncThunk(
  'auth/signOutAsync',
  async (args, thunkAPI) => {
    return null;
  },
);

// Then, handle actions in your reducers:
const slice = createSlice({
  name: 'auth',
  initialState: {
    user: null,
    isLoading: false,
    error: null,
    errMessage: null,
    token: null,
    tokenExpiryInSeconds: null,
  },
  reducers: {
    storeUser: (state, action) => {
      state.user = action.payload;
    },
    storeRefreshToken: (state, action) => {
      console.log(action.payload);
      state.token = action.payload;
      state.tokenExpiryInSeconds = action.payload;
    },
    clearErrMessage: (state) => {
      state.errMessage = null;
    },
  },
  extraReducers: {
    // Add reducers for additional action types here, and handle loading state as needed
    [signInAsync.pending]: (state, action) => {
      state.errMessage = null;
      state.isLoading = true;
    },
    [signInAsync.fulfilled]: (state, action) => {
      state.errMessage = null;
      state.user = action.payload;
      state.isLoading = false;
    },
    [signInAsync.rejected]: (state, action) => {
      if (action.error && action.error.code) {
        state.errMessage = 'Invalid email or password!';
      } else {
        state.errMessage = 'Error occurred during login';
      }
      state.isLoading = false;
    },
    [signOutAsync.pending]: (state, action) => {
      state.error = null;
      state.isLoading = true;
    },
    [signOutAsync.fulfilled]: (state, action) => {
      state.error = null;
      state.user = null;
      state.token = null;
      state.tokenExpiryInSeconds = null;
      state.isLoading = false;
    },
    [signOutAsync.rejected]: (state, action) => {
      state.error = action.error;
      state.isLoading = false;
    },
  },
});

export const {storeUser, clearErrMessage, storeRefreshToken} = slice.actions;

export default slice.reducer;

```

Here is my store file: 
```
import {configureStore, createStore} from '@reduxjs/toolkit';
import authReducer from '../features/login/authSlice';
import AsyncStorage from '@react-native-community/async-storage';
import {persistReducer, persistStore} from 'redux-persist';
import {combineReducers} from 'redux';
// import hardSet from 'redux-persist/lib/stateReconciler/hardSet';
// import autoMergeLevel2 from 'redux-persist/lib/stateReconciler/autoMergeLevel2';

const reducers = combineReducers({
  auth: authReducer,
  // other reducers goes here...
});

const persistConfig = {
  key: 'root',
  storage: AsyncStorage,
  //stateReconciler: hardSet,
};

const _persistedReducer = persistReducer(persistConfig, reducers);

export const store = createStore(_persistedReducer);
export const persistor = persistStore(store);
```

my main index.js file where I use PersistGate: 
```

import React from 'react';
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import {setCustomTextInput, setCustomText} from 'react-native-global-props';
import {store, persistor} from './src/stores/store';
import {Provider} from 'react-redux';
import {PersistGate} from 'redux-persist/lib/integration/react';

const RNRedux = () => (
  <Provider store={store}>
    <PersistGate loading={null} persistor={persistor}>
      <App />
    </PersistGate>
  </Provider>
);

AppRegistry.registerComponent(appName, () => RNRedux);

```

When I click login button, it says : 

`Error: Actions must be plain objects. Use custom middleware for async actions.`

I realize I am not configureStore() anywhere. where should I configure it?

I am not sure how do I understand the error. could anyone please help me understand and point mistakes in my code? Thanks

**Comment by rikinshah23** [comment]
Turned out I was not passing middleware in store configuration. 
Since I was using thunk, I passed it like so: hope it will be helpful to someone else. 

```
// using thunk middleware
export default configureStore({
  reducer: _persistedReducer,
  middleware: [thunk],
});
```

**Comment by markerikson** [comment]
@rikinshah23 unless you're actually customizing the middleware somehow, you shouldn't pass a `middleware` parameter at all.  `configureStore` will add the thunk middleware, and some others, automatically.  However, your previous code snippet showed you were using the original Redux `createStore` API, not `configureStore`, which would explain the problem.

**Comment by rikinshah23** [comment]
@markerikson thanks for your comment. its helpful to understand the concept. 

Although when I try comment out middleware it gives me below error. 

![Uploading image.png…]()

const reducers = combineReducers({
  auth: authReducer,
  home: homeReducer,
  // other reducers goes here...
});

const persistConfig = {
  key: 'root',
  storage: AsyncStorage,
};

const _persistedReducer = persistReducer(persistConfig, reducers);

// using thunk middleware
export default configureStore({
  reducer: _persistedReducer,
  // middleware: [thunk],
});

**Comment by markerikson** [comment]
The issue is exactly what the error is telling you.  `redux-persist` sends non-serializable values in via actions.  You need to use the `getDefaultMiddleware()` option to tell the serializability check middleware to ignore those.

Please see https://github.com/rt2zz/redux-persist/issues/988#issuecomment-552242978 for instructions.

**Comment by rikinshah23** [comment]
Thanks a lot @markerikson 

I used` getDefaultMiddleware()` to set serializableCheck as false. and my app store is working fine now, without adding extra middleware. 

```
export default configureStore({
  reducer: _persistedReducer,
  middleware: getDefaultMiddleware({
    serializableCheck: false,
  }),
});
```

Kindly suggest if it still looks incorrect.

**Comment by markerikson** [comment]
I personally would suggest adding the `redux-persist` actions to the ignored list for that middleware, rather than turning it off entirely.  It's there to prevent common mistakes.  But, up to you.

**Comment by rikinshah23** [comment]
I am fairly new to configure store for the app and redux tools as whole.
so I followed your suggested comment above and added only redux-persist actions in ignore list. 

```
export default configureStore({
  reducer: _persistedReducer,
  middleware: getDefaultMiddleware({
    serializableCheck: {
      ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
    },
  }),
}); 
```

Again thanks for your time.
