### ISSUE TITLE
Add more documentation

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#59]
We now have a published docs site at https://redux-starter-kit.js.org , and I've moved the API reference content from the README over to there.

However, the API doc pages are pretty short with only some simple examples, and they don't go into very much depth.

It would be great if we can expand those pages with more descriptive content.

I'd also like to see some example projects set up showing how to use this in action.  One idea would be to base it off of a recent project shown on Reddit [that I refactored to make use of RSK](https://www.reddit.com/r/reactjs/comments/a0b1sa/frustrated_with_redux_so_i_created_abredux_vs/).

**Comment by denisw** [comment]
During the TypeScript rewrite, I started extending and refining the current API docs a bit within the doc comments. I am currently drafting extended docs pages for the various functions based on these efforts. I'll make sure to create small PR's as I go.

**Comment by markerikson** [comment]
Just added a "Usage Guide" page in #105 :

https://redux-starter-kit.js.org/usage/usage-guide

Definitely still need some tutorial-like examples, though.

**Comment by matthewsecrist** [comment]
Is there anything specific you're looking for in a tutorial? I'm interested in helping, but not sure what kind of tutorials/apps you're looking for.

**Comment by markerikson** [comment]
@matthewsecrist : Thanks!  Yeah, I'd specifically like to see two tutorial pages that walk through actually using RSK:

- Creating a new Redux project from scratch
- Updating an existing Redux project to use RSK

As part of that, it would be good to show how thunks and other side effects fit in (since we've had some people recently asking if it's possible to "add thunks to slices" - see #76 ).

For the "existing app" project, I was considering using a slightly slimmed-down version of this app's codebase: https://github.com/productioncoder/youtube-react/issues/1 .

The "new" app probably doesn't have to be overly complex either.

**Comment by matthewsecrist** [comment]
Gotcha, I'll play around with it and see what I can come up with. :)

**Comment by markerikson** [comment]
Great!  Yeah, just lemme know here if/when you get started on something and we can coordinate.

**Comment by matthewsecrist** [comment]
Not sure if you're looking for something more complex than this, but I made https://github.com/matthewsecrist/ChooseAWinner which is just a simple app that will let the user add a list of things and then it chooses items from the list and puts them into a different list. It makes use of `createSlice` and shows off both the "mutative" and traditional ways of updating the state.

**Comment by markerikson** [comment]
@matthewsecrist : it's a potential starting point, yeah.  would be nice to expand it a bit, maybe add another slice or two, and have some actions that get handled by both slices.

**Comment by matthewsecrist** [comment]
Yeah, I didn't know if you wanted something real basic to show off setup and such or something a bit more complex. What about something more like https://github.com/matthewsecrist/github_viewer ? Still needs some cleanup and refactoring right now, but is that more of what you're looking for?

**Comment by markerikson** [comment]
The tutorial aspects are now mostly covered. I've got a "Basic" and "Intermediate" tutorial added, and will be doing an "Advanced" one shortly.

Another suggestion: add a "Migration" page comparing what RSK offers vs core Redux.

**Comment by markerikson** [comment]
Finished the "Advanced" tutorial: https://redux-starter-kit.js.org/tutorials/advanced-tutorial .

I think this is actually mostly good for now.  Really, the "Examples and Tutorials" link ought to be cleaned up or removed.

**Comment by MikeYermolayev** [comment]
Hi all, it would be really cool if some examples are added about how to fix circular imports. Because currently docs have a nice example demonstrating the issue but no words about how to deal with them in scope of RSK.

Personally for me circular imports are the biggest issue I've faced right now using the RSK so would like to see some 'best practices' on how people used to fix them.
Thanks

**Comment by markerikson** [comment]
@MikeYermolayev : hmm.  Interesting point.

In general, breaking circular dependencies usually involves moving certain values out into a separate file, and having both the main files import that one.  Michel Weststrate gave some suggestions in his post [How to fix nasty circular dependency issues in JS](https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de).

Specifically, you could:

- Add a separate `commonActions` file, define your action creators with `createAction()` in there, and have both slice files import those and reference them in the `extraReducers` section
- Write the `reducers` section as normal in both slices, but hand-write the expected action constants from the other file in the `extraReducers` section rather than relying on the value of `someActionCreator.type`

**Comment by MikeYermolayev** [comment]
Your first suggestion sounds like the same thing if I use `createReducer` instead of `createSlice` and describe actions with `createAction` in separate file. So this is what I ended up with
Instead of having one `todos.slice.js` I switched to having `todos.reducer.js` and `todos.actions.js`
Thanks for the tip 🙏

**Comment by markerikson** [comment]
We've got a "Usage with TS" page thanks to @phryneas .

At this point I think we're fairly good on docs page for now.  Totally open to suggestions and improvements, though.  

Anything else obvious that _needs_ to be added, as far as new pages or topics?

**Comment by LoiKos** [comment]
Hello @markerikson,

I was looking for good practices on nested Slices/Reducers. I'll explain my case : I have a complex form handle by a slice. Managing every part of the form inside one only slice create a lots of actions, selectors on the same file.  I suppose that the recommending way is to build for each part a slice and then combine them with `combineReducers` but I think it could be great to add a section that explain how to cut a large functionality into little slice that easy to manage
