### ISSUE TITLE
Type for state

### ISSUE THREAD

**Issue by seanaguinaga** [reduxjs/redux-toolkit#590]
This is a question but I have no idea where to ask it

This is simply the code in the create-react-app template

```import { createSlice } from "@reduxjs/toolkit";

export const counterSlice = createSlice({
  name: "counter",
  initialState: {
    value: 0,
  },
  reducers: {
    increment: (state) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
    incrementByAmount: (state, action) => {
      state.value += action.payload;
    },
  },
});

export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched
export const incrementAsync = (amount: number) => (dispatch: Function) => {
  setTimeout(() => {
    dispatch(incrementByAmount(amount));
  }, 1000);
};

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state) => state.counter.value)`
export const selectCount = (state) => state.counter.value;

export default counterSlice.reducer;

```

**How would I type this in TypeScript?**

<img width="799" alt="Screen Shot 2020-06-03 at 4 58 01 PM" src="https://user-images.githubusercontent.com/15254340/83700398-970e8500-a5bb-11ea-947f-825c46a02e76.png">

**Comment by markerikson** [comment]
Please see these resources:

- https://redux.js.org/recipes/usage-with-typescript
- https://redux-toolkit.js.org/usage/usage-with-typescript
- https://github.com/reduxjs/cra-template-redux-typescript

**Comment by seanaguinaga** [comment]
Unfortunately that does not help with this issue regarding slices.

Since types are inferred and how that is done is hidden there don't seem to be any instructions on how to get typescript to infer or get the real shape of the state even with such a simple example like a counter

<img width="779" alt="Screen Shot 2020-06-04 at 11 45 58 AM" src="https://user-images.githubusercontent.com/15254340/83798610-5b29fd00-a659-11ea-942b-e800c2dfd64e.png">

**Comment by markerikson** [comment]
Those pages do cover this question.  You need to export a `RootState` type from your store setup, import that here, and use it with the selector:

https://redux-toolkit.js.org/usage/usage-with-typescript#getting-the-state-type

And the TS template I linked does exactly that in this same file:

- https://github.com/reduxjs/cra-template-redux-typescript/blob/936939be276f9a05c21df9ae862988a6a9cbdf9b/template/src/app/store.ts#L10
- https://github.com/reduxjs/cra-template-redux-typescript/blob/936939be276f9a05c21df9ae862988a6a9cbdf9b/template/src/features/counter/counterSlice.ts#L48
