### ISSUE TITLE
keep original state with filter in reducer slice

### ISSUE THREAD

**Issue by hellsingblack** [reduxjs/redux-toolkit#591]
I thing I misundestand something

I tried to filter my state for a search feature like this in a slice reducers

```
const equipments = createSlice({
  name: 'equips',
  initialState: {
    entities: [],
  },
  reducers: {
    searchEquipments: (state, action) => {
      const filterEntities = state.entities.filter(
        (entitie) => entitie.name.toLowerCase().indexOf(action.payload.toLowerCase()) !== -1,
      );

      state.entities = filterEntities;
    },
  },
```

However the probleme is  `state.entities = filterEntities` mutate state. How can I filter state in reducer slice ?

Thanks a lot

**Comment by phryneas** [comment]
The idea of a reducer is to mutate state. If you don't want to mutate the state, you most likely want to use a filtering selector instead.

Generally, please keep in mind that this is a bug/issue tracker and not a support forum. 
For questions, please join the discord Reactiflux #redux channel or ask questions on stackoverflow. 
We (and lots of other members of the community) will gladly help you there.

Meanwhile I'll close this.
