### ISSUE TITLE
IE11 - Object.isFrozen: argument is not an object

### ISSUE THREAD

**Issue by michael-haberzettel** [reduxjs/redux-toolkit#592]
Hello,

I've encoutered an issue with redux-toolkit and IE11. **The following error occurs when starting webpack dev server. Fortunatly the problem doesn't exist in bundled app !**

The error : 
`Object.isFrozen: argument is not an object`

After some investigation, this error seems to be related to immer library : https://github.com/immerjs/immer/issues/600. A fix has been published in version 6.0.6

After manual setting the latest version of immer in internal dependencies of redux-toolkit, my application works again.

Would it be possible to update the version of immer in your library ?

PS : sorry for my poor english.

**Comment by markerikson** [comment]
We already specify ` "immer": "^6.0.1",`, so it's just a question of when you happened to install or update the dependencies in your own project.

**Comment by michael-haberzettel** [comment]
Thank you for your response. Indeed an update was enough to solve the problem.
