### ISSUE TITLE
redux-toolkit.esm has no exported member PayloadAction

### ISSUE THREAD

**Issue by telaviv** [reduxjs/redux-toolkit#600]
Let me start by saying, I'm sure this is a configuration issue, but I can't find any information about this and I'm not even sure where to start debugging. 

I have some code like this:
```
import { createSlice, PayloadAction } from '@reduxjs/toolkit'
import { Card } from 'engine'

export default createSlice({
    name: 'selectedCard',
    initialState: null as Card | null,
    reducers: {
        setCard: (state, { card }: createAction.PayloadAction<Card>) =>
            card.payload,
        clearCard: () => null,
    },
})
```

And errors like this: 
```
[tsl] ERROR in /home/shawn/dev/card-dungeon-redux/client/reducers/selectedCard.ts(1,23)
      TS2305: Module '"../../node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm"' has no exported member 'PayloadAction'.
```

When I look at the `redux-toolkit.esm` I in fact see no exported member called `PayloadAction`. I don't see a `types.d.ts` with global types. I'm not sure how I'm supposed to get access to this guy. 

Maybe a related issue, but I'm also getting issues with the type in `state` in the `createSlice` definition.

```
[tsl] ERROR in /home/shawn/dev/card-dungeon-redux/client/reducers/selectedCard.ts(8,19)
      TS7006: Parameter 'state' implicitly has an 'any' type.
```

Here is my tsconfig:
```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "noImplicitAny": true,
    "module": "es6",
    "target": "es5",
    "jsx": "react",
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "allowJs": true
  },
  "include": [
    "client/**/*",
    "common/**/*"
  ]
}
```

**Comment by markerikson** [comment]
Since it's an ESM module, it's plain JS, with no type information.  The type data is all in `typings.d.ts`, as you can see here: https://unpkg.com/browse/@reduxjs/toolkit@1.3.6/dist/typings.d.ts .

It's definitely a configuration issue of some kind, because TypeScript should be looking at our `package.json` file to see the `typings` field, and following that to `dist/typings.d.ts`.  No idea why TS isn't picking that up, and why it's thinking that `PayloadAction` is an actual export instead of a type.

**Comment by telaviv** [comment]
The solution was adding this line to my config `"moduleResolution": "node"`. Honestly not sure how I got this far without that .... Anyway thanks @markerikson that was actually really helpful to get me to debug this properly!

**Comment by Oogarchenko** [comment]
> The solution was adding this line to my config `"moduleResolution": "node"`. Honestly not sure how I got this far without that .... Anyway thanks @markerikson that was actually really helpful to get me to debug this properly!

didn`t work for me, still have exact same error

**Comment by SenselessA** [comment]
didn`t work for me +
`TS2305: Module '"../../../../Work/face2action.web2.0/node_modules/@reduxjs/toolkit/dist"' has no exported member 'PayloadAction'.`

**Comment by AbreezaSaleem** [comment]
+1. need a solution for this

**Comment by phryneas** [comment]
We will need a reproduction repo - since it's working just finde for us we have no way of replicating it. And please, open a new issue if you have one. This has been solved.

**Comment by DevPowers** [comment]
Updating to a newer version of Typescript worked for me
