### ISSUE TITLE
Getting "is not a function" error while trying to access state

### ISSUE THREAD

**Issue by Luisdv93** [reduxjs/redux-toolkit#601]
I'm having a issue accessing my state, basically I want to update the property of an object inside my array. Similarly to the Intermediate Tutorial which shows this:

```
import { createSlice } from '@reduxjs/toolkit'

const todosSlice = createSlice({
  name: 'todos',
  initialState: [],
  reducers: {
    addTodo(state, action) {
      const { id, text } = action.payload
      state.push({ id, text, completed: false })
    },
    toggleTodo(state, action) {
      const todo = state.find(todo => todo.id === action.payload)
      if (todo) {
        todo.completed = !todo.completed
      }
    }
  }
})

export const { addTodo, toggleTodo } = todosSlice.actions

export default todosSlice.reducer
```

My state is something like this:

```
import { createSlice } from '@reduxjs/toolkit'

const propertiesSlice = createSlice({
  name: 'properties',
  initialState: {
    properties: [],
    loading: true,
    error: false,
  },
  reducers: {
    toggleCheck(state, action) {
      const id = action.payload.id;

      const property = state.properties.find(p => p.id === id)

      if (property) {
        property.checked = !property.checked
      }
    }
  }
})

export const { toggleCheck } = propertiesSlice.actions

export default propertiesSlice.reducer
```

I'm getting the following error, which is weird because I have around 30 reducers and it's my first time having this problem.

![image](https://user-images.githubusercontent.com/7731089/84425718-07d32400-abf0-11ea-957a-32fa7c1707b7.png)

**Comment by Luisdv93** [comment]
Ok. Seems like the issue was on my part, another nesting level I wasn't aware of.

**Comment by Tellefsonjr** [comment]
Hi @Luisdv93  - any chance you can elaborate on your issue? I'm running into the same thing and cannot find where a nesting issue may be happening..

**Comment by Luisdv93** [comment]
> Hi @Luisdv93 - any chance you can elaborate on your issue? I'm running into the same thing and cannot find where a nesting issue may be happening..

Hi @Tellefsonjr. This happened more than a year ago so I may be wrong but I was mistakenly setting the new state to state.properties instead of setting it to just the state. Basically check the reducer where you're setting the state you're having problems with and make sure you're not wrongly setting to a deeper level in the state object. 

Hope this helps.

**Comment by sokoya** [comment]
That should be state.properties.properties
