### ISSUE TITLE
Store.replaceReducer() re-call all previous actions

### ISSUE THREAD

**Issue by thongdoan** [reduxjs/redux-toolkit#611]
Dear Redux Toolkit,

Thanks for awesome library.
But today, i got an issue: Store.replaceReducer() re-call ALL previous ACTIONS.
Finally, i found that it is because of Redux-DevTools, it re-call all actions when Redux dispatch ActionTypes.REPLACE in Store.replaceReducer:

```
Redux DevTools:

if (/^@@redux\/(INIT|REPLACE)/.test(liftedAction.type)) {

   if (options.shouldHotReload === false) {
    // CLEAR HISTORY
   }
...
REPEAT ACTIONS
...
}
```

Please consider make shouldHotReload = false or document it. Maybe it will help someone, it was take my day(debug, looking on react,  redux, redux dev-tools source code) to found that.

Thanks,

**Comment by markerikson** [comment]
I'm not clear what you're asking for here.

Your reducer shouldn't care how many actions are being dispatched, or if they're being sent from the actual app or the Redux DevTools.

In addition, the DevTools are not part of RTK itself, we just use them in RTK.

**Comment by thongdoan** [comment]
My mean that it wasted my time and maybe will waste time of others. 
Because you recommend people to use DevTools, so you should say about it in your documents

When i call store.replaceReducer(), it re-dispatch previous actions (all old actions). 


`@Your reducer shouldn't care how many actions are being dispatched, or if they're being sent from the actual app or the Redux DevTools.`

Example:

- 1h30 AM, I clicked  Button1, my screen is show: Last Click Time  on Button1 = 1h30 AM,
- At 2h00 AM, when click Button2 to call store.replaceReducer, it show: Last Click Time on Button1: 2h00 AM, because of DevTools republish all previous actions in this time

```
onUserClick: (state, action)=> {
     state.clickedTime = date.now(); 
}
```
..

**Comment by phryneas** [comment]
I'm sorry to say this, but this is a bug in your reducer.

You see, Redux assumes your reducer to be pure. So executing the same reducer with the same input any times should, free of any side effects, result in the same state.

If you are using `Date.now()` (or `Math.random()`, or a counter that is stored outside of your state) in your reducer, you are violating that rule. 

This is explicitly stated in the [reducer documentation](https://redux.js.org/basics/reducers#handling-actions):

> Things you should never do inside a reducer:
>
>   * Mutate its arguments; (granted, this is allowed/expected in RTK opposed to plain redux)
>   * Perform side effects like API calls and routing transitions;
>   * Call non-pure functions, e.g. Date.now() or Math.random().

Doing so nonetheless results in the problems you have encountered - and also in the future might cause problems with other store enhancers than the redux devtools.

**Comment by thongdoan** [comment]
Thanks you very much for the explanation. 

It refreshes my brain, i will try to restore shouldHotReload = true.

Thanks again,

**Comment by phryneas** [comment]
If you have any of those problems in the future, come over to the #redux channel in [Reactiflux](https://discord.gg/jTBrng) and just ask some questions. There are a lot of people there that can help you :)

**Comment by thongdoan** [comment]
thanks you, i will do it :)
