### ISSUE TITLE
Redux toolkit reducers created using 'createSlice' stripping out line breaks in text?

### ISSUE THREAD

**Issue by ra-external** [reduxjs/redux-toolkit#613]
We have a reducer created using 'createSlice' where we are receiving and storing the text of an article

```
    currentArticleReceived(state, action: PayloadAction<Article>) {
      log('currentarticlereceived',action.payload)
      state.currentArticle = action.payload;
```
the text of this article contains line breaks `\n`

```
currentarticlereceived {
  "id": "5ee8dc6c2811d62b2302575d",
  "title": "Line breaks",
  "text": "Line\n\nbreaks\n\nfun \n\nis",
```
However these line breaks are not stored in the Redux store

![image](https://user-images.githubusercontent.com/60699805/84797122-bfee3b80-aff9-11ea-9978-0c46970e2da8.png)

I'm not sure what the issue is but it seems that the reducer, which is created using `createSlice`, is stripping out the line breaks.

**Comment by markerikson** [comment]
Are you sure that there is an actual data change going on here? It's entirely likely that what you're seeing is simply an artifact of the serialization for the DevTools, and that the data in the store is unchanged.

Can you create a CodeSandbox that demonstrates this as an actual problem?

**Comment by ra-external** [comment]
You are absolutely correct.  We are receiving the correct data.

![image](https://user-images.githubusercontent.com/60699805/84800713-7b18d380-affe-11ea-9cb4-ebf104276350.png)

Perhaps it's because sometimes the content is not text with line breaks, but instead html.

We are displaying the text with 

`          dangerouslySetInnerHTML={{ __html: text }}`

So perhaps here is where the issue arises (that the client does not display the line breaks)
