### ISSUE TITLE
Current (from Immer) is not exported

### ISSUE THREAD

**Issue by GitLuca** [reduxjs/redux-toolkit#616]
Following the [documentation](https://redux-toolkit.js.org/api/other-exports#current) I tried to export the current method from "redux-toolkit", but apparently is not exported.

Ts gave me this error: 
'Module `"../../../../node_modules/@reduxjs/toolkit/dist/typings"' has no exported member 'current'.`

I'm on version 1.3.6.

**Comment by phryneas** [comment]
Yeah, unfortunately the docs for the upcoming 1.4.0 are already out - 1.3.6 shipped with immer 6, which had not yet `current`. You can log doing `console.log({...vatriable})` in that version. 1.4.0 will be out in a few days. Sorry for the inconvenience!

**Comment by fifinfield** [comment]
@phryneas I suddenly started getting this issue I am on 1.4.0. What is the fix for this?

./node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js
Attempted import error: 'current' is not exported from 'immer'.

**Comment by phryneas** [comment]
@fifinfield Do you maybe have an older version of `immer` installed? Should be version 7.0.3, sometimes multiple versions are installed & the bundler chooses the wrong one
