### ISSUE TITLE
[Question] What's the point in not throwing rejected asyncThunk action?

### ISSUE THREAD

**Issue by h0tw4t3r** [reduxjs/redux-toolkit#618]
Hey.

My question may be dramatically basic, but, how do you really handle rejections in `asyncThunk` actions?

IMHO, the clearest, and the most obvious way would be to use `try` and `catch` blocks in the places we dispatch actions, just like what the author of #520 wanted to achieve:
```ts
export const login = createAsyncThunk(
  'auth/login',
  async (credentials: Credentials): Promise<User> => {
    // returned function CAN throw an error, or fulfill.
    return authClient.login(credentials.username, credentials.password);
  }
);
```
and using it just like @affanshahid mentioned:
```ts
async function handleClick() {
  try {
    await dispatch(login(credentials))
  } catch (err) {
    showToastForError(err)
  }
}
```

AFAIK, the only case where you don't use `unwrapResult`, is when you want to abort promise, but why can't we inject the `abort` function in the returned promise, either it is rejected or fulfilled?

The try-catch rejection handling in thunks is stated here:
https://github.com/reduxjs/redux-toolkit/blob/9a410e73b2cec7079c0b546b10a514ecbc3c3be1/src/createAsyncThunk.ts#L432-L434

And as I understood is used to not dispatch an action, if it's rejected:
https://github.com/reduxjs/redux-toolkit/blob/9a410e73b2cec7079c0b546b10a514ecbc3c3be1/src/createAsyncThunk.ts#L443

And this function simply unwraps the payload:
https://github.com/reduxjs/redux-toolkit/blob/9a410e73b2cec7079c0b546b10a514ecbc3c3be1/src/createAsyncThunk.ts#L482-L489

But what if this unwrapping would be right in the:
https://github.com/reduxjs/redux-toolkit/blob/9a410e73b2cec7079c0b546b10a514ecbc3c3be1/src/createAsyncThunk.ts#L451

But would look like:
```ts
// don't know if it works, just for the sake of the concept
Object.assign(promise.then(action => action.payload, action => action.error), { abort })
```

Is this approach possible?

**Comment by phryneas** [comment]
There are many people who keep all business logic out of components. That includes async error handling.

So these people just `dispatch(fetchSomething())` in a click handler and handle all the errors in their reducers.

If we let that `dispatch` call actually reject the returned Promise, everyone who used redux that way would get lots of unhandled promise rejections on network errors, even though they actually handled those network errors absolutely correctly - just in a more "reduxy" way.

It is not our intention to spam the console of users of our library with error messages if they do something correct - so we have to fall back to a way that works for both approaches. And that means always resolving promises and offering a way to make them throw as opt-in behaviour.
