### ISSUE TITLE
`updateMany` ignores early updates if later updates have the same ID

### ISSUE THREAD

**Issue by jakeboone02** [reduxjs/redux-toolkit#619]
The `updateMany` action generated by the `createEntityAdapter` function is not working as intended when there are multiple updates to the same entity.

Consider the following code:

```ts
const slice = createSlice({
  name: 'books',
  initialState: booksAdapter.getInitialState(),
  reducers: {
    bookAdd: adapter.addOne,
    bookUpdates: adapter.updateMany,
  },
});

// configure store and add books ...

store.dispatch(
  slice.actions.bookUpdates([
    { id: 1, changes: { title: 'New Title 1' } },
    { id: 2, changes: { title: 'New Title 2' } },
    { id: 1, changes: { author: 'New Author 1' } },
    { id: 2, changes: { author: 'New Author 2' } },
  ])
);
```

The outcome of that last statement should be that entity `1` has a title of "New Title 1" _and_ a new author of "New Author 1".  But what actually happens is that the `author` is changed but not the title.

The [docs](https://redux-toolkit.js.org/api/createEntityAdapter) say, "If `updateMany()` is called with multiple updates targeted to the same ID, they will be merged into a single update, with later updates overwriting the earlier ones."  That's a little ambiguous.  It could mean that the later updates should be merged with earlier updates (not conflicting if the fields are different), or that the later updates would completely replace earlier updates with the same ID.  It's doing the latter, but should do the former.

See the codesandbox here:

https://codesandbox.io/s/redux-toolkit-updatemany-test-verzl?file=/src/App.tsx

**Comment by markerikson** [comment]
Yeah, I think this is an actual bug. Here's the offending bit of code:

https://github.com/reduxjs/redux-toolkit/blob/9a410e73b2cec7079c0b546b10a514ecbc3c3be1/src/entities/unsorted_state_adapter.ts#L106-L117

The issue is that the updates are nested in `update.changes`, and the spread there isn't merging that nested field together.

I'm busy atm, but I'd happily take a PR and some unit tests to fix this.

**Comment by jakeboone02** [comment]
Thanks for taking a look, @markerikson.  I've opened PR #621 to fix it.

**Comment by markerikson** [comment]
Live in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.4.0

**Comment by karlsoderback** [comment]
I am using redux-toolkit v1.7.0 and I am still experiencing issues with several updates of the same id. I experience the reverse problem of what is described in the example above, the first update for the id takes effect but not the following.

**Comment by markerikson** [comment]
@karlsoderback if you're seeing problems, could you file a new issue with a CodeSandbox or a project that reproduces the problem?  (fwiw we haven't changed any of this behavior since this issue was closed.)

**Comment by jakeboone02** [comment]
I tried to reproduce the issue the @karlsoderback reported [here](https://codesandbox.io/s/redux-toolkit-updatemany-test-1-7-1-2r5zk?file=/src/App.tsx), but it appears to be working fine, or at least working as expected.

**Comment by karlsoderback** [comment]
Thanks for your replies, I'll put together a reproducer as soon as I can!

**Comment by karlsoderback** [comment]
I refactored the sandbox provided by @jakeboone02 [here](https://codesandbox.io/s/exehh?file=/src/App.tsx) to closer reflect my project where the issue is experienced. In this example you should see the effect I described.

**Comment by markerikson** [comment]
@karlsoderback If you're actually seeing a bug, please open up a new issue so we can keep track of it.

**Comment by jakeboone02** [comment]
@karlsoderback When I remove the `sortComparer` declaration in the `createEntityAdapter` call, the updates work as expected: the second one takes priority. See [here](https://codesandbox.io/s/redux-toolkit-updatemany-test-1-7-1-forked-7fcvl?file=/src/App.tsx).

@markerikson I can't tell what's going on here because the [`updateManyMutably`](https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/entities/unsorted_state_adapter.ts#L125) function doesn't seem to have anything to do with `sortComparer` (even after being wrapped by [`createStateOperator`](https://github.com/reduxjs/redux-toolkit/blob/3d201328871cbd765b4814a778c42f86c45d3474/packages/toolkit/src/entities/state_adapter.ts#L21)). Probably a new bug, but maybe his `sortComparer` is configured incorrectly?

**Comment by markerikson** [comment]
new issue please :)

**Comment by karlsoderback** [comment]
Posted in new issue: https://github.com/reduxjs/redux-toolkit/issues/1853
