### ISSUE TITLE
Update non-serializable error message to include URL to better resolution docs

### ISSUE THREAD

**Issue by cloeper** [reduxjs/redux-toolkit#622]
When passing something non-serializable in an action, we see the following error:

```
A non-serializable value was detected in an action, in the path: `<PATH>`. Value: <VALUE>
 
Take a look at the logic that dispatched this action:  
Object { <OBJECT> }
 
(See https://redux.js.org/faq/actions#why-should-type-be-a-string-or-at-least-serializable-why-should-my-action-types-be-constants)
```

This is great to understand why redux defaults to requiring serialized payload, but it doesn't help point to a potential resolution. There are a number of cases where passing a non-serializable object makes a lot of sense. File upload for instance.

The solution can be deployed tactically by configuring middleware like this:
```
configureStore({
//...
  middleware: getDefaultMiddleware({
    serializableCheck: {
      ignoredActions: [ "your/action" ]
    }
  })
})
```

And I think it'd be really helpful to include a link to documentation that explained this, not just a link that explains why the error is happening.

**Comment by markerikson** [comment]
Agreed. 

Can you file a PR that adds:

- A new section to the "Usage Guide" docs page discussing how to deal with serializability and the middleware
- A change to that error message that links to the newly added header in that page?

**Comment by cloeper** [comment]
Sure thing, here it is: https://github.com/reduxjs/redux-toolkit/pull/623

**Comment by markerikson** [comment]
And fixed by your PR.
