### ISSUE TITLE
export actions from createReducer

### ISSUE THREAD

**Issue by plandem** [reduxjs/redux-toolkit#625]
as I understand from source code, this one will not work:
```
const myState = createReducer({ count: 0, items: []}, {
    reset: state => { state.count = 0 },
    increment: state => { state.count += 1 },
    decrement: state => { state.count -= 1 },
    addItem(state, action) {
        const { id, value } = action.payload;
        state.push({ id, value });
    }
});

dispatch(myState.actions.increment())
```

since we used inline actions and created reducer does not hold actions. Am I right?

This how I was planning to use with useReducer

**Comment by phryneas** [comment]
That's explicitly what `createSlice` exists for.

**Comment by plandem** [comment]
yeah, I know, hoped for createReducer. Probably need to update documentation for createReducer, because there are examples for inline actions for reducer that will not work - you dispatch actions that were created from createAction.

**Comment by phryneas** [comment]
The documentation never implies anywhere that it would create action creators. It does create a reducer, that works with externally generated actions (and action creators, for convenience), nothing more.

It does not have the name `createReducerAndActionCreators`.

**Comment by phryneas** [comment]
Also, is there any particular reason why you are hoping for `createReducer`?

This is the exact distinction between `createReducer` and  `createSlice`: one creates action creators, one does not.

**Comment by plandem** [comment]
ok, I will rephrase:
```
const counterReducer = createReducer(0, {
  increment: (state, action) => state + action.payload,
  decrement: (state, action) => state - action.payload
})
```
this example from documentation will not work at all since you can't dispatch these actions. I'm ok to use createSlice, but since I used official documentation as reference I hoped that can achieve same with createReducer - use reducer/actions for useReducer hook.

**Comment by phryneas** [comment]
> ok, I will rephrase:
> 
> ```
> const counterReducer = createReducer(0, {
>   increment: (state, action) => state + action.payload,
>   decrement: (state, action) => state - action.payload
> })
> ```
> 
> this example from documentation will not work at all since you can't dispatch these actions. I'm ok to use createSlice, but since I used official documentation as reference I hoped that can achieve same with createReducer - use reducer/actions for useReducer hook.

`dispatch({type: "increment"})`

**Comment by markerikson** [comment]
Yeah, the point of `createReducer` is that the string keys in the object _are_ the action types that will be handled, regardless of where and how those actions are dispatched.  so, `dispatch({type: "increment"})` will match `createReducer(0, {increment: state => state + 1})`.

Note that `createSlice` calls `createReducer` internally, it just adds specific custom-prefixed action types as the keys so that those actions will be handled by the reducer.

Both `createReducer` and `createSlice` generate plain simple reducer functions, with no actual dependency on Redux, and those can be used with `useReducer`. I've used `createSlice` multiple times to generate reducers that were _only_ used in React components with `useReducer`.

**Comment by plandem** [comment]
yeah, got you point about dispatching action like `dispatch({type: "increment", payload: 1})` without action creator

**Comment by plandem** [comment]
@markerikson think I can explain what was bothering me. I think documentation still can be updated to point on some cases, otherwise it may be confusing for some people, especially newcomers into redux/redux-toolkit:

```
export const reset = createAction('reset');

const counter = createSlice({
    name: 'counter',
    initialState: 0,
    reducers: {
        [reset]: (state, action) => {
            console.log('[reset-inline] reduce');
        },
    },
    extraReducers: {
        [reset]: () => {
            console.log('[reset-extra] reduce');
        }
    }
});

export const { actions } = counter;
.....
dispatch(reset()); //will fall into `extraReducers`, action.type='reset'
dispatch(actions.reset()); //will fall into `reducers`, action.type='counter/reset'
```

It can be confusing in case of  example how to use `createAction/createSlice` together, since createSlice will auto-prefix, but you should export/dispatch action from slice, otherwise it will be considered as external and will fall into extraReducers. Since these examples go together as one piece of code, it can be confusing for newcomers.

P.S.: btw, kudos to my old buddy from redux-orm contribution times ;)

P.P.S.: my english is not good enough for documentation updates probably :(

**Comment by markerikson** [comment]
If you can point to areas of the docs that can be improved and at least say _what_ you think should be changed, or where new explanations ought to go, that would be helpful.

I get the point of the confusion there, but not sure where/how to clarify things.

**Comment by plandem** [comment]
@markerikson 

Ok, scanned docs one more time and looks like all examples are valid actually.

But maybe this part:

```markdown
**Like reducers, extraReducers** should be an object containing Redux **case reducer functions.** However, the keys should be other Redux string action type constants, and createSlice will not auto-generate action types or action creators for reducers included in this parameter.
```
with following example can confuse

```javascript
const incrementBy = createAction('incrementBy')

createSlice({
  name: 'counter',
  initialState: 0,
  reducers: {},
  extraReducers: {
    [incrementBy]: (state, action) => {
      return state + action.payload
    }
  }
})
```
Of course documentation adds more details, but who will read all this things and understand same time in a proper way? 

Idk, maybe update example like this:
```javascript
const incrementBy = createAction('incrementBy')

createSlice({
  name: 'counter',
  initialState: 0,
  reducers: {
    // we can't use action creator in reducers, since it will be auto prefixed
  },
  extraReducers: {
    [incrementBy]: (state, action) => {
      return state + action.payload
    }
  }
})
```

what do you think?

**Comment by plandem** [comment]
```
const incrementBy = createAction('incrementBy')

createReducer(0, {
  [incrementBy]: (state) => state //action creator can be used
});

createSlice({
  name: 'counter',
  initialState: 0,
  reducers: {
    //action creator can't be used or will generate another action creator.
  },
  extraReducers: {
    [incrementBy]: (state) => state //action creator can be used
  }
})
