### ISSUE TITLE
Immer ^6.0.1 issue with Invalid property descriptor

### ISSUE THREAD

**Issue by mercurial-hc** [reduxjs/redux-toolkit#627]
Hello! First of all, I'd like to thank you for this wonderful project.

## Issue
I'm trying to use the **createSlice** API but whenever I run the application, I'm getting the following error - 

```
Uncaught TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>
    at Function.assign (<anonymous>)
    at setWindowProperties (http://localhost:1212/dist/renderer.dev.js:9925:66)
    at C:\Users\User\Workspace\Project\client\node_modules\@reduxjs\toolkit\dist\redux-toolkit.cjs.development.js:643:18
    at Immer.produce (C:\Users\User\Workspace\Project\client\node_modules\immer\dist\immer.cjs.development.js:725:18)
    at C:\Users\User\Workspace\Project\client\node_modules\@reduxjs\toolkit\dist\redux-toolkit.cjs.development.js:642:16
    at combination (C:\Users\User\Workspace\Project\client\node_modules\redux\lib\redux.js:465:29)
    at C:\Users\User\Workspace\Project\client\node_modules\redux-persist\lib\persistReducer.js:159:20
    at dispatch (C:\Users\User\Workspace\Project\client\node_modules\redux\lib\redux.js:219:22)
    at http://localhost:1212/dist/renderer.dev.js:16183:18
    at http://localhost:1212/dist/renderer.dev.js:23190:7675
```

Upon inspecting the call-stack, this error originates from **createSlice** in turn calls **createReducer** which utilizes **Immer.js** for handling mutation in the state to produce the next state.

## Fixes I've tried
I suspected that this was an issue with Babel but trying to modify babel config and/or adding plugin was an exercise in futility.

## Resolution
Finally, I updated the Immer version used by RTK to ^7.0.1 and this **fixed** the issue. 
I did this by modifying the yarn.lock as a temporary workaround.

Can we bump the Immer version to the latest to fix this issue?

## Additional Info
(Since the source is under NDA, I won't be able to provide an excerpt.)
Current Project Setup -
Based on [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate)

**Comment by markerikson** [comment]
Yeah, we've already updated to Immer 7 on `master`, and that will be out in RTK 1.4 shortly (as in, "as soon as I finish updating docs in #610 and merge it in").

**Comment by mercurial-hc** [comment]
Thanks for the quick resolution.
Really appreciate the great work!
