### ISSUE TITLE
Additional docs updates post-1.4

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#628]
_Originally posted by @msutkowski in https://github.com/reduxjs/redux-toolkit/pull/610#issuecomment-645438848_:

I went through the docs and found some more places that need to be updated with this PR. I also added some notes about the Advanced Tutorial that can get moved into its own issue.

### Quick start
- `createReducer()`
  - [ ] Update definition

### Basic tutorial:
- Introducing: `createReducer`
  - Could be updated, but not necessary
- Summary: createReducer
  - [ ] Update `createReducer` definition
  
### Intermediate tutorial:
 - #Summary
   - [ ] Remove or update this copy: 
    > Coming soon: an Advanced Tutorial, where we'll look at how to use RTK in an app that does async data fetching and uses TypeScript.

### Advanced tutorial

**General notes:** Being that the tutorials link to specific commits in a repo, we should consider rewriting this page and pointing to a codesandbox instead of commits. I think the commit-linking approach locks us into examples that could easily become outdated. If we keep this as an example of a 'Migration guide', this would become a non-issue with a new tutorials section.

#### Changes without a new Advanced Tutorial:
- #Writing Thunks in Redux Toolkit
  - [ ] Update copy: 
    > However, Redux Toolkit does not currently provide any special functions or syntax for writing thunk functions. In particular, they cannot be defined as part of a createSlice() call. You have to write them separate from the reducer logic.
    
#### Changes with a new Advanced Tutorial:
   - [ ] Update to use `createAsyncThunk`?
   - [ ] Use `createEntityAdapter`
   - [ ] `useAppDispatch` instead of `useDispatch` in the TS example
   - [ ] show a generic reducer loading state with `addMatchers` by toggling value on /pending|rejected|fulfilled
   - [ ] show debugging actions with `addDefaultCase`

### Usage guide
 - #Async Requests with createAsyncThunk
   - [ ] Add paragraph about how cancellation is handled?
 - #Normalizing with normalizr
   - [ ] Add a note about `normalizr` typically being called in the action creator so that reducers can easily extract it's desired data _(this question comes up often in discord)_

### Usage with Typescript
 - #createReducer
   - [ ] Show additional properties (addMatchers/addDefaultCase) and a relevant example

**Comment by markerikson** [comment]
I'd also like to extract the dev check middleware details to their own API reference pages. I would _like_ to have the API ref divided into sub-categories, like this:

- Store Setup
  - `configureStore`
  - `getDefaultMiddleware`
  - `createSerializableMiddleware`
  - `createImmutableMiddleware`
- Reducers and Actions
  - `createAction`
  - `createReducer`
  - `createSlice`
  - `createAsyncThunk`
  - `createEntityAdapter`
- Other
  - `createSelector`
  - Other Exports

And I'd _like_ to have all those subcategories expanded by default.  Supposedly, DS alpha.58 supports that, per https://github.com/facebook/docusaurus/pull/2682 , but I just updated and tried to use the `collapsed: false` option on categories and it's not doing anything.  So, we'll revisit this idea later.

**Comment by markerikson** [comment]
Believe all the items here have been sufficiently resolved.

**Comment by abdulrasak2k** [comment]
h
