### ISSUE TITLE
Code splitting / injecting reducers

### ISSUE THREAD

**Issue by TamasSzigeti** [reduxjs/redux-toolkit#636]
Hi,
thanks for this awesome package that has already helped me immensly.

I'm in the process of trying to split out reusable code into packages, and was wondering if there was a recommended way of doing this with redux-toolkit – preferably while not falling back to manual store creation and not losing the inferred types in TS.

I tried the examples from the redux doc – typings get complicated quickly – and also went through all the linked packages – most of them are unmaintained and none of them hits the quality I would like to have.

Maybe an out-of-the-box support in this package for an injectReducer() api would be nice.

Any thoughts, comments, recommendations welcome.

**Comment by markerikson** [comment]
Nothing about RTK should change the various recommended patterns for dealing with injection.  I get that this can also make TS usage tricky, but I don't think there's anything special we need to do on that end.

I'm not against adding something, but I'm not sure what if anything would actually be relevant to add.

**Comment by TamasSzigeti** [comment]
Well I was thinking the package could provide a simple injectReducer described here: https://redux.js.org/recipes/code-splitting
But if you feel that's out of scope here, that's fine.
Thank you for your response though.

**Comment by MohitKS5** [comment]
An example on how to implement this (injectReducer or reducerManager) without falling back to manual store creation would be good.
