### ISSUE TITLE
Cannot find module '@reduxjs/toolkit' or its corresponding type declarations.

### ISSUE THREAD

**Issue by Edward-Fedoruk** [reduxjs/redux-toolkit#639]
looks like type declarations aren't visible for ts. After installing @reduxjs/toolkit have this error:
 
![image](https://user-images.githubusercontent.com/31627098/85943792-a078dc00-b932-11ea-948f-99012cbc0339.png)

My tsconfig:
![image](https://user-images.githubusercontent.com/31627098/85943817-c8683f80-b932-11ea-9c1a-6809bc732783.png)

Webpack loader: 
![image](https://user-images.githubusercontent.com/31627098/85943832-dae27900-b932-11ea-8c25-ae3cd46811e5.png)

packeg.json: 

> {
  "name": "spicyhr",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server --env.NODE_ENV=development --open",
    "build": "webpack --env.NODE_ENV=production",
    "test": "jest",
    "lint": "eslint . --ext .ts,.tsx",
    "test-watch": "jest --watch"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint",
      "pre-push": "npm run lint"
    }
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.10.2",
    "@babel/preset-env": "^7.10.2",
    "@babel/preset-react": "^7.10.1",
    "@babel/preset-typescript": "^7.10.1",
    "@svgr/webpack": "^5.4.0",
    "@testing-library/jest-dom": "^5.10.1",
    "@testing-library/react": "^10.3.0",
    "@types/classnames": "^2.2.10",
    "@types/enzyme": "^3.10.5",
    "@types/jest": "^25.2.3",
    "@types/node-sass": "^4.11.1",
    "@types/ramda": "github:types/npm-ramda#dist",
    "@types/react": "^16.9.35",
    "@types/react-bootstrap": "^1.0.1",
    "@types/react-dom": "^16.9.8",
    "@types/react-redux": "^7.1.9",
    "@types/react-router-dom": "^5.1.5",
    "@types/webpack-env": "^1.15.2",
    "@typescript-eslint/eslint-plugin": "^3.3.0",
    "@typescript-eslint/parser": "^3.3.0",
    "awesome-typescript-loader": "^5.2.1",
    "babel-loader": "^8.1.0",
    "babel-plugin-ramda": "^2.0.0",
    "babel-plugin-react-remove-properties": "^0.3.0",
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^3.5.3",
    "css-modules-typescript-loader": "^4.0.0",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "eslint": "^7.2.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-plugin-import": "^2.21.2",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-react": "^7.20.0",
    "eslint-plugin-react-hooks": "^4.0.4",
    "html-webpack-plugin": "^4.3.0",
    "husky": "^4.2.5",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^26.0.1",
    "mini-css-extract-plugin": "^0.9.0",
    "node-sass": "^4.14.1",
    "optimize-css-assets-webpack-plugin": "^5.0.3",
    "prettier": "^2.0.5",
    "redux-mock-store": "^1.5.4",
    "sass": "^1.26.7",
    "sass-loader": "^8.0.2",
    "script-ext-html-webpack-plugin": "^2.1.4",
    "source-map-loader": "^1.0.0",
    "style-loader": "^1.2.1",
    "svg-url-loader": "^6.0.0",
    "ts-jest": "^26.1.1",
    "typescript": "^3.9.3",
    "url-loader": "^4.1.0",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.11.0",
    "webpack-merge": "^4.2.2"
  },
  "dependencies": {
    "@reduxjs/toolkit": "^1.4.0",
    "axios": "^0.19.2",
    "bootstrap": "^4.5.0",
    "classnames": "^2.2.6",
    "i18next": "^19.4.5",
    "i18next-browser-languagedetector": "^4.3.0",
    "ramda": "^0.27.0",
    "react": "^16.13.1",
    "react-bootstrap": "^1.0.1",
    "react-dom": "^16.13.1",
    "react-i18next": "^11.5.0",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.2.0",
    "react-scrollbars-custom": "^4.0.25",
    "redux": "^4.0.5",
    "ts-loader": "^7.0.5"
  }
}

**Comment by phryneas** [comment]
Getting this in vscode means that it is not any error in your build pipeline, but is a `tsserver` (thus, configuration of your `typescript` package) thing.

It most likely correlates to `"moduleResolution": "Node"` in your `tsconfig.json`, which should be `node` with a small leading `n`. `"Node"` is not a valid value and might make you fallback to `classic` behaviour.

**Comment by Edward-Fedoruk** [comment]
I also have this: 
![image](https://user-images.githubusercontent.com/31627098/85944751-99090100-b939-11ea-8e3f-0f2b58ce59fd.png)
but only in webpack production mode, dev mode works fine

**Comment by phryneas** [comment]
Which is a completely different problem. Is your first problem solved?

Also, line 3 in that file is your code, not RTK's. (I don't see a reason for that error though) 

And you're pretty much mimicing `createAction` there, with the same generic signature and only less functionality. 
Why not just `export { createAction as createAppAction }` if you want to rename it?
