### ISSUE TITLE
Customized error serialization for `createAsyncTask`

### ISSUE THREAD

**Issue by Yserz** [reduxjs/redux-toolkit#644]
Hey,

I'm having a hard time with error mapping using `reduxjs/redux-toolkit`. The situation is as follows:

1. When any backend request fails it results in an error of the form:
`{
message: string,
code: number,
label: string,
}`
2. When the thunk rejects the error gets serialized by `miniSerializeError` https://github.com/reduxjs/redux-toolkit/blob/de1282c1ec7eb8db1590a60c55f0ec21004b8675/src/createAsyncThunk.ts#L50

Result:
The `label` is stripped from the error.

Expected result:
`createAsyncTask` can be (globally) configured to keep certain attributes on errors from rejections. This could be fully optional and default to the current values.

Note when using `thunkAPI.rejectWithValue`:
1. The API feels to be inconsistent because the error in the action is in the `payload` instead of in the `error` attribute. There is an error in the error field though but is only including the `message` attribute of the error.
2. When using `unwrapResult` on such a value it will throw only the error from the `error` attribute which makes further code necessary to get the actual error from the rejected action.

IMHO it would be best to allow to specify which additional attributes on an error should be serialized when a thunk gets rejected in order to use the API in the usual way.

Related issues:
https://github.com/reduxjs/redux-toolkit/issues/588

**Comment by markerikson** [comment]
Fixed by #812 , I believe.
