### ISSUE TITLE
createEntityAdapter: Proper way to insert / update a nested entity?

### ISSUE THREAD

**Issue by theogravity** [reduxjs/redux-toolkit#647]
I'm not sure what the right strategy is for the following and am looking for guidance:

- Upsert a new `document`
- Update the `project.documents` to include a new document id or do not do anything if the document id exists (based on upsert)

```js
// Entity definitions
export const documentEntity = new schema.Entity('documents')
export const projectsEntity = new schema.Entity('projects', {
  documents: [documentEntity],
})
```

```js
// projects.slice
import { createEntityAdapter, createSlice } from '@reduxjs/toolkit'

export const projectsAdapter = createEntityAdapter()

const slice = createSlice({
  name: 'projects',
  initialState: projectsAdapter.getInitialState(),
  ...
})

export default slice.reducer
```

```js
// documents.slice
import { createSlice, createEntityAdapter } from '@reduxjs/toolkit'
import { loadProject } from '../projects/projects.thunks'

export const documentsAdapter = createEntityAdapter()

export const slice = createSlice({
  name: 'documents',
  initialState: documentsAdapter.getInitialState(),
  ...
})

export default slice.reducer
```

State looks like this (used `createEntityAdapter` / `normalizr` to populate it):

```
{
  projects: {
    ids: [...]
    entities: {
      ... : {
        documents: [<document ids>]
      }
    }
  },
  documents: {
    ids: [...]
    entities: {
      ...
    }
  }
}
```

I'm concerned that I would have to iterate through the `project.documents` array to determine if the id exists or not since a project may contain a subset of available documents. 

The CRUD methods provided by `createEntityAdapter`, does not mention any kind of resolution strategy with sub-entities.

**Comment by markerikson** [comment]
Yeah, we don't do anything regarding relationships or nested updates atm. Those add a lot of potential complexity, and are more the domain of something like https://github.com/redux-orm/redux-orm .

**Comment by theogravity** [comment]
@markerikson you are amazing with your fast responses - Thank you so much for your help

**Comment by markerikson** [comment]
Heh, in this case I just happened to have refreshed the GH notifications page like 2 minutes after you'd posted this :)
