### ISSUE TITLE
createAction return value when action creator is called in dispatch with 0 argumnets

### ISSUE THREAD

**Issue by iamerratic** [reduxjs/redux-toolkit#648]
type = 'as given by user'
When we call action creator in dispatch as a function with 0 arguments then the return value of our action is { type: type,payload:undefined}. So we can just check the arguments and can remove the payload undefined property which makes our action look a bit clean.

Thanks

**Comment by markerikson** [comment]
Sorry, I'm afraid I can't quite understand what you're asking for here.  Can you clarify?
