### ISSUE TITLE
ES Modules for browsers

### ISSUE THREAD

**Issue by jonjharrison** [reduxjs/redux-toolkit#652]
Would be great to add support for browser-friendly ES modules if possible - currently they don't load when loaded as modules from the browser because of the `process.env.NODE_ENV` references.

Looks like this was solved in the core redux package by adding an additional rollup [config](https://github.com/reduxjs/redux/blob/b08cf38b7bbf2dcb3f4668493514ca1ecc121737/rollup.config.js#L75), would it be possible to have something similar for toolkit?

**Comment by markerikson** [comment]
Sure, happy to accept a PR on that.

**Comment by msutkowski** [comment]
I did some digging around regarding this, and it seems like there is no easy way to get `tsdx` to do this at this time. I can swap out the regular ESM build with this browser-specific version like redux does but I've been unable to get multiple variations of the ESM build to happen. Ideally, we could just pass in a new custom build format _(like 'mjs')_ and have it process the defined config for the format, but `tsdx` restricts the build to it's supported formats as it supplies defaults. There is some more context in this issue: https://github.com/formium/tsdx/issues/631, but it seems like the `patch-package` solution might be a little bit of a 🐰 🕳️. Maybe someone else can figure this out :)

**Comment by markerikson** [comment]
So this is a bit confusing to me. We apparently merged #658 a year ago, and that should have been in the 1.5.0 and 1.5.1 releases. But, I don't see any `.esm.production` artifacts in either published package.

So, I'm going to see if we can actually fix this in #957 , now.

**Comment by markerikson** [comment]
Should be resolved by #957 , and will be out in 1.6.
