### ISSUE TITLE
Canceling an already running asyncThunk action

### ISSUE THREAD

**Issue by hmbrg** [reduxjs/redux-toolkit#654]
The current API allows canceling before a payload creator is called or cancel an already-running action why a promise reference. But how would I go about canceling an already-running action without having the promise reference to call `.abort()` on?

**Comment by tannera** [comment]
You can not cancel an HTTP request out of thin air, you will need to save the promise reference somewhere, in order to abort it.

**Comment by phryneas** [comment]
tannera pretty much said it. Closing this one as I'm cleaning up right now.
