### ISSUE TITLE
[Feather] EntityAdapter raise function

### ISSUE THREAD

**Issue by TheBegining** [reduxjs/redux-toolkit#657]
Recently,I am using D3.js to draw a chessboard.
![image](https://user-images.githubusercontent.com/17702287/87858291-6f9f2c00-c95f-11ea-9aee-ba4cf2e4905e.png)

When I drag my chessman I want it raise to the top of the layer.D3 support the dom operation.

![image](https://user-images.githubusercontent.com/17702287/87858366-f6ec9f80-c95f-11ea-83f6-92768faa2e45.png)

But When I update the chessman position in redux,The chessboard will rerender.

The chessman will comes back.

dragging
![image](https://user-images.githubusercontent.com/17702287/87858371-07047f00-c960-11ea-841c-161b756208db.png)

stop drag
![image](https://user-images.githubusercontent.com/17702287/87858376-0d92f680-c960-11ea-9c45-70d268f8c2be.png)

If there is a raise function for the EntityAdapter I can raise it to the top.
![image](https://user-images.githubusercontent.com/17702287/87858410-4763fd00-c960-11ea-8564-9b5bd9f36105.png)

**Comment by markerikson** [comment]
I'm not sure what you're actually asking for here.

The entity adapter has no notion of "raising".  That's an application-specific concept.

If you want to reorder things, use the `sortComparer` option of `createEntityAdapter`, and dispatch an action that alters the field that you're sorting on.  The entity adapter will then re-sort the IDs array based on that field.
