### ISSUE TITLE
store.dispatch have type 'newer' when use '(getDefaultMiddleware) => getDefaultMiddleware()' to init middleware in configureStore function

### ISSUE THREAD

**Issue by Gruzchick** [reduxjs/redux-toolkit#659]
In this [repo](https://github.com/Gruzchick/redux-toolkit-dispatch-type-never) bug reproduces. In my project I use it this way:
`function configureAppStore() {
  return configureStore({
    reducer: rootReducer,
    middleware: (getDefaultMiddleware) =>
      getDefaultMiddleware().concat(routerMiddleware(history)),
  });
}`

**Comment by phryneas** [comment]
I'm sorry, but that repo contains a completely working version without the routerMiddleware. Could you update that please?

**Comment by Gruzchick** [comment]
> I'm sorry, but that repo contains a completely working version without the routerMiddleware. Could you update that please?
> 
> routerMiddleware could be from react-router-redux or connected-react-router (and a dozen other libs), so you have knowledge there that I don't ;)
> 
> PS: at least [in this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFBzgYygUwIY0wQTRmAgDsAaFdLXTAJUwBMBXNTKS1NCEAI2FL0mrdgGdO6MgDNgAc2ZYAyjGiYkAXzhSoPOAHIAAlhYAPAFaiA9CogAbANbAYegNxIkoSLETUceAEI6AO6i7AASwKIqUACecJraunoAFpHRMXoe4NDwCHDYYGC2MQCywIyMtphB2Fjkktmh9Rh+mMqq8Vo6IPrGzCaZnjk+Osx4UGUVVTVYnYk9etykgkRMALQ0RBsQY+yZSEtRcAItIJik8AC8vrSExGQAFHonWGcXegCUB2RHjJin5yuNzwdxIpCefwB7y+31IR24zAu7AYLDYUDg1xatBRIigDwADPVkKgAN

**Comment by Gruzchick** [comment]
@phryneas, I think that routerMiddleware is not mattered. I have updated the repo and make screenshots, it seems that WebStorm shows wrong types or I misunderstood something.
![image](https://user-images.githubusercontent.com/13402010/87872348-eda41700-c9e1-11ea-89c5-d8f22a56192f.png)
![image](https://user-images.githubusercontent.com/13402010/87872440-cd288c80-c9e2-11ea-853f-a3e97c5aac74.png)

**Comment by phryneas** [comment]
Really seems to be an editor issue, here it is in VS code:

![image](https://user-images.githubusercontent.com/4282439/87873118-fe8f6100-c9be-11ea-8fb5-58ae3e1cb34e.png)

![image](https://user-images.githubusercontent.com/4282439/87873132-123ac780-c9bf-11ea-9d8f-73b799fdf12f.png)

If you gain any insights into this (some webstorm configuration necessary to use the right `tsconfig` or right TS version maybe?), please add it here as a comment, maybe it helps someone else :)

**Comment by Gruzchick** [comment]
https://youtrack.jetbrains.com/issue/WEB-46527
