### ISSUE TITLE
Is there any rules or guides to contribute chinese docs?

### ISSUE THREAD

**Issue by Xwil** [reduxjs/redux-toolkit#660]
Hi guys, I'm planning to translate docs into chinese, is there any suggestion about how to organize folder etc ?

**Comment by markerikson** [comment]
Docusaurus v2 doesn't appear to support internationalization at the moment.  It might be easiest just to set up a clone of the RTK docs at another URL, and we could link over there.

**Comment by Xwil** [comment]
> Docusaurus v2 doesn't appear to support internationalization at the moment. It might be easiest just to set up a clone of the RTK docs at another URL, and we could link over there.

ok thx, I'll try.
