### ISSUE TITLE
configureStore slice action not being triggered when called

### ISSUE THREAD

**Issue by jafrmartins** [reduxjs/redux-toolkit#662]
Hi. My action (defined in the debug tools as a function just isnt being called). Thanks for all the help!

![2020-07-20](https://user-images.githubusercontent.com/13779709/87887915-17c8f980-ca21-11ea-8615-a4ad98910612.png)

When the action is called from the class instance that has a reference to the store created by the RTK.configureStore method everything works fine has shown in the picture above. But when i call the slice action from another class that has a reference to the main class (even when called from global window scope) the action just isnt triggered.

[Projecto Demo - Google Chrome 2020-07-20 00-49-27.zip](https://github.com/reduxjs/redux-toolkit/files/4944871/Projecto.Demo.-.Google.Chrome.2020-07-20.00-49-27.zip)

I created a new action and added a break point that never gets called i dont know why. Please help me if you can. Dont think its global scope because i added a jquery event so that a action is called on the class that has the reference, never happens.

Everything seems to be defined has shown in the attachment. Thanks for all the help!

Greetings.

**Comment by jafrmartins** [comment]
I forgot to enable clickthrought. forget the previous attachement.

[Projecto Demo - Google Chrome 2020-07-20 01-01-56.zip](https://github.com/reduxjs/redux-toolkit/files/4944885/Projecto.Demo.-.Google.Chrome.2020-07-20.01-01-56.zip)

**Comment by jafrmartins** [comment]
desktop capture isnt working properly. Sorry. The action just never gets called. everything looks defined in the debugger tools of vscode. DONT WASTE YOUR TIME ON THE ATTACHEMENTS, they are pointless!

**Comment by jafrmartins** [comment]
![2020-07-20 (3)](https://user-images.githubusercontent.com/13779709/87888620-c8d19300-ca25-11ea-9a4f-86a2323f4fe5.png)
![2020-07-20 (4)](https://user-images.githubusercontent.com/13779709/87888621-c96a2980-ca25-11ea-963f-c200f681c991.png)
![2020-07-20 (5)](https://user-images.githubusercontent.com/13779709/87888622-ca02c000-ca25-11ea-883f-065f9d5e06b8.png)

**Comment by jafrmartins** [comment]
RTK.configureStore nested property as an object of the reducer passed to the constructor.

**Comment by jafrmartins** [comment]
https://www.youtube.com/watch?v=Yop62wQH498

**Comment by jafrmartins** [comment]
sorry

**Comment by phryneas** [comment]
If you haven't figured it out yet: action creators only return action objects when called. You still have to `dispatch` those.

**Comment by jafrmartins** [comment]
Thank you! I forgot that.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
