### ISSUE TITLE
How to infer type for thunkAPI

### ISSUE THREAD

**Issue by lukesmurray** [reduxjs/redux-toolkit#664]
Thank you for making redux easy to use with typescript. I find this toolkit to be a joy to use. 

I've recently come across an issue which I can't seem to find a solution to in the docs. I'm not sure how to create a type definition for the thunkAPI object when passing the thunkAPI to a separate function. In the code below I've left question marks where I'm having the issue. I often have several thunks which could share some common code. The common code may need to use dispatch or other methods on the thunkAPI. But I can't seem to find a way to define the type of the thunkAPI on the helper function.

```ts
export const myThunk = createAsyncThunk<
  void,
  arg,
  RootThunkApiConfig
>("ADD_TODO", async (arg, thunkAPI) => {
  myHelperFunction(arg, thunkAPI)
});

myHelperFunction(arg: arg, thunkAPI: ???) {

}
```

Please let me know if this is documented somewhere, against best practices, or if there is a better place to ask this type of question.

Thank You :rocket:

**Comment by markerikson** [comment]
Hmm. One way to do this _might_ be something like:

```ts
type PayloadCreatorType = Parameters<typeof myThunk>[1];
type ThunkApiType = Parameters<PayloadCreatorType>[1];
```

I'm not sure this will work, and also not sure it's a good idea :)  But you could try that and see what happens.

**Comment by phryneas** [comment]
Hi @lukesmurray!

Unfortunately, as the `thunkAPI` parameter only contains references to types that are used passively, TypeScript cannot infer that paramter - you have to specify it manually as per the example in [the TypeScript documentation](https://redux-toolkit.js.org/usage/usage-with-typescript#createasyncthunk)

**Comment by phryneas** [comment]
Sorry, I misread that a little bit.

We are not exporting the `AsyncThunkPayloadCreator` type that is used for the function signature or the `GetThunkAPI` type that is used for the `thunkAPI` parameter, as those types are internals and we try to expose as little as possible of thsoe. 
Probably it is best to not forward the whole `ThunkApi`, but just the methods being used (`getState` etc.) - those can easily be typed by hand.

**Comment by lukesmurray** [comment]
Thank you @phryneas and @markerikson. @markerikson that didn't quite work but I like the idea. 

@phryneas thats similar to what I'm currently doing. I really only use `getState` and `dispatch` anyway in the helper code. I actually tried exposing `GetThunkAPI` just to see if I could get it working but it was a can of worms.

I think this can be closed out. I'll just provide the types for the methods I use manually.

**Comment by lukesmurray** [comment]
```ts
// see docs for definition of Dispatch and State
export type RootDispatch = typeof store.dispatch;

export type RootState = ReturnType<typeof rootReducer>;

export type RootThunkAPI = {
  getState: () => RootState;
  dispatch: RootDispatch;
};
```

Leaving the solution for my trivial needs here for future readers.

**Comment by polaroidkidd** [comment]
I'm coming across a similar challenge as @lukesmurray , but in my case I'd like to type the `rejectWithValue` call (so far unsuccessfully)

```typescript
const initializeApplication = createAsyncThunk<
  AppThunkDispatch,
  null,
  { state: RootState; rejectValue: IAuthErrorResponse }
>(
  "app/initializeApplication",
  async (
    _,
    {
      dispatch,
      rejectWithValue,
    }: { 
      dispatch: AppDispatch; 
      rejectWithValue: any // <-- Too open, but other types such as
                           // RejectedActionFromAsyncThunk or RejectedWithValueActionFromAsyncThunk 
                           // extend AnyAction and I couldn't find an appropriate way to type this. 
                           // Isn't this a dispatch call?
   }
  ) => {
    try {
      const mappedUser = await authApi.fetchCurrentUserDetails();

      return dispatch(userActions.setUser(mappedUser));
    } catch (error) {
      const responseData: IAuthErrorResponse = {
        statusCode: error.status,
        error: error.statusText,
        message: "Invalid Token",
      };

      return rejectWithValue(responseData);
    }
  }
);
```

**Comment by Visual-Dawg** [comment]
I have the same use case. 
Wouldnt it make sense to expose this type? Because it gets used directly in user code and changing its signature would be a breaking change.

**Comment by phryneas** [comment]
@Visual-Dawg your question doesn't have to do anything with the initial question of this issue, and I have no idea which of the many answers you are referencing.
Could you please open a new issue and explain in enough detail there?

**Comment by einarq** [comment]
@phryneas 
Shouldnt make assumptions of course, but I'm fairly confident @Visual-Dawg meant the GetThunkAPI type ?

I just now came across the same, and ended up using the same solution as @lukesmurray suggested here:
https://github.com/reduxjs/redux-toolkit/issues/664#issuecomment-661284737

**Comment by vvklimov** [comment]
It seems that in one of the latest versions they finally exported the GetThunkAPI type, so if you are still encountering the problem you can update to the latest version of Redux Toolkit using your packet manager (in my case it's npm):
`npm i @reduxjs/toolkit`

and then import GetThunkAPI directly from it: 
`import { GetThunkAPI } from "@reduxjs/toolkit";`

create a type for GetThunkAPI in my case it was:
```
export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
export type AsyncThunkConfig = {
  state: RootState;
  dispatch: AppDispatch;
  rejectValue: { error: string };
};
```
and then you can infer the thunkAPI type in your function:
```
myHelperFunction(arg: arg, thunkAPI: GetThunkAPI<AsyncFuncConfig>) {
}
```
this solved my problem.
