### ISSUE TITLE
express relationship between two entities

### ISSUE THREAD

**Issue by leo-vannini** [reduxjs/redux-toolkit#665]
Maybe I'm not phrasing this properly, but what is the best way to be expressing relationship between entities that have been created using `createEntityAdapter`.

For instance, in the redux tutorial involving posts and users, if we tracked that each post was associated with a user id, and we had two entities, users and posts, how can we express that relationship between the two?

Thanks again for all the help and all you guys do!

**Comment by markerikson** [comment]
Part of the idea of "normalization" is that items express relationships to each other by storing the IDs of other items.  For example, the `post` object refers to the user who wrote it as `post.user`, and we can then look up the right user object with that ID.

RTK does not currently include any functionality to help you specifically manage relationships.  For lighter-weight behaviors, you can generally write the code to do that sort of thing yourself.  If you have some _very_ complex relational data, you may want to look at something like https://redux-orm.github.io/redux-orm/ as a more powerful solution.

**Comment by leo-vannini** [comment]
Thanks for the answer and insight, Mark!

Should I close this issue?

**Comment by markerikson** [comment]
Assuming that answers your question, yeah, I'll go ahead and close it.
