### ISSUE TITLE
[Feature Request] Type improvement createReducer

### ISSUE THREAD

**Issue by tkow** [reduxjs/redux-toolkit#670]
I use bellow extension types of redux-toolkit in my project.
I suggest you would add bellow extension types in this library for createReducer overload .

```typescript
import { Reducer } from '@reduxjs/toolkit'
declare module '@reduxjs/toolkit' {
  export type DefinedActions<ActionCreators> = ReturnType<
    ActionCreators[keyof ActionCreators]
  >
  interface GeneralActionCreator {
    (...args: any[]): any
    type: string
  }

  export type ActionReducerMap<
    State,
    IActionCreators extends {
      [key in string]: GeneralActionCreator
    }
  > = {
    [key in IActionCreators[keyof IActionCreators]['type']]: (
      state: State,
      action: ReturnType<
        Extract<IActionCreators[keyof IActionCreators], { type: key }>
      >
    ) => State
  }

  export declare function createReducer<
    S,
    IActionCreators extends {
      [key in string]: GeneralActionCreator
    }
  >(
    initialState: S,
    actionsMap: ActionReducerMap<S, IActionCreators>,
    actionMatchers?: ActionMatcherDescriptionCollection<S>,
    defaultCaseReducer?: CaseReducer<S>
  ): Reducer<S>
}
```

and I create bellow example actions.
```typescript
 export default {
  setUser: createAction<AuthState['user'], 'auth/setUser'>(
    'auth/setUser'
  ),

  setIsAuthenticated: createAction<
    AuthState['isAuthenticated'],
    'auth/setIsAuthenticated'
  >('auth/setIsAuthenticated'),

  setPermissions: createAction<
    AuthState['permissions'],
    'auth/setPermissions'
  >('auth/setPermissions'),
}
```

When you create reducer with createReducer API.
You can infer the reducer's actions' type and acquire warning if you forget defining reducers should implement action type in the actions specifying this typeof actions like bellow.

```typescript
type AuthActionCreatorMap = typeof actions

const exampleReducer = createReducer<AuthState, AuthActionCreatorMap>(initialState(), {
  [actions.setIsAuthenticated.type]: (state, action) => state,
  [actions.setUser.type]: (state, acton) => state,
  [actions.setPermissions.type]: (state, action) => state,
})
```

I show you vscode example images.

![スクリーンショット 2020-07-24 15 11 23](https://user-images.githubusercontent.com/7004725/88371285-aeedd280-cdce-11ea-8d2c-10b891f094d3.png)
![スクリーンショット 2020-07-24 16 57 53](https://user-images.githubusercontent.com/7004725/88371359-d6dd3600-cdce-11ea-8171-9cde8c18e917.png)

If It is helpful for users, I make pr.

**Comment by phryneas** [comment]
If you want a 1:1 mapping between a certain set of actions and a reducer, I'd recommend you use `createSlice`, where you define the reducers and it automatically generates all the action creators from that.
That way, you have a guarantee that there is a reducer for every action creator, which is what you want if I interpret your suggestion correctly.

The intended use of `createReducer` is rather one, where you mix actions from many different sources into one reducer - and in that case, your suggestion would really just shift the problem from defining a reducer to defining an union type that needs to be complete.

I have to say that I really like your TypeScript there (just from reading, I haven't tested it) and especially the use of `Extract` - but I personally think this is not something we'll add, as the focus of Redux Toolkit is to get people to write less types using type inference, not more (Redux is confusing enough for newcomers anyway) and this even just being present might lead people on a path they don't need to learn to walk. Most people should use `createSlice` in this exact situation.

@markerikson might have another opinion though, let's see ;)

**Comment by tkow** [comment]
@phryneas Thank you for a quick response.

I tried and recognized what you mean.
That's true, I can get type hints from even if I convert arguments different types from start to payload with typing reducer's action.

```typescript
      const testSlice = createSlice({
        name: 'test',
        initialState: 0,
        reducers: {
          testAction: {
            reducer: (
              state,
              action: {
                payload: string
              }
            ) => Number(action.payload),
            prepare: (a: string, b: number) => ({
              payload: a
            })
          }
        }
      })
```

Though, I prefer ducks rules and often divide a redux file to actions, reducers, state, so on for prevent exploding code lines. In addition, we reuse some redux codes using redux-actions and glad to use my suggested features because these may  improve portability.
But  I don't have any trouble now even if this is not accepted . It's Okey for me to close this issue.

**Comment by tkow** [comment]
I rewrite these types in my library because it had some bugs. 
This library I make is for light weight duplicating redux component and portability.
If it's something helpful for you, be comfortable to use.

https://github.com/tkow/redux-duplicator/blob/master/types/redux-toolkit.d.ts
https://github.com/tkow/redux-duplicator/blob/master/test/%40redux-toolkit-integration.test.ts

**Comment by markerikson** [comment]
Yeah, I'm with @phryneas here. I think this is interesting at a technical level, but not exactly in line with how we're trying to get folks to use RTK.

Thanks anyway!
