### ISSUE TITLE
type issue with thunk action return type using condition

### ISSUE THREAD

**Issue by ShravanSunder** [reduxjs/redux-toolkit#674]
**I have the following thunk action** 
```
const getStore = createAsyncThunk(
    `timeline/store/getStore`,
    async ({ storeGuid }: { storeGuid: string }, thunkApi): any => {
        return await getStoreApi(storeGuid);
    },
    {
        condition: ({storeGuid}: {storeGuid: string}, thunkApi) : boolean | undefined=> {
            let s = storeInfoSelector(thunkapi.getState());
            if (s.storeGuid == storeGuid || storeGuid == null) return false;
        },
    }
)

```
```
When i don't have the condition  parameter the getStore type is
const getStore: ((arg: {
    storeGuid: string;
}) => AsyncThunkAction<any, {
    storeGuid: string;
}, {}>) & {
    pending: ActionCreatorWithPreparedPayload<[string, {
        storeGuid: string;
    }], undefined, string, never, {
        arg: {
            storeGuid: string;
        };
        requestId: string;
    }>;
```
**however when i add the condition the type changes to** 
```

const getStore: (() => AsyncThunkAction<unknown, void, {}>) & {
    pending: ActionCreatorWithPreparedPayload<[string, void], undefined, string, never, {
        arg: void;
        requestId: string;
    }>;
    rejected: ActionCreatorWithPreparedPayload<...>;
    fulfilled: ActionCreatorWithPreparedPayload<...>;
    typePrefix: string;
}
```

**The issue is with the**  <unknown, void, {}> **versus** <any, {storeGuid: string;}, {}>
i can't currently use the thunk properly in my component as typescript complains about the function used with a parameter when none is expected.

I'm not sure how to force the thunk type to retain my typing

_>  TS2554: Expected 0 arguments, but got 1._

**Comment by phryneas** [comment]
I just tested this in a codesandbox (see https://codesandbox.io/s/eloquent-keller-vp85m?file=/src/App.tsx ) and it seems to be working correct for me. Can you provide a reproduction of this?

Also, in general once you start using `thunkApi.getState()` usually you need to provide generic arguments as described in the documentation:
https://redux-toolkit.js.org/usage/usage-with-typescript#createasyncthunk

**Comment by phryneas** [comment]
Also, are you using WebStorm? We've had another case where in WebStorm, incorrect types were shown because they try to speed up things with an incorrect algorithm.

**Comment by ShravanSunder** [comment]
i'm not using webstorm.  Its a react app hosted in asp.NET.  part of the app is in plain js.  And some of it is in typescript.  
I"ve been converting it to typescript as i go.

I tried recreating this in codesandbox and it seems to work fine.  i'm trying to think of how i could send a reproduction other wise

**Comment by ShravanSunder** [comment]
oh once i added the generic arguments it worked!

`const getStore = createAsyncThunk<any, getStoreType, any>(`

thanks so much for the pointer! @phryneas
