### ISSUE TITLE
[Redux-toolkit] [createEntityAdapter] Cannot read property 'ids' of undefined

### ISSUE THREAD

**Issue by daminhtung** [reduxjs/redux-toolkit#675]
Hi, I got an error when running the test. Any help or suggestions for me?

- redux-mock-store: ^1.5.4
- "@types/redux-mock-store": "^1.0.2",
- "@reduxjs/toolkit": "^1.3.5",
- "@testing-library/react-native": "^5.0.3",

### Error when run testing

`TypeError: Cannot read property 'ids' of undefined`

>       47 |   const items = useSelector((state: MyState) => {
>     > 48 |     return myEntityAdapter.getSelectors().selectAll(state.mystate)
>             |                                         ^
>       49 |   })
>       50 | 
> 

My test:
```
const { queryByTestId } = render(
      <Provider store={store}>
        <MenuProvider skipInstanceCheck={true}>
          <MyComponent />
        </MenuProvider>
      </Provider>
    )
```

`mySlice.ts`

```
...
export const myEntityAdapter = createEntityAdapter<Item>()
...
```

**Comment by markerikson** [comment]
Does `state.mystate` actually exist at that point in time?

Note that you shouldn't generally be calling `getSelectors()` in app code like that.  Instead, you should be calling it once in the slice file and exporting them.  You also probably should be generating "globalized" selectors by passing in a selector that accepts the root state and returns this specific slice, like `export const {selectAll : selectAllItems} = itemsAdapter.getSelectors(state => state.items)`:

https://redux-toolkit.js.org/api/createEntityAdapter#selector-functions

**Comment by tylercaceres** [comment]
I get the same issue.
Were you able to resolve it?

This is what i get in the console log when I try to run the app:
function createSelectorsFactory() {
  function getSelectors(selectState) {
    var selectIds = function selectIds(state) {
      return state.ids; // <--- this is where it says the error is even though i pass a custom selectId function
    };

I use this:
export const fakeAdapter = createEntityAdapter({
  selectId: chat => chat.fake_id
});

**Comment by tylercaceres** [comment]
> Does `state.mystate` actually exist at that point in time?
> 
> Note that you shouldn't generally be calling `getSelectors()` in app code like that. Instead, you should be calling it once in the slice file and exporting them. You also probably should be generating "globalized" selectors by passing in a selector that accepts the root state and returns this specific slice, like `export const {selectAll : selectAllItems} = itemsAdapter.getSelectors(state => state.items)`:
> 
> https://redux-toolkit.js.org/api/createEntityAdapter#selector-functions

Hello @markerikson ,
I've exported directly from the slice file as:

fakeSlice.js
`export const {
  selectIds: selectChatIds,
  selectEntities: selectChatEntities,
  selectAll: selectAllChats,
  selectTotal: selectTotalChats,
  selectById: selectChatById
} = omnichannelAdapter.getSelectors(state => state.omnichannel);`

However, i have another file - that contains my selectors. Trying to include these above selectors into the selectors.js file, it fails the jest tests as well.

selectors.js
`import {
  selectChatIds,
  selectChatEntities,
  selectAllChats,
  selectTotalChats,
  selectChatById
} from './fakeSlice';

export {
  selectChatIds,
  selectChatEntities,
  selectAllChats,
  selectTotalChats,
  selectChatById
};`

Might you know why? I exported the selectors as you mentioned above.

**Comment by markerikson** [comment]
Afraid I'd need to see an example that reproduces this issue to really have any suggestions here, sorry.

**Comment by poww10s** [comment]
Hi! I just saw this in the closed issues. I'm also having this issue.

I export the selectors in the slice file:
![image](https://user-images.githubusercontent.com/6687517/99477312-4350e780-2920-11eb-9fe7-feef75471654.png)

and I call the selector in my component:
![image](https://user-images.githubusercontent.com/6687517/99477355-5a8fd500-2920-11eb-8962-60d3e0d7c408.png)

but this happens on compile!
![image](https://user-images.githubusercontent.com/6687517/99477380-64b1d380-2920-11eb-961a-d58f5dd5ca2c.png)

and if I check the redux state...
![image](https://user-images.githubusercontent.com/6687517/99477411-74311c80-2920-11eb-8f45-c5a7665f6ee3.png)

It does indeed exist!

using the useSelector hook from React-Redux manually works and finds the state as existing, but I can't seem to get this to work even if I define the state for the selectors in my component, it just can't seem to find them.

**Comment by markerikson** [comment]
@poww10s yeah, that's happening because you're actually calling `selectAll()` without passing in an actual Redux state value :)

`const timbre = timbreSelectors.selectAll()`

the point of a Redux selector is that you have to pass in the entire Redux state value as the argument.  (Technically it's possible to reorder the arguments, but in practice they always get written and used as `selectSomething(state, otherArg1, otherArg2)`.

In a component, you don't have access to the actual `state` value, so you're supposed to pass that to `useSelector`, which then grabs the store instance from context and calls `yourSelector(store.getState())`.

**Comment by daminhtung** [comment]
Just set init state like this, i resolved my problem.
Thanks all.

```
 const initialState = myAdapter.getInitialState({
      entities: { ... },
      error: null,
    })
```

**Comment by poww10s** [comment]
so what am I doing wrong here?
![image](https://user-images.githubusercontent.com/6687517/99479013-6e890600-2923-11eb-96f1-a463fb6df8a5.png)
![image](https://user-images.githubusercontent.com/6687517/99479034-7779d780-2923-11eb-8b72-cb8d63b485db.png)

it also happens it if I do this: 
![image](https://user-images.githubusercontent.com/6687517/99479177-a728df80-2923-11eb-9c41-7ec7f93834d8.png)

![image](https://user-images.githubusercontent.com/6687517/99479165-a2642b80-2923-11eb-92df-bfcabede3b2d.png)

**Comment by markerikson** [comment]
Effectively all selectors, including `selectAll`, must have the Redux `state` value passed in as the first argument.

So, `selectAll()` here is passing `undefined` as the first argument.  That is _not_ the Redux state :)

The correct usage would be `selectAll(state)`, but like I said - in a component, you don't have access to the `state` object in the component to begin with.  That's the whole point of `useSelector`.

You might want to read through https://redux.js.org/tutorials/fundamentals/part-5-ui-react and https://blog.isquaredsoftware.com/2018/11/react-redux-history-implementation/ to get a better understanding of what React-Redux actually does for you, and https://blog.isquaredsoftware.com/2017/12/idiomatic-redux-using-reselect-selectors/ to understand how to use selectors correctly.

**Comment by poww10s** [comment]
![image](https://user-images.githubusercontent.com/6687517/99479334-f838d380-2923-11eb-8092-30d2c79ba732.png)

I am also setting my initialState like that @daminhtung 

doing this works: 
![image](https://user-images.githubusercontent.com/6687517/99479376-0dadfd80-2924-11eb-940c-a4cc10f1e0ab.png)
but I would rather not have to reinvent the wheel further down the line when I'm trying to grab a lot of values

**Comment by markerikson** [comment]
The right usage here would be either:

```js
// pass the selector here - don't call it yourself!
const timbreItems = useSelector(timbreSelectors.selectAll);
```

or:

```js
const oneSpecificItem = useSelector(state => timbreSelectors.selectById(state, "someId"));
```

but calling `timbreSelectors.selectAll()`, by itself, is wrong - because you haven't passed in a `state` value.

**Comment by poww10s** [comment]
@markerikson oh I see my mistake now. 
thank you!

**Comment by daminhtung** [comment]
@poww10s 
@markerikson said right.
And my case just uses in testing with jest.
