### ISSUE TITLE
Property 'then' does not exist on type 'AsyncThunkAction'

### ISSUE THREAD

**Issue by ezhikov** [reduxjs/redux-toolkit#678]
Hi. I'm following instruction on how to get thunk result in place where dispatch was called, but typescript don't see `AsyncThunkAction` as thenable. I tried both approaches, from [createAsyncThunk doc page](https://redux-toolkit.js.org/api/createAsyncThunk) and from [usage with Typescript](https://redux-toolkit.js.org/usage/usage-with-typescript#createasyncthunk). In second case I'm getting ```Argument of type 'AsyncThunkAction<boolean, number, {}>' is not assignable to parameter of type 'Action<unknown>'.
  Property 'type' is missing in type 'AsyncThunkAction<boolean, number, {}>' but required in type 'Action<unknown>'.ts(2345)```

Here is [sandbox](https://codesandbox.io/s/sleepy-ganguly-vdof9?file=/src/App.tsx) with both approaches.

**Comment by phryneas** [comment]
You need to [type your dispatch correctly](https://redux-toolkit.js.org/usage/usage-with-typescript#getting-the-dispatch-type).

**Comment by ezhikov** [comment]
Yes. My bad. I somehow missed this. Thank you.
