### ISSUE TITLE
npm ERR! 404 Not Found 

### ISSUE THREAD

**Issue by sonuKumar03** [reduxjs/redux-toolkit#682]
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@reduxjs%2ftoolkit - Not found

### npm log 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '@reduxjs/toolkit' ]
2 info using npm@6.14.7
3 info using node@v14.7.0
4 verbose npm-session 7ead6690692113a0
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@reduxjs%2ftoolkit 1263ms
8 http fetch GET 404 https://registry.npmjs.org/@reduxjs%2ftoolkit 479ms
9 silly fetchPackageMetaData error for @reduxjs/toolkit@latest 404 Not Found - GET https://registry.npmjs.org/@reduxjs%2ftoolkit - Not found
10 timing stage:rollbackFailedOptional Completed in 3ms
11 timing stage:runTopLevelLifecycles Completed in 3850ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@reduxjs%2ftoolkit - Not found
12 verbose stack     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:114:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
13 verbose statusCode 404
14 verbose pkgid @reduxjs/toolkit@latest
16 verbose Linux 5.4.0-42-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "@reduxjs/toolkit"
18 verbose node v14.7.0
19 verbose npm  v6.14.7
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/@reduxjs%2ftoolkit - Not found
22 error 404
23 error 404 '@reduxjs/toolkit@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

**Comment by capfsb** [comment]
Same problem here

**Comment by phryneas** [comment]
This is a npm outage: https://status.npmjs.org/

I'll leave this issue open until that is resolved so people see it first when looking at the issues.

**Comment by sonuKumar03** [comment]
Now It is Working :
issue resolved
