### ISSUE TITLE
Map show up as empty object in redux devtools

### ISSUE THREAD

**Issue by steinarb** [reduxjs/redux-toolkit#683]
See the issue https://github.com/reduxjs/redux-devtools/issues/496

[Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) shows up as empty object (i.e. "{}") in redux devtools.

The rationale for getting it working again (i.e. it used to work and no longer works, and Map is a very useful datatype to use), is here: https://github.com/reduxjs/redux-devtools/issues/496#issuecomment-623255605

The suggested fix/workaround is to set up serialize in the redux-devtools options: https://github.com/reduxjs/redux-devtools/issues/496#issuecomment-670246737

But since setting up redux-devtools is handled inside redux-toolkit, I need redux-toolkit to do it.

Is it possible to have redux-toolkit set up redux-devtools so that Map will show up?

**Comment by steinarb** [comment]
I was able to set serialize to true using the [devTools parameter to configureStore](https://redux-toolkit.js.org/api/configureStore#devtools), like so:
```
const store = configureStore({
    reducer: createRootReducer(history),
    middleware: [
        sagaMiddleware,
        routerMiddleware(history),
    ],
    devTools: { serialize: { options: true } },
});
```

So what I'm arguing for now, is that the default should be to set up devtools with serialize set to true (I understand there may be performance considerations).

**Comment by phryneas** [comment]
We [explicitly recommend against](https://redux.js.org/style-guide/style-guide/#do-not-put-non-serializable-values-in-state-or-actions) using objects that cannot be trivially reserialized using JSON.parse in the store, as this does not only need extra configuration of the devtools, but might also cause all kinds of problems with third-party middlewares like `redux-persist` and for everything except Map and Set also with `immer`.

So enabling this by default would probably send a wrong signal ;)

**Comment by markerikson** [comment]
We have always [specifically told users to _never_ put non-serializable values into the Redux store](https://redux.js.org/style-guide/style-guide#do-not-put-non-serializable-values-in-state-or-actions), exactly for this reason.  Use of `Map`s in the store also will likely lead to bugs where your UI does not re-render properly, because React-Redux relies on reference checks to determine if values have changed.
