### ISSUE TITLE
Actions aren't resolved with generic slice return types

### ISSUE THREAD

**Issue by huwshimi** [reduxjs/redux-toolkit#689]
When adding a return type to a generic createSlice function the action types are no longer resolved.

Here is the example from the docs with the return type added:

```ts
export const createGenericSlice = <
  T,
  Reducers extends SliceCaseReducers<GenericState<T>>
>({
  name = "",
  initialState,
  reducers,
}: {
  name: string;
  initialState: GenericState<T>;
  reducers: ValidateSliceCaseReducers<GenericState<T>, Reducers>;
}): Slice<GenericState<T>, Reducers, string> => { // Return type added here
  return createSlice({
    name,
    initialState,
    reducers: {
      start(state) {
        state.status = "loading";
      },
      /**
       * If you want to write to values of the state that depend on the generic
       * (in this case: `state.data`, which is T), you might need to specify the
       * State type manually here, as it defaults to `Draft<GenericState<T>>`,
       * which can sometimes be problematic with yet-unresolved generics.
       * This is a general problem when working with immer's Draft type and generics.
       */
      success(state: GenericState<T>, action: PayloadAction<T>) {
        state.data = action.payload;
        state.status = "finished";
      },
      ...reducers,
    },
  });
};

const wrappedSlice = createGenericSlice({
  name: "test",
  initialState: { status: "loading" } as GenericState<string>,
  reducers: {
    magic(state) {
      state.status = "finished";
      state.data = "hocus pocus";
    },
  },
});

const actions = wrappedSlice.actions;

actions.magic(); // Works fine
actions.start(); // Not found
actions.success(); // Not found
```

The start and success actions are not resolved: `Property 'success' does not exist on type 'CaseReducerActions<{ magic(state: { data?: string; status: "loading" | "finished" | "error"; }): void; }>'.`.

Removing the return type allows the actions to resolve.

Am I providing the wrong return type or do I have to resolve the actions in another way?

Here is a [playground](https://www.typescriptlang.org/play?ssl=25&ssc=3&pln=25&pc=45#code/JYWwDg9gTgLgBAbwFBzgYygUwIY0wZQBtg1MAaFOABWwE9CJsATAQTRmAgDsLUiTMAYWwBnTACVMTAK6koI3nABq2Yk1wFipYWMky5Cyv1IUAvnABmUCCDgAiAAJYZADwBWIgPQwIEQgGtgGDsAbiQkYC48KAtsUjgAcUwuTCgSfBgNAB4AFQA+REp1TIB+AC44HLDUEUyYaREKuwZmSIBzOzgAH3sLSOARAAspTp67VOsoUKRTcMwXSFh0blr0LA0klLS0Y0w4AF44LMocxT1ZVJE4ebwuJivdnQkpC-kszdT0usxcvLykPIACmQqC42BAe0Odjsin6HFUGQ0imcr0MpgqILgYIhFVqaS4bWqcDhwAR3wqH22iLwvyJKIMFRUag0j1Ez30l3eyU+O2+vzIcHOBjyYVMAEoKrsuVsvtl8gKhZcBXj2gV9gVMVh6lAuGscHhdsDKKDweRjcSuEFSYRqWbUKh6ZcMeaaplYIDahoxYV7b64J68AA6AMNA72FpMdrTP1wUyKX2eABUiZdqETcAAkhY4LQINI4AB3bBROA+QtpPCliBwABuqmkmCuEGzMGG-u+pcGuDgTEwYGSTDg3E7eza3O2qbg6cBkU7A3QbIqAAMA5hA8VsEuBQXBiRBsSrjkxQLc-mQMA2oN4CkpFX-f20MALLQR5P07bS7R+3AQMXpKpCBfYYsAFURiXgXtYmkQgYCuMslwAESgbALBgaUeVtX48i3N9C13NB9zQYt-RsTAOAhK4ACM9jAaxKMITBfw4NBCyCfdaDIgBaaQuCwEQ-BrW8xxlNAREDXCcl3K552wOBhNSVQ4FoiB6MYvDkkLaBAgJVjW2JEAISgAByK4kJQ+AYC-PZi0HeTtjEt9PFTERZFIEQRA9clEnHWUaXlOA4g4bgKhoehGFYdhOC4X5vUxGNV3XXBZMOQKosDMA6AjIl4u+YM6lDKE+ktIYRmy+041TQMqsdeR41jRRxVFMIkDQFZ4ALZCwH7JhdjDDB9UwSl0i0TAjRNHF7DwWoYUoEkyQ0DF21wBomgjKNYwCq4ht5bIVQJPJkReBkfXtX82hITyvRO30EpDK5Cv6EqmGjP0Eo3MM7EGCA0FDSAfpEF7UAqoGzDFZrWq4VZUpWMMOuwLqpF2QNoch5qUbEs6LrB8J0by7B3WxpBcZctA3I8uwpuCbGgA) with this code and errors.

I noticed createSlice is being updated, so maybe this issue will be resolved in the PR: https://github.com/reduxjs/redux-toolkit/pull/637.

**Comment by markerikson** [comment]
Out of curiosity, why are you trying to specify a return type there in the first place?

**Comment by huwshimi** [comment]
@markerikson we have [@typescript-eslint/explicit-module-boundary-types](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md) turned on in our project.

**Comment by markerikson** [comment]
Well, that's why.  Turn off that lint rule :)

If it compiles and runs fine without explicitly declaring a return type, then you don't need it here.

Lint rules are supposed to _help_ you.  If a lint rule doesn't "spark joy", turn it off :)

**Comment by huwshimi** [comment]
@markerikson hah, fair point. I might just do that :).

**Comment by phryneas** [comment]
Yeah, have to agree very strongly with Mark there. RTK enables you to write a lot less TS code, but when you start specifying it's types manually, you're in for a very bad time. I'd also suggest turning that rule off.

**Comment by huwshimi** [comment]
Thanks a lot @phryneas and @markerikson, I'll do without the rule.
