### ISSUE TITLE
[FEATURE] getState inside the prepare callback for an action creator

### ISSUE THREAD

**Issue by monsonjeremy** [reduxjs/redux-toolkit#692]
It doesn't seem currently possible, but I would like to be able to use `getState` inside the action creator prepare callback like so

```javascript
const addTodo = createAction('todos/add', function prepare(text, thunkAPI) {
  const someOtherState = getRelatedState(getState())
  const result = performSomeLogic(someOtherState, text)
  return {
    payload: {
     result
    }
  }
})
```

Is this possible at all?

**Comment by phryneas** [comment]
No, that function isn't available, as the action creator (and thus, prepare) could be called anywhere and even with multiple stores.

Also, it seems as if you're moving logic from the reducer to the action creator. That does not seem like a good practice, business logic should reside specifically in the reducer. 
Do you have a specific reason for that?

**Comment by monsonjeremy** [comment]
@phryneas I was thinking this is useful if the action creator needs access to a part of the state that lives in a different reducer. For instance maybe my state tree looks like this
```javascript
{
    user: {
       id: '123'
    }
    todos: {
    ...
    }
}
```

I could totally use the `createAsyncThunk` function, but my logic is synchronous so it seems confusing.

**Comment by phryneas** [comment]
Yeah, you better write a traditional thunk if you really need access to `getState`. Definitely no `createAsyncThunk` situation.

But even in your case, that looks like you are merging state values together that could exist independently. 
Most of the time it's still possible to keep those completely individual and just calculate the derived state in the selector. That way you don't risk keeping the same data (or values derived from the same data) in two different places and having that go out of sync somehow.

**Comment by monsonjeremy** [comment]
@phryneas True, I could definitely pass the `user.id` into the action wherever it's called instead of relying on plucking it off the tree in the action. Thanks for the really quick response, feel free to close!
