### ISSUE TITLE
addMatcher type error in typescript: ts(2345)

### ISSUE THREAD

**Issue by wangming-0215** [reduxjs/redux-toolkit#693]
The `matcher` argument of `addMatcher` function has wrong type in typescript.

```
type LoadingState = { loading: boolean };

const initialState: LoadingState = {
  loading: Loading.Idle,
};

const slice = createSlice({
  name: '@loading',
  initialState: initialState,
  reducers: {},
  extraReducers: (builder) => {
    builder.addMatcher(
      (action) => action.type.endsWith('/pending'),
      (state, action) => {
        console.log('loading: ', state, action);
      }
    );
  },
});
```
![2020-08-13_10-04](https://user-images.githubusercontent.com/21071580/90086490-199a8a00-dd4d-11ea-9cbb-dc6225ea0227.png)

**Comment by msutkowski** [comment]
That error should show that it must be a type predicate. You can type it like this:

```ts
.addMatcher((action): action is AnyAction => action.type.endsWith('/pending'), (state, action) => {})
```

I'd recommend changing out `AnyAction` for whatever you know the type of that action is going to be. If you're just using it for a boolean or the actual action payload doesn't matter, `AnyAction` is fine.

**Comment by wangming-0215** [comment]
> That error should show that it must be a type predicate. You can type it like this:
> 
> ```ts
> .addMatcher((action): action is AnyAction => action.type.endsWith('/pending'), (state, action) => {})
> ```
> 
> I'd recommend changing out `AnyAction` for whatever you know the type of that action is going to be. If you're just using it for a boolean or the actual action payload doesn't matter, `AnyAction` is fine.

Thx! I had solved this problem just like you said. And I attempt to manage the loading state in a separate reducer, so I think `AnyAction` is fine

**Comment by MichalW** [comment]
Maybe this answer will help you:
https://stackoverflow.com/a/64917926/3532554
