### ISSUE TITLE
'current' is not exported from 'immer'.

### ISSUE THREAD

**Issue by fifinfield** [reduxjs/redux-toolkit#694]
reduxjs/toolkit 1.4.0

./node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js
Attempted import error: 'current' is not exported from 'immer'.

What is the issue and fix for this?

**Comment by markerikson** [comment]
Dunno what to tell you. We clearly export it:

https://github.com/reduxjs/redux-toolkit/blob/b1a1dac3ac396719583b0105cdfc3160c07e7356/src/index.ts#L3

Double-check to make sure you have Immer 7 installed.

**Comment by ravola** [comment]
@markerikson Yes i noticed that too and wondered why would it fail. Apparently my command prompt was not opened in administrator mode. When i open in administrator more and run it works fine. However, does it matter if the command prompt is not in admin mode?

**Comment by fifinfield** [comment]
@markerikson  Yes i noticed that too and wondered why would it fail. Apparently my command prompt was not opened in administrator mode. When i open in administrator mode and run, it works fine. However, does it matter if the command prompt is not in admin mode?

**Comment by phryneas** [comment]
It should not matter, but it could be all sorts of weird configuration on your machine, like the admin prompt having a different PATH variable and using a different node version or something.

Generally, you should never run anything as administrator except if you are making active modifications to your operating system or need to install software for all users of your machine. It is definitely never required to actively do software development.
It is a possibility that you did a `npm install` or `yarn install` as administrator (which you should NEVER do, as node packages can run arbitratry code on installation) and that the `immer` module folder is owned by administrator now and cannot be accessed by your normal user.
Best to delete node_modules folder and run `npm/yarn install` as a normal user again.

**Comment by fifinfield** [comment]
@phryneas Thank you. I will verify this.
