### ISSUE TITLE
Typescript, reducer's action type equal AnyAction

### ISSUE THREAD

**Issue by Luchanso** [reduxjs/redux-toolkit#708]
When slice created, reducer's action is AnyAction, I think it's not critical, but why? 🙂 
We can't infer type from reducers in slice?
![image](https://user-images.githubusercontent.com/2098777/91076599-67b26600-e648-11ea-84be-e5776260b990.png)

**Comment by Luchanso** [comment]
Oh, I know answer, because reducer can accept all actions, right?

**Comment by markerikson** [comment]
Exactly. 

A slice reducer can (and _will_) be called with "any action" that is dispatched in the app.

Your specific case reducers will be matched against specific action types, so _they_ can say they expect the action they receive is a more specific type.

**Comment by Luchanso** [comment]
Thank you!
