### ISSUE TITLE
Importing data into initialState of createSlice from file causes a state mutation error, but defining the same value does not

### ISSUE THREAD

**Issue by namsnath** [reduxjs/redux-toolkit#711]
Hi,
I have a new reducer defined like so:
```
import { createSlice } from '@reduxjs/toolkit';
import CLASHMAP from '../constants/ClashMap';

const initialState = {
    data: JSON.parse(localStorage.getItem('timetable')) || [],
    timestamp: localStorage.getItem('timetableTimestamp') || null,
    clashmap: CLASHMAP,
};

const timetableSlice = createSlice({
	name: 'timetable',
	initialState,
	reducers: {},
});

export default timetableSlice.reducer;
```

The clashmap being imported has a structure like so:
```
{
  A1: {
    clashesWith: ['A1',],
    isFilled: false,
    currentlyClashesWith: [],
  },
  B1: {...}
}
```

And the error being thrown is: 
```
Error: Invariant failed: A state mutation was detected between dispatches, in the path 'timetable.clashmap.A1.currentlyClashesWith'.  This may cause incorrect behavior. (https://redux.js.org/troubleshooting#never-mutate-reducer-arguments)
```

I do not get the issue, since all I am doing is adding the slice reducer to the root reducer, not modifying state anywhere.

If I define the exact same value that is being imported directly in the `initialState` object, it does not throw the error.

Any insight into this would be appreciated. If this is a bug, I would like to try and submit a fix if possible.

StackOverflow [link](https://stackoverflow.com/questions/63621361/redux-detects-a-state-mutation-on-populating-initialstate-with-an-import-not-wh)

**Comment by phryneas** [comment]
The error message means that you modified data from the state *between dispatches*, meaning you modified it somewhere outside of redux, probably in a component like this:

```js
function MyComponent(){
  const myData = useSelector(state => state.timetable.clashmap.A1);
  myData.currentlyClashesWith = { ... }
}
```

**Comment by namsnath** [comment]
This part of the state isn't hooked up anywhere. 
And it's definitely an issue with this particular reducer, since removing the reducer solves the issue.

Also, like I mentioned before, if I define the exact same object in the reducer file, there is no error. If I import the object, there is an error.

**Comment by phryneas** [comment]
Then I'd assume your bundler does some magic and fills in some data at a later time, which is weird but would not be unheard of.

Try doing
```js
console.log({...initialState})
setTimeout(() => console.log({...initialState}), 1000)
```

in that file. It's pretty likely that there will be a difference between the two console.logs.

**Comment by namsnath** [comment]
So I got this:
```
{"data":[],"timestamp":null,"clashmap":{"A1":{"clashesWith":["A1","L1","L2","L13","L14"],"isFilled":false,"currentlyClashesWith":[]}}}
```

and

```
{"data":[],"timestamp":null,"clashmap":{"A1":{"clashesWith":["A1","L1","L2","L13","L14"],"isFilled":false,"currentlyClashesWith":[]}}}
```

Looks identical to me

**Comment by namsnath** [comment]
Okay, so the error stack trace mentioned a particular line. I removed the dispatch from there, and the error disappears.
This is not ideal since I need that call. 
It also happens with every other dispatch I do. Every dispatch throws the same error.

The thing bugging me is still how the import does not work, but the defined value does.

**Comment by markerikson** [comment]
@namsnath FWIW, this thread isn't a great place for us to give support. That said, it would help if you could actually show us the stack trace, and the relevant lines of code.

**Comment by namsnath** [comment]
@markerikson I was just setting up a project to see if I can replicate the issue in a clean repo. I'll put up a link in a bit.
Thanks for all the help till now though!

**Comment by namsnath** [comment]
Hey, I can't seem to reproduce the issue in a clean repo.
I'll try to figure this out.
Thanks a lot for the help @phryneas @markerikson !

**Comment by namsnath** [comment]
I think I figured out the issue.
I was importing the same constant somewhere else in my app. (I'm slowly porting everything to use redux)
This is independent of redux. One of the hooks there uses the clashmap as an initial state and then performs actions on it.
Creating a copy of the file and importing that in Redux fixed the issue.

I assumed initialising the hook with the constant would create a copy, but I guess that is not how it works.

Thanks guys, Cheers!

**Comment by markerikson** [comment]
Yeah, I figured something like that was likely the case :)  Glad you got it figured out!
