### ISSUE TITLE
Any plan about using Tuple/Record proposal?

### ISSUE THREAD

**Issue by marcog83** [reduxjs/redux-toolkit#718]
Hi, I love redux toolkit.
 it helps me and my team designing a micro frontend application.😍
tc39 has Tuple and Record proposal about two new deeply immutable data structures to JavaScript. Toolkit uses immer.js to cover this aspect. I'd like to ask if redux-toolkit considers this proposal a valid option  to deal with immutability. 
Is there any plan to investigate if Tuple/Record can replace immer.js?

thanks a lot for your great work

**Comment by phryneas** [comment]
As right now, the polyfills are only able to run without memory leaks in Chrome canary, it's probably a little early for that. But yeah, those are definitely gonna be great and, in combination with [Deep Path Properties in Record Literals](https://github.com/tc39/proposal-deep-path-properties-for-record) might be an alternative for immer. But right now, they are probably years away.

**Comment by markerikson** [comment]
Yeah. This is still far enough out it's not even worth paying any attention to for us, and given that we _do_ have Immer in here already, I see no reason to change that any time soon.
