### ISSUE TITLE
Typing problem with `createAsyncThunk`

### ISSUE THREAD

**Issue by garronej** [reduxjs/redux-toolkit#722]
Hi,

I think there is a problem with the types of the `pending`, `fulfilled` and `rejected` properties of the function returned by `createAsyncThunk`, shouldn't they be `string`s?  

Otherwise, the [overview example](https://redux-toolkit.js.org/api/createAsyncThunk) gives types error: 

![image](https://user-images.githubusercontent.com/6702424/92912005-afe3cd80-f429-11ea-820a-154bcb0d4b85.png)

Best regards

**Comment by phryneas** [comment]
Nope, those are action creators. You should use the builder notation if using TypeScript.

https://redux-toolkit.js.org/usage/usage-with-typescript#type-safety-with-extrareducers

**Comment by garronej** [comment]
Ok my bad, sorry for not reading through
