### ISSUE TITLE
Make clearer how to not mutate state when you want to.

### ISSUE THREAD

**Issue by klequis** [reduxjs/redux-toolkit#725]
Here is a suggestion that would make the doc clearer to me. Don't know if that is the majority of the user base. I have only read 80% of the doc so could have missed something, so apology if I did.

I got from the doc that you 'could mutate state or not but not both' and the doc was clear to me on how to mutate state but no on how to not mutate when you didn't want to.

This thread made it clear to me: https://github.com/reduxjs/redux-toolkit/issues/242

If I'm understanding things correctly:

mutate state
```js
state.something = something
```

don't mutate
```js
return newState
```

I accidentally did (i.e., not mutation0
```js
state = newState
```
And spent a while trying to figure how why the store was not updating.

> hope I got that work but my code is working now

I think a useful addition would be to 
1. make it clearer that in the rare case you don't want to mutate state you just need the `return` keyword with the new state. 
2. I also didn't see any place that said what would the result will be if you did `state = newState`, which in my case was the store didn't update.
3. A third thing I didn't get from the doc was if you could make the mutate vs not mutate choice on a per reducer basis rather than on some larger slice or project level. Making point #1 clearer would solve this.

**Comment by markerikson** [comment]
Yeah, please feel free to submit PRs to improve any docs phrasing or descriptions you feel aren't clear enough.

**Comment by markerikson** [comment]
Covered by the new "Writing Reducers with Immer" page: https://redux-toolkit.js.org/usage/immer-reducers
