### ISSUE TITLE
Attempted import error: 'nanoid' is not exported from '@reduxjs/toolkit'?

### ISSUE THREAD

**Issue by cuongdevjs** [reduxjs/redux-toolkit#726]
Throw error when import nanoid from toolkit?

**Comment by phryneas** [comment]
Works perfectly fine in this CodeSandbox with the current version:

https://codesandbox.io/s/rtk-nanoid-mqf8r

**Comment by markerikson** [comment]
We know it's exported correctly, because we've used it :) 

If you can show a project that reproduces the issue we might be able to take a look, but I'm going to close this.

**Comment by cuongdevjs** [comment]
thanks for your help :) I using the old version and updated, it work be fine. :)
