### ISSUE TITLE
createAsyncThunk never rejected

### ISSUE THREAD

**Issue by atinyakov** [reduxjs/redux-toolkit#728]
I got an error from API( `fetchRoot `returns 500), but despite that `createAsyncThunk `marked as **fullfiled** and never as **rejected** . I also have another snippet, which uses _builder API_ but it has same issue. 

![issue](https://user-images.githubusercontent.com/33699664/93108512-8b9f1f80-f6bb-11ea-8e69-f7b1474b0a7f.jpg)

Expected behavior:
`createAsyncThunk  `is rejected as stated [here](https://redux-toolkit.js.org/api/createAsyncThunk#handling-thunk-errors)

**Comment by markerikson** [comment]
The `fetch` API only returns a rejected promise if there was an actual network failure.  It does _not_ reject the promise if there is a 4xx or 5xx HTTP response.

You'll need to check the response type yourself, preferably by [using a `fetch` wrapper function that does that for you and rejects the promise if it's a failure error code](https://kentcdodds.com/blog/replace-axios-with-a-simple-custom-fetch-wrapper/), or an existing library like https://github.com/developit/redaxios .
