### ISSUE TITLE
let end users to decide if es5 support should be enabled?

### ISSUE THREAD

**Issue by shadeofgod** [reduxjs/redux-toolkit#731]
Hey I wrote electron apps with RTK, it can be certain that code always runs in a stable chromium environment, so I think it might be better to let the end user (which means us the end product developpers) to decide when to turns that on?

It can be done by simply re-export that API from immer.

much appreciate 🙇

**Comment by markerikson** [comment]
Per https://github.com/reduxjs/redux-toolkit/releases/tag/v1.3.0 :

> Redux Toolkit force-enables ES5 support. This is because we expect RTK to be used in multiple environments that do not support Proxies, such as Internet Explorer and React Native. It's also how Immer previously behaved, so we want to keep that behavior consistent and not break code given that this is a minor release of RTK. (In a hypothetical future major release, we may stop force-enabling the ES5 plugin and ask you to do it if necessary.)

So, possibly in the future, but not now.

**Comment by phryneas** [comment]
This might be something to consider as opt-in with a 2.0 release, but having it in a minor release would be too much of a breaking change. We'll see when that happens :)
