### ISSUE TITLE
createAsyncThunk does not wait for " fulfilled " to be called before getting called again

### ISSUE THREAD

**Issue by kanand7** [reduxjs/redux-toolkit#733]
I have facing a weird issue while working with the redux toolkit. While using for some time now, I realized that actions are being called without waiting for the previous one to complete. ( at least what I was expecting here ) 

**Example:** 
First `addSurvey/fetchSurveys/pending` action corresponds to the last `addSurvey/fetchSurveys/fulfilled `. So ultimately I lose the changes I was expecting. This goes to race condition and causing all uncertainty. 
![image](https://user-images.githubusercontent.com/7007918/93329148-0a5f9e00-f81d-11ea-8b7d-255afd1b729e.png)

My code: 
```
export const fetchSurveys = createAsyncThunk('addSurvey/fetchSurveys', async ({...args}) => {
  return await getSurveys(args);
});
```

Am I doing something wrong or is it the way it works?

**Comment by phryneas** [comment]
Your `fetchSurveys` will start whenever you dispatch it - that's what dispatching means. 

There is no "waiting" for anything, and I believe that is stated nowhere in the docs - if you find a statement in the docs that could be interpreted as such, please report it.

**Comment by markerikson** [comment]
And really, this is the entire point of all the `meta` values that `createAsyncThunk` adds to the actions it dispatches, including a unique request ID, the payload args, etc, as well as the `condition` option.  If you want your app to only allow a single request in flight at a time, or only handle the response for the latest outgoing request, it's up to you to write the logic to do so using those values.
