### ISSUE TITLE
Cleaning up an effect in useEffect

### ISSUE THREAD

**Issue by Ruslan-I7** [reduxjs/redux-toolkit#737]
Hello, I would like to specify what to do when try to effect of clean?

For example I have code like this:
```
  useEffect(() => {
    if (objAudiosState.loading.endsWith(rejected)) {
      message.error(objAudiosState.msgFetchState);
    }
    return () => {
      objAudiosState.loading = ''; // clean up
    }
  }, [objAudiosState.loading, objAudiosState.msgFetchState]);
```

As I understood I can't change value cuz of immer

**Part of code which pass state**
```
    builder.addCase(myAudiosAction.rejected, (state: Draft<any>, action: PayloadAction<any>) => {
      state.loading = action.type;
      state.msgFetchState = action.payload;
    });
```

**Comment by markerikson** [comment]
You're never supposed to do _any_ changes to the Redux state outside of a reducer, so that `objAudiosState.loading =` is definitely wrong.  You'd need to dispatch an action instead.
