### ISSUE TITLE
dispatch().then with Typescript

### ISSUE THREAD

**Issue by Sun-2** [reduxjs/redux-toolkit#741]
Taken straight out of `createAsyncThunk` docs:
```
const onClick = () => {
  dispatch(fetchUserById(userId)).then(() => {
    // do additional work
  })
}
```

Typescript errors out with:
```
Property 'then' does not exist on type 'AsyncThunkAction<any, { account: string; password: string; }, {}>'.
```

This is just a TS error however, with `// @ts-ignore`  it works fine.

**Comment by phryneas** [comment]
Your `dispatch` is typed wrong.

https://redux-toolkit.js.org/usage/usage-with-typescript#getting-the-dispatch-type

**Comment by Sun-2** [comment]
Damn, I feel ashamed for missing this.

Thank you very much.
