### ISSUE TITLE
Dispatching action from custom store enhancer doesn't hit middleware(s)

### ISSUE THREAD

**Issue by hannojg** [reduxjs/redux-toolkit#742]
Hey, 
I ran into an issue where dispatching from custom store enhancers wouldn't hit the middleware(s). I created a simple reproduction:
https://codesandbox.io/s/reduxjs-enhancer-middleware-gnxoo?file=/src/index.js

Perhaps I am just hitting my knowledge edge about redux and missing something crucial.
I think the store in the enhancer isn't enhanced with the middlewares (wrong order or something?).

Thank you so much in advance for your time looking into this.

**Comment by hannojg** [comment]
Just found this recipe: https://redux.js.org/recipes/configuring-your-store#extending-redux-functionality
When dispatching actions from the `monitorReducerEnhancer` it's the very same: it doesn't go through the middleware. So I guess this must be something redux specific?

**Comment by markerikson** [comment]
Correct.  Ordering of enhancers matters.

In this case, there's two things happening:

- `applyMiddleware` and `customEnhancer` are both enhancers, and just like middleware, enhancers effectively form a pipeline `a -> b -> c`, etc.  So, actions dispatched directly from `b` to `c` will never get seen by `a`.
- The line `store.dispatch(fruitSlice.actions.set("Peach"));` is referring to the non-middleware-decorated version of the store, without `applyMiddleware`.  

Change the line to `reduxStore.dispatch(fruitSlice.actions.set("Peach"));` and this should work as expected.
