### ISSUE TITLE
Inconsistency in clearing state.error in the Advanced Tutorial

### ISSUE THREAD

**Issue by dwiyatci** [reduxjs/redux-toolkit#744]
Hi again! :)) I noticed that in the Advanced Tutorial, the `state.error` for `issues` slice and `comments` slice are being cleared inconsistently.

- In the `issues` slice, the `state.error` is cleared in "fulfilled" reducers:
https://codesandbox.io/s/rtk-github-issues-example-03-final-ihttc?from-embed=&file=/src/features/issuesList/issuesSlice.ts:1106-1131

- In the `comments` slice, the `state.error` is cleared in "pending" and "fulfilled" reducers:
https://codesandbox.io/s/rtk-github-issues-example-03-final-ihttc?from-embed=&file=/src/features/issueDetails/commentsSlice.ts:535-846

What would be the best place to clear the error state in order to make it consistent when dealing with async requests? Would it be enough to clear it in the "pending" reducers only? 🤔

**Comment by akursat** [comment]
The "pending" state is about loading not about error.
**_success:_**
state.loading = false
state.error = null
**_failure:_**
   state.loading = false
   state.error = payload
**_pending:_**
   state.loading = true

**Comment by dwiyatci** [comment]
@akursat Hm yeah, I guess that's one way to look at it. 🙂 But imagine `state.error` is used to render an error message. Then you would want to clear it as soon as you make a request to the network (as it enters the `pending` reducer), otherwise the error message will still be shown along with the loading spinner until the network comes back to you with a result (either `fulfilled` or `rejected`).

So this formulation may well also be desirable:
```javascript
pending: (state) => {
  state.loading = true;
  state.error = null;
},
fulfilled: (state) => {
  state.loading = false;
},
rejected: (state, action) => {
  state.loading = false;
  state.error = action.payload;
}
```

**Comment by markerikson** [comment]
Obsolete due to #905 .
