### ISSUE TITLE
Advices on using without react

### ISSUE THREAD

**Issue by ZYinMD** [reduxjs/redux-toolkit#748]
I'm tempted to use redux in my node server code: I have a NoSQL database where each doc is a nested json-like object. The daily operations of the DB are mostly mutating different slices of a doc in response to different events. As the logic of these events are growing more complicated, I'm thinking redux may help me.

I imagine I'll do it in this fasion:
```js
const oldDoc = await db.retrieve(id);
const newDoc = rootReducer(oldDoc, action);
await db.set(id, newDoc);
```
This will reset the whole doc, but there won't be any measurable performance difference compared to only patching the changed slices.

I imagine I'll simply use `createSlice` and `combineReducers` from redux-toolkit, and won't use `store` / `getState` / `dispatch` etc. The benefits I expect to get is less cognitive overhead and more testable logic (I'll put all logic into reducers).

This may be an uncommon use of redux, so before doing it I hope to hear some comments from people: is it over kill? Am I using the wrong tool? Is there better tools or patterns that already solve my problem? Any caveats? etc, etc.

Thanks so much!

**Comment by markerikson** [comment]
That seems perfectly fine to me.  

A reducer is _just_ a function.  Pure functions are the most straightforward to use, since they're just "call function with inputs, get new result as output".  

If you find it helpful to format your logic as a reducer, then yes, Redux Toolkit is the best way to write a reducer.

**Comment by ZYinMD** [comment]
Hi thanks Mark! I think mutating a doc in a NoSQL database is one of the most common tasks done by programmers. Have you heard about people using reducers and combineReducers? I can't imagine why it's not a hot trend, it seems so good.

**Comment by phryneas** [comment]
Since there's no real discussion going on any more, I'm gonna close this one :)
