### ISSUE TITLE
Strange behviour of state in slice (revoked proxy)

### ISSUE THREAD

**Issue by suyashdeshpande** [reduxjs/redux-toolkit#753]
Sandbox: https://codesandbox.io/s/ucjrx?file=/src/features/todos/todosSlice.js

In todoSlice.js, at line 14, when I try to do console.log, it is printed as a revoked proxy (browser console). But when I put a breakpoint in chrome dev tools and go through that line step by step, it is not a revoked proxy.
Why is this happening?

**Comment by phryneas** [comment]
That's a problem with the devtools - see this code:
```js
let x = {};
console.log(x);
x.y = "foo";
```
now you see an empty object in the console, but once you click on it, you will see a `y` property in there.

The console does not freeze an object in time. And on top of that, the browser console sucks at logging proxy objects.

If you want to log your draft state, see [this section in the docs](https://redux-toolkit.js.org/api/createReducer#logging-draft-state-values)

**Comment by suyashdeshpande** [comment]
@phryneas Thanks for the help
