### ISSUE TITLE
Is it possible to use createAsyncThunk with useReducer?

### ISSUE THREAD

**Issue by jordyvandomselaar** [reduxjs/redux-toolkit#754]
I have a Thunk like so:

```javascript
const storeEmployee = createAsyncThunk("employee/store", async (foo, thunkAPI) => {
  debugger;
  console.log("YOOOO", thunkAPI);

  return true;
});
```

I dispatch it like so:

```javascript
useEffect(() => {
    dispatch(storeEmployee());
  }, []);
```

Unfortunately, nothing is being logged. Is there a way to use createAsyncThunk like this?

My Slice:

```javascript
const employeeSlice = createSlice({
  name: "employee",
  initialState: initialEmployeeState,
  reducers: {
    updateValue(state, action) {
      const { field, value } = action.payload;

      state.employee[field] = value;

      if (value === undefined) {
        delete state[field];
      }
    }
  }
});
```

And how I use it:

```javascript
const [state, dispatch] = useReducer(employeeSlice.reducer, initialEmployeeState);
```

**Comment by phryneas** [comment]
No, react's `useReducer` does not support middlewares and it does not have support for thunks. It only supports plain `dispatch`, I'm sorry.

**Comment by jordyvandomselaar** [comment]
Alright =), thanks for the clear explanation!

**Comment by jotatoledo** [comment]
Sorry for pinging, any hints in how to create a custom `useThunkReducer `hook that supports AsyncThunkCreators?
I hacked something together just for the purpose of fast delivery to a client, but it feels so flaky.

**Comment by phryneas** [comment]
> Sorry for pinging, any hints in how to create a custom `useThunkReducer `hook that supports AsyncThunkCreators? I hacked something together just for the purpose of fast delivery to a client, but it feels so flaky.

That will always be a hack. React's `useReducer` works in a way that is just not 1:1 mappable on Redux middleware.

**Comment by jotatoledo** [comment]
I mean, the following works, but I had to give up on strong typing:

```
import {
	Action,
	AnyAction,
	getDefaultMiddleware,
	isPlainObject,
	Reducer,
} from "@reduxjs/toolkit";
import { useMemo, useRef, useState } from "react";
import {
	Middleware,
	Dispatch,
	MiddlewareAPI,
	ReducersMapObject,
	combineReducers,
} from "redux";

export function useAsyncThunkReducer<
	S extends {},
	A extends Action = AnyAction,
	AppDispatch extends Dispatch<A> = Dispatch<any>
>(
	reducer: Reducer<S, A> | ReducersMapObject<S, A>,
	initState: S
): [S, AppDispatch] {
	const [state, setState] = useState(initState);
	const stateRef = useRef(state); // stores most recent state
	const rootReducer: Reducer<S, A> = useMemo(() => {
		if (typeof reducer === "function") {
			return reducer;
		} else if (isPlainObject(reducer)) {
			return combineReducers(reducer);
		} else {
			throw new Error(
				'"reducer" is a required argument, and must be a function or an object of functions that can be passed to combineReducers'
			);
		}
	}, [reducer]);

	const middlewares = useMemo(() => getDefaultMiddleware<S>(), []);
	const dispatch = useMemo(
		() =>
			enhanceDispatch({
				getState: () => stateRef.current, // access most recent state
				dispatch: (action) => {
					// TODO: remove any
					stateRef.current = rootReducer(stateRef.current, action as any); // makes getState() possible
					setState(stateRef.current); // trigger re-render
					return action;
				},
			})(...middlewares),
		[middlewares, rootReducer]
	);

	return [state, dispatch as AppDispatch];
}

function enhanceDispatch<S = any, D extends Dispatch = Dispatch<AnyAction>>({
	getState,
	dispatch,
}: MiddlewareAPI<D, S>) {
	return (...middlewares: Middleware<{}, S, D>[]): D => {
		let finalDispatch: D;
		const middlewareAPI: MiddlewareAPI<Dispatch, S> = {
			getState,
			dispatch: (action) => finalDispatch(action),
		};
		// TODO: remove any
		finalDispatch = middlewares
			.map((m) => m(middlewareAPI as any))
			.reduceRight((next, mw: any) => mw(next), dispatch) as D;
		return finalDispatch;
	};
}
```

Maybe it can be useful for others :)

**Comment by phryneas** [comment]
It does something similar, but not the same thing.

It will either not match Redux middleware behaviour or not match `useReducer` behaviour.

In `useReducer`, the next state will be calculated *during render* (as the reducer can just reference the most up-to-date variables from the scope of the next render) and only be definitely finalized *after commit*, so when a `useEffect` would take place. At the same time, you want to trigger thunks directly after `dispatch` - but due to the logic above `getState` will not return the new state yet and might not do so for quite some time.

So yes, this does something similar - but it does not integrate exact middleware behaviour with `useReducer`, since that is just impossible.
