### ISSUE TITLE
meta and error on rejectWithValue

### ISSUE THREAD

**Issue by Fakkio** [reduxjs/redux-toolkit#755]
Hi!

There's a way to customize `error` and `meta` object, when thunks return a `rejectWithValue`? I use a generalized reducer for displayng errors messages of rejected thunks, and when i use `rejectWithValue` it will display "Rejected" message.

**Comment by markerikson** [comment]
Not at the moment, no, but we're having a discussion about a possible API for customizing `meta` over in #750 .

**Comment by markerikson** [comment]
Resolved in #1083 .
