### ISSUE TITLE
reduxjs/toolkit fails in uglify in webpack

### ISSUE THREAD

**Issue by steinarb** [reduxjs/redux-toolkit#758]
Starting with reduxjs/toolkit version 1.3.0 my webpack build fails with:
```
ERROR in bundle.js from UglifyJs
Unexpected token: keyword «const» [./node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js:1141,0][bundle.js:164749,0]
```

I'm using uglifyjs-webpack-plugin version 2.2.0 which is the currently newest.

Downgrading reduxjs/toolkit to 1.2.5 makes webpack build again

**Comment by steinarb** [comment]
I found this issue on uglifyjs-webpack-plugin, with a rather confusing response in the comments https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/362

**Comment by phryneas** [comment]
Your bundler is using the ESM build, which is made for a modern target. Uglify cannot interpret modern JS. You'll either have to switch uglify for something that actually supports ES6 or tell your bundler to use one of our other entry points.

**Comment by markerikson** [comment]
@steinarb yep.  You should specifically switch to Terser, which is a maintained fork of Uglify with support for modern syntax.
