### ISSUE TITLE
Is there a way to tell createAsyncThunk the type of the value returned from thunkAPI rejectWithValue?

### ISSUE THREAD

**Issue by Kleinhummel** [reduxjs/redux-toolkit#762]
I am using createAsyncThunk and builder.addCase(thunkCreator.rejected) in my slice in the extraReducers. I am using typescript. But the type of action.payload is `unknown` in the rejected case. Is there a way to tell the createAsyncThunk function the type of the rejected value?

**Comment by msutkowski** [comment]
You'd want to use `rejectWithValue` and specify it's generic. There is documentation and a handful of examples here: https://redux-toolkit.js.org/usage/usage-with-typescript#createasyncthunk
