### ISSUE TITLE
Bind multiple actions to same extra reducer

### ISSUE THREAD

**Issue by Djazz1995** [reduxjs/redux-toolkit#764]
Hi,

I couldn't find this in the documentation. 

Is it possible to bind multiple actions to the same extraReducer? See below:

```
extraReducers: {
    [(action1.rejected.type,
    action2.rejected.type)]: (state, action) => {
      // Do same error handling for the rejections of action1 and action2
    }
}
```

Kind regards,

Djazz

**Comment by phryneas** [comment]
Yes, [using a matcher](https://redux-toolkit.js.org/api/createReducer#builderaddmatcher)
