### ISSUE TITLE
Redux saga take every doesn't run with redux tool kit

### ISSUE THREAD

**Issue by Millroy094** [reduxjs/redux-toolkit#772]
Hi,

I been trying to introduce redux sagas and redux tool kit to my project. The problem I am having at the moment is that the watcher saga is not catching on the dispatched action in the takeEvery effect and running the handler. I can't see anything wrong with the code. Can anyone Help!!!

**Comment by phryneas** [comment]
This is an issue tracker, not a help forum. Please ask questions like this either on StackOverflow or in the #redux channel on the [Reactiflux Discord](https://www.reactiflux.com/).

Also, when asking there: please provide some context. Nobody will be able to help you without seeing your code.
