### ISSUE TITLE
[WebStorm] CaseReducer<AuthState, PayloadAction<>> in createSlice leads to ActionCreatorWithNonInferrablePayload<>

### ISSUE THREAD

**Issue by gygabyte017** [reduxjs/redux-toolkit#774]
Assume this simple code:

```
type MyState = {
  n: number
};

const initialState: MyState = {
  n: 0
}

const myAction: CaseReducer<MyState, PayloadAction<number>> = (state, action) => ({
  ...state,
  n: action.payload
});

const mySlice = createSlice({
  name: "my",
  initialState,
  reducers: {
    myAction
  },
});
```

If I now check the myAction `mySlice.actions.myAction` it has type  `ActionCreatorWithNonInferrablePayload<string>`, so it allows something like `mySlice.actions.myAction("this is not a number")` which is wrong.

So why the payload of the action seems not inferrable as the name suggests even tough I created it as a `PayloadAction<number>`? What am I doing wrong?

**Comment by phryneas** [comment]
Try `initialState as MyState `.

Am 24. Oktober 2020 15:23:15 MESZ schrieb gygabyte017 <notifications@github.com>:
>Assume this simple code:
>
>```
>type MyState = {
>  n: number
>};
>
>const initialState = {
>  n: 0
>}
>
>const myAction: CaseReducer<MyState, PayloadAction<number>> = (state,
>action) => ({
>  ...state,
>  n: action.payload
>});
>
>const mySlice = createSlice({
>  name: "my",
>  initialState,
>  reducers: {
>    myAction
>  },
>});
>```
>
>If I now check the myAction `mySlice.actions.myAction` it has type 
>`ActionCreatorWithNonInferrablePayload<string>`, so it allows something
>like `mySlice.actions.myAction("this is not a number")` which is wrong.
>
>So why the payload of the action seems not inferrable as the name
>suggests even tough I created it as a `PayloadAction<number>`? What and
>I doing wrong?

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by gygabyte017** [comment]
> 
> Try `initialState as MyState `. Am 24. Oktober 2020 15:23:15 MESZ schrieb gygabyte017 <notifications@github.com>:
> […](#)
> Assume this simple code: ``` type MyState = { n: number }; const initialState = { n: 0 } const myAction: CaseReducer<MyState, PayloadAction<number>> = (state, action) => ({ ...state, n: action.payload }); const mySlice = createSlice({ name: "my", initialState, reducers: { myAction }, }); ``` If I now check the myAction `mySlice.actions.myAction` it has type `ActionCreatorWithNonInferrablePayload<string>`, so it allows something like `mySlice.actions.myAction("this is not a number")` which is wrong. So why the payload of the action seems not inferrable as the name suggests even tough I created it as a `PayloadAction<number>`? What and I doing wrong?
> -- Sent from my Android phone with K-9 Mail. Please excuse my brevity.

Yes sorry I forgot to type the initialState (edited), however the behaviour remains the same.

**Comment by phryneas** [comment]
Not as a type definition, but as a deliberate assertion with `as`. Ts does too much flow analysis for it's own good sometimed. I'm on mobile right now, but pretty sure that your problem is that the slice is working on a subtype of MyState, which means your case reducer accepts too wide arguments for the types to infer from it.

Am 24. Oktober 2020 15:54:48 MESZ schrieb gygabyte017 <notifications@github.com>:
>> >
>> Try `initialState as MyState `. Am 24. Oktober 2020 15:23:15 MESZ
>schrieb gygabyte017 <notifications@github.com>:>
>> […](#)>
>> Assume this simple code: ``` type MyState = { n: number }; const
>initialState = { n: 0 } const myAction: CaseReducer<MyState,
>PayloadAction<number>> = (state, action) => ({ ...state, n:
>action.payload }); const mySlice = createSlice({ name: "my",
>initialState, reducers: { myAction }, }); ``` If I now check the
>myAction `mySlice.actions.myAction` it has type
>`ActionCreatorWithNonInferrablePayload<string>`, so it allows something
>like `mySlice.actions.myAction("this is not a number")` which is wrong.
>So why the payload of the action seems not inferrable as the name
>suggests even tough I created it as a `PayloadAction<number>`? What and
>I doing wrong?>
>> -- Sent from my Android phone with K-9 Mail. Please excuse my
>brevity.>
>>
>Yes sorry I forgot to type the initialState (edited), however the
>behaviour remains the same.>
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/reduxjs/redux-toolkit/issues/774#issuecomment-715918609

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by phryneas** [comment]
I just put your example [into the TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMIEMDOBTAShgJgVwGMMoAaOABRQE8AbCFXAQUJmAgDtzCoMUYMAZVrBiAXzgAzKBBBwA5AAFeBAB4ArNAHoYECLQDWwGPIBQpmNTAY4AWWqCY-GwF5EpuHA4AuL-hAARiSmYgDc5oScaPDAHMbAKLSOzr72yQJwbggeXr4ADCERUfAg1CxsnL6omDgExFAAPGlOAuRUdAzMrOwcDRz+QVAAfEOZcAAU0c7kKN2cAJSZo+PZngB0G1OtOT5wsxUca2A09Iwh8+GmkRzRcKXCoq5wPHwCD8QrOyggGL4ARKU-qQcrF4ol0hhgZ4VEQSGhfKtPHcynMODkxMCxBdzPcRMQ1vsemg1qVyj0gA) and the type of myAction in that example is actually inferred as `ActionCreatorWithPayload<number, string>`.
Do you have any irregalularities in your TS setup? `strict: false` in your tsconfig.json?

**Comment by gygabyte017** [comment]
This is my tsconfig.json:

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "jsx": "react-native",
    "lib": [
      "dom",
      "esnext"
    ],
    "moduleResolution": "node",
    "noEmit": false,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "strict": true
  }
}
```

Actually I see a lot of difference between my file in WebStorm and the one in TS playground:

**mySlice**
```
const mySlice: Slice<MyState, {myAction: CaseReducer<MyState, {payload: number; type: string;}>;}, "my">

const mySlice: Slice<MyState, {myAction: (state: Draft<MyState>, action: PayloadAction<number>) => (void | MyState)}, "my">
```

**actions**
```
Slice<MyState, {myAction: CaseReducer<MyState, { payload: number; type: string; }>; }, "my">.actions: CaseReducerActions<{myAction: CaseReducer<MyState, {payload: number; type: string;}>;}>

Slice<MyState, {myAction: (state: Draft<MyState>, action: PayloadAction<number>) => (void | MyState)},"my">.actions: CaseReducerActions<{myAction: (state: Draft<MyState>, action: PayloadAction<number>) => (void | MyState)}>
```

**myAction**
```
myAction: ActionCreatorWithPayload<number, string>

myAction: ActionCreatorWithNonInferrablePayload<string>
```

I do wonder what is happening...

**Comment by phryneas** [comment]
Oh, these are not tsc errors, but WebStorm errors?
Webstorm tries to "guess" types to be faster than the typescript compile host and regularly gets it wrong. It's a pretty shitty IDE to develop TypeScript in unfortunately :(

See https://youtrack.jetbrains.com/issue/WEB-46527 and https://youtrack.jetbrains.com/issue/WEB-42559 for example.

**Comment by phryneas** [comment]
I guess I'll close this since there's nothing we can do about it unfortunately :(
