### ISSUE TITLE
Allow to unwrap async thunks automatically

### ISSUE THREAD

**Issue by bisubus** [reduxjs/redux-toolkit#775]
It makes sense that the result of async thunk is wrapped by default and points made in #618 are valid. However, users could be allowed to change this behaviour if they need to reduce verbosity:

```js
try {
  result = unwrapResult(await dispatch(asyncAction()));
  ...
```

The suggestion is to add an option that will apply `unwrapResult` automatically:
```js
let asyncAction = createAsyncThunk(
  'asyncAction',
  ...,
  { unwrap: true }
);
```

**Comment by msutkowski** [comment]
Hey there! Just chiming in, but you can do this really easily without library modifications if you want to. I'd think most folks would prefer this route as well as you can better handle errors and it's very transparent that this could potentially throw.

```js
// hooks.js
export const useUnwrapAsyncThunk = () => {
  const dispatch = useDispatch();
  return (asyncThunk) => {
    return dispatch(asyncThunk).then(unwrapResult);
  };
};

// component.js
const unwrap = useUnwrapAsyncThunk();

unwrap(yourAsyncThunk());
```

**Comment by msutkowski** [comment]
Following up with a TS version of this. Thanks to @phryneas for helping with this 🥇 

```ts
export const useUnwrapAsyncThunk = () => {
  const dispatch = useAppDispatch();
  return <R extends any>(
    asyncThunk: AsyncThunkAction<R, any, any>
  ): Promise<R> => dispatch(asyncThunk).then(unwrapResult);
};
```

**Comment by tomasbruckner** [comment]
@msutkowski  hi, is there simple solution when you are not using hooks?

Same goes for default serializeError function

**Comment by markerikson** [comment]
@tomasbruckner can you clarify what you're trying to do?

**Comment by tomasbruckner** [comment]
@markerikson there are 2 cases I would like to achieve.

1st is that I want to unwrap every createAsyncThunk (same as the original author).

But I am using connected components instead hooks.

So instead of 
```
await asyncAction().then(unwrapResult);
```

I would like to have
```
await asyncAction();
```

2nd requirement is that I want to access the original axios error if asyncAction throws and I don't want to define custom serializeError for each createAsyncThunk or rejectWithValue in each payloadCreator body.

I understand that I am not using Redux best practices, but we are migrating 100k lines of TS project from redux to redux toolkit and we are not able to rewrite the whole logic in each component.

**Comment by phryneas** [comment]
You can access the original error message by passing in a `serializeError` that just passes through the original value at thunk creation.

So you would define
```js
const myThunk = createAsyncThunk(
  "something", 
  () => { /*...*/ },
  { serializeError: x => x }
)
```

As for automatically unwrapping, you could just change
```js
const mapDispatchToProps = {
  foo: myThunk
}
``` 
to
```js
function unwrapped = thunk => (...args) => thunk(...args).then(unwrapResult);

const mapDispatchToProps = {
  foo: unwrapped(myThunk)
}
```

**Comment by flaviuse** [comment]
> Following up with a TS version of this. Thanks to @phryneas for helping with this 🥇
> 
> ```ts
> export const useUnwrapAsyncThunk = () => {
>   const dispatch = useAppDispatch();
>   return <R extends any>(
>     asyncThunk: AsyncThunkAction<R, any, any>
>   ): Promise<R> => dispatch(asyncThunk).then(unwrapResult);
> };
> ```

Hey fellow googlers, if like me you had problems of infinite loops when using that code with dependencies array don't forget to memoize the callback :
 ```ts
export const useThunkDispatch = () => {
  return useCallback(
    <R extends any>(asyncThunk: AsyncThunkAction<R, any, any>): Promise<R> =>
      store.dispatch(asyncThunk).then(unwrapResult),
    [],
  );
};
```
Note : I use directly store.dispatch instead of declaring a useAppDispatch() but you can add both if you don't want to unwrap everytime

**Comment by defint** [comment]
Is there any chance to do this feature with the ability to auto-unwrap action? We have a very ridiculous code with the custom wrapping of all places on the project.

**Comment by markerikson** [comment]
@defint please see the previous discussions: linked from https://github.com/reduxjs/redux-toolkit/issues/910#issuecomment-786129164 

I'm tentatively open to the idea, but it's not an immediate priority for us to work on atm.  If you or someone else would like to open a PR that makes the changes, we can look at that.

**Comment by phryneas** [comment]
@markerikson @defint generally though, this is a change that probably requires a lot of extra code and extra complexity for (seeing the many viable workaroungs in this topic alone) little gain.
The TypeScript types would almost duplicate.

Even implementing something like `await dispatch(async(3, { unwrap: true }))` has significant complexity overhead: https://github.com/reduxjs/redux-toolkit/commit/94c67a2d31258b3d490f784f7bf3cdfbc7acc5d7

What would be thinkable and what we are trying out in rtk-query at the moment would be the ability to
`await dispatch(async(3)).unwrap()`. That would actually be possible to implement with very little overhead.

**Comment by markerikson** [comment]
Ah, yes, I like that idea!
