### ISSUE TITLE
Pass parameters to the pending action of createAsyncThunk

### ISSUE THREAD

**Issue by benmeiri** [reduxjs/redux-toolkit#776]
I'm using createAsyncThunk to handle all my api resquests. I want to access the original input from the pending state to show a specific loading message. Something like:
```
export const getUser = createAsyncThunk('users/getUser', async (id) => {
  const { data } = await api.get(id);
  return data;
});

const contactsSlice = createSlice({
  name: 'users',
  initialState,
  reducers,
   extraReducers: {
    [reducers.pending]: (state, action) => {
      // this is the logic I would like to add
      state.users[action.payload.id].loading = true;
    },
    [addContact.fulfilled]: (state, action) => {
           // set user logic
    },
}

```
I really don't want to do if rom the Thunk function with dispatch, but to leverage the pending state.
Is there a way to pass parameters to the pending state?

Thanks in advance!

**Comment by markerikson** [comment]
Per the API reference docs at https://redux-toolkit.js.org/api/createAsyncThunk#payloadcreator , the `pending` action should have that ID value you passed in available as `action.meta.arg`.

**Comment by benmeiri** [comment]
Apparently, in the refactor from regular `dispatch` using the `react-thunk` to use the `createAsyncThunk` I forgot  to change the array to an object. Thanks.
