### ISSUE TITLE
Default Thunk middleware doesn't work with FAST_REFRESH CRA

### ISSUE THREAD

**Issue by denisrudov** [reduxjs/redux-toolkit#777]
if to use [...getDefaultMiddleware] found that default thunk middleware breaks FAST_REFRESH feature of CRA.
if to use latest redux-thunk separately - all is ok

**Comment by denisrudov** [comment]
if to use **[...getDefaultMiddleware]** found that default thunk middleware breaks FAST_REFRESH feature of CRA. 
if to use latest redux-thunk separately - all is ok

**Comment by phryneas** [comment]
How exactly does it break?

**Comment by markerikson** [comment]
Yeah, there's two problems with this:

- We need info on what specifically you're seeing break, how, and why.  (As always, a CodeSandbox or Github repo that reproduces the issue would be extremely helpful)
- Second, off the top of my head I don't see any way that Fast Refresh would have _any_ relation on how the Redux middleware get set up

**Comment by denisrudov** [comment]
@markerikson @phryneas sorry guys. looks like it is my mistake. I'll double check next time before creating an issue
