### ISSUE TITLE
Async Thunk actions are missing TS Type definition for abort method

### ISSUE THREAD

**Issue by DiogoDoreto** [reduxjs/redux-toolkit#778]
I'm getting the following error on my application when trying to call abort:

    Property 'abort' does not exist on type 'AsyncThunkAction<MyServiceResponse, void, {}>'.  TS2339

Minimal demo: https://codesandbox.io/s/rtk-missing-abort-type-k261g?file=/src/App.tsx

<img width="469" alt="image" src="https://user-images.githubusercontent.com/259302/97406924-39782d80-18fa-11eb-9690-1e2d16198679.png">

**Comment by phryneas** [comment]
`abort` is a property of the `Promise` returned by dispatching the action:

```ts
const store = configureStore({reducer(){return {}}});

const action = createAsyncThunk("test", async () => "foo");
store.dispatch(action()).abort();
```

**Comment by DiogoDoreto** [comment]
@phryneas I just created a minimal example to reproduce the issue. Dispatch does not magically add the abort method. 

Please try to run your code in a TypeScript project to confirm.

**Comment by phryneas** [comment]
I literally put that exact code into your codesandbox.

**Comment by DiogoDoreto** [comment]
> Also, yes it "does magically add the abort method". 

Thanks for your support. Since I'm using the regular `useDispatch` hook in my app, your types were not included in the returned value.

Leaving the link in the docs for future reference: https://redux-toolkit.js.org/usage/usage-with-typescript#using-the-extracted-dispatch-type-with-react-redux
