### ISSUE TITLE
Cannot use complex object as initial state for createslice

### ISSUE THREAD

**Issue by kylemiller3** [reduxjs/redux-toolkit#779]
I have 5 duplicate components and each needs to listen to their own actions dispatched and not the others. Here is my slice code:

```typescript
const initialState: SelectBarState = {
  handle: undefined,
  platformHandles: {
    twitter: [],
    reddit: [],
    alexa: [],
  },
  platform: PLATFORMS.twitter,
  color: COLORS[0],
  tickers: [],
};
const wrappedInitialState = {
  0: { ...initialState },
  1: { ...initialState },
  2: { ...initialState },
  3: { ...initialState },
  4: { ...initialState },
};

const selectBarSlice = createSlice({
  name: "select bar",
  wrappedInitialState,
  reducers: {
...
```
with this I get ``Argument of type '{ name: string; wrappedInitialState: { 0: { handle: string | undefined; platformHandles: { [key: string]: string[]; }; platform: Platform; color: string; tickers: Ticker[]; }; 1: { handle: string | undefined; platformHandles: { ...; }; platform: Platform; color: string; tickers: Ticker[]; }; 2: { ...; }; 3: { ...; }...' is not assignable to parameter of type 'CreateSliceOptions<unknown, SliceCaseReducers<unknown>, string>'.
  Object literal may only specify known properties, and 'wrappedInitialState' does not exist in type 'CreateSliceOptions<unknown, SliceCaseReducers<unknown>, string>'.`` However I can do 

```typescript
const selectBarSlice = createSlice({
  name: "select bar",
  initialState,
  reducers: {
... 
```
Just fine and I'm not sure why. I might be missing something obvious here. Also, is there a better way of solving this use-case? Any help is appreciated.

**Comment by phryneas** [comment]
RTK expects to get the initial state for the slice to be passed int as `initialState`. It doesn't know an option named `wrappedInitialState`.

```js
const selectBarSlice = createSlice({
  name: "select bar",
  initialState: wrappedInitialState,
  reducers: {
```

**Comment by kylemiller3** [comment]
Thank you not sure why that didn't occur to me :)
