### ISSUE TITLE
Advice on how to test actions / async actions

### ISSUE THREAD

**Issue by jamiehaywood** [reduxjs/redux-toolkit#787]
hello there,

I have this code, but I'm not entirely sure what I should be testing here. I've broken it down into a couple of possible areas, but I'm unsure on implementation, and  would really appreciate some guidance:
- HTTP request is made
- the `login()` thunk returns the correct value
- the error reject value is correctly returned

I was thinking of mocking a `200` and `403` response from axios and then asserting on the returned values, but I'm a bit stuck in this regard.

```
export const login = createAsyncThunk<
  LoginResponse,
  Credentials,
  { rejectValue: APIError }
>('login', async ({ email, password }, thunkAPI) => {
  try {
    const { data } = await axios.post(
      '/auth/login',
      {
        email,
        password,
      }
    );
    return data;
  } catch (e) {
    return thunkAPI.rejectWithValue(e.response.data);
  }
});
```

**Comment by markerikson** [comment]
There's nothing specific about testing RTK code - it's really about how you want to test Redux logic in general.  I'd suggest looking at the "Testing" page in the Redux core docs:

https://redux.js.org/recipes/writing-tests

That said, tbh I wouldn't find a test for this thunk all that useful.  98% of what's happening there is library code (either RTK or axios).  I don't feel that testing that provides me much confidence in terms of how my own code works or the rest of the app.
