### ISSUE TITLE
How to dispatch action from saga?

### ISSUE THREAD

**Issue by aqueiros** [reduxjs/redux-toolkit#789]

**Comment by phryneas** [comment]
Why are you asking this in redux-toolkit and not in redux-saga? There is nothing specific to RTK here.

Also, this is *not* a support forum, this is a bug tracker. We can't handle that here, the volume would be too high.
Please ask questions on stackoverflow or in the reactiflux discord chat channel.

**Comment by aqueiros** [comment]
I am very sorry. I did not meant to write the issue here. When I realised I was writing it in the wrong repo I cut my question to paste it in the redux-saga repo and then indadvertedly submitted the issue here without any text. 😓

**Comment by markerikson** [comment]
no worries, it happens :)
