### ISSUE TITLE
[Idea] Cached createAsyncThunks

### ISSUE THREAD

**Issue by yhnavein** [reduxjs/redux-toolkit#794]
Hi,

I was wondering about extending `createAsyncThunk` with a new option that will allow to cache thunks. I am already doing it manually like this:

```ts
export const loadCountriesList = createAsyncThunk(
  sliceName + '/loadCountries',
  async (thunkAPI) => {
    return ApiCache.getOrCreate(
      sliceName + '/loadCountries',
      async () => {
        const response = await clients.countryClient.getCountries();
        return response.data;
      }
    );
  }
);
```

I am using SessionStorage for cache. I am caching quite a few of the thunks and I was thinking about introducing the same functionality directly to `createAsyncThunk` so that it can look like this:

```ts
export const loadCountriesList = createAsyncThunk(
  sliceName + '/loadCountries',
  async (thunkAPI) => {
    const response = await clients.countryClient.getCountries();
    return response.data;
  }, 
  { cache: true }
);
```

I will be taking a look at the Redux Toolkit code to see how it can be implemented, but I wanted to see how you guys see that feature.

And yes, I know that browser's built in network cache can be used to achieve something similar on the Network level, BUT my company unfortunately uses retarded .NET APIs hosted by IIS ( 🤮 ) and this is simply not an option. I had to come up with something on the FrontEnd side.

What do you think about this? Discussion is really welcomed

**Comment by markerikson** [comment]
@phryneas is actually working on a prototype of a new data fetching abstraction for use with RTK that would involve caching.  I'd suggest taking a look at it:

https://github.com/rtk-incubator/simple-query

**Comment by phryneas** [comment]
I'm not seeing any merit in this to be honest. That kind of caching should either be done by the browser (which means: just set correct headers on your server) or in your fetching logic, but I wouldn't want to do that in `createAsyncThunk`.

**Comment by slim-hmidi** [comment]
@phryneas how does the new api will manage the cache data whenever the data will be updated in the server?
Does the user should force the api to refetch by setting a flag or how?

**Comment by phryneas** [comment]
Yes, rtk-query will have a refetch option.

**Comment by slim-hmidi** [comment]
under the hood the option should executed every amount of time?
e.g:
1-)first time you get the data then save them in the cache.
2-)second render the api retrieves the data from the cache.
3-)Meanwile new item was updated or added.
the cached data and new data are different now.
4-) the rtk-query should refetch after some period of time to update the
cache ?

**Comment by phryneas** [comment]
rtk-query allows for both polling for data and for automatic invalidation in case you call a mutation that would change something you are using somewhere else.

But really, that's very far from this initial discussion.
As for "extending `createAsyncThunk` with some kind of caching", I'm just going to say "no": `cAT` is not really the best place to implement that as a general rule, and this kind of caching behaviour is usually the browser's job (although you can take control over it, but even then it's not the job of `createAsyncThunk`, but the job of your api layer - as you are doing there.

So, for this topic, I'm going to close this. rtk-query will go into public alpha in the next few weeks and everything should then be discussed over there.
