### ISSUE TITLE
Type error on abort method

### ISSUE THREAD

**Issue by macabeus** [reduxjs/redux-toolkit#796]
The [doc](https://redux-toolkit.js.org/api/createAsyncThunk#canceling-while-running) says that `dispatch ` returns a `promise` and we could use `promise.abort()` to cancel a running thunk.

But I'm trying to do that, and I'm receiving an error type on TS:
![image](https://user-images.githubusercontent.com/9501115/98554541-bd39fe80-2298-11eb-9095-02d876529558.png)
My reducer type is `createAsyncThunk<void, void, ThunkApiConfig>`.

I could use `// @ts-expect-error` to ignore the error and everything works fine. I think that it's just an error on type definition on `redux-toolkit` itself.

**Comment by phryneas** [comment]
I assume this is the same as in https://github.com/reduxjs/redux-toolkit/issues/778 ?

**Comment by macabeus** [comment]
@phryneas Is almost the same case, but I'm using `useDispatch`, not `store.dispatch`

Minimal example:

```js
const dispatch = useDispatch()

const handleOnClick = () => {
  const promise = dispatch(startDispense())
  promise.abort()
}
```

I can do that, because the property `abort` is added on the `Promise` returned by `dispatch`, but it results on a type error.

**Comment by phryneas** [comment]
[See the docs](https://redux-toolkit.js.org/usage/usage-with-typescript#getting-the-dispatch-type) (as linked in that other thread)
