### ISSUE TITLE
TypeScript integration with Asynchronous thunks. Typings missing?

### ISSUE THREAD

**Issue by JoseFMP** [reduxjs/redux-toolkit#798]
If I create a thunk using `const myThunk = createAsyncThunk<{ isCool: boolean }, { isLate: boolean }>( ... )` wondering, is there any way I can get the typings for the fulfilled, pending and rejected actions?

i.e. I know I can access `mythunk.fulfilled` , `mythunk.pending` etc. but when using it, I do not have the typings of the action. I.e. I can define the typings of the data returned by the thunk, but I also need the arguments passed to the thunk that come embed in the `meta: { arg }` property.

All in all wondering why I cannot do `typeof mythunk.pending` and get the typing of
```
export interface PendingAction<ThunkArg> {
  type: string
  payload: undefined
  meta: {
    requestId: string
    arg: ThunkArg
  }
}
```

Am I missing something?

**Comment by markerikson** [comment]
`myThunk.fulfilled` is the action _creator_.  If you want the type of the _action object_, you'd need to do:

`type MyPendingAction = ReturnType<typeof myThunk.fulfilled>;`
