### ISSUE TITLE
In regards to the new requestId addition to the library and loading state for thunks.

### ISSUE THREAD

**Issue by mikeyhunt** [reduxjs/redux-toolkit#803]
## Foreword:

I understand this is better suited for a small utility on its own, but when I saw `requestId`, I thought it'd solve exactly my case, but it turns out it's more suited for tracking **all requests and differentiating between them.** This is for small component state. I'm not aware of how common the use-case of a centralized requests manager is for the sole purpose of displaying the loading state in regards to a component.

## The business goal:

I need to have a loading flag that I can keep track of while a thunk is doing its thing so I can display a spinner.

## The solution:

@phryneas suggested that, with the newer version, I can look at `requestId` in order to differentiate between requests. The problem was that there was no easy way to correlate a request being launched to a given component. `dispatch`, then look at `requestId`, store it, when the thunk is done, check if the `requestId` matches with that stored one?

Well, that could work, but it's ugly. Instead, I came up with a hook that I hope will serve inspiration for some upcoming utility in regards to this functionality:

```js
import React, { useState } from 'react';

import { useDispatch } from 'react-redux';

/**
 * Hook that tells us whether or not a request from within a thunk is still ongoing.
 *
 * @returns {array} Returns the loading state and the callback so that it can be triggered from anywhere within a component.
 */
export const useLoading = () => {
    const dispatch = useDispatch();
    const [loading, setLoading] = useState(false);

    /**
     * Dispatches with a thunk and sets the state.
     *
     * @param {RTK:AsyncThunk} thunk An async thunk.
     * @param {mixed} args Args to be passed to the thunk.
     */
    const dispatchWithLoading = (thunk, ...args) => {
        setLoading(true);
        const promise = dispatch(thunk(...args));

        promise
        .then(() => setLoading(false))
        .catch(() => setLoading(false));

        return promise;
    }

    return [loading, dispatchWithLoading];
}
```

Usage:

```js
const [loading, callThunk] = useLoading();
..
..
..
<div className={`container ${loading ? 'loading' : ''}`}>
    <div onClick={() => callThunk(theThunk, args)}>Click Me!</div>
</div>
```

## Considerations

1. The callback needs to be returned in the form of a promise so that people still have access to the original `dispatch` object. Simply `setLoading` doesn't cut it. This way, people can do something once the thunk's been resolved/rejected.

2. In regards to (1), is that actually going to happen? I haven't seen *any* code that's waiting for a `dispatch` inside a component, so, clearly, there's usually no need for `.then`, `.catch` in there. All error handling happens at the `createAsyncThunk` level. I guess someone could just put all that logic inside a local function within the component if they think they need some advanced logic.

**Comment by markerikson** [comment]
Afraid I'm not quite sure what you're asking for here.

FWIW, both the new Redux tutorials show examples of waiting on a promise from a thunk, inside of a component, specifically for the purposes of showing a loading spinner, using basically the `setState` approach you're showing there:

https://redux.js.org/tutorials/essentials/part-5-async-logic#checking-thunk-results-in-components

https://redux.js.org/tutorials/fundamentals/part-7-standard-patterns#thunks-and-promises

**Comment by msutkowski** [comment]
I have a couple of ideas for you. 

1. If you're going to use that code, just use `promise.finally()`
2. Regarding your comment about not seeing _any code_ that relies on the result of a thunk... look at the examples that use the resulting payload for form field-level validation. You _could_ put those errors in state and select them out, but it's much simpler to just use extracted payload from the thunk result. 
3. Depending on your actual usage, you might want to just consider having a button that handles loading like this for you. I personally do something very similar to your code, but just in a wrapped button component where I don't care about tracking the loading state across many components.
4. Outside of that, another useful pattern is just a general loading reducer, which would most likely be a better fit for what you're trying to achieve here. Your example limits where you can actually observe the loading state of a given action type if you really want.

In general, if you think about loading: A. application-level loading, B. slice loading, C. individual thunk/request loading, D. isolated component loading. Thinking about these possibilities make it really hard to have a general utility, as every application has totally different needs.

**Comment by phryneas** [comment]
I'm just doing a "cleaning sweep" through the open issues.
Since this is not really a feature suggestion/change request to RTK itself, but more of a "here's how I use this", I'll close this for now.
