### ISSUE TITLE
disable middlewares using config object

### ISSUE THREAD

**Issue by alzalabany** [reduxjs/redux-toolkit#805]
i always wondered why do we have redux-immutable-state-invariant and immer in same setup !

the whole point of immer is to detect mutation, so when basically would invariant be of any use ?

not sure, but anyhow it's giving me a lot of warnings `ImmutableStateInvariantMiddleware took 46ms, which is more than the warning threshold of 32ms.` in large apps, so i need an option to just disable certain middleware by its name in `configureStore` example :-
```js
const store = configureStore({
  reducer,
  middleware: getDefaultMiddleware({
    thunk: {
      extraArgument: { api },
    },
    serializableCheck: false,
  }, ['redux-immutable-state-invariant'] ), <--- 2nd arg list of middlewares to disable
  preloadedState: undefined,
  devTools: true,
});
```

**Comment by phryneas** [comment]
What you are looking for is `immutableCheck: false`, just like the `serializableCheck: false` to disable the `SerializableStateInvariantMiddleware` that you are already using one line above that.

**Comment by markerikson** [comment]
Immer's purpose is to allow simpler immutable update logic.  As a bonus, it also freezes state in development mode.  So, there's a bit of overlap with the immutable middleware, but the middleware also covers cases where you aren't using Immer, or end up mutating state outside of reducers.

**Comment by levywinnikes** [comment]
> Immer's purpose is to allow simpler immutable update logic. As a bonus, it also freezes state in development mode. So, there's a bit of overlap with the immutable middleware, but the middleware also covers cases where you aren't using Immer, or end up mutating state outside of reducers.


Thank you! This helped me a lot!

**Comment by DianaKoenraadt** [comment]
I applied `immutableCheck: false` but kept getting the warning `SerializableStateInvariantMiddleware took 70ms, which is more than the warning threshold of 32ms.`

Turns out that `immutableCheck: false` only works if you also set `serializableCheck: false`.
If instead you use `ignorePaths` and `ignoreActions`, then `immutableCheck: false` won't work

**Comment by phryneas** [comment]
@DianaKoenraadt the immutability middleware and the serializabilityMiddleware are two different middlewares that are disabled and/or configured using two different ways. You might need to disable none, one or both depending on your application and data.

Generally though, if the message says **Serializable**StateInvariantMiddleware, it's not the **`immutable`**`Check` option you are looking for.
