### ISSUE TITLE
Pass dispatch to createAsyncThunk condition function

### ISSUE THREAD

**Issue by ahmedosama74574** [reduxjs/redux-toolkit#810]
According to the [docs](https://redux-toolkit.js.org/api/createAsyncThunk#cancellation), the only arguments you get in `condition` are `getState` and `extra`. What about dispatch ? Do I have to manually import the store in order to use inside condition. I need to dispatch another action if this action is cancelled. even if I set `dispatchConditionRejection: true`. I can not dispatch an action from within a reducer.

**Comment by phryneas** [comment]
`dispatchConditionRejection: true` will just lead to the dispatch of a `rejected` action with `meta.condition: true`, so you can react to that.

But it sounds like you want to do more in that condition than checking a condition.
Maybe a condition is just not the right tool there? That we deliberately left out the ability to `dispatch` from there should be a good indicator for that ;)

You might consider wrapping your asyncThunk in a normal thunk and doing more stuff there before dispatching the asyncThunk from inside that.

**Comment by ahmedosama74574** [comment]
> dispatchConditionRejection: true will just lead to the dispatch of a rejected action with meta.condition: true, so you can react to that.

Still, reacting to the action will be inside a reducer. I can not dispatch an action there (especially that it has side effects)

> You might consider wrapping your asyncThunk in a normal thunk and doing more stuff there before dispatching the asyncThunk from inside that.

That's exactly what I thought about doing, but I was wondering It would be less code to write if I just have the `dispatch` function inside the condition.

> That we deliberately left out the ability to dispatch from there should be a good indicator for that ;)
Seems reasonable, but this could be a really good use case, If I am not gonna dispatch this action, I might want to dispatch another one.

The point of `redux-toolkit` is to help us write less code and at the same time not violate redux guidelines. As far as I know, This is not violating anything.

**Comment by phryneas** [comment]
To put it bluntly: You are planning to abuse a tool here.
The purpose of `condition` is to decide whether a thunk should start. Nothing more. Definitely not side effects.

> Still, reacting to the action will be inside a reducer. I can not dispatch an action there (especially that it has side effects)

An action has already been dispatched. You can react to that action in every reducer. If you want to have a different action (why?), you need a different approach.

> The point of redux-toolkit is to help us write less code and at the same time not violate redux guidelines. As far as I know, This is not violating anything.

The point of redux toolkit is to make the 80% case more easy - and more easily readable. Having a condition (look at the name!) with side effects has nothing to do with readability - it is unexpected. This is a code smell, even now before it has been written. 
I'm very much not in favor to add features that can **only** be used to write code that is unexpected to the reader.

**Comment by ahmedosama74574** [comment]
Ok. This debate is over whether we should allow dispatching actions inside condition or not. In your opinion, we shouldn't because that's not the purpose of condition.
Cool! What about adding another optional parameter `altActions`, that accepts an array of actions that get dispatched if `condition` returns `false`

**Comment by markerikson** [comment]
fwiw, at this point it sounds like your usage scenario is custom enough that it might just be better to write a thunk by hand, vs trying to make `createAsyncThunk` more flexible.

**Comment by msutkowski** [comment]
Agreed with @markerikson. The other option you can do immediately is:

```js
const result = dispatch(yourAsyncThunk());
if (yourAsyncThunk.rejected.match(result)) {
  // you could check and make sure it was rejected due to conditions as well if you wanted
  dispatch(otherThing())
  dispatch(someOtherThing())
}
```

This would literally be the same thing as RTK introducing an `onReject` callback or `altActions`

**Comment by phryneas** [comment]
> Ok. This debate is over whether we should allow dispatching actions inside condition or not. In your opinion, we shouldn't because that's not the purpose of condition.
> Cool! What about adding another optional parameter `altActions`, that accepts an array of actions that get dispatched if `condition` returns `false`

I already asked: why do you not use the action that *is* being dispatched?

**Comment by ahmedosama74574** [comment]
@phryneas The action that's dispatched by `createAsyncThunk` will, indeed, dispatch a `pending` and `fulfilled`/ `rejected`  actions. I don't want those to be called but dispatch a totally different action.

**Comment by ahmedosama74574** [comment]
@markerikson Imho, I think it's not really a custom scenario. This could be a really good use case, _If this action is cancelled, dispatch that other action_.
But, in the end, it's up to you if you think it's needed or not.

**Comment by phryneas** [comment]
@ahmedosama74574 For now, you have only demanded changes and not given a single reason.

I ask for a third time: why?

Do you not like the action? Do you want additional information there? Do you want less information there? Do you have a middleware that only triggers if five different actions in exactly the same order appear?

Why?

**Comment by ahmedosama74574** [comment]
@phryneas Say you have an action that does some async stuff, then you will need to dispatch `pending` and `fulfilled`/` rejected` when it's finished to render appropriate UI. Maybe in condition, you want to check if this action is already fulfilled and in that case, you want to do some synchronous stuff, instead. `pending` and `fulfilled`/`rejected` not needed in that case.

**Comment by phryneas** [comment]
But you can still just check for "`rejected` with `meta.condition: true`" and "`rejected` with `meta.condition: false`". 
You do have that information in the action that is being dispatched, you do not need another action for that. And there will also not be a `pending` action in the `rejected` "with condition" case.

**Comment by ahmedosama74574** [comment]
IMO, Writing a custom thunk would be better because this way, I don't have to manually check action rejection everytime I dispatch the action. I just want to call `dispatch` and let it make its own decisions.
Anyway, Thanks for the beautiful discussion
