### ISSUE TITLE
How can I make that typescript understand thunk dispatch return type 

### ISSUE THREAD

**Issue by vikei** [reduxjs/redux-toolkit#818]
As I understood I need somehow add thunks function to store type, so dispatch will understand return type, but where I can add this typing?

<img width="1027" alt="Screenshot 2020-11-24 at 17 47 11" src="https://user-images.githubusercontent.com/55663427/100117065-1bf89e00-2e7d-11eb-9281-37edb9d2ba7e.png">
<img width="831" alt="Screenshot 2020-11-24 at 17 47 47" src="https://user-images.githubusercontent.com/55663427/100117174-3468b880-2e7d-11eb-834f-270c5692c05e.png">
<img width="408" alt="Screenshot 2020-11-24 at 17 48 39" src="https://user-images.githubusercontent.com/55663427/100117279-4e0a0000-2e7d-11eb-8270-0d046f0d4006.png">
<img width="635" alt="Screenshot 2020-11-24 at 17 49 06" src="https://user-images.githubusercontent.com/55663427/100117344-5f530c80-2e7d-11eb-94bd-3d2308136a6b.png">
<img width="364" alt="Screenshot 2020-11-24 at 17 49 24" src="https://user-images.githubusercontent.com/55663427/100117385-69750b00-2e7d-11eb-821d-99643836450c.png">

I need somewhere pass thunk type to dispatch can see it, but where?
<img width="322" alt="Screenshot 2020-11-24 at 17 52 52" src="https://user-images.githubusercontent.com/55663427/100117875-f1f3ab80-2e7d-11eb-9642-e85c7e69e4ff.png">

**Comment by phryneas** [comment]
That looks a lot like webstorm. And like your code is correct.
Unfortunately, WebStorm does not actually evaluate types. It tries to guess, takes shortcuts and fails miserably. Does the same code in vscode (or just running `tsc` on the command line) work without errror?

See for reference: https://youtrack.jetbrains.com/issue/WEB-46527 and https://youtrack.jetbrains.com/issue/WEB-42559 for example.

**Comment by vikei** [comment]
@phryneas 

TypeScript also don't understand)

<img width="821" alt="Screenshot 2020-11-24 at 18 11 07" src="https://user-images.githubusercontent.com/55663427/100120328-8232f000-2e80-11eb-91b3-0de937cf8311.png">

**Comment by phryneas** [comment]
If you just do `const returned = await dispatch(createCategoryThunk(values))` and hover over `returned` what type is that?

**Comment by phryneas** [comment]
(Same question for `createCategoryThunk` itself.)

**Comment by vikei** [comment]
```ts
const result: PayloadAction<CategoryEntity, string, {arg: CategoryDto, requestId: string}, never> | PayloadAction<unknown, string, {arg: CategoryDto, requestId: string, aborted: boolean, condition: boolean}, SerializedError>
```

```ts
createCategoryThunk(
    arg: CategoryDto): AsyncThunkAction<CategoryEntity, CategoryDto, ThunkApiConfig>
```

**Comment by phryneas** [comment]
Ahhhh. Completely different error.
You never check if the returned action is a `fulfilled` action. At that point it could also be a `rejected` action with an unknown payload.

So either wrap a `if (createCategoryThunk.fulfilled.match(action))` around it, or [unwrap the result](https://redux-toolkit.js.org/api/createAsyncThunk#handling-thunk-results)

**Comment by vikei** [comment]
Thanks man! You best!

**Comment by phryneas** [comment]
You're welcome. Just for the future: come visit us in #redux on the Reactiflux Discord - this issue tracker is not really the place for things like this ;)
