### ISSUE TITLE
How to connect to redux devtools?

### ISSUE THREAD

**Issue by RichMatthews** [reduxjs/redux-toolkit#820]
I'm seeing a fair bit of conflicting info of how to set it up. I'm working with react native

I've gone with this:

```
import { configureStore } from '@reduxjs/toolkit'
import devToolsEnhancer from 'remote-redux-devtools'
import leaguesReducer from '../reducer'

const store = configureStore({
    reducer: {
        leagues: leaguesReducer,
    },
    devTools: false,
    enhancers: [devToolsEnhancer({ realtime: true })],
})

export default store
```

passing my store into provider. if I log `store.getState()` it works in the console. I cant connect to devtools, what do I need to do?

**Comment by phryneas** [comment]
You are doing the right thing.

Unfortunately though, the https certificate of https://remotedev.io has expired last year. And the remote devtools try to connect over https by default (which is a good thing). So you have to either use a local server, or disable encryption by setting the `secure` option to `false`, sending all your store contents unencrypted over the internet.

Unfortunately, both are not very nice options.

@markerikson  there is an issue over at https://github.com/zalmoxisus/remote-redux-devtools/issues/139, but @zalmoxisus is not answering. Do you have other ways of contacting them? If it's just the certificate, the we can surely help with that (setting up LetsEncrypt is usually a breeze).

**Comment by markerikson** [comment]
Not really, no.  They were already mostly inactive the last couple years.  

The main Redux DevTools repo did get transferred to the `reduxjs` Github org a few months ago, I think, and @timdorr now has publish rights for the browser extensions.

Don't know if anything was done about this tool, though.

**Comment by phryneas** [comment]
So the only thing we could really do would be to fork `remote-redux-devtools` and set up our own domain :/

The hosting is something I could probably do on my infrastructure, but right now I have other things on my mind than setting it up. But let's put it on the TODO list in the long run.

**Comment by timdorr** [comment]
Yes, I do have access to all of that now. There was an effort to get that all updated, but I think it fizzled out a bit.

**Comment by markerikson** [comment]
Oh good - does that really include the `remote-redux-devtools` repo / site too?

Lenz, are you saying that it's a _site_ that needs a new cert?  I haven't looked at `remote-redux-devtools` to see how it works.

**Comment by phryneas** [comment]
Yup, exactly that. That same cert might need some extra configuration to be also delivered over websocket (?) but that's the exact same cert.

Click this link to see: https://remotedev.io/ - as soon as you accept the insecure certificate, the remote browser extensions start working again as long as the redux that tries to connect from them is running in the same browser. (just that's not really the point of remote-dev-tools -.-)

**Comment by RichMatthews** [comment]
so I've managed to successfully connect to React Native Debugger app.

and this worked:

```
const store = configureStore({leagues: leaguesReducer, window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__())
```

how would this look as the equivalent in toolkit? where do I put the `window.` references?

**Comment by markerikson** [comment]
RTK's `configureStore` _should_ do that automatically:

```js
configureStore({reducer: leaguesReducer})
```

**Comment by RichMatthews** [comment]
ah cool, yeh that worked. might be worth updating the docs slightly [here](https://redux-toolkit.js.org/api/configureStore) as it is simple to setup with React Native as it turns out but it took me a couple of days and a bunch of internet browsing to get there

**Comment by markerikson** [comment]
@RichMatthews can you clarify what specific steps need to be done to get this to work with RN?

**Comment by jkoutavas** [comment]
> @RichMatthews can you clarify what specific steps need to be done to get this to work with RN?

@RichMatthews yes, please chime in. :-)

**Comment by hasanaktas** [comment]
Can anyone make it with React native?  I still haven't succeeded

**Comment by Pepeu07** [comment]
@hasanaktas @markerikson 
After a few hours this is what worked for me:

`const store = configureStore({
    reducer:{
        general:GeneralReducers
    },
    devTools:[
        devToolsEnhancer({ realtime: true })
    ],
})`

I've only been able to get it to work with the React Native Debugger app (https://github.com/jhen0409/react-native-debugger)

The steps that I took where:
1) run project
2) open React Native Debugger app at the desired port  `open 'rndebugger://set-debugger-loc?host=localhost&port=8070'` which I made a packadge.json script for convenience
3) then I started the debug mode on the project

Hope this helps

**Comment by Sir-hennihau** [comment]
@Pepeu07 I tried it myself. I could even connect to [React Native Debugger](https://github.com/jhen0409/react-native-debugger) without any additional configuration.

```
export const rootStore = configureStore({
    reducer: rootReducer,
});
```

```
       "react-native": "0.62.0",
        "react": "16.11.0",
        "@reduxjs/toolkit": "^1.5.1",
        "react-redux": "^7.2.4"
```

**Comment by phamquyetthang** [comment]
> Can anyone make it with React native? I still haven't succeeded

use react-native-debugger , you open redux devtool without any config

**Comment by solancer** [comment]
Here's how I got it working

Installed DevTool cli

`yarn add --dev @redux-devtools/cli`

or 

`npm install --save-dev @redux-devtools/cli`


add below config as a script

"scripts": { "redux-devtools": "redux-devtools --open=electron --hostname=localhost --port=8000" }


Make changes to store like below (don't forget to add port number same as the script above)

```
import { configureStore } from '@reduxjs/toolkit'
import authReducer from '../features/auth/authSlice';
import devToolsEnhancer from 'remote-redux-devtools';

export default configureStore({
    reducer: {
        auth:authReducer,
    },
    devTools: false,
    enhancers: [devToolsEnhancer({ realtime: true, port: 8000 })],
})

```

**Comment by spirobel** [comment]
@solancer do we need to to pass the actioncreators, like in: https://github.com/zalmoxisus/redux-devtools-extension/commit/64717bb9b3534ff616d9db56c2be680627c7b09d ?

**Comment by umarCogentlabs** [comment]
How to do in typescript?

**Comment by phryneas** [comment]
@umarCogentlabs with exactly the same code.

**Comment by dipanjanpanja6** [comment]
just do 
```
const store = configureStore({
  reducer: {
    // Add the generated reducer as a specific top-level slice
  },
  devTools: true,
});
```

**Comment by Bsingh2697** [comment]
<img width="605" alt="Screenshot 2022-04-27 at 12 17 05" src="https://user-images.githubusercontent.com/36998578/165506716-185dbdb7-3390-4d4b-8061-4f536a5904a9.png">
I have setup this but still not working, doesn't show anything in extension

**Comment by dipanjanpanja6** [comment]
@Bsingh2697 remove enhancers and middleware and try once.

**Comment by spirobel** [comment]
> just do `devTools: true` , its working for me
@dipanjanpanja6 what if you need to use remote devtools like me? (I am developing a browser extension, so the normal redux devtools dont work)

**Comment by B-R-Bender** [comment]
hey guys I wonder if anyone knows how to make DevTools work with https dev server?

**Comment by phryneas** [comment]
@B-R-Bender the devtools are in your browser, so is the website - there is no data sent over any wire, so it doesn't matter if you use http or https

**Comment by B-R-Bender** [comment]
@phryneas the thing is I'm using nx as a monorepo handler and one I've update my config to use ssl I'm not able to see anything in redux devtools
I've tried to turn ssl off and devtools are back

**Comment by phryneas** [comment]
@B-R-Bender you are looking at a website that is using Redux and you have opened the Redux Devtools in the same browser tab, right?

**Comment by mirek11s** [comment]
has anyone manage to make the debugger work with windows machine?

**Comment by Awais6** [comment]
no option work for me

**Comment by maniac-tech** [comment]
I'm facing this issue with Expo v49, any update or known solutions to it ?

**Comment by xXanth0s** [comment]
This worked for me.


First of all, install the package `@redux-devtools/cli` via 

```bash
npm i -D @redux-devtools/cli
```

Add this script to your package.json and start the script. A redux devtool app should appear. 

```
"redux-devtools": "redux-devtools --open=electron --hostname=localhost --port=8000",
```

In your app, change the store to the following configuration

```typescript
const backgroundStore = configureStore<StateModel>({
  reducer: storeReducers,
  devTools: false,
  enhancers: getDefaultEnhancers =>
    getDefaultEnhancers()
      .concat(devToolsEnhancer({ realtime: true, hostname: 'localhost', port: 8000 })),
});
```


Start your app. You should see your redux store in the redux dev tools window, which has beened opened before. 
If not, set this configuration

![image](https://github.com/reduxjs/redux-toolkit/assets/6882434/74f86ab8-4e63-410d-8299-d7fa00eccdd1)

**Comment by liquidvisual** [comment]
@xXanth0s Did your solution work for Expo v49-51? I'm pretty sure it doesn't work with Hermes and we're all [doomed](https://github.com/jhen0409/react-native-debugger/discussions/774) to suffer zero DX for all eternity.
