### ISSUE TITLE
compare original state with reference equality

### ISSUE THREAD

**Issue by jackielii** [reduxjs/redux-toolkit#829]
I have a reducer created using `createSlice`. Inside one of the case reducer, I'd like to compare with the original state with reference equality. How do I achieve this?

```
const slice = createSlice({
  name: 'filter',
  initialState: emptyConstraint,
  reducers: {
    addPlain(state, action: PayloadAction<{ parent: Constraint.AsObject }>) {
      if (state === action.payload.parent) { // <<<< how should I do equality check? do I need to import: https://immerjs.github.io/immer/docs/original
          // do something with state
      }
    },
})
```

**Comment by phryneas** [comment]
You can use `original` from `immer`:

`import {original] from 'immer';`

`if (original(state) === action.payload.parent)`

**Comment by jackielii** [comment]
> You can use `original` from `immer`:
This is what I end up doing, however, I had to add `immer` as an explicit dependency as it's not re-exported. Would this be ok? Will there be any incompatibilities?

**Comment by jackielii** [comment]
@phryneas turns out it doesn't always work.

If I just do `yarn add immer`, it installs 8.0.0. `original` calls `isDraft` which will return false because the draft from redux-toolkit is different from immer

Did found a workaround:  In Yarn, I have to align the immer version to exactly redux-toolkit is using so that they resolve to the same immer source code inside node_modules. 

However, the workaround is flaky and since redux-toolkit re-exports some of the immer's functions like `current`, I think we should export `original` as well.

**Comment by phryneas** [comment]
The current RTK 1.5 uses immer 8.0.0. But yeah, probably we should re-export `original` as it is quite useful. Actually, I thought we already did that. @markerikson what are your thoughts? We had good uses for `original` in performance scenarios if I recall correctly

**Comment by markerikson** [comment]
Probably reasonable to re-export that too, yeah.
