### ISSUE TITLE
Add documentation to show how to use `createAction` with meta/error 

### ISSUE THREAD

**Issue by sheepsteak** [reduxjs/redux-toolkit#833]
I appreciate this may come across as a StackOverflow question but I think there's a gap in the documentation here. I'm happy to do a PR for this as soon as I figure out.

I'm really struggling with how I can use `createAction` to create actions that can have an `error`. I've read the existing docs and looked through the type tests and still can't figure it out.

I'm attempting to do something like this to fit with Flux Standard Actions:

```ts
const addProduct = createAction(
  "ADD_PRODUCT",
  (args: { id: string; quantity: string } | Error) => ({
    error: args instanceof Error,
    payload:
      args instanceof Error
        ? args
        : {
            id: args.id,
            quantity: args.quantity
          }
  })
);

// addProduct is then usable like so
const action1 = addProduct({id: '1', quantity: 1});
const action2 = addProduct(new Error("error"));
```

Is this the correct way to use `createAction` to declare an action that can take an error (or `meta`)? Obviously there would be type guards needed to work out if this is a normal action or error action and I've found [`isError` from `flux-standard-actions`](https://github.com/redux-utilities/flux-standard-action#iserroraction) works great for this:

```ts
const action2 = addProduct(new Error("error"));

if(isError(action2)) {
  // payload now inferred as Error
  console.log(action2.payload.message);
}
```

It might be worth adding a function like this to the toolkit as it's a common thing to do when using error actions.

Am I on the right track here? Would it be helpful if I added something to the docs to show how to make an action that has `meta` and/or `error` properties?

**Comment by markerikson** [comment]
You're looking for "prepare callbacks" as the second argument to `createAction`:

https://redux-toolkit.js.org/api/createAction#using-prepare-callbacks-to-customize-action-contents

So yes, the snippet you've got there looks mostly correct, glancing at it.  Is there something about it that isn't working as expected?

Docs improvements are always welcome!

**Comment by sheepsteak** [comment]
> So yes, the snippet you've got there looks mostly correct, glancing at it. Is there something about it that isn't working as expected?

I saw the mention of "Flux Standard Actions" in the docs and naively assumed that the handling of `Error` being passed in was automatic so I could do something like this:

```ts
const addProduct = createAction<{ id: string; quantity: string }>(
  "ADD_PRODUCT"
);

// can then do either of these
const action1 = addProduct({id: '1', quantity: 1});
const action2 = addProduct(new Error("error"));
```

I understand what you're saying though and using Flux Standard Actions is just a suggestion. I might just use separate error actions and go with the flow 😄 

Thanks for the explanation!
