### ISSUE TITLE
createAction with required payload

### ISSUE THREAD

**Issue by koshpendi** [reduxjs/redux-toolkit#834]
Hi! Can you provide example how to create action with required payload?
for example if i create like this

```
const foo = createAction<{ email: string }>('some_type');
```
type of **foo()** equals to `ActionCreatorWithOptionalPayload`
How to get it with `ActionCreatorWithPayload`?

**Comment by phryneas** [comment]
I'm 99% sure you're using TypeScript with `strictNullChecks: false` in your `tsconfig.json`.

That means that your code up there is handled by TypeScript like `const foo = createAction<{ email: string } | null | undefined>('some_type');` - and that `undefined` is interpreted by RTK as "this is optional".

Other than you enabling strict mode for your TypeScript config, there is unfortunately not much we can do about it.

**Comment by koshpendi** [comment]
@phryneas thanks for reply but unfortunately  `strictNullChecks: true` not helped. 

```const foo = createAction<any>('some_type')``` with that i got what i need becouse of ```IsAny<P, ActionCreatorWithPayload<any, T>``` but `any`...

![image](https://user-images.githubusercontent.com/46047833/101278559-3409df00-37e6-11eb-8b70-a559b7eab4e3.png)

**Comment by phryneas** [comment]
Could you provide a reproduction for that? From my side, everything works as expected as you can see [in this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMZQKYEMaoIJJsCAOwF84AzKCEOAcgAE0ATAVwA8ArAZwHoYIIANgGtgMGgFgAUFKRFO8MvzgBeOCgxZc+IgB4EcVCHTABALjjyowQgHM4xAHwAKGpyqoA+jACeYVDQBKAG4pKW5uOAB3aCFOcmtUKUUIJ31DYzM4ACIseSziANDJcLoYTgBaVFY-PEqoSig4AFFq1DxURjgARjh0KBtmEFRCMoAaOAAjZngbCHgABgA6JwAmAFY1gBZCyWSnAKA)

**Comment by koshpendi** [comment]
@phryneas thanks much. After couple of fixes everything is work as expected.
```
"strict": true,
"strictNullChecks": true,
``` 
was helpful
