### ISSUE TITLE
TypeError: Cannot read property 'pending' of undefined in the redux toolkit while using createAsyncThunk and createSlice

### ISSUE THREAD

**Issue by Satyam-code143** [reduxjs/redux-toolkit#836]
I am getting the above-mentioned error on just adding the **extraReducer** to my **createSlice**.

This is a **react-native** application.

Here is my code:

```
export const login = createAsyncThunk(
      'loginAuth/login',
      async ({username, password}) => {
        try {
          const res = await api.post('SomeApi', {
            username,
            password,
          });
         
          return res.data;
        } catch (e) {
          return console.error(e.message);
        }
      },
    );

    const loginSlice = createSlice({
      name: 'loginAuth',
      initialState: {
        loginStatus: false,
        isLoading: false,
        error: '',
      },
      reducers: {
        //Yet to be filled
      },
      extraReducers: {
        [login.pending]: (state) => {
          state.isLoading = true;
        },
        [login.fulfilled]: (state, action) => {
          state.isLoading = false;
        },
        [login.rejected]: (state, action) => {
          state.error = action;
        },
      },
    });
// this is another file calling the dispatch
 class Login extends Component {
      state = {
        data: {
          username: '',
          password: '',
        },
        textHidden: true,
      };
    
      handelSubmit = (status) => {
        if (status) {
          this.props.login(this.state.data);
        }
      };
    render(){
        return(
    //The UI for Input is here. I confirmed that the dispatch is working fine. I did log the username and password. But I didn't use the createAsyncThunk
    )
    }
    
    const mapDispatchToProps = (dispatch) => ({
      login: (data) => dispatch(login(data)),
    });
    
    export default connect(null, mapDispatchToProps)(Login);
```

To confirm the dispatch I did write another function with the same name login() where I logged the username and password:

```
export const login = ({username, password}) => async (dispatch) => {
      console.log(username,password); // Here the dispatch is working fine
      //  called that API and dispatched to a reducer dispatch(loginSucess(result.data))
};
```

The same is on stack-overflow:

[stackoverflow.com/questions/65194394/typeerror-cannot-read-property-pending-of-undefined-in-the-redux-toolkit-whil](url)

Only the required dependencies are mentioned below:

```
"dependencies": {
    "@reduxjs/toolkit": "^1.4.0",
    "axios": "^0.21.0",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-redux": "^7.2.2",
  },
```

**Comment by phryneas** [comment]
I assume that `login` and `loginSlice` are not in the same file & you just simplified that here, right?
You might have a circular import. In fact, the screenshot of the error message even contains a warning about that.
Move `logiǹ` into a file that does not import any slice and not any files that recursively might import a slice - or into the same file as your `loginSlice`.

**Comment by Satyam-code143** [comment]
@phryneas 
Both `login `and `loginSlice `are in the same file.

This might help:

```
import {createSlice, createAsyncThunk} from '@reduxjs/toolkit';
import api from '../../Api/api';

// Slice
const loginSlice = createSlice({
  name: 'loginAuth',
  initialState: {
    loginStatus: false,
    isLoading: false,
    error: '',
    userData: null,
  },
  reducers: {},
  extraReducers: {
    [loginSystem.pending]: (state) => {
      state.isLoading = true;
    },
    [loginSystem.rejected]: (state, action) => {
      state.isLoading = false;
      state.error = action.error.message;
    },
    [loginSystem.fulfilled]: (state, action) => {
      state.isLoading = false;
      state.loginStatus = true;
      state.userData = action.payload;
    },
  },
});

const LoginSlice = loginSlice.reducer;
export default LoginSlice;


export const loginSystem = createAsyncThunk(
  'loginAuth/loginSystem',
  async ({username, password}) => {
    console.log(username, password);
    const res = await api.post('/api/auth/signin', {
      username,
      password,
    });
    console.log(res.data);
    return res.data;
  },
);

```


I have changed the name but the remaining is fame. The above code is in a single file.


Now the remaining is the same:

```
import {connect} from 'react-redux';
import {loginSystem} from '../../redux/slices/loginSlice';

class Login extends Component {
      state = {
        data: {
          username: '',
          password: '',
        },
        textHidden: true,
      };
    
      handelSubmit = (status) => {
        if (status) {
          this.props.login(this.state.data);
        }
      };
    render(){
        return(
    //The UI for Input is here. I confirmed that the dispatch is working fine. I did log the username and password. But I didn't use the createAsyncThunk
    )
    }
    
    const mapDispatchToProps = (dispatch) => ({
      login: (data) => dispatch(loginSystem(data)),
    });
    
    export default connect(null, mapDispatchToProps)(Login);

```

The above code is in another file.

Thank You !!

**Comment by phryneas** [comment]
JavaScript code is executed from top to bottom.
If you want to use `loginSystem` in `loginSlice`, you have to define it before using it, not after.

**Comment by Satyam-code143** [comment]
L🤣L I just didn't notice how foolish of me.
@phryneas 
**Thank you!!**

**Comment by aditya-alshi** [comment]
[https://github.com/aditya-alshi/postbulletin/blob/main/src/bulletinApp/feature/todos/todosSlice.js](url)

help me. Same issue. 

`import { createSelector, nanoid, createAsyncThunk } from "@reduxjs/toolkit"
import { createSlice } from "@reduxjs/toolkit"
// import { nanoid } from "@reduxjs/toolkit"

import { getLocStoData } from "../../modifyLocsto"

// export const todosAsyncMiddleWare = storeAPI => next => action =>{
//     if(typeof action === 'function'){
//         return action(storeAPI.dispatch, storeAPI.getState)
//     }
//     return next(action)
// }

// export const fetchTodosFromLocStor = (dispatch, getState)=>{
//     setTimeout(async ()=>{
//         console.log(locStoData)
//         dispatch(loadTodos(locStoData))
//     }, 4000)
// }
export const fetchTodosFromLocStor = createAsyncThunk('todos/loadTodos', async()=>{
    // const locStoData = await getLocStoData("todos")
    return [
        { id:0, text: "Asfaq Miya", completed: false, color: "Blue" },
        { id:1, text: "Paiso ke Ameer", completed: false, color: "Purple" },
        { id:2, text: "Pooja", completed: false, color: "Green" },
        { id:3, text: "Kabhi na jaye ishwar ke kareeb", completed: false, color: "Orange" },
        { id:4, text: "Jo Maauf karta hai uska dil", completed: false, color: "Black" },
        { id:5, text: "Bohot bada hota hai", completed: false, color: "White" }
    ]
    // return new Promise(resolve=>{
    //     setTimeout(async ()=>{
    //     }, 4000)
    // })
})


const initialState = [
  
    { id:0, text: "killing Machine", completed: false, color: "Blue" },
    { id:1, text: "jaanwar", completed: false, color: "Purple" },
    
]

export const selectFilteredTodos = createSelector(
    state => state.todos,
    state => state.filters.color,
    (todos, color)=>{
        if(color.length === 0){
            return todos
        }
        return todos.filter(todo=>color.includes(todo.color))
    }
)

// const todoReducer= (state = initialState, action) => {
//     switch(action.type){
//         case "todos/loadTodos":
//             return action.payload
//         default:
//             return state
//     }
// }


const todosSlice = createSlice({
    name: "todos",
    initialState,
    reducers:{
        addTodos : {
            reducer(state, action){
                state.push(action.payload)
            },
            prepare(text){
                return{
                    payload : {id: nanoid(), text: text}
                }
            }
            
        },
    },
    extraReducers : builder =>{
        builder.addCase(loadTodos.fulfilled, (state, action)=>{
            state = action.payload
        })
    }

})

export default todosSlice.reducer;
export const {loadTodos, addTodos} = todosSlice.actions

`
