### ISSUE TITLE
prepare not triggered when dispatching by type name

### ISSUE THREAD

**Issue by audunsol** [reduxjs/redux-toolkit#837]
I am struggling with triggering some `prepare` action in some special cases where we are using the action type string. Repro sample:

```javascript
import { configureStore, createSlice }  from '@reduxjs/toolkit'; // version 1.5 and 1.4
import {nanoid} from 'nanoid';

const slice = createSlice({
  name: 'todos',
  initialState: [],
  reducers: {
    addTodo: {
      prepare: (p) => {
        console.log('########### HELLO From PREPARE ---', p);
        return {payload: {...p, id: nanoid()}};
      },
      reducer: (todos, action) => {
        console.log('########### HELLO From reducer', action.payload);
        todos.push(action.payload)
      }
    }
  }
});

const store = configureStore({reducer: slice.reducer});
const addTodo2 = p => ({type: slice.actions.addTodo.type, payload: p});

console.log('Dispatch directly - triggers prepare:');
store.dispatch(slice.actions.addTodo({text: 'Do stuff'})); // logs HELLO from PREPARE and HELLO from reducer

console.log('Dispatch by type name - does not trigger prepare:');
store.dispatch({type: slice.actions.addTodo.type, payload: {text: 'Do stuff'}}); // logs just HELLO from reducer
```

Code pen here: https://codepen.io/audunsol/pen/eYddgLo?editors=1111

Is this not supposed to be supported?

In our specific case, this happens when trying to use a custom api-middleware, where we pass in the action type strings as our onStart, onSuccess, and onError handlers, where it seems like best practice to pass in serializable strings, and not functions.

**Comment by phryneas** [comment]
No, `prepare` is the `prepare` statement for the internally wrapped `createAction`. It is not executed on reducer level, only on action creator level.

**Comment by markerikson** [comment]
Yep.  `prepare` looks roughly like:

```js
const addTodo = (text) => {
  const restOfAction = prepare(text);
  return {type: "todos/todoAdded", ...restOfAction};
}
```

so it's part of the action creator, not the reducer.
