### ISSUE TITLE
'freeze' is not exported from 'immer'.

### ISSUE THREAD

**Issue by stan-stepien** [reduxjs/redux-toolkit#838]
"@reduxjs/toolkit": "^1.5.0",

followed the tutorial https://redux.js.org/introduction/getting-started
used this command to install: npx create-react-app my-app --template redux

./node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js
Attempted import error: 'freeze' is not exported from 'immer'.

**Comment by phryneas** [comment]
Please check that you have the correct version of immer installed and that you have only one version of immer installed in your application. Should be immer >= 8.0.0

**Comment by stan-stepien** [comment]
Thanks this solved the issue, react-dev-utils\package.json references immer@7.0.9
