### ISSUE TITLE
Immer behaviour in redux toolkit

### ISSUE THREAD

**Issue by suyashdeshpande** [reduxjs/redux-toolkit#839]
Hi,

I have few doubts regarding immer behaviour in redux toolkit.

1. Why we can't mutate and return new state together at the same time?
2. If we return a new state, are we opting out of immer in this case (Since we are creating a new copy)?
3. Can we use current() inside a slice and opt-out of immer?
4. How does immer freezing works in case of slice?

Thanks

**Comment by suyashdeshpande** [comment]
@phryneas @markerikson Can you help?

**Comment by phryneas** [comment]
Honestly, all of these questions are handled in the immer documentation. RTK does nothing differently from any other library or your own code using immer.

But, here in short order:

1. you modify the state and then return something completely different. Is the state now the new returned value or the modified original state? There is no defined behaviour
2. immer will still freeze your returned object unless you have already frozen it
3. you can use original to get the original value, but if you return something immerable, it will still be frozen
4. as in immer

**Comment by suyashdeshpande** [comment]
@phryneas Thanks for such a quick response. 
1 more question -> Why does immer freezes a state (returned from slice) as I know nobody is changing the state. We want to prevent state mutations inside slice, right, why after returning of state?

**Comment by phryneas** [comment]
You want to prevent accidentally mutating your state in your component.

```js
// in your component:
const someList = useSelector(state => state.posts);
someList.sort() // this line would mutate your state
```
