### ISSUE TITLE
Unknown type of payload

### ISSUE THREAD

**Issue by tduraj** [reduxjs/redux-toolkit#840]
Howdy,
I created async action using `createAsyncThunk` function.
Then, I added actions created by this function to extraReducers:
```
  extraReducers: (builder) => builder
    .addCase(myAction.pending, (state) => {
      state.isLoading = true;
    })
    .addCase(myAction.fulfilled, (state) => {
      state.isLoading = false;
    })
    .addCase(myAction.rejected, (state, action) => {
      **state.error = action.payload;**
      state.isLoading = false;
    }),
```
The problem is `action.payload` has unknown type. I tried to type addCase callback like this
`.addCase(signInAction.rejected, (state, action: PayloadAction<InitialSliceState>) => {`

But it's makes another error:
`Argument of type 'AsyncThunkRejectedActionCreator<SignInBody, {}>' is not assignable to parameter of type 'string'.`

**Comment by phryneas** [comment]
How did you use `createAsyncThunk`?

**Comment by tduraj** [comment]
```
interface RequestBody {
  username: string;
  password: string;
}

interface ResponseBody {
  error: string | null;
  data: string[];
}

export const myAction = createAsyncThunk(
  'action/test',
  async (body: RequestBody) => {
    return axios.post<ResponseBody>('/test', body);
  },
);
```

**Comment by phryneas** [comment]
In this case, that's totally okay as it is. The `rejected` case happens because an error is thrown in that code before a payload could have been returned. There is no payload, hence it's type is unknown in that case.
As for the error details, you can find these in `action.error`

**Comment by tduraj** [comment]
Of course, you're right. Typing of fulfilled action payload works perfect. Thanks for explanation 😄
