### ISSUE TITLE
ActionCreatorWithNonInferrablePayload when using createSlice() creator

### ISSUE THREAD

**Issue by amcsi** [reduxjs/redux-toolkit#847]
[Here is a TypeScript playground link.](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYQIYGcCmAlTATAVwGNMoAaOIqTVGTAZQBtgSKAFVAT0YlTwEEiMYBAB2cAL5wAZlAgg4AcgAC1QgA8AVugD0MCBEYBrYDEUBuAFCXM6yLDjBRdKNNQk4AcUyjSLAGKYMEQAFvQwtJgAPAAqAHyIlnDJcHi0qABccDFWEta29vDSBKJCIuIA5kEAkqKmwKiM4ZGxcQAUTvWNACLpWTEAlFnevlABQaHNdK2JKXDUMARQ4ghJcylpEVmdwj3pZGvJErn5dtBFJWVilNSRgcFhzCSxFFOYcLZ0onjoXj5+RHukwi03i7UOcFEqBAmCy6BgY1EFQOcx2DSaINhcDelgGsxSRDE8Lg6GIJHQ6DQWFwhBIUCyVJw+GIpCib3YXB4fEEwjErQSAF44G14ZEKEgwJzeHhJHiBQlVusUgslisIUrkgA6bWiugojVzTaZOCS7jS-VK44Qq0QlXLG40OhMFiYNqKjVQmEW9Zoxrs9XK5l09BZd0G5KkojkkMksmYCmMmks8gBo7eiQDE6WQmiYnoJ7vIVUR2YIGPF1tRQhTCcRQUKowWpdDEtUQEEAAI1I7QAzANM9YdDo4ABROyYMpIuAwELAX76OBduCocTuXniYu0aDLqOYMDCKeoSHtrvkSEQeAruA88rIW76KAAdVMIQAcmJatJSFBUB3GJgODNPhLHzF1NTXcp0E1SNoysIA)

After creating a (dynamic) slice, the payloads for the reducer/actions I create are not inferrable. It seems like there may be some disconnect between `GenericFetchState<T>` and `State` (even though `State` needs to extend `GenericFetchState<T>`), because this works if I don't allow the freedom of expanding the state shape and only allowed it to be exactly `GenericFetchState<T>`.

**Comment by phryneas** [comment]
That's perfectly valid and a TypeScript thing. `T` could be any supertype of `number` in this context, it cannot be explicitly narrowed down by inference just based on the state type.

For example, as you wrote it, it would also allow for `const slice = createFetchSlice<string | number, GenericFetchState<number>>('hey', getInitialState<number>(3));`

See this twitter thread by Ryan Cavanaugh: https://twitter.com/SeaRyanC/status/1337176976444932099

**Comment by amcsi** [comment]
@phryneas 

1. But if T is `string|number`, and `State extends GenericFetchState<T>`, then wouldn't `State` have to extend `GenericFetchState<string|number>`?
2. If not, then how am I expected to be able to restrict `State` that the `{data: T}` bit would always be a given?
3. This is a slimmed down example. In my real code there's a bunch of complex stuff happening, but all the typing (regarding State) _works exactly as I expect_, with the **only exception** being reaching into these action creators from the created slice.

**Comment by phryneas** [comment]
You could try it without adding `T`.

[see playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYQIYGcCmAlTATAVwGNMoAaOIqTVGTAZQBtgSKAFVAT0YlTwEEiMYBAB2cAL5wAZlAgg4AcgAC1QgA8AVugD0MCBEYBrYDEUBuAFCXM6yLDjBRdKNNQk4AcUyjSLAGKYMEQAFvQwtJgAPAAqAHyIlnDJcHi0qABccDFWEta29vDSBKJCIuIA5kEAkqKmwKiM4ZGxcQAUTvWNACLpWTEAlFnevlABQaHNdK2JKXDUMARQ4ghJcylpEVmdwj3pZGvJErn5dtBFJWVilNSRgcFhzCRRU5hwtnSieOhePn5E90mEWmqFEnDi7UOcFEqBAmCy6BgY1EFQOcx2DSawPhcFelgGsxSRDEiLg6GIJHQ6DQWFwhBIUCyNJw+GIpBe2PYXB4fEEwjEHMiAG1FJtUIoALoQuAAXjgbURkQoSDA3N4eEkBJlCVW6xSCyWKyheuSADpzYq6GiTXMxVlVdx1da9ccoa6oQbljcaHQmCxMG1dSaYXDnesMY1XmG5mo2VB0FkgzbkuSiJSE2SKZgqcy6XHoykJGGJAMTpZiaJSegnm85VQfZhAY9-W1FCFMJxFBQqjBal0sS1RAQQAAjUjtADMA1L1h0OjgAFE7Jgyii4DAQsAfvo4GO4KD91dxPXaNBDyQwMI16hocOx+RoRB4Ae+eVkLd9FAAOqmEIAOTEWppFIKBUBHRhMA4R0+Esat-VNdx+UrU1U3TKwgA)

**Comment by phryneas** [comment]
As for the questions:
1. TS is TS. Put it in, be appalled :/
2. see last comment
3. this has nothing to do with RTK, but is normal TS behaviour, as you can see in [this codesandbox](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYQIYGcCmAlTATAVwGNMoAaOIqTVGTAZQBtgSKAFVAT0YlTwEEiMYBAB2cAL5wAZlAgg4AcgAC1QgA8AVugD0MCBEYBrYDEUBuAFCXM6yLDjBRdKNNQk4AcUyjSLAGKYMEQAFvQwtJgAPAAqAHyIlnDJcHi0qABccDFWEta29vDSBKJCIuIA5kEAkqKmwKiM4ZGxcQAUTvWNACLpWTEAlFnevlABQaHNdK2JKXDUMARQ4ghJcylpEVmdwj3pZGvJErn5dtBFJWVilNSRgcFhzCSxFFOYcLZ0onjoXj5+RHukwi03i7UOcFEqBAmCy6BgY1EFQOcx2DSaINhcDelgGsxSCyW4jgAG0AAxwDCU0ScSm-GIUClU1A0unYzEAXTZRDE8MseUsPNE8Lg6Ce7wAvDcaHQgY8WJg2ooQphOIoKFUYLUuhiWqICCAAEakdoAZgGAysliAA)

**Comment by amcsi** [comment]
I do need `T`, because I create slices of many data shapes. But it seems like I was able to get it to work with your example but keeping T [like this](https://www.typescriptlang.org/play?ssl=17&ssc=64&pln=17&pc=77#code/JYWwDg9gTgLgBAbzgYQIYGcCmAlTATAVwGNMoAaOIqTVGTAZQBtgSKAFVAT0YlTwEEiMYBAB2cAL5wAZlAgg4AcgAC1QgA8AVugD0MCBEYBrYDEUBuAFCXM6yLDjBRdKNNQk4AcUyjSLAGKYMEQAFvQwtJgAPAAqAHyIlnDJcHi0qABccDFWEta29vDSBKJCIuIA5kEAkqKmwKiM4ZGxcQAUTvWNACLpWTEAlFnevlABQaHNdK2JKXDUMARQ4ghJcylpEVmdwj3pZGvJErn5dtBFJWVilNSRgcFhzCRRU5hwtnSieOhePn5E90mEWm8XahzgolQIEwWXQMDGogqBzmOwaTWBMLgr0sA1mKSIYjhcHQxBI6HQaCwuEIJCgWUpOHwxFILwx7C4PD4gmEYlZkQA2opNqhFABdOIJAC8cDacMiFCQYA5vDwklxkoSq3WKQWSxW4O1yQAdCa5XRkYa5sKskruCqLdrjuCneDdcsbjQ6EwWJg2lrDZDoQ71qjGq9g3M1MyoOgsv7LckSUQybHiaTMOSGdToxGUhJgxIBidLATRET0E83tKqJ7MIDHj62ooQphOIoKFUYLUuuiWqICCAAEakdoAZgGResOh0cAAonZMGVEXAYCFgD99HBh3BUOJ3DzxDXaNAd8nMGBhMvUBCB8PyBCIPBd3BueVkLd9FAAOqmEIAOTEWppFIKBUEHRhMA4O0+EsCsfSNfdynQI0kxTKwgA).
It's still a bit weird that I couldn't have a generic parameter of `T` itself [like in the example in the redux-toolkit docs](https://redux-toolkit.js.org/usage/usage-with-typescript#wrapping-createslice). But I'm still a bit new to typescript, so there's not much I can do for now than to accept that this is normal for some reason.
Thanks for your help!

**Comment by amcsi** [comment]
Also I don't get it... back to what I was originally trying to do, how come it's recognized here (as I'm expecting) that `initialState.data` is of type T? It does look like TypeScript recognizes my type properly; it's just that something doesn't make that typing get all the way to the returned slice's action creators :/
![image](https://user-images.githubusercontent.com/116494/101940695-28078e00-3be7-11eb-9134-7948c31abc6e.png)

**Comment by phryneas** [comment]
Well, as you saw from point 3 in my last answer: that type just does not make it out of that function. I have no idea why. But again, this has nothing to do with action creators or anything RTK. It's just how that generic flows there.

**Comment by amcsi** [comment]
Oh yeah, apparently if I return that `initialState.data`, suddenly it appears as `unknown`. OK, I get it, this really does look to be a TypeScript issue.

**Comment by lukemcgregor** [comment]
It seems to happen if you have a type like Partial<T> eg where {} is a possible value. You can get around it by nesting this {thing: Partial<T>}
