### ISSUE TITLE
Typescript - Unable to wrap AsyncThunk with an abstract type

### ISSUE THREAD

**Issue by dprslt** [reduxjs/redux-toolkit#851]
I try to wrap an AsyncThunk within an abstract crud thunk factory.

I simply want to define an interface for an AsyncThunk who needs at least an uuid as parameter.

```ts
export type IdentifiedElement = { uuid: string };

export interface CrudThunks<ElementType> {
    getOneThunk: AsyncThunk<ElementType, IdentifiedElement, {}>;
}
```

Unfortunately, i can't assign to the getOneThunk an AsyncThunk defined with a params extending my IdentifiedElement :

```ts
interface GetOneParam extends IdentifiedElement {
    anoterParam: string
}

const getOneThunk = createAsyncThunk<string, GetOneParam>(`/getOne`, async () => {
    return "toto";
});

const myCruds: CrudThunks<string> = {
    getOneThunk: getOneThunk
} 
```

I got the following Error : 

```
Type 'AsyncThunk<string, GetOneParam, {}>' is not assignable to type 'AsyncThunk<string, IdentifiedElement, {}>'.
Type 'AsyncThunk<string, GetOneParam, {}>' is not assignable to type '(arg: IdentifiedElement) => AsyncThunkAction<string, IdentifiedElement, {}>'. 
Types of parameters 'arg' and 'arg' are incompatible. 
Property 'anoterParam' is missing in type 'IdentifiedElement' but required in type 'GetOneParam'.
```
I was able to reproduce the bug with only some parts of my code in a [TypeScript SandBox](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFB1XAggZwJ4DsDGAKgBYCuuA1gDRz5QCmAhjPVnkWZVUgL5wBmUCCDgByAAIMAJqQAeAK0wB6GBAgAbCsBiiA3EgP1ZkWHBjYw9OAEkp9XDGD9g9KQFF19EPfgBeRHCkpMBSAFxwmDBQwLgA5nA8+khGJvAxLFD8jPhWAMJQpFIk5BSYADweXj6EFvQAfIgoaLH0MADyuPTFlOFsBN0UFZ7eDjWWNLY+Ti7uwz40CDx1+jwGSgBUSCTAmHBSEPS7uBDwAO7QFHD02sT0UMnG0GkOd1k5cPmFA+VNqJUjMDG9G4aDgAHFWh16AAFRhQRggIFXWQsXBSXaTBzTVz-HxwfyYxzOHFzBzcBrIUEtdqdAa9HD9TiDXGjWo0CE0mFwhFAhZLFZIdZKAzpV7ZKwcqGw+EiIyo9E2OxY4mzKoORqgxjHDLShHhSLROK8Az4CC4SJwalQgb42gMZisBkcEplA0xWLsyGdXUgOoACgABkorZ0AzRGE64H6AJT4im-OAMGCkKC4OAAIlUqnTK2jSVN5vgIGwn3R4VL31dUXdDX8lOaXq6TPCIabJV4cCAA)

This pattern works well with something else than AsyncThunk.
Did i miss something ? Is they're another way to achieve what i want to to  ?

**Comment by pkirilin** [comment]
In your example, `createAsyncThunk` is expecting type `GetOneParam`. `createAsyncThunk` doesn't know anything about `IdentifiedElement` and can't "autocast" it. Also, second generic types of `createAsyncThunk` and `AsyncThunk` must match.

Replace `IdentifiedElement` with `GetOneParam` inside `CrudThunks`:

```ts
export interface CrudThunks<ElementType> {
  getOneThunk: AsyncThunk<ElementType, GetOneParam, {}>;
}
```

**Comment by dprslt** [comment]
I want to have a "generic/abstract" `CrudThunks` type that enforce the Thunk parameter to have at least an ID (to at least match the interface of `IdentifiedElement`. And in the same time have a specific Thunk with fully typed param.

I'll run on the `CrudThunks` some generic function which will only need an ID and do not care about the other attributes.

Typescript allow me to do the following without trouble, so i was expected to be able to do the same thing with an `AsyncThunk`.

```ts
const myGetOneParams: GetOneParam = {uuid: '01', anotherParam: 'query'};
let myIdentifiedElement: IdentifiedElement = myGetOneParams;
`
``

I they're a way i can type my `AsyncCrud` to achieve what i want to do ? Since, the same pattern works well with another generic type, i assume that i'm stuck by the type of `AsyncThunk`.

It looks like the `AsyncThunk` type check the assignation "both ways".
When we try to assign `AsyncThunk<, GetOneParam,> `to a `AsyncThunk<, IdentifiedElement,>` it evaluates the assignation of a `GetOneParam` to an `IdentifiedElement` (which should be ok) and then assign the `IdentifiedElement` to a `GetOneParam` (which logically fails).

Why the second check is needed since the right part of the affectation is a subtype of the left one ?

**Comment by pkirilin** [comment]
You are trying to assign type `AsyncThunk<T, GetOneParam, {}>` to type `AsyncThunk<T, IdentifiedElement, {}>`. These types are checked *contravariantly* by default. In your case, you can force typescript to check them *bivariantly* instead by specifying `strictFunctionTypes: false` in your `tsconfig.json`:

```json
{
  "compilerOptions": {
    "strictFunctionTypes": false
  }
}
```

More detailed explanation: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#strict-function-types

**Comment by dprslt** [comment]
Whoo ! thank you for the lecture, i'm pretty new to Typescript and i didn't know about this concept. It's make sense now, and i understand why it's could be dangerous.

I think i would not be able to achieve this abstraction without turning off this strict function type or ignore theses errors ...

Thank you for your time and your explanations !
