### ISSUE TITLE
TypeScript type for the result of dispatching a createAsyncThunk

### ISSUE THREAD

**Issue by hoffmanilya** [reduxjs/redux-toolkit#852]
Thanks for an awesome library! 

I asked on [SO ](https://stackoverflow.com/questions/65149053/how-should-you-type-a-async-thunk-being-passed-as-an-argument) but wasn't able to get a definitive answer around this. I've also seen a few similar issues here but I'm using the `connect` API instead of the `useDispatch` hook which most of those examples use. Given the code below, what should the type be for my `loadAction` so that TS knows this is a promise and that it has a `type` property.

```
interface ApiResponse {
  data: string;
}

interface ApiErrorResponse {
  message: string;
}

const api = () =>
  new Promise<ApiResponse>((resolve) => {
    resolve({ data: "123" });
  });

const loadSomething = createAsyncThunk<
  string,
  void,
  { rejectValue: ApiErrorResponse }
>("something", async (_, { rejectWithValue }) => {
  try {
    const result = await api();
    return result.data;
  } catch (err) {
    if (!err.response) throw err;

    return rejectWithValue(err.data as ApiErrorResponse);
  }
});

const List = ({ data = "Something", loadAction }: ListProps) => {
  React.useEffect(() => {
    const fetchData = async () => {
      const result = await loadAction();
      if (result.type.endsWith("rejected")) alert("Failed");
    };
    fetchData();
  }, [loadAction]);

  return <div>#{data}</div>;
};

interface DispatchProps {
  loadAction: () => AsyncThunkAction<string, void, {}>; //This doesn't work so what type should this be?
}

interface OwnProps {
  data?: string;
}

type ListProps = DispatchProps & OwnProps;

const mapDispatch = {
  loadAction: loadSomething
};

const ListContainer = connect<void, DispatchProps, OwnProps, {}>(
  null,
  mapDispatch
)(List);
```

**Comment by msutkowski** [comment]
@hoffmanilya The answer you got on SO is right. Per your comment there, if you wanted to have the type and use it in a child component, you can do something like this: https://codesandbox.io/s/using-inferred-type-example-connect-9rzsc?file=/src/features/counter/Counter.tsx:1652-2520

```ts
const mapDispatch = {
  asyncThunk
};

const connector = connect(mapState, mapDispatch);

type PropsFromRedux = ConnectedProps<typeof connector>;

const ChildComponent = ({
  asyncThunk
}: {
  asyncThunk: PropsFromRedux["asyncThunk"];
}) => {
```

**Comment by markerikson** [comment]
or, y'know, `({asyncThunk}: PropsFromRedux) => {` :)

**Comment by msutkowski** [comment]
> or, y'know, `({asyncThunk}: PropsFromRedux) => {` :)

Or this, assuming it's named the same way :D

**Comment by hoffmanilya** [comment]
Thanks both for your help. I can now see how the type could be passed to a child component and that makes total sense.

May I ask you what you would suggest for a model where I have a "generic" table that's used by multiple other tables. For example:

```
// Generic table that accepts any load action.

const GenericTable = ({loadRecords}) => {
  useEffect(()=>{
    loadRecords().then(()=> alert('loaded'))
  })

  return (...)
};

// Connected users table that passes a load users action to the `GenericTable`.

const UsersTable = ({loadUsers}: UserTableProps) => <GenericTable loadRecords={loadUsers} />;

const mapDispatch = {
  loadUsers
};

const connector = connect(null, mapDispatch);

type UserTableProps = ConnectedProps<typeof connector>;

// Connected logs table that passes a load logs action to the `GenericTable`.

const LogsTable = ({loadLogs}: LogsTableProps) => <GenericTable loadRecords={loadLogs} />;

const mapDispatch = {
  loadLogs
};

const connector = connect(null, mapDispatch);

type LogsTableProps = ConnectedProps<typeof connector>;
```

I feel like it's "wrong" to introduce a dependency on either `UsersTableProps` or `LogsTableProps` when typing the `GenericTable` props but I can't seem to figure out how else to do this when inferring the types using `ConnectedProps`.

**Comment by msutkowski** [comment]
Is there a particular reason you're using `connect` in general? There is no need to pass that down multiple levels - you can just `useDispatch` inside of your `GenericTable`, or connect it directly to the action instead of worry about trying to type things however far down.

**Comment by hoffmanilya** [comment]
@msutkowski thanks for the advice! I'll give the `useDispatch` route a try.
