### ISSUE TITLE
How to test addMatcher builder createSlice reducer in jest?

### ISSUE THREAD

**Issue by seankwon** [reduxjs/redux-toolkit#854]
Hi

I have the following `createSlice` reducer
```javascript
const mySlice = createSlice({
  name: 'mySlice',
  initialState: { loadingState: undefined },
  reducers: {},
  extraReducers: (builder) => {
    builder.addMatcher(isAnyOf(myThunk.pending, (state) => state.loadingState = "loading" ))
  }
});
```

And the following test:
```javascript
import reducer, { myThunk } from './myReducer';

describe('reducer', () => {
    it('has a pending state', () => {
      expect(reducer(undefined, { type: myThunk.pending })).toEqual(
        expect.objectContaining({ loadingState: 'loading' }),
      );
    });
});
```

But i would get the following error:

```
 FAIL  src/redux/reducers/myReducer.test.js
  ● myReducer › has a pending state

    expect(received).toEqual(expected) // deep equality

    Expected: ObjectContaining {"loadingState": "loading"}
    Received: {"loadingState": undefined }
```

Is there a way to test the reducer itself or will i have to create functions for each matcher action and test the individual function instead? The functionality in the UI (browser) works, but not in a jest test.

**Comment by phryneas** [comment]
try to `console.log` your action. `myThunk.pending` is an action creator, not a string, so you are just putting the wrong action in.

**Comment by seankwon** [comment]
ahh, gotcha, you're correct. thank you for the very quick response. Really appreciate the work you guys put in :)
