### ISSUE TITLE
createAction with prepare not typing args

### ISSUE THREAD

**Issue by stephen-dahl** [reduxjs/redux-toolkit#864]
consider the following code sample

```typescript
interface MyType {
	key1: string;
	key2: number;
}

const prepare = <K extends keyof MyType>(key: K, value: MyType[K]) => ({
	payload: { key, value },
});

const action = createAction('action', prepare);

prepare('key1', 0); // Error 0 is not type string
action('key1', 0); // no error
```
I see that action is typed to (...args: any[]) is there a way to have this infer the args of the prepare function

![image](https://user-images.githubusercontent.com/6061073/103696230-de466500-4f52-11eb-9652-a788ffec19ef.png)

**Comment by phryneas** [comment]
No, TypeScript cannot handle functions with later-to-be-resolved generic arguments as generic arguments.

**Comment by stephen-dahl** [comment]
ok, ts limitation, thanks
