### ISSUE TITLE
Cannot type check WritableDraft with optional parameters

### ISSUE THREAD

**Issue by GitLuca** [reduxjs/redux-toolkit#868]
Hi, I encountered a strange toolkit behavior, inside a Slice created with _CreateSlice_.
I don't know if it's a bug or I misunderstood something. 
_I'm using redux toolkit 1.5.0 and typescript 4.1.2._

I have a state structured like that
```
type State = {
    matches: {
        [matchId: string]: Match
    }
}

type Match = {
    id: number
    provider?: {
         id: number
         data: string
    }
}
```
I want to write a reducer like this:

```
editData(state, action) {
     const matchId = action.payload.matchId;
     // provider is optional, check its existance
     if (state.matches[matchId] && state.matches[matchId].provider) {
          state.matches[matchId].provider.data = action.payload.data;
      }
}
```

**This type check doesn't work, typescript says: "object is possibly undefined", and I have to add a "!" to the provider.** 
` state.matches[matchId].provider!.data = action.payload.data`

Why can't I use an if statement to check if the provider part is not undefined? Outside the slice, or using a temporary variable it does work, but not checking the state directly.

**If I write something like that (just for testing purposes) typescript throws no errors.**

```
editData(state, action) {
     const match = state.matches[matchId];
     const matchId = action.payload.matchId;
     // provider is optional, check its existance
     if (match &&match.provider) {
         match.provider.data = action.payload.data;
      }
}
```

Thank you!

**Comment by markerikson** [comment]
Seems like normal TS behavior to me (and not anything specific to RTK anyway).  TS's inference is good, but sometimes you just have to be more specific about what you're trying to tell it.

**Comment by phryneas** [comment]
Yes, as you can see this happens outside of RTK as well: [playground](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=23&pc=2#code/FDAuE8AcFMAIGVQENRwLywN7Fr2BbFAYwAtoBnALixzzoG1DRSBJAE2vNACcBLAOwDmAXWoBZYiVq4AvsDlgocCcxKwM2Orw6x+AV3wAjaN2mxI3APYA3bSYD81TXS079Rk2ZdsUSTjwFBMzkFADM9fiJQXkt+WGg2XlAAEV8ACi4UaGpELIAaWCQomP4nSCRwABtLJB1MJlYdLj4hAp9kfxbBGRkAShoXIliuAkl2dULi2IA6cqqatmmGknYAbi8Aeg3zK1s2E1heclhLSGjYpEqC0mgiAGtD0GPoAA8j5EjoL15Q2AzkVBLSQURhjNjCWAAMkhsEygOWIOW7GEs12dm4-WcLjwcOgQNUiLBKIsNnR03aSAmRXO-FmFWqtXJvnW2JCQA)
