### ISSUE TITLE
Disabling the non-serializable data warning

### ISSUE THREAD

**Issue by catamphetamine** [reduxjs/redux-toolkit#870]
In my code, I parse all date ISO strings into `Date`s because it's better this way.

That causes `@reduxjs/toolkit` to log two error messages:

> A non-serializable value was detected in an action, in the path:

> A non-serializable value was detected in the state, in the path:

There seems to be no configuration option to disable those error messages.

For anyone coming here from Google, my solution to the issue is:

```js
const consoleError = console.error; // eslint-disable-line no-console
console.error = (...args) => { // eslint-disable-line no-console
  if (args && typeof args[0] === 'string' && args[0].indexOf('A non-serializable value was detected in') > -1) {
    // Ignore.
  } else {
    // Log the error as normally.
    consoleError.apply(console, args);
  }
};
```

**Comment by markerikson** [comment]
The options for customizing or disabling this are specifically listed in the docs already:

- https://redux-toolkit.js.org/api/getDefaultMiddleware#customizing-the-included-middleware
- https://redux-toolkit.js.org/api/serializabilityMiddleware

**Comment by catamphetamine** [comment]
@markerikson 
Oh, thx
