### ISSUE TITLE
Update immer to fix vuln

### ISSUE THREAD

**Issue by FrederikBolding** [reduxjs/redux-toolkit#871]
Immer just released a new version that fixes a prototype pollution vuln.

https://github.com/immerjs/immer/commit/da2bd4fa0edc9335543089fe7d290d6a346c40c5

Is it possible to update the dependency?

**Comment by markerikson** [comment]
Our dependency is on `immer@^8.0.0`, so there's nothing we need to change - you just need to reinstall things on your end / update your own lockfiles.

**Comment by FrederikBolding** [comment]
Ah, my bad! We were using `1.4.0` which uses v7 of immer. Thanks for the heads up! 👍

**Comment by markerikson** [comment]
Yep, we specifically bumped from Immer 7 to 8 in RTK 1.5:

https://github.com/reduxjs/redux-toolkit/releases/tag/v1.5.0

**Comment by FrederikBolding** [comment]
Yeah, I figured! Solving the issue by bumping our Redux Toolkit dependency. 
Thanks for building a great library and sorry about the confusion! 😄
