### ISSUE TITLE
[FEATURE REQUEST] Slices that will always be present on `preloadState` could be flagged as `initialState: "preloaded"` instead of an actual initial state value

### ISSUE THREAD

**Issue by cbdeveloper** [reduxjs/redux-toolkit#873]
Every now and then I wish this would be possible. I like to find out if there are other people out there that would benefit from this pattern.

Sometimes, there are some values that will not change during the life-cycle of my app. And I'd like to add them to my Redux `state`, but it's not as simple as it sounds.

My use case is something like this:

- I have an object that I call `INTERNATIONAL`. It's generated by reading the `location.hostname` to define the `COUNTRY` and `LANGUAGE` that my user is in.

```
type INTERNATIONAL = {
  COUNTRY: TYPES.COUNTRY,
  LANGUAGE: TYPES.LANGUAGE
}
```

This is a React single page app. So that is done in `index.tsx` before the React app is even mounted. Once that object is built. It will **never** change during my app's life-cycle.

Right now I'm serving it as `props` to my `App` component. Here is how I'm currently doing it:

```
// On index.tsx
<App INTERNATIONAL={INTERNATIONAL}/>

// On App.tsx
return(
  <InternationalContext.Provider value={props.INTERNATIONAL}>
      // Now the rest of my App can access it via `useContext()`
  </InternationalContext.Provider>
);
```

This is fine for most uses. But it doesn't feel 100% right, because that is something that I consider to be `state`, and it's being provided in a different way, rather than just using `useSelector`. 

Also, the problem is that sometimes I wish to access it from an `action thunk`, for example. And that is simply not available through `store.getState()`. So I need to pass the values I need through parameters, making a verbose, harder to read code.

That's why I'd like to add it to my Redux state. Let's try to do that.

I'll definitely create a slice for it, but given the fact that the `INTERNATIONAL` object will be calculated and ready before the `configureStore` call, I will definitely add it to the `preloadedState`, rather than `dispatch` an update action after the `store` has mounted.

```
const store = configureStore({
  reducer: rootReducer,
  preloadedState: {
    INTERNATIONAL: INTERNATIONAL
  }
});
```

That's nice. My store will be create with the `INTERNATIONAL` object readily available for my code to access throughout my whole app.

I'll create a slice for it:

```
const INTERNATIONAL_SLICE = createSlice({
  name: "INTERNATIONAL",
  initialState: { // A INITIAL STATE IS REQUIRED },
  reducers: {
    // ...
  }
});
```
That is my problem. The fact that `initialState` is required is a pain, because I can't know upfront what it will be. So I have two options here, as far as I know:

- **OPTION 1**: Add the `initialState` with some default values that will never be used (since state is being preloaded) and won't make any sense at all.
- **OPTION 2**: Make its properties `COUNTRY and LANGUAGE` optionals, or make its whole slice type as `null || INTERNATIONAL`. Either way, that results in having to deal with types assertions everywhere when I'm working with `state.INTERNATIONAL`.

The problem is that both available options are bad, IMO.

**This is my feature request:**

For slices that for sure **will be 100% preloaded** on the `configureStore` call (i.e: will be present on the `preloadedState` object), I wish it was possible to avoid adding the `initialState` property with a valid state value. Maybe we could use some kind of flag like:

```
const INTERNATIONAL_SLICE = createSlice({
  name: "INTERNATIONAL",
  initialState: "preloaded",     // THIS WOULD FLAG THAT THE preloadedState SHOULD BE USED
  reducers: {
    // ...
  }
});
});
```

Then I guess some kind of check should be made during the `store` build process. If the slice `initialState` was flagged as `"preloaded"` and was not provided on the `configureStore` call, then an error should be thrown.

Is that even, remotely possible? Does anybody else would find that useful?

**PS:** Are there any workarounds for this kind of situation? Would really like to know those.

**Comment by markerikson** [comment]
Realistically, no, that's not possible (especially at the TypeScript level).

I'd recommend going the "dummy initial state" route here.

**Comment by jnachtigall** [comment]
@cbdeveloper fwiw, I hit the same problem. Option 1 with a dummy initial state that never will be used is what I did, too. It seems to be the only way to make TypeScript happy. So you have double code: initialState (that is only there to make TypeScript happy and otherwise useless) and then the  `preloadedState`. 

Option 2 seems even worse.
