### ISSUE TITLE
Extreme CPU usage while reading the tutorials 

### ISSUE THREAD

**Issue by RayVR** [reduxjs/redux-toolkit#877]
I'm getting 95%+ CPU usage while trying to read through the tutorial. Safari actually warned me the site was using significant resources. I don't see anything on these pages that should cause this so thought it could be a bug. 

This is with Safari 14.0.2 on MacOS 11.1.
Chrome 87.0.4280.141 did not show the same high CPU usage.

**Comment by msutkowski** [comment]
Could you link to the particular page? It's most likely codesandbox

**Comment by RayVR** [comment]
https://redux-toolkit.js.org/tutorials/intermediate-tutorial is one example. The beginner tutorial showed the same issues.

**Comment by LeadProgramming** [comment]
I can barely scroll through the page without it freezing intermittently. I thought my iPhone. Please fix I am still reading 😥

**Comment by markerikson** [comment]
I can only assume this is the CodeSandboxes that are in the page.

FWIW, we're debating removing the existing RTK tutorials, because the new "Redux Essentials" and "Redux Fundamentals" in the core docs do a better job of teaching Redux and RTK.  I'd suggest reading those first:

https://redux.js.org/tutorials/index

**Comment by msutkowski** [comment]
@RayVR @LeadProgramming Can you try looking at the tutorials here and let us know if it helps? https://deploy-preview-880--redux-starter-kit-docs.netlify.app/tutorials/intermediate-tutorial

**Comment by RayVR** [comment]
@msutkowski The linked page resolves the issue.

**Comment by markerikson** [comment]
Cool. Ok, merged that PR.

@msutkowski , could you do me a favor and update all the Redux core sandboxes the same way?
