### ISSUE TITLE
Issues with entityAdapter "getInitialState()" calls within reducers

### ISSUE THREAD

**Issue by yoruvo** [reduxjs/redux-toolkit#878]
Hi,

first of all, thank you for this amazing project, it has made life a lot easier for me.

As seen in the Reactiflux Discord, there is a problem that appears with a specific use case.

If you try to use the RTK `entityResolver` to dynamically create sets of normalized items, you may need to create a new `EntityState` object within your state in a reducer function.  ex.
```ts
// inside a createSlice:
  extraReducers: (builder) => {
    builder
      .addCase(gamesStateActions.createGame, (state, action) => {
        // Initialize new EntityState.
        state[action.payload.game.id] = adapter.getInitialState()
        
        // Get some entities to load into the new state.
        const incomingEntities = [
          action.payload.playerBundle.entityBundle,
          ...action.payload.locationBundle.entityBundles,
        ]

        // Add them!
        adapter.addMany(
          state[action.payload.game.id],
          incomingEntities.map((entityBundle) => entityBundle.entity),
        )
      })
```

However, the `adapter.addMany` call in that reducer will NOT actually add the entities to the state.

It is possible to make this work by changing it to:

```ts
        state[myId] = adapter.addMany(
          state[myId],
          myEntities,
        )
```

However, by design, the adapter should update the state just by calling the function, without assigning it to the variable.

Quotes by phryneas and acemarke in the Discord chat which may be relevant for the solution:

> [...] `entityAdapter` only modifies the state if it's a drafted state and otherwise returns a modified copy

> `adapter.getInitialState` does not return a drafted object, but a native one

> is it that the updater function sees an undrafted state and thinks it's supposed to return a value, not mutate?

**Comment by jameshoward** [comment]
I am trying to do something very similar on a new project and seeing the same issue. The code is (almost) identical to some that I had on a different project that used RTK 1.4, where it worked fine.

**Comment by EskiMojo14** [comment]
Only a few years too late, but the explanation from Lenz/Mark is correct - a [quick test](https://codesandbox.io/p/sandbox/immer-draft-test-5cm6ld) proves that values set into a draft are not themselves wrapped by drafts during the rest of that recipe's execution.
