### ISSUE TITLE
Conditionally cancelled thunk logs error to the console

### ISSUE THREAD

**Issue by eegli** [reduxjs/redux-toolkit#883]
#### Issue description
When generating a thunk action creator via `createAsyncThunk` and passing in a callback to the conditions object, the thunk is cancelled when the condition is met. However, this is done in a way so that an error is thrown, which is logged to the console even though the thunk may have been cancelled on purpose.

```tsx
// src/createAsyncThunk.ts

const promise = (async function() {
  let finalAction: ReturnType<typeof fulfilled | typeof rejected>
  try {
    if (
      options &&
      options.condition &&
      options.condition(arg, { getState, extra }) === false
    ) {
      // eslint-disable-next-line no-throw-literal
      throw {
        name: 'ConditionError',
        message: 'Aborted due to condition callback returning false.'
      }
    }
  }
```

#### Steps to reproduce the issue

1.  Create an async thunk [as in the docs](https://redux-toolkit.js.org/api/createAsyncThunk#canceling-before-execution)
2.  Add a condition to cancel before execution
3.  Dispatch an action that will cancel the thunk
4.  Check your console

#### What's the expected result?
- Although the docs suggest otherwise, I would expect a "rejected" action to be dispatched.

#### What's the actual result?
- An error is thrown and logged to the console.  Yes, this works to stop the execution flow, but it's simply not nice to have these error messages in production. 

#### Additional details
I found this "bug" working with the Spotify API when I wanted to cancel a thunk if some part of the user library is fetched.
- [Live example (requires Spotify login)](https://spotify-api-starter.nougatfactory.com/)
- [Code from live example](https://github.com/eegli/spotify-web-api-starter/blob/master/src/redux/slices/library.slice.ts)

**Comment by phryneas** [comment]
That `throw` is within a `try` block that on `catch` will set `finalAction`. This should lead to a `rejected` action to be returned from the `dispatch` and only finally throwing an error if you `unwrapResult` on it - which is a method with the explicit goal of throwing an error on a rejected action.

**Comment by phryneas** [comment]
And that is exactly what you are doing:
```ts
    const fetchAgain = (url: string) => {
      dispatch(fetchUserSavedTracks(url))
        .then(unwrapResult)
        .then((res) => {
          if (res.next) fetchAgain(res.next);
        });
    };
```

**Comment by eegli** [comment]
My bad, I completely forgot that I was chaining promises *without* catching them, and now that I check it's clearly mentioned in the docs. Thanks a lot for your help.
