### ISSUE TITLE
Only run serializableCheck on actions and not on state

### ISSUE THREAD

**Issue by ksjogo** [reduxjs/redux-toolkit#885]
The serializableCheck is quite valuable, but with our state architecture it often takes up to 100ms for every action of which a lot might be dispatched.
It would be great to have an option to only run the check on the current action and not the whole state.
This seems to be quite easy to add around
https://github.com/reduxjs/redux-toolkit/blob/ba8c911c53e67365499ac00982f640b369360a64/src/serializableStateInvariantMiddleware.ts#L193
Could I create a PR?

**Comment by markerikson** [comment]
Yeah, that seems reasonable.  Please go ahead.

**Comment by phryneas** [comment]
While you're at it: it might also be interesting to skip out of the check if the part of the state is frozen. That will usually be the case with data that was autofrozen by immer, so most of the time the check would be pretty obsolete anyways.

**Comment by markerikson** [comment]
Yeah, would it be worth having the mutation check middleware look for frozen state as well?

I could see that speeding up both of these middleware noticeably, which would actually improve the value.
