### ISSUE TITLE
Action creator from createSlice uses event object as payload

### ISSUE THREAD

**Issue by Oksert** [reduxjs/redux-toolkit#886]
I want to use actionCreator from createSlice without payload. But if I use this action as callback Payload somehow equals Event object

```
const menuReducer = createSlice({
  name: 'menu',
  initialState,
  reducers: {
    openMenu(state, payload) {
      console.log(payload)
      state.open = true;
    },
  },
});
```

```
export const { openMenu} = menuReducer.actions;
import { toggleMenu as _toggleMenu } from '@store/index';
const Example = () => (
     <IconButton onClick={toggleMenu} >
         <Menu />
      </IconButton>
)
const mapDispatchToProps = {
  toggleMenu: _toggleMenu,
};
```
Console.shows
`
payload: Class {dispatchConfig: null, _targetInst: null, _dispatchListeners: null, _dispatchInstances: null, …}`

Example on sandbox. Click test and checkout console https://codesandbox.io/s/rtk-github-issues-example-02-issues-display-forked-zd9es

**Comment by phryneas** [comment]
That is because react calls that click handler with an event as an argument - like it would do with any function passed in at that position. 
If you want to prevent that, you have to `<IconButton onClick={() => toggleMenu()} >`.

**Comment by Oksert** [comment]
Ok.I thought there were more clear way to solve this or maybe there is some practice. Because developer who is unaware of this problem can easily think that this is redundant code and change it back to onClick={toggleMenu}

**Comment by phryneas** [comment]
This is a generic React/Programming problem and has nothing to do with Redux. If you pass a function that accepts argument A into a slot that passes argument B in, you will get B. TypeScript will warn you of this, with pure JavaScript you're pretty much on your own there.

**Comment by Oksert** [comment]
Ok. Thank you for respond
