### ISSUE TITLE
Issue with aborting createAsyncThunk

### ISSUE THREAD

**Issue by Shannor** [reduxjs/redux-toolkit#887]
Hey everyone, I've been using RTK for a while now with no real issues and love where the library is going. Recently I ran into my first need to actually abort a call and tried following the docs however I ended up getting an runtime error saying that 
`Uncaught TypeError: promise.abort is not a function`. I'm on version 1.5.0.

I'm not sure what i could be doing wrong as my code looks like this and follows the tutorial.
```js
const promise = dispatch(
      asnycThunkCall({
        productId: "id",
      }),
    );
  return () => {
    promise.abort();
  };
```

My dispatch is also setup like 
```js
export type AppDispatch = typeof store.dispatch;
export const useAppDispatch = () => useDispatch<AppDispatch>();
```
I tried printing out the promise returned from the dispatch and I didn't see an abort function but I don't know how reliable that is. Any tips?

**Comment by markerikson** [comment]
hmm.  there's certainly _supposed_ to be one there :)  

https://github.com/reduxjs/redux-toolkit/blob/ba8c911c53e67365499ac00982f640b369360a64/src/createAsyncThunk.ts#L463

Can you provide a CodeSandbox that reproduces the issue?

**Comment by Shannor** [comment]
Sure I will make one now! I saw that too so I was confused why I wasn't getting it back.

**Comment by msutkowski** [comment]
That's weird - it's for sure there: https://codesandbox.io/s/rtk-counter-with-abort-tohwm?file=/src/features/counter/Counter.tsx:562-695. _(i've added it to a useEffect as well as in the increment async button handler below)_.

I don't think you're going to be able to reproduce this with a CSB. In your local project, have you tried regenerating a lock file and purging node modules? If you didn't get a TS error, but got a run time error, it seems like it's probably module caching-related? :shrug:

**Comment by Shannor** [comment]
@msutkowski Hmm let me try that. You are correct that I couldn't recreate in the CSB. It worked on there with the same setup. So something must be off with my versions or modules. Thanks let me try that.

**Comment by Shannor** [comment]
@msutkowski I delete my node_modules and package-lock.json. And the issue is still happening. Comparing my promise to the promise in CSB is definitely different. 

In the CSB it looks correct. On my local machine it looks like this
```js

Promise {<pending>}
__proto__: Promise
[[PromiseState]]: "fulfilled"
[[PromiseResult]]: Array(6)
```
Like maybe something is striping the extra fields from it and just returning the raw promise. Any ideas there?

**Comment by markerikson** [comment]
That sounds _extremely_ weird.  Like, to the point of not being possible.

Maybe try throwing some breakpoints or logging into the RTK code in `node_modules` and see what it's stepping through?

**Comment by Shannor** [comment]
Ok trying that now.

**Comment by Shannor** [comment]
I figured it out! Thanks everyone for the help. So I have some custom middleware that I have setup to call before every thunk to auth check the user. It looks like this 
```js
const setTokenMiddleWare: Middleware = () => (next) => async (action) => {
  const needsAuth =
    /:Auth/.test(action.type) || /Auth\/pending/.test(action.type);
  if (!needsAuth) {
    return next(action);
  } else {
    try {
      const token = await auth.getToken();
      if (token) {
        api.setAuthToken(token);
        next(action);
      } else {
        next(actions.notSignedIn());
      }
    } catch (e) {
      next(actions.notSignedIn());
    }
  }
};
```

However, I know it's buggy and there is probably a better and cleaner way to do this. But more importantly it seems this middleware was some how striping information off of the return from `createAsyncThunk`.

**Comment by markerikson** [comment]
Ah, yes, there's two problems there:

- You're not doing `return next()` in the later section, so if the thunk middleware is after this its return value will get ignored
- By making this `async`, it'll return its own promise, which will be different than the one the thunk middleware returns

**Comment by Shannor** [comment]
@markerikson Hmm I see. Do you have a way to handle this pattern? Essentially I want to check the users auth status and get a new token before performing any requests. However, my current implementation always happens after the `createAsyncAction` thunk finishes. Is there a way to model that type of flow? Am I on the right track?

**Comment by markerikson** [comment]
Not sure - I'd really need to see this in action.

**Comment by Shannor** [comment]
That's fair. I did your above changes and things are working now as expected. I'll play around more to see if I can better fine tune it. Thanks again for the help I really appreciate it!
