### ISSUE TITLE
Bump immer dependency version to 8.0.1

### ISSUE THREAD

**Issue by koriner** [reduxjs/redux-toolkit#890]
There is a current npm vulnerability for immer which is giving us warnings. Would it be possible to bump the version of immer?

Related patch on immer: https://github.com/immerjs/immer/commit/da2bd4fa0edc9335543089fe7d290d6a346c40c5

**Comment by markerikson** [comment]
We already depend on `immer@^8.0.0`, so you just need to update your own installation.  

Dupe of #871, #874, #879 .
