### ISSUE TITLE
[Docs] Should variable name for inital state be "initialState" only?

### ISSUE THREAD

**Issue by surpriso1997** [reduxjs/redux-toolkit#891]
Problem: 
If the initial State param is named anything other than 'initialState' typescript gives this error:

```
Argument of type '{ name: string; initState: state; reducers: { a(s: any, action: { payload: state; type: string; }): void; b(s: any, action: { payload: state; type: string; }): void; }; }' is not assignable to parameter of type 'CreateSliceOptions<any, SliceCaseReducers<any>, string>'.
  Object literal may only specify known properties, and 'initState' does not exist in type 'CreateSliceOptions<any, SliceCaseReducers<any>, string>'.
```

Example:
I have created this simple slice. Here the variable name for initial state is initState and typescript shows the  error above. 
```
import { createSlice, PayloadAction, Slice } from "@reduxjs/toolkit";


interface state { name: string };

interface actionData{id:number}

let initState: state = { name: 'this' };

const Test: Slice = createSlice({
    name: "TestSlice",
    initState,
    reducers: {
        a(s, action: PayloadAction<actionData>) {
            console.log(s);
        },
        b(s, action: PayloadAction<actionData>) {
            console.log(s);
        }
    }
});

export default Test.reducer;

```

Docs say that ```The state type is based on the type of the initialState field```. But it does not mention that it has to be "initialState" only. 
I am a beginner in redux toolkit and typescript in general and I was wondering why it worked when I copied and pasted the example code and my example above did not work. 
 I was more confused when I hovered over the initialState variable in vscode and it gave proper type description :
```CreateSliceOptions<state, { a(s: any, action: PayloadAction<state>): void; b(s: any, action: PayloadAction<state>): void; }, string>.initialState: state```

while initState in my example gave the error message.

**Comment by phryneas** [comment]
If you put Diesel into a Gasoline car, it will break down. 
These are options with names, you cannot call the `reducers` option `funnyFunctions`, you cannot cann `name` `nomNom` and as well you cannot give a new name to `initialState`.

In your code, you can name it whatever you want, but every documented option to any of our APIs has to be that name. There is no guessing, not with our APIs nor with anyone elses.

So if you want to call it `initState`, you can do

```js
let initState: state = { name: 'this' };

const Test: Slice = createSlice({
    name: "TestSlice",
    initialState: initState,
    reducers: {
        a(s, action: PayloadAction<actionData>) {
            console.log(s);
        },
        b(s, action: PayloadAction<actionData>) {
            console.log(s);
        }
    }
});

```

**Comment by surpriso1997** [comment]
@phryneas  I didn't know initalState was a named parameter. Now I can see in type file that initalstate is a variable in CreateSliceOptions interface. Coming from other  languages I forgot that  {intialState: initialState  }  can be written as only {initialState } in js and ts. Thanks for the quick reply.
