### ISSUE TITLE
Performance issues when saving big data

### ISSUE THREAD

**Issue by santosjs** [reduxjs/redux-toolkit#893]
Hi all! I have a question about performance.

In my project, when I save the data with 10k objects to store with entitiyAdapter, it all starts to freeze on any other change that does not concern this object. 

Is it a bad practice to save that large data to store? or am I doing something wrong?

I have an example to recreate this - [Sandbox example](https://codesandbox.io/s/frosty-hopper-e4hjs?file=/src/Example.js)

Thanks!

**Comment by msutkowski** [comment]
In this case, you could set `immutableCheck: false` in the middleware config and that'll go away: https://codesandbox.io/s/compassionate-hermann-w0376?file=/src/App.js:227-307.

Note: this is disabled by default in production, so you don't have to worry about it there.

**Comment by santosjs** [comment]
Thanks a lot. It's very helpful. I found in the [docs](https://redux-toolkit.js.org/api/immutabilityMiddleware) that there are some additional options for this
