### ISSUE TITLE
Exporting 'createAsyncThunk' actions for use in different slices

### ISSUE THREAD

**Issue by JoeVanGundy** [reduxjs/redux-toolkit#894]
In the following example, how do I get the action ` getUserInfo.fulfilled ` in another slice?

```

const getUserInfo= createAsyncThunk(
  'users/getUserInfo',
  async (userId, thunkAPI) => {
  }
)

const usersSlice = createSlice({
  name: 'users',
  initialState: { },
  reducers: {},
  extraReducers: {
    [getUserInfo.fulfilled]: (state, action) => {}
  }
})

```

I need to be able to do something like:

```


const otherSlice = createSlice({
  name: 'otherSlice',
  initialState: { },
  reducers: {},
  extraReducers: {
    [users.getUserInfo.fulfilled]: (state, action) => {
        # Do something in this state with the result of getUserInfo
     }
  }
})

```

My first thought was to just export those action names, but I read in the docs that they are not available to be exported (at least automatically).

The only solution I can think of is to stop using extraReducers and just manually dispatch started, success and failure in the thunk. (As a side note, I also had the same problem of not being able to get the action types when I was going to test my code).

I love how little code `extraReducers` requires, but I can't for the life of me figure this out.
Am I going about this wrong?

**Comment by msutkowski** [comment]
Hi @JoeVanGundy ,

Being that you're sharing the `createAsyncThunk` between multiple slices, you should put it into a common file to eliminate circular import issues. Then you can: 


```ts
// userSlice.js
import { getUserInfo } from './common';

const usersSlice = createSlice({
  name: 'contactInformation',
  initialState: { },
  reducers: {},
  extraReducers: builder => {
    builder.addCase(getUserInfo.fulfilled, (state, action) => {
        console.log(action.payload);
     }
  }
})

// otherSlice.js
import { getUserInfo } from './common';

const otherSlice = createSlice({
  name: 'otherName',
  initialState: { },
  reducers: {},
  extraReducers: builder => {
    builder.addCase(getUserInfo.fulfilled, (state, action) => {
        console.log(action.payload);
     }
  }
})
```

**Comment by JoeVanGundy** [comment]
Thanks for quick reply @msutkowski!
I had just discovered that action types actually exist in the getUserInfo object (at `getUserInfo.fulfilled.type`).

I'm in the process of refactoring our codebase to use Redux Toolkit so some of the reducers still need the actual string to use in the switch statement.

Just to double check, as long as there are no circular dependencies, there no problem of having something like this right?

```

import { getUserInfo } from './usersSlice';

...
export default function oldReducer(state = initialState, action) {
  switch (action.type) {
    case getUserInfo.fulfilled.type:
      return {
        ...state,
        loading: true,
        loaded: false,
      };
...
```

**Comment by msutkowski** [comment]
Nope, that'll work just fine :+1:

**Comment by JoeVanGundy** [comment]
@msutkowski
Perfect! Thanks so much! 😄
