### ISSUE TITLE
Docs - add info about builder matcher global scope

### ISSUE THREAD

**Issue by EmilMalanczak** [reduxjs/redux-toolkit#897]
Hey, 

Recently I've run into strange bug based on builder matchers. 
After doing thunk action created with `createAsyncThunk` with `typePrefix: 'x/something',` my user object was dissapearing in despite of that it is located in slice `'y'`. 

Problem was located in builder matcher. 
In slice `'y'` I have 2 different thunks that are doin almost the same so I've added a matcher with helpers `isFulfilled isRejected isPending` from `redux-toolkit` to reduce unnecessary code. 

After invoking actions from thunk `'x/something'` matchers in slice `y` were passing which caused to overwrite data in slice `y`. However in devtools history of invoked actions were showing only actions with prefix `x` but after looking into state differences 2 slices were affected.

In docs there is no information that the builder matchers are globally scoped. It was a bit confusing to find but luckily I didn't have to deal with a big store. Currently the only information that might help in docs is:

`Redux Toolkit exports several type-safe action matching utilities that you can leverage when checking for specific kinds of actions. These are primarily useful for the builder.addMatcher() cases in createSlice and createReducer, as well as when writing custom middleware.`

but still that is not so straightforward.

**Comment by phryneas** [comment]
Hm. Actually, I believe there is no documentation at all that would imply that it is possible to use the matchers without an argument at all - so we probably should add that.

In general though: there is never any connection between the name of a slice and any `extraReducers`. The point of `extraReducers` is to interact with stuf that is "external to the slice" and all of our documentation shows to use `asyncThunk.fulfilled` or `asyncThunk.fulfilled.match`.

The documentation of the matcher utilities at the moment states that all action matchers should be called with one or more actions/thunks as argument. So at least from reading the docs, I can't really see how you might have come to the conclusion you had there - aside from just blindly trying "something".

**Comment by EmilMalanczak** [comment]
I mean docs are written pretty well and intuitively.  

I get the point now, I'm new to toolkit so forgive me 😜 

https://redux-toolkit.js.org/usage/usage-with-typescript#type-safety-with-extrareducers

By reading that fragment from docs I got feel like these matchers are working around specfic slice that the extraReducers were attached, not on whole store. Probably my bad 🤷 

If you want to state for using one or more action maybe it's a point to consider change types to require at least 1 action ? My typescript wasn't complaining at all about that so I think that's a good point

**Comment by markerikson** [comment]
I'm going to close this because I'm not quite sure exactly what content is worth adding. If you or someone else would like to improve the docs, please go ahead and file a PR to do so. Thanks!
