### ISSUE TITLE
Mutating state via Array.prototype.concat does not produce a state change

### ISSUE THREAD

**Issue by TheWirv** [reduxjs/redux-toolkit#899]
Hi, I am not sure whether this is an issue with RTK or `immer` (I suppose would be the next best guess), but I just wanted to call to attention that there's a problem with using `concat` on an array inside of a case reducer.

The following two code snippets don't produce the same results although they are semantically identical:

```typescript
const someCaseReducer = (state) => {
  // Does not result in a state change
  state.someArray.concat(someNewArray);
}
```

```typescript
const someCaseReducer = (state) => {
  // This does however work perfectly, and results in a state change
  state.someArray.push(...someNewArray);
}
```

**Comment by phryneas** [comment]
`.concat` is a non-mutating option: https://doesitmutate.xyz/concat/

**Comment by TheWirv** [comment]
🤦🏼  You're right, that was my own stupidity and ignorance, sorry.
