### ISSUE TITLE
Consider exporting `miniSerializeError`

### ISSUE THREAD

**Issue by joekrill** [reduxjs/redux-toolkit#902]
Has there been any consideration to exporting the `miniSerializeError` implementation that `createAsyncThunk` uses? I've run into a few cases where it could be useful to use outside of async thunks. It's obviously trivial to recreate/copy the implementation, but seems like it could be a useful thing to include in the "Other exports". I'm happy to get a PR in for it (+ docs) if it's something that would be considered.

**Comment by markerikson** [comment]
Yeah, I think this is something we could do in 1.6.  Could you file that PR?
