### ISSUE TITLE
Follow the official Redux example and report an error using @Redux JS/Toolkit

### ISSUE THREAD

**Issue by VitaminCtea** [reduxjs/redux-toolkit#904]
Uncaught TypeError: Cannot read property 'ids' of undefined    state_selectors.ts:12
The above error occurred in the <Navbar> component
Uncaught TypeError: Cannot read property 'ids' of undefined

The above is error message!

I try to click on the first message, jump to the source code and find the error is: const selectIds = (state: any) => state.ids

I didn't know what was going on, I was following the code on the website step by step. After the error occurred, I carefully compared the code in the sandbox and found no error, but now there is an error, causing the program to not run.

I don't know how to solve this, first time using @reduxjs/tookit library

**Comment by VitaminCtea** [comment]
Here's the code for postsSlice.js:

import { createSlice, createAsyncThunk, createSelector, createEntityAdapter } from '@reduxjs/toolkit'

import { client } from '../../api/client'

const postsAdapter = createEntityAdapter({
    sortComparer: (a, b) => b.date.localeCompare(a.date)
})

const initialState = postsAdapter.getInitialState({
    status: 'idle',
    error: null
})

export const fetchPosts = createAsyncThunk('posts/fetchPosts', async () => {
    const response = await client.get('/fakeApi/posts')
    return response.posts
})

export const addNewPost = createAsyncThunk('posts/addNewPost', async initialPost => {
    const response = await client.post('/fakeApi/posts', { post: initialPost })
    return response.post
})

const postsSlice = createSlice({
    name: 'posts',
    initialState,
    reducers: {
        reactionAdded(state, action) {
            const { postId, reaction } = action.payload
            const existingPost = state.entities[postId]
            if (existingPost) existingPost.reactions[reaction]++
        },
        postUpdated(state, action) {
            const { id, title, content } = action.payload
            const existingPost = state.entities[id]
            if (existingPost) {
                existingPost.title = title
                existingPost.content = content
            }
        }
    },
    extraReducers: {
        [ fetchPosts.pending ]: (state, action) => {
            state.status = 'loading'
        },
        [ fetchPosts.fulfilled ]: (state, action) => {
            state.status = 'succeeded'
            postsAdapter.upsertMany(state, action.payload)
        },
        [ fetchPosts.rejected ]: (state, action) => {
            state.status = 'failed'
            state.error = action.payload
        },
        [ addNewPost.fulfilled ]: postsAdapter.addOne
    }
})

export const { postAdded, postUpdated, reactionAdded } = postsSlice.actions

export default postsSlice.reducer

export const { 
    selectAll: selectAllPosts, 
    selectById: selectPostById, 
    selectIds: selectPostIds 
} = postsAdapter.getSelectors(state => state.posts)

export const selectPostsByUser = createSelector(
    [ selectAllPosts, (state, userId) => userId ],
    (posts, userId) => posts.filter(post => post.user === userId)
)


Here's the code for usersSlice.js:

import { createSlice, createAsyncThunk, createEntityAdapter } from '@reduxjs/toolkit'
import { client } from '../../api/client'

const usersAdapter = createEntityAdapter()

const initialState = usersAdapter.getInitialState()

export const fetchUsers = createAsyncThunk('users/fetchUsers', async () => {
    const response = await client.get('/fakeApi/users')
    return response.users
})

const usersSlice = createSlice({
    name: 'users',
    initialState,
    reducers: {},
    extraReducers: {
        [ fetchUsers.fulfilled ]: usersAdapter.setAll
    }
})

export default usersSlice.reducer

export const { selectAll: selectAllUsers, selectById: selectUserById } = usersAdapter.getSelectors(state => state.users)


Here's the code for notificationsSlice.js:

import { createSlice, createAsyncThunk, createEntityAdapter } from '@reduxjs/toolkit'

import { client } from '../../api/client'

const notificationAdapter = createEntityAdapter({
    sortComparer: (a, b) => b.date.localeCompare(a.date)
})

export const fetchNotifications = createAsyncThunk('notifications/fetchNotifications', async (_, { getState }) => {
    const [ latestNotification ] = selectAllNotifications(getState())
    const latestTimestamp = latestNotification ? latestNotification.date : ''
    const response = await client.get(`/fakeApi/notifications?since=${ latestTimestamp }`)
    return response.notifications
})

const notificationsSlice = createSlice({
    name: 'notifications',
    initialState: notificationAdapter.getInitialState(),
    reducers: {
        allNotificationsRead(state, action) {
            Object.values(state.entities).forEach(notification => notification.read = true)
        }
    },
    extraReducers: {
        [ fetchNotifications.fulfilled ]: (state, action) => {
            Object.values(state.entities).forEach(notification => notification.isNew = !notification.read)
            notificationAdapter.upsertMany(state, action.payload)
        }
    }
})

export const { allNotificationsRead } = notificationsSlice.actions

export default notificationsSlice.reducer

export const { selectAll: selectAllNotifications } = notificationAdapter.getSelectors(state => state.notifications)

**Comment by phryneas** [comment]
The problem is likely you not passing the reducer into `createStore`, nothing directly in the reducers. But this is really a usage question that belongs to StackOverflow, not into out issues as these are mainly for bug reports.  
So please open an issue there if you cannot figure it out, but please make sure to format your code correctly there.
