### ISSUE TITLE
Throw error on rejection

### ISSUE THREAD

**Issue by Fiorello** [reduxjs/redux-toolkit#910]
Hi, I'm migrating my application from redux-thunk + redux-promise-middleware to redux-toolkit.

I have a problem that I cannot solve that concerns throwing the error in an asynchronous action.

The main difference with redux-promise-middleware is that if an error is generated in an asynchronous action, it dispatches the failed action and at the same time does not stop the error throw.
On the redux-toolkit instead the action is only rejected.
Reading the various issues on redux-toolkit, I deduced that adding the serializeError option and throwing the error, I did also receive the error on the dispatch of the action, however the reject action is not performed.

I'm going to write some code to explain the context:

```
class PostContainer extends React.Component {
  public componentDidMount() {
    try {
      this.props.preload();
    } catch(err) {
      console.log(err);
      // i'd like to receive here the error
    }
  }
}

const mapDispatchToProps = (dispatch: any) => ({
  preload() {
    await dispatch(preload());
    dispatch(somethingelse())
  }
});

export default connect(null, mapDispatchToProps)(PostContainer);

// action
const preload = createAsyncThunk('post/preload', async (_: void, { dispatch }) => {
  // if one of this two action throw an error
  await dispatch(getPosts());
  await dispatch(getUsers());
});

expost const postSlice = createSlice({
  name: 'post',
  initialState,
  reducers: {},
  extraReducers: (builder) => {
    // i'd like to receive the rejected action
    builder.addCase(prealod.rejected, (state, action) => {
      return {
        ...state,
        isError: true
      }
    })
  }
})

````

Is there a way to achieve this with redux-toolkit?
Maybe should i use the `unwrapResult` utility?
If this is the case, how can i implement in this scenario?
Thanks for you time.

**Comment by markerikson** [comment]
Yeah, I think you want `await dispatch(getPosts()).then(unwrapResult)`.  That should throw if the request failed and the thunk rejected.  In turn, throwing an error inside of `preload` will cause _it_ to reject as well.

**Comment by Fiorello** [comment]
It seems that in order to work I need to add unwrapResult to all dispatches in this case.

```
const preload = createAsyncThunk('post/preload', async (_: void, { dispatch }) => {
  await dispatch(getPosts()).then(unwrapResult);
  await dispatch(getUsers()).then(unwrapResult);
});

const mapDispatchToProps = (dispatch: any) => ({
  preload() {
    await dispatch(preload()).then(unwrapResult);
    dispatch(somethingelse())
  }
});
```
My entire application works like this, so I should add it everywhere.
It turns out really awkward and ugly to read.

**Comment by markerikson** [comment]
Agreed that it's not terribly pretty if you have to add that in a bunch of spots.

FWIW, these threads have prior discussion on the topic: #734, #775 , and #792 .  In particular, #792 has a lot of design discussion related to this, such as https://github.com/reduxjs/redux-toolkit/pull/792#issuecomment-722710316 .

**Comment by Fiorello** [comment]
Ok, thanks for you time. ;)

**Comment by tribou** [comment]
Just wanted to thank you both for opening this issue and compiling those prior discussion threads around this topic. I hit the same migration issue until I realized I didn't completely understand `unwrapResult`.

**Comment by tribou** [comment]
I may have found a limitation when using the `condition` option along with this pattern of `unwrapResult`ing the async thunks.

If you `unwrapResult`, then the `dispatchConditionRejection` appears to be permanently `true`. Is this intentional? If so, I suppose there's not a pattern to:

- Prevent concurrent thunks/etc. using `condition` while
- Using try/catch to catch async errors?

I hacked together a naive example here: https://codesandbox.io/s/unwrap-createasyncthunk-with-failed-condition-pmdq6

If you click the Increment button while it is incrementing, it will throw the ConditionError in the console. I'm eager to hear if there's a workaround that I may have missed.

**Comment by phryneas** [comment]
@tribou while that rejected action is not dispatched, it *is* returned from the asyncThunk, as the asnycThunk has to return *something* and that "something" can either be a fulfilled action or a rejected action. Using a fulfilled action with an empty payload would be quite weird, so it *has* to be a rejected action. And putting a rejected action into `unwrapResult` will lead to an error being thrown.

So you probably need to wrap some kind of own logic around that if you want to act differently on that.

**Comment by tribou** [comment]
Thank you for that input. I agree that would be an unwanted case to have to add to RTK.

I did find a solution that restores my expected use case of 1) throwing errors by default after dispatching rejections and 2) ignoring `ConditionError`--appending this middleware after the RTK default middleware:

```ts
import { Middleware } from "@reduxjs/toolkit";

export const throwMiddleware: Middleware = () => (next) => (action) => {
  next(action);
  if (action?.error) {
    throw action.error;
  }
};
```

With this in place, I no longer need to `.then(unwrapResult)` everywhere which, in turn, ignores `ConditionError`s.
