### ISSUE TITLE
Is it impossible to use Partial Payload?

### ISSUE THREAD

**Issue by silphir** [reduxjs/redux-toolkit#913]
👋 Hello~!
I like this toolkit, because it makes easy to use redux! 

I have a question with using `createAction` with `Partial payload`.

I use toolkit with `redux-observable` middleware, and I use payload to use async function's args.
But it occur type error like below.

```ts
type ActionPayloadType = {
  foo?: string;
  bar?: string;
} // <- all optional. Like Partial<T>

const tempAction = createAction<ActionPayloadType>('FETCH_ASYNC');
// tempAction type: ActionCreatorWithNonInferrablePayload<string>

const tempEpic = actions$.pipe(
  filter(tempAction.match),
  mergeMap(({ payload: { foo, bar }}) => fetchAsync(foo, bar).pipe(
//                       ^^^  ^^^ type error: payload type is unknown
    ...
  ),
);
```

Am I using wrong?
Or is there any way to use all optional(or Partial) payload like `ActionCreatorWithOptionalPayload`?

**Comment by phryneas** [comment]
I would assume that works [this example does](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMZQKYEMaoIJJsCAOwF84AzKCEOAcgAE0ATAVwA8ArAZwHoYIIANgGtgMGgChxMAJ5hUcXPiIAFdNIER0jACqz5AXkTi45fgH4AXHE4wowQgHMA3MbgAjdFEvXb95+NJubjgAHgBaOHQBATgIMCVCKIA6OAAZYCF5VVhgKJDtAD5JJCIbOCxwRQJCOEMUDCwqohCmwlV1TR09AoAKGgAxAFFtAGEACQB9bABlAE0AORGaAEoXIPLUSrxq8r0rVpG0TGgAdVEAC3miAElCMlQoKHQ3AVR2jS0QmztHIvESwhldDbIhWdCEaS1RAyORWABEAiiSLhxEkwDIcB6FTArSSIEwSHOPWBCWWyyMJgBnEEqCSGgcxJBhCSYDUH0YSQ8UGWASAA) but I'm not a rxjs user, so I'm not sure if you applied the filter correctly.

**Comment by silphir** [comment]
@phryneas Thanks for check!
In my case, `tempAction`'s type is `ActionCreatorWithNonInferrablePayload<string>`.

![image](https://user-images.githubusercontent.com/18396998/109790493-d1917500-7c54-11eb-9f52-e6bab0e065af.png)
![image](https://user-images.githubusercontent.com/18396998/109790938-3e0c7400-7c55-11eb-9d54-6b6dd86d80c8.png)

I saw yours example and I've done with typescript playground like yours, but `tempAction`'s type is `ActionCreatorWithPayload<ActionPayloadType, string>`.

![image](https://user-images.githubusercontent.com/18396998/109791356-b4a97180-7c55-11eb-8872-5ce31d505a0a.png)

i don't know why two things are different.. 😢
I am using `typescript@4.1.3` and `@reduxjs/tookit@1.5.0`.

**Comment by phryneas** [comment]
That is just WebStorm being WebStorm unfortunately. They give you a "quick view" of the types that doesn't match the real types at all. Ther is some key combination to actually show the real types, which should be correct.

**Comment by silphir** [comment]
Oh I'm sorry... This is vscode using Webstrom darcula theme... 😭

**Comment by phryneas** [comment]
Hmm... do you have `strict: true` in your `tsconfig.json`? Not being on strict mode is known to cause problems sometimes.

**Comment by silphir** [comment]
I've not used `strict: true`. That's why it happened... 
I've been using typescript incorrectly... 😭 

I'm sorry to waste your time even though it's not a redux-toolkit issue.
Thanks~!

**Comment by markerikson** [comment]
no worries :)
