### ISSUE TITLE
export Original was not found

### ISSUE THREAD

**Issue by emanual4real** [reduxjs/redux-toolkit#916]
[Documentation](https://redux-toolkit.js.org/usage/immer-reducers#debugging-and-inspecting-drafted-state) says that original is exported but isDraft is not.  When I attempt to use original, I get the below error:
`"export 'original' was not found in '@reduxjs/toolkit'`

minimum code is something like this:
```
import { createSlice, current, original } from '@reduxjs/toolkit';
...

export const reportSlice = createSlice({
  name: 'report',
  initialState: {
   ...
  },
  reducers: {
    filterWhere: (state, action) => {
      console.log('current(state)', current(state));
      console.log('original(state)', original(state));
    },
  },
});

**Comment by markerikson** [comment]
Yeah, my bad. It _is_ in there on `master`, but it hasn't been released yet.

I'll update the docs page accordingly.

**Comment by markerikson** [comment]
Docs updated, should be published in a couple minutes.
