### ISSUE TITLE
Is it possible to type action payloads?

### ISSUE THREAD

**Issue by badsyntax** [reduxjs/redux-toolkit#921]
Here's a simple usecase, pulled from https://redux-toolkit.js.org/usage/usage-with-typescript#createslice:

```ts
type State = number;

const increment: CaseReducer<State, PayloadAction<number>> = (state, action) =>
  state + action.payload

const exampleSlice = createSlice({
  name: 'test',
  initialState: 0,
  reducers: {
    increment
  }
});
exampleSlice.actions.increment('a string') // no type error on the action payload
```

**Comment by phryneas** [comment]
You are not calling an action, but are directly calling your case reducer in that example

**Comment by badsyntax** [comment]
Apologies, i have updated the example.

**Comment by phryneas** [comment]
Just saw the edit: this *does* give an error, check it [in this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQZQDbDJoA0cAwhgM5oBKaAJgK5FSkAKGAnnhBvQILIYwCADs4AXzgAzKBBBwA5AAF0TAB4ArSgHoYECHgDWwGIoBQ5mJzBo4OGFjsBeOKMYgARmigBuS8hilPDAoqhoIGiiMABc5FS0DMw+ADwOTuxcPHyCwmIp7l4+AHzFcK4AFMEZcBhCIqIAlOXF5nBw1dhwANS19WIAdGBZvPQBQfBo6hjgeLgEROUo6E74hGgVCG1uM2hxitjBisTboabAGHjp2HEADCftaslQlHFb7e2h4ZHR2xLmEka-imMzAczWRAGdTyokoAy+6B+MAqigwHRgUFCAHNFM0dDo3BA4NZbHAfHIoHAxMSABZ2aENODDbijIA)

Your TypeScript setup might be screwed up in some way.

**Comment by badsyntax** [comment]
Interesting, many thanks. I will do some research as to why i'm not getting typed action payloads, and will update and close this issue once i've figured it out.

**Comment by phryneas** [comment]
Just as a hint: Check your IDE. If it's IntelliJ/WebStorm, that's probably the reason. They do not use the TypeScript compiler for most of their type hints, but a "faster approximation", which really does not work out well.

**Comment by badsyntax** [comment]
I have figured it out. I was defining the `State` and `CaseReducers` types when creating my slice:

```ts
const userSlice = createSlice<
  UserStateSlice,
  SliceCaseReducers<UserStateSlice>
>({...})
```

Removing those types fixes things. I can't remember _why_ i added those types. 

Thanks again for validating this!

**Comment by badsyntax** [comment]
(About your previous comment, I'm using vscode and have set the `typescript.tsdk` to use the local typescript compiler.)

**Comment by phryneas** [comment]
> I have figured it out. I was defining the `State` and `CaseReducers` types when creating my slice:
> 
> ```ts
> const userSlice = createSlice<
>   UserStateSlice,
>   SliceCaseReducers<UserStateSlice>
> >({...})
> ```
> 
> Removing those types fixes things. I can't remember _why_ i added those types.
> 
> Thanks again for validating this!

Yes, you should *never* provide generic attributes to `createSlice`. You would need to re-type the whole slice essentially twice with no benefit at all - and mask errors as seen here.
