### ISSUE TITLE
Promote hooks pattern around redux-actions

### ISSUE THREAD

**Issue by jaimefps** [reduxjs/redux-toolkit#923]
I personally enjoy the composition pattern from react-hooks. I think it's a better approach for simpler and more declarative code, compared to the class component paradigm.

However, when using @reduxjs/toolkit, we often have to write a bit too much boilerplate to be able to combine redux-actions with react-hooks. Particularly there is a lot of repetition around `useDispatch` and `useCallback` for each action that should be accessed within other hooks or components. 

So for example, we end up having the following boilerplate:

```
const { createAction } from '@reduxjs/toolkit';
const { useDispatch, useCallback } = 'react-redux';

type MyType = { some: string };
const action = createAction<MyType>('ACTION_TYPE');

/**
 * So much boilerplate!
 */
const useMyAction = () => {
  const dispatch = useDispatch();
  return useCallback((params: MyType) => {
      return dispatch(action(params), [dispatch]);
  });
}

const MyComponent = () => {
  const action = useMyAction();
  return <button onClick={myAction}>click</button>
}
```

I've started using the following helper factory to easily generate react-hooks for my redux-actions:

```
const { createAction } from '@reduxjs/toolkit';

export const createActionHook = <P>(actionCreator: ReturnType<typeof createAction>) => () => {
  const dispatch = useDispatch();
  return useCallback((payload: P) => dispatch(actionCreator(payload)), [dispatch]);
};
```

The previous code would now look like this:

```
const { createAction } from '@reduxjs/toolkit';
const { createActionHook } = './path/to/helpers';

type MyType = { some: string };
const action = createAction<MyType>('ACTION_TYPE');
const useMyAction = createActionHook<MyType>(action);

const MyComponent = () => {
  const action = useMyAction();
  return <button onClick={myAction}>click</button>
}
```

From what experimentation I have done, this continues to work and provide sufficiently strong type inference in all three cases:
- actions with payload
- action with no payload
- actions generated via the prepareAction callback

Would something like this be worth having as a native solution in @reduxjs/toolkit?

**Comment by phryneas** [comment]
Something like that would be part of `react-redux`, not `@reduxjs/toolkit`.

It was actually considered and decided against - you can [read up on it in the context of this post](https://github.com/reduxjs/react-redux/issues/1252#issuecomment-488170883).

Instead it ended up as a recipe in the docs, ready for everyone to copy/paste into their codebase: https://react-redux.js.org/api/hooks#recipe-useactions
