### ISSUE TITLE
Is there anyway to have autocomplete with Javascript ?

### ISSUE THREAD

**Issue by RigottiG** [reduxjs/redux-toolkit#927]
When creating an action, with javascript, is there any way to have autocomplete when using Javascript in the moment at called ?

```javascript
import { createSlice } from '@reduxjs/toolkit'

const counterSlice = createSlice({
  name: 'counter',
  initialState: 0,
  reducers: {
    increment: (state, {payload: { quantity } }) => state + quantity,
  },
})

export { increment } = counterSlice.actions

increment( { quantity: 10 } ) // Here the autocomplete should appear
```

**Comment by markerikson** [comment]
This really requires TypeScript to get proper intellisense, sorry.

**Comment by phryneas** [comment]
You can try to work a bit with jsdoc though:

```js
const counterSlice = createSlice({
  name: 'counter',
  initialState: 0,
  reducers: {
    increment: (
      state, 
      /**  @param action {import('@reduxjs/toolkit').PayloadAction<{quantity: number}>} */
      {payload: { quantity } }
    ) => state + quantity,
  },
})
```

but no guarantee if that will work as this

**Comment by johnemau** [comment]
> You can try to work a bit with jsdoc though:
> 
> ```js
> const counterSlice = createSlice({
>   name: 'counter',
>   initialState: 0,
>   reducers: {
>     increment: (
>       state, 
>       /**  @param action {import('@reduxjs/toolkit').PayloadAction<{quantity: number}>} */
>       {payload: { quantity } }
>     ) => state + quantity,
>   },
> })
> ```
> 
> but no guarantee if that will work as this

The above worked for me ✅
