### ISSUE TITLE
Incorrect error: "A state mutation was detected inside a dispatch"

### ISSUE THREAD

**Issue by ledeneveugene** [reduxjs/redux-toolkit#929]
I am trying to save the uploaded file object link to the storage, but as I guess detectMutation function works incorrectly and I get an error.

![err1](https://user-images.githubusercontent.com/51231845/111610916-ee00e600-87ec-11eb-9eb3-25567f9883de.png)
![err2](https://user-images.githubusercontent.com/51231845/111611800-e55cdf80-87ed-11eb-9ca0-1820e9cc18c1.png)
![err3](https://user-images.githubusercontent.com/51231845/111611796-e4c44900-87ed-11eb-8680-7ef2fa461b84.png)

**Comment by markerikson** [comment]
`File` objects are, as far as I know, not fully serializable and shouldn't go into the store. Similarly, note that the error here is pointing to a real `Date` instance, which really shouldn't go into the store either:

https://redux.js.org/style-guide/style-guide#do-not-put-non-serializable-values-in-state-or-actions

If you _really_ want to turn off those checks, you can:

- https://redux-toolkit.js.org/api/getDefaultMiddleware#customizing-the-included-middleware
- https://redux-toolkit.js.org/api/immutabilityMiddleware#options

Also, as a side note, you can simplify that reducer logic considerably by switching to RTK's `createSlice`:

https://redux.js.org/tutorials/fundamentals/part-8-modern-redux#using-createslice
