### ISSUE TITLE
An intermediate tutorial

### ISSUE THREAD

**Issue by blueskybreeze** [reduxjs/redux-toolkit#933]
Your docs has a really simple counter increment and decrement example

https://redux-toolkit.js.org/tutorials/quick-start

and then there is a super long 

https://redux-toolkit.js.org/usage/usage-guide

that talks about fetching data that is as difficult as building a rocket.  I can understand some parts of relativity and quantum mechanics, yet I cannot understand this guide. It is one of the most difficult programming writing I have ever read, and I have 25+ years of programming experience. And I am just trying to understand the part about fetching data but nothing more.

If it is done by jQuery, it is a few lines, and if done by React, a little bit more complicated but very understandable.

On the Usage Guide, the line

```js
const fetchUsers = () => async dispatch => {
```

does that block of code already fetch data and can display on screen? There is no Demo.
And then the following section "Redux Data Fetching Patterns" -- is it just to explain the previous block of code?
I find it very confusing. It has `getRepoDetailsStarted`?  What Repo? First we have users and now Repo? How are they related?
And then the "Async Requests with createAsyncThunk" section... and now the reducer code is all empty... is it supposed to be empty? And now there is `extraReducers`... what in the world is going on? We are getting some data to display on the page. How come it sounded like Big Bang and Black Hole and Worm Hole?

There is a big gap there.  What is so simple to do in React, is **so** difficult to do in Redux Toolkit.

Can you give an intermediate tutorial, with some simple instructions to:

1. Fetch data from https://jsonplaceholder.typicode.com/users using `fetch()`, and then print a table in a the webpage

2. Have an increment and decrement button, and fetch https://jsonplaceholder.typicode.com/users/1 or 2, or 3, as appropriate? Button should be disabled if it cannot be decremented or incremented. (10 users in the DB).

That's it.  Can you give such a tutorial as opposed to jumping from a simple counter to a mind blogging mini-book tutorial just to fetch some data?

**Comment by phryneas** [comment]
Have you by any chance looked at the tutorials overview and taken a look at the other two tutorials linked there?
https://redux-toolkit.js.org/tutorials/overview

**Comment by markerikson** [comment]
Yeah, the "Usage Guide" is explicitly _not_ a "tutorial".  The "Tutorials" page links to the real tutorials, which are actually over in the Redux core docs, and cover everything you need to know to get started with RTK.

**Comment by blueskybreeze** [comment]
> https://redux-toolkit.js.org/tutorials/overview

Do you mean the Redux Toolkit Quick Start tutorial
and the TypeScript Quick Start tutorial?

The first one is the counter example.  It basically just mentioned "do this, do this, do that" and it will work, but still, I can try to understand it as to how it works in the Redux's way.

The second one... I cannot read, because I don't use TypeScript.  And I hate to read something by guessing.  It also doesn't talk about fetch either.

**Comment by blueskybreeze** [comment]
> Yeah, the "Usage Guide" is explicitly _not_ a "tutorial". The "Tutorials" page links to the real tutorials, which are actually over in the Redux core docs, and cover everything you need to know to get started with RTK:
> 
> * https://redux.js.org/tutorials/essentials/part-1-overview-concepts
> * https://redux.js.org/tutorials/fundamentals/part-1-overview

So can you have a tutorial about one step higher difficulty?  It is just one simple counter example and that's it. It also mainly is just "do this, this and this"... it is getting back to the Pragmatic Programming way of programming. Just type this, type that, and it will work.

And usually, the docs are hard to read because one docs, if you are lucky, is linking to 6 other links, and if not lucky, linking to some 20 links.  The other day I was trying to read https://overreacted.io/a-complete-guide-to-useeffect and my god, it has how many links, probably more than 50 links.  A lot of the docs are like a soup of links.  It'd help it the docs is more self-contained.

For example, can you discuss the simplest way of just keeping the data in Redux store, and keep `loading` as a component state? The mechanism of dispatching "starting to load", and then "data is obtained", is like code shouting to the Redux store all the time, so the program can become a lot of shouting. It is like the modern Spaghetti code.  How does it compare to merely doing a fetch, and then the success handler does one shout, saying the data is obtained and put it into the Redux store? What are the pros and cons?

**Comment by markerikson** [comment]
@blueskybreeze: serious question - have you _tried_ reading through either of those "Essentials" or "Fundamentals" tutorials I linked? Because they explain all the concepts you're asking about, in details.

**Comment by blueskybreeze** [comment]
> @blueskybreeze: serious question - have you _tried_ reading through either of those "Essentials" or "Fundamentals" tutorials I linked? Because they explain all the concepts you're asking about, in detail.

I did.  But like this guide, first it said "unopinionated", and then later on, "These steps are not required, but are recommended in the Redux tutorials as a suggested pattern".  I don't see an explanation, and these two tutorials are just going to link to 20 other docs, and those docs are going to in turn link to other docs.

**Comment by markerikson** [comment]
Uh... I'm sorry. I'm really not sure what you're referring to here at this point.

The "Essentials" and "Fundamentals" tutorials do _not_ "link to 20 other docs". They walk you straight through, start to finish, explaining _everything_ you need to know to get started using Redux correctly.

Those tutorials are what we have, and they cover the two primary use cases: people who want to jump straight into using RTK right away without worrying about how it works inside ("Essentials"), and people who want to know "how it works" first and then move on to using RTK as the right approach ("Fundamentals").  We've got a lot of other things that we're trying to work on, and we do not plan to write any additional tutorials at this point.

_Please_ take the time to read through those tutorials, _all the way through_.

**Comment by blueskybreeze** [comment]
added afterwards: Also, Redux Toolkit can also have a intermediate doc that is in between this simple counter tutorial and the other one of the most often used cases: fetching data and display it on screen. Having one small counter tutorial is not enough. It does not even talk about code reuse of having 3 counters on the same page without duplicating a lot of code.

So do those docs talk about why having `loading` not as a component state but in the one and only store?

I know how Redux works. It merely is to shout out with an action name with some data, so that the reduce will create a new app state for the whole app to use, and it has this wiring directly feeding into the needed component instead of all the way from top to bottom to have everything re-rendered. It tried to re-render the minimum number of components.

**Comment by markerikson** [comment]
> So do those docs talk about why having loading not as a component state but in the one and only Redux store?

YES, they do:

- https://redux.js.org/tutorials/fundamentals/part-6-async-logic
- https://redux.js.org/tutorials/essentials/part-5-async-logic

I'm sorry, but I'm getting tired of repeating myself.  

That "quick" start tutorial is simply meant to be the fastest possible "copy some code and get something working" example. It is _not_ meant to teach you Redux itself, or RTK as a whole.  The "Essentials" and "Fundamentals" tutorials" do that.

Please. Read those.
