### ISSUE TITLE
[1.5.0] Call stack exceeded when using selectors created from createDraftSafeSelector or entityAdapter.getSelectors

### ISSUE THREAD

**Issue by garrettjoecox** [reduxjs/redux-toolkit#934]
We are running into an extremely weird issue with the new 1.5.0 release where in a production build, any selector created from `createDraftSafeSelector` or `entityAdapter.getSelectors()` will throw a call stack exceeded when used within our application. In a dev build everything works perfectly fine, which has made this a huge pain to debug. 

We were able to resolve this by downgrading to 1.4.0. I have used redux toolkit for multiple projects in the past and am not doing anything out of the ordinary in this one, (no recursive or non-serializable values in state) 

Any ideas if this is our problem or a bug within `createDraftSafeSelector`?

**Comment by markerikson** [comment]
Can you put together a CodeSandbox or a repo that reproduces the issue?

**Comment by garrettjoecox** [comment]
I tried to reproduce on web and was unable to, sadly my issue is happening in a react-native production build which is kind of a pain to get set up locally so I don't expect to get much support, but if you do happen to be familiar with react-native this is a code snippet for reproducing:
```js
import {
  configureStore,
  createDraftSafeSelector,
  createEntityAdapter,
  createSelector,
  createSlice,
  nanoid,
} from '@reduxjs/toolkit';
import * as React from 'react';
import { Text, View } from 'react-native';
import { Provider, useDispatch, useSelector } from 'react-redux';

const entityAdapter = createEntityAdapter();

const { selectEntities: selectAllEntities } = entityAdapter.getSelectors(state => state.entity);

const workingSelectEntities = createSelector(
  state => state.entity,
  entityState => entityState,
);
const brokenSelectEntities = createDraftSafeSelector(
  state => state.entity,
  entityState => entityState,
);

const entitySlice = createSlice({
  name: 'entity',
  initialState: entityAdapter.getInitialState(),
  reducers: {
    hydrate(state) {
      entityAdapter.addMany(state, [
        { id: nanoid(), name: '1' },
        { id: nanoid(), name: '2' },
      ]);
    },
  },
});

const { hydrate } = entitySlice.actions;

const store = configureStore({
  reducer: {
    entity: entitySlice.reducer,
  },
});

export const App = () => (
  <Provider store={store}>
    <AppContainer />
  </Provider>
);

function AppContainer() {
  const dispatch = useDispatch();
  const result = useSelector(state => {
    try {
      // This works fine
      // return state.entity;

      // This works fine
      // return workingSelectEntities(state);

      // This will throw
      // return brokenSelectEntities(state);

      // This will throw
      return selectAllEntities(state);
    } catch (error) {
      return {
        message: error.message,
        stack: error.stack,
      };
    }
  });

  React.useEffect(() => {
    dispatch(hydrate());
  }, [dispatch]);

  return (
    <View>
      <Text>test</Text>
      <Text>{JSON.stringify(result, null, 4)}</Text>
    </View>
  );
}
```

**Comment by markerikson** [comment]
Hmm. Yeah, really not sure what's going on there. Can you try to paste a stack trace even if it's minified, or identify where the loop is happening?

**Comment by garrettjoecox** [comment]
Not super useful sadly /:
```
RangeError: Maximum call stack size exceeded     
at r (address at index.android.bundle:1:484756)     
at r (address at index.android.bundle:1:484756)     
at r (address at index.android.bundle:1:484756)     
at r (address at index.android.bundle:1:484756)     
at r (address at index.android.bundle:1:484756)     
at r (address at index.android.bundle:1:484756)     
at r (address at index.android.bundle:1:484756)
....
```

**Comment by garrettjoecox** [comment]
The fact that it's only happening in production basically kills all of the tools I have to actually debug it ☹️

**Comment by markerikson** [comment]
Ouch. Yeah, that's basically useless :(

My only immediate suggestion here would to be start hand-editing some of the files in `node_modules/@reduxjs/toolkit/`, and add logging in the production files or something to get a sense of what's going on. I realize that's completely icky and painful, but I don't have any better ideas here.

**Comment by phryneas** [comment]
Given that the implementation of `createDraftSelector` is really short, maybe we can pinpoint it further?

```ts
export const createDraftSafeSelector: typeof createSelector = (
  ...args: unknown[]
) => {
  const selector = (createSelector as any)(...args)
  const wrappedSelector = (value: unknown, ...rest: unknown[]) =>
    selector(isDraft(value) ? current(value) : value, ...rest)
  return wrappedSelector as any
}
```

Can you test if it already throws when you just call `isDraft(state)` or `current(state)`?

**Comment by garrettjoecox** [comment]
> Can you test if it already throws when you just call `isDraft(state)` or `current(state)`?

`isDraft(state)` returns `false` and `current(state)` throws the following:

```
Error: [Immer] minified error nr: 22 '[object Object]'. Find the full error at: https://bit.ly/3cXEKWf     
at t (address at index.android.bundle:1:476697)     
at U (address at index.android.bundle:1:480121)     
at anonymous (address at index.android.bundle:1:493856)     
at c (address at index.android.bundle:1:524791)     
at anonymous (address at index.android.bundle:1:525461)     
at s (address at index.android.bundle:1:493633)     
at wr (address at index.android.bundle:1:85036)     
at rl (address at index.android.bundle:1:89943)
...
```

**Comment by garrettjoecox** [comment]
Which I suppose the error makes sense because isDraft returned false

**Comment by garrettjoecox** [comment]
When I copy the implementation of `createDraftSafeSelector` into my code, and use it instead of what is exported from RTK, I do not get the call stack exceeded errror.

**Comment by phryneas** [comment]
Oh wait... is this your code minification fucking up? Can you just disable minification in your code?

**Comment by phryneas** [comment]
I remember that we had the case where that minified RTK build has a shadowed variable somewhere, which is 100% correct JavaScript, but some external minifier fucks up with that.

**Comment by garrettjoecox** [comment]
Disabling minification seems to have resolved my issue, thank you for the help!

**Comment by phryneas** [comment]
Just for completeness:

This is the production build of RTK 1.5 = `yt` is `createDraftSafeSelector`.
```js
yt = function () {
  var t = pt.apply(void 0, arguments),
    n = function (n) {
      for (
        var r = arguments.length, o = new Array(r > 1 ? r - 1 : 0), i = 1;
        i < r;
        i++
      )
        o[i - 1] = arguments[i];
      return t.apply(void 0, [e(n) ? k(n) : n].concat(o));
    };
  return n;
};
```

The problem is that there are two variables `n` here - the `const n` that is also returned and also the argument `n` - the argument shadowing the outer const.
Seems some parsers (can you check what you are using for minfication? I'm guessing terser?) will fuck this up, and somehow make `n` call itself.

**Comment by garrettjoecox** [comment]
> can you check what you are using for minfication? I'm guessing terser?

Honestly I'm not sure, just using the vanilla React-native setup which uses babel & metro. Metro seems to have some sort of support for terser & uglify-es, not sure what is used in the defaults.

**Comment by phryneas** [comment]
Hmm. At least the next person with that problem will have a starting point here :)

**Comment by msvargas** [comment]
I have the same issue with RN, any solution please?

Sentry Log:

![image](https://user-images.githubusercontent.com/8255332/122443233-fcce7480-cf64-11eb-9a9f-3956605842b8.png)
