### ISSUE TITLE
Testing examples in documentation

### ISSUE THREAD

**Issue by sperrys** [reduxjs/redux-toolkit#936]
Definitely a nicety, and might be out of the project's scope, but an opinionated example of testing toolkit capabilities would be valuable imo.

**Comment by msutkowski** [comment]
@sperrys Can you provide a little more information about what specifically you'd like to know how to test? Would these tests be for a specific framework? Are there any major topics that you think would have value? Unit tests, integration tests, etc? Would you be interested in this in the form of documentation, runnable examples, or some other format??

**Comment by markerikson** [comment]
There's nothing unique about testing any of RTK's behavior that's any different than what we've already got in the Redux core docs "Testing" page:

https://redux.js.org/recipes/writing-tests
