### ISSUE TITLE
Check for undefined middleware on startup

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#937]
It's possible for a user to return `undefined` from the `middleware` creation callback in `configureStore`, in which case there are no middleware at all. We should consider this a user error and throw when that happens.  (ref: https://stackoverflow.com/q/66781880/62937 )

**Comment by Shrugsy** [comment]
I'm happy to take this one if nobody has started yet

**Comment by phryneas** [comment]
@Shrugsy go for it :)
