### ISSUE TITLE
Component not re-rendering on state update

### ISSUE THREAD

**Issue by sickdyd** [reduxjs/redux-toolkit#942]
Codesandbox: https://codesandbox.io/s/condescending-wiles-funk0?file=/src/App.js

**Problem**: When I update the state of my store the components are not re-rendered. In the above example you can see from the console that the data is correctly fetched, but the component is not re-rendered and keep rendering just `Loading....`

**Expected behavior**: When I update the state, the components are re-rendered.

I found a workaround by using useState in the component and subscribing to store changes like:

```
store.subscribe(() => setComponentState(store.getData())
```

This basically forces a re-render each time the data is updated, but it doesn't sound like the appropriate way to make it work.

How can I make this work?
Thanks!

**Comment by markerikson** [comment]
You should _not_ be using the `useStore` hook. You should be using the `useSelector` hook, which subscribes to store updates:

- https://redux.js.org/tutorials/fundamentals/part-5-ui-react#reading-state-from-the-store-with-useselector
- https://redux.js.org/tutorials/essentials/part-2-app-structure#reading-data-with-useselector
- https://react-redux.js.org/api/hooks#useselector

**Comment by sickdyd** [comment]
@markerikson Great! Thank you for your reply. I just went through the docs by myself, but I not carefully enough I see. Will fix as suggested!

**Comment by tkrafael** [comment]
I had a similar problem with typescript:
```
// #redux.ts
const slice = createSlice({
    name: 'addresses',
    initialState: [] as Address[],
//... some irrelevant code here,
  selectors: { all: (state)=> state}
}

// this array will be changed to make method be usable in tsx
export const sortedAddresses = createSelector([slice.selectors.all], (addresses) => {
    const n = [...addresses]
    n.sort((a, b) => (a.main && b.main) ? 0 : (a.main ? -1 : 1))
    return n
})

```
const { removeAddresses, sortedAddresses, addressSelectors } = useAddressRedux()
    const selector = useSelector(addressSelectors.all); // << this code won't compile

    const addresses = sortedAddresses(selector)
```
// #view.tsx
```

I've discovered (idk exactly why yet) that I need to set selector calling "unwrap" when `createSelector` is called:


```
export const sortedAddresses = createSelector([slice.selectors.all.unwrapped], (addresses) => {
    const n = [...addresses]
    n.sort((a, b) => (a.main && b.main) ? 0 : (a.main ? -1 : 1))
    return n
})

```
Can someone more experienced explain why it is needed? Didn't find in redux docs

**Comment by EskiMojo14** [comment]
@tkrafael other than being nothing to do with the issue at hand:

As [the docs](https://redux-toolkit.js.org/api/createSlice#selectors-1) say, it entirely depends on your state shape. 

If your slice is located at its name, i.e. `state.addresses`, you can use the `slice.selectors` property. 

On the other hand, if your slice is the entire state, you can call `slice.getSelectors()` to get selectors that accept the same parameters as the original selectors (which are attached at `.unwrapped`, as you've discovered). If your code is working with the unwrapped selectors, this is probably what you want:

```ts
export const sortedAddresses = createSelector([slice.getSelectors().all], (addresses) => {
    const n = [...addresses]
    n.sort((a, b) => (a.main && b.main) ? 0 : (a.main ? -1 : 1))
    return n
})
```

If the slice is somewhere else entirely, you need to provide an input selector to select the slice state, i.e. `getSelectors(state => state.myAddresses)`
