### ISSUE TITLE
./node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js Attempted import error: 'freeze' is not exported from 'immer'.

### ISSUE THREAD

**Issue by orszaczky** [reduxjs/redux-toolkit#945]
After installing a random package and probably some packages got updated, i'm gettin this error:

./node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js
Attempted import error: 'freeze' is not exported from 'immer'.

"@reduxjs/toolkit", "version": "1.5.0",
"immer", "version": "7.0.15"

**Comment by phryneas** [comment]
Please make sure to update to RTK version 1.5.1 and immer v8 and see if that resolves your problems.

**Comment by markerikson** [comment]
Yeah, RTK 1.5 requires Immer 8, so something's wrong with your `node_modules` installation.  If you've specifically listed Immer and are requiring a lower version, that's probably why.
