### ISSUE TITLE
provide a simpler action creator that ignores payload

### ISSUE THREAD

**Issue by danielo515** [reduxjs/redux-toolkit#947]
By default, `createAction` will define an action creator that will pass whatever it gets as arguments as payload. This can have a bad impact if you define a simple action creator that just dispatch a string action but you pass it as an event handler. It will pass the react/dom event as payload, impacting redux and redux-devtools performance.

It will be awesome if you can provide an alternative implementation like `createSimpleAction` that just ignores it's arguments and just dispatches the type action.

Regards

**Comment by markerikson** [comment]
This is kind of the tradeoff for being an abstraction layer.

Because we use `createAction` everywhere, and particularly in `createSlice` and `createAsyncThunk`, we can't have separate variations of that.

Note that if you're using `useDispatch`, this will rarely be an issue anyway, because you're not using the auto-bound `props.someActionCreator` and won't be passing it directly to an event handler. Instead, you're probably doing `onClick={() => dispatch(someActionCreator())}`.

So, agreed that this is an implementation detail that may be annoying in some situations, but I don't think there's anything we can do about this.

**Comment by phryneas** [comment]
Adding to that, if you use `createAction`, you can just use something like
```js
const stubPrepare =  () => ({ payload: undefined });

const myAction = createAction("foo", stubPrepare)

// or:
const mySlice = createSlice({
  // ..
  reducers: {
    foo: {
      reducer(){},
      prepare: stubPrepare
    }
  }
})
```

**Comment by danielo515** [comment]
The way I'm using them is binding with bind action creators. I don't like coupling my containers with redux specific stuff so I usually encapsulate them within hooks. Using bind action creators is super convenient there because it requires very little code:

```js
export function useNavigateDays() {
  const dispatch = useDispatch();

  const daysAgo = useSelector(state => state.stats.daysAgo);

  return {
    daysAgo,
    ...bindActionCreators({ nextDay, previousDay }, dispatch),
  };
}
```

Sure there are many ways to bind them that will prevent this, but none of them is that convenient 😄
I just passed a dummy prepare function, but that will get rid of the meta properties the toolkit adds.
Maybe creating a bindPayloadLessActionCreators that doesn't pass down any arguments.
What do you have against providing a different createAction function? I mean, a totally new one with a different name, like createPayloadLessAction or something like that. There is a type for it  right (IIRC)?

**Comment by phryneas** [comment]
The point is: `createAction` is only a helper. 
We don't expect that to be used except in edge cases.

If you are using RTK as we are intending it, you usually won't use it at all. 
It's just a primitive that our other apis (createSlice, createAsyncThunk) are built upon and we are exposing it as it can be useful in edge cases.

So, from that point, your question would extend to "have `createSlice`-created actions work without payload", as that is the API we actually expect to be used. And that would end up with two `createSlice` implementations - one for action creators that always accept a payload and one for action creators that never accept a payload. But that would be highly impractical. Usually, you would mix actions with and without payload within a slice. And at that point the whole thing breaks apart.

So, to sum that up:
We don't expect anyone to use `createAction` a lot. In fact, we don't really want people to do that. So we are not going to add a new API that is an edge case of something we already consider an edge case in the first place.
Especially as there already is a way to use `createAction` in the way you want, I have given an example of that above.

**Comment by danielo515** [comment]
What you suggested is what I'm already using.
I didn't know that this toolkit was so intentionally restricted, ok then.

Is create reducer also considered an edge case usage too?

**Comment by markerikson** [comment]
To a certain extent, yes. `createSlice` is our recommended standard approach for writing Redux logic, and most people shouldn't need to call `createReducer` directly.

As I said, this is part of the tradeoff for being an opinionated abstraction layer. It simplifies the typical use cases, but has some limitations in other rarer use cases.
