### ISSUE TITLE
Add `setOne/setMany` CRUD APIs to createEntityAdapter

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#954]
We can currently add new items or merge into existing items, but there's no built-in way to _replace_ items.

NgRx actually added a `setOne` API shortly after we ported the adapter logic over;

https://github.com/ngrx/platform/issues/2369

We might as well port `setOne`, and add `setMany` also.

**Comment by HHK1** [comment]
Waouh I *just* stumbled upon that issue, I love it when the exact feature request you wished for is already opened in the issues. 

Can I implement this or is someone else working on it already ?

**Comment by markerikson** [comment]
@HHK1 No one's working on it yet - go for it!

Note that the entity adapter logic is split into two files, `unsorted_state_adapter.ts` and `sorted_state_adapter.ts`.  Most of the adapter CRUD functions have split implementations on either side, but a couple of them (the `remove*` functions) are only implemented in the `unsorted` file and then imported and reused in the `sorted` file.

I imagine that we would probably want to have `setOne` and `setMany` share a common implementation internally.  For example, I think one of the `add*` implementations really just has `addMany()`, and `addOne` is implemented as `addMany([entity], state)` (ie, turning the single item into a one-item array).  We probably want to do something similar here.

**Comment by HHK1** [comment]
>(ie, turning the single item into a one-item array)

Actually I went the other way around, just like addMany calls addOne in a for loop, do you see any issues with it ?

```
function setOneMutably(entity: T, state: R): void {
    const key = selectIdValue(entity, selectId)
    if (!(key in state.entities)) {
      state.ids.push(key)
    }
    state.entities[key] = entity
  }

  function setManyMutably(
    newEntities: T[] | Record<EntityId, T>,
    state: R
  ): void {
    newEntities = ensureEntitiesArray(newEntities)
    for (const entity of newEntities) {
      setOneMutably(entity, state)
    }
  }
```

I'm done with the unsorted, adding the same to the sorted adapter right now.

**Comment by mr-new-0509** [comment]
Hello, dear.
I can't find setOne in entityAdapter. Please let me know the reason. In the doc, it is clearly described setOne is existed.
But I can't find it and the error is occured.
Please help me.
Thanks.

**Comment by markerikson** [comment]
@mr-new-0509 what version of RTK are you using? It was only added in 1.6.0.

**Comment by mr-new-0509** [comment]
I am using 1.5.1.
Thanks a lot.
Could you please let me know how I can upgrade the RTK version?

**Comment by markerikson** [comment]
@mr-new-0509 Same as any other NPM package :)  Either change the version number in your `package.json` and reinstall with either `npm` or `yarn`, or use that same package manager's built-in "add" / "update"-type commands.

**Comment by mr-new-0509** [comment]
It WORKS!.
Thanks really very so much.
You are COOL!
