### ISSUE TITLE
[RTK Query Migration] Migrate RTKQ source and docs files to this repo

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#963]
Once we're happy with the final RTKQ alpha status, we need to port all of the source and docs files over here into this git repo.

Ideally, I want all the source files to end up in `src/query/` and the docs in `docs/query`.

I also want to preserve the Git history of all those files.

This may require running the RTKQ repo through a clone + `filter-branch`-style reprocessing, to create a new repo with the same names.  Alternately, we could make a clone, then move the files in that repo and detect renames.

Either way, after that we pull the RTKQ branch over here and merge in with an "allow-unrelated" to get the files to combine together.

**Comment by hardfist** [comment]
so rtkq will not be a standalone package？

**Comment by markerikson** [comment]
Nope, that's the whole point of the "extra entry points" thing I asked you to set up :)

We want RTKQ to be directly included in the `@reduxjs/toolkit` package on NPM - no other packages to install.

But, since it's a good chunk of extra logic, we want to ensure that you only pay for those bytes if you actually need them, _and_ we need to provide both "vanilla JS" and "React-specific" versions of `createApi`, so that people who want to use `createApi` with Angular or Vue or Svelte aren't fighting with having to add dependencies on React too.

**Comment by hardfist** [comment]
its a pity that you dont have a chance to fight monorepo beast

**Comment by markerikson** [comment]
Hah, nice way to put it :)

I've debated putting all the Redux projects (Redux, React-Redux, RTK) into a monorepo, mostly to enable having a single combined docs site.  But, that would be a ton of effort, and I don't see enough benefit right now.  (Besides, we've got _wayyyy_ too many other things to work on right now.)

**Comment by markerikson** [comment]
First steps resolved by #1006 and #1007 .
