### ISSUE TITLE
[RTK Query Migration] Fill out remaining not-yet-covered RTKQ docs content

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#964]
Depends on #963 .

Once the RTKQ source/docs content is in this repo, we need to update the RTK docs to include that info. My plan is:

- New `RTK Query` subcategory under "API Reference", with `createApi` and friends
- New "RTK Query" subcategory under "Usage Guide", containing the content previously in the RTKQ "Concepts" section

Could also argue it should be its own top-level section in some way (maybe just the "Concepts" material, but not the API reference?)

We'll need to emphasize that this is all exported by the new `"@reduxjs/toolkit/query"` and `"@reduxjs/toolkit/query/react"` entry points, not the main `"@reduxjs/toolkit"` entry point.

This should probably be done on a 1.6 integration branch so that we don't publish it too early.

**Comment by markerikson** [comment]
Primary work was done in #1015 .

Going to leave this open to cover fleshing out the rest of the missing content.

**Comment by markerikson** [comment]
Missing pieces from discussion:

- Could use an "RTK Overview" page in addition to the Tutorial and Usage Guide areas
- "Comparison" page
- Explanation of why we don't do normalization (put that on "Comparison", maybe?)
- I think some of the hooks aren't fully documented yet
- No TypeScript usage guide and insufficient types docs for the APIs

**Comment by Shrugsy** [comment]
Just so it doesn't get missed:

The 'bailing out of errors' section on 'Error Handling' is still TODO also: https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/usage/rtk-query/error-handling#bailing-out-of-errors

**Comment by markerikson** [comment]
Per a user:

> It might be worth adding at least a one-line explanation of "reducerPath" in the Getting Started introduction, because it wasn't immediately clear to me what it does and I questioned if it was really even necessary. This section is more helpful, although it could also maybe add just a little bit more detail: https://rtk-query-docs.netlify.app/api/createapi/#reducerpath

**Comment by Shrugsy** [comment]
Both the "bailing out of errors" section & "Need to cover how to use a custom base query" are intended to be covered by #1057

**Comment by Shrugsy** [comment]
> Show switching from existing thunk-based fetching logic to RTKQ

Intended to be covered by #1060

**Comment by Shrugsy** [comment]
> Could use an "RTK Overview" page in addition to the Tutorial and Usage Guide areas

This is intended to be covered by #1066 
@markerikson let me know if you had something different in mind as an 'overview'

**Comment by markerikson** [comment]
I don't see any information on how the cached data lifetime + subscriptions behavior works.  I wrote up a Reddit comment describing it:

https://www.reddit.com/r/reactjs/comments/nej4sv/redux_to_store_a_lot_of_data/gykyzms/

**Comment by Shrugsy** [comment]
Navigating to RTK Query `Usage` & `API Reference` pages is a little tedious due to the multiple levels of nesting.

For example, if looking for what the generated react hooks return (IMO likely to be one of the higher traffic sections), you need to:
- Click `API Reference`
- scroll all the way down to the bottom past the expanded sections
- Click `RTK Query` right at the bottom
- scroll all the way down to the bottom
- Click `Generated API Slices`
- scroll all the way down to the bottom
- click `React Hooks

[React Hooks link location in sidebar](https://user-images.githubusercontent.com/22929669/118775699-8ccbc080-b8ca-11eb-9cdc-2d516b0b84c5.png)

@markerikson what are your thoughts on shifting them out somewhere higher to reduce nesting?
e.g. something like 'Using RTK Query' and 'API Reference - RTK Query' at the top level:  
![image](https://user-images.githubusercontent.com/22929669/118776702-9bff3e00-b8cb-11eb-90e5-4036d1432cdf.png)

**Comment by Shrugsy** [comment]
> I don't see any information on how the cached data lifetime + subscriptions behavior works. I wrote up a Reddit comment describing it:

@markerikson we have this currently: https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/usage/rtk-query/cached-data#default-cache-handling-behaviour

But I think your explanation was very handy, so I've merged it together with the existing description under #1071

**Comment by markerikson** [comment]
Obligatory Twitter poll to get feedback on the docs organization:

https://twitter.com/acemarke/status/1395023250212655105

**Comment by akursat** [comment]
@markerikson Perhaps by ignoring the type definitions, the documentation can be made more readable.
You can group all type definitions under API reference and give a link from sections. 
I think showing all type definitions in similar sections will increase consistency.
For example, the Mutations section contains the mutation endpoint type definition, while the Queries section does not.
The Queries section contains the hook type definition, while the Mutations section does not.

**Comment by markerikson** [comment]
Yeah, if we do have typedefs in the "Usage" pages, those need to be moved to the relevant API ref pages (and the "Usage" pages should probably link over to the API refs as appropriate).

**Comment by Shrugsy** [comment]
Regarding typedefs in the usage pages, please see the proposed updated version from #1074 

the changes would still keep the 'Query hook return types' in the `Queries` usage page, and 'Mutation Hook Trigger Type' in the `Mutations` usage page, as they are the most relevant parts of the type signatures for each hook respectively.

Each of the two pages is proposed to also include a line linking to their respective API pages like:
> See useQuery for the hook signature and additional details.
>  See useMutation for the hook signature and additional details.

Please let me know your thoughts if you think this is still too much type information for the 'Usage' pages

https://deploy-preview-1074--redux-starter-kit-docs.netlify.app/usage/rtk-query/queries#query-hook-return-types
https://deploy-preview-1074--redux-starter-kit-docs.netlify.app/usage/rtk-query/mutations#mutation-hook-trigger-type

**Comment by markerikson** [comment]
Hmm. Just out of curiosity, could we limit it to the 5-ish most frequently used fields just to keep it short here?

Also, would it be easier to read the descriptions if they were bullet points after the code block, instead of inline comments?

**Comment by markerikson** [comment]
FWIW, the Twitter poll is leaning towards having a single top-level "RTK Query" section.  (Small sample size, etc, but FYI.)

**Comment by markerikson** [comment]
We need to actually describe how to use `queryFn` :)  Added that to the checklist.

**Comment by markerikson** [comment]
Also some examples of `transformResponse`, including at least a mention of using `createEntityAdapter` with that.

**Comment by Shrugsy** [comment]
> - Describe the queryFn option and usage
> - Using transformResponse

Both of the above are intended to be covered by #1081

**Comment by markerikson** [comment]
Final bits of cleanup work:

- [ ] Grammar/text editing pass
- [ ] 1.6 release notes
- [ ] Ought to list bundle size info in either "Overview" or "Comparison
- [ ] TS type visibility

**Comment by markerikson** [comment]
Gonna say this is good to go :)
