### ISSUE TITLE
Error in type definition for createSlice in generic context?

### ISSUE THREAD

**Issue by dhilgarth** [reduxjs/redux-toolkit#966]
Background: I have multiple slices that have a similar layout and base logic on which each slice individually expands.
I want to implement this repetitive layout and base logic in one place and then build my slices from that.
Basically, I am trying to create a wrapper around `createSlice` that has largely the same signature as `createSlice` but internally adds more reducers and properties to the state.
Part of that is that the state has a generic type and that doesn't seem to work correctly.
Minimum reproducible sample:

![image](https://user-images.githubusercontent.com/1180105/113148791-902fbd80-9232-11eb-90ed-e2f3d7c27c46.png)

**Comment by markerikson** [comment]
We specifically have a docs section that provides guidance on trying to wrap `createSlice` when using TS:

https://redux-toolkit.js.org/usage/usage-with-typescript#wrapping-createslice

Does that resolve your issue?

**Comment by dhilgarth** [comment]
It does but not in a way I would have liked. Basically, the comment above `success` is exactly my problem. I wanted to get this to work without explicitly specifying the state type.
But looks like someone already thought about it and deemed it not solvable.

**Comment by dhilgarth** [comment]
Need to re-open, sorry. This explicit definition of the type causes downstream problems.

Assume that my wrapped slice creator also creates thunks.

My first simple approach was this: https://codesandbox.io/s/restless-field-zzhfi?file=/src/index.ts:1674-1734
Basically: Call `createSlice` in my wrapped method and use the created actions in my thunks.
This doesn't work, because it complains that the actions are not callable:
> This expression is not callable.
> Not all constituents of type 'void | ActionCreatorWithPreparedPayload...' are callable.

I found out that the spread of `options.reducers` is the problem. However, if I remove spreading those reducers, I can no longer explicitly specify the type of the `state` parameter in the generic reducer: https://codesandbox.io/s/nifty-napier-c0ccg?file=/src/index.ts
It says:
```
 Type 'WritableDraft<MySliceState<T>>' is not assignable to type 'State'.
 'State' could be instantiated with an arbitrary type which could be unrelated to 'WritableDraft<MySliceState<T>>'
 ```

This is too deep into the typescript type system specifics for me to understand but it does seem as if some type definition at some place is not quite correct, doesn't it?

Thanks

**Comment by dhilgarth** [comment]
Solution for now: Some casting
https://codesandbox.io/s/priceless-newton-iw6cv?file=/src/index.ts

**Comment by phryneas** [comment]
The case is required and there is really no way around it.

This is just a thing with unresolved generics and applying conditional types to them - as you can see in [this TS playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwg9gOwCYEtgsQQwDYBVwQA8uAfFALxS5QQAewEyAzlE8AE4oIDmUA-FSgAuKgG4AUOIBmAVwQBjdIihS4cYiQAUwEbgCUUAN7ioKuYowJWcALYQAYgk2Z23EfGRpLOfJA0HjU1MXXkpgEygAX0lIoA).

Nothing we can do in our types.

**Comment by dhilgarth** [comment]
Thanks for the clarification
