### ISSUE TITLE
Test tree-shaking behavior

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#982]
Bundlephobia tries to report tree shaking behavior for individual exports, but we're getting some sketchy numers:

https://bundlephobia.com/result?p=@reduxjs/toolkit@1.6.0-alpha.0

Not sure if that means that tree shaking isn't working at all, or that the way it's being tested is screwy.

@phryneas reported he saw differing behavior for single-file vs multi-file RTKQ builds.

We should run some additional tests to get a sense of whether RTK actually shakes correctly (ie, using just `configureStore` / `createSlice` / `createEntityAdapter` in separate builds of a CRA / Next app and seeing what the size is as a result, with bundle inspection as well).

Should also probably try https://github.com/mweststrate/import-size again

**Comment by justinformentin** [comment]
Tree shaking seems to be working as expected from a preliminary test.

Here is the file I used.

```
import React from "react";
import ReactDOM from "react-dom";
import { Provider } from "react-redux";
import {
  configureStore,
  createSlice,
  createAction,
  nanoid,
} from "@reduxjs/toolkit";

const increment = createAction("counter/increment");

export const counterSlice = createSlice({
  name: "counter",
  initialState: { id: nanoid() },
  reducers: {},
});

const store = configureStore({
  reducer: {
    counter: counterSlice.reducer,
  },
});

function App() {
  return <div></div>;
}

ReactDOM.render(
  <React.StrictMode>
    <Provider store={store}>
      <App />
    </Provider>
  </React.StrictMode>,
  document.getElementById("root")
);

```

I then removed each import one at a time and these were my build results

With `configureStore`, `createSlice`, `createAction`, `nanoid`

```
  50.55 KB  build\static\js\2.6d07b76a.chunk.js
  769 B     build\static\js\runtime-main.3e2806af.js
  389 B     build\static\js\main.0ebb9d88.chunk.js
```

With `configureStore`, `createSlice`, `createAction`

```
  50.47 KB (-84 B)  build\static\js\2.c28d3bc9.chunk.js
  769 B             build\static\js\runtime-main.3e2806af.js
  382 B (-7 B)      build\static\js\main.ed4b126b.chunk.js
```

With `configureStore`, `createSlice`

```
  50.47 KB         build\static\js\2.4bf2e913.chunk.js
  769 B            build\static\js\runtime-main.3e2806af.js
  368 B (-14 B)    build\static\js\main.29263f43.chunk.js
```

With `configureStore`

```
  49.84 KB (-646 B)  build\static\js\2.9ff90555.chunk.js
  769 B              build\static\js\runtime-main.3e2806af.js
  309 B (-59 B)      build\static\js\main.c0d96ffb.chunk.js
```

**Comment by markerikson** [comment]
@justinformentin great, thanks! Just for kicks, could you throw in `createEntityAdapter` and `createAsyncThunk` too? More concerned with them shaking at all then exact sizes, but more info never hurts.

**Comment by justinformentin** [comment]
No problem! I believe I spoke too soon though. I forgot that Terser removes dead code. I spent some more time and built an unminified version. Reading through it, even if I don't include `createEntityAdapter`/`createAsyncThunk` in my app, the full functions exist in the output, but greyed out as a "declared but not used". Built using the default CRA webpack config, the output is of course minified, and those functions don't exist. Keeping mangling in mind, I disabled mangling as much as I could and I added some un-mangle-able code inside the functions in the redux node_modules so I could search for it just to be doubly sure. So maybe this is where the confusion is coming from.

**Comment by markerikson** [comment]
FWIW, running `import-size --report configureStore createSlice createAsyncThunk createEntityAdapter` produces these results:

```
┌──────────────────────────────────┬───────────┬────────────┬───────────┐
│             (index)              │ just this │ cumulative │ increment │
├──────────────────────────────────┼───────────┼────────────┼───────────┤
│ import * from '@reduxjs/toolkit' │   10759   │     0      │     0     │
│          configureStore          │   6307    │    6307    │     0     │
│           createSlice            │   5606    │    7003    │    696    │
│         createAsyncThunk         │   6490    │    8431    │   1428    │
│       createEntityAdapter        │   6315    │    9758    │   1327    │
└──────────────────────────────────┴───────────┴────────────┴───────────┘
```

I'll be honest and say I don't get how `configureStore` could be taking up that much space by itself - I don't think we reference Immer anywhere in there, do we?

Huh. Maybe it's because we call `enableES5` in `index.ts`?

**Comment by markerikson** [comment]
No, moving `enableES5` to `createReducer.ts` made no difference. Commenting it out entirely did shrink the size a bit, as expected.

I guess there is a fair bit of code involved with `configureStore`. All the Redux core stuff (`createStore`, `applyMiddleware`, `compose`), plus the DevTools config.

I'm gonna say that tree shaking is working sufficiently fine as far as we can tell and close this.
