### ISSUE TITLE
getter isn't being updated when property is changed.

### ISSUE THREAD

**Issue by RigottiG** [reduxjs/redux-toolkit#984]
I have a getter that returns a value inside a factory, but when redux-tookit changes my value, the getter isn’t updated. I tried it without redux-toolkit and it is working fine.

In my reducer setBalanceVisibility, when value isVisible is changed, the getter formattedValueSignal doesn’t get updated.

```javascript
/*Redux*/

const initialState = {
  current: userFactory(),
  isLoading: false,
  hasError: false,
}

const userSlice = createSlice({
  name: '@user',
  initialState,
  reducers: {
    setBalanceVisibility(state) { 
      state.current.balance.isVisible = !state.current.balance.isVisible
    },
  },
})


/*Factory*/
export function userFactory(object) {
  if (!object) {
    return null
  }

  const { name, email, accountBalance } = object

  return {
    name,
    email,
    balance: balanceFactory(accountBalance),
  }
}

export function balanceFactory(object) {
  if (!object) {
    return null
  }

  const { value, formattedValue, isVisible } = object

  return {
    value,
    formattedValue,
    isVisible,
    get formattedValueSignal() {
      if (this.isVisible) {
        return this.formattedValue.split(' ')[1]
      }

      return '-- --'
    },
  }
}
```

**Comment by emilioheinz** [comment]
@markerikson Could you please take a look at this? It is quite important for us!

**Comment by RigottiG** [comment]
help pls

**Comment by phryneas** [comment]
We explicitly advise against using non-serializable state (which includes functions, and getters are functions) in redux and this is a prime example.

On modification, this creates a clone of your original values - and that original function probably carries some kind of scope reference over.

Please do not do this. Logic like this belongs into a selector.

**Comment by phryneas** [comment]
And one more spam comment (which includes unsolicited mentioning of maintainers except for specificly answering them) and I'm gonna close & lock this one. 
It will not make it more seen, it just makes it more annoying for all of our mailboxes.

**Comment by emilioheinz** [comment]
Sorry about the mentioning. 

"Please do not do this. Logic like this belongs into a selector."

Is there any example that we can follow or take a look?

**Comment by phryneas** [comment]
```js
function selectSomethingFormattedFromState(state) {
  if (state.foo.bar.baz.isVisible ) {
    return something
  }
}
```

**Comment by emilioheinz** [comment]
Nice, thank you for the attention, and sorry again about the ongoing mentioning. I think you can close the issue!
