### ISSUE TITLE
Change counterReducer to counterSlice in quick-start.md

### ISSUE THREAD

**Issue by JessTaDa** [reduxjs/redux-toolkit#985]
An example in the quick-start docs in the tutorials section references counterReducer instead of counterSlice. Is this a mistake?

![Screen Shot 2021-04-07 at 1 35 32 pm](https://user-images.githubusercontent.com/17763644/113808257-fecbc880-97a8-11eb-9d99-6ad97a0f6716.png)

I've made updates here as per the contribution guidelines https://github.com/JessTaDa/redux-toolkit

**Comment by markerikson** [comment]
No, that's correct as-is. 

The typical slice file pattern is:

```js
const counterSlice = createSlice({
  name: 'counter',
  initialState: {value: 0},
  reducers: {
    increment(state, action) {
      state.value++
    }
  }
})

export const {increment} = counterSlice.actions;

// Key line here:
export default counterSlice.reducer;
```

In other words, we don't ever export the `counterSlice` object - just the action creators and the slice reducer inside of it.  And, the default export _is_ the slice reducer itself.  

Within the importing file, we could give that file any name we want, such as `import fred from '../features/counter/counterSlice'`.  But, `counterReducer` would be the idiomatic name for that variable.
