### ISSUE TITLE
Feature request: built-in action type guards

### ISSUE THREAD

**Issue by felskov** [reduxjs/redux-toolkit#987]
createSlice is awesome, but if I want to intercept actions in a middleware and assert that they're of a given type, there is no built-in way of doing so (at least we haven't been able to find any?).

In our specific case, we have a tracking middleware that submits requests when certain actions are dispatched. Currently we've done this by implementing type guards manually, one of them looks something like this:

```ts
import { Middleware } from "redux";

import { AddToBasketAction } from "../slices/basket";

function isAddToBasketAction(action: AnyAction): action is AddToBasketAction {
  return action.type === "basket/addToBasket"
}

export const trackingMiddleware: Middleware = () => (next) => (action) => {
  next(action);

  if (isAddToBasketAction(action)) {
    // type guard means action signature is inferred
    trackAddToBasket(action);
  }
};
```

While this works, it will silently break if the slice or action is renamed at some point in the future - there will be no warnings from TypeScript, so unless someone figures out that the tracking middleware will also need to be updated accordingly, we risk deploying a build to production that doesn't actually track the expected events.

Furthermore we need to manually extract the action signature into a reusable type (e.g. `type AddToBasketAction = PayloadAction<{ ... }>`), which feels slightly awkward when using createSlice.

It would be great to have a built-in way to run such assertions, which could provide but type guarding and remove the need to hardcode reducer and action names as in the example above.

Perhaps it could look something like this:

```ts
import { isAction } from "@reduxjs/toolkit";
import { Middleware } from "redux";

import { addToBasket } from "../slices/basket";

const middleware: Middleware = () => (next) => (action) => {
  next(action);

  if (isAction(addToBasket, action)) {
    // type of action can be inferred based on signature from addToBasket action creator
  }
};
```

**Comment by phryneas** [comment]
I'm gonna point you at
https://redux-toolkit.js.org/api/createAction#actioncreatormatch (valid for ALL action creators exposed by RTK)
and
https://redux-toolkit.js.org/api/matching-utilities
and close this :)
