### ISSUE TITLE
Typescript: Payload Type based on a type properties becomes a union

### ISSUE THREAD

**Issue by bmakan** [reduxjs/redux-toolkit#988]
I am fairly new to TypeScript so maybe I did something wrong. I'm trying to create an action/reducer which will allow me to set properties on an object of type `Type`. The properties and values should be based on the `Type`.
E.g., property name must be a string, id must be and int. 

Inspired by: [docs](https://www.typescriptlang.org/docs/handbook/2/generics.html#using-type-parameters-in-generic-constraints)
Working example: [playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgzhATlAvFA3gKClAlgEwC4oA7AVwFsAjJAGm1IEMKJi5hFcSBzegXwDcmTADMyJAMbBcAexJQEwAAqIZkRKAA8AaQggoEAB7AIJfHCgBrPTJGwEiAHwAKdFDCMQAGxmMiGKz1aKAA3Ri8yaD4oPmI3D29ffzdrEGJdEGCwiNZ7JABtDIBdGJiASgwGAHoqqAARGQUZFlCZGXw2zD5hCTl2KDIHYngkVEqcAmIAFgBWAA56HBJmXIByACkZAAt5BohV-iFMGqgANXDIqFBIC0ZEaF7Ee6kvfXwkXBCIfCgRVQorltoCNkNdoO9IGYuNwoHJAdBUphFCo1EhQK53J4fH44oE0lBVgQDqELrk5qU+GUhMjVOp0fEsUlcaliKtlixidlIqzNjsSCBVhSqcITgA5FZQCiDYBQGhQRgKDjQpEQZS0tEgDEJbHJPGs9n7LKk4gicIIIVCIA)

(In case playground link stops working)
```ts
type User = {
  id: number,
  name: string,
};

function setProperty<Key extends keyof User>({ payload: { key, value } }: { payload: { key: Key, value: User[Key] } }) {
  // Do some voodoo
}

const user: User = {
  id: 458,
  name: 'John Doe',
};

// Value types are correctly derived from the User type depending on the key
setProperty({ payload: { key: 'id', value: 8 } });
setProperty({ payload: { key: 'name', value: 'Johnny' } });

// Name must be a string
setProperty({ payload: { key: 'name', value: false } });

```

Reduxjs Toolkit attempt:
```ts
type User = {
    id: number,
    name: string,
};
const slice = createSlice({
    reducers: {
        setUser: <Key extends keyof User>( // This may be overriding something I am unaware of
            state: SliceState,
            { payload }: PayloadAction<{ key: Key, value: User[Key] }>,
        ) => {}
    },
});
```

```ts
slice.actions.setUser({ key: 'name', value: 8 }); // False Positive
slice.actions.setUser({ key: 'name', value: 'lol' }); // True Positive
slice.actions.setUser({ key: 'name', value: false }); // True Negative
```

This is what vscode shows me when I mouse hover over `slice.actions.setUser`:
```ts
(property) setUser: ActionCreatorWithOptionalPayload
(payload?: {
    key: keyof User;
    value: string | number; // Should be User[Key]
}) => {
    payload: {
        key: keyof User;
        value: string | number; // Should be User[Key]
    };
    type: string;
}
```

Something is causing the value to become `string | number` rather than based on the property type (`User[Key]`).

**Comment by phryneas** [comment]
As we map over your function to generate a new function out of it, TypeScript does not provide us any way to detect that it is a generic function, so we have no way of preserving that.

You could use an alternative approach like this:
```ts
type ValidCombinations<T> = {
  [K in keyof T]: {key: K, value: T[K]}
}[keyof T]
```

[Full playground](https://www.typescriptlang.org/play?ssl=9&ssc=11&pln=6&pc=1#code/C4TwDgpgBAqgzhATlAvFA3gKClAlgEwC4oA7AVwFsAjJAGm1IEMKJi5hFcSBzegXwDcmYaEhQAaowA2BAMIB7al0bBc8knAA8AFQB8qDAwDaAaTwkoAawgh5AMyjaAusXTWQxE7SgA3aWVZHUyc+TD4jd3tHJ2E7MhIAY1V1KARgAAVEeUhEUAAKdCgwRhApeUYiDCsbbz8pAKg+RtcikrKK4kkZfAUlEhU1DU14JH0+AEpDHAB6aagAEXlUxWgfeXl8dbDhBPV2KDIERGIR5DQsHAJiABYAVgAOehx+lmIAcgApeQALC0WIN78ISYWYSfzQUQQOBQRiIaC7RBwpJSEBQfBIXA+CD4KB2LIUKDAb7QU6E8DQdGQEj4LjcKApInQdyYNKZbJIfKFYqlcqVQrud4EQG+cHEe6NRrjISsrI5TmtHkdKoCqBvF4A2qi1VfX4kEBvCUTYGggByzGgFEOwCgNBhqQ4tJZEAyso5IAKCvafOqHlV6uFdQCxDs0gQhqlmCAA)

**Comment by bmakan** [comment]
Indeed that achieves my goal. Thanks!

Gonna close as it's not an issue but a misuse on my side.
