### ISSUE TITLE
Auto create reducers based on key list of store

### ISSUE THREAD

**Issue by tema1411** [reduxjs/redux-toolkit#996]
**Problem:** We must describe every simple setter in reducer

```js
const INITIAL_STATE = {
  isInitiatingForm: false,
  isWaitingApiResponse: false,
};

const store = createSlice({
  name: STORE_NAME,
  initialState: INITIAL_STATE,
  reducers: {
    setIsInitiatingForm: (state, { payload }) => {
      state.isInitiatingForm = payload;
    },
    setIsWaitingApiResponse: (state, { payload }) => {
      state.isWaitingApiResponse = payload;
    },
  },
});
```

**proposal** Add additional key of configuration to `createSlice` for auto create setters 
```js
const INITIAL_STATE = {
  isInitiatingForm: false,
  isWaitingApiResponse: false,
};

const store = createSlice({
  name: STORE_NAME,
  initialState: INITIAL_STATE,
  keysForSetter: [isInitiatingForm, isWaitingApiResponse]
});

console.log(store.actions) 
/*In console
{
  setIsInitiatingForm: ƒ ()
  setIsWaitingApiResponse: ƒ ()
}
*/
```

Reducer created automatically based on `keysForSetter` array and use pattern` set + name of store key`. 

**What do you think?**

**Comment by phryneas** [comment]
Since we [recommend against writing actions in a setter-style](https://redux.js.org/style-guide/style-guide/#model-actions-as-events-not-setters) I don't see us adding something like this, I'm sorry.

**Comment by tema1411** [comment]
> Since we [recommend against writing actions in a setter-style](https://redux.js.org/style-guide/style-guide/#model-actions-as-events-not-setters) I don't see us adding something like this, I'm sorry.

Thanks for your answer))

**Comment by markerikson** [comment]
If you want to write a "truly generic reducer", you can do something like:

```js
const itemSlice = createSlice({
  name: "someItem",
  initialState: {a: 1, b: 2},
  reducers: {
    oneValueUpdated(state, action) {
      const {key, value} = action.payload;
      state[key] = value;
    },
    manyValuesUpdated(state, action) {
      Object.assign(state, action.payload);
    }
  }
})
```

However, **I would recommend _against_ doing this in almost all cases**, because it goes against the principle that [reducers should own the state shape](https://redux.js.org/style-guide/style-guide#reducers-should-own-the-state-shape).
