### ISSUE TITLE
Question re Testing Redux Toolkit Slice Actions

### ISSUE THREAD

**Issue by stuartflanagan** [reduxjs/redux-toolkit#998]
I am trying to test redux toolkit with `redux-mock-store`
At present I am checking the `requestId` against a state stored `currentRequestId`
This results in the fulfilled action never completing or assigning a payload to check in the test.

Just looking on some advice on this situation. The check for if a request is inflight and not to make a new one until it is finished is great for preventing race conditions, but it seems without being able to mock the state's `currentRequestId` this cannot be done and the action will never get past this condition in the test.

**Comment by markerikson** [comment]
Sorry for the belated response. Can you show an example of what you're trying to do?

**Comment by stuartflanagan** [comment]
Sorry I will get one ready soon.

**Comment by markerikson** [comment]
Closing due to lack of response.
