### ISSUE TITLE
Parametrised selectors memoization

### ISSUE THREAD

**Issue by irmantaszenkus** [reduxjs/redux-toolkit#999]
Hello, according to docs and source code, all selectors are created with `createSelector` from `reselect`. `reselect` does not provide a way to handle parametrised selectors and recommends taking approach like such
```ts
const createNameSelector = () => createSelector(selectById, selectName)
``` 
And then in `react-redux` version we would create selector instance for each component that needs it
```js
connect(() => {
  const selectName = createNameSelector();
  return (state, { id }) => ({
    name: selectName(state, id)
  })
})
```

When using `redux-toolkit` and creating globalized selectors like this
```js
const globalizedSelectors = personsAdapter.getSelectors(state => state.persons);
```
`globalizedSelectors` becomes this single instance and if I were to use it like this
```js
connect(
  (state, {id}) => ({
    name: globalizedSelectors.selectById(state, id)
  })
)
```
Selector memoization would become pointless, as each component will pass different `id` and overwrite cached version.

I could however do something like this
```js
const createNameSelector = () => createSelector(
  globalizedSelectors.getSelectors(state => state.persons).selectById,
  selectName
);
```
And have instances created each time. But then in my opinion it would be efficient to access non-memoized selectors from `redux-toolkit` and use them like this
```js
const createNameSelector = () => createSelector(
  globalizedSelectors.selectors.selectById,
  selectName
)
```

**Comment by phryneas** [comment]
Hm, that is actually a real problem. `selectById` is defined as
```js
createDraftSafeSelector(
        selectGlobalizedEntities,
        selectId,
        selectById
      )
```
and while `selectId` and `selectById` have irrelevant execution times, actually `selectGlobalizedEntities` should not re-run on every argument change.

Coincidentally, that should already get solved by accident in https://github.com/reduxjs/redux-toolkit/pull/990 - can you take a look and verify that?

**Comment by markerikson** [comment]
It's important to realize that for `selectById`, memoization doesn't matter at all - it's a straight lookup, not actual _derived_ data.  Ditto for `selectGlobalizedEntities`.

**Comment by phryneas** [comment]
@markerikson not 100% agreeing. Assuming you have 100 components and many entities, I would not want `selectGlobalizedEntities` to re-run, because it is doing a map over the whole array. I would want *that* to be memoized.
`selectById` would be irrelevant though.

**Comment by markerikson** [comment]
`selectGlobalizedEntities` _should_ be memoizing correctly, though:

```js
    const selectGlobalizedEntities = createDraftSafeSelector(
      selectState,
      selectEntities
    )
```

It's only going to re-run the output selector once the entities state changes. The rest of the time it's just a cache hit.

**Comment by phryneas** [comment]
Ah right, it's prefaced with `selectState`, I somehow forgot about that part.

**Comment by irmantaszenkus** [comment]
It seems that none of 5 memoized selector actually benefit from `reselect`. `selectEntities`, `selectAll`, `selectIds` do work correctly but they are straight accessors and have no derived state computation. `selectById` is also just an accessor too and does not need memoization, but instead it gets memoized and then cache is cleaned up each time new `id` is passed.
If you support my arguments, I would like to contribute and remove memoization

**Comment by phryneas** [comment]
`selectAll` is not a straight accessor and does benefit from memoization - quite a lot over only calling it twice.

In general: it doesn't hurt having it in there. 
No application should ever hit a performance level where having reselect here or not would make any perceivable difference.

**Comment by irmantaszenkus** [comment]
But it does hurt very very slightly for selectors like `selectById`, by executing code, that memoizes return value. And at the same time it does not provide any benefit.
Would it make sense to return memoized selectors for all of them except parametrised `selectById`?

**Comment by markerikson** [comment]
We're talking a couple comparisons and a `map()` call inside of `createSelector`. This is not meaningful perf-wise, at all.

Realistically, `selectAll` is the only one that does any derivation, so it's the only one that _needs_ to be written using `createSelector`. But, I'm not seeing enough reason to really make any changes here atm.
